### ISSUE TITLE
App Transport Security policy requires the use of a secure connection on iOS9

### ISSUE THREAD

**Issue by bikegriffith** [TheWidlarzGroup/react-native-video#100]
See related issue from another project https://github.com/meteor/meteor/issues/4560

The workaround is to add a new set of keys to `Info.plist`:

```
NSAppTransportSecurity: Dictionary
 - NSAllowsArbitraryLoads: Boolean = YES
```

**Comment by edward** [comment]
@bikegriffith What do you think about adding this proviso to the README as part of the setup instructions? I feel like it might as well be at this point since this bug is outside of the scope of the project.

**Comment by bikegriffith** [comment]
That seems reasonable, but it also might be worthwhile to include it directly in the `Examples/VideoPlayer/iOS/Info.plist`

**Comment by edward** [comment]
Makes sense to do that in the example.

**Comment by akshaygore06** [comment]
Edit the info.plist to allow the arbitrary load. This will solve the problem

<img width="482" alt="screen shot 2018-05-18 at 12 35 30 am" src="https://user-images.githubusercontent.com/9061850/40222324-fb5f5c58-5a33-11e8-895c-55e08af3b8fd.png">

**Comment by OmarBasem** [comment]
It does not solve the problem
