### ISSUE TITLE
correct video format for Android for maximum compatibility

### ISSUE THREAD

**Issue by badpenguin** [TheWidlarzGroup/react-native-video#1000]
I've problem playing a mp4 stored locally. On the emulator things does not work or work depending of the API level.

So far:
level 19: no video  - no audio  - onEnd never called - error what=1
level 21: no video  - yes audio - onEnd event called - error what=1
level 23: yes video - yes audio - onEnd event called - NO error

Wich is the format for maximum compatibility also for Android 19 (4.4.2) ?

I usually use "ffmpeg" with those settings:

VIDEO="-strict 2 -vcodec libx264 -f mp4 -crf 22 -b:v $MAXBITRATE -maxrate $MAXBITRATE -bufsize $MAXBITRATE -pix_fmt yuv420p -movflags faststart $SCALE"

AUDIO="-ac 2 -codec:a aac -b:a 128k"

**Comment by badpenguin** [comment]
Solved using ffmepg options:

VIDEO="-vcodec libx264 -profile:v baseline -movflags faststart $SCALE"
AUDIO="-ac 2 -codec:a aac -ar 44100 -b:a 128k"

**Comment by Winglonelion** [comment]
I met same proplem, how to config this ?
