### ISSUE TITLE
HLS stream: video freezes but audio plays

### ISSUE THREAD

**Issue by shouvik44** [TheWidlarzGroup/react-native-video#1003]
I'm using react-native-video to play an m3u8 file hosted on AWS, and literally stuck... 

When I play the file on react-native-video in my IOS simulator and my iPhone 8, I see the following odd behavior
1) In normal play mode, the first video interval plays and then freezes on the last frame of the interval, while the audio continues to play as expected to the end.
2) If I drag the player's time bar to a specific point, that specific video interval plays and again freezes - while the audio picks up and continues to play from that point to the end.

I debugged and found the following
- After onLoadStart, onBuffer is called 4 times before onLoad is called.
- After onLoad, onBuffer is called a 5th time.
- After the 5th onBuffer, onProgress is called for every 250ms interval.
- I've changed my "progressUpdateInterval" from the default 250ms to 10000ms, but onProgress continues to fire every 250ms.

Note: The file plays fine in multiple HLS testers.

**Comment by urikphytech** [comment]
I'm getting this behavior as well when playing a regular video (in full screen mode)
The video starts playing and after a few seconds the image freezes but the audio keeps playing. 
@shouvik44 Do you have any insights on this?

**Comment by shouvik44** [comment]
@uriklar I was able to get the video to play by moving it from a full-page
modal to a new page. I'm not sure why that works, but the video streams
very nicely. Hope that works for you.

**Comment by paddy57** [comment]
What is full-page modal ?

**Comment by koolll** [comment]
Hi did you got any solution?

**Comment by dustinblackman** [comment]
Also experiencing this issue, not clear on a workaround. This shouldn't be marked as closed.

**Comment by freeboub** [comment]
@dustinblackman as there is no url provided nobody can reproduce this 2018 issue... But if you open a PR fixing this issue I would be happy to reopen it before merging the fix !
