### ISSUE TITLE
HLS stream Android 4.4 - error (-38, 0)

### ISSUE THREAD

**Issue by nbennink** [TheWidlarzGroup/react-native-video#1004]
## Expected behaviour:
The video component receives a m3u8 file and plays the stream (Android 4.4).

## Actual behaviour:
The video component shows nothing (black box), there is no error in the JS console, or in the app.

The Android logcat gives this error:

```
E/MediaPlayer: Should have subtitle controller already set
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: start called in state 0
    error (-38, 0)
E/MediaPlayer: Error (-38,0)
E/MediaPlayer: Error (-38,0)
```
This is the only thing I can find related to to the mediaplayer. Normal videos, or devices with Android 5+ are working fine.

## Environment:
`react-native info` returns:

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.3 => 0.53.3

Device OS: Android 4.4(.2).

**Comment by RyanColton** [comment]
I am having this issue as well on 5.0

**Comment by djw27** [comment]
Can you should us your video code? What are you passing as the `uri`?

**Comment by nbennink** [comment]
`<Video source={{uri: this.state.sourceUri}} style={styles.Video}/>`

The uri goes to a .m3u8 file on my server (eg: https://example.com/file/stream.m3u8). When I open it in Chrome it downloads the file. On iOS and Android 5.0+ it's working. And .mp4 files work on every platform.

**Comment by cobarx** [comment]
Try the ExoPlayer version of react-native-video. ExoPlayer support for HLS is much better than the stock Android video player.

**Comment by nbennink** [comment]
@cobarx I'm having issues with the Exoplayer. When switching between videos it will switch to an infinite buffer state. It is easy to reproduce. Just change the sourceUri a several times and after a few times it will will freeze.

No error in both the logcat, or React Native. Is this a known issue? Because it seems to fix the Android 4.4 problem. But I can't use the Exoplayer with this bug.

**Comment by eyalcohen4** [comment]
hey, 
I'm facing the same problem. HLS playing sometimes goes into buffer state (playbackState=buffering) without any progress/continue to play. 

did you manage to solve this/find a workaround? @nbennink

**Comment by nbennink** [comment]
@eyalcohen4 No, I still have the issue and I can't find a solution. I'm still looking into it so I'll let you know when I know more.

**Comment by eyalcohen4** [comment]
I can update that in a clean & new Android-only app (not a react native one, bootstrapped with Android Studio), Exoplayer (2.5.1) doesn't get stuck in buffering mode.
@nbennink

**Comment by eyalcohen4** [comment]
Hey, 
I've updated to 2.1.1, and the player still gets stuck in buffering mode at X times of loading.

you can see a reproducing repository [here](https://github.com/eyalcohen4/react-native-video-hls-bug). 

Click on the green field for X times (here it's sometimes 5, sometimes 30) and eventually it won't play anymore.
Tested on Samsung Galaxy S8, OnePlus 5 and LG K10

Please let us know if we can do something!!

cc @cobarx

**Comment by jenskuhrjorgensen** [comment]
I'm having a similar problem with a different error: 
`error: {
      extra: -38,
      what: 1
}`

@nbennink Do you know where I can find documentation for the error codes?

**Comment by djw27** [comment]
The only info I've been able to find on error codes, although yours is not present. Depends if you're using exo player or not too:

https://developer.android.com/reference/android/media/MediaPlayer#MEDIA_ERROR_IO

**Comment by nbennink** [comment]
@jenskuhrjorgensen -38 seems to be a playerstate error. I solved HLS streaming by using the exoplayer. But with the exoplayer I get a new problem as seen in the comments above.

You can find an installation guide for the exoplayer in the readme.

**Comment by jenskuhrjorgensen** [comment]
Thx @djw27 and @nbennink  
I'm actually using [react-native-video-controls](https://github.com/itsnubix/react-native-video-controls/issues?utf8=%E2%9C%93&q=is%3Aissue+error) v.2.2.2 which uses [react-native-video](https://github.com/react-native-community/react-native-video) v.2.0.0. Which means I'm using the Exo player, right? 

@nbennink Where do you find the explanation for the error code?

The video I'm trying to play has the following format (I don't want to share the actual content):
https://player.vimeo.com/external/75564593.hd.mp4?s=2345gfa026634550f3e5a6914a55544c08f734b68&profile_id=125

And the error occurs at Android 5.0.1. The sound is there, but no video.

**Comment by eyalcohen4** [comment]
Hey,
Can update that we've found a direction - the buffering problem is happening only in HTTPS & HLS videos.

We're now using http only for exoplayer.
Hope it'll help someone

**Comment by chops318** [comment]
One thing to note is the bridge between exoplayer and RN is not passing onTimedMetadata, I've seen it logged in logcat, however, the JS does not see it for whatever reason. I'll be looking into fixing that event, but as of now, only iOS can use onTimedMetadata

**Comment by nbennink** [comment]
@eyalcohen4 Any update on this yet? Http is a solution for the buffering option but is not an option for me. For me it is also with MP4 files. I'm searching for a solution and I'll let you know when I have something.

Edit: Update to RNVideo 2.3.1 doesn't solve the problem.

**Comment by cobarx** [comment]
@eyalcohen4 @nbennink
Ok I setup the example project. I see the buffering issue but only very occasionally.  From https://github.com/google/ExoPlayer/issues/1446, it sounds like there are a couple things that can make this more likely like a very high bitrate, corrupt video, or incorrectly setup audio. Can you check and make sure everything on the video is good. I will check and see what I can come up with, it's hard to reproduce but maybe I set it up to cycle through automatically. We can also explore buffer timeouts.

As a workaround, what if whenever it goes into the buffering state, it starts a timer. If more than a few seconds go by without exiting buffering, it pauses then unpauses the video. Not optimal but wondering if that makes it workable at least.

 On MediaPlayer, from https://stackoverflow.com/questions/9008770/media-player-called-in-state-0-error-38-0 it sounds like we are asking the video to start before it's completed the prepare step. I will have to setup a 4.4 emulator and walk through all the states to see why that's happening.

On either of these, more investigation from other folks would help a lot. Digging through this stuff is pretty time consuming and tedious.

**Comment by cobarx** [comment]
Also, I'm pretty sure this is an ExoPlayer issue. React Native doesn't do anything fancy that tends to affect things like this. It's possible that react-native-video sets up the video differently than the ExoPlayer demo, but there shouldn't be many differences.

If we can verify it does happen in a native ExoPlayer project and put together a good example, it should be pretty easy to get the ExoPlayer team to fix it.

**Comment by nbennink** [comment]
It might be possible that we have to trust our SSL certificate manually.
https://github.com/square/okhttp/wiki/HTTPS#customizing-trusted-certificates

When looking at other Exoplayer implementations and the official docs I saw them using the DefaultHttpDataSourceFactory instead of the OkHttpDataSourceFactory. Is there a reason why RNVideo is using this? 

In `DataSourceUtil.java` this seems to work for me. But I don't know if it can lead to other problems if we change it to this.
 ```
  private static HttpDataSource.Factory buildHttpDataSourceFactory(ReactContext context, DefaultBandwidthMeter bandwidthMeter, Map<String, String> requestHeaders) {
        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory(getUserAgent(context), bandwidthMeter);

        // Add request headers
        if (requestHeaders != null) {
            for (Map.Entry<String, String> entry : requestHeaders.entrySet())
            {
                factory.setDefaultRequestProperty(entry.getKey(), entry.getValue());
            }
        }

        return factory;
    }
```

**Comment by cobarx** [comment]
@nbennink I don't know why OkHTTPClient was chosen, it's been there since the ExoPlayer code was first added. Apparently, it's supposed to provide better performance than the default HTTP client. Since ExoPlayer is using the default factory, I'm ok with trying that. Does it fix the issue?

In order to switch, we need to add cookie support to the code you pasted above to maintain parity with what we already offer. I believe RN uses OkHTTP for fetch, so we'll need to check and make sure the default HTTP client sees those cookies as well.

**Comment by nbennink** [comment]
@cobarx I will try to look into cookies. But I'm not entirely sure on how to use them.

For me the default factory is working. The original problems I had: HLS stream on 4.4 and videos getting stuck are both fixed. I don't experience performance issues on my Samsung Galaxy J5 and the Google Nexus 5X. I haven't noticed new issues in my own app.

**Comment by brianephraim** [comment]
I've been experiencing the infinite buffer state in a set of videos with react-native-video ExoPlayer.  After about 9-30 video source changes, the next video gets stuck buffering, and trying to play any other videos also fails. This was not in a 4.4 device, but with Android 9.  I've spent a lot of time trying to fix this, and finally, the snippet provided by @nbennink in this thread replacing `HttpDataSource.Factory buildHttpDataSourceFactory` seems to fix it.  I hope to see it in the next release.

I also tried replacing `https` with `http` in urls but that didn't seem to have any effect.

Here are a couple videos that were exhibiting the problem:
https://pp.tedcdn.com/vids/intro_01/v02/master.m3u8
https://pp.tedcdn.com/vids/intro_02/v02/master.m3u8

**Comment by theoneit** [comment]
> Thx @djw27 and @nbennink
> I'm actually using [react-native-video-controls](https://github.com/itsnubix/react-native-video-controls/issues?utf8=%E2%9C%93&q=is%3Aissue+error) v.2.2.2 which uses [react-native-video](https://github.com/react-native-community/react-native-video) v.2.0.0. Which means I'm using the Exo player, right?
> 
> @nbennink Where do you find the explanation for the error code?
> 
> The video I'm trying to play has the following format (I don't want to share the actual content):
> https://player.vimeo.com/external/75564593.hd.mp4?s=2345gfa026634550f3e5a6914a55544c08f734b68&profile_id=125
> 
> And the error occurs at Android 5.0.1. The sound is there, but no video.

@jenskuhrjorgensen have you solved that issue ?

**Comment by jenskuhrjorgensen** [comment]
@theoneit honestly I can't remember how it ended, and I'm no longer working on that project. Sorry.

**Comment by daxaxelrod** [comment]
Looking into this more. my hls stream works fine on web and ios. Looking at logcat, throwing a 

java.io.FileNotFoundException: No content provider: https://s0-d- <rest of my url>

**Comment by daxaxelrod** [comment]
https://stackoverflow.com/a/42160256/4698066

https://github.com/react-native-video/react-native-video/blob/faf8aed29bb566fe3b7a3125cc91845d68a62982/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L337
