### ISSUE TITLE
podspec throws error because it's looking for v2.0.0

### ISSUE THREAD

**Issue by vs-lance** [TheWidlarzGroup/react-native-video#1007]
1. Add RNV using "yarn add react-native-video"
2. Add "pod 'react-native-video', :podspec => './node_modules/react-native-video/react-native-video.podspec'" to a podile file
3. Run "pod install"

Installer throws error saying "v2.0.0" can not be cloned. After checking the repo, there is no tag for v2.0.0 (nor for v1.2.0)

**Comment by cobarx** [comment]
I've just published 2.1.0 and made sure to tag it. Go ahead and give it a shot, you should be able to clone without issues now.

**Comment by vs-lance** [comment]
I finally got to test this. Works like a charm - thanks!
