### ISSUE TITLE
Cannot load .mov video

### ISSUE THREAD

**Issue by edward** [TheWidlarzGroup/react-native-video#101]
I’m trying to load `.mov` video by passing

```
source={ {uri: 'some-video.mov', type: 'mov' } }
```

as a prop to `<Video>` but end up seeing this error about a `nil string parameter`:

![image](https://cloud.githubusercontent.com/assets/325/10668074/815cbece-78a8-11e5-83d1-ca0b6863411e.png)

I know that video is there and this component plays `.mp4` files beautifully, but I can’t seem to get other filetypes to play. Any ideas?

**Comment by machard** [comment]
https://github.com/brentvatne/react-native-video/issues/1 ?

**Comment by edward** [comment]
@machard confirmed that it's not the same issue. The file is definitely there and Xcode is aware/copies it in.

**Comment by klausbreyer** [comment]
.MOV does not work for me, too. 

Solution: convert the video file: 
ffmpeg -i A.MOV -vcodec copy -acodec copy out.mp4

**Comment by klausbreyer** [comment]
Also make sure, that the video is available. Should look like this. 
![screen shot 2015-11-05 at 14 59 48](https://cloud.githubusercontent.com/assets/32771/10970294/07b1a7ca-83ce-11e5-9e53-c0e5f1a4bf20.png)

**Comment by klausbreyer** [comment]
And restart the Simulator after copying.

**Comment by edward** [comment]
@klausbreyer sadly not a fix for me :( The `.mov` I have has transparency/alpha channel jazz going on that’s not supported by the encoding I have in `.mp4`

**Comment by tomprogers** [comment]
`.mov` won't play on Android natively, FYI. You'll need to transcode to e.g. `.mp4`.

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by taltultc** [comment]
try this:
https://github.com/taltultc/react-native-mov-to-mp4

**Comment by tomprogers** [comment]
Well, I assume this problem still obtains because Android still doesn't bundle the necessary codec.

I don't think transcoding files on the fly is an especially good solution. It sounds like a great way to drain the user's battery, though!

**Comment by taltultc** [comment]
Well, if you want to convert big video files so ffmpeg will do great work on server side, but for small video size convert to mp4 will not drain the battery cuz it take only few seconds.
This is just another option :)

**Comment by zchwyng** [comment]
Closing this since it's outdated.
