### ISSUE TITLE
Change audio track from stream

### ISSUE THREAD

**Issue by acollazomayer** [TheWidlarzGroup/react-native-video#1011]
Is it posible to change the audio track from a stream with this library

**Comment by cobarx** [comment]
Not yet, I will be starting work on this once the text track selection feature is complete.

**Comment by jaybrto** [comment]
Hey Hampton! Any news on adding audio track selector like you did on closed captions?

**Comment by cobarx** [comment]
@jaybrto Hey man, I decided to give it a look based on your interest and put in some time in this afternoon. It's very straightforward and coming along nicely! As soon as it's all there, I'll push it to a branch and you can put in some testing.

Do you happen to have some sample media I could use to test it? Right now, the only video I have is an HLS playlist with 2 audio tracks. A few more examples, especially an mp4 would be fantastic to make sure it handles all the possibilities.

**Comment by acollazomayer** [comment]
@cobarx hi I have some streams, m3u8 and mpd streams to test if you need so. I can talk to some coworkers about the posibility of making a mp4 with two audios. Thanks!!

**Comment by acollazomayer** [comment]
@cobarx I can get you a mp4 with two audios. Talk me back when you need them

**Comment by cobarx** [comment]
@acollazomayer I'm working on it now, so if you're able to send it over today that would be great. My email is me@hamptonmaxwell.com if you don't want to post it publicly.

**Comment by jaybrto** [comment]
On it! I'm going to put something together for you asap. Its going to be a HLS stream with a couple of audio tracks. One of them tagged with audio description but its just another audio track. Thanks!

**Comment by cobarx** [comment]
@acollazomayer Never mind, just saw your email with the videos! Will be testing very shortly.

**Comment by cobarx** [comment]
@acollazomayer I'm not having any luck with those videos. 

On the mp4, it appears there's something funky with the audio tracks, it crashes on ExoPlayer and there's no sound on iOS. I can get it to work but have to use super compatible players like VLC.

For the streams, it looks like most of the audio is in English, so it's pretty hard to tell if it works even if I switch to the Spanish stream.

I'm going to see if I have any sample videos that I have lying around to test this.

**Comment by cobarx** [comment]
Ok this is theoretically all done and needs testing. See #1137. I would appreciate code reviews if anyone wants to look at it.

Test with: https://github.com/react-native-community/react-native-video.git#feature/select-audio-track

I made the default behavior be that it auto-selects the audio track that matches the customer's system language if available.

You can see the audio tracks that are available in the onLoad payload.

I got a working test video by re-encoding the mp4 from @acollazomayer. I can post a link to that, but am not sure if that's allowed to be distributed.

Edit: fix URL

**Comment by vikassemwal1994** [comment]
Hi @cobarx thank you so much for this reply, I am also working on the same scenario, Can I please get the demo video with dual-audio
Thank you again

**Comment by freeboub** [comment]
I am working to demonstrate it on sample. Should come in some days !

**Comment by hueniverse** [comment]
Thanks @freeboub!

**Comment by AlkenD** [comment]
> I am working to demonstrate it on sample. Should come in some days !

so is there a working demo for this ?. I couldn’t find any.

**Comment by freeboub** [comment]
@AlkenD check basic sample in master branch. The audio tracks selector is available

**Comment by AlkenD** [comment]
> @AlkenD check basic sample in master branch. The audio tracks selector is available

The example's seems to be outdated or not working I was looking for a hooks version for the same

**Comment by freeboub** [comment]
@AlkenD please check on master branch, the android sample works fine !
