### ISSUE TITLE
Video restarts when calling seek(0) in onEnd callback

### ISSUE THREAD

**Issue by cristiantone** [TheWidlarzGroup/react-native-video#1013]
Hi,

I'm playing a video in my app and I'm using the onEnd callback with the following code:
`this.setState({playing: false, currentTime: 0, percent: 0});
 this.player.seek(0);`.

The seeker and the controls reset to the initial state, but the video starts playing event if the repeat option is set to false.

Can anyone help me?

**Comment by cobarx** [comment]
Repeat will automatically seek to the beginning when the video ends. However, since you are manually seeking, you're overriding the repeat behavior. You will need to change your logic in `onEnd` to not seek to the beginning.

**Comment by augustosamame** [comment]
I am being bit by this as well.

```
repeat={false}
paused={this.state.paused}
```

When video stops playing I want to be able to click on play button and for it to start playing again from the beginning. So, standard behavior.

This onEnd function:

```
onEnd = () => {
        this.video.seek(0);
        this.setState({paused: true});
    };
```

Will have the effect of the video repeating itself from the beginning again.

If I don't include `this.video.seek(0);` then video will not play again when pressing play button as it's at the end of the video.

So how to achieve proper behavior? Thanks in advance for your help.

**Comment by augustosamame** [comment]
This solved it: 
onEnd = () =>  this.setState({ paused: true }, () => this.video.seek(0))

**Comment by Joshmatjjen** [comment]
Hope this solution helps

```
function onEnd(e) {
       console.log('Audio ended', e);
       setAudioState({ ...audioState, play: false, currentTime: 0 });
       setTimeout(() => {
         audioRef.current.seek(0);
       }, 500);
  }

```

**Comment by davilico05** [comment]
Same here with the possibility of replay once video finished.
> If I don't include `this.video.seek(0);` then video will not play again when pressing play button as it's at the end of the video.

It would be great have a "this.video.stop()" to player reset and allow us play video again.

I solved it with setTimeout but seem it a botched job

> Hope this solution helps
> 
> ```
> function onEnd(e) {
>        console.log('Audio ended', e);
>        setAudioState({ ...audioState, play: false, currentTime: 0 });
>        setTimeout(() => {
>          audioRef.current.seek(0);
>        }, 500);
>   }
> ```
