### ISSUE TITLE
Rate does not accept all values iOS

### ISSUE THREAD

**Issue by Waltari10** [TheWidlarzGroup/react-native-video#1014]
I was trying to set rate to values like 0.1845 and noticed that it does not work as intended. Instead AVPlayer seems to round the rate to the closest on of these numbers: 0.50, 0.67, 0.80, 1.0, 1.25, 1.50, and 2.0.

I think this is because the default audio time pitch algorithm only allows these values. I wonder if one of the others allows float values like this? Basically in order to fix this issue on iOS the algorithm needs to be able to be replaced. Haven't tested this on Android.

Related issue on StackOverflow: https://stackoverflow.com/questions/6630356/avplayer-rate-property-does-not-work

AVPlayerItem algorithm documentation:
https://developer.apple.com/documentation/avfoundation/avplayeritem/1385855-audiotimepitchalgorithm

Available Algorithms: https://developer.apple.com/documentation/avfoundation/avaudiotimepitchalgorithm

**Comment by cobarx** [comment]
I'm pretty swamped with other PRs at the moment. However, if you want to implement a PR to support this, it would be great!

**Comment by kesha-antonov** [comment]
Same here!
1.75 playing on speed 1.5

@Waltari10 @cobarx Guys, did you fix it or found a solution?

**Comment by kesha-antonov** [comment]
Hey guys! @Waltari10 @cobarx I created PR for this
