### ISSUE TITLE
Scrubber

### ISSUE THREAD

**Issue by jasecoop** [TheWidlarzGroup/react-native-video#102]
Has anyone used react-native-video and created a scrubber? Seems there isn't one at the moment.

I'd like the user to be able to change the time using a scrubber (e.g. youtube videos).

**Comment by jasonwiener** [comment]
did u ever find anything on this? i'm more interested to scrub locally store video, but the component should be similar internally.

**Comment by jasecoop** [comment]
@jasonwiener I ended up building my own. I used the React-native gesture responder system to drag the scrubber left and right, then calculating the new audio time based on the scrubbers positioning.

The gesture responder system made it pretty easy in the end.

**Comment by jasonwiener** [comment]
thanks! any chance you wanna share?

**Comment by jasecoop** [comment]
@jasonwiener sure I'd be happy to, let me get my code in order and put it in a gist, I will give you a shout here when done

**Comment by jasonwiener** [comment]
@jasecoop Truly appreciate that!

**Comment by stereodenis** [comment]
@jasecoop do you mean seek controls? like these https://github.com/brentvatne/react-native-video/blob/master/Examples/VideoPlayer/index.ios.js

**Comment by jasecoop** [comment]
@stereodenis Yep, in fact it was this that sent me in the right direction. On top of that I made the seek controls interactive so you can drag and seek. cc @jasonwiener

**Comment by jasonwiener** [comment]
@jasecoop that's what i'm trying to get my head around as well!

**Comment by jasecoop** [comment]
@jasonwiener This code is a thrown together as it's a WIP, but I've tried to simplify. I hope you'll find it useful.

I'm using what I've called a 'toggle' (I'm sure there's a more technical name) for the element that's draggable. It's left positioning lives is stored in state. 
On drag: 
- Calculate new toggle position and set state
  On drag release:
- Calculate percentage of toggle position to container width
- Use this percentage to calculate the new audio/video time the user has dragged to
- Seek to new time

React-native gesture responder system handles the dragging events for us. So just work out the maths of positioning relative to track current time and you're good to go.

Next I need to work out how to seek to a certain point of the track when the user touches the scrubber.

```
  getInitialState: function() {
    return {
      toggleLeftPosition: 0
    }
  },

  getCurrentTimePercentage() {
    var percentage = parseFloat(this.props.audio.currentTime) / parseFloat(this.props.audio.duration);
    var w = Dimensions.get('window').width;
    var x = percentage * w;
    this.setState({
      toggleLeftPosition: x
    })
  },

  setNewTime() {
    var x = this.state.toggleLeftPosition;
    var windowWidth = Dimensions.get('window').width;
    var percentage = (x*100) / windowWidth;

    var totalSeconds = this.props.audio.duration;
    var newTime = (percentage/100)*totalSeconds;
    this.setState({
      currentTime: newTime
    })

    // seek to new time
    this.props.audio.setTime(newTime)
  },

  setPosition: function(e) {
     //Update our state with the deltaX/deltaY of the movement
     this.setState({
       toggleLeftPosition: this.state.toggleLeftPosition + (e.nativeEvent.pageX - this.drag.x)
     });
     //Set our drag to be the new position so our delta can be calculated next time correctly
     this.drag.x = e.nativeEvent.pageX;
   },

   onRelease: function(e){
     this.dragging = false;
     this.setNewTime();
   },

   _onStartShouldSetResponder: function(e) {
     this.dragging = true;
     //Setup initial drag coordinates
     this.drag = {
       x: e.nativeEvent.pageX,
       y: e.nativeEvent.pageY
     }
     return true;
   },
   _onMoveShouldSetResponder: function(e) {
     return true;
   },

   caculateTime() {
     if(!this.dragging) {
       this.getCurrentTimePercentage();
     }
   },

  componentWillReceiveProps() {
    if(!this.props.audio.paused && this.props.audio.uri == this.props.uriSource) {
      this.caculateTime();
    }
  },

  render: function() {
    return (

      <View>
          <View
            style={ [ local.toggle, { left: this.state.toggleLeftPosition } ] }
            onResponderMove = { this.setPosition }
            onResponderRelease = { this.onRelease }
            onStartShouldSetResponder = { this._onStartShouldSetResponder }
            onMoveShouldSetResponder = { this._onMoveShouldSetResponder }
          />
      </View>

    );
  }
});
```

**Comment by jasonwiener** [comment]
@jasecoop SUPER cool and thanks a ton. i'll give it a whirl and holler back with thoughts too! truly appreciate the openness!

**Comment by rsokz** [comment]
@jasecoop Do we have a final version of this solution?
