### ISSUE TITLE
video pauses music even if muted

### ISSUE THREAD

**Issue by JesperLekland** [TheWidlarzGroup/react-native-video#1026]
Thanks for a terrific library! 

I have a video without an audio track (explicitly removed) and with the `muted` prop set to `true`, still when mounting (or resuming) the video it pauses the music playing on an iOS device. It works as expected on Android. Any idea how to solve this?

**Comment by remigallego** [comment]
Can you try using 3.0.0 ?

**Comment by JesperLekland** [comment]
I'll try it first thing Monday and get back to you 👍

**Comment by ivan-kaminskyi** [comment]
We are also experiencing this issue on 3.2.1? Is there any workaround to fix it apart of patching lib sources?

**Comment by Thram** [comment]
Same here, having problems with Spotify even with a video without Audio on iOS

**Comment by alexcbluk** [comment]
This is what I did to resolve this problem:
1) Follow the steps shown for Audio Mixing: https://github.com/react-native-video/react-native-video#audio-mixing

2) Configure in your xcode project:
https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW3

**Comment by mattijsf** [comment]
For me it worked by just setting `ignoreSilentSwitch="obey"` this implicitly sets the audio session category to `AVAudioSessionCategoryAmbient` as mentioned in https://github.com/react-native-video/react-native-video#audio-mixing
