### ISSUE TITLE
IOS: unable to load more than 16 videos on one component

### ISSUE THREAD

**Issue by fatwhale** [TheWidlarzGroup/react-native-video#1029]
I'm trying to load a list of react-native-videos on a swiper. However, only the first 16 videos loads. Does anyone face the same issue? Or is there a solution?

**Comment by cobarx** [comment]
This is a system limitation from what I understand and exists in native iOS apps as well. It needs to get documented at some point.

I would see about unmounting the videos when they are swiped off screen.

**Comment by fatwhale** [comment]
seems it might be solved soon. the simulator can load more than 16 now. But iPhone would still be stuck at 16

**Comment by ami9000** [comment]
I count 16 videos max as well before I get a blacked out view. My current workaround is to render an <Image> in the <Video>'s place when it is is off screen.
