### ISSUE TITLE
onBuffer calls only in beginning.

### ISSUE THREAD

**Issue by karan101292** [TheWidlarzGroup/react-native-video#1033]
Hi, `onBuffer` is called only once, in the beginning of the video. It doesn't call again if video stuck in between due to slow internet. It should call `onBuffer` whenever video is stuck due to slow internet.

**Comment by karan101292** [comment]
Hi, any update on this?

**Comment by cobarx** [comment]
@karan101292 Which platform are you seeing this problem on?
