### ISSUE TITLE
[discussion] Switching to ExoPlayer as the default Android video player

### ISSUE THREAD

**Issue by cobarx** [TheWidlarzGroup/react-native-video#1038]
I wanted to get feedback from the community about what needs to happen to make Android use ExoPlayer as the default video player that gets used when you do `react-native link`. As soon as possible, I'd like to switch over and devote all future development efforts to expanding the ExoPlayer feature set. I'm happy to merge PRs to continue to support the old Android player, however doing new development myself for two different players is more work than I want when there's no real benefit to having both.

As far as I know, ExoPlayer has feature parity with the old player. Fixes for progress updates and support for repeat mode were just added. For the app I work on, ExoPlayer is working great. However, other people may have features I haven't tested or issues I'm not aware of. If so, please chime in.

**Comment by cobarx** [comment]
ExoPlayer works significantly better than the old player on both older devices and with formats like HLS. Plus it gets updated on a regular interval whereas old Android versions are stuck with the media player they shipped with. So I think it's a no brainer to make ExoPlayer the default.

**Comment by mandriv** [comment]
Had no issues with ExoPlayer on Android - would definitely opt for making it default.

**Comment by PimDeWitte** [comment]
+1 would recommend making it default

**Comment by eyalcohen4** [comment]
After https://github.com/react-native-community/react-native-video/issues/1004#issuecomment-394664464, I can now support making exoplayer default and will be happy to help with anything regarding this.

@cobarx

**Comment by chops318** [comment]
Just a note, on the java side, exoplayer sees timedMetadata, however, the JS side does not see it. I've taken a quick look through the source, and it looks fine, but haven't had the time to debug this. Has anyone successfully seen timed metadata on the JS side using exoplayer?

**Comment by fendorio** [comment]
+1 for ExoPlayer being the default choice of player.

**Comment by cobarx** [comment]
Ok I've merged #1062 to do this and will push out a 2.3.0 release later today!

@chops318 I'm not sure how to setup a video that uses timed metadata, can you provide an example? I can debug once I have that.

**Comment by chops318** [comment]
@cobarx , we use Wowza, if you could PM me when giving it a go, I can throw up a stream and give you a link. Thanks

**Comment by PerspectivesLab** [comment]
we are still waiting 2.3.0, and also video doesnt autoplay on android  and exoplayer for 2.2.0, hopefully it will change on 2.3.0

**Comment by cobarx** [comment]
@PerspectivesLab Sorry about that. I went on vacation last week and didn't want to issue a release and then find out something was broken and not be able to fix it. Pushed 2.3.0 out just now.

I am going to do a 3.0 release shortly that cleans up a bunch of the API stuff that is busted like Android not autoplaying and making returning from background behavior consistent across platforms. That way we can be extra safe and not break anybody's apps.

In the meantime, you can work around it with:
`paused={false}`
Sorry for the inconvenience :/

**Comment by PerspectivesLab** [comment]
thats ok @cobarx looking forward, i will test that asap, keep up the great work 👍

**Comment by cobarx** [comment]
@PerspectivesLab Got autoplay on ExoPlayer working with #1083. It will be included in 3.0.

@chops318 I'm not seeing any contact info in your GitHub profile, can you email the link to me@hamptonmaxwell.com
