### ISSUE TITLE
Issue while using android-exoplayer

### ISSUE THREAD

**Issue by karan101292** [TheWidlarzGroup/react-native-video#1047]
Hi, I am not able to build android uisng while android-exoplayer.
It is throwing  Multiple dex exception.

```
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/ws/WebSocketReader$FrameCallback;

```
any solution?

**Comment by cobarx** [comment]
It looks like our version of OkHTTPClient3 is different than another library you have in your project. You can try changing your build.gradle from:
```
compile project(':react-native-video')
```
to:
```
compile(project(':react-native-video')) {
  exclude group: 'com.squareup.okhttp3'
}
```
Let me know if that works for you.

**Comment by cobarx** [comment]
I'd also be interested which other library is conflicting with this library so I can look into whether we need to go back to the other OkHTTPClient3 version.

**Comment by karan101292** [comment]
Hi, the solution you provided worked well.
I think com.facebook.fresco is conflicting with exoplayer.
com.facebook.fresco has okhttp3 - 1.0.1
and android-exoplayer has okhttp3 - 2.7.3

**Comment by cobarx** [comment]
Glad it worked. Thanks for providing that info, I'm not sure there's any way around it, Android doesn't handle multiple packages using different versions well.
