### ISSUE TITLE
ExoPlayer: Doesn't start playing AKA autoplay not working

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1052]
I'm using react-native-fs to play a local M4A file. This works fine on iOS and the standard Android media player. When using ExoPlayer, the paused state needs to flipped twice for the file to play upon load.

**Comment by cobarx** [comment]
Were you setting playInBackground to true? There was a bug where if you did that it ignored the paused flag. I've merged #833 which fixes that issue.

**Comment by anshul-kai** [comment]
Yes, I had `playInBackground` set to `true`. The new version `2.3.0` no longer has this issue.
