### ISSUE TITLE
ExoPlayer: Android 6.0 - Video disappears

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1053]
I'm using a full screen background video which seems to disappear after minimizing the app. This works just fine on other OS versions and on 6.0 if using the standard MediaPlayer build.

**Comment by eyalcohen4** [comment]
Can u provide a reproduction repo? 
Also, what do you mean by minimizing the app? 

If you can try to test this the Exoplayer instead of MediaPlayer and let us know if it's still happened it would be great.

**Comment by anshul-kai** [comment]
Tried on a few devices and it looks like this may be device specific too. Can't recreate on Nexus 5 Android 6.0.1 but happens sometimes on Lenevo A7020a48 Android 6.0. Seems quite intermittent and a bit more rare than I had originally thought.

Thanks for looking into this.

**Comment by anshul-kai** [comment]
A little more info for you @cobarx. This is happening only upon a video switch which is followed by a minimize. My app uses a full screen video background and we tried several times and this is the only case where this happens. Seems pretty corner case. Feel free to ignore and close out the issue.
