### ISSUE TITLE
Cannot play ogg files

### ISSUE THREAD

**Issue by mapinas** [TheWidlarzGroup/react-native-video#1054]
I can play mp3 files without problems, but not ogg files. I receive the following error:

```
domain: "AVFoundationErrorDomain"
code: -11828
```

Code:

 ```
  <Video source={{uri: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Sv-elva.ogg"}} 
          repeat={true} 
          onLoadStart={ () => console.log("Loading sound" ) } 
          onBuffer={ () => console.log("Buffering sound" ) } 
          onEnd={ () => console.log("Ending sound" ) } 
          onError={ (err) => console.log(err)  }
    />
```

Replacing uri: "https://www.sample-videos.com/audio/mp3/crowd-cheering.mp3" and it works. (I also tried other ogg files with the same result.)

react-native: 0.54.2
react-native-video: 2.1.1

**Comment by cobarx** [comment]
AVPlayer doesn't support Ogg Vorbis:
https://stackoverflow.com/questions/21879981/avfoundation-avplayer-supported-formats-no-vob-or-mpg-containers

We would have to pull in additional libraries to support it. It's something we can consider further down the road.
