### ISSUE TITLE
Thank you for reviving this project!

### ISSUE THREAD

**Issue by djw27** [TheWidlarzGroup/react-native-video#1056]
Not an issue - I just wanted to thanks @cobarx for saving this project - your hard work in reviving this project is super appreciated!

Video is a huge part of our app and we'll be giving back to this project as much as possible.

**Comment by cobarx** [comment]
@djw27 Thank you, I greatly appreciate the acknowledgement.

I really welcome the contributions. There's a lot of places we could use help, I'd love to get feedback on what to prioritize and how things should work in addition to any PRs or code reviews you want to do. Still figuring out how to set that up and make the community aware of it.

**Comment by eyalcohen4** [comment]
Many many thanks. we also use it in many places, and we'll try to contribute back when possible.

Thank you @cobarx!
