### ISSUE TITLE
Component to Display while Content is Downloading

### ISSUE THREAD

**Issue by cancan101** [TheWidlarzGroup/react-native-video#106]
Take a prop of a component to show while the video is downloading.

**Comment by a-axton** [comment]
I was able to accomplish this by using the onProgress callback, currentTime will stay at 0 until it has enough buffer to start loading. As showing something when video was buffering I am saving currentTime to state and then comparing it to the currentTime value in onProgress

**Comment by mattapperson** [comment]
Closing this as using onProgress is a solid solution
