### ISSUE TITLE
无法在react-navigation 和 FlastList中是实现全屏

### ISSUE THREAD

**Issue by shaoting0730** [TheWidlarzGroup/react-native-video#1064]
### Current behavior
I use video in FlatList and react navigation, and I can't play it all on screen

### Reproduction steps
1.
2.
3.

### Expected behavior
React -navigation and FlatList for full screen

### Platform
* iOS
* Android 

### Video sample
http://124.129.157.208:8810/SD/zhishidian/grade_8_1/wuli_shu/01.mp4

**Comment by cobarx** [comment]
Hi @pheromone, can you add a code sample to reproduce this issue? This video plays fine without a FlatList, so I'm guessing the issue is how you have the FlatList setup.
