### ISSUE TITLE
Media not playing across navigation screens (Android)

### ISSUE THREAD

**Issue by Zenmai0822** [TheWidlarzGroup/react-native-video#1065]
### Current behavior

The Menu Screen has a background music track implemented by `<Video>`, and the background music is stopped whenever the user navigates away. `this.props.navigator.push()` is used with `react-native-navigation`  

### Reproduction steps

```
react-native-video: 2.1.1
react-native-navigation: 1.1.444
react-native: 0.49.5
android: 8.1
```

1. User navigates to another screen
2. Background music stops playing

### Expected behavior

Expecting the `<Video>` component will be persistent across navigation screens 

### Platform
Which player are you experiencing the problem on:

* Android MediaPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

```{javascript}
class MenuScreen extends Component {
 

  constructor(props) {
    super(props);
    this.player = '';
    this.state = {
      _mute: this.props._mute
    }
  }

  goToClueOfTheDay = () => {
    this.props.getRandomClue()
        .then(() => {
          this.props.navigator.push({
            screen: "rnJeopardy.ClueOfTheDayScreen",
            title: 'ClueOfTheDayScreen',
            animated: true,
            animationType: 'fade',
            backButtonHidden: true
          });
        });
  }

  render() {
    return (
      <View style={{alignItems: 'center', justifyContent: 'center', backgroundColor: '#060CE9'}}>
        <Menu 
          onPressedClueOfTheDay={this.goToClueOfTheDay}
        <DefaultFeedback />

        {this.props._mute!= 'null' && !this.props._mute && 
            <Video source={{uri: 'https://ia600302.us.archive.org/3/items/JeopardyTheme/Jeopardy.mp3'}}    
              ref={video => this.player = video}
              rate={1.0}
              volume={1.0}
              repeat={true}
              paused={this.state._mute}
              playInBackground={false}
              style={{height: 0}} 
          />
        }
      </View>
    );
  }
}
```

**Comment by cobarx** [comment]
I've used react-navigation before and didn't need to make any special changes to get it to work.

A couple things you could try: switch over to ExoPlayer, set the playWhenInactive prop. I don't think either should be necessary though. Is your mute flag getting set somehow?

It is a total pain to setup navigation, any chance you can share the whole project with me? You can email the info to the email address on my GitHub profile if that is convenient for you.

**Comment by cobarx** [comment]
Oh I just took a second look at your code and it appears you are mixing native components and React Native components. I bet that's the issue, loading a new activity causes the other activities underneath it to fire their onPause methods which is pausing the React Native view that Video lives in.

There's no easy way to handle this on Android as playWhenInactive is not supported there. Feel free to implement that and submit a PR. Alternately, you can set playInBackground and then add some logic to differentiate between navigating to a new activity and going to the background. It's hacky but should be doable.

**Comment by cobarx** [comment]
Another person was running into a similar issue using TabNavigator. Are you using a tab or stack navigator? If it's tabs, it's because the video gets detached which causes it to pause.

I'm currently working on a PR to address that issue and it will be included in the 4.0.0 release.

**Comment by MigueVeliz** [comment]
Awesome!

**Comment by nicer00ster** [comment]
@cobarx Related to #1124 but in my case, I thought I had fixed the issue, which for some it probably will so I'll share what I did to resolve this. 

I moved the Video component outside of my routes, and initiated it on the same level where my root component is for my Navigator. So both the Video and Navigator would live in a file called ```Root.js``` then in your ```App.js``` you'd create your Provider with your store, and wrap the Root component there. Doing this persists the audio into any screen that you change to. 

If you're using react-navigation you'll likely experience issues if you want to access the video ref on the component itself. I spent a lot of time the past two days trying to figure out how I can access the ref from within my defined routes. I tried react-navigation's onRef method, the new forwardRef method, defining the ref within a Context provider and passing it down the tree. The ref will be carried down a 3-4 levels deep before being lost at a navigation route. So if you're trying to use the .seek() method you might come across this same problem I did. If anyone figured out how to do so, please share! ❤️

**Comment by Domingowen** [comment]
i have same problem when i used the react navigation createBottomTabNavigator api in android, i expect you will fixed bug. thanks for!

**Comment by alexandruenache19** [comment]
Any updates on this issue? I am using createBottomTabNavigaton in android and the bug is still there. Thanks!

**Comment by klodha** [comment]
Same here, despite code having line commented out (stopPlayback() method call), it is still stopping playback upon switching tabs when using createBottomTabNavigaton
