### ISSUE TITLE
HLS stream UI block when loading a broken URL (iOS)

### ISSUE THREAD

**Issue by HeinzStaschen** [TheWidlarzGroup/react-native-video#1067]
### Current behavior
Screen doesn't render until the onError callback gets triggered.

### Reproduction steps
Set the Video component source uri to a broken https m3u8 URL.

### Expected behavior
Screen needs to render normally so I can display a loader and then handle the onError event if needed.

### Platform
* iOS

### Video sample
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

I've investigated RCTVideo.m and noticed you guys use AVURLAsset (which I suspect might be the cause of the issue):
```
if (isNetwork) {
    NSArray *cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookies];
    AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:@{AVURLAssetHTTPCookiesKey : cookies}];
    return [AVPlayerItem playerItemWithAsset:asset];
  }
```

Refer to link for possible solution:
https://stackoverflow.com/questions/38777384/avurlasset-urlassetwithurloptions-blocks-main-thread-with-remote-url

**Comment by danielmcmillan** [comment]
Do you still get this issue if you don't specify any one of the props 'ignoreSilentSwitch', 'rate', 'volume' or 'muted'?
If not than my pull request #1086 may fix the issue. Potentially the cause is what you have referenced and this just happens to work around it though.

**Comment by namgk** [comment]
I have the same problem, but I have 'volume' prop on. Will try to remove it.

**Comment by treemore** [comment]
use charles.  start throttling . the ios ui will block util buffed success

**Comment by cobarx** [comment]
Are people still having this issue? 

I tested the PR in #1113 and it has the side effect of causing the video to show up if you start the video paused. I think the solution @HeinzStaschen proposed is the right way to handle this, but it will take a fair bit of work to implement that. So lmk if that rework is needed.

**Comment by StuartMorris0** [comment]
This issue still exists for me on iOS.

I only have props for source, onError, style and controls. The video locks up the main UI thread when loading the video, once the video is loaded it is released.

**Comment by BaderSerhan** [comment]
@StuartMorris0 are you starting the videos paused?

**Comment by StuartMorris0** [comment]
I think they autoplay but I cannot remember 100%.

**Comment by muganwas** [comment]
I'm using version 5.0.2 and I'm still experiencing this issue. Is there a solution?
