### ISSUE TITLE
Exoplayer - Unable to connect to VIDEO_URL, Unrecognized media format

### ISSUE THREAD

**Issue by urikphytech** [TheWidlarzGroup/react-native-video#1068]
### Current behavior
onError callback throws the following error:
```
{"error":{"":"Unable to connect to https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4","errorString":"Unrecognized media format"}}
```

### Reproduction steps

Component:
```
<Video
              source={{
                uri:
                  "https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4"
              }}
              ref={ref => {
                this.player = ref;
              }}
              style={styles.player}
              paused={this.state.moviePaused}
              onError={e => console.log(e)}
              onPlaybackStalled={this.pauseMovie}
            />
```

using Exoplayer

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4

**Comment by cobarx** [comment]
What device are you running into this on? I tested this on an Android 7.1 emulator with ExoPlayer and it loads and plays properly.

From https://github.com/google/ExoPlayer/issues/2069, it sounds like your device may not have the necessary codecs installed. If that's the case, there's not much we can do. They suggest trying it with Android MediaPlayer to verify that. Can you switch over to MediaPlayer and test that. The other possibility is that the server was having some kind of outage and was returning some kind of error page. I would try it again to make sure that's not it.

I'm surprised that codecs would be the issue here though because the video is an mp4 using the most conservative encoding settings.

**Comment by albinhubsch** [comment]
@urikphytech did you succeed in solving this??

**Comment by sahilvicesoftware** [comment]
Facing same issue.Video doesn't play sometime

**Comment by nathantqn** [comment]
I'm facing the same issue, Sometimes the video raises the error like this on Sentry (I'm using m3u8 format, and sometimes it cannot connect to the streaming fragment)

**Comment by cKurultayKalkan** [comment]
+1

**Comment by CHaNGeTe** [comment]
Try making explicit the mimetype on the source object.

Which kind of stream are you using?

**Comment by cKurultayKalkan** [comment]
In my case, it was about the ssl certificate of the website. Could you track the error from Android Studio -> Logcat.

"Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found"

**Comment by ezranbayantemur** [comment]
Any update? I'm having same issue too..

**Comment by CHaNGeTe** [comment]
@ezranbayantemur paste logcat log

**Comment by ezranbayantemur** [comment]
> @ezranbayantemur paste logcat log

@CHaNGeTe 

2019-09-16 14:01:31.900 18219-18219/com.myapp W/MediaPlayer: Couldn't open https://www.m.....89567.mp4: java.io.FileNotFoundException: No content provider: https://www.m.....89567.mp4

Url is working on web browser and I tried on iOS, it works fine. Problem only occurs Android side.

**Comment by CHaNGeTe** [comment]
It seems it is receiving a 404 for the video url. Can you share it?
If that's not the case try  including `type: 'mp4'` on the source object

**Comment by ezranbayantemur** [comment]
But it's load the video for 3-4 seconds. When I refresh the page video component stuck on load and gives error. Sometimes it's gives the error and still keeps playing for 3-4 seconds.. 

Test Video: 
https://www.medicres.club/usershares/0e7de5e6e98d67ca9d370fb538b02b99cb26f8c2c9f6471c66bae94a23531a9033589567.mp4

You mean `source={{ uri: https://www.medicres.club/${props.video} type: 'mp4' }}` , right?

By the way, it can play this video " https://vjs.zencdn.net/v/oceans.mp4 " with no problem..

**Comment by aniket-dalvi** [comment]
I am also facing the same issue. any update on this?

**Comment by edritech93** [comment]
same for me

**Comment by rohitsingh2410** [comment]
The issue is very random sometimes it works and sometime it do not. 
any update or workaround on this?
@edritech93  @aniket-dalvi

**Comment by aniket-dalvi** [comment]
If you are running your application in android then check the network logs in network profile of Android Studio while loading the media. It will help you to debug the issue. @rohitsingh2410

**Comment by rohitsingh2410** [comment]
@aniket-dalvi . I have videos alredy downloaded in system.  Do you have any other suggestions?

**Comment by erfanshekari** [comment]
same issue for me. 

source: {
    uri: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8', 
    type: "m3u8",
}

**Comment by freeboub** [comment]
@erfanshekari it works on master branch on my side.

**Comment by freeboub** [comment]
let's close this old issue without clear reproduction step.
most of provided urls are not available anymore.
Please open new ticket with reproduction step and logcat for more investigations.

**Comment by cejuo** [comment]
> 



> In my case, it was about the ssl certificate of the website. Could you track the error from Android Studio -> Logcat.
> 
> "Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found"

This happens to me too. It was working fine a couple of months before.
Did you find any solution?
