### ISSUE TITLE
Audio Keeps Playing Even After React Native Refreshed

### ISSUE THREAD

**Issue by cancan101** [TheWidlarzGroup/react-native-video#107]
I reloaded JS but I still hear audio playing.

**Comment by aleclarson** [comment]
I've also experienced this. Might take a look later.

**Comment by arilitan** [comment]
I've experienced this issue as well. I think it this is more suited for the react-native project it self - there should be some sort of callback and/or event fired when the JS bundle is being reloaded.

Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by cmmartin** [comment]
I'm experiencing this issue fairly consistently. The question is how does the native video player instance survive the unmount? Seems to me this is indicative of a failure to clean up the native instance which would imply a memory leak in this library

**Comment by zhigang1992** [comment]
For me, this was happening because of https://github.com/kmagiera/react-native-screens/pull/93 if you're using `react-native-screens` try disable it first.

**Comment by cmmartin** [comment]
Nice work @zhigang1992. I am using react-native-screens and disabling it has resolved this

**Comment by tslater** [comment]
I'm currently using react-native-screens. Even though it looks like they fixed this, I'm still experiencing the issue. Just to clarify @zhigang1992  or @cmmartin, by "disable" do you mean to remove react-native-screens from the project? Or just not use it for the video? Or is there some other property/settings that can be disabled?

**Comment by enfipy** [comment]
Facing this issue too on `v6.0.0-beta.4`, @tslater any luck with fixing this?

Also, I think this issue is linked: https://github.com/react-native-video/react-native-video/issues/2281.

**Comment by tslater** [comment]
No, I was only using react-native-video for DRM support. Given this issue,
we decided to contribute DRM to expo-av and switched back to that since we
weren't having this and other issues.

**Comment by interstates21** [comment]
> Facing this issue too on v6.0.0-beta.4, @tslater any luck with fixing this?

Same for me :(
