### ISSUE TITLE
How to get the buffer data?

### ISSUE THREAD

**Issue by ghyzx** [TheWidlarzGroup/react-native-video#1077]
How to get the buffer data after the video is fully buffered? I want to have it stored locally.

related issue
https://github.com/react-native-community/react-native-video/issues/838

**Comment by cobarx** [comment]
It's not possible to save the video from the buffer at the moment. There is a PR in #885 but I haven't had a chance to evaluate it yet.

Otherwise, it will probably be quite awhile before we support this on ExoPlayer.

**Comment by ghyzx** [comment]
Thank you for your prompt reply, and looking forward to this function very much.

**Comment by efleurine** [comment]
Interesting I did not know you could do such thing.

One question, assuming a video has been fully buffered at this point and the user decided to replay it again. Will it go and re-download it again or would the player play it from the buffer?

thank you for your answer(s).

**Comment by cobarx** [comment]
It should play from the buffer. You can test this by turning off WiFi and seeing what happens.

**Comment by cobarx** [comment]
However, be aware that the player is not likely to keep the whole video in memory (unless it's very short). How much the player buffers varies depending on platform. On some, it's configurable.

**Comment by ghyzx** [comment]
Thank you for your attention.

I found something like this: if you play the same video over and over again, it will use the buffered data. But if you switch to another video, then come back again, the buffered data for the last video seems to have lost.

I did this at present: add a download button, manually download and store it locally, then you can use the local data (if it has been downloaded).

![11111](https://user-images.githubusercontent.com/5229158/42121448-e64a2960-7c61-11e8-8190-1b467780b591.png)
