### ISSUE TITLE
What the target property means in the onLoad callback ?

### ISSUE THREAD

**Issue by nmsdvid** [TheWidlarzGroup/react-native-video#1087]
I have two hls streaming videos. One is working and the other not, the only difference what I can see from the logs is that the target property values are different . Does somebody knows what these values stand for ? 

### Platform
iOS
Android

**Comment by cobarx** [comment]
It's not anything important, I believe it's an id that React Native creates to distinguish between different native modules.

If you're seeing the video not working on both iOS & ExoPlayer, chances are something's wrong with the video. iOS HLS support is extremely good and rarely has issues. Feel free to share a link to your video if you are able.

**Comment by cobarx** [comment]
Do you see any errors in the console on Xcode (or in onError)?

**Comment by nmsdvid** [comment]
@cobarx No I don't see any errors, its just not playing. I have tested various videos and it seems when the target property is 5 the video is not playing and if the value is higher then the video is playing.

**Comment by cobarx** [comment]
Can you provide an example video I can take a look at?

**Comment by nmsdvid** [comment]
Sure here they are, 
**720p (working)** 
http://woozle-hls-vod.dcp.adaptive.level3.net/WoozlepediaApp/TEST/asset.ism/manifest.m3u8?dcp_ver=aos4&videostream=720p_TEST.mp4:750000&audiostream=720p_TEST.mp4:20000 and **1080p (not working)**
http://woozle-hls-vod.dcp.adaptive.level3.net/WoozlepediaApp/TEST/asset.ism/manifest.m3u8?dcp_ver=aos4&videostream=1080p_TEST.mp4:750000&audiostream=1080p_TEST.mp4:20000
