### ISSUE TITLE
Expose allowsExternalPlayback

### ISSUE THREAD

**Issue by cancan101** [TheWidlarzGroup/react-native-video#109]
See [Apple Docs](https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVPlayer_Class/index.html#//apple_ref/occ/instp/AVPlayer/allowsExternalPlayback)

**Comment by PavelMikhadziuk** [comment]
I am not sure that here is right place for asking such question, but...we use in our project "react-native": "0.55.3","react-native-track-player": "^1.1.3", "react-native-video": "3.2.1" and "react-native-airplay-ios": "ssh://git@github.com:gazedash/react-native-airplay-ios.git#5affebb69853957da6dc6d034c1032130044575b". The main component uses `<Video />` for the slider. When user login in, he can play tracks from a remote streaming server as well as streaming to other devices via airplay. But we faced with several problems. One of them - when a user logs out during streaming to another device, the video from the slider starts to stream on remote device via airplay - like here https://www.reddit.com/r/apple/comments/7tmpyv/its_really_annoying_when_youre_playing_a_video/
I tried to use props `allowsExternalPlayback={false}` for `Video` component but it doesn't help.
@genglei01 @cancan101 @hellogerard FYI. Thank you in advance
