### ISSUE TITLE
DRM and security

### ISSUE THREAD

**Issue by sridhard** [TheWidlarzGroup/react-native-video#1093]
Hi,

1. Does react-native-video support playing of HLS encrypted content using clear key in ios and android?

2. Does react-native-video support DRM using widevine(Android) and Fairplay(ios)?

**Comment by cobarx** [comment]
Widevine is not currently supported. There is a PR to provide this, but I don't currently have an environment where I can test it. I'll look into getting it setup.

The other three are to the best of my knowledge unsupported. PRs or sample files / DRM servers that could be used for testing would be welcome.

**Comment by danielmarino24i** [comment]
For 2 I would suggest to check this PR: https://github.com/react-native-community/react-native-video/pull/1445

**Comment by Mahigoli** [comment]
Hi Does react-native-video support playing of HLS encrypted content using clear key in ios and android and TV?  And also does it support play in offline mode?

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/pull/1445

**Comment by expertguy** [comment]
`sdsddssdscsdcdsc
sdcsdc
sdcsd
csdcsc
dscscsc
scsdc
sdcs`
