### ISSUE TITLE
Sound from other app muted on iOS

### ISSUE THREAD

**Issue by Sin-** [TheWidlarzGroup/react-native-video#1095]
### Current behavior
The videos I play in my app have no sound and I want to be able to listen to music from another app (spotify, soundcloud etc.) while watching the video. So I set the muted prop to true on my video player and added the line `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];` to my AppDelegate.m
It works perfectly on Android, I can watch my video while listening to music from another app, but on iOS once the music is started, if I open my app back, the music stops...

### Reproduction steps
Play a video with the muted prop to true, start music from other app, return to the app playing the video

### Platform
iOS

If while the video plays I open the control center and start the music again the video freezes, I need to pause and play it to make it play again and the music stops again...

Anyone has an idea?
Thanks!

**Comment by cobarx** [comment]
Do you have the ignoreSilentSwitch prop set? That will override the value set in AppDelegate. I'm looking into how to rework this so everything can be controlled by react-native-video and customizing AppDelegate will no longer be required.

**Comment by flikQ** [comment]
Did you find a solution for this @cobarx @Sin- ? I took am suffering from having silent videos interfere with other audio and not releasing the sound back to those original apps using it.

**Comment by Sin-** [comment]
Yes! I wasn't looking in the right place.
In my app I have a video demonstrating an exercise without sound, the video is muted.
But I also have a timer to perform the exercices and a bell sound when the timer ends.
All my configuration for this lib was good, but I wrongly thought it was the culprit because music was playing until I pressed play on the video.
In fact, it was a misconfiguration of the react-native-sound library playing the bell sound that is also wrapping the AVAudioSession.
My best guess for your problem is to look for another lib in your projects that uses AVAudioSession, and if there is none, be sure to follow again the iOS configuration steps of this repo.

**Comment by njensen58** [comment]
Hit this issue this week using react-native-video with react-native-sound, same example too.  I have a muted workout video carousel playing with a ding after timed workouts, but I can either have background music or the ding, not both.

Curious on what you found about react-native-video and/or react-native-sound that helped you fix this?

I'm currently creating a new sound instance when the ding is triggered, and then releasing it onEnd.
I updated it today so that Sound.setCategory("Ambient") is set on mount, and then I set it to "Playback" for when I need the sound to play.  While this does allow music initially, it shuts off the music and doesn't play the sound when it's triggered.

[EDIT]: Found the issue
  react-native-sound's setCategory method takes an optional second argument, given 'true' it will 'mix with others'.  That was the issue, all I had to do with video was make that update to the AppDelegate file.

**Comment by Redge-Ballard** [comment]
@njensen58 any chance you could give me some pointers on how you were able to update the AppDelegate file? I've tried adding the framework to my binaries and adding the line referenced above, but always get a `Use of undeclared identifier 'AVAudioSession'` error. Any tips would be very appreciated.

**Comment by njensen58** [comment]
Hey @Redge-Ballard , I can definitely try :)

In my `ios/AppDelegate.m` file, I've added two things.  Disregard the firebase code as that is from another module I needed to add here as well.

At the top of the file I added:
```
#import "AppDelegate.h"
#import <Firebase.h> // firebase - disregard
#import <AVFoundation/AVFoundation.h> 
```

Then in the didFinishLaunchingWithOptions function:
```
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  InitializeFlipper(application);
#endif

  if ([FIRApp defaultApp] == nil) { // firebase - disregard
    [FIRApp configure];
  }

  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
... // other boiler plate code
```

I can remember if I had to run a `pod install` inside of my ios folder as well, but it doesn't hurt to try that if you haven't.  Then of course do a rebuild to have it all included. `npx react-native run-ios`

Hope that helps! If you are using any other modules along with react-native-video that trigger audio/video functionality, that could also be the issue.  It was for me.


[Edit]: I forgot to mention I also added this to my `Podfile` for basic video under the `target 'APP_NAME' do:

`pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'`

though revisiting this now I don't know if having that is necessary...  But it works, so I don't touch it.

**Comment by Redge-Ballard** [comment]
Wow I was obviously suffering from code fatigue because I was putting the import inside of an #ifdef block -_- Definitely not used to those. But your snippet made me realize it, so thank you so much!

**Comment by hanpanpan200** [comment]
I fixed the problem after following https://github.com/react-native-video/react-native-video#audio-mixing with the iOS native code updates.

The https://github.com/react-native-video/react-native-video#ignoresilentswitch doesn't work for my case.

**Comment by sanyamg99** [comment]
`_[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];_` 
is great for a background video. But what if you want to have a background video in one part of your app and a regular video playing elsewhere. If we set it in AppDelegate, it's a global setting for the whole app right? Could this be part of the props for the video component so we can control it a bit more?

**Comment by sanyamg99** [comment]
Does anyone has any solution for this?
Even after adding [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil]; in my AppDelegate.m file, music from other apps stops.
I have also tried to set ignoreSilentSwitch to both ignore and obey but nothing seems to work.
Any help will be very much appreciated

**Comment by AkramSyed002** [comment]
i face the same issue even i follow both the appDelgate and ignoreSilentSwitch={'ignore'}
                disableFocus={true}
