### ISSUE TITLE
TypeError:undefined is not an object

### ISSUE THREAD

**Issue by kannanseeni** [TheWidlarzGroup/react-native-video#1097]
TypeError:undefined is not an object(evaluating'_reactNative.NativeModules.UIManager.RCTVideo.Constants')

**Comment by malashkevich** [comment]
@kannanseeni make sure you added RCTVideo to Libraries in XCode and Added to Linked Frameworks and Libraries as well

**Comment by cobarx** [comment]
Yes this is something due to not having the link step completed.
