### ISSUE TITLE
Android ':react-native-video:compileDebugJavaWithJavac' Error

### ISSUE THREAD

**Issue by Jvheaney** [TheWidlarzGroup/react-native-video#1098]
### Current behavior
I run "react-native run-android" after installing the module and it fails to compile, bringing up the following error:

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':react-native-video:compileDebugJavaWithJavac'.
>> Compilation failed; see the compiler error output for details.

This obviously does not happen on iOS, and that version has been running with no issues.

### Reproduction steps
1. Install react-native-video
2. Run react-native run-android

### Expected behavior
The app should compile without this error.

### Platform
I am going to include both ExoPlayer and MediaPlayer since the problem is with Android as a whole.
* Android ExoPlayer
* Android MediaPlayer

I am new to React Native, so please excuse me if I did not include enough information. Let me know what is required and I will get it asap.

Thanks for the help.

**Comment by Jvheaney** [comment]
I removed the reference to Maven that was not local, then cleaned gradle. After doing that, I opened up Android Studio and did all of the suggested fixes when trying to gradle sync.

Magically it worked.

**Comment by h-dung-95** [comment]
How do you do it? @Jvheaney
