### ISSUE TITLE
The player cannot play the resource after call seek() method in onLoad callback

### ISSUE THREAD

**Issue by yurnery** [TheWidlarzGroup/react-native-video#1099]
### Current behavior
when the player is ready, it callback the onLoad(), in onLoad method i seek to  initial time, now the player can work well, but when i continue seek, the player cannot play any more, and i send onBuffer when i seek, only ios has this problem, android works well

### Reproduction steps
1. in the onLoad callback, use seek method, like `this.video.seek(3000);`
2. now the player can seek to the time and play, then slide the slider or any other way to call the seek method, the player cannot seek to the time and cannot play anymore, and the  onBuffer is fire when seek
 
### Expected behavior
whenever i seek to play, the player can work

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by yurnery** [comment]
addition to  the Reproduction steps:
on step 2: it may work in pre steps, but if you still call seek method for 5~6times, i will not work, the local resource is ok

**Comment by treemore** [comment]
i know the workround . setTimeout 3000

**Comment by yurnery** [comment]
@treemore you are right, i setTimeout(500) can work in some case, but some case cannot work; 3000 is too long for me, do u know the cause?

**Comment by yurnery** [comment]
i fix it by myself, just in the setSeek(info) method, comment the paused method, like this:
```
CMTime cmSeekTime = CMTimeMakeWithSeconds(seekTime, timeScale);
    CMTime current = item.currentTime;
    // TODO figure out a good tolerance level
    CMTime tolerance = CMTimeMake(1000, timeScale);
//    BOOL wasPaused = _paused;

    if (CMTimeCompare(current, cmSeekTime) != 0) {
//      if (!wasPaused) [_player pause];
      [_player seekToTime:cmSeekTime toleranceBefore:tolerance toleranceAfter:tolerance completionHandler:^(BOOL finished) {
//        if (!wasPaused) {
//          [self setPaused:false];
//        };
...

**Comment by xoapit** [comment]
Do you have any solutions for this case in android?
