### ISSUE TITLE
autoplay prop to control auto playing

### ISSUE THREAD

**Issue by johanneslumpe** [TheWidlarzGroup/react-native-video#11]
We should consider adding an `autoplay` property so the user can control whether the video should play as soon as it becomes ready or wait for user interaction/whatever.

**Comment by brentvatne** [comment]
:+1: closing this as we've covered it with the discussion in #14

**Comment by haofeng123** [comment]
how to control auto playing +1

**Comment by tinazheng** [comment]
uhh this discussion in #14 seems closed, and this is a much-requested feature. can we reopen this ticket please?
