### ISSUE TITLE
How a video/audio length is determined?

### ISSUE THREAD

**Issue by efleurine** [TheWidlarzGroup/react-native-video#1100]
I am able to play some audio/video files where the player would give me the full duration of the media. But for some other media files. It would return the duration as a negative number.

I am sort of new to media file spec world.

So my question is how the duration is determined. Is it like through metadata inside the media file or something else?

Thanks for your answer(s).

**Comment by cobarx** [comment]
It's completely determined by the underlying native player framework. If you can provide a few samples of ones that don't report the duration properly, I can see if it's possible to workaround the duration not being detected.

**Comment by efleurine** [comment]
@cobarx of course here they are.

Here the links for those audio files. (I could not upload them in the comments)

Thanks

[https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj](https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj)


[https://drive.google.com/uc?export=download&id=1VM9_umeyzJn0v1pRzR1BSm9y3IhZ3c0E](https://drive.google.com/uc?export=download&id=1VM9_umeyzJn0v1pRzR1BSm9y3IhZ3c0E)


[https://drive.google.com/uc?export=download&id=1bmvPOy2IVbkUROgm0dqiZry_miiL4OqI
](https://drive.google.com/uc?export=download&id=1bmvPOy2IVbkUROgm0dqiZry_miiL4OqI
)


[https://drive.google.com/uc?export=download&id=1V-c_WmanMA9i5BwfkmTs-605BQDsfyzC](https://drive.google.com/uc?export=download&id=1V-c_WmanMA9i5BwfkmTs-605BQDsfyzC)

**Comment by cobarx** [comment]
Hi @efleurine I'm filling getting a chance to look at this. Which platform are you having these duration issues on?

**Comment by namnhbap** [comment]
Hi @cobarx 
I'm getting wrong duration. Can you help me?
On iOS: duration: 9841.2666015625
But on android: duration: 9818.682
9841 is the right duration.
I'm using version 4.2.0

**Comment by Javimtib92** [comment]
I have the same issue, for me sometimes it return duration with this negative number -9223372036854776. There are a lot of opened issues related to the same topic

**Comment by smironescu** [comment]
seems that I have a similar problem... checking the `event.nativeEvent` playableDuration property is not equal as song duration and this is driving me a bit crazy as the method `onEnd` is not firing correctly at the end of the song...
Any suggestions/ideas? Should be possible to rewrite that `event.nativeEvent` playableDuration property? I know already the length of each song that is coming from my list...
