### ISSUE TITLE
determine live stream (hls m3u8) status (bad streaming speed or disconnecting)

### ISSUE THREAD

**Issue by bodaghialib4** [TheWidlarzGroup/react-native-video#1101]
In iOS and ExoPlayer (for android) I want to determine stream disconnecting and low quality of streaming caused by lower bandwidth.

Sometimes in the middle of our streaming because of bad internet bandwidth, our clients observing stream very bad and we want to determine this when it occur.
Is there any solution to determine  bad receiving stream or disconnecting stream?

**Comment by cobarx** [comment]
You can register for the onBuffer event, which should fire whenever the buffer gets fully exhausted. I don't know how well this works though.

**Comment by cobarx** [comment]
It should also fire once enough data is in the buffer that it can start playing again.

**Comment by bodaghialib4** [comment]
@cobarx 
thanks for your response, 
but we use race-native-video for online realtime video game and need to disable buffering and not allow users to pause/play.

**Comment by cobarx** [comment]
It's going to take a fair bit of work to get what you want, I would suggest poking around in the native code and seeing how it works. What you're describing is probably pretty complex.

If you don't want play / pause simply don't provide UI to toggle it.

**Comment by bodaghialib4** [comment]
ok,
thanks.
