### ISSUE TITLE
Videos loop only 3 times on iOS

### ISSUE THREAD

**Issue by Sin-** [TheWidlarzGroup/react-native-video#1102]
### Current behavior
I have videos that I want to make loop infinitely.
I set the repeat prop to true and it works perfectly on Android, the video loops infinitely.
But on iOS, the video stops after 3 loops and the player turns to a black screen.

### Reproduction steps
Try to loop a video more than 3 times on iOS

### Platform
* iOS

**Comment by barnesheaton** [comment]
I'm having the same issue. This worked for me though.

```
onEnd={() => {
    this.video.seek(0)
}}
```

And make sure repeat is set to false

`repeat={false}`

Hope this helps
