### ISSUE TITLE
MediaPlayer issue on older devices

### ISSUE THREAD

**Issue by PetarZo** [TheWidlarzGroup/react-native-video#1104]
### Current behavior
Describe what happens when you encounter this issue.
Screen a: Displays a video. If the user clicks the video, the video starts playing. At the end of the video, the app navigates to screen B, which displays a random video.
It works on my device(Galaxy S7) but not on the device of my friend(Galaxy S5 active).
When I run it on his device, the screen is black - no video.
Android Studio log gives me the following error:
```
07-02 16:29:53.884 2436-2881/? E/MediaPlayerService: WFD client is not created 
07-02 16:29:53.923 2436-8813/? E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
07-02 16:29:53.926 2436-8812/? E/MediaCodec: configure failed with err 0xffffec77, resetting...
07-02 16:29:53.941 7722-7734/com.strafenapp E/MediaPlayer: error (1, -5001)
07-02 16:29:53.952 7722-7722/com.strafenapp E/MediaPlayer: Error (1,-5001)
07-02 16:29:56.712 7722-7722/com.strafenapp E/MediaPlayer: isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
```

Screen A:
`import React from 'react';
import {
  Text,
  View,
  Button, Image, TouchableOpacity, TouchableWithoutFeedback, Modal, Dimensions, Platform } from 'react-native';
import Video from 'react-native-video';
import Orientation from 'react-native-orientation';

import {
  AdMobBanner,
  AdMobInterstitial,
  PublisherBanner,
  AdMobRewarded,
} from 'react-native-admob';

export default class Wheel extends React.Component {

  state= {
    isVideoPaused: undefined
  }

  onLayout(e) {
     const {width, height} = Dimensions.get('window')
     console.log(width, height)
   }

  static navigationOptions = {
    tabBarLabel: 'Rad',
    tabBarIcon: ({tintColor}) => (
      <Image

        source={require('../images/wheel.png')}
        style={{width: 22, height: 22, tintColor: tintColor}}>

      </Image>
    )
  }

  componentWillMount() {
    Orientation.lockToPortrait();

   }

   componentDidlMount() {
    Orientation.lockToPortrait();
    }

    generateRandomVideo() {
      this.setState({ isVideoPaused: true });
      const videos=[
        //Klassiker
        {file: 'dummyvideo_1', name: '...und Klappe'},
        {file: 'dummyvideo_2', name: 'Ausgerollt'},
        {file: 'dummyvideo_3', name: 'Nix WLAN'},
        {file: 'dummyvideo_4', name: 'Zucker, gebt mir Zucker'},
        {file: 'dummyvideo_5', name: 'No Money, baby'},
        {file: 'dummyvideo_6', name: 'Home, sweet Home'},

        //Sportstrafen
        {file: 'dummyvideo_7', name: 'Der Kasperl'},
        {file: 'dummyvideo_8', name: 'Weit-weit-weg'},
        {file: 'dummyvideo_9', name: 'Der Muskelmann'},
        {file: 'dummyvideo_10', name: 'Jump, Jump'},
        {file: 'dummyvideo_11', name: 'Das Brett'},
        {file: 'dummyvideo_12', name: 'Das brennt'},

        //Schulische Strafen
        {file: 'dummyvideo_13', name: 'Ich wars nicht...'},
        {file: 'dummyvideo_14', name: 'Der Einstein'},
        {file: 'dummyvideo_15', name: 'Ähh Schiller, nein Shakespeare'},
        {file: 'dummyvideo_16', name: 'Grumpydad = Grantiger Papa'},
        {file: 'dummyvideo_17', name: 'Was steht da?'},
        {file: 'dummyvideo_18', name: 'Bis zur Unendlichkeit'},

        //Eltern-Strafen
        {file: 'dummyvideo_19', name: 'James'},
        {file: 'dummyvideo_20', name: 'Tut das gut'},
        {file: 'dummyvideo_21', name: 'Klar kann der helfen'},
        {file: 'dummyvideo_22', name: 'Ich hoffe das ist nur Erde...?'},
        {file: 'dummyvideo_23', name: 'Mrs. Doubtfire'},
        {file: 'dummyvideo_24', name: 'Tischlein, deck dich'},

        //kreative Strafen
        {file: 'dummyvideo_25', name: 'Damals'},
        {file: 'dummyvideo_26', name: 'Wohin willst du denn hin'},
        {file: 'dummyvideo_27', name: 'Wo warst du?'},
        {file: 'dummyvideo_28', name: 'Blinde Kuh...bist du'},
        {file: 'dummyvideo_29', name: 'Echt so viele'},
        {file: 'dummyvideo_30', name: 'Die Stille'},
        {file: 'dummyvideo_31', name: 'Move like Jagger'},
        {file: 'dummyvideo_32', name: 'Der Ja-Sager'},
        {file: 'dummyvideo_33', name: 'Musical-Style'},
        {file: 'dummyvideo_34', name: 'Ich lieeebe Dich'},
        {file: 'dummyvideo_35', name: 'Der Shopping-Begleiter'},
        {file: 'dummyvideo_36', name: 'Der beste Dad der Welt'},
        {file: 'dummyvideo_36', name: 'Keine Strafe'},

      ];
      var random = Math.floor((Math.random() * videos.length) + 0);
      var video = (videos[random]);
      this.props.navigation.navigate('RandomVideo', { video })
    }

    playVideo() {
       this.player && this.player.seek(0);
       this.setState({ isVideoPaused: false   });
   }

//--------------RENDER--------------------------
  render() {

    // check, which platform is used and set admobID based on platform
    var admobID;
    var bannerSize;
    var deviceID;
      if (Platform.OS === 'ios'){
        admobID = 'ca-app-pub-3940256099942544/6300978111'
        bannerSize = 'smartBannerPortrait'
        deviceID= 'C720C061-AA46-49D7-B39F-5114FAE8B82C'
        console.log(admobID);
      } else {
        admobID = 'ca-app-pub-3940256099942544/6300978111'
        bannerSize = 'smartBanner'
        deviceID= 'EMULATOR'
        console.log(admobID);
      }

    const { navigate } = this.props.navigation;
    return (
      <View style={
      {

        flex: 1,
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'black'
      }
    }>

<TouchableWithoutFeedback
onPress={
    () => this.playVideo()
        }
>
<Video source={ { uri: 'gluecksrad' } }
   ref={(ref) => {
     this.player = ref
   }}
   rate={1.0}
   volume={1.0}
   muted={false}
   onClick
   resizeMode="contain"
   onClick={
       () => this.playVideo()
           }
   paused={this.state.isVideoPaused}
   onLoad={() => {
    this.setState({
      isVideoPaused: true
    });
  }}

   onEnd={
       () => this.generateRandomVideo()
           }
   style={styles.wheelStyle}

/>

</TouchableWithoutFeedback>
        <TouchableOpacity
          onPress={
              () => this.playVideo()
                  }
          >
          <Image
            style={{ width: 60, height: 60, marginBottom: 40,
              flexDirection: 'column',  resizeMode: 'contain'
            }}
            source={require('../images/play_button.png')}
            >
          </Image>
        </TouchableOpacity>

        <AdMobBanner
      adSize= {bannerSize}
      adUnitID= {admobID}
      testDevices={[AdMobBanner.simulatorId]}

    />

    </View>
  );
  }
}

const styles = {

  wheelStyle: {
    width: '100%',

    marginTop: 20,

    flexDirection: 'column',
    flex: 1

  },
};
`

Screen B:
`import React, { Component } from 'react';
import {  Text,
          View,
          Button,
          Image,
          FlatList,
          Platform,
          AppRegistry,
          ActivityIndicator,
          TouchableOpacity,
          Dimensions,
          NavigationActions
         } from 'react-native';

import { List, ListItem, SearchBar } from 'react-native-elements';
import Video from 'react-native-video';

import Orientation from 'react-native-orientation';

export default class RandomVideoScreen extends Component {

  constructor(props){
    super(props);
    console.log(Platform.OS);

    const { video } = this.props.navigation.state.params;
    console.log(video.name);

    this.state = {
        videoIOS: null,
      videoAndroid: video.file,
    };

    switch(video.name) {
      //Klassiker
      case '...und Klappe':
        this.state= {
          videoIOS: (require('../assets/Fernsehverbot.mp4')) || {},
          videoAndroid: 'fernsehverbot',

        };
        break;

        case 'Keine Strafe':
          this.state= {
            
            videoAndroid: 'keinestrafe',

          };
          break;

      case 'Ausgerollt':
        this.state= {
          videoIOS: (require('../assets/Fahrradverbot.mp4')) || {},
          videoAndroid: 'fahrradverbot',

        };
        break;

      case 'Nix WLAN':
        this.state= {
          videoIOS: (require('../assets/Smartphoneverbot.mp4')) || {},
          videoAndroid: 'smartphoneverbot',

        };
        break;

      case 'Zucker, gebt mir Zucker':
        this.state= {
          videoIOS: (require('../assets/Suessigkeiten.mp4')) || {},
          videoAndroid: 'suessigkeiten',

        };
        break;

      case 'No Money, baby':
        this.state= {
          videoIOS: (require('../assets/Taschengeldentzug.mp4')) || {},
          videoAndroid: 'taschengeldentzug',

        };
        break;

      case 'Home, sweet Home':
        this.state= {
          videoIOS: (require('../assets/Hausarrest.mp4')) || {},
          videoAndroid: 'hausarrest',

        };
        break;

        //Sportstrafen
      case 'Der Kasperl':
        this.state= {
          videoIOS: (require('../assets/Hampelmann.mp4')) || {},
          videoAndroid: 'hampelmann',

        };
        break;

      case 'Weit-weit-weg':
        this.state= {
          videoIOS: (require('../assets/Laufen.mp4')) || {},
          videoAndroid: 'laufen',

        };
        break;

      case 'Der Muskelmann':
        this.state= {
          videoIOS: (require('../assets/Liegestuetze.mp4')) || {},
          videoAndroid: 'liegestuetze',

        };
        break;

      case 'Jump, Jump':
        this.state= {
          videoIOS: (require('../assets/Seilspringen.mp4')) || {},
          videoAndroid: 'seilspringen',

        };
        break;

      case 'Das Brett':
        this.state= {
          videoIOS: (require('../assets/Situps.mp4')) || {},
          videoAndroid: 'situps',

        };
        break;

      case 'Das brennt':
        this.state= {
          videoIOS: (require('../assets/Kniebeuge.mp4')) || {},
          videoAndroid: 'kniebeuge',

        };
        break;

        //Schulische Strafen
      case 'Ich wars nicht...':
        this.state= {
          videoIOS: (require('../assets/Aufsatz.mp4')) || {},
          videoAndroid: 'aufsatz',

        };
        break;

      case 'Der Einstein':
        this.state= {
          videoIOS: (require('../assets/Rechnen.mp4')) || {},
          videoAndroid: 'rechnen',

        };
        break;

      case 'Ähh Schiller, nein Shakespeare':
        this.state= {
          videoIOS: (require('../assets/Gedicht.mp4')) || {},
          videoAndroid: 'gedicht',

        };
        break;

      case 'Grumpydad = Grantiger Papa':
        this.state= {
          videoIOS: (require('../assets/Vokabeln.mp4')) || {},
          videoAndroid: 'vokabeln',

        };
        break;

      case 'Was steht da?':
        this.state= {
          videoIOS: (require('../assets/Schreiben.mp4')) || {},
          videoAndroid: 'schreiben',

        };
        break;

      case 'Bis zur Unendlichkeit':
        this.state= {
          videoIOS: (require('../assets/Planeten.mp4')) || {},
          videoAndroid: 'planeten',

        };
        break;

        //Eltern-Strafen
      case 'James':
        this.state= {
          videoIOS: (require('../assets/James.mp4')) || {},
          videoAndroid: 'james',

        };
        break;

      case 'Tut das gut':
        this.state= {
          videoIOS: (require('../assets/Massage.mp4')) || {},
          videoAndroid: 'massage',

        };
        break;

      case 'Klar kann der helfen':
        this.state= {
          videoIOS: (require('../assets/Helfen.mp4')) || {},
          videoAndroid: 'helfen',

        };
        break;

      case 'Ich hoffe das ist nur Erde...?':
        this.state= {
          videoIOS: (require('../assets/Putzen.mp4')) || {},
          videoAndroid: 'putzen',

        };
        break;

      case 'Mrs. Doubtfire':
        this.state= {
          videoIOS: (require('../assets/Kuechendienst.mp4')) || {},
          videoAndroid: 'kuechendienst',

        };

      break;

      case 'Tischlein, deck dich':
        this.state= {
          videoIOS: (require('../assets/TischDecken.mp4')) || {},
          videoAndroid: 'tischdecken',

        };
        break;

        //kreative Strafen
      case 'Damals':
        this.state= {
          videoIOS: (require('../assets/Geschichten.mp4')) || {},
          videoAndroid: 'geschichten',

        };
        break;

      case 'Wohin willst du denn hin':
        this.state= {
          videoIOS: (require('../assets/Abstand.mp4')) || {},
          videoAndroid: 'abstand',

        };
        break;

      case 'Wo warst du?':
        this.state= {
          videoIOS: (require('../assets/WoWarst.mp4')) || {},
          videoAndroid: 'wowarst',

        };
        break;

      case 'Blinde Kuh...bist du':
        this.state= {
          videoIOS: (require('../assets/BlindeKuh.mp4')) || {},
          videoAndroid: 'blindekuh',

        };
        break;

      case 'Echt so viele':
        this.state= {
          videoIOS: (require('../assets/Zaehlen.mp4')) || {},
          videoAndroid: 'zaehlen',

        };
        break;

      case 'Die Stille':
        this.state= {
          videoIOS: (require('../assets/Stille.mp4')) || {},
          videoAndroid: 'stille',

        };
        break;

      case 'Move like Jagger':
        this.state= {
          videoIOS: (require('../assets/ElternTanzen.mp4')) || {},
          videoAndroid: 'elterntanzen',

        };
        break;

      case 'Der Ja-Sager':
        this.state= {
          videoIOS: (require('../assets/JaSager.mp4')) || {},
          videoAndroid: 'jasager',

        };
        break;

      case 'Musical-Style':
        this.state= {
          videoIOS: (require('../assets/Musical.mp4')) || {},
          videoAndroid: 'musical',

        };
        break;

      case 'Ich lieeebe Dich':
        this.state= {
          videoIOS: (require('../assets/LiebeDich.mp4')) || {},
          videoAndroid: 'liebedich',

        };
        break;

      case 'Der Shopping-Begleiter':
        this.state= {
          videoIOS: (require('../assets/Shopping.mp4')) || {},
          videoAndroid: 'shopping',

        };
        break;

      case 'Der beste Dad der Welt':
        this.state= {
          videoIOS: (require('../assets/BesterDad.mp4')) || {},
          videoAndroid: 'besterdad',

        };
        break;

      default:
      this.state= {
        videoIOS: (require('../assets/BesterDad.mp4')) || {},
        videoAndroid: 'besterdad',

      }
      break;
  }
}

  componentWillMount() {
     // The getOrientation method is async. It happens sometimes that
     // you need the orientation at the moment the JS runtime starts running on device.
     // `getInitialOrientation` returns directly because its a constant set at the
     // beginning of the JS runtime.

     const initial = Orientation.getInitialOrientation();
     if (initial === 'PORTRAIT') {
       Orientation.unlockAllOrientations();

     } else {
       // do something else
        Orientation.unlockAllOrientations();
     }
   }
   componentWillUnmount(){
     Orientation.lockToPortrait();
   }

  onLayout(e) {
     const {width, height} = Dimensions.get('window');
     console.log(width, height);

   }

   getIndex(){

   }

  render() {
    var videoAndroid = this.state.videoAndroid;
    var videoIOS = this.state.videoIOS;
    var resolveAssetSource = require('react-native/Libraries/Image/resolveAssetSource');

    console.log(videoIOS);
    console.log(videoAndroid);

    const {
      containerStyle,
      introTextContainerStyle,
      introTextStyle,
      introTextHighlightStyle,
      loginButtonsContainerStyle,
      backgroundVideo
    } = styles;

      if (Platform.OS === 'ios')

      return (
        <View style={ containerStyle }

          >
       <Video source={ resolveAssetSource(videoIOS) }
          ref={(ref) => {
            this.player = ref

          }}
          rate={1.0}
          volume={1.0}
          muted={false}
          resizeMode="contain"
          repeat={true}
          style={ backgroundVideo }

       />

      </View>

      );
else
return (
  <View style={ containerStyle }

    >
 <Video source={ { uri: videoAndroid } }
    ref={(ref) => {
      this.player = ref
    }}
    rate={1.0}
    volume={1.0}
    muted={false}
    resizeMode="contain"
    repeat={true}
    style={ backgroundVideo }

 />

</View>

);
    }
  }

  const styles = {
  containerStyle: {
    height: '100%',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black'
  },

  introTextContainerStyle: {
    borderColor: 'black',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '50%'
  },

  introTextStyle: {
    fontSize: 24,
    textAlign: 'center',
    lineHeight: 40
  },

  introTextHighlightStyle: {
    fontSize: 24,
    textAlign: 'center',
    fontWeight: '700',
    color:'gold'
  },

  loginButtonsContainerStyle: {
    borderColor: 'blue',
    borderWidth: 1,
    height: '50%',
    justifyContent: 'center',
    alignItems: 'center'
  },

  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,

    bottom: 0,
    right: 0,
  }
};
`

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen
Obviously I want the video to play.

### Platform
Which player are you experiencing the problem on:
I am on Android MediaPlayer -  I also tried it with ExpoPlayer tho, same effect.

Also in Android Studio I am getting the error: "Unable to find module with Gradle path ':react-native-video' (needed by module 'app'.)"

**Comment by cobarx** [comment]
Unfortunately, what is probably going on is that the older device doesn't have the necessary codecs available to play that video, that's why you're seeing the problem on both ExoPlayer and MediaPlayer.

This is a very common issue for people, so I've created #1105 to document it.

Your best bet is to re-encode the video with more compatible settings such as using the h.264 main profile instead of high, or dropping the level.
