### ISSUE TITLE
ReactVideoViewManager.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by xstable** [TheWidlarzGroup/react-native-video#1107]
On building debug or realease-package, the following Note is thrown: 

```
Note: /xxxxx/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by ghost** [comment]
Same issue for me.

**Comment by havinhthai** [comment]
Any update?

**Comment by TechAsif** [comment]
Same for me

**Comment by ouar** [comment]
Any update?

**Comment by ouar** [comment]
when i use gradle-6.7-all.zip to build the application, i have this issue :
react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
