### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by TomClarkson** [TheWidlarzGroup/react-native-video#111]
What am I doing wrong? I can't click RCTVideo.xcodeproj to open it per the instructions.

![link](https://cloud.githubusercontent.com/assets/2054503/11554857/8c1a3fc0-9a00-11e5-9308-1d79aff969c9.gif)

Also it would be helpful if the docs used RCTVideo instead of RNOverlay, I'm happy to send a gif of setting it up or record a video if that helps.

**Comment by jadsonlourenco** [comment]
You can just open the folder of this module "node_modules/react-native-video", and drag the xcode project inside your **Libraries**, like this: ![Demo](https://facebook.github.io/react-native/img/AddToLibraries.png)  
Then you need add the **libRCTVideo.a** to build, liking like this: ![Demo](https://facebook.github.io/react-native/img/AddToBuildPhases.png) Done!

Doc page: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content
PS: many modules for IOS need do this too.

**Comment by isair** [comment]
Closing as @jadsonlourenco has provided the correct solution.
