### ISSUE TITLE
overlap video in two screen

### ISSUE THREAD

**Issue by pppluto** [TheWidlarzGroup/react-native-video#1110]
### Current behavior
video player in previous route screen **covered** part of current route screen video player
when I **navigate A to B**, as the image below , left part belonged route A, and It covered another player which belonged route B,

![image](https://user-images.githubusercontent.com/13927313/42301975-df6ef4f8-804a-11e8-8915-7bf39ccdb7aa.png)

![default](https://user-images.githubusercontent.com/13927313/42305883-8837cd62-805f-11e8-9efb-651ab08ceb05.gif)

### Reproduction steps
1. playing a video in A route
2. navigate to B route
3. part of A's player still show in B's player and  covered B's player

### Expected behavior
player show not be covered by another player in different route

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

### env
"react-native-video": "^2.0.0",
"react-native": "^0.55.4",
"react-navigation": "1.5.11",

**Comment by pppluto** [comment]
https://github.com/react-community/react-native-maps/issues/453

**Comment by samsol38** [comment]
> @MrPluto ExoPlayer uses a SurfaceView by default which doesn't support layering views on top of each other. You should update to the latest react-native-video release and set the `useTextureView` prop to true.

Thanks. Its working. 😊☺️👍👏
