### ISSUE TITLE
loading long time 

### ISSUE THREAD

**Issue by xhw1993** [TheWidlarzGroup/react-native-video#1111]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by xhw1993** [comment]
I find issue , begin play loading long time , so somebody know how to resolve it , thank you

**Comment by cobarx** [comment]
We need more info about this problem to troubleshoot it. Please provide a link to the video that has the problem and which platform you're having the issue on.
