### ISSUE TITLE
error:could not install the app and errors in mainApplication.java file with this library .. 

### ISSUE THREAD

**Issue by Romandeep** [TheWidlarzGroup/react-native-video#1112]
### Current behavior
Describe what happens when you encounter this issue.
`Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-video'.
      > Could not resolve all dependencies for configuration ':react-native-video:_debugPublishCopy'.
         > Could not find com.android.support:support-annotations:27.0.0.
           Searched in the following locations:
               file:/F:/android sdk/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.pom               file:/F:/android sdk/sdk/extras/android/m2repository/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar               file:/C:/Users/roman/LiveProjects/App/android/sdk-manager/com/android/support/support-annotations/27.0.0/support-annotations-27.0.0.jar
           Required by:
               App:react-native-video:unspecified > com.google.android.exoplayer:extension-okhttp:2.7.3
               App:react-native-video:unspecified > com.google.android.exoplayer:exoplayer:2.7.3 > com.google.android.exoplayer:exoplayer-core:2.7.3
               App:react-native-video:unspecified > com.google.android.exoplayer:exoplayer:2.7.3 > com.google.android.exoplayer:exoplayer-dash:2.7.3
               App:react-native-video:unspecified > com.google.android.exoplayer:exoplayer:2.7.3 > com.google.android.exoplayer:exoplayer-hls:2.7.3
               App:react-native-video:unspecified > com.google.android.exoplayer:exoplayer:2.7.3 > com.google.android.exoplayer:exoplayer-smoothstreaming:2.7.3
               App:react-native-video:unspecified > com.google.android.exoplayer:exoplayer:2.7.3 > com.google.android.exoplayer:exoplayer-ui:2.7.3`

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by cobarx** [comment]
You need to reinstall the Android Support Repository in Android Studio so it updates to have the latest version.

**Comment by Romandeep** [comment]
i done this and resolved my issue. Thanks
