### ISSUE TITLE
Video Stuck on Infinite Buffer

### ISSUE THREAD

**Issue by pushkarhike** [TheWidlarzGroup/react-native-video#1114]
### Current behavior
I have a list of videos in a flat list and very frequently the videos get stuck on an infinite buffer. If one video fails to load all other videos also get stuck.

### Reproduction steps
No specific repro steps, but happens very frequently.

### Expected behavior
The videos should play. Also if one video gets stuck the others should play.

### Platform
Which player are you experiencing the problem on:

* Android ExoPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by treemore** [comment]
you can try this PR
https://github.com/react-native-community/react-native-video/pull/1113

**Comment by marlti7** [comment]
i face same problem

**Comment by NikolayDonev** [comment]
I have no issues with IOS, but once I pause the video it buffers forever.

**Comment by Balasnest** [comment]
Facing the same problem. Getting issue after playing the same video multiple times. It will play after reopened the app. Do we need to clear any resource from the app?

**Comment by naeemqaswar** [comment]
I'm also facing the same issue and its been a month but no clue why its happening. No tracking and no reproduction sequence, happening out of nowhere, just stuck at buffering. Tried changing video at run-time, also tried pause, play and replay but not luck. As Video Player is the most important component of my app, any help will be highly appreciated.

**Comment by SparseSpeculator** [comment]
I have the same issue on Android. Any news on this?

**Comment by faridsaud** [comment]
Same issue, any news here?

**Comment by naveenkumar-kv** [comment]
I can see this issue in IOS 16 and above, it's stuck in buffering indefinitely. It's working fine in android.
