### ISSUE TITLE
confusing documentation for "paused" prop

### ISSUE THREAD

**Issue by yanush** [TheWidlarzGroup/react-native-video#1116]
### Current behavior
seems like the docs for the paused props is incorrect:
"Controls whether the media is paused
false (default) - Pause the media
true - Don't pause the media"

### Expected behavior
should be:
"Controls whether the media is paused
false (default) - Don't pause the media
true - Pause the media"

**Comment by cobarx** [comment]
Thanks for catching this, I updated the docs.
