### ISSUE TITLE
react-native link doesn't link all the targets but only default target

### ISSUE THREAD

**Issue by waqarmobi** [TheWidlarzGroup/react-native-video#1118]
### Current behavior
react-native link command doesnt link all the targets and only the default ones. so running the same codebase on another target starts to give you this error
`undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants'`

### Reproduction steps
1) make a react native app.
2) make another target
3) npm i react-native-video
4) react-native link
5) run both targets

### Expected behavior
The link command should link the package/library with all the available targets so we dont have to manually do it. Right now i have to manually link the library.

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by cobarx** [comment]
What do you mean by creating other targets? I haven't done that before, can you give me a quick howto on how to set that up. Is this something works with other libraries?

**Comment by waqarmobi** [comment]
In xcode you can create multiple targets/schemes by going into the project and on the left side you can see Project and then Targets.  
![image](https://user-images.githubusercontent.com/40453350/42678600-09edb8a2-8688-11e8-8120-a7c4bf71fef3.png)

So when you have multiple targets already set up and then you link the react-native-video, it only gets linked with the first(default) target, plays video only on the first one and gives exceptions on the all other.

Other libraries which I've used for some icons gets linked with all targets.

The workaround I found is link the react-native-video with the default target and then duplicate that target to multiple and configure them separately.
![image](https://user-images.githubusercontent.com/40453350/42678842-d2e0fbca-8688-11e8-976e-fec02033c91e.png)

you can follow this link for what we're trying to implement. https://medium.com/@jacks205/adding-multiple-target-pipelines-for-react-native-apps-and-fastlane-circleci-deployment-pt-1-ae9590ae52f2

**Comment by cobarx** [comment]
Thanks for the heads up @xstable, I've updated the docs accordingly.
