### ISSUE TITLE
No support for mp3's

### ISSUE THREAD

**Issue by jasecoop** [TheWidlarzGroup/react-native-video#112]
One of the handy things about this tool is that it supports mp3's, though only if rendered via a url.

If you try to render an mp3 from locally you get the following error. 

I'm curious why this would work with url and not locally, any ideas?

![](https://s3.amazonaws.com/f.cl.ly/items/0e242g1v3g3t2R0F311s/Image%202015-12-09%20at%209.44.25%20pm.png)

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by anshul-kai** [comment]
Definitely finding this to be a problem here too. It does seem strange that mp3 files would play from a URL but not from local files.

+1

**Comment by zchwyng** [comment]
Closing this since it's outdated.
