### ISSUE TITLE
Cannot seek when playing a local .mp3 file

### ISSUE THREAD

**Issue by nishantWM** [TheWidlarzGroup/react-native-video#1123]
### Current behavior
Playing an .mp3 file, cannot seek anywhere. It always seeks to 0

### Reproduction steps
1.Set source for <Video> component with local mp3 file
2.Seek using slider by calling this.player.seek() function

### Expected behavior
Player should seek to the specified time

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by hoangtranuit** [comment]
I got same problem for some files.

**Comment by moneynguyen0o0** [comment]
+1

**Comment by atomictechdeveloper** [comment]
I got the same problem but interestingly not on all files.
This to me suggests it's how the mp3 was made that makes the difference.

Anyone found a particular mp3 encoding method that always works with seek?

**Comment by atomictechdeveloper** [comment]
The way I found to get around this was to convert it to m4a or to use Audacity to convert to a different mp3 bitrate format.

**Comment by onitzschke** [comment]
I have the same problem with mp3 stream, `seekableDuration ` = 108.

**Comment by ckaloger** [comment]
+1

**Comment by spyshower** [comment]
This happens to me with mp4.

**Comment by sbyaniv** [comment]
The same happens to me.
The player always jumps to 0 when using seek.
Happens with mp4, web and ogv formats.
Works with well with 3gp format :/
