### ISSUE TITLE
Error related to props source

### ISSUE THREAD

**Issue by shoki2shoki** [TheWidlarzGroup/react-native-video#1126]
I got error related to props source when I tried to display video footage in Flatlist. I think this is caused by url but I don't understand where to fix.
coulld you tell me the solution for this problem?
```
  renderItem = ({item}) => {
    return(
      <TouchableOpacity 
        key={item.name}
        style={{flex:1 , height: 300, backgroundColor: 'red', marginBottom: 10, borderRadius:10}} 
        onPress={() => console.log(item.url)}
      >
        <Video
          source={{uri: item.url}}
          ref={(ref) => {
            this.player = ref
          }}
          onError={(e) => console.log(e)}
          style={styles.backgroundVideo}
          resizeMode='contain'
        />
        <Text style={{ fontSize: 20, fontWeight: 'bold', marginBottom: 10 }}>{item.url}</Text>
        <View style={{ flexDirection: 'row' }}>
          <Text >{item.name}</Text>
        </View>
      </TouchableOpacity>
    );
  }
  render() {
    return (
      <View style={{width: '100%'}}>
        <FlatList
          data={this.props.items}
          renderItem={this.renderItem.bind(this)}
          keyExtractor={item => item.name}
          style={{marginHorizontal: 5}}
        />
      </View>
    );
  }
}
```

**Comment by shoki2shoki** [comment]
iOS error screen
![img_1896](https://user-images.githubusercontent.com/26036412/42687777-1d26ab86-86c4-11e8-82cf-5b86baab1ffe.PNG)

**Comment by shoki2shoki** [comment]
android
I didn't get any error but couldn't display video. 
![screenshot_20180713-172623](https://user-images.githubusercontent.com/26036412/42687804-2ccdfc1a-86c4-11e8-9671-d86e4dcb8c2e.jpg)
 error screen

**Comment by waqarmobi** [comment]
your `item.url` is null thats why it is giving this error. Check why your item.url is null?
may be try doing a conditional rendering. dont render this video component when the item.url is null?

something like ` {item.url ?   <Video
          source={{uri: item.url}}
          ref={(ref) => {
            this.player = ref
          }}
          onError={(e) => console.log(e)}
          style={styles.backgroundVideo}
          resizeMode='contain' :
         <Text title={'no url'} />
        />`

a very bad example but you can try testing it like that to figure out whats the problem.

**Comment by shoki2shoki** [comment]
Thank you for your reply. I wrote the code below because the code that you mentioned didn't work well. 
```
      { item.url ?
        <Video
          source={{uri: item.url}}
          ref={(ref) => {
            this.player = ref
          }}
          onError={(e) => console.log(e)}
          style={styles.backgroundVideo}
          resizeMode='contain'
        />
      : 'nothing'}
```
but I got the same error on both platform

**Comment by shoki2shoki** [comment]
this.props.items is below.
```
      items: [
        {name:'umetani', url: './518263874.224752.mp4'},
        {name:'tamotsu', url: './IMG_1410.m4v'},
        {name:'kozuka', url: './IMG_1525.m4v'}
      ]
```
I confirmed path is right. If I use `require` not `source` and I wrote the file name above directly not using variable, it displays video correctly. but we can't use variable together with `require`.

**Comment by shoki2shoki** [comment]
If I wrote like this, I got error. 
```source={{uri: './518263874.224752.mp4', type:'mp4'}}```
`source={{uri:` is intended for only URL?

**Comment by waqarmobi** [comment]
in the example the code is used like this . May be go through the example and see how it works.

`source={require('./broadchurch.mp4')}`

**Comment by shoki2shoki** [comment]
If I use `require` , it shows video correctly, but I want to use variable inside of `require()` .
this article said that we can't use variable inside of `require`. Is it correct?
https://stackoverflow.com/questions/47887697/require-must-have-a-single-string-literal-argument-react-native

**Comment by cobarx** [comment]
@shoki2shoki That's correct. You can't have variables inside require, so you need to load all the items you want to require at the time the app starts. What you can do though is:
```
// In one file, example: Videos.js:
export default {
  bigBuckBunny: require('./bbb.mp4'),
  sintel: require('./sintel.mp4')
}

// In another file:
import Videos from './Videos';

render() {
  const currVideo = Videos.bigBuckBunny;
  return <Video source={ currVideo } />;
}
```
or something similar.

Thanks for helping out @waqarmobi, super appreciate getting the info to diagnose what's going on!

Edit: fix formatting
