### ISSUE TITLE
Handling network connection change from wifi to mobile data and vice versa ?

### ISSUE THREAD

**Issue by waqarmobi** [TheWidlarzGroup/react-native-video#1127]
### Current behavior
The player stops working when the network connection is changed.

### Reproduction steps
Playing through a network and then changing the connection.

### Expected behavior
The expected behaviour would be to handle the connection change seemlessly without any audio delay.
### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

**Comment by cobarx** [comment]
I can look into this. My concern is that we shouldn't automatically keep playing if you lose your WiFi connection. If you don't realize you've gotten out of range of WiFi, you could end up eating up a huge percentage of your data plan. 

In my opinion, this needs to be configurable behavior so that the app can determine if there is a risk of excessive data usage and provide an alert or setting if the author feels it's appropriate.

We can keep playing what's in the buffer though until it's exhausted.

**Comment by waqarmobi** [comment]
Indeed, it should be a configurable behavior. I'm using this package only to play audio from network and currently the audio stops when the network is changed from wifi to mobile data. Ideally the network change should be seamless and the stream must be gapless.
Please let me know if there is a way we can continue playing the same instance of video object? 
right now I have to reset the URL to empty and then to the stream to let rn video to start the playback again.

**Comment by pribeh** [comment]
Anybody made any progress on this issue?

**Comment by rogerkerse** [comment]
It would be nice. I have the same issue. Not even onError is called when network is changed and video stops. I only get yellow warning message

**Comment by Hobahung** [comment]
Hey, my solution is listen network change from disconnect to connect. I replace videoUrl

`_netInfoSubscription: NetInfoSubscription | null = null;
  isConnected = true
  componentDidMount() {
    this._netInfoSubscription = NetInfo.addEventListener(state => {
      this.listenNetworkChange(state.isConnected);
    });
  }
  listenNetworkChange = (isConnected: any) => {
    const videoUrl = this.state.videoUrl
    if(this.isConnected === false && isConnected === true) {
      this.setState({videoUrl: videoUrl.replace('m3u8', '')}, () => {
        this.setState({videoUrl: videoUrl})
      })
    }
    this.isConnected = isConnected
  };
  componentWillUnmount() {
    this._netInfoSubscription && this._netInfoSubscription();
  }`

**Comment by 0xleeaki** [comment]
Hey, my solution is listen network change from disconnect to connect. I replace videoUrl to reload video and seek to current time.

```
_netInfoSubscription: NetInfoSubscription | null = null;
  isConnected = true
  componentDidMount() {
    this._netInfoSubscription = NetInfo.addEventListener(state => {
      this.listenNetworkChange(state.isConnected);
    });
  }
  listenNetworkChange = (isConnected: any) => {
    const videoUrl = this.state.videoUrl
    if(!this.isConnected && isConnected) {
      this.setState({videoUrl: videoUrl.replace('m3u8', '')}, () => {
        this.setState({videoUrl: videoUrl})
      })
    }
    this.isConnected = isConnected
  };
  componentWillUnmount() {
    this._netInfoSubscription && this._netInfoSubscription();
  }
```

You can convert to hook. Good luck 🗡️
