### ISSUE TITLE
Is there a way to play video in android virtual device?

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1129]
I try to use react-native-video in my project and have a question. 
Is there a way to play video in android virtual device?

### Reproduction steps
I just made really simple code in READ.ME, but I can't see video playing.

### Expected behavior
Describe what you wanted to happen
Play the video on android virtual device.

### Platform
Which player are you experiencing the problem on:
I develop my project on OS X, using android virtual device in android studio.

Thanks.

**Comment by cobarx** [comment]
Make sure you have a style with width & height set, otherwise the video will be too small to see. It does work on the virtual device.
