### ISSUE TITLE
how to set local file path dynamically on android?

### ISSUE THREAD

**Issue by saintfirewater** [TheWidlarzGroup/react-native-video#1132]
I bring file list enable to be changed from sd card or usb to the program. So I want to change 'local file path' on android platform.
But when I wrote code like this,
```
<Video
  source={require(this.state.resourceList[playIndex])}
/>
```

I don't use ExpoPlayer.
I got an error, **'require expect exactly 1 string literal arqument'**.

how can I make this properly? Thank you in advance.

**Comment by saeid85** [comment]
Hi,
You can't put variable inside "require". If you have to change local video dynamically, one solution is put all local videos in a separate file. import it & call videos from imported file in source prop.
If it is not clear let me know to send a sample.
