### ISSUE TITLE
Audio playback stops when back button is tapped on android

### ISSUE THREAD

**Issue by waqarmobi** [TheWidlarzGroup/react-native-video#1134]
### Current behavior
I've configured the playInBackground and it works fine in the background when I navigate away with the center button and app switcher but the audio stops when I use the back button. 

### Expected behavior
The expected behavior would be to keep playing the background audio when back button is tapped/pressed if its configured to do so.
### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

**Comment by fidelsam1992** [comment]
Any update for this issue ?

**Comment by 29hsaeed** [comment]
@fidelsam1992 
> Found a temporary solution to solve this. Insert the code below under your `MainActivity.java`
> 
> ```
> @Override
>     public void invokeDefaultOnBackPressed() {
>         moveTaskToBack(true);
>     }
> ```
Unfortunately this solution didn't work for me. 
Any other suggestion?
