### ISSUE TITLE
Android: onLoad and onEnd firing twice

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1136]
### Current behavior
Looks like `onLoad` and `onEnd` triggers are firing twice on Android. I'm using the Exoplayer implementation with the latest release of `3.0.0` but I've had this issue since version `1.0`.

### Reproduction steps
Play any file and change the source to notice the issue. I'm changing the source upon `onEnd` but I'm quite certain this will happen regardless.

### Expected behavior
Triggers should fire once per source.

### Platform
* Android ExoPlayer
* Android MediaPlayer - Haven't tested this recently as I moved to using ExoPlayer but I'm sure the problem is still happening.

**Comment by jayeshanandani** [comment]
I can reproduce the same behavior on latest version in android Expo player.

**Comment by ptgamr** [comment]
I got same problem... have to debounce my `onEnd` callback
