### ISSUE TITLE
Warning: Native component for "RCTVideo" does not exist [SOLVED]

### ISSUE THREAD

**Issue by eysi09** [TheWidlarzGroup/react-native-video#114]
Hey all!

I get the following error:

```
Warning: Native component for "RCTVideo" does not exist
```

when requiring the Video component like so:

``` javascript
var Video = require('react-native-video');
```

I've followed the install instructions exactly, tried uninstalling and installing again but to no avail. I'm using `react-native ^0.16.0-rc` and `react-native-video ^0.6.1` in my project.

**Comment by eysi09** [comment]
Ah, scratch that. I did screw up the install process. 

In step 3, instead of adding the `libRTCVideo.a` to the `Build Phases` of the main project I was adding it to the `Build Phases` of some subdirectory. Sorry about that.

**Comment by stereodenis** [comment]
@eysi09 close?

**Comment by toddmetheny** [comment]
I am seeing this same warning...would you mine posting what I need to include and where?
