### ISSUE TITLE
(ios)the same uri work in 3.0.0 but not work in 3.1.0

### ISSUE THREAD

**Issue by SHISME** [TheWidlarzGroup/react-native-video#1140]
### Current behavior

When i upgrade from 3.0.0 to 3.1.0, the video can not load with the same uri, in 3.0.0 the uri is ok,but in  3.1.0 it not work, have something to mind before upgrade?

### Platform
* iphoneX iOS 11.4

### Video sample

```
<Video
              source={{uri:audio_uri}}
              paused={!should_play}
              onLoad={this.on_load as any}
              onEnd={this.on_audio_end}
              onProgress={this.render_animate}
 />

```

**Comment by SHISME** [comment]
android also have this problem

**Comment by cobarx** [comment]
I will go ahead and test this to see if I can find any problems. Which uri are you using, I am guessing 3.1.0 has a bug for some files but not all.

**Comment by SHISME** [comment]
hi cobarx, I use local resource, in 3.0.0 need use absolute path，but in 3.1.0 ,need use relative path

**Comment by SHISME** [comment]
ok,i will make a simple example for you later

**Comment by SHISME** [comment]
In my project the ios directory structure like this
```
├── rnVideoTest
│   ├── AppDelegate.h
│   ├── AppDelegate.m
│   ├── Base.lproj
│   ├── Images.xcassets
│   ├── Info.plist
│   ├── main.m
│   └── static
│       └── test.mp3
```
in early version, we need use the MainBundlePath in the uri can make it work

```javascript
import React, {Component} from 'react';
import {
  StyleSheet,
  View,
} from 'react-native';
import Video from 'react-native-video';
import { MainBundlePath } from 'react-native-fs';


type Props = {};
export default class App extends Component<Props> {
  render() {
    console.warn('mainPath:', MainBundlePath);
    return (
      <View style={styles.container}>
        <Video
          source={{uri: MainBundlePath + '/static/test.mp3'}}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

```
But recently ,we update our version to 3.1.0, in 3.1.0, we use this relative path can work, if add `MainBundlePath` , it can't work

```
 <Video
          source={{uri: 'static/test.mp3'}}
        />
```

**Comment by SHISME** [comment]
i found `uri: 'static/test.mp3'` also work in 3.0.0, our team's member tell me they use `MainBundlePath ` because early version can't work with `uri: 'static/test.mp3`

**Comment by tibbus** [comment]
Same issue here, works on 3.0.0 but doesn't on 3.1.0 with a local uri

**Comment by pontusab** [comment]
For me it works with `3.0.1` in dev mode but not once released.

**Comment by cobarx** [comment]
I just released version 3.2.0 which contains PR #1162 by @ashnfb for this problem. Let us know if that fixes it or not.

**Comment by pontusab** [comment]
Thanks @cobarx and @ashnfb, this now works perfectly. Awesome work and thanks for a great library!

**Comment by mbret** [comment]
Quick fix, thanks a lot :)

**Comment by unicornRainbows** [comment]
YOU amazing HEROS!!

**Comment by light-of-king** [comment]
3.2.0 is good use,but 3.2.1 & 3.1.0 is not
