### ISSUE TITLE
[android] new pull request with android support not download on npm

### ISSUE THREAD

**Issue by gangstaJS** [TheWidlarzGroup/react-native-video#115]
When I do `install react-native-video --save` npm install old version plugin without support android.

**Comment by isair** [comment]
A new version isn't out yet. Meanwhile, you can add the following line to your dependencies instead:

``` js
"react-native-video": "git://github.com/brentvatne/react-native-video.git#f4c3e1"
```

**Comment by gangstaJS** [comment]
ok, tnx
