### ISSUE TITLE
iOS Video not displaying in release mode from bundled assets

### ISSUE THREAD

**Issue by ahmetabdi** [TheWidlarzGroup/react-native-video#1150]
### Current behavior
Video does not display in 'Release' Build Configuration' in iOS

### Reproduction steps

```
<Video style={styles.landingVideo} muted repeat resizeMode="cover" source={require('../../assets/videos/bg.mp4')} />
```

Build in iOS a choose 'Release' build configuration by changing the scheme cmd + shift + <

### Expected behavior
Video to display

### Platform
Which player are you experiencing the problem on:
* iOS

Package version 3.1.0
react-native 0.56.0

**Comment by younes0x53** [comment]
same issue on ios, works fine on Android !

**Comment by camelmasa** [comment]
I encountered same issue.

Then, I tried to use [this PR](https://github.com/react-native-community/react-native-video/pull/1113)'s branch on my project. It works 👍

**Comment by alexandrughinea** [comment]
Same issue here, `React Native 0.56` and `react-native-video 3.1.0`

**Comment by SHISME** [comment]
same issue here, `React Native 0.51.0` and `react-native-video 3.1.0`

**Comment by arpitjacob** [comment]
Yes same issue, `React Native 0.56 and react-native-video 3.1.0 `

**Comment by ashnfb** [comment]
I'll take a look at the bundling issue. Am fixing another issue in the code at the same time.


________________________________

**Comment by ahmetabdi** [comment]
@ashnfb 🙏 hero

**Comment by ahmetabdi** [comment]
Hope a new release comes soon looking forwards to it

**Comment by JesperLekland** [comment]
Fix did not work for me (v3.2.0)

**Comment by unicornRainbows** [comment]
Trying it out now!
Shot for this! really epic

**Comment by martinfrouin** [comment]
I still have this issue with react-native-video 3.2.1.
It's working well on my iOS simulator (debug & release) and on my iPad (debug)
but not on my iPad (Release)
Do you have a solution ?
