### ISSUE TITLE
Video freeze/stuck after switching to another video multiple times

### ISSUE THREAD

**Issue by orafoxinc** [TheWidlarzGroup/react-native-video#1151]
### Current behavior
I am trying to develop a video player app with a list of videos. The current behavior of app is, on click of any record play a video with given seek position and after click on another record switch a video in a player with given seek position. It works properly for the very first time with 3 to 4 videos but after that, it freezes in playing. And interestingly it will start playing that freeze video after 5 to 7 minutes. I have used streaming HLS URL with 2 to 4 hours duration. I have used react native ExoPlayer.

### Expected behavior
I want my app plays videos without freezing on switching another video.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by cobarx** [comment]
I want to make sure I replicate your scenario. So there is a list with a bunch of items each has a different video. When you click on one video, it seeks to the position from the previous video? Does the previous video pause?

**Comment by orafoxinc** [comment]
Actually, there is a list with a bunch of items each has a different video and its seek position. So whenever we click on any video it will play with its own given seek position. 
We have only one player for all list of video. So all video plays with that one player only.

**Comment by cobarx** [comment]
Ok, so you click on a thumbnail and it sets a new source for the video player.

One thing that might be the issue is you should not call seek until you receive the onLoad event for the new video. If that's not the problem, there must be some kind of bug that will require some investigation.

**Comment by orafoxinc** [comment]
Yes right, we seek video after onLoad method of a video. So it plays well for the first 3 to 4 video. but after that, it starts freezing.

**Comment by orafoxinc** [comment]
Okay, can you please provide me your linked message? It would be helpful for me.

**Comment by cobarx** [comment]
I had gotten a message from Kresimir on LinkedIn, I thought that was you. It's not appropriate for posting here.

**Comment by orafoxinc** [comment]
Ok let me talk to Kresimir. Thank you.

**Comment by marlti7** [comment]
i face the same problem

**Comment by cobarx** [comment]
I setup an example where I can cycle between 5 different videos and it seeks to a random position between 10 & 60 seconds after onLoad and it's working properly.

Can someone provide a code sample that easily reproduces this bug?

**Comment by cobarx** [comment]
Fairly certain the issue is what's described at https://google.github.io/ExoPlayer/faqs.html under "Why do some MPEG-TS files fail to play?"

We will need to set flags for videos that don't have IDR keyframes. This behavior will also need to be configurable since there are performance issues and other drawbacks when these flags are enabled.

**Comment by cobarx** [comment]
@marlti7 I've been working with @ervishu83's team to diagnose this. For them it appears to be an incorrectly configured HLS playlist.

Your problem sounds like it may be a video that's encoded without IDR keyframes. In that case, you either need to re-encode the video or pass special flags to ExoPlayer to workaround the issue. It's described here:
https://google.github.io/ExoPlayer/faqs.html#why-do-some-mpeg-ts-files-fail-to-play
I will post a branch for you to test with tomorrow and if it works, I'll figure out how to make it configurable and create a PR.

**Comment by marabej** [comment]
Hello

There are many streams with this problem. 
You can fix easily that for non-HLS streams with a small modification of the react-native-video source code.
In this file:
brentvatne/exoplayer/ReactExoplayerView.java
you can edit this method: 
```
private MediaSource buildMediaSource(Uri uri, String overrideExtension) {
.....
case C.TYPE_OTHER:                                                                                                          
  DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();                                        
 extractorsFactory.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);
    return new ExtractorMediaSource(uri, mediaDataSourceFactory, extractorsFactory, mainHandler, null);
```
This is very common problem with exo player and the developers should include
prop for ALLOW_NON_IDR_KEYFRAMES to overcome this.
Many streams have iFrames which are not IDR and often exoplayer doesn't plays them.

But I don't know how to pass DefaultExtractorsFactory() to HlsMediaSource to 
make the player work and for HLS streams, because if the HLS stream consists MPEG-TS,
we should set somehow  ALLOW_NON_IDR_KEYFRAMES and for it

If the developers decide to work for solution I can also give here for several days 2-3 streams. One correct, one which is not playable without this option ALLOW_NON_IDR_KEYFRAMES etc.

"defualt" - you can analyze streams with ffprobe

best regards

**Comment by bajaga** [comment]
On android I have a component/screen where i have imported the react-native-video component to play videos which works prefect. But after going back and forth(the component gets mounted/unmounted) to that screen and playing other videos it wont play anymore it just gets stuck on buffering(the function passed as buffering props is called only once with isBuffering true and onLoad is never triggered) no matter what video i try to play, I need to kill the app and run it again after which it works but if I repeat the mentioned steps it happens again.

**Comment by snackvideo-dkeith** [comment]
@bajaga Did you ever find a solution to your problem?

**Comment by marabej** [comment]
I discovered another problem with react-native-video.
Big problem with many devices. ExoPlayer / MediaPlayer plays low resolution 
standard definition files/streams mpeg-ts with awful quality.
For example it's easy to see the problem in channels with rounded logos.
The logo, texts are "aliased" with bad pixelisation. I checked it on amlogic devices, Smart TV-s etc.
The result is same. I checked with .ts file which captured from multicast stream. 
The same file plays perfectly in the default android video player, 
but with poor quality in react-native-video (ExoPlayer,MediaPlayer).
I thought, that this is a hardware problem but I was wrong. 
With react-native-video android with media player the problem is with the View which it uses.
This is buggy:
**https://github.com/yqritc/Android-ScalableVideoView**
Modification the source of brentvante/react for MediaPlayer to use standard VideoView solves the problem, but I don't know how to solve it with ExoPlayer
Brentvante should edit his code to not use ScllableVideoView, but standard VideoView insted. 
The difference is huge

**Comment by hoorsa** [comment]
+1
react-native-video@2.0.0 to 3.2.1
react-native-navigation@1.1.480
react-native@0.51
react@16.0.0-beta.5

**Comment by hoorsa** [comment]
Hi, (sorry for my English).
I think this issue is related to `playWhenReady`, because in `adb logcat` when the video freezes `playWhenReady=false` but should be `true`, so i added `player.setPlayWhenReady(true);`  to `private void videoLoaded()` before `eventEmitter.load(player.getDuration(), player.getCurrentPosition(), width, height,
                    getAudioTrackInfo(), getTextTrackInfo(), getVideoTrackInfo());` [https://github.com/react-native-community/react-native-video/blob/c30f246f5694452f4f081ff30ac4523dfd89f41d/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L633](https://github.com/react-native-community/react-native-video/blob/c30f246f5694452f4f081ff30ac4523dfd89f41d/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L633)

This change causes the video played after load but in my case this is not problem.
After 2 days i did not see any video freeze and i think this solved my problem.

Edit:
My problem was related to `requestAudioFocus()`.

**Comment by canyavall** [comment]
Could be a PR created from @hoorsa solution? It fixed one issue we had with HLS when switching between channels.

After changing channels (and sending the url to the exoplayer) 50 times (always 50....) the stream was freezing.

Thx for your solution @hoorsa

**Comment by canyavall** [comment]
Could be a PR created from @hoorsa solution? It fixed one issue we had with HLS when switching between channels.

After changing channels (and sending the url to the exoplayer) 50 times (always 50....) the stream was freezing.

Thx for your solution @hoorsa

**Comment by canyavall** [comment]
Could be a PR created from @hoorsa solution? It fixed one issue we had with HLS when switching between channels.

After changing channels (and sending the url to the exoplayer) 50 times (always 50....) the stream was freezing.

Thx for your solution @hoorsa

**Comment by canyavall** [comment]
Could be a PR created from @hoorsa solution? It fixed one issue we had with HLS when switching between channels.

After changing channels (and sending the url to the exoplayer) 50 times (always 50....) the stream was freezing.

Thx for your solution @hoorsa

**Comment by canyavall** [comment]
Could be a PR created from @hoorsa solution? It fixed one issue we had with HLS when switching between channels.

After changing channels (and sending the url to the exoplayer) 50 times (always 50....) the stream was freezing.

Thx for your solution @hoorsa

**Comment by anaelsh** [comment]
> Hi, (sorry for my English).
> I think this issue is related to `playWhenReady`, because in `adb logcat` when the video freezes `playWhenReady=false` but should be `true`, so i added `player.setPlayWhenReady(true);` to `private void videoLoaded()` before `eventEmitter.load(player.getDuration(), player.getCurrentPosition(), width, height, getAudioTrackInfo(), getTextTrackInfo(), getVideoTrackInfo());`
> 
> https://github.com/react-native-community/react-native-video/blob/c30f246f5694452f4f081ff30ac4523dfd89f41d/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L633
> 
> This change causes the video played after load but in my case this is not problem.
> After 2 days i did not see any video freeze and i think this solved my problem.
> 
> Edit:
> My problem was related to `requestAudioFocus()`.

Thank you ! This solved our freezing video issue

**Comment by paddy57** [comment]
> https://google.github.io/ExoPlayer/faqs.html

Hello, how can i acheive this?
I'm using react-native-video 3.0.0
when i my video loads its freeze for a moment after 1 sec and then start normally
How can i know my mp4 links had IDR Keyframes or not ?

**Comment by paddy57** [comment]
> Hi, (sorry for my English).
> I think this issue is related to `playWhenReady`, because in `adb logcat` when the video freezes `playWhenReady=false` but should be `true`, so i added `player.setPlayWhenReady(true);` to `private void videoLoaded()` before `eventEmitter.load(player.getDuration(), player.getCurrentPosition(), width, height, getAudioTrackInfo(), getTextTrackInfo(), getVideoTrackInfo());`
> 
> https://github.com/react-native-community/react-native-video/blob/c30f246f5694452f4f081ff30ac4523dfd89f41d/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L633
> 
> This change causes the video played after load but in my case this is not problem.
> After 2 days i did not see any video freeze and i think this solved my problem.
> 
> Edit:
> My problem was related to `requestAudioFocus()`.

HII @hoorsa I'm having same problem, How you resolved it ?
My video lags a frame then plays smooth if i use video which has audio,
but if i used the video which does not have audio then it does not lag. can you help me with that?
I'm using react-native-video@3.0.0
react-native 0.55.4

**Comment by GrinchakAndrew** [comment]
> Hello
> 
> There are many streams with this problem.
> You can fix easily that for non-HLS streams with a small modification of the react-native-video source code.
> In this file:
> brentvatne/exoplayer/ReactExoplayerView.java
> you can edit this method:
> 
> ```
> private MediaSource buildMediaSource(Uri uri, String overrideExtension) {
> .....
> case C.TYPE_OTHER:                                                                                                          
>   DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();                                        
>  extractorsFactory.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);
>     return new ExtractorMediaSource(uri, mediaDataSourceFactory, extractorsFactory, mainHandler, null);
> ```
> 
> This is very common problem with exo player and the developers should include
> prop for ALLOW_NON_IDR_KEYFRAMES to overcome this.
> Many streams have iFrames which are not IDR and often exoplayer doesn't plays them.
> 
> But I don't know how to pass DefaultExtractorsFactory() to HlsMediaSource to
> make the player work and for HLS streams, because if the HLS stream consists MPEG-TS,
> we should set somehow ALLOW_NON_IDR_KEYFRAMES and for it
> 
> If the developers decide to work for solution I can also give here for several days 2-3 streams. One correct, one which is not playable without this option ALLOW_NON_IDR_KEYFRAMES etc.
> 
> "defualt" - you can analyze streams with ffprobe
> 
> best regards

Hello, actually, this solution breeds reference errors for `DefaultTsPayloadReaderFactory`, and it is not clear how to import this, as even trying to import it as extractor class, the build fails. So, I would highly appreciate the working code solution here, or an example of the flag passed down as a prop to Video, IF the PR discussed about did come to fruition. Thank you for any input.

**Comment by caijiami** [comment]
Is there a good solution to the same problem @defualt @ervishu83 @cobarx @GrinchakAndrew @bajaga

**Comment by KishoreBarik** [comment]
Experiencing similar issue in android. The video getting stuck in a frame after swiping to another video and coming back.
The audio keeps playing and seekbar is moving but not the video frame.

Also I can see controls for both video at once for sometime.

https://user-images.githubusercontent.com/13726932/159647019-5e9d8801-1975-48aa-9300-5ab0f63ad722.mp4

**Comment by koolll** [comment]
Is that any solution ? it been almost 2 year since this bug occur

**Comment by ScreamZ** [comment]
Interest in too

**Comment by raghvendra007** [comment]
Is there any solution for this in IOS

**Comment by tanmoy-desuntech** [comment]
I have a screen which plays online streaming of different channels. But, when it starts playing whole screen freezes and if I want to change channel I keep tapping on different channels, nothing occurs! Even, there is an overlay over the video player, which has a custom play pause button. That does not even respond properly as screen is freezed. What is possible solution?

**Comment by pgpankajbigstep** [comment]
> Experiencing similar issue in android. The video getting stuck in a frame after swiping to another video and coming back. The audio keeps playing and seekbar is moving but not the video frame.
> 
> Also I can see controls for both video at once for sometime.

Did you get any solution for this issue ?
