### ISSUE TITLE
Android: TextTrack selector issue. TextTrack not going away after turning them on and then off.

### ISSUE THREAD

**Issue by aecorredor** [TheWidlarzGroup/react-native-video#1154]
### Current behavior
I'm using the the TextTrack selector functionality that was added not so long ago. It's working fine in iOS, but on Android, I select the one I want, but then if I try to turn it off (by passing null to the selectedTextTrack prop) the track that was previously selected doesn't go away.

### Reproduction steps
1. Play a video on Android that has text tracks.
2. Select a text track.
3. Try removing the text track by passing null to the selectedTextTrack prop.

### Expected behavior
The previously selected text track should go away.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

**Comment by shlokamin** [comment]
If you're just trying to turn the captions off, try setting the selectedTextTrack type to 'disabled':

selectedTextTrack={{
  type: "disabled",
  value: "should_not_matter"
}}

This is what I do in my app through a toggle button.

**Comment by aecorredor** [comment]
@shlokamin that worked, thanks man!

**Comment by alanlanglois** [comment]
Got a similar issue on iOS. 
When I remove the subtitles using the above method, the last subtitle stays on screen. 
If I remove it when there is no subtitles it's fine. 
Also if I disable subtitles, go fullscreen and come back the subtiles are gone (as it should).
