### ISSUE TITLE
[android][windows] When try run example from rnv repo on windows 7, see black rectangle

### ISSUE THREAD

**Issue by gangstaJS** [TheWidlarzGroup/react-native-video#116]
When try run example from rnv repo on windows 7, see black rectangle
http://take.ms/wF2YI

**Comment by gangstaJS** [comment]
Maybe it's due to the fact that the module `buferutil` not install correct?

**Comment by aboutqx** [comment]
Had the same problem in windows 8.1,really want to know why,but how can we debug this?Use the "adb logcat"?

**Comment by aboutqx** [comment]
Well，I found that video can't play in a simulator like Genymotion or avd.When testing in a real device the video plays.
