### ISSUE TITLE
React native starter not working

### ISSUE THREAD

**Issue by Amalnraghavan** [TheWidlarzGroup/react-native-video#1168]
### Current behavior
When I installed packages like react-native-video,then when I start project using npm start,  I was stucked with starting packager... when I consulted with somebody, they suggested that it may be due to missing in dependency. How I can solve the issue

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by cobarx** [comment]
We'd need to see the logs from the packager. 

Did this problem only start when you added react-native-video? If not, I would start from a simple project with no dependencies and add them one at a time to figure out which package is causing the problem.
