### ISSUE TITLE
Adaptive streaming is not working in Android

### ISSUE THREAD

**Issue by bsjaffer** [TheWidlarzGroup/react-native-video#1171]
Hi , 

We are trying to play video from media service with the format of m3u8, video is playing fine but its not adaptive in android. Is there any specific settings i need to turn on to make it adaptive or how to find in which resolution video is playing ? 

https://disprzmsindia.streaming.mediaservices.windows.net/426f4d5d-44d9-4355-96de-76fcf56d65b9/c27f1f4d-f88c-4761-8b59-56b3dd97.ism/manifest(format=m3u8-aapl).m3u8

Please let me know soon as its happening in production app.

**Comment by cobarx** [comment]
@bsjaffer Are you using ExoPlayer? I checked the ExoPlayer code and it looks like it's setup by default to do adaptive track selection. I also checked the playlist and all 6 video tracks are being detected properly.

I don't have much experience with doing adaptive streaming, so you will need to do some investigation in the ExoPlayer code to figure out what's going on. IIRC, the demo ExoPlayer app (https://google.github.io/ExoPlayer/demo-application.html) has code to display the resolution. It would be very welcome to add that capability to react-native-video as well.

**Comment by cobarx** [comment]
As far as checking to see which track is playing, take a look at:
https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L524

You could create a similar getVideoTrackInfo info method and query the mapped tracks and see if there is any info to indicate the currently selected track. You'd need some way to trigger it, I'd imagine there is an ExoPlayer event when the track changes but am not 100% sure about that.

**Comment by bsjaffer** [comment]
@cobarx  my bad, I didnt make the configuration properly for ExoPlayer. It worked for me now in android. Is there a way to play video's adaptively in IOS also ?

**Comment by cobarx** [comment]
It should work automatically on iOS AFAIK.

**Comment by aecorredor** [comment]
@bsjaffer what did you have to fix for the ExoPlayer configuration? I am running into the same issue, the player can't play Adaptive Bitrate Content, it just stalls since the beginning.

**Comment by mrdja026** [comment]
+1, i am using 2.3.1 (ExoPlayer not MediaPlayer) version, and in the documentation of react-native-video there is no mentioning of adaptive streaming config or i just need glasses. Maybe i should mention the main i idea i want to accomplish, i want somehow parse the manifest data(HLS, or DASH) and offer to the user all video tracks available (all resolutions) so if he does not like adaptive, he can chose, but i cannot find the moment when the manifest is being parsed, or i am on the wrong track, any ideas?

Tnx

**Comment by Ashwin-Mothilal** [comment]
@aecorredor It didn't work. Seems like the player doesn't it yet.

**Comment by sangupandi** [comment]
> @cobarx my bad, I didnt make the configuration properly for ExoPlayer. It worked for me now in android. Is there a way to play video's adaptively in IOS also ?

Can you please explain the config for adaptive bit streaming.

**Comment by alikazemkhanloo** [comment]
@cobarx so we cannot change the resolution manually in iOS, right?

**Comment by michaelmaitland** [comment]
@cobarx any chance you could share config for ios?
