### ISSUE TITLE
[iOS] NSURLErrorDomain -1008 and -1009

### ISSUE THREAD

**Issue by zachrnolan** [TheWidlarzGroup/react-native-video#1177]
### Current behavior
Our users are occasionally getting errors during remote video playback:

```
{"error":{"code":-1008,"domain":"NSURLErrorDomain"},"target":9623}
{"error":{"code":-1009,"domain":"NSURLErrorDomain"},"target":1954} 
```

It looks like these errors are coming directly from iOS:
```
NSURLErrorResourceUnavailable =         -1008,
NSURLErrorNotConnectedToInternet =      -1009,
```

Error -1008 seems to be triggered when there is a network "delay": https://www.buzztouch.com/forum/thread.php?tid=F8002ED5B6297062FE5A30C&currentPage=11

### Reproduction steps
Cannot consistantely reproduce

### Expected behavior
Most of the time, the users networks seem to be working fine when they receive this error.

Is there a way for this library to use a longer timeout, so these errors are triggered less often?

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by ShimShamSam** [comment]
This is a huge issue and turning "useWebkit" off is not an option for us. Re-implementing the functionality with WebView is a bit of a pain.
