### ISSUE TITLE
Video quality selector

### ISSUE THREAD

**Issue by sridhard** [TheWidlarzGroup/react-native-video#1180]
Query:

Whether react-native-video has support for the video track selection? I want to implement video quality selection feature like youtube. How to implement this feature

**Comment by sridhard** [comment]
@cobarx I have submitted pull request for youtube like video track selection. Please review

**Comment by cobarx** [comment]
Going to close this since we are addressing it in the PR.

**Comment by santanu07** [comment]
can you give me a full example code of video quality selector?

**Comment by MBakhtiyor** [comment]
> can you give me a full example code of video quality selector?

I need it too. Give me please too. I need change videoTrack in iOS. Is there any variant?

**Comment by VaibhavValere** [comment]
@sridhard @cobarx Has this functionality been integrated into the released version?
