### ISSUE TITLE
HLS adaptive bitrate video not playing on Android (ExoPlayer)

### ISSUE THREAD

**Issue by aecorredor** [TheWidlarzGroup/react-native-video#1181]
### Current behavior
I have an HLS ABR video and it's not playing on Android ExoPlayer. The player just stays in the initial buffering state and I see a black screen.

### Reproduction steps
Play an HLS video with adaptive bitrate on Android ExoPlayer.

### Expected behavior
The video plays normally.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video File Example
http://video.ocean.com/abr/_definst_/smil:v2/video/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/36D64B7D46B8498494460EAB891AAFC1/93C69734057745FCAD595BD34902B10F.v2.eng.smil/playlist.m3u8

**Comment by aecorredor** [comment]
Thanks for testing it out @cobarx. I'll go ahead and open an issue over there then.

**Comment by luisnaranjo733** [comment]
@aecorredor did you ever post an issue? I searched their github and couldn't find anything
