### ISSUE TITLE
Android kills video when in the background, causes app to crash when restarting.

### ISSUE THREAD

**Issue by Alanz2223** [TheWidlarzGroup/react-native-video#1184]
### Current behavior
Hello I have a video component and use it to stream videos about 3 mins in length although it varies. I have the playInbackground prop set to true. The issue stems whenever the app is placed in the background and then I try to do some action like opening another app such as the browser or messages. The video will play for a bit and then it suddenly stops and whenever I try to navigate to my app again it goes into this loop where it just keeps switching blank screens until it finally crashes with "Unfortunately your app has crashed". 

### Reproduction steps
Have the following video component 
`<Video 
                  ref="audioElement"
                  source={{uri: this.state.quality.url}}
                  style={Styles.video}
                  playInBackground={true}
                  bufferConfig={{
                    minBufferMs: 4000,
                    maxBufferMs: 10000,
                    bufferForPlaybackMs: 2500,
                    bufferForPlaybackAfterRebufferMs: 4000
                  }}
                  progressInterval={2} 
                  paused={this.state.paused}
                  //poster={currentVid.thumbnail_url}
                  onProgress={(val) => this.setTime(val)}
                  onBuffer={(val) => this.onBuffer(val)} 
                  onLoad={(val) => this.setDuration(val)}
                  onLoadStart={(val) => this.onLoadStart(val)}
                  onError={(e) => {console.log(e)}}    
                />`

Play some video and then navigate to do something else.

**it should be noted I also have react-native-track-player that uses exoplayer as well but whenever the app is active, nothing seems to be conflicting and all the components work fine.

I have looked at the app through the profiler and it consumes on average about 150 MB of memory.

### Expected behavior
Just play the video without crashing or gracefully pause it without crashing the app on restart.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
Any mp4 video.

Here is the logcat message that whenever the video is killed
`08-11 17:28:03.426   512   512 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...`

The logcat message whenever the app crashes on restart

`IllegalStateException (@ContextImpl:startServiceCommon:1538) {main}`

**Comment by mmuil** [comment]
@Alanz2223 Hey! Have you solved this? Could this be related? #1211

**Comment by Alanz2223** [comment]
@mmuil unfortunately I have not been able to resolve this and yes I have not had a chance to test your issue but I think they are definitely related. The OS is trying to reclaim memory/save power and kills the video. I am not an Android dev but creating the video as some sort of prioritized service similar to how the audio players do it, could be a solution.
