### ISSUE TITLE
AVFoundationErrorDomain with HTTPS link

### ISSUE THREAD

**Issue by hans0low** [TheWidlarzGroup/react-native-video#1188]
### Current behavior
Nothing appears but the poster and an error pops up on console:
error: 
code: -11850
domain:"AVFoundationErrorDomain"

### Reproduction steps
Normal <Video> component using link shared.

### Platform
Which player are you experiencing the problem on:
* iOS

### My Code
```
<Video
                                source={{uri: video.link}}
                                ref={(ref) => {
                                    this.player = ref
                                }}
                                poster={'https://baconmockup.com/300/200/'}
                                onError={(err) => console.log(err)}
                                resize='contain'
                                style={styles.video}
                            />
```

**Comment by hans0low** [comment]
Found issue similar to mine on #446. I apologize for repost.

**Comment by JMV2112** [comment]
How did you get this to work? I'm still having this issue with youtube links.

**Comment by alphabikram** [comment]
I am having the same issue, can somebody tell me how to fix this issue ?

@hans0low how did you fix this ?
Please help.

**Comment by hans0low** [comment]
For me it was how i was getting the video from the backend.

I wasn't getting the byte range of the video from azure blob storage and setting the correct headers for the player to be able to read the video correctly.

```
// get byte range
const range = req.headers.range;

// if byte range exists
if (range) {
    // chop the video by the range
    const parts = range.replace(/bytes=/, '').split('-');
    const start = parseInt(parts[0], 10);
    const end = parts[1] ? parseInt(parts[1], 10) : result.contentLength - 1;
    const chunksize = (end - start) + 1;
    res.writeHead(206, {
        'Content-Range': `bytes ${start}-${end}/${result.contentLength}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunksize,
        'Content-Type': 'video/mp4',
    });
    blobService.createReadStream(blobContainer, blobName, { 'rangeStart': start, 'rangeEnd': end }).pipe(res);
} 
else {
    // set headers to mime type
    res.writeHead(200, { 'Content-Length': result.contentLength, 'Content-Type': `video/${blobName.split('.')[1]}` });
                    
    // pipe stream
    blobService.createReadStream(blobContainer, blobName).pipe(res);
}
```

We choose to do it manually with this code snippet but i believe you can have it done by azure using the Azure Media Service SDK. That is if you go through azure blob storage. I did not try using youtube links so I am not sure what the error might be.

**Comment by alphabikram** [comment]
@hans0low I think I got a issue which is little different:
This is my issue:

> I am using the streaming url from CloudFront.

Sample url:
https://d14nt81hc5bide.cloudfront.net/qyYj1PcUkYg2ALDfzAdhZAmb

On android , it is working fine but in iOS it says:
domain = AVFoundationErrorDomain , code = -11828

From apple doc the error code 11828 is AVErrorFileFormatNotRecognized.
The media could not be opened because it is not in a recognized format.


Thanks for your kind reply.

**Comment by SlakkedisStudio** [comment]
> @hans0low I think I got a issue which is little different:
> This is my issue:
> 
> > I am using the streaming url from CloudFront.
> 
> Sample url:
> https://d14nt81hc5bide.cloudfront.net/qyYj1PcUkYg2ALDfzAdhZAmb
> 
> On android , it is working fine but in iOS it says:
> domain = AVFoundationErrorDomain , code = -11828
> 
> From apple doc the error code 11828 is AVErrorFileFormatNotRecognized.
> The media could not be opened because it is not in a recognized format.
> 
> Thanks for your kind reply.

We have an access token being passed as a query string and we're running into the same issue.

e.g. 
```domain.com/video1.mp4?access_token=123jlkasdkljlkj1.12asdlkfja.1asdklfj```

Did you manage to get a solution for your problem @octopusbaba ?

Thanks! Looking forward to your reply.

**Comment by CHaNGeTe** [comment]
Does your url return content-type header?

**Comment by Millne** [comment]
I also encountered the same problem
Sample url:
https://taomh.cn:8443/com-reader-backmanager/static/ttt/stream.mpd

On android , it is working fine but in iOS it says:
domain = AVFoundationErrorDomain , code = -11828

**Comment by CHaNGeTe** [comment]
I see your server is returning ContentType application/octet-stream;charset=UTF-8
Can you try making it return application/dash+xml
@Millne

**Comment by minhchienwikipedia** [comment]
I facing the same issue with youtube URL `https://www.youtube.com/watch?v=r1Fx0tqK5Z4` , how can I resolve this issue?

**Comment by CHaNGeTe** [comment]
There is no youtube integration @minhchienwikipedia

**Comment by CHaNGeTe** [comment]
Maybe it suits you more this lib: https://github.com/inProgress-team/react-native-youtube
