### ISSUE TITLE
Control audio from notifications

### ISSUE THREAD

**Issue by oakcreations** [TheWidlarzGroup/react-native-video#1189]
Is it possible to control audio in background through notifications? (Androind & IOS)

example:
<img src="https://developers.google.com/cast/images/a/sender-control-notification1.png">

**Comment by cobarx** [comment]
It's not supported currently, but would be a great feature to have. I believe react-native-track-player already has this implemented, so you could try that or port it over to react-native-video.

**Comment by moonstruck** [comment]
You may try [https://github.com/tanguyantoine/react-native-music-control](https://github.com/tanguyantoine/react-native-music-control )

**Comment by punyaslokdutta** [comment]
> You may try https://github.com/tanguyantoine/react-native-music-control

It can be integrated with react-native-video?
