### ISSUE TITLE
When muted={true} the fullscreen volume control won't unmute

### ISSUE THREAD

**Issue by kennym** [TheWidlarzGroup/react-native-video#1192]
### Current behavior
When I set `muted={true}` and try to unmute in the fullscreen player the sound won't unmute.

### Expected behavior
I should hear sound after unmuting from the fullscreen controls.

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by lklepner** [comment]
Changing the volume setting to 0.0 rather than using `muted={true}` to achieve muting in advance of video playback has the same impact. The audio controls in the fullscreen view cannot be used to unmute the audio.

**Comment by guliash** [comment]
https://github.com/guliash/react-native-video-example/tree/muted_fullscreen
Demo.

**Comment by guoguozhang** [comment]
When muted={true}  and controls={true} the muted btn not work in iOS ? Have nothing to do with fullscreen.  Has no one solved the problem？

**Comment by snamstorm** [comment]
Also having this issue - when `muted={true}`, pressing unmute on the controls doesn't unmute

If `muted={false}` - sound works fine when pressing play on a video

**Comment by CHaNGeTe** [comment]
Try this PR
https://github.com/react-native-community/react-native-video/pull/1654

**Comment by snamstorm** [comment]
@CHaNGeTe tested your code changes with my project and issue is fixed for me - hope #1654 can be merged soon. Thanks for fixing!

**Comment by CHaNGeTe** [comment]
Check on 4.4.3

**Comment by kennym** [comment]
Thank you! Happy to see this got fixed.
