### ISSUE TITLE
DRM support

### ISSUE THREAD

**Issue by khat33b** [TheWidlarzGroup/react-native-video#1198]
Does React Native Video support DRM? If yes, how to play a DRM video? If no, when will this feature be implemented?

**Comment by cobarx** [comment]
There is no DRM support currently. Someone created a DRM PR for ExoPlayer on Android but I haven't been able to test this because I don't have any DRM content + a DRM server I can test against. On iOS, there's no work done on it at all.

If you can provide that, I will get the PR updated and test it.

DRM PR:
https://github.com/react-native-community/react-native-video/pull/858

**Comment by khat33b** [comment]
My company has them but I'm not allowed to give them to anyone. Can Facebook help you out in this matter? I'm sure that they can spare a server and content.

**Comment by cobarx** [comment]
The PR is #789 and someone provided samples so I can test it.

That PR needs to be updated to work with the latest ExoPlayer that we integrated in a recent release.  If you want to get it updated that will help out a lot.

**Comment by khat33b** [comment]
I have managed to replace react-native-video's ExoPlayer with my own ExoPlayer implementation from my old Android project which does support DRM but it is a older version with UI in it.

I currently have a project to finish at work. I shall be free from 15 October. I shall do it then.

**Comment by brentluna** [comment]
@khat33b Are you still planning on trying to tackle this soon? I have been attempting, but have been struggling, as I continue to have "unresolved module... hastemap" issues when trying to use the package from local repo. So if you are still planning on attempting today, I may just wait to see what you come up with.

**Comment by brentluna** [comment]
@khat33b no worries. Is the project you mentioned that you used your own exoplayer implementation available on github?

**Comment by brentluna** [comment]
@khat33b Is your ExoPlayer implementation open source? If so, do you have a link?

**Comment by khat33b** [comment]
@brentluna No, sorry. It's not open source.

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/pull/1445
