### ISSUE TITLE
Allow jumping to arbitrary timecodes

### ISSUE THREAD

**Issue by johanneslumpe** [TheWidlarzGroup/react-native-video#12]
If we want to display a kind of progress bar during playing of the video we need a way to "scrub" through the video and update the video's `currentTime` accordingly.

**Comment by brentvatne** [comment]
:+1: this is definitely needed! Currently have this in TODOS in README, I think this is might be a good next step

**Comment by brentvatne** [comment]
If anyone has time to work on this, a PR is welcome!

**Comment by johanneslumpe** [comment]
This is being worked on in the `feature/seeking` branch.

**Comment by meric426** [comment]
@johanneslumpe and @brentvatne: any idea when this will be merged to master and pushed to npmjs?

**Comment by brentvatne** [comment]
@meric426 @johanneslumpe - published in `0.3.5`!
