### ISSUE TITLE
Manual Installation & Link Process for iOS

### ISSUE THREAD

**Issue by aethernet** [TheWidlarzGroup/react-native-video#1200]
On iOS by following the installation process on iOS from the doc resulted in a not working - no error in any logs state.

I installed a few modules before relying on native code and it's been a nightmare every time. Probably because of some weird configuration in my project (which is an hybrid app and involves a lot of native code).

I usually rely on a manual link and avoid `$ pod install` at all cost as it destroy my project pretty much every time.

I was very sad to not find a manual installation process in the doc. 
So I'm willing to write it. Unfortunately, I don't know where to find the list of required linked binary and framework to make this plugin works without silently crashing in the background.

I ended up adding all media and av lib I found in Xcode and it worked...
Next step would be to remove them one by one until crash.

If someone has info, I'll be very happy to contribute to the doc.

On a side note, I also found that filename cannot contain spaces (provoke silent crash) which should be stated in the doc and should throw an error.

Thank you for this amazing piece of work!

E.

**Comment by cobarx** [comment]
I have brought react-native-video into a hybrid app before but only using `pod install`. That worked fine for me. I would recommend creating a git branch and seeing if you can get the pod approach to work and then toss it out if it doesn't work. IMO, CocoaPods is not great but the pain is a heck of a lot less than doing things by hand.

As far as dependencies go, we are not using any 3rd party dependencies. Doing a quick parse of the code indicates you need to link to React Native, AVFoundation, and MediaAccessibility. Maybe there is 1 or 2 others.

Best of luck, I'd gladly add any info on this to the doc.
