### ISSUE TITLE
Muted video still pauses playing Android audio

### ISSUE THREAD

**Issue by taylorkline** [TheWidlarzGroup/react-native-video#1201]
### Current behavior

Going to a screen with the `Video` component displayed causes any background music to stop playing on the Android device.

### Reproduction steps

v3.2.0

Add the component to a screen with `muted={true}`:

```
         <Video
                    muted={true}
                    source={...}
                    style={...}
                />
```

### Expected behavior

I would expect the `Video` component to not affect any background audio at all.

### Platform
Which player are you experiencing the problem on:
* Android

### Related

#1103

**Comment by stacywang0601** [comment]
The same issue also happened on iOS. Any solution for this?

Or can anyone tell me what happened (the logic )to make it pause in muted situation? What I can do to stop this issue?

**Comment by d42me** [comment]
@stacywang0601 Encountered the same problem, for iOS, please see https://github.com/react-native-community/react-native-video#audio-mixing.

**Comment by kelvinoshea** [comment]
Also encountering this issue. Fix?

**Comment by HarshitMadhav** [comment]
Me too I am facing this issue. Any fix?

**Comment by bornalibertines** [comment]
Hi From my understanding you trying to set the video to mute when it starts,
I found a solution for Android for it it is in the plugin file ExpoPlayerView.java
in function  setVideoView set player.setVolume(0.0f);
private void setVideoView() {
        if (surfaceView instanceof TextureView) {
            player.setVolume(0.0f);
            player.setVideoTextureView((TextureView) surfaceView);
        } else if (surfaceView instanceof SurfaceView) {
            player.setVolume(0.0f);
            player.setVideoSurfaceView((SurfaceView) surfaceView);
        }
    }

**Comment by chris35469** [comment]
Anyone still having related issues try changing the following in the `/android/settings.gradle` file: 

`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

to 

`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

**Comment by ovy9086** [comment]
2 years later... still happening :|

**Comment by itsmefordyfy** [comment]
Why this issue still present, hays!

**Comment by MichaelDanielTom** [comment]
We use autolinking, and since the correct player is not linked by default, we needed to modify our [`react-native.config.js`](https://github.com/react-native-community/cli/blob/master/docs/configuration.md) to use the correct exoplayer like in [this issue](https://github.com/react-native-community/react-native-video/issues/1746#issuecomment-535310510):
```
module.exports = {
  dependencies: {
     'react-native-video': {
       platforms: {
         android: {
           sourceDir: './node_modules/react-native-video/android-exoplayer',
         },
     },
  },
};
```

We also needed to make sure that this config wasn't getting changed by a previous installation, so we removed these lines from `settings.gradle`:
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
These lines, along with any other leftover native code, should also be able to be removed with `react-native unlink react-native-video` depending on your setup.

**Comment by syedamirali14** [comment]
> android-exoplayer

but i need to use android-exoplayer

**Comment by syedamirali14** [comment]
> Anyone still having related issues try changing the following in the `/android/settings.gradle` file:
> 
> `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`
> 
> to
> 
> `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

but i need to use android-exoplayer
