### ISSUE TITLE
playableDuration in Exoplayer is not credent

### ISSUE THREAD

**Issue by Winglonelion** [TheWidlarzGroup/react-native-video#1210]
### Current behavior

Hi, i'm back. Recently i back to maintained some module and notied that the playableDuration returned inonProgress callback is can not be trust.

It work acceptable in short videos, but with long videos over 1 hour. It usually return value smaller than `currentTime` and persist one value in many loops of updating `onProgress`.
Like this: 

![screen shot 2018-08-31 at 1 06 28 pm](https://user-images.githubusercontent.com/16574690/44895476-b6a9b700-ad1e-11e8-91a6-50680ac8931e.png)

It is useless to depend on it to show loading icon in your Video or display buffer line in Video control bar. 

Any ideas for this ? I will spend 2 hour to go deep in native code to know how it be and response late, thanks!

### Reproduction steps
Just use a long Video with duration > 1 hour and log playableDuration and currentTime in onProgress callback

### Expected behavior
playableDuration must be bigger than currentTime when Video play in normal case.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by cobarx** [comment]
playableDuration is the number of seconds past currentTime that are buffered and can be played without further buffering.

I didn't realize the docs didn't describe the meaning of that field. I'll get them updated.

**Comment by Winglonelion** [comment]
Thank you, i think it need a clarify description for prevent some mistake assumption. Thanks again for your contributions with this wonder repo 🤗
