### ISSUE TITLE
Support yuvj420p pixel format

### ISSUE THREAD

**Issue by lyrl** [TheWidlarzGroup/react-native-video#1212]
### Current behavior
I Can Play h264 yuv420p stream ,but h264 yuvj420p not

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by cobarx** [comment]
We are limited by what the AVPlayer library on iOS supports. If AVPlayer doesn't support yuvj420p, there's nothing we can do. I'd need more info to be certain that's the problem.

This article mentions that someone with a thumbnail in their stream had problems:
https://forums.plex.tv/t/hevc-direct-play-cant-figure-out-the-rules/214751/6
