### ISSUE TITLE
Notification bar controls

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1214]
I am using react-native-video as a audio player that will continue to stream in the background then the app is closed.

I am in need of a notification to sit in the top notification bar when the app is playing music that will let me pause, play and some other custom events. How has anyone else achieved this?

**Comment by moonstruck** [comment]
You may try [https://github.com/tanguyantoine/react-native-music-control](https://github.com/tanguyantoine/react-native-music-control )

**Comment by ghost** [comment]
Is this feature added now, Now am using this library in a  ott app  client requirement is that he get to control at least play pause from notification center when video is playing in background or picture in picture

**Comment by skfaisal93** [comment]
Any update on this?

**Comment by skfaisal93** [comment]
Please update

**Comment by freeboub** [comment]
@skfaisal93 if nobody implement it, no update 🤷
