### ISSUE TITLE
android  - audio stream plays in background DURING phone calls

### ISSUE THREAD

**Issue by taliseen** [TheWidlarzGroup/react-native-video#1217]
### Current behavior
While stream is playing on android, if I get a phone call, it continues to play in the background
### Reproduction steps
Hit play, recieve phone call
### Expected behavior
stream should stop during call and restart directly afterwards, maintaining state of controls.
### Platform
Which player are you experiencing the problem on:
Android Exoplayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by nehacs09** [comment]
Hi @taliseen Did u find a fix for this issue. I am also facing the same issue even in the latest version of library.

**Comment by MisaZ10** [comment]
I have the same issue!

**Comment by jeanffc** [comment]
I have the same issue :/

**Comment by JeremiahUL** [comment]
Same here

**Comment by tvpranav** [comment]
@taliseen @jeanffc @JeremiahUL @MisaZ10 @nehacurefit Have you guys found any way to resolve this? Please help!!

**Comment by Cassianosch** [comment]
Same here

**Comment by krunalbad** [comment]
Same here

**Comment by Fedeorlandau** [comment]
Hi there, this is still happening 2021

**Comment by sidferreira** [comment]
Use `onAudioFocusChanged`
