### ISSUE TITLE
[Android] Cannot find symbol class Dynamic

### ISSUE THREAD

**Issue by hblumberg** [TheWidlarzGroup/react-native-video#1218]
### Current behavior
I am unable to build the app, and I get the following error:
`error: cannot find symbol class Dynamic` in `ReactExoplayerViewManager.java`.

### Reproduction steps
1. Install react-native-video and manually link it using the Android directions: https://github.com/react-native-community/react-native-video#installation
2. Try to build the app.

### Expected behavior
I expect the app to build without errors.

### Platform
* Android ExoPlayer

Does anyone know why this is happening or how I might work around it? Thank you!

**Comment by hblumberg** [comment]
This was my mistake - it was trying to use an old version of RN which was being installed by Gradle. Sorry!

**Comment by tarunmehta-quovantis** [comment]
@hblumberg how did you solve this error. :) ?
