### ISSUE TITLE
HLS Video Streming

### ISSUE THREAD

**Issue by PooriaFarhad** [TheWidlarzGroup/react-native-video#122]
Hello,
Is it possible to use it as video streaming player?

**Comment by stereodenis** [comment]
@PooriaFarhad yes, it is possible. I played m3u8 files

**Comment by kitolog** [comment]
Hi, some m3u8 files playing normal, some not playing.
For example, this works: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8
but files m3u files from TVheadent not working. File structure from TVheadent looks like:

#EXTM3U
#EXTINF:-1,DELUXE MUSIC
http://39.44.12.48:9981/stream/channel/df28765ea0e821f43f8bd8cb9c355c1a

**Comment by kitolog** [comment]
I found a solution: you need video to be encoded h264 and audio mp4a(aac)
Only with this codecs streaming on ios works as needed.

**Comment by nvcken** [comment]
is it possible to do Live Streaming via HLS, I think it belongs to backend but please give me some hints?

**Comment by kitolog** [comment]
You can use https://github.com/Jalle19/node-ffmpeg-mpegts-proxy for live streaming conversion and in config set: 
`{
    "name"         : "Live 1",
    "provider"     : "livesources",
    "url"          : "/live1",
    "source"       : "http://some-live-source",
    "avconvOptions": {
      "output": [
        "-vcodec", "h264", "-acodec", "aac", "-strict", "-2"
      ]
    }
  },`

**Comment by nvcken** [comment]
@kitolog 
As I understand pattern , please correct me if wrong
iOS device feed camera stream --->  node-ffmpeg-mpegts-proxy --->  then it serve to iOS device play stream via HTTP url ( react-native-video), right ?
And, Could you please tell me some hints about any open source implement feed camera stream on iOS ? I don't have any clue about protocol or mechanism at this point
Thanks

**Comment by kitolog** [comment]
search for streaming plugins.
For example, you can try https://github.com/GuilhermeMedeiros/react-native-videocore for video broadcast. So, what we do:
Video broadcast from device -> node-ffmpeg-mpegts-proxy -> open stream http url in react-native-video

**Comment by ghost** [comment]
@nvcken @kitolog Nginx has [an RTMP module](https://github.com/arut/nginx-rtmp-module) and supports HLS, so you can drop-in VideoCore, push a stream to Nginx, and replay from most recent browsers. You'll have about a 30 second delay, but the benefit is rock-solid software, with a minimum of coding.

**Comment by nvcken** [comment]
Thanks @Zintinio .
I will try it. By the way, 30 second delay has been concern. I don't mind to use any higher performance support HLS & RTMP framework.(beyond node) Please let me know.
As I understand, the way to of proxy server broadcast is:
- source RTMP -----> Proxy Server : convert to mpegs by ffmpeg --> output stream http serves .m3u8 ( this way seem serves primarily of OS X, iOS devices)
- source RTMP -----> Proxy Server --> output stream RTMP ( flash player, browser ...)

So I think the delay comes from converting rtmp to mpegs by ffmpeg, Could we optimize it?

**Comment by ghost** [comment]
@nvcken Are you trying to stream peer-to-peer, or broadcast? There's more details here: https://github.com/arut/nginx-rtmp-module/issues/378

**Comment by nvcken** [comment]
@Zintinio 
My pattern is
Devices stream to Server , Server stream to multi-devices. So it is one-to-many, seem broadcast (one-way)

**Comment by haichongsihao** [comment]
@nvcken have you solved the problem that play stream via HTTP url  in ios?can you share me your idea

**Comment by dgurns** [comment]
Hey just figured out how to play live HLS streams on iOS and Android, in case anybody is having issues:
[https://github.com/react-native-community/react-native-video/issues/522#issuecomment-291015622](https://github.com/react-native-community/react-native-video/issues/522#issuecomment-291015622)

**Comment by brendonco** [comment]
anyone can suggest which library are you using to play live streaming?

**Comment by chinnisasi** [comment]
@PooriaFarhad pls help .. i m not able to play http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 .. when i m using react-native-video component
