### ISSUE TITLE
Android app crashes when video loaded - Audio issue ?

### ISSUE THREAD

**Issue by jhackGC** [TheWidlarzGroup/react-native-video#1220]
Hi !
Just got this weird error , thanks in advance.

### Current behavior
Android App crashes when videos are loaded

### Reproduction steps
// package.json
```
 "dependencies": {
    "aws-amplify": "^1.0.8",
    "aws-amplify-react-native": "^2.0.0",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-progress": "^3.5.0",
    "react-native-vector-icons": "^5.0.0",
    "react-native-video": "^3.0.0",
    "react-navigation": "^2.12.1",
    "react-waterfall": "^4.0.0"
  },

```
// linking with

$ react-native link
Scanning folders for symlinks in /Users/javierhack/Documents/dev/learning_projects/react-native/ReactNativeReduxCasts_start/albums/node_modules (23ms)

rnpm-install info Platform 'ios' module react-native-vector-icons is already linked
rnpm-install info Platform 'android' module react-native-vector-icons is already linked
rnpm-install info Platform 'ios' module react-native-video is already linked
rnpm-install info Platform 'android' module react-native-video is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project

// video.js 
```
<Video
     source={{ uri: 'https://s3-sa-east-1.amazonaws.com/albums-userfiles-mobilehub-405038094/public/PlaneOverhead.mp4' }}
      style={{ width: 300, height: 300 }}
      muted={true}
      resizeMode="contain"
      onError={this.handleError}
      onLoadStart={this.handleLoadStart}
      onLoad={this.handleLoad}
      onProgress={this.handleProgress}
      onEnd={this.handleEnd}
      onBuffer={this.handleBuffer}
      paused={true}
      ref={ref => this.player = ref}
/>
```

#### Note: 
If I remove the style prop,

```
<Video
     source={{ uri: 'https://s3-sa-east-1.amazonaws.com/albums-userfiles-mobilehub-405038094/public/PlaneOverhead.mp4' }}

      muted={true}
      resizeMode="contain"
      onError={this.handleError}
      onLoadStart={this.handleLoadStart}
      onLoad={this.handleLoad}
      onProgress={this.handleProgress}
      onEnd={this.handleEnd}
      onBuffer={this.handleBuffer}
      paused={true}
      ref={ref => this.player = ref}
/>
```

it is loaded and does not crashes, as shown in the callback run for onLoad={this.handleLoad}

 ```
handleLoad = (metaData) => {
        // Alert.alert('The Movie has been loaded! metaDat: ', metaData);
        console.warn('The Movie has been loaded! metaDat: ', metaData);
       ...
    }
```

// logcat console
```
9-06 12:15:35.676 29669-29669/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=ready
09-06 12:15:35.691 29669-29722/com.albums W/ReactNativeJS: 'The Movie has been loaded! metaDat: ', { canStepForward: true,
      canStepBackward: true,
      canPlayReverse: true,
      canPlaySlowForward: true,
      canPlayFastForward: true,
      textTracks: [],
      naturalSize: { orientation: 'landscape', height: 1080, width: 1920 },
      canPlaySlowReverse: true,
      currentTime: 0,
      duration: 12.91 }

```

### Expected behavior
Video is loaded and shown, paused and muted.

### Platform
* Android ExoPlayer

### Video sample
https://s3-sa-east-1.amazonaws.com/albums-userfiles-mobilehub-405038094/public/PlaneOverhead.mp4

### Logccat dump
09-06 12:10:28.128 29320-29320/com.albums I/ExoPlayerImpl: Init 91d2c9c [ExoPlayerLib/2.7.3] [generic_x86_64, Android SDK built for x86_64, unknown, 23]
09-06 12:10:28.133 1644-1802/system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@613a7acom.brentvatne.exoplayer.ReactExoplayerView{d93422b V.E...... ......I. 0,0-0,0} req=1flags=0x0
09-06 12:10:28.134 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
09-06 12:10:28.135 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=idle
09-06 12:10:28.162 29320-29320/com.albums I/ExoPlayerImpl: Init e1e7688 [ExoPlayerLib/2.7.3] [generic_x86_64, Android SDK built for x86_64, unknown, 23]
09-06 12:10:28.165 1644-2155/system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@613a7acom.brentvatne.exoplayer.ReactExoplayerView{3b88446 V.E...... ......I. 0,0-0,0} req=1flags=0x0
09-06 12:10:28.166 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
    onStateChanged: playWhenReady=false, playbackState=idle
09-06 12:10:28.168 29320-29320/com.albums D/AudioManager: AudioManager dispatching onAudioFocusChange(-1) for android.media.AudioManager@613a7acom.brentvatne.exoplayer.ReactExoplayerView{d93422b V.E...... ......I. 0,0-0,0}
09-06 12:10:28.179 29320-29320/com.albums I/ExoPlayerImpl: Init 201d607 [ExoPlayerLib/2.7.3] [generic_x86_64, Android SDK built for x86_64, unknown, 23]
09-06 12:10:28.183 1644-3708/system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@613a7acom.brentvatne.exoplayer.ReactExoplayerView{fcb155d V.E...... ......I. 0,0-0,0} req=1flags=0x0
09-06 12:10:28.185 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
    onStateChanged: playWhenReady=false, playbackState=idle
09-06 12:10:28.186 29320-29320/com.albums D/AudioManager: AudioManager dispatching onAudioFocusChange(-1) for android.media.AudioManager@613a7acom.brentvatne.exoplayer.ReactExoplayerView{3b88446 V.E...... ......I. 0,0-0,0}
09-06 12:10:28.255 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=buffering
09-06 12:10:28.256 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=buffering
09-06 12:10:28.258 29320-29320/com.albums D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=buffering
09-06 12:10:28.304 29320-29387/com.albums D/SoLoader: About to load: libimagepipeline.so
    libimagepipeline.so not found on /data/data/com.albums/lib-main
    Result 0 for libimagepipeline.so in source com.facebook.soloader.ApkSoSource[root = /data/data/com.albums/lib-main flags = 1]
    Extraction logs: null
09-06 12:10:28.322 29320-29387/com.albums D/SoLoader: Loaded: libimagepipeline.so
09-06 12:10:28.688 29320-29381/com.albums W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
    Unrecognized profile/level 0/2 for video/mpeg2
    Unrecognized profile/level 0/3 for video/mpeg2
09-06 12:10:28.727 29320-29381/com.albums I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
09-06 12:10:28.756 29320-29399/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:28.761 29320-29400/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:28.766 29320-29401/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:28.792 29320-29399/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.827 29320-29397/com.albums I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 30023681
09-06 12:10:28.851 29320-29400/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.851 29320-29399/com.albums W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
09-06 12:10:28.852 29320-29399/com.albums E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
09-06 12:10:28.863 29320-29401/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.863 29320-29399/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.885 29320-29398/com.albums I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 30023682
09-06 12:10:28.886 29320-29401/com.albums W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
09-06 12:10:28.886 29320-29401/com.albums E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
09-06 12:10:28.896 29320-29401/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.917 29320-29396/com.albums I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 30023683
09-06 12:10:28.920 29320-29330/com.albums I/art: Background sticky concurrent mark sweep GC freed 7258(314KB) AllocSpace objects, 1(16KB) LOS objects, 0% free, 5MB/5MB, paused 10.072ms total 67.060ms
09-06 12:10:28.920 29320-29400/com.albums W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
09-06 12:10:28.920 29320-29400/com.albums E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
09-06 12:10:28.921 29320-29399/com.albums E/OMXNodeInstance: setConfig(1:google.h264.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:28.921 29320-29399/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:28.921 29320-29401/com.albums E/OMXNodeInstance: setConfig(1:google.h264.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:28.922 29320-29401/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:28.926 29320-29400/com.albums D/SoftAVCDec: Number of CPU cores: 4
09-06 12:10:28.928 29320-29400/com.albums E/OMXNodeInstance: setConfig(1:google.h264.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:28.928 29320-29400/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:29.013 29320-29330/com.albums W/art: Suspending all threads took: 7.665ms
09-06 12:10:29.015 29320-29410/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:29.036 29320-29411/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:29.037 29320-29330/com.albums I/art: Background partial concurrent mark sweep GC freed 3096(110KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/10MB, paused 22.263ms total 106.853ms
09-06 12:10:29.039 29320-29412/com.albums I/OMXClient: Using client-side OMX mux.
09-06 12:10:29.113 29320-29410/com.albums E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:29.113 29320-29410/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:29.148 29320-29417/com.albums I/SoftAAC2: limiting to stereo output
09-06 12:10:29.157 29320-29417/com.albums I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
09-06 12:10:29.233 29320-29412/com.albums E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:29.233 29320-29412/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:29.281 29320-29425/com.albums I/SoftAAC2: limiting to stereo output
09-06 12:10:29.286 29320-29425/com.albums I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
09-06 12:10:29.294 29320-29411/com.albums E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
09-06 12:10:29.294 29320-29411/com.albums I/ACodec: codec does not support config priority (err -2147483648)
09-06 12:10:29.322 1253-1285/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3112960
09-06 12:10:29.328 29320-29432/com.albums I/SoftAAC2: limiting to stereo output
09-06 12:10:29.339 29320-29432/com.albums I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
    
    
    --------- beginning of crash
09-06 12:10:29.381 29320-29396/com.albums A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xc14e1000 in tid 29396 (MediaCodec_loop)
09-06 12:10:29.433 1356-1356/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/4931947:userdebug/test-keys'
    Revision: '0'
09-06 12:10:29.434 1356-1356/? A/DEBUG: ABI: 'x86'
09-06 12:10:29.437 1356-1356/? A/DEBUG: pid: 29320, tid: 29396, name: MediaCodec_loop  >>> com.albums <<<
    signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc14e1000
09-06 12:10:29.448 1356-1356/? A/DEBUG:     eax 002f7600  ebx ea168eb4  ecx 000af980  edx ea206f3c
09-06 12:10:29.449 1356-1356/? A/DEBUG:     esi bf7c1000  edi c14e1000
        xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000177  xss 0000002b
        eip ea162a38  ebp 003fffc4  esp d893b0b4  flags 00210202
09-06 12:10:29.451 1356-1356/? A/DEBUG: backtrace:
        #00 pc 00002a38  /system/lib/libOpenglSystemCommon.so (goldfish_dma_write(goldfish_dma_context*, void*, unsigned int)+56)
        #01 pc 00003853  /system/lib/libOpenglSystemCommon.so (ExtendedRCEncoderContext::lockAndWriteDma(void*, unsigned int)+67)
        #02 pc 00003062  /system/lib/lib_renderControl_enc.so
        #03 pc 0000314e  /system/lib/hw/gralloc.ranchu.so
        #04 pc 00009e67  /system/lib/libui.so (android::GraphicBufferMapper::unlock(native_handle const*)+71)
        #05 pc 0012987d  /system/lib/libstagefright.so (android::SoftwareRenderer::render(void const*, unsigned int, long long, long long, void*, android::sp<android::AMessage> const&)+813)
        #06 pc 000dec7e  /system/lib/libstagefright.so (android::MediaCodec::onReleaseOutputBuffer(android::sp<android::AMessage> const&)+670)
09-06 12:10:29.452 1356-1356/? A/DEBUG:     #07 pc 000da678  /system/lib/libstagefright.so (android::MediaCodec::onMessageReceived(android::sp<android::AMessage> const&)+6920)
        #08 pc 0000c9b9  /system/lib/libstagefright_foundation.so (android::AHandler::deliverMessage(android::sp<android::AMessage> const&)+41)
        #09 pc 00010ed2  /system/lib/libstagefright_foundation.so (android::AMessage::deliver()+114)
        #10 pc 0000ddef  /system/lib/libstagefright_foundation.so (android::ALooper::loop()+463)
        #11 pc 0000e7a3  /system/lib/libstagefright_foundation.so (android::ALooper::LooperThread::threadLoop()+35)
        #12 pc 00014aac  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+418)
        #13 pc 0006bfae  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+98)
        #14 pc 000141cf  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+122)
        #15 pc 00081923  /system/lib/libc.so (__pthread_start(void*)+56)
        #16 pc 000227f2  /system/lib/libc.so (__start_thread+25)
        #17 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
    
    
    --------- beginning of system
09-06 12:10:29.762 1644-29454/system_process W/ActivityManager:   Force finishing activity com.albums/.MainActivity
09-06 12:10:29.762 1356-1356/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
09-06 12:10:29.762 1356-1356/? E/DEBUG: AM write failed: Broken pipe
09-06 12:10:29.762 1644-1663/system_process I/BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
09-06 12:10:29.774 1253-2046/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1327104
09-06 12:10:29.799 1644-29454/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 112)
09-06 12:10:29.800 1644-29454/system_process W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
09-06 12:10:29.805 1644-1665/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 60)
09-06 12:10:29.808 1251-1251/? E/lowmemorykiller: Error writing /proc/29320/oom_score_adj; errno=22
09-06 12:10:29.825 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.826 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.827 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.828 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.829 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
    Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.830 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.832 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.834 1644-1686/system_process W/InputDispatcher: channel 'bdf276 com.albums/com.albums.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-06 12:10:29.834 1644-1686/system_process E/InputDispatcher: channel 'bdf276 com.albums/com.albums.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-06 12:10:29.837 1644-1652/system_process W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7f7a6e51bf78)
09-06 12:10:29.849 1365-1365/? I/Zygote: Process 29320 exited due to signal (11)
09-06 12:10:29.856 1644-2055/system_process W/MediaFocusControl:   AudioFocus   audio focus client died
09-06 12:10:29.857 1644-2055/system_process I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@d5ffbf1
09-06 12:10:29.857 1644-2213/system_process I/ActivityManager: Process com.albums (pid 29320) has died
09-06 12:10:29.857 1644-2055/system_process I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@d5ffbf1
    AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@d5ffbf1
09-06 12:10:29.857 1644-2055/system_process W/MediaFocusControl:   AudioFocus   audio focus client died
      AudioFocus   audio focus client died
09-06 12:10:29.857 1644-18742/system_process D/GraphicsStats: Buffer count: 3
09-06 12:10:29.920 1644-2155/system_process I/WindowState: WIN DEATH: Window{bdf276 u0 com.albums/com.albums.MainActivity}
09-06 12:10:29.920 1644-2155/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'bdf276 com.albums/com.albums.MainActivity (server)'
09-06 12:10:29.921 1644-3708/system_process I/WindowState: WIN DEATH: Window{e07e3d6 u0 SurfaceView}
09-06 12:10:29.923 1644-1658/system_process I/WindowState: WIN DEATH: Window{e4b6657 u0 SurfaceView}
09-06 12:10:29.924 1644-1806/system_process I/WindowState: WIN DEATH: Window{d934544 u0 SurfaceView}
09-06 12:10:29.928 1644-10088/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
09-06 12:10:29.935 1644-10088/system_process D/EGL_emulation: eglCreateContext: 0x7f7a580bbd60: maj 3 min 0 rcv 3
09-06 12:10:29.947 1644-10088/system_process D/EGL_emulation: eglMakeCurrent: 0x7f7a580bbd60: ver 3 0 (tinfo 0x7f7a574b78e0)
09-06 12:10:29.948 1644-10088/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
    glUtilsParamSize: unknow param 0x00008824
09-06 12:10:29.950 2429-2808/com.google.android.gms W/art: Long monitor contention event with owner method=boolean ozo.a(ozn, android.content.ServiceConnection, java.lang.String) from :com.google.android.gms@12874027@12.8.74 (040800-204998136):4 waiters=1 for 104ms
09-06 12:10:29.989 1644-10088/system_process D/EGL_emulation: eglMakeCurrent: 0x7f7a580bbd60: ver 3 0 (tinfo 0x7f7a574b78e0)
09-06 12:10:30.043 1644-7693/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.052 1644-18735/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.100 1644-2055/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.127 1644-18735/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.136 1644-18735/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.155 2035-2216/com.android.launcher3 D/EGL_emulation: eglMakeCurrent: 0x7f7a69961d20: ver 3 0 (tinfo 0x7f7a699428e0)
09-06 12:10:30.158 1644-1657/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-06 12:10:30.678 1644-1665/system_process W/WindowAnimator: Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
    Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-06 12:10:30.679 1644-1665/system_process W/WindowAnimator: Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
    Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-06 12:10:31.251 1360-1711/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 15914474 , only wrote 15776748

**Comment by andyschwob** [comment]
@jhackGC seeing the exact same behavior on these CPUs, did you find any way around this?

**Comment by jhackGC** [comment]
Hey @andyschwob  I dont think I understand the question, I found a solution changing the AVD CPU architecture from 64 to 32 bits, like said here: "it only fails when the AVD has a x86_64 CPU assigned, if you use the same AVD config, but change it to have a x86 CPU instead, it works fine " 

pls clarify the question, you have the same behavior for all CPUs mentioned x86 and x86_64? 

Cheers

**Comment by iagormoraes** [comment]
I tested in emulator Android 6.0 with CPU x86_64 and the crash is real, on x86 the video loads perfectly.

Edit: On emulator Android 5 if the video have audio, it will not load.

**Comment by Venkat1P** [comment]
it is failing on USB connect device too
