### ISSUE TITLE
I can not play m3u8 files

### ISSUE THREAD

**Issue by CarlosTolenk** [TheWidlarzGroup/react-native-video#1222]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

My code

           <Video
                            ref={(ref) => {
                                this.player = ref
                            }} 
                            // source={{uri: 'http://ss2.domint.net:2130/cdt_str/diamantetv/playlist.m3u8'}}
                             source={{uri: 'http://live-4-201.rutube.ru/live-hls/xG6l_yXWo9vD4PvHW_ImqA/1536210339/49/52896/move/four/dirs/upper/720p.m3u8'}}        
                            // source={{ uri: 'https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_10mb.mp4' }}                
                            style={styles.video}
                            resizeMode='stretch'    
                            onBuffer={this.onBuffer}   
                            onLoad={this.onLoad}   
                            paused={this.state.paused}
                            // onProgress={this.setTime}
                    />

I tried to play an mp4 file from a url, it works but I need to play a live streaming

**Comment by Neto-Pavanini** [comment]
I'm also having the same problem, Any progress ?

**Comment by echokk11** [comment]
same issue, did not work in Android

**Comment by OlegNovosad** [comment]
Any progress here? I also struggle with playing my video stream url from the server in "m3u8" format.

**Comment by JustinXu0223** [comment]
> Any progress here? I also struggle with playing my video stream url from the server in "m3u8" format.

I use the intranet host on the android virtual device and replace the host with ip.

**Comment by luisnaranjo733** [comment]
@JustinXu0223  can you clarify a bit? why does that work?

**Comment by luisnaranjo733** [comment]
I set the type and my m3u8 video is not working either. I manually set the type in Java with the debugger, so I'm 100% sure the type is getting set to HLS correctly
```java
    private MediaSource buildMediaSource(Uri uri, String overrideExtension) {
        int type = Util.inferContentType(!TextUtils.isEmpty(overrideExtension) ? "." + overrideExtension
                : uri.getLastPathSegment());
        switch (type) {
            case C.TYPE_SS:
                return new SsMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultSsChunkSource.Factory(mediaDataSourceFactory), 
                        minLoadRetryCount, SsMediaSource.DEFAULT_LIVE_PRESENTATION_DELAY_MS, 
                        mainHandler, null);
            case C.TYPE_DASH:
                return new DashMediaSource(uri, buildDataSourceFactory(false),
                        new DefaultDashChunkSource.Factory(mediaDataSourceFactory), 
                        minLoadRetryCount, DashMediaSource.DEFAULT_LIVE_PRESENTATION_DELAY_MS,
                        mainHandler, null);
            case C.TYPE_HLS:
                return new HlsMediaSource(uri, mediaDataSourceFactory, 
                        minLoadRetryCount, mainHandler, null);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource(uri, mediaDataSourceFactory, new DefaultExtractorsFactory(),
                        mainHandler, null);
            default: {
                throw new IllegalStateException("Unsupported type: " + type);
            }
```

**Comment by luisnaranjo733** [comment]
I did notice that the HlsMediaSource, SSMediaSource, ExtractorMediaSource and DashMediaSource APIs from Exoplayer are marked as deprecated. Not sure if that could potentially be related

**Comment by gazedash** [comment]
@luisnaranjo733 see my PR, it's a little bit dirty, but with that I was able to play these types of streams
https://github.com/react-native-community/react-native-video/pull/1480
