### ISSUE TITLE
local uri video does not play

### ISSUE THREAD

**Issue by heyman333** [TheWidlarzGroup/react-native-video#1226]
### Current behavior
Can't Play local uri like `file:///data/user/0/cache/Camera/4b70adf4-50a4-401a-ae59-d7b3a6058491.mp4` after remote video uri is played 

### Reproduction steps
1. server-fetched video played very well
2. navigate other screen on which playing local video uri(Path: `file:///data/user/0/co.kr.castnets_app/cache/Camera/4b70adf4-50a4-401a-ae59-d7b3a6058491.mp4`)
3. Video does not play.

### Expected behavior
local video (`file:///data/user/0/co.kr.castnets_app/cache/Camera/4b70adf4-50a4-401a-ae59-d7b3a6058491.mp4`) plays

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by pqminh** [comment]
the same

**Comment by heyman333** [comment]
@pqminh I am just using other library [react-native-video-processing](https://github.com/shahen94/react-native-video-processing)

this issue occurs in old android device only
