### ISSUE TITLE
When playing WMV format video, it is wrong:'AVFoundationErrorDomain', code: -11800 /11828

### ISSUE THREAD

**Issue by HAPENLY** [TheWidlarzGroup/react-native-video#1227]
### Current behavior
Describe what happens when you encounter this issue.

When playing WMV format video, 

http://xx.xx.241.173:3100/20e4cca045372042f3a90f131d817de3d7ec.wmv

{ error: { domain: 'AVFoundationErrorDomain', code: -11828 },
  target: 464 }

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
 >1
http://xx.xx.241.173:3100/20e4cca045372042f3a90f131d817de3d7ec.wmv
 >2
{ error: { domain: 'AVFoundationErrorDomain', code: -11828 },
  target: 464 }

### Expected behavior
Describe what you wanted to happen

Play video 

normal

### Platform
Which player are you experiencing the problem on:
* iOS
### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

https://drive.google.com/open?id=1Fe6aWoDlf7TMM1TDdk6eZsu7TEsFwNV8

**Comment by joshien1997** [comment]
Can you play WMV format video on Android ??? @HAPENLY 
When playing WMV format => only dark screen :( please help
