### ISSUE TITLE
Android files missing?

### ISSUE THREAD

**Issue by scgough** [TheWidlarzGroup/react-native-video#123]
Hi there,
I've installed the package (for my Android React-Native project) via npm but the `android` folder referenced in the java side of my project isn't there within `node_modules`:

`project(':RCTVideo').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

From terminal I can see that version 0.6.1 has been installed. Because of this my Android project won't compile.

To get around the issue (as per here: https://github.com/brentvatne/react-native-video/issues/115) , I then downloaded the master ZIP from GitHub. The project compiles and runs on my Android device but I now get the error: 

`'Video' has no propType for native prop 'RCTVideo.testID' of native type 'String'` where `Video` is my JS side reference to the component.

Can anyone help?

I'm running node v5.0.0 and npm 3.3.9

**Comment by scgough** [comment]
Apologies - This was a setup error on my part - ignore.

**Comment by duynd1** [comment]
@scgough I had same problem on Android, but don't know how to fix it.
Can you advise me?
