### ISSUE TITLE
Android ExoPlayer video/poster display issue

### ISSUE THREAD

**Issue by pqminh** [TheWidlarzGroup/react-native-video#1230]
### Current behavior
I don't know why my video play wrong position. Video is playing at the top and poster or something display at bottom like picture below.

### Expected behavior
Video play fullscreen.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
"react-native-video": "^3.2.0",
"react-native": "^0.47.2",

### Image
![1536757514084](https://user-images.githubusercontent.com/13993984/45426834-802d4e00-b6c7-11e8-8881-1a9d6094c593.JPEG)

**Comment by SuhairZain** [comment]
@pqminh Were you able to fix this issue? I'm having the same problem.
