### ISSUE TITLE
create gh pages for docs

### ISSUE THREAD

**Issue by nicholasess** [TheWidlarzGroup/react-native-video#1232]
Hi everyone!
I'm member of the core team [docz](https://github.com/pedronauck/docz) and i will send a PR with docs to react-native-video. Before that, i need that you create in settings the github page in branch master the directory ```docs```. 

After tell me when the github page created.

Thanks

**Comment by cobarx** [comment]
Hi @nicholasess docz looks cool, and I'd welcome it in the project.

I'm not sure what you're asking for. We already have a `docs` directory in the project. Are you wanting me to enable Wiki support or something else?
