### ISSUE TITLE
Video loop (repeat) freeze on android

### ISSUE THREAD

**Issue by camel113** [TheWidlarzGroup/react-native-video#1239]
### Current behavior
I have short video (duration 15 sec.). Video plays with prop repeat `true`. After approx. 1 minute of being on screen, video freeze. This only happens on Android.
Also after waiting for 10 minutes, the video starts to play again
My videos are stored on google cloud platform
https://storage.googleapis.com/video-footstats/versoix.MOV

### Reproduction steps
My component is exactly like this
```
import React from "react";
import { AppRegistry, View, StyleSheet, Dimensions, TouchableOpacity } from "react-native";
import { StyleProvider, Root} from "native-base";
import Video from 'react-native-video';
import styles from '../Styles';

const { width, height } = Dimensions.get('window');

class SingleVideo extends React.Component {

    constructor(props){
        super(props);
        this.state = {
          screenWidth: width,
          heightScaled: 0,
          display:'none'
        };
    }

    onBuffer(){}

    onEnd(){}
    
    videoError(e){console.log(e)}

    render() {
      return (
        <View style={styles.flatListSocialFeed}>
          <Video source={{uri: 'https://storage.googleapis.com/video-footstats/versoix.MOV'}}
             ref={(ref) => {
               this.player = ref
             }}
             onBuffer={this.onBuffer.bind(this)}
             onEnd={this.onEnd.bind(this)}
             onError={this.videoError.bind(this)}
             paused={false}
             onLoad={response => {
              const { width, height } = response.naturalSize;
              var heightScaled = height * (this.state.screenWidth / width);
              if(heightScaled>350){
                heightScaled = 350
              }
              this.setState({heightScaled,display:'flex'});
             }}
             repeat={true}
             muted={true}
             resizeMode={"contain"}
             style={{
                width: this.state.screenWidth,
                height: this.state.heightScaled,
                display: this.state.loaded
          }} />
        </View>
      );
    }
}
export default SingleVideo;
```

### Expected behavior
Video should not freeze.

### Platform
* Android ExoPlayer

### Video sample
None

**Comment by kirillplatonov** [comment]
I have similar problem. I don't use loop. But it freezes on second attempt to play video. The problem happens only on Android.

**Comment by JakubPod** [comment]
I know this is a 1-year-old issue, but since it's still open and since I still run into it myself recently, I'm going to share my workaround.

Cache your video before playing it. I used _react-native-video-cache_ to cache video and then _react-native-fs_ to clear the cache. Now it loops flawlessly.

There might be a better way to do it without using two libs, but this was the most convenient for me.

**Comment by CHaNGeTe** [comment]
Can you check on https://github.com/react-native-community/react-native-video/pull/1655 ?
PR was not designed for this, but it is solving some async issues when setting props.

**Comment by CHaNGeTe** [comment]
It works for me on that branch

**Comment by pmella16** [comment]
> I have similar problem. I don't use loop. But it freezes on second attempt to play video. The problem happens only on Android.

mee too, any solution? :(

**Comment by Sunii-999** [comment]
> I have similar problem. I don't use loop. But it freezes on second attempt to play video. The problem happens only on Android.

2026 and i ran into the same issue, my video is about 3 seconds long but a video thats 19s long works as it should - where could i find the fix if there is any?
