### ISSUE TITLE
playInBackground={false} not working

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1240]
### Current behavior
I've tried the master branch and 3.1.0 and looks like when playInBackground is set to false, the audio continues playing even when the app is in the background.

### Reproduction steps
Just set playInBackground to false :)

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by MoonBlueSky** [comment]
android  +1

**Comment by otaro808** [comment]
Maybe you would like to pause the video when the screen is not being focused. 
(Forgive if I'm wrong..)
If so, you can review this comment for a solution.
[https://github.com/react-native-community/react-native-video/issues/1223](https://github.com/react-native-community/react-native-video/issues/1223)

**Comment by anshul-kai** [comment]
Any update on this? I'd be happy to help out with the research and submit a PR if I can be pointed in the right direction as I haven't spent much time with the inner workings of this lib. Thanks!

**Comment by anshul-kai** [comment]
I dug into this and it appears to be a corner case where `playInBackground` and `playWhenInactive` oppose each other. Perhaps an improvement to the function below or added details to the documentation would avoid this issue for others. I didn't find this to be an issue on Android FWIW.

```
- (void)applicationWillResignActive:(NSNotification *)notification
{
  if (_playInBackground || _playWhenInactive || _paused) return;
  
  [_player pause];
  [_player setRate:0.0];
}
```
