### ISSUE TITLE
cann't loading online video .

### ISSUE THREAD

**Issue by pengcao1** [TheWidlarzGroup/react-native-video#1242]
### Current behavior
<Video ...>
  onError={this.onError}
</Video>
onError = () => {
    consonle.log("something wrong");
}

### Reproduction steps
try to open a online mp3 audio

### Expected behavior
the online mp3 audio can play success

### Platform
"react-native": "0.55.2",
"react-native-video": "3.2.1",
"react": "16.3.1",
android 7.1.1

### Video sample
09-18 00:01:18.639 10358 10358 W FA      : setCurrentScreen cannot be called with the same class and name
09-18 00:01:20.245 10358 10358 W MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-18 00:01:20.247 10358 10358 W MediaPlayer: Couldn't open https://xxxxxxxx.mp3: java.io.FileNotFoundException: No content provider: https://xxxxxxxx.mp3
09-18 00:01:20.249   231   231 I MediaPlayerService: processName cmdline:/proc/10358/cmdline
09-18 00:01:20.251   231   249 I MediaPlayerFactory:  createFFPlayer
09-18 00:01:20.252   231   249 E FFPlayerHelper: isBDDirectory() ,path = https://xxxxxxxx.mp3
09-18 00:01:20.252   231   249 E FFPlayerHelper: isBDDirectory(): no BDMV
09-18 00:01:20.253   231   249 E RockFFPlayerBase: FFMPlayerBase:eDisplayIdMain
09-18 00:01:20.254   231   249 D FFPlayerHelper: MediaServer is SP_FOREGROUND, tid=249
09-18 00:01:20.254   231   249 D RkExtensionPlayer: RkExtensionPlayer in
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess in
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess subDir
09-18 00:01:20.252   231   249 E FFPlayerHelper: isBDDirectory(): no BDMV
09-18 00:01:20.253   231   249 E RockFFPlayerBase: FFMPlayerBase:eDisplayIdMain
09-18 00:01:20.254   231   249 D FFPlayerHelper: MediaServer is SP_FOREGROUND, tid=249
09-18 00:01:20.254   231   249 D RkExtensionPlayer: RkExtensionPlayer in
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess in
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess subDirectory[0] = /tmp/rk_ext_subtitle/,right = -1
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess subDirectory[1] = /data/rk_ext_subtitle/,right = -1
09-18 00:01:20.255   231   249 E RkExtensionPlayer: checkDirectoryAccess subDirectory[2] = /data/media/0/rk_ext_subtitle/,right = -1
09-18 00:01:20.255   231   249 E RkExtensionPlayer: createDirectory(), path = /tmp/rk_ext_subtitle/
09-18 00:01:20.255   231   249 E RkExtensionPlayer: createDirectory(), create directory = /tmp/rk_ext_subtitle/ fail,reson = No such file or directory
09-18 00:01:20.255   231   249 E RkExtensionPlayer: createDirectory(), path = /data/rk_ext_subtitle/
09-18 00:01:20.256   231   249 E RkExtensionPlayer: createDirectory(), create directory = /data/rk_ext_subtitle/ fail,reson = Permission denied
09-18 00:01:20.256   231   249 E RkExtensionPlayer: createDirectory(), path = /data/media/0/rk_ext_subtitle/
09-18 00:01:20.242   231   231 W Binder:231_1: type=1400 audit(0.0:9158): avc: denied { create } for name="rk_ext_subtitle" scontext=u:r:mediaserver:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0
09-18 00:01:20.258   231   249 E RkExtensionPlayer: createDirectory(), path = /data/media/0/rk_ext_subtitle/b22283c0/
09-18 00:01:20.258   231   249 D RkExtensionPlayer: checkDirectoryAccess: directory = /data/media/0/rk_ext_subtitle/b22283c0/
09-18 00:01:20.261   231   249 E TraceThread: TraceThread::randomUID() --> [UID=74418c6d]
09-18 00:01:20.262   231 10690 E TraceThread:     VsyncReciver(tid = 2959972640)--> [UID=74418c6d] VsyncReciver::startthread
09-18 00:01:20.262   231   249 E TraceThread:     RockFFPlayer(tid = 2965195040)--> [UID=74418c6d] FFMPlayer Construction; object=0xb226c000
09-18 00:01:20.262   231   249 I RockFFPlayer: setDataSource in 0xb226c000
09-18 00:01:20.262   231   249 D RockFFPlayer: start:create thread
09-18 00:01:20.263   231 10691 D RockFFPlayer: RkMessageQueue::run()
09-18 00:01:20.263   231   249 D RockFFPlayer: start:create thread ok,mThreadStatus=0
09-18 00:01:20.263   231   249 D RockFFPlayer: normal,set User-Agent: AppleCoreMedia/1.0.0.7B367 (iPad; U; CPU OS 4_3_3 like Mac OS X)
09-18 00:01:20.263   231   249 D RockFFPlayer: enter enqueueMessage
09-18 00:01:20.263   231   249 D RockFFPlayer: enqueueMessage:****1
09-18 00:01:20.263   231   249 D RockFFPlayer: enqueueMessage:****2
09-18 00:01:20.263   231   249 D RockFFPlayer: enqueueMessage:****3
09-18 00:01:20.263   231   249 D RockFFPlayer: enqueueMessage:Message 1,set signal
09-18 00:01:20.263   231   249 D RockFFPlayer: enqueueMessage:sync wait
09-18 00:01:20.263   231 10691 D RockFFPlayer: deliverMessage
09-18 00:01:20.264   231 10691 D RockFFPlayer: run : dequeueMessage Message 20

**Comment by pologonzalo** [comment]
Why would you like a video-player to reproduce music? Wouldnt be easier to use: https://github.com/zmxv/react-native-sound ?

**Comment by pengcao1** [comment]
> Why would you like a video-player to reproduce music? Wouldnt be easier to use: 
https://github.com/zmxv/react-native-sound?

because does not complete the project from the first line code, but debug

**Comment by cobarx** [comment]
I would look at react-native-track-player for playing music, I've had good luck with it.

However, react-native-video should be able to play mp3s without issue. It looks like you might be using react-native-video with MediaPlayer, I would recommend using ExoPlayer instead as that generally works better.

**Comment by pengcao1** [comment]
> I would look at react-native-track-player for playing music, I've had good luck with it.
> 
> However, react-native-video should be able to play mp3s without issue. It looks like you might be using react-native-video with MediaPlayer, I would recommend using ExoPlayer instead as that generally works better.

How can we change from MediaPlayer to ExoPlayer?
