### ISSUE TITLE
How I can resume current media (Spotify) after video ended?

### ISSUE THREAD

**Issue by renandelmonico** [TheWidlarzGroup/react-native-video#1243]
When I play a video, Spotify is paused, but after the video ends I need resume my Spotify. How I can do this? Any ideas?

**Comment by nickmacia** [comment]
I have nearly the same issue. 

I want the audio track to a video to play over whatever audio I have running in the background, whether it be Spotify or some other app. 

Current behavior is such that even if you have a video with muted audio playing, your secondary (i.e. background) audio source will pause. Default behavior should be such that the playing of a video does not inhibit any other audio that may be playing (provided that the video is not in a full screen player). 

Ideally, a prop should be exposed to manually control this.

**Comment by cobarx** [comment]
We need an audio manager that allows us to set the correct audio modes to support stuff like this. It's something I want to work on but haven't had the time to fully understand and build.

If you're dedicated, there is an audio manager in Expo that could be ported to this project.

For a quick fix, look at the audio modes for iOS & Android and set them manually. Here is a write-up:
https://github.com/react-native-community/react-native-video/issues/1103
