### ISSUE TITLE
Want to know if there is any video size limit

### ISSUE THREAD

**Issue by sanilcgs** [TheWidlarzGroup/react-native-video#1248]
I am using react-native-video for a video player. For my app, there will be videos having size more than 500mb or more. So I want to know whether this package can work normally for bigger size videos. Presently small sized videos are working fine.

**Comment by cobarx** [comment]
Yes, large video should work. If you run into any issues, feel free to post a bug report. Make sure to include a link to the video so we can look into it.

**Comment by sanilcgs** [comment]
@cobarx Thanks for the response. I have a video file having type mov. when I try to play this video, the  video is not showing. I have tested in android device. I think, android won't support video file with type mov. Is there any way to play those type of videos using this package??

**Comment by cobarx** [comment]
No, we support whatever formats ExoPlayer supports which are covered here:
https://google.github.io/ExoPlayer/supported-formats.html

Your best bet is to convert to a widely supported format like mp4 that will play on iOS & Android. The only way to get support for stuff like MOV is to build your own player and implement the codecs yourself like MXPlayer does.

**Comment by paddy57** [comment]
> No, we support whatever formats ExoPlayer supports which are covered here:
> https://google.github.io/ExoPlayer/supported-formats.html
> 
> Your best bet is to convert to a widely supported format like mp4 that will play on iOS & Android. The only way to get support for stuff like MOV is to build your own player and implement the codecs yourself like MXPlayer does.

When my video size is more than 10 mb(or more than 20 sec) then videos freezes for a moment and starts again. can you help me with that. I'm using exo=player, but with android player it works perfectely.
