### ISSUE TITLE
Video still plays even though paused = true

### ISSUE THREAD

**Issue by AlexandruVoica** [TheWidlarzGroup/react-native-video#1249]
### Current behavior
I am working on a client project and the part I am working on is playing videos attached to posts in a newsfeed. Because I have not found a package to satisfy the requirements, I've started coding the video player controls from scratch. I eventually got to building the progress/seek bar. I did it using a <View> with the Gesture Responder API from react-native. The paused prop of the <Video> component is controlled by state (`this.state.videoPlayer.paused`). I update the state every time a new touch is started on the seek bar to `this.state.videoPlayer.paused = true` and change back to false when the touch is released. This worked perfectly fine the first few iterations. After this I tried using the Animated API of react-native, trying to add a few fade-in/fade-out animations to the controls, which are in a separate <View> from the <Video>, meaning I never included the <Video> component in an <Animated.View>. After failing to properly control these using setTimeout and setInterval, I deleted every line of code regarding these and then I tried the seeking feature again. **Even though the `paused` prop is clearly a true value, the video continues to play**. The reason I am sure of its value, is because I checked using react-devtools. Even the <RTCVideo> seems to have the right value (true). I fixed this by changing the state to `this.state.paused`. Then I tried the app in landscape mode. The bug IS BACK. 

I am beyond going nuts at this point. 

Anyone have an idea how and why?

### Expected behavior
Video should pause when progress/seek bar is tapped/clicked. 

### Platform
Which player are you experiencing the problem on:
* iOS simulator
Using: 
react-native-video 3.2.1
react-native: 0.48.4

### Video sample
A stock .mp4 video from the internet. Forgot source.

**Comment by AlexandruVoica** [comment]
I do not know if it was a problem with my code or not (I still believe it's a bug), but I cleaned up my state and added the seek() into a setTimeout with timeout 0, called **after** a setState and now it works as expected.

I'm closing this and kindly request that this issue be deleted.

**Comment by grifotv** [comment]
had same issue, it solved with the `setTimeot` hack mentioned here https://github.com/react-native-community/react-native-video/issues/1249#issuecomment-424636539

**Comment by itsfaraaz** [comment]
> I do not know if it was a problem with my code or not (I still believe it's a bug), but I cleaned up my state and added the seek() into a setTimeout with timeout 0, called **after** a setState and now it works as expected.
> 
> I'm closing this and kindly request that this issue be deleted.

Thank you, five years later this is still an issue and works.
