### ISSUE TITLE
[Android] Playing local files

### ISSUE THREAD

**Issue by hunteredwards** [TheWidlarzGroup/react-native-video#125]
I have tried this:  `<Video source={{uri: "/storage/emulated/0/test.mp4" }} ....` to no avail, and I was wondering if anyone has had any success playing local files on Android. If so, I would like to know how or if this is currently only available for iOS.

@buhe Is your [pull request](https://github.com/brentvatne/react-native-video/pull/124) trying to fix this?

Thanks.

**Comment by buhe** [comment]
yes !

**Comment by isair** [comment]
Try putting your video file in your Android raw sources folder and then using it as `<Video source={{ uri: 'test' }} />`. I will keep this issue open until the README is updated to state this.

**Comment by hunteredwards** [comment]
@isair the requirement is for playback on video found within the external storage directory, not assets compiled with the app.  Basically, the functionality should mimic playback like found with the Gallery app.  

@buhe do you have a working example of playing back an external resource?

Additionally, has anyone been able to play locally stored videos on either iOS or Android?

**Comment by hunteredwards** [comment]
I figured it out. [This function](https://github.com/brentvatne/react-native-video/blob/master/Video.js#L73-L75) adds the prefix `file://` to the uri. On both platforms, commenting this out and having the absolute path without the `file://` causes the playback for a local file to work as intended. Maybe a bug?

**Comment by buhe** [comment]
Android is ok after comment this , but don't luck at iOS.
My case is I download some online video and cache it ,user don't need download again next playback.

**Comment by hunteredwards** [comment]
@isair since you've added a good amount of the android support, I was wondering if you have managed to get remote URLs to play? I haven't had any success thus far. Any help would be greatly appreciated. Thanks.

**Comment by buhe** [comment]
@hunteredwards  you can try my fork to play external storage video.
I am not android expert, so this fork maybe not unstable..but it is meet my requirement.
"react-native-video": "git://github.com/buhe/react-native-video.git#d872933"

**Comment by ghost** [comment]
When I created Lumpen Radio iOS app using this module a year ago I was able to store local video files under the project root folder in [`src/assets/videos`](https://github.com/jhabdas/lumpen-radio/commit/f82f2c5f84a1c5f2c0396abdc67c60670792c62f#diff-11c044931baa37c1746c6da284613a05). I was happy with this as I envisioned one day being able to leverage the same location for Android.

During the Android support addition [@isair mentioned](https://github.com/react-native-community/react-native-video/pull/103#issuecomment-157237650) video files for Android can be stored under `android/app/src/main/res/raw/`. While I'm extremely grateful for the Android support, the location specified seems less than ideal as it lends itself to duplication of video assets by platform.

Poking through the open PRs I noticed [this promising gem](https://github.com/react-native-community/react-native-video/pull/251), which appears to allow one to leverage the RN asset system to do the resolving and help prevent by-platform file duplication or any kind of funky "cross-the-streams" loading of files for iOS from the Android raw sources folder.

**Keywords**
storage location where to store android video

**Related issues**
https://github.com/react-native-community/react-native-video/issues/246

**Comment by ghost** [comment]
See #251 for loading local files using RN assets system.

**Comment by tadeaspetak** [comment]
Has anyone figured out how to load anything from `/storage/emulated/0...` on Android? I have tried a bunch of things (commenting out adding the `file://` and updating the Java class to use `FileInputStream` when setting src) but to no avail... cheers a ton in advance!

**Comment by valerybodak** [comment]
@tadeaspetak 
Did you resolve issue with load anything from **/storage/emulated/0**...
?

**Comment by seeya** [comment]
Facing the same issues. Keep getting `Trying to load empty source.` even though the file exists. Can confirm as I used `await RNFetchBlob.fs.exists(outputPath)` and it returns true.

**Comment by bd-arc** [comment]
For anyone stumbling upon this issue while trying to load local videos (i.e. native project assets rather than RN static resources), I have a few tips.

In my case, it was a matter of saving precious megabytes for CodePush updates. Indeed, when the videos are part of the RN project's static resources, they will be included in the JS bundle sent to CodePush and retrieved by the users. I'll let you do the calculation, but when you save more than 30 MB per update times 50k users, that counts! Not to mention the enhanced user experience.

To do so, you'll first need to add the video files to your project:

- **Android**: Save your `mp4` files under the directory `android/app/src/main/res/raw`. Note that files in this directory must be lowercase and underscored (e.g. `my_video.mp4`) and that subdirectories are not supported by Android.
- **iOS**: Open Xcode and add your `mp4` files to the project (right-click the project and select "Add Files to [PROJECTNAME]"). Subdirectories are supported by iOS.

Then for the tricky part that cost me a lot of trials and errors:

- **Android**: use the filename as the uri **but don't specify the file extension**.
  - Example: `<Video source={{ uri: 'my_video' }} />`
- **iOS**: it's the exact opposite, meaning **you need to specify the file extension**.
  - Example: `<Video source={{ uri: 'my_video.mp4' }} />`

I didn't find this info anywhere so I thought it could help a frustrated dev or two ;-)

**Comment by ZeeshanAhmadKhalil** [comment]
> For anyone stumbling upon this issue while trying to load local videos (i.e. native project assets rather than RN static resources), I have a few tips.
> 
> In my case, it was a matter of saving previous megabytes for CodePush updates. Indeed, when the videos are part of the RN project's static resources, they will be included in the JS bundle sent to CodePush and retrieved by the users. I'll let you do the calculation, but when you save more than 30 MB per update times 50k users, that counts! Not to mention the enhanced user experience.
> 
> To do so, you'll first need to add the video files to your project:
> 
> * **Android**: Save your `mp4` files under the directory `android/app/src/main/res/raw`. Note that files in this directory must be lowercase and underscored (e.g. `my_video.mp4`) and that subdirectories are not supported by Android.
> * **iOS**: Open Xcode and add your `mp4` files to the project (right-click the project and select "Add Files to [PROJECTNAME]"). Subdirectories are supported by iOS.
> 
> Then for the tricky part that cost me a lot of trials and errors:
> 
> * **Android**: use the filename as the uri **but don't specify the file extension**.
>   
>   * Example: `<Video source={{ uri: 'my_video' }} />`
> * **iOS**: it's the exact opposite, meaning **you need to specify the file extension**.
>   
>   * Example: `<Video source={{ uri: 'my_video.mp4' }} />`
> 
> I didn't find this info anywhere so I thought it could help a frustrated dev or two ;-)

How we can download file in `android/app/src/main/res/raw`

**Comment by acarkaan** [comment]
> > For anyone stumbling upon this issue while trying to load local videos (i.e. native project assets rather than RN static resources), I have a few tips.
> > In my case, it was a matter of saving previous megabytes for CodePush updates. Indeed, when the videos are part of the RN project's static resources, they will be included in the JS bundle sent to CodePush and retrieved by the users. I'll let you do the calculation, but when you save more than 30 MB per update times 50k users, that counts! Not to mention the enhanced user experience.
> > To do so, you'll first need to add the video files to your project:
> > 
> > * **Android**: Save your `mp4` files under the directory `android/app/src/main/res/raw`. Note that files in this directory must be lowercase and underscored (e.g. `my_video.mp4`) and that subdirectories are not supported by Android.
> > * **iOS**: Open Xcode and add your `mp4` files to the project (right-click the project and select "Add Files to [PROJECTNAME]"). Subdirectories are supported by iOS.
> > 
> > Then for the tricky part that cost me a lot of trials and errors:
> > 
> > * **Android**: use the filename as the uri **but don't specify the file extension**.
> >   
> >   * Example: `<Video source={{ uri: 'my_video' }} />`
> > * **iOS**: it's the exact opposite, meaning **you need to specify the file extension**.
> >   
> >   * Example: `<Video source={{ uri: 'my_video.mp4' }} />`
> > 
> > I didn't find this info anywhere so I thought it could help a frustrated dev or two ;-)
> 
> How we can download file in `android/app/src/main/res/raw`

u cant download something to raw folder after build
