### ISSUE TITLE
No option to change the subtitle position in the video

### ISSUE THREAD

**Issue by lakshin** [TheWidlarzGroup/react-native-video#1252]
### Current behavior
The subtitles are displayed on the top of the video as shown in the below image.

![image](https://user-images.githubusercontent.com/9911515/46091435-7da31c00-c1d0-11e8-940e-d62f838b32b1.png)

### Reproduction steps
Create a Video element and set the required text track attributes.

<Video
                  ref={(ref) => {this.player = ref }}
                  source={{ uri: this.state.url}} 
                  paused={this.state.paused}
                  style={this.state.isFullScreen ? styles.videoFullScreen : styles.videoNormal}
                  resizeMode="contain"
                  onLoad={this.videoOnLoad.bind(this)}
                  onProgress={this.videoOnProgress.bind(this)}
                  onEnd={this.videoOnEnd.bind(this)}
                  onBuffer={this.onBuffer.bind(this)}
                  textTracks={this.state.subtitles}
                  selectedTextTrack={{
                  type: "title",
                  value: this.state.selectedTextTrack,
                  volume:{volume}
                }}
                />

### Expected behavior
It's better if the subtitles are displayed on the bottom of the video by default and its really great if there is an option to change the subtitle position

### Platform
Only had the chance to test it in,
* Android ExoPlayer

**Comment by cobarx** [comment]
With VTT files, the author can position the subtitles wherever they want on the screen. If they don't configure a position, they go to the bottom, however I'm guessing your video has them configured.

Feel free to reopen if this isn't the case.

**Comment by lakshin** [comment]
The comment explains the solution. it was pre-configured in the VTT file itself.
