### ISSUE TITLE
audio mixing

### ISSUE THREAD

**Issue by qimus** [TheWidlarzGroup/react-native-video#1254]
### Current behavior
Hi, i have problem with use together react-native-video and react-native-sound components. I need to play sound to use react-native-sound and play video to use react-native-video at the same time, but when Video component was rendering audio from react-native-sound was missing. I found some solution for iOS in react-native-video documentation, but info for android i can't find.

### Expected behavior
react-native-video can play video without catch audio flow or together other app, which can play music

### Platform
* Android

**Comment by luutruong** [comment]
I want this too.

Platform:
* IOS

**Comment by pengcao1** [comment]
@qimus  I think you can try to add the `disableFocus ={true}`
`disableFocus` is set to false default.
 There is only one voice(the video = vioce + picture) can be play at the same time if we request the audio resource(named audioFocus in android),

so, if you want to play more two difference voices at the same time. please set `disableFocus` to true

**Comment by hssrrw** [comment]
Came across the same issue. Turns out, `disableFocus` implemented for Android only https://github.com/react-native-community/react-native-video/search?q=disableFocus&unscoped_q=disableFocus

**Comment by KurtMakesWeb** [comment]
Just ran into this issue, trying to get my video to not pause the background music from other apps in Android. 

Just threw in some Log's into the code and am finding that regardless of setting disableFocus={true} on the Video component, it is still running the "requestAudioFocus" function the first time around. "disableFocus" seems to be false right at first, but then it's true, but by that time the background music has already been paused.

**Comment by KurtMakesWeb** [comment]
I submitted a fix for this issue here: https://github.com/react-native-community/react-native-video/pull/1469

**Comment by imanderson** [comment]
I confirm this fix solves my issue too. Thank you 💪🏽

**Comment by AkramSyed002** [comment]
Hy there I still face the same issue my case I want to play both video and audio as background music in emulator I can have both voice while on real device I can’t here background music voice
