### ISSUE TITLE
Not working on real android device

### ISSUE THREAD

**Issue by UKulikov** [TheWidlarzGroup/react-native-video#1257]
### Current behavior
The video is goind well on emulator, but not working on real device.

Device: Samsung Galaxy S8 
Android: 8.0.0
RN version: Tried 0.55.4, current is 0.57.1 
TargetSdkVersion: Tried 26, current is 27

This issue appears with ExoPlayer. With old android player,video is not working on both platforms. 
With Android MediaPlayer  - on phone get error code -1015,  what: 1, on emulator -2147483648

Situation with ExoPlayer is better, it works for emulators differrent APIs (19-26), but not working on real device.

Error is: 
ReactNativeJS:    { '': 'None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtra
ctor, WavExtractor) could read the stream.',
ReactNativeJS:      errorString: 'Unrecognized
media format' } }

### Platform
Version 3.2.1
* Android ExoPlayer
* Android MediaPlayer

### Video sample
Video url : https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4
Tried with several videos, all have same error.

UPDATE:
Also had tried on Samsung Galaxy Alpha - got error  { error: { extra: -2147483648, what: 1 } }
What i have missed?

**Comment by akyker20** [comment]
I am seeing the same issue. @UKulikov find any work arounds?

**Comment by UKulikov** [comment]
@akyker20 , i have get it to work by chaning to version "react-native-video": "^2.2.0", it has been used in my previous project, and used old player.  It's worked for me.

**Comment by minh-dai** [comment]
same isses :((( 
"react": "16.11.0",
 "react-native": "0.62.2",
