### ISSUE TITLE
Controls don't show up on Android or iOS

### ISSUE THREAD

**Issue by fabdrol** [TheWidlarzGroup/react-native-video#1261]
### Current behavior
When I render a video player with the "controls" flag set to true, controls are not visible on Android and iOS

### Reproduction steps
1. Render a video player component with a HLS stream

### Expected behavior
I expect controls to be visible when I tap the screen

### Platform
* iOS
* Android ExoPlayer

**Comment by abrown1982** [comment]
I'm seeing the same thing.

Installed, added a video to test, all fine.  Added controls={true} but no controls seem to show.

**Comment by ssilverr** [comment]
I'm not seeing the controls on android, only on iOS

**Comment by cobarx** [comment]
See my comments in #1278, ExoPlayer doesn't have controls available. iOS controls show for me in fullscreen, I will have to check when windowed.

**Comment by yazmnh87** [comment]
I'm experiencing this issue, although I'm not playing a video, just an audio file.  I'm currently testing on IOS.
