### ISSUE TITLE
Android ExoPlayer has an overlaid frame when using SurfaceView instead of TextureView by default

### ISSUE THREAD

**Issue by 73R3WY** [TheWidlarzGroup/react-native-video#1263]
### Current behavior
Using the Video component on Android with `useTextureView` using default/unset prop value will cause the Video view to have an overlaying frame on top of the video playing.

### Reproduction steps
Use a Video component and test it with Android devices running Android OS version 6-7

### Expected behavior
The video view will have the video playing without any view on top of the video player view.

### Platform
* Android ExoPlayer
* ONLY ON ANDROID VERSIONS 6.x.x (M) and 7.x.x (N)

### Workaround
* Used `useTextureView={true}` so that the Android native code will use TextureView instead of the default SurfaceView

### Screenshot sample
<img width="825" alt="screen shot 2018-10-05 at 7 39 21 pm" src="https://user-images.githubusercontent.com/8436044/46533216-65b94f80-c8d6-11e8-8dcc-434801d99460.png">

**Comment by cobarx** [comment]
Can you describe what's causing the issue? Is this a situation where you have multiple videos layered on top of each other?

The way SurfaceView works is that it punches a hole through any other views on top of it, so if it's not the top view or there are multiple videos, things get weird. TextureView behaves like a normal view. The reason I made SurfaceView the default is that it potentially has better performance, however a lot of people have issues like this, so I'm open to switching it in the next release.

**Comment by 73R3WY** [comment]
There are no multiple videos layered on top of each other. Although there is a TouchableOpacity with an Image component on top of the Video view component. I tried setting the `zIndex` of the Video view or its container but the overlaid frame is still shown. I also tried removing the other view on top of the Video view. If it adds more information, the Video view is inside a TouchableWithoutFeedback component inside a Fragment:

```Typescript
      <Fragment>
        <TouchableWithoutFeedback onPress={this.props.onPressHandler}>
          {this.state.source != null && (
            <View style={[Style.pressContainer, this.props.videoStyle]}>
              <Loading ref={this._loadingObj} />
              <Video
                useTextureView={true}
                rate={this.state.rate}
                source={{ uri: this.state.source! }}
                style={{ flex: 1 }}
                resizeMode="contain"
                progressUpdateInterval={}
                key={this.state.key}
                onProgress={}
                ref={this._videoObj}
                // onEnd={}
                onLoad={}
                onLoadStart={}
                paused={!this.state.autoPlay}
              />
            </View>
          )}
        </TouchableWithoutFeedback>

        {!this.state.autoPlay! && (
          <View style={Style.playButtonContainer}>
            <TouchableOpacity onPress={this.props.onPressHandler}>
              <Image source={playIcon} />
            </TouchableOpacity>
          </View>
        )}
      </Fragment>
```

**Comment by Ashwin-Mothilal** [comment]
Facing the same issue and why the documentation says [useTextureView ](https://github.com/react-native-community/react-native-video#usetextureview) is true by default?

**Comment by Ashwin-Mothilal** [comment]
Facing the same issue and why the documentation says [useTextureView ](https://github.com/react-native-community/react-native-video#usetextureview) is true by default?
