### ISSUE TITLE
Build/Compiling required for local testing?

### ISSUE THREAD

**Issue by brentluna** [TheWidlarzGroup/react-native-video#1268]
Hi, I wanted to mess around with a fork of this library to try and get DRM support working. 

I was planning on either having my package.json point the package to my github repo or symlink it from inside the app's node_modules. 

Are there any build steps required? I couldn't find anything in the readme. 

Thanks

**Comment by cobarx** [comment]
Add something like this to your package.json:
"react-native-video": "file:../react-native-video",

**Comment by brentluna** [comment]
Thank you for the response @cobarx . I've been spending some time trying to get it to work yet have been struggling. 



```
bundling failed: Error: Unable to resolve module `./../../node_modules/react-native-video/Video` from `/Users/bluna/code/TestProject/components/player/Player.js`: The module `./../../node_modules/react-native-video/Video` could not be found from `/Users/bluna/code/TestProject/components/player/Player.js`. Indeed, none of these files exist:
  * `/Users/bluna/code/TestProject/node_modules/react-native-video/Video(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
```

Yet the react-native-video is symlinked  in the testProject/node_modules, and when I `cd` into it, it does indeed have the Video.js. Any thoughts on what I'm missing?
