### ISSUE TITLE
Exoplayer 2.8.4 "yarn add" installs 2.7.3 

### ISSUE THREAD

**Issue by GroupXTech** [TheWidlarzGroup/react-native-video#1269]
### Current behavior
Node modules installs exoplayer 2.7.3
And when I manually make the changes to the gradle it fails the build.

yarn add react-native-video

update node module to explayer 2.8.4

* Android ExoPlayer

Is there something else I should be doing?

Thanks in advance.

**Comment by cobarx** [comment]
Since the 2.8.4 version isn't released on npm yet, you get react-native-video 3.2.1 which is the latest released version.

Do:
`yarn add react-native-video@https://github.com/react-native-community/react-native-video.git#master`

I expect to have 4.0.0 out by the end of next week.

**Comment by GroupXTech** [comment]
Thanks... Much appreciated.
