### ISSUE TITLE
[feature] Support for playing multiple videos in a sequence

### ISSUE THREAD

**Issue by thsig** [TheWidlarzGroup/react-native-video#127]
Greetings!

It looks like my team will eventually need the ability to play multiple videos in a sequence, so we were thinking of adding that functionality to `react-native-video` and then submitting a pull request.

Before we start with this, I wanted to reach out and ask if you had any ideas on how best to implement this (also with an eye on fitting with the project's existing design and the maintainers' ideas for the project's future development), any potential pitfalls on the way and perhaps the estimated complexity/difficulty level of this task?

Also, in terms of the API, I was thinking the clips could be passed in as an array:

```
<Video source={[
    {uri: "clip1"},
    {uri: "clip2"},
    ...
  ]}
  ...
/>
```

Any opinions on this? Thanks!

**Comment by TylerNoblett** [comment]
+1 I would really like to see this happen, if possible

**Comment by arunraj-qburst** [comment]
Any solution on this ? I am also looking for a solution for this

**Comment by MandapatiBhavani** [comment]
Any Solution for android? i am looking for the this.

**Comment by arunraj-qburst** [comment]
> Any Solution for android? i am looking for the this.

I just listen to the video on end event and updated the source from my video list array. a video index is being used , just increase the count each time the video reaches the end. For my requirement, this was enough.

**Comment by zchwyng** [comment]
Closing this since a solution is provided in the thread.
