### ISSUE TITLE
Cookie handling changes between React Native 0.55 & 0.57

### ISSUE THREAD

**Issue by gtebbutt** [TheWidlarzGroup/react-native-video#1273]
### Current behavior
After upgrading from 0.55 to 0.57, the cookies sent by `react-native-video` are not the same as those sent by `fetch` requests. The video request does send *some* cookies, which suggests to me that there's a synchronisation/update issue rather than a total change of behaviour.

The cookies are set from the root domain and the video request is to a subdomain, which may or may not be relevant (the cookie domain is set correctly, and working fine across the subdomains on web and on RN 0.55).

It's also worth noting that there definitely has been some change in RN's cookie handling in the last couple of versions (see https://github.com/facebook/react-native/issues/19376 and https://github.com/facebook/react-native/issues/19958), but nobody seems to be sure what precisely has changed. I've chased a few dead-ends myself with no luck. 

### Reproduction steps
- Make a `fetch` request that sets a cookie
- Open a video on the same domain (but different subdomain)
- The new cookie will not be sent with the video request

### Expected behavior
As per 0.55, the cookies sent by `react-native-video` remain in sync with those sent by the `react-native` default `fetch` implementation.

### Platform
* iOS

### Video sample
N/A

**Comment by cobarx** [comment]
Good times, it's always nice when new React Native releases cause regressions. It will be awhile before I can get to this, so I'd see if you can track it down and send a PR over.

Version 4.0.0 is going to pretty much require React Native 0.57 FWIW due to the Gradle 3 plugin requirement for the latest ExoPlayer.

**Comment by gtebbutt** [comment]
Understood, that all makes sense. I'll definitely keep looking into it as I get time, but I also wanted to flag it here in case anyone has input or suggestions that might be helpful!

**Comment by gtebbutt** [comment]
After spending some decent time on this, I'm unfortunately no closer to a fix, but I do at least have a workaround. 

I've got things working again by:
- Manually grabbing the `set-cookie` headers from the `fetch` request
- Splitting them back into an array using `set-cookie-parser.splitCookiesString()` (because RN helpfully concatenates them all into a difficult to split single string with ambiguous separators 🙄)
- Explicitly writing each one for the relevant subdomain using `react-native-cookies.setFromResponse()`

In terms of the root cause, I'm drawing something of a blank. There are a few issues regarding multiple `set-cookie` headers on Android, but they don't appear relevant on iOS where I've been testing this. It could be related to changes made in RN to accommodate cookies in the new `WKWebView`, especially since writing to the `react-native-cookies` storage fixes the issue, but I can't see anywhere in the code where `WKWebView` cookie handling should leak into the normal `fetch` requests. It could also be something completely unrelated that I haven't yet spotted among the several thousand commits that make up a React Native release.

**Comment by janet-rivas** [comment]
I have the same issue after migrate from .55.4 to .56 and .57.0 react-native-cookies third part library does not return all my cookies

**Comment by corradio** [comment]
I've submitted this PR that could potentially fix this:
https://github.com/facebook/react-native/pull/22178

**Comment by shangardezi** [comment]
Can someone advise what's the best way to pass cookies into the component?

**Comment by gtebbutt** [comment]
@shangardezi The workaround I mentioned above (parsing the cookie header, and then using `react-native-cookies` to explicitly save the cookie) is working well in production for us. 

It seems that this component and `react-native-cookies` always use the same cookie storage, but the latest versions of React Native itself no longer do so reliably.
