### ISSUE TITLE
implement minLoadRetryCount on ios to reload a video after `onError`

### ISSUE THREAD

**Issue by aalzanki** [TheWidlarzGroup/react-native-video#1274]
### Current behavior
I'm trying to add a retry button that shows up when `onError` gets called. The button shows up as expected, but I can't figure out how to ask the `<Video/>` component to reload/retry. Is it possible to reload the video after it fails loading?

### Reproduction steps
1) Implement a retry button that is only visible after `onError` is called
2) Turn off internet
3) open the app
4) wait for the retry button to show up
5) Tap it (nothing happens, of course, but I'm wondering how I'd get the video to reload here)

### Expected behavior
Reload  the video at step 5.

### Platform
Which player are you experiencing the problem on:
* iOS

Thank you for the help!

**Comment by cobarx** [comment]
Without testing it, either:
* Set the source to null, then set it back to the original source
* Render null instead of a `<Video />`, then render `<Video />` again

It would make sense to have a `reload()` method for situations like this. I'll keep it in mind when adding features. Feel free to submit a PR.

**Comment by aalzanki** [comment]
@cobarx thank you! The second option works (rendering null and then the component again). I'll try to add a reload method when I get a chance!

**Comment by jariwalabhavesh** [comment]
@cobarx :
Actually, **minLoadRetryCount** should be there in ios as well. I facing an issue in case of streaming. When streaming start and I load streaming url in a video then sometime ios giving an error like
```
error:{code:-1008, domain: ""NSURLErrorDomain""}
```

but in case of android I had set **minLoadRetryCount** to **50** so it working without any issue. Is there a specific way to retry loading video in ios

**Comment by alikazemkhanloo** [comment]
any news about this `reload()` function?

**Comment by nathantqn** [comment]
I'm facing same error like @jariwalabhavesh, any update on this streaming problem :( . I already reported details in this thread: https://github.com/react-native-community/react-native-video/issues/1809

**Comment by jariwalabhavesh** [comment]
@nenjamin2405 : No not any update. I had to delay streaming play on video player after studio actually start recording streaming.

**Comment by JorgeVV** [comment]
Passing a different `key` will recreate the component so if you store a key in the state and update it when `onError` is fired it will reload. It's similar to cobarx's second solution without a flash of blank content.

**Comment by d1verseTI** [comment]
Not to bring up a dead thread, but is there a realod now ? I

> Did not try it, but passing a different `key` will recreate the component so if your store a key in the state and update it when `onError` it will reload. It's similar to cobarx's second solution without a flash of blank content.

Tried that but I think the video component is not destroyed and than You end up with 2 than 3 etc. video compoentns
