### ISSUE TITLE
not all Mp4 files plays

### ISSUE THREAD

**Issue by elbakly** [TheWidlarzGroup/react-native-video#1276]
### Current behavior
Describe what happens when you encounter this issue.
I have a list of mp4 , some videos plays and some dont
### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
 using this list below only the second and the third works

```
 videos:[
                {uri:"https://walemah.com/videos/Hindi.mp4"},
                {uri:"https://walemah.com/videos/toystory.mp4"},
                {uri:"https://walemah.com/videos/CookingMeatinaPan.mp4"},
                {uri:"https://walemah.com/videos/PeopleEatingOut.mp4"},
                {uri:"https://walemah.com/videos/HotelBuffet.mp4"},
            ],
```
### Expected behavior
Describe what you wanted to happen
I wanted to run a playlist of videos but i figured out that not all videos works 
### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
included in the sample

**Comment by cobarx** [comment]
I was able to play the first video using both ExoPlayer and MediaPlayer. I would try switching to ExoPlayer since it is better supported.

However, chances are there is some kind of incompatibility where your device doesn't have the right codecs to play that video. I would need to see the logs from Android Studio to say for sure.

**Comment by DISKONEKTeD** [comment]
I am experiencing this same issue on iOS specifically, not android. However, the videos were uploaded on a android device. So i am using the ios simulator to view them and only one video out of three work.

That said, I was under the imrpession android can't play .mov file format, yet my android phone is playing them just fine. So I been seeing/reading contradicting information.

I'm using the default player, whichever that is.

edit: Ok, well for my related issue, the mp4 files uploaded on my android device had spaces in their respective filenames, for the ones that didn't stream on iOS. So i removed the spaces and magically it works now. Really weird.

**Comment by alisa-hui** [comment]
这些视频在我的应用上面都可以播放，但是我们自己的远程的mp4的视频都不能播放，请问是什么原因呢？

**Comment by elbakly** [comment]
@alisa-hui  for me some of mine worked and some not has to do with encoding , try downloading the one online and put it on your remote server and check

**Comment by alisa-hui** [comment]
@elbakly好的，谢谢

**Comment by eladwass** [comment]
I have maybe a similar issue. did you figure it out?
My video does not start from the beginning and jump on the first few seconds. however when playing the exact video in other apps the video plays from the beginning?
