### ISSUE TITLE
No controls on Android exoplayer

### ISSUE THREAD

**Issue by ssilverr** [TheWidlarzGroup/react-native-video#1277]
### Current behavior
No controls are present in android exoplayer. 

```
        <Video
          source={{
            uri: 'https://www.w3schools.com/html/mov_bbb.mp4'
          }}
          style={styles.backgroundVideo}
          paused
          controls
          resizeMode="contain"
          progressUpdateInterval={2500}
        //   useTexturxeView
        />

```
android logs: 
`W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.brentvatne.exoplayer.ReactExoplayerViewManager`
every time the app is opened

the video plays if i take out the paused option. 

<img width="761" alt="screen shot 2018-10-10 at 18 13 42" src="https://user-images.githubusercontent.com/36010813/46750475-52ccc380-ccb8-11e8-8aa2-0b10a5df298b.png">

### Reproduction steps

Running on a Mac

Tried multiple versions of rn-video, no change. 

 "react-native-video": "^3.2.1",
 "react-native": "0.57.1",

tested on (in debug):
   Pixel 2 Xl, api 28, emulator
   Nexus 5X, api 28, emulator
   Huawei honor 7, real device

The Media player works normally (no fullscreen though), if I take out the -exoplayer from 
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')` in settings.gradle

### Expected behavior
Normal controls show, play, pause, fullscreen

### Platform
Which player are you experiencing the problem on:

* Android ExoPlayer

### Video sample

https://www.w3schools.com/html/mov_bbb.mp4

**Comment by cobarx** [comment]
See #1278, we don't have a set of controls for ExoPlayer built at this time, so we can't show them. You will need to build / use someone else's controls.

**Comment by IbrahimSulai** [comment]
Opened a PR (#1414) for showing the controls in Android Exoplayer.
