### ISSUE TITLE
Can not play downloaded file (not assets)

### ISSUE THREAD

**Issue by rayshih** [TheWidlarzGroup/react-native-video#128]
Because of this line:

``` js
const isNetwork = !!(uri && uri.match(/^https?:/));
```

https://github.com/brentvatne/react-native-video/blob/master/Video.js#L77

and this if condition

``` java
            if (isNetwork) {
                setDataSource(uriString);
            } else {
                setRawData(mThemedReactContext.getResources().getIdentifier(
                        uriString,
                        "raw",
                        mThemedReactContext.getPackageName()
                ));
            }
```

https://github.com/brentvatne/react-native-video/blob/master/android%2Fsrc%2Fmain%2Fjava%2Fcom%2Fbrentvatne%2Freact%2FReactVideoView.java#L123

So if the uri is set to `file://....` then it won't play.

**Comment by yamill** [comment]
Yeah i'm having the same issue. I'm trying to play a downloaded file `file:///private/var/mobile/Containers/Data/Application/...` etc... and it won't play. 

@rayshih did you figure out how to fix this?

**Comment by rayshih** [comment]
@yamill I forked one and do some modify about that. I should create a pull request later.

**Comment by gravitinos** [comment]
Hey guys, I was able to play the file by removing the `file://` at the beginning, so it's just `/private/var/mobile...etc`

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.
