### ISSUE TITLE
Buffering issue with ExoPlayer on Android

### ISSUE THREAD

**Issue by funkyfourier** [TheWidlarzGroup/react-native-video#1282]
### Current behavior
Sometimes when I do seek(), the video gets stuck and the onBuffering event says isBuffering is true. Then after about five minutes or so onBuffering says isBuffering is false, and the video resumes playing. This is with both mp4 files and mp3 audio files, but only when they are being played from an online location. When local files are played it does not occur.

I have tried with files from our own server and to test I also tried with this mp3: [https://www.mfiles.co.uk/mp3-downloads/chopin-nocturne-op9-no2.mp3](url)

In LogCat I see this message every time it occurs:

`
D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
W/audio_hw_generic: Not supplying enough data to HAL, expected position 21225938 , only wrote 20695680
`

That last line I only see when the bug occurs, the first one is normal.

### Reproduction steps
Call seek() repeatedly, i.e by sliding a progress bar back and forward.

### Expected behavior
The video probably buffering for a moment, 

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

Occured on Android Nougat, Oreo and Pie, emulator and real devices.

Edit: Using latest release 3.2.1

**Comment by dackmin** [comment]
Same here, without even needing to call seek() repeatedly. One call is enough, but it only occurs with external files as well.

**Comment by funkyfourier** [comment]
Good to know it's not just me. I wonder if #1173 is related, and in that case, will it be solved once 4.0.0 is out?

I tried to upgrade to newest release of ExoPlayer, but it would not build because of appcompat support library version conflicts.

**Comment by dackmin** [comment]
@cobarx when is 4.0.0 rolling out ? Wasn't it already published and unpublished for a particular reason ?

**Comment by cobarx** [comment]
Just released 4.0.0, which has a bunch of HTTP client fixes from OkHTTP 3.11.0. Can you test this again and see how it does.

**Comment by funkyfourier** [comment]
I have tried to reproduce it on both emulator and real device for several minutes without succeeding, so then it is probably safe to assume that it has been fixed.

Also, the bug did not occur nearly as often in the bundled release version.
