### ISSUE TITLE
TypeError:undefined is not an object (evaluating '_reactNative.NativeModules.UIManager. RCTVideo.Contstants')

### ISSUE THREAD

**Issue by EvalGitHub** [TheWidlarzGroup/react-native-video#1289]
![image](https://user-images.githubusercontent.com/26053763/46989097-4a4c1100-d12e-11e8-8d28-61da6069c4d4.png)

**Comment by djw27** [comment]
This is a duplicate (https://github.com/react-native-community/react-native-video/issues/873). Make sure you link the project correctly.

**Comment by ghost** [comment]
How to link with expo?
