### ISSUE TITLE
A new release, pls, so Android code is in npm.

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#129]
Thanks.

**Comment by brentvatne** [comment]
cc @isair

**Comment by isair** [comment]
Sorry, I've been swamped lately. I'll hopefully take a look at the initial issues with the Android implementation, fix them, and release a version this weekend.

**Comment by ghost** [comment]
We are using it in Android and it seems to work, just we must use git url not normal versioning... but sure, I don't know if Android support as it is master needs some tweaks yet before published.
