### ISSUE TITLE
Disable picture in picture in control

### ISSUE THREAD

**Issue by wuuuaaaa** [TheWidlarzGroup/react-native-video#1291]
### Current behavior
When the video is playing there is a Picture in Picture button available. 
May i know how to hide/disable that button?

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by elzii** [comment]
@worldpeach Can you provide a screenshot?

**Comment by wuuuaaaa** [comment]
Hi,

Here is the screenshot of the picture in picture button.

<img width="640" alt="screen shot 2018-11-05 at 11 08 51 pm" src="https://user-images.githubusercontent.com/40857320/48006519-9815d100-e150-11e8-8a1b-9790a49a6521.png">
<img width="644" alt="screen shot 2018-11-05 at 11 09 13 pm" src="https://user-images.githubusercontent.com/40857320/48006520-98ae6780-e150-11e8-8aaa-a07ad4d61378.png">

**Comment by jacklj** [comment]
Any updates on this - is it possible to disable picture-in-picture? Thanks

**Comment by kanikag** [comment]
Any updates?

**Comment by sanjay628** [comment]
I am stuck over here issue can anyone please resolve this ??

**Comment by Masoodvali** [comment]
How to disable the PIP mode, default value is false yet PIP is Enabled How??

**Comment by sanjay628** [comment]
Still no update ?

**Comment by olivierlesnicki** [comment]
+1

**Comment by oduonye1992** [comment]
+1

**Comment by shankarbhai** [comment]
update plz

**Comment by p1yu5h** [comment]
Do we have an update on this? Any workaround?
