### ISSUE TITLE
Media can not play when `paused` status change from true to false

### ISSUE THREAD

**Issue by pengcao1** [TheWidlarzGroup/react-native-video#1292]
### Current behavior
I have embedded `Video` component in my js component(named `Player.js`) like below code snippet 
`
<Video
paused={this.state.paused}
....
/>
`
fist I trigger `this.setState({paused: true})` and 1s or 2s later trigger  `this.setState({paused: false})`

now, `playWhenReady` will be set as false in `ReactExoplayerView` on `onHostResume` method
and front  code `onProgress` does not invoked.

### Reproduction steps
see above

### Expected behavior
media can play auto when `paused` set to false

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
### Video sample
n/a
### key log info 
10-19 19:18:03.063 12183 12183 D ReactExoplayerView: initializePlayer to setPlayWhenReady(true)
10-19 19:18:03.063 12183 12183 D ReactExoplayerView: setPlayWhenReady to set playWhenReady=true
10-19 19:18:03.067  1846  4669 I MediaFocusControl: requestAudioFocus() from uid/pid 10110/12183 clientId=android.media.AudioManager@5e10d66com.brentvatne.exoplayer.ReactExoplayerView{5cbf8a7 V.E...... ......I. 0,0-0,0} callingPack=xxxxx.development req=1 flags=0x0 sdk=26
10-19 19:18:03.068 12183 12183 D ReactExoplayerView: setPlayWhenReady hasAudioFocus = true
10-19 19:18:03.069 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
10-19 19:18:03.078 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
10-19 19:18:03.194 12183 12183 D ReactExoplayerView: onHostResume to setPlayWhenReady true,playInBackground=true,isInBackground=false
10-19 19:18:03.194 12183 12183 D ReactExoplayerView: setPlayWhenReady to set playWhenReady=true
10-19 19:18:03.196  1846  4669 I MediaFocusControl: requestAudioFocus() from uid/pid 10110/12183 clientId=android.media.AudioManager@5e10d66com.brentvatne.exoplayer.ReactExoplayerView{5cbf8a7 V.E...... ......ID 0,0-1080,0 #b77} callingPack=xxxxxxx.development req=1 flags=0x0 sdk=26
10-19 19:18:03.197 12183 12183 D ReactExoplayerView: setPlayWhenReady hasAudioFocus = true
10-19 19:18:03.280 12183 12183 D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@5e10d66com.brentvatne.exoplayer.ReactExoplayerView{5cbf8a7 V.E...... ......I. 0,0-0,0}
10-19 19:18:04.724 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=ready
10-19 19:18:05.471 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
10-19 19:18:05.482 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=ready
10-19 19:18:11.001 12183 12183 D ReactExoplayerView: pausePlayback .. player = com.google.android.exoplayer2.SimpleExoPlayer@bce9a2b,,player.getPlayWhenReady() = true
10-19 19:18:11.002 12183 12183 D ReactExoplayerView: setPlayWhenReady to set playWhenReady=false
10-19 19:18:11.002 12183 12183 D ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=ready
10-19 19:18:11.014  1846  4669 I MediaFocusControl: abandonAudioFocus() from uid/pid 10110/12183 clientId=android.media.AudioManager@5e10d66com.brentvatne.exoplayer.ReactExoplayerView{5cbf8a7 V.E...... ......ID 0,0-1080,0 #b77}

**Comment by mohitbhansali** [comment]
@pengcao1 Did you find any solution for this?

**Comment by pengcao1** [comment]
@mohitbhansali 
override the `ReactExoplayerView`'s `toString` method

**Comment by hungps** [comment]
@pengcao1 Can you tell more specific? Thanks.
