### ISSUE TITLE
ExoPlayer: Audio Plays but Video Frames Not Updating for About 4 Seconds

### ISSUE THREAD

**Issue by FullstackJack** [TheWidlarzGroup/react-native-video#1294]
### Current behavior
After updating the basic android demo to work with Android SDK 28, Gradle 4.6, and Java 8, the provided broadchurch.mp4 file plays fine with the MediaPlayer, but ExoPlayer experiences a stuck video frame for the first 4 seconds of the video sample. The audio is heard playing and finally when the characters enter from the right of the screen, the video track begins rendering video frames from that point forward. Interesting to note, the "stuck" frame is the second shot where the video picks up from. I hope this makes sense.

### Reproduction steps
1. git clone the fork at https://github.com/FullstackJack/react-native-video/commit/0f5af8a789b43ec1a0934221bf5790e1718e9ec2
2. cd examples/basic
3. npm i, react-native run-android.
If you have latest Android Studio and SDK 28 installed, it should compile and install the APK.

### Expected behavior
The video frames should begin rendering from the same place on all platforms and players. There should not be a stuck frame lag.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
broadchurch.mp4

**Comment by paddy57** [comment]
Have you found any solution ?
