### ISSUE TITLE
[Android ExoPlayer] `seek` doesn't work the first time when paused

### ISSUE THREAD

**Issue by hblumberg** [TheWidlarzGroup/react-native-video#1295]
### Current behavior
When a video is paused on Android ExoPlayer, I have to call `seek` twice to get it to actually seek.

### Reproduction steps
1. Pause a video.
2. Call `seek`. [Nothing happens]
3. Call `seek` again. [Seeks correctly]

### Expected behavior
I expect to only have to call `seek` once.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
(It is not happening on iOS as far as I can tell.)

Let me know if I can provide any other details. Thank you!

**Comment by hieuptit93** [comment]
me too

**Comment by firofame** [comment]
"react-native-video": "^4.4.1" - same issue.
do we have any workaround?

**Comment by tonyphpfox** [comment]
Now it's 2021 and I still get this issue :(
