### ISSUE TITLE
Cannot install react-native-video version 4.x

### ISSUE THREAD

**Issue by LuongTruong** [TheWidlarzGroup/react-native-video#1296]
Hi everyone, I know it is kind of ridiculous that I am not able to install the react-native-video version 4.x.

My current React native version: 0.57.3

### Current behavior
I always get the react-native-video version 3.2.1 instead of version 4.x

### Reproduction steps
1/ Create a new react native app: "react-native init DemoVideo"
2/ Every time I use the syntax: "npm install react-native-video" or even "npm install react-native-video@latest". React-native-video version 3.2.1 is installed.

### Expected behavior
There should be the newest version mentioned by you guys: version 4.x

Is the react-native-video version 4.x released? If yes, please let me know the syntax to install it.

Thank you in advance!

**Comment by n1ru4l** [comment]
There is no version 4 published to npm.

**Comment by LuongTruong** [comment]
@n1ru4l : thank you very very much for your quick comment

**Comment by Alanz2223** [comment]
I am sorry kind of new, how do you get version 4 and update it on your package.json?
