### ISSUE TITLE
The sound of the video is too quiet

### ISSUE THREAD

**Issue by drmmyx** [TheWidlarzGroup/react-native-video#1299]
i currently playing a mp4 video with this devices. 
i turn the phone volume to the maximum and i only barely hear somethings clear 
```
 <Video
                    source={{ uri: uri }}
                    style={styles.video}
                    muted={false}
                    repeat={true}
                    resizeMode={"cover"}
                    volume={5.0}
                    rate={1.0}
                    ignoreSilentSwitch={"obey"}
                />
```
try to change the volume to higher but i dont think it got any effect

**Comment by cobarx** [comment]
The max volume you can set is 1.0. Have you tested this video in other players to see if it is quiet there as well? We can't do anything if the audio is naturally quiet.
