### ISSUE TITLE
Rename component to something that includes audio too

### ISSUE THREAD

**Issue by johanneslumpe** [TheWidlarzGroup/react-native-video#13]
Since we are leveraging `AVPlayer` under the hood, playing audio just works fine too. Same rules apply. So It might be nice to rename the compoent to `AudioVideo` or something or just `Media` so people can easily understand that they can also play mp3s with this.

**Comment by brianchirls** [comment]
I'm all for supporting audio, but consider that audio does not require any display. So this raises the question of what it should look like if there's no video track.

**Comment by johanneslumpe** [comment]
Well it wouldn't display anything I guess. Right now you won't see anything. So you could just create a style which sizes the player to a height of 0. And then you'd just add you own custom controls to interface with it. How does that sound?

**Comment by johanneslumpe** [comment]
Or we could allow the user to pass in a static image, which gets displayed while playing the file. But I think not displaying anything should work for now

**Comment by brianchirls** [comment]
Yes, I think not displaying anything for now is the way to go. And I think
let's also assume custom controls as well. Player controls that make
everybody happy are hard/impossible to get right, and people almost always
want to customize them.

**Comment by mwilc0x** [comment]
So does it make sense to have the audio be combined with video?

I think for someone looking to use this module, a simple default controls setup would go a long way. Then, could give the ability to customize their own layout. 

I'm thinking of a use case where I have ~20 of mp3 URL strings I would want to pass to this component. Then, I could play/pause the current track and go back and forth throughout the array of URL's to listen. 

What do you guys think?

**Comment by brentvatne** [comment]
@mjw56 - agreed that this would be very useful, what would the ideal API for that look like to you? eg: `<Audio tracks={this.state.tracksArray} />`?

**Comment by mwilc0x** [comment]
@brentvatne hey, yeah I was thinking of passing in an array. I guess it could accept a single string too and just convert that to an array?

What do you think?

**Comment by johanneslumpe** [comment]
We could maybe call it `playlist`?

**Comment by johanneslumpe** [comment]
Also @mjw56 I don't see any issue why we shouldn't merge audio and video into a single component
because the underlying AVPlayer can take care of both and the default controls should also be applyable to both media types.

**Comment by mwilc0x** [comment]
Ok, would it potentially look something like this?

``` javascript
var Media = require('react-native-media');
var { Audio, Video } = Media;
```

**Comment by brentvatne** [comment]
@mjw56 - I like that

**Comment by brentvatne** [comment]
@mjw56 - definitely something to consider going forward, we are going to focus on getting the `Video` component working great and then look at this again. Something like `<Media>` element or `<Audio>` `<Video>` could work, we'll just have to see.

**Comment by brentvatne** [comment]
Closing this, discussions will continue in #14 :smile: :+1: :100:

**Comment by mwilc0x** [comment]
Ok, btw right now I am doing it where I handle the successive playbacks from the component level. I have the playlist track data in a flux store which I can then query from when a song ends, skip track, etc. This approach is working really nicely. It would be nice though to have playlist support in the future. Overall this component works great for handling .mp3 url's. :) I need to test it out some more using some other audio file types.

**Comment by csakon** [comment]
@mjw56 I attempted to upload a .mp3 into my project with no luck, I can only use mp4s. How did you manage to get mp3s to work?

**Comment by mwilc0x** [comment]
@csakon I'm currently only using mp3's loaded from URL's. I haven't tried with mp3 files from disk yet. I don't see why that shouldn't work though?

**Comment by csakon** [comment]
@mjw56 mp3 files from disk don't work, a red react native error pops up saying something about expecing an mp4 at the src. However, I found an iOS app that will let you export audio into mp4 and that works like a charm. I also learned that the names for the uri are case sensitive.

**Comment by jonaswindey** [comment]
@mjw56 can you share a gist with an example to load mp3(s) from an external url?

**Comment by jasecoop** [comment]
@mjw56 @csakon I've had the same problem with loading mp3's from disk. Doesn't work. Bit of a shame, as mp4 increases the file size.

Curious why this would work with a url but not locally... Any ideas?
