### ISSUE TITLE
Audio Tracks missing for android onLoad

### ISSUE THREAD

**Issue by evanjmg** [TheWidlarzGroup/react-native-video#1300]
### Current behavior
I get no audio tracks for video with audio, onLoad should have audioTracks for android as it says all platforms in readme

### Reproduction steps
onLoad={(payload) => console.log(payload)}

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* Google Pixel XL, 8.1.0

### Video sample
Any .mp4 video with audio, just use this silly penguin video https://www.youtube.com/watch?v=RY9FRdl7dq0 use this https://youtubemp4.to/ to convert and download mp4 - video and audio work, but no audio tracks are provided

**Comment by cobarx** [comment]
The README is indicating that onLoad exists for all platforms, but not all platforms will have all the fields unfortunately. All ongoing work that I'm doing is only for Android ExoPlayer, if you want support on Android MediaPlayer you are welcome to submit a PR however I'm not doing any new development for it anymore.

**Comment by evanjmg** [comment]
I'm not a Java programmer unfortunately; this is how far I got, but the callback isn't firing and it's loading the entire video again - https://stackoverflow.com/questions/53503522/react-native-android-detect-sound-exists-on-remote-video-url

**Comment by evanjmg** [comment]
This also does not work for mp4s for ios  (4.2.0)
