### ISSUE TITLE
where is version 4.0.0 or when will be released ?

### ISSUE THREAD

**Issue by birkanozekan** [TheWidlarzGroup/react-native-video#1307]

**Comment by Alanz2223** [comment]
same thing i asked and no response as well.. v4 is not available through NPM and there is no mention on how to actually obtain it in the updating documentation

**Comment by mxmzb** [comment]
@holospeed master branch is currently 3.2.1 on github though.

**Comment by birkanozekan** [comment]
Thanks.
I understand that README content goes ahead of the current branch. 
So we didn't miss anything.
