### ISSUE TITLE
Solution of Memory Leak On Android

### ISSUE THREAD

**Issue by linguokun1** [TheWidlarzGroup/react-native-video#1308]
Just append two lines code in the source java code can solve it.
![relovememleak](https://user-images.githubusercontent.com/16397362/47764584-cafb3780-dd00-11e8-8bfe-a82dcbcf3b42.jpg)

**Comment by linguokun1** [comment]
These two lines code can solve two memory leaks on Android

**Comment by Winglonelion** [comment]
Can you describe your problems and your solution more clarify ?

**Comment by linguokun1** [comment]
@Winglonelion
Two lines code that the arrow point to can solve memory leak on Android phone. 
If lack of these two lines code, the "react-native-video" will leak to serious memory leak on Android phone.
Leakcanary can reproduce these memory leak easily.

**Comment by Winglonelion** [comment]
I think you should create a PR, i will test it and reply soon 👍

**Comment by linguokun1** [comment]
@Winglonelion  I have created a PR, two line codes solve the memory leak, and the try catch solve the crash on XiaoMi M4 Phone(may be  the same to other few phones on kitkat) when call mp.selectTrack(0);
