### ISSUE TITLE
Android Rotation Issue

### ISSUE THREAD

**Issue by scgough** [TheWidlarzGroup/react-native-video#131]
Hi
I have the player working in an app. On Android though, when I rotate the screen from portrait to landscape the video is squashed in the bottom half of the screen (see image). The player works fine with iOS

```
<View style={styles.fullScreen}>
      <Video 
             ref="VIDEO_WINDOW"
             source={{uri: this.state.source}}
             style={styles.fullScreen}
             rate={this.state.rate}
             paused={this.state.paused}
             volume={this.state.volume}
             muted={this.state.muted}
             resizeMode={this.state.resizeMode}
             onLoad={this.onLoad}
             onProgress={this.onProgress}
             onEnd={this._onEnd}
             repeat={false} />
         </View>
```

_resizeMode = 'contain'_

Styles:

```
fullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
```

![screenshot_2016-01-21-10-37-55](https://cloud.githubusercontent.com/assets/3042561/12478273/f5738e8a-c02b-11e5-9808-cfe39e688641.png)

PS - I've tried this on a Samsung Galaxy S3 (Android 4.4) and a Moto G (Android 5.0.2)

**Comment by DonnieWest** [comment]
I'm experiencing the same bug on Android 6.0.1 on my Nexus 5

Any workarounds?

**Comment by ejb1123** [comment]
I am also having this issue. Did anyone figure out how to fix it?

**Comment by rameshvishnoi90904** [comment]
Please Help!!! @brentvatne

**Comment by jallens** [comment]
Please Help!!! @brentvatne @isair

**Comment by vinayr** [comment]
I use a workaround like this -

```
  _onLayout = event => {
    const { width, height } = event.nativeEvent.layout;
    if (width > height) {
      this.setState({resizeMode: 'stretch'});
    } else {
      this.setState({resizeMode: 'contain'});
    }
  }
```

**Comment by izakvandermerwe** [comment]
@vinayr Thanks for the snippet! Been battling with this for a few hours.

**Comment by DonnieWest** [comment]
@sjchmiela is there a reason this was closed? The behavior is still quite different from iOS vs Android

**Comment by sjchmiela** [comment]
Sorry then, thought the snipped is the solution.

**Comment by yaraht17** [comment]
Anyone can help me! I have same issues.

**Comment by zchwyng** [comment]
Closing this since it's outdated.

**Comment by olarid** [comment]
Having the same issue right now...

**Comment by olarid** [comment]
Got it work correctly by using Dimensions.get('window').width and Dimensions.get('window').height for the width and height of the video styling
