### ISSUE TITLE
UI thread gets blocked on iOS when loading text tracks 

### ISSUE THREAD

**Issue by lakshin** [TheWidlarzGroup/react-native-video#1313]
### Current behavior
When textTracks prop is present with an array of subtitles (I had 3 subtitles) it freezes the app and takes about 5-10 seconds to load the video component. Works fine in android.

### Reproduction steps
Set textTracks prop with subtitles and load a video is IOS

### Expected behavior
If it takes time to load should load the text track asynchronously without without blocking the UI as its done in android. 

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by ma-pe** [comment]
We are experiencing the same :(

**Comment by allinelara** [comment]
I have the same issue

**Comment by berkcoker** [comment]
I have the same issue when just loading audio...

**Comment by aevzp** [comment]
The same

**Comment by edferreira** [comment]
I have the same issue

**Comment by antoniohansen** [comment]
Hi guys any news on this issue? I'm facing the same problem and it's quite anoying.

**Comment by jfbn** [comment]
Almost 2 years later and this issue still persists. Loading textTracks onto the video component freezes the UI thread.

**Comment by ghost** [comment]
The same issue here. UI is blocked on Android and iOS while buffering with props `textTracks` and `selectedTextTrack`.

**Comment by nizar-banna** [comment]
Same issue here
