### ISSUE TITLE
[Android, ExoPlayer] Infinite buffering after cancelling okhttp connections when using HTTP/2.0 (e.g. AWS's S3 + CloudFare)

### ISSUE THREAD

**Issue by ddudek** [TheWidlarzGroup/react-native-video#1315]
### Current behavior
Videos can't re-start (infinite "buffering") when using videos hosted on AWS's S3 + cached by CloudFlare. The same video hosted on another simple web server loads just fine each time, no matter how many times I try removing/adding the video component, or restarting the app.

Other android player in a native app works just fine for the same videos, iOS loads fine as well.

### Reproduction steps
Reproducible each time, but only in particular circumstances, or state of the cloud/cache (e.g I can reproduce it consistently in Poland, in the morning, but I cannot reproduce it in the afternoon). Steps:
1. upload the same file to AWS S3 + CloudFare and to a simple webserver.
2. Start an app with 2 video components in the main view (example project attached)
3. Videos start playing
4. Get out of the app using "back" button, open the app again (or just remove the view and add it back again without closing the app)
5. Repeat 3 & 4 few times

Result: the video hosted on AWS S3 + CloudFare stops starting after 1st or few times, other video starts fine each and every time.

Video recording reproducing the issue: https://drive.google.com/file/d/1Wfxr6GkZFfP2-WM4hHSfiiwYBritt4mN/view

Example project used to reproduce issue: [bug_infinite_buffering_src.zip](https://github.com/react-native-community/react-native-video/files/2556644/bug_infinite_buffering_src.zip)

Log file: [bug_infinite_buffering_log.log](https://github.com/react-native-community/react-native-video/files/2556678/bug_infinite_buffering_log.log)

### Expected behavior
Videos should start each and every time.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

react-native: 0.56.0
react-native-video: ^3.2.1

### Video sample
Loads fine:
'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_20mb.mp4',
'http://handcraftedmobile.com/sample_dev_videos/bunny.mp4',
'https://handcraftedmobile.com/sample_dev_videos/bunny.mp4',
'https://handcraftedmobile.com/sample_dev_videos/bunny-big.mp4',

Has trouble reloading:
'https://vid.twinbody.com/1811/bunny-big.mp4'
'https://vid.twinbody.com/1811/bunny.mp4'
... and other private videos hosted the same way as the one above

Please help me find the issue, any suggestions how to debug it appreciated.

**Comment by ddudek** [comment]
Hm, the difference between these host is that AWS host uses HTTP/2, while my host uses HTTP/1.1, which lead me to this issue: https://github.com/square/okhttp/issues/3915

I enforced HTTP/1.1 as follows makes the issue not reproducible: https://github.com/ddudek/react-native-video/commit/5bb797f5093013da213be1b2974278e86beb2a65

**Comment by cobarx** [comment]
Please test again with 4.0.0 which includes OkHTTP 3.12.0. The 3.11.0 release of OkHTTP has a bunch of fixes for issues related to this.
