### ISSUE TITLE
`onAudioFocusChanged` event missing in README

### ISSUE THREAD

**Issue by guilhermedeoliveira** [TheWidlarzGroup/react-native-video#1316]
At the basic example file `index.android.js`, there is an event `onAudioFocusChange` that is missing in the documentation.

**Comment by n1ru4l** [comment]
@guilhermedeoliveira Feel free to send a pull request that adds the documentation.

**Comment by guilhermedeoliveira** [comment]
@n1ru4l ok!

**Comment by guilhermedeoliveira** [comment]
PR #1331
