### ISSUE TITLE
AVFoundationErrorDomain code: -11800 with https on iOS

### ISSUE THREAD

**Issue by Sin-** [TheWidlarzGroup/react-native-video#1317]
### Current behavior
On iOS the video does not play, the onBuffer function is called once with this data:
`{isBuffering: false, target: 969}`
And then the onError function is called with this data:
`{error:code: -11800, domain: "AVFoundationErrorDomain"}, target: 969}`

The video is played successfully on Android.

### Reproduction steps
- Create a new react native project
- Install and link (manually because cocoapods created issues in my project) the library 
- Try to play Big buck bunny:
````
<Video
  source={{
    uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  }}
  onBuffer={onBuffer}
  onError={onError}
  style={{ width: constants.screenWidth, height: constants.screenWidth * 0.55 }}
/>
````
### Expected behavior
The video would play

### Platform
* iOS

### Video sample
https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by mitevdev** [comment]
it works by me but I get the same error with another URL.

**Comment by yernandus** [comment]
I am having this for local downloaded file

**Comment by Strate** [comment]
@yernandus Hi, I've got exactly the same issue, for local downloaded file. Did you solved this somehow?

**Comment by Sin-** [comment]
I had to come back to the commit before installing the lib and reinstalled it completely which solved the problem. So, don't really know what happened.

**Comment by SamiChab** [comment]
I have the error only on my iPhone simulator, but not on real device...
`react-native-video@5.0.2`

**Comment by dnosk** [comment]
Same here, reopen the issue?
`react-native-video@5.0.2`

**Comment by jacklj** [comment]
Same here, have this problem on iOS simulator, but not on a physical device. Version 5.0.0 and 5.0.2

**Comment by Shabnam-Veranloo** [comment]
i have issue in react-native-video@4.4.5 too(ios)

**Comment by wsrast** [comment]
I'm seeing this problem intermittently. I had some luck adding the `type: "mp4"` to the `source` prop of the video tag, but that was a red herring, it seems. This problem is back for me in version 5.0.2, after playing just fine for quite a while.

Doing some digging in the issues here, I found several related items:

https://github.com/react-native-community/react-native-video/issues/275
(http vs. https issue suggested)
https://github.com/react-native-community/react-native-video/issues/1886
(encoding issue suggested)
https://github.com/react-native-community/react-native-video/issues/1940
(no cause suggested)
https://github.com/react-native-community/react-native-video/issues/2044
(no suggestions)

This seems to be a prevalent and continuing issue. Why is this closed?

**Comment by ahtokca** [comment]
iOS Simulator of iPhone 11

```
{"error": {"code": -11800, "domain": "AVFoundationErrorDomain", "localizedDescription": "The operation could not be completed", "localizedFailureReason": "An unknown error occurred (1718449215)", "localizedRecoverySuggestion": ""}, "target": 11939}
```

react-native-video@5.1.1 :(

**Comment by katiachumakova** [comment]
Same issue here, why is this closed?

**Comment by katiachumakova** [comment]
> I have the error only on my iPhone simulator, but not on real device...
> `react-native-video@5.0.2`

Same issue here, why is this closed?

**Comment by carlosedof** [comment]
lots of requests from the same issue, no solutions yet. its time to move on to a better lib where at least we have some response from creators.

**Comment by AndresTIY** [comment]
Same issue happening here. Right now it seems to only happen in production, I'm not able to recreate it locally yet.
Using mp4 streaming from Cloudfront. Source object looks like:

```
 source={{
              uri: videoItem.url,
              type: videoItem.type,
            }}
```

**Comment by muhammadhurali** [comment]
After scratching my head around this, I replaced the video URL which I was getting from the server and placed a dummy video URL from the internet. The video started playing. I think this has something to do with the video conversion or generation at the application backend, this package is working ifine.

**Comment by AndresTIY** [comment]
@muhammadhurali Would you happen to know how the video should be converted? We're using Cloudfront to handle this conversion.

**Comment by shpetimselaci** [comment]
Same issue here.

**Comment by PeterOla** [comment]
I just found out my issue was caused because the video url has an http:// and not https://

**Comment by sushilbansal** [comment]
i think i might have a solution if you control the video upload yourself on your server. Try this metadata while uploading video on the server:
contentType: 'application/gzip'
and do not set any encoding. Not sure if you do not control the videos uploading then how it can be managed.

**Comment by nborkhataria** [comment]
@sushilbansal , Issue is with streaming video on iOS device from server, not with uploading to server. Are you able to stream video from server to iOS device ?

**Comment by Beyazatli** [comment]
same issue "AVFoundationErrorDomain 11800" on any iOS simulator.

**Comment by sushilbansal** [comment]
@nborkhataria : you will see a difference with videos uploaded using contentType: 'application/gzip' and without this option. Try it out. I tested it and videos uploaded with {contentType: 'application/gzip'} do not get shown on ios and gave me AVFoundationErrorDomain code error.

**Comment by gerryfletch** [comment]
Intermittent for me too. Restarting the simulator sometimes fixes it.

**Comment by raghvendra007** [comment]
when I used https URLs instead of http URL then it worked

**Comment by hebertporto** [comment]
Same here, remote URL only with HTTPS

**Comment by arnelamo** [comment]
I suddenly got this problem, and I tried to reload the app and restart the dev server, with no luck.
What worked for me was to quit and restart the simulator, restart the dev server - then everything was fine. Seems to be a problem with the iOS simulator.

**Comment by trickyc0d3r** [comment]
same here. is it can play .flv stream on ios?

**Comment by vishv-unjiya** [comment]
I'm encountering an issue where some videos on iOS are failing to load and giving the following error:

`{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 4792}`

The videos that fail are MP4 files served over HTTPS, and the error seems to occur inconsistently. I've verified that the source URLs are correct, and some videos load fine while others throw this error.

Here’s the code I’m using for the <Video> component:

```
<Video
  ref={ref => {
    if (!videoRefs.current) {
      videoRefs.current = {};
    }
    videoRefs.current[videoId] = ref;
  }}
  source={{ uri: item?.video }}
  style={styles.videoPlayer}
  resizeMode={'contain'}
  paused={!isActiveVideo || paused}
  controls={false}
  repeat={true}
  onLoadStart={() => {
    if (typeof updateVideo === 'function') {
      updateVideo(videoId, { loadStartTime: Date.now(), isReady: false });
    }
  }}
  onLoad={data =>
    data && typeof handleVideoLoad === 'function'
      ? handleVideoLoad(data, videoId)
      : null
  }
  onError={error =>
    typeof handleVideoError === 'function'
      ? handleVideoError(videoId, error)
      : null
  }
  onBuffer={data =>
    data && typeof handleBuffering === 'function'
      ? handleBuffering(data.isBuffering, videoId)
      : null
  }
  onReadyForDisplay={() => {
    if (typeof updateVideo === 'function') {
      updateVideo(videoId, { readyForDisplayTime: Date.now(), isReady: true });
    }
    if (isActiveVideo && typeof updateVideo === 'function') {
      setTimeout(() => {
        updateVideo(videoId, { isPaused: false, autoPlayTriggered: true });
      }, 0);
    }
  }}
  // other props...
/>
```

I’m not sure what might be causing the issue, as the video files themselves are valid MP4s served over HTTPS. It's also worth mentioning that this only happens on iOS devices, not on Android.

Has anyone experienced something similar, or do you have any insights on what could be going wrong here?

Thanks in advance!
