### ISSUE TITLE
Can't play in android

### ISSUE THREAD

**Issue by wengbenjue** [TheWidlarzGroup/react-native-video#132]
Android can't play

**Comment by MrJacobJunker** [comment]
I also have problems using android both on my own project and using the example project.

**Comment by tal952** [comment]
+1

**Comment by doostin** [comment]
I'm also having issues in Android, I can't even get the events to fire so it just seems to be silently failing.

EDIT: My project was using RN 0.18.1, I updated to 0.19.0 and the video is now playing.

**Comment by tklivan** [comment]
+1

**Comment by lsgrep** [comment]
+1

**Comment by peng051410** [comment]
+1

**Comment by Naoto-Ida** [comment]
+1

Although I have managed to play an external video.
Even when placing the video in the resources folder, I still can't play local files.
(0.22.2)

**Comment by kmiloaguilar** [comment]
@Naoto-Ida I have the same behaviour. I can play external videos but no local videos similar to the example.

**Comment by Naoto-Ida** [comment]
@kmiloaguilar 

It now works for me. I'm on `0.25.1`.
Make sure all the packages are part of the Android project.
Also, turns out that symbolic links don't work...
I had a .mp4 in the root folder, and Android Studio doesn't seem to like that(?).

I have my file in the `res/raw` directory.

**Comment by kmiloaguilar** [comment]
@Naoto-Ida my react-native version is `0.28.0`.
What all packages do you mean? I have the react native video added in there, since I have already test with external framework. 

I took out the video from the root and added into an assets that I have in the root. My thinking over this one is that you need to let know the android app about this video as an asset. And I am not sure how to add this.

**Comment by Naoto-Ida** [comment]
@kmiloaguilar What I mean is, did you add all the stuff you need to add in `build.gradle`, etc.?

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by xiongpinli** [comment]
![111](https://cloud.githubusercontent.com/assets/15320529/20713023/a33fe2a6-b681-11e6-8a58-6907dacea22d.png)
I can play the local video in this way, but if I change the uri by file:///storage/sdcard/Android/data/项目名字/files/learn-resource/android-2-17-4-3/video/by_taxi1.mp4。it can't play,why? the uri is same,just change the form.

**Comment by evanjmg** [comment]
Same here
