### ISSUE TITLE
Video does not take up entire space

### ISSUE THREAD

**Issue by willds40** [TheWidlarzGroup/react-native-video#1321]
### Current behavior
When video loads, video leaves a border around it. Even when set to take up the entire space of the container, there is still empty space around the video. 

https://user-images.githubusercontent.com/14314808/48285417-8bcf9380-e430-11e8-8f34-d0dc1a129e01.png

### Reproduction steps

**Styles** 

  videoPlayer: {
    position: 'absolute',
    top:0,
    left: 0,
    bottom: 0,
    right: 0,
  },
video_player_container: {
    flex:.4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.black,
  },

**Video player render function** 

<View style={this.state.fullScreen === true ? styles.video_player_container_fullscreen : styles.video_player_container}>
            {this.state.spinnerVisible !== true || this.props.hidden ? null :
            <View style={[styles.activityContainer, styles.activityHorizontal]}>
              <ActivityIndicator size="large" color={Colors.primary_red} />
            </View>
            }
            {this.captionsLoaded() ?
              <Video
                audioOnly={this.props.AvType==='audio' ? true : false}
                ref={(ref) => {
                  this.player = ref
                }}
                source={{uri:mediaItem.url}}
                style={styles.videoPlayer}
                textTracks={
                  this.captionsExist() ?
                    [{
                      title: "English",
                      language: "en",
                      type: "text/vtt",
                      uri: this.state.captionsFilePath
                    },
                    {
                      title: "empty",
                      language: "en",
                      type: "text/vtt",
                      uri: this.state.emptyCaptionFilePath
                    }]
                    : null
                }
                selectedTextTrack={this.state.captionsFilePath ? this.state.captions : null}
                rate={this.state.rate}
                paused={this.props.paused}
                volume={this.state.volume}
                muted={this.state.muted}
                resizeMode={this.state.resizeMode}
                onProgress={this.onProgress}
                onLoad={this.onLoad}
                onEnd={this.onEnd}
              />
              : null
            }

### Expected behavior
Video takes up entire space of container. 

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by cobarx** [comment]
I haven't encountered this problem before. Which resize mode are you using?

**Comment by willds40** [comment]
I was using "contain" and the was definitely the issue. I apologize. I am not sure how we missed that,

**Comment by cauyyl** [comment]
> I was using "contain" and the was definitely the issue. I apologize. I am not sure how we missed that,

I was use 'content', and the video is at the top-left of the screen. 'contain' has fixed this problem.

**Comment by Murtala-1** [comment]
use a 'cover' on the resizeMode instead of 'content'
resizeMode="cover"
