### ISSUE TITLE
`Seek` jumps to the wrong position

### ISSUE THREAD

**Issue by tleewu** [TheWidlarzGroup/react-native-video#1322]
### Current behavior
I'm currently using `react-native-video` to play an online audio URL. I'm trying to seek to a specific position after my video loads (through the `onLoad` callback). The `seek` function works, but it's off by like 6 seconds.

I'm seeking to 100s, but in actuality, it begins playing at like 94s. However, when I log the `data` from the `inProgress` callback, it says the video is playing at 100s.

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
https://secure-hwcdn.libsyn.com/p/d/a/b/dab854701edf5816/Acquired_-_Behance_V2.mp3?c_id=23661376&cs_id=23661376&expiration=1541894047&hwt=4175afb70d5f74a0d64791a45eba906d

**Comment by tleewu** [comment]
Seems related to this issue: https://github.com/react-native-community/react-native-video/issues/452

But this issue seemed inconclusive.

**Comment by geroale** [comment]
Same issue here.
