### ISSUE TITLE
Audio only, no Video

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#1323]
I am trying to play a Video on the iOS simulator (v11.4) linked to VS Code IDE, but all i hear is the audio. I am using .mp4 files from aws S3 which play fine on the simulator's video player and every other player on the mac and on the web. Interstingly i also hear the just audio from .m4v files, but no video still. Right now in its simplest form i'm doing this:

render() {
  return(
         <View>
              <Video
                  source={{uri: 'https...........file.mp4'}}
              />
         </View>
  );
no StyleSheet.

Why no video? Just a blank white screen playing the audio.

**Comment by cobarx** [comment]
Without the stylesheet, the video has no idea how big it should be, so nothing is drawn.

**Comment by waheedakhtar694** [comment]
i am having the same issue but i have also passed the stylesheet i can listen the audio but video only shows black screen, i am not using expo player.

**Comment by chai86** [comment]
Play with the StyleSheet (eg. Flex, alignContent) and for me the video came into view

**Comment by waheedakhtar694** [comment]
here is my code on IOS it is working fine but on android it been showing this black screen with audio i can listen the audio in the background but video is not been displayed.
i tried with expo-player but i have another library **react-native-track-player** and expo-player conflicting with it and as a result application start crashing but on old player app is not crashing but is show this black screen with audio.
![Here is a screenshot](https://user-images.githubusercontent.com/45425486/69545645-045daf80-0fb4-11ea-958d-bddeb064d249.jpeg)


```return (
        <View style={styles.container}>
          <Video
            // controls
            // source={{ uri: this.props.url }}   // Can be a URL or a local file.
            source={{ uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' }}   // Can be a URL or a local file.
            ref={(ref) => {
              this.player = ref
            }}
            // pictureInPicture
            // paused={this.state.paused}
            // onLoadStart={this.loadStart}// Store reference
            // onBuffer={this.onBuffer}                // Callback when remote video is buffering
            // onError={this.videoError}               // Callback when video cannot be loaded
            style={styles.backgroundVideo}
            // resizeMode='contain'
            // useTextureView={false}
           />
        </View>
    )
  }
}

const styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    height: 200,
    width: 200
  },
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1
  }
})

**Comment by waheedakhtar694** [comment]
Any update on this ?

**Comment by ashwinimirajkar** [comment]
Remove android:hardwareAccelerated="false" from AndroidManifest.xml file

**Comment by waheed25** [comment]
@ashwinimirajkar Already fixed

**Comment by githubvisiontrek** [comment]
i am facing this issue as on ios only voice coming but no video black screen

**Comment by Milo00123** [comment]
I am having the same issue here any update ?

**Comment by vishalyad16** [comment]
I’m facing an issue where a white blank screen appears, and when I click on the screen, I can hear the sound of the recorded video, but the video itself is not visible on **IOS**.

The video URL path after recording : - file:///private/var/mobile/Containers/Data/Application/7246E127-F961-4CCC-B635-7858B01B62F9/tmp/78F67FAD-3B00-49F8-968E-87AAC0E600A2.mov

@KrzysztofMoch @moskalakamil  @iceu-bb @freeboub  @waheed25  @ashwinimirajkar

**Comment by vishalyad16** [comment]
I've tried updating the SDK to the latest version, but the issue still persists. Is there any update on this?"
@KrzysztofMoch @moskalakamil @iceu-bb @freeboub @waheed25 @ashwinimirajkar

**Comment by vishalyad16** [comment]
Just following up on this—waiting for your reply, it's urgent. Appreciate your prompt response!
@KrzysztofMoch @moskalakamil @iceu-bb @freeboub @waheed25 @ashwinimirajkar

**Comment by moskalakamil** [comment]
@vishalyad16, @Milo00123 could you share your component code?

**Comment by vishalyad16** [comment]
> @vishalyad16, @Milo00123 could you share your component code?

`import React, { useState, useRef } from 'react';
import { View, TouchableOpacity, StyleSheet,Image } from 'react-native';
// packages
import Video from 'react-native-video';
import Slider from 'react-native-slider';
//components
import MyText from '../../components/atoms/MyText';
//assets
import colors from '../../assets/colors/colors';
import pausemp4 from '../../assets/images/pausemp4.png'
import playmp4 from '../../assets/images/playmp4.png'
//utils
import { Dimension } from '../../utils/config';

const CustomControls = ({ videoUrl }) => {
    //var:useRef
    const ref = useRef();
    //hook:useState
    const [visible, setVisible] = useState(false);
    const [paused, setpaused] = useState(false);
    const [progress, setProgress] = useState({ currentTime: 0, seekableDuration: 0 });
    const [fullScreen, setFullScreen] = useState(false);
    const screenWidth = Dimension.width;
    const screenHeight = Dimension.height;
    //Function:To handle format timer
    const format = seconds => {
        let mins = parseInt(seconds / 60).toString().padStart(2, '0');
        let secs = (Math.trunc(seconds) % 60).toString().padStart(2, '0');
        return `${mins}:${secs}`;
    };
    return (
        <View style={styles.container}>
            <TouchableOpacity
                style={{
                    width: fullScreen ? screenWidth : screenWidth * 0.8,
                    height: fullScreen ? screenHeight * 0.4 : screenHeight * 0.25,
                    borderRadius: 10,overflow:'hidden'
                }}
                activeOpacity={0.7}
                onPress={() => setVisible(true)}>
                <Video
                    paused={paused}
                    source={{ uri: videoUrl }}
                    ref={ref}
                    onProgress={x => setProgress(x)}
                    onEnd={() => {
                        setProgress({ currentTime: 0, seekableDuration: 0 })
                        setpaused(true);
                        ref.current.seek(0);
                    }}
                    style={{
                        width: fullScreen ? screenWidth : screenWidth * 0.8,
                        height: fullScreen ? screenHeight * 0.4 : screenHeight * 0.25,
                        borderRadius: 40
                    }}
                    onLoad={() => { setpaused(true); setVisible(true) }}
                    resizeMode="cover"
                    controls={false}
                    alignItems="center"
                    justifyContent="center"
                />
                {visible && (
                    <TouchableOpacity onPress={() => setVisible(false)} style={styles.buttonView}>
                        <View style={styles.playPauseView}>
                             <TouchableOpacity onPress={() => setpaused(!paused)}>
                                <Image
                                    source={paused ? playmp4 : pausemp4}
                                    style={[styles.imageStyle, { width: 50, height: 50 }]}
                                    resizeMode='contain'
                                />
                            </TouchableOpacity>
                        </View>
                        <View style={styles.sliderView}>
                            <View style={{}}>
                                <MyText 
                                   text={format(progress.currentTime)} 
                                   color={colors.white} style{styles.timeTextStyle} 
                                  />
                                <Slider
                                    style={{ width: fullScreen ? '90%' : screenWidth * 0.68, height: 3 }}
                                    minimumValue={0}
                                    maximumValue={progress.seekableDuration}
                                    minimumTrackTintColor="#9EBE21"
                                    maximumTrackTintColor="#fff"
                                    thumbTintColor="#9EBE21"
                                    animated={true}
                                    useNativeDriver={true}
                                    value={progress.currentTime}
                                    onValueChange={(x) => {
                                        ref.current.seek(x);
                                    }}
                                />
                            </View>
                        </View>
                    </TouchableOpacity>)
                }
            </TouchableOpacity>
        </View>
    );
};
export default CustomControls;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.white,
        alignItems: 'center',
    },
    buttonView: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    playPauseView: {
        flexDirection: 'row',
        marginBottom:40,
        marginTop:60
    },
    playPauseIcon: {
        marginLeft: 60,
        marginRight: 60
    },
    sliderView: {
        flexDirection: 'row',
        alignItems: 'center'
    },
    timeTextStyle: {
        textAlign:'right',
        marginBottom:5
    }
})`

**Comment by moskalakamil** [comment]
The video which you provided is your local video - i cant check it, but i check your code on another video and it is working correctly

**Comment by vishalyad16** [comment]
@moskalakamil Thanks! Here is the code where the CustomControls component is rendered.

` return (
        <View>
            {loading ? (
                <View style={{ alignItems: 'center' }}>
                    <Progress.Circle
                        size={45}
                        progress={uploadProgress}
                        color='#7C7C7C'
                        textStyle={{ fontSize: 16 }}
                        showsText={true}
                        formatText={() => `${Math.round(uploadProgress * 100)}%`}
                    />
                    {((!netDown && !chance1 && !chance2) && (<MyText style={{ fontSize: 14, color: colors.grey, marginTop: 5 }} text='Video uploading...' />))}
                    {chance1 && (<MyText style={{ fontSize: 14, color: colors.red, marginTop: 5 }} text='Your connection is down...' />)}
                    {chance2 && (<MyText style={{ fontSize: 14, color: colors.red, marginTop: 5 }} text='It is taking longer than usual...' />)}
                    {netDown && (<MyText style={{ fontSize: 14, color: colors.red, marginTop: 5 }} text='Video upload failed...' />)}
                </View>
            ) : (
                submitted ? (
                    <View style={styles.container}>
                        <View style={styles.mainView}>
                            {!customUrl && <View style={styles.buttonView}>
                                <TouchableOpacity>
                                    <CustomButton
                                        mode="outline"
                                        btnStyle={styles.btnStyle}
                                        textColor={colors.white}
                                        // disabled={loader}
                                        onPress={() => handleRecordVideo()}
                                    >
                                        <Icons
                                            name="videocam"
                                            size={20}
                                            color={colors.primary}
                                        />
                                    </CustomButton>
                                    <MyText
                                        text="Record"
                                        fontWeight="900"
                                        fontsize={14}
                                        color={colors.light_grey}
                                        style={{ marginTop: 1, marginLeft: 15 }}
                                    />
                                </TouchableOpacity>
                            </View>}
                            <View>
                                {errorMessage && (<Text style={{color: 'red',
              fontSize: 13 ,marginTop:10,marginLeft:65,
              alignItems: 'center'}}>{ errorMessage}</Text>)}
                            </View>
                        </View>
                        {customUrl && (<View>
                            <CustomControls videoUrl={customUrl} onClose={handleRestart} />
                            <View style={styles.recordButtonView}>
                                <CustomButton
                                    mode='outline'
                                    textColor={colors.white}
                                    onPress={onRecordAgain}
                                    btnStyle={[style.btnStyle, { marginRight: 10 }]}
                                >
                                    Record Again
                                </CustomButton>
                                <CustomButton
                                    btnStyle={styles.submitBtnStyle}
                                    textColor={colors.white}
                                    onPress={onSubmit}
                                >
                                    Submit
                                </CustomButton>
                            </View>
                        </View>)}
                    </View>
                ) : (
                    <View style={styles.successMessageContainer}>
                        <CheckIcon name="check" size={20} color="#9fbf21" style={styles.successIcon} />
                        <MyText style={styles.successMessage} text='Video uploaded successfully.' />
                        <TouchableOpacity onPress={handleDeleteVideo}>
                        <TrashIcon
                              name="trash"
                              size={22}
                              color={colors.light_grey}
                              marginLeft={65}
                            />
                        </TouchableOpacity>
                    </View>)
            )}
        </View>
);`
    
// styles
    
import { StyleSheet} from 'react-native'
import colors from '../../../assets/colors/colors'
export default StyleSheet.create({
    container:{
        flex:1,
    },
    mainView:{
        flex:1,
    },
    buttonView:{
        flexDirection: 'row', 
        justifyContent: 'center', 
        marginTop: 15
    },
    btnStyle: {
        width: 120,
        width: 80, 
        height: 45, 
        marginTop: 5 
      },
      recordButtonView:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start',
        paddingHorizontal:15,
        paddingVertical:10
      },
    successMessageContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 3,
        marginVertical: 3
    },
    successMessage: {
        fontSize: 14,
        color: colors.primary,
    },
    successIcon: {
        marginRight: 5,
    },
    fileNameTextStyle: {
        marginLeft: 5,
        color: colors.deep_blue,
        fontSize: 14,
    },
    submitBtnStyle:{
        width:120,
        height:45
    },
    loaderContainer:{
        alignItems:'center'
    }
})


![Image](https://github.com/user-attachments/assets/f289f1aa-ef57-4a65-a66b-1409de67dd77)
![Image](https://github.com/user-attachments/assets/3418488a-e2f8-4787-b7d0-b610e3649f06)

Please let me know if anything else is required. I've been struggling to fix this issue for about two weeks. I appreciate your prompt response!

**Comment by moskalakamil** [comment]
@vishalyad16, please create the shortest possible reproduction of this error using a single component that works independently—without icons or imports from other files. That would be amazing
