### ISSUE TITLE
local video file doesn't play on Android release app

### ISSUE THREAD

**Issue by Solitaryo** [TheWidlarzGroup/react-native-video#1324]
### Current behavior
I have several local files that I'm loading in the app, on different screens. The thing is, in emulator works perfect, and if I run the app directly in the Android device, the video works, BUT, once I build the release app, the video doesn't show, is just a black view, with nothing working.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
1) require local file: const video = require('../assets/videos/video1.mp4');
2) put the video in react-native player:
`<Video
              style={styles.video}
              source={video}
              repeat
              muted={true}
              fullscreen={false}
              resizeMode="cover"
              bufferForPlaybackMs={500}
            />`
3) buid signed APK, and load the app in a device, video is not showing.

### Expected behavior
The video should show.

### Platform
Which player are you experiencing the problem on:
* Android. Tested on Moto E5, Google Pixel 2 XL and Samsung Galaxy Note 8.

### More Info:
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.3",
"react-native-video": "^3.2.0",

Building the app on:
macOS High Sierra 10.13.6
Android Studio 3.1.4

**Comment by cokealmonacid** [comment]
Hi! did you find any solution to this problem?

**Comment by godza** [comment]
This happens in IOS also.

**Comment by cagataykapuagasi** [comment]
Same issue

**Comment by romainbraun** [comment]
In my case I fixed it by using the old Android Media Player, replacing:
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
with
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

**Comment by smismailalam** [comment]
Hello, Same issue
did anybody find any solution to this problem?

**Comment by Neha0595** [comment]
This happens in both android and IOS, I copied media files in my project directory as well, 
<Video
        repeat
        source={require('../assets/videos/myvideo.mp4)}
        resizeMode="cover"
        style={{ flex: 1 }}
        paused={false}
      />
But show black screen in both android and ios as well

**Comment by r0b0t3d** [comment]
It seems like there is issue with video files inside `assets` folder https://github.com/facebook/metro/issues/290
I moved my video file outside `assets` folder and it works.
You guys may give it a try

**Comment by syedamirali14** [comment]
maybe it's video format issue
did you check this format of video?
codec: AAC, H.264
colour profile: HD (1-1-1)

**Comment by jeremyfrancis** [comment]
Works fine on fullscreen, but when putting it in a view on Android, the audio plays, but there is nothing on the screen! In the emulator in debug it shows up, but in production it is blank with just the audio.

iOS works great.

I tried putting the video outside of the assets folder, no luck.

Anymore solutions?

**Comment by jeremyfrancis** [comment]
> Works fine on fullscreen, but when putting it in a view on Android, the audio plays, but there is nothing on the screen! In the emulator in debug it shows up, but in production it is blank with just the audio.
> 
> iOS works great.
> 
> I tried putting the video outside of the assets folder, no luck.
> 
> Anymore solutions?

OK I feel dumb. My solution was obvious. My video files are .mov format and obviously Android does not support .mov because Apple made it. Converted to .mp4 and walla.
