### ISSUE TITLE
Video Skipping on some android devices

### ISSUE THREAD

**Issue by mattdwardle** [TheWidlarzGroup/react-native-video#1329]
### Current behavior
When you load the video through remote uri the video skips. This only happens on some android devices like google pixel 2. Also, I have read that version 4.0.0 of react-native-video fixes alot of issues. How do I get this version?

I have also tried adding

```  
compileOptions {
     targetCompatibility JavaVersion.VERSION_1_8
}
dependencies {
**
    implementation 'com.google.android.exoplayer:exoplayer:2.7.2'
}
```

### Platform
Which player are you experiencing the problem on:
I have tried on both ExoPlayer and media player and the same thing.
* Android ExoPlayer
* Android MediaPlayer

I am currently using:

- React-native 0.57.4 (Also tried 0.56)
- react-native-video 3.2.1

**Comment by cobarx** [comment]
I just released 4.0.0, so go ahead and give that a shot first.

Are you seeing this on all videos or just some of them?

**Comment by DavitVosk** [comment]
Any success @mattdwardle ?

**Comment by mattdwardle** [comment]
@DavitVosk yeah V4.0.1 seemed to fix the issue and I don't seem to have as many android video related issues in general.

**Comment by DavitVosk** [comment]
thanks @mattdwardle, will check that version

**Comment by fossage** [comment]
I am experiencing a similar issue with local videos, however the issue does not seem to be resolved for me after upgrading.  For a little context:

- On Pixel 2 and Pixel 3 videos skip the first few frames when they begin to play
- The issue does not happen on all videos, only some.  Not sure what the differentiating factor is as all of the videos I'm using are very similar in terms of size and length
- I am on RN 0.57 and RN Video 4.1.0

I've done some initial digging and it seems it may be potentially related to this issue: https://github.com/google/ExoPlayer/issues/2865, however I have only done a very cursory look, so this may be entirely different.

**Comment by DavitVosk** [comment]
4.0.1 version does not work properly for Android as well... So for Android I use `react-native-af-video-player` package which is based on `rn-video` but it works more properly... Hope this will help someone

**Comment by fossage** [comment]
I have solved my issue.  In my case I had videos that had no sound.  Half of them were encoded with an audio track(`aac codec`), and the other half weren't.  It appears it may be something with having an audio channel with no data on Pixel devices specifically.  I used ffmpeg to re-encode the videos without the audio track and everything works now!  

I'm still totally baffled as to why this seems to be specific to the Pixel, but hopefully this is helpful.

**Comment by iagormoraes** [comment]
In android 5 emulator at least the video don't play if the mp4 format have audio, when I convert to webm without audio using VP9, the video plays just fine.

**Comment by pateljoel** [comment]
@mattdwardle @iagormoraes @fossage Has there been any success with this or is there some sort of workaround?, This is currently my **main** issue on my android test devices that this keeps happening on.

**Comment by maderesponsively** [comment]
I'm having the same issues on Pixel 6. The video skips during play back throughout the video.
