### ISSUE TITLE
Cannot read property 'ScaleAspectFill' of undefined

### ISSUE THREAD

**Issue by tklivan** [TheWidlarzGroup/react-native-video#133]
Following instructions to the letter. I get the error "Cannot read property 'ScaleAspectFill' of undefined". Can't figure out what is needed to be done. Any advise?

**Comment by isair** [comment]
@nurdeen I just published 0.7.0 to npm, could you check if the issue persists?

**Comment by tklivan** [comment]
I will recheck this once I get the video part working again for IOS.

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by alphabikram** [comment]
@cobarx  react native video works great in IOS but in android it is complaing about ScaleAspectFill property says:

" TypeError: TypeError: Cannot read property 'ScaleNone' of null

I have put        
 resizeMode="cover"  property   inside that <Video> tag .
Any change to this property is not working and throwing the same error. 

BTW , I am trying to  play the audio only.
Any help?

**Comment by alphabikram** [comment]
@cobarx It I remove that property : resizeMode then it says => Cannot read property 'ScaleNone' of null :(
