### ISSUE TITLE
App crash when request full screen in modal

### ISSUE THREAD

**Issue by luutruong** [TheWidlarzGroup/react-native-video#1332]
### Current behavior
I have setup play video in modal and when request to play full screen the app crashed.

### Reproduction steps
1. Setup play video in modal https://facebook.github.io/react-native/docs/modal#docsNav
2. In the modal request to play full screen

### Platform
Which player are you experiencing the problem on:
* iOS

### Stack errors:
```
[viewController presentViewController:_playerViewController animated:true completion:^{
                _playerViewController.showsPlaybackControls = YES;
                _fullscreenPlayerPresented = fullscreen;
                if(self.onVideoFullscreenPlayerDidPresent) {
                    self.onVideoFullscreenPlayerDidPresent(@{@"target": self.reactTag});
                }
            }];
```

**Comment by DavitVosk** [comment]
@luutruong did you find any solution to this problem?

**Comment by luutruong** [comment]
@DavitVosk Long time a ago. I did not the solution which I've made :(

**Comment by DavitVosk** [comment]
@luutruong thanks for the answer. 
I found the solution. In modal you can easily go to full screen from video controllers only. Namely you need just pass `true` `controls` to `Video`, and that it :)
