### ISSUE TITLE
react-native-video/Video.js`. Indeed, none of these files exist

### ISSUE THREAD

**Issue by Jaydip2711** [TheWidlarzGroup/react-native-video#1334]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by cobarx** [comment]
Not sure how to help with this. I'll need more info about how your project is setup and what you've done to troubleshoot. Please re-open if you can provide more info.
