### ISSUE TITLE
Change the font-size of the textTrack

### ISSUE THREAD

**Issue by allinelara** [TheWidlarzGroup/react-native-video#1335]
I was wondering if it is possible to change the font-size of the textTrack.  

### Current behavior
Changing the font size of the textTrack doesn’t seem to be possible.  If I change it directly in the file (SRT) the font-size doesn’t change. And as far as I see there is no possibility to provide an external stylesheet as possible when using web-vtt: 

Ex: internal e external style in VTT  https://www.speechpad.com/captions/webvtt

  The font size on Android is really large - much larger than on iOS.

### Reproduction steps

Ex.: srt file
```
1
00:00:01,000 --> 00:00:02,123
<font face="Cronos Pro Light" size="10" color="#00ff00">This is crazy. What did I do?</font>

2
00:00:03,000 --> 00:00:05,000
<font size="10px" color="white">phrase</font>
<b>bold</b>, <i>italic</i>, <u>underlined</u>
<font color="#ff0000">red text</font>

3
00:00:06,000 --> 00:00:08,000  X1:40 X2:600 Y1:20 Y2:50
Another subtitle demonstrating position.
```

### Expected behavior
It should be possible to apply internal or external styling to the textTracks.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android

**Comment by nbennink** [comment]
I was looking for the same thing last week and found out that the font styling is actually handled by the OS (in the settings of the phone).

Android: Go to settings > accessibility > hearing > Google subtitles
iOS: Go to settings > general > Accessibility > subtitles > style

**Comment by cobarx** [comment]
We are at the mercy of whatever the underlying players support. The WebVTT spec does allow inline styling however at least on the web browser side, none of them have implemented support yet. AVPlayer and ExoPlayer tend to get features way after the browsers, so I doubt they support it. It's also possible to style with an CSS file, but again I don't believe AVPlayer or ExoPlayer support that.

Feel free to investigate and see if it's possible to support this. If so, we'd welcome a PR.

**Comment by pybuche** [comment]
@zchwyng 👋 Do you think we can merge this [PR](https://github.com/IbsenFahir/react-native-video/pull/1) ☝️ and release a `5.2.1` to handle subtitle size?
