### ISSUE TITLE
add image on top of videoview

### ISSUE THREAD

**Issue by ZeroCool00** [TheWidlarzGroup/react-native-video#1336]
is it possible to add image on top of videoview. something like this: 

![screen shot 2018-11-20 at 10 29 39 am](https://user-images.githubusercontent.com/18139594/48752443-3e181e00-ecaf-11e8-8150-cef8aaefdb49.png)

![screen shot 2018-11-20 at 10 30 55 am](https://user-images.githubusercontent.com/18139594/48752467-6bfd6280-ecaf-11e8-92d7-857742e4686e.png)

**Comment by cobarx** [comment]
Yes, create a container that holds both. Something like:
```
const imageStyle = {
  position: 'absolute',
  bottom: 20,
  left: 100
};

<View style={styles.container}>
  <Video />
  <Image style={imageStyle}
</View>
```
