### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by PhaNToMloRDs** [TheWidlarzGroup/react-native-video#1337]
this is my Code : 

import {NativeModules} from 'react-native';

var RNImmediatePhoneCall = {
  immediatePhoneCall: function(number) {
        NativeModules.RNImmediatePhoneCall.immediatePhoneCall(number);
  }
};

export default RNImmediatePhoneCall;

and get this error : 

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

please help me and compelet that code whit example number

**Comment by cobarx** [comment]
I'm not sure how this is related to react-native-video. Please re-open if there is a connection, otherwise you'll need to get support from the RNImmediatePhoneCall project.
