### ISSUE TITLE
Android can't show quikly

### ISSUE THREAD

**Issue by wengbenjue** [TheWidlarzGroup/react-native-video#134]
I use react-native  0.18.0 ,IOS is ok, but I cat't play the same video in android,there is no  erro,I try the http file and local file ,why

can  you give me some code

**Comment by tklivan** [comment]
+1

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.
