### ISSUE TITLE
Unable to resolve keymirror 

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#1340]
my iOS simulator on the Mac thros the following error:

Unable to resolve module 'keymirror' from ....../MyProject/node_modules/react-native-video/TextTrackType.js (also same for VideoResizeMode.js). Module doesnt exist in the module map or .../MyProject/node_modules directory.

I prefer to use Yarn and have updated that to the most recent version to try and resolve the problem but its not budging.

**Comment by cobarx** [comment]
I encountered this today and restarting the yarn server fixed it. Were you able to get this resolved?

**Comment by abdojulari** [comment]
I followed a tutorial on https://www.npmjs.com/package/react-native-nyt-360-video and ran it but I got the same error. Where is VideoResizeMode.js ?
