### ISSUE TITLE
Video with playInBackground changes behavior with different Android versions

### ISSUE THREAD

**Issue by brennan-pilcher** [TheWidlarzGroup/react-native-video#1341]
### Current behavior
In our app, we have videos that have the option to be shown normally (video + audio) or hidden (only audio). The user is given the option to toggle between the modes without halting playback. In both cases, shown or hidden, the video component is still being rendered. Additionally, the playInBackground prop is set to true so that the user can leave the app and come back without the video stopping. However, we have noticed that this functionality appears to be breaking on newer versions of Android when the video is hidden.

### Reproduction steps
From our testing with several physical and emulated Android devices, this appears to work fine prior to Android 8.1 but versions 8.1 and 9 have different and seemingly related problems.

On Android 8.1:
- Enter a screen containing a video
- Play the video
- Toggle the video into the hidden mode
- Exit the app
- Notice that the media continues playing audio as expected
- Return to the app
- Toggle the video into the shown mode
- Notice that the video area is completely blank

On Android 9:
- Enter a screen containing a video
- Play the video
- Toggle the video into the hidden mode
- Exit the app
- Notice that the media stops playing audio
- Return to the app
- Toggle the video into the shown mode
- Notice that the video area is completely blank and the audio is still not playing

#### Video Player styles
```javascript
video_player_container: {
    flex:.4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.black,
  }
```

```javascript
videoPlayer: {
    position: 'absolute',
    top:0,
    left: 0,
    bottom: 0,
    right: 0
  }
``` 

#### Video Player render function
```javascript
<View style={this.state.fullScreen === true ? styles.video_player_container_fullscreen : styles.video_player_container}>
    {this.state.spinnerVisible !== true || this.props.hidden ? null :
    <View style={[styles.activityContainer, styles.activityHorizontal]}>
        <ActivityIndicator size="large" color={Colors.primary_red} />
    </View>
    }
    {this.captionsLoaded() ?
        <Video
        audioOnly={this.props.AvType==='audio' ? true : false}
        ref={(ref) => {
            this.player = ref
        }}
        poster={this.props.AvType ==='audio' ? this.props.image : null}
        source={{uri:mediaItem.url}}
        style={styles.videoPlayer}
        textTracks={
            this.captionsExist() ?
            [{
                title: "English",
                language: "en",
                type: "text/vtt",
                uri: this.state.captionsFilePath
            },
            {
                title: "empty",
                language: "en",
                type: "text/vtt",
                uri: this.state.emptyCaptionFilePath
            }]
            : null
        }
        selectedTextTrack={this.state.captionsFilePath ? this.state.captions : null}
        rate={this.state.rate}
        paused={this.props.paused}
        volume={this.state.volume}
        muted={this.state.muted}
        resizeMode={this.state.resizeMode}
        onProgress={this.onProgress}
        onLoad={this.onLoad}
        onEnd={this.onEnd}
        playInBackground={true}
        />
        : null
    }
</View>
```

### Expected behavior
The audio and video should continue playing upon exiting and re-entering the app when playInBackground is set to true (and the behavior should not differ among Android versions).

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

### Workaround
After some experimentation, we found a workaround. If we added a non-zero borderWidth to the video, it would function as expected in both Android 8.1 and Android 9.

```javascript
videoPlayer: {
    position: 'absolute',
    top:0,
    left: 0,
    bottom: 0,
    right: 0,
    borderWidth: 1
  }
```

**Comment by androidparth90** [comment]
any luck with the solution for this issue ?

**Comment by brennan-pilcher** [comment]
Not as far as I'm aware, but I don't work on the project where I encountered this issue anymore so I don't know if the team found a workaround or not
