### ISSUE TITLE
onMoveShouldSetResponder not working

### ISSUE THREAD

**Issue by ZeroCool00** [TheWidlarzGroup/react-native-video#1344]
i m not getting any event when click on a video view.
as per the documentation this props call for every touch move on the view, but its not calling.

**Comment by OtacilioN** [comment]
I am facing this issue only in iOS, but not related to react-native-video, are you using react navigation @ZeroCool00 ? I saw this issue: https://github.com/react-navigation/react-navigation/issues/5482
