### ISSUE TITLE
Picture not showing in video when used in FlatList 

### ISSUE THREAD

**Issue by code76kb** [TheWidlarzGroup/react-native-video#1345]
When use in FlatList video is not showing but sound is playing, and when navigated to different screen then video will appear on top of new screen. 

platform : Android
react-native-video version : 3.2.1

**Comment by cobarx** [comment]
Can you provide a code snippet of this? Please try version 4.0.0 as it makes useTextureView on by default which may help with the video appearing on the top of the new screen.

**Comment by code76kb** [comment]
Thanks  for the suggestion, here is code ..
```

<TouchableOpacity>
     <Video style={{width:200,height:200,}}
                    repeat={true}
                    source={{uri:'http://192.168.1.172:5080/LiveApp/streams/149421666655679747236001.mp4'}}
                    paused={false}
                    muted={false}
                    playInBackground={false}
                    playWhenInactive={false}
                    resizeMode={'stretch'}
                    /> 
</TouchableOpacity>
```
```

**Comment by code76kb** [comment]
version 4.0.0.
same problem .

**Comment by codervss** [comment]
Has anyone come up with a Solution?
Still waiting
