### ISSUE TITLE
Feature request: seek() callback function or promise

### ISSUE THREAD

**Issue by dylancom** [TheWidlarzGroup/react-native-video#1347]
### Current behavior 
The seek method has a small delay. After calling seek(), the onProgress method doesn't immediately return the new progress position. Therefore I would like to be able to know when the seek() method finished.

### Reproduction steps
I have a progress bar(slider) below the video player that allows you to seek the video by dragging.
In a normal state it, the progress bar will show the progress of the video and when you are dragging, the progress bar will show the dragging position.

In order to determine what to show, I have a onSeeking boolean, so the progress bar understands when to show the progress of the video / or the dragging position.

When someone completed dragging, the seek() method get's called and onSeeking will be set to false.
Because seek doesn't directly put the video in the new position (small delay), the progress bar will jump shortly after dragging back to it's original position and quickly after that to the new seeked position.

### Expected behavior
In order to not make the progress bar jump after dragging, I would like seek to have a callback or return a promise so I can set my onSeeking boolean to false after the seek() method finished seeking.

### Platform
* iOS

**Comment by cobarx** [comment]
There actually is a callback that fires when the seek completes, except it wasn't documented lol so good luck knowing about that. When I started looking at the code I also discovered that the Android implementations report the time before the seek, so I had to fix that. 

I've merged #1351 to address this.
