### ISSUE TITLE
Execution failed for task ':app:preDebugBuild'. versi 4.0.1

### ISSUE THREAD

**Issue by khalisafkari** [TheWidlarzGroup/react-native-video#1349]
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.exoplayer:exoplayer-dash' has different version for the compile (r2.4.2) and runtime (2.9.1) classpath. You should manually set the same version via DependencyResolution

**Comment by cobarx** [comment]
It looks like you have another module that's including ExoPlayer, but they are using an older version. ExoPlayer versions don't tend to be compatible, so you'll need to see if you can get them to upgrade their module to use ExoPlayer 2.9.x.
