### ISSUE TITLE
Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'

### ISSUE THREAD

**Issue by MrJYJ** [TheWidlarzGroup/react-native-video#1352]
### Current behavior
When I run the command ： react-native run-android ,

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'.
> Could not find support-compat.jar (com.android.support:support-compat:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
63 actionable tasks: 1 executed, 62 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

### Expected behavior
it should run without any problem

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by gbenga504** [comment]
So I had the same issue while building got resolved it by adding this to the bottom of my android/build.gradle

subprojects {
     afterEvaluate {project ->
         if (project.hasProperty("android")) {
            android {
                compileOptions {
                    sourceCompatibility 1.8
                    targetCompatibility 1.8
                }
            }
        }
    }
}

**Comment by nlabofa** [comment]
> So I had the same issue while building got resolved it by adding this to the bottom of my android/build.gradle
> 
> subprojects {
> afterEvaluate {project ->
> if (project.hasProperty("android")) {
> android {
> compileOptions {
> sourceCompatibility 1.8
> targetCompatibility 1.8
> }
> }
> }
> }
> }

Didn't work for me. Still having the same error

**Comment by Mohsen322** [comment]
> 
> 
> So I had the same issue while building got resolved it by adding this to the bottom of my android/build.gradle
> 
> subprojects {
> afterEvaluate {project ->
> if (project.hasProperty("android")) {
> android {
> compileOptions {
> sourceCompatibility 1.8
> targetCompatibility 1.8
> }
> }
> }
> }
> }

didn't work...

**Comment by KashmitAI** [comment]
I get the same issue here after upgrading to RN 0.56->0.57.8 and react-native-video to version 4, the proposed solution don't work for me either.

**Comment by mikebouwmans** [comment]
I am getting the same issue when installing fresh

**Comment by costerik** [comment]
I'm facing the same issue :-(
This is searched on https://jcenter.bintray.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.jar
and the result for this link is 
`{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}`

**Comment by anirudh-eka** [comment]
Has anyone been able to solve this issue?

**Comment by zvs001** [comment]
My project:
react-native: 0.59.8
react-native-video: 4.4.1
compileSdkVersion = 28

supportLibVersion = "28.0.0" // updating 27.0.1 => 28.0.0 was the solution for me
implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

**Comment by nachumFreedman** [comment]
nu?

**Comment by nachumFreedman** [comment]
put maven { url "https://maven.google.com" } in your build/gradle
