### ISSUE TITLE
Video not playing on UWP

### ISSUE THREAD

**Issue by ltengea** [TheWidlarzGroup/react-native-video#1357]
### Current behavior
Video not playing and seems to be in a paused state. I've tried seeking to a different time and it shows a still image.
Tried deploy to both Windows 10 and Xbox One. Both not playing

### Reproduction steps
Using 
    "react": "16.6.1",
    "react-native": "0.55.4",
    "react-native-video": "3.2.1"

Sample code
`<Video ref={(ref) => {
                this.player = ref
            }}
                   style={styles.backgroundVideo}
                   onLoad={this.onLoad}
                   source={{uri: 'https://www.w3schools.com/html/mov_bbb.mp4'}}
            />
`

### Expected behavior
Video plays on load automatically

### Platform
Which player are you experiencing the problem on:
* Windows UWP

### Video sample
https://www.w3schools.com/html/mov_bbb.mp4

**Comment by uguraktas** [comment]
I have that same problem

**Comment by ghost** [comment]
@ltengea 
I've had a similar issue, for some reason the rate prop was at 0 by default on windows.
Simply adding `rate={1}` fixed the issue
