### ISSUE TITLE
Video controls not show in android device but in ios it's working perfect. why?

### ISSUE THREAD

**Issue by Jaydip2711** [TheWidlarzGroup/react-native-video#1358]
### Platform
iOS
Android

### issues
Android

* Android ExoPlayer

My issue is simple to understand, when I used a library called "React-native-video", it's working perfectly in ios, but in android, it's not working great. In Android, I cannot show default video controls like play, pause button, play time etc. for more info please see attached image. I  clearly differentiated with my issue. with a control, an image is an iOS device and without controls images in android device. 
![screenshot_1544690182](https://user-images.githubusercontent.com/29274771/49928719-bd7fc280-fee6-11e8-828c-090ee34e6880.png)
![simulator screen shot - iphone 6 - 2018-12-13 at 14 28 36](https://user-images.githubusercontent.com/29274771/49928720-bd7fc280-fee6-11e8-840b-220a6f054e51.png)

**Comment by cobarx** [comment]
There's not enough info here to be able to diagnose the issue. Please provide a code snippet or sample app showing the issue.

**Comment by Jaydip2711** [comment]
> There's not enough info here to be able to diagnose the issue. Please provide a code snippet or sample app showing the issue.

Hello @cobarx,

Thanks for replying. 

My issue is simple to understand, when I used a library called "React-native-video", it's working perfectly in ios, but in android, it's not working great. In Android, I cannot show default video controls like play, pause button, play time etc. for more info please see attached image. I  clearly differentiated with my issue. with a control, an image is an iOS device and without controls images in android device. 
![screenshot_1544690182](https://user-images.githubusercontent.com/29274771/49928623-8c9f8d80-fee6-11e8-9b59-22178a71970f.png)
![simulator screen shot - iphone 6 - 2018-12-13 at 14 28 36](https://user-images.githubusercontent.com/29274771/49928624-8c9f8d80-fee6-11e8-842d-4682198466f9.png)

**Comment by Alb3niz** [comment]
I believe this was answered in #1278 
@cobarx mentioned that iOS provides default set of media controls while Android does not. You can build your own or use an existing module like react-native-media-controls.

**Comment by IbrahimSulai** [comment]
Opened a PR (#1414) for showing the controls in Android Exoplayer.

**Comment by Usman4358** [comment]
Video control prop is working on ios but not on android using react native modal.
