### ISSUE TITLE
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath

### ISSUE THREAD

**Issue by yangbinlovegis** [TheWidlarzGroup/react-native-video#1364]
### Current behavior
npm i reac-native-video
react-native link react-native-video
react-native run-android

when I use do this ,it is cause an error
-----------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
> Could not determine artifacts for com.google.android.exoplayer:exoplayer-ui:2.9.1
   > Could not get resource 'https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-ui/2.9.1/exoplayer-ui-2.9.1.aar'.
      > Could not HEAD 'https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-ui/2.9.1/exoplayer-ui-2.9.1.aar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/52.84.245.63, d29vzk4ow07wi7.cloudfront.net/52.84.245.146, d29vzk4ow07wi7.cloudfront.net/52.84.245.74, d29vzk4ow07wi7.cloudfront.net/52.84.245.66] failed: Read timed out
<img width="1440" alt="2018-12-04 5 03 13" src="https://user-images.githubusercontent.com/8787605/49430676-9f2f0e00-f7e6-11e8-9de7-463d19e04e31.png">

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue

 happen.
### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on

* Android
### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by darkfiredarkhalo** [comment]
添加maven仓库即可解决.原因是aliyun和谷歌的仓库中还没有最新版的exoplayer.具体操作如下:
android目录下的build.gradle中添加
maven{
url "https://jcenter.bintray.com"
}

**Comment by StuartMorris0** [comment]
It appears the repo is currently missing:

https://github.com/google/ExoPlayer/issues/5225

This issue has a temp solution using a different maven url. 
maven {
            url 'https://google.bintray.com/exoplayer/'
        }

**Comment by yangbinlovegis** [comment]
> I have the same issue, was you able to resolve?
> 
> Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.9.1
> Failed to resolve: com.google.android.exoplayer:exoplayer-dash:2.9.1

turn off the proxy,and 'react-native run-android' maybe 5 or 10 times, I success

**Comment by StuartMorris0** [comment]
see the issue link and answer above

**Comment by yangbinlovegis** [comment]
> see the issue link and answer above

I have solved this problem , when my net speed is good I download the pack, I will close this issues

**Comment by ghost** [comment]
> > see the issue link and answer above
> 
> I have solved this problem , when my net speed is good I download the pack, I will close this issues

Please where in your project do you store the pack after you downloaded
