### ISSUE TITLE
How to play next video on Button click?

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#1367]
I have an array of videos, called VIDEOS [ ] whose index I increment +1 when i click a button. The button fires a function nextVideo().

How do i get the player to play the next video?
So  <Video source={{uri: VIDEOS[videoCounter]}} /> needs to reload in my render() function in App.js with the updated counter called videoCounter.

**Comment by cobarx** [comment]
You can set the uri from this.state.

Something like:
```
onPress = () => {
  this.setState({ videoCounter: this.state.videoCounter + 1 });
}

source={{ uri: VIDEOS[this.state.videoCounter] }}
```
