### ISSUE TITLE
Delay on video rewind after media ends

### ISSUE THREAD

**Issue by lucasfp13** [TheWidlarzGroup/react-native-video#1368]
I'm doing

`
this.setState({paused: true}, this.player.seek(0))
`

after the media ends, but it's taking so long and many times the video can't be played again.

I'd like to know if there is some way to rewind video to start position without the seek method or how to do this using seek(0) without delay.

**Comment by lucasfp13** [comment]
@SparkleFaerieCoder a workaround for this is to set a ''pause'' state to true in onEnd method's call and use the ''repeat'' prop, was the way that I'm solve this after try hard with seek method.

**Comment by lake2** [comment]
same issue + 1

**Comment by vladpuz** [comment]
+1
