### ISSUE TITLE
Master at 4.1.0 failing to compile on iOS

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1370]
### Current behavior
`Build input file cannot be found: '/node_modules/react-native-video/ios/RCTVideoManager.m'`

### Reproduction steps
Modify `package.json` to use the `master` branch and re-install libs using `npm i`.

`"react-native-video": "react-native-community/react-native-video",`

### Expected behavior
It compiles :)

### Platform
* iOS

**Comment by cobarx** [comment]
It should be looking for RCTVideoManager.m in ios/Video/RCTVideoManager.m from version 4.0.0 on. I can't test this on my work machine to be sure, but I'd be surprised if there's a problem here.

Can you try wiping out node_modules/react-native-video, doing an `npm install` and seeing if there's still a problem.

**Comment by anshul-kai** [comment]
Thanks for following up @cobarx. I did indeed refresh `node_modules` multiple times to end up with the same problem again and again. `"react-native-video": "^4.1.0",` works just fine which confuses me as theoretically npm should be on master, isn't it?

**Comment by cobarx** [comment]
So I take it you're wanting to target master. I would set your source to:
https://github.com/react-native-community/react-native-video.git#master

There may be some kind of issue where just:
https://github.com/react-native-community/react-native-video.git
won't work. I'm not sure what's needed to fix that.

**Comment by anshul-kai** [comment]
I actually have a fork that stopped working after rebasing on `4.1.0` and everything was working fine as of `4.0.1`.

Unfortunately, your suggested syntax also ends up with the same error.

**Comment by cobarx** [comment]
I would try unlinking and relinking the react-native-video module:
`react-native unlink react-native-video && react-native link react-native-video`

**Comment by anshul-kai** [comment]
Thanks again for following up. Cleaning `ios/build` actually fixed the issue.

**Comment by cobarx** [comment]
Glad to hear it, thanks for letting me know what resolved the issue.
