### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer:2.9.1.

### ISSUE THREAD

**Issue by darkfiredarkhalo** [TheWidlarzGroup/react-native-video#1372]
### Current behavior
Describe what happens when you encounter this issue.

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.google.android.exoplayer:exoplayer:2.9.1.
> Could not find com.google.android.exoplayer:extension-okhttp:2.9.1.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
https://github.com/react-native-community/react-native-video#installation

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:

* Android ExoPlayer

**Comment by darkfiredarkhalo** [comment]
添加maven仓库即可解决.原因是aliyun和谷歌的仓库中还没有最新版的exoplayer.具体操作如下:
android目录下的build.gradle中添加
maven{
            url "https://jcenter.bintray.com"
        }

**Comment by marekchen** [comment]
@darkfiredarkhalo 你现在还可以用吗？我这边加了也没用

**Comment by darkfiredarkhalo** [comment]
可以,是android目录下的build.gradle,如下
allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter(){
                    url "http://maven.aliyun.com/nexus/content/repositories/central/"
                }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven{
            url "https://jcenter.bintray.com"
        }
    }
}
如果还不行,你可能需要翻墙
