### ISSUE TITLE
Failed to resolve: com.google.android.exoplayer

### ISSUE THREAD

**Issue by ozankonur** [TheWidlarzGroup/react-native-video#1375]
I am getting exoplayer Android build gradle error.

I follwed the steps but I am getting this error:

> Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.9.1
Install Repository and sync project
Open File
Show in Project Structure dialog

> Failed to resolve: com.google.android.exoplayer:exoplayer-dash:2.9.1
Install Repository and sync project
Open File
Show in Project Structure dialog

When I try to install repo and sync, I am getting 
> Could not found dependency "com.google.android.exoplayer:exoplayer-core:2.9.1"

Here is my android/build.gradle codes:
`buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
    }
}
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}`

Any suggestion ?

**Comment by wack17s** [comment]
@ozankonur next code in `build.gradle` (not `app/build.gradle`) fixed problem for me
```
allprojects {
    repositories {
        mavenLocal()
        google()
        maven { url "https://maven.google.com" }
        maven { url "https://google.bintray.com/exoplayer" } <----- add this line
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by ozankonur** [comment]
@wack17s It solved the problem.. Here is my latest android/build.gradle codes;

`allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
         maven { url "https://google.bintray.com/exoplayer" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}`

**Comment by TTKatrina** [comment]
@wack17s  Excuse me... How did you know exoplayer changed the repo? I cannot find any note from the official site's readme: https://github.com/google/ExoPlayer.
