### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer-smoothstreaming:2.9.1

### ISSUE THREAD

**Issue by Arjan-Zuidema** [TheWidlarzGroup/react-native-video#1378]
### Current behavior
Android is unable to build.

Could not find com.google.android.exoplayer:exoplayer-smoothstreaming:2.9.1

### Reproduction steps
Run `yarn android`

### Expected behavior
A proper build that does not fail

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by tunjiadeyeri** [comment]
It's a problem with bintray not mirroring exoplayer to jcenter


adding

 maven {
            url 'https://google.bintray.com/exoplayer/'
        }

to repositories in android/gradle should fix it


see: https://github.com/google/ExoPlayer/issues/5225

**Comment by Arjan-Zuidema** [comment]
@tunjiadeyeri That fixed the issue, thanks!
