### ISSUE TITLE
Provide support for WebVTT chapters

### ISSUE THREAD

**Issue by cybercoder** [TheWidlarzGroup/react-native-video#1379]
I need to trigger some actions on specific times in a video play. my code looks like this:

```javascript
                <Video
                    source={
                        {
                            uri: `${Config.mediaURI}/${exam.media.file}`,
                        }
                    }
                    textTracks = {[
                        {
                            title: "Exam Questions",
                            language: "fa",
                            type : TextTrackType.VTT,
                            uri: `${Config.mediaURI}/${exam.media.WebVTTFile}`
                        }
                    ]}
                    style={{flex:0.5, width: "100%",backgroundColor:"yellow"}}

                    selectedTextTrack={{
                        type : "chapters",
                        value: "Exam question",
                        disabled : true,
                        index : 0
                    }}
                    onTimedMetadata={(meta)=>this.setState({meta})}
                />
```
the `meta` is empty. webVTT content shown as subtitle!

**Comment by cobarx** [comment]
Without the platform info, I don't have any way to investigate this.

**Comment by cybercoder** [comment]
Platform : Android
Actually i need to use `WebVTT` file as chapters and on any chapter run a function, So i inject `webVTT` but i can't disable show on video and there's noting on `onTimedMetadata`

**Comment by cobarx** [comment]
WebVTT is only supported for display as subtitles, chapters have not been implemented. Feel free to submit a PR to add chapter support. 

Timed metadata is for tracks containing ID3 tags and is unrelated to WebVTT.

**Comment by Ayesha1766** [comment]
Hi Vahid Alimohamadi,
Have you added any custom slider to support chapters in react native video.
