### ISSUE TITLE
iOS Remote Videos not playing

### ISSUE THREAD

**Issue by StuartMorris0** [TheWidlarzGroup/react-native-video#1380]
I wanted to report an issue I was able to figure out but might need some work...

Testing on iOS Simulator, using the latest version of react-native and react-native-video. We were using remote URIs for the source.

I noticed if a video is uploaded as .mp4 it would not play. I would get an error in console such as:
error: {domain: "AVFoundationErrorDomain", code: -11800}

In XCode console there would be an error similar to:
<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=URL_IN_QUESTION, NSErrorFailingURLKey=URL_IN_QUESTION, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7DECC485-AD0D-4DD2-9FDA-74D8DEBC1215>.<1>"

Note: This is for an HTTPS url, in case that comes into play.

The resolution I have found is that the player will play videos uploaded as .MP4 but not .mp4, strangely. I uploaded the same video, with the same name and path with the correct .MP4 instead and all works fine. 

This should either be detailed or researched.

**Comment by lonewolfaka9** [comment]
+1

**Comment by tmjordan** [comment]
Hi @StuartMorris0 , did you find a solution. i have the same problem, using remote url video on ios.
No problem with android

**Comment by StuartMorris0** [comment]
@tmjordan. I put my resolution above. That is what worked for me

**Comment by tmjordan** [comment]
Thanks @StuartMorris0, it's working now. But it's a weird behavior. Anyway i'm glad to have a workaround :)

**Comment by koo27** [comment]
Same weird behaviour on Android too.

**Comment by kyhnlbyrk** [comment]
Hey I have a problem like this but a bit different MP4 extension is not working for me.. 

https://github.com/react-native-community/react-native-video/issues/1540 the problem is this

**Comment by jasonparekh** [comment]
I had a similar issue, turned out the problem was my Mac VM didn't have an audio output device.  The workaround for me was to install Loopback which creates a dummy device.

**Comment by kyhnlbyrk** [comment]
I have tried on the real device same and I got the same problem.. So in my case its now related to VM

**Comment by all9lives** [comment]
The workaround to name remote files with `.MP4` extension worked for me. Maybe this should be added to the docs as they use `.mp4` extensions everywhere in the docs.  

(Thanks @StuartMorris0 for finding the workaround. )

**Comment by e3bmo3ty** [comment]
i have the same problem and this resolution is not solving it. :(
