### ISSUE TITLE
compression quality and times

### ISSUE THREAD

**Issue by nicoara** [TheWidlarzGroup/react-native-video#1386]
Hi,
I was using Whatsapp ant it compresses video phenomenally, from 40 mb to 5 mb (85% reduction) while keeping good quality. I am wondering if I can achieve similar results with the react-native-video library.

I have tried to use the compression for a 40 mb video using anothe library, react-native-image-picker, and the compression takes a whole few minute, so I cannot add this to production.
For a 17 mb video, for the below options, it takes ~70 secons, which is very long. Also is there a callback to know the percent of how much is done from the compression process?

My goal is to have a decent video after compression of under 10 mb, with the waiting time for about 10 seconds for the compression. How large can the original video be? What are the options to use?

Additional Information

React Native version: [0.54.4]
Platform: [both]
Development Operating System: [MacOS]
Dev tools: [Xcode and Android Studio]
Device: [Samsung Galaxy S4 with Android 5.0.1]

Thanks

**Comment by nicoara** [comment]
thanks .

**Comment by Lunziyuan** [comment]
Have you found any good ways? @nicoara

**Comment by gilons** [comment]
https://www.npmjs.com/package/react-native-ffmpeg

**Comment by gilons** [comment]
checkout that
