### ISSUE TITLE
To support from marshmallow to latest android sdk version

### ISSUE THREAD

**Issue by sahdev0** [TheWidlarzGroup/react-native-video#1388]
Hello,

I am new to React Native and creating an application which will stream video from Vimeo server. I have one doubt:

In Doc, already mentioned that latest react-native-video will support from SDK version >26+ which is Oreo version of android but I want to support play videos from our Android Application from marshmallow  to Latest android. Is it ok to use old version of react-native-video 3.2.1 with latest Android versions or is there any options to use both.

Please suggest any better approach you have.

**Comment by cobarx** [comment]
You can run on 4.1 and up fine. The SDK 26 requirement is for the target SDK not the minimum SDK. This explains it: https://stackoverflow.com/questions/24510219/what-is-the-difference-between-min-sdk-version-target-sdk-version-vs-compile-sd
