### ISSUE TITLE
how to get buffering progress on Android ?

### ISSUE THREAD

**Issue by zk6859** [TheWidlarzGroup/react-native-video#1389]
### Current behavior
I don't know how to get buffering progress on Android.Do you have any API?

### Platform
Android 

### Version
react 16.5.0
react-native 0.57.2
react-native-video 4.20

![qq 20181219155154](https://user-images.githubusercontent.com/24285753/50206329-02539f80-03a6-11e9-88c9-7b722d962f14.png)

**Comment by cobarx** [comment]
What values are you getting back in your onProgress event?
