### ISSUE TITLE
360 degree video

### ISSUE THREAD

**Issue by sprice** [TheWidlarzGroup/react-native-video#139]
Would you accept a pull request for 360 degree video support?

**Comment by isair** [comment]
Certainly. Is the implementation both for iOS and Android?

**Comment by sprice** [comment]
Thanks. That's the hope.

**Comment by SteveAquino** [comment]
@sprice Any progress on this?  I'm super interested in having something like this, and I'd love to contribute if possible.

**Comment by JoschaP** [comment]
+1

**Comment by giolaq** [comment]
+1

**Comment by donedgardo** [comment]
+1 Discovery VR app has this 360 video feature and its made in react-native.

**Comment by openGeeksLab** [comment]
+1

**Comment by BTMouseKing** [comment]
@donedgardo Do you know how Discovery VR implemented the 360 video feature in react native? Looking for a solution.

**Comment by donedgardo** [comment]
@BTMouseKing I think it's a native bridge with Google VR SDK, I made one but my C code knowledge is very limited. I'll post it when I get on computer

**Comment by BTMouseKing** [comment]
@donedgardo Thank you very much! Looking forward.

**Comment by marekpridal** [comment]
Have you anybody tried it? I would like to play 360 video from server using this repository. I have tried [one before](https://github.com/tiero/react-native-360) but it's not stable yet.

**Comment by ashtonlance** [comment]
Any update on this?

**Comment by davichoso** [comment]
https://github.com/davichoso/react-native-video360

**Comment by shinspiegel** [comment]
Does anyone have any other sugestions?
