### ISSUE TITLE
Need help to integrate DRM in IOS

### ISSUE THREAD

**Issue by Hamzayy** [TheWidlarzGroup/react-native-video#1390]
### Current behavior
Currently react-native-video does not support DRM. I need to integrate it by myself. For that I need some help if anyone can help me out it'll be a great favour. 

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

**Comment by AndrewJack** [comment]
I doubt this will be implemented anytime soon. maybe try using the Brightcove players. There's a react native binding that seems ok. https://github.com/manse/react-native-brightcove-player

**Comment by Hamzayy** [comment]
@AndrewJack Thanks for coming out, I really appreciate it. Can you please confirm if brightcove-player supports DRM for both IOS and Android? I'll have a look by myself too.

**Comment by cobarx** [comment]
Apple has their own DRM called FairPlay that you can integrate into the player, however it will only work on iOS & Mac. I'm not sure whether we would be able to support other DRMs as they require SDKs and may not have licenses that allow redistribution in an open source project.

For FairPlay, here is Apple's dev center: https://developer.apple.com/streaming/fps/
and an article describing how to integrate it in Swift unfortunately: https://icapps.com/blog/how-integrate-basic-hls-stream-fairplay

**Comment by danielmarino24i** [comment]
I would suggest to check this PR: https://github.com/react-native-community/react-native-video/pull/1445

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/pull/1445
