### ISSUE TITLE
IOS: alert 'appName would like to access the microphone'

### ISSUE THREAD

**Issue by AlekseiIvshin** [TheWidlarzGroup/react-native-video#1391]
### Current behavior
Alert `%appName% would like to access the microphone` is shown, when video player is mounted(or starting play).

### Reproduction steps
Run application first time and try play video.

### Expected behavior
Application will not ask access the microphone.

### Platform
iOS simulator
macOS Mojave

**Comment by whathejoe** [comment]
Same thing happening to me

react-native-video@3.2.1
react-native@0.56.0

**Comment by darknblack** [comment]
Same here

**Comment by norbertsongin** [comment]
same here

**Comment by johniak** [comment]
It happens also on my simulator :(

**Comment by piotrgiedziun** [comment]
it works fine here

**Comment by vidangelops** [comment]
We're experiencing the same thing. I'm assuming its an included library? We shouldn't need the mic to play video with the native player, right?

**Comment by jiantongc** [comment]
Same, seems like is because the video player trying to play through the microphone?!

**Comment by cokealmonacid** [comment]
Same here, there is no property for disallow the microphone access request

**Comment by AshtonKem** [comment]
Same. It's unclear to me if this is something that will affect actual devices, or if it's just a simulator only bug.

**Comment by adamnbowen** [comment]
It does ask on actual devices, we've tested it on an iPhone X and an iPhone 8

**Comment by AshtonKem** [comment]
Well, that seems very bad.

**Comment by AshtonKem** [comment]
Digging into it, this might actually be a problem with the iOS simulator itself, see [this](https://github.com/insidegui/WWDC/issues/445) issue.

**Comment by klodha** [comment]
I am also facing same issue. Running on macOS Mojave, 10.14.3 and right after adding video player, simulator is asking for microphone permission whenever video player scene init. Not tested on device yet, but based on other feedbacks above, it might appear on device as well. 

Since status of this bug is yet open, just wanted to check if there is any work-around while the original issue get resolved?

**Comment by tvanmil** [comment]
I have the same issue, macOS Mojave 10.14.6.

**Comment by jedashford** [comment]
Apple is now actively rejecting our app for this. 

> We noticed that your app requests the user’s consent to access their microphone and Bluetooth but does not clarify the use of the microphone and Bluetooth in the applicable purpose string.

So we're going to give a different description than our current message, but then they're going to want to test it. And since we have no feature actually using the microphone, they're going to deny us again. We're kinda stuck here.

**Comment by franekantoni** [comment]
Faced similar issue today. When a video is played during a webRTC call it interferes with mediaDevices. It causes the local stream to go mute without programatically muting the track (audio track still has the enabled prop set to true). It does not happen when the 'muted' prop of the Video component is set to true.  Has this bug with Video component accessing the microphone got resolved?

**Comment by kaushik-prasanna** [comment]
Facing the same issue. Apple is rejecting the binary with the message :

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Only react-native-video is accessing microphone, though for what purpose, not sure.

Ping : @cobarx , @ashnfb

**Comment by kaushik-prasanna** [comment]
CC : @n1ru4l
