### ISSUE TITLE
Support seamless looping

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1392]
### Current behavior
Currently, looping works but isn't seamless and very visible/audible when playing seamless files.

### Reproduction steps
Play any seamless video or audio to notice the onEnd and seek to 0 taking a non-zero time.

### Solution
Although tedious from initial investigation of code, the use of `AVQueuePlayer` would solve this problem.

### Expected behavior
Seamless Playback

### Platform
* iOS

**Comment by anshul-kai** [comment]
Similar to #657

**Comment by JPWallhorn** [comment]
@a-koka  We had the same issue but this is not a video player issue actually. A lot of times the audio track that's within the video file is slightly longer than the video itself. Therefore, there is a little lag.

You can either remove the audio track completely and make sure it's the same exact length. This is a tool that makes it both the same length: https://github.com/fluthaus/NHBAVAssetTrimming

Because even using the native Looper didn't work. Once we fixed the audio track, our loop was perfect.

**Comment by anshul-kai** [comment]
Thanks for sharing this information, @JPWallhorn. My use case involves mostly M4A audio files and I can notice a blip when the file loops. The blip sounds different on different bitrates and there seems to be no blip when looping files using react-native-sound. So I know this is an issue with this library.

**Comment by JPWallhorn** [comment]
Got it, that makes total sense. I would recommend using Native Modules in this case because I don't think this library will switch anytime soon to `AVQueuePlayer`. Therefore, you can use it within your React Native App.

**Comment by cantonalex** [comment]
I agree, as someone trying to have the same use case. I noticed while looping the video in VLC it's a seamless loop and with this library there is a split second hiccup.
Did you find a work around @a-koka ?

**Comment by Krayen** [comment]
> @a-koka We had the same issue but this is not a video player issue actually. A lot of times the audio track that's within the video file is slightly longer than the video itself. Therefore, there is a little lag.

+1 for this. Stumbled upon the same issue where in After Effects my loop was seamless, but in both Quicktime and in my app it stuttered when repeated. It was just meant to be a background with some animation, no sound. So when rendering it with Adobe Media Encoder, I had to remove the 'Export sound' from the h264 settings. Now it repeats seamlessly.

**Comment by anshul-kai** [comment]
The same track works fine on Android when using react-native-sound. I agree that it is specific to encoding as results have been different for different formats but this is still something worthwhile looking into.

In the meanwhile, anybody else experiencing this issue, using 256 Kbps M4A files proved to be the best in our testing.
