### ISSUE TITLE
video stops playing when changing source [ios]

### ISSUE THREAD

**Issue by rogerkerse** [TheWidlarzGroup/react-native-video#1403]
### Current behavior
When I change video source on existing <Video /> element then video stops playing but audio continues.

### Reproduction steps
Happens only on iOS and only on react-native-video 4, not on 3.
1. Start playing video on one source
2. Switch video source
That is it.

### Expected behavior
It should continue playing video from new source just as audio does.

### Platform
* iOS only on react-native-video 4 (on version 3 everything is fine), Tested on simulator.

**Comment by cobarx** [comment]
This is now fixed in 4.3.0 with #1395
