### ISSUE TITLE
Show list video preview for iOS

### ISSUE THREAD

**Issue by bharatidudhrejiya** [TheWidlarzGroup/react-native-video#1405]
**Current behavior**

Only show first video preview from list of videos.

**Reproduction steps**

I have latest react-native and react-native-video

List more then one video like this

`<Video
          ref={ref => this._video = ref}
          source={{ uri: "https://www.radiantmediaplayer.com/media/bbb-360p.mp4" }}
          resizeMode={'cover'}
           repeat={true}
           paused = {true}
           style={{
                        height: 200,
                        width: 200,
           }}
           onLoad={() => {
                        console.warn("test")
                    this._video.seek(2);
            }} />
   <Video
          ref={ref => this._video = ref}
          source={{ uri: "https://www.radiantmediaplayer.com/media/bbb-360p.mp4" }}
          resizeMode={'cover'}
           repeat={true}
           paused = {true}
           style={{
                        height: 200,
                        width: 200,
           }}
           onLoad={() => {
                        console.warn("test")
                    this._video.seek(2);
            }} />`

**Platform**
iOS only

**Comment by cobarx** [comment]
I'm not sure what you mean by preview. You want to create a playlist of videos and have it play the next one after the first one completes?

**Comment by bharatidudhrejiya** [comment]
I mean to say that the list of videos do not show thumbnail of videos.

But, now I have solved this issue by adding unique "ref" on each video in list.

Thanks!

**Comment by paddy57** [comment]
@bharatidudhjiya can you please tell me in detail how did you achieve the thumbnail part ? i'm stuck there only
