### ISSUE TITLE
react-native-video disables siblings when working in react-native-fluid-transitions

### ISSUE THREAD

**Issue by joris1995** [TheWidlarzGroup/react-native-video#1411]
### Current behavior
I am building a video app and use [react-native-fluid-transitions](FluidNavigator) for shared-element transitions. I found out, though, that this isn't working together properly.

I have two controls living together with my video component in the same view, a pause/play button and a navigation button. on iOS, these `TouchableOpacity` components work fine but on Android they don't seem to detect touch anymore, as if some sort of transparent view is blocking interaction with them. This is not the case though and when I remove the video component, I can tap my buttons like normal. The same happens when I remove react-native-fluid-transitions from my app: The buttons seem to work fine together with the video component.

### Reproduction steps
My code looks as follows:
```
render() {
    let url = this.props.navigation.getParam('video')
    if (url == "" || url == null) {
      return (
        <View>
          {Renderer.getInstance().renderNavigationButton(() => this.backButtonTapped())}
          <Text style={{alignSelf: 'center'}}>No video available</Text>
          {this.renderControls()}
        </View>
      );
    } else {
      return (
          <View style={internalStyles.container}>
            <Video style={internalStyles.videoContainer}
                ref={(ref) => {
                 this.props.player = ref
                }}
                source={{uri: url}}
                controls={false}
                onEnd={() => this.videoEnded()}
                paused={this.state.paused}
                muted={false}
                repeat={false}
                resizeMode={"contain"}
                volume={1.0}
                rate={1.0}
                ignoreSilentSwitch={"obey"}
              />              
            {this.renderControls()}
            {Renderer.getInstance().renderNavigationButton(() => this.backButtonTapped())}
          </View>
      );
    }
  }
```

`this.renderControls()` is a function that renders either a play or pause button, depending on whether `this.state.paused` is true or not. `Renderer` is a singleton that contains functions that return views that I use in multiple components throughout my app, which in this case is used for providing the backButton.

These controls work fine in other contexts, but when used in a component lives inside a FluidNavigator (the stack navigator of react-native-fluid-transitions) and a react-native-video element, they don't work on Android.

### Expected behavior
I would expect the video component to be able to live inside a FluidNavigator without disabling it's sibling views (in this case TouchableOpacities)

### Platform
* Android

### Video sample
not relevant

**Comment by rauchp** [comment]
Were you able to solve this?

**Comment by ghost** [comment]
@joris1995 Have you solved the problem?
