### ISSUE TITLE
"None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream."

### ISSUE THREAD

**Issue by GaurravsIN** [TheWidlarzGroup/react-native-video#1416]
### Current behavior
I am running a video streaming api into Videos tag android simulator. but getting this message

<img width="1096" alt="screen shot 2019-01-08 at 11 58 20 am" src="https://user-images.githubusercontent.com/42542169/50813640-105d6600-133d-11e9-9179-e49122de021e.png">

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
It should run the video appropriately.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

**Comment by cobarx** [comment]
Without seeing the stream, I'm not able to provide any insight into this. Please link to a sample stream if possible.

**Comment by sangs303** [comment]
i have faced the same issue.

[CMAF - Copy.zip](https://github.com/react-native-community/react-native-video/files/3150993/CMAF.-.Copy.zip)

**Comment by devpedrofurquim** [comment]
Has any of you guys found a solution yet?
