### ISSUE TITLE
Component children not rendered in contentOverlayView on iOS

### ISSUE THREAD

**Issue by maxschmeling** [TheWidlarzGroup/react-native-video#1418]
### Current behavior
The component currently has code for inserting react subviews into the `contentOverlayView` property on the `AVPlayerViewController` but they will always be destroyed when the `_playerViewController` is set to `nil` and recreated by `usePlayerViewController`.

### Reproduction steps
Render a `<Video>` component with `controls={true}` and children.

### Expected behavior
Children of the `<Video>` component should be rendered in the `contentOverlayView` view between the video and the player controls.

### Platform
iOS

**Comment by maxschmeling** [comment]
I'm not sure if this is just unfinished code that isn't intended to be supported, but it would be very useful if it worked. I have multiple use cases for it, so I'm happy to PR a fix for it soon.

**Comment by maxschmeling** [comment]
Also, I was able to modify the `RCTVideo.m` code locally to keep a reference to the `view` from `insertReactSubview` and re-add it every time the `AVPlayerViewController` is recreated and that fixes the problem.

**Comment by bogdan-vol** [comment]
> Also, I was able to modify the `RCTVideo.m` code locally to keep a reference to the `view` from `insertReactSubview` and re-add it every time the `AVPlayerViewController` is recreated and that fixes the problem.

hi @maxschmeling . that sounds exactly like what i need for my project. I tried the same but I know very little on obj c/swift. Can you guide me a bit?

**Comment by maxschmeling** [comment]
@bogdan-vol it's on my todo list to get a PR submitted for this with a better implementation, but this is what I did to get it working for now: https://github.com/react-native-community/react-native-video/compare/master...maxschmeling:1418-render-children?expand=1

**Comment by bogdan-vol** [comment]
Thanks a lot @maxschmeling . this works to a point where, for example, I add a `TouchableOpacity` as a child and in the fullscreen mode it is visible but it loses the `onPress` functionality. I'll give it a try and see if i can fix this.

**Comment by maxschmeling** [comment]
@bogdan-vol the children are set as the [contentOverlayView](https://developer.apple.com/documentation/avkit/avplayerviewcontroller/1615835-contentoverlayview?language=objc) on the `AVPlayerViewController`. Unfortunately, since this layer is between the video and the player controls layer, it is explicitly "untouchable". The user cannot interact with any of the children.
