### ISSUE TITLE
How can I get the embedded subtitles of the videos ? 

### ISSUE THREAD

**Issue by omar20261** [TheWidlarzGroup/react-native-video#1421]
I want to get the hardcoded subtitles from the videos (if it was exist) as an array instead of displaying it as a captions .. any help ?

**Comment by EugeneKovalev** [comment]
@omar20261 Have you found a solution?
As I understand, right now this lib suggests using web-hosted subtitles which is totally inappropriate.

**Comment by Yusuf007R** [comment]
did you guys found the solution?
