### ISSUE TITLE
dynamically change audioOnly prop

### ISSUE THREAD

**Issue by OceanRingTech** [TheWidlarzGroup/react-native-video#1424]
### Current behavior
Describe what happens when you encounter this issue.
I am not able to change the "audioOnly" prop dynamically. The initial value on video player render cannot be changed.

### Expected behavior
Describe what you wanted to happen
With this component I am receving both video and audio files. So  I want to switch to the required one if an option is fulfilled.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

Would be very much grateful for any help.

**Comment by anirudh-eka** [comment]
We are also facing this problem. Is there any solution or work around?

**Comment by flexgrip** [comment]
Does this prop actually stop fetching the video when you’re using HLS with separate audio tracks? Or does this just render the image, but still downloads all of the video?

I guess I can test it somehow and find out. Although I’m not sure how. Maybe I can enable audio only and then delete the video files from my manifest after it stops playing... hmm.
