### ISSUE TITLE
Get Progress status for audioOnly

### ISSUE THREAD

**Issue by stephane-r** [TheWidlarzGroup/react-native-video#1425]
### Expected behavior
Hi guys !
Is it possible to go to the selected minute when `audioOnly` props is enabled ? (method exist ?)

I would like add small custom player, but i don't know if i can get this information (documentation send no information about this).

Thank you community !

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

**Comment by pengcao1** [comment]
what's your information means?
abulm 、singer、date of the audio or the others
