### ISSUE TITLE
Multiple dex files define Lorg/reactnative/camera/BuildConfig;

### ISSUE THREAD

**Issue by slade77777** [TheWidlarzGroup/react-native-video#1426]
### Current behavior
I add library to my current project but I meet a trouble in android, ios is working well
 What went wrong:
> Task :app:transformDexArchiveWithDexMergerForDebug FAILED
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/reactnative/camera/BuildConfig;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lorg/reactnative/camera/BuildConfig;

Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lorg/reactnative/camera/BuildConfig;

### Reproduction steps
yarn add react-native-video
react-native link react-native-video

I use Sdk version 27.0.3

### Expected behavior
app can install in android

### Platform
Which player are you experiencing the problem on:
* Android

**Comment by kievmontana** [comment]
Hi! Maybe a bit late but try to add to your `android/app/build.gradle` 
 multiDexEnabled true inside dependencies like so:

`defaultConfig {
      ...
       multiDexEnabled true
    }`
