### ISSUE TITLE
I can not play video with m3u8 format

### ISSUE THREAD

**Issue by isacmdev** [TheWidlarzGroup/react-native-video#1427]
### Current behavior
When a streaming url is assigned to source, the video never plays.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

### Sample

This is my configuration in the Video component:

Version: 4.3.1

` <Video
      source={{uri: "https://s3.amazonaws.com/yojma/hls/movie/yvZmxnCwaHGSLUpKFzoTlYrOXRdWQgePIqihbfcs/main.m3u8", type:"m3u8"} }
     navigator={ this.props.navigation }
      />`

And this in app/build.gradle:

`dependencies {
    compile project(':react-native-video-exoplayer')
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
}`

And this settings.gradle: 

`rootProject.name = 'Yojma'
include ':react-native-video-exoplayer'
project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
include ':app'`

This is what the m3u8 file looks like:
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=500000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=426x240,AUDIO="aac",SUBTITLES="subs"
240p/file.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=800000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=640x360,AUDIO="aac",SUBTITLES="subs"
360p/file.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1400000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=854x480,AUDIO="aac",SUBTITLES="subs"
480p/file.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2800000,NAME="Main",CODECS="avc1.66.30",RESOLUTION=1280x720,AUDIO="aac",SUBTITLES="subs"
720p/file.m3u8

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="InglÃ©s", DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en", URI="test/audio_english.m3u8"`

**Comment by Navidhp** [comment]
+1

**Comment by cokealmonacid** [comment]
Anyone?

**Comment by CHaNGeTe** [comment]
I am getting this when requesting the stream:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AllAccessDisabled</Code>
    <Message>All access to this object has been disabled</Message>
    <RequestId>02469639E7DD7EB0</RequestId>
    <HostId>4iaIa9tYD60Pal7z290fFnLz7stI9SVwfNxak7noyndG0xmAHThMQto5IuFckXRIFj1xDJ30JM8=</HostId>
</Error>
```

Please share updated streams you are using to diagnose.

**Comment by karanpratapsingh** [comment]
it worked for me when I do this

```
      source={{
        uri,
        type: 'm3u8',
      }}
```
