### ISSUE TITLE
Linker command failed - Xcode Build failed

### ISSUE THREAD

**Issue by TiToMoskito** [TheWidlarzGroup/react-native-video#1430]
### Current behavior
When I want to build the project I got this error:
```
ld: library not found for -lRNVideoPlayer
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And I used the command: `react-native link react-native-video`
### Platform
* iOS

### Picture sample
<img width="570" alt="bildschirmfoto 2019-01-18 um 15 15 56" src="https://user-images.githubusercontent.com/7590208/51392144-6c419f00-1b34-11e9-93ec-daed28da0e40.png">

**Comment by TiToMoskito** [comment]
I just linked everything manually and it works now.

**Comment by jorchg** [comment]
> I just linked everything manually and it works now.

Hey @TiToMoskito I have the same problem. Could you please describe how to manual link this library?

Thank you very much.
