### ISSUE TITLE
android SDK 26 for v4.x

### ISSUE THREAD

**Issue by songzhw** [TheWidlarzGroup/react-native-video#1433]
### Current behavior
According to the README: "Version 4.0.0 now requires Android SDK 26+ and Gradle 3 plugin in order to support ExoPlayer 2.9.0. Google is dropping support for apps using SDKs older than 26 as of October 2018 and Gradle 2 as of January 2019. React Native 0.57 defaults to Gradle 3 & SDK 27.". 
This requires the minSDK for Android at least 26, which is quite high for most application on the market. Most apps are still using minSDK 21, or even 19.

And about "Google recommend sdk 26", I am afraid we are getting it wrong. It requires:
* targetSDK to be 26 or higher
* but the minSDK could still be lower, like 21, 19, 16...

Actually "ExoPlayer 2.9.0 requires SDK 26+" is similar. [This PR](https://github.com/google/ExoPlayer/issues/5274) is just what I am talking about.

### Suggestion
* Make the targetSDK to be 26
* Make the minSDK to lower version, like 19

**Comment by RemyLivewall** [comment]
This should already be possible by overriding the minSdkVersion as seen here: https://github.com/react-native-community/react-native-video#using-app-build-settings. ExoPlayer itself has most features compatible back to API 16.

**Comment by songzhw** [comment]
yes, this could be a solution. 

p.s. but as a library, I think the minSDK is better not to be that high.

**Comment by cobarx** [comment]
We only require minSDK 16, the requirement of 26+ is for the targetSDK. I've updated the README to reflect this. Sorry for the confusion.

**Comment by songzhw** [comment]
> We only require minSDK 16, the requirement of 26+ is for the targetSDK. I've updated the README to reflect this. Sorry for the confusion.

Yes, it's odd. I saw the source code of react-native-video is `minSdkVersion safeExtGet('minSdkVersion', 16)`. But if I am using the latest react-native-video v4.x, I get an error that minSDK is 26. 

p.s. If I switch to react-native-video v3.x , then I don't have this error
