### ISSUE TITLE
Add selectedVideoTrack support for iOS

### ISSUE THREAD

**Issue by am33t** [TheWidlarzGroup/react-native-video#1435]
### Description
Thank you for adding "selectedVideoTrack" for Android ExoPlayer. It works great. Can you add same for iOS? Is there any workaround for iOS?

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by MBakhtiyor** [comment]
Hi. Is there any news about this?

**Comment by flexgrip** [comment]
It definitely doesn't work. I may try to take a look at this... but my skills with the native xcode library this is based on are lacking.

**Comment by mav-raj** [comment]
> ### Description
> Thank you for adding "selectedVideoTrack" for Android ExoPlayer. It works great. Can you add same for iOS? Is there any workaround for iOS?
> 
> ### Platform
> Which player are you experiencing the problem on:
> 
> * iOS

Which version of react-native-video are you using? Because for me selectVideoTrack doesn't work on either of Android or IOS., or am I missing something?

**Comment by khurramwaqar** [comment]
> > ### Description
> > Thank you for adding "selectedVideoTrack" for Android ExoPlayer. It works great. Can you add same for iOS? Is there any workaround for iOS?
> > ### Platform
> > Which player are you experiencing the problem on:
> > 
> > * iOS
> 
> Which version of react-native-video are you using? Because for me selectVideoTrack doesn't work on either of Android or IOS., or am I missing something?

Hi,

can you tell how you have enabled the ABR in android exo.

a sample code can work for me.
