### ISSUE TITLE
VideoPlayer example is broken (again)

### ISSUE THREAD

**Issue by PublicParadise** [TheWidlarzGroup/react-native-video#144]
#### Steps:

```
# start fresh...
git clone https://github.com/brentvatne/react-native-video.git
cd react-native-video
npm install
cd Examples/VideoPlayer/
npm install
open VideoPlayer.xcodeproj
# then hit build/run
```
#### Result:

<img width="624" alt="screen shot 2016-02-05 at 5 25 55 pm" src="https://cloud.githubusercontent.com/assets/2541332/12863651/0fa03c8c-cc2e-11e5-851c-20c955e52ee0.png">

**Comment by PublicParadise** [comment]
I think you guys upgraded to `react-native 0.19.0` (see https://github.com/brentvatne/react-native-video/commit/38e5296eee41bafcc9f7f67c6e85097fde9036c6) but then forgot to update `package.json` in the example. Right?

**Comment by PublicParadise** [comment]
Nope. Still getting the same error even with fixing `package.json`.

**Comment by PublicParadise** [comment]
This commit broke the example: https://github.com/brentvatne/react-native-video/commit/9685932c4207f958992aff4cd7bce11b2de5a662

**Comment by corbt** [comment]
Fixed in https://github.com/brentvatne/react-native-video/pull/149
