### ISSUE TITLE
Exoplayer crashes if the source URI doesn't contain a path

### ISSUE THREAD

**Issue by phsumi** [TheWidlarzGroup/react-native-video#1440]
### Current behavior
RN Video crashes when invoked with a URL that doesn't contain a path (e.g. `http://localhost:8080`)

### Reproduction steps
Just point it to a root URI that serves an actual video file, if the URI doesn't contain a path. It appears the player assumes there is a file name in the path and tries to resolve the content type (regardless of the fact that the server returns the content type anyway).

`<Video source={{uri: "http://127.0.01:8080/?file=foo.mp4"}}`

Error:

`Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference @ inferContentType`

This "fixes" the issue:

`<Video source={{uri: "http://127.0.0.1:8080/foo.mp4"}}`

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by mahadazad** [comment]
I am also having the same issue, only happens on Android Simulator. iOS works fine. The URL that I am providing redirects to another destination. e.g. I provide the uri as `https://live.example.com` the url would redirect to `https://example.com/abc.mp3`

**Comment by paschaldev** [comment]
+1

**Comment by CHaNGeTe** [comment]
Just to get more info, redirect is done by 302 status code?

Have you tried to make the `type`explicit?
```
<Video source={{
uri: "http://127.0.01:8080/?file=foo.mp4",
type: 'mp4'
}}
```

**Comment by ahmetsozkesen** [comment]
> Just to get more info, redirect is done by 302 status code?
> 
> Have you tried to make the `type`explicit?
> 
> ```
> <Video source={{
> uri: "http://127.0.01:8080/?file=foo.mp4",
> type: 'mp4'
> }}
> ```

It has been a while but works like a charm thanks.

**Comment by Rotemy** [comment]
Thanks! saved my say!
