### ISSUE TITLE
I can't play a .mp3 file

### ISSUE THREAD

**Issue by EzequielDeOliveira** [TheWidlarzGroup/react-native-video#1442]
## I've tried use a path for my file, when i put a path to .mp4 file ok but when i put a .mp3 file in the same folder , the audio can't reproduce

my code for VideoComponent:

    import React, {Component} from 'react'
    import PropTypes from 'prop-types'
    import { View, StyleSheet } from 'react-native'
    import Video from 'react-native-video'

    export default class VideoComponent extends React.Component {

      renderVideo () {
          return(
            <Video
              source={{uri: 'file:./assets/JB.mp3'}}
              style={{ width: 800, height: 800 }}
              muted={false}
              repeat={true}
              resizeMode={"cover"}
              volume={1.0}
              rate={1.0}
              ignoreSilentSwitch={"obey"}

            />
          )
      }

      render () {
        return (
          <View>
            {this.renderVideo()}
          </View>
        )
      }
    }

    // Later on in your styles..
    var styles = StyleSheet.create({
      backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
      },
    });

code for app.js :

    import React, {Component} from 'react';
    import {Platform, StyleSheet, Text, View} from 'react-native';
    import VideoComponent from './VideoComponent'

    export default class App extends Component {
      render() {
        return (
            <View>
            <VideoComponent />
            </View>
        );
      }
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
      }
    });

**Comment by gazedash** [comment]
Can reproduce this on android (both on genymotion and avd)

**Comment by EzequielDeOliveira** [comment]
I'm using avd for android , i can play video, but when i try a .mp3, don't reproduces anything

**Comment by kesha-antonov** [comment]
Can't play mp3 on Xiaomi Mi8

**Comment by onitzschke** [comment]
I'm also not able to play `mp3` files.
No problems with `mp4` files.

**Comment by gazedash** [comment]
Downgrading to 4.2.0 make mp3 files work

**Comment by onitzschke** [comment]
@cobarx please reopen this issue, see https://github.com/react-native-community/react-native-video/commit/2898f8cb5a9ac7bfd112477b07f9bc90737e4f5d

**Comment by brian-pitsch** [comment]
I can't play m4a files either in 4.3.x, but it works in 4.2.0.
There is an index out-of-bounds error in logcat, so I'm guessing it's related to 4.3 upgrade that broke playing files only an audio track.

**Comment by wkmcyz** [comment]
I downgraded to v4.2.0 as @brian-pitsch said, and .mp3 file is able to be played. And I tried using Android MediaPlayer instead of Android ExoPlayer in v4.3.1, which worked but caused device to be slow when playing.

**Comment by timmywil** [comment]
Just wanted to point out that I had similar issues with version 4.4.0. I was also not able to play `.mp3` streams in Android and downgrading to 4.2.0 fixed it.

**Comment by Strate** [comment]
Thank you all guys for founding working 4.2.0 version!

**Comment by douglaswissett** [comment]
Hey @Jimud1 - I'm also getting this error (Could not resolve okhttp3) when using react-native-video@4.2.0 with react-native@0.59.1
Did you manage to solve your issue?

**Comment by ghost** [comment]
> Hey @Jimud1 - I'm also getting this error (Could not resolve okhttp3) when using react-native-video@4.2.0 with react-native@0.59.1
> Did you manage to solve your issue?

Sadly Douglas I did not find the solution for this fix, if you have any luck in the meantime be sure to put your results up here, I will do the same if I make any progress. Kind regards, James

**Comment by funkyfourier** [comment]
> > Hey @Jimud1 - I'm also getting this error (Could not resolve okhttp3) when using react-native-video@4.2.0 with react-native@0.59.1
> > Did you manage to solve your issue?
> 
> Sadly Douglas I did not find the solution for this fix, if you have any luck in the meantime be sure to put your results up here, I will do the same if I make any progress. Kind regards, James

The solutions is described here: https://github.com/react-native-community/react-native-video/issues/1524

Basically, just replace `implementation 'com.squareup.okhttp3:okhttp:3.12.0'` with `implementation 'com.squareup.okhttp3:okhttp:3.12.1'` in react-native-video's build.gradle file.

Now, I have not succeeded in getting a (remote) mp3 or m4a file to play on 4.2.0 with RN-0.59.1, not on Android nor iOS. Also tried react-native-video 4.4.0 on RN-0.59.1, but no luck there either.

**Comment by ghost** [comment]
> > > Hey @Jimud1 - I'm also getting this error (Could not resolve okhttp3) when using react-native-video@4.2.0 with react-native@0.59.1
> > > Did you manage to solve your issue?
> > 
> > 
> > Sadly Douglas I did not find the solution for this fix, if you have any luck in the meantime be sure to put your results up here, I will do the same if I make any progress. Kind regards, James
> 
> The solutions is described here: #1524
> 
> Basically, just replace `implementation 'com.squareup.okhttp3:okhttp:3.12.0'` with `implementation 'com.squareup.okhttp3:okhttp:3.12.1'` in react-native-video's build.gradle file.
> 
> Now, I have not succeeded in getting a (remote) mp3 or m4a file to play on 4.2.0 with RN-0.59.1, not on Android nor iOS. Also tried react-native-video 4.4.0 on RN-0.59.1, but no luck there either.

I was able to get the project working on RN0-59.0 but did not try .1, I suggest rolling back to 59.0.



Thanks for the help so far, does anybody know how it'd be best for me to ensure the change within the react-native-video always updates as expected, is it postInstall or preInstall using package.json scripts? or another key word?

**Comment by ghost** [comment]
To resolve the okhttp issue i created a script as below and added it within a scripts folder
react-native-video-gradle-fix.js
`const fs = require('fs')

try {
        var curDir = __dirname
        var rootDir = process.cwd()

        var file = `${rootDir}/node_modules/react-native-video/android-exoplayer/build.gradle`;
        var data = fs.readFileSync(file, 'utf8');

        var doLast = "//FixApplied";
        if (data.indexOf(doLast) !== -1) {
            throw "React Native Video Gradle fixed.";
        }
        
        var result = data.replace('implementation(\'com.google.android.exoplayer:exoplayer:2.9.1\') {', 'implementation(\'com.google.android.exoplayer:exoplayer:2.7.3\') {');
        var result2 = result.replace('implementation(\'com.google.android.exoplayer:extension-okhttp:2.9.1\') {', 'implementation(\'com.google.android.exoplayer:extension-okhttp:2.9.3\') {');
        var result3 = result2.replace('implementation \'com.squareup.okhttp3:okhttp:3.12.0\'', 'implementation \'com.squareup.okhttp3:okhttp:3.12.1\'');

        fs.writeFileSync(file, result3, 'utf8');
        console.log('React Native Video Gradle Fix Done');
    } catch (error) {
        console.error(error);
    }`

then within package.json {
scripts {
    "postinstall": "node scripts/react-native-video-fix.js"
  }
}


It's a bit of a dirty fix but it works.

Good luck everybody! And thanks for the help!

J

**Comment by funkyfourier** [comment]
Ok, I managed to get audio only working on both android and iOS.

On iOS, it seems like having defined textTracks breaks playback of files which are audio only. So when I removed the following code audio starts working again:

`textTracks={[
                {
                  title: "English CC",
                  language: "en",
                  type: TextTrackType.VTT,
                  uri: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
                }
              ]}
              selectedTextTrack={{
                type: "title",
                value: "English CC"
              }} `

On Android, implementing [PR 1529](https://github.com/react-native-community/react-native-video/pull/1529) did the trick. I hope that one will get merged with the next release.

On Android subtitles are displayed regardless of the file being audio only or not, but on iOS it just fails silently if the media file is audio only. It would be ideal if perhaps on iOS there could be an onError called with an appropriate description on those cases.

Edit: This is with react-native-video 4.4.0 on RN 0.59.1

**Comment by ghost** [comment]
> Ok, I managed to get audio only working on both android and iOS.
> 
> On iOS, it seems like having defined textTracks breaks playback of files which are audio only. So when I removed the following code audio starts working again:
> 
> `textTracks={[ { title: "English CC", language: "en", type: TextTrackType.VTT, uri: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt" } ]} selectedTextTrack={{ type: "title", value: "English CC" }} `
> 
> On Android, implementing [PR 1529](https://github.com/react-native-community/react-native-video/pull/1529) did the trick. I hope that one will get merged with the next release.
> 
> On Android subtitles are displayed regardless of the file being audio only or not, but on iOS it just fails silently if the media file is audio only. It would be ideal if perhaps on iOS there could be an onError called with an appropriate description on those cases.
> 
> Edit: This is with react-native-video 4.4.0 on RN 0.59.1

Funky when you're using local files are you using require('../path/to/file') instead of the uri???

E.g

![image](https://user-images.githubusercontent.com/31246882/54820537-75b3c880-4c97-11e9-8fae-afac24d8db0e.png)


My bad I read that incorrectly. my bad. 

I wish you luck with the object definitions, hope you find the culprit!

**Comment by funkyfourier** [comment]
> Funky when you're using local files are you using require('../path/to/file') instead of the uri???

Yep.

**Comment by gazedash** [comment]
@funkyfourier does the mp3 files work on 4.4.0 if you don't specify the text tracks? 🤔

**Comment by funkyfourier** [comment]
> @funkyfourier does the mp3 files work on 4.4.0 if you don't specify the text tracks? 🤔

Yes, on iOS it does when not specifying text tracks. On Android it works, regardless of text tracks, if I implement [PR 1529](https://github.com/react-native-community/react-native-video/pull/1529).

**Comment by wangliang1124** [comment]
> PR 1529
It works for me. (4.4.0 )
https://github.com/react-native-community/react-native-video/pull/1529

**Comment by funkyfourier** [comment]
Just tried the 4.4.1 release, and it is working fine for playing audio only files on android.

**Comment by awinograd** [comment]
Same issue trying to use textTracks with an mp3 on react-native-video@5.0.1
