### ISSUE TITLE
Spotify doesnt stop background audio

### ISSUE THREAD

**Issue by taliseen** [TheWidlarzGroup/react-native-video#1443]
### Current behavior
Android - When playing audio-only streaming in the background, opening spotify and hitting play in spotify does not stop the audio from react-native-video in my app.

### Reproduction steps
open my app, hit play on stream, open spotify, hit play
### Expected behavior
my app should stop playing audio in background upon starting spotify or any other app audio 
This works fine on ios by the way
### Platform
Which player are you experiencing the problem on:

* Android ExoPlayer
version info:
android api level 26 rnv 3.0 rn .57

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by MisaZ10** [comment]
You tried whith this event ?

onAudioFocusChanged={this.onAudioFocusChanged} // Callback when audio focus has been lost - pause if focus has been lost
