### ISSUE TITLE
MediaFocusControl: Max AudioFocus stack size reached, failing requestAudioFocus()

### ISSUE THREAD

**Issue by mytrytry** [TheWidlarzGroup/react-native-video#1444]
### Current behavior
Video component may cause the following message in logcat
```
MediaFocusControl: Max AudioFocus stack size reached, failing requestAudioFocus()
```

At the same time, because requesting audio focus failed the video component cannot play any video.
### Reproduction steps

1. Render multiple Video components in a FlatList
2. Play and stop over 100 times
3. The Video component cannot play any video. The following message appears in logcat

```
MediaFocusControl: Max AudioFocus stack size reached, failing requestAudioFocus()
```

Possible reason:
* The Video component calls requestAudioFocus/abandonAudioFocus for audio focus
* AudioFocus stack uses clientId as a unique identifier
* clientId is concatenated from ReactExoplayerView.toString
* ReactExoplayerView.toString is NOT guaranteed not to change for the lifetime of the object
* abandonAudioFocus cannot reduce the size of AudioFocus stack because the different clientId from requestAudioFocus 
* Max AudioFocus stack size (100) can easily reached
* The Video component fails to request audio focus

### Expected behavior
The Video component plays video normally.

Workaround works for me:   
Override the toString method in combrentvatne.exoplayer.ReactExoplayerView. This guarantees the return value not to change for the lifetime of the object.

```
@Override
public String toString() {
      return getClass().getName() + "@" + Integer.toHexString(System.identityHashCode(this)); 
}
```

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by pengcao1** [comment]
@mytrytry 
Yes, correct.
did you have any idea for this issue?
about two weeks ago, I meet the same issue,
Maybe we can talk

**Comment by pengcao1** [comment]
yeah,
could we assign the audiofocus id when we require audiofocus instead of  Object.toString
> I read the android source code, I can't find the interface
1 we can't control the Android native lifecycle 
2 we can't get the full audiofocus stack

**Comment by dkoo761** [comment]
+1

I have multiple <video> elements on my page (up to 5, although they are only playing audio) which are started/stopped at the same time. If I click my Play/Pause button about once a second to toggle them on/off, I run into this error after fewer than 20 clicks. After that, the user must close the app and reopen it for it to work again.

@mytrytry I tried your fix and thankfully it worked like a charm! Thank you sooo much as this was turning into a blocker for me.
