### ISSUE TITLE
Trying to register two views with the same name RCTVideo

### ISSUE THREAD

**Issue by khushhal** [TheWidlarzGroup/react-native-video#1450]
### Current behavior
App crash

### Reproduction steps
1. I am using the react-native-video for videos in app, and then i install the react-native-gifted-chat library for chat functionality in app.
2. After installing react-native-gifted-chat the app crashed and its saying trying to register two views with the same name RCTVideo.
3. The react-native-video is used in one view and react-native-gifted-chat in different view.

### Expected behavior
App shouldn't be crash.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android

I am not sure if this is issue of react-native-video or react-native-gifted-chat.
![screenshot_2019-01-26-12-23-37-542](https://user-images.githubusercontent.com/8819343/51783813-8ba87f80-2165-11e9-8699-a3131fe51c04.jpeg)

**Comment by vanhungoz** [comment]
i resolved it by delete react-native-video in gifted-chat/node-module. it's just a trick

**Comment by jaspervanbrian** [comment]
Same issue here.

**Comment by stephanschoenig** [comment]
Same issue, which started when I upgraded to the latest version of gifted-chat that now has a dependency on react-native-video.

**Comment by khushhal** [comment]
if you are not having video in chat you can downgrade the version to use both libraries together
"react-native-gifted-chat": "^0.4.3"

But with this video will not supported in chat.

**Comment by khalisafkari** [comment]
Trik work 
1. Clone giftchat repo
2. Open package.json move dep react-native-video : 3.*.*  to peerDependencies 
"react-native-video":"*"

**Comment by chevulkar** [comment]
Trik work

    1. Clone giftchat repo

    2. Open package.json move dep react-native-video : 3._._  to peerDependencies
       "react-native-video":"*"


This dosen't work :(

**Comment by khalisafkari** [comment]
@chevulkar after editing package.json install the file through the path

Or your npm install https://github.com/khalis411/react-native-gifted-chat.git

**Comment by chevulkar** [comment]
which package.json should I edit my app or gifted chat's ?

**Comment by khalisafkari** [comment]
Gifted chat

**Comment by shide1989** [comment]
After looking in the rn giftedchat component, there is no need for **react-native-video**, 
to resolve this issue you can remove the react-native-video package from the node_modules.

Note to the author : react-native-video isn't used at all in your giftedchat package, can you please remove it from package.json and package-lock.json ?
thanks

**Comment by joaodematejr** [comment]
+1

**Comment by joaodematejr** [comment]
"react-native-video": "^4.4.0",   
"react-native-gifted-chat": "^0.7.2",

**Comment by rabindrachhachan** [comment]
Same issue. When i upgrade gifted chat from 0.4.3 to 0.7.2. I have used react-native-video .

**Comment by SumitThakr** [comment]
I have solve this problem by following steps--
  1> install separately "react-native-video"
  2> Delete  "react-native-video" folder from Node-Modules of Gifted Chat repositories, if it is exist..
  3>after  that  "react-native link react-native-video"
       like That:
         include ':react-native-video'
        project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react- 
        native-video/android')

     ensure that link with only "android" not with "android-exoplayer"

**Comment by AriesTech** [comment]
Instead of importing again react-native-video, you can use directly the one declared in gifted chat (without any modification):

import Video from "react-native-gifted-chat/node_modules/react-native-video";

**Comment by noelsp** [comment]
> Instead of importing again react-native-video, you can use directly the one declared in gifted chat (without any modification):
> 
> import Video from "react-native-gifted-chat/node_modules/react-native-video";

Thanks, @AriesTech ! It works. I also had to replace my podfile:
`pod 'react-native-video', :path => '../node_modules/react-native-gifted-chat/node_modules/react-native-video/react-native-video.podspec'
`

**Comment by Eddy118** [comment]
I am not Using react-native-gifted-chat but still I am getting this error Tried To register two Views with the same name RTCVideoView

**Comment by stardollarstar** [comment]
so after 2 hours of debugging doing some random things..... I found a solution. This project uses some kind of old Git and gradle can't get it without jcenter().

Anyways, add jcenter() to your build.gradle (not APP build.gradle) and npx react-native run-android (rebuild)

**Comment by dguard** [comment]
@SumitThakr

>3>after that "react-native link react-native-video"

Thanks,
That solved issue for `react-native-video-controls` module

**Comment by bivainis** [comment]
Had the same error, but not using any other package. It could be that there was some leftover module in node_modules. 

1. removed node_modules dir `rm -rf node_modules`
2. installed packages again
3. installed pods again
4. ran on simulator: video works
