### ISSUE TITLE
how to detect tap event to dismiss keyboard?

### ISSUE THREAD

**Issue by ManuRodgers** [TheWidlarzGroup/react-native-video#1451]
### Current behavior
Describe what happens when you encounter this issue.
I am working on a chat app with react-native-video and react-native-gifted-chat, and I put GiftedChat component on top of Video component. Please see those two pictures below,  when I want to type something, then the keyboard will pop up and I can only tap on the area where the last chat message shows to dismiss keyboard. what I want to achieve is that I can also tap the above video area to dismiss the keyboard with Keyboard.dismiss(). Therefore, I want to know how to detect the tap event on react-native-video to invoke Keyboard.dismiss()
![image](https://user-images.githubusercontent.com/33333844/51793189-95d38800-2210-11e9-96b9-a568720d5347.png)
![image](https://user-images.githubusercontent.com/33333844/51793205-ce736180-2210-11e9-845a-03c3739f4f89.png)

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by ethanyuwang** [comment]
did you find a solution to this?
