### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by vpandura** [TheWidlarzGroup/react-native-video#1454]
### Current behavior
Trying to embedding it with an existing component. Getting error : 

``in ./node_modules/react-native-video/Video.js
Module parse failed: Unexpected token (54:7)
You may need an appropriate loader to handle this file type.
|   }
| 
|   seek = (time, tolerance = 100) => {
|     if (isNaN(time)) throw new Error('Specified time is not a number');
|     
``
### Reproduction steps
Code : 
`import Video from 'react-native-video';
.
.
.
return(
  <Video
        source={{ uri: './videosample/SampleVideo.mp4' }}
        style={{ width: 800, height: 800 }}
      />
)
`
### Expected behavior
Display video

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by vanhungoz** [comment]
you have to make sure that pass integer when using seek(number) function

**Comment by mbeghe** [comment]
@vpandura did you find a solution for this?
