### ISSUE TITLE
Error 403: Unrecognized media format - error streaming 

### ISSUE THREAD

**Issue by isacmdev** [TheWidlarzGroup/react-native-video#1456]
### Current behavior
The video never plays

### Reproduction steps
Add the streaming link and compile.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Example:
    import React, { Component } from 'react';
    import Video fom 'react-native-video';

    export default class VideoTest extends React.Component {

    render() {
        return (
             <View>
                    <Video
                    source={{ uri: "https://s3.amazonaws.com/yojma/hls/movie/TDGVYNnBhbQMusqagzXlUZmKxcJPEoSdvIpwLAef/main.m3u8"}}
                />               
             </View>
        )
    }}
`

**Comment by fabiorbap** [comment]
Im having the same problem. The video actually plays sometimes, but it eventually doesn't.

**Comment by andy-io** [comment]
is there a solution for this bug?

**Comment by nathantqn** [comment]
I'm facing the same problem, any solution for this :(

**Comment by cKurultayKalkan** [comment]
Duplicate of #1068

**Comment by SanthoshCreationz** [comment]
![Screenshot_2020-10-18-14-57-03-611_com liontvranipet](https://user-images.githubusercontent.com/45474802/96369770-68173b00-1179-11eb-8398-11f8d2872a8f.jpg)

Can anyone help me to fix this issue.

**Comment by softwebtuts** [comment]
> ![Screenshot_2020-10-18-14-57-03-611_com liontvranipet](https://user-images.githubusercontent.com/45474802/96369770-68173b00-1179-11eb-8398-11f8d2872a8f.jpg)
> 
> Can anyone help me to fix this issue.

Having the same issue please anyone help me.
