### ISSUE TITLE
audioOnly with hls doesn't work

### ISSUE THREAD

**Issue by jedashford** [TheWidlarzGroup/react-native-video#1457]
### Current behavior
Setting audioOnly option when feeding an hls playlist doesn't play only the audio. It still plays the video.

### Reproduction steps
Set the audioOnly option to true. 

### Expected behavior
Video Still plays

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
Here is the example player:
```      
<VideoPlayer
        source={{ uri: 'https://dhr9tsl74k2dl.cloudfront.net/102_Heath_Harmison_audio_only_test.m3u8' }}
        poster={'https://baconmockup.com/300/200/'}
        selectedAudioTrack={{
          type: "name",
          value: "English"
        }}
        audioOnly={true}
        onProgress={onProgress}
        progressUpdateInterval={1000}
        playInBackground
        ignoreSilentSwitch='ignore'
        paused={paused}
        onBuffer={onBuffer}
        onEnd={onEnd}
        onLoad={onLoad}
        volume={volume}
        style={styles.video}
        resizeMode={'contain'}
        ref={ref => onRef(ref)}
      />
```

I've tried setting the selectedAudioTrack. I've tried adding a specific 'English' audio track to the hls file, I've tried with and without selectedAudioTrack, with and without the poster. Nothing will play just audio for me. It always loads and plays the video tracks. 

Anyone using hls and can play audio only? 

I have a feeling I'm not configuring the playlist correctly.

**Comment by jedashford** [comment]
wait... Looking at the PR that added audioOnly, it appears that adding the param `audioOnly` only adds the poster to the screen. 

https://github.com/react-native-community/react-native-video/pull/1039

Unless I'm missing something, the PR above doesn't have logic to `false (default) - Display the video as normal, true - Show the poster and play the audio`

Am I missing something?

```
Indicates whether the player should only play the audio track and instead of displaying the video track, show the poster instead.

false (default) - Display the video as normal
true - Show the poster and play the audio
```

**Comment by jedashford** [comment]
Hls can't select audio only stream. The documentation for the PR referenced here should probably be revised

**Comment by mtalhagaoglu** [comment]
Hi. I'm facing with same problem. I want to show the video only at certain times but i can't control that with audioOnly or giving poster.
