### ISSUE TITLE
How to resize video without changing it's aspect ratio?

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1458]
### Current behavior

```
  constructor(props) {
    super(props);
    this.state = {
        screenWidth: Dimensions.get('window').width,
        heightScaled: null,
    };  
  }   

<View style={styles.videoView}>
       <Video 
          source={video}
          ref={(ref) => { this.player = ref }}  
          repeat={true}
          resizeMode={"contain"}
          style={{
              width: this.state.screenWidth,
              height: this.state.heightScaled,
           }}
          onLoad={response => {
                const { width, height } = response.naturalSize;
                const heightScaled = height * (this.state.screenWidth / width);

                response.naturalSize.orientation = "horizontal";
                this.setState({ heightScaled: heightScaled });
          }}
       />
</View>
```
**styles**
```
videoView: {
  flex: 1,
  width: Dimensions.get('window').width,
  height: 100
}
```

I'm fetching video from api and then using it in a video component using react-native-video. I don't know how I can resize my video to fit in a view without stretching the video.

### Expected behavior

Here is the result of the above code.

[output](https://i.stack.imgur.com/jpdrR.png)

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

**Comment by ShaneKeney** [comment]
Came across this while looking for an answer.

I solved this by just doing the following

```
videoView: {
  flex: 1,
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').width
}
```

And then just use ` resizeMode={Video.RESIZE_MODE_CONTAIN}` as a prop to the Video component

**Comment by plus-** [comment]
Cover and contain both have weird aspect ratio, whereas they are both resize mode that don't temper the aspect ratio.
Stretched (which actively changes the aspect ratio) will display properly on android.

So I think the problem is the video source itself in android has the wrong aspect ratio.
