### ISSUE TITLE
Video stops in between on Android

### ISSUE THREAD

**Issue by sahilvicesoftware** [TheWidlarzGroup/react-native-video#1459]
### Current behavior
I am playing a video from a remote URL.It works fine on iOS but, on android it stops after 2-3 minutes every time i play it

### Expected behavior
Video should play for full length

### Platform
Which player are you experiencing the problem on:

* Android ExoPlayer

### Video sample
https://res.cloudinary.com/www-elate-wellbeing-com/video/upload/v1545985674/self_love_and_forgiveness_meditation.mp4

**Comment by vbnospace** [comment]
I am also facing this issue

**Comment by v-vashchenko** [comment]
same +1

**Comment by KarinaKorsgaard** [comment]
Same for me. Although I am using react-native-video. Also seems to start very slow on android every time it is played.

**Comment by v-vashchenko** [comment]
> Same for me. Although I am using react-native-video. Also seems to start very slow on android every time it is played.

Have a try with a current stable version, for me issue was resolved

**Comment by KarinaKorsgaard** [comment]
Which version are you using? 
I have "react-native-video": "^5.0.2",

**Comment by pateljoel** [comment]
Has this issue been fixed???

**Comment by kesha-antonov** [comment]
Any solution guys?

**Comment by freeboub** [comment]
Just tested on androidtv emulator.
No issue found.
I close the ticket, please attach a logcat for more investigation.
