### ISSUE TITLE
RCTNetworking in RN v0.18.1 and Element Type is invalid in RN v0.19

### ISSUE THREAD

**Issue by tklivan** [TheWidlarzGroup/react-native-video#146]
## When using RN v0.18.1

The component works well for iOS. However it failed in Android with the message "RCTNetworking.sendRequest got 6 arguments, expected 7" upon loading of app.

After reading up online, I decided to upgrade to RN v0.19.
## After upgrade to RN v0.19

BOTH iOS & Android fails on the screen using the component with the message:
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of"

Doing the following resolves the iOS screen and loads the video:

`var Video = require('react-native-video').default;`

Error is gone on Android but video is not loading.

**Comment by tklivan** [comment]
Question: Where do i put the video files for android? Which directory?

**Comment by doublefree** [comment]
+1

**Comment by tklivan** [comment]
Ok I have placed videos in res/raw.

Nothing is loaded though. Any help?

**Comment by joseph-adam** [comment]
Does anyone know why this happens?

RCTWebSocketModule.connect was called with 4 arguments, but expects 2.

**Comment by braco** [comment]
@nurdeen 

import Video from 'react-native-video';

**Comment by tklivan** [comment]
@braco 

That only works on IOS. Android is still the same. No video loaded. No errors.

**Comment by hinet** [comment]
me too,Android is still the same. No video loaded. No errors.

**Comment by Choujiji** [comment]
+1, RN 0.21  Android
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of"

**Comment by KBLNY** [comment]
+1 Android is still the same. No video loaded. Got the following:
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of"

**Comment by Choujiji** [comment]
Doing the following resolves the iOS screen and loads the video:

var Video = require('react-native-video').default;

video can be played. Thanks.

RN 0.24.0 Android 4.3

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by unmec** [comment]
@Choujiji Thanks you saved my day. :)
iOS 10
RN 0.39.0
