### ISSUE TITLE
Sounds from other apps stop when launching.

### ISSUE THREAD

**Issue by wmonecke** [TheWidlarzGroup/react-native-video#1462]
### Current behavior
I thought the muting of the video / settings silent `ignoreSilentSwitch` to ignore would allow audio from other apps to still play while using the app with react-native-video.

I have a background video on my main landing page.

### Expected behavior
Audio of other apps (Spotify), should keep going while using the app.

### Platform
* iOS
* Android

**Comment by wmonecke** [comment]
@cobarx Any ideas?

**Comment by franckmaurin** [comment]
Same here

**Comment by chuanzhang2018** [comment]
Same here    version 3.2.1

**Comment by evanjmg** [comment]
I get this still

**Comment by zi6xuan** [comment]
same too

**Comment by zi6xuan** [comment]
https://github.com/react-native-community/react-native-video/pull/959
It seems that someone has already proposed pr, I don’t know when it will merge.

**Comment by zi6xuan** [comment]
In the readmine about this

> Audio Mixing
> At some point in the future, react-native-video will include an Audio Manager for configuring how videos mix with other apps playing sounds on the device.
> 
> On iOS, if you would like to allow other apps to play music over your video component, make the following change:
> 
> AppDelegate.m
> 
> #import <AVFoundation/AVFoundation.h>  // import
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   ...
>   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];  // allow
>   ...
> }
> You can also use the ignoreSilentSwitch prop.

It is work for me

**Comment by camel113** [comment]
@zi6xuan maybe works for iOS but no information about Android

**Comment by camel113** [comment]
@wmonecke did you find a solution?

**Comment by jaycee425** [comment]
seems still no solution for android?

**Comment by ThienMD** [comment]
still have error in ios

**Comment by CHaNGeTe** [comment]
Can you check with https://github.com/react-native-community/react-native-video/pull/1469?

**Comment by CHaNGeTe** [comment]
Check on 4.4.3

**Comment by bcgilliom** [comment]
Just a note in case someone else hits the same thing... If you have a video that shows on launch, like behind a sign in screen, the setCategory call in app delegate needs to happen before any of the react native bundle loading stuff for it to work in release builds

**Comment by 0xPetra** [comment]
From the docs. This should work:

> To use this feature on iOS, you must:
> * [Enable Background Audio](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW3) in your Xcode project
> * Set the ignoreSilentSwitch prop to "ignore"

**Comment by Adnan-Bacic** [comment]
to allow sounds to keep playing from other apps(tested itunes music and safari)for me it worked when i set:
`ignoreSilentSwitch="obey"`

i did not have to edit AppDelegate.m

the docs for this can be a little confusing, to quote a previous answer:

> In the readmine about this
> 
> > Audio Mixing
> > At some point in the future, react-native-video will include an Audio Manager for configuring how videos mix with other apps playing sounds on the device.
> > On iOS, if you would like to allow other apps to play music over your video component, make the following change:
> > AppDelegate.m
> > #import <AVFoundation/AVFoundation.h>  // import
> > 
> > * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> >   {
> >   ...
> >   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];  // allow
> >   ...
> >   }
> >   You can also use the ignoreSilentSwitch prop.
> 
> It is work for me

the docs just mention:

`You can also use the ignoreSilentSwitch prop.`

but what does it have to be set to?

for this person it worked setting `ignoreSilentSwitch` to `ignore`.
for me it worked setting `ignoreSilentSwitch` to `obey`.

i also only had problems on ios. android worked fine, even if it was just `muted={true}`.

**Comment by sanyamg99** [comment]
Does anyone has any solution for this?
Even after adding `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];` in my AppDelegate.m file, music from other apps stops.
I have also tried to set **ignoreSilentSwitch** to both ignore and obey but nothing seems to work.
Any help will be very much appreciated

**Comment by bmitioglov** [comment]
for me it only works with 'obey', but I want my videos to actually ignore the switch. What could I do?
I tried this: 

- [Enable Background Audio](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW3) in your Xcode project

- Set the ignoreSilentSwitch prop to "ignore"

It didn't work for me

**Comment by frankusu** [comment]
Same here, I'm trying to 
Play background music when video muted -> stop background music when video unmuted 
But even with the Appdelegate change and ignoreSilentSwitch. if I have 
`mixWithOther={isVideoMuted ? 'mix' : 'inherit'}`  the inherit doesn't apply
