### ISSUE TITLE
Accessing view manager configs directly off UIManager via UIManager['RCTVideo'] is no longer supported. Use UIManager.getViewManagerConfig('RCTVideo') instead.

### ISSUE THREAD

**Issue by omercanyigit** [TheWidlarzGroup/react-native-video#1463]
I can not use the library. It is saying that

" Accessing view manager configs directly off UIManager via UIManager['RCTVideo'] is no longer supported. Use UIManager.getViewManagerConfig('RCTVideo') instead. "

what can i do?

Thanx

**Comment by jakks-team** [comment]
I'm getting just a warning for this same issue, made a fix for it on my own device.
After the fix it is able to play Audio correctly. Haven't tested for Video.

https://github.com/react-native-community/react-native-video/commit/e830128f2ad595c28117900b599f4652614ebef4
This is the commit for my changes.

**Comment by alphabikram** [comment]
please somebody update this ?

**Comment by omercanyigit** [comment]
@jakks-team reason is correct but you have to update from the node_modules. It must be updated from the author.

**Comment by jakks-team** [comment]
> @jakks-team reason is correct but you have to update from the node_modules. It must be updated from the author.

any guide on how to update from node_modules?
I'm new to committing changes for github projects.

**Comment by zacwasielewski** [comment]
@jakks-team You should submit a pull request with your change.

Here are the guidelines for this specific project: https://github.com/react-native-community/react-native-video/blob/master/.github/PULL_REQUEST_TEMPLATE.md

And here are instructions for creating a pull request on Github: https://help.github.com/articles/creating-a-pull-request/

Hope that helps!

**Comment by jgreen01su** [comment]
> > @jakks-team reason is correct but you have to update from the node_modules. It must be updated from the author.
> 
> any guide on how to update from node_modules?
> I'm new to committing changes for github projects.

I think @omercanyigit means [installing git commit as npm package](https://stackoverflow.com/a/18049685). ¯\_(ツ)_/¯

I've tested this commit and it works on Android and iOS. Thank you so much @jakks-team !

This is a critical bug fix!

**Comment by mhtoyoda** [comment]
When will this commit @jakks-team ?

**Comment by jakks-team** [comment]
> When will this commit @jakks-team ?

I'm not sure.
As I don't have write access to merge my commit to the master branch.
Please [check here](https://github.com/react-native-community/react-native-video/pull/1466) for the status as someone else helped to open a PR to merge my commit already.

And I think someone should close this issue and check on [the PR](https://github.com/react-native-community/react-native-video/pull/1466) to have someone with write access to master branch to merge this there.

**Comment by luisnaranjo733** [comment]
According to the PR @jakks-team  linked above, this is fixed with 4.4.0, but I'm still seeing this issue on that version.

I see a different fix than the one that jakks-team presented in my node_modules 4.4.40

    let nativeResizeMode;
    const RCTVideoInstance = this.getViewManagerConfig('RCTVideo');

    if (resizeMode === VideoResizeMode.stretch) {
      nativeResizeMode = RCTVideoInstance.Constants.ScaleToFill;
    } else if (resizeMode === VideoResizeMode.contain) {
      nativeResizeMode = RCTVideoInstance.Constants.ScaleAspectFit;
    } else if (resizeMode === VideoResizeMode.cover) {
      nativeResizeMode = RCTVideoInstance.Constants.ScaleAspectFill;
    } else {
      nativeResizeMode = RCTVideoInstance.Constants.ScaleNone;
    }
