### ISSUE TITLE
react-native-video crashing in production AVPlayer _createAndConfigureFigPlayerWithType:completionHandler:

### ISSUE THREAD

**Issue by wmonecke** [TheWidlarzGroup/react-native-video#1472]
### Current behavior

I have seen 3 occurrences of the following crash in my production app and wanted to see if anyone has encountered the same problem?

<img width="1023" alt="screenshot 2019-02-07 at 23 34 54" src="https://user-images.githubusercontent.com/24256469/52447478-1ce9ff80-2b31-11e9-98c3-47ab9a59fef9.png">

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
It is a plain .mp4 file

**Comment by evanjmg** [comment]
+1 I have the same issue. It crashes and then it works when I open the app again.

**Comment by jvandenaardweg** [comment]
Same issue

Only have crash reports from iPhone XR on  iOS 12.3.1. Dunno if that's the same user for me though and if it's relevant to know

![Screenshot 2019-07-23 at 14 24 57](https://user-images.githubusercontent.com/5155373/61712077-d17d8380-ad55-11e9-997e-9f9c733ac882.png)

```
"react-native-video": "^4.4.4",
"react-native": "0.59.9",
```

**Comment by flexgrip** [comment]
Everything works great for me in my debug scheme. Then I toggle from debug to release and poof (the moment I hit play). No idea what can be causing this. I feel like this stuff happens randomly every so many hours. I manage to get everything working and then a few hours later it crumbles.

**Comment by fatinWasta** [comment]
+1
Any leads on this one?

**Comment by qclmnt** [comment]
Do you guys check that you remove all observers on your AVPlayer or AVPlayerItem when you deallocate it? I had a similar issue caused because of that.
