### ISSUE TITLE
Is seek method work on Android ?

### ISSUE THREAD

**Issue by stephane-r** [TheWidlarzGroup/react-native-video#1476]
### Current behavior
I would like jump to minutes using `seek` method. I try the example on documentation, but nothing is happening : 

```
<Video
            source={{ uri: `https://${YOUTUBE_API_STREAM_URL}/${source.id}` }}
            audioOnly={true}
            ref={audio => (this.audio = audio)}
          />
```

And button with onPress event : 

`this.audio.seek(100); // nothing is happening`

### Expected behavior
I would like jump to 100 secondes.

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

Thank you !

**Comment by ronfogel** [comment]
I am experiencing the same issue.
I was able to verify that the issue exists only in exo player while it works with the older android player.

**Comment by iagormoraes** [comment]
I'm using the version 3x and is working fine, inside of onEnd at least works because the ref already exists.

**Comment by firofame** [comment]
"react-native-video": "^4.4.1",
In Android, it doesn't work when paused.

**Comment by giniedp** [comment]
Having the same issue. 

- Android
- exoplayer

This happens however only for .aac files. mp3, wav and video files seek fine

**Comment by giniedp** [comment]
for my case i can go around the issue by recording audio files in mp4 format.

**Comment by pyeonjaesik** [comment]
Did you fix  this error?

**Comment by stephane-r** [comment]
Hey

`seek` method is ok on my Android project https://github.com/stephane-r/HoloPlay/blob/develop/src/components/Player/index.tsx#L242

**Comment by Abdullah1428** [comment]
I needed to show the exact time of the video to the user according to the sliding of the trim slider. 
I was facing a similar issue and I got to manage a workaround in my case. I hope it's helpful to anyone facing a similar issue.

```
const [check, setCheck] = useState(true)
onProgress = {onProgress}

const onProgress = ({currentTime}) => {
    if (Math.round(currentTime) === 0 && checked) {
      if (player) {
        player.current.seek('jump to your desired value');
        setChecked(false);
      }
    }

   if (Math.round(currentTime) > 0) {
      if (checked) {
      } else {
        setChecked(true);
      }
    }
}
```

**Comment by DrifterAtSea** [comment]
Try recording a video with the camera and play the mp4. If you can seek with the camera generated mp4, then the problem appears to be with the encoder not being properly setup.
