### ISSUE TITLE
(IOS) Element type is invalid: expected a string

### ISSUE THREAD

**Issue by orcunorcun** [TheWidlarzGroup/react-native-video#1477]
**Versions:**
"react": "^16.5.1",
"react-native": "0.51.0",
"react-native-video": "^4.3.1",

**Error Message:** 
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.

Check the render method of `Video`.

**Codes:**

```
import Video from 'react-native-video';

const styles = StyleSheet.create({
  video: {
    width: Dimensions.get('window').width * 0.15,
  },
});
------------------------------------------------
return (
  <Video
      source={{ uri: video.url }}
     resizeMode='cover'
      style={styles.video}
  />
);
```

**Comment by ramirobg94** [comment]
+1

**Comment by DeabitTech** [comment]
why closed this issue? i have already now exactly, please can you help me? @hueniverse

**Comment by freeboub** [comment]
Looks like a host issue, please define height and width
