### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1479]
Message `Undefined is not an object` on start application
![image](https://user-images.githubusercontent.com/30437729/52607949-88f19e00-2e78-11e9-892d-73108ef4b569.png)

**Comment by DrummerSi** [comment]
+1 same issue here

**Comment by samtoya** [comment]
+1 same issue

**Comment by DrummerSi** [comment]
I solved this issue today.

First remove the pod video component and re-add it
```
react-native unlink react-native-video
react-native link react-native-video
```

Then open the PODFILE in your IOS directory and make sure it looks something like:
```
target '<project_name>' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification',
    'RCTCameraRoll',
    'RCTSettings',
    'RCTBlob',
    'RCTGeolocation',
    'DevSupport'
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
end
```

Note: yoga, DoubleConversion, glog & Folly are all required too

Then run `pod install` from the IOS directory.
Before running 'react-native run-ios', I made sure that the project properly compiled within Xcode.

**Comment by n1ru4l** [comment]
Seems like you did not link the project. Please follow the instructions mentioned in the readme.

**Comment by snowch** [comment]
I don't have an ios folder - presumably because I'm using Expo.  Does this component work with Expo projects?

**Comment by n1ru4l** [comment]
@snowch Depends. might work with the expo SDK, however a pure expo project does AFAIK not allow adding additional native code (and therefore `react-native-video` might not work).
