### ISSUE TITLE
Would be great to support alpha channel videos

### ISSUE THREAD

**Issue by gijoehosaphat** [TheWidlarzGroup/react-native-video#148]
Some videos have alpha channels, and can be creatively used to really enhance ones app. Would really be great if this could be an enhancement.

**Comment by kitolog** [comment]
+1

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by lab-intermedia-vsvu-sk** [comment]
the first question is still on top

**Comment by lukechatton** [comment]
Was there every any progress on this front? Alpha channels would be great.

**Comment by ethanyuwang** [comment]
has there been a support for this?

**Comment by anutting** [comment]
Any update on this?

**Comment by psychosoft** [comment]
WOuld be gr8

**Comment by andresteves** [comment]
Any support on this?

**Comment by freeboub** [comment]
I have reopen the issue, but it seems exoplayer doesn't support it : https://github.com/google/ExoPlayer/issues/7789

I didn't check avplayer support
