### ISSUE TITLE
Program type already present: com.RNFetchBlob.RNFetchBlob$3

### ISSUE THREAD

**Issue by alphabikram** [TheWidlarzGroup/react-native-video#1481]
RNFetchBlob **works perfectly with my IOS version** but I am not able to work with Android version.

When I try to run for android :
react-native run-android

**Error says =>**

**FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: **Error while merging dex archives:** /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/62, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/externalLibsDexMerger/debug/0, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/46.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/47.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/48.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/56.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/57.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/58.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/59.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/60.jar, /Volumes/King/_REACT_NATIVE/Good_Vibes/android/app/build/intermediates/transforms/dexBuilder/debug/61.jar
  **Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.**
  **Program type already present: com.RNFetchBlob.RNFetchBlob$3**

**Any idea?** 
I couldn't figure how to fix duplicate classes issue with this library.

**Comment by DguillonStark** [comment]
Same issue :/ did you fix it ?

**Comment by alphabikram** [comment]
@DguillonStark I probably changed my way how I installed that fetch blob.
But I can't remember now. 

Try making trials and trials with your process. 
That's only way I went pass through.

**Comment by DguillonStark** [comment]
I unistall it, and follow the manual linking on android, now it's work 👍
