### ISSUE TITLE
NSURLErrorDomain Code -1001 in iOS with require assets in Debug

### ISSUE THREAD

**Issue by jorgecuesta** [TheWidlarzGroup/react-native-video#1484]
### Current behavior
I'm trying to use video with require and works well in Android and in iOS, but in iOS it just work in Release not in Debug

It call`onError`:
![screenshot 2019-02-14 18 14 28](https://user-images.githubusercontent.com/9866992/52818065-79df3b80-3084-11e9-9eb3-a8adb45c9587.png)

The local server say:
```
::1 - - [14/Feb/2019:21:08:27 +0000] "HEAD /assets/src/assets/videos/SF89.mp4?platform=ios&hash=e2aa51e6584d75c6f832f0ff05acb925 HTTP/1.1" 200 - "-" "MyApp/1 CFNetwork/975.0.3 Darwin/18.2.0"
::1 - - [14/Feb/2019:21:08:27 +0000] "GET /assets/src/assets/videos/SF89.mp4?platform=ios&hash=e2aa51e6584d75c6f832f0ff05acb925 HTTP/1.1" 206 16384 "-" "MyApp/1 CFNetwork/975.0.3 Darwin/18.2.0"
```

If I use any kind of external video it works well.

I also check the Info.plist settings and allow access things under http on localhost.
![info plist transport](https://user-images.githubusercontent.com/9866992/52818350-4f41b280-3085-11e9-98e0-b5a91780dff4.png)

After all the assets resolutions go through http to `http://localhost:8081/assets/.../SF89.mp4`

### Reproduction steps

Dependencies:
"react-native": "0.57.8"
"react-native-video": "^4.3.1"

Cocoa Pods:
`pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'`

```javascript
<Video
  source={require('../../assets/videos/SF89.mp4')}
  resizeMode="cover"
  style={{
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  }}
  onLoad={() => {
    console.log('load');
  }}
  onLoadStart={() => {
    console.log('load start');
  }}
  onError={(e) => {
    console.error(e);
  }}
/>
```

### Expected behavior
See the video like I can in Android or iOS in Release

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
https://drive.google.com/file/d/12iV55WYnLzalYfnhjKE6xul_To3kjBav/view?usp=sharing

**Comment by ghost** [comment]
did you ever figure this out?

**Comment by jorgecuesta** [comment]
@pollen-official I really don't remember how I skip this error, but was something with me project and the dependencies. I drop the entire project and start a new one clean with all me dependencies cleaned and didn't get it happening again.
