### ISSUE TITLE
[iOS] Video pauses when notification tray or control center is opened

### ISSUE THREAD

**Issue by manjariParthiban** [TheWidlarzGroup/react-native-video#1489]
### Current behavior
When a locally saved video is playing and the control center or notification tray is opened, video pauses with no event.

### Expected behavior
The video should not pause but continue playing like in android or there should be an event to handle it

### Platform
* iOS

**Comment by ghost** [comment]
> playWhenInactive

>Determine whether the media should continue playing when notifications or the Control Center are in 
>front of the video.

>false (default) - Don't continue playing the media
>true - Continue playing the media
>Platforms: iOS`

**Comment by unknownpwn** [comment]
Did you even read the ticket I posted? It has nothing to do with that
issue.

**Comment by unknownpwn** [comment]
Woops, I'm sorry, I mixed up my responses.

**Comment by harryuses** [comment]
How do I put code into ios?
