### ISSUE TITLE
rotation  not working

### ISSUE THREAD

**Issue by meiqi1992** [TheWidlarzGroup/react-native-video#1490]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

this is my code:
<Video
                        ref={(ref) => { this.videoRef = ref }}
                        source={{ uri:decodeVideourl,}}
                        resizeMode= {resizeMode}
                        rate={1.0}
                        volume={1.0}
                        muted={false}
                        rotation = {90} //not working
                        ignoreSilentSwitch={"ignore"}
                        style={{ width: 200, height: 200}}
                        paused={isPaused}
                        onLoadStart={this._onLoadStart}
                        onBuffer={this._onBuffering}
                        onLoad={this._onLoad}
                        onProgress={this._onProgressChange}
                        onEnd={this._onPlayEnd}
                        onError={this._onPlayError}
                        playInBackground={false}
                        playWhenInactive={false}
                        repeat = {repeat}
                    />
result:  rotation not working

**Comment by emilemoureau** [comment]
Add useTextureView={true}
