### ISSUE TITLE
Multiple video with Swiper component 

### ISSUE THREAD

**Issue by jothikannan** [TheWidlarzGroup/react-native-video#1494]
### Current behavior
Multiple videos within swiper component are not working as expected

### Reproduction steps
1. install react-native-swiper component
2. Add more than one video in swiper component
3. Give reference for each video

### Expected behavior
Whenever I have the video in the View, concern video should play, when we move to the next video it should play, in case the next item is an image, the video should be stopped playing

### Platform
Which player are you experiencing the problem on:
* iOS

Code sample:
You can check my completed work around here

https://snack.expo.io/@jothikannanc/swiper-video

**Comment by DavidCow** [comment]
Please elaborate more on your current behavior section. 

I have a similar problem.
I build my own Swiper component and it shows half of the videos. So sometimes a video would work perfectly fine. Then there is a video where I can only see the thumbnail. And sometimes it is completely black. No error messages. Working on Android

**Comment by baophong09** [comment]
I face same problem

**Comment by matiasgitl** [comment]
Did you find any solution?

**Comment by mattsff** [comment]
Did you find any solution?

**Comment by huyenpham-agilityio** [comment]
I got same issue, did you resolve it ? @jothikannan

**Comment by kishanbharda** [comment]
Same issue here. 
When I load multiple videos on swiper component crash happens on android. However I set `pause={true}` on video so not every video is playing, but still it crashing.
Have anyone find solution ?

**Comment by ferbeab** [comment]
I have a working implementation using https://github.com/Luehang/react-native-swipe-render and a fork from https://github.com/itsnubix/react-native-video-controls
I can share if anyone is interested

**Comment by farshid1** [comment]
@ferbeab yes very interested!

**Comment by usmanuj7** [comment]
@ferbeab I am stuck in the same issue can you please provide me with the solution.

**Comment by Khenisiddharth** [comment]
I have same issue.any one have solution

**Comment by Khenisiddharth** [comment]
> 
> 
> I have a working implementation using https://github.com/Luehang/react-native-swipe-render and a fork from https://github.com/itsnubix/react-native-video-controls
> I can share if anyone is interested

can you please share me your demo

**Comment by ferbeab** [comment]
Sorry to everyone, I didn't read the messages. I will create a demo repository and share it with you tomorrow.

**Comment by Khenisiddharth** [comment]
Thanks

**Comment by ferbeab** [comment]
You can find a minimal working example on this [repo](https://github.com/ferbeab/video-swiper-demo). I have only been able to test it for iOS, so let me know if there are any issues. Happy Sunday!

**Comment by Khenisiddharth** [comment]
@ferbeab didn't work in android. Here is my code. can you please check and let me know what is problem in my code.


import React, { useEffect, useState } from 'react';
import Video from 'react-native-video';
import {
    Dimensions,
    StyleSheet,
    View,
    StatusBar,
} from 'react-native';
import SwipeRender from "react-native-swipe-render";



export default function Fullscreenvideo() {
    return (
        <>
            <StatusBar barStyle="light-content" backgroundColor="black" />
            <View style={{ flex: 1 }}>
            <SwipeRender
                    index={0}
                    loop={true}
                    autoplay={false}
                    loadMinimal={true}
                    loadMinimalSize={2}
                    horizontal={false}
                    data={[
                      { uri: "https://video-aws.vd4v.com/20210726/3/155738404215439638196.mp4" },
                      { uri: "https://video-aws.vd4v.com/vivashow/watermark/20210729/3/155888742085533362767.mp4" },
                      { uri: "https://video-aws.vd4v.com/20210728/3/155851770162529289372.mp4" },
                      { uri: "https://vjs.zencdn.net/v/oceans.mp4" },
                  ]}
                    renderItem={({ item, index }) => (
                        <>
                        <View key={"SwipeRender-slide#" + index} style={{flex: 1, backgroundColor: "#000"}}>
                            <Video
                                source={{ uri: item.uri }}
                                resizeMode="contain"
                                repeat={true}
                                style={styles.videostyle}
                            />
                        </View>
                        </>
                    )}
                />
            </View>
        </>
    )
}
const styles = StyleSheet.create({
    videostyle: {
        zIndex: 0,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
    },
})

**Comment by ferbeab** [comment]
@Khenisiddharth I just pushed an update that fixes Android version. However, I was able to make your code work by fixing some syntax errors. You weren't closing neither of the `<View>` tags. Here is the snippet:
```
import React, {useEffect, useState} from 'react';
import Video from 'react-native-video';
import {Dimensions, StyleSheet, View, StatusBar} from 'react-native';
import SwipeRender from 'react-native-swipe-render';

export default Fullscreenvideo = () => {
  [index, setIndex] = useState(0);
  return (
    <>
      <View style={{flex: 1}}>
        <SwipeRender
          index={0}
          loop={true}
          autoplay={false}
          loadMinimal={true}
          loadMinimalSize={2}
          horizontal={false}
          data={[
            {
              uri: 'https://video-aws.vd4v.com/20210726/3/155738404215439638196.mp4',
            },
            {
              uri: 'https://video-aws.vd4v.com/vivashow/watermark/20210729/3/155888742085533362767.mp4',
            },
            {
              uri: 'https://video-aws.vd4v.com/20210728/3/155851770162529289372.mp4',
            },
            {uri: 'https://vjs.zencdn.net/v/oceans.mp4'},
          ]}
          renderItem={({item, index}) => (
            <>
              <View
                key={'SwipeRender-slide#' + index}
                style={{flex: 1, backgroundColor: '#0'}}>
                <Video
                  source={{uri: item.uri}}
                  resizeMode="contain"
                  repeat={true}
                  style={styles.videostyle}
                />
              </View>
            </>
          )}
        />
      </View>
    </>
  );
};
const styles = StyleSheet.create({
  videostyle: {
    zIndex: 0,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});

```

**Comment by Khenisiddharth** [comment]
Thank's
check and let you know
