### ISSUE TITLE
Is there any way to use .ass subtitles?

### ISSUE THREAD

**Issue by bryanalejandro0** [TheWidlarzGroup/react-native-video#1496]
### Platform
Which player are you experiencing the problem on:
* Android

I have a video page but use .ass subtitles and I'm doing the mobile version so I wanted to know if there is any way to use these subtitles with a library or some other video plugin, thanks for your answer.

**Comment by cobarx** [comment]
It appears there is ASS support in ExoPlayer, however I have not tested it. You should be able to pass in an ASS sub. The ExoPlayer [supported formats guide](https://google.github.io/ExoPlayer/supported-formats.html) says you need to "Use MimeTypes.TEXT_SSA".

For our team, we currently use the libass-wasm Node module hosted inside a WebView to handle ASS.

**Comment by lightninglu10** [comment]
@cobarx could you expand a bit more on this? Do you bundle the libass-wasm node module into your react native code and inject that into the webview? Or do you load a webpage where this module already exists?
