### ISSUE TITLE
Streaming with Google Drive 

### ISSUE THREAD

**Issue by BenzBenzz** [TheWidlarzGroup/react-native-video#1497]
I have a google drive video and I want to stream it with react native. I do not want to download it before and then enable the player. I want a stream it in live directly.
I use this library

I've try this:
```
    <Video source={{
        uri: "https://www.googleapis.com/drive/v3/files/ID?alt=media",
        headers: {
            Authorization: 'Bearer STUFF',
        }
    }} />
```

But I've got this error 
NSURLErrorDomain error -1002 means NSURLErrorUnsupportedURL

**Comment by msaad99** [comment]
React Native Video only supports media URLs (URLs which end in .mp4 etc)

**Comment by escobar5** [comment]
Is there any reason for this, there are many cases where a query string is present, for example a firebase storage file url might be like this: https://firebasestorage.googleapis.com/v0/b/project-XXXXXXX.appspot.com/o/video.mp4?alt=media, the file is a mp4, but the url doesn't end in mp4.

**Comment by escobar5** [comment]
I found out that in my case the problem is when using VideoCaching Pod, if I switch to the react-native-video Pod, then the video is loaded correctly

**Comment by ThePlatinum** [comment]
@escobar5 what do you mean by using the react-native-video pod? I'm using the expoav library and it's not working out for Google Drive links

**Comment by sam-uraii** [comment]
Hello guys!! what is the solution then??? I am facing the same problem.
