### ISSUE TITLE
Unable to build app after instaling react-native-video

### ISSUE THREAD

**Issue by deepak-jha-kgp** [TheWidlarzGroup/react-native-video#1498]
### Current behavior
`> Task :react-native-video:compileDebugJavaWithJavac FAILED
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ExoPlayerView.java:25: error: cannot find symbol
import com.google.android.exoplayer2.ui.SubtitleView;
                                       ^
  symbol:   class SubtitleView
  location: package com.google.android.exoplayer2.ui
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ExoPlayerView.java:34: error: cannot find symbol
    private final SubtitleView subtitleLayout;
                  ^
  symbol:   class SubtitleView
  location: class ExoPlayerView
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ReactExoplayerView.java:67: error: cannot find symbol
import com.google.android.exoplayer2.ui.PlayerControlView;
                                       ^
  symbol:   class PlayerControlView
  location: package com.google.android.exoplayer2.ui
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ReactExoplayerView.java:100: error: cannot find symbol
    private PlayerControlView playerControlView;
            ^
  symbol:   class PlayerControlView
  location: class ReactExoplayerView
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ExoPlayerView.java:74: error: cannot find symbol
        subtitleLayout = new SubtitleView(context);
                             ^
  symbol:   class SubtitleView
  location: class ExoPlayerView
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ReactExoplayerView.java:283: error: cannot find symbol
            playerControlView = new PlayerControlView(getContext());
                                    ^
  symbol:   class PlayerControlView
  location: class ReactExoplayerView
F:\newapp\classcast\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ReactExoplayerView.java:1160: error: cannot find symbol
        } else if (getChildAt(1) instanceof PlayerControlView && exoPlayerView != null) {
                                            ^
  symbol:   class PlayerControlView
  location: class ReactExoplayerView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-video:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

### Reproduction steps
Installed react-native-video and linked it as per guidlines.
These are my dependencies
`"dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.5",
    "react-native-elements": "^1.0.0",
    "react-native-firebase": "^5.2.2",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-modal": "^7.0.2",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-svg": "^9.2.4",
    "react-native-svg-charts": "^5.2.0",
    "react-native-vector-icons": "^6.2.0",
    "react-native-video": "^4.4.0",
    "react-navigation": "^3.2.1"
  },`

### Expected behavior
A normal build

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by morgenhaar** [comment]
I had the same problem
I went to android/app/build.gradle and added 
```
android {
...
  compileOptions {
     sourceCompatibility 1.8
     targetCompatibility 1.8
  }
}
```

**Comment by deepak-jha-kgp** [comment]
Hey, I tried doing this earlier. This solves the problem when I build the app on a colleagues's system, but gives the same error when I try on mine. I'm baffled!  :(

**Comment by cobarx** [comment]
Try unlinking and re-linking with `react-native unlink react-native-video` and `react-native link react-native-video`. This sort of thing happens all the time for me and it's sort of magic to get it working again. Sometimes restarting Android Studio will fix it as well.

**Comment by CHaNGeTe** [comment]
try the previous mentioned approach, and version 4.4.2

**Comment by dhaneshgosai** [comment]
Hello Team,

I too have facing this issue after adding react-native-video plugin.

Can you help us to resolve this issue ?

Error :

`> Task :react-native-video:compileDebugJavaWithJavac
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:278: error: constructor HlsMediaSource in class HlsMediaSource cannot be applied to given types;
                return new HlsMediaSource(uri, mediaDataSourceFactory, mainHandler, null);
                       ^
  required: Uri,HlsDataSourceFactory,HlsExtractorFactory,CompositeSequenceableLoaderFactory,LoadErrorHandlingPolicy,HlsPlaylistTracker,boolean,boolean,Object
  found: Uri,Factory,Handler,<null>
  reason: actual and formal argument lists differ in length
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:740: error: cannot find symbol
            trackSelector.setSelectionOverride(index, groups, null);
                         ^
  symbol:   method setSelectionOverride(int,TrackGroupArray,<null>)
  location: variable trackSelector of type MappingTrackSelector
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:761: error: cannot find symbol
            trackSelector.clearSelectionOverrides(index);
                         ^
  symbol:   method clearSelectionOverrides(int)
  location: variable trackSelector of type MappingTrackSelector
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:766: error: cannot find symbol
            trackSelector.clearSelectionOverrides(trackIndex);
                         ^
  symbol:   method clearSelectionOverrides(int)
  location: variable trackSelector of type MappingTrackSelector
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:770: error: cannot find symbol
        MappingTrackSelector.SelectionOverride override
                            ^
  symbol:   class SelectionOverride
  location: class MappingTrackSelector
/Users/dhaneshgosai/Downloads/Acharya_FINAL_JULY232019/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:771: error: cannot find symbol
                = new MappingTrackSelector.SelectionOverride(
                                          ^
  symbol:   class SelectionOverride
  location: class MappingTrackSelector
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

> Task :react-native-video:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-video:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23m 51s
229 actionable tasks: 229 executed
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html`

Above detail while build failed.

**Comment by CHaNGeTe** [comment]
Have you manually updated exoplayer?
Make sure you are using 2.9.3

The errors you are getting should be deprecation warnings on 2.9.3.

Seems you are trying to use a higher version, maybe you have another library setting it to another version?

In any event, if you don't see any other version being used, try this PR please:
https://github.com/react-native-community/react-native-video/pull/1653
