### ISSUE TITLE
[Android 4.4.4] video not working

### ISSUE THREAD

**Issue by stereodenis** [TheWidlarzGroup/react-native-video#150]
Works on android v5.1.0 and not working on v4.4.4

**Comment by peng051410** [comment]
In my project android never work!

**Comment by peng051410** [comment]
I get an error in logcat, it's E/MediaPlayer﹕ Should have subtitle controller already set.

**Comment by scgough** [comment]
Video works on Android 4.2 and 5 for me - just as a sidenote, check the encoding of the video files. Some devices are fussy. Upload a video to your device on it's own and check it plays correctly.

**Comment by WhatAKitty** [comment]
Not work for me on Android 4.2 and works fine on Android 6 when I use m3u8.

**Comment by WhatAKitty** [comment]
@peng051410 I got it also, but I can play normally.

**Comment by hinet** [comment]
it could not work under Android 5

**Comment by WhatAKitty** [comment]
I change my video format to 'mp4' and it worked on Android.

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.
