### ISSUE TITLE
Error undefined is not an object (evaluating 'RCTVideoInstance.Contants' )

### ISSUE THREAD

**Issue by lehuydev2203** [TheWidlarzGroup/react-native-video#1502]
I have issue when i run , and project warning Error 
![image](https://user-images.githubusercontent.com/41155784/53562916-36f18d80-3b85-11e9-8da6-518b7fc83875.png)

**Comment by MaheshNandam** [comment]
Facing the same issue, switched to 4.3.0 version.

**Comment by Kendysond** [comment]
Hi @lehuyroxyproduction , 

Had the same issue  too. Not sure why it's not mentioned in the readme, but running `react-native link react-native-video` fixed the error for me. 

I hope this helps.

**Comment by tkulpa** [comment]
Hey @lehuyroxyproduction , how you solved that, I have same issue

**Comment by cinder92** [comment]
@tkulpa i have the same issue, have you solved it?

**Comment by ashish-dhiman** [comment]
I am also facing similar issue.

**Comment by mailaustin37** [comment]
@Kendysond it was actually stated that you had to link after installing. You just have to look closely to notice it as different instructions were placed in an accordion for different platforms. 
I was finally able to solve the issue by just changing a line of code. 
This will work even with the latest version. I got it to work with version 4.4.0 so no need to downgrade back to 4.3.0.

After installing with npm install --save react-native-video, then run react-native link react-native-video (**very important step**).
If you try building now, you'll keep getting an error.
The problem seems to stem from the **ExoPlayer library player** which is inserted at default with react native link. We need to change this to the **Android MediaPlayer based player**.
To fix this, open the android/settings.gradle and replace the line of code below:
**include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')**
 with this
**include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')**

building should run to completion and the RCTVideoInstance.Contants error cleared afterwards. I hope this helps someone as the problem took me almost a day to crack

**Comment by maxmatthews** [comment]
Running `pod install` in `cd ios` after `yarn install` and `react-native link` may also help!

**Comment by happypandaa** [comment]
you can try react-native unlink react-native-video before link, and check the RTCVideo in xcode libraries. I fixed that in this way.

**Comment by roycedot** [comment]
Make sure you see libRCTVideo.a in 'Linked Frameworks and Libraries'

**Comment by qingyangCode** [comment]
> Facing the same issue, switched to 4.3.0 version.

I have the same issue. I solve it by one line code.

@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setCurrentActivity(this)
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new ReactVideoPackage())// this code very important
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "ipChannel", null);

        setContentView(mReactRootView);
    }
![image](https://user-images.githubusercontent.com/9857247/59858086-e0ff5a80-93ac-11e9-9440-2c24516c1206.png)

**Comment by saadkhan1706** [comment]
> Hi @lehuyroxyproduction ,
> 
> Had the same issue too. Not sure why it's not mentioned in the readme, but running `react-native link react-native-video` fixed the error for me.
> 
> I hope this helps.

that was the solution to my problem :D kudos
this should be included in the documentation

**Comment by CHaNGeTe** [comment]
It is https://github.com/react-native-community/react-native-video#installation (on both android and ios) Or am I missing something?

**Comment by saadkhan6670** [comment]
@CHaNGeTe  to link the module is not mentioned in the documentation you have to run > react-native link react-native-video also

**Comment by CHaNGeTe** [comment]
Platform links are unfoldable
![image](https://user-images.githubusercontent.com/1237997/60440194-98e60080-9c14-11e9-943f-9f4cdf5267ca.png)

**Comment by saadkhan6670** [comment]
> Platform links are unfoldable
> ![image](https://user-images.githubusercontent.com/1237997/60440194-98e60080-9c14-11e9-943f-9f4cdf5267ca.png)

Thanks man (Y) i completely missed it

**Comment by MwareSolutons** [comment]
for me it works perfectly on IOS but not for TVOS does anybody else have the same issue ?

i have used pods like this

 pod 'react-native-video', :path => '../../node_modules/react-native-video'

**Comment by CHaNGeTe** [comment]
Can you check if opening the project on Xcode, on the Pods subproject, under development pods appears react-native-video ? If not, seems it is not linking properly for tvOS

**Comment by MwareSolutons** [comment]
> Can you check if opening the project on Xcode, on the Pods subproject, under development pods appears react-native-video ? If not, seems it is not linking properly for tvOS

Hi Changete thanks for you reply its does see my screenshot

[Screenshot 2019-07-09 at 12.50.04.pdf](https://github.com/react-native-community/react-native-video/files/3372566/Screenshot.2019-07-09.at.12.50.04.pdf)

[Screenshot 2019-07-09 at 12.51.49.pdf](https://github.com/react-native-community/react-native-video/files/3372573/Screenshot.2019-07-09.at.12.51.49.pdf)

**Comment by MwareSolutons** [comment]
I found out is not adding it to the input and output files of the embed pod frameworks

see screenshot
[Screenshot 2019-07-09 at 13.27.25.pdf](https://github.com/react-native-community/react-native-video/files/3372719/Screenshot.2019-07-09.at.13.27.25.pdf)

**Comment by CHaNGeTe** [comment]
Sometimes it helps to delete the workspace, and make a `pod install` on the folder

**Comment by MwareSolutons** [comment]
tried that to did not work...

**Comment by MwareSolutons** [comment]
ok new information it works on 2.0 and not on 4.4.0 and why is this closed ??

**Comment by MwareSolutons** [comment]
ok i fixed it by removing this:    s.static_framework = true from the podspec not sure why this make it work but problem solved ...

**Comment by JasonCareter** [comment]
> Running `pod install` in `cd ios` after `yarn install` and `react-native link` may also help!

this do helped me, thks

**Comment by siliconavengers** [comment]
on React Native 0.60 or above, let's try these steps:

```
# Add package
yarn add react-native-video

# open ios/Podfile and add the following package

pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'

# Run pod install
pod install
```

And then It will work.

**Comment by lhanc-hx** [comment]
> ok i fixed it by removing this: s.static_framework = true from the podspec not sure why this make it work but problem solved ...

This is the only thing that works for me too. 

Did you stick with this solution? 
Is there a way to do this from the Podfile instead of the podspec?
On what CocoaPods version are you on?

**Comment by CHaNGeTe** [comment]
I don´t know if it helps, but I think there is a typo.
Should :podspec instead of :path

pod 'react-native-video', **:podspec** => '../node_modules/react-native-video/react-native-video.podspec'

**Comment by Kuhne1** [comment]
Hope this helps someone, Manually link on IOS. version 4.4.4
1. Drag the xcode project file RCTVideo.xcodeproj  into your libraries section

2. There are two libRCTVideo.a files
open the folders and drag the libRCTVideo.a file under the Products folder into your link binary with libraries folder. 

If you get a build issue with derived data, make sure that you have  dragged the correct libRCTVideo.a file !!!

**Comment by SavageWilliam** [comment]
@kozak-iz-kh  can you give info on your `react-native` version and version of this package? For 0.60 and above the installation setup quotes linking is not required?

**Comment by SupriyaGo** [comment]
my react-native app version is 0.60 and it's not working, when I am linking the library, the app is getting crashed. after unlinking getting the following error
![Screenshot_1575615422](https://user-images.githubusercontent.com/40319687/70303205-0aaa2200-1825-11ea-87f9-de7cdbf64f1a.png)

**Comment by tuanlv89** [comment]
> Hi @lehuyroxyproduction ,
> 
> Had the same issue too. Not sure why it's not mentioned in the readme, but running `react-native link react-native-video` fixed the error for me.
> 
> I hope this helps.

thank you sir, its worked for me

**Comment by techtunix** [comment]
Leave all and Simply Go Native and Do it Like this!

1). ` expo install expo-av `

2). Your  **App.js** should be look like this.

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Video } from 'expo-av';

export default class App extends React.Component {
  render(){
    return (
      < View style={styles.container} >
        < Text >Open up App.js to start working on your app!< / Text >

        < Video
        source={{ uri: 'https://www.yourdomain.com/uploads/video_file.mp4' }}
        shouldPlay
        useNativeControls 
        style={{ width: "100%", height: "50%" }}
      />

      </ View >
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
}); 

3). Then ` expo start `

That's all!

I hope it will be helpfull for someone who are looking to work with Videos in their ReactNative Apps, at begnining level.

**Comment by LuthfulahiO** [comment]
> Leave all and Simply Go Native and Do it Like this!
> 
> 1). `expo install expo-av`
> 
> 2). Your **App.js** should be look like this.
> 
> import React from 'react';
> import { StyleSheet, Text, View } from 'react-native';
> import { Video } from 'expo-av';
> 
> export default class App extends React.Component {
> render(){
> return (
> < View style={styles.container} >
> < Text >Open up App.js to start working on your app!< / Text >
> 
> ```
>     < Video
>     source={{ uri: 'https://www.yourdomain.com/uploads/video_file.mp4' }}
>     shouldPlay
>     useNativeControls 
>     style={{ width: "100%", height: "50%" }}
>   />
> 
>   </ View >
> );
> ```
> 
> }
> }
> const styles = StyleSheet.create({
> container: {
> flex: 1,
> backgroundColor: '#fff',
> alignItems: 'center',
> justifyContent: 'center',
> },
> });
> 
> 3). Then `expo start`
> 
> That's all!
> 
> I hope it will be helpfull for someone who are looking to work with Videos in their ReactNative Apps, at begnining level.

This works if you are developing with expo.

**Comment by PiotrAleksander** [comment]
Changing:
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`
to
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

in **android/settings.gradle** (-exoplayer was deleted)
resolved the issue for me.
Please refer to: https://github.com/react-native-community/react-native-video#Android-installation

**Comment by Bensigo** [comment]
> > Leave all and Simply Go Native and Do it Like this!
> > 1). `expo install expo-av`
> > 2). Your **App.js** should be look like this.
> > import React from 'react';
> > import { StyleSheet, Text, View } from 'react-native';
> > import { Video } from 'expo-av';
> > export default class App extends React.Component {
> > render(){
> > return (
> > < View style={styles.container} >
> > < Text >Open up App.js to start working on your app!< / Text >
> > ```
> >     < Video
> >     source={{ uri: 'https://www.yourdomain.com/uploads/video_file.mp4' }}
> >     shouldPlay
> >     useNativeControls 
> >     style={{ width: "100%", height: "50%" }}
> >   />
> > 
> >   </ View >
> > );
> > ```
> > 
> > 
> > }
> > }
> > const styles = StyleSheet.create({
> > container: {
> > flex: 1,
> > backgroundColor: '#fff',
> > alignItems: 'center',
> > justifyContent: 'center',
> > },
> > });
> > 3). Then `expo start`
> > That's all!
> > I hope it will be helpfull for someone who are looking to work with Videos in their ReactNative Apps, at begnining level.
> 
> This works if you are developing with expo.

react-native-video don't work with Expo .

**Comment by ghost** [comment]
I Just needed to do a Pod Install. 
@Kendysond's answer lead me to realize that I didn't have package linking done. 
Current version of React Native now does auto Linking. React Version: v0.63.2

**Comment by jiabinxiong** [comment]
ios      
我在真机也有这个问题   把APP 删除  再通过 XCode重新安装

模拟机第一次也有问题    
    重新启动     


希望对大家有帮助
