### ISSUE TITLE
How to get playable duration outside of onProgress

### ISSUE THREAD

**Issue by msaad99** [TheWidlarzGroup/react-native-video#1504]
How can I get access to playable duration (which is the buffer time) outside of onProgress? I need to be able to show how much a video has buffered even if its paused but I can only get playable duration in onProgress and onProgress is not triggered when the video is paused.

**Comment by cobarx** [comment]
We don't currently have that capability. I think the best approach would be to see if we can generate buffering events at regular intervals while paused that contain that info. I don't have the time to tackle that at the moment, so you will have to look into it yourself or see if another contributor can help.

**Comment by msaad99** [comment]
Hey, yeah I've come up with a similar solution and have got it working on my end. Thanks.

**Comment by michaelfreund** [comment]
> Hey, yeah I've come up with a similar solution and have got it working on my end. Thanks.

@msaad99 would you mind sharing your solution here?

**Comment by FahadRS** [comment]
@msaad99  I am also facing this issue, can you please share how did you implemented that

**Comment by reactdevrocks** [comment]
@msaad99 @FahadRS would you mind to share something about the above as i am also facing the same issue.
