### ISSUE TITLE
play after aplication close

### ISSUE THREAD

**Issue by arbabi2010** [TheWidlarzGroup/react-native-video#1508]
### Current behavior
I set `playInBackground : true` but when the app is closed or press back, the audio be stoped .
 I want the music to continue to be played in background on menu. 

### Platform
* iOS 
* Android ExoPlayer
* Android MediaPlayer

**Comment by googl3r** [comment]
in ios you should you should Enable Background Audio in your xcode project and set the ignoreSilentSwitch prop to "ignore" as it is suggested in the documentation

[playInBackground](https://github.com/react-native-community/react-native-video#playinbackground)

**Comment by arbabi2010** [comment]
@googl3r  Thanks. and what about android? I have this problem in android.

**Comment by SwiftyWang** [comment]
Have the same question. I am using this lib to play music but when the component unmount(such as press **back button**) then the music will stop.
If press **home button** then music is playing in the background very well.
