### ISSUE TITLE
External subtitle support for HLS video Streaming on ios (.m3u8 format)

### ISSUE THREAD

**Issue by mostain-unified** [TheWidlarzGroup/react-native-video#1511]
Currently I am unable to show the external subtiles for HLS Streaming (.m3u8) for ios. It properly working on android. Just I need a confirmation is it possible to show  subtitles by external textTracks for HLS video(.m3u8) on iOs ??? If possible then how, whats the probs need to pass?? Waiting for your valuable response.

**Comment by alanlanglois** [comment]
You'll find in the doc: 
> On iOS, sidecar text tracks are only supported for individual files, not HLS playlists. For HLS, you should include the text tracks as part of the playlist.

Which format do you use for iOS subtitle?
iOS only support `.vtt`. 

I know it might be not enough to help :)

**Comment by mostain-unified** [comment]
textTracks={[
                      {
                       title: "English CC",
                       language: "en",
                       type: TextTrackType.VTT, // "text/vtt" 
                       uri:"http://example.com/upload/subtitles/15268160828768448935b015d52d28da.vtt"
                         }
                        ]}
                        selectedTextTrack={{
                            type: "language",
                            value: "en"  
                          }}
                        source={{uri:'https://example/upload/screener/124/152149235611207236405ab0218496e27_fs.m3u8'}}

I am using above props but video stop playing. Its only work when I use  .mp4 format of video source. But I need subtiles in .m3u8 format externally.

**Comment by CHaNGeTe** [comment]
Currently, as stated on the doc referenced by @alanlanglois, we are not supporting sidecar textracks for HLS (m3u8)

I will leave the issue opened as I think I got an approach to make it work in the future.

**Comment by yansfil** [comment]
any other improvements?

**Comment by ferrannp** [comment]
@CHaNGeTe ?

**Comment by paulomota** [comment]
I'm facing the same with my app, it was a hard work tryng to fix videos with subtitles on ios. For now I'll try to reproduce only mp4 videos when my app running on ios phones.

**Comment by CarlosPlasencia** [comment]
@CHaNGeTe, are you find solution to use sidecar text tracks?

**Comment by nriccar** [comment]
Any news?

**Comment by iSued** [comment]
Does this mean that sidecar subtitles are working for you guys when using android?
@nriccar

**Comment by Salar-g** [comment]
@CHaNGeTe Will there be support for ios sidecar text tracks in the near future for HLS videos? or Is it already added?

**Comment by nriccar** [comment]
Im currently developing an open library to add subtitles without the need of using them inside the react-native-video. Will let you know!

**Comment by Salar-g** [comment]
@nriccar Thanks for doing this. It's gonna help us a lot. Do you have any timelines for releasing this library by any chance? I can also help out get it released faster?

**Comment by sannjayy** [comment]
> Playing external subtitles with m3u8 link of video #2590

yes!

**Comment by nriccar** [comment]
@Salar-g I have done a little project that should help https://github.com/nriccar/react-native-subtitles

Its an early stage of the implementation. Contribution is welcome

**Comment by sannjayy** [comment]
> @Salar-g I have done a little project that should help https://github.com/nriccar/react-native-subtitles
> 
> Its an early stage of the implementation. Contribution is welcome

how can we use it? please tell us

**Comment by nriccar** [comment]
Yes of course! Try it out.. just consider is a first version! You can contribute with PRs or issues and Ill help you.

**Comment by sannjayy** [comment]
> Yes of course! Try it out.. just consider is a first version! You can contribute with PRs or issues and Ill help you.

Where should I place this?
```
<Subtitles
    {...{ currentTime, hasSeeked }}
    selectedsubtitle={{ 
      file:
        'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
    }} 
/>
```

**Comment by nriccar** [comment]
As a sibling of the video component. Feel free to create issues on the repo. I will improve documentation as I maintain it

**Comment by sannjayy** [comment]
> As a sibling of the video component. Feel free to create issues on the repo. I will improve documentation as I maintain it

Can I get your facebook, instagram id? So we can discuss further?

**Comment by nriccar** [comment]
It would be better if it’s using the repo issues so that it is documented within the repo!

**Comment by srihitawork** [comment]
> Currently, as stated on the doc referenced by @alanlanglois, we are not supporting sidecar textracks for HLS (m3u8)
> 
> I will leave the issue opened as I think I got an approach to make it work in the future.

Please will you share the approch

**Comment by justintoth** [comment]
Still seems to be an issue in 2023, Android CC works fine on m3u8 videos but iOS CC doesn't work.

**Comment by himanshuttn** [comment]
@alanlanglois Are we planning to have this support anytime soon?

**Comment by anhquan291** [comment]
Hi @nriccar thanks for your work. 
However, I noticed that the subtitles don’t really match the video. Do you have any suggestions? Thank you
