### ISSUE TITLE
Play next video when video is fullscreen

### ISSUE THREAD

**Issue by vanhungoz** [TheWidlarzGroup/react-native-video#1512]
### Current behavior
when videoComponent is in fullscreen mode.
onEnd is called, i use setState to play next video but it display black screen, only have audio.

### Expected behavior
show next video correctly 
### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by vanhungoz** [comment]
if i dismiss fullscreen before setState next video, it works correctly

**Comment by dylancom** [comment]
I'm having the same issue, the screen stays black when I update the video. (only audio)
@vanhungoz Did you found a way to stay in fullscreen mode without dismissing?

**Comment by vanhungoz** [comment]
@dylancompanjen , no, i did not :(
