### ISSUE TITLE
How to Enable Picture In Picture IOS

### ISSUE THREAD

**Issue by kadircanerergun** [TheWidlarzGroup/react-native-video#1516]
### Current behavior
There is a scrollview and I add pictureInPicture={true} to Video component but video is not playing at the corner on page scroll. Is there any implementation steps to figure this feaature ?

 ```
<Video
                    source={{uri:this.state.videoUrl}}   // Can be a URL or a local file.
                    ref={(ref) => {
                        this.playerRef = ref;
                    }}
                    fullscreen={true}
                    style={styles.videoPlayer}
                    controls={true}
                    fullscreenAutorotate={true}
                    paused={true}
                    pictureInPicture={true}
                    onPictureInPictureStatusChanged={() => {
                        console.log("PIP CHANGED");
                    }}
                />
```

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by rogerkerse** [comment]
I think it is global system wide picture in picture. I tried setting picture in picture true as well, but nothing happens.

**Comment by Spoutnik97** [comment]
Picture in Picture is supported on iOS from iOS 14: https://www.apple.com/ios/ios-14/features/
