### ISSUE TITLE
Music is paused when Video is playing

### ISSUE THREAD

**Issue by toddw** [TheWidlarzGroup/react-native-video#152]
I'm using the <Video> component as a background video for one of my screens, much like the referenced login screen. I set `muted` to `true` but when I have music playing, when you open the app, the music is paused. I can see how this is probably expected behavior, most of the time, but when we are using the video in the background like the login screen, it would be nice if the music could keep playing.

Any ideas how this can be worked around?

**Comment by toddw** [comment]
Solved: http://stackoverflow.com/a/23464916
Add this to your AppDelegate `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];`

**Comment by brentvatne** [comment]
Nice one @toddw :) Could you add that to the README?

**Comment by proProbe** [comment]
This solves the problem on `ios`. How would one solve this for android?

**Comment by lpetkovic** [comment]
This workaround alone didn't quite work for me.
Also, I figured that un-pausing music pauses the video, so, in the end, this solution, combined with initially setting video to paused and un-pausing it few milliseconds later, worked.

**Comment by danielreuterwall** [comment]
This is great for a background video. But what if you want to have a background video in one part of your app and a regular video playing elsewhere. If we set it in AppDelegate, it's a global setting for the whole app right? Could this be part of the props for the video component so we can control it a bit more? What do you think @brentvatne?

**Comment by dlombardi** [comment]
+1 for the above ^

**Comment by tomexa** [comment]
Would love to know how to do it for Android!

**Comment by jonasb** [comment]
@tomexa If you're using ExoPlayer on Android: `disableFocus={true}`, see [here](https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/README.md#exoplayer-only-props).

**Comment by caseyt** [comment]
Setting disableFocus={true} does not work on Android. The requestAudioFocus() method is called when the ReactExoplayerView is created with the initializePlayer() method, and the disableFocus prop is not set until after the view is created. disableFocus and isPaused will always be set to their default values when the first initializePlayer() method is called.

**Comment by n1ru4l** [comment]
@caseyt Are you working on a pull request to address this issue?

**Comment by Rpaixao** [comment]
+1

**Comment by n1ru4l** [comment]
```diff
patch-package
--- a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -330,13 +330,13 @@ class ReactExoplayerView extends FrameLayout implements
     }
 
     private boolean requestAudioFocus() {
-        if (disableFocus) {
-            return true;
-        }
-        int result = audioManager.requestAudioFocus(this,
-                AudioManager.STREAM_MUSIC,
-                AudioManager.AUDIOFOCUS_GAIN);
-        return result == AudioManager.AUDIOFOCUS_REQUEST_GRANTED;
+        // if (disableFocus) {
+        return true;
+        // }
+        // int result = audioManager.requestAudioFocus(this,
+        //         AudioManager.STREAM_MUSIC,
+        //         AudioManager.AUDIOFOCUS_GAIN);
+        // return result == AudioManager.AUDIOFOCUS_REQUEST_GRANTED;
     }
 
     private void setPlayWhenReady(boolean playWhenReady) {
```

At the moment I am using this patch with patch-package.

**Comment by caseyt** [comment]
I believe the fix for this is just removing `setPlayWhenReady(!isPaused);` from `ReactExoplayerView.java` line 237.

**Comment by Natteke** [comment]
i dont know why, but IOS solution works only when production: false O_O

**Comment by jamesshaw49** [comment]
> Any ideas on this? My main app Scene is using a video as a background and this is a deal breaker.
> 
> This should be reopened.

Agreed.
