### ISSUE TITLE
IOS :'Video' has no propType for native prop

### ISSUE THREAD

**Issue by SreevatsaAcharya** [TheWidlarzGroup/react-native-video#1522]
### Current behavior
the library works fine on android after some minor changes but on IOS it shows this error
### Reproduction steps
1. npm install react-native-video
2. react-native link react-native-video
3. react-native run-ios
![Screenshot 2019-03-14 at 1 38 49 PM](https://user-images.githubusercontent.com/26269254/54341120-10405600-465f-11e9-8801-e1902478e9ae.png)

**have tried multiple times reinstalling node_modules, or restarting the packager**

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by uditchandhoke1912** [comment]
Hi, are you able to resolve this issue? I am also facing the same.

**Comment by SreevatsaAcharya** [comment]
@uditchandhoke1912 , No i am still stuck, tried restarting the packager, changed the package versions but no luck, let me know if you find any solution.

**Comment by uditchandhoke1912** [comment]
@SreevatsaAcharya  which react-native version you are using?

**Comment by keenubee** [comment]
I'm also facing this issue with `RN 0.55.4` / `"react-native-video": "^4.4.0"`

**Comment by SreevatsaAcharya** [comment]
@uditchandhoke1912  Rn 0.55.4

**Comment by uditchandhoke1912** [comment]
@SreevatsaAcharya  @keenubee  "react-native-video": "^4.4.0" works with RN 0.57 or higher.
Use react-native-video 3.x to make it work correctly. This worked for me, it should work for you guys as well. Thanks

**Comment by RohitRajpal** [comment]
Use react-native-video 3.x 
It didn't worked

**Comment by CHaNGeTe** [comment]
Seems, as the message states, that your code is out of sync.
After installing/downgrading react-native-video to 3.x, you need to pod install / update.

A way to check it is: Open your xcode workspace, open Pods, open react-native-video and search for `restoreUserInterfaceForPIPStopCompletionHandler`on `RCTVideoManager.m`

That event was not even present on 3.x versions
