### ISSUE TITLE
Audio only HLS file won't play

### ISSUE THREAD

**Issue by airlaser** [TheWidlarzGroup/react-native-video#1523]
### Current behavior
`https://d9mv1cgynqqzh.cloudfront.net/7e1aae08-503c-4a9e-9bd0-8e59e0ddf5eb-master-high.m3u8`

Using this as the source uri will not load. It plays fine in any other player I use. This is supposed to be an audio only HLS stream. 

### Reproduction steps
Put that file as the uri in source. 

### Expected behavior
I want it to play the file. 

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
See above

**Comment by airlaser** [comment]
To clarify - this is on all audio-only HLS files I try, not just this example.

**Comment by mtalhagaoglu** [comment]
did you solve that problem? i am facing same issue on android (i couldn't try on ios but probably won't work)

**Comment by perminder-klair** [comment]
exactly same issue I have, audio only stream does not works

**Comment by perminder-klair** [comment]
turns out I was using HTTP instead of HTTPS, it was not related to android 10
