### ISSUE TITLE
ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath

### ISSUE THREAD

**Issue by Adetiwa** [TheWidlarzGroup/react-native-video#1524]
### Current behavior
Describe what happens when you encounter this issue.

Hello. I am unable to build or run the project on Android.

I get this error on Android Studio
```

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Show Details
Affected Modules: react-native-video


ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Show Details
Affected Modules: react-native-video


ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
Show Details
Affected Modules: react-native-video


ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.14.0.
Show Details
Affected Modules: react-native-video
```

**Comment by Adetiwa** [comment]
Nevermind. Seen the issue and fixed

**Comment by kashsbd** [comment]
Hello @Adetiwa , how did you overcome this issue ?

**Comment by Adetiwa** [comment]
Hi @B4UGUYS, I simply changed the react native video dependency to this, and the project built successfully.

```
dependencies {
    compileOnly 'com.facebook.react:react-native:+'
    implementation 'com.google.android.exoplayer:exoplayer:2.7.3'

    implementation('com.google.android.exoplayer:extension-okhttp:2.9.3') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
}
```

**Comment by kashsbd** [comment]
Thanks dude !

**Comment by leethree** [comment]
I'm experiencing this issue after upgrading to RN 0.59. @Adetiwa 's solution is just a workaround. we need a proper fix from the library.

**Comment by arminsal1** [comment]
I'm also getting this error

**Comment by panda8z** [comment]
I'm experiencing this issue after upgrading to RN 0.59.1, and I resolved by set  all of the third`s build gradle to below:

```
android {
  compileSdkVersion 28
  buildToolsVersion "28.0.3"
  defaultConfig {
    minSdkVersion 16
    targetSdkVersion 28
    versionCode 1
    versionName "1.0"
    ndk {
      abiFilters "armeabi-v7a", "x86"
    }
  }
}

```
**the most importent  things is these three：**
- compileSdkVersion   
- buildToolsVersion 
- targetSdkVersion

All  of the  third party Libraries  should be  Api28
Like this：

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 27)
    buildToolsVersion safeExtGet('buildToolsVersion', '27.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 27)
        versionCode 1
        versionName "1.0"
    }
}

```
and  define  in  Project`s  build.gralde  like below:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
 
}

```
![image](https://user-images.githubusercontent.com/24646937/55213259-b7131d80-522d-11e9-896f-0c1bc1c294de.png)

**Comment by ahmaddehnavi** [comment]
> Hi @B4UGUYS, I simply changed the react native video dependency to this, and the project built successfully.
> 
> ```
> dependencies {
>     compileOnly 'com.facebook.react:react-native:+'
>     implementation 'com.google.android.exoplayer:exoplayer:2.7.3'
> 
>     implementation('com.google.android.exoplayer:extension-okhttp:2.9.3') {
>         exclude group: 'com.squareup.okhttp3', module: 'okhttp'
>     }
>     implementation 'com.squareup.okhttp3:okhttp:3.12.1'
> }
> ```
 // without change library code

 ```
 implementation (project(':react-native-video')){
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.google.android.exoplayer', module: 'exoplayer'
 }
  implementation('com.google.android.exoplayer:exoplayer:2.7.3') {
        exclude group: 'com.android.support'
  }

```

**Comment by jamesmcn1** [comment]
Not sure if this will help, but whilst upgrading to use compileSdkVersion 28, i had upgraded my classpath to use:
```
classpath 'com.android.tools.build:gradle:3.3.0-alpha12'
```

Switching back to this solved the problem:
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
    }

**Comment by 404-html** [comment]
Problem is gone for me after updating `react-native-video` package to recent version which is `4.4.2`.

**Comment by CHaNGeTe** [comment]
Try 4.4.2, if problem persists, I will reopen the issue
