### ISSUE TITLE
Video not working only in iphone xs.

### ISSUE THREAD

**Issue by ZeroCool00** [TheWidlarzGroup/react-native-video#1526]
### Current behavior
Video showing only blank screen on iphone xs. (other device working fine)
### Platform
Which player are you experiencing the problem on:
* iOS

### Version

```
"react-native-video": "^4.4.0",
 "react-native": "^0.58.6",
"react": "16.6.3",
```

**Comment by Saad9624** [comment]
how are you playing videos in rest of the iphone devices in react native?
