### ISSUE TITLE
App freezes if source prop changes often

### ISSUE THREAD

**Issue by gazedash** [TheWidlarzGroup/react-native-video#1528]
### Current behavior
Describe what happens when you encounter this issue.
Whole app freezes

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

1. Make a list of tracks
2. User presses next, next, next... until the app freezes

### Expected behavior
Describe what you wanted to happen

The app doesn't freeze

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by paddy57** [comment]
Did you find any solution ?

**Comment by gazedash** [comment]
@paddy57 you can throttle / debounce the redux action or handler (for example) which you use to set the source. But it is not the best solution, it's just a hack

**Comment by paddy57** [comment]
> @paddy57 you can throttle / debounce the redux action or handler (for example) which you use to set the source. But it is not the best solution, it's just a hack

Thank you for reply, i'm not using redux though, can you tell me any alternative.
