### ISSUE TITLE
NSURLErrorDomain Code -1001 with a redirected url

### ISSUE THREAD

**Issue by gazedash** [TheWidlarzGroup/react-native-video#1532]
### Current behavior
Describe what happens when you encounter this issue.
onError callback is being called with NSURLErrorDomain and code -1001

### Reproduction steps

1. Set source to be { uri: "https://rss.art19.com/episodes/75bbbfff-93cb-46f4-951c-4ab2161e441f.mp3" }
2. Wait for an onError callback to be called

(The url is redirected to https://content.production.cdn.art19.com/episodes/75bbbfff-93cb-46f4-951c-4ab2161e441f/9c06c65271e2d22e4f83a428579e51821e7bf28a99d656b3d28978f30f14b302c9b88c41c9104df490f16834c3253aeb9e367973f3918fbcd247ba51745862a1/Le_Canon_Sur_La_Tempe_Chap_1.mp3
And if paste the direct url, it works fine)

### Expected behavior
Describe what you wanted to happen
Expect that this file will be played without an error.

### Platform
Which player are you experiencing the problem on:
* iOS

Is there a way to follow redirects and overcome this issue?

**Comment by a-warner** [comment]
I'm experiencing the same issue. I'm currently working around it via a hack where I try to follow the redirect manually and use the resolved URL, but would love to know what's going on here

**Comment by gazedash** [comment]
@a-warner Yeah, I did the same, essentially I pass an onError callback and inside that callback I do a XMLHttpRequest, and if I see that url changed, I set a new url for react-native-video. But interestingly enough, some redirects do work with react-native-video without workarounds...

**Comment by a-warner** [comment]
@gazedash yes I have also noticed that some redirects work! E.g. I'm developing using [Rails's activestorage](https://edgeguides.rubyonrails.org/active_storage_overview.html) to host files, and Rails uses a one-hop 302 redirect strategy for all stored file asset URLs. The idea here is that where files are stored is transparent to the clients of the application, and might switch out from under you etc, so there is _always_ a one-hop 302 redirect.

In "local" development mode, where files are stored on disk, the redirects work fine with `react-native-video`, but using the amazon S3 backend breaks for some reason. As far as I can tell the initial asset URL and the redirect are entirely the same request/response/headers-wise, except that in local mode the redirect goes to the same host and with Amazon of course the 302 goes to a different host.

I haven't had time to game this out but my current suspicion is that there's a problem with 302s that change the hostname 🤷‍♂️

**Comment by s1rd4v3** [comment]
This seems to still be an issue. Did you found a solution to that?
