### ISSUE TITLE
domain = AVFoundationErrorDomain , code =  -11828

### ISSUE THREAD

**Issue by alphabikram** [TheWidlarzGroup/react-native-video#1536]
I am using the streaming url from CloudFront.

Sample url:
https://d14nt81hc5bide.cloudfront.net/qyYj1PcUkYg2ALDfzAdhZAmb

On android , it is working fine but in iOS it says:
domain = AVFoundationErrorDomain , code =  -11828

From apple doc the error code 11828 is AVErrorFileFormatNotRecognized.
The media could not be opened because it is not in a recognized format.

Can someone suggest how to fix this error ?

**Comment by ss876079056** [comment]
hello, how to fix this error ?

**Comment by ss876079056** [comment]
I have a same error

**Comment by alphabikram** [comment]
@ss876079056  i got the same one ... only solution i find is to modify my url to have .mp3 extension... but I am unable to do that till now...
I am pending ..

**Comment by alphabikram** [comment]
I have tried with several urls but I am not able to fix  this error. 

:(

**Comment by pjreact** [comment]
I'm also facing the same issue.

**Comment by alphabikram** [comment]
@pjreact  only solution is to make the url to have .mp3 extension.... by any means :) otherwise there is no solution that I could reach to

**Comment by chgsilva** [comment]
same here, any luck on this?

**Comment by CHaNGeTe** [comment]
Make sure you return the correct `Content-Type` header from cloudfront

**Comment by amerllica** [comment]
@CHaNGeTe, your solution doesn't work. I run a local server to serve **MKV** film format type, and got the same error as this current issue. then I add the `video/x-matroska` to the mimeType of apache. but this solution just changes the error not to solve it.

**Comment by skourt** [comment]
Had a similar issue where certain videos gave me the "media format not supported" error on iOS. For me the issue was caused by Apple devices not recognizing the video format at all (issue also occurred on Mac after downloading the video), so I had to manually set the type to 'mp4'. The way I did this was by caching the video and appending the extension on error using RNFetchBlob.

```
useEffect(() => {
    if (error) RNFetchBlob.config({ fileCache: true, appendExt: 'mp4' }).fetch('GET', source)
    .then(result => setNewPath(result.path()))
}, [error])
```

Then with the video...

```
<Video 
    source={{ uri: newPath.length > 0 ? newPath : source }}
    onError={() => setError(true)}
    ...
/>
```

Hopefully this helps!
