### ISSUE TITLE
When use "textTracks" and "paused", player will get stuck after 2 videos

### ISSUE THREAD

**Issue by gsunsnackv** [TheWidlarzGroup/react-native-video#1538]
### Current behavior
Play videos that has `textTracks` and also `paused` is binded to state in order to use custom controls.
Video player completely stuck after 2 videos. Cannot play at all.
If no textTracks or no paused, you can play videos forever

### Reproduction steps
1. `git clone https://github.com/gsunsnackv/react-native-player-stuck`
2. `yarn`
3. Open a Android emulator (with Android 9)
4. `react-native run-android`
5. Click the watch button and watch the video
6. Verify the pause button works
7. Go back
8. Repeat 5 to 7 and you will get stuck in 2 or 3 videos

9. (Below are optional) Remove line 159
```
paused={this.state.paused}
```
10. Reload and repeat 5 to 7. Things will work fine

11. Put back line 159

12. Remove line 150 to 158
```
textTracks={[
                {
                  title: 'English CC',
                  language: 'en',
                  type: TextTrackType.VTT,
                  uri: captions[index],
                },
              ]}
              selectedTextTrack={{type: 'title', value: 'English CC'}}
```
13. Reload and repeat 5 to 7. Things will work fine

### Expected behavior
Do not stuck

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by gsunsnackv** [comment]
Hello. Any update on this issue?

**Comment by sunshineo** [comment]
Can someone have a look for us?

I just added a $10 reward for this issue. The total reward now is $10.  Join me to add more reward to get this issue fixed faster. You can do it here: https://www.issuereward.com/issue/Op6ilwG9jP
I suggest admin of this repo install the Issue Reward bot from https://github.com/apps/issue-reward-beta, so the bot can comment automatically without the need to copy paste.

**Comment by gsunsnackv** [comment]
Could someone have a look at this? It's been a while

**Comment by CHaNGeTe** [comment]
I think this is the route problem:
https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L220

Exoplayer instance is not being released.
@cobarx @n1ru4l @jenshandersson @ashnfb 
what do you think?
I know it is here in order to keep playing audio when on background, but seems it is retaining some resources that make successive plays to fail


Edit: seems it is not related, as release is being fired by `onDropViewInstance`

**Comment by CHaNGeTe** [comment]
@gsunsnackv 
Can you test the branch from this PR?
https://github.com/react-native-community/react-native-video/pull/1655

I have been testing it on your example project, and seems now is not producing the bug.

**Comment by Balasnest** [comment]
#

**Comment by Balasnest** [comment]
@CHaNGeTe will look into it #1655 and let you know.

**Comment by CHaNGeTe** [comment]
thank you @Balasnest !

**Comment by gsunsnackv** [comment]
@CHaNGeTe I confirm that particular pull request fix this problem. https://github.com/gsunsnackv/react-native-player-stuck/tree/handle-props-racing-conditions-on-expplayer

I wonder if this will solve the black screen problem in general. Fingers crossed

**Comment by CHaNGeTe** [comment]
Thank you so much @gsunsnackv .
Please come back with feedback about the other issues.

**Comment by Balasnest** [comment]
@CHaNGeTe I have checked from #1655 this branch and its working now.

**Comment by CHaNGeTe** [comment]
Released to 4.4.4

**Comment by cms24us** [comment]
i just install release 4.4.4 and have the same issue. after three videos on android, i got a black screen. on ios works fine. any news on this? i see is closed

**Comment by CHaNGeTe** [comment]
@cms24us it has to do with textTracks and paused? if not use the other 2 issues
https://github.com/react-native-community/react-native-video/issues/1318
https://github.com/react-native-community/react-native-video/issues/1547

Can be related to a bad update to 4.4.4? As @Balasnest and @gsunsnackv reported it to be solved. (same for me when local testing)

**Comment by cms24us** [comment]
@CHaNGeTe i use paused property. that why i whrite here. my bad.
