### ISSUE TITLE
Can't play non .mp4 videos using URL

### ISSUE THREAD

**Issue by promerob** [TheWidlarzGroup/react-native-video#154]
I found this test video, [an awesome funny cat video](http://falcon479.startdedicated.com/files/round_boxes.mp4), that contains the file extension at the end of the URL and it works fine. If the URL doesn't contain a file extension, e.g. a YouTube, Flickr, or Vimeo video, it doesn't work. (And no local files, as other have pointed out)

Am I doing something wrong? I didn't read any limitations on the documentation

**Comment by isair** [comment]
The URL you need to provide is a video file URL. The YouTube and other provider URLs you are trying don't work as they don't point to video files, they point to web pages. You have to parse the web page and get the URL to the video file being shown on that page or find a library that provides this functionality.

**Comment by nautical** [comment]
if you curl the above link it actually gives the video stream not html and works fine for me . But for youtube and other as mentioned requires further parsing . As for youtube you can use youtube-dl and get link of the stream .

**Comment by nautical** [comment]
For youtube you can try using youtube-dl and get stream link , similar for other services .

**Comment by tomprogers** [comment]
Re: the original topic, we have found that Android will not play `.mov` files natively, but both iOS and Android _will_ play `.mp4` files. This means we've had to transcode video that's being recorded on iOS devices (which comes out in `.mov` format, at least by default).

**Comment by Antonhansel** [comment]
Hi,

I'm giving the player a valid youtube stream url retrieved using https://github.com/fent/node-ytdl-core as suggested.
Example: 

`https://r3---sn-a5mekn7y.googlevideo.com/videoplayback?lmt=1453664102865380&dur=9158.251&key=cms1&mime=video%2Fmp4&sparams=dur,expire,gcr,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&expire=1463786703&fexp=9406993%2C9410705%2C9416126%2C9416891%2C9422596%2C9426963%2C9428398%2C9429693%2C9429695%2C9431012%2C9432368%2C9433096%2C9433408%2C9433946%2C9433960%2C9434495%2C9434810%2C9435278%2C9435578%2C9435687%2C9435876%2C9436634%2C9436835%2C9436918%2C9436973%2C9437158&id=o-AOIXwVrqi9bA_FxTln9NCgUtaII_JGnIjJhJi60NteNW&source=youtube&ip=2606:6000:ca89:e700:c062:915e:4750:7815&gcr=us&pl=32&ipbits=0&upn=RtGQBvJboT0&sver=3&requiressl=yes&itag=22&ratebypass=yes&signature=02A82C3F72B5286A8AECA221784EB44F9F098325.68ED7D429BDA667439000BA6ACA0EA49A023EF6A&redirect_counter=1&req_id=1f66747739bea3ee&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-a5mekn7y&ms=au&mt=1463764877&mv=m&nh=IgpwcjA0LmxheDAyKgkxMjcuMC4wLjE`

The player crashes with throwing the following error:

`Exception thrown while executing UI block: *** -[NSURL initFileURLWithPath:]: nil string parameter`

Any idea where this could come from?

**Comment by SaraChicaD** [comment]
@isair how did you figure that out? is that still the case? thanks in advance!

**Comment by zchwyng** [comment]
Closing this since it's outdated.
