### ISSUE TITLE
Crash on XCode builded(ready for upload to app store) - iOS

### ISSUE THREAD

**Issue by kyhnlbyrk** [TheWidlarzGroup/react-native-video#1540]
Hi,

Error : load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://gubretas-demo.pop-soft.com/static/videos/toprak.mp4, NSErrorFailingURLKey=https://gubretas-demo.pop-soft.com/static/videos/toprak.mp4, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <E7AB796A-47B2-4883-958B-0D9E06EEADFB>.<2>"

If I started the project with "react-native run-ios" there is no problem, everything is working perfect.. However, If I start the project from the Xcode (ready for archiving) I get the following error, and app freezes(crashes). How can I fix this problem

I am getting the video from the URL that I wrote here.

### Expected behavior
I wanted to work like it works in "react-native run-ios"
### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
https://gubretas-demo.pop-soft.com/static/videos/toprak.mp4

**Comment by kyhnlbyrk** [comment]
Guys this is urgent please help !

**Comment by rogerkerse** [comment]
I get the same error when I switch wifis while video is playing and it is offline for few seconds. After few of those errors my app crashes

**Comment by anas7asiadev** [comment]
+1

**Comment by hexatex** [comment]
+1

**Comment by CHaNGeTe** [comment]
Sorry for the late reply.
@kyhnlbyrk @rogerkerse did you found a workaround for this?

Can you illustrate more how to reproduce it?

> I get the same error when I switch wifis while video is playing and it is offline for few seconds. After few of those errors my app crashes

@kyhnlbyrk this is also your scenario? ^

**Comment by CHaNGeTe** [comment]
I see error code is 999
```
NSURLErrorCancelled = -999,
```
Are you mutating somehow the source object?
