### ISSUE TITLE
Add support for react-native-web

### ISSUE THREAD

**Issue by anthonycmain** [TheWidlarzGroup/react-native-video#1542]
### Current behavior
It would be great if you were able to add a proxy around the module if react-native-web is being used.

I've seen you're component used in a number of projects, particularly react-native-gifted-chat and it would be awesome if that was web enabled.

There error that is raised is "Can't resolve 'AssetRegistry' in 'react-native/Libraries/Image'"

### Reproduction steps
Compile a react-native-project with react-native-video as a dependency

### Expected behavior
Fall back to a web compatible video component

### Platform
react-native-web

### Screenshot
<img width="489" alt="Screenshot 2019-04-03 at 14 43 20" src="https://user-images.githubusercontent.com/950131/55485730-ead1b700-5622-11e9-8f6a-23c284137a44.png">

**Comment by zhigang1992** [comment]
You can Use https://github.com/QuantumBA/react-native-web-video and create a alias

**Comment by MwareSolutons** [comment]
Where you able to fix thiss ? I am also interested in serving video on react-native-web

**Comment by itsezc** [comment]
Would be interested in seeing this implemented, it is very much necessary since react-native-dom is no longer in active development
