### ISSUE TITLE
Unable to create layer for ReactViewGroup

### ISSUE THREAD

**Issue by genglei01** [TheWidlarzGroup/react-native-video#1544]
### Current behavior
Execute the `seek` method and get the following error:

04-04 15:26:25.115: E/art(27010): JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethod called with pending exception java.lang.IllegalStateException: Unable to create layer for ReactViewGroup @65d79f9, size 12260x12 exceeds max size 8192
04-04 15:26:25.115: E/art(27010):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
04-04 15:26:25.116: E/art(27010):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:328)
04-04 15:26:25.116: E/art(27010):   at void android.os.Looper.loop() (Looper.java:148)
04-04 15:26:25.116: E/art(27010):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6425)
04-04 15:26:25.116: E/art(27010):   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-04 15:26:25.116: E/art(27010):   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1113)
04-04 15:26:25.116: E/art(27010):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:974)
04-04 15:26:25.116: E/art(27010):     in call to CallObjectMethod
04-04 15:26:25.116: E/art(27010):     from void android.os.MessageQueue.nativePollOnce(long, int)

### Reproduction steps
1.A big video
2.Seek from start to end on android.

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer

RN:0.57
    "react-native-video": "^4.4.0",

**Comment by perrosnk** [comment]
I am experiencing the same issue on react-native: 61.2 and Android: 5.1.1
