### ISSUE TITLE
I got an error. It doesn't show video in android and it shows black screen

### ISSUE THREAD

**Issue by 1152295219** [TheWidlarzGroup/react-native-video#1548]
![}LO3CR6PW{H Q4`76X6{K00](https://user-images.githubusercontent.com/45189527/55927459-b758e300-5c47-11e9-81de-8e01f95093c2.png)

**Comment by 1152295219** [comment]
<Video ref="myvideo" 
      source={{uri:"http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"}}
      style={{width:width,height:180, top: 0, left: 0, bottom: 0, right: 0,}}
      rate={1.0}                              // 0 is paused, 1 is normal. 
      volume={1.0}                            
      muted={true}                          
      paused={true}                       
      resizeMode="cover"                      
      repeat={true}                         
      playInBackground={false}                
      playWhenInactive={false}              
      ignoreSilentSwitch={"ignore"}          
      progressUpdateInterval={250.0}          
      onLoadStart={this.loadStart}            
      onLoad={this.setDuration}              
      onProgress={this.setTime}              
      onEnd={this.onEnd}                    
      onError={this.videoError}              
      onBuffer={this.onBuffer}               
      onTimedMetadata={this.onTimedMetadata}  
/>

**Comment by SovaJob** [comment]
Having the same issue
"react-native-video": "3.2.1"

onLoadStart - fire, but onVideoLoaded - sometimes fires only after 5-10 minutes

**Comment by X-Tender** [comment]
I experienced the same issue.
The problem and the solution for me was that the URL to the video must be via https, it's not enough that the server redirects to https, the initial call from within the app must be https.

**Comment by 1152295219** [comment]
> 我遇到了同样的问题。
> 对我来说问题和解决方案是视频的URL必须是通过https，服务器重定向到https是不够的，应用程序内的初始调用必须是https。

I have resolved the problem with the new video version of NPM

**Comment by gsunsnackv** [comment]
I used to run into stucked black screen all the time. The most strange one I experience is https://github.com/react-native-community/react-native-video/issues/1538

My feeling is this project manage the native video player instances very poorly (especially on Android). The project frequently mess things up when you have multiple native video player instances. In our project, we had to do a lot of difficult and hard things to ensure that we only have one instance of a screen that have the <Video> tag, thus only one native video player instance, then it won't stuck.

**Comment by Balasnest** [comment]
@gsunsnackv  did you manage to get it to work?

**Comment by gsunsnackv** [comment]
@Balasnest Our workaround is to have one page that never get unmounted but only hidden. That way we got one instance of whatever native player this project is using. That way it does not stuck. But it is really bad

**Comment by CHaNGeTe** [comment]
Please test with 4.4.4.
If still not works I will reopen the issue
