### ISSUE TITLE
Can hear video but can't see it

### ISSUE THREAD

**Issue by bickerstoff** [TheWidlarzGroup/react-native-video#155]
I've setup the video like this
`<View>
                <YouTube
                    ref="youtubePlayer"
                    videoId="G8KpPw303PY"
                    play={true}
                    hidden={false}
                    playsInline={true}

```
                onReady={(e)=>{this.setState({isReady: true})}}
                onChangeState={(e)=>{this.setState({status: e.state})}}
                onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
                onError={(e)=>{this.setState({error: e.error})}}
                onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}
                style={{backgroundColor: 'black', height: 300}} />   
        </View>   `
```

When I build and run in the iOS simulator, I can't see the video. I can only hear it.

**Comment by bickerstoff** [comment]
I've figured out how to solve this
`<View>
                <YouTube
                    ref="youtubePlayer"
                    videoId="G8KpPw303PY"
                    play={true}
                    hidden={false}
                    playsInline={true}

```
                onReady={(e)=>{this.setState({isReady: true})}}
                onChangeState={(e)=>{this.setState({status: e.state})}}
                onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
                onError={(e)=>{this.setState({error: e.error})}}
                onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}
                style={{backgroundColor: 'blue', height: 300, width: 440}} />   
        </View>   `
```

Both width and height must be set or the visible areal it so small that you can't see the video.

**Comment by Antonhansel** [comment]
Hey @bickerstoff, just curious, have you built a Youtube component yourself that retrieves the stream url from the videoId?
It doesn't seem to be included into react-native-video, am I wrong?
