### ISSUE TITLE
player.seek() is not accurate

### ISSUE THREAD

**Issue by miladrasooli** [TheWidlarzGroup/react-native-video#1550]
### Current behavior
I'm trying to show a trimmed video by limiting currentTime in onProgress event. But when the video reaches a limit and I seek to the start time of trimmed video, `player.seek(startTime)` goes to the wrong position (slightly before the given time). for example If I seek to 1.79323 it seeks to 1.63343!

### Reproduction steps
Just seek to a time and watch the play position

### Expected behavior
It should seek to the desired time

### Platform
Which player are you experiencing the problem on:
* iOS

### Version
React Native 0.54.7
react-native-video 4.3.1

**Comment by NikiLee2016** [comment]
same problem

**Comment by voidrender** [comment]
Try using a smaller tolerance in the seek function call:

`player.seek(42, 0.5);`

**Comment by geroale** [comment]
Same issue on Android: it has an error of almost 6 seconds after seeking. `accuracy` parameter in `player.seek` doesn't work.

**Comment by pyeonjaesik** [comment]
any solution?

**Comment by yalcinozer** [comment]
On Android, if I seek to 19, it goes ~10 ish numbers. If I seek to 8, it goes ~0 ish numbers. I thinks It goes only multiples of 10.

**Comment by yalcinozer** [comment]
> On Android, if I seek to 19, it goes ~10 ish numbers. If I seek to 8, it goes ~0 ish numbers. I thinks It goes only multiples of 10.

After trying some different files, I see seek method affected by the video itself. Altough sek is accurate for some videos, its inaccurate for some other videos.

**Comment by oojikoo** [comment]
I ended up the same conclusion as @yalcinozer.
@yalcinozer have you found why some videos get inaccurate position when seeking?

**Comment by yalcinozer** [comment]
@oojikoo Have no idea. But codec type could be the reason I guess.

**Comment by oojikoo** [comment]
@yalcinozer thank you for the reply! I think I will try other audio formats.

**Comment by Abdullah1428** [comment]
I needed to show the exact time of the video to the user according to the sliding of the trim slider. 
I was facing a similar issue and I got to manage a workaround in my case. I hope it's helpful to anyone facing a similar issue.

```
const [check, setCheck] = useState(true)
onProgress = {onProgress}

const onProgress = ({currentTime}) => {
    if (Math.round(currentTime) === 0 && checked) {
      if (player) {
        player.current.seek('jump to your desired value');
        setChecked(false);
      }
    }

   if (Math.round(currentTime) > 0) {
      if (checked) {
      } else {
        setChecked(true);
      }
    }
}
```
