### ISSUE TITLE
Reset live stream duration player

### ISSUE THREAD

**Issue by ducchungtx** [TheWidlarzGroup/react-native-video#1552]
I have a project play video stream from a Television station and I have 2 components, 1 component for play video in Main Application and 1 component to work with fullscreen player. In the main application when I click to go to Fullscreen in Main Component it will pause video in this component and run in Fullscreen Component. Now when I back Main Component I want this video player is reset and player duration same the Fullscreen before. Has any method function or props can do it?

Thanks for reading and sorry for my bad English.

**Comment by Masoodvali** [comment]
@ducchungtx Do you find any Solution??
