### ISSUE TITLE
Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'

### ISSUE THREAD

**Issue by TheSixer** [TheWidlarzGroup/react-native-video#1554]
* What went wrong:
Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'.
> Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
  Required by:
      project :react-native-video
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints:
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.9.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'

> Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
  Required by:
      project :react-native-video
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints:
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.9.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'

> Could not resolve com.squareup.okio:okio:1.13.0.
  Required by:
      project :react-native-video
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints:
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.10.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp:3.10.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okio:okio' strictly '1.13.0' because of the following reason: debugRuntimeClasspath uses version 1.13.0

> Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
  Required by:
      project :react-native-video > com.facebook.react:react-native:0.56.0
      project :react-native-video > com.facebook.react:react-native:0.56.0 > com.facebook.fresco:imagepipeline-okhttp3:1.9.0
      project :react-native-video > com.facebook.react:react-native:0.56.0 > com.squareup.okhttp3:okhttp-urlconnection:3.10.0
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints:
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.9.1'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.9.1' because of the following reason: debugRuntimeClasspath uses version 3.9.1
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.9.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'

> Could not resolve com.squareup.okio:okio:1.14.0.
  Required by:
      project :react-native-video > com.facebook.react:react-native:0.56.0
      project :react-native-video > com.squareup.okhttp3:okhttp:3.10.0
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints:
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okhttp3:okhttp:3.10.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'henan_medicine:react-native-video:unspecified' --> 'com.facebook.react:react-native:0.56.0' --> 'com.squareup.okhttp3:okhttp:3.10.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'henan_medicine:react-native-video:unspecified' --> 'com.squareup.okio:okio' strictly '1.13.0' because of the following reason: debugRuntimeClasspath uses version 1.13.0

**Comment by luisnaranjo733** [comment]
I'm also seeing this issue on version 3 when I upgraded to RN 0.59.
I upgraded to version 4 and the build issue is fixed, but video player is broken (using it through reactxp-video)

**Comment by samcampisi** [comment]
I am experiencing this issue with version 4.4.1

**Comment by halaharr** [comment]
Is there a workaround for this issue?

**Comment by 404-html** [comment]
Problem is gone for me after updating `react-native-video` package to recent version which is `4.4.2`.

**Comment by 1omarsaid** [comment]
How do you update?
