### ISSUE TITLE
Issue displaying multiple video instances in flatlist

### ISSUE THREAD

**Issue by AlbinBackstrom** [TheWidlarzGroup/react-native-video#1557]
### Current behavior
Scrolling in a flatlist with multiple instances of video gives a black view/screen where the video should be. Only iOS real devices. 
Getting AVFoundationErrorDomain with error code 11839 is that the iOS devices has reached its limit of video instances of AVPlayer that is used native.

### Reproduction steps
Having a flatlist that renders multiple videos

### Expected behavior
Should render videos just like flatlist render images

### Platform
Which player are you experiencing the problem on:
* iOS

### Stuff that I tried
I’ve tried saving the key of the item that renders with onViewableItemsChanged prop and save it and a maximum of ten in redux. Then i fetch this array where the video component is rendered to only render the video component where the id of the item is same as in the array from redux. This should in theory only render items that are viewed or has been viewed recently.

Before this, the videos wasn’t loaded at all now they are rendered for a while but after a couple has been rendered and played the issues is back. The actual component is alwayes rendered (if the keys/id has been saved and fetched to redux) but has a black screen.

Looking for input of how to solve this. Thanks.

**Comment by yemi** [comment]
+1

**Comment by ghost** [comment]
same problem

**Comment by gsunsnackv** [comment]
I used to run into stucked black screen all the time. The most strange one I experience is https://github.com/react-native-community/react-native-video/issues/1538

My feeling is this project manage the native video player instances very poorly (especially on Android). The project frequently mess things up when you have multiple native video player instances. In our project, we had to do a lot of difficult and hard things to ensure that we only have one instance of a screen that have the <Video> tag, thus only one native video player instance, then it won't stuck.

**Comment by CHaNGeTe** [comment]
Please test with 4.4.4.
If still not works I will reopen the issue

**Comment by chris35469** [comment]
Still getting this issue after testing with 4.4.4.

**Comment by liquidvisual** [comment]
@CHaNGeTe Please open this back up, still an issue in 2021.

**Comment by GustavPS** [comment]
still an issue
