### ISSUE TITLE
Cannot build for iOS when libRTCVideo.a is included

### ISSUE THREAD

**Issue by SteveAquino** [TheWidlarzGroup/react-native-video#156]
I'm trying to follow the install instructions for iOS and the build is failing consistently, both when invoked from `react-native run-ios` and building from Xcode.  I've followed the instructions and I'm attempting to load a video from a URL, but it just will not work - building the project always fails when I include `libRTCVideo.a` with this error:

``` bash
Undefined symbols for architecture x86_64:
  "__RCTLogFormat", referenced from:
      -[RCTVideo insertReactSubview:atIndex:] in libRCTVideo.a(RCTVideo.o)
      -[RCTVideo removeReactSubview:] in libRCTVideo.a(RCTVideo.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
    Ld build/Build/Products/Debug-iphonesimulator/Indolja.app/Indolja normal x86_64
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/Indolja.app
An error was encountered processing the command (domain=LaunchServicesError, code=0):
The operation couldn’t be completed. (LaunchServicesError error 0.)
Launching org.reactjs.native.example.Indolja
org.reactjs.native.example.Indolja: 57422
Steves-Mac-mini:Indolja saquino$
```

Here's a screenshot of the `Link Binary With Libraries` section of `Build Phases` as well as the error output:

![screen shot 2016-02-26 at 10 58 09 pm](https://cloud.githubusercontent.com/assets/539839/13371503/81cbd406-dcdc-11e5-9745-72bd5ee547be.png)

---

![screen shot 2016-02-26 at 10 56 18 pm](https://cloud.githubusercontent.com/assets/539839/13371498/5228be8a-dcdc-11e5-8d95-2f17b55fd4c6.png)

Other info:
- `react-native` version 0.20.0
- `react-native-video` version 0.7.1
- Xcode version 7.1

**Comment by SteveAquino** [comment]
I got it to work by monkey patching `RTCVideo.m` and simply commenting out any reference to `RTCLogError`, which seemed related to the error message.

![screen shot 2016-02-26 at 11 51 27 pm](https://cloud.githubusercontent.com/assets/539839/13371816/fb1b4614-dce3-11e5-8a1e-8c8b1dc602ba.png)

This fixes my build problem but obviously it's not right.  Is this an issue with my project or something with react-native-video?  I used this library in another project with no problems, so I'm not sure what's going on here.  This is a fresh app with nothing but the react welcome page and  a `<Video />` component.

**Comment by eduardoboucas** [comment]
I'm getting a similar problem as well, but I don't see any error messages. The build just fails as soon as I add `libRTCVideo.a` to `Build Phases`.

I tried commenting out the lines mentioned by @SteveAquino but it still didn't work. This and the fact that I don't see the same error messages makes me thing it's actually a different issue.

Using React Native version `0.21.0`, `react-native-video` version `0.7.1` and Xcode version `7.2.1`.

**Comment by eduardoboucas** [comment]
I got it working by getting rid of NVM and reinstalling everything from scratch.

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.
