### ISSUE TITLE
ExoPlayer ignores playInBackground

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#1561]
### Current behavior
playInBackground being ignored by ExoPlayer. Works fine on iOS.

**Comment by anshul-kai** [comment]
Related to #1564

**Comment by crwecker** [comment]
Fwiw, we experienced this same issue, and for whatever reason, removing the bufferConfig allowed it to function properly.

**Comment by androidparth90** [comment]
@crwecker : can you please explain how did you solve this ?
