### ISSUE TITLE
onAudioFocusChanged will call when start to play at first time.

### ISSUE THREAD

**Issue by SwiftyWang** [TheWidlarzGroup/react-native-video#1562]
### Current behavior
I register onAudioFocusChanged listener and the implementation is 
```
  onAudioFocusChanged(data) {
    this.setState({
      paused: !data.hasAudioFocus
    });
  }
```
 
### Reproduction steps
100%
1. Always when I first-time click play button which will set state paused to false.
2. The onAudioFocusChanged will be called and hasAudioFocus is false.
3. Finally, it will cause my player paused again.
4. Then I press play button again no callback will be called. the behavior is normal.

### Expected behavior
No onAudioFocusChanged will be called when first time play.

### Platform
* Android

**Comment by mojtaba-hajishah** [comment]
Same here.

Platform: Android
react-native-video: 4.4.1

**Comment by SwiftyWang** [comment]
Sames this lib has already died. poor react-native.
