### ISSUE TITLE
IOS player, it takes 10 secs for the player to play remote .mp3

### ISSUE THREAD

**Issue by shuuha** [TheWidlarzGroup/react-native-video#1565]
When playing a remote uri media file (.mp3), the IOS player loads it in 2-3 secs, but after that it takes 10 seconds before the playback begins.

### Expected behavior
An android it starts playing the remote file right after the onLoad listener fires.

### Platform
Which player are you experiencing the problem on:
* iOS

I have tried disabling, configuring buffering, tried to run the video component with no setting enabled except source prop, but still same.

Would much appreciate any help.

**Comment by shuuha** [comment]
Additional information:

Here is how I am using the Video component:

```
<Video
                  repeat
                  ignoreSilentSwitch={"ignore"}
                  progressUpdateInterval={50}
                  playInBackground={false}
                  playWhenInactive={false}
                  resizeMode="cover"
                  source={{ uri: `http://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3` }}
                  ref={ref => (this.player = ref)}
                  onLoad={this.onVideoLoad}
                  onLoadStart={this.onLoadStart}
                  onProgress={this.onPlayerProgress}
                  onEnd={this.onPlaybackEnd}
                  onError={this.onVideoLoadError}
                  onBuffer={this.onVideoBuffer}
                  style={{ flex: 1 }}
                  controls={false}
                  paused={playerPause}
                />
```

Here are the logs when the listeners get triggered:
![image](https://user-images.githubusercontent.com/32106081/56730845-5b777980-6772-11e9-8448-0cf84523e473.png)

As you can see first **onLoadStart** triggers, then **onLoad**, which should mean that the file is loaded and it should play right away (which happens on Exoplayer). But on IOS we can see a delay before the loaded file is played.

What is interesting is that if .mp4 is loaded it plays much faster.
Or maybe is this the expected behaivor for IOS audio player?

**Comment by shuuha** [comment]
Anybody can share his experience with playing remote audio files on the IOS?

**Comment by minhlaunchdeck** [comment]
I have the same issue. The onLoad event starts very quickly but then it takes a while (8-10 seconds) for the audio (mp3) to be actually played.

**Comment by shuuha** [comment]
So this means that this is the expected behaivor while playing remote audio files on IOS. Can any of the devs confirm this, please?

**Comment by shuuha** [comment]
It seems that the delay had something to do with the server, that was serving the file. After the backend guy made some changes to the storage where the files wered saved (AWS), the delay reduced to 1-2 seconds. So I think I will close the issue.
