### ISSUE TITLE
Empty <Video/> component when local path contains spaces (IOS).

### ISSUE THREAD

**Issue by Chugunenok** [TheWidlarzGroup/react-native-video#1566]
### Current behavior
Empty Video component (shows nothing) when local path contains spaces (IOS).

### Reproduction steps
When path in {uri:path} contains spaces - Video component shows nothing

Fail Path example:
_file:///var/mobile/Containers/Data/Application/9B8A4DAE-C338-46DC-95F8-6B6EAB791604/Documents/Camera/test spaces.mov_
Works with path (space replaced with _)
_file:///var/mobile/Containers/Data/Application/9B8A4DAE-C338-46DC-95F8-6B6EAB791604/Documents/Camera/test_spaces.mov_

### Expected behavior
Player should play video from local path contains spaces.
Now have to replace spaces with %20 at JS code.

### Platform
Which player are you experiencing the problem on:
* iOS

Same issue mentioned in [this comment](https://github.com/react-native-community/react-native-video/issues/644#issuecomment-466590481)

**Comment by shuuha** [comment]
try "decodeURI(path)". should work.

**Comment by Chugunenok** [comment]
@shuuha 
> try "decodeURI(path)". should work.

Will encodeURI(encodeURI()) return correct path? How can I control that path is already encoded?

I suppose Video should do encoding inside it, as encoding should be executed ALWAYS.
NSURL needs encoded path to init.
In Swift i do the following: URL.init(string: localPath.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
Do not know the way to do it in ObjC.

**Comment by pdsouza** [comment]
I can confirm that this issue is occurring with the latest release 5.0.2 on iOS with remote URLs containing spaces as well.

We are currently working around this issue by using `encodeURI` for now:

```js
<Video
  source={{uri: encodeURI(uri)}}
  controls={true}
/>
```

Although unaffected by this issue, Android works fine with `encodeURI` as well.
