### ISSUE TITLE
android:How to fullscreen in Flatlist?

### ISSUE THREAD

**Issue by Wangzihao5325** [TheWidlarzGroup/react-native-video#1567]
i try to resize Video with height:100% width:100% but it just cover a item,
can anyone help me,android, How to fullscreen video in Flatlist?
thanks a lot

**Comment by ghost** [comment]
same issue here

**Comment by ethanleeX** [comment]
maybe the problem is that you android device has notch

**Comment by r0b0t3d** [comment]
You could try this #2073 to see whether it solve your problem
