### ISSUE TITLE
Not able to display  wistia videos and youtube videos using react native video

### ISSUE THREAD

**Issue by mitulshah96** [TheWidlarzGroup/react-native-video#1569]
Not able to display  wistia videos and youtube videos using react native video

**Comment by mitulshah96** [comment]
wistia url: http://fast.wistia.net/embed/iframe/8je6hmyugi?autoPlay=true&silentAutoPlay=deny
youtube url : https://www.youtube.com/watch?v=xa-_FIy2NgE

**Comment by DikenOpenxcell** [comment]
@mitulshah96 Have you found any solution regarding Youtube video play?

**Comment by asilvestre87** [comment]
Any solution?

**Comment by chulanovskyi** [comment]
I really doubt that this library can render Youtube links. As the error says - `unrecognized media format`

I've tried different approaches, looked for some sort of "youtube direct video URL extractor", but found none :(

![photo_2019-06-24_20-36-47](https://user-images.githubusercontent.com/13966263/60039640-e23bca80-96bf-11e9-82b5-a7d0cb127e8e.jpg)

**Comment by CHaNGeTe** [comment]
This library does not support loading Youtube Videos, the url your passing in is not actually a stream url.
Youtube support is not currently in the roadmap.
You will need sth like: https://github.com/inProgress-team/react-native-youtube
https://www.npmjs.com/package/react-native-wistia
