### ISSUE TITLE
Android expansion file not working

### ISSUE THREAD

**Issue by vincentum** [TheWidlarzGroup/react-native-video#1574]
### Current behavior
Android expansion file not working. Video shows nothing like it empty.

### Reproduction steps
1. Set source as { uri: 'test', mainVer: 1 } and build the app
2. Create expansion zip file, rename to main.1.<package-name>.obb and put it in share storage under my app package folder
3. Open app. Video not playing.

### Expected behavior
1. Video playing from file in expansion file.

### Platform
Which player are you experiencing the problem on:
* Android

Am I wrong or is this expansion file support on Android is over?

**Comment by chiefchief** [comment]
> ### Current behavior
> Android expansion file not working. Video shows nothing like it empty.
> 
> ### Reproduction steps
> 1. Set source as { uri: 'test', mainVer: 1 } and build the app
> 2. Create expansion zip file, rename to main.1..obb and put it in share storage under my app package folder
> 3. Open app. Video not playing.
> 
> ### Expected behavior
> 1. Video playing from file in expansion file.
> 
> ### Platform
> Which player are you experiencing the problem on:
> 
> * Android
> 
> Am I wrong or is this expansion file support on Android is over?

have you find solution?
