### ISSUE TITLE
Suggestion: replace video caching with KTVHTTPCache and AndroidVideoCache

### ISSUE THREAD

**Issue by zhigang1992** [TheWidlarzGroup/react-native-video#1579]
Currently, Caching is implemented on iOS only on AVPlayer level. Which might be problematic.

Where [KTVHTTPCache](https://github.com/ChangbaDevs/KTVHTTPCache) for iOS and [AndroidVideoCache](https://github.com/danikula/AndroidVideoCache) for Android implemented video caching completely different. 

They started an HTTP server and caching, loading video from there instead. It's much more stable and reliable.

I've created a react-native wrapper around them https://github.com/zhigang1992/react-native-video-cache but would love to see if you guys are interested in integration them directly from this repo?

**Comment by GoktuqCan** [comment]
I think this issue needs to be revisited. @zachrnolan great repo, thanks.

**Comment by smironescu** [comment]
Raising issue @zhigang1992 

- I've been testing your solution and seems to work perfectly, but: Works very well on local and remote devices. Doesn't work when you stream to any local device (AirPlay). For example, stream a video on the local TV, doesn't work. It keeps loading.. 
- Right now I've uninstalled the solution as was a pain finding the problem with my team :(. Nice work anyway

**Comment by zhigang1992** [comment]
Aha, that'd actually make sense because the HTTP proxy server is hosted locally on the Phone.

If you want to be able to AirPlay, it'd probably need to do a `url.replace(/localhost/, 'lan.ip')` if the cache server is open to LAN access (Which I'm not 100% sure).

**Comment by khattab93** [comment]
@zhigang1992 I tested your solution but I found that the synchronous convert method works only for short videos, 4 or 5 seconds. When I tested it with a video of length 19 seconds it fails :( Nice work anyway
