### ISSUE TITLE
How to set video not loaded when video Component in Flatlist out of view ?

### ISSUE THREAD

**Issue by auchaphon** [TheWidlarzGroup/react-native-video#1580]
Platform android
- I have many data -> video
- Video length more 3 min.

Please help me, now always app crash

**Comment by jonyhandoko** [comment]
Yeah I also want to do this like instagram feeds by using flatlist. Please anyone help. Now when I load 10 videos, will start buffer and downloading all the video makes the apps very laggy.

**Comment by SwiftyWang** [comment]
please use the native app to do this kind of feature

**Comment by pppluto** [comment]
use a holder or poster to replace video when it's not viewable.

**Comment by jsuhangita** [comment]
> please use the native app to do this kind of feature

Any details how to do that?

**Comment by FadiAboMsalam** [comment]
@auchaphon @jonyhandoko guys please check how i achieved this, i just posted the solution on [stackoverflow](https://stackoverflow.com/questions/54839940/pause-video-in-flatlist-when-out-of-view/57470418#57470418)
please let me know if this is helpful

**Comment by duyanhla** [comment]
> @auchaphon @jonyhandoko guys please check how i achieved this, i just posted the solution on [stackoverflow](https://stackoverflow.com/questions/54839940/pause-video-in-flatlist-when-out-of-view/57470418#57470418)
> please let me know if this is helpful

Hello sir, your solution work perfectly but i have an issue that when scroll to current index, the video will auto play (Using native media player), how can i prevent it, thank you.
