### ISSUE TITLE
react-native-video shows blank screen in my app without any error log

### ISSUE THREAD

**Issue by ManalLiaquat** [TheWidlarzGroup/react-native-video#1582]
### Current behavior
Describe what happens when you encounter this issue.

> I am using only one video file for each screen (I have four screens), when I switch to another screen the video not play on the next screen when I goto previous screen video is playing and shows the black (blank area) screen without throwing error.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior

> I just want to play video on each screen as I goto another screen

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
> I have downloaded [this video](https://www.youtube.com/watch?v=TcMBFSGVi1c) and use it from my project.
`<Video source={require("../../assets/video/backgroundVideo.mp4")} />`

**Comment by ejkkan** [comment]
https://github.com/react-native-community/react-native-video/issues/338#issuecomment-251856958

**Comment by gsunsnackv** [comment]
I used to run into stucked black screen all the time. The most strange one I experience is https://github.com/react-native-community/react-native-video/issues/1538

My feeling is this project manage the native video player instances very poorly (especially on Android). The project frequently mess things up when you have multiple native video player instances. In our project, we had to do a lot of difficult and hard things to ensure that we only have one instance of a screen that have the <Video> tag, thus only one native video player instance, then it won't stuck.

**Comment by CHaNGeTe** [comment]
Can you try on 4.4.4?

**Comment by codervss** [comment]
Does changing to 4.4.4 resolve the issue

> Can you try on 4.4.4?

Does changing to 4.4.4 resolve the issue?
Have been stuck in this for a long time now

**Comment by waheedakhtar694** [comment]
@gsunsnackv i am having same issue on android on `v5.0.2` on ios it works fine.

**Comment by IamMasterWayne** [comment]
+1

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
"react-native-video": "^5.0.2"

React Native Android Black Screen For Android

**Comment by petrosmm** [comment]
can someone tell me if this is related to https://github.com/google/ExoPlayer/issues/58, https://github.com/google/ExoPlayer/issues/2993 ?? because I do remember experiencing those issues before?

**Comment by petrosmm** [comment]
> Can you try on 4.4.4?

can someone tell me if this is related to google/ExoPlayer#58, google/ExoPlayer#2993, and/or https://exoplayer.dev/supported-devices.html ?? because I do remember experiencing those issues before?
