### ISSUE TITLE
Playing m3u file 

### ISSUE THREAD

**Issue by anaslaaroussi** [TheWidlarzGroup/react-native-video#1583]
Hi,
Is it possible to read m3u file  that is used for IPTV?

**Comment by canyavall** [comment]
Yes it is

**Comment by anaslaaroussi** [comment]
When I use a m3u file, the screen stay black , but it work with the other type of files.

**Comment by canyavall** [comment]
We are using it with m3u and no problems, we can run any stream, maybe some missconfigurations?
