### ISSUE TITLE
show last frame onEnd instead of first

### ISSUE THREAD

**Issue by o0JoeCool0o** [TheWidlarzGroup/react-native-video#1584]
### Current behavior
Describe what happens when you encounter this issue.
When the video reaches the end the image doesnt display the last frame of the video it shows the starting frame.

I have tried adding .seek(data.duration) to the onEnd() however it seems to restart and play the video from the beginning. Even if I also add .stop() after this. 

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
play a video

### Expected behavior
Describe what you wanted to happen
I want the last frame to continue be displayed and the video to be stopped.

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by TimmeeG** [comment]
@o0JoeCool0o Did you find a work around for this?

**Comment by o0JoeCool0o** [comment]
Yes I did. I ended up doing this: 

Create a function that gets called onProgressUpdated: and check the seekableDuration and currentTime to see if the video is at the end. Then I just call pause. Maybe not the right way but it seems to work!
 ```
  <Video 
       onProgress = {this._progressUpdated} ...
```
```
   _progressUpdated = (data) => {      
        if(data.currentTime > data.seekableDuration-0.5){
            this.player.pause();
        }
    }
```
