### ISSUE TITLE
 Unable to resolve dependency for ':react-native-video@debug/compileClasspath':

### ISSUE THREAD

**Issue by iparshantnagpal** [TheWidlarzGroup/react-native-video#1585]
Hi  Admin

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.9.1.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.0.0.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.13.0.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.0.0.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.squareup.okio:okio:1.14.0.
Show Details
Affected Modules: react-native-video

ERROR: Unable to resolve dependency for ':react-native-video@debug/compileClasspath': Could not resolve com.android.support:support-annotations:27.1.1.
Show Details
Affected Modules: react-native-video

Please change provided to compile

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
    }
}

dependencies {
    provided 'com.facebook.react:react-native:+'
    compile 'com.google.android.exoplayer:exoplayer:2.7.3'
    compile('com.google.android.exoplayer:extension-okhttp:2.7.3') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
    compile 'com.squareup.okhttp3:okhttp:3.9.1'
}

**Comment by iparshantnagpal** [comment]
Please change 
provided 'com.facebook.react:react-native:+'
to 
compile 'com.facebook.react:react-native:+'

**Comment by yrjwcharm** [comment]
@paramaggarwal  谢谢大佬。 我解决了。 你应该明确下 应该 是在react-native-video 依赖库 build.gradle 里把provided 改成 compile .

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/58222383-71b02f80-7d48-11e9-9f97-fa8e5243e3c2.png)

**Comment by yrjwcharm** [comment]
已解决

**Comment by yrjwcharm** [comment]
我是yrjwcharm -----已解决 谢谢大佬

**Comment by Damoness** [comment]
> Please change
> provided 'com.facebook.react:react-native:+'
> to
> compile 'com.facebook.react:react-native:+'

thank you
