### ISSUE TITLE
react-native-video not playing cached videos even path exsists

### ISSUE THREAD

**Issue by saqlainawan** [TheWidlarzGroup/react-native-video#1588]
### Current behavior
Video is captured on react-native-camera and its is cached and got the uri. But gives error trying to load empty source

### Expected behavior
After video is cached from react-native-camera, It should play in react-native-video.

### Platform
Which player are you experiencing the problem on:
* Android
*React-Native

**Comment by traxx10** [comment]
I Have the same issue.
Anyone know how to resolve this?

**Comment by jhopper28** [comment]
This can happen if you attempt to assign a string file path directly to the component's source attribute instead of an object with a uri property like `source={{ uri: 'file:///path/to/resource.jpg' }}`.
