### ISSUE TITLE
Video playing takes major place on the main Js thread.

### ISSUE THREAD

**Issue by yasahmed** [TheWidlarzGroup/react-native-video#1589]
### Current behavior
Video playing takes place on the main Js thread (90%), so react-native app Freeze on android (i didn't test on IOS)

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
I think that video playing doesn't need to take all js Thread memory !

### Platform
Which player are you experiencing the problem on:

android-exoplayer

### Video sample
![image](https://user-images.githubusercontent.com/6693263/57815786-64071280-7768-11e9-8042-966aa97f174e.png)

Is there a solution for this or is it a bug?

**Comment by ptgamr** [comment]
+1 for this...

Other controls seems pretty il-responsive when the video is playing. Would be nice to know the reason why and if there is a way to improve it.

**Comment by CHaNGeTe** [comment]
A lot of work has to be done wrt optimisation.
In the meantime, tell us a bit more about your setup.
are you using the controls prop?
Have you tried increasing [progressupdateinterval](https://github.com/react-native-community/react-native-video#progressupdateinterval) ?
