### ISSUE TITLE
No support for twitch urls

### ISSUE THREAD

**Issue by harikanammi** [TheWidlarzGroup/react-native-video#1594]
### Current behaviour
Video is not displaying while giving uri:- https://player.twitch.tv/?autoplay=false&video=v202120863

### Reproduction steps
- Installed react-native-video.
- Followed manual Linking process for both platforms- iOS & Android.
- I placed the uri:- https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/1455/8/207277102/706899312.mp4?token=1559118009-0x6d1fc4ad0ca796215f94d40e9110505ab4291dc9 it is working fine in both Platforms.
- When i placed the uri:- https://player.twitch.tv/?autoplay=false&video=v202120863 it is not working in both Platforms.

### Expected behaviour
Video will be displaying with uri:-https://player.twitch.tv/?autoplay=false&video=v202120863
### Platform

* iOS
* Android ExpoPlayer
### Versions

>   "react": "16.8.3",
>    "react-native": "0.59.5",
>    "react-native-video": "^4.4.1"

### Code
```
import React, { Component } from "react";
import { Platform, StyleSheet, View, Text } from "react-native";
import Video from "react-native-video";

type Props = {};
export default class VideoPlayer extends Component<Props> {
  constructor(props) {
    super(props);
    this.state = {
      quality: "",
      error: "",

      paused: false,
      currentTime: "",
      duration: ""
    };
  }
  onLoad(data) {
    this.setState({ duration: data.duration });
  }
  onProgress(data) {
    this.setState({ currentTime: data.currentTime });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Video Player</Text>
        <View
          style={{
            margin: 1
          }}
        >
          <Video
            source={{
              uri: "https://player.twitch.tv/?autoplay=false&video=v202120863",
              type: "mp4"
            }}
            rate={1.0}
            volume={1.0}
            paused={this.state.paused}
            muted={false}
            resizeMode="contain"
            onLoad={this.onLoad.bind(this)}
            onProgress={this.onProgress.bind(this)}
            onEnd={() => {
              this.setState({ paused: !this.state.paused });
            }}
            repeat={true}
            playInBackground={false}
            playWhenInactive={false}
            style={styles.backgroundVideo}
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    marginTop: 20
  },
  backgroundVideo: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,

    width: 300,
    height: 180
  }
});
```
### Screenshots:-

iOS:-
![Simulator Screen Shot - iPhone 6 Plus - 2019-05-28 at 17 50 02](https://user-images.githubusercontent.com/31063894/58478011-9c4c1f00-8172-11e9-8da1-bcd18ff233e6.png)
Android:-
![Screenshot_20190528-174958](https://user-images.githubusercontent.com/31063894/58478099-d6b5bc00-8172-11e9-9591-c062634ebdec.png)

**Comment by CHaNGeTe** [comment]
There is no support for twitch videos by setting the twitch url directly
