### ISSUE TITLE
Could not find support-media-compat.jar

### ISSUE THREAD

**Issue by aliakbarazizi** [TheWidlarzGroup/react-native-video#1595]
# Bug

I get this error for building

```* What went wrong:
Could not resolve all files for configuration ':react-native-video:debugCompileClasspath'.
> Could not find support-media-compat.jar (com.android.support:support-media-compat:28.0.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/support-media-compat/28.0.0/support-media-compat-28.0.0.jar```

## Environment info

<!--
  Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project
-->

React native info output: 
```bash
   React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      Memory: 1.65 GB / 7.92 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - D:\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```

Library version: 28.0.0

## Steps To Reproduce

Install react-native-video in new react native project

Describe what you expected to happen:

1. building successfull

**Comment by aminbaybon** [comment]
also my problem 
:(

**Comment by aminbaybon** [comment]
add
 ```
compileSdkVersion safeExtGet('compileSdkVersion', 28)
    buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
        targetSdkVersion safeExtGet('targetSdkVersion', 28) 
```

in android parts of 
1- node_modules/react-native-video/android/build.gradle 
also in 2 -  node_modules/react-native-video/android-exoplayer/build.gradle   ...


and add this lines in your mainbuild.gradle of project 
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
    }
```
then run your project again . i works for me

**Comment by aliakbarazizi** [comment]
@aminbaybon I solve problem by changing in android-expoplayer/build.gradle
add `@aar` at this line

```implementation "com.android.support:support-media-compat:${safeExtGet('supportLibVersion', '+')}@aar"```

I think it's a bug in windows, because I get no error in mac.

**Comment by aliakbarazizi** [comment]
@hueniverse tnx for closing not resolved issues. closing in fact is a solution for issues!

**Comment by hueniverse** [comment]
@aliazizi I really don't appreciate your tone and attitude - I don't work for you. This is a 3 years old issue. If you found a solution, you should have submitted a pull request. I don't work for you or your company and after three years, no one else had the time to resolve this. If you would like to open a new PR with a fix, it will get reviewed.

**Comment by aliakbarazizi** [comment]
> @aliazizi I really don't appreciate your tone and attitude - I don't work for you. This is a 3 years old issue. If you found a solution, you should have submitted a pull request. I don't work for you or your company and after three years, no one else had the time to resolve this. If you would like to open a new PR with a fix, it will get reviewed.

Usually libraries close issue after 1 month stale warning. I never asked you to help me and will never need you.
Issue means problem and open issue mean it's not resolved.
I don't know where you get word "work fo me" but i guess it's because of your imagination.
Even if you want, i don't need your help.
This is a public library and it's not only for you.


I resolved my issue as explained and I don't know how to solve it in library. You can be sure if I find it I'll make pull request. Don't be judgmental.

Years is not answer to issues, in fact make it bolder.

After 3 years the issue is still exist so open it. This is not personal opinion. Like most library you can add warning for inactivity and after that close it, but this one is still active.

**Comment by aliakbarazizi** [comment]
I don't understand why repo admin wants to close issue and say we have active library. I saw lot of not resolved closed issues and cause of someone like you closed that the issue exist after years. Please be a nice admin and don't put your imagination or person opinion in this.

**Comment by hueniverse** [comment]
Having 1100+ open issues means that no one looks at them and people just give up on even trying to close issues. Open source is driven by the people who show up and do the work, not the people using the code. You have an issue that has been ignored for three years. Closing issues doesn't delete them or make them go away. Closing it with a `stale` label clearly communicates to others why it was closed. If someone else searches for it, they will find it and maybe they will find a solution for it.
