### ISSUE TITLE
Android lock screen background stop

### ISSUE THREAD

**Issue by GH974** [TheWidlarzGroup/react-native-video#1596]
# Bug

audio in Background stops when the Android is locked and screen is off.
However if the Android is locked, but the screen is on (showing lock screen and encouraging the user to press home button to unlock) background and audio run

## Environment info

React native info output:

```bash
 // paste it here
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 461.25 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: x.x.x
Android 9
react-native-video 4.4.1
## Steps To Reproduce

Describe what you expected to happen:

1.

2.

**Comment by CHaNGeTe** [comment]
Can you fill `Steps To Reproduce` and what you expected to happen?
Please share your Video component props also to help us track the issue.

**Comment by GH974** [comment]
Hi, i don't know to reproduce this. I receive this error on android device, production mode. I have be notified bye a user, who use my app, I have not more information at the moment sorry. 
I report anyway in case someone has the same worries and more information

**Comment by fidelsam1992** [comment]
@GH974  It seems there are new restrictions on android 9 with the background services 
https://developer.android.com/about/versions/pie/android-9.0-changes-all

Anyone knows how to come around this in react-native ?

This looks related #1341

**Comment by fidelsam1992** [comment]
@GH974 I have solved by this workaround : 
- My project is using react-native-music-control (https://github.com/tanguyantoine/react-native-music-control)
- I update the package to the latest and included ` <uses-permission android:name="android.permission.FOREGROUND_SERVICE" /> ` to the manifest

**Comment by GH974** [comment]
@fidelsam1992 hi, yes it's me who suggested the bug fix in react-native-music-control, but, this problem is another, in background mode, its works, but in few minutes the music is stopped

**Comment by iphonic** [comment]
Some of the users of our App experiencing Audio stop after it plays for some time in Background mode on Android, we are unable to find why, using version 5.2.1.

Thanks.
