### ISSUE TITLE
How to perform caching on videos while playing it from remote uri

### ISSUE THREAD

**Issue by cisnayan** [TheWidlarzGroup/react-native-video#1599]
Is there any proper solution to implement caching for both platforms iOS and android?

**Comment by badri21P** [comment]
by default you can implement caching on ios. Please refer to this link [here]( https://github.com/react-native-community/react-native-video/tree/master/examples/video-caching ). 
If you need to cache the video in android, then react-native-video doesn't support caching on android. you have to use external libraries like react-native-fetch-blob to download the file and play it locally.You can find full reference over [here](https://stackoverflow.com/questions/44090112/how-to-implement-cache-in-react-native-video/44090821).
