### ISSUE TITLE
iOS, Unable to simultaneously satisfy constraints when setting controls to true 

### ISSUE THREAD

**Issue by ericfu88** [TheWidlarzGroup/react-native-video#160]
Set "controls" to true in index.ios.js, like this:
  state = {
...
    controls: true,
...
  };

results in "Unable to simultaneously satisfy constraints..". Tested this on iPhone 6 emulator. 
Does anyone else have this issue?

**Comment by ericfu88** [comment]
Sample of the warning: 
2016-03-03 21:37:25.806 VideoPlayer[44633:479318] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fe3a17725e0 UIImageView:0x7fe3a38cc840.centerX == AVUnsupportedContentIndicatorView:0x7fe3a3930a10.centerX>",
    "<NSLayoutConstraint:0x7fe3a1772d60 H:|-(>=10)-[UIImageView:0x7fe3a38cc840]   (Names: '|':AVUnsupportedContentIndicatorView:0x7fe3a3930a10 )>",
    "<NSLayoutConstraint:0x7fe3a3a31340 H:|-(0)-[AVUnsupportedContentIndicatorView:0x7fe3a3930a10]   (Names: '|':UIView:0x7fe3a3930300 )>",
    "<NSLayoutConstraint:0x7fe3a3a313d0 H:[AVUnsupportedContentIndicatorView:0x7fe3a3930a10]-(0)-|   (Names: '|':UIView:0x7fe3a3930300 )>",
    "<NSLayoutConstraint:0x7fe3a3a31150 H:|-(0)-[UIView:0x7fe3a3930300]   (Names: '|':AVPlayerView:0x7fe3a392f440 )>",
    "<NSLayoutConstraint:0x7fe3a3a311c0 H:[UIView:0x7fe3a3930300]-(0)-|   (Names: '|':AVPlayerView:0x7fe3a392f440 )>",
    "<NSLayoutConstraint:0x7fe3a395f750 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x7fe3a392f440(0)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fe3a17725e0 UIImageView:0x7fe3a38cc840.centerX == AVUnsupportedContentIndicatorView:0x7fe3a3930a10.centerX>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-03-03 21:37:25.808 VideoPlayer[44633:479318] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fe3a1772d60 H:|-(>=10)-[UIImageView:0x7fe3a38cc840]   (Names: '|':AVUnsupportedContentIndicatorView:0x7fe3a3930a10 )>",
    "<NSLayoutConstraint:0x7fe3a176ca00 H:[UIImageView:0x7fe3a38cc840]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x7fe3a3930a10 )>",
    "<NSLayoutConstraint:0x7fe3a3a31340 H:|-(0)-[AVUnsupportedContentIndicatorView:0x7fe3a3930a10]   (Names: '|':UIView:0x7fe3a3930300 )>",
    "<NSLayoutConstraint:0x7fe3a3a313d0 H:[AVUnsupportedContentIndicatorView:0x7fe3a3930a10]-(0)-|   (Names: '|':UIView:0x7fe3a3930300 )>",
    "<NSLayoutConstraint:0x7fe3a3a31150 H:|-(0)-[UIView:0x7fe3a3930300]   (Names: '|':AVPlayerView:0x7fe3a392f440 )>",
    "<NSLayoutConstraint:0x7fe3a3a311c0 H:[UIView:0x7fe3a3930300]-(0)-|   (Names: '|':AVPlayerView:0x7fe3a392f440 )>",
    "<NSLayoutConstraint:0x7fe3a395f750 'UIView-Encapsulated-Layout-Width' H:[AVPlayerView:0x7fe3a392f440(0)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fe3a176ca00 H:[UIImageView:0x7fe3a38cc840]-(>=10)-|   (Names: '|':AVUnsupportedContentIndicatorView:0x7fe3a3930a10 )>

**Comment by corbt** [comment]
Yes, I'm getting this same error. Trying to determine if it's a problem with my usage or something inherent to the library.

**Comment by Emilios1995** [comment]
I'm getting the same error.
What I want to do is change the source of the video based on my state.
Whenever I change that state, the application crashes

**Comment by sjchmiela** [comment]
That's not an error, but a warning. As far as I know, it can't be cured, but it's harmless.
