### ISSUE TITLE
[REQUEST] Play in reverse

### ISSUE THREAD

**Issue by alz10** [TheWidlarzGroup/react-native-video#1601]
I have this animated low poly background video that i used in my app using this library unfortunately when video reaches the end, it just loops to the first duration of the video. It looks jerky. I wanted it to be seemless loop when/if the video reaches the end, it will just play in reverse and vice versa if the reversed video reaches the start

**Comment by hannojg** [comment]
The native libraries used in this library don't support reverse playback, thus implementing it in this library is not (or very hardly) possible.
