### ISSUE TITLE
[iOS] Sound will echo when playback speed is slowed down

### ISSUE THREAD

**Issue by gorvinsky** [TheWidlarzGroup/react-native-video#1603]
# Bug

Sound will echo if I set ``rate`` lower than 1 like 0.5 in iOS. This is an audio only MP3. Not sure if video has this problem as well or not.

## Environment info

react-native: 0.47.1
react-native-video: 2.3.1

## Steps To Reproduce

Set ``audioOnly={true}`` and ``rate={0.5}`` in the Video component.

Describe what you expected to happen:

1. Audio playback speed slowed down to 50% without producing any echo.

## Reproducible sample code

```
<Video
    ...
    audioOnly={true}
    rate={0.5}
    ...
/>
```

**Comment by truckhiem** [comment]
Any idea??

**Comment by rikner** [comment]
I would guess that what you hear is not an echo but audio artifacts caused by the time stretching algorithm which tries to keep the original pitch while slowing down the tempo (no time stretching would sound like slowing down a vinyl record).

edit: https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling

**Comment by gorvinsky** [comment]
@rikner Even if you're right, it only occur in iOS. Android is fine. So it's still need fixing.

**Comment by rikner** [comment]
@gorvinsky True. I guess it's a matter of being able to change the type of `audioTimePitchAlgorithm` used in `AVPlayerItem`.

**Comment by pabloluz** [comment]
I'm also interested in this topic.

**Comment by sampsonjoliver** [comment]
I believe this is solved by https://github.com/react-native-community/react-native-video/pull/1570 though that PR has not been merged for some time now
