### ISSUE TITLE
Video doesn't work in Android in Debug mode but it works in Production

### ISSUE THREAD

**Issue by matteocollina** [TheWidlarzGroup/react-native-video#1604]
# Bug
Video doesn't work in Android only in Debug mode (`$ react-native run-android`), it works in Production (with my device plugged: `$ sudo react-native run-android`).
iOS works fine.

## Environment info

Environment:
  OS: macOS 10.14.4
  Node: 10.14.2
  Yarn: 1.15.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Library version: 4.4.1

## Reproducible sample code

I have "_enter_screen.mp4_" in _src/main/res/raw/enter_screen.mp4_

```
const styles = StyleSheet.create({
    video: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    }
})

<Video source={{uri:'enter_screen'}}
                    ref={(ref) => {
                        this.player = ref
                    }}    
                    resizeMode="cover"    
                    controls={false}
                    style={styles.video} />

```

**Comment by tonyhb** [comment]
Remove underscores in your video name.

See https://github.com/react-native-community/react-native-video/issues/1186#issuecomment-552738393

**Comment by Saad9624** [comment]
from resource folder how do you able to play video in ios?
