### ISSUE TITLE
Tipe of extensions

### ISSUE THREAD

**Issue by diegogurgel** [TheWidlarzGroup/react-native-video#1605]
What kind of extensions are supported by source attribute? And can I put a playlist file assuming that the video player will automatically select from that playlist using the Adaptive Bitrate Streaming. If no where can I specify the uri options for the ABS. Thank you.

**Comment by jensellfors** [comment]
Please see the documentation for AVPlayer and ExoPlayer. But if you use a HLS (.m3u8) playlist then ABS will be used.
