### ISSUE TITLE
`Video` has no propType for native prop `RCTVideo.onRestoreUserInterfaceForPictureInPictureStop` of native type `BOOL`

### ISSUE THREAD

**Issue by matteocollina** [TheWidlarzGroup/react-native-video#1606]
# Bug
ExceptionsManager.js:71 Unhandled JS Exception: Error: `Video` has no propType for native prop `RCTVideo.onRestoreUserInterfaceForPictureInPictureStop` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

This error is located at:
    in RCTVideo (at Video.js:312)
    in Video (at index.js:255)
    in RCTView (at View.js:60)

## Environment info
Environment:
  OS: macOS 10.14.5
  Node: 10.14.2
  Yarn: 1.15.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

React native info output:

Library version: 4.4.1

## Reproducible sample code

`const styles = StyleSheet.create({
    video: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    }
})

<Video source={{uri:'enter_screen'}}
                    ref={(ref) => {
                        this.player = ref
                    }}    
                    resizeMode="cover"    
                    controls={false}
                    style={styles.video} />`

**Comment by jiangbophd** [comment]
same issue

**Comment by jensellfors** [comment]
> Version 4.x requires react-native >= 0.57.0

Either upgrade `react-native` or downgrade `react-native-video`. Make sure to run `pod install` after you do.
