### ISSUE TITLE
 I want to stop playing the current media when using another media app.

### ISSUE THREAD

**Issue by wsupajirakit** [TheWidlarzGroup/react-native-video#1608]
I want to stop playing the current media when using another media app.

ex.
My App current Play
and when open Youtube and play some vdo on youtube
I want to stop my App and Play only Youtube (but it's play both app)

iOS it's stop my app when play Youtube
But Android it's not

                 <Video
                 volume={this.state.volume}
                 paused={this.state.paused}
                 ref={(ref) => { this.video = ref }}
                 source={{ uri : this.state.url  }}
                 playInBackground={true}
                 playWhenInactive={true}
                 shouldPlay
                 ignoreSilentSwitch={"ignore"} 
                 resizeMode="cover"
                 style={{width: 1, height: 1}}
                 />

**Comment by CHaNGeTe** [comment]
Are you using the prop `playInBackground` on purpose?

**Comment by Adamcrg** [comment]
> Are you using the prop `playInBackground` on purpose?

I have the same question asking for help.
I used `playInBackground={false}`
