### ISSUE TITLE
the latest release version is 0.6.1 on 17 Sep 2015, shall we have a new release?

### ISSUE THREAD

**Issue by xing-zheng** [TheWidlarzGroup/react-native-video#161]
@brentvatne @isair

There are very much commits since the last release version, and address many problem in this project, shall we have a new release version and publish to NPM.

Thank you very much!

**Comment by lucasfeliciano** [comment]
:+1: would be awesome

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by larryranches** [comment]
+1 Please update NPM version number, there's new code here that isn't accessible by NPM installs!
