### ISSUE TITLE
instantiating <Video /> breaks the app on ios

### ISSUE THREAD

**Issue by rockwellll** [TheWidlarzGroup/react-native-video#1610]
hello, when i instantiate a <Video /> component, the screen turns black and immediately the system quits the app, only on ios i have this issue

this where i render the <Video /> component: 

`  <View style={{position: "relative"}}>
          <CachedImage  style={{width: "100%", height: "100%" , position: "absolute", }}
        source={{uri: this.props.image.uri}}/>
        <View style={[{opacity, transfrom: [{translateX: "-50%"}, {translateY: "-50%"}] }, styles.loadingIndicator]}>
          <Spinner type="Circle" size={38} color = "#FBC62C" />
          </View>
          <Video   
            source={{ uri: this.state.uri }}
            style={{ width: 200, height: 100 }}
            rate={this.state.rate}
            paused={ this.state.paused} 
            volume={this.state.volume}
            muted={this.state.muted}  
            ignoreSilentSwitch={this.state.ignoreSilentSwitch}
            resizeMode="cover"
            onLoad={this.onLoad}
            onBuffer={this.onBuffer}
            onProgress={this.onProgress}
            onEnd={() => null}
            repeat={true}
          />
        </View>
        </TouchableWithoutFeedback>`

**Comment by jensellfors** [comment]
What is the value of `state.uri` on the inital render? Make sure it's not undefined. Would need to see some more logs to debug this.

**Comment by rockwellll** [comment]
indeed, i was using a method to cached the url by using the convertProxyToUrl it was not working on ios, hence breaking the app
