### ISSUE TITLE
[Question] Is this library maintained?

### ISSUE THREAD

**Issue by canyavall** [TheWidlarzGroup/react-native-video#1615]
I'm a bit worried if this library is being maintained or not... I can see +500 issues and 48 PR... I just would like to know if there will be new releases or not as there are so many PR

If it is not or there's no answer, I'd like to know if someone created a fork and is maintaining it.

Thank you very much ^_^

**Comment by CHaNGeTe** [comment]
IMO it is maintained but not actively maintained.
@cobarx checks the PRs when he has the chance, and I am trying to lend a hand when I can.
