### ISSUE TITLE
Duplicate Headers

### ISSUE THREAD

**Issue by hotdev405** [TheWidlarzGroup/react-native-video#1616]
When header item such as user agent is passed in source prop, it is duplicated.

For example, if user agent is passed as 'xxx', in network call, two user agents are present in header.

One of them is React Native Video/Exoplayer v2.9 and another is XXX

Only the custom set user agent should be present and the default user agent should be overwritten. But this is not happening. Any idea on how to solve this ?
Thanks !

**Comment by CHaNGeTe** [comment]
How can I test that?

**Comment by hotdev405** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/50766870/59306271-32686500-8c9c-11e9-80ae-cd55fe5dc4be.png">

**Comment by hotdev405** [comment]
@CHaNGeTe just pass headers to the source prop to the video component, then analyse the network calls made by the app using traffic capture app, then you can see this

**Comment by hotdev405** [comment]
@CHaNGeTe please help me fix this issue

**Comment by CHaNGeTe** [comment]
@hotdev405 to allow this feature will require some refactoring.
As userAgent is being set here: https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java#L80

**Comment by CHaNGeTe** [comment]
I have no access to my dev env right now, but maybe something like this should work:
```
public static DataSource.Factory getDefaultDataSourceFactory(ReactContext context, DefaultBandwidthMeter bandwidthMeter, Map<String, String> requestHeaders) {
        if (defaultDataSourceFactory == null || (requestHeaders != null && !requestHeaders.isEmpty())) {
            for (Entry<String, String> entry : map.entrySet()) {
                if (entry.getKey().toLowerCase() == USERAGENT_HEADER && !TextUtils.isEmpty(entry.getValue())) {
                    setUserAgent(entry.getValue());
                }
            }
            
            defaultDataSourceFactory = buildDataSourceFactory(context, bandwidthMeter, requestHeaders);
        }
        return defaultDataSourceFactory;
    }
```

**Comment by hotdev405** [comment]
@CHaNGeTe cool thanks for the solution, can you make a pr and merge this in your next release ? that would be really helpful

**Comment by CHaNGeTe** [comment]
Did you have the chance to test it?
