### ISSUE TITLE
Does this lib support set http proxy? 

### ISSUE THREAD

**Issue by SwiftyWang** [TheWidlarzGroup/react-native-video#1619]
My videos only can be played in a specific country. I want to use proxy to let people aren't in that country can play it. Is this possible?

**Comment by CHaNGeTe** [comment]
What do you mean? Proxying the urls to be loaded?

**Comment by SwiftyWang** [comment]
> What do you mean? Proxying the urls to be loaded?

yes, allow to set proxy domain and port? Like some other http client.

**Comment by CHaNGeTe** [comment]
Providing a network proxy is out of scope, but you can load proxied urls.
