### ISSUE TITLE
iOS - Display native player when phone is blocked

### ISSUE THREAD

**Issue by fabiosarcansky** [TheWidlarzGroup/react-native-video#1620]
# iOS: Is there a way to display the native player to play and pause the audio file when the phone is blocked?

Some apps, when they're playing an audio file and the user block the phone or slide down the status bar, display a native player where the user is able to play or pause the audio directly without opening the app.

This is an example of what I'm talking about:
![File (14)](https://user-images.githubusercontent.com/2282184/59395907-c0a42000-8d5c-11e9-80bd-c4241a0a1e4b.jpg)

Is there a way to display it with `react-native-video`?

**Comment by jensellfors** [comment]
This is currently not implemented. You can have a look here for implementation details [Controlling background audio](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/controlling_background_audio).
