### ISSUE TITLE
iOS - Evicted by jetsam due to memory pressure

### ISSUE THREAD

**Issue by paul-doherty** [TheWidlarzGroup/react-native-video#1621]
# Question

Hi,

I was wondering how other people deal with memory usage for the video. I am seeing my app killed by jetsam on iOS due to low memory. Profiling the app shows that while playing a relatively small high quality video the RAM quite easily goes to ~500MB. Given the older iPhones have 1GB of RAM I am not surprised I was evicted.

I saw on Android there is a bufferConfig object which looks perfect for my purposes but I can't see an equivalent on iOS. I (obviously falsely) presumed the player would keep the consumed memory in check by freeing played parts from the RAM.

Can anybody offer any guidance here?
Thanks,
Paul

**Comment by CHaNGeTe** [comment]
I haven't check, currently testing on iPhone 7 and I am not receiving crashes for memory.

Maybe this helps?
https://developer.apple.com/documentation/avfoundation/avplayeritem/1643630-preferredforwardbufferduration?language=objc

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video#maxbitrate

Maybe limiting the bitrate you get the ABR to load smaller resolution chunks and helps memory

**Comment by flexgrip** [comment]
I'm testing this now. This is kind of a deal breaker isn't it? If your users are switching the app to the background, the only thing I can think of would be to try and detect that and dump the bitrate down to the lowest setting?
