### ISSUE TITLE
Why do videos need to be re-buffered after changing the position of the progress bar?

### ISSUE THREAD

**Issue by A-ANing** [TheWidlarzGroup/react-native-video#1630]
Why do videos need to be re-buffered after changing the position of the progress bar?

I want to drag the progress bar to where it has been buffered, and not to re-buffered where it has been buffered. What should I do?

**Comment by jensellfors** [comment]
What platform is this for? It works fine on iOS for me at least. And if thats your case then it's probably an issue with the underlaying native player...

**Comment by jonathangreco** [comment]
@jenshandersson It's on android, using controls set to true, indeed, when we use the slide, the video is re buffed again.

It's not a big deal for local videos, but for streaming :s

**Comment by AE0011** [comment]
I also have this problem on Android. if all video buffered and i seek video a second before, all buffered data will lost
i'm using custom controller

**Comment by CHaNGeTe** [comment]
Which version are you using? Can you try 4.4.4?

**Comment by AE0011** [comment]
@CHaNGeTe 
I'm using last version(4.4.4) 
could problem be from native side?

**Comment by CHaNGeTe** [comment]
Can be a problem of caching strategy. I will try to check

**Comment by liran** [comment]
Is there any progress?

**Comment by A-ANing** [comment]
For example, the current video has one minute. If the video has been buffered to 30 seconds and the current playback position is 20 seconds, if I adjust the playback position to 10 seconds, the 30 seconds previously buffered will disappear, and the video will have to consume the network to load the video again.



## What I want is a result

If the progress is adjusted to the position that has been played, the previously buffered video will not be emptied, so that the network will not be consumed again to load the video

**Comment by A-ANing** [comment]
[This is the video](https://streamja.com/jnod4)

Pay attention to the buffering progress of the video as you look back. @jenshandersson

**Comment by A-ANing** [comment]
我使用`seek()` 调整播放进度

**Comment by androidparth90** [comment]
same issue for me. Has anyone found the solution yet?

**Comment by mohsinulhaq** [comment]
This happens on iOS as well for HLS and CMAF streams alike. I verified by running the stream, thereby downloading the required `.ts/.cmfv` files, turning the internet off, and then rewinding back to the start. The player attempts to download all those files again, thereby showing that there is no caching at all (unlike on the web).

**Comment by A-ANing** [comment]
However, it seems that I haven't found this problem in the latest version（v5.1.1） of Android, and I haven't tried IOS yet; Pull the progress bar to the played position, it will not consume the network to reload and clear the cached part;

Is it because it solves the problem?

**Comment by mohsinulhaq** [comment]
@A-ANing I think it depends on the length of the stream. I have a 20 min 1080p video with an audio bitrate of 128kbps. If I watch it continuously for 10 minutes, pulling all the HLS chunks in, and then go back to the 0 timestamp, it begins downloading again. But if I watch only a few minutes and go back, it doesn't redownload.

**Comment by sagar-simformsolutions** [comment]
> [This is the video](https://streamja.com/jnod4)
> 
> Pay attention to the buffering progress of the video as you look back. @jenshandersson


Hello @A-ANing 

I have seen your reference video, I have noticed that You are using custom controls with preloaded , is this same library ?
as I have to achieve somewhat the same as yours  

- Preloaded buffer 
- Custom controls


Thanks
