### ISSUE TITLE
react-native-web support 

### ISSUE THREAD

**Issue by MwareSolutons** [TheWidlarzGroup/react-native-video#1631]
Hi All,

I was wondering how to get this working with react-native-web does anybody know or has done it ?

**Comment by cobarx** [comment]
The project doesn't currently support react-native-web, you would have to do your own port.

I don't know that there is a lot of value in doing that though. We integrated directly against the html `<video />` element and have been very happy with that. There is a lot of ease in being able to directly register against the `video` events and properties without the abstraction of having to go thru react-native-video.

**Comment by MwareSolutons** [comment]
Thanks for you answer i can surely understand where you are coming from the problem for me is that react-native-dom seems to be in experimental mode and react-native-web is not.

We will try to make out own port

**Comment by CHaNGeTe** [comment]
In theory, via webpack config, you can alias react-native-dom to react-native just for this module, but I have been trying with no luck.

**Comment by jensellfors** [comment]
I would be interested in helping out with a RNW version/port @MwareSolutons

**Comment by BayCo** [comment]
Hey, any updates?
