### ISSUE TITLE
Does this library support for video watermark?

### ISSUE THREAD

**Issue by sharadkatre19** [TheWidlarzGroup/react-native-video#1632]
# Does this library support for video watermark?
I want to add a watermark feature for my app for both image and video. For the image, I am using a react-native-image-marker library, But I want to add water for video also. Please help how to do this or suggest any other library for watermarking in the video.

Thanks.

**Comment by CHaNGeTe** [comment]
This will require video processing, and it is not currently on the roadmap.

If it is enough for you, you can place a floating image over the video.

**Comment by karanpratapsingh** [comment]
@CHaNGeTe how can I add floating image over the video??

**Comment by CHaNGeTe** [comment]
This is pseudo code but:
```
<View style={{position: 'relative', etc etc}}>
     <Video  style={{position: 'absolute', top, left, bottom, right as 0}}.../>
     <Image style={{position: 'absolute', bottom, right as 10 if you want it on the bottom right margin}}.../>
</View>```

**Comment by karanpratapsingh** [comment]
@CHaNGeTe oh, this approach, thanks mate...this'll do is i'm not able to get the native solution working

**Comment by kalyan711987kalyan** [comment]
>      <Image style={{position: 'absolute', bottom, right as 10 if you want it on the bottom right margin}}.../>

How will this work. If I want to upload video to cloud and play on browser

**Comment by CHaNGeTe** [comment]
How is this related to watermark?

**Comment by basemkhirat** [comment]
What about displaying this floating image when the video appeared in full-screen?
