### ISSUE TITLE
Streaming video from G-Drive: "AVFoundationErrorDomain" -11850

### ISSUE THREAD

**Issue by Quach90** [TheWidlarzGroup/react-native-video#1635]
# Question

I am working on an application where I need to play a video in my app that is streamed from Google Drive through a Nodejs app (for authentication).
The video streams perfectly fine into the browser or a HTML video element, but the moment I try it in the app it fails. 
I have tried a lot of different options now without any luck. Sending it in Ranges or the whole thing. I am not able to figure out exactly what is required of the format of the video for this library to work, which is where I am assuming the issue is.

I am getting the following error:

code: -11850
domain: "AVFoundationErrorDomain"

Below is a snippet of the backend where I am loading the video and pipe it through to the app. In the example I have handling for both Range and no Range.

                        
                        var range = request.headers.range;
                        if (!range) {
                            response.writeHead(200, {
                                "Accept-Ranges": "bytes",
                                "Cache-Control": "public, max-age=3600",
                                "Content-Length": file.size,
                                "Content-Type": "video/mp4"
                            });

                            drive.files.get(
                                {
                                    fileId,
                                    alt: "media"
                                },
                                { responseType: "stream" },
                                function(err, res2) {
                                    res2.data
                                        .on("end", () => {
                                            console.log("Done");
                                        })
                                        .on("error", err => {
                                            console.log("Error", err);
                                        })
                                        .pipe(response);
                                }
                            );
                        } else {
                            var positions = range
                                .replace(/bytes=/, "")
                                .split("-");
                            var start = parseInt(positions[0], 10);
                            var total = file.size;
                            var end = positions[1]
                                ? parseInt(positions[1], 10)
                                : total - 1;
                            var chunksize = end - start + 1;

                            response.writeHead(206, {
                                "Content-Range":
                                    "bytes " + start + "-" + end + "/" + total,
                                "Accept-Ranges": "bytes",
                                "Content-Length": chunksize,
                                "Content-Type": "video/mp4"
                            });

                            drive.files.get(
                                {
                                    fileId,
                                    alt: "media",
                                    headers: { Range: `bytes=${start}-${end}` }
                                },
                                { responseType: "stream" },
                                function(err, res2) {
                                    res2.data
                                        .on("end", () => {
                                            console.log("Done");
                                            response.end();
                                        })
                                        .on("error", err => {
                                            console.log("Error", err);
                                        })
                                        .pipe(response);
                                }
                            );
                        }

**Comment by CHaNGeTe** [comment]
Can I get sample project to test it? Is the auth required for videos shared publicly?

**Comment by Quach90** [comment]
> Can I get sample project to test it? Is the auth required for videos shared publicly?

I do not believe that you can connect to google drive without authentication. I can look at setting up an example project if needed, but it would require auth.

**Comment by CHaNGeTe** [comment]
https://stackoverflow.com/a/42244954

**Comment by CHaNGeTe** [comment]
If you are handling cors, maybe you need to add Range to `Access-Control-Allow-Headers` on the server

Have you tested on postman to request bytes 0-2?

**Comment by RomuloDevelop** [comment]
I have a similar problem, i'm getting the following error:

errorException: "None of the available extractors (MatroskaExtracto…avExtractor, AmrExtractor) could read the stream."
errorString: "Unrecognized media format"

I don't want to create a streaming video server when google drive has feature for that. In another issue i read that this library only support media URLs. If the video in google drive is public and any page can consumme it, why react-native-video can't?, is a limitation of the library or is something related with android/ios?

**Comment by CHaNGeTe** [comment]
@RomuloDevelop that's from ExoPlayer right? The original issue is on iOS.

For your case, if you make the source type explicit it may help.
```
source={{
    uri: "your uri here",
    type: 'mp4'
}}
```
