### ISSUE TITLE
Suddenly start displaying a black screen after playing multiple videos (SHOWSTOPPER)

### ISSUE THREAD

**Issue by Balasnest** [TheWidlarzGroup/react-native-video#1636]
# Bug

Suddenly start displaying a black screen for all after playing multiple videos and will never play until the app is reopened again.

## Environment info
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 127.50 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-checkbox: 2.0.0
      react-native-cli: 2.0.1
      react-native-datepicker: 1.6.0
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.1

React native info output:

```bash
 // paste it here
```

Library version: 3.2.1

## Steps To Reproduce

1. Try to play different videos 

2. It will start to display a black screen and will never play until the app is reopened. Whichever video is loaded, it's in the **isBuffering:true** always. There is no error.

```
Debbug output:
1 >>>> === videoURL === <video_url>
2 >>>> === onBuffer === {isBuffering: true}
3 >>>> === onLoadStart ===
After few mins, got this error log:
4 >>>> ===
error:
"": "okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR"
errorString: "Unrecognized media format"
```

What would be the problem?

**Comment by gsunsnackv** [comment]
I have the same problem all the time. The most strange one I experience is https://github.com/react-native-community/react-native-video/issues/1538

My feeling is this project manage the native video player instances very poorly (especially on Android). The project frequently mess things up when you have multiple native video player instances. In our project, we had to do a lot of difficult and hard things to ensure that we only have one instance of a screen that have the <Video> tag, thus only one native video player instance, then it won't stuck.

**Comment by Balasnest** [comment]
It worked for me after upgrading from 3.2.1 to 4.0.1. Not sure in the old version. Thanks @gsunsnackv

**Comment by gsunsnackv** [comment]
@Balasnest I suggest you check carefully, especially on Android 9.0
We are on 4.4.2 and it's just not working

**Comment by Balasnest** [comment]
@gsunsnackv Yes. Tried multiple times playing video. It's coming back to the same issue. 

 **Please look into this priority.**

**Comment by gsunsnackv** [comment]
@Balasnest Don't get your hope up. There are many issues about this problem, I have filed a couple myself. But it go no attention from anyone ever. It's almost like they abandoned this project

**Comment by CHaNGeTe** [comment]
> It worked for me after upgrading from 3.2.1 to 4.0.1. Not sure in the old version. Thanks @gsunsnackv

Was the issue present on 4.0.1?

**Comment by Balasnest** [comment]
@CHaNGeTe Yes. Still and its not working. It looks like everything works at first. If we use for a while will end up with bugs. You can able to reproduce in android 9.0 device.

**ITS A SHOWSTOPPER!!!**

**Comment by CHaNGeTe** [comment]
Can you try on 4.4.4?

**Comment by Kamilsw1** [comment]
I have very similar issue happening on android on 4.4.4

Steps to reproduce:
1. Throttle your internet connection.
2. Try to play 3 different videos. (It will display a black screen)
3. Stop throttling your internet connection.
4. Try playing any video.
5. It will display a black screen and will never play until the app is reopened. Whichever video is loaded, it's in the isBuffering:true always. There is no error. (just like op)

**Comment by paddy57** [comment]
I have flat list , where after each 10th video, i'm adding another 10 videos, and  after more 10 videos i'm getting black screen on them, while audio is playing

I'm using react-native-video@3.0.0 and android player 
Can anyone guilde me through this.
Thank you.

**Comment by chris35469** [comment]
This is an old problem that seems related to how performance is handled on the Android side. Someone previously suggested unmounting off-screen videos to address this. Not sure if it works.   
Duplicate of #1318

**Comment by minhchienwikipedia** [comment]
Any update? I'm getting the same issue with play multiple videos

**Comment by IamMasterWayne** [comment]
+1

**Comment by zchwyng** [comment]
+1

**Comment by jphilipstevens** [comment]
We moved to expo-av and have not had an issue. Given that I believe they both use the same underlying video component on Android I think this is specific to this project.

We also ejected off expo and I'm using rn 0.64 without expokit.

**Comment by zchwyng** [comment]
+1
Tried everything, including switching to Expo-AV, but the problem is still there on both iOS and Android.

**Comment by jphilipstevens** [comment]
@zchwyng what versions of rn, rn video and the overall steps to reproduce? I remember for us we have a screen that users navigate to that shows a single video..this was where we saw most of the issues. Sometimes the issue would show up in our flat list

**Comment by zchwyng** [comment]
> @zchwyng what versions of rn, rn video and the overall steps to reproduce? I remember for us we have a screen that users navigate to that shows a single video..this was where we saw most of the issues. Sometimes the issue would show up in our flat list

React Native 0.64.0, React Native Video 5.1.1, Expo-AV 8.6.0. 

I'm showing videos in a FlatList and autoplaying them with onViewableItemsChanged. Works great until you scroll long enough in the FlatList (usually 20-30 videos, they are each around 1-2 mb, high resolution) and the app crashes. I worked around the problem somewhat by letting people navigate to another screen to view the single video, but eventually, when you have looked at enough videos, the app still crashes. It seems like React Native Video doesn't do garbage collecting correctly...

**Comment by jphilipstevens** [comment]
@zchwyng we had a similar issue. I am not sure that this crash is related to the black screen. The issue may be inside the FlatList more than RN video. I wrote the exact same feature and implemented 2 similar lists, one with FlatList and one with RecyclerListView (https://github.com/Flipkart/recyclerlistview). So far the RLV is handling things better but I am aggressively deallocating elements.

as for the black screen, this seems more in reference to RN video. IIRC when I tested this last year there were some events not firing when the video was supposed to be ready for display. Since then I have made the eng department move to expo-av, upgrade to RN 0.64, and a new design has come in so our app is not in the same position it was when this issue came up

**Comment by zchwyng** [comment]
> @zchwyng we had a similar issue. I am not sure that this crash is related to the black screen. The issue may be inside the FlatList more than RN video. I wrote the exact same feature and implemented 2 similar lists, one with FlatList and one with RecyclerListView (https://github.com/Flipkart/recyclerlistview). So far the RLV is handling things better but I am aggressively deallocating elements.
> 
> as for the black screen, this seems more in reference to RN video. IIRC when I tested this last year there were some events not firing when the video was supposed to be ready for display. Since then I have made the eng department move to expo-av, upgrade to RN 0.64, and a new design has come in so our app is not in the same position it was when this issue came up

Ok. Thanks for your response. I've looked a bit at RecyclerListView, and will make a test with it. I've also tried implementing it with ScrollView and experienced the same problems.

**Comment by zchwyng** [comment]
@jphilipstevens Thanks a lot! RecyclerListView solved my problems. 🙏 I'm using the prop "optimizeForInsertDeleteAnimations" for optimization. What else are you doing to deallocate elements?

**Comment by hueniverse** [comment]
Consolidated into #2668
