### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by zhaoqigang** [TheWidlarzGroup/react-native-video#1637]
# Bug

when i  yarn add react-native-video  and  react-native link  react-native-video  then  react-native run-android     then  it crash  

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gochinatv.optimu/com.gochinatv.optimu.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

then i  add  style  in Androidmanifest     it still crash
 

## Environment info

react-native  0.59  
Xiaomi 6 android8.0 

React native info output:

```bash
 // paste it here
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 517.36 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

Library version: x.x.x

## Steps To Reproduce

Describe what you expected to happen:

1.

2.

**Comment by victorwww** [comment]
Please @zhaoqigang how do you solved. i have the same problem.

**Comment by victorwww** [comment]
I solved my problem run ./gradlew clean in /android.
I wasted time believing that rn-clean-project did this.
now my app is opening.

**Comment by JonathanVeg** [comment]
I got the same bug and the ./gradlew clean solved my problem too. Thanks Victorwww.
