### ISSUE TITLE
Weird black border around the video painting

### ISSUE THREAD

**Issue by silenaker** [TheWidlarzGroup/react-native-video#1638]
There was a same issue but was closed. #1483

### Current behavior
There was a weird black border around the video painting, and I could not eliminate the black border by whatever means I had used.

### Reproduction steps
1. use `react-native init AwesomeProject` to initiate a simple demo react native app.
2. use `react-native install react-native-video` to install and link react-native-video.
3. copy the `App.js` code from here:
```javascript
import React, { Component } from "react";
import { View } from "react-native";
import Video from "react-native-video";

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Video
          style={{
            width: 300,
            height: 200
          }}
          resizeMode="cover"
          source={require("./demo.mp4")}
          repeat
        />
      </View>
    );
  }
}
```
4. download [sample videos](https://sample-videos.com/index.php) here.
5. plug-in your iPhone 6/7/8 Plus device on your Mac.
6. use `react-native run-ios --device` command to run demo app on the device (make sure you have followed the react native official instructions for [running-on-device](https://facebook.github.io/react-native/docs/running-on-device)).

### Expected behavior
There is no weird black border

### Platform
* device: iPhone 6/7/8 Plus (12.3.2)
* react-native: 0.59.9
* react-native-video: ^4.4.2
* xcode: 10.2.1
* Mac: 10.14.3

**Comment by juliafriberg** [comment]
@silenaker Is this still an issue for you or have you found a solution for it? I'm experiencing it as well.

**Comment by kdmldev** [comment]
same issue here

**Comment by npicouet** [comment]
Same issue here. Reproduced on iPhone 6s Plus.

**Comment by vishalsiddhi** [comment]
Anybody solved this issue? I am facing same issue.

**Comment by asafda** [comment]
Same here
Using react-native-video 5.0.2 and react-native 0.61.5
For us it happens on some Android devices such as Pixel 3 and Pixel 4 XL

**Comment by wannesco** [comment]
For us it seems to be fixed by adding the following css to the container of the video.

```
shadow-opacity: 1;
shadow-color: white;
```

**Comment by adamkoch** [comment]
Does anyone have any tips for addressing this? Or have any ideas on what is causing it? Ran into myself and not sure where to  start looking. I tried @wannesco's suggestion but that didn't seem to help.

**Comment by wannesco** [comment]
To avoid this issue I was thinking to add an inner border for the container that contains the video so the black border would be hidden below the parent border. After some css changes it worked for me like I posted before.
Maybe try doing something similar? Good luck.

**Comment by adamkoch** [comment]
Thanks for the reply. I actually re-read the issue here and it might not be what I'm seeing. If it's an actual pure black border I can fix that without issue. I am seeing a very faint (hard to see) black background around my videos on iOS devices only. Might be a different issue. Not sure if anyone cc'd here has a screenshot to share of what they are seeing.

**Comment by BeKnowDo** [comment]
This is definitely caused by an aspect ratio issue - not sure exactly how to solve for it...

**Comment by semiherdogan** [comment]
I added bottom border (like below). Seems like solved this for me.

```
borderBottomWidth: 1,
borderBottomColor: 'transparent',
```

Edit:

borderBottom solved iphone7 but 7+ still shows that border.

Thank you @wannesco, given shadow to container view saved me.

```
shadowOpacity: 1,
shadowColor: '#fff',
```

**Comment by gignupg** [comment]
Is there still no solution to this? I'm facing the same issue on Android.

**Comment by FrederickEngelhardt** [comment]
Yeah those other items look like workaround that do not remove the outline but cover it with a color.

Expected:
- The video should have no outline and the only colors should come from video source
- `shadow` solutions require knowledge of the wrapped container `backgroundColor` to blend the video. This seems less scalable and prone to issue with larger design systems. Those teams would need to pass in a variable for the shadow color to allow for the container to blend into other background colors.

**Comment by Mindgames55** [comment]
> Is there still no solution to this? I'm facing the same issue on Android.

it seems the workaround above got merged for IOS but box-shadow doesn't work for Android , any updates for Android here ?

**Comment by chef-de-poste** [comment]
Change resizeMode="contain" to resizeMode="cover"

**Comment by Mindgames55** [comment]
> Change resizeMode="contain" to resizeMode="cover"

that's ultimately what I did but that results in a not-ideal scaling. I guess I can change the video asset itself but not a scalable solution
