### ISSUE TITLE
Unable to change continuous frame change by seeking

### ISSUE THREAD

**Issue by Neha0595** [TheWidlarzGroup/react-native-video#1644]
# Question
I use react-native-video component to make video Editing tool - cover selection like instagram.And I want to change frame continuously on dragging cover handle.For this I used gesture handler Pan Gesture and its onPanGestureEvent listener I use Seek method to continuously change frame on seeking.

But behaviour is not intuitive.It change frame when gesture handler END state reached.

My code is: 
```
this.postCoverGestureListener = () => {
      this.foxyVideo.current.getNode().seek(this.videoSeeker.__getValue());
    };
    this.onPostCoverGestureEvent = Animated.event(
      [
        {
          nativeEvent: {
            x: this.postCoverAnimatedPosition,
          },
        },
      ],
      {
        listener: this.postCoverGestureListener,
      },
    );

```
And the Video Component is : 
`const AnimatedVideo = Animated.createAnimatedComponent(AnimatedVideo)`
`<AnimatedVideo
        ref={this.foxyVideo}
        repeat={videoRepeat}
        source={{ uri: props.currentContentItem.uri }}
        paused={props.pauseVideo}
        resizeMode="cover"
        style={{ flex: 1 }}
        rate={props.currentContentSpeedParams.videoRate}
        onEnd={props.videoEditingInitiate ? () => {} : this.onVideoEnd}
        onProgress={props.currentVideoAction === 'Trim' ? this.onProgress : () => {}}
      />`

**Comment by CHaNGeTe** [comment]
Are you implementing `onPanHandlerStateChange` as well?

**Comment by Neha0595** [comment]
yes

**Comment by Neha0595** [comment]
Here is my Code snippet:

`videoSplitBar = props => (
    <PanGestureHandler onGestureEvent={props.currentContentSplitParams.onSplitBarGestureEvent} onHandlerStateChange={this.onSplitHandlerStateChange(props.currentContentSplitParams.splitBar)}>
      <Animated.View style={[styles.videoSplitBar, { left: props.currentContentSplitParams.splitBar }]}>
        <FoxyIcon
          icon={images.previewScreenIcons.trimSelect}
          height={36}
          width={20}
          backgroundColor="white"
          borderRadius={4}
          tintColor="black"
        />
      </Animated.View>
    </PanGestureHandler>
  );`

On the panning of this split bar I want to change video frame frame.Is onHandlerStateChange generate this error
