### ISSUE TITLE
Particular audio stream not working on Android

### ISSUE THREAD

**Issue by Nikooos** [TheWidlarzGroup/react-native-video#1648]
# Question

I am creating a simple radio streaming app with only a play and pause button to play a streaming url. React-native-video seemed the best way to go, and it is working for most streams I can find, but of course the particular stream I use doesn't work. On Android that is. On iOS it is working like it should.

I have 4 urls for this one stream, but none of them are working. 

http://www.goedkoopstreamen.nl/luister/klmopen/mp3/
http://www.goedkoopstreamen.nl/luister/klmopen/pls/
http://www.goedkoopstreamen.nl/luister/klmopen/wm/
http://www.goedkoopstreamen.nl/luister/klmopen/real/
http://www.goedkoopstreamen.nl/luister/klmopen/ipad/

This is just about all of my code. The commented uri-s are the ones that are working, but the uncommented doesn't. Is it just a falty stream or are there any other things I could try?

<Video source={{
          uri: "http://klmopen.gkstreamen.nl/listen.pls",
          //uri: "http://icecast.omroep.nl/radio1-bb-mp3",
          }} 
          ref={component => (this._video = component)}
          paused={this.state.paused}
          playInBackground={true}
          onBuffer={this.onBuffer}                // Callback when remote video is buffering
          onError={this.videoError}               // Callback when video cannot be loaded
          style={styles.backgroundVideo} />

**Comment by CHaNGeTe** [comment]
hello @Nikooos ,
sometimes it helps (when no extension present) to provide explicitly a mimetype, specially for android.

Can you try setting source object like this?
source={{uri: "http://www.goedkoopstreamen.nl/luister/klmopen/mp3/", type: "m3u8"}}

**Comment by Nikooos** [comment]
Sounded pretty good.. Unfortunately didn't get my stream up and going.

I'm getting the following error:
2019-07-05 09:15:16.916 29643-29855/com.klmopenradio E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:619)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:500)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:425)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:450)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

Seems to be troubles with the exoplayer?

**Comment by CHaNGeTe** [comment]
I dunno if I should have access to the resource, or it is private, but...
http://www.goedkoopstreamen.nl/luister/klmopen/mp3/
return a m3u8 playlist
```
#EXTM3U
#EXTINF:0, klmopen
http://klmopen.gkstreamen.nl:80
```
That points to `http://klmopen.gkstreamen.nl:80` which seems it is not responding.

**Comment by Nikooos** [comment]
It's not private, so no problem. 

I've been complaining about the resource but they don't seem to be able to change anything to make my life easier about this. 
However it does work when I just tap the link and open it in my browser. So that's their argument that there's nothing wrong with the stream. So I'm about to give up on this.

http://klmopen.gkstreamen.nl:80 is working in iTunes though.. It's starting to drive me crazy.

**Comment by CHaNGeTe** [comment]
Yep, they seem to handle redirects in a kinda tricky way.
They allow you to change the streaming port? I think 80 is maybe interfering

**Comment by kgrajan12** [comment]
I'm getting like

> This device does not provide audio/ac3 codec
