### ISSUE TITLE
Refresh the data source multiple times.the video player on Android will get stuck in an infinite buffering state

### ISSUE THREAD

**Issue by ryanypm** [TheWidlarzGroup/react-native-video#1649]
# Bug

  I have a FlatList. A player will be displayed when scrolling stops. But after multiple times of hidden display, the video player will be in an infinite buffer state. You need to restart the app to continue playing.

Library version: 4.4.2

## Steps To Reproduce

1. Create a FlatList. Item full screen. There is a video on each item(Not displayed by default).
2. When the scroll bar stops, calculate the video you want to display and play it.
3. Repeat step 2 to reproduce
...

Describe what you expected to happen:

I expect the video to not get stuck.

## Other

This problem has been around for a while, and I hope to get a solution as soon as possible because it is very serious!

The following is a solution for others, except that you can't set a cookie, everything else works fine.
```
DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory(getUserAgent(context));

// This is the cache I added, please ignore it.
LeastRecentlyUsedCacheEvictor usedCache = new LeastRecentlyUsedCacheEvictor(300 * 1024 * 1024);
SimpleCache simpleCache = new SimpleCache(new File(context.getCacheDir(), "shm.video.key"), usedCache);

if (requestHeaders != null) {
	factory.getDefaultRequestProperties().set(requestHeaders);
}
return new CacheDataSourceFactory(simpleCache, factory);
```

**Comment by Balasnest** [comment]
#

**Comment by Balasnest** [comment]
Most of the issue has the same problem
#1538
#1636

@ryanypm can you try with this #1655. New PR has been raised for this. Let me know once tested from this PR.

**Comment by CHaNGeTe** [comment]
Yes, feedback on that PR https://github.com/react-native-community/react-native-video/pull/1655 will be much appreaciated

**Comment by ryanypm** [comment]
RP #1655 solved.
