### ISSUE TITLE
Can this lib play AES 128 encrypted M3U8 generated by FFMPEG  ?

### ISSUE THREAD

**Issue by abdullahoday710** [TheWidlarzGroup/react-native-video#1651]

**Comment by CHaNGeTe** [comment]
Which encryption are you using?

**Comment by abdullahoday710** [comment]
> 
> 
> Which encryption are you using?

ffmpeg default AES 128 bit

**Comment by CHaNGeTe** [comment]
Do you need Authorization flow?
A sample stream will be cool to test
Are you targeting ios or android or both?

**Comment by abdullahoday710** [comment]
> 
> 
> Do you need Authorization flow?
> A sample stream will be cool to test
> Are you targeting ios or android or both?

Yeah I'm targeting both platforms and what i need is to pass the decryption key which is hard coded in my program to the video element.

**Comment by CHaNGeTe** [comment]
AES 128 works both for Android / iOS.
you can test with this stream:
https://www.radiantmediaplayer.com/media/rmp-segment/bbb-abr-aes/playlist.m3u8

**Comment by CHaNGeTe** [comment]
chunk manifests come with encryption and key is provided by URL to relative path
```
#EXT-X-KEY:METHOD=AES-128,URI="file.key",IV=0x9256b016abc7ad3deaef1f093be826d3
```

**Comment by abdullahoday710** [comment]
> 
> 
> chunk manifests come with encryption and key is provided by URL to relative path
> 
> ```
> #EXT-X-KEY:METHOD=AES-128,URI="file.key",IV=0x9256b016abc7ad3deaef1f093be826d3
> ```

does this URI scheme work ? #EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,XXXXXX",

**Comment by hnrqsss** [comment]
Using the url works for me, but using a local file doens't work.

**Comment by abdullahoday710** [comment]
> 
> 
> but using a local file doens't work.

the .m3u8 file and the key file has to be in the same directory.

**Comment by hnrqsss** [comment]
Thanks, its work

**Comment by JowelTisso** [comment]
@vertexpotato @hnrqsss Hello, Can you help me with the issue... By providing a working code of how you did it...? Please do if you can, would be really helpful.

**Comment by JowelTisso** [comment]
I am able to play m3u8 with .ts files locally... But would like to mention that it can only be played when i used the exoplayer...Hope it helps...

**Comment by Arise-cn** [comment]
how to play this?
