### ISSUE TITLE
rnpm & AndroidX for next release

### ISSUE THREAD

**Issue by Shanie1331** [TheWidlarzGroup/react-native-video#1656]
# Requesting update for next releases.

The packages use deprecated "rnpm" config that will stop working from next release of React-native. Please give a release update for the same.
React-Native 6.0 have some breathtaking changes like:
1. completely removing "rnpm" in next release.

<img width="709" alt="Screen Shot 2019-07-08 at 12 48 56 AM" src="https://user-images.githubusercontent.com/27643210/60772885-4461ea00-a11a-11e9-8288-b9613adb634c.png">

2. AndroidX migration for mantained support lib version. All the support libs are updated to jetpack AndroidX. you can check these changes [here](https://developer.android.com/jetpack/androidx/migrate).

These changes seems mandatory and I will be great if I can help you on same.

**Comment by CHaNGeTe** [comment]
We are preparing for the upgrade:
https://github.com/react-native-community/react-native-video/issues/1656

But always, help is welcomed!

**Comment by CHaNGeTe** [comment]
@Shanie1331 your feedback on that PR will be much appreciated. Specially about the rnpm part.

**Comment by kpratik2015** [comment]
Add this to app/build.gradle and it might work

`preBuild.doFirst {
        ant.replaceregexp(match:'android.support.v4.content.', replace:'androidx.core.content.', flags:'g', byline:true) {
            fileset(dir: '../../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer', includes: '*.java')
        }
        ant.replaceregexp(match:'android.support.annotation.', replace:'androidx.annotation.', flags:'g', byline:true) {
            fileset(dir: '../../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer', includes: '*.java')
        }
}`

**Comment by tslater** [comment]
The above link is just linking to this issue. Here is the PR (as far as I can tell) for reference:
https://github.com/react-native-community/react-native-video/pull/1626

**Comment by CHaNGeTe** [comment]
Sorry for that, yes, I meant this PR https://github.com/react-native-community/react-native-video/pull/1626
