### ISSUE TITLE
disableFocus and onAudioFocusChanged don't work 

### ISSUE THREAD

**Issue by gazedash** [TheWidlarzGroup/react-native-video#1657]
# Bug

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 45.70 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.9 
```

Library version: 4.4.2, 4.4.3 and previous versions 

## Steps To Reproduce

1. Add 
```
onAudioFocusChanged = (event) => {
    this.setState({ paused: !event.hasAudioFocus })
    this.props.onAudioFocusChanged(event)
  }

onAudioFocusChanged={this.onAudioFocusChanged}
```

or `disableFocus={true}`
2. Make a call to the phone on which the app is working

Describe what you expected to happen:

1. Playback stops when call happens

It works only when headphones are connected

**Comment by CHaNGeTe** [comment]
This props are not documented AFAIK, but will take a look.
Is that on Android or iOS?

**Comment by CHaNGeTe** [comment]
Please test on this PR, it is still not released: https://github.com/react-native-community/react-native-video/tree/release/4.4.3

**Comment by gazedash** [comment]
@CHaNGeTe I tried it, still didn't help. But thanks

**Comment by gazedash** [comment]
@CHaNGeTe 

I discovered that when I plug my headphones, make a call to my phone, onaudiofocuschange gets called and everything works. But if i don't use headphones and listen through speakers instead, onaudiofocuschange doesn't get called. It's an important issue.
