### ISSUE TITLE
How to save a video from hls?

### ISSUE THREAD

**Issue by cokealmonacid** [TheWidlarzGroup/react-native-video#1658]
# Question

At present im using react-native-video for show a streaming video from a raspberry (like a security camera) the idea behind this, is that the user can start and stop recording a video from the stream (hls / m3u8 uri file) and save it on the phone. There is any possible way to do this with react-native-video? any suggestions?

**Comment by CHaNGeTe** [comment]
Right now the feature is not present.
Only HTTP streams in MP4 format are allowed to be saved on device (via `save` function)

I am planning to extend this to HLS, but with a totally different purpose (Offline playback).
But my plan is to store the full video, not in an interactive way (start recording, end recording)

Maybe this helps:
https://github.com/react-native-community/react-native-video/blob/master/ios/VideoCaching/RCTVideoCache.m

But I am not sure

**Comment by CHaNGeTe** [comment]
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html

**Comment by cokealmonacid** [comment]
thanks for your time @CHaNGeTe !

**Comment by ghost** [comment]
when are you going to add offline playback feature?

**Comment by CHaNGeTe** [comment]
I have it working via external lib on my company, but will require heavy refactor to be integrated here.
First we are aiming to stabilize the project issues before releasing new features

**Comment by snoopytimes** [comment]
@CHaNGeTe Is there any update to adding offline playback?  I am specifically looking to be able to use the built it offline capabilities from ExoPlayer and AVPlayer

**Comment by AnassHmida** [comment]
@snoopytimes Any progress on this ?

**Comment by safwenbelkassem** [comment]
@AnassHmida  Nothing bro

**Comment by salatielsql** [comment]
> I have it working via external lib on my company, but will require heavy refactor to be integrated here.
> First we are aiming to stabilize the project issues before releasing new features

Hello, can you share the name of the external lib?

**Comment by glrahulborah** [comment]
Any update on this? I am also looking for offline playback of hls videos.

**Comment by ArieBen** [comment]
is there any buffer we can tap into to get the fragment? 
Like hls.js has a BUFFER_APPENDING event from which we can extract the current fragment....
I'm desperately looking for a solution in React Native...

**Comment by samandarkuchkarov** [comment]
Any update?

**Comment by KrzysztofMoch** [comment]
This can't be done via `react-native-video` - you have to manually download video and then pass path to it into player

**Comment by moskalakamil** [comment]
Hey all!
We've recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=1658) that lets you download and play video content offline - including DRM-protected streams. 
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=1658)
