### ISSUE TITLE
How to get playable duration when the video is paused

### ISSUE THREAD

**Issue by FahadRS** [TheWidlarzGroup/react-native-video#1661]
Right now OnProgress event is fired when video is playing so i am able to get the playable duration, but this event is not triggered when the video is paused.

I just wanted to know is there any way i can get the playable duration when the video is paused

I know this question is already been asked more than one time, but none of them gives the answer or i am not able to understand 
Similar questions to this

https://github.com/react-native-community/react-native-video/issues/1504
https://github.com/react-native-community/react-native-video/issues/273
https://github.com/react-native-community/react-native-video/issues/1179

I have also asked this question on SO but did not received any answer from there also

https://stackoverflow.com/questions/56947252/how-to-get-the-playable-duration-in-react-native-video-when-the-video-is-paused

**Comment by Bayramito** [comment]
did you find any solution for this ?

**Comment by freeboub** [comment]
@Bayramito the onProgress callback shall be called in pause mode now (on V6.0.0-alpha)
