### ISSUE TITLE
Video failing to load and play on android (ERROR: Unable to instantiate decoder OMX.qcom.video.decoder.avc)

### ISSUE THREAD

**Issue by OmarBasem** [TheWidlarzGroup/react-native-video#1664]
# Bug

Video fails to load and play on android (physical device) about 50% of the times. It happens at random. For example a screen with 5 videos, it loads and play. Then I refresh the bundle, it does not load any of the videos, or sometimes just load one video. The videos that do not load just shows a black screen. Also sometimes the video loads on a screen then, if i try to open that same video in another screen (or modal) it does not load and play, although it is cached (same behaviour happens without caching, also even if the video is local). onLoadStart get called, but onLoad does not get called. It is working perfectly on iOS. This behaviour happens on android in all sceanarios: in debug mode and with out it, and release build and dev build. 
## Environment info

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 186.69 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.9 
      react-native-video: 4.4.3
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

Create a FlatList with few videos, you will notice the videos won't always load. Also have an option where you click on a button to open another screen with a horizontal list of the same videos, a lot of times they play on the main screen, but does not play on the horizontal screen, (or even modal)

Describe what you expected to happen:

Videos to always load.

**Comment by OmarBasem** [comment]
I have been trying to debug for several days without any success, please if someone knows what could be the problem help me!

**Comment by OmarBasem** [comment]
I tried using onError and it throw this error object: 
error:
errorException: "com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])"
errorString: "Unable to instantiate decoder OMX.qcom.video.decoder.avc"

Why is this happening? It happens for both local and remote uri.

**Comment by CHaNGeTe** [comment]
Can you try with 4.4.4 release? It has some fixes for exoplayer.
Specially for situations where are more than one instance of the component (FlatLists, ...)

**Comment by OmarBasem** [comment]
@CHaNGeTe same problem still there. The problem is that when rendering  a video component, the decoder has to be released before a new one is initialized, which seems to be react-native-video not doing on android, hence this error:  "Unable to instantiate decoder OMX.qcom.video.decoder.avc".

**Comment by CHaNGeTe** [comment]
We are calling Exoplayer.release. But I will try to check

**Comment by nathantqn** [comment]
Hi @CHaNGeTe, I had the same problem with @ramon90 in my production app. The users randomly get video playback error. This is the summary after I investigated this error on Sentry so far:

**I have a carousel to show multiple videos, it will get the decode error after I play concurrently 6 videos (It's okay to play concurrently 5 videos)**

**Unable to instantiate decoder OMX.qcom.video.decoder.avc**
Happened on several phone models:
SM-A500FU
SM-T387V (M1AJQ)
SM-A500FU (MMB29M)
SM-T387V (M1AJQ)

**Unable to instantiate decoder OMX.Exynos.avc.dec**
Happened on
SM-A310F (NRD90M)

**Unable to connect to (Fragment of HLS video) (Unrecognized media format)**
Redmi Note 4 (NRD90M)
Android 9

**Comment by ReneMarquez** [comment]
same issue here, sometimes the videos load correctly, if not it just shows a black screen
on iOS everything works correctly
just fyi, I'm in the latest version 4.4.4

**Comment by ghost** [comment]
happens to me too, can someone help to fix this?

**Comment by ghost** [comment]
I am able to reproduce the issue by going back to the previous screen and return to video screen again.

**Comment by OmarBasem** [comment]
@robert589 to avoid this issue, only render one video component at a time. If there is more than one video on a screen, just render a thumbnail image.

**Comment by ReneMarquez** [comment]
> @robert589 to avoid this issue, only render one video component at a time. If there is more than one video on a screen, just render a thumbnail image.

yeah, this is what I ended up doing on Android, seems like the library is not ready for multiple video components in the same scene

**Comment by sauravexodus** [comment]
How do you release the existing Exoplayer instance?

**Comment by asimwadood** [comment]
> Can you try with 4.4.4 release? It has some fixes for exoplayer.
> Specially for situations where are more than one instance of the component (FlatLists, ...)

the problem will be resolved if you used removeClippedSubviews props of flatlist.

**Comment by asimwadood** [comment]
> # Bug
> Video fails to load and play on android (physical device) about 50% of the times. It happens at random. For example a screen with 5 videos, it loads and play. Then I refresh the bundle, it does not load any of the videos, or sometimes just load one video. The videos that do not load just shows a black screen. Also sometimes the video loads on a screen then, if i try to open that same video in another screen (or modal) it does not load and play, although it is cached (same behaviour happens without caching, also even if the video is local). onLoadStart get called, but onLoad does not get called. It is working perfectly on iOS. This behaviour happens on android in all sceanarios: in debug mode and with out it, and release build and dev build.
> 
> ## Environment info
> React Native Environment Info:
> System:
> OS: macOS 10.14.4
> CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> Memory: 186.69 MB / 16.00 GB
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 10.16.0 - /usr/local/bin/node
> Yarn: 1.16.0 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> iOS SDK:
> Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
> Android SDK:
> API Levels: 23, 25, 26, 27, 28
> Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
> System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
> IDEs:
> Android Studio: 3.4 AI-183.6156.11.34.5522156
> Xcode: 10.2/10E125 - /usr/bin/xcodebuild
> npmPackages:
> react: 16.8.3 => 16.8.3
> react-native: ^0.59.9 => 0.59.9
> react-native-video: 4.4.3
> npmGlobalPackages:
> react-native-cli: 2.0.1
> 
> ## Steps To Reproduce
> Create a FlatList with few videos, you will notice the videos won't always load. Also have an option where you click on a button to open another screen with a horizontal list of the same videos, a lot of times they play on the main screen, but does not play on the horizontal screen, (or even modal)
> 
> Describe what you expected to happen:
> 
> Videos to always load.

the problem will be resolved if you used removeClippedSubviews props of flatlist.

**Comment by ghost** [comment]
This issue isn't resolved it seems.

When having multiple videos in flatlist and autoplaying when they come in view, after a few videos the error occurs. I have attached the screenshot for the reference.

PS: I am on the latest react-native-video version and using exoplayer

![Screenshot 2020-04-20 at 8 14 35 AM](https://user-images.githubusercontent.com/37217713/79709207-36fba200-82df-11ea-8432-879aef11a535.png)

**Comment by kartavyaparekh96** [comment]
@crushy26 have you find any solution?

**Comment by caijiami** [comment]
Is there a solution? And the network path will slow the video load by a few seconds

**Comment by victoriaSh** [comment]
Have somebody found a solution? 
I have the similar issue on Xiaomi Poco M3. Sometimes video works, sometimes there is a black screen or error "Decoder init failed". On the old Nexus 5 (only -19 error sometimes) and iOS everything is working fine.
I don't have a FlatList. Just a component with Video which gets its source from props:

`<LetterVideo card={cards[data.cardNum]} navigation={this.props.navigation} 
                    prev={()=>{this._prevCard()}} next={()=>{this._nextCard()}} />`
_prevCard and _nextCard are changing cardNum.

And inside LetterVideo.js:
`<Video source={{uri: "https://mydomain.com"+card.video.video}}
            rate={1.0}
            ref={videoEl}
            volume={1.0}
            muted={true}
            paused={paused}
            repeat={repeat}
            resizeMode={"cover"}
            playWhenInactive={false}
            onLoad={(data)=>{_updateProgressBar(data)}}
            onEnd={(e)=>{_autoNextCard()}}
            onError={(e)=>{ 
                    console.log("video error", e);
                    if (e.error && e.error.extra == -19){
                        console.log("media player error", e);
                    } else {
                        setReloadOpened(true)
                    }
            }}
            style={styles.video} />`

**Comment by Murugeshrockey-RN** [comment]
Still the issue is not resolved

**Comment by jfbn** [comment]
This just happened for the first time for me, after having used the library for ~6 months.

**Comment by siddharthkr** [comment]
Can someone please provide any solution for this problem ?

**Comment by liquidvisual** [comment]
> @robert589 to avoid this issue, only render one video component at a time. If there is more than one video on a screen, just render a thumbnail image.

What method/library are you using to determine the video currently in view? I've been down a rabbit hole this past week trying to find something non-buggy / maintained that acts as a visibility sensor for RN. There's not a whole lot out there - I've settled on [InViewPort](https://github.com/CoffeeBeansLabs/react-native-inviewport#readme) but it's also a bit of a nightmare.

**Comment by ShakeelAhmad-dev** [comment]
any solution ? 
when rendering video list in flatlist ....

**Comment by ghost** [comment]
Render one video in a view at a time. Use item visible prop from flatlist

**Comment by ShakeelAhmad-dev** [comment]
@crushy26  can you share any example code ?

**Comment by yosukapr0** [comment]
Anyone get the solution? I face this issue after 1 month use this library. I'm using `react-native-fs` to download the video file and play it using ViewPort in flatlist. It working normally before but now I get the bug!

**Comment by mizefsl** [comment]
Any solution to this? I keep getting the same error from times to times.

**Comment by Murugeshrockey-RN** [comment]
I solved this issue by using the **expo-av https://docs.expo.dev/versions/latest/sdk/av/ library.** Please avoid this react-native video. expo-av has lots of video options and I didn't face that Unable to instantiate decoder issue in expo-av.

Note: Before installing **expo-av**, we need to install **react -native unimodules**  first(https://docs.expo.dev/bare/installing-unimodules/) **library**

**Comment by brunolcarlos** [comment]
Same issue 
https://github.com/expo/expo/issues/16403

**Comment by brunolcarlos** [comment]
> I solved this issue by using the **expo-av https://docs.expo.dev/versions/latest/sdk/av/ library.** Please avoid this react-native video. expo-av has lots of video options and I didn't face that Unable to instantiate decoder issue in expo-av.
> 
> Note: Before installing **expo-av**, we need to install **react -native unimodules** first(https://docs.expo.dev/bare/installing-unimodules/) **library**

I have the issue and I'm using the latest version

**Comment by sarevok89** [comment]
Yes, we struggle with the same issue and can't find any solution. We have about 30 videos with auto-play in a FlatList.

**Comment by ravivarmatadi** [comment]
> This issue isn't resolved it seems.
> 
> When having multiple videos in flatlist and autoplaying when they come in view, after a few videos the error occurs. I have attached the screenshot for the reference.
> 
> PS: I am on the latest react-native-video version and using exoplayer
> 
> ![Screenshot 2020-04-20 at 8 14 35 AM](https://user-images.githubusercontent.com/37217713/79709207-36fba200-82df-11ea-8432-879aef11a535.png)

Me also getting same issue

**Comment by abdoerrahiem** [comment]
any solution?? I got the same error when using flatlist

**Comment by qhoarau** [comment]
I got the same issue, is there any solution ?

**Comment by rohitsingh2410** [comment]
Any update on this ? i am still getting error
![image](https://user-images.githubusercontent.com/17305828/187703203-8455b627-527b-44f8-870c-e6aab01491c7.png)

**Comment by rohitsingh2410** [comment]
> Any solution to this? I keep getting the same error from times to times.

DId you found any solution?

**Comment by rohitsingh2410** [comment]
> How do you release the existing Exoplayer instance?

DId you found any solution?

**Comment by rohitsingh2410** [comment]
> I have been trying to debug for several days without any success, please if someone knows what could be the problem help me!

DId you found any solution?

**Comment by mikealche** [comment]
Same here! It's impossible to load videos inside a FlatList

**Comment by Takesizmail** [comment]
+ 1

**Comment by coucoseth** [comment]
I have the same issue, i am loading one video in my component.
Why is the issue closed without a solution?
Anyone fix it yet?

**Comment by OmarBasem** [comment]
Here is the solution: https://github.com/google/ExoPlayer/issues/6168#issuecomment-1447753880

**Comment by manjunath-nuveb** [comment]
@OmarBasem   I have a single video component. This issue persists when I navigate between screens or when I put the app in the background and then bring it back to the foreground.

**Comment by anasvemmully** [comment]
+1, Me too facing the problem, this should be fixed asap!
normal videos are working fine but this problem shows while playing drm videos

**Comment by arnavr15** [comment]
For RN, I changed the `build.gradle` inside `android` to below, now it seems to work fine:

> buildscript {
>     ext {
>         buildToolsVersion = "33.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 33
>         targetSdkVersion = 33
>         ndkVersion =  "23.1.7779620"
>         kotlinVersion = "1.8.0"
>     }
>     repositories {
>         google()
>         mavenCentral()
>         maven { url 'https://maven.google.com' }
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:7.3.1")
>         classpath("com.facebook.react:react-native-gradle-plugin")
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
>         classpath 'com.google.gms:google-services:4.3.15'
>     }
> }
> 
> apply plugin: "com.facebook.react.rootproject"

**Comment by willerrodrigo** [comment]
> For RN, I changed the `build.gradle` inside `android` to below, now it seems to work fine:
> 
> > buildscript {
> > ext {
> > buildToolsVersion = "33.0.0"
> > minSdkVersion = 21
> > compileSdkVersion = 33
> > targetSdkVersion = 33
> > ndkVersion =  "23.1.7779620"
> > kotlinVersion = "1.8.0"
> > }
> > repositories {
> > google()
> > mavenCentral()
> > maven { url 'https://maven.google.com' }
> > }
> > dependencies {
> > classpath("com.android.tools.build:gradle:7.3.1")
> > classpath("com.facebook.react:react-native-gradle-plugin")
> > classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
> > classpath 'com.google.gms:google-services:4.3.15'
> > }
> > }
> > apply plugin: "com.facebook.react.rootproject"

@arnavr15 what did you change exactly?

**Comment by rimohi345-oss** [comment]
Any update on this issue?
