### ISSUE TITLE
New props to disable full screen on iOS

### ISSUE THREAD

**Issue by jonathangreco** [TheWidlarzGroup/react-native-video#1665]
# Feature Request
Since the fullscreen mode on iOS is not yet able to be fixed, we must add a new props to disable the fullscren when controls is true.

## Why it is needed
This is a must have since fullscreen give a bad user experience. In the meantime, fullscreen can be fixed

For further information see #1319

**Comment by jonathangreco** [comment]
@cobarx @CHaNGeTe @johanneslumpe @ashnfb Someone is interested to take this one ?

**Comment by CHaNGeTe** [comment]
Can you check if callbacks are called properly on this PR?
https://github.com/react-native-community/react-native-video/pull/1669

**Comment by jonathangreco** [comment]
@CHaNGeTe I don't understand why I have to check this. And what is the relation between your PR and my feature request ?

You may not understand what I'm asking here : 

Since the fullscreen mode broke the layout as said here #1319, here #1645 and  here #1441 I ask for a NEW PROPS that does not exist yet to disable the fullscreen button on IOS.

**Comment by jonathangreco** [comment]
@ashnfb @CHaNGeTe @cobarx Is this feature can be handled ?

**Comment by jonathangreco** [comment]
@ashnfb @CHaNGeTe @cobarx ping ping ping

**Comment by jonathangreco** [comment]
@ashnfb @CHaNGeTe @cobarx I am increasingly wondering what I need to do to see this problem solved. I am more likely to be struck by lightning than to see a property disabling fullscreen button on iOS when controls = true.

Seriously I feel bad about this.

**Comment by ashnfb** [comment]
Jonathon, we are volunteers, without any compensation, and with full time jobs elsewhere.

The best way to see this done is to create a PR that implements the feature - yourself. Honestly it isn't that hard to open xcode up and see if you can.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jonathangreco** [comment]
@ashnfb You've right , i'm done.

**Comment by jonathangreco** [comment]
@ashnfb 
After a good night here I am again, yesterday was a bad day, sorry. I fully understand that contributors and maintainers have no obligations to answer nor delivering anything. You do that for the great of good and the open source project.

But, your are maintainers, collaborators, you know your job, you have experience. I've not. I'm a PHP developer, with a javascript experience. I've not the time to learn and acquire as much expertise as you have on iOS or Java code to debug the project. That's why I rely on you to do so. (And you did mention that you'll add this functionality on an issue before https://github.com/react-native-community/react-native-video/issues/1645#issuecomment-508155338) Now you can't, I got it, but please tell me that weeks ago, so I can find a workaround myself and don't let me hold my breath for months.

If you can't (all contributors and maintainers) do that anymore, create an issue and search for maintainers or warn people that this project is about to be left unmaintained.

**Comment by ashnfb** [comment]
That's a very unfair message as I have continued to look into the scrollview issue even this past week. I had asked you to create a feature request, but never said when or if I would implement it.  Please don't communicate with me if you're going to assign blame. I don't have any tolérance for that, and no maintainer on github would.

________________________________

**Comment by jonathangreco** [comment]
@ashnfb Hum I probably misspoke. I don't give any blame, maybe a lack of communication.

From the comment I linked it says (from you)

> @jonathangreco agreed. Let me see about adding a props for hiding the button. It's unfortunate, but this is due to using legacy APIs for displaying fullscreen content. Upgrading to newer APIs is a bigger undertaking. I will post updates about the fullscreen button in #1319

In your opinion what should i understand from you then ?
Again I give no blame sorry if you've understood that, but there is indeed a lack of communication from both of us. Can you please see my point even if I say that badly ?

Again I have to say sorry, since you take all of this personnaly (you should'nt), i'm truly sorry if I have been rude.
There is no rush anymore on my side, I switched on iOS for a javascript buttons with no fullscreen, it's ugly but at least it works.

**Comment by ashnfb** [comment]
To be honest, I had been hoping to fix the root cause of the issue with the scrollview, instead of implementing a workaround.

I have asked to withdraw as a contributor from this project. I have a newborn and a full-time job and haven’t been able to contribute as much as I hoped I would.

I am glad you found a workaround for your issue.

Bye
________________________________

**Comment by jonathangreco** [comment]
Thanks, bye. Enjoy the life with your newborn. Hope you'll fix this when you'll find the time
