### ISSUE TITLE
Set backgroundColor of video player?

### ISSUE THREAD

**Issue by rollsroyc3** [TheWidlarzGroup/react-native-video#1666]
I have a video that is in portrait mode, and I also have to set a marginBottom to include a button, this causes the sides of the video to be black. Is there a way to set this color to white? You can see in the image, about 90% of the left and right side have those thin black bars, of course this might be better or worse depending on device, screen size, etc....

<img width="351" alt="Screenshot 2019-07-11 16 09 06" src="https://user-images.githubusercontent.com/940209/61082256-1c62d700-a3f7-11e9-8a3e-7880d09860c0.png">

I tried setting the video style property but no luck. Also tried setting it manually on line 314 but still no luck.. 

` <View style={[nativeProps.style, {backgroundColor: 'white'}]}>`

Here is my code
    
    <View style={styles.container}>
        <Video
          ref={ref => {
            this.player = ref;
          }}
          source={require("../../assets/videos/walkthrough.mp4")}
          style={styles.backgroundVideo}
          resizeMode="cover"
          onEnd={this.onEnd}
          repeat={false}
          paused={this.state.isVideoPaused}
        />

        <View style={styles.footer}>{this.renderButton()}</View>
      </View>
    

Styles:
    
 container: {
    flex: 1,
    backgroundColor: colors.white
  },
  backgroundVideo: {
    backgroundColor: colors.white,
    flex: 1,
    marginBottom: 10,
    ...ifIphoneX({
      marginBottom: 50
    })
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    alignSelf: "stretch",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    ...ifIphoneX({
      marginBottom: 15
    })
  },

**Comment by rollsroyc3** [comment]
No solutions or workarounds that we know of?

**Comment by CHaNGeTe** [comment]
Which platform? It works for me on ios/android if not using controls.

![image](https://user-images.githubusercontent.com/1237997/61576299-c538c280-aad8-11e9-8c1b-d1bab7f3672a.png)

**Comment by CHaNGeTe** [comment]
For using it on ios with controls you will need to add this line
```
- (void)usePlayerViewController
{
  if( _player )
  {
    if (!_playerViewController) {
      _playerViewController = [self createPlayerViewController:_player withPlayerItem:_playerItem];
/**ADD THIS LINE **/      _playerViewController.view.backgroundColor = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0];
    }
```
