### ISSUE TITLE
Video not showing when using Flat List(Android)

### ISSUE THREAD

**Issue by codervss** [TheWidlarzGroup/react-native-video#1667]
# Bug
Video not showing when using Flat List in Android but works Fine on IOS.

Library Versions :
react-native-video : 2.3.1
react-native : 0.56.0

Code :
export default class VideoX extends React.Component{
    constructor(props){
        super(props)
        this.state={
            url : ["http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4","http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4","http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4","http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4","http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"]
        }
    }

    renderVideo = ({item}) =>{
        console.log('Itemx', item);
        
        return(
        <View style={styles.container}> 
            <View style={stylex.videoWrap}>
                <Video source={{uri: item}}
                ref={(ref) => {
                    this.player = ref
                }}
                repeat={true}
                onBuffer={()=>{console.log('buffer',true)}}
                onEnd={()=>{console.log('end',true)}}
                onError={()=>{console.log('error',true)}}
                onLoad={()=>{console.log('load', true)}}
                onProgress={()=>{console.log('progress', true)}}
                resizeMode={'contain'}
                style={styles.backgroundVideo} />
            </View>
        </View>
        )
    }

    render(){
        const {url} = this.state
        return(
            <FlatList 
                data={url}
                renderItem={(item)=>this.renderVideo(item)}
            />
        )
    }
}

const styles = StyleSheet.create({
    container:{ flex: 1, alignItems : 'center'},
    backgroundVideo: {
      position: 'absolute',
      top: 0,
      left: 10,
      bottom: 0,
      right: 10,
    },
  });

![Screenshot_1562928461](https://user-images.githubusercontent.com/35517904/61123015-e12cda80-a4c0-11e9-8f86-3c7a5b105aae.png)

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by Moemen02** [comment]
Hey, do you have a solution?
