### ISSUE TITLE
[iOS] setPaused is always paused, affecting ignoreSilentSwitch

### ISSUE THREAD

**Issue by maltefiala** [TheWidlarzGroup/react-native-video#1668]
# Bug

## Description

setPaused is always paused, else is never reached. This affects ignoreSilentSwitch as it is never reached.

https://github.com/react-native-community/react-native-video/blob/03114bc78036dd690a85ad7bb2b1bae4b2c431b2/ios/Video/RCTVideo.m#L858
```
  if (paused) {
    [_player pause];
    [_player setRate:0.0];
  } else {
    if([_ignoreSilentSwitch isEqualToString:@"ignore"]) {
      [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
    } else if([_ignoreSilentSwitch isEqualToString:@"obey"]) {
      [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
    }
    [_player play];
    [_player setRate:_rate];
  }
```

As applikations like youtube do ignore the switch as well, the current default setting brakes known iOS app design.

Affects https://github.com/react-native-community/react-native-video/issues/874

## (Bad) workaround for fixing ignoreSilentSwitch
```
{
  if([_ignoreSilentSwitch isEqualToString:@"ignore"]) {
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];
  } else if([_ignoreSilentSwitch isEqualToString:@"obey"]) {
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
  }

  if (paused) {
    [_player pause];
    [_player setRate:0.0];
  } else {
    [_player play];
    [_player setRate:_rate];
  }
  
  _paused = paused;
}
```

**Comment by weblancaster** [comment]
Thanks for sharing this. In my case, I decided to remove the `paused`

**Comment by JaiminWork** [comment]
I tried all tricks but still the audio does not seem to play. 
using ios 17.5 

Code : 
          <Video
            ignoreSilentSwitch='ignore'
            controls={true}
            fullscreen={false}
            style={{
              width: '100%',
              backgroundColor: '#eb343',
              height: '100%',
            }}
            source={{uri: url}}
          />
