### ISSUE TITLE
Issues combining with flipkart's/recyclerlist

### ISSUE THREAD

**Issue by badri21P** [TheWidlarzGroup/react-native-video#1673]
I am using this with [flipkart's/recyclerlist](https://github.com/Flipkart/recyclerlistview). I am able to figure out all autoplay on visible or not, but i could change the video aspect ratio when the player remounted. i am able to set the height of the video player but the video is not automatically changing its aspect ration on changed height.
The first player with initial player mounted
https://drive.google.com/open?id=1-WM1tJZcH00vLFwQ4_RV89MhVFdyTxQJ

after that when i scroll down and came up the aspect changed as per the players previous mounted video ratio
https://drive.google.com/open?id=1rJ9BZOfp-v9bqFNSFvHuT-B4DpKgeiti
another video ex:
https://drive.google.com/open?id=1CBo06uOXcMRwpURIGvomFaHADyNXhDwZ
you can clearly see the weird aspect.

i am wondering if there is something like change video size on src changed methods or any way to manually change the aspect ratio.
BTW i have tried setting video width on the video component but it changes video player width not the actual video. and tried changing resizeMode to contain after src changed in videoplayer component but no luck.

**Comment by CHaNGeTe** [comment]
which platform?
and library version?

**Comment by badri21P** [comment]
As of now i am only focusing on android and testing in it, but in future i need it to work on both android and ios.
The library versions are react-native-video: "4.4.1", recyclerlistview: "2.0.3"

**Comment by CHaNGeTe** [comment]
4.4.4 introduced several fixes for android exoplayer, specially for scenarios with multiple instances, can you check that version?

**Comment by badri21P** [comment]
Thank you, i haven't updated in some time. i will check that and let you know

**Comment by badri21P** [comment]
NO, it doesn't help. Still having the issue

**Comment by CHaNGeTe** [comment]
Do you have a small project reproducing the issue?

**Comment by badri21P** [comment]
Nope, but i could do it asap. I upload it once i finish it.
