### ISSUE TITLE
Audio is mute when Do not Disturb Mode is ON in iOS

### ISSUE THREAD

**Issue by Balasnest** [TheWidlarzGroup/react-native-video#1674]
Audio is mute when **Do not Disturb / Silence** Mode is ON in iOS.

**Actual output:**
Audio is mute even media volume is changed.

**Expected output:**
It should purely depend on media volume.

lib: react-native-video : 4.4.4

**Comment by flexgrip** [comment]
You should be using the `ignoreSilentSwitch` prop to get this to work. However, I’m noticing that these props aren’t always getting passed. If you grep for that variable in the RTVideo.m file in the library itself, you can hardcode it.

**Comment by tmaly1980** [comment]
@flexgrip works for me!
