### ISSUE TITLE
Loading is very slow

### ISSUE THREAD

**Issue by brave-coder9** [TheWidlarzGroup/react-native-video#1675]
I am using react-native-video 4.4.2
```
        <Video
          style={{ position: 'absolute', opacity: 0 }}
          source={{ uri: trackUrl }}
          audioOnly={true}
          ref={ref => this.player = ref}
          volume={1.0}
          muted={false}
          rate={speedRate}
          paused={isPaused}
          onEnd={this._onEnd}
          onLoad={this._onLoad}
          onSeek={this._onSeek}
          playInBackground={true}
          playWhenInactive={true}
          onBuffer={this._onBuffer}
          ignoreSilentSwitch={'ignore'}
          onProgress={this._onProgress}
          onLoadStart={this._onLoadStart}
        />
```
It's too long (4s) between `Loading` and `Buffering`
![image](https://user-images.githubusercontent.com/30062357/61518612-910fc400-aa3c-11e9-9666-06c68a08920d.png)

How can I reduce the loading time?

**Comment by marcos-nunes-dev** [comment]
Same here, any news?

**Comment by gazedash** [comment]
Having the same problem on iOS. ios-buffer-config PR fixes the issue though.

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/pull/1353 this one right?

**Comment by gazedash** [comment]
@CHaNGeTe yes

**Comment by syrakozz** [comment]
also same issue with the latest version , video init is very slow on real device iphone

**Comment by tom-krusch** [comment]
Loading Time on iOS Simulator is slower than Android, but on real iOS device it is even slower

**Comment by hiennguyen92** [comment]
any update for issues?

**Comment by sharmad1205** [comment]
Having same issue I am using a video as a background.
Video size is about 33mb and stored in assets 
`On load start  7:59:02 pm`
`On load  7:59:09 pm`
takes about 7 sec to load and video start running.

**Comment by khushmanvar** [comment]
forget this package , try [https://docs.expo.io/versions/latest/sdk/video/](expo-av Video) package . It's loading time is quite faster than this. To use this package on vanilla react-native app you have to install expo uniodules.

**Comment by anhnd11** [comment]
Any update?

**Comment by evtuw** [comment]
@brave-merida Did you resolved it yet? I have same issue in Android devices

**Comment by Surik266** [comment]
+1

**Comment by OfficialRohitSharma442** [comment]
same issue in my device

**Comment by muhammadashfaq** [comment]
I am also facing this issue

**Comment by mueenrehman** [comment]
has anyone found the correct solution to it? Please do mention me if someone has found it

**Comment by ShubhamBalgujar** [comment]
For android it is related to exoplayer. For more details visit this link
[](https://medium.com/@filipluch/how-to-improve-buffering-by-4-times-with-drip-feeding-technique-in-exoplayer-on-android-b59eb0c4d9cc)

**Comment by ShubhamBalgujar** [comment]
For android it is related to exoplayer.
https://medium.com/@filipluch/how-to-improve-buffering-by-4-times-with-drip-feeding-technique-in-exoplayer-on-android-b59eb0c4d9cc

**Comment by iGroza** [comment]
+1

**Comment by dipankurXT** [comment]
Same issue here. Any update on this ?

**Comment by amirkhanzada51** [comment]
Same issue here android & ios both.

**Comment by priyaWedo** [comment]
same issue happening with me
