### ISSUE TITLE
Unable to reload, must rebuild project after exception.

### ISSUE THREAD

**Issue by yanivkalfa** [TheWidlarzGroup/react-native-video#168]
if you use the library, add a video to a view, and later introduce an error to the code, You cannot refresh the app, the second time you refresh the app, Xcode pops up on debug navigation bar. pointing to the error, and you have to rebuild the project - not just fix it JS then refresh.

**Comment by qthompson** [comment]
I think I’m also experiencing something like this.

Sometimes I run the app from Xcode and then it gets stuck on a white screen (before my JS code is executed). 

The only way I can seem to get it to run correctly again is by restarting the react native packager/server.

Is anybody else seeing this happen, or have any ideas on where to look to find out why this happens?
