### ISSUE TITLE
Video Live Streaming in React Native using Amazon S3 and Clouad Front

### ISSUE THREAD

**Issue by hamedmardanpour** [TheWidlarzGroup/react-native-video#1680]
# Question
Hello everybody. I'm creating a video live streaming application in React.js using Amazon S3 and Amazon Cloudfront service. But I don't know how to use these services in React. Can you help me please?

**Comment by DavidTxx** [comment]
Hi,
You should check that post which is exactly about that:
http://facebook.github.io/react-native/blog/2018/03/05/AWS-app-sync

**Comment by zabojad** [comment]
@hamedmardanpour  Did you find any ressources regarding this?
