### ISSUE TITLE
How to STOP video player when switching Tab?

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#1686]
I'm using a TabNavigator in react native (createBottomTabNavigator). When navigating away from a particular tab, i'd like the video player to stop playing (not pause). Should a user navigate back to the tab, they should be able to tap the video to start play from the beginning again. 

Any idea how this can be achieved?

Thanks

**Comment by italogustavoborba** [comment]
hHi @chai86 :

```
this.props.navigation.addListener(
      'didBlur', payload => {
        this.setState({
          this._player.seek(0);
          isPaused: true
        });
      }
```
<Video ...
                paused={isPaused}
                ref={(ref) => this._player = ref}/>
```

```

**Comment by chai86** [comment]
@italogustavoborba Thanks. I used:
```
            <NavigationEvents
                   onWillFocus={() => {
                       this._player.seek(0);
                       this.setState({paused: false});  
                   }}
              />
```
When focusing back to stop and unpause again. Did the trick

**Comment by CHaNGeTe** [comment]
Conditional rendering does not help?
I mean using didBlur / willFocus to determine if the component should be rendered

**Comment by Isaacmeedinaa** [comment]
When going back to the original tab, it should resume the video.. How can I achieve this?

**Comment by emrepirnaz** [comment]
> When going back to the original tab, it should resume the video.. How can I achieve this?

Hi, my resolve;

`navigation.addListener('didFocus', () => {
			this.setState({
				paused: false,
			});
		});`

**Comment by Maheshbokhani** [comment]
Try this!
  
      {...}

     const [pause, setPause] = useState(false)

     useEffect(() => {
          const blur = navigation.addListener('blur', () => {
          setPause(true)
        });

        const focus = navigation.addListener('focus', () => {
        setPause(false)
      });

       return blur, focus;
      }, [navigation]);

       {...}
         <Video
           source={{ uri: ENTER_HERE_URL }}
           paused={pause}
            style={styles.bgView} />

       {...}

**Comment by aravi365** [comment]
> Try this!
> 
> ```
>   {...}
> 
>  const [pause, setPause] = useState(false)
> 
>  useEffect(() => {
>       const blur = navigation.addListener('blur', () => {
>       setPause(true)
>     });
> 
>     const focus = navigation.addListener('focus', () => {
>     setPause(false)
>   });
> 
>    return blur, focus;
>   }, [navigation]);
> 
>    {...}
>      <Video
>        source={{ uri: ENTER_HERE_URL }}
>        paused={pause}
>         style={styles.bgView} />
> 
>    {...}
> ```

It worked! Thanks alot

**Comment by Riaz5687** [comment]
> const [pause, setPause] = useState(false)

it worked for me. Thanks

**Comment by Riaz5687** [comment]
> Try this!
> 
> ```
>   {...}
> 
>  const [pause, setPause] = useState(false)
> 
>  useEffect(() => {
>       const blur = navigation.addListener('blur', () => {
>       setPause(true)
>     });
> 
>     const focus = navigation.addListener('focus', () => {
>     setPause(false)
>   });
> 
>    return blur, focus;
>   }, [navigation]);
> 
>    {...}
>      <Video
>        source={{ uri: ENTER_HERE_URL }}
>        paused={pause}
>         style={styles.bgView} />
> 
>    {...}
> ```

It worked for me. Thanks.

**Comment by neriolorona** [comment]
yeah, that worked for me too thanks

**Comment by freeboub** [comment]
Looks like done, let's close

**Comment by kookooapp** [comment]
It is not working in IOS....
I'm using a TabNavigator in react native (createBottomTabNavigator). When navigating away from a particular tab, i'd like the video player to stop playing (not pause). It is  playing in background...

Any idea how this can be achieved?

Thank you..

**Comment by keval7838** [comment]
> It is not working in IOS.... I'm using a TabNavigator in react native (createBottomTabNavigator). When navigating away from a particular tab, i'd like the video player to stop playing (not pause). It is playing in background...
> 
> Any idea how this can be achieved?
> 
> Thank you..

same issue here

**Comment by khoatran121294** [comment]
> > It is not working in IOS.... I'm using a TabNavigator in react native (createBottomTabNavigator). When navigating away from a particular tab, i'd like the video player to stop playing (not pause). It is playing in background...
> > Any idea how this can be achieved?
> > Thank you..
> 
> same issue here

It not worked with React state, can use setNativeProps in Ref:
`videoref.current.setNativeProps({ paused: true })`

I encountered this issue & found the solution here: https://github.com/TheWidlarzGroup/react-native-video/issues/2458
