### ISSUE TITLE
Several GET requests

### ISSUE THREAD

**Issue by OmarBasem** [TheWidlarzGroup/react-native-video#1687]
# Bug

When loading a video, react-native-video component makes at least 3 GET requests, which is a big waste of data. Also, setting repeat property to true causes infinite GET requests.

## Environment info

 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 404.71 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: x.x.x

## Steps To Reproduce

1. Just to load a video player, and monitor the GET requests.
...

Describe what you expected to happen:

1. Only one GET request should be issued.

## Reproducible sample code

```
 <Video
            ref={this.video} resizeMode={resizeMode}
            onEnd={this.onEnd}
            onBuffer={({isBuffering}) => this.setState({isBuffering})}
            onReadyForDisplay={() => this.setState({ready: true})}
            onProgress={this.onProgress} paused={this.state.paused}
            controls={this.videoRoute && Platform.OS === 'ios' && !video.flip}
            source={{uri: this.props.video.uri}}
            style={[{
              width: size,
              height: videoHeight,
              backgroundColor: '#000',
              maxHeight: h('80%', true),
              transform: [{scaleX: !video.flip ? 1 : -1}]
            }, style]}
          />
```

**Comment by jensellfors** [comment]
This is the native player fetching chunks of the video probably. RNV isn't doing any GET requests at all. Please refer to StackOverflow for ExpoPlayer performance issues.
