### ISSUE TITLE
Take out the black waiting screen.

### ISSUE THREAD

**Issue by nachumFreedman** [TheWidlarzGroup/react-native-video#1689]
Instead of being seethrough, this library shows a black screen when the video is loading? 

why isn't it seethrough. 

I really don't understand this because on 4.4.1 it was fine, then we updated and now it's got the bug again, I reverted, it was fine, now randomly it's back??

**Comment by CHaNGeTe** [comment]
@jenshandersson can you take a look at this?
Maybe the handle props racing PR broke this (https://github.com/react-native-community/react-native-video/pull/1655).

https://github.com/react-native-community/react-native-video/pull/1627

**Comment by jensellfors** [comment]
@nachumFreedman what platform are you talking about? Are you using `poster`? Please share some code so we can test it out. 

I just tried on iOS and the video is transparent while loading.

**Comment by nachumFreedman** [comment]
I'm using android, this does not happen on IOS. (tested on around 5 different actual devices, no emulator)

**Comment by jensellfors** [comment]
Ok thanks for letting us know, but can you please answer my questions above so we can try to reproduce. Using ExoPlayer or MediaPlayer? Poster? Please include the code where you initiate your `<Video />`

**Comment by jensellfors** [comment]
Ok I found it, but looks like this was introduced years ago: https://github.com/react-native-community/react-native-video/blob/c29244bf8963cf91c8bb971211a37a8975673459/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java#L72

Removing this line gives you transparent view while loading, you can try this yourself. But before removing this I need to know why it was introduced. @cobarx is there a reason for setting the background color to black on Android? (And what is the shutterView...?).
ping @CHaNGeTe

**Comment by nachumFreedman** [comment]
Correct that is the line and removing it does clear the black. It was already removed last version but this latest version it either got put back in or I don't know...

**Comment by nachumFreedman** [comment]
Btw no poster and not in expo my code differes a lot (I'm using it a few times)

**Comment by anaelsh** [comment]
> Ok I found it, but looks like this was introduced years ago:
> 
> https://github.com/react-native-community/react-native-video/blob/c29244bf8963cf91c8bb971211a37a8975673459/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java#L72
> 
> Removing this line gives you transparent view while loading, you can try this yourself. But before removing this I need to know why it was introduced. @cobarx is there a reason for setting the background color to black on Android? (And what is the shutterView...?).
> ping @CHaNGeTe

Removing this line didn't remove the black screen for me

**Comment by fabOnReact** [comment]
seems that this [pull request](https://github.com/react-native-community/react-native-video/pull/1627) fixed a bug connected to poster and video showing at the same time, but it is now causing a black screen. I experience this in scrollview, while scrolling down and then backup. The video has to load again, the poster does not show instead a black background is displayed.

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
"react-native-video": "^5.0.2"

React Native Android Black Screen For Android

**Comment by redko-o** [comment]
same issue
