### ISSUE TITLE
Repeat prop creates gap in sound and video when repeating

### ISSUE THREAD

**Issue by cantonalex** [TheWidlarzGroup/react-native-video#1691]
I have checked my audio and video and despite being a perfect loop, when repeat prop is marked true. There is still a jitter when the video loops.

**Comment by TalalBazerbachi** [comment]
@cantonalex were you able to fix the problem

**Comment by murtuzamacdev** [comment]
For gapless video, you will need update the exoplayer to latest 2.12.0

I have created a forked repo which can be helpful: 

https://github.com/murtuzamacdev/react-native-audio-exoplayer#readme
