### ISSUE TITLE
local audio onError，'AVFoundationErrorDomain'  

### ISSUE THREAD

**Issue by yanjie311** [TheWidlarzGroup/react-native-video#1692]
{ error: { code: -11800, domain: 'AVFoundationErrorDomain' },
  target: 5997 }
iOS platform

**Comment by jensellfors** [comment]
If you need help with iOS errors please check StackOverflow

**Comment by yanjie311** [comment]
I have checked StackOverflow, but it did not help. Only audio sent by one Android device cannot be played on Apple device, and other devices can play normally.
