### ISSUE TITLE
Inconsistent error handling

### ISSUE THREAD

**Issue by gazedash** [TheWidlarzGroup/react-native-video#1693]
# Bug

On iOS it doesn't call the onError callback or onVideoError callback e.g. when internet was disconnected and buffered segment ended.
On android, it calls this callback.

Two more issues:
* It doesn't start the first time if you set paused={true} after error, and then set paused={false} again, user has to click again after that.
* If there was an error with playback (e.g. no internet), and the paused prop is false, it won't continue to play after internet is available again

React Native 0.59
React Native Video 4.4.4

**Comment by naeemqaswar** [comment]
In android, its handled pretty well but in your case you can fix it using "@react-native-community/netinfo". Player doesn't throw any error when internet turns off, you can use "netinfo" listener to observe connection status and intentionally pause the video and if available you can resume it.
