### ISSUE TITLE
Controls Still showing

### ISSUE THREAD

**Issue by eyalabadi98** [TheWidlarzGroup/react-native-video#1694]
# Bug

I am using the Video component, but when I set controls={false}, the video controls still show on IOS. I would like to disable access to the user to pause, advance etc.

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 41.93 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.0 AI-171.4443003
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-svg: 6.0.0-rc1
```

Library version: latest

## Steps To Reproduce

1. Play a video
2. Set controls either true or false, it always shows the controls

Describe what you expected to happen:

1. I'd like for the controls to disappear

## Reproducible sample code

                       ```<Video
                        ref={p => { this.videoPlayer = p; }}
                        source={{ uri: 'a URL' }}
                        style={{width: this.state.orientationWidth, height: this.state.orientationHeight }}
                        controls={false}
                        fullscreen={false}
                        resizeMode='cover'
                    ```>

**Comment by jensellfors** [comment]
What version of `react-native-video` are you using? It works fine for me... Can you try moving the `controls={false}` prop to the top, could be introduced in the prop setting race condition PR...

**Comment by eyalabadi98** [comment]
Hello,
I am using version ^5.0.0 and used the following component:

![Screen Shot 2019-08-08 at 11 34 35 AM](https://user-images.githubusercontent.com/3536706/62716694-907da400-b9d0-11e9-8788-ae3eed3d45c7.png)

and I still get the video controls

**Comment by igor-lemon** [comment]
The same issue

**Comment by igor-lemon** [comment]
@HardikDhanani can you help?

**Comment by igor-lemon** [comment]
@CHaNGeTe can you help?

**Comment by igor-lemon** [comment]
@eyalabadi98 https://github.com/react-native-community/react-native-video/issues/1786#issuecomment-538705715

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/issues/1786#issuecomment-538720633
