### ISSUE TITLE
Doesn't always play 

### ISSUE THREAD

**Issue by nachumFreedman** [TheWidlarzGroup/react-native-video#1695]
I'm using about 30 videos per app and every now and then on Android the video doesn't pkay, this is two separate issues 

1. Video doesn't play, meaning video is Frozen on first frame and won't move.

2. Video just shows a white screen (this issue may not be related to this library and shouldn't be the focus of this post)

**Comment by nachumFreedman** [comment]
After a lot of research, in the senarios is doesn't play. 

This library doesnt seem to seek to a negative number (when the video doesn't play it's always because the seek is a negative number)

The other issue is that after this occors once you must click play and it will play but throughout any next concurrent videos it won't auto play again  It doesn't auto play after this

**Comment by CHaNGeTe** [comment]
We can include a max(0, seekTime) here
https://github.com/react-native-community/react-native-video/blob/master/Video.js#L55

**Comment by nachumFreedman** [comment]
After 2 whole days on this bug, found this. https://github.com/react-native-community/react-native-video/issues/1151 

Please add this to the library, this library is getting a scary amount of Issues for such a well-used library.
