### ISSUE TITLE
Exoplayer doesn't work with mute=true

### ISSUE THREAD

**Issue by andrewchae** [TheWidlarzGroup/react-native-video#1696]
Works much better except it seems `muted={true}` does not seem to work. 
it works if you flip it
`muted={this.state.muted}`
`true -> false -> true` 
but not when the video starts. 

on Android
A working hack is 
```
        InteractionManager.runAfterInteractions(() => {
            _.delay(() => {
                this.setState({muted: this.props.muted});
            }, 1);
        });
```

_Originally posted by @note89 in https://github.com/react-native-community/react-native-video/pull/426#issuecomment-277719931_

I tried variations on the hack but to get it working consistently some audio always plays before muting

**Comment by DrawGu** [comment]
I have the same problem.

**Comment by CHaNGeTe** [comment]
check https://github.com/react-native-community/react-native-video/pull/1699

**Comment by itsmefordyfy** [comment]
>  InteractionManager.runAfterInteractions(() => {
>             _.delay(() => {
>                 this.setState({muted: this.props.muted});
>             }, 1);
>         });

Where I can find this file?
