### ISSUE TITLE
Whether the video cache is always displayed and whether the cached video is cached the next time it is played.

### ISSUE THREAD

**Issue by HuangZhe007** [TheWidlarzGroup/react-native-video#1698]
# Question

Whether the video cache is always displayed and whether the cached video is cached the next time it is played.

**Comment by oleksiy-nesterov** [comment]
the same question... for me, seems like no, each time it looks like the video downloading started again.
maybe this is reason https://github.com/react-native-community/react-native-video/issues/1710
