### ISSUE TITLE
Rotate video and make fullscreen

### ISSUE THREAD

**Issue by shahankit** [TheWidlarzGroup/react-native-video#170]
I have got complex view hierarchy and at leaf have the Video node. Basically I use the scrollable tab view each of which contains a video and full screen button. Now the fullscreen button should rotate the video and make the video fullscreen. Currently I'm trying to move the video out of the current position and move it to another view which is inside parent and has position absolute and top left right bottom to 0. I have created a demo app for same here: https://github.com/shahankit/ViewPagerVideoTest.
But the current implementation does not help in starting the video exactly from where I left before fullscreen button is pressed. I can store the time and make the video player seek time, but that will still reload the video. Is there any way in which I can use the same video and rotate it and make it fullscreen.

**Comment by shahankit** [comment]
One solution I think is to provide a fullscreen prop which sets the `AVPlayer` to fullscreen from native side using following code:

```
self.window?.addSubview(self)
self.transform = CGAffineTransformMakeRotation(CGFloat(degreesToRadians(90)))
UIView.animateWithDuration(0.3,
    animations: { () -> Void in
        self.frame = self.window!.bounds
        self.resetControlFrame()
    })
```

**Comment by shahankit** [comment]
I found using native controls better which automatically provides fullscreen button functionality. Sorry for not checking that out previously.

**Comment by WhatAKitty** [comment]
@shahankit Is it work well in android? I found it is broken in android while it works fine in IOS.

**Comment by shahankit** [comment]
Yeah using native controls works on iOS but not on android so we are using another player for android.

**Comment by WhatAKitty** [comment]
@shahankit Which player? I work hard in custom skin.

**Comment by jayshah123** [comment]
@WhatAKitty One way would be to change height and width from JS is by emitting event from native (fullscreen onclick listener) to JS side(with listener in JS which will change size) (since it seems, native android code cannot change its own height/width using layoutparams)

**Comment by mostafa** [comment]
Check [this](https://github.com/mostafa/react-native-fullscreen-video) out!
It may help!
