### ISSUE TITLE
Can i pass the decryption key to the video directly ?

### ISSUE THREAD

**Issue by abdullahoday710** [TheWidlarzGroup/react-native-video#1700]
I have a common encryption video encrypted by ffmpeg and i need to pass the decryption key to the player directly is there such thing ? the only solution i have is to download the whole video , decrypt it and play it.

**Comment by CHaNGeTe** [comment]
@3bodyZZ this library still has no DRM support.
This is on route, but still unmerged.
https://github.com/react-native-community/react-native-video/pull/1445

Shouldn't decryption key come from a License server?

**Comment by abdullahoday710** [comment]
> Shouldn't decryption key come from a License server?

my application has a different and specific purpose so it have to be passed directly

**Comment by abdullahoday710** [comment]
@CHaNGeTe i will probably go with webviews to do this because i have a deadline , still it would be cool if we had a native feature.

**Comment by CHaNGeTe** [comment]
I have not tested yet, but If the key is present on the same route as the manifest
`#EXT-X-KEY:METHOD=AES-128,URI="key.bin"`
I think it should just work
