### ISSUE TITLE
IPTV Live Stream Only works on emulator

### ISSUE THREAD

**Issue by Nepherius** [TheWidlarzGroup/react-native-video#1704]
# Bug

IPTV Live stream links only work on emulators and not actual phones. Tested on S8+ and s10+, works fine on both Genymotion and Android Virtual Device with multiple configs.
Regular iptv links like movies work as intended both on emulators and physical devices.

The only error I'm getting from the player is : {extra: -2147483648, what: 1}

## Environment info

React native info output:

```bash
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.39 GB / 15.85 GB
  Binaries:
    Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
```

Library version: ^5.0.0

## Steps To Reproduce

1. react-native init project
2. yarn add react-native-video
3. add Video component and try a live stream iptv link

Describe what you expected to happen:

1. I expect it to work ...

## Reproducible sample code

Use any code from readme or from examples dir

**Comment by canyavall** [comment]
Can you show the code?

We have an IPTV project working (playing HLS)
