### ISSUE TITLE
5.0.0 extremely slow on Android from URL

### ISSUE THREAD

**Issue by cristianoccazinsp** [TheWidlarzGroup/react-native-video#1705]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 19.24 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 25.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

Library version: "react-native-video": "5.0.0"

Playing a fairly big video (low quality 45 seconds video) seem to be very slow on Android when loaded from a remote URL. On IOS, this doesn't seem to be an issue and the video plays and seeks quite well.

When testing on Android, it takes a long time (10-15 seconds) to even load the first frame / video duration. After it starts playing, it blocks very often, and trying to seek will end up in a frozen video again and no loading.

Not doing anything special with the player:
```
 <Video
          {...props}
          style={[
            styles.video,
            this.getSizeStyles(),
            style,
            customStyles.video,
          ]}
          ref={p => { this.player = p; }}
          paused={this.props.paused
            ? this.props.paused || !this.state.isPlaying
            : !this.state.isPlaying}
          onProgress={this.onProgress}
          onEnd={this.onEnd}
          onLoad={this.onLoad}
          source={video}
          resizeMode={resizeMode}
        />
```

**Comment by Vista1nik** [comment]
It will be good if maintainers take a look at this issue...

**Comment by jhonnyrogerb** [comment]
Same here! Extremely slow on Android when I load any video from S3, even a relatively small video (15MB, 15s) takes almost a minute to load. (debug and release)

**Comment by CHaNGeTe** [comment]
Does the video allow progressive downloading?

**Comment by cristianoccazinsp** [comment]
Yes, and it works fine on other Android devices and on iOS.
Can't tell if this is an Android 9 issue or a pixel 2 issue, but even my
$100 Motorola with android 8 doesn't have this problem. Same videos always.

**Comment by fabriziobertoglio1987** [comment]
I am also experiencing this issue.

**Comment by fabriziobertoglio1987** [comment]
I m experiencing the issue on Android 7.1.
How can we make the video load faster? Considering I can not decrease the size (1 mb). Are there alternative libraries? Should I write native code?

**Comment by Vista1nik** [comment]
I think React Native only for companies who have a lot developers to resolve problems like this. So this will be fixed really not soon. 
There is working video component in Expo but they don't support 0.60

**Comment by cristianoccazinsp** [comment]
I understand that, and I've been fixing bugs on other libraries as I find
them and as they fit my needs. I would definitely fix this one but I didn't
see anything obvious from a quick look into the Java code. Would appreciate
some directions.

**Comment by janpe** [comment]
Also seeing this issue. Downgrading back to 4.4.1 makes it a lot faster. ~1s on 4.4.1 vs more than 10s on >5.0.0.
