### ISSUE TITLE
Android X update for Exo Player?

### ISSUE THREAD

**Issue by rollsroyc3** [TheWidlarzGroup/react-native-video#1706]
Im trying to build on bitrise but I got the following error:

`/Users/vagrant/git/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java:3: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;`

Looking at the code in _**exoplayer/**_ I see that there are still some old references to _**android.support**_. Is there a reason this hasnt been updated to support Android X yet?

Running the latest "react-native-video": "^5.0.0",

**Comment by benoitdion** [comment]
This was fixed in 5.0.2. Closing the issue for now but feel free to open a new one if this persists after 5.0.2.
