### ISSUE TITLE
Control Center in iOS, Tray in Android, Device-aware audio

### ISSUE THREAD

**Issue by avanrossum** [TheWidlarzGroup/react-native-video#1707]
### Current behavior
When playing a video or audio track with background/inactive set to true, the device is not aware of the audio from the react-native app. Audio cannot be controlled via control center or the android tray.  Since device is not "aware" of the audio, other audio will actually play over it.

RN 0.59.10, 0.57.x
RNV 5.0.0, 4.0.0

### Reproduction steps
1. Set prop "playInBackground" to true
1. Start app, play video
1. Leave app
1. Try to control audio without killing app.

### Expected behavior
Control center and android tray would be aware of the audio.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android MediaPlayer

### Video sample
Irrelevant

### Additional notes

This may be the expected behavior, but if it is, I see no purpose in having "playInBackground" as an available prop, because that is a terrible user experience.  Is there another component that I need to have in order to enable this?

Thanks for the great component otherwise =]

**Comment by avanrossum** [comment]
We ended up writing our own native components for this, as react-native-music-control was causing some issues with iOS, and it seemed faster to just write our ow.  Jury's still out on that one.

However, we will continue to watch this, as if this does get fully added to the roadmap I believe it would be preferable to use the built-in

**Comment by flexgrip** [comment]
@avanrossom

Able to share any of that code or give a general synopsis on how you did it?

**Comment by avanrossum** [comment]
@flexgrip Unfortunately, we're not ready to release any code at this time, mostly because we don't have the bandwidth to maintain it well. A colleague wrote the Android component, but for iOS I think I can help give you some direction:

Apple's documentation on this is borderline nonexistent, which makes it extremely frustrating to build on.

There are essentially three components of it:

**Initialize the Control Center Component**
- When our app starts to play audio, we call a function that essentially tells the control center we want to talk to it, and we set the settings we want to use (please note that this is simplified for brevity.  The code below is not intended to be complete, rather, sets a direction to work in)



```Objective-C
//Sets the initial data for the player 
RCT_EXPORT_METHOD(setInitialData:(NSDictionary *)data) 
{ 
    [self initMP]; 
    MPNowPlayingInfoCenter *center = [MPNowPlayingInfoCenter defaultCenter]; 
    NSMutableDictionary *nowPlayingInfo = [NSMutableDictionary dictionary]; 
    if (@available(iOS 11.0, *)) { 
        center.playbackState = MPNowPlayingPlaybackStatePlaying; 
    } 
//interruption observer 
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(routeChange:) name:AVAudioSessionRouteChangeNotification object:nil]; 
    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents]; 
    self.audioInterruptionsObserved = false; 
 
    //Sets the values 
    nowPlayingInfo[MPMediaItemPropertyTitle] = data[@"title"]; 
    nowPlayingInfo[MPMediaItemPropertyArtist] = data[@"artist"]; 

..... more code .....


}

- (void)initMP{
MPRemoteCommandCenter *remoteCommandCenter = [MPRemoteCommandCenter sharedCommandCenter]; 

//The features
remoteCommandCenter.previousTrackCommand.enabled = NO; 
remoteCommandCenter.nextTrackCommand.enabled = NO; 
remoteCommandCenter.playCommand.enabled = YES; 
remoteCommandCenter.pauseCommand.enabled = YES; 

//The selectors (it would appear that iOS gets weird if you don't specify a target, even if you aren't using the selector.
[remoteCommandCenter.previousTrackCommand addTarget:self action:@selector(actionDoNothing:)]; 
[remoteCommandCenter.nextTrackCommand addTarget:self action:@selector(actionDoNothing:)];
[remoteCommandCenter.playCommand addTarget:self action:@selector(onPlay:)]; 
[remoteCommandCenter.pauseCommand addTarget:self action:@selector(onPause:)]; 
}
```

**Hook up links between iOS and RN**
- You'll need to use playback speed, rather than just play/pause to control the playback.  Here's an example:

```Objective-C

if ([state isEqual:@"play"]) { 
        speed = [NSNumber numberWithDouble:1]; 
        if (@available(iOS 11.0, *)) { 
            center.playbackState = MPNowPlayingPlaybackStatePlaying; 
        } 
    } else { 
        speed = [NSNumber numberWithDouble:0]; 
        if (@available(iOS 11.0, *)) { 
            center.playbackState = MPNowPlayingPlaybackStatePaused; 
        } 
    } 
```

**When you end the playback, you need to clear the component.**
- I don't know that this is strictly necessary, but it's definitely not a good idea to disconnect your playback but leave the audio as an option in the control center =]

```Objective-C
//Remove our control over the control center
RCT_EXPORT_METHOD(resetNowPlaying){ 
    MPNowPlayingInfoCenter *center = [MPNowPlayingInfoCenter defaultCenter]; 
    center.nowPlayingInfo = nil; 
    self.artworkUrl = nil; 
    if (@available(iOS 11.0, *)) { 
        center.playbackState = MPNowPlayingPlaybackStateStopped; 
    } 
} 

```


I hope this helps somewhat!

**Comment by sampsonjoliver** [comment]
`react-native-music-control` is fairly buggy, especially on Android. It would be good to see more support from both ends on integrating together, but ideally it'd be nice to see https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b be implemented (at least for exoplayer) and configurable via a prop, and possibly a custom solution for iOS.

**Comment by flexgrip** [comment]
Yeah. This is one of those “nice to haves”. But there are far more important core issues I think RNV will get attention on before this, unless one of us creates a magic PR. Once my current project is stabile, I may take a swing at it.

**Comment by sampsonjoliver** [comment]
Just did a bit of digging. I agree it's not a core feature of RNV, but it might be nice to see an implementation guide of using `react-native-music-control` in the documentation.

Also, given the Android issues of RNMC, I _think_ it's a fairly minimal amount of work to support https://github.com/react-native-community/react-native-video/issues/1808 . Might be worth looking into at least! If I can provide the magic PR I will, but depends on if I get time.

**Comment by a7urag** [comment]
Does anyone else require this feature? I can write in android, but need support in ios.

**Comment by singh100ful** [comment]
React native track player seems a better option for notification tray but integrating it with RN Video is bit of tough task. Can anyone help out ?

**Comment by jariwalabhavesh** [comment]
@singh100ful : 
What can be do is we can install both RNV and react-native-track-player in-app.
But I am not sure about how to control or show notification controls for video as well by using react-native-track-player methods??

**Comment by gilbertl** [comment]
> @singh100ful :
> What can be do is we can install both RNV and react-native-track-player in-app.
> But I am not sure about how to control or show notification controls for video as well by using react-native-track-player methods??

Kind of. I'm playing with it right now. 

If you have react-native-track-player install, you can listen to remote-play / remote-pause events to respond to Control Center events.

I only just started though; there are likely issues that need to be hacked around.

**Comment by alexghi** [comment]
are there any news on this? I think there are a lot of us who are interested in this. What can we do?

**Comment by vargajacint** [comment]
Any update?

**Comment by reberthkss** [comment]
some progress guys? I thinking on give a try to `react-native-push-notification` to build the tray, as it provide some useful configurations for notification components.

**Comment by alexghi** [comment]
I ended up using `react-native music-controls` with the package itself. and it's been working great. Had no problems whatsoever. App is in production.

**Comment by reberthkss** [comment]
i'm using `react-native-music-controls` too and loving it.

**Comment by asankad-xino** [comment]
> I ended up using `react-native music-controls` with the package itself. and it's been working great. Had no problems whatsoever. App is in production.

Happy to hear this news. I have the same use case. This means 'react-native-video' is using for playing tracks/videos in the react native application and using 'react-native-music-control' can media controls on lock screen and notification center for iOS and Android ? If so can you please provide a sample code how can we used that and pass multi tracks to the music control as well.

**Comment by reberthkss** [comment]
> > I ended up using `react-native music-controls` with the package itself. and it's been working great. Had no problems whatsoever. App is in production.
> 
> Happy to hear this news. I have the same use case. This means 'react-native-video' is using for playing tracks/videos in the react native application and using 'react-native-music-control' can media controls on lock screen and notification center for iOS and Android ? If so can you please provide a sample code how can we used that and pass multi tracks to the music control as well.

Follow in below my basic player component with `react-native-video` + `react-native-music-control` as example.
https://gist.github.com/reberthkss/c99383615eb3b38a4712c057ee66f74c
