### ISSUE TITLE
Build: build failed: could not setcwd()

### ISSUE THREAD

**Issue by karltaylor** [TheWidlarzGroup/react-native-video#1708]
# Bug

When I run a `clean` on Android Studio I get the following error:

![Screenshot 2019-08-09 at 11 34 10](https://user-images.githubusercontent.com/6763109/62773265-a3a87680-ba99-11e9-9d85-1afaaf50be03.png)

```
Could not set process working directory to '/node_modules/tmmedia-nextgen-sdk-neutron-tester/platformBuilds/tmmedia-nextgen-sdk-neutron-testerExample_android': could not setcwd() (errno 2: No such file or directory)
```

Update:

When I added this directory:

```sh
mkdir -p tmmedia-nextgen-sdk-neutron-tester/platformBuilds/tmmedia-nextgen-sdk-neutron-testerExample_android
```

I get 

```sh
Task 'clean' not found in root project 'tmmedia-nextgen-sdk-neutron-testerExample_android'.
```

So added:

```java
// node_modules/tmmedia-nextgen-sdk-neutron-tester/platformBuilds/tmmedia-nextgen-sdk-neutron-testerExample_android/build.gradle
plugins {
    id "base"
}
```

And then run another clean, and then the error is:

```sh
Project 'react-native-video' not found in root project 'tmmedia-nextgen-sdk-neutron-testerExample_android'.
```

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 353.71 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
```

Library version: 4.4.4

## Steps To Reproduce

1. Install `react-native-video`
2. Open android studio
3. Clean build.

Describe what you expected to happen:

1. It to work

---

I can't actually find any reference to this module apart from here: https://github.com/ApollosProject/apollos-prototype/pull/869#issuecomment-511227476 so it would be interesting to see what this thing is.

The project works and builds absolutely fine when running `npx react-native run android`

**Comment by Chubacca** [comment]
I'm having this issue. To work around it for now, I'm deleting any reference to tmmedia in `react-native-video.iml` and `react-native-video~1.iml`:

Change line 2:

`<module external.linked.project.id=":react-native-video" external.linked.project.path="$MODULE_DIR$" external.root.project.path="$MODULE_DIR$/../../tmmedia-nextgen-sdk-neutron-tester/platformBuilds/tmmedia-nextgen-sdk-neutron-testerExample_android" external.system.id="GRADLE" type="JAVA_MODULE" version="4">`

to

`<module external.linked.project.id=":react-native-video" external.linked.project.path="$MODULE_DIR$" external.root.project.path="$MODULE_DIR$/../../../android" external.system.id="GRADLE" type="JAVA_MODULE" version="4">`

This seems to fix it for me as a temporary solution.
