### ISSUE TITLE
iOS Video caching on version 5.0.0 not working

### ISSUE THREAD

**Issue by eddyjusufi** [TheWidlarzGroup/react-native-video#1710]
# Bug
I have encountered that VideoCaching on iOS using react-native-video `v5.0.0` is not working. Video Caching is practically non-existent. When I revert back to `v4.3.1` caching works perfectly fine. Does anyone else encounter this issue as well?

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 2.02 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.0.0

## Steps To Reproduce

1. Have react-native-video on version `5.0.0` and latest react-native (`v.0.60.+`)
2. Enable Video Caching through Podfile
3. Watch a remote video through URL. 
4. Refresh app to encounter the issue - the video has not been cached and would not load without an internet connection.

Describe what you expected to happen:

1. The expected behaviour is that once loaded for the first time, watching the same video (through the same URL) would not require an internet connection to be loaded and watched again.

## Reproducible sample code

Following the steps above is enough to encounter the issue. No specific sample code needed.

**Comment by Flouwrian** [comment]
Yes, i have this issue! I get the following error message: Error: Asset is nil 
using react native 62.2 and react-native-video 5.0.2

im going to try reverting !

**Comment by gilbert** [comment]
Can confirm: reverting back to 4.4.5 from 5.1alpha8 did fix the caching problem.
