### ISSUE TITLE
Plans to upgrade Exoplayer?

### ISSUE THREAD

**Issue by mark-carrington** [TheWidlarzGroup/react-native-video#1711]
# Feature Request

Upgrade Exoplayer dependency to 2.10.1 or newer (if available).

## Why it is needed

We are currently using both 'react-native-video' (version 5.0.0) and 'react-native-track-player' (version 1.1.8), but these libraries have a dependency conflict on Exoplayer (see below):

react-native-track-player -> com.google.android.exoplayer.exoplayer-core:2.10.1
react-native-video ->  com.google.android.exoplayer.*:2.9.3

Whilst it is possible to downgrade 'react-native-track-player' to earlier version (1.1.4) to get the same version Exoplayer, we lose some of the nice new features in 1.1.8. I would expect others to hit this problem soon too, as I wouldn't believe using both these libraries together is that uncommon. 

So I wanted to find out if you had plans to update the ExoPlayer libraries to a newer version? 

Thanks
Mark

**Comment by CHaNGeTe** [comment]
I am preparing a PR with the update, but dunno the ETA.

**Comment by jariwalabhavesh** [comment]
@CHaNGeTe : I am also facing same issue with react-native-track-player and react-native-video
if you can create version that support before android-x as well.

**Comment by matteocollina** [comment]
I have the same issue with `react-native-video 4.4.4` and `react-native 0.60.4`
only in Android, iOS works

![Schermata 2019-08-13 alle 18 12 49](https://user-images.githubusercontent.com/8715726/62957909-fc5b7480-bdf5-11e9-81c9-155432c5dbf9.png)

**Comment by benoitdion** [comment]
We upgraded Exoplayer in #1753! We'll release the change in a 5.1-alpha soon
