### ISSUE TITLE
blank page on Android when refresh many times

### ISSUE THREAD

**Issue by MuhammedFadel** [TheWidlarzGroup/react-native-video#1712]
I am using react-native 0.59.9 and react-native-video 5.0.0 ( exo-player)

Everything works fine in iOS but in android I am getting a blank page when refresh the app many times, is there any solution for this problem ?

**Comment by KaoPengHsiang** [comment]
Same problems
@MuhammedFadel  
Is there any solution have you found?  ><?

**Comment by CHaNGeTe** [comment]
By those refreshes you mean from dev server?

**Comment by KaoPengHsiang** [comment]
@CHaNGeTe 
I use RNRF Actions.refresh , and then the video preview become blank not a black block. looks weird
 ˊ ˇ ˋ"
But it still work when pressing start.

**Comment by MuhammedFadel** [comment]
> By those refreshes you mean from dev server?

yes, also with production version when I close app and run agin same thing happen
