### ISSUE TITLE
Which version is compatible with android 4.4.4 because the latest one doesn't repeat the video

### ISSUE THREAD

**Issue by fouad1994** [TheWidlarzGroup/react-native-video#1716]

**Comment by CHaNGeTe** [comment]
Can you provide more info? I suggest changing the title to Repeat does not work and filling the Issue Template

Are you using android-exoplayer?

**Comment by kevmmdev** [comment]
I am having the same issue, indeed the video does not repeat

"react-native": "^0.58.5",
"react-native-video": "^4.4.2",

**Comment by kevmmdev** [comment]
okay quick solution for me was not to use android-exoplayer.
