### ISSUE TITLE
MKV format doesnt play

### ISSUE THREAD

**Issue by hotdev405** [TheWidlarzGroup/react-native-video#1718]
MKV format videos such as 'https://storage.googleapis.com/staging.theworldvision-48016.appspot.com/sg21080p.NF.DL.H264.Multi.DDP.5.1.MSUBS.Telly.Exclusive/sg2_S02E01_.2019.1080p.NF.DL.H264.Multi.DDP.5.1_[Moviegod.in].mkv' doesnt play or takes too long to load. 

How to fix this ?

**Comment by CHaNGeTe** [comment]
Is the cdn configured for progressive downloading?

**Comment by amerllica** [comment]
Hi dear @CHaNGeTe, Do your community has any plan to support more file types? if not, why you didn't close such these kind of issues? if yes, after these years, why you didn't use something like [**vlckit**](https://code.videolan.org/videolan/VLCKit) to support more file types?
