### ISSUE TITLE
How to understand if a video is paused by controls

### ISSUE THREAD

**Issue by seriiix** [TheWidlarzGroup/react-native-video#1719]
We can use `paused={this.state.pause}` prop to pause/play a video but how can we find out if a video is paused when we use controls as well? `controls={true}`.

**Comment by jonathangreco** [comment]
It seems you already answered your own question... don't you think ?

**Comment by seriiix** [comment]
@jonathangreco When you pause with controls it'll **NOT** update your `this.state.pause`. So `this.state.pause` remains false but the video is paused.

**Comment by codervss** [comment]
@seriiix Have you come up with a workaround for the above stated issue?
