### ISSUE TITLE
No software license

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#172]
Without a software license this software is not legally allowed to be used for any purpose without the express written permission of the author. Please choose a license and add the license file to the code. Conveniently http://choosealicense.com makes the process easy and fast.

**Comment by brentvatne** [comment]
@calvinmikael - here you go! https://github.com/brentvatne/react-native-video/blob/master/LICENSE

**Comment by brentvatne** [comment]
thanks for pointing this out by the way
