### ISSUE TITLE
[URGENT!] Documentation is Wrong

### ISSUE THREAD

**Issue by edgarclerigo** [TheWidlarzGroup/react-native-video#1721]
Following your example to install the `react-native-video` with CocoaPods on the line where you have, 

`pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'`

This doesn't work, it should be for example:

`pod 'react-native-video', :path => '../node_modules/react-native-video'`

**Comment by jonathangreco** [comment]
you can make a pull request for this fix if it's that urgent :) Thanks for your report on this one :)

**Comment by CHaNGeTe** [comment]
Fixed on 00b3eda39d5609a2bddced255f4d85de967be090
