### ISSUE TITLE
Repeat creates a gap when looping on version 5.0.0 but is fine on previous ...

### ISSUE THREAD

**Issue by perottosson** [TheWidlarzGroup/react-native-video#1724]
# Bug

The repeat doesnt work properly on Android using react-native-video v5.0.0. There is a break for about one second in the playback everytime it repeats. When I revert back to v4.4.4 it works perfectly fine. 

However Im getting a warning while installing v4.4.4 that:

> warn The following packages use deprecated "rnpm" config that will stop working from next release:  - react-native-video:

Anyone else noticed this bug with repeat

**Comment by jonstuebe** [comment]
I knew it wasn't working on 5 but had no idea that on the older versions it worked. This is so helpful as I've been trying everything trying to get other libraries working properly.

update: I'm only getting repeat to work on android for 4.4.4. IOS still doesn't loop. Did it ever?
