### ISSUE TITLE
How to get bitrate and bandwidth of video

### ISSUE THREAD

**Issue by pjreact** [TheWidlarzGroup/react-native-video#1726]
How can I get bitrate and bandwidth of video? I need to manage some stat.

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video#onbandwidthupdate

**Comment by joemewes** [comment]
this only works on Android? any solutions for iOS where we want to track this data for analytics purpose. thanks.

**Comment by asallem94** [comment]
I want to know this answer for iOS too

**Comment by ericlifs** [comment]
Any updates on supporting this on ios? I noticed that the prop is commented out here https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.m#L801. Anyone knows another video player library that supports this feature?

Thanks

**Comment by Fedeorlandau** [comment]
Any updates on this? https://github.com/react-native-video/react-native-video/pull/1745 the PRa was created 2 years ago.

**Comment by freeboub** [comment]
onBandwidthUpdate notification added for alpha.10 version
