### ISSUE TITLE
Is there any way of dynamically change the videosource?

### ISSUE THREAD

**Issue by perottosson** [TheWidlarzGroup/react-native-video#1727]
# Question
Is there any way of dynamically change the videosource?

My approach is simply by changing the clip name with a hook, changing video1 to video2. But I was not able to update the videoinstance

This doesnt work:
```
const [clipSelected, setClipSelected] = useState('video1');

<Video  source={require('./' + clipSelected + '.mp4')}
```

Are there any way of doing this?

**Comment by CptFabulouso** [comment]
Does providing key prop help? `<Video key={clipSelected} source={require('./' + clipSelected + '.mp4')} />`

**Comment by Yarkhan** [comment]
For me, this is currently broken on iOS. Switching video sources will log this into the console:
```
Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
```
In my case, I'm loading local files into the <Video /> component (using `source={{uri: path}}`. It may be working with remote files, but I can't confirm that right now.

Changing the prop `key` doesn't solve the issue.
In Android, everything works as expected.

I'm getting this error on all versions of this library in rn 0.59+

**Comment by CHaNGeTe** [comment]
Can you test with this branch?
https://github.com/24i/react-native-video/tree/feature/ios-player-deinit

if it works I will make the PR

**Comment by kennedy0527** [comment]
@CHaNGeTe 
I've tested your code with react-native-video version 5.0.2

now after change video source, previous video wasn't showing anymore but still did not show new video (just display a black screen with a play button which is no functionality)

but audio keeps playing the new source btw

**Comment by wiredmatt** [comment]
Any updates? As @kennedy0527 says the new video won't come up, even using the useState hook.

The onError event of the component outputs the following error:

`com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403`

**Comment by tgreco** [comment]
I am encountering this issue on iOS as well.
