### ISSUE TITLE
How to seek to the "live edge" of an ongoing HLS stream

### ISSUE THREAD

**Issue by canyavall** [TheWidlarzGroup/react-native-video#1728]
We have an HLS stream running, we created a progress bar to be able to move around the asset and with the seek function it works perfectly fine.

My main issue is when I want to go live again... There's any way to reach the edge of the current HLS stream?

I tried with seek(0), seek(-1), seek(new Date.now().getTime()).... but the only way I could get it is with seek(new Date.now().getTime()-9000)

In exoplayer they say soemthing about  a variable (C.TIME_UNSET)
https://github.com/google/ExoPlayer/issues/472
Any idea?

**Comment by CHaNGeTe** [comment]
Are you working with Live videos with Window right?
I had some problems there as well, let me check what was the workaround I used.
I think for ios it was seek(TIME_WHEN_LOAD - CURRENT_TIME + TIME_MAX_WINDOW) but time is reported different in Android

**Comment by flexgrip** [comment]
This is a big deal for me. In my android version, for some reason certain phones open a live stream and instantly peg the timeline slider to the back of the buffer. So the video skips and hops around showing negative integers for the time.

If the user drags the timeline slider forward it fixes it. But it doesn’t seem to happen on all androids.

**Comment by naveenvignesh5** [comment]
Any update on this issue. I am currently using Mux video livestream with `react-native-video`. Manual seek causes issue.

**Comment by nathanguigui** [comment]
You can add the current timestamp in a get parameter of the live url that will reload the component and seek to last moment.

**Comment by pmayer** [comment]
For iOS it should be possible to use `CMTime.positiveInfinity` to seek to live. Is it possible to set this value in `seek()`?

**Comment by techiespace** [comment]
Any update on this issue for iOS and Android?

**Comment by samarthjain10** [comment]
on iOS this seems to work but on android the hls stream starts from the beginning and seekableDuration isn't updating

**Comment by CDBridger** [comment]
bump, was their a resolution to this?

**Comment by charles-mersereau** [comment]
The solution I'm using is to take advantage of the onLoad event. That event gives you the duration of the media, which in an HLS stream reflects the "live edge" of the stream. As long as you've captured a reference of the video component, you can then call seek on the player for the value of the duration which will catch up the player.

I wasn't sure at first if the ref would get set before onLoad, but it's been very consistent for me.

This is my code, the URL is from the service I'm using, 100ms.

```
<Video source={{uri: room.hlsStreamingState?.variants[0].hlsStreamUrl}}
	ref={(ref) => {
		setPlayer(ref);
	}} 
	style={styles.hlsVideo}
	resizeMode='contain'
	onLoad={(props) => {
		player.seek(props.duration);
	}}
/>
```

**Comment by karltaylor** [comment]
> The solution I'm using is to take advantage of the onLoad event. That event gives you the duration of the media, which in an HLS stream reflects the "live edge" of the stream. As long as you've captured a reference of the video component, you can then call seek on the player for the value of the duration which will catch up the player.
> 
> I wasn't sure at first if the ref would get set before onLoad, but it's been very consistent for me.
> 
> This is my code, the URL is from the service I'm using, 100ms.
> 
> ```
> <Video source={{uri: room.hlsStreamingState?.variants[0].hlsStreamUrl}}
> 	ref={(ref) => {
> 		setPlayer(ref);
> 	}} 
> 	style={styles.hlsVideo}
> 	resizeMode='contain'
> 	onLoad={(props) => {
> 		player.seek(props.duration);
> 	}}
> />
> ```

When using a Mux livestream the `OnLoadData.duration` is `0` ☹️

**Comment by freeboub** [comment]
To close this thread, you should seek to duration.
A sample live stream is now available in the basic sample to experiment
