### ISSUE TITLE
Black screen when playing video on Android 4.4 (API 19)  kitkat

### ISSUE THREAD

**Issue by perottosson** [TheWidlarzGroup/react-native-video#1731]
Im getting a black screen when playing video on Android 4.4 (API 19). Not sure what is happening. Works fine on Android 9 (API 28)

Is the library not supported on Android 4.4?

**Comment by grayey** [comment]
exactly same problem  here.. been on this for 4 days. works well on android versuons 9-6

**Comment by perottosson** [comment]
Hi! I found the problem. This is a codec issue both on video and audio. You need to export you movie as Mpeg4. Dont remember which codec I used for the audio but kitkat is very picky about this! 

More info here:
https://developer.android.com/guide/topics/media/media-formats

I ended up doing everything in android studio since I found react native a bit unreliable in this case where I used some highres videofiles with large filesize ...

**Comment by vladpuz** [comment]
+1
