### ISSUE TITLE
After switching tab,Instead of playing current video, all other are playing at once in Andoird

### ISSUE THREAD

**Issue by paddy57** [TheWidlarzGroup/react-native-video#1732]
When i come on tab which has video component, video is not playing.
I have flat list which has video componnt, to render multiple videos,video play smoothly on home screen but when i switch from Home screen to Another screen and come back to home screen, instead of playing current video its playing remaining videos on Android, 

I'm using react-navigation's createMaterialBottomTabNavigator 

Here id my Video Compoent  code

            <View key={this.state.videoIndex} style={{ width: SCREEN_WIDTH, }} >
                <Video
                    repeat
                    paused={this.state.videoPaused}
                    muted={this.state.videoMute}
                    source={{ uri: this.state.source }}
                    ref={ref => {
                        this.player = ref;
                    }}
                    // onBuffer={this.onVideoBuffer}
                    style={{
                        width: SCREEN_WIDTH,
                        height: this.state.height,
                    }}
                />
               
            </View>

Here is my Home Screen code 

 renderItemVideoLike = ({ item, index }) => {
       
        console.log('video Numer', index, this.state.videoNumber);
        return (
                    <View>

                        <VideoComponent
                            item={item}
                            source={source}
                            height={height}
                            videoIndex={index}
                            videoPaused={this.state.videoNumber !== index}
                            videoMute={false}

                        />
          </View>

}

    <FlatList
                    horizontal={true}
                    bounces={false}
                    pagingEnabled={true}
                    keyExtractor={(item) => item.toString()}
                    removeClippedSubviews
                    showsHorizontalScrollIndicator={false}
                    // key={this.state.key}
                    viewabilityConfig={this.viewabilityConfig}
                    data={this.state.videoList}
                    extraData={this.state}
                    renderItem={this.renderItemVideoLike}
                    onViewableItemsChanged={this.onViewableItemsChanged}
                />

**Comment by MarianBe** [comment]
can you show the whole Video Component code please

**Comment by CHaNGeTe** [comment]
I think they use of key prop is related
Can you try to set the same key to the video instance?

**Comment by paddy57** [comment]
I switch to to android player instead of exoplayer and then my problem was
solved

>
