### ISSUE TITLE
Already have some way to build markers in the player?

### ISSUE THREAD

**Issue by marcos-nunes-dev** [TheWidlarzGroup/react-native-video#1733]
basically is a way to mark the timeline video with themes and this kind of stuff

**Comment by MarianBe** [comment]
what exactly do you mean? do you want to add markers to your scrubber? if so, you need to make your own video controls i'm afraid.

**Comment by marcos-nunes-dev** [comment]
@MarianBe like this: https://reactjsexample.com/react-video-player-with-markers/

**Comment by MarianBe** [comment]
@MarcosRenato266 no, i'm afraid this is not built in. you would have to build this yourself.

**Comment by marcos-nunes-dev** [comment]
OK! thx for your attention Marian :D have a nice day
