### ISSUE TITLE
How to keep playing video on moving to other screen using React Navigation

### ISSUE THREAD

**Issue by klodha** [TheWidlarzGroup/react-native-video#1736]
# Question

I have gone through the existing issues in this repository, and those are related to stopping video playback when moving from screen A to screen B, using react navigation.

However, in my app with tab navigation, I want to keep video playback active even while switching the screen. 

Since video playback is internally being created in its own native view, is there any prop or method, by which I can get this behaviour. 

Thanks

**Comment by CHaNGeTe** [comment]
Can you check if you are using page optimizations that are removing the unactive tab from the tree?

**Comment by klodha** [comment]
@CHaNGeTe I am not using anything special, its a fresh react native project. I am using redux and async storage plugin in addition to video plugin.

**Comment by cbothra** [comment]
Hi, did someone figured out Solution for this? I am also facing same problem.

**Comment by CHaNGeTe** [comment]
which nav lib are you using?
RNV version
RN version

**Comment by klodha** [comment]
@cbothra @CHaNGeTe Here is my configuration information,

```config
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
    Memory: 5.57 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native: 0.60.5
```

React native video in my package JSON:
` "react-native-video": "^5.0.0",`
React Navigation:
`"react-navigation": "^3.11.1",`

**Comment by ajimae** [comment]
Please guys, what's the update on this?

**Comment by CHaNGeTe** [comment]
I think the point is your screen itself is being 'released'.
I mean, your ar not pushing to the stack, but resetting the stack.
So if the container view is released, the video is released as well.

Which platform are you experiencing this behaviour?

**Comment by tarahiw** [comment]
did someone figured out Solution for this? I am also facing same problem
