### ISSUE TITLE
Video showing black screen when useTextureView is set to true

### ISSUE THREAD

**Issue by codervss** [TheWidlarzGroup/react-native-video#1739]
# Bug

I am using a FlatList and to properly show videos i have to use textureView instead of surfaceView, but when i set useTextureView to true then the video is black only for android .
I am using exoplayer and 3.2.1 version of react-native-video

## Environment info

React native info output:
npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: 3.2.1

Describe what you expected to happen:

1. Render multiple videos with textureView for exoplayer in android

**Comment by waheedakhtar694** [comment]
in my case i didn't set `useTextureView ` but on android screen always remain black screen with audio is playing. @cobarx any solution of this ? on IOS it works fine.
