### ISSUE TITLE
ExoPlayer with autoLinking ?

### ISSUE THREAD

**Issue by ezranbayantemur** [TheWidlarzGroup/react-native-video#1747]
Is ExoPlayer comes by default with autolink? (RN >60 versions )

If it's not how can we switch to ExoPlayer?

**Comment by CHaNGeTe** [comment]
I will check how to do it.
Indeed I think it is a good topic for https://github.com/react-native-community/react-native-video/issues/1628

**Comment by lemming** [comment]
You can assign custom project directory for react-native-video in `android/settings.gradle` **after** automatic linking like so:

```
rootProject.name = 'MyAwesomeRNApp'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
include ':app'
```

**Comment by ezranbayantemur** [comment]
> You can assign custom project directory for react-native-video in `android/settings.gradle` **after** automatic linking like so:
> 
> ```
> rootProject.name = 'MyAwesomeRNApp'
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> include ':app'
> ```

Thank you so much ! 💪

**Comment by nhjuhoang** [comment]
> Is ExoPlayer comes by default with autolink? (RN >60 versions )
> 
> If it's not how can we switch to ExoPlayer?

create react-native.config

module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};

**Comment by shababcreative** [comment]
Can someone give me the installation instructions for RN >60 versions, I'm lost here :/

**Comment by FaiChou** [comment]
[Here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-autolink-a-local-library) is the explanation:
 
![image](https://user-images.githubusercontent.com/18500846/72062591-0c2ea480-3313-11ea-8791-873ce4be240e.png)

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
"react-native-video": "^5.0.2"

React Native Android Black Screen For Android

**Comment by krishcdbry** [comment]
> [Here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-autolink-a-local-library) is the explanation:
> 
> ![image](https://user-images.githubusercontent.com/18500846/72062591-0c2ea480-3313-11ea-8791-873ce4be240e.png)

Awesome !! It worked.

**Comment by sannjayy** [comment]
what for ios?

**Comment by prayaslashkari** [comment]
How will know I am using Exo player? @krishcdbry @FaiChou @nhjuhoang

**Comment by BasixKOR** [comment]
Assuming ExoPlayer is recommended, I think the workaround shown above should be present in README.
