### ISSUE TITLE
Silent videos cause other applications to stop playback (iOS)

### ISSUE THREAD

**Issue by mattfordham** [TheWidlarzGroup/react-native-video#1754]
# Bug

Silent videos cause other applications to stop playback (iOS).

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
      Memory: 306.28 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/v8.12.0/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 19, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.59.5
```

Library version: 4.4.4

## Steps To Reproduce

1. Implement a `<Video>` tag with `muted`, `volume={0}`, and  "disabled" `selectedAudioTrack` props.

## Expected Results

1. Other applications playing audio (Spotify, etc) should not pause playback.

## Reproducible sample code

```
<Video
  source={'video.mp4'}
  muted
  volume={0}
  selectedAudioTrack={{
    type: 'disabled'
  }}
/>
```

**Comment by CHaNGeTe** [comment]
Will try to implement `disableFocus` https://github.com/react-native-community/react-native-video#disablefocus
on ios as well

By now it should be achievable via
https://www.npmjs.com/package/react-native-audio-session

**Comment by CHaNGeTe** [comment]
Can you checkout this branch?
https://github.com/24i/react-native-video/tree/feature/ios-audioFocus

And pass to the player the prop `disableAudioFocus`?

**Comment by ds8k** [comment]
@CHaNGeTe Tried out those changes you made and they don't seem to work?

**Comment by kinigitbyday** [comment]
@CHaNGeTe I just tried tried from that branch and it seems to work. Background audio kept playing through the silent video with `disableAudioFocus`.

**Comment by kinigitbyday** [comment]
@CHaNGeTe Actually, it works on the simulator, but I couldn't get it to work on an actual device.

**Comment by raynor85** [comment]
A ugly workaround I have found for iOS is adding this code inside `AppDelegate.m` in my RN project to force ALL video instances to behave like if `disableFocus` were always present in every one of them when the app run on an Android device:
```objective-c
// other existing imports
#import <AVFoundation/AVFoundation.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
  // other existing code
}
```
You also need to add `AVFoundation.framework` in your project through `Build phases > Link Binary With Libraries`.

<img width="790" alt="Screenshot 2019-12-21 at 01 09 23" src="https://user-images.githubusercontent.com/5817333/71300643-975cf000-238e-11ea-9602-a5b471ede205.png">

NB: use the search filter on the top right to avoid getting lost on the Xcode UI nonsense!

<img width="800" alt="Screenshot 2019-12-21 at 01 07 01" src="https://user-images.githubusercontent.com/5817333/71300600-3cc39400-238e-11ea-9e1d-d41f8656af26.png">

I have tried to insert that code inside `RCTVideo.m` to be able to mimic the Android behaviour and allow each video behaviour to be controlled independently, but I was not able to make it work. Any suggestion is appreciated.

**Comment by Redge-Ballard** [comment]
@raynor85 When I try to use this approach I get the error "Use of undeclared identifier 'AVAudioSession'" even though I have the framework added in my build phases. Any idea what I might be missing? I'm on Xcode 11.6 if that's relevant.

**Comment by lissau** [comment]
Is there any progress on this issue?

**Comment by chika-kasymov** [comment]
@lissau I believe you can set the `mixWithOthers="mix"` as the video player option. That will add the ability to play audio from multiple apps at the same time.

**Comment by Cygnus2112** [comment]
Doesn't appear to me that `mixWithOthers` is available to use yet.
