### ISSUE TITLE
Videos with audio lags a frame/ Freeze for a moment 

### ISSUE THREAD

**Issue by paddy57** [TheWidlarzGroup/react-native-video#1755]
My video lags a frame then plays smooth if i use videos which has audio,
but if i use the videos which does not have audio then it does not lag. can you help me with that? Thank you.

Here is a demo video - https://streamable.com  "just notice a freeze after 1 sec for a moment only"

Environment:
  OS: macOS 10.14.4
  Node: 10.6.0
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.3 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Library version: react-native-video@3.0.0

## Steps To Reproduce
Play mp4 videos containg audio 

Describe what you expected to happen:
Video should play smoothly with audio

## Reproducible sample code

             <View>
                    <Video
                        repeat
                        resizeMode='cover'
                        poster={this.props.videoThumbnail}
                        posterResizeMode="cover"
                        source={{ uri: this.state.videosSwipe[this.state.videoSwipeNumber] }}
                        ref={ref => {
                            this.player = ref;
                        }}
                        onBuffer={this.onBuffer}
                        onError={this.handleError}
                        style={{
                            width: SCREEN_WIDTH,
                            height: 500
                        }}
                        onLoad={this.onLoad}
                    />

                    <TouchableOpacity onPress={() => this.nextVideo()}>
                        <Text style={{ color: 'white', fontSize: 22, marginTop: 20, }}>Next</Text>
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => this.prevVideo()}>
                        <Text style={{ color: 'white', fontSize: 22, marginTop: 15, }}>Prev</Text>
                    </TouchableOpacity>
                    <Text style={{ color: 'white', marginTop: 10, justifyContent: 'center', alignSelf: 'center', fontSize: 25 }}>{this.state.videoLength}</Text>
                </View>

**Comment by paddy57** [comment]
Hii,
@cobarx Can you help me with this?

**Comment by CHaNGeTe** [comment]
any reason of using `Library version: react-native-video@3.0.0`?
5.x version is released

Also please say which platform you are experiencing this

**Comment by paddy57** [comment]
Hii, i was using 3.0.0 because i saw on git it was stable, but now i had this issue, I upgraded to 5.0.0, it got resolved, thank you for reply. But I really want to know what was the issue in 3.0.0 with videos having audio

**Comment by CHaNGeTe** [comment]
Great to know! I am closing the issue.

**Comment by fdlnfjrrmdni** [comment]
i have same issue, i was using 5.0.2
