### ISSUE TITLE
iOS native controls close callback

### ISSUE THREAD

**Issue by karolis-arbaciauskas** [TheWidlarzGroup/react-native-video#1757]
Hi, I just want to know if there is any way to know when close button was called? For ios I would like to use native controls. But I need to know when back button was pressed

**Comment by jonathangreco** [comment]
Hey, please can you dig into the repo before asking it seems your demands has already been asked so many times I can't count. Plus, I think a pull request is already made on this. Thanks.

**Comment by deepakvirtual** [comment]
Hi, I also need to know if we can have a close button , in some screenshots and other apps i have seen a cross button . How can i display that or i have to handle that manually ?
![Screenshot 2019-11-29 at 6 37 24 PM](https://user-images.githubusercontent.com/55827967/69870953-7c3f1900-12d7-11ea-9ba9-c8a562f24453.png)

Or, it will be great if i can get an event when the controls are displayed and when they gets hidden,  so i can add custom buttons and toggle their visibility according to default controls .

**Comment by florandom** [comment]
Any update on that?? iOS native close callback prop?

**Comment by ethanyuwang** [comment]
also looking for this functionality

**Comment by cenaHara** [comment]
hi all can you help me ios native mute callback

**Comment by nitishfastco** [comment]
any update on this 
i am stuck here,i need to know ,how can i get the callback for native cross button
