### ISSUE TITLE
Can't seek back on encrypted hls VOD playlist

### ISSUE THREAD

**Issue by abdullahoday710** [TheWidlarzGroup/react-native-video#1758]
# Question

i have a simple hls encrypted m3u8 generated by FFmpeg and served through python simple http server:

```
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:16
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="key.bin"
#EXTINF:16.433333,
output0.ts
#EXTINF:14.433333,
output1.ts
#EXTINF:14.166667,
output2.ts
#EXTINF:14.966667,
output3.ts
#EXT-X-ENDLIST
```
it does play fine on react-native-video and i can seek forward.

however i can't seek backwards and the whole playback stops how can i fix this ? or is it a bug in the library ?

**Comment by CHaNGeTe** [comment]
Is key.bin in the same path as the manifest? I guess it is as it plays at first, I don't think it is related, but as you are not setting attributes, can you remove the last commas on EXTINF?

**Comment by CHaNGeTe** [comment]
I also see first segment exceeds the #EXT-X-TARGETDURATION, spec says it should be equal to nearest integer (which is true in your manifest, but I will try playing with it and setting it to 17)

**Comment by abdullahoday710** [comment]
> 
> 
> Is key.bin in the same path as the manifest? I guess it is as it plays at first, I don't think it is related, but as you are not setting attributes, can you remove the last commas on EXTINF?

Yes it is in the same path as the manifest, and the manifest is auto generated so i see no reason to remove the commas although i will try to.

**Comment by abdullahoday710** [comment]
> 
> 
> I also see first segment exceeds the #EXT-X-TARGETDURATION, spec says it should be equal to nearest integer (which is true in your manifest, but I will try playing with it and setting it to 17)

after hours of searching it turns out that i needed to add #EXT-X-ALLOW-CACHE:YES to the manifest and it worked but still a little bit buggy

**Comment by CHaNGeTe** [comment]
great news @3bodyZZ thanks for reporting it back.

What it is buggy now?

**Comment by abdullahoday710** [comment]
> 
> 
> great news @3bodyZZ thanks for reporting it back.
> 
> What it is buggy now?

yeah and i think its because of the server i saw the logs it is very slow at handling get requests, i will try with another server and see.

**Comment by CHaNGeTe** [comment]
Are you setting progressive support on the server for the ts files?

Related Headers: 
```
"Accept-Ranges": "bytes",
 "Cache-Control": "public, max-age=3600",
  "Content-Length": file.size,
```
Server should handle `Range` header on requests
f.e; Range: "bytes=0-4" 

As youy use simple server from python, maybe this helps:
https://gist.github.com/wassname/d7582bbcbd91189f80d8624ba46542c0

P.S: I think Xampp has Range support by default, not sure
