### ISSUE TITLE
Suport more protocols

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1759]
add support for all these Protocol: RTMP/RTMPT/RTMPE/RTSP/HLS/HTTP(S)-FLV Video codec: H.264, H.265,FLV, VP6, MPEG4 Audio codec: AAC, MP3, SPEEX, NELLYMOSER, ADPCM_SWF, G.711

**Comment by CHaNGeTe** [comment]
Any guide for this?
AVPlayer doesn't support RTMP streaming, we will need to make sth similar to VLCkit or ffmpeg approach.
