### ISSUE TITLE
[Android] textTracks does not work?

### ISSUE THREAD

**Issue by brooklyn097** [TheWidlarzGroup/react-native-video#1760]
# Question

I've done a lot of research but still can't make it works. Here is my react-native-video configs:
```
<Video
ref={(ref) => this.videoPlayer = ref}
source={{
uri: 'https://video.com/file.mp4',
}}
rate={1.0}
volume={1.0}
muted={false}
paused={!this.state.isPlaying}
resizeMode={'contain'}
playWhenInactive={false}
playInBackground={false}
ignoreSilentSwitch={'ignore'}
progressUpdateInterval={250.0}
onLoadStart={this._onLoadStart}
onLoad={this._onLoaded}
onProgress={this._onProgressChanged}
onEnd={this._onEnd}
onError={this._onError}
onBuffer={this._onBuffering}
selectedTextTrack={{
    type: "title",
    value: "English CC"
}}
textTracks={[
    {
        title: "English CC",
        language: "en",
        type: TextTrackType.VTT, // "text/vtt"
        uri: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
     },
     {
        title: "Spanish Subtitles",
        language: "es",
        type: TextTrackType.SRT, // "application/x-subrip"
        uri: "https://durian.blender.org/wp-content/content/subtitles/sintel_es.srt"
     }
 ]}
 style={{width: this.state.videoWidth, height: this.state.videoHeight}}/>
```

The text tracks uri are from documents, i also try several different sources to make sure that there is no corss-origin blocked but still won't work. I've console.log in onLoad function to see if the textTracks are loaded but the result only like this:

```
canStepForward:true
canStepBackward:true
canPlayReverse:true
canPlaySlowReverse:true
canPlaySlowForward:true
canPlayFastForward:true
orientation:landscape
natureSize:{
    height:1080
    width:1920
}
currentTime:0
duration:10144.009
```
There is no textTracks loaded. So what's wrong with my code?

**Comment by CHaNGeTe** [comment]
Which platform are you checking?

**Comment by brooklyn097** [comment]
> Which platform are you checking?

Hi, I'm testing on Android only

**Comment by CHaNGeTe** [comment]
Are you using android or android exoplayer?

**Comment by brooklyn097** [comment]
> Are you using android or android exoplayer?

Can you please tell me how do i check which version I am using? I've done with default installation and above configs. sorry for that noob

**Comment by CHaNGeTe** [comment]
Don't worry
https://github.com/react-native-community/react-native-video#android-installation

Open android/settings.gradle and check if:
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

or 
`
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

**Comment by CHaNGeTe** [comment]
If you are using the second one, I will recommend you to change it to the exoplayer one

**Comment by mehrankhandev** [comment]
Also one more point i want to add if react-native version >0.60 and autolinking will not add  "android-exoplayer" so you have to add this line to **android/settings.gradle** .  Check this issue #1747

```
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-531736338

**Comment by brooklyn097** [comment]
I thought autolinking will make all the features work. I've just done manual linking and change to use ExoPlayer and  It's working perfectly now. Thank you guys so much for supporting me.
