### ISSUE TITLE
Roadmap discussion

### ISSUE THREAD

**Issue by CHaNGeTe** [TheWidlarzGroup/react-native-video#1761]
This is the place to discuss feature additions to RNVideo.

**First one**, is to follow up https://github.com/react-native-community/react-native-video/issues/1628 and **stabilize** the project.

**After that**:
- Basic DRM https://github.com/react-native-community/react-native-video/issues/1761#issuecomment-533792169
- AudioManager https://github.com/react-native-community/react-native-video/issues/1761#issuecomment-533791810
- Download / Offline playback https://github.com/react-native-community/react-native-video/issues/1761#issuecomment-533791933

**Comment by CHaNGeTe** [comment]
**AudioManager**

- Refactor android audio manager
- Provide same functionality for iOS

Can help:
https://github.com/BonnierNews/react-native-audio-session

Related PRs:
https://github.com/react-native-community/react-native-video/pull/1415

Related issues:
https://github.com/react-native-community/react-native-video/issues/1754
https://github.com/react-native-community/react-native-video/issues/1707
https://github.com/react-native-community/react-native-video/issues/1765

Possibility to play on earpiece:
https://github.com/react-native-community/react-native-video/issues/835

**Comment by CHaNGeTe** [comment]
**Download / Offline playback**
- Both for iOS / Android

Notes: I have a working version, but needs heavy refactoring (using ExoPlayer download service and AVAggregateDownloadTask on iOS)

Related Issues:
https://github.com/react-native-community/react-native-video/issues/1762

**Comment by CHaNGeTe** [comment]
**Basic DRM Support**
- Both for iOS / Android
iOS: fairplay
Android: Widevine (ATV & mobile), Playready (only ATV), Clearkey?

PRs:
- (Main) https://github.com/react-native-community/react-native-video/pull/1445
- https://github.com/react-native-community/react-native-video/pull/1382
- https://github.com/react-native-community/react-native-video/pull/858
- https://github.com/react-native-community/react-native-video/pull/789

Related Issues:
https://github.com/react-native-community/react-native-video/issues/1390
https://github.com/react-native-community/react-native-video/issues/1198
https://github.com/react-native-community/react-native-video/issues/1093
https://github.com/react-native-community/react-native-video/issues/546
https://github.com/react-native-community/react-native-video/issues/518

**Comment by khat33b** [comment]
@CHaNGeTe Will there be a new release soon with the integration of DRM, AudioManager and Download / Offline playback? There hasn't been a release for the past 7 months.

**Comment by v-vashchenko** [comment]
Hello! May be offtopic, but could someone comment the downgrade of main package version from 5.1.0 to 4.4.5? unfortunatly can't find any info about the action(

**Comment by v-vashchenko** [comment]
^^ was facing the strange issue with 5.1.0 on android: some videos stopped while playback and never resumed, pre-testing of 4.4.5. shows up a great result! thanks to contributors!!
