### ISSUE TITLE
Play from source which is still downloading

### ISSUE THREAD

**Issue by muz786** [TheWidlarzGroup/react-native-video#1762]
Hi,

I wanted to avoid the bottleneck to wait 4 5 seconds before a video starts to stream using the URL on devices with slower internet connection.
To solve the problem, I started downloading the video in advance on app load. On video screen I gave the path to the local video file which is still downloading but it does not play and give the error -1 which i think is EOF exception.To summarize the video cannot play until the whole file is downloaded. 

I looked at the mp4 structure and figured that the metadata of mp4 file is at the end of file by default so I also tried by reconfiguring the video encoding to place this metadata at the start of the file using ffmeg but still it did not work. 

Is there any way to avoid the EOF exception on video file that is still downloading in progress?

Any help will be highly appreciated.

**Comment by CHaNGeTe** [comment]
For iOS there is video-caching setup, check https://github.com/react-native-community/react-native-video/tree/master/ios/VideoCaching

I have still not played with it, but maybe @cobarx or @n1ru4l can provide you some help there.

I know another method, but is not yet implemented on the repo (but it is on roadmap https://github.com/react-native-community/react-native-video/issues/1761#issuecomment-533791933):
For iOS: AVAssetDownloadTask(mp4) / AVAggregateTask (hls, ...) can provide you an asset that can be feed to the AVPlayer instance.
https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/using_avfoundation_to_play_and_persist_http_live_streams
For Android: You can share a cache betwen ExoPlayerDownloadService and ExoPlayer instance.

**Comment by eddyjusufi** [comment]
@CHaNGeTe Is there currently a way on the JavaScript side of the app to check whether a file has been cached? For example, by having the media's source can we check whether that source has been cached or not?

**Comment by n1ru4l** [comment]
> For iOS there is video-caching setup, check https://github.com/react-native-community/react-native-video/tree/master/ios/VideoCaching
>
>I have still not played with it, but maybe @cobarx or @n1ru4l can provide you some help there.

Check: https://github.com/react-native-community/react-native-video/blob/master/docs/caching.md

**Comment by alexstroukov** [comment]
`bottleneck to wait 4 5 seconds before a video starts to stream using the URL`

@muz786 one ~~solution~~ workaround to this is to stop using `onLoad` as your indicator that the video is ready to play. Instead, wait for the first progress tick to pause your video on the first frame and turn off your loading state. 

```
  const [isLoading, setLoading] = React.useState(true);
  const [isPaused, setIsPaused] = React.useState(false);
  const onProgress = React.useCallback(
    () => {
      if (isLoading) {
        setLoading(false);
        setIsPaused(true);
      }
    },
    [isLoading],
  );

<Video
  paused={isPaused}
  onProgress={onProgress}
/>
```
