### ISSUE TITLE
Audio Mixing

### ISSUE THREAD

**Issue by VeenaCPE** [TheWidlarzGroup/react-native-video#1765]
# Bug

  Play an audio from different app in background. Now click play video from your application Background audio is mixing with the video of your application. 

## Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Expected behaviour
The background audio should pause and video in the foreground should play

**Comment by CHaNGeTe** [comment]
Do you have disableFocus prop added?

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/blob/master/README.md#disableFocus

Which version of the library are you using?

**Comment by VeenaCPE** [comment]
I am using "react-native-video: 4.4.0". Yes, I have added the props disableFocus by default it is set to false.
