### ISSUE TITLE
Proposal: Migrate native code to Kotlin and Swift

### ISSUE THREAD

**Issue by benoitdion** [TheWidlarzGroup/react-native-video#1767]
Following up on some of the good discussion in #1628 and a suggestion from @CHaNGeTe I wanted to start a new proposal: Migrate native code to Kotlin and Swift.

Pros: 
- Safer, more modern and productive languages recommended by Google And Apple.
- More familiar to developers coming from the native world, might increase contributions

Cons:
- Less common in the react-native world. react-native core is still java/objective-c.
- Kotlin is a new dependency some react-native apps may not have yet.

**Comment by nickfujita** [comment]
Here is a PR for the Swift conversion. Would be great if anyone has time to give it a try.
https://github.com/react-native-video/react-native-video/pull/2527
