### ISSUE TITLE
type: 'mov' causes error when it's a .mov

### ISSUE THREAD

**Issue by andresn** [TheWidlarzGroup/react-native-video#177]
Please correct me if I'm wrong, but today it seems "type" is a required config for both .mov, .mp4, and .mp3 files. Otherwise, I see the "[NSURL initFileURLWithPath:]: nil string parameter" error.

I'm running:
react-native-video: 0.7.1
react-native-cli: 0.1.10
react-native: 0.22.2

Also, communicate the neat feature of being able to play mp3s standalone.

**Comment by andresn** [comment]
I'm not sure what changed, but it doesn't look like type is required. mov being specified actually causes a nil error, so updated issue's title.

**Comment by mattapperson** [comment]
@andresn still an issue?
