### ISSUE TITLE
VideoCaching: library not found for -lObjC

### ISSUE THREAD

**Issue by igor-lemon** [TheWidlarzGroup/react-native-video#1770]
# Bug

I can't compile the Cached version.
I have an error: 
`ld: library not found for -lObjC`

![image](https://user-images.githubusercontent.com/14764799/65506084-6fff9f80-ded3-11e9-93f5-10c1e22846a0.png)

## Platform
iOS

## Environment info

  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 291.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 26.0.2, 27.0.3, 28.0.3
        System Images: android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: 5.0.2

## Steps To Reproduce

1) pod 'react-native-video/VideoCaching',
    :path => '../node_modules/react-native-video/react-native-video.podspec'
2) Compile the app

**Comment by SeanDunford** [comment]
@igor-lemon  where is the `SPTPersistentCache.podspec` located?
