### ISSUE TITLE
video show at the back when install in tvbox

### ISSUE THREAD

**Issue by andrewchin1193** [TheWidlarzGroup/react-native-video#1771]
![97F5BFA5-4D2A-4301-A3B1-50F33C2B487C](https://user-images.githubusercontent.com/38956347/65516544-c42a7400-df13-11e9-8c07-1020a784e1c5.jpg)

After i install release apk into tvbox, video is showing at the back. Is anyone know how to fix this issue?
Android Tv Box version:
Android 4.4.2
React native Version:
"react-native": "0.59.8",
"react-native-video": "^5.0.0",

Source code:

    componentWillMount() {
        const { navigation } = this.props;
        const item = navigation.getParam('item');
        this.setState({ txtVideoUrl: PICTURE_URL + item.song.filePath })
    }

    render() {
        return (
            <ImageBackground source={Images.background1} style={{ width: '100%', height: '100%' }} blurRadius={5}>
                <Video source={{ uri: this.state.txtVideoUrl }}   // Can be a URL or a local file.
                    ref={(ref) => {
                        this.player = ref
                    }}                                      // Store reference
                    onBuffer={this.onBuffer}                // Callback when remote video is buffering
                    onError={this.videoError}               // Callback when video cannot be loaded
                    resizeMode={'cover'}
                    style={styles.backgroundVideo} />

            </ImageBackground>

        )
    }
}

**Comment by CHaNGeTe** [comment]
Is the ImageBackground the layer on top?

**Comment by andrewchin1193** [comment]
is not about the ImageBackground, It's still the same even i removed it.

**Comment by CHaNGeTe** [comment]
What is the dotted image then?

**Comment by CHaNGeTe** [comment]
Make sure nothing has zIndex set to a higher value, or try to increase zIndex of the video
