### ISSUE TITLE
domain = AVFoundationErrorDomain , code = -11839, target = 19803

### ISSUE THREAD

**Issue by jigarkbarot** [TheWidlarzGroup/react-native-video#1774]
I am using a local media file and streaming url from cloud server.

Here is sample url:
https://d192a4z5wljn2.cloudfront.net/RYC0E8H253bP/hoookedup/5414/v3m47XH1uM.mp4

I was tested on the ios device & I have load 25-30 and more videos on flatlist.
It says:
domain = AVFoundationErrorDomain , code = -11839, target = 19803

From apple doc, the error code -11839 is AVErrorDecoderTemporarilyUnavailable.
The appropriate decoder is currently not available.

Can someone suggest how to fix this error?

**Comment by CHaNGeTe** [comment]
Are you rendering multiple video instances?

**Comment by LeviWilliams** [comment]
@CHaNGeTe he would be because he's rendering 25-30 more on a flatlist

**Comment by CHaNGeTe** [comment]
I would suggest make them show poster and paused until clicked, or at least track the visibility of the items inscreen (https://facebook.github.io/react-native/docs/virtualizedlist.html#viewabilityconfigcallbackpairs) and conditionally render them

**Comment by jigarkbarot** [comment]
@CHaNGeTe  I already write that code using (https://facebook.github.io/react-native/docs/virtualizedlist.html#viewabilityconfigcallbackpairs) but it doesn't work

**Comment by jigarkbarot** [comment]
@CHaNGeTe @LeviWilliams 

Here is my sample code :
```
this.viewabilityConfig = {viewAreaCoveragePercentThreshold: 50};


_onViewableItemsChanged = (props) => {
    const changed = props.changed;
    const viewableItems = props.viewableItems;
    
    changed.forEach((item) => {
        if (!item.isViewable) {
            this.videoRef["Video_Scroll_" + item.index].refVideo.pausedVideo()
        }
    })
    viewableItems.forEach((item) => {
        if (item.isViewable) {
            this.videoRef["Video_Scroll_" + item.index].refVideo.playVideo()

        }
    })
}



<FlatList
    data={videoList}
    extraData={videoList}
    renderItem={({item, index}) => {
        return (
            <View>
            <MyVideoCard
                index={index}
                totalItems={videoList.length}
                item={item}
                ref={(ref) => this.videoRef = {
                    ...this.videoRef,
                    [`Video_Scroll_${index}`]: ref
                }}
                playVideo={this.videoPaused}
            />
            </View>
        )
    }}
    keyExtractor={(item, index) =>index.toString()}
    viewabilityConfig={this.viewabilityConfig}
    onViewableItemsChanged={this._onViewableItemsChanged}
/>

```
If i am wrong let me know.

**Comment by CHaNGeTe** [comment]
I think it is not recommended to use index as key, but apart of it:
-pausedVideo() just pauses the video, but does not conditionally render? I will recommend to "free" the instances that are not in screen.
-when viewable items change, are you calling playVideo() even if they are already playing?
I mean,
viewable group A: 0 1 2 3 4 5 6
viewable group B: 1 2 3 4 5 6 7 (you scrolled, all items are the same but one pops out and new one enters, are you calling again playVideo() for 1-6 because they are `viewableItems` but they were already `viewableItems` in the previous `_onViewableItemsChanged` call ?

Can you share a little standalone example project?

**Comment by CHaNGeTe** [comment]
Can you try adding `removeClippedSubviews` to your FlatList?
And `minimumViewTime=600`  on `viewabilityConfig`

**Comment by jigarkbarot** [comment]
@CHaNGeTe

Please check sample file:
https://gist.github.com/jigarkbarot/4f9e286d2f030b6a5df530fc8cafcd88

I have checked with minimumViewTime=600 on viewabilityConfig but not working

**Comment by igor-lemon** [comment]
Huh. I have the same issue...

**Comment by igor-lemon** [comment]
@jigarkbarot try to add this props to FlatList

```
windowSize={4}
initialNumToRender={0}
maxToRenderPerBatch={1}
removeClippedSubviews
```

**Comment by jigarkbarot** [comment]
@igor-lemon  it's working Thank you so much
