### ISSUE TITLE
Video + IMAGE in one Carousel

### ISSUE THREAD

**Issue by DungBuiDeveloper** [TheWidlarzGroup/react-native-video#1775]
I have a carousel of videos and images, my video is always the first element and autoplay however if my data is how long it will render many videos and make the audio repeat.

Libraries used

react-native-snap-carousel

**Comment by rajatTemaniya** [comment]
This plugin having an issue. I guess  it will load all the data at first & start autoplay for all video tag. Don't know why

I also faced this issue.
In my case: I have 2 images and 1 video at the end. Whenever carousel active my video is loaded and video track will start playing.

Fixing: 
const [videoPlayPause, setVideoPlayPause] = useState(**true**)

1) Set use state boolean variable true at initial
 <Video **paused**={**videoPlayPause**} />
 
 2) Get the index when swipe or Next will perform match the index of data. if sliding index is ur video. set the pause variable false. ur video will start playing.
 
 <Carousel
  **onSnapToItem**={index => {
                    if ( index == dataLength -1 ) {
                        console.log('Boom Index Play:', index);
                        **setVideoPlayPause**(false) 
                    }
                }}
/>
