### ISSUE TITLE
Can't load multiple video on scrollView

### ISSUE THREAD

**Issue by jigarkbarot** [TheWidlarzGroup/react-native-video#1781]
I have multiple videos and images in the grid view using parallax scrollView. If I scroll to large list on the screen then some video not load. It displays blank view.

Here is sample :
```
<Scrollview>
photoAndVideoGallery.map((item,index)=>{
return(
item.type ==="image"?
<Image source={{uri:item.url}} style={} />
:
<Video 
source-{{uri:item.url}} style={} 
paused={true}
muted={true}
onError={this.videoError}
bufferConfig={{
minBufferMs: 15000,
maxBufferMs: 50000,
bufferForPlaybackMs: 2500,
bufferForPlaybackAfterRebufferMs: 5000
}}
/>
/>
)
})  
</Scrollview>
```

Please help me out. I am stuck on this stuff.

**Comment by HardikDhanani** [comment]
same issue.

**Comment by keithpickering** [comment]
Why was this closed? I'm experiencing the same issue and it's easily replicable.

**Comment by freeboub** [comment]
Shall be follow up in https://github.com/react-native-video/react-native-video/issues/2668
