### ISSUE TITLE
How to start the video from where it was left before closing the app?

### ISSUE THREAD

**Issue by Vandanabisht17** [TheWidlarzGroup/react-native-video#1783]
I am trying to add a feature to start a video from where it was left . Can anyone help me please?

**Comment by swizes** [comment]
you need to store the current state of the video in asyncstorage and once the app is on foreground, use the timestamp to continue

**Comment by CHaNGeTe** [comment]
That's it, for now you have to store last reported progress in device's AsyncStorage.
Thanks @swizes

**Comment by Vandanabisht17** [comment]
I'll try using asyncstorage .
Thanks @swizes

**Comment by gazedash** [comment]
Note that at least on previous versions of `react-native-video` you had to wait until onLoad completion before using seek method, otherwise seeking wouldn't happen. If you have met this problem, now you know what to do.
Actually, the fix on app side is not that hard, so it's not a big problem.

**Comment by Vandanabisht17** [comment]
Thank you @gazedash  Actually i am getting the same seeking issue and i am trying to fix it.
