### ISSUE TITLE
Video controls always is showing

### ISSUE THREAD

**Issue by igor-lemon** [TheWidlarzGroup/react-native-video#1786]
If I put Video component in FlatList I see video controls.
Any params, like controls: false, fullscreen: false, can't be able to disable these controls.

iOS 13.1, 
Lib version v5.0.2 (but it reproduced on old versions too)

Any thoughts?

**Comment by igor-lemon** [comment]
Found a reason.
If I put something inside the Video component I'll see the controls.

This is my case with incorrect controls
```js
<Video ...>
   <Text>FOO</Text>
</Video>
```

What need to change for correct controls work
```js
<>
  <Video ... />
  <Text>FOO</Text>
</>
```

**Comment by CHaNGeTe** [comment]
Seems this code is related:
https://github.com/react-native-community/react-native-video/blob/master/ios/Video/RCTVideo.m#L1438-L1441

Is assuming that every child view added is controls. I will have to take a look on that.
For now setting the childs as siblings as @igor-lemon suggests workarounds it
