### ISSUE TITLE
gradle build - :react-native-video:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by givik** [TheWidlarzGroup/react-native-video#1789]
# Bug

```
> Task :react-native-video:compileDebugJavaWithJavac FAILED
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java:3: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;
                                 ^
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java:5: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ResizeMode.java:3: error: package android.support.annotation does not exist
import android.support.annotation.IntDef;
                                 ^
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ResizeMode.java:33: error: cannot find symbol
    @IntDef({
     ^
  symbol:   class IntDef
  location: class ResizeMode
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java:75: error: cannot find symbol
    @StringDef({
     ^
  symbol:   class StringDef
  location: class VideoEventEmitter
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java:72: error: cannot find symbol
        shutterView.setBackgroundColor(ContextCompat.getColor(context, android.R.color.black));
                                       ^
  symbol:   variable ContextCompat
  location: class ExoPlayerView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors
```

## Platform

* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 34.75 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 16, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.2, 27.0.0, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2
```

Library version: 4.4.2

**Comment by olinations** [comment]
Not sure if you fixed this yet or not, but here is how I fixed it... 

In these 2 files...

.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java:3: error: package android.support.annotation does not exist
import android.support.annotation.StringDef;

.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ResizeMode.java:3: error: package android.support.annotation does not exist
import android.support.annotation.IntDef;

replace ``android.support`` with ``androidx``

for this one...

.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java:5: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;

replace  ``android.support.v4`` with ``androidx.core``

**Comment by lumixraku** [comment]
but it says 
/repos/ViroSample/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/VideoEventEmitter.java:3: error: package androidx.support.annotation does not exist
import androidx.support.annotation.StringDef;

**Comment by oguennec** [comment]
Thanks @olinations, I had the same issue with react-native-video": "^4.4.5" on the following environment and fixed it with your changes that I applied using [patch-package](https://github.com/ds300/patch-package).

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by mkamals** [comment]
I am facing the above issue in the version 4.4.5 even though I have this two lines in the gradle.properties file.

android.useAndroidX=true
android.enableJetifier=true

I had to manually change the import lines in the node_modules like @olinations said.

**Comment by ghost** [comment]
> 感谢@olinations，在以下环境中我对react-native-video“：” ^ 4.4.5“遇到了相同的问题，并使用您使用[patch-package](https://github.com/ds300/patch-package)进行的更改对其进行了[修复](https://github.com/ds300/patch-package)。
> 
> ```
> System:
>     OS: macOS Mojave 10.14.6
>     CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
>     Memory: 1.49 GB / 16.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
>     Yarn: 1.22.4 - /usr/local/bin/yarn
>     npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
>     Android SDK:
>       API Levels: 23, 25, 26, 27, 28, 29
>       Build Tools: 27.0.3, 28.0.3, 29.0.0
>       System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
>   IDEs:
>     Android Studio: 3.4 AI-183.6156.11.34.5522156
>     Xcode: 10.3/10G8 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.9.0 => 16.9.0
>     react-native: 0.61.5 => 0.61.5
> ```

Can you tell me how to use it?

**Comment by MartinPavlik** [comment]
Any update on this? For no apparent reason it started giving me this error today :cry: 

LOL and after I run `npx react-native run-android` it was possible to also build production, anyone has an idea why? :sweat_smile:

**Comment by lumberman** [comment]
`react-native` do jetify for you (convert old android modules to new format) when building directly you need to add `$> npx jetify` to solve the problem with module migration
