### ISSUE TITLE
Video is not played on iOS simulator

### ISSUE THREAD

**Issue by volodyad** [TheWidlarzGroup/react-native-video#179]
Have tries both local and remote url,
have tried 5, 6 , 6s versions
in xcode console it shows - ERROR:   316 errro: -66680
when I try to debug  RTCVideo.m it shows 
_playerItem.error.code = -11800
NSUnderlyingError = NSOSStatusErrorDomain

**Comment by philmower** [comment]
Unfortunately having worked with native objective C, Xamarin and now React Native, I have never seen a video play successfully in the simulator. Although I have heard that one or two very specific codecs may work.

This is one of many shortcomings of the simulator itself rather than this particular plugin or React Native. I'm afraid you'll need to test on a real device!

**Comment by philmower** [comment]
Digging a little deeper, it appears that playback from a local video file does work in the simulator! Still no luck with streaming though.

**Comment by diehell** [comment]
@philmower can you share your code on how you do it in simulator. I can't get it to work. :(

**Comment by mattapperson** [comment]
this is an iOS simulator bug 😞

**Comment by cparjaszewski** [comment]
@mattapperson how can you just simply close this issue? iOS simulator is a #1 development tool to developing iOS apps, how developers can know the video is not playing in their default development sandbox? 

I personally don't like such "close-an-issue" behaviour / approach on Github, when a lot of useful bug reports are randomly being closed, without even voting or discussing if the issue should be closed.

PS. This is still an issue and it's Q4 2017.

**Comment by mattapperson** [comment]
@krzysztofp The issue is not one of "it only exists on the simulator" but that the simulator itself has a bug. There is nothing to fix here. So unless you work for apple or have found a fix or a work-around, there is nothing to discuss.

**Comment by cparjaszewski** [comment]
@mattapperson as said before, sometimes the video is playing in the Simulator, so I doubt it's an iOS Simulator issue, looks to me like another excuse how to close and not fix a problem.

You also have not provided any proof this is a bug on Apple's side, so this is rather an opinion, not a matter of fact. Very disappointing. I cannot deploy this to my client as I cannot test it.

**Comment by cparjaszewski** [comment]
I really think you should build something that works both in sandbox and production environments, otherwise it's half-usable.

EDIT:
I also think if you're 100% sure this is iOS Simulator bug, you should investigate it, report to Apple and refer in this ticket as an related issue, so the community can know they should be pinging and following up the Apple's team, their issue tracker is pretty active, so they should have resolve this issue pretty quick.

But again - I really doubt this is an iOS Simulator issue. For sure this is a simple issue to be fixed from Obj-C perspective.

**Comment by mattapperson** [comment]
@krzysztofp I think you should appreciate the time donated by volunteers that you are using for free. Have a fix or an idea? great I will be more then happy to re-open the issue. If you don't I suggest you find another project to troll

**Comment by cparjaszewski** [comment]
@mattapperson sure - but on the other hand nobody is forcing you to volunteer. I'm just not accepting the fact so many issues are being closed without a real reason, so from my perspective they are just excuses not to really work and solve the problem (which is fine in a volunteer project, right?) - but please just don't close a ticket unless you're 100% sure - as you're also wasting a lot of time of other's people using your tool and cannot test it - therefore we need to find a way-around, so please respect both sides' time.

**Comment by mattapperson** [comment]
@krzysztofp How am I wasting peoples time when closing an issue where no one has a solution, and all those with experience with an issue say it is not fixable? If someone is able to find a fix they can open a PR. If they find a work-around they can still paste it here. The fact that this is closed is because no one has an answer in spite of many hours of research and testing. Sorry if this offends you or is not how you would run the project but it is how we are doing things.

**Comment by cparjaszewski** [comment]
@mattapperson a digression - I'm looking into this bug right now, should have a solution shortly.

I'm just saying - there should be rules to open a ticket and rules to close a ticket.

I've seen many times people opening tickets for wrong reason, but this ticket is 100% valid (and still actual which is frustrating, taking into consideration the fact it's ~1.5 year later).

I think this time you've broken rules of closing a ticket from the common sense perspective - by providing a fact "this is an iOS bug" without:
a) proving this fact (so it is actually an opinion and a discussion is required)
b) reporting this bug to Apple and referencing this ticket here or asking somebody to do the same if you're too busy
c) suggesting anything, like "we should look into it deeper" or "we should report this to Apple" or "we should write our own iOS Simulator" or suggesting a workaround for people without an iPhone to test this - so people like me are left with nothing / a dead-end


Maybe I'm wrong - but think of this from the opposite perspective (user of your library). How frustrating it is to report a VALID issue and seeing it closed without any proper reason or hope for the future fix. This is just wrong IMO.

**Comment by mattapperson** [comment]
Having an issue closed does not mean the issue will never be fixed. That is what you are mistaking here. And you are in fact proving this by working on a fix. Closing an issue means it is not ACTIVELY being worked on. You are confusing closing and locking of issues.

Your points about not providing work are nice, and ideals. At the end of the day I do not always have the time to do that, so I do the best I can for the community. If you think you can maintain this project better then I am happy to discuss with you you taking over maintainer-ship of this module

**Comment by cparjaszewski** [comment]
@mattapperson maybe you're right - but can you agree with me, when you're closing a ticket there should be at least some disclosure what should happen next? Some people (like me) can also have a feeling you're closing this and this never will get fixed etc. So - maybe more transparency and call to action is needed?

**Comment by mattapperson** [comment]
@krzysztofp in a perfect world, yes. Again, you are talking about free software and donated time. If you look at past issues you will note that when that time exists I and others have posted that information. Here I felt it is sufficient given that others have also posted that similar issues exist in other platforms and native apps themselves.

**Comment by mattapperson** [comment]
As a maintainer it is 100% impossible to make every last person happy. I am sorry that you are currently one of the people that are unhappy. My offer remains, take the wheel, or I respectfully ask that you remain silent on the issue.
