### ISSUE TITLE
Video controls stick when scrolling

### ISSUE THREAD

**Issue by Tommoore96** [TheWidlarzGroup/react-native-video#1792]
Using version 5 and tried 5.0.2.  Both have the same error where if I am shown the video controls they will stick in the same position even when scrolling, only disappearing after a few seconds.

Here is my code:

`    <View
      style={{
        backgroundColor: 'white',
        padding: 15,
        marginTop: 13,
        width: '100%',
        // justifyContent: 'flex-start',
        borderRadius: 5,
      }}>
              <Video
                controls={true}
                resizeMode="cover"
                source={{ uri: video.content }}
                paused={true}
                style={{
                  height: 200,
                  width: '100%',
                  marginVertical: 10,
                  top: 0,
                  left: 0,
                  bottom: 0,
                  right: 0,
                  flex: 1,
                }}
              />
          </View>`

And here are some screenshots of the issue:
![Screenshot_20191014-142929_SchoolSpiderParentApp](https://user-images.githubusercontent.com/27972790/66758385-123cf280-ee96-11e9-9e04-86943e6230bc.jpg)
![Screenshot_20191014-142926_SchoolSpiderParentApp](https://user-images.githubusercontent.com/27972790/66758401-19640080-ee96-11e9-876e-7ba39e093181.jpg)

**Comment by Krypternite** [comment]
did you find a fix for this ?

**Comment by Tommoore96** [comment]
No, I just used an iframe through webview to display the video instead.

**Comment by djpetenice** [comment]
Have the same issue - could do with a fix for this. Controls seems in fixed position.

**Comment by GuestInCorle** [comment]
I have the same issue. React Native 0.61.5, React Native Video 5.0.2 with ExoPlayer.

**Comment by jakubgrzelak** [comment]
@GuestInCorle @djpetenice any luck ... I am facing the same problem :(

**Comment by sujithln** [comment]
Any solutions?

**Comment by GarryLaly** [comment]
Same issue, any solution for this?

**Comment by riteshchoudhary199** [comment]
same issue any luck ?

**Comment by TalhaAbbas55** [comment]
why closed this issue when it is still preset 😭

**Comment by TalhaAbbas55** [comment]
why close this issue when it is still present 😭

**Comment by gkueny** [comment]
@TalhaAbbas55 , Do you try with v5 or v6 ?

v5 are not maintained anymore, and I can not reproduce the issue in `react-native-video@6.0.0-rc.0`.
If you still reproduce the issue can you share a simple repro ?
