### ISSUE TITLE
onBuffer doesn't work as expected anymore

### ISSUE THREAD

**Issue by paschaldev** [TheWidlarzGroup/react-native-video#1795]
# Bug

The `onBuffer` callback is always `true` after upgrading to version 5. It never returns `false` even when streaming `m3u8` smoothly. Prior to upgrading to the latest version, I was on version `4.4.1`.

I want to be able to show a spinner while a video is buffering and remove the spinner when its done buffering youtube style. I stored the buffer value in state. This was working perfectly in the previous version until I upgraded and now the spinner is inifinite because `onBuffer` is never false.

## Platform

* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 62.73 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
```

Library version: 5.0.2

## Steps To Reproduce

```js
<Video 
                            paused={paused}
                            source={{
                                uri: this.props.navigation.getParam('uri')
                            }}
                            onBack={this.goBack}
                            ref={videoPlayer => this.player.ref = videoPlayer}
                            onEnd={this.onVideoEnd}
                            onLoad={this.onVideoLoad}
                            onProgress={this.onProgress}
                            onBuffer={this.onBuffer} /* <=== Here *
                            onReadyForDisplay={() => { /*Had to manuever temporarily with this but just at the start */
                                this.setState({
                                    buffering: false
                                })
                            }}
                            onError={this.onError}
                            resizeMode="contain"
                            ref={ ref => this.player.ref = ref}
                            style={[
                                Platform.OS === "android" ? styles.videoContainerAndroid : styles.videoContainerIOS, styles.videoContainer,
                                advertActive ? { opacity: 0 } : null
                            ]}
                            selectedVideoTrack={selectedVideoTrack}
                        />
```

## Video sample
Tried with all `.m3u8` HLS streams

**Comment by flexgrip** [comment]
I'm finding there are tons of props that don't work in v5. Like `selectedVideoTrack`, `maxBitRate` and even `audioOnly` and `poster` act funny together.

**Comment by paschaldev** [comment]
Oh yes, I just noticed that of `selectedVideoTrack`

**Comment by flexgrip** [comment]
One other thing, even if you could get `selectedVideoTrack` to work in v5, the onLoad data doesn't give you the videoTracks array anymore. As far as I can tell, there's no way to know which track is which.

I ended up reverting to v4.4.4 and now I have a quality selector that works on both iOS and Android using `selectedVideoTrack` on android and `maxBitRate` on iOS... what a mess.

I used to use onBuffer to know when things were playing because onPlay didn't work and onProgress fires so many times that it is easy to fill up memory if you don't watch it.

This whole thing is making me wonder if we should freeze this package and work on making sure the existing features work from v4-v5. Keep in mind, I'm not saying this to complain... just that I think it might be worthwhile to make a big effort to PR a bunch of bug fixes.

**Comment by Jadeon-FPM** [comment]
I second this. It seems that 4.4.4 still works fine for my needs for the time being, but I noticed that using 5.0.2 I was actually able to disable multi-dex on Android while it's needed in my project with 4.4.4. Odd.

Another thing is that the docs don't actually list `onBuffer` under `eventProps`, but it's used in the code example.

**Comment by santanu07** [comment]
Oh yes, I just faced that of onBuffer doesn't work
please give me solution if any

**Comment by chj-damon** [comment]
same here. `onBuffer` doesn't work on android.

**Comment by IamMasterWayne** [comment]
+1

**Comment by 97mit** [comment]
Try this as a temporary solution in onProgress. 
onProgress(data){
    this.setState({lastProgress: this.state.currentTime});
    this.setState({currentTime: data.currentTime});
    if(this.state.lastProgress == data.currentTime){
       this.setState({isBuffering: true});
   }else{
       this.setState({isBuffering: false});
  }
}

**Comment by jphilipstevens** [comment]
For us we are seeing that the exoplayer events never goes from playbackstate of buffering to playback state of ready

In this log the events show a video is ready and we can see it play
```
2020-04-08 11:17:37.810 6897-6897/ly.trybe.dev D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
2020-04-08 11:17:37.813 6897-6897/ly.trybe.dev D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
2020-04-08 11:17:37.833 6897-6897/ly.trybe.dev D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@250964ecom.brentvatne.exoplayer.ReactExoplayerView{11fb024 V.E...... ........ 0,0-1080,1080 #9fd}
2020-04-08 11:17:38.401 6897-6897/ly.trybe.dev D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=ready
```

In this case the onStateChanged is never fired and we cannot see any errors in LogCat
```
2020-04-08 11:18:18.107 6897-6897/ly.trybe.dev D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
2020-04-08 11:18:18.108 6897-6897/ly.trybe.dev D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
2020-04-08 11:18:18.120 6897-6897/ly.trybe.dev D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@250964ecom.brentvatne.exoplayer.ReactExoplayerView{11fb024 V.E...... ........ 0,0-1080,1080 #9fd}
```

**Comment by luisfuertes** [comment]
how can I make it work get the resolutions in the onLoad and add it to the selectedVideoTrack prop with version 5 of react-native-video? Any workaround?

**Comment by ebeliejinfren** [comment]
same issue

**Comment by luisfuertes** [comment]
Any update with this?
