### ISSUE TITLE
Android multiple videos error

### ISSUE THREAD

**Issue by mezalejandro** [TheWidlarzGroup/react-native-video#1796]
# Bug

Array of videos i have the following error on console:
![image](https://user-images.githubusercontent.com/568141/66844148-3525e000-ef44-11e9-9121-3f70a1d6e33d.png)

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 16.64 GB / 31.89 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 16.63 GB / 31.89 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
```

Library version: ^5.0.2

## Reproducible sample code

<Video
            ref={ref => this.player = ref}
            style={styles.video}
            onProgress={this.onProgress}
            source={{uri: url}}            
            onLoad={this.onLoad}
            onBuffer={this.onBuffer}
            onEnd={this.onEnd}
            onError={this.onError}
            repeat={false}
            resizeMode="contain"   
          />

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by flexgrip** [comment]
This is not enough info to know what's going on here. So you have an array of videos and you pass one instance into the component or all of the videos at once?

**Comment by supagu** [comment]
I am also getting this problem in android after upgrading to "react-native-video": "^5.0.2", playing a single video.

react native version: "react-native": "0.60.5",





```
<Video source={require('../../assets/buly-intro.mp4')}
                    ref={(ref) => {
                        this.player = ref
                    }}
                    onLoad={this.onVideoLoad}
                    onError={this.onVideoError}
                    onEnd={this.onVideoEnd}
                    style={ViewStyles.backgroundVideo}
                    resizeMode="stretch"
                    rate={0.5}
                />
```

style:
```
backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
```

sample videos I tried:
https://drive.google.com/open?id=1-bz5VbHqAvJH5F7jBcVX8bmMs69nrslL
https://drive.google.com/open?id=1vWQcIZ_61gmWfnbPUFuI92-0fObynnJR


from my settings.gradle:
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

from android/app/build.gradle:
```

dependencies {
  compile project(':react-native-video')
  implementation "androidx.appcompat:appcompat:1.0.0" // for react-native-video

}
```

**Comment by yuripinage** [comment]
Any updates?
