### ISSUE TITLE
Reuse same AVPlayer instance

### ISSUE THREAD

**Issue by johanneslumpe** [TheWidlarzGroup/react-native-video#18]
We are currently throwing away and re-creating the AVPlayer. It would be nicer if we just reused the same instance and exchanged the item if the source changes.

**Comment by brentvatne** [comment]
@johanneslumpe - are there any tradeoffs here? what is the cost of throwing away & creating a new one?

**Comment by eduedix** [comment]
@brentvatne: I am going back and forth in the Navigator in my small app, which has a page that loads Video.
Everytime i go to the page with Video, memory usage jumps by around 70MB. I think thats cos new instance is alloc'ed each time.

**Comment by brentvatne** [comment]
@eduedix - that sounds like a good enough reason right there! thanks

**Comment by eduedix** [comment]
It would be indeed useful to have an API, which could let me kill the instance. It seems having only 1 instance is still not the optimum solution.
I might be wrong about this.

**Comment by brentvatne** [comment]
@eduedix - ideally how would you like to manage this?

**Comment by johanneslumpe** [comment]
@eduedix it's one instance per element, not sure why you need multiple players per element?

**Comment by johanneslumpe** [comment]
@brentvatne at the very least we'd save the cost of allocating a new instance. It might not be a huge optimization, but less allocation is always better ;)

**Comment by eduedix** [comment]
@brentvatne @johanneslumpe I am still in for only one instance. But it seems instance stays on in the background forever.

**Comment by johanneslumpe** [comment]
@brentvatne @eduedix I just pushed a small fix branch for this.
https://github.com/brentvatne/react-native-video/tree/feature/fix-unremoved-playerlayer

After that gets merged, you should see a significant memory drop, when removing the view with the video.
