### ISSUE TITLE
Video not showing on Android Emu

### ISSUE THREAD

**Issue by Miyaguisan** [TheWidlarzGroup/react-native-video#1800]
# Bug

Video component is not displaying video on Android emulator.

> Video does show on iOS (both emulator and device)

The library was added via the auto-linking feature of RN 0.6.x

## Platform

Android

Which player are you experiencing the problem on:

* Android ExoPlayer

## Environment info
 info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 902.69 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.14.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

Library version: 5.0.2

## Steps To Reproduce

1. yarn add react-native-video
2. cd ios && pod install && cd ..
3. import Video from 'react-native-video'
4. <Video...
5. react-native run-android | react-native run-ios

## Expected behaviour

1. For the video component to work the same / similar on both iOS & Android.
2. For the video to show.

## Reproducible sample code

Not at the moment, simply added the library and used a dummy video uri | URL

## Video sample
[Vimeo video](https://vimeo.com/367377937)

**Comment by Duckers** [comment]
Same here. Is this the expected behavior?

**Comment by MoeMamdouh** [comment]
its happened with me at Android (RTL) only

**Comment by mpereal** [comment]
Hi, same for me. An idea ?

**Comment by jacksonsmith** [comment]
+1
