### ISSUE TITLE
Switching video on press causes flickering in iOS

### ISSUE THREAD

**Issue by Zontex** [TheWidlarzGroup/react-native-video#1801]
# Bug

I have an application that show a specific video in a loop, a 5 seconds video.
When the video is pressed it changes the video to a different one, once that video is finished it goes back to the previous video.

Video 1 - loop all the time.
Video 2 - When pressed shown, once finished goes back to video 1.

The problem is in iOS when changing the video both pressing changing from 1 to 2 and when the video is finished from 2 back to 1, there is a white flickering effect which is probably due to the video changing.

In Android it's smooth, can't see this problem at all but iOS this bug happens everytime.

## Platform

iOS production and iOS simulator, android doesn't have this issue.

Which player are you experiencing the problem on:
* iOS

## Environment info

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Memory: 20.26 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.10.2 
    react-native: ^0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.
```

Library version: 5.0.2

## Steps To Reproduce

1. Take 2 video files of 3-5 seconds each
2. Play the first video in loop, add onPress event to that video
3. Once press event happened, switch to the second video
4. Once the second video finished - switch back to the first video.
...

## Expected behaviour

Switching videos without flickering or white screen / background noises.
Android working perfectly fine and as expected.

## Video sample

iOS bug replication: https://www.youtube.com/watch?v=4ait39Z8w2c

**Comment by Zontex** [comment]
I'm closing this issue, it's not a bug in the framework.

When doing a transition between 2 videos in iOS for a split second you can see the background, in my case it was white background behind the video which made the flickering effect.

I fixed it by taking the last frame from the video and putting it as background image, by doing so when the video end the background will look exactly the same as the video so no flickering and the transition is 100% smooth.

**Comment by fabOnReact** [comment]
@Zontex I also have the same issue and I would like to read your code to receive inspiration to solve it. I believe you must be using some callbacks to change the background image of your container.

Thanks a lot

**Comment by Zontex** [comment]
@fabriziobertoglio1987 Sorry for the late reply, someone else emailed me regarding this issue so I will post the solution here:
```
<TouchableWithoutFeedback onPress={() => this._playCyclePressed()}>
                  <View style={styles.container}>
                      {Platform.OS === 'ios' &&
                        <ImageBackground source={Images.frames[this.state.currentItem.tag]} style={{width: wp('100%'), height: hp('100%')}}/>
                      }
                      <Video source={this.state.currentPlayCycle}
                         ref={(ref) => this.expression = ref}
                         style={styles.phoneBase}
                         resizeMode={'stretch'}
                         repeat={this.state.repeatExpression}
                         onEnd={() => this._onVideoEnd()}
                      />
              </View>
</TouchableWithoutFeedback>
```

If you will look at this part:

```
{Platform.OS === 'ios' &&
      <ImageBackground source={Images.frames[this.state.currentItem.tag]} style={{width: wp('100%'), height: hp('100%')}}/>
}
```

This is the actual fix, this issue seems to be effecting iOS only, the solution is to take the last frame of the video when it's ending and to put it as a background so the background because the video will fit the video when it's ended. 

This needs to be done manually, to crop the frame from the video take picture and put it as background, every video might have different frame - I kept them in json file for each video and that's how I pull them out.

Hope it helps.
