### ISSUE TITLE
No sound on one iPhone but proper sound another

### ISSUE THREAD

**Issue by olinations** [TheWidlarzGroup/react-native-video#1803]
I have no sound on videos on iPhone 6, but I have proper sound on iPhone 6 Plus and iPhone X in simulator.

I set:` ignoreSilentSwitch={"ignore"}`

I am using `presentFullscreenPlayer()` and I have these other properties...
````
muted={false}
controls={false}
resizeMode={"cover"}
fullscreen={false}
repeat={false}
paused={true}
````
The iPhone 6 that does not play sound of the video plays sound in all other apps but this one.

**Comment by olinations** [comment]
I actually found a work-around solution to this by using setNativeProps on the ref of the videoPlayer when the full screen presents like this...

````
onFullscreenPlayerDidPresent={() => {
  videoPlayer.setNativeProps({ paused: false, ignoreSilentSwitch: 'ignore', mute: false })
 }}
````

**Comment by trithien98** [comment]
Hi @olinations do you solve this problem. do you have sound when play video in mode not fullscreen ?? , i currently facing with this issue , my case is my app have production in appstore , and  some iphone devices have sound in video and some dont , example is : my iphone 11 , 10  have sound and iphone 6 doenst have

**Comment by vrishty** [comment]
Hi @trithien98, does the sound work for you now in all of the devices or are you still facing this issue? I have the similar issue, hoping to get a solution. Thanks
