### ISSUE TITLE
Black screen when video  loaded

### ISSUE THREAD

**Issue by issamabdelkrim** [TheWidlarzGroup/react-native-video#1805]
Hello everyone 
I have a black screen when i run a video . I can listen to the sound but the video is black .
When i make adb logcat i have this issue
Couldn't open file on client side, trying server side
D/NuPlayerDriver( 1150): reset(0xb58f5520)
Can someone help me 
thanks

**Comment by mbergdal** [comment]
Hi!
Same problem here. It seems to be ok for me on the ios simulator, and on android api level 28. Not working on api level 29.

**Comment by ghost** [comment]
samke issue on android displays as an small video in a corner of screen.

**Comment by KarenQiao** [comment]
same issue on android

**Comment by ghost** [comment]
I just solved with the following changes:

**before:** `resizeMode='content. // with black screen`
**After:** `resizeMode='contain. // solved `

**Comment by nimerfatsme** [comment]
i have also this issue , it is not solved with @muhammadwafa  solution

**Comment by minhchienwikipedia** [comment]
Same issue on android, any update?

**Comment by b3coded** [comment]
Try to set width and height manually, this solved my problem.

Example with [StyledComponents](https://github.com/styled-components/styled-components):

```js
import styled from 'styled-components/native';
import Video from 'react-native-video';
import {Dimensions} from 'react-native';

const {width, height} = Dimensions.get('screen');

export const Player = styled(Video)`
  width: ${width};
  height: ${height};
`;
```
