### ISSUE TITLE
Video doesn't play on iOS simulator if there are too many large files in the app's localstorage

### ISSUE THREAD

**Issue by jacklj** [TheWidlarzGroup/react-native-video#1806]
# Bug

Hi, I'm developing an app which has lots (~170) of large (~150MB) video files in the app's system storage (I've put them in `/Documents/videos`). These video files are downloaded automatically when you open the app (to bypass App Store size restrictions and to minimise app package size). However, when I have more than a small number of videos stored there, the react-native-video player can't play them - it just shows a black screen, with no error message. When I delete the majority of the videos, I can then play the remaining videos, as expected. Any ideas as to what the problem is? Thanks 

## Platform

Which player are you experiencing the problem on:
* iOS (iOS simulator (iPad 6th generation, iOS 11.4))
## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 329.98 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.0.0

## Steps To Reproduce

1. Put loads of video files into the app's system storage
2. Try and play one of them with react-native-video - you'll just see a black rectangle

## Expected behaviour

1. The video plays

**Comment by Saad9624** [comment]
hello can specify the path where you put the video file in project
