### ISSUE TITLE
【Android】Video not working for SDK below 27 (not including 27)

### ISSUE THREAD

**Issue by Zontex** [TheWidlarzGroup/react-native-video#1807]
# Bug

Tested the app using react-native-video, any android device below SDK 27 there is no video and only working sound, other versions including 27 it's working perfectly.

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
 OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Memory: 19.66 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.10.2 
    react-native: ^0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.0.2

## Steps To Reproduce

Use react-native-video on android version below SDK 27
In my app I have 3 sources of video (different files, different places) all doesn't work on < 27
...

## Expected behaviour

Both Audio and video working, same as iOS and > 27

**Comment by nhjuhoang** [comment]
same here
