### ISSUE TITLE
Expose props to configure PlayerNotificationManager

### ISSUE THREAD

**Issue by sampsonjoliver** [TheWidlarzGroup/react-native-video#1808]
# Feature Request
Support [PlayerNotificationManager](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html)

## Why it is needed

There are a few other issues asking for native implementation of notification-tray/control center controls for the video session from the lock screen or elsewhere on device. As [this blog post suggests](https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b), it's a best practice for video-playback, and for the same motivations that the exoplayer team implemented this it would make sense for this library to support it.

## Possible implementation

Highly recommended reading: https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b

The `react-native-video` exoplayer API could expose a `usePlayerNotificationManager` prop, which takes a boolean and selectively creates the `PlayerNotificationManager` and sets the exoplayer instance to it. Additional configuration props could be passed to a `MediaDescriptionAdapter` implementation;

### Code sample

```
const VideoPlayer = () => {
  return <Video usePlayerNotificationManager={true, {
    useNavigationActions: boolean,
    fastForwardIncrementMs: boolean,
    rewindIncrementMs: boolean,
    useStopAction: boolean,
    notificationColor: Color
    notificationSmallIcon: ...,
    notificationBadgeIcon: ...,
    notificationVisibility: ...
  }}
}
```

```
ReactExoplayerViewManager.java
public ReactExoplayerViewManager(ReactExoplayerConfig config) {
  this.config = config;
  this.playerNotificationManager  = new PlayerNotificationManager(...)
  this.playerNotificationManager.setUseNavigationActions(config.useNavigationActions)
  // etc
}

protected ReactExoplayerView createViewInstance(ThemedReactContext themedReactContext) {
  return new ReactExoplayerView(themedReactContext, config, playerNotificationManager);
}
```

```
// ReactExoplayerView.java
public void run() {
  player = ExoPlayerFactory.newSimpleInstance(getContext(), renderersFactory,
                            trackSelector, defaultLoadControl, null, bandwidthMeter);

  playerNotificationManager.setPlayer(player)
}

...

private void releasePlayer() {
  ...
  playerNotificationManager.setPlayer(null);
  ...
}
```

**Comment by MaxJadav** [comment]
@hueniverse  @sampsonjoliver  Any update on this for iOS?
