### ISSUE TITLE
Users keep randomly getting errors in video playback of HLS links

### ISSUE THREAD

**Issue by nathantqn** [TheWidlarzGroup/react-native-video#1809]
# Bug

I used Sentry as Error Tracking Software to trace errors in my app and there are 3 kinds of error that my users keep randomly receiving:

**For Android:**
1. Unable to instantiate decoder OMX.qcom.video.decoder.avc
2. Unable to instantiate decoder OMX.Exynos.avc.dec
3. Unable to connect to (Fragment of HLS video) (Unrecognized media format)

**For iOS:**
1. NSURLErrorDomain

----------------------------------
- I already commented on this thread: https://github.com/react-native-community/react-native-video/issues/1664#issuecomment-514048113, and I saw this thread is still opening also: https://github.com/react-native-community/react-native-video/issues/1068

- I have used different versions of `react-native-video` (v4.3.1, v4.4.4, v5.0.2), I also migrated from react native 0.58.4 to 0.61.1, about 1 year has passed, but those errors are still not resolved.

- I changed multiple providers for HLS links but nothing changes (I used Vimeo, Cloudflare, ...)
- I already increased the value of attribute `minLoadRetryCount` but it couldn't help

## Platform
* iOS
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 288.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
```

Library version: "react-native-video": "^5.0.2",

## Steps To Reproduce

Those errors randomly happen, sometimes everything is working fine, but sometimes those errors appear

## Expected behaviour

The video playback should be consistently fine

**Comment by s4kh** [comment]
Also getting an error for `mpd` from CloudFront. Error getting on `onError` callback: `{error:{extra:-214748348, what:1}}`

**Comment by nathantqn** [comment]
Hi @cobarx, could you please help me on the above issue :(. It's annoying my production users

**Comment by ghost** [comment]
+1

When having multiple videos in flatlist and autoplaying when they come in view, after a few videos the error occurs: Unable to instantiate decoder OMX.qcom.video.decoder.avc

PS: I am on the latest react-native-video version and using exoplayer

**Comment by ghost** [comment]
@nenjamin2405 did you find any solution for this?

**Comment by nathantqn** [comment]
Hi @crushy26, no I didn't find any solution for this, my users on production are living with it :D

**Comment by ghost** [comment]
@nenjamin2405 so the video isn't loading for your users? or have you done any workaround?

for now, I am displaying thumbnail as soon as video goes out of view. Seems to be working fine.

**Comment by nathantqn** [comment]
@crushy26 I was facing a same problem just like you when I had a snap carousel with multiple videos to slide. And yes, I used the same approach as you, when I swipe to the next video, I need to display the thumbnail for the previous one to unmount the video component for it. But my users also facing this error randomly when they watch a specific video (1 video only, not a flat list), that's why I raised this issue, my current solution is when facing the issue, I reload the video (by changing the video URL to null and change back to the real url), after trying about 3 times, if it does still not work, then I appear an error message and tell them `something went wrong, please try again later`

**Comment by ghost** [comment]
Oh I see. I tried the null and URL solution, but seems like it doesn't work at all. Thank for the reply though. I hope they solve this problem soon.

**Comment by kartavyaparekh96** [comment]
+1

**Comment by enigmablue** [comment]
+1 getting random issues too

**Comment by AndresTIY** [comment]
+1 sounds similar to my issue. happens with mp3 & hls only on android [#2263 ](https://github.com/react-native-video/react-native-video/issues/2263)

**Comment by RenovJ** [comment]
+1 same happening at multiple videos in carousel with auto-playing on focused video

**Comment by RenovJ** [comment]
I found an issue on Android ExoPlayer looking related to this issue.(https://github.com/google/ExoPlayer/issues/2872)
According to it, this issue seems to be caused from handling media sequence of HLS streaming mechanism of ExoPlayer.
And the similar error is happening on not only HLS, but mp4..(in my case, rarely happening than HLS)
The issue was closed by resolving with adding HLSExceptionError handler.
But as you can check the ExoPlayer issue, the problem is very tricky to solve and the solution is not completely solving this issue.
The error is still happening when request numbers of HLS chunks in couple seconds.
So I tried to reduce the request number of HLS chunks.
In my case, 1) changed to load number of video component at a same time from 3 to 1.
2) reduced bufferMSs from bufferConfig of react-native-video props.
After that, it works much better. I hope this helps you all!

**Comment by liquidvisual** [comment]
> In my case, 1) changed to load number of video component at a same time from 3 to 1.

@RenovJ How do you load them one at a time, if there are multiple in a list?

**Comment by freeboub** [comment]
should be fixed by: https://github.com/react-native-video/react-native-video/pull/2498
I think.
Need to test again once merged.

But according to exoplayer issue description, you should have network error on your CDN ...

**Comment by Takesizmail** [comment]
+1
