### ISSUE TITLE
texttracks do not work

### ISSUE THREAD

**Issue by khat33b** [TheWidlarzGroup/react-native-video#1815]
# Bug

In the GitHub README, the prop `texttracks` are described (https://github.com/react-native-community/react-native-video#texttracks) but this feature is not working.

## Platform

All platforms
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 293.09 MB / 7.53 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2
  npmPackages:
    react: ^16.11.0 => 16.11.0 
    react-native: ^0.61.4 => 0.61.4 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2

```

Library version: 5.0.2

## Steps To Reproduce

1. Create the Video tag and include the texttracks parameter
```
    <Video
      ref={player}
      source={{uri: asset.url}}
      controls
      style={styles.backgroundVideo}
      poster={asset.details.thumb_land}
      resizeMode="contain"
      textTracks={[
        {
          title: 'English CC',
          language: 'en',
          type: TextTrackType.VTT,
          uri: asset.cc_url_vtt,
        },
        {
          title: 'English Subtitles',
          language: 'en',
          type: TextTrackType.SRT,
          uri: asset.subtitle_url,
        },
      ]}
    />
```

## Expected behaviour

1. The subtitle should show

**Comment by naeemqaswar** [comment]
At first i also had trouble implementing TextTracks but later i understood how to sync and make it working. Make sure to follow these:
- Manually link the plugin
- Only ExoPlayer will work for Subtitles and by default its set to AndroidPlayer, you can change or verify it in /android/settings.gradle
- Along with "textTracks" also set "selectedTextTrack". To match textTrack with video, i'm setting "index" value. Updating your code to following:
`<Video
      ref={player}
      source={{uri: asset.url}}
      controls
      style={styles.backgroundVideo}
      poster={asset.details.thumb_land}
      resizeMode="contain"
      textTracks={[
        {
          index: 0,
          title: 'English CC',
          language: 'en',
          type: TextTrackType.VTT,
          uri: asset.cc_url_vtt,
        },
        {
          index: 1,
          title: 'English Subtitles',
          language: 'en',
          type: TextTrackType.SRT,
          uri: asset.subtitle_url,
        },
      ]}
      selectedTextTrack={{
          type: 'index',
          value: 0,
      }}
    />`

I hope it works, PEACE !!

**Comment by aevzp** [comment]
1. I unlink and remove react-native-video
2. For RN > 0.60 `yarn add react-native-video`
3. Manual link for Android
4. I had an error `transformDexArchiveWithDexMergerForDebug`
5. Then I've added to `app > build.gradle`.
    `defaultConfig {
        ....
        multiDexEnabled true
    }`
AND into dependencies
`implementation 'com.android.support:multidex:1.0.0'`
6. Done for me. (RN 0.60.6)
