### ISSUE TITLE
Support equalizer (EQ)

### ISSUE THREAD

**Issue by marf** [TheWidlarzGroup/react-native-video#1817]
# Feature Request

Hello, I am wondering if there is the possibility to support an Audio EQ for the output audio of react-native-video, do you have any hints on how to do it?

## Why it is needed

I am developing an app that uses react-native-video to display music videos but some users asked an equalizer to change the audio output.

Any suggestions?

**Comment by Taque** [comment]
add a gif animation of equalizer to your project and also add a steady image of the same equalizer. then add variable equalizer to the state and change it with the state by pause props of video Component. Recently I worked in this way in a Project :)

**Comment by marf** [comment]
> add a gif animation of equalizer to your project and also add a steady image of the same equalizer. then add variable equalizer to the state and change it with the state by pause props of video Component. Recently I worked in this way in a Project :)

Hello, thank you, but how can I tweak the audio accordingly to the changes in the equalizer? :)

**Comment by Taque** [comment]
Use > https://github.com/c19354837/react-native-system-setting and Use your var equalizer to handle with Sound.......
   SystemSetting.getVolume().then((volume)=>{
    if(volume>0){
      this.setState({equalizer:false})
    } else{
      this.setState({equalizer:true})
    }
   });

**Comment by marf** [comment]
> Use > https://github.com/c19354837/react-native-system-setting and Use your var equalizer to handle with Sound.......
> SystemSetting.getVolume().then((volume)=>{
> if(volume>0){
> this.setState({equalizer:false})
> } else{
> this.setState({equalizer:true})
> }
> });

This simply handles the volume, the EQ is used to change how the audio is listened, for example increase the bass etc.

This is an example of equalizer: [EQ](https://community.spotify.com/t5/image/serverpage/image-id/98168i215BCE5D04438BF8/image-dimensions/244x434?v=1.0)
