### ISSUE TITLE
Expose native imperative API

### ISSUE THREAD

**Issue by JofBigHealth** [TheWidlarzGroup/react-native-video#1819]
# Feature Request

Expose `.play`, `.pause` and other native player functionalities

## Why it is needed

Changing play/pause state by updating a prop is slow.... it can be in the order of 30ms in a typical app and considerably more if the JS is doing some heavy work. This makes fine control of the player using React not really an option. (Notwithstanding Android's abysmal codec startup time but that's another story! Not much we can do about that)

By exposing play/pause methods the player state can be changed with millisecond response times. (From experience the round-trip time of JS calling a native method which then calls a JS callback is <6ms in total even in a bad case so it's much faster)

## Possible implementation

Needs methods added to the native and JS code along with the type declarations. Might have to update Java to keep some MediaPlayer state information around to handle `.play` and `.pause` being called on a MediaPlayer instance that's in a state that doesn't allow it. For instance, from memory calling `.pause` on a media player that PlaybackStopped state throws an exception.

I'm working on a fork shortly so might be able to contribute back if it's agreed other people would like this feature too.

**Comment by mym0404** [comment]
is this completed? I can't find any method for this.

**Comment by freeboub** [comment]
@mym0404 no not implemented...
