### ISSUE TITLE
TypeError: TypeError: Cannot read property 'Constants' of null

### ISSUE THREAD

**Issue by jetmirfeka** [TheWidlarzGroup/react-native-video#1820]
"react-native-video": "^5.0.2",

**Comment by nileshchavan** [comment]
I'm facing this error in the debug mode as well.

Env:

   

> Android SDK:
>       API Levels: 26, 27, 28, 29
>       Build Tools: 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.1
>       System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
>       Android NDK: 20.0.5594570
>   IDEs:
>     Android Studio: 3.5 AI-191.8026.42.35.5791312
>     Xcode: 11.2/11B52 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.8.6 => 16.8.6 
>     react-native: 0.60.5 => 0.60.5 
>   npmGlobalPackages:
>     react-native-cli: 2.0.1
>     react-native-pose: 0.9.1
>     react-native: 0.60.4

**Comment by r0b0t3d** [comment]
If you are working on android and not using autolinking, please make sure you follow the instruction [here](https://github.com/react-native-community/react-native-video#android-installation) strictly. 
For me, I forgot to add `ReactVideoPackage`  on `MainApplication.java`

**Comment by youndyan** [comment]
React-native video Cannot read property 'Constants' of NULL

**Comment by youndyan** [comment]
How do you solve this, online and so on

**Comment by Nirmit04** [comment]
Any Solutions to this?
I am using react-native version 0.65.1 and the librarie's documentation say it will be autolinked

**Comment by MuhammadTanveer94** [comment]
I am using react-native version 0.66.2 and the library documentation say it will be autolinked. Any solution?

**Comment by 3xo13** [comment]
Hi, Did anyone managed to solve this ?, i'm learning react native with expo and i got the same error

**Comment by freeboub** [comment]
I tried, I think this is just an incompatibility with expo...

**Comment by 3xo13** [comment]
Yeah I believe so as well, I found a way around it by using the library
provided by expo instead of the one directly for react native
