### ISSUE TITLE
Android video player running into infinite buffer loop when tapped rapidly on seek controls

### ISSUE THREAD

**Issue by sourabhdadapure** [TheWidlarzGroup/react-native-video#1821]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: 5.0.2

## Steps To Reproduce

1. Tap on seek forward button rapidly 
2. The player keeps buffering
3.  Never gets out buffer loop 
...

## Expected behaviour

1. Doesn't crash on seek forward button tap
2. Doesn't run into an infinite buffer loop
3. At least have a refresh method which can be utilized to get out of that buffer loop

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by lkw1830** [comment]
same here

**Comment by owenjeon** [comment]
Same here

**Comment by santanu07** [comment]
I have faced same problem.
please help me

**Comment by leethree** [comment]
probably related to: https://github.com/react-native-community/react-native-video/issues/1320

**Comment by PhuongUS** [comment]
Same here

**Comment by devbot-pcarrillo** [comment]
any know if this happens in lower versions of the plugin?

**Comment by devbot-pcarrillo** [comment]
https://github.com/react-native-video/react-native-video/issues/1320#issuecomment-709563750

**Comment by vishnu-keyvalue** [comment]
same here
