### ISSUE TITLE
Read HLS playlist file on iOS (m3u8) from a base64 encoded data-uri?

### ISSUE THREAD

**Issue by raymondjacobson** [TheWidlarzGroup/react-native-video#1823]
I found a somewhat related issue of folks talking about reading entire videos in base64 as a data uri (https://github.com/react-native-community/react-native-video/issues/266), which sounds like kind-of a bad idea, but a use case of mine requires being able to construct m3u8 files on the fly (their constituent segments being full web URL identifiers). 

This does work on Hls.js as well as native iOS safari HLS playback, but I can't seem to get video/audio to start with react-native-video by passing it a data URI in the source.

Is this supported?
TY!

**Comment by raymondjacobson** [comment]
it actually appears as if setting 
source={{ uri: 'data:application/vnd.apple.mpegURL;base64,XYZ' }} 
crashes the app entirely, handleError isn't invoked on the <Video> element unfortunately

**Comment by raymondjacobson** [comment]
https://github.com/raymondjacobson/react-native-video/commit/bebfb5753debfc72c3461291a9c98856f34d4fec

need to test this more broadly, but i believe data URI's should be treated as `isNetwork` and that fixes up this issue

**Comment by raymondjacobson** [comment]
https://github.com/react-native-community/react-native-video/pull/1842

**Comment by double-u-a** [comment]
@raymondjacobson You mentioned a m3u8 file as a base64 dataURL working on native iOS, I've been trying to generate M3U8's on the fly as base64 strings but native iOS/MacOS Safari won't play them (it works fine on HLS.js but that doesn't run on iOS unfortunately). How did you manage to do it?
