### ISSUE TITLE
Controls not working on Amazon Fire TV Stick

### ISSUE THREAD

**Issue by timoschlueter** [TheWidlarzGroup/react-native-video#1828]
# Bug

I tried using the library with Exo Player inside an App for the Amazon Fire TV. The media file is playing, sound and video are working without any problems. Unfortunately, the controls don't show up when using the Amazon Fire TV Remote. The player is not registering any events from the remote.

Is this expected since Amazon is using a forked version of Android on their devices?
I noticed that Amazon is publishing a fork of Exo Player on https://github.com/amzn/exoplayer-amazon-port. If this bug is out of scope of react-native-video, is there a way to use their version of Exo Player with this package?

## Platform

* Android ExoPlayer (Amazon Fire TV Stick)

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 145.92 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 25.0.1, 28.0.3, 29.0.2
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.0.2

## Steps To Reproduce

1. Run the example code on an Amazon Fire TV Stick
2. Try to access the controls (Play/Pause or Select Button)

## Expected behaviour

1. The controls should show up

## Reproducible sample code

```
import Video from 'react-native-video';

<Video source={{uri: "https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_stereo.avi"}}
       ref={(ref) => {
         this.player = ref
       }}
       onBuffer={this.onBuffer}
       onError={this.videoError}
       style={styles.backgroundVideo} />

var styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});
```

## Video sample
Not related to a specific file.

**Comment by timoschlueter** [comment]
I dug a little deeper:

This is also an issue using the Amazon Port of Exo Player. The controls are still not working properly.
You can reproduce it using the Amazon port by modifying the **react-native-video/android-exoplayer/build.gradle**:

```
dependencies {
    implementation('com.amazon.android:exoplayer:2.9.0') {
        exclude group: 'com.android.support'
    }
...
    implementation('com.amazon.android:extension-okhttp:2.9.0') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
}
```

With that out of the way I tried debugging on the device itself. When I first start the app, the controls are visible and are working properly. I implemented the TVEventHandler module from -react-native (see: https://facebook.github.io/react-native/docs/building-for-apple-tv) to console.log all the events that the remote is firing. When I start the app, the player is loading an showing the controls. When spamming the remote (any button) the events are firing. But as soon as the controls fade out, the event handler for the remote stops firing. 
With no events firing I can see why the controls won't show up again.

 Is this a known issue? The events from the remote should still be emitting even when the controls are faded out.

**Comment by matejpolak** [comment]
@timoschlueter I have exactly the same issue. If you run it in emulator you can use the player controls with mouse, so it's touchable, but the focus is not there. Have you found any solution before I start digging into it? 

Of course and option here would be to build a custom UI, but  nativeControls should be working anyway.

**Comment by timoschlueter** [comment]
Unfortunately I haven’t found a solution yet. 
I ended up building my own controls which isn’t my favorite solution. Still hoping that this issue will be addressed sometime in the future.

**Comment by myparish** [comment]
+1

**Comment by freddieerg** [comment]
+1

**Comment by ChiBao284** [comment]
+1

**Comment by rohitninawe** [comment]
+1

**Comment by rohitninawe** [comment]
my SOLUTION:

TVEventHandler  will not work with default `react-native": "0.64`, you will have to change it with `"react-native": "npm:react-native-tvos@latest"`
To do so, use this command: `yarn add react-native@npm:react-native-tvos@latest` then clean and rebuild your project. 🎉

**Comment by Neerajjp** [comment]
Still there is no solution for this. The control bar should remain there constantly. Its very difficult for developers in react native

**Comment by Neerajjp** [comment]
https://github.com/amzn/exoplayer-amazon-port/issues/92

This issue is also related with the same
