### ISSUE TITLE
Cannot play video in background at the first time

### ISSUE THREAD

**Issue by truckhiem** [TheWidlarzGroup/react-native-video#1830]
# Bug

- When I lock screen after touch to play an video, that video cannot play until I unlock the phone. I found that the event like onLoadStart, onLoad, onBuffering still response while app in background (lock screen), but video cannot play

- But when I keep the app foreground until video played, after that I lock screen and next another video, it's work well.

## Platform
* iOS

Thanks

**Comment by rorygarand** [comment]
Maybe related to this issue: https://github.com/react-native-community/react-native-video/issues/1735 ?
