### ISSUE TITLE
 "x" button to dismiss/exist the video player?

### ISSUE THREAD

**Issue by letam245** [TheWidlarzGroup/react-native-video#1835]
![Screen_Shot_2019-12-03_at_4_05_07_PM](https://user-images.githubusercontent.com/28547581/70100634-24f6bc80-15e7-11ea-93b9-130be961de09.png)

how do I display the 'x' button for the video player in iOS, the native TVPlayer has the "x" to dismiss the player viewController? is there a props for this or can this feature be added if not available yet?

**Comment by niloufarMakhzani** [comment]
Any update? Or is it possible to hide scale or mute button? so I can place my close button there

**Comment by ObidosDev** [comment]
Looks like it will shown if you wrap it in RN <Modal/>. But it is super bad behaviour as for me

**Comment by LautaroMir** [comment]
The X is showing when "controls={true}" but I can't seem to find a way to execute a callback when the user press the X. Any ideas?

**Comment by sergiulucaci** [comment]
@LautaroMir what version are you using? "X" not appearing for me at all

**Comment by louis-nucleus** [comment]
i have the same problem with here does anyone has any ideas about that

**Comment by fermedev** [comment]
Fix this, please!

**Comment by philipbrady13** [comment]
also running into this issue using `"react-native-video": "5.0.2"`. i have set `controls={ true }` and can see play/pause controls but the `X` does not appear. i am able to swipe from left to right to navigate to the previous screen but this is not ideal. any ideas on how to fix?

**Comment by taschik** [comment]
@philipbrady13 this is my Video configuration but I run it in a fixed width/height window which allows to open a full screen, and this full screen has the X

```
<VideoPlayerContainer
          allowsExternalPlayback={true}
          automaticallyWaitsToMinimizeStalling={true}
          controls={true}
          fullscreen={true}
          ignoreSilentSwitch="ignore"
          onEnd={onEnd}
          onError={(error) => onVideoError(error)}
          onExternalPlaybackChange={(payload) => onExternalPlaybackChange(payload)}
          onLoadStart={onLoadStart}
          onLoad={onLoad} 
          onReadyForDisplay={onReadyForDisplay}
          ref={(ref: Video | null) => {
            player.current = ref
          }}
          source={{ uri: video.video }}
        />
```

This looks like this here:
![Untitled 2](https://user-images.githubusercontent.com/351623/99597871-91352080-29f0-11eb-9e6c-0891231eaecc.png)

and when clicking the full screen button it looks like this:
<img width="285" alt="Screen Shot 2020-11-18 at 2 50 12 PM" src="https://user-images.githubusercontent.com/351623/99597901-9e520f80-29f0-11eb-988f-cd26a3bb0e37.png">

Unfortunately there is a bug that doesnt dismiss the full screen automatically at the end of the video and is described here: https://github.com/react-native-video/react-native-video/issues/2178 

A fix would be apprciated but this might be a workaround for you.

**Comment by Chinna111** [comment]
Do it below code.    

```
                <Card >
                  <Text style={{ flexDirection: "row", textAlign: "right", marginRight: 10, marginBottom: 1 }} onPress={() => {    setVideoPath(''); }}> X </Text>
                  <Video
                    source={{ uri: videoPath }} // Can be a URL or a local file.
                    style={{ width: '100%', height: 250, marginVertical: 8 }}
                    controls
                    posterResizeMode="cover"
                    resizeMode="cover"

                  />
                </Card>
```

**Comment by vargajacint** [comment]
Any update?

**Comment by NiharR27** [comment]
Any follow up on this?

**Comment by EnricoVacondio** [comment]
It depends on type of screen, If it's inside a modal the button will be always shown otherwise no. In my case it worked.

**Comment by nikunjdhamelia** [comment]
Any update?

**Comment by belghithb** [comment]
Any update please?

**Comment by jepasarell** [comment]
If using react-navigation, make your video screen options fullScreenModal and it works nicely:

`options={{ headerShown: false, presentation: 'fullScreenModal' }}`

**Comment by felire** [comment]
> If using react-navigation, make your video screen options fullScreenModal and it works nicely:
> 
> `options={{ headerShown: false, presentation: 'fullScreenModal' }}`

That worked for me
