### ISSUE TITLE
Stream from multipart/x-mixed-replace

### ISSUE THREAD

**Issue by cristianoccazinsp** [TheWidlarzGroup/react-native-video#1837]
# Feature Request

Is it possible to stream from a request that returns "multipart/x-mixed-replace"? Any ideas on how to achieve this?

Can react-native-video instead stream from an "infinite" local file? That is, stream as the file keeps getting appended.

**Comment by yyavor0705** [comment]
@cristianoccazinsp any success on this?

**Comment by cristianoccazinsp** [comment]
Nope, let me know if you find anything. I pretty much paused this "feature" / research.

**Comment by softov** [comment]
update?

**Comment by cristianoccazinsp** [comment]
Still haven't found a solution. Right now I think the only way is to implement native bridges iOS and Android that render HTTP multipart/x-mixed-replace output into a View.
