### ISSUE TITLE
undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

### ISSUE THREAD

**Issue by braco** [TheWidlarzGroup/react-native-video#184]
Getting red screen of death with

undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

on Android

under react-native 0.23.1

**Comment by bbhh** [comment]
Did you try re-running: `react-native run-android` or `react-native run-ios`? I had this same problem but this did the trick for me. I forgot to re-run this after installing react-native-video through npm install.

**Comment by braco** [comment]
@bbhh: definitely did, happens on Android every time. Thanks for the reply.

**Comment by braco** [comment]
Fixed, I think one of the gradles had a typo. For anyone finding this bug, double check that all three files are perfect: build.gradle, settings.gradle, MainActivity.java

**Comment by lsps9150414** [comment]
@braco  I am getting this when `react-native run-ios`. This can't be a problem in any of the gradle files or the MainActivity.java, right?

**Comment by vgurbuxani** [comment]
I'm having the same issue, running react-native run-ios. please advise on how to fix this?

**Comment by bayrontq** [comment]
I'm having the same issue for `react-native run-ios`.

**Comment by uc-asa** [comment]
I am trying to run video in IOS device using react native but I found Unhandled JS Exception: undefined is not an object (evaluating 'NativeModules.UIManager.RCTVideo.Constants') error. Error screen shot here
http://screencast.com/t/xoL6C50QKDi

**Comment by logileifs** [comment]
Same issue here. Has anyone found a solution/workaround for this problem ?

**Comment by BranoMatan** [comment]
Also looking for solution, using `react-native run-android`.

**Comment by logileifs** [comment]
@BranoMatan I found out the problem was with the `rnpm link react-native-video` not working properly.
Solution: open `android/app/src/main/java/com/app_name/MainApplication.java` in the top section of the file (where all the imports are) add `import com.brentvatne.react.ReactVideoPackage;` and then in the `getPackages()` method add `new ReactVideoPackage()`, build again and run.

**Comment by BranoMatan** [comment]
Thanks @logileifs ! Worked perfectly

**Comment by Johnny1109** [comment]
@logileifs where can i find the getPackages() method? i did other changes as you suggested.

**Comment by logileifs** [comment]
@Johnny1109 if your react native version is 0.29.0 or greater you will find it in `android/app/src/main/java/com/NAME_OF_YOUR_APP/MainApplication.java`  
If your react native version is less than 0.29.0 than you will find it in `android/app/src/main/java/com/app_name/MainActivity.java`  

You can see your react native version in `package.json` in your project root directory

**Comment by Johnny1109** [comment]
@logileifs thanks logileifs, i got it in MainApplication.java

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage();
          new ReactVideoPackage();
      );
    }

is this correct, because still i am getting error

**Comment by logileifs** [comment]
@Johnny1109 You're almost there! Just change the semicolon after `new MainReactPackage()` to a comma. It should look like this:

```
protected List getPackages() {
    return Arrays.asList(
        new MainReactPackage(),
        new ReactVideoPackage()
    );
}
```

**Comment by Johnny1109** [comment]
@logileifs thank you so much.. it works now

**Comment by logileifs** [comment]
@Johnny1109 you are very welcome :)

**Comment by Johnny1109** [comment]
@logileifs any idea why video not visible, i can hear the audio.. thanks in advance

**Comment by logileifs** [comment]
@Johnny1109 I'm sorry but that's a totally unrelated problem. Most likely your view is too small so your video is not appearing or it's simply not on the screen itself. You should really ask that question somewhere else like [stackoverflow](http://stackoverflow.com)

**Comment by ManiSJ** [comment]
@logileifs I am getting below error after doing what you suggested

 error: cannot find symbol
                  new ReactVideoPackage()
                      ^
  symbol: class ReactVideoPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.

**Comment by America-first-melon** [comment]
you are great!

**Comment by Tzinov15** [comment]
Just wanted to post my most recent workaround for iOS in case someone runs into this again. I blew away `node_modules`, reset any XCode changes to the `.pbxproj` related to `react-native-video`, then did a fresh `npm install` and a fresh `react-native link react-native-video` and it worked. I'm assuming the linking got messed up somehow and removing those attempts and starting over helped

**Comment by scotttharvey** [comment]
undefined is not an object (evaluating 'CardIOUtilities.DETECTION_MODE')
No matter what i do i keep getting this error. What can i do?

**Comment by varunrayen** [comment]
@Tzinov15 Still i have the issue after following your steps. I am trying to do this in Expo. Any suggestions?

**Comment by pvroosendaal** [comment]
@varunrayen I'm also experiencing the issue after following @Tzinov15 steps.. Anybody have a solution?

**Comment by netors** [comment]
Same issue, not working
![img_6697](https://user-images.githubusercontent.com/893833/29532343-84cd65c2-8661-11e7-9266-cb8290348f3e.PNG)

```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.46.4
```

on my package.json
```
...
  "dependencies": {
    "expo": "^19.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.1",
    "react-native-awesome-card-io": "^0.6.4",
    "react-native-video": "^2.0.0"
  }
...
```

**Comment by vinils** [comment]
same issue on expo!

**Comment by vinils** [comment]
@varunrayen I opened an issue on expo, could you help me to provide a repro?

**Comment by decadef20** [comment]
Same issue. The  [doc](https://github.com/react-native-community/react-native-video#android) me . Before you use it , you must run `rnpm link`.When the link may fail,do it manually.

**Comment by adiagr95** [comment]
For Expo users, this library doesn't seem compatible with Expo, you can use this library :

https://github.com/expo/videoplayer

**Comment by custam** [comment]
I solved it by installing react-native-video with pods :
1) install pods
2) add this to your podfile is ios folder of your project : 
`pod 'react-native-video', path: '../node_modules/react-native-video'`
3) launch pod install
4) maybe delete the "-obj" in the "target support files" of file "pods". You can find it by opening your xcworkspace file in xcode.
5) rerun your project

**Comment by Lipfroy** [comment]
to link library on iOS do next steps:
1)in XCode right click on "Libraries" folder and choose 'add files to prjctname'
then go to node_modules/react-native-video/ios/ and choose RCTVIdeo.xcodeproj
2) go to targets -> Build Phases ->Link Binary With Libraries hit + and choose libRCTVideo.a
3)profit

**Comment by vbnospace** [comment]
same with expo too

**Comment by arasemami** [comment]
try to add dependencies in build.grade Module: app

dependencies {
    .....
    compile project(':react-native-video')
}

**Comment by kotelesroberto** [comment]
Run the command of react-native link and after react-native run-android.

The first command links the dependencies and after that it will work!

**Comment by MaffooBristol** [comment]
@Lipfroy I was hoping this would be the magical solution but it broke my build. Metro bundler should supposedly do all this linking manually so doing it in XCode is unnecessary:

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-video (to unlink run: "react-native unlink react-native-video")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

**Comment by MaffooBristol** [comment]
Found the solution for my case, after re-unlinking the native dependency:

```
cd ios/
pod install
```
Thanks to https://github.com/react-native-community/react-native-video/issues/1502#issuecomment-480905260
