### ISSUE TITLE
Multiple dynamic videos inherits play state

### ISSUE THREAD

**Issue by djpetenice** [TheWidlarzGroup/react-native-video#1840]
### Current behavior
Adding multiple dynamic videos inherits the previous videos play state.

### Expected behavior
If paused prop is set to true video should be paused

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

I have a component that I'm using to dynamically to add in video in my main component:

render() {
    var video = this.props.video;
    var index = this.props.index;

  return (

   <Video
           onLoad={()=>{this.setState({isLoading:false})}}
           controls={true}
           paused={true}
           key={'player'+index}
           poster={video.image+'?'+new Date()}
           ref={(ref) => {
               this['player${index}'] = ref
             }}
           style={styles.fullScreen}
           resizeMode='cover'
           source={{uri: video.src+'?'+new Date()}}
           repeat={true}
          />
}

This is being imported in my main app component:

{revArray.map((video,index) => (
     <Video key={'video'+index}  video={video} index={index} />
   ))}

Each time I add a video it's inheriting the play state from the previous video. I've added a dynamic ref but that doesn't seem to stop the issue.

**Comment by hamzaehsan95** [comment]
Any updates on this one please?
