### ISSUE TITLE
How to do Picture in Picture for android in this library. Thanks

### ISSUE THREAD

**Issue by Utkarshkataria** [TheWidlarzGroup/react-native-video#1841]
# Feature Request

**Comment by matejpolak** [comment]
Hi @Utkarshkataria there is a pull request opened for Android PIP already. See:

- #1776 - PIP itself
- #1780 - MediaSession (mainly for displaying play/pause, etc.. in PIP window)

I'm already using it in some of the projects I'm working on. Feel free to test it out, and comment back with suggestions and improvements.

**Comment by nitesh3539** [comment]
Hi @matejpolak I have nested screen and video is child screen, I want to use PIP on child screen such that video PIP mode is on parent screen.

How i can do it?
Please update me on this.

Thanks

**Comment by matejpolak** [comment]
> Hi @matejpolak I have nested screen and video is child screen, I want to use PIP on child screen such that video PIP mode is on parent screen.
> 
> How i can do it?
> Please update me on this.
> 
> Thanks

@nitesh3539 please see my comment here: #1858

**Comment by jrhager84** [comment]
Is this possible now?

**Comment by freeboub** [comment]
@jrhager84 no, to be followed in https://github.com/react-native-video/react-native-video/issues/2621
