### ISSUE TITLE
React-native-video with react-native-webrtc

### ISSUE THREAD

**Issue by johndm76** [TheWidlarzGroup/react-native-video#1844]
Hi
Can i use a local stream that has been got from mediaDevices.getUserMedia({...}) as a source to a Video element? If yes, how?
Cause i'm trying to use the local stream as a source to a Video element like below, but nothing appears in the video (remains blank):
...
import Video from 'react-native-video';
...
<Video source={{ uri: stream.toURL() }} repeat />
...

Thank you

**Comment by johndm76** [comment]
Please any help

**Comment by et-hh** [comment]
i want help too
