### ISSUE TITLE
When muted={true} the fullscreen audio control not making mute/unmute

### ISSUE THREAD

**Issue by pramodsharma403** [TheWidlarzGroup/react-native-video#1845]
# Bug

When I set muted={true} & using audio control of full screen to make mute/unmute not working. 

## Platform
IOS
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 "react": "16.8.3",
  "react-native": "0.59.9",
```

Library version: 5.0.2

## Expected behaviour

1. Video should be mute/unmute on basis of audio control.

**Comment by tom-krusch** [comment]
i have the same issue (version: 5.1.0-alpha1)

**Comment by benvp** [comment]
Having the same issue. I couldn't figure out how to fix this in the react-native-video codebase, but at least I have a workaround which does seem to work. Only caveat is, that it is relying on a separate package `react-native-system-setting` to keep track of the volume control.

The basic idea is, to unset the `muted` prop when a switch in the volume control is done. This way we achieve the behaviour that the video is always muted and as soon as you unmute it, it will pick up at the last volume which has been set before. I achieved this currently like this:

```ts
import SystemSetting from 'react-native-system-setting';

export const useVolumeListener = (handler: (volume: number) => void) => {
  useEffect(() => {
    const listener = SystemSetting.addVolumeListener(({ value: volume }: { value: number }) =>
      handler(volume),
    );

    return () => {
      SystemSetting.removeVolumeListener(listener);
    };
  }, [handler]);
};
```

VideoPlayer:
```ts

export const Player: React.FC = () => {
  const [isMuted, setIsMuted] = useState(true);
  const [isFullScreenVisible, setIsFullScreenVisible] = useState(false);

  const unmuteOnVolumeChange = useCallback(() => setIsMuted(!isFullScreenVisible), [
    isMuted,
    setIsMuted,
    isFullScreenVisible,
  ]);

  useVolumeListener(unmuteOnVolumeChange);

  return (
    <Video
      onFullscreenPlayerDidPresent={() => setIsFullScreenVisible(true)}
      onFullscreenPlayerDidDismiss={() => setIsFullScreenVisible(false)}
      muted={isMuted}
    />
  );
}

**Comment by sergeymild** [comment]
Same issue, then video plays without sound, and show it on full screen, on fullscreen audio toggle not working

**Comment by qinjialei24** [comment]
don't use muted prop, use setNativeProps (https://reactnative.dev/docs/direct-manipulation)

`  videoPlayRef.current?.setNativeProps({
                    muted: false
                });
`
this works for me

**Comment by yaduvanshi-studio-labs** [comment]
`             const [videoVolume, setVideoVolume] = useState(1.0);

                        <Video 
                        onEnd={onEnd}
                        onLoad={onLoad}
                        onLoadStart={onLoadStart}
                        onProgress={onProgress}
                        volume={videoVolume}
                        />
                        
                        
                        <TouchableOpacity
                            onPress={() => {
                              if (muteSound === true) {
                                setMuteSound(false);
                                setVideoVolume(1.0);
                              } else {
                                setMuteSound(true);
                                setVideoVolume(0.0);
                              }
                            }}
                        />
`

**Comment by takuro-kira** [comment]
Same issue on [v6.3.0](https://github.com/TheWidlarzGroup/react-native-video/releases/tag/v6.3.0)

setFullScreen is a better function than presentFullscreenPlayer.
But this problem can't be fixed in my case.

When muted = true, fullscreen starts in muted state (fullscreen volume buttons and mute icon), but fullscreen volume buttons don't work properly.

When muted = false, fullscreen starts in unmuted state, fullscreen volume buttons can be muted/unmuted and volume can change, but if repeat is on, muted is will be unmuted again when repeated.

Also, fullscreen mute change can't be detected, so own ui mute icon can't change when back from fullscreen.

And fullscreen volume is device volume, not video volume.

I tried several things but can't solve this problem.
It seems the only way is to prepare my own fullscreen with controller without setFullscreen function.

Any solutions?

**Comment by jadus** [comment]
Hi,
Same problem here on iOS, anyone found a solution ?
