### ISSUE TITLE
Android app crashes when controls are enabled with ExoPlayer

### ISSUE THREAD

**Issue by adamivancza** [TheWidlarzGroup/react-native-video#1846]
# Bug

If I enable the controls property upon rendering the android app crashes. Stacktrace: 

```
java.lang.IndexOutOfBoundsException: index=1 count=0
    at android.view.ViewGroup.addInArray(ViewGroup.java:5381)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5274)
    at android.view.ViewGroup.addView(ViewGroup.java:5083)
    at com.brentvatne.exoplayer.ReactExoplayerView.addPlayerControl(ReactExoplayerView.java:326)
    at com.brentvatne.exoplayer.ReactExoplayerView.setControls(ReactExoplayerView.java:1183)
    at com.brentvatne.exoplayer.ReactExoplayerView$4.run(ReactExoplayerView.java:395)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6986)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

## Platform
Android ExoPlayer only

## Environment info
React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
      Memory: 356.16 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 19, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.9.0 => 16.9.0 
      react-native: 0.59.9 => 0.59.9 
```

Library version: 5.1.0-alpha1
Tried with: 4.4.4 and 4.4.2 also

## Steps To Reproduce

1. Set `controls` property to true
2. App crashes
...

## Expected behaviour

1.  Set `controls` property to true
2. App not crashes

## Reproducible sample code

```import React, { PureComponent } from 'react';
import { StyleSheet, TouchableOpacity, View, Platform } from 'react-native';
import PropTypes from 'prop-types';
import Video from 'react-native-video';

import { GREY_4, BROWN } from '../styles/colors';

export class VideoPlayer extends PureComponent {
  static propTypes = {
    videoUri: PropTypes.string.isRequired,
    videoThumbnail: PropTypes.string,
    fullScreen: PropTypes.string,
    onExitFullScreen: PropTypes.func,
  };

  constructor(props) {
    super(props);

    this.state = {
      muted: false,
      paused: true,
      showThumbnail: Platform.OS === 'ios', // only show thumbnail on iOS - android is broken
    };
  }

  componentDidMount() {
    const { fullScreen } = this.props;
    if (!fullScreen) { return null; }
    if (this.videoPlayer) {
      this.timeout = this.setFullScreenTimeout();
    }
    return null;
  }

  componentWillUnmount() {
    clearTimeout(this.timeout);
  }

  onProgress = () => {
    this.setState({ showThumbnail: false });
  };

  onEnd = () => {
    this.setState({ paused: true });
    this.video.seek(0);
  };

  onAudioBecomingNoisy = () => {
    this.setState({ paused: true });
  };

  onAudioFocusChanged = (event: { hasAudioFocus: boolean }) => {
    this.setState({ paused: !event.hasAudioFocus });
  };

  onFullscreenPlayerDidDismiss = () => {
    const { onExitFullScreen } = this.props;
    if (onExitFullScreen) { onExitFullScreen(); }
    return null;
  }

  setFullScreenTimeout() {
    setTimeout(() => {
      this.videoPlayer.presentFullscreenPlayer();
    }, 100);
  }

  video = Video;

  render() {
    const { videoUri, videoThumbnail } = this.props;
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.fullScreen}
          onPress={() => this.setState({ paused: !this.state.paused })}
        >
          <Video
            ref={(ref) => { this.videoPlayer = ref; }}
            /* For ExoPlayer */
            source={{ uri: videoUri }}
            poster={this.state.showThumbnail ? videoThumbnail : null}
            posterResizeMode="cover"
            controls
            style={styles.fullScreen}
            paused={this.state.paused}
            muted={this.state.muted}
            onProgress={this.onProgress}
            onEnd={this.onEnd}
            onAudioBecomingNoisy={this.onAudioBecomingNoisy}
            onAudioFocusChanged={this.onAudioFocusChanged}
            onFullscreenPlayerDidDismiss={this.onFullscreenPlayerDidDismiss}
            repeat={false}
          />
        </TouchableOpacity>
      </View>
    );
  }
}


const styles = StyleSheet.create({
  container: {
    height: 189,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: BROWN,
    borderWidth: 3,
    borderColor: GREY_4,
  },
  fullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});

export default VideoPlayer;
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by wmccoubrey** [comment]
@adamivancza did you ever get a solution to this? I am hitting the same issue with this version?

**Comment by adamivancza** [comment]
@wmccoubrey yeah I found a workaround. Turned out this only happens if the <Video \> component was not returned on render function for the first render. E.g.
This works:
`render() {
return <Video />
}
`

And this crashes:
`render(){
if(loading) return <Loading \>
return <Video \>
}`

Hope this helps you as well.

**Comment by trilam1409** [comment]
@adamivancza I follow your way. It works.

Do you know what reason to make this error?

Is there any way to use  
`render(){ if(loading) return <Loading \> return <Video \> }`

**Comment by adamivancza** [comment]
@trilam1409 thx for the feedback - I'm glad that at least my workaround works :).

Based on the stack track I've attached it crashes inside native ExoPlayer lib.

**Comment by trilam1409** [comment]
@adamivancza thank you very much. I spent a long time for this error.

I'm using  `react-native-video@5.1.0-alpha2` and `react-native@0.61.5` for a new app.

But I used to make another app. It also includes a video. **Still working well** with `react-native-video@5.1.0-alpha2` and `react-native@0.62.1`.

If anyone sees this problem, you can convert to the old version.

Once again, thanks for your support.

**Comment by golya** [comment]
@adamivancza I tried your workaround but it does not work for me, sometimes it is fine sometimes it is crashing. 
Did you try in production and everything was fine with it?

**Comment by adamivancza** [comment]
@golya yeah it's used in production and I didn't see any crashes related to this on Sentry.

**Comment by golya** [comment]
@adamivancza thanks for your quick response, I am not sure what is the difference. :(

**Comment by adamivancza** [comment]
@golya actually the app is using my own fork for some time now. My fork is at alpha-6 + this [PR](https://github.com/react-native-video/react-native-video/pull/1669). https://github.com/adamivancza/react-native-video#bd8ad569280bc40ca1695322c7ca8e798f16d00e

**Comment by golya** [comment]
@adamivancza thanks! however it seems the pull request is an iOS change. I will try your fork as well. On the other it seems I have to debug because it still not really normal that you have to use a workaround for a really basic feature.

**Comment by golya** [comment]
@cobarx I am going to debug this issue, do you know where should I start or know someone who can help facilitate the solution? (I tagged you as I am not sure who is the main contributor of this package. :) )

**Comment by golya** [comment]
It seems I found a solution, in file android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:
``` 402     /**
 403      * Adding Player control to the frame layout
 404      */
 405     private void addPlayerControl() {
 406         if(player == null) return;
 407         LayoutParams layoutParams = new LayoutParams(
 408                 LayoutParams.MATCH_PARENT,
 409                 LayoutParams.MATCH_PARENT);
 410         playerControlView.setLayoutParams(layoutParams);
 411         int indexOfPC = indexOfChild(playerControlView);
 412         if (indexOfPC != -1) {
 413             removeViewAt(indexOfPC);
 414         }
 415         addView(playerControlView, 1, layoutParams);
 416     }
```
if you change the line 415 to. `addView(playerControlView);` then there is no crash.

**Comment by frank-west-iii** [comment]
Without wanting to fork we were able to work around this in our codebase today.

With the controls set to `false` the error goes away. I am guessing the controls are rendering ahead of the player in some sort of race condition.

Our solution ran counter to what was stated above as a solution. Our component was being rendered immediately on the initial mount of the component and adding a no-render ended up solving our issue.

```
const [render, setRender] = useState(false);
useEffect(
  function() {
    setTimeout(() => setRender(true), 0);
  },
  [setRender]
);

if (!render) return <Fragment />;

return (
  <Video controls={true} {...props} />
);
```

**Comment by se09deluca** [comment]
@frank-west-iii  workaround works for me! 

thank you 👍🏻 

I made it work using a component like that:
```
const VideoWithControls = ({ ...props }) => {
  const [render, setRender] = useState(false);
  useEffect(
    function () {
      setTimeout(() => setRender(true), 0);
    },
    [setRender],
  );

  if (!render) {
    return <></>;
  }

  return <Video controls={true} {...props} />;
};
```



> Without wanting to fork we were able to work around this in our codebase today.
> 
> With the controls set to `false` the error goes away. I am guessing the controls are rendering ahead of the player in some sort of race condition.
> 
> Our solution ran counter to what was stated above as a solution. Our component was being rendered immediately on the initial mount of the component and adding a no-render ended up solving our issue.
> 
> ```
> const [render, setRender] = useState(false);
> useEffect(
>   function() {
>     setTimeout(() => setRender(true), 0);
>   },
>   [setRender]
> );
> 
> if (!render) return <Fragment />;
> 
> return (
>   <Video controls={true} {...props} />
> );
> ```
