### ISSUE TITLE
How do I play the video resource in the local absolute path

### ISSUE THREAD

**Issue by yanglingnan** [TheWidlarzGroup/react-native-video#1852]
How do I play the video resource in the local absolute path

uri: "file:///var/mobile/Containers/Data/Application/0EDB7D7A-358E-4EFC-9251-202BBBBC0E83/Library/Caches/Camera/CB1453E4-5F96-4350-B9DB-577E6A20FB62.mov"

**Comment by univalchemist** [comment]
I am also facing issue in playing audio with the local path.
uri: 'Users/admin/Library/Developer/CoreSimulator/Devices/1737D694-25E7-4AAD-AF7F-3C27BDDB05E1/data/Containers/Data/Application/482505EB-FC20-49D4-A6D8-A2E1087956D6/Documents/Harry Potter and the Philosophers Stone/6.mp3'

**Comment by AndriyShpyra** [comment]
I Have the same issue. Have someone found how to do it?

**Comment by binhnt12** [comment]
I have same issue with path: file:///storage/0403-0201/Music/ekscts.mp3 on android device

**Comment by dorthwein** [comment]
Same... on ios though - any updates?

**Comment by dorthwein** [comment]
So i'm only using this to play MP3s and my issue was the downloaded filepath didnt have .mp3 at the end.  Ensuring it had this made the local uris work.
