### ISSUE TITLE
PIP support for android in case of nested screen 

### ISSUE THREAD

**Issue by nitesh3539** [TheWidlarzGroup/react-native-video#1858]
I want to use PIP mode in  child screen such that PIP mode comes on top of parent screen.

Like if we have parent screen A and child screen B, If we are in screen B and want to allow Screen B to go In PIP mode, Then , screen B comes as PIP mode on top of Screen A.

Please help me out.

Thanks

**Comment by matejpolak** [comment]
Hi @nitesh3539, the above described scenario is not an ideal case for PIP mode. PiP mode in general behaves differently on each platform, like this:

So far, PiP mode as is, is working only on Android and iOS (iPad ONLY!)
1. iOS (iPad) - Should be working same as you described above.
2. Android - When entering PIP mode (by setting `pictureInPicture` prop, or pressing Home/Recent button) Whole app goes to PIP, so the app itself if minified and you see the android home screen for example and the minified app in a PIP window above it.

But the case you are describing is fully achievable by styles of the player window (if player is screen B). I have it like this in several projects already.

See:
![65509102-fe732180-ded1-11e9-829b-09c92e47ae68](https://user-images.githubusercontent.com/31282181/71416760-45ec8380-2662-11ea-9bbc-645225adcbb4.gif)

![65509104-003ce500-ded2-11e9-9af2-bf2190e4fa21](https://user-images.githubusercontent.com/31282181/71416766-4a18a100-2662-11ea-944e-96be6bcd65b0.gif)

![65509110-016e1200-ded2-11e9-84b0-3686ee469aaa](https://user-images.githubusercontent.com/31282181/71416773-500e8200-2662-11ea-90db-1b9333a35273.gif)

All those examples are combination of styles and PanResponers, and obviously it's working on all platforms.

**Comment by nitesh3539** [comment]
can you reference me with a set of code ?

Thanks

**Comment by nitesh3539** [comment]
Hi @matejpolak please update me on this. I need a neet explanation for this.

Thanks

**Comment by matejpolak** [comment]
Hi @nitesh3539, please think about the player as of any other UI element like a div or View for example. You can style it in any way you like, you can for example make it rounded and bouncing on the screen, same as any other element. So in my case, I have a MiniPlayerContainer component, which receiver all the player UI elements and Video component as a children prop and render it like this.

```
    return renderMiniPlayerContainer ? (
        <Animated.View
            style={{
                position: 'absolute',
                bottom: isMiniPlayer ? margin : 0,
                right: isMiniPlayer ? margin : 0,
                transform: [{ translateX: this.translateX }],
                width: this.playerWidth.interpolate({
                    inputRange: [0, 100],
                    outputRange: ['0%', '100%']
                }),
                height: this.playerHeight.interpolate({
                    inputRange: [0, 100],
                    outputRange: ['0%', '100%']
                })
            }}
            {...(isMiniPlayer ? this.panResponder.panHandlers : {})}
        >
            <View
                // We must keep both views,
                // because Animated.View doesn't have onLayout callback prop
                style={styles}
                onLayout={this.onContainerLayout}
            >
                {children}
            </View>
        </Animated.View>
    ) : (
        children
    );
```

In the code above, width and height are either 100 and 100 (fullscreen player), or any other value like 25 and 30 (landscape miniplayer). Hope this helps. Please consider this as a non tested raw snippet explaining my idea behind it.

**Comment by matejpolak** [comment]
And for the swipe gesture, you can use something like this: https://medium.com/@andi.gu.ca/exploring-react-natives-panresponder-and-layoutanimation-dde77e7f4cc9. 

But again, please, this is only my idea, and there are of course similar/better/more... ways how to achieve above described behavior.

**Comment by sharan-SKY** [comment]
Can this be merged please? Dont want to reinvent the wheel to make PiP for android. 😄
