### ISSUE TITLE
[iOS] iTunes playback stopped even if video is muted

### ISSUE THREAD

**Issue by skizzo** [TheWidlarzGroup/react-native-video#186]
Is there any way to prevent other audio sources (like iTunes) from stopping playback when the Video component is used? Would be super cool and I guess I'm not the only one who wants to use a muted video. Thing is, not even setting the <Video>'s `muted` property to `true`or its `volume`property to `0` currently leaves other sound sources playing in the background. Any ideas?

**Comment by ivanbrens** [comment]
+1

**Comment by mskalra** [comment]
+1

**Comment by mskalra** [comment]
Found the answer: https://github.com/brentvatne/react-native-video/pull/201/commits/c2272bc8d65906de4e7366c15fc3bf59f4783874 

Enjoy!
