### ISSUE TITLE
playInBackground is not working in ios

### ISSUE THREAD

**Issue by tomNjerry** [TheWidlarzGroup/react-native-video#1860]
### Current behavior
* playInBackground is not playing the audio while the app is in the background if target OS for ios is  13.0 also after enabling the audio capabilities.

### Reproduction steps
* enable the audio capability for the app.
* build the project targeting ios 13.0.
 

### Expected behavior
* should play audio while the app is in the background

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by fidelsam1992** [comment]
@tomNjerry I am facing the same issue, it looks like a bug with iOS 13
https://forums.developer.apple.com/thread/121990

**Comment by anastely** [comment]
Are you solve it?
