### ISSUE TITLE
How to Continues video player when switching Tab?

### ISSUE THREAD

**Issue by tarahiw** [TheWidlarzGroup/react-native-video#1861]
# Hi I'm trying to build a music player with this library

## Why it is needed

I need to fully understand the life cycle of this library Because I'm going to control Navigation / NAVIGATE and  on this library Navigation / BACK

I'm going in time Navigation / BACK Player to continue

**Comment by ThadeusAjayi** [comment]
You can use NavigationEvents props: onDidBlur to pause when you navigate from the player and onDidFocus to play when you come back to the player component.
If you're using react navigation
