### ISSUE TITLE
Support for local subtitles/textTrack

### ISSUE THREAD

**Issue by ysrarff** [TheWidlarzGroup/react-native-video#1864]
# Feature Request

Support for local subtitles/textTrack

## Why it is needed

This feature could possibly avoid devs from having to do any complex video processing tasks for simple use cases such as rendering texts on videos (E.G. avoid setting up and using react-native-unimodules and react-gl)

## Possible implementation

Hi, great plugin you guys have here, the documentation was clear and integrating it into my project was a breeze. Anyway, I would like to know if there would be a future support for locally adding subtitles to the video. In this case, I have my local subtitle (.VTT) file generated from [react-native-fs](https://github.com/itinance/react-native-fs) and I tested it and it didn't work but using external .VTT files hosted on a remote server such as [this one](https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt) works!

### Code sample

```
const getFile = await RNFS.readDir(RNFS.DocumentDirectoryPath);
const file = getFile[0].path; // <--- path to local subtitle

...


<Video
    source={{ uri: this.state.uri }}
    style={style.videoPlayback}
    repeat={true}
    textTracks={[
            {
                title: "English CC",
                language: "en",
                type: TextTrackType.VTT, // "text/vtt"
                uri: file // ...or implement something along the lines of require(file)
            },
        ]}
    selectedTextTrack={{ type: 'title', value: "English CC" }}
/>
```

**Comment by shababcreative** [comment]
Local subtitles files work fine for me, make sure your app have storage permission, I even added support for `.ass` files by converting it to `.vtt` using [react-native-ffmpeg](https://github.com/tanersener/react-native-ffmpeg)

**Comment by cgtarmenta** [comment]
@shababcreative what about embedded srt tracks?

**Comment by davekedar** [comment]
Will this work on version 61 or above?
