### ISSUE TITLE
download video manualy

### ISSUE THREAD

**Issue by milad145** [TheWidlarzGroup/react-native-video#1866]
hey everyone,
i'm using this module for play video in my app, but i don't want the video loaded or downloaded automatically because of data usage, i want it start downloading after press play button.
is there a way for it?
sory because of my poor english

**Comment by ThadeusAjayi** [comment]
When you mount your component, if the play state is paused, it doesnt start downloading until you set the paused state to false, then buffering starts and then download starts.
