### ISSUE TITLE
seek() jump inaccurate

### ISSUE THREAD

**Issue by ChenPrince** [TheWidlarzGroup/react-native-video#1873]
example:
when input seek(125),The player will play at random a few seconds ahead of schedule,such as  from 123 seconds.
I don't know if it's a video source problem

**Comment by lkretvix** [comment]
This just happened to me as well, my issue more being that it will always go to the closest ~5 seconds before the time set to seek (i.e. seek 8, goes to ~5). This StackOverflow post describes the issue pretty well: https://stackoverflow.com/questions/57592417/unexpected-behaviour-using-seek-in-react-native-video

**Comment by ChenPrince** [comment]
> This just happened to me as well, my issue more being that it will always go to the closest ~5 seconds before the time set to seek (i.e. seek 8, goes to ~5). This StackOverflow post describes the issue pretty well: https://stackoverflow.com/questions/57592417/unexpected-behaviour-using-seek-in-react-native-video

I've looked at players on some commercial apps and found that they are more or less affected by this situation(Is it normal?) , it's said on the Internet that it's related to keyframes

**Comment by lkretvix** [comment]
> I've looked at players on some commercial apps and found that they are more or less affected by this situation(Is it normal?) , it's said on the Internet that it's related to keyframes

Hmm I wonder if there's a workaround for it then. It appears to not affect the player on iOS, so my assumption is that it may be an issue with Google's Exoplayer.

**Comment by ChenPrince** [comment]
> > I've looked at players on some commercial apps and found that they are more or less affected by this situation(Is it normal?) , it's said on the Internet that it's related to keyframes
> 
> Hmm I wonder if there's a workaround for it then. It appears to not affect the player on iOS, so my assumption is that it may be an issue with Google's Exoplayer.

Hmm I can only create an illusion to make dragging more accurate and smooth, but in fact it is not accurate.

**Comment by pyeonjaesik** [comment]
@ChenPrince Hi did you solve this error?
