### ISSUE TITLE
Trying to download video with .mp4 link > getting "Error: Error decoding image data"

### ISSUE THREAD

**Issue by levelingup** [TheWidlarzGroup/react-native-video#1875]
## Bug
getting this error:  **Error: Error decoding image data** when I'm trying to download a .mp4 video that's an https://

this is what I have
```
const repostSubmit = async () => {
  const mediaArray = props.navigation.state.params.media;
  try {
    for (let media of mediaArray) {
      await CameraRoll.saveToCameraRoll(
        'https://some.mp4/url',
      );
    }
  } catch (error) {
    console.log('catch error media submit: ', error);
  }
}

```

then when I take off the /url, and just leave .mp4 without anything trailing, I get this error:  **Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)**

## Platform
* iOS

## Environment info

React Native version 0.61.5
Library version: 1.3.0

**Comment by levelingup** [comment]
If anyone who is curious, I skipped the documentation where remote urls **does not** work with CameraRoll. What I had to do was use rn-fetch-blob to save the file onto the device and then use CameraRoll as a supplement to grabbing the video file.

**Comment by eyalabadi98** [comment]
@levelingup can you show us a code sample of how you accomplished it?
