### ISSUE TITLE
Separated Player from Component

### ISSUE THREAD

**Issue by Ufosek** [TheWidlarzGroup/react-native-video#1876]
Hello,

I am migrating from Native iOS & Android to RN with my app. I have a feature that user can start a video, then close it but audio would be still playing in background. User then can go to the other screen and the same video will continue to play (without any pause).

The way I was doing it on Native side was to have separated VideoPlayer and I was injecting it into views when needed (actually on iOS I had a reference to `PlayerView` and I just added it as subview. On Android side I injected it by setting `playerView.player = videoPlayer.getPlayer()`)

Is it possible to do so with this great library? Or I have to use my Native code for handling this?

Regards

**Comment by benoitdion** [comment]
Hi @Ufosek, take a look at the [playinBackground](https://github.com/react-native-community/react-native-video#playinbackground) prop

**Comment by Ufosek** [comment]
@benoitdion Thanks but this is not my case. I don't have a problem with playing in background but with playing the same player on 2 different views. Recently I started implementing my own native player and I will post my solution here when it will be ready.

**Comment by benoitdion** [comment]
Got it! As you now know, player re-use across views is currently not a supported feature.

**Comment by klaaz0r** [comment]
+1 for this, I am playing audio and video and separating the "View" from state would be perfect, so I can have a minified player on the screen and play audio without any components.

**Comment by Ufosek** [comment]
@benoitdion @klaaz0r 
I just released very first version of my library to handle this issue: [react-native-standalone-video-player](https://github.com/SparingSoftware/react-native-standalone-video-player).
It is still without official and stable release yet but IMO already useful.
