### ISSUE TITLE
why the video stop after play a few minutes in android？

### ISSUE THREAD

**Issue by MingHaoDu** [TheWidlarzGroup/react-native-video#1877]
# problem
when I play online videos ,it stops after play a few minutes,but the local video  play normally.

**Comment by MingHaoDu** [comment]
Has anyone had this problem?

**Comment by wenlynnchen** [comment]
I have the same problem! Video stops after few minutes and there was no error. Does anyone knows how to fix the problem? Thanks a lot!

**Comment by sandsame** [comment]
I have the same problem!Does anyone knows how to fix the problem?Thanks a lot

**Comment by yairtal** [comment]
same problem here

**Comment by pdsouza** [comment]
Have you tried switching from the default MediaPlayer to ExoPlayer? I have noticed that ExoPlayer performs better. See [instructions to enable ExoPlayer](https://github.com/react-native-community/react-native-video#androidsettingsgradle).

**Comment by wenlynnchen** [comment]
> Have you tried switching from the default MediaPlayer to ExoPlayer? I have noticed that ExoPlayer performs better. See [instructions to enable ExoPlayer](https://github.com/react-native-community/react-native-video#androidsettingsgradle).

But I am not using Expo

**Comment by pdsouza** [comment]
> > Have you tried switching from the default MediaPlayer to ExoPlayer? I have noticed that ExoPlayer performs better. See [instructions to enable ExoPlayer](https://github.com/react-native-community/react-native-video#androidsettingsgradle).
> 
> But I am not using Expo

**ExoPlayer** is not related to Expo. This is an Android video player library that `react-native-video` can optionally use rather than the default MediaPlayer.

**Comment by wenlynnchen** [comment]
@pdsouza I see! I will try ExoPlayer. But is there any props I can use to control which player I want to use? Also, how can I enable ExoPlayer? I read the instructions, I only have to add following code to my app/build.gradle file? Thanks!!


```
android {
   ... // Various other settings go here
   compileOptions {
     targetCompatibility JavaVersion.VERSION_1_8
   }
}
```

**Comment by rfischer20** [comment]
We are facing the same issue and will try exo but reviewing past tickets, it looks like this may have happened before to others. If anyone has succeeded in getting this to work please share. This looks to be a pretty big breaking issue.

**Comment by pdsouza** [comment]
@wenlynnchen If you're on RN >= 0.60, which does autolinking of native modules, it should be sufficient to add this to `android/settings.gradle`:

```
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

If you are using a version of RN < 0.60, you should follow the manual instructions [here](https://github.com/react-native-community/react-native-video#android-installation).

**Comment by dbilgin** [comment]
@pdsouza Your solution seems to be crashing the app for me unfortunately.

**Comment by valascus** [comment]
Still having this issue, even with exoplayer. This is a huge bug.

**Comment by liquidvisual** [comment]
This is such a massive bug. How are people actually shipping apps with video reliance under React Native? :/

**Comment by valascus** [comment]
> This is such a massive bug. How are people actually shipping apps with video reliance under React Native? :/

I don't... I'm using expo-av video player. can't use this package anymore. Good luck to the warriors that keep using this package.

**Comment by liquidvisual** [comment]
@valascus I wish I could move my current project to Expo, looks good. Is the expo-av player able to run ads, out of curiosity?

**Comment by valascus** [comment]
> @valascus I wish I could move my current project to Expo, looks good. Is the expo-av player able to run ads, out of curiosity?

I didn't move to expo. I'm using unimodules. No, as far as I know.

**Comment by kesha-antonov** [comment]
Maybe related https://stackoverflow.com/questions/14890827/android-mediaplayer-stops-after-half-an-hour-of-playback

**Comment by freeboub** [comment]
Lack of information in this ticket... No platform information, no trace provided, no sample url.
Then, It cannot be investigated.

**Comment by satyabrata-dash5** [comment]
same problem with me
