### ISSUE TITLE
List of videos results in error code 1001

### ISSUE THREAD

**Issue by kp-98** [TheWidlarzGroup/react-native-video#1878]
When i try to load my videos in I get the following error: 

```
error: {domain: "NSURLErrorDomain", code: -1001}
target: 2149
```
That's it, there is no other information and I couldnt find anything on the web. If you have any idea what this means please let me know. All URLs I am using do in fact exist. I am loading a vertical list of horizontal lists of videos , so you can scroll left and down. The videos that get this error are totally sporadic:

```
x = [1 , 2, 3, 4, 5,]
y = [6, 7, 8, 9, 10, 11, 12, 13, 14]
z = [15,]
```

Sometimes this error is on video 1, 4, 5, 7, 15, etc,
Totally random, sometimes it happens to many, sometimes to none. My render ahead horizontally is 3 videos and my render ahead vertically is 2

**Comment by fmartins** [comment]
👍

**Comment by fernandatoledo** [comment]
Hey! I'm having the same issue, were you able to fix this? Thank you!

**Comment by meetp-zluck** [comment]
Hi! I am having the same issue. We are developing an app that has similar feature to Youtube shorts/IG reels.
In slow connection, we'd get below in couple of seconds. In same slow connection Youtube shorts/IG reel video works. But we get below:

```
{
    "localizedRecoverySuggestion": "",
    "code": -1001,
    "localizedFailureReason": "",
    "domain": "NSURLErrorDomain",
    "localizedDescription": "The request timed out."
}
```

Is there any way to fix this?

**Comment by MrXyfir** [comment]
Did anyone figure this out? It started happening randomly ever since upgrading Expo, React Native, and this package to v6. I tried switching to entirely different hosts for the videos and that hasn't solved it.

**Comment by muhammad-kumail** [comment]
Still facing issue in ios using v^6.7.0.
