### ISSUE TITLE
onPlaybackRateChange not called

### ISSUE THREAD

**Issue by baconcheese113** [TheWidlarzGroup/react-native-video#1879]
# Bug

Unable to get onPlaybackRateChange to fire when using Android emulator and physical device. Haven't checked iOS.

## Platform
I'm unsure how to tell if I'm using ExoPlayer or Mediaplayer.

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
 OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 19.27 GB / 31.95 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

## Steps To Reproduce

```
    <Video
      key={currentVideo}
      style={{
        width: "100%",
        height: 300
      }}
      paused={paused}
      ref={player}
      playWhenInactive
      onPlaybackRateChange={() => console.log("playback change")}
      onSeek={handleSeek}
      onProgress={handleProgress}
      source={{ uri: videoUrl }}
      resizeMode="contain"
      controls
      disableFocus
      playsInline
      fullScreen={false}
    />
```

## Expected behaviour

1. `onPlaybackRateChange` should be called with the current playrate when it's changed

**Comment by adamivancza** [comment]
I'm experiencing the same on Android using ExoPlayer. I'm using react-native 0.59.9 and react-native-video 4.4.4.

It seems to me that the native 'onPlaybackParametersChanged' is not called and that's causing this bug: https://github.com/react-native-community/react-native-video/blob/b97663e09243836fd565e3def149b0bb94dfb82a/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L814

**Comment by baconcheese113** [comment]
Are there any other callbacks available for capturing onPause and onPlay? Better yet, if the user taps on the play button

**Comment by adamivancza** [comment]
There’s one for playing: https://github.com/react-native-community/react-native-video/blob/master/README.md#onprogress

But I didn’t find anything else for pause 😒

**Comment by baconcheese113** [comment]
I went back to 4.4.0 to try to figure out where it broke and it doesn't seem like it was working there either. Unable to check before that due to a flood of dependency errors.

**Comment by baconcheese113** [comment]
Well, since I can't even get the examples to run with the symlink'd package and deps...I just went ahead and implemented my own janky but functional pause/play tracker

```js
const PAUSED = 'PAUSED';
const PLAYING = 'PLAYING';
const prevMillis = React.useRef();
const prevPlayerTime = React.useRef();
const curState = React.useRef();
const probablyPlaying = React.useRef(0);
const probablyPaused = React.useRef(0);

const handleProgress = progress => {
  const { currentTime } = progress;
  const currentMillis = Date.now();
  // worldDelta is Date.now() - prevMillis - should be positive time like 300
  const worldDeltaSeconds = (currentMillis - prevMillis.current) / 1000;
  // playerDelta is currentTime - prevPlayerTime - will be 300 if playing, negative if seeking backwards, 0 if stopped
  const playerDeltaSeconds = currentTime - prevPlayerTime.current;
  const worldPlayerDelta = Math.abs(worldDeltaSeconds - playerDeltaSeconds);
  // if curState is paused and Math.abs(worldDelta - playDelta) < .100 then setProbablyPlaying + 1 and setProbablyPaused 0
  if (worldPlayerDelta < 0.1) {
    probablyPlaying.current = probablyPlaying.current + 1;
    probablyPaused.current = 0;
  }

  // else if curState is playing and Math.abs(worldDelta - playDelta) < .350 then setProbablyPaused + 1 and setProbablyPlaying 0
  else if (worldPlayerDelta < 0.31) {
    probablyPaused.current = probablyPaused.current + 1;
    probablyPlaying.current = 0;
  } else {
    probablyPaused.current = 0;
    probablyPlaying.current = 0;
  }

  if (curState.current !== PLAYING && probablyPlaying.current === 2) {
    curState.current = PLAYING;
    console.log(PLAYING);
  } else if (curState.current !== PAUSED && probablyPaused.current === 2) {
    curState.current = PAUSED;
    console.log(PAUSED);
  }

  // Cache time values
  prevMillis.current = currentMillis;
  prevPlayerTime.current = currentTime;
};

```

**Comment by bigbadfatman** [comment]
Facing the same issue. Would be nice to hear from a contributor if, and when, it'll be fixed.

**Comment by bigbadfatman** [comment]
This issue [https://github.com/react-native-community/react-native-video/issues/1920] might be of help. It seems you might be defaulting to Mediaplayer instead of Exoplayer

**Comment by kylegillen** [comment]
Anybody find a workaround?

**Comment by limoli** [comment]
iOS works well, but Android doesn't trigger this event.

**Comment by dangkhoa2708** [comment]
Experiencing the same issue, any update guys ?

**Comment by jamesdarabi** [comment]
Just ran into the same issue. Works on iOS, but not Android. Here's my info incase that helps...

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 149.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 3.8.5 - /Users/jamesdarabi/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by dritonberisha1** [comment]
Same issue using this version 5.1.0-alpha8

**Comment by jackyleehong** [comment]
Yup. mine also facing the same problem using the latest version. It confirmed break on Android, IOS is working

**Comment by iddar** [comment]
Bug keep on `"react-native-video": "5.1.1"`

**Comment by pelaxa** [comment]
any updates on this?

**Comment by c0m1t** [comment]
Is there any way to fix this issue?

**Comment by tasosxak** [comment]
Any update ? Doesn't trigger this event on Android device using ExoPlayer, but works on iOS.

"react-native": "0.66.1",
"react-native-video": "https://github.com/r0b0t3d/react-native-video.git#feature/android-fullscreen"

**Comment by c0m1t** [comment]
No. Go away stale bot.

@hueniverse Could you please take a look at this issue?

**Comment by hueniverse** [comment]
If someone can fork https://github.com/hueniverse/react-native-video-test to recreate the bug on Android, I'll take a look and see if I can figure it out.

**Comment by jrhager84** [comment]
@hueniverse Was this ever fixed? I'm facing the same issue.

**Comment by kirgy** [comment]
This is still an active issue in July 2022. There's no reliable way to determine video play/pause state on Android.

**Comment by freeboub** [comment]
@kirgy See onPlaybackStateChanged on V6

**Comment by dehimer** [comment]
Is it still actual?
