### ISSUE TITLE
DRM support

### ISSUE THREAD

**Issue by XBDRX** [TheWidlarzGroup/react-native-video#188]
Are there any plans to support widevine/playready etc?

**Comment by mattapperson** [comment]
Not at this time due to needing to then distribute their SDKs (that would not be legal)

**Comment by Phenek** [comment]
Any news about DRM?
Because on WWDC 16 Apple said that:
Support MPEG Common Encryption (CENC)
		• supports FairPlay streaming with cbcs mode
		• first step to harmonize all DRM technologies
		• in the future you should be able encode and encrypt your content once and use it with 		Widevine, PlayReady, PrimeTime and FairPlay

@mattapperson Is it usable now? 6month later, I didn't find good information about that..

**Comment by RWOverdijk** [comment]
👍

**Comment by mattapperson** [comment]
Honestly this is not something I know enough about to speak intelligently on. But as far as I know this is still not something we can legally support... if I'm wrong and someone submits a PR for DRM support that does not bundle a drm lib illegally I would be extatic to merge it asap

**Comment by RWOverdijk** [comment]
I'll try to find some more info on this. Surely there's an option somewhere? Or is the problem the custom player?

**Comment by mattapperson** [comment]
@RWOverdijk my understanding here is that the issue is connected with the distribution of the 3rd party libraries needed to enable DRM along with lack of built-in support for them on iOS meaning iOS would have to move to a new player. Making this a very large task that even if completed might pose legal issues. All these items can technically be worked around but it would be a massive undertaking

**Comment by RWOverdijk** [comment]
@mattapperson Sorry for the questions, but maybe I can eventually help out if I have enough info... How would one go about implementing a fairplay-ready player for iOS then? Perhaps using that path, I can figure out a solution. I happen to know some people that had early access to fair play, so maybe they can help me get something (if needed) from apple.

**Comment by aryan007** [comment]
Hi 

I saw this commit 
https://github.com/react-native-community/react-native-video/pull/789/files?diff=split

Does this mean that it supports DRM content now ?

**Comment by acollazomayer** [comment]
Is this true? does this library now supports DRM please let me now

**Comment by amirpervaiz086** [comment]
Hi guys, do we have DRM support for iOS (FairPlay) or Android (dash)? any pointers would be appreciated. thanks

**Comment by acollazomayer** [comment]
@amirpervaiz086 This library does not provide iOS Fairplay support. And there is a work in progress PR that supports DASH DRM. https://github.com/react-native-community/react-native-video/pull/789
