### ISSUE TITLE
Video freezes when I enter fullscreen

### ISSUE THREAD

**Issue by oscadev** [TheWidlarzGroup/react-native-video#1884]
video player works, but when I enter fullscreen, the audio keeps playing fine, but the video freezes on a frame after like 2 seconds of going full-screen, and stays that way. Playing the video without fullscreen at max width and height also works fine, but then I dont have access to the seeking and other controls.

**Comment by eyalabadi98** [comment]
Same issue. Any solution?

**Comment by oscadev** [comment]
@eyalabadi98 hey, if you are also working on a React Native TVOS project, I solved the issue by not using fullscreen=true at all, and instead just set the dimension of the player to be full screen. You can still access the controls (play, pause etc) through props (enableControls=true or whatever it was called).

**Comment by eyalabadi98** [comment]
oh ok interesting, im working on IOS, so ill take a look at it! Thanks

**Comment by brandtnewlabs** [comment]
What happened? This issue still exists 1 year later. Did you find a workaround?

**Comment by aryella-lacerda** [comment]
This is a problem for me, too. Anyone found a solution or a workaround?

**Comment by oscadev** [comment]
> What happened? This issue still exists 1 year later. Did you find a workaround?

The solution was to not use “full screen” at all. I thought I needed fullscreen to have access to the controls like on an iPhone, but TV is different. It doesnt use “fullscreen”, and you can still access the control overlays with “enableControls = {true}” or whatever the parameter is called.
