### ISSUE TITLE
MP4 container file with AAC audio throws AVFoundationErrorDomain -11800 on iOS

### ISSUE THREAD

**Issue by lesmo** [TheWidlarzGroup/react-native-video#1886]
Attempting to play a short (10 sec) MP4 video file hosted on Firebase Hosting with AAC audio throws:

```ts
{
  error: {
    domain: "AVFoundationErrorDomain",
    code: -11800
  },
  target: 7379
}
```

MP4 file encoded with the following settings on Adobe Premiere Pro:
![image](https://user-images.githubusercontent.com/2228196/73244892-94fd6b00-4170-11ea-941e-abc790412e7f.png)

At first I thought I picked an unsupported video codec, but rendering the video with different video codecs without audio results in proper playback. It just doesn't like the audio. I've also tried using different AAC sample rate and audio quality.

Browsing through the issues I couldn't find something similar.

**EDIT:** local playback works correctly, this seems to be an issue with streaming I guess?

## Platform
iOS 13.3 (so far on iPhone 11 Simulator)

## Environment info
<details>
  <summary>Click to expand</summary>

```bash
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 984.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 26, 27, 28
      Build Tools: 28.0.2, 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native: 0.61.4
```

Library version: 5.0.2
</details>

## Reproducible sample code
```ts
<Video
  style={{ width: '100%', height: '100%' }}
  source={{ uri: 'https://firebasestorage.googleapis.com/<the url>' }}
  resizeMode="cover"
  paused={false}
  playWhenInactive={true}
  onError={console.log}
/>
```

**Comment by Gabogg07** [comment]
Hello Lesmo I am having a similar issue, any workaround for this?

**Comment by lesmo** [comment]
> Hello Lesmo I am having a similar issue, any workaround for this?

Yes! Google Cloud Storage (and thus Firebase Storage) doesn't support streaming at all. iOS won't download the file, it'll try to download partial parts of the file which seems to be unsupported by Storage.

My workaround is to transcode the video into HLS with ffmpeg and use that instead. It works perfectly on Android and iOS, and has the added bonus of adaptive streaming.

I guess I'll close this issue since it's not a problem with the lib.
