### ISSUE TITLE
Can't display subtitle tracks on video - iOS

### ISSUE THREAD

**Issue by AndresTIY** [TheWidlarzGroup/react-native-video#1887]
# Bug

I'm not able to display subtitles on my video. Not sure if my code is incorrect or if I missed anything. 

I've tried:
- reinstalling all packages and pod install as well
- Setting tracks with local state onLoad. So it would look like
```js
const [textTracks, setTextTracks] = useState([])
const [selectedTextTrack, setSelectedTextTrack] = useState({ type: 'disabled' })

const onLoad = () => {
    setSelectedTextTrack({ type: 'index', value: 0 })
    setTextTracks({
        [
            {index: 0, language: 'en', type: TextTrackType.VTT, uri: captions.english },
            {index: 1, language: 'es', type: TextTrackType.VTT, uri: captions.spanish },
        ]
    })
}



<Video 
    ....
    onLoad={onLoad}
    selectedTextTrack={selectedTextTrack}
    textTracks={textTracks}
/>

```
 - - but that didn't work
- Setting text tracks and selected text track initially.

```js
<Video 
    ....
    selectedTextTrack={{type: 'index', value: 0}}
    textTracks={[
            {index: 0, language: 'en', type: TextTrackType.VTT, uri: captions.english },
            {index: 1, language: 'es', type: TextTrackType.VTT, uri: captions.spanish },
        ]}
/>

```
- - not only did this not work, but the video screen is just a white background and it will not play the video at all. 

That's it. Sample code is below. I'm hoping I'm just missing something

## Platform
iOS

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.48 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1


```

Library version: 5.0.2

## Steps To Reproduce

-  It may be hard to test and reproduce due to videos being internal
- I've tried setting `selectedTextTrack` 

...

## Expected behaviour

1. Expected subtitles to be displayed anywhere on the screen video screen

## Reproducible sample code

```js
import React, { useState, createRef } from 'react';

import { View } from 'native-base';

import Video, { TextTrackType } from 'react-native-video';

import styles from '../styles';

const VideoPlayer = ({ videoUrl, captions }) => {
  const videoRef = createRef();

  const { english, spanish } = captions;

  //  http://cdn1.name.com/captions/video-1-5-en.vtt
  // videoURL is an mp4 file

  return (
    <View>
      <Video
        ref={videoRef}
        paused={paused}
        controls={false}
        resizeMode="contain"
        style={styles.videoPlayer}
        source={{ uri: videoUrl }}
        selectedTextTrack={{
          type: 'index',
          value: 0,
        }}
        textTracks={[
          {
            index: 0,
            language: 'en',
            type: TextTrackType.VTT,
            uri: english,
          },
          {
            index: 1,
            language: 'es',
            type: TextTrackType.VTT,
            uri: spanish,
          },
        ]}
      />
    </View>
  );
};

export default VideoPlayer;
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by zosimanoz** [comment]
I am also having the same issue. Did anyone solved the issue ?

**Comment by lingtran** [comment]
We are also experiencing the textTrack display issue in iOS. Any insight and/or recommendations will be appreciated! 

**How we are seeing it:**
The captions we specify in the textTrack loads initially, but when we bring the app to the background and then return it to the foreground, the captions disappear. I know when I set `playInBackground={false}`, we don't experience captions issues. It is only when it is set to 'true' in iOS do we see this issue.

**Code snippet of some of the relevant properties, happy to say more if that'll help:**
```
     <ReactNativeVideo
         ...
         textTracks={[{
         title: 'English',
          language: 'en',
          type: 'text/vtt',
          uri: path
         }]}
         ...
         playInBackground={true}
         playWhenInactive={true}
       />
```
**Dependency versions:**
- react-native-library: 5.0.2
- react-native: 0.59.10
- react: 16.8.6

**Comment by AndresTIY** [comment]
Yes I'm still experiencing the issue. Subtitles did show for a moment a few days ago but I wasn't able to make it show again. I've moved on for now but still need to eventually get this working. I wonder if it's a nesting issue since I have [Screen] => [Video Container Component] => [Video]. I'll experiment when I can.

**Comment by lingtran** [comment]
Yes, keep us posted please!

**Comment by AndresTIY** [comment]
Not sure it this helps but I did manage to get my subtitles working and was able to replicate the bug. My video sources can be either m3u8 files or mp4 files. The m3u8 files seem to not work with subtitles but the mp4s are working just fine. 

@lingtran i think your issue is a bit different from mine but check your file type just in case!

edit: it's related to this issue: https://github.com/react-native-community/react-native-video/issues/1511

**Comment by romulomachado** [comment]
@lingtran I have the exact same issue. Did you manage to fix it? If so, can you share the solution? 

Thank you! :)

**Comment by hiteshtSociosquares** [comment]
i have same issue,
