### ISSUE TITLE
Is there a way to convert AVI to MP4 on the save function ?

### ISSUE THREAD

**Issue by brunods-dev** [TheWidlarzGroup/react-native-video#1890]
# Feature Request
 I've found this: 
https://stackoverflow.com/a/32391332/11700502
I tryed to implement but i don´t have skills on Obj-c.
Could someone helps me ?
thanks 

## Why it is needed
Because AVI is not suported on IOS

**Comment by benoitdion** [comment]
Hi @brunodias28, closing this issue as video format conversion outside of the scope of this project. You might have better luck asking this question on stackoverflow or in the reactiflux react-native channel.
