### ISSUE TITLE
Error on use Video component

### ISSUE THREAD

**Issue by Tautorn** [TheWidlarzGroup/react-native-video#1894]
# Bug
I have an youtube link, when I try using React-native-video components shows `{"error": {"extra": -2147483648, "what": 1}}` `onError` callback.

## Platform 
* Android

## Environment info

**System:**
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 188.69 MB / 15.36 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Library version: x.x.x**
"react": "16.9.0",
 "react-native": "0.61.5",
"react-native-video": "^5.0.2",

## Code

```
import React, { memo } from 'react'
import { View } from 'react-native'
import Video from 'react-native-video'

function Preview() {
  
  const onError = (error) => {
    console.log('onError,', error)
  }
  
  const onBuffer = (onBuffer) => {
    console.log('onBuffer,', onBuffer)
  }
  
  const player = useRef()
  
  return (
    <View>
      <Video
        onError={onError}
        onBuffer={onBuffer} 
        source={{uri: "https://www.youtube.com/watch?v=9lnqVP2LJfc"}}
        ref={(ref) => {
          player.current = ref
        }}    
      />
    </View>
  )
}

export default memo(Preview)
```

**Comment by skullet** [comment]
I am also getting this error

**Comment by talon-i-am** [comment]
I am getting this error on an Android emulator but on Android version 7. It works on Android version 9 for me.

**Comment by skullet** [comment]
I was able to get around this - it seems that without an extra configuration file to explicitly use Exoplayer the default player is used. I can't find the issue where I found this work around but if I do I'll link it back here.

Place this in your root directory for your app and name it react-native.config.js

    module.exports = {
      dependencies: {
        'react-native-video': {
          platforms: {
            android: {
              sourceDir: '../node_modules/react-native-video/android-exoplayer',
           },
          },
        },
      },
    };

**Comment by talon-i-am** [comment]
@skullet do you do a manual link then or just letting it auto link?

**Comment by skullet** [comment]
> @skullet do you do a manual link then or just letting it auto link?

auto link worked for me. I'm on RN 61.5

**Comment by dbilgin** [comment]
@skullet's solution crashes my app unfortunately.

**Comment by skullet** [comment]
> @skullet's solution crashes my app unfortunately.

Does logcat give any clues about what is happening?

**Comment by dbilgin** [comment]
@skullet Thanks for following up. I get the error below, any ideas?

```
 14849 14849 E AndroidRuntime: java.lang.IllegalArgumentException
 14849 14849 E AndroidRuntime: 	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
 14849 14849 E AndroidRuntime: 	at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:71)
 14849 14849 E AndroidRuntime: 	at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:59)
 14849 14849 E AndroidRuntime: 	at com.brentvatne.exoplayer.ReactExoplayerView$4.run(ReactExoplayerView.java:365)
 14849 14849 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
 14849 14849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
 14849 14849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
 14849 14849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
 14849 14849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
 14849 14849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 14849 14849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
  2048  2325 W ActivityTaskManager:   Force finishing activity xxx/.MainActivity
```

**Comment by talon-i-am** [comment]
worked for me, thanks @skullet

**Comment by skullet** [comment]
> @skullet Thanks for following up. I get the error below, any ideas?
> 
Unfortunately I don't know what this could be. I was getting the above error when playing DASH and HLS resources not youtube.

**Comment by dbilgin** [comment]
Thanks for taking a look anyway, I try to play it from my own server.

**Comment by dbilgin** [comment]
I have found the issue, turns out exo and `rate` prop don't get along well. It started working after removing it. Now it sometimes simply cannot download the file randomly, but when it does, it seems like it works fine.

**Comment by davidwico** [comment]
Thanks @skullet, it worked for me too

**Comment by Aung-Myint-Thein** [comment]
I still got the same error ... in RN 61.5 with "react-native link react-native-video" ... any suggestion? In my logcat, I found the following:

```
NuPlayerDriver: reset(0xf076bae0)
02-20 12:23:56.590   441  9832 D NuPlayerDriver: notifyListener_l(0xf076bae0), (1, 0, 0)
02-20 12:23:56.590   441  9832 D NuPlayerDriver: notifyListener_l(0xf076bae0), (8, 0, 0)
02-20 12:23:56.593   441 18117 W AMessage: failed to post message as target looper for handler 0 is gone.
02-20 12:23:56.593   441 18117 I ExtendedGenericSource: cancel poll buffering
02-20 12:23:56.593   441 18117 D NuPlayerDriver: notifyResetComplete(0xf076bae0)
02-20 12:23:56.594   441  9832 D NuPlayerDriver: reset(0xf076bae0)
02-20 12:23:56.595 15509 15509 W MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://vimeo.com/391510151
```

**Comment by rsimbu89** [comment]
> I was able to get around this - it seems that without an extra configuration file to explicitly use Exoplayer the default player is used. I can't find the issue where I found this work around but if I do I'll link it back here.
> 
> Place this in your root directory for your app and name it react-native.config.js
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>        },
>       },
>     },
>   },
> };
> ```

Thanks @skullet It's worked for me also.

**Comment by dphurley** [comment]
> I was able to get around this - it seems that without an extra configuration file to explicitly use Exoplayer the default player is used. I can't find the issue where I found this work around but if I do I'll link it back here.
> 
> Place this in your root directory for your app and name it react-native.config.js
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>        },
>       },
>     },
>   },
> };
> ```

Thanks @skullet! Worked for me as well.

**Comment by keyberth-rengel** [comment]
Error => {"error": {"extra": -1004, "what": 1}}

**Comment by upgradrh** [comment]
> 'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>        },
>       },
>     },

Getting this error after using this

{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}
