### ISSUE TITLE
Streaming private hls stream from cloudfront using signed URL

### ISSUE THREAD

**Issue by s4kh** [TheWidlarzGroup/react-native-video#1896]
# Feature Request
Serving private video(HLS dash stream) content from cloudfront which uses signed URL, add query param to playlist URLs.
## Why it is needed
we can create signed URL for playlist file but inside playlist file video files are not called with signedURL query params, so access denied is returned from cloudfront.
## Possible implementation
network request processor in react-native-video

**Comment by nriccar** [comment]
Nothing on this?

**Comment by s4kh** [comment]
you have to signed cookies on video storage folder to get it working. And pass cookies as headers in android, for iOS set cookies.

**Comment by f4z3k4s** [comment]
For anybody who might be struggling with this, the solution is [here](https://stackoverflow.com/questions/59363691/react-native-video-cookies).

**Comment by bob-user** [comment]
If you still want to use signed urls, you could try this little hack inspired this [comment](https://github.com/react-native-video/react-native-video/issues/1896#issuecomment-785796317) : 

- in your backend you sign the url with a custom policy giving access to all playlist files of your video [(doc)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html) : 
```
{
    "Statement": [
        {
            "Resource": "https://<pathToFile>.m3u8/*",
            "Condition": {
                ...
            }
        }
    ]
}
```

- in your video wrapper component :
*Specific code for video uri without query params except cloudfront ones*

```
const getHeaders = () => {
    let headers = { Cookie: '' }

    // uri of the video with the following format :
    // https://<pathToFile>.m3u8?Policy=<customPolicy>&Key-Pair-Id=<keyPairId>&Signature=<signature>
    const { uri } = props

    const splittedUri = uri.split('?')
    if (splittedUri.length < 2) return undefined

    const queryParamsString = splittedUri[1]
    const queryParams = queryParamsString.split('&')

    queryParams.forEach(param => {
        const [name, value] = param.split('=')
        headers.Cookie += (`CloudFront-${name}=${value};`)
    })

    return headers
 }
```

and then 

```
<Video
    source={{
        uri,
        headers: getHeaders()
    }}
/>
```
