### ISSUE TITLE
Android exoplayer controls autohide

### ISSUE THREAD

**Issue by soliloquyx** [TheWidlarzGroup/react-native-video#1903]
### Current behavior
When using Android exoplayer and setting controls to true, then initially controls are shown for few seconds and then they autohide. When they are autohidden, then they cannot be brought back by toggling controls to false and back to true.

### Reproduction steps
Have any video set to fullscreen and controls turned on.

### Expected behavior
I expect controls to stay visible.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by Bashamd455** [comment]
Hi, @soliloquyx Did you find any workaround to this issue. My requirement is to hide/visible controls when I pressed on a custom play/pause button. Thank you!

**Comment by soliloquyx** [comment]
> Hi, @soliloquyx Did you find any workaround to this issue. My requirement is to hide/visible controls when I pressed on a custom play/pause button. Thank you!

As of yet, we haven't. Currently just working on other tasks.

**Comment by Bashamd455** [comment]
@soliloquyx Thanks for the response. For time being I am going to use the media controls library.

**Comment by LiamBCN** [comment]
+1

**Comment by abakers** [comment]
Had this issue recently, updated to latest RN version (0.66.3) which seems to have fixed the problem. Not sure what caused it. Previous RN version I had was 0.64.2. Rolled back just to make sure that it had something to do with RN versions and yes, the issue reappeared when rolling back to previous version.
