### ISSUE TITLE
Android Exo Player

### ISSUE THREAD

**Issue by yvbeek** [TheWidlarzGroup/react-native-video#1904]
How can I tell if the app is actually using the Android Exo player or the old player?
And does the Exo player have a built-in fullscreen button?

**Comment by benoitdion** [comment]
hi @yvbeek, see https://github.com/react-native-community/react-native-video#android-installation for how to configure react-native-video with Exoplayer.

**Comment by yvbeek** [comment]
@benoitdion thanks, but I already read the installation guide.

- How can I be sure it is using the Exo player?
Does it look different? How can I tell?

- Even with the latest beta I don’t see a fullscreen button on Android. Fullscreen should be built-in for the latest betas right?

**Comment by ludvigeriksson** [comment]
@yvbeek Did you figure out how to get a fullscreen button?
