### ISSUE TITLE
Notification Player UI

### ISSUE THREAD

**Issue by anastely** [TheWidlarzGroup/react-native-video#1905]
Hello,

I have used this package to handles videos and sounds on my app, it works very well, but is there a way to make a Notification Player UI like Spotify or else?
![IMG_20200210_013712](https://user-images.githubusercontent.com/24620979/74112509-ef052400-4ba5-11ea-93d3-e4d67c9a00a5.jpg)

**Comment by benoitdion** [comment]
Hi @anastely, closing as this is currently not supported by react-native-video. You may want to look at https://github.com/tanguyantoine/react-native-music-control which works well with react-native-video.
