### ISSUE TITLE
Position difference between seekTime and currentTime is too large  when video seek

### ISSUE THREAD

**Issue by Kweiza** [TheWidlarzGroup/react-native-video#1908]
When I try to seek using ref.seek(time),
Position difference between seekTime and currentTime is too large on 'onSeek'

I wanted to seek 23sec, but onSeek gave me currentTime 19sec.

Is there any solution to solve this problem?

Library version: 5.0.2

## Steps To Reproduce

![untitled](https://user-images.githubusercontent.com/5517346/74500036-0129ee00-4f29-11ea-9eca-4eb70050d23b.gif)

## Expected behaviour

1. seek(23)
2. onSeek={data => console.log(data.currentTime)} // currentTime -> +-0.5sec

## Reproducible sample code

```
import React from 'react';
import {inject, observer} from 'mobx-react';

import {StoreTypes} from '~/store';
import ApplicationStore from '~/store/ApplicationStore';

import {ScreenContainer, Text, Button} from '~/monade/UI';
import Video from 'react-native-video';
import RNBackgroundDownloader from 'react-native-background-downloader';
import {Dimensions} from 'react-native';

interface Props {
  applicationStore?: ApplicationStore;
}

interface State {
  currentTime: number;
}

@inject((store: StoreTypes) => ({
  applicationStore: store.applicationStore,
}))
@observer
export default class Screen extends React.Component<Props> {
  player: Video | null = null;

  state = {
    currentTime: 0,
  };

  render() {
    const videoDest = `${RNBackgroundDownloader.directories.documents}/video/23758.mp4`;
    const videoSize = {
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').width * (9 / 16),
    };

    return (
      <ScreenContainer>
        <Video
          source={{uri: videoDest}}
          ref={ref => (this.player = ref)}
          style={{...videoSize}}
          onProgress={({currentTime}) => this.setState({currentTime})}
          onEnd={() => {
            this.setState({pause: true, currentTime: 0});
          }}
          currentTime={this.state.currentTime}
          onSeek={data => {
            console.log(data);
            this.setState({currentTime: data.seekTime});
          }}
        />
        <Text>{`current time: ${this.state.currentTime}`}</Text>
        <Button title={'to 10sec'} onPress={() => this.player?.seek(10)} />
        <Button title={'to 20sec'} onPress={() => this.player?.seek(20)} />
        <Button title={'to 23sec'} onPress={() => this.player?.seek(23)} />
      </ScreenContainer>
    );
  }
}

```

**Comment by B1Z1** [comment]
I have the same problem and dont know what I can do with this

**Comment by jkerb8** [comment]
This is a serious issue for me as well. Has anyone figured out a work-around or what's causing this?

**Comment by chiefchief** [comment]
same

**Comment by jkerb8** [comment]
If it helps, I only experience this with some videos. I believe it has to do with the keyframe interval of the video. If you have the ability to encode the video, you can set this keyframe interval parameter (along with many others that might help) using ffmpeg.

**Comment by chiefchief** [comment]
my issue was with mp3 file, when i converted it into mp4, it was solved

**Comment by vhminh199** [comment]
the issue is still here, someone help ?

**Comment by mgpepe** [comment]
Same problem here. Does not depend on video. Seems like depends on how soon you call seek after loading. However, waiting for `onLoad` or `onReadyForDisplay` does not do it. Actually, the best way to achieve this issue is to put seek in `onLoad`.

Through a button I discovered that pressing second time fixes it to the right seek time. So my temporary solution was to simulate that:
```
let seekTimes = 0;
const handleSeek = (e) => {
  if (e.currentTime != e.seekTime && seekTimes < 5) { // I noticed 2nd time does it, you can pick any number
    seekTimes++;
    videoRef.current.player.ref.seek(e.seekTime);
  }
};
```

I mean, it is a crappy solution but it is also a crappy bug that happens randomly on any video.

**Comment by ArthurEgide** [comment]
Same problem...

**Comment by orzhtml** [comment]
Same problem...

**Comment by newkilho** [comment]
`ffmpeg -i input.mp4 -force_key_frames "expr:gte(t,n_forced*1)"  output.mp4`

Solved by forcing adding keyframes to the video.

**Comment by joaohd98** [comment]
Same issue...

**Comment by kotoyama** [comment]
Same. Any updates?

**Comment by w4t3r-45** [comment]
same issue guys , if i change the seek manually currentTime is not same as The duration :
example : if video has 182 sec , when i seek manually "let's say to middle" then i wait for video to ends , it is showing currentTime: 179.601 (sometime + -) , any solution please

**Comment by freeboub** [comment]
@w4t3r-45 which version do you use ? There was some patch adding seek precision if i remember well. Did you try with V6 release ?

**Comment by w4t3r-45** [comment]
@freeboub no i am using ^5.2.0 in the project should we migrate to the latest release ? 
is there a workaround we should do without migrating ? also can you kindly send me the PR link that solved the issue if you still remember it.

**Comment by freeboub** [comment]
@w4t3r-45 I think you can have a look to this one 
https://github.com/react-native-video/react-native-video/pull/2555/files
