### ISSUE TITLE
iOS textTrack for VTT not displaying upon app's return to foreground

### ISSUE THREAD

**Issue by lingtran** [TheWidlarzGroup/react-native-video#1909]
# Bug

The captions file we have in the textTrack loads  and displays when the media opens initially. However, after we navigate away from the app and return the app to focus (i.e. return it to the foreground), the captions do not return to display. 

_Additional details:_
These signs seem to suggest that the bug lives at the library level for iOS. We do not have any captions issues for Android.
- I noticed if I set `playInBackground={false}`, we don't reproduce this captions issue. It is only when it is set to 'true' in iOS does the bug emerge.
- Attempts to toggle the captions on again yields no response.
- We inspected our app state and validated that all required data is present and correct.

That being said, non-negotiable acceptance criteria are (1) captions have to work in iOS to observe accessibility for our users, and (2) we have to have playInBackground set to true. So...we appreciate hearing from the community and maintainers any insights to resolve this issue!

## Platform

iOS

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 64.41 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 5.0.2

## Steps To Reproduce

1. Open video player in app
2. Turn on captions
3. Navigate away from app to Home screen or another app of choice, while video player is playing in the background
4. Return to app with video player

## Expected behaviour

1. See video in a new current time position, including captions still on display matching the video where it's at.

## Reproducible sample code

```
import React from 'react';
import ReactNativeVideo from 'react-native-video';
import PropTypes from 'prop-types';

export default class VideoPlayer extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            // details
        };
        this.effect = this.effect.bind(this)
    }

    componentDidMount() {
        this.effect();
    }

    componentDidUpdate(prevProps) {
       // stuff
    }

    componentWillUnmount() {
        // stuff
    }

    onSeek = (data) => {
        // stuff
    }

    onProgress = (args) => {
        // stuff
    }

    effect() {
        // stuff
    }

    render() {
        const selectedTextTrack = this.props.captionsOn ? {type: 'title', value: 'English'} : {type: 'title', value: 'empty'}

        return (
          <ReactNativeVideo
             audioOnly={avType === 'audio'}
             ref={(ref) => {
                this.player = ref}}
             poster={imageUri)}
             source={{uri:sourceUrl}}
             style={styles.video_player}
             textTracks={[{
                title: 'English',
                language: 'en',
                type: 'text/vtt',
                uri: path
             }]}
            selectedTextTrack={selectedTextTrack}
            rate={1}
            volume={1}
            muted={false}
            resizeMode="contain"
            onProgress={this.onProgress}
            onSeek={this.onSeek}
            onLoad={this.props.onLoad}
            onEnd={this.props.onEnd(true)}
            playInBackground={true}
            playWhenInactive={true}
         />
        )
    }
}

// propTypes validation
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
Can provide if needed

**Comment by benoitdion** [comment]
Hi @lingtran, thank you for the detailed bug report! I don't currently have the bandwidth to work on a fix but I'm happy to review and merge a PR resolving the issue!

**Comment by lingtran** [comment]
Thanks for the quick response @benoitdion! We will see what we can do and work on submitting a PR. Any pointers and/or tips that may come to mind so far upon reading this issue will be appreciated!
