### ISSUE TITLE
it can't work at less than Android 5

### ISSUE THREAD

**Issue by hinet** [TheWidlarzGroup/react-native-video#191]
Android 5.1 can be played, but the following can not work under the Android 5.1

**Comment by gravitinos** [comment]
I've got it working on android 4.2.2 and 4.2.3.
which have you tried?

**Comment by mattapperson** [comment]
@hinet still an issue?

**Comment by CrazyStoneJy** [comment]
i have same issue

**Comment by mohsen0071** [comment]
@mattapperson i have this issue right now, actually we have a wowza streaming engine for playing videos and player can't play stream format in android under 5 version, but it can plays .mp4 format, do you have a solution for it? thanks in advance

**Comment by mattapperson** [comment]
Can you post a reprodusable use-case?

**Comment by mohsen0071** [comment]
@mattapperson thanks for reply, unfortunately i cant send use-case here, cause i'm working on private project in company.

**Comment by cobarx** [comment]
Closing this since there's not enough info to reproduce and this is old.
