### ISSUE TITLE
iOS recorded video is not playing in android device?

### ISSUE THREAD

**Issue by yogeshj-aloha** [TheWidlarzGroup/react-native-video#1911]
I am not able play iOS device recorded video in android phone using react-native

Its play in iOS but not play in android
Extension is : .mov for iOS and .mp4 for android

**Comment by benoitdion** [comment]
Hi @yogeshj-aloha, this issue is outside of the scope of what react-native-video provides. Exoplayer does not support .mov (see https://exoplayer.dev/supported-formats.html). You may need to encode the video differently on ios.

**Comment by traxx10** [comment]
How do we encode?
