### ISSUE TITLE
Force media preloading / gapless playback

### ISSUE THREAD

**Issue by Informatic** [TheWidlarzGroup/react-native-video#1917]
# Feature Request

Force media buffering / preloading and gapless playback

## Why it is needed

I'm attempting to create a gapless video playback loop by showing two videos on top of each other and switching them when apropriate. (while ensuring the component is not fully recreated by using `key` properly)
Currently, the best I could get (at least on Android) was ~0.25s of black screen between two consecutive videos, even when flipping `paused` prop state around based on `onReadyForDisplay` event. (however I still might be doing something wrong)

Unrelated to method above, this can still be reproduced by just creating `<Video paused={true} />` component, that results in just a transparent view. (while It'd be nice to have it preload first video frame, like HTML5 Video does for example)

## Possible implementation

It'd be nice to somehow tell video player to preload first frame, even though `paused` prop is kept on, and then somehow reduce time needed to render successive frames after flipping `paused` prop off.

**Side question:**
~Couldn't find it anywhere in docs... How do I switch between Exoplayer and "plain" Video player on Android?~ Found it. Still not sure whether by default I use native MediaPlayer or ExoPlayer, need to test things out...

**Update:**
After preliminary testing, it seems like behaviour on ExoPlayer is completely different, and seems to somwhat fit my expectations (ie. it seems to preload first frame on component creation)

**Comment by MahefaAbel** [comment]
Need it too

**Comment by liquidvisual** [comment]
I'll have what he's having
