### ISSUE TITLE
method onBuffer is not exist?

### ISSUE THREAD

**Issue by ARDcode** [TheWidlarzGroup/react-native-video#1920]
In usage example: 
```
<Video source={{uri: "background"}}   // Can be a URL or a local file.
       ref={(ref) => {
         this.player = ref
       }}                                      // Store reference
       onBuffer={this.onBuffer}                // Callback when remote video is buffering
       onError={this.videoError}               // Callback when video cannot be loaded
       style={styles.backgroundVideo} />
``` 
But in **Event props** onBuffer prop is not exist. And in code is same too. 
Please delete this from docs or fix onBuffer method work.

P.S. [issue#1872](https://github.com/react-native-community/react-native-video/issues/1872)

**Comment by mattglover11** [comment]
+1

**Comment by sayem314** [comment]
+2

**Comment by openwell** [comment]
+3 even onError does throw any error

**Comment by IamMasterWayne** [comment]
+1

**Comment by sayem314** [comment]
I found out that by default this uses MediaPlayer which doesn't have onBuffer support but after switching to ExoPlayer it's working!

**Comment by sayem314** [comment]
If you are curois how to enable exoplayer then follow these steps:

- create `react-native.config.js` with following content:

```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```

- now enable multidex following this [tutorial](https://developer.android.com/studio/build/multidex)

- clean using `gradlew clean` and rebuild to make it work

**Comment by openwell** [comment]
> If you are curois how to enable exoplayer then follow these steps:
> 
> * create `react-native.config.js` with following content:
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> };
> ```
> 
> * now enable multidex following this [tutorial](https://developer.android.com/studio/build/multidex)
> * clean using `gradlew clean` and rebuild to make it work

Works for me. thank you

**Comment by teamtechalpha** [comment]
Try using

`onPlaybackStalled={this.handleBuffer.bind(this, { isBuffering: true })}
and onPlaybackResume={this.handleBuffer.bind(this, { isBuffering: false })}
`

We explored the code and found these to be working on version _^4.4.4_

**Comment by binduN** [comment]
Hey @sayem314 and @openwell , can you tell me under which path do we create react-native.config.js ?

**Comment by openwell** [comment]
@binduN main directory where you have package.json

**Comment by binduN** [comment]
@openwell thank you. got it to work.

**Comment by max-kim** [comment]
Instead of creating `react-native.config.js` you can use [solution from lib](https://github.com/react-native-community/react-native-video#android-installation) readme:

**android/settings.gradle**

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by prisar** [comment]
I am able to find do my work using `onLoad` and `onLoadStart`.

- onLoad : setting buffering to true
- onLoadStart: setting buffering to false

**Comment by ebeliejinfren** [comment]
same issue

**Comment by lordival** [comment]
+1

**Comment by DISKONEKTeD** [comment]
It works fine in exoplayer. So this should not be done. Just switch to exo, it's what i did and everything works better

**Comment by appdev-cts** [comment]
Same issues onBuffer is not working on android. Is anyone solved this issues ?

**Comment by prisar** [comment]
@appdev-cts try exoplayer

**Comment by prisar** [comment]
```
              onReadyForDisplay={() => {
                console.log('onReadyForDisplay');
                this.setState({
                  loading: false,
                });
                addVideoView(item);
              }}
              onBuffer={() => {
                console.log('onBuffer');
                this.setState({
                  loading: true,
                });
              }}
              onLoad={() => {
                this.setState({
                  paused: false,
                });
              }}
              onProgress={() => {
                // console.log('onProgress ==' + index);
              }}
              onError={(err) => {
                console.log(err);
                alert('Error occured');
              }}
```

**Comment by UzairSoken** [comment]
Hy I am facing the same issue of slow loading video and i have implemented the expo player solution but its not working on some android devices ,On Samsung devices its not even opening the application it just crashes after i open the application with no errors.

Any recommendations or any other solution to overcome slow video load

**Comment by haseebthedev** [comment]
@teamtechalpha

This worked for me. THANK YOU SO MUCH!!!

**Comment by freeboub** [comment]
Issue not clear ...
Let's close it.

**Comment by mayankgahlot** [comment]
// use onLoad , onLoadStart and onProgress to show buffering image

// Please use your own style, this is only an example of buffering functionality not complete screen code

    const [duration, setDuration] = useState(0.001)
    const [currentTime, setCurrentTime] = useState(0.001)
    const [seekValue, setSeekValue] = useState(0)
    const [buffering, setBuffering] = useState(false)
    
    
 const onProgress = (progress) => {
        if(currentTime == progress?.currentTime)
        {
          setBuffering(true)
        }
        else{
          setBuffering(false)
        }
        setCurrentTime(progress?.currentTime)
        setSeekValue(progress?.playableDuration)
    }

const onLoad = ({ duration }) => {
        setDuration(duration)
        setBuffering(false)
    }
    return (
       <Video
                    source={{ uri: videoItem ? videoItem?.media_url : video?.media_url }}
                    ref={ref => videoRef = ref}
                    onLoad={onLoad}
                    onLoadStart={()=>setBuffering(true)}
                    onProgress={onProgress}
         />
 {buffering && <Image source={your buffering gif}/>
)

**Comment by Yumesh-Kumar** [comment]
> Try using
> 
> `onPlaybackStalled={this.handleBuffer.bind(this, { isBuffering: true })} and onPlaybackResume={this.handleBuffer.bind(this, { isBuffering: false })} `
> 
> We explored the code and found these to be working on version _^4.4.4_

this is really working in my case with ^5.0

**Comment by komal1502** [comment]
> If you are curois how to enable exoplayer then follow these steps:
> 
> * create `react-native.config.js` with following content:
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> };
> ```
> 
> * now enable multidex following this [tutorial](https://developer.android.com/studio/build/multidex)
> * clean using `gradlew clean` and rebuild to make it work

![image](https://github.com/react-native-video/react-native-video/assets/32698245/ca201782-e94c-4fbe-8492-8f7529093082)
It throws me this error when i try to do what you mentioned.

**Comment by freeboub** [comment]
@komal1502 not linked to the ticket. but as far as I remember, I fixed it by adding:
android.enableDexingArtifactTransform=false

in graddle.properties file

**Comment by ghost** [comment]
> progress functions Finally workings. 
small changes to
  setSeekValue(progress?.currentTime);
