### ISSUE TITLE
Refreshing the video source while it plays

### ISSUE THREAD

**Issue by jearaneda** [TheWidlarzGroup/react-native-video#1922]
I need to refresh the URL for the current video while it plays, in order to avoid the URL expiration datetime set in the API.

Currently, the server sends a video URL with an expiration time of 3 minutes from the request. In cases where the video lasts for, say, 20 minutes, the user cannot access it for further playback. Thus, I'd like to change the VideoPlayer's source when the onSeek event is triggered.

I tried using onSeek() and the props do change, but the video doesn't seem to trigger a 'reload' action. How can i trigger this action, such that the video source -with a newer expiration time- is used instead of the old one?

**Comment by waheedakhtar694** [comment]
@jearaneda Have you found a solution for this I am having a similar problem but I am loading video from a source Like I have a list of videos one will be played and below will be the suggestions I am can select one from the list When I select from list source gets updated but the video didn't play on ios on android is works fine.
