### ISSUE TITLE
Is there a way to play an encrypted local m3u8 video?

### ISSUE THREAD

**Issue by finntenzor** [TheWidlarzGroup/react-native-video#1923]
# Bug

Can't play an encrypted m3u8 video from local file system.

## Platform

Android. But I don't know which player I am using. I have no idea how to found my config.

## Environment info

React native info output:

```bash
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.18 GB / 15.71 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Programs\npm_nm\node_global\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.3
      System Images: android-19 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

Library version: 5.0.2

## Steps To Reproduce

```js
import VideoPlayer from 'react-native-video'

const uri = 'file:///storage/emulated/0/test/demo.m3u8'

const player = () => (
  <VideoPlayer
    source={{ uri }}
    ....
  />
)
```

I have an m3u8 file and many ts file in the "test" folder. The ts files are encrypted and the key was Base64 encoded in the m3u8 file.

The test folder looks like:

```bash
-rw-rw---- 1 root sdcard_rw   1112 2020-02-21 14:54 demo.m3u8
-rw-rw---- 1 root sdcard_rw 281824 2020-02-21 14:49 v.f22311_2.ts
-rw-rw---- 1 root sdcard_rw 139696 2020-02-21 14:49 v.f22311_3.ts
-rw-rw---- 1 root sdcard_rw 326944 2020-02-21 14:49 v.f22311_4.ts
-rw-rw---- 1 root sdcard_rw 147776 2020-02-21 14:49 v.f22311_5.ts
-rw-rw---- 1 root sdcard_rw 219600 2020-02-21 14:49 v.f22311_6.ts
-rw-rw---- 1 root sdcard_rw  69200 2020-02-21 14:49 v.f22311_7.ts
```

The content of demo.m3u8:

```txt
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:5
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:2.500,
v.f22311_2.ts
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:1.875,
v.f22311_3.ts
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:2.625,
v.f22311_4.ts
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:1.083,
v.f22311_5.ts
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:4.125,
v.f22311_6.ts
#EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;base64,lIGnJTHspNpGEFnrdmpsww==",IV=0x00000000000000000000000000000000
#EXTINF:2.875,
v.f22311_7.ts
#EXT-X-ENDLIST
```

When I try to play the file, got:
```json
{
  "error": {
    "extra": -2147483648,
    "what": 1
  }
}
```

## Expected behaviour

1. Play successfully.

## Video sample

https://bestdet.ddltech.top/storage/video/demo7.m3u8
https://bestdet.ddltech.top/storage/video/v.f22311_2.ts
https://bestdet.ddltech.top/storage/video/v.f22311_3.ts
https://bestdet.ddltech.top/storage/video/v.f22311_4.ts
https://bestdet.ddltech.top/storage/video/v.f22311_5.ts
https://bestdet.ddltech.top/storage/video/v.f22311_6.ts
https://bestdet.ddltech.top/storage/video/v.f22311_7.ts

## Other

When I set the source to "https://bestdet.ddltech.top/storage/video/demo7.m3u8", everything runs ok. But crashed if I set the source to "file:///storage/emulated/0/test/demo.m3u8".

I have to download and storage the video file in to the local file system and keep them encrypted due to some reason. Is there any solution?

I have try to look up the source of this library. However I don't know how it works, why there are two play (MediaPlayer and ExoPlayer), which player I am using and how to debug it. Please help me!!!

**Comment by benoitdion** [comment]
are you seeing anything relevant in the adb logs?

**Comment by finntenzor** [comment]
> are you seeing anything relevant in the adb logs?

![image](https://user-images.githubusercontent.com/7535112/75141533-16bec500-572c-11ea-9611-1912a3a59330.png)
![image](https://user-images.githubusercontent.com/7535112/75141539-1cb4a600-572c-11ea-8a7e-81101e047765.png)

I have moved the file. I'm sure the path is correct.
But I'm not sure is there any other useful message in adb logs.

**Comment by mexhit** [comment]
I have the same error while trying to play video in android, from flipper I got those errors: 
![image](https://user-images.githubusercontent.com/17933786/121020795-0277cd80-c7a1-11eb-8fdc-abcf6c9b1483.png)

**Comment by mexhit** [comment]
@finntenzor I fixed problem using ExoPlayer https://stackoverflow.com/questions/59542183/use-exoplayer-in-react-native.
Hope it works for you

**Comment by DeepakmBinmile** [comment]
@finntenzor any solution you got?

**Comment by finntenzor** [comment]
> @finntenzor any solution you got?

Use ExoPlayer. This will be more complicated but it works.
