### ISSUE TITLE
Black screen on Android X

### ISSUE THREAD

**Issue by ScreamZ** [TheWidlarzGroup/react-native-video#1924]
# Bug

I installed react native video on my phone 
![Screenshot_20200221-173855](https://user-images.githubusercontent.com/6640835/75053225-2f7f6e80-54d1-11ea-8965-321f0af47830.jpg)

on ios everything is fine but on Android I get the sound without the video, I tried resizing, switch from exo player to the other one, but still. Changed the video also…

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 152.28 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /var/folders/g4/m_tk137d0wxfcz66c8vkh71m0000gp/T/yarn--1582302904636-0.9072258199201693/node
    Yarn: 1.21.1 - /var/folders/g4/m_tk137d0wxfcz66c8vkh71m0000gp/T/yarn--1582302904636-0.9072258199201693/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.3, 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    generator-react-native-expo: 0.0.0
    react-native-true-sight: 1.0.1
```

Library version: 4.x.x to 5.x.x included

## Steps To Reproduce

Take the most simple example from the doc with local video or https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

## Expected behavior

Video displaying without black screen on video box

## Video sample
https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

Thanks for taking a look at

**Comment by ScreamZ** [comment]
Some troll in my project team added `android:hardwareAccelerated="false"` in AndroidManifest.xml… That's why I got the bug.

**Comment by benoitdion** [comment]
@ScreamZ is your issue resolved?

**Comment by mayconmesquita** [comment]
@ScreamZ please close the issue if resolved.

**Comment by ScreamZ** [comment]
I'll let me just get back to my computer 😅 there is no way to close on the mobile app 😋

Thanks guys

**Comment by swaroopaillinda** [comment]
@ScreamZ  I need to keep the android:hardwearacceleration = "false" in my manifest as it is crashing my with fatel error

but My Video is not visible but audio i shearing not normal mp4 video but it has authentication header

can you tell me how to overcome this issues I need both of them to be working

**Comment by ayush8385** [comment]
@swaroopaillinda you got any solution for this error ?
