### ISSUE TITLE
Android Orientation Issue

### ISSUE THREAD

**Issue by alexpoon2000** [TheWidlarzGroup/react-native-video#1929]
When I rotate the screen the on Android, the video size does not adjust. However, I can see the video control is in full width
<img width="410" alt="Screenshot 2020-02-25 at 10 06 09 AM" src="https://user-images.githubusercontent.com/7920692/75208636-4070fe00-57b7-11ea-8756-a26d2f618c47.png">

**Comment by iacocesar** [comment]
Hi,

You need force the screen resize with a timeout func to get a new screen dimensions.

**Comment by 349989153** [comment]
@IacoCesar Does "resize" mean setting style with device width and device height ?

No it doesn't help, player on Android is not really full screen ,it still in it's container View

```
<Video
            source={{ uri: 'https://www.iyougx.com/video/demo.mp4' }}
            style={
              !this.state.isFullScreen
                ? styles.video
                : { width: DEVICE_WIDTH, height: DEVICE_HEIGHT }
            }
            paused={true}
            fullscreen={Platform.select({
              ios: true,
              android: false,
            })}
            onFullscreenPlayerDidPresent={this.onFullscreenPlayerDidPresent}
            onFullscreenPlayerDidDismiss={this.onFullscreenPlayerDidDismiss}
            controls={true}
            fullscreenAutorotate={true}
            fullscreenOrientation="landscape"
            resizeMode="cover"
          />
```

set `isFullScreen` to true when `onFullscreenPlayerDidPresent` is called and to false when `onFullscreenPlayerDidDismiss` is called
