### ISSUE TITLE
need onPaused event on iOS platform.

### ISSUE THREAD

**Issue by xing-zheng** [TheWidlarzGroup/react-native-video#193]
In fullscreen mode, It's unable to pause video by pressing the built-in pause button.

Please fire onPause event, so that we have an opportunity to invoke "this.setState({paused: true});

**Comment by shanealsingh** [comment]
@xing-zheng For the time being I just put an invisible button over the native one and control playback that way.

**Comment by xing-zheng** [comment]
@shanealsingh Thank you!

**Comment by corbt** [comment]
The `onPlaybackRateChange` callback should give you what you need -- it'll return 1 if playback is ongoing and 0 otherwise. I'm using it for this and it seems to work.

**Comment by mattapperson** [comment]
closing due to suggestions made

**Comment by flexdhana** [comment]
Thanks @corbt it helps me.. for others, here is the example based on @corbt suggestion.

```
  _onPlaybackRateChange = (event) => {
         console.log("_onPlaybackRateChange : "+event.playbackRate)
  };

 <Video
        source={{uri: "video.mp4"}}
       onPlaybackRateChange={this._onPlaybackRateChange.bind(this)}
  />
```
