### ISSUE TITLE
AVFoundationErrorDomain -11829

### ISSUE THREAD

**Issue by premillos** [TheWidlarzGroup/react-native-video#1934]
# Bug

![image](https://user-images.githubusercontent.com/16378134/75687275-83abff00-5cd8-11ea-8e75-ad31d10e70b2.png)

![image](https://user-images.githubusercontent.com/16378134/75687231-6d9e3e80-5cd8-11ea-8af0-90fb0bd2ca48.png)

## Platform

Which player are you experiencing the problem on:
* iOS
## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 51.12 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 25.0.3, 27.0.3, 28.0.3, 29.0.1
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-qiyu: 3.12.0
    react-native: 0.61.3
```

Library version: 4.4.4
i can play this video in chrome
i have no idea what's happen

**Comment by pssgo** [comment]
i can play this video in chrome

**Comment by premillos** [comment]
After transcoding the video to h.264 format, I solved this problem. The original format was h.264 / AAC

**Comment by Gabogg07** [comment]
@pssgo How did you manage to transcode the video? I am currently having a similar issue but with an audio file and can't seem to find a way around it
Thanks in advance

**Comment by premillos** [comment]
@Gabogg07  The existing solution is to use ffmpeg to convert on the server side
