### ISSUE TITLE
Hardware Decoding or Software Decoding

### ISSUE THREAD

**Issue by MwareSolutons** [TheWidlarzGroup/react-native-video#1935]
hi all,

I have a question the Exo Player is this using Android's hardware acceleration or software?
Is there a way to adjust this to software or hardware ?

Thanks in advance....

**Comment by A-ANing** [comment]
+1

**Comment by freeboub** [comment]
Players shall use hardware decoding if available.
You can also try to use surfaceView instead of textureView which are more efficient.

**Comment by freeboub** [comment]
Please open another ticket if a change is needed
