### ISSUE TITLE
Progressive Load on Local Cached Video

### ISSUE THREAD

**Issue by enigmablue** [TheWidlarzGroup/react-native-video#1936]
I use react-native-fs to preload videos and put them on user's mobile. 
I'm expecting that when the video is loaded on the local device, it can be progressively loaded.

However when i try to put the URI source to the path all i get is

```
2020-03-04 07:51:37.401 'video props source ', { uri: '/Users/soqqlepteltd/Library/Developer/CoreSimulator/Devices/60177C63-6FC9-47EE-89F7-73AA3D940FD2/data/Containers/Data/Application/04E48EAF-7C63-40F7-A797-6E45B5A32077/Documents/1583278564271.mp4' }
2020-03-04 07:51:37.414 starting onloadstart
2020-03-04 07:51:37.426 'onerror ', { error: { code: -1100, domain: 'NSURLErrorDomain' },
  target: 299 }
```

-1100 code i believe is file not found.  I set the URI when react-native-fs 's progress method is called. But now i just double checked, that the file is not saved until the whole download is completed.

Any ideas if anyone has done this before?

## Platform
Need on both ios / android

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 21.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.4 => 3.0.4 
    react: ^16.12.0 => 16.12.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

"react-native-video": "^5.0.2",

## Steps To Reproduce

1. Download a file with react-native-fs
2. Hook up the local file to react-native-video

**Comment by nnajiabraham** [comment]
Hi @enigmablue
Did you figure this out, was trying to do something similar in order to get it working like a local proxy server for videos to load and play faster?

**Comment by orzhtml** [comment]
Has the problem been solved? Why is it closed?

**Comment by enigmablue** [comment]
I ended up making my videos m3u8 (hls) 

And even if the files were mp4, the files were already progressively loading from my was s3 bucket (as long as i set the mime correctly in the bucket)

**Comment by ahmadsyed** [comment]
Hi @enigmablue , After you converted m3u8, what you did do next? How you downloaded the video and played it as a local file?

**Comment by enigmablue** [comment]
The m3u8 is just saved in my aws s3 bucket. And i just load the link into my video player and it iwll play progressively. in the end i didn't need to 'download' the file first.
