### ISSUE TITLE
Multiple Video elements causing memory spike and crash (iOS)

### ISSUE THREAD

**Issue by scgough** [TheWidlarzGroup/react-native-video#1938]
I have a feed which displays multiple videos in a `<FlatList/>`. Each video is hosted offsite on a URI. Each video in the feed is muted and paused. I was playing only the video's in the viewport _but_ this crash occurs even with all of them paused. 

Each 'page' of the FlatList has 12 videos. I can scroll through no more than 2 pages before the crash.

On iOS I started seeing the app crash with the error `Message from debugger: Terminated due to memory issue` in Xcode. 

- When running on a device I see memory spike slightly (it goes from ~120MB to ~150MB, holds for a few seconds then the app crashes). 
- On a simulator, I can see the memory climb rapidly as soon as the feed is loaded. The memory is not released even after closing the screen and each subsequent return to the screen increases it further. 

As mentioned, I tried keeping the videos all paused but the same thing happens. 
When I switch out all the <Video/> for a <FastImage/> (using the `props.thumbnail` URI) component the crash stops and the memory doesn't spike.

Example of how I'm initialising each `<Video />` in the `<FlatList />`

```
<Video
  source={{ uri: props.uri }} 
  repeat={true}
  muted={true}
  volume={0.0}
  paused={props.paused}
  posterResizeMode="cover"
  resizeMode="cover"
  poster={props.thumbnail}
  style={props.style}
  ref={ref => {
    this.player = ref;
  }}
/>
```

## Platform
- iOS 
- ExoPlayer
- RN 0.59.10
- React 16.8.6
- react-native-video 5.1.0-alpha1 (this is so I can fix the pause video bug in earlier versions)

Side note - Android also experiences crashes but seems to hold out for much longer than iOS

**Comment by chuckwu0** [comment]
+1 
I met the same problem

**Comment by teamtechalpha** [comment]
We have a same setup and faced similar issues, we ended up using viewport aware component to not load videos until the view was visible on the screen.

Here is a nice article that describes it all
https://blog.netcetera.com/viewport-aware-components-for-react-native-apps-a28ea605e89e

**Comment by scgough** [comment]
Yes, in terms of keeping this in check the method used in my instance was to employ the `FlatList` `viewabilityConfig` and `onViewableItemsChanged` methods. Video's 'off screen' are changed to thumbnail images to keep memory in check. 

However, this is FlatList is essentially doing the work here. 
In some instances >1 videos are required on screen so it looks like you should basically manage the instances well or memory will spike and crash the app eventually. 
This could still be an issue within the `react-native-video` component but I can also see the argument that if you're adding multiple video component instances (such as in a feed maybe) you can expect memory to go "a little kaka".

**Comment by pribeh** [comment]
@scgough is there anything you do to keep the the scroll smooth while loading/unloading video players? We're finding that the re-render is causing the UI/JS threads to drop frames massively when using viewabilityConfig to load or unload the videos. @teamtechalpha how is the viewport aware component working for you guys? Do you experience any rendering issues / framerate drops using it?

**Comment by scgough** [comment]
@pribeh - did have a couple of issues with scrolling (mainly on Android) but used an `Animatable.View` from `react-native-animatable` to fade in the `<Video />` as it came into view. Also, (depending on your app requirements) make sure the video isn't too high quality/file size so it's not a huge hit on that side of things.

**Comment by pribeh** [comment]
@scgough thanks. I believe the issue is possibly caused by using state to change the paused props while scrolling at the same time as the video. I believe this may be causing the component to rerender twice thus causing the large frame-rate drop. I'm not sure we can pause/play the video through the this.player = ref but I'm going to try.

**Comment by scgough** [comment]
@pribeh - just as an extra bit of info to this which might help you. 
Use `<Image />` with the cover/placeholder image for the video (instead of many `<Video />` instances paused) then use the animated.view to wrap the `<Video />` component (playing) when it is on screen. This way you'll only ever have 2 or 3 videos loading in at once. All other instances will be an Image until they are ready to play.

**Comment by pribeh** [comment]
Adding even the smallest timeout (400ms) to the playing of the video after it loads seemed to establish much better performance (less frame-rate drop). I would be interested in finding a way to play/pause the video without using state to change the props.
 
```	
//triggers the video to load and then play
startVideo = () => {
		this.setState({ loadVideo: true })
		setTimeout(() => {
			this.setState({ pausedVideo: false });
		}, 400);
	}
```

Having a minimumviewtime in the viewabilityconfig of the flatlist helps a bit as well

```
		//config for registering flatlist item viewability
		this.viewabilityConfig = {
			waitForInteraction: false,
			minimumViewTime: 250,
			viewAreaCoveragePercentThreshold: 50
		}
```

Using progressUpdateInterval helps too.

**Comment by pribeh** [comment]
@scgough I'm already using an image placeholder with a conditional <image>/<video> render but I'll apply animation next to the video to gracefully load it in. Thanks for the tips

**Comment by ahmedelsayed11233** [comment]
@scgough can you provide an example of rendering audio files with flautist as I am stuck with this as when scrolling all videos re-rendering crazy

**Comment by 60pfennig** [comment]
For all people who are reading and getting the same errors. For me the real helpfull thing to get rid of the crashes was to conditionaly render the video component.
To do this I used `onViewableItemsChanged` to see which are in the viewport. I store the indicies in a state. In the render function if the index of the video to render is visible I will render the component otherwise it renders just a placeholder image. It's important to not just pause the videos but also unmount them by conditionaly render them with `isVisible ? <Video ... /> : <Placeholder />`
