### ISSUE TITLE
ExoPlayer ignores MIME types when loading MPEG-DASH

### ISSUE THREAD

**Issue by gtebbutt** [TheWidlarzGroup/react-native-video#1939]
# Bug

When loading a valid MPD from an API endpoint with a URL of the form `/api/video/4667/manifest`, the player gives the following error:
```
None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
```

It took me more time than I'd care to admit to figure out that the `application/dash+xml` MIME type was being ignored and only the file extension in the URL was being checked! 

Given that API endpoints often don't have a concept of type extensions, it seems as though MIME type checking would be an improvement. 

The relevant switch statement is below: 

https://github.com/react-native-community/react-native-video/blob/1ecb09acc4e2baa7cdb9f9b5c9f3a07b802503f8/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L469-L500

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 377.81 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

## Steps To Reproduce

1. Load an MPD from any URL that doesn't end in `.mpd`

## Expected behaviour

1. The video will play successfully, assuming the MIME type is `application/dash+xml`

**Comment by waheedakhtar694** [comment]
Same issue here `.mpd` extension not working.
