### ISSUE TITLE
AVFoundationErrorDomain -11800

### ISSUE THREAD

**Issue by luiscerqueira** [TheWidlarzGroup/react-native-video#1940]
# Bug

 I am not able play remote videos on an IOS simulator (it was not possible to test it on a real device).

When I try to play an .m3u8 file or even an mp4 file, the console prints the following error:

```bash
2020-03-05 11:09:56.213199-0800 rntest[25157:381125] Task <F24E38AA-49E7-4546-B3F9-EE84F50EA7C0>.<3> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://cdn.theoplayer.com/video/elephants-dream/1280/media_w370587926_b2962000_vo_slen_t64TWFpbg==_0.ts, NSErrorFailingURLKey=https://cdn.theoplayer.com/video/elephants-dream/1280/media_w370587926_b2962000_vo_slen_t64TWFpbg==_0.ts, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <F24E38AA-49E7-4546-B3F9-EE84F50EA7C0>.<3>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F24E38AA-49E7-4546-B3F9-EE84F50EA7C0>.<3>, NSLocalizedDescription=cancelled} [-999]
2020-03-05 11:09:56.214277-0800 rntest[25157:381125] Task <1ABBAD14-21BE-4245-92E3-6B7657D0F050>.<3> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://cdn.theoplayer.com/video/elephants-dream/en/media_w370587926_b160000_ao_slen_t64RW5nbGlzaA==_1.aac, NSErrorFailingURLKey=https://cdn.theoplayer.com/video/elephants-dream/en/media_w370587926_b160000_ao_slen_t64RW5nbGlzaA==_1.aac, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1ABBAD14-21BE-4245-92E3-6B7657D0F050>.<3>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1ABBAD14-21BE-4245-92E3-6B7657D0F050>.<3>, NSLocalizedDescription=cancelled} [-999]
2020-03-05 11:09:56.217 [info][tid:com.facebook.react.JavaScript] 'On error', { error: { code: -11800, domain: 'AVFoundationErrorDomain' },
  target: 3 }
2020-03-05 11:09:56.228471-0800 rntest[25157:381087] Task <F24E38AA-49E7-4546-B3F9-EE84F50EA7C0>.<3> finished
```

The onError event of the react-native-video video throws an error code -11800 with the domain of AVFoundationErrorDomain.
The IOS emulator logs show that the error is an NSURLErrorDomain with the code -999, which means canceled.

After some research, I read that we need to go to the Info.plist file and check / update the ATS and set allow arbitrary loads to be true. This didn't work, and when looking for more information I saw some people talking about subdomain problems (which I didn't quite understand) or that the 999 error is common when a request is called twice or the reference to the object manager is being deallocated prematurely.

I tried many things, but I can't seem to get it to work.

Can anyone help me with this?
Do I need to do any extra configuration for this to work?

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 119.88 MB / 7.95 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.
```

Library version: 5.0.2

## Steps To Reproduce

1. yarn add @react-native-video
2. cd ios && pod install && cd ..
3. react-native run-ios
...

## Expected behaviour

The video should play

## Reproducible sample code

```javascript
<Video
    ref={videoRef}
    source={{
      uri: "https://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8", 
      type: "application/x-mpegurl"
   }}
  controls={false}
   resizeMode={'contain'}
   onLoad={onLoadEnd}
   onProgress={onProgress}
   onEnd={onEnd}
   paused={!state.play}
   {...rest}
/>
```

## Video sample
- http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
- https://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8
- https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multiple-subtitles.ism/.m3u8

**Comment by luiscerqueira** [comment]
I haven't been able to solve the problem yet.

@cobarx I saw that you have a react-native-video-test repository,  testing local, mp4, dash and hls videos, as well as testing text tracks. This is similar to what I am doing. I would like to know if you did not have this same problem that I am having, and if so, how did you solve it?

**Comment by Gabogg07** [comment]
Any updates on this?

**Comment by luiscerqueira** [comment]
@Gabogg07 
I haven't found a solution yet.

Does anyone know if this is a problem related only to the ios simulator or is it happening on a real device? I still haven't been able to test it on a real device.

**Comment by Gabogg07** [comment]
Usually the fixes involve adding the extension at the end of the file or using https, which you both seem to use. My issue is with some audios so is similar but not the same, but it happens in real device

**Comment by Shabnam-Veranloo** [comment]
@Gabogg07 
@luiscerqueira 
do you found any solution?

**Comment by Gabogg07** [comment]
No yet, at least not for my case @Shabnam-Veranloo

**Comment by wsrast** [comment]
I managed to fix this by doing the following:
1. Stash any of your changes in your git branch, then revert back to an earlier branch (in my case, my development branch), and reload your app in the simulator.
2. In your iOS Simulator menu: Device -> Erase All Content and Settings...
3. Revert back to your original git branch and restart your dev Metro server.
4. Reopen your app and try the video again. The error should be gone.

I only have theories on why this would work, and haven't done the legwork to see if `#1` or `#2`, or a combination of both, is the real fix here, but hopefully this will help someone else out.

**Comment by Yassir4** [comment]
Thank you @wsrast, erasing all content and settings worked for me 👍

**Comment by cchanche** [comment]
I was having pretty much the same error : my app could read audio files from a server just fine, but for some reasons, once i downloaded these files on local storage, some files triggered `NSURLErrorDomain` or `AVFoundationErrorDomain` and wouldn't play. 

I realized files on the server were .m4a files and i was overwriting the file format with .mp3, which is obviously not a good practice whatever the error might be...

So far, It looks like it fixed the problem ! 🥳

I'm not sure this was the core issue for that particular problem, especially given that I could read some local overwritten .mp3 files without triggering `onError`, but I hope it can help some of you.

**Comment by katiachumakova** [comment]
I am having the same issue but I can't load external videos, I created a test project for this

Versions:
```
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-video": "^5.1.1"
```

My code:
````
import React from 'react';
import {SafeAreaView, Text} from 'react-native';
import Video from 'react-native-video';

export default class App extends React.Component {
  render() {
    return (
      <SafeAreaView>
        <Text>Video Test</Text>
        <Video
          source={{
            uri:
              'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
          }}
          onBuffer={(e) => console.log('buffer', e)}
          onError={(e) => console.log('error', e)}
          style={{width: '100%', height: 250}}
          resizeMode={'contain'}
        />
      </SafeAreaView>
    );
  }
}
````

**Comment by AirborneEagle** [comment]
I am also grappling with this issue on my ios 14 simulator.
This issue has only shown up for us in our simulators, and it will eventually go away on its own.  The video data never changes, and has been the same for over a year. Yet still this issue shows up once in a while. It really hampers the development cycle.

Although, I did find the root cause of the issue here in the apple forums:
https://developer.apple.com/forums/thread/653346
```
This error code is returned when persistent key has expired. The server always
has an option to add a validity period for each key it issues for offline playback.
Once the validity period is over iOS will refuse to decrypt offline content protected
with such key and indicate the error with this error code.
```

This would explain why @wsrast s solution would work. it clears the old key, and the player is forced to get a new one. 
What I don't understand is:
1. How to have the player request a new key every time
and 
2. (something else. I got distracted before writing it down. will edit if I remember)

**Comment by AirborneEagle** [comment]
update:  The fix provided by @wsrast worked for me. probably wipes the dev key mentioned [here](https://developer.apple.com/forums/thread/653346)

**Comment by topherPedersen** [comment]
@Gabogg07 's solution fixed my problem: make sure you are using "https" and not "http" for your video URLs or iOS will get mad at you.

**Comment by jonattasts** [comment]
> I managed to fix this by doing the following:
> 
> 1. Stash any of your changes in your git branch, then revert back to an earlier branch (in my case, my development branch), and reload your app in the simulator.
> 2. In your iOS Simulator menu: Device -> Erase All Content and Settings...
> 3. Revert back to your original git branch and restart your dev Metro server.
> 4. Reopen your app and try the video again. The error should be gone.
> 
> I only have theories on why this would work, and haven't done the legwork to see if `#1` or `#2`, or a combination of both, is the real fix here, but hopefully this will help someone else out.

**The second option worked for me.** 🚀  👍🏻  👏🏻

**Comment by samithaFHSS** [comment]
Ensure that link has `HTTPS` not `HTTP`.
