### ISSUE TITLE
Setting paused prop to true pauses the video, but then setting it back to false does not play the video

### ISSUE THREAD

**Issue by ajpaulingalls** [TheWidlarzGroup/react-native-video#1945]
# Bug

Setting paused prop to true pauses the video, but then setting it back to false does not play the video.  Instead of playing from paused location, it plays a few frames then pauses again.  

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 64.15 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.0 => 16.13.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.1.0-alpha6

## Steps To Reproduce

```bash
[paused, setPaused] = useState(false);

<TouchableOpacity
        onPress={() => {
          setPaused(!paused);
        }}>
  <Video
            source={{uri: videoInfo.signedVideoUrl}}
            paused={paused}
          />
</TouchableOpacity>
```

## Expected behavior

1. Tapping once should pause the video
2. Tapping a second time should start the video at paused point

## Actual behavior
1. Tapping once pauses the video
2. Tapping a second time video start then immediately stops (less than a second).

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by ZhangTaoK** [comment]
+1 我也有相同的问题。I have the same question

**Comment by nickfujita** [comment]
Confirmed. This appears to only happen for me when in fullscreen mode thought. Strangely, after setting pause then play again, playback resumes as normal for that time and any future toggles.

**Comment by gauravroyzz** [comment]
whats the fix?
any updates

**Comment by ivan-vilches** [comment]
any solution?

**Comment by freeboub** [comment]
@ivan-vilches it is a very old ticket... Do you have the issue on last versions ?
