### ISSUE TITLE
audio not playing after paused prop changes  for the first time, After that it works as expected 

### ISSUE THREAD

**Issue by ncmajith** [TheWidlarzGroup/react-native-video#1946]
# Bug

 The audio paused when the paused prop changes, but wont start playing after props set to false for first time

## Platform
IOS and Android

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 120.88 MB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6200805
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by V3RT1AG0** [comment]
I was facing the same problem. For me commenting the following line of code in ReactExoPlayerView.java worked:

```
 case AudioManager.AUDIOFOCUS_LOSS:
                eventEmitter.audioFocusChanged(false);
//              pausePlayback();   //Comment out this line
                audioManager.abandonAudioFocus(this);
                break;
```

**Comment by sami3898** [comment]
after changing pause prop whole audio is play from the start. how to prevent it?

**Comment by b8ne** [comment]
@V3RT1AG0 looks like this has been removed in newer versions but im still facing the same issue. i.e. starting paused and setting state to unpause has no sound.
@ncmajith did you find a solution?

**Comment by SteveKF** [comment]
I got the exact same problem. Changing the paused prop again or uncommenting the line which @V3RT1AG0 mentions fixes this problem.
