### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by Feinikes74580** [TheWidlarzGroup/react-native-video#1948]
Failed to compile.

./node_modules/react-native-video/Video.js
Module parse failed: Unexpected token (54:7)
You may need an appropriate loader to handle this file type.
|   }
| 
|   seek = (time, tolerance = 100) => {
|     if (isNaN(time)) throw new Error('Specified time is not a number');
|

**Comment by macsj200** [comment]
I'm also encountering this using Expo and Storybook.
