### ISSUE TITLE
[iOS] Fullscreen does not have close button

### ISSUE THREAD

**Issue by shanealsingh** [TheWidlarzGroup/react-native-video#195]
I would like to display the video in fullscreen as a modal. However the 'Done' button usually found in the top left hand corner is not visible. See below.

![screen shot 2016-04-24 at 9 05 37 pm](https://cloud.githubusercontent.com/assets/1868594/14773590/8c4f1e22-0a60-11e6-9cb4-1d8f00815580.png)

**Comment by dwaligora** [comment]
any idea guys what my cause  that?

**Comment by dwaligora** [comment]
@shanealsingh have you sorted out somehow maybe?

**Comment by dwaligora** [comment]
I think, I have found something which explain the problem: 

http://stackoverflow.com/questions/31036301/no-done-button-on-avplayerviewcontroller

also, when I change my video fullscreen styles to:

``` javascript
  fullScreenVideo: {
    position: 'absolute',
    top: 10,
    left: 0,
    bottom: 0,
    right: 0
  }
```

than the video is opened not in the fullscreen and after click the fullscreen mode in the player control bar, the done button appear.
