### ISSUE TITLE
Video source URL with headers

### ISSUE THREAD

**Issue by jellohouse** [TheWidlarzGroup/react-native-video#1950]
Does react-native-video support providing headers in the source like this:

```
<Video
   source={{
     uri: myUrl,
     method: 'GET',
     headers: {
       'some-header': 'some-value',
     }
   }}
   ...
/>
```

I know that we can do this with `Image` components and it works properly.

If I load a video with a URL which doesn't require the headers it works properly,
but when I load the same video from similar URL which requires the headers (for authentication purposes) the video does not load...

react-native-video ^3.2.0

**Comment by knubie** [comment]
@jellohouse Check out https://github.com/react-native-community/react-native-video#headers

**Comment by jellohouse** [comment]
Ohh i see - Thank you!
