### ISSUE TITLE
DASH (mpd) video not being played on Android 

### ISSUE THREAD

**Issue by franco948** [TheWidlarzGroup/react-native-video#1951]
# Bug

I'm trying to play a DASH (mpd) video. When I run the application, the video doesn't play, the screen is completely white. The biggest problem is that the console is not throwing any error, which makes hard to debug the problem.

I'm using **ReNative** to deploy the application on Android.

## Platform

* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
c:\dev\ReNativePlayGround>react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.84 GB / 15.85 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

Library version: 
- react-native-video: 5.0.2

## Steps To Reproduce

1. `rnv new` and select the **blank** template 
2. Install the **react-native-video** plugin with `rnv plugin add` and select the plugin number 118
3. `rnv run -p android -d`

## Expected behaviour

1. Video playing on Android

## Reproducible sample code

```js
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Api } from 'renative';

import Video from 'react-native-video';

let AppContainer;

class App extends React.Component {
  render() {
    return (
      <View style={{ alignItems: 'center', justifyContent: 'center', flex: 1 }}>
        <Video
            source={{ uri: 'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd', type: 'mpd' }}
            style={styles.backgroundVideo}
            controls
        />
      </View>
    );
  }
}

var styles = StyleSheet.create({
    backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
});

export default App;
```

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
"react-native-video": "^5.0.2"

React native Video Black screen for Android

**Comment by RogerParis** [comment]
> "react-native": "0.61.5"
> "react-native-video": "^5.0.2"
> 
> React native Video Black screen for Android

+1

**Comment by franco948** [comment]
I resolved the problem by opening the file `settings.gradle` and replacing this line:

```java
// project(':react-native-video').projectDir = new File(rootProject.projectDir, '../../node_modules/react-native-video/android')
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../../node_modules/react-native-video/android-exoplayer')
```

**Comment by ItaloSa** [comment]
Hey @franco948 can you share this example project repo?
