### ISSUE TITLE
Last version on npm/yarn

### ISSUE THREAD

**Issue by erickmonteiro** [TheWidlarzGroup/react-native-video#1954]
On install 
```
yarn add react-native-video
```

^ 4.4.5 is installed instead of ^ 5.0.2

![Annotation 2020-03-24 101839](https://user-images.githubusercontent.com/5949005/77429761-e022ab80-6db8-11ea-9371-8e5c708b6d7b.png)

**Comment by t-fritsch** [comment]
what is strange with this is that I installed ract-native-video about a month ago, and the current version installed by npm/yarn was 5.0.2. 🤷‍♂

**Comment by rohitkum28** [comment]
Even I am facing this issue. I recently installed react-native-video from npm and it has installed version 4.4.5.

**Comment by joeyscarim** [comment]
also curious why latest version is 4.4.5, when previous versions were 5.x

@cobarx can you shed some light on this please?

**Comment by v-vashchenko** [comment]
android 5.1.0 was broken as I can see. Our project had troubles which were fixed in 4.4.5. Actually there were (caching i guess) bug, and we can't play large videos because they were stopping while playback and never resumed.
