### ISSUE TITLE
[iOS] - How to show loading (indicator) when live steam be interrupted (using hls)

### ISSUE THREAD

**Issue by sinv207** [TheWidlarzGroup/react-native-video#1955]
# Problem

I'm building hls player(m3u8) for livestreaming. And want to show loading (indicator) when livesteam be interrupted. I tried setState({loading: true}) in onBuffer(), but not working.

## Environment info
react-native: 0.59.9
react-native-video: 4.4.4

**Comment by sayem314** [comment]
use exoplayer and `onBuffer={({isBuffering}) => setLoading(isBuffering)}`

**Comment by sinv207** [comment]
> use exoplayer and `onBuffer={({isBuffering}) => setLoading(isBuffering)}`

Thanks sayem314
I'm using setState({loading: isBuffering}). 
On android it worked for me, but ios player isn't working when livesteam be interrupted.

**Comment by sayem314** [comment]
I'm not sure about iOS, but maybe use react-native-video 5.x branch an see if that works!
