### ISSUE TITLE
Problems playing aac_adts format

### ISSUE THREAD

**Issue by lucasOlivio** [TheWidlarzGroup/react-native-video#1957]
# Bug

When I record an audio using the module react-native-audio and set the OutputFormat: "aac_adts" in iPhone it plays normal, but in android the onLoad receives and object with duration 0, the audio plays but only once, I think because of the duration 0

## Platform
Android 9, samsung J7 Neo 

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.3 Linux Mint 19.3 (Tricia)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 418.56 MB / 15.36 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.3 => 0.61.3
```

Library version: 5.0.2

## Steps To Reproduce

1. Record an audio using react-native-audio, set OutputFormat to aac_adts
2. Try to play on android 2x
...

## Expected behaviour

1. The audio plays as many times as you need

**Comment by trexnguyen28** [comment]
Same here. Any solution ?

**Comment by lucasOlivio** [comment]
@thiennguyen2428 I downgraded to the version 4.4.5 and now I can play the audio as many times as I need. The duration is still 0 or negative, but at least I can play the audio again, so I just removed the duration text for now, while we don't have a fix.

**Comment by Manouli** [comment]
Yep duration is negative for me too when using aac.

**Comment by khushal87** [comment]
Any fixes for the same?
