### ISSUE TITLE
packages use deprecated "rnpm" config that will stop working from next release:

### ISSUE THREAD

**Issue by Akshayagt20** [TheWidlarzGroup/react-native-video#1958]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-video: https://github.com/react-native-community/react-native-video#readme
<img width="641" alt="Screenshot 2020-03-28 at 1 28 43 PM" src="https://user-images.githubusercontent.com/62073262/77818415-16816300-70f8-11ea-9f74-ab8068a683c4.png">

warning after build completed.
checked on android device and iOS  device.

Is this warning will affect in future ?if yes what are they?

**Comment by AxayDixit** [comment]
> warn The following packages use deprecated "rnpm" config that will stop working from next release:
> 
> * react-native-video: https://github.com/react-native-community/react-native-video#readme
> 
> <img alt="Screenshot 2020-03-28 at 1 28 43 PM" width="641" src="https://user-images.githubusercontent.com/62073262/77818415-16816300-70f8-11ea-9f74-ab8068a683c4.png">
> 
> warning after build completed.
> checked on android device and iOS device.
> 
> Is this warning will affect in future ?if yes what are they?

Were you able to resolve this?

**Comment by sivaLeo** [comment]
+1. @AxayDixit I too face this warning

**Comment by JeevaS0722** [comment]
> warn The following packages use deprecated "rnpm" config that will stop working from next release:
> 
> * react-native-video: https://github.com/react-native-community/react-native-video#readme
> 
> <img alt="Screenshot 2020-03-28 at 1 28 43 PM" width="641" src="https://user-images.githubusercontent.com/62073262/77818415-16816300-70f8-11ea-9f74-ab8068a683c4.png">
> 
> warning after build completed.
> checked on android device and iOS device.
> 
> Is this warning will affect in future ?if yes what are they?

@AxayDixit I also face this warning

**Comment by novlihalsi** [comment]
how to fix this?

**Comment by drocha-vg** [comment]
Seems that we need to change the package.
