### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by doublex** [TheWidlarzGroup/react-native-video#196]
Hello,
We have problems to play this HLS video stream on Android:
http://doppelbauer.name/hls-master.m3u8
Chrome (Android 6) plays the video:
http://doppelbauer.name/hls-test.html
Thanks a lot

**Comment by kitolog** [comment]
You can try this:
https://github.com/brentvatne/react-native-video/issues/122#issuecomment-180374051

**Comment by mattapperson** [comment]
Android HLS outside of web view (what chrome uses) SUCKS... not a lot we can do about that without a custom implementation that would be very large 😞

**Comment by doublex** [comment]
Would it be possible to feed the player from a javascript HLS implementation like:
https://github.com/dailymotion/hls.js

**Comment by mattapperson** [comment]
Sorry no. That library relies on HTML5 APIs

**Comment by mattapperson** [comment]
Your best bet would be a PR or alternate module https://github.com/react-native-community/react-native-video/pull/256
Sadly this one was abandoned
