### ISSUE TITLE
Exoplayer playback issue

### ISSUE THREAD

**Issue by sayem314** [TheWidlarzGroup/react-native-video#1960]
# Bug

![image](https://user-images.githubusercontent.com/14138401/77832045-4e6ec180-715d-11ea-9dc2-c8268e1d4a9f.png)

## Platform
* Android ExoPlayer

## Environment info

```
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 288.70 MB / 7.67 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /tmp/yarn--1585424058306-0.11591669179655639/node
    Yarn: 1.22.4 - /tmp/yarn--1585424058306-0.11591669179655639/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.4.5 and 5.1.0-alpha6

## Issue

I'm trying to play videos with exoplayer, maximum videos is not working while mediaplayer works totally fine. Error console log:

```
{"errorException": "Response code: 500", "errorString": "Unrecognized media format"}
```

**Comment by geroale** [comment]
Same issue here.

**Comment by jensellfors** [comment]
What type video are you trying to play? You can see supported formats here https://exoplayer.dev/supported-formats.html

**Comment by sayem314** [comment]
@jenshandersson x264, as I said in the post MediaPlayer plays fine so ExoPlayer should play as well.

**Comment by jensellfors** [comment]
Sounds like an issue with Exoplayer then, have a look in their issues

**Comment by sayem314** [comment]
@jenshandersson could be but again `react-native-video` is using older version of exoplayer.

**Comment by jensellfors** [comment]
You can upgrade it and test. But x264 is common and works for most. I saw an ExoPlayer issue around self signed certs, maybe that's something. But this is more a question for StackOverflow.
