### ISSUE TITLE
Can't install react-native-video for Windows

### ISSUE THREAD

**Issue by franco948** [TheWidlarzGroup/react-native-video#1965]
# Bug

I'm following the steps for Windows in the **README** file of the repository. After adding a reference to the `ReactNativeVideoCPP` project, I include the header `winrt/ReactNativeVideoCPP.h` to the `pch.h` file and I get the error: **cannot open source file "winrt/ReactNativeVideoCPP.h"**.

> I installed the library using the link to the GitHub repository instead of `npm i react-native-video` because this last approach didn't come with the **ReactNativeVideoCPP** project.

## Platform

Which player are you experiencing the problem on:

* Windows UWP

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.63 GB / 15.86 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0-0 => 0.60.6
```

Library version: https://github.com/react-native-community/react-native-video (in **package.json**)

## Steps To Reproduce

1. Create a project using the steps in the [Getting Started](https://microsoft.github.io/react-native-windows/docs/getting-started) guide of React Native
2. Add `ReactNativeVideoCPP` project to the solution
3. Add a reference to `ReactNativeVideoCPP` in the main application project
4. Add `#include "winrt/ReactNativeVideoCPP.h"` in pch.h
...

**Comment by casperbox** [comment]
I had this same issue, app doesn't compile after following all the steps 👎

**Comment by itsaberi** [comment]
+1

**Comment by itsaberi** [comment]
same issue
