### ISSUE TITLE
TypeError null is not an object (evaluating 'RCTVideoInstance.Contants' )

### ISSUE THREAD

**Issue by liyongqi666** [TheWidlarzGroup/react-native-video#1966]
There was a bug when my project was running：
TypeError null is not an object (evaluating 'RCTVideoInstance.Contants' )

it didn't work after **react-native link react-native-video** and restart my project

![image](https://user-images.githubusercontent.com/53437455/78332686-0e736880-75bb-11ea-8efa-a7114ee5297c.png)

**Comment by hirvin-faria** [comment]
run again the command `npx react-native run-android` or `npx react-native run-ios`.

**Comment by Razorholt** [comment]
Same issue and I tried all suggestions.

**Comment by sudipta-pran** [comment]
I am having the same issue. I'm using it in an expo project. Has anyone found the solution?

**Comment by sagardalal21** [comment]
Having the same issue. Is there any solution, please?
