### ISSUE TITLE
Is there feature for offline video (mpd video url) download using react-native-video?

### ISSUE THREAD

**Issue by raikk** [TheWidlarzGroup/react-native-video#1967]
# Feature Request

**Comment by moskalakamil** [comment]
Hey all!
We've recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=1967) that lets you download and play video content offline - including DRM-protected streams. 
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=1967)
