### ISSUE TITLE
When pass `callback` to component, it doesn't trigger.

### ISSUE THREAD

**Issue by broerjuang** [TheWidlarzGroup/react-native-video#1969]
# Bug
When pass `callback` to component, it doesn't trigger.
For example,

```javascript
<Video 
    source={source}
   onError={(error) => console.log('error onError', error)}
 />
```

but the error triggered when give it a constant or value
```javascript
<Video 
    source={source}
   onError={console.log("Error")}
 />
```

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by bigbadfatman** [comment]
Don't really have much to go on here to help with your actual issue. But with the second example, it isn't really triggering the error callback, it is just getting executed.
