### ISSUE TITLE
Is there anyway to allow idle timeout on IOS?

### ISSUE THREAD

**Issue by seanadkinson** [TheWidlarzGroup/react-native-video#197]
We are using `react-native-video` to play a background video on our login screen.  Works great, thanks!  But while this video is playing (on a loop, forever), the app will never idle and lock, which seems undesirable.  When I comment out the background video, the idle timeout works as expected.

Is there anyway to allow the idle timeout to take effect while the background video is playing?  And if so, can this library expose that as an option?

**Comment by mskalra** [comment]
+1

**Comment by mattapperson** [comment]
This can not be done without private APIs 😞
