### ISSUE TITLE
How to check, if exoplayer is running on Android?

### ISSUE THREAD

**Issue by swizes** [TheWidlarzGroup/react-native-video#1971]
Hello,

I have implemented the module with correct configurations for exoplayer on android but I would like to assure that it is successfully configurated and android is not using its default media player, how can I detect it?

**Comment by jensellfors** [comment]
If you are using the default setup you will be using MediaPlayer. I think you can tell from the color of the thumb on the seeker, white=Exo green=MediaPlayer :) Otherwise add some logging to the java files

**Comment by pk936** [comment]
I see green thumb even I have tried both configs to use exoplayer:

1. Created **react-native.config.js** in root folder and added following lines:

```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};

```

2. In **settings.gradle**, added following lines:
```

include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by nageshvarmak** [comment]
Can you please elaborate with some Images ? i tried with logging but the logs added in .java file are not visible in the terminal,
