### ISSUE TITLE
Video from local file extremely slow to load on ios device

### ISSUE THREAD

**Issue by 82rules** [TheWidlarzGroup/react-native-video#1972]
# Bug

Video playing from local file works fine on android/ios simulators. 
However on device, android works fine but ios takes 30 seconds + to load a mp4 that is 30 mb in size and about 45 seconds in length. 

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 520.71 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.12.0 => 16.12.0 
    react-native: ^0.61.5 => 0.61.5
```

Library version:  4.4.5

## Steps To Reproduce

Load react-native-video using a local mp4 and build to device

## Expected behaviour

Video to start playing immediately

## Video sample
https://www.pexels.com/video/a-poodle-dog-s-fur-swaying-by-the-wind-blows-3299684/

**Comment by naninmartins** [comment]
Hey I'm with the same problem here, at my case I'm consuming a video from S3 bucket and at ios the stream delay almost 30 min to reproduce, anyone have some fix for this? Recently my device has been updated ios version to 12.4.5

**Comment by etsraphael** [comment]
Hi! I got the same problem.. I have to wait 5min to play 2 secondes of my video :/

**Comment by jensellfors** [comment]
Sounds like you are loading the video using the JS bridge, that will be slow when running on device over WiFi. Instead you can add the video asset to eg Xcode project and load using file://
