### ISSUE TITLE
5.1.x out of alpha

### ISSUE THREAD

**Issue by scandinaro** [TheWidlarzGroup/react-native-video#1973]
I'm currently blocked by this bug (https://github.com/react-native-community/react-native-video/pull/1699).  I've been able to test the fix successfully in the alpha version, but I'm worried about stability since it is still titled as `alpha`.  Is there a schedule for when we should expect a 5.1.x version to be in wide release?

**Comment by JustinM-AllSocial** [comment]
Lets get an update for this please

**Comment by merissaacosta** [comment]
Any updates on this?

**Comment by sharifhh** [comment]
The fix is not working 100%, I have seen a reproduction on 5.1.0-alpha, I will try to investigate why ...

**Comment by michaelknoch** [comment]
would be awesome to get current master released on npm. The new version of exoplayer has some nifty improvements.

**Comment by jacob-israel-turner** [comment]
I've seen some recent updates to the version on NPM, but is 5.1 ready for production?  I'm trying to decide which version to lock in to...
