### ISSUE TITLE
isBuffering returns false on onBuffer

### ISSUE THREAD

**Issue by doruxan** [TheWidlarzGroup/react-native-video#1975]
I'm using **v4.4.4**  on my project. As you can se below I listed the written and possible eventProps on my video player to get a feeling how can I design a ux for user to get a seemles video start after some caching operations. 

On **IOS**, much of them won't fire. Also my main problem now is onBuffer returns isBuffering prop false most of the time. 

On **Android** I'm using **exoPlaye**r. onBuffer just calls twice, but in expected sequence.

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 79.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found

 ```
   const onPlayPressed = () => {
        console.log('play')
        setPaused(!paused)
    }

    const onBuffer = (meta) => {
        // setIsBuffering(meta.isBuffering)
        console.log('BUFFER', meta)
    }

    const onStart = (meta) => {
        console.log('VIDEO ON START', meta)
    }

    const onEnd = (meta) => {
        console.log('VIDEO ON END', meta)
    }

    const onLoad = (meta) => {
        console.log('VIDEO ON LOAD', meta)
    }

    const onLoadStart = (meta) => {
        console.log('VIDEO ON LOAD START', meta)
    }

    const onProgress = (meta) => {
        console.log('VIDEO ON PROGRESS', meta)
    }

    const onPlaybackStalled = (meta) => {
        console.log('VIDEO ON PLAYBACK STALLED', meta)
    }

    const onPlaybackResume = (meta) => {
        console.log('VIDEO ON PLAYBACK RESUME', meta)
    }



      <Video
                    source={{ uri: item.video }}
                    style={styles.thumbnail}
                    resizeMode={'cover'}
                    repeat={true}
                    disableFocus={false}
                    muted={true}
                    paused={paused}
                    onDownloadBegin={onDownloadBegin}
                    onDownloadProgress={onDownloadProgress}
                    onDownloadEnd={onDownloadEnd}
                    onBuffer={onBuffer}
                    onStart={onStart}
                    onEnd={onEnd}
                    onLoad={onLoad}
                    onLoadStart={onLoadStart}
                    onProgress={onProgress}
                    onPlaybackStalled={onPlaybackStalled}
                    onPlaybackResume={onPlaybackResume}
                    useTextureView
                />

```

this is console for IOS
![image](https://user-images.githubusercontent.com/45385634/79466720-9e76d080-8005-11ea-991c-5fb7f9490a42.png)

this is console for Android

[Thu Apr 16 2020 17:03:20.647]  LOG      VIDEO ON LOAD START {"src": {"isNetwork": true, "type": "", "uri": "MyUriThatIHaveWrittenForYouGuys"}, "target": 19}
[Thu Apr 16 2020 17:03:22.410]  LOG      BUFFER {"isBuffering": true, "target": 19}
[Thu Apr 16 2020 17:03:22.450]  LOG      BUFFER {"isBuffering": false, "target": 19}
[Thu Apr 16 2020 17:03:22.500]  LOG      BUFFER {"isBuffering": false, "target": 19}
[Thu Apr 16 2020 17:03:22.540]  LOG      VIDEO ON LOAD {"audioTracks": [], "canPlayFastForward": false, "canPlayReverse": false, "canPlaySlowForward": false, "canPlaySlowReverse": false, "canStepBackward": false, "canStepForward": false, "currentTime": 0, "duration": 7.637333393096924, "naturalSize": {"height": 1080, "orientation": "landscape", "width": 1920}, "target": 19, "textTracks": []}
[Thu Apr 16 2020 17:03:22.570]  LOG      BUFFER {"isBuffering": false, "target": 19}
[Thu Apr 16 2020 17:03:22.610]  LOG      BUFFER {"isBuffering": false, "target": 19}
[Thu Apr 16 2020 17:03:22.640]  LOG      BUFFER {"isBuffering": false, "target": 19}

**Comment by osafahmad** [comment]
hi i see thumbnail object in your post Image .. i want to know how can show thumbnail in android like ios .

**Comment by doruxan** [comment]
It's just a style name actually but I think I will be going to set video components height:0 to keep it mounted, and conditionally show an image till videoOnStart function set a state. When the "playing" state is set, video will get its predefined height.

Something like;
```
<>
{!videoPlaying && <Image />}
<Video style={videoPlaying ? {styles.videoStyle} : {height:0}} /> 
</>
```

**Comment by naninmartins** [comment]
Hey I'm passing the same at Ios platform, the video can't caching and reproduce so slowly, can anyone fix this?

**Comment by ataravati** [comment]
I'm having the same issue.

**Comment by eraykose** [comment]
I have the same issue on iOS with v4.4.5. I also realized it doesn't return true most of the time when it actually buffering, then it returns suddenly false when buffer finishes. But I don't know when the buffer actually starts.

**Comment by Ashwin-Mothilal** [comment]
I have also faced the same issue, but I solved it like this. 

```
canShowBufferOrPlayPauseButton = () => {
    return (
      this.props.bufferedDuration < this.props.currentTime
    );
};
```

You can get `playableDuration` which is bufferedDuration and `currentTime` in [onProgress](https://github.com/react-native-community/react-native-video#onprogress) method

**Comment by AndresTIY** [comment]
@Ashwin-Mothilal Does that work for you? Maybe because I'm on the simulator, but my bufferedDuration -> `playableDuration` is always the full length of my video. Even when I change my network speed to 3G, my video just pauses and waits until it's ready, but `playableDuration` is always the length of the video. 

I'm using react-native-video 5.0.2 and the video type is mp4

**Comment by Ashwin-Mothilal** [comment]
I uploaded a 10min HD video so the `playableDuration` differs as I progress through the video. I'm not sure about your video type. I'm on react-native-video 4.4.4

**Comment by WaqarAmjad345** [comment]
sane issue

**Comment by Joao360** [comment]
> I have also faced the same issue, but I solved it like this.
> 
> ```
> canShowBufferOrPlayPauseButton = () => {
>     return (
>       this.props.bufferedDuration < this.props.currentTime
>     );
> };
> ```
> 
> You can get `playableDuration` which is bufferedDuration and `currentTime` in [onProgress](https://github.com/react-native-community/react-native-video#onprogress) method

This solution doesn't work every time, is there any better way to see if the video is buffering? 

One way I'm thinking is checking if the currentTime is increasing while the video is not paused and add a timeout when it's not increasing

**Comment by ghost** [comment]
The same issue here. The `playableDuration` workaround doesn't work for me as it's always higher than `currentTime`.

**Comment by Navipro70** [comment]
const PROGRESS_UPDATE_INTERVAL = 250 //MS
const DOUBLE_PROGRESS_UPDATE_INTERVAL = 0.5 // SEC

onProgress = ({currentTime, playableDuration, duration}) => {
   ...
  const isBuffering = currentTime >= playableDuration - DOUBLE_PROGRESS_UPDATE_INTERVAL && playableDuration !== duration
  setIsBuffering(isBuffering)
}

**Comment by mouhcine007** [comment]
any updates on this ?

**Comment by freeboub** [comment]
@mouhcine007 is it reproduced on V6 ?
