### ISSUE TITLE
Huawei mobile phone rate set  problem

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#1980]
Some phones of huawei cannot set the doubling speed. When the doubling speed is one, it will play normally; 
![image](https://user-images.githubusercontent.com/33045757/79966727-703f3800-84c0-11ea-88f5-61d21d7a2a3f.png)

when the doubling speed is greater than one, it will stop playing and cannot continue to play.

![image](https://user-images.githubusercontent.com/33045757/79966032-6b2db900-84bf-11ea-9c74-ca75660548d9.png)

My Package.json is:
![image](https://user-images.githubusercontent.com/33045757/79966278-cc558c80-84bf-11ea-8a5a-d5ef504e6765.png)

**Comment by zuozoe** [comment]
the same issue
