### ISSUE TITLE
Why no "autoplay" props, and poster hide quickly when page load 

### ISSUE THREAD

**Issue by skykingit** [TheWidlarzGroup/react-native-video#1982]
i can not find a props to set the video autoplay false
so i have to set props paused="true"
but it make a bug when i set a poster
when the page load ,the poster hide quickly because the video auotplay

**Comment by alierenkara** [comment]
You should use onLoad and paused props. When the video loads you should setState paused true
`onLoad = () => {
    this.setState({
      paused: true
    })
  }`

**Comment by skykingit** [comment]
> You should use onLoad and paused props. When the video loads you should setState paused true
> `onLoad = () => { this.setState({ paused: true }) }`

ok,thanks
