### ISSUE TITLE
[Android] Opacity is black instead of the color of the parent view of a video

### ISSUE THREAD

**Issue by FrederickEngelhardt** [TheWidlarzGroup/react-native-video#1983]
# Bug

Android does not behave like iOS for opacity. Android will show a black screen as the opacity increases as to iOS which will reveal the container underneath.

This issue happens when applying opacity to a parent view or directly to the react-native-video component.

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.04 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/<my username>/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. Add RNVideo to any android project
2. Add opacity to the RNVideo component. Notice that iOS can display the background color if RNVideo is transparent.
...

## Expected behaviour

1. Android should not show black background for player if the background parent view is a lighter color

## Reproducible sample code

```
const style = {
    width: 500,
    height: 500,
    opacity: 0.5,
  };
const Component = () =>    ( 
<RNVideo
        source={<ANY VIDEO url or asset>}
        style={style} 
        hideShutterView // hides blackscreen on android
      />)
```

**Comment by Christian-Athom** [comment]
I can confirm that for both players this problem exists. I also tried to see where the problem arrises, but so far no luck in identifying the problem.

**Comment by mycarrysun** [comment]
Can confirm this problem exists in our project as well

**Comment by Christian-Athom** [comment]
I have found a solution to the problem, you can modify the ExoPlayerView a little bit to have the correct opacity:

Find the function: updateSurfaceView in ExoPlayerView.java and change it to:

```
private void updateSurfaceView() {
        if (useTextureView) {
            TextureView view  = new TextureView(context);
            view.setOpaque(false);
            view.setLayoutParams(layoutParams);
            surfaceView = view;
        }
        else {
            SurfaceView view  = new SurfaceView(context);
            view.setLayoutParams(layoutParams);
            surfaceView = view;
        }

        if (layout.getChildAt(0) != null) {
            layout.removeViewAt(0);
        }
        layout.addView(surfaceView, 0, layoutParams);

        if (this.player != null) {
            setVideoView();
        }
    }
```

**Comment by georgewwindsor** [comment]
still an issue, bump.

**Comment by areimann-sf** [comment]
Running into this as well...bump

**Comment by AudyOdi** [comment]
I encountered this issue recently. I found out that the video component doesn't support opacity props. So even if the parent view supports opacity, if the underlying children components don't support it, then the component won't show opacity correctly. You can try changing the video component to a regular View and see if you still can reproduce this issue.
