### ISSUE TITLE
[iOS] AudioObjectRemovePropertyListener: no object with given ID 0

### ISSUE THREAD

**Issue by PauloMello99** [TheWidlarzGroup/react-native-video#1984]
# Bug

When in PRD environment, the Player still plays its audio even if you are out of the screen who mounted it. On Xcode log every time I navigate back to the video screen and go back, it logs the message: App[XXX:XXX] AudioObjectRemovePropertyListener: no object with given ID 0

## Platform
* iOS

## Environment info

System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 45.71 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 4.4.5

## Steps To Reproduce

1. Implement  screens A and B, B must have the VideoPlayer with a m3u8 running (using react-navigation 4.0.10)
2. While the video playing, go back to screen A

## Expected behaviour

1. VideoPlayer be properly unmounted as its listeners on iOS

**Comment by enigmablue** [comment]
+1
