### ISSUE TITLE
Background video freezes when i pull down notifications

### ISSUE THREAD

**Issue by mirzaam786** [TheWidlarzGroup/react-native-video#1986]
# Bug

I have a background video playing (video is local to the app) and runs smoothly on android and iOS. However on iOS when i pull down from the notification centre the video freezes. The only way to start it again is to close the app and restart it. There are no additional error messages. This happens on the iOS simulator and on devices. 

Code is:

       <SafeAreaView style={styles.container}>

       <Video
               style={styles.backgroundVideo}
               source={backgroundImage}
               muted={true}
               repeat={true}
               resizeMode={"cover"}
               rate={1.0}
               ignoreSilentSwitch={"obey"}
         />

**Comment by mirzaam786** [comment]
This is on RN 0.59

**Comment by mirzaam786** [comment]
Anyone have an answer to this. It doesn't happen if i switch to another application, only if i pull something down

**Comment by mirzaam786** [comment]
Still  not working, need a response please.

**Comment by AndresTIY** [comment]
So when the AppState becomes inactive, the video pauses automatically. 

[AppState Docs](https://reactnative.dev/docs/appstate)

AppState changes to `inactive` when the notification center is pulled down. So maybe something like this would help...

```js
import { AppState } from 'react-native';
import React, { useState, useEffect } from 'react';
import Video from 'react-native-video';

const SampleVideoFile = () => {
  const [videoPaused, toggleVideoPaused] = useState(false);
  const [appActive, setAppActive] = useState(false);

  const handleAppStateChange = nextAppState => {
    if (nextAppState === 'active') {
      setAppActive(true);
    } else {
      setAppActive(false);
    }
  };

  useEffect(() => {
    AppState.addEventListener('change', handleAppStateChange);
    return () => AppState.removeEventListener('change', handleAppStateChange);
  }, []);

  useEffect(() => {
    appActive ? toggleVideoPaused(false) : toggleVideoPaused(true);
  }, [appActive]);

  return (
    <Video
      style={styles.backgroundVideo}
      source={backgroundImage}
      muted
      repeat
      paused={videoPaused}
      resizeMode="cover"
      rate={1.0}
      ignoreSilentSwitch="obey"
    />
  );
};


```
 

Hope this helps!

**Comment by mirzaam786** [comment]
thanks Andres, that worked perfectly

**Comment by waqaramjad** [comment]
use that prop, it will resolve the issue 
`playWhenInactive:true`
