### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()'

### ISSUE THREAD

**Issue by iamadityaaz** [TheWidlarzGroup/react-native-video#1989]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 2.63 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

> Error log - From Sentry.io
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference
    at com.yqritc.scalablevideoview.ScalableVideoView.getCurrentPosition(ScalableVideoView.java:200)
    at android.widget.MediaController.setProgress(MediaController.java:438)
    at android.widget.MediaController.show(MediaController.java:358)
    at android.widget.MediaController.show(MediaController.java:314)
    at com.brentvatne.react.ReactVideoView$2.run(ReactVideoView.java:572)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6820)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
```

![Screenshot 2020-05-03 at 1 06 28 PM](https://user-images.githubusercontent.com/30999510/80908809-970f3100-8d40-11ea-821f-7bcfddb1c11f.png)

**Comment by minh-dai** [comment]
same issues :((

**Comment by dharminderraja** [comment]
same here.

**Comment by dharminderraja** [comment]
same issue

**Comment by zvs001** [comment]
Easy to reproduce with react-navigation.

I had video, which automatically start playing on some screen. (tab in my case)
When I navigate to different screen, crash immediately appears.

Temporary solved by: 
```
  const isFocused = useIsFocused()
  if (!isFocused) return null
```

**Comment by zvs001** [comment]
This problem make android version very unstable.

Meantime, I switched to exoplayer. And issue gone.

**Comment by cakesoft-rohit** [comment]
Facing this issue, any workaround?

**Comment by Mozartted** [comment]
Any workarounds for this issue ? still facing it.

**Comment by bogas04** [comment]
As per [this](https://stackoverflow.com/questions/27926267/android-mediaplayer-getduration-and-getcurrentposition-has-nullpointerexce/27926911) it seems the issue is that react-native-video internally makes calls that try to access async value. So the proper solution would be actually in the native land where such access calls are made in a thread-safe manner.

**Comment by AparnaManjalavil** [comment]
I'm stuck with same issue. Any solution?

**Comment by abolfazlyounesi** [comment]
I am having this issue too. Any fixes/solutions?

**Comment by wood1986** [comment]
I have a fix for that.

See https://github.com/wood1986/react-native-video/commit/2e86e8f7782adcf8bddecaaef12c4297a1be5741

But I do not know how I contribute this fix as react-native-video is preparing 6.0.0. ReactVideoView no longer exists in main branch or 6.0.0

**Comment by wood1986** [comment]
I have a fix for that.

See https://github.com/wood1986/react-native-video/commit/1330a78a63881ff24629f8cec1fcfe18ce62250e

But I do not know how I contribute this fix as react-native-video is preparing 6.0.0. ReactVideoView no longer exists in main branch or 6.0.0

**Comment by hueniverse** [comment]
@wood1986 you should be able to map the patch to the current master and open a new PR.

**Comment by coayscue** [comment]
Yeah this worked  for me

> Easy to reproduce with react-navigation.
> 
> I had video, which automatically start playing on some screen. (tab in my case) When I navigate to different screen, crash immediately appears.
> 
> Temporary solved by:
> 
> ```
>   const isFocused = useIsFocused()
>   if (!isFocused) return null
> ```

**Comment by chandwho** [comment]
> This problem make android version very unstable.
> 
> Meantime, I switched to exoplayer. And issue gone.

@zvs001 Thanks! Switching to exoplayer fixed the issue

**Comment by vannamphuc** [comment]
> > This problem make android version very unstable.
> > Meantime, I switched to exoplayer. And issue gone.
> 
> @zvs001 Thanks! Switching to exoplayer fixed the issue

Hello @chandwho How can you fix this. Can you describe for me

**Comment by freeboub** [comment]
@tomheo11233aA the easiest is to switch on v6.0.0-beta.9

**Comment by chandwho** [comment]
> > > This problem make android version very unstable.
> > > Meantime, I switched to exoplayer. And issue gone.
> > 
> > 
> > @zvs001 Thanks! Switching to exoplayer fixed the issue
> 
> Hello @chandwho How can you fix this. Can you describe for me

@tomheo11233aA add this in dependencies of your react-native.config.js file

'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },

react-native-video will switch to exoplayer
