### ISSUE TITLE
HLS not working

### ISSUE THREAD

**Issue by boringstuff-dev** [TheWidlarzGroup/react-native-video#1990]
# Bug

 installation method with jetifier
I'm using the latest version of react-native-video
- yarn add react-native-video@5.1.0-alpha5
I've also tried with version 4.4.5 (same results)

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
    Memory: 1.39 GB / 7.97 GB
  Binaries:
    Node: 13.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: javac 12
    Python: 3.7.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
```

## Steps To Reproduce

import Video from 'react-native-video';
<View style={{ flex: 1}}>
      <Video
        source={{uri: ' https://stream.mux.com/### ', type:"m3u8"}}   // THIS IS NOT WORKING
        source={{uri: ' https://cdn3.wowza.com/##/hls/live/playlist.m3u8 ', type:"m3u8"}}   // THIS IS NOT WORKING
        // source={require('../../assets/test.mp4')} // THIS IS WORKING 
        resizeMode="cover"
        onError={console.log('ERROR LOADING')}
        style={{ 
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            right: 0
        }}
      />

WHAT I HAVE ALREADY DONE AFTER THE INSTALLATION:

- in settings.gradle: 
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')

// include ':react-native-video'
// project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

- added to build.grandle:
dependencies {
    compile project(':react-native-video')
    implementation "androidx.appcompat:appcompat:1.0.0" 

- added to MainApplication.java
          packages.add(new ReactVideoPackage());

## Expected behaviour

1. Reproduce correctly from the HLS source

Any idea of what i'm missing or if there are others steps to do?
Thanks

**Comment by karanpratapsingh** [comment]
@Gollum97 Hey did it work? I am also trying this with MUX

**Comment by jocelNardi** [comment]
@boringstuff-dev , did it work ?

**Comment by scottschindler** [comment]
Hey @boringstuff-dev @karanpratapsingh @jocelNardi same problem. Any luck with a fix?
