### ISSUE TITLE
Audio file works on Android but not iOS - AVFoundationErrorDomain

### ISSUE THREAD

**Issue by Gabogg07** [TheWidlarzGroup/react-native-video#1993]
# Bug

I have an audio I need to produce and it works like a charm in Android, but when it comes to IOS I get {"error": {"code": -11828, "domain": "AVFoundationErrorDomain"}, "target": 6675}

I am using https and also enabled arbitrary loads as they were some of the solutions I managed to find out there

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Memory: 130.45 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.1.0 => 3.2.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

Library version: 5.0.1

## Steps To Reproduce

1. Open a video player with audio only props and set the source to https://s3-us-west-2.amazonaws.com/uriji-media-dev/posts/5eb2f32dd801504ba30e087a/services/1588787996.mp3
2- I get {"error": {"code": -11828, "domain": "AVFoundationErrorDomain"}, "target": 6675} error
...

## Expected behaviour

1. The audio will reproduce

## Reproducible sample code
      <Video
        source={{ uri: 'https://s3-us-west-2.amazonaws.com/uriji-media-dev/posts/5eb2f32dd801504ba30e087a/services/1588787996.mp3'}}
        audioOnly
      />

**Comment by ZhangTaoK** [comment]
+1

**Comment by kartavyaparekh96** [comment]
Any update?

**Comment by andry1001** [comment]
+1

**Comment by geroale** [comment]
+1

**Comment by BadtzMaru** [comment]
the same problem to me
