### ISSUE TITLE
Video from server is not playing in android

### ISSUE THREAD

**Issue by Saad9624** [TheWidlarzGroup/react-native-video#1995]
# Bug

Video is not playing when fetching from remote server while the same url is playing on browser perfectly
i am getting this weired error cant find related to this error in the existing issues
error {"error": {"extra": -2147483648,
"what": 1}}

## Platform

Which player are you experiencing the problem on:

* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

 react: 16.9.0 => 16.9.0
 react-native: 0.62.1 => 0.62.1
 Node: 12.10.0
react-native-video => 4.4.5

Library version: 4.4.5

If possible, include a link to the video that has the problem that can be streamed or downloaded from.
some of the videos are playing that are located on google drive but the video located on our server is not playing

**Comment by Saad9624** [comment]
Also please if no one is maintaining this piece of garbage then i would recommend to close it :)

**Comment by moulie415** [comment]
@Saad9624 I was getting this error when I was pointing to the wrong url, when I went to the url it was 404ing, make sure its a valid url.

**Comment by jschnurholmes** [comment]
@Saad9624 I was having issues playing videos from a remote URL that didn't have a file extension. The exoplayer integration at least uses the file extensions to setup the correct type of media source before making the request. Not sure what error I was receiving, but make sure your URL has a file extension and it matches the remote file contents. If this is your issue, you can alternatively pass the `type` attribute of the `source` parameter with the appropriate file extension for the remote contents if you know it ahead of time.

**Comment by Saad9624** [comment]
it seems like the video file is invalid try playing this short video https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4
    On Tuesday, May 26, 2020, 08:07:49 PM GMT+5, jschnurholmes <notifications@github.com> wrote:  
 
 


@Saad9624 I was having issues playing videos from a remote URL that didn't have a file extension. The exoplayer integration at least uses the file extensions to setup the correct type of media source before making the request. Not sure what error I was receiving, but make sure your URL has a file extension and it matches the remote file contents.

**Comment by Saad9624** [comment]
i solved this by adding this dependency in react-native.config.js 
 dependencies: {
        'react-native-video': {
            platforms: {
                android: {
                    sourceDir: '../node_modules/react-native-video/android-exoplayer',
                },
            },
        },
         },
