### ISSUE TITLE
iOS 10 crash NSInternalInconsistencyException AVPlayerItem was deallocated while key value observers were still registered with it

### ISSUE THREAD

**Issue by marf** [TheWidlarzGroup/react-native-video#1996]
# Bug
Hello, I am using react-native and I see lots of crashes on **iPhone 5, iPhone 5c running iOS 10** with this issue:

Fatal Exception: NSInternalInconsistencyException
An instance 0x15eed6e0 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x15bbf0c0> ( <NSKeyValueObservance 0x15ea0a30: Observer: 0x15af23b0, Key path: status, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x15ea4e50> <NSKeyValueObservance 0x15ecf130: Observer: 0x15af23b0, Key path: playbackBufferEmpty, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x15aea630> <NSKeyValueObservance 0x15ef5920: Observer: 0x15af23b0, Key path: playbackLikelyToKeepUp, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x15ef5900> <NSKeyValueObservance 0x15ece400: Observer: 0x15af23b0, Key path: timedMetadata, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x15ab8650> )

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 757.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.npm-packages/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.0.2

**Comment by geroale** [comment]
Same issue here.
