### ISSUE TITLE
Android.  When auto play is turned on, the current display screen cannot be kept on.

### ISSUE THREAD

**Issue by A-ANing** [TheWidlarzGroup/react-native-video#1997]
# Bug

If the video is played automatically, it can't keep the screen on. You have to click pause manually and then click play. I wonder if the "keepscreen on" method works when it plays automatically?

**Comment by A-ANing** [comment]
"react-native-video": "^4.4.4",

**Comment by ngxu** [comment]
`
this.state={
paused:true
}
componentDidMount() {
        this.setState({
            paused:false
        })
    }

<Video
paused={this.state.paused}
/>
`

Use this method to solve the problem

**Comment by ngxu** [comment]
`this.state={
paused:true
}
componentDidMount() {
this.setState({
paused:false
})
}
`

Use this method to solve the problem

**Comment by ngxu** [comment]
`this.state={
paused:true
}

componentDidMount() {
this.setState({
paused:false
})
}


<Video paused={this.state.paused}/>`


Use this method to solve the problem

**Comment by ngxu** [comment]
`componentDidMount() {
       
        this.setState({
            paused:false
        })

    }`


Use this method to solve the problem

**Comment by ngxu** [comment]
```
componentDidMount() {

    this.setState({
        paused:false
    })

}

```
Use this method to solve the problem
