### ISSUE TITLE
Video disappears when app goes to background and returns to foreground

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#1998]
I'm building an iOS app and i have used this module like so: 

```

                 <Video 
                      source={{uri: this.state.url }}      
                      ref={(ref) => {this._player = ref}}
                      repeat={this.state.repeat}  
                      paused={this.state.paused}
                      style={styles.video}
                 /> 


```
When the app is sent to the background on the iPhone, then when it is recalled to the foreground, the video is gone! Why is this?

I don't mind the video restarting from the beginning, but it needs to be there, playing, as theres a huge gap on the app screen. 

The user has to go to another tab in the bottomTabNavigator and return, to get the video back!

**Comment by jensellfors** [comment]
Try setting these props and see if there's a difference:

```
playInBackground={false}
playWhenInactive={false}
```

**Comment by chai86** [comment]
Yes that helps thanks

**Comment by franekantoni** [comment]
I faced the same problem, setting those props to false didn't help. I am using react-native-video to play a video stream. I also need audio to play in the background. Is there any fix for that?
