### ISSUE TITLE
Issue with onSeek callback

### ISSUE THREAD

**Issue by JohnPremKumar** [TheWidlarzGroup/react-native-video#1999]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
 // paste it here
System:
    OS: Windows 10
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 1.51 GB / 6.95 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 21.1.2, 24.0.1, 25.0.0, 26.0.2, 27.0.1, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: Version  3.0.0.0 AI-171.4443003
  npmPackages:
    react: 16.8.1 => 16.8.1
    react-native: 0.61.3 => 0.61.3
```

Library version: 4.4.5

## Steps To Reproduce

1. Initialize the video player with onSeek callback handle
2. Seek the video using seek() method
3. The onSeek callback is called immediately

## Expected behaviour

1. As per the documentation the onSeek callback should be called only after the seek completion.

**Comment by igor-bv** [comment]
I have the same issue...
Any updates on this issue?

@JohnPremKumar, were you able to fix it somehow?:)
