### ISSUE TITLE
Unable to play multiple videos at the same time

### ISSUE THREAD

**Issue by danklammer** [TheWidlarzGroup/react-native-video#2]
I believe it has to do with the limitations of MediaPlayer rather than using AVPlayer.

![multiple-videos](https://cloud.githubusercontent.com/assets/1743221/6951805/e81d9d76-d88b-11e4-8a83-4489d461eb7f.gif)

**Comment by brentvatne** [comment]
@danklammer - If you get a chance to do this before me, converting this to AVPlayer seems like a good choice going forward, PR is welcome and I'll give you a commit bit. Otherwise I'll take care of it when I have time. Thanks for letting me know!

**Comment by danklammer** [comment]
👍

**Comment by brentvatne** [comment]
@danklammer - I took care of this in e504944ef593d947f34d3a1acbb75c07ab03e7c4 - pull down 0.1.6 and the app that you recorded above should just work.

![two-videos](https://cloud.githubusercontent.com/assets/90494/6995316/5f049240-daf4-11e4-82ef-eec468d43775.gif)

Thanks for letting me know about the issue! :smile:

**Comment by danklammer** [comment]
Awesome! Thanks @brentvatne!
