### ISSUE TITLE
[iOS] If muted video used as background, blocks out other music apps

### ISSUE THREAD

**Issue by skleest** [TheWidlarzGroup/react-native-video#200]
We're using muted video as a background in our app. On iOS, opening our app turns off other music apps. On Android, it is fine. Any work arounds?

**Comment by brentvatne** [comment]
https://github.com/brentvatne/react-native-video/issues/152

Can you add this to README? :)

**Comment by skleest** [comment]
Ah, my apologies for missing this. Just set a PR, thanks for the quick response @brentvatne.
