### ISSUE TITLE
Undefined is not an object (evaluating '_this.player.seek')

### ISSUE THREAD

**Issue by sami3898** [TheWidlarzGroup/react-native-video#2000]
# Bug
So i'm working with react-native-video and using ref to access seek method.
i'm calling it on Touchable Opacity's onPress.

=> Here is my code 
```
<TouchableOpacity
              disabled={this.state.isPlay}
              style={styles.playerCircle}
              onPress={() => {
                //this.player.props.
                this.player.seek(10)
                  this.setState({
                    isPlay: true,
                    isPause: false,
                    isStop: false,
                  })
                this.props.userStore.countClick();
              }}>
              <Image source={PLAY_ICON} style={styles.playerButtons} />
            </TouchableOpacity>
``` 

## Environment info
React native info output:

```bash
 System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz
    Memory: 2.60 GB / 7.91 GB
  Binaries:
    Node: 13.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  Languages:
    Java: 1.8.0_60
    Python: 3.7.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^4.4.5
![1589172596601](https://user-images.githubusercontent.com/32996863/81525043-030d1d00-9371-11ea-94e3-936dd172b310.JPEG)

**Comment by deepak-jha-kgp** [comment]
Please share your `Video ` component code, and make sure your touchable has access to `this`  either they should both be present in same render, or should have bind them

**Comment by sami3898** [comment]
> Please share your `Video ` component code, and make sure your touchable has access to `this` either they should both be present in same render, or should have bind them

Here is my Video Component Code
`if (
      this.state.songURL != '' &&
      this.state.isPause == false &&
      this.state.defaultSong != ''
    ) {
      AudioPlayer = (
        <View>
        <Viedo
          //source={this.state.songURL != '' ? {uri: 'file://'+this.state.songURL} : this.defaultSong()}
          ref={ref => {
            this.player = ref;
          }}
          source={
            this.state.songURL == null
              ? this.defaultSong()
              : {uri: 'file://' + this.state.songURL}
          }
          audioOnly={true}
          playInBackground={true}
          paused={this.state.isPause}
          onProgress={(time) => this.setState({currentTime: time.currentTime})}
          onEnd={() => {
            console.log('===== SONG END =====')
            renderRepeat = renderRepeat + 1;
            if(renderRepeat >= this.state.repeat){
              console.log(' ====== PLAY TIME : ' + renderRepeat)
              this.setState({isPause: true,isPlay:false,isStop:false})
            } else {
              this.setState({isPause: true},() => this.setState({isPause: false}))
            }
          }}
        />
        </View>
      );
    }`

**Comment by jensellfors** [comment]
Please post this on StackOverflow, as it seems to be issues with how you use refs.

**Comment by metinvio** [comment]
you should define your ref like `const player = useRef(null)` and assign it in your video component like 
`<Video 
...
ref={ref => (player.current = ref)}
..
/>` 

don't forget to import:
`import React, {useRef} from 'react'`
