### ISSUE TITLE
is it really neccessary to add "androidx.appcompat:appcompat:1.0.0" if using jetifier?

### ISSUE THREAD

**Issue by JNUfeatherwit** [TheWidlarzGroup/react-native-video#2001]
## version
react-native:0.62
react-native-video:5.0.2
## problem
If I remove "androidx.appcompat:appcompat:1.0.0"  from android/app/build.gradle  ,the project is also compiled successfully

**Comment by andrekovac** [comment]
@JNUfeatherwit What is your result? Did you eventually remove it?
