### ISSUE TITLE
online video upload problem (AVFoundationErrorDomain)

### ISSUE THREAD

**Issue by rintsyman** [TheWidlarzGroup/react-native-video#2002]
Hi, I used react native video with this url (https://oneplay.dev.arkeup.com/uploads/3624702a-c107-40da-8096-121ce564307d.mov)
 react-native-video always switches to onError with this error 
-code: -11850
-domain: "AVFoundationErrorDomain"
-target: 3635
I would like to know the cause of this error, does our server have a problem or is there a config to do on my project?
![Capture d’écran 2020-05-13 à 13 26 02](https://user-images.githubusercontent.com/22023617/81801588-558b3c80-951d-11ea-8843-9bd79c2bcebe.png)

**Comment by jensellfors** [comment]
Maybe you had SSL cert issues? I just tried it and it worked fine.

![image](https://user-images.githubusercontent.com/1150467/82055384-b0a96480-96c0-11ea-8303-910c3aa5361e.png)

**Comment by rintsyman** [comment]
To help someone 
This is the server response problem, react native video makes the error when the server response is status 200. 
I had to modify my server's response with proxy_force_ranges on
React native video makes AVFoundationErrorDomain error if the status is 200 and we have to force our server to return 206

**Comment by jensellfors** [comment]
Thanks for clarifying that @rintsyman! This is an issue with iOS's AVPlayer, not react-native-video. Good to know though! 👍

**Comment by chj-damon** [comment]
@rintsyman @jenshandersson ok now we know it's an issue with AVPlayer, how can we solve this problem? I can confirm that my server returns 206, but it still doesn't work.

**Comment by BadtzMaru** [comment]
I tried return status 206. But it dosen't work as well.
