### ISSUE TITLE
Does audioOnly mode reduce network data?

### ISSUE THREAD

**Issue by tnluan** [TheWidlarzGroup/react-native-video#2003]
I wonder if audioOnly mode only retrieves audio channel of the network file.
I assume if mp4 file volume is 10MB, then it only takes network 3-4MB when running with audioOnly mode.

Could you please consult this?

**Comment by jensellfors** [comment]
Looking at the code it does not. It simply tells the js code to keep the poster. Will look at updating the docs for this
