### ISSUE TITLE
IOS controls, play / pause buttons callback

### ISSUE THREAD

**Issue by AndriyShpyra** [TheWidlarzGroup/react-native-video#2006]
Is there a way to know when the 'Play' or 'Pause' button has been pressed on IOS video controls?

We need to implement such flow:
disable autoplay (now we set 'paused' property  to true ), 
But when the play button has been pressed, the  'paused' property should be changed to false

The actual result, when the play button has been pressed, the video remains in the paused state

**Comment by jensellfors** [comment]
This is what you need I think: https://github.com/react-native-community/react-native-video#onplaybackratechange

**Comment by AndriyShpyra** [comment]
@jenshandersson  thanks!
