### ISSUE TITLE
Muted doesn't work

### ISSUE THREAD

**Issue by arochedy** [TheWidlarzGroup/react-native-video#2008]
# Bug

I tried to use muted={true} on a video and I still have sound of the video on Android
## Platform

Which player are you experiencing the problem on:

* Android ExoPlayer
* Android MediaPlayer

I don't know if I have ExoPlayer or no (I don't think so beacuse fullscreen doesn't work too)

## Environment info

React native info output:

 react: 16.9.0 => 16.9.0 
 react-native: 0.61.5 => 0.61.5

Library version: 4.4.5

## Expected behaviour

1. No sound on the video

## Reproducible sample code

    <Video source={PrezVideo}   // Can be a URL or a local file.
    ref={(ref) => {
    this.playerAndroid = ref
    }}
    paused={false}
    muted={true}
    // onEnd={() => this.onEndAndroid()}                                // Store reference
    // onBuffer={this.onBuffer}                // Callback when remote video is buffering
    onError={(e) => this.videoError(e)} // Callback when video cannot be loaded
    resizeMode="contain"
    repeat={true}
    // fullscreen={true}
    style={this.getVideoStyle()}
    />

**Comment by jensellfors** [comment]
Closing as fixed in this PR https://github.com/react-native-community/react-native-video/pull/1699
