### ISSUE TITLE
onLoad event firing issue

### ISSUE THREAD

**Issue by yahacom** [TheWidlarzGroup/react-native-video#2009]
# Bug
The onLoad event fires immediately after the onLoadStart event, while the video is still in the process of loading. The problem is relevant for the iOS platform. Tested on iOS 13.4.1 and 13.3.1 (iPhone 6, 10).
On Android, everything works as expected: the onLoadStart event fires -> the video loads -> the onLoad event fires.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 24.39 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 5.0.2, also 4.4.5

## Steps To Reproduce

1. Pass some callbacks to onLoadStart and onLoad props
2. When video start loading the event onLoadStart fired
3. After this immediately onLoad event fired, when loading process not finished

## Expected behaviour

1. onLoadStart event fired when video start loading
2. video loading
3. onLoad event fired when video is loaded

## Reproducible sample code

```js
<Video
          source={{
            uri: fullVideoUrl,
          }}
          volume={1.0}
          muted={true}
          paused={videoPause}
          repeat={true}
          playInBackground={false}
          playWhenInactive={false}
          onLoadStart={() => {
            console.log('onLoadStart', new Date());
          }}
          onLoad={() => {
            console.log('onLoad', new Date());
          }}
        />
```

**Comment by jensellfors** [comment]
You might be interested in this event instead: https://github.com/react-native-community/react-native-video#onreadyfordisplay. We are just implementing callbacks of AVPlayer for iOS
