### ISSUE TITLE
NSURLErrorDomain "code": -1013

### ISSUE THREAD

**Issue by jellohouse** [TheWidlarzGroup/react-native-video#2011]
I'm getting an error like this, but I'm not to sure what might be causing it:

`{"error": {"code": -1013, "domain": "NSURLErrorDomain"}, "target": 1323}`

Here is a snippet of my code

```
<Video
   source={{
     uri: videoUrl,
     method: 'GET',
     headers: {
       'X-Auth-Token': this.state.token,
     },
   }}
   ref={(player) => {
     this.player = player;
   }}
   onError={(err) => this.videoError(err)}
.... />
```
The video plays well if I replace source to local file...
And works also when I tested with this https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

So maybe it has something to do with fetching the video... I pass on an authorization token by headers.
But this exact code used to work no problem when I was running my project on RN 0.55 and react-native-video 3.x, so I'm not sure.

I recently updated my project with versions below

Has anyone had a similar experience?

-----------
RN 0.62
react-native-video 4.4.5
iOS sdk 12.2

**Comment by jensellfors** [comment]
You need to uncomment in RCTVideo.m like the docs say https://github.com/react-native-community/react-native-video#headers

**Comment by zoultrex** [comment]
> You need to uncomment in RCTVideo.m like the docs say https://github.com/react-native-community/react-native-video#headers

Hi @jenshandersson, maybe that documentation changed, but I cannot find anything related to a RTCVideo.m file on that link. 

Do you have another example about it to show?

**Comment by alexhernandez** [comment]
> You need to uncomment in RCTVideo.m like the docs say https://github.com/react-native-community/react-native-video#headers

@jenshandersson Do you have an example? I also seem to be getting this issue
