### ISSUE TITLE
Headers supported for iOS 

### ISSUE THREAD

**Issue by ThomasCarca** [TheWidlarzGroup/react-native-video#2012]
# Feature Request

Hello, My team has been using your library for different features and it is very useful to us, thank you !

We've recently come across the necessity to fetch a video with Authorization headers containing an authentication token and realized this was [once possible](https://github.com/react-native-community/react-native-video/pull/805) for both android and iOS using the headers props but is [no longer supported now](https://github.com/react-native-community/react-native-video/pull/1092). 
The reason, as I understood, is the used API is private and it could cause the app to be rejected upon submission to the store. (see [this issue](https://github.com/react-native-community/react-native-video/issues/1091))

## Why it is needed

My team and I would very much like this feature implemented or any hint on a workaround in the meantime as it delivers a lot of value for our product.

## Possible implementation

We have, unfortunately no idea whatsoever on a possible implementation.

Thank you for your time !

**Comment by jensellfors** [comment]
I feel we should add back `AVURLAssetHTTPHeaderFieldsKey` as this is not a private function and thus shouldn't lead to rejection. Expo are using this in their code as well. We've been setting `AVURLAssetHTTPHeaderFieldsKey` in our app and not got rejected. I will raise a PR for it.

https://github.com/expo/expo/blob/ee5af9cb39695818cd0bd860e083c08ad5bd3532/packages/expo-av/ios/EXAV/EXAVPlayerData.m#L116
