### ISSUE TITLE
Continues log in the iPhone Pro 13.3.

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [TheWidlarzGroup/react-native-video#2016]
Hi,

I have use the library to video play. and have continues log on the simulator. 

nw_endpoint_flow_copy_multipath_subflow_counts Called on non-Multipath connection 

After long time app crash.

**Comment by jensellfors** [comment]
Seems to be an issue with Simulator https://stackoverflow.com/questions/58431840/using-an-avplayer-returns-a-non-multipath-connection-error
