### ISSUE TITLE
Video does not play if device not connected to PC

### ISSUE THREAD

**Issue by MIPB** [TheWidlarzGroup/react-native-video#2018]
# Bug

I am running the latest version of react-native-video.

Everything works correctly when I am testing the app in my device connected by USB and metro server is running.
But when the device is disconnected, the video does not play.

The video is in the local assets folder --> assets/videos/video.mp4

I tried react native link but still no video shown if device is disconnected.

Does anyone know if this is a known issue? 

Thanks

**Comment by UberMC** [comment]
Same

**Comment by DigohD** [comment]
This seems to still be an issue. As long as the device has a connection to the development server the video works. Unplugging the cable and restarting application causes the video to not render anymore.

EDIT: Built a release .apk and installed on the phone. Now it works. Perhaps React Native streams video files from the development computer for performance reasons?
