### ISSUE TITLE
No player controls

### ISSUE THREAD

**Issue by hassankhan** [TheWidlarzGroup/react-native-video#202]
Hi, apologies if this is a stupid question, but I can't seem to get any controls to show up. I've tried running the example project as well with no luck.

Any help would be appreciated, thanks!

**Comment by corbt** [comment]
I've also noticed that the iOS native controls don't work well on the current `master` branch. Using 0.7.1 in my project and controls work fine in that version, not sure where it broke.

**Comment by hassankhan** [comment]
If I manually change the default from `NO` to `YES` in `RCTVideo.m` I can get them to show up, it seems as if the property isn't being passed correctly.

**Comment by dwaligora** [comment]
@hassankhan if you will use `0.8.0-beta` you should be able to display the controls by setting `fullscreen` on component and `presentFullscreenPlayer` (let me know if I am wrong but I guess that should help).

**Comment by cubbuk** [comment]
Is `presentFullscreenPlayer` also available to Android? I couldn't manage to work it my own project.

**Comment by sjchmiela** [comment]
No, it isn't.

**Comment by yonatanmn** [comment]
so what's the purpose of `fullscreen` prop now? 
and what can I do to have android similar full screen+controls

**Comment by hassankhan** [comment]
Wicked, thanks @dwaligora

**Comment by yagottahavehart** [comment]
Bump  @yonatanmn's question. Is there a workaround for android fullscreen w/ controls?

**Comment by mattapperson** [comment]
Fixed now -> https://github.com/react-native-community/react-native-video/pull/270
