### ISSUE TITLE
Can't run video m3u8 local device in ios

### ISSUE THREAD

**Issue by KhanhDuy-123** [TheWidlarzGroup/react-native-video#2020]
error: {…}, target: 1417}
error:
code: -1100
domain: "NSURLErrorDomain"
__proto__: Object
target: 1417
__proto__: Object

Please help me

**Comment by Flouwrian** [comment]
i also have this error while trying to read a file with react native video from anywhere.
i try to load: source={{uri: '/var/mobile/Containers/Data/Application/0721E93F-F31E-4121-88F1-4C0ED6E696A6/Library/Caches/notify_download_200326_MPr_Statement_Corona_Notify.mp4'} 
and get {"error":{"domain":"NSURLErrorDomain","code":-1100},"target":1673} 

i also tried to put the file into the documents folder, with the same error.
