### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by carl0804** [TheWidlarzGroup/react-native-video#2021]
Android Exoplayer is not working. Screen is blank. But IOS is OK.

   ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }

  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-video": "^5.0.2"
  },

**android/settings.gradle:**

include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

**android/app/build.gradle**

dependencies {
   ...
    compile project(':react-native-video')
    implementation "androidx.appcompat:appcompat:1.0.0"
}

**android/gradle.properties**
android.useAndroidX=true
android.enableJetifier=true

**MainApplication.java**
```
add -> import com.brentvatne.react.ReactVideoPackage;

@Override
 protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          packages.add(new ReactVideoPackage());
          return packages;
 }
```

I tried **react-native link react-native-video** and manually link, but both are not working.
Just blank with no error.

**Comment by RenovJ** [comment]
Same here. Just blank on released version on Android device. while displayed well on virtual Android device.

**Comment by UberMC** [comment]
yeah works fine in debug but blank on production version

**Comment by andrekovac** [comment]
This also happens to me.

@carl0804 , @avinashlng1080 , @RenovJ , @UberMC 

- Are you also working with an ejected Expo project?
- I'm also using another package in my project which also uses the Exoplayer (https://github.com/react-native-kit/react-native-track-player) Are you as well?
- Did anyone of you find a solution in the meantime? - perhaps even another package?

I got it working by using the Android MediaPlayer based player instead of Exoplayer. The player doesn't seem super stable but works at least. Would like to switch to the new ExoPlayer if possible.

**Comment by UberMC** [comment]
The solution for me was the video was http not https.
So switch video to https or reconfigure android to allow http.(not secure)

AndroidManifest.xml
<application
      android:usesCleartextTraffic="true"

**Comment by andrekovac** [comment]
@UberMC Interesting. In my case it is indeed `https`. But that hints that the error might be related to the shape of the url. My url has some attributes coming after the file extension. Perhaps that influences it.. in fact it has the following form: `https://firebasestorage.googleapis.com/v0/b/foo.mp4?alt=media&token=abc123`

**Comment by UberMC** [comment]
Well your video isn't playable from a browser either

**Comment by andrekovac** [comment]
@UberMC The Video does play in the browser. I didn't want to write the original token here and changed the url. `abc123` is not the real token.

**Comment by RenovJ** [comment]
The solution worked for me as well!
Video file indicated as http url is not playable on my physical android
device.

2020년 6월 26일 (금) 오전 2:33, Trent <notifications@github.com>님이 작성:

**Comment by ZhminkoRoman** [comment]
If you use http protocol of video, please, add android:usesCleartextTraffic="true" to your AndroidManifest.xml
