### ISSUE TITLE
[iOS] Local subtitle not playing with local video

### ISSUE THREAD

**Issue by PauloMello99** [TheWidlarzGroup/react-native-video#2023]
# Bug

When playing a local video (.mp4), it normally runs, but when I select a texttrack that is a local subtitlte (.vtt), the subtitle do not shows up

## Platform
iOS

Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 157.35 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: ^4.4.5

## Steps To Reproduce

1. Download a subtitle_en.vtt
2. Download a video.mp4
3. Setup the texttrack and video source

## Expected behaviour

1. Local subtitle be normally displayed

**Comment by PauloMello99** [comment]
I do not know why, but it happens only when you are on development mode on react native, when you build up the application for production, it shows normally the subtitle as expected.

**Comment by taschik** [comment]
@PauloMello99 did you find a solution to your issue?
