### ISSUE TITLE
hls audioOnly option doesn't work

### ISSUE THREAD

**Issue by mtalhagaoglu** [TheWidlarzGroup/react-native-video#2024]
# Bug

when streaming hls files, making audioOnly true doesn't change anything, showing video everytime

## Platform
i can only test for android exoplayer now

Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by ApWin** [comment]
The same problem !!!

**Comment by mtalhagaoglu** [comment]
if you set style {width: 0,length: 0}, video will not shown. but you will loose ability to set poster. you need to add poster image manually. i used that way but it's not a real solution

**Comment by katiachumakova** [comment]
anything new on this?

**Comment by lcevasco-antorcha** [comment]
> if you set style {width: 0,length: 0}, video will not shown. but you will loose ability to set poster. you need to add poster image manually. i used that way but it's not a real solution

You also will lose the controls right? there is another solution to this?
