### ISSUE TITLE
Audio plays in iOS but not in Android for Expo React Native app

### ISSUE THREAD

**Issue by vaibhavverma9** [TheWidlarzGroup/react-native-video#2025]
# Audio plays in iOS but not in Android for Expo React Native app

Hi everyone, I have come across a video based bug on Expo. I'm not sure if this is the right place to submit, but I haven't received much help from the Expo forums these past few days, so I thought I'd try here. 

I am playing a video in my Expo / React Native app. The video works perfectly on both iOS and Android. However, the audio does not play on Android. (Note, he video's audio works perfectly on iOS.)

I'm using Expo SDK 37. 

Here is my video functional component:

```
import React, { useEffect, useRef } from 'react'; 
import { Video, Audio } from 'expo-av';   

export default function SingleVideo(props) {

    useEffect(() => {
        Audio.setAudioModeAsync({
            playsInSilentModeIOS: true
        }); 
    }, [])

    return (
        <Video
            source={{uri: props.source}}
            rate={1.0}
            volume={1.0}
            isMuted={false}
            resizeMode="cover"
            usePoster={true}
            shouldPlay={props.shouldPlay}
            progressUpdateIntervalMillis={50}
            isLooping
            style={{ width: '100%', height: '100%'}}
        >
        </Video>
    )
}
```

## Platform
I am specifically testing this on Android Expo client. However, this bug exists in all Android devices on standalone apps too. 

## Environment info

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 65.44 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
  npmGlobalPackages:
    *react-native*: Not Found

## Video sample
Here is a video that can be streamed: https://stream.mux.com/2SNz7Mg5ff00ACBazeXhEd81TNKmyOyPMO8mUa29yJUY.m3u8

(Again, note that the video is streaming perfectly. The audio on iOS works perfectly. However, the audio on Android does not work at all).

**Comment by jensellfors** [comment]
This is the wrong project, you need to go to Expo: https://github.com/expo/expo/
