### ISSUE TITLE
How to handle network failure and no internet condition.

### ISSUE THREAD

**Issue by amitiwary999** [TheWidlarzGroup/react-native-video#2026]
# Bug

I am loading video from url. How can we handle no internet connection? If there is no internet, I want to show some loader and I am already using minLoadRetryCount, so if there is an error I want to show retry button and when user click on retry button, then start loading vide from starting point(I tried to seek(0) but it's not working) 

## Platform

  Android and ios

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 3.25 GB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      Android NDK: 20.1.5948944

```

Library version: 4.4.4

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by jensellfors** [comment]
You should be able to use the onError callback for errors

**Comment by Joao360** [comment]
Just tested onError callback and for network errors it only works for Android.

For iOS I had to use onBuffer callback and give it a timeout when it's buffering to declare the network failed (not the optimal solution).

```
onBuffer = ({ isBuffering }) => {
    if (isBuffering) {
      if (Platform.OS === 'ios') {
        clearTimeout(this.bufferTimeout)
        this.bufferTimeout = setTimeout(
          () => this.showNetworkErrorPopup('Buffering timed out'),
          3000
        )
      }
    } else {
      if (Platform.OS === 'ios') clearTimeout(this.bufferTimeout)
    }
  }
```

I'm using "react-native-video": "^5.0.2",

**Comment by Joao360** [comment]
Just found out this solution is not 100% viable due to #1975
