### ISSUE TITLE
why not support macOS

### ISSUE THREAD

**Issue by ltovem** [TheWidlarzGroup/react-native-video#2027]
I want it can use in macOS

**Comment by Riveascore** [comment]
Same, video is a pretty basic requirement to satisfy.

**Comment by Riveascore** [comment]
The error I'm seeing most frequently is:

```sh
Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager
```

**Comment by Riveascore** [comment]
### Other users who also want this feature

- https://github.com/rknell
- https://github.com/elcssmouhsine
- https://github.com/eveningkid
- https://github.com/CatsNipYummy
- https://github.com/sheshnathiicmr
