### ISSUE TITLE
android          this.player.seek

### ISSUE THREAD

**Issue by Miluaaa** [TheWidlarzGroup/react-native-video#2030]
error while updating property 'seek' of a view managed by:RCTVideo

java.lang.string  cannot be cast to java.lang.double

**Comment by faizplus** [comment]
@Miluaaa did you get the solution?

**Comment by ghost** [comment]
@Miluaaa @faizplus Did you find the solution? I have the same issue.

**Comment by freeboub** [comment]
@faizplus give a number instead of a string to seek function
