### ISSUE TITLE
How to add custom control bar or customize control bar???

### ISSUE THREAD

**Issue by Arjun-aks** [TheWidlarzGroup/react-native-video#2033]

**Comment by TechAsif** [comment]
please flow the blog post  I hope You will be satisfied

https://medium.com/prototyped/react-native-video-handling-fullscreen-and-controls-on-android-dbb45a2e52ea

**Comment by infinitbility** [comment]
Check below documentation to create custom controls

https://infinitbility.com/react-native-video-example-with-custom-control
