### ISSUE TITLE
IOS playInBackground not working 

### ISSUE THREAD

**Issue by bittu1028** [TheWidlarzGroup/react-native-video#2036]
```
<Video
    source={{uri: videoUrl}} // Can be a URL or a local file.
    ref={(ref) => {
        this.player = ref;
    }} // Store reference
    playInBackground={true}
    playWhenInactive={true}
    onError={this.videoError} // Callback when video cannot be loaded
    resizeMode="cover"
    ignoreSilentSwitch="ignore"
    controls
    muted={false}
    repeat={false}
    paused
    volume={1.0}
    rate={1.0}
    style={{
        height: !keyboardOpenedState ? 200 : 0,
        width:viewportWidth,
        backgroundColor: 'black',
        position: 'absolute',
        top:0,
        left:0,
        right:0,
        bottom:0,
    }}
/>
```

**Comment by bittu1028** [comment]
@jenshandersson  why this issue is closed ?

**Comment by jensellfors** [comment]
This is not an issue with the lib. Have you added background audio to the plist as described here: https://github.com/react-native-community/react-native-video#playinbackground?

**Comment by bittu1028** [comment]
<img width="580" alt="Screen Shot 2020-06-11 at 7 18 19 PM" src="https://user-images.githubusercontent.com/8937295/84391165-52689680-ac18-11ea-8f36-e39e9755af7d.png">
 
@jenshandersson  I have followed every instruction of the documentation still i am not able to play in background mode

**Comment by jensellfors** [comment]
Ah you have set `paused` prop, you can't do that and use controls. Try unsetting paused.

**Comment by bittu1028** [comment]
@jenshandersson  unsetting the paused does not resolve the problem I am still unable to play on background mode or when casting with airplay

**Comment by jensellfors** [comment]
Haven't seen this issue before. Try debugging RCTVideo.m and see what happens. Works fine here. Have you rebuilt after setting background capabilities?

**Comment by bittu1028** [comment]
@jenshandersson  it seems there was some cache issue after I unset the paused prop it seems to be working now thanks

**Comment by jensellfors** [comment]
👍

**Comment by jensellfors** [comment]
@bittu1028 we would need a way to control the autoplay behavior, I created a proposal for it: https://github.com/react-native-community/react-native-video/issues/2048

**Comment by lulirl** [comment]
I am unable to play on background mode in IOS. Do you know what is that I am missing? 

 <Video
        ref={videoRef}
        style={[styles.videoPlayer]}
        source={{ uri: video || '' }}
        resizeMode="contain"
        useNativeControls={true}
        // @ts-ignore
        onPlaybackStatusUpdate={setVideoStatus}
        shouldPlay={isStreaming}
        usePoster={!isStreaming}
        volume={1.0}
        rate={1.0}
        muted={false}
        ignoreSilentSwitch={'ignore'}
        playWhenInactive={true}
        playInBackground={true}
        {...(!isStreaming && { posterSource: { uri: banner, posterStyle: { resizeMode: 'contain' } } })}
      />

<img width="633" alt="Screen Shot 2022-05-03 at 17 31 27" src="https://user-images.githubusercontent.com/87732012/166561105-330765b7-1f49-40fc-9379-2fb7929fc45f.png">

<img width="535" alt="Screen Shot 2022-05-03 at 17 31 53" src="https://user-images.githubusercontent.com/87732012/166561141-a898cfc6-9fc0-4672-8c61-e36984760e53.png">

**Comment by AlbertoMeQ** [comment]
@lulirl Any update? I have the same exact issue!
