### ISSUE TITLE
mixWithOthers doesnt't do anything

### ISSUE THREAD

**Issue by mtalhagaoglu** [TheWidlarzGroup/react-native-video#2037]
Hi. I'm trying to stream two video. One of from youtube-iframe and other in react-native-video. youtube and video have to play at the same time. I was using react-native-track-player and it has amazing AVAudioSession settings, i was using audioMixing on there but react-native-video doesn't have that. I am trying to use audioMixing but it doesn't do anything because in library files it didn't defined.

**Comment by arkist** [comment]
It's not yet available. officially, 5.1.0-alpha6 is still WIP.
the version that `5.1.0-alpha6` which is on npm is registered 5 months ago and it does not include this option.

You can try patch b4582c6 via https://github.com/ds300/patch-package
