### ISSUE TITLE
How can i control in change play sound in the background - ios?

### ISSUE THREAD

**Issue by anastely** [TheWidlarzGroup/react-native-video#2038]
# Bug
I'm work in react native music app, 
I use `react-native-video` in this case to play songs,
and in `playInBackground` prop i change it conditionally based on user status subscription, 
If this user bought a full package, I change it to true that's mean play songs in the background if false don't play it in the background.

But the problem with iOS app it when i want to enable Audio in the background should i add this to info.Plist

    <key>UIBackgroundModes</key>
    	<array>
    		<string>audio</string>
    	</array>

So in my case, every user can play a song in the background!
So how can i handle it and control play song in the background based on user status?

Code Snippet:

     <Video
                ref={ref => {
                  this.player = ref;
                }}
                source={{
                  uri: this.props.songs[this.props.currentIndex].url,
                }}
                paused={this.props.isPause}
                playInBackground={this.props.isPaid} // refere to user subscribtion. "Paid = true / Unpaid = false"
                playWhenInactive={true}
                onLoad={this.onLoad}
                onProgress={this.onProgress.bind(this)}
                onEnd={this.onEnd}
                controls={false}
              />

## Platform
iOS

## Environment info
 OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 31.13 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-16 | Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
 
React native info output:

 npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Library version: 5.0.2

**Comment by jensellfors** [comment]
Try setting `playWhenInactive` to false or `this.props.isPaid`, looking into the code it looks like both need to be false in order to pause on going into background...
