### ISSUE TITLE
[iOS] No media sound when phone is in silent mode.

### ISSUE THREAD

**Issue by bcalik** [TheWidlarzGroup/react-native-video#204]
There is no video sound when the phone is in silent mode in iOS.
It should actually play media sounds even if it is in silent mode, as seen on instagram or any other app.

**Comment by dojiboy9** [comment]
Go into your `ios/AppDelegate.m` file and insert the line:

`[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];`

just before the end of the `didFinishLaunchingWithOptions` method. This should replace the similarly looking line you have there already. The issue is most likely that you have done `setCategory:AVAudioSessionCategoryAmbient` which will mute the sound in silent mode.

**Comment by mattapperson** [comment]
We should actually provide an API for this... @bcalik mind opening a feature request ticket?

**Comment by bcalik** [comment]
@mattapperson What do you mean by feature request ticket? Consider this issue as a feature request ticket by labelling it.

**Comment by mattapperson** [comment]
@bcalik I went ahead and created a ticket that outlines what is needed as more of a feature request to make it easier for a dev to just pick it up and run with it.
https://github.com/react-native-community/react-native-video/issues/310

**Comment by timwuhaotian** [comment]
> `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];`

Just add to that answer, we need to 

link the AVFoundation lib and then

#import <AVFoundation/AVFoundation.h> on the top of the AppDelegate.m

**Comment by kadikraman** [comment]
For anyone else stumbling on this from a Google/issue search - this is now built into the library. You can use [ignoreSilentSwitch](https://github.com/react-native-community/react-native-video/blob/8962720f56719b89840e7f3ac5924532937fa08f/README.md#ignoresilentswitch)

```js
<Video
  [---]
  ignoreSilentSwitch="ignore"
/>
```

**Comment by samibaris** [comment]
![image](https://github.com/react-native-video/react-native-video/assets/122496426/d8936931-5e76-436f-8284-0ab386459c9f)
doesnt work,
