### ISSUE TITLE
After onEnd called,seek back to play video or click play, onProgress not called again.

### ISSUE THREAD

**Issue by jiyunkeji** [TheWidlarzGroup/react-native-video#2040]
# Bug

After onEnd called,I seek back to play video or  or click paly, onProgress not called again.

## Platform

Which player are you experiencing the problem on:
* iOS
* Android 

## Environment info

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 273.43 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/yrx/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      Build Tools: 26.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_161 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

React native info output:

```bash
 // paste it here

<img width="587" alt="image" src="https://user-images.githubusercontent.com/50569560/84011373-95243780-a9a8-11ea-8f9d-18306d88d59f.png">

```

Library version: 0.62.2

## Steps To Reproduce

<img width="700" alt="image" src="https://user-images.githubusercontent.com/50569560/84010686-99038a00-a9a7-11ea-9c78-badb12608d1d.png">

## Expected behaviour

No matter I seek back or replay, after onEnd called, I need onProgress can be called.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by gbferreira** [comment]
Same problem. I'm using onEnd event to seek for begin.

```
onEnd={() => this.player.seek(0)}
```

**Comment by mendyEdri** [comment]
Same problem for me, reproduced only in Android devices.

**Comment by deepakkumar5396** [comment]
Same problem for me, any solution please ?

**Comment by tackanoway35** [comment]
Same problem on Android for me, any solution please ?
