### ISSUE TITLE
Can't play videos taken directly from iphone or android cameraroll on react-native-video? I get ' nil string parameter ' error on iOS

### ISSUE THREAD

**Issue by hamoody-omar** [TheWidlarzGroup/react-native-video#2041]
I don't seem to be able to play videos taken directly from iPhone or android cameraroll especially iPhone using the uri provided by the node. I can tell that the uris are all right because I can use them as images and see them on the cameraroll and select the video that I want but then I get nil string parameter error on ios. On android, it shows it as a picture but it doesn't play it. in fact, android doesn't play any local video using a relative or absolute path even with the file:// prefix. I am thinking that might be a permission error because I can play the videos I stored on AWS. If anyone knows how to grant permission for android I would so much appreciate it if you enlighten me. I can't seem to figure out the nil string parameter error. Any ideas? Thank you in advance.

<Video
       source={{uri: this.state.selectedVideo.node.image.uri}}
  />

"react-native": "0.62.2",
"react-native-video": "^4.4.5",

**Comment by ferbeab** [comment]
same issue here
"react-native": "0.63.0"
"react-native-video": "^4.4.5",

**Comment by ferbeab** [comment]
Solution from @chrispaynter at #1572 fixed it for me!
