### ISSUE TITLE
AVFoundationErrorDomain 11821

### ISSUE THREAD

**Issue by Daha62** [TheWidlarzGroup/react-native-video#2044]
# Bug

When I try to display video from url in mobile app, some of them doesn't play and comes up with error `{ code: -11821, domain: 'AVFoundationErrorDomain' }`

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 61.45 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 21, 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.0.2

**Comment by Bekys** [comment]
how to fix it?somebody know it ?

**Comment by chrisozgo99** [comment]
I am getting a similar issue on iOS: 
` {"error": {"code": -11800, "domain": "AVFoundationErrorDomain"}, "target": 1599}`
Trying to pull a video from AWS S3 server. Works when I reference a video that was uploaded with an iOS device, but does not work when I try to reference a video from an Android device. Only on iOS.

Any solution would be greatly appreciated!

**Comment by ljunb** [comment]
same issue

**Comment by meiqi1992** [comment]
+1 same issue

**Comment by AndresTIY** [comment]
+1 samesies

**Comment by Bekys** [comment]
some are ok, and some have this issue ;so its format may be not supported; you can convert the format of video to a right modern; i use HandBrake[https://handbrake.fr/](url);Hope useful!

**Comment by Daha62** [comment]
It was because of fullHD video, even Safari can't play such format
