### ISSUE TITLE
ReactVideoView does not clean up correctly

### ISSUE THREAD

**Issue by ocalvo** [TheWidlarzGroup/react-native-video#2045]
# Bug

ReactVideoView manages its own instance of MediaPlayer and calls SetMediaPlayer() to initialize MediaPlayerElement.
However, it never calls SetMediaPlayer(null) and does not call Close on the MediaPlayer instance. This makes a lingering active MediaPlayer instance that sometimes makes the entire app crash as Xaml cannot handle an active MediaPlayer while the Xaml Element is no longer in the Xaml tree.

## Platform

Which player are you experiencing the problem on:
* Windows UWP

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

This has been reported in the wild and is a heavy hitter for apps that use Media.

## Expected behaviour

No crash after Media have exited the tree.

## Reproducible sample code
N/A

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
N/A

**Comment by jensellfors** [comment]
Sounds like you know how to fix it ;) Mind submitting a PR?
