### ISSUE TITLE
Video positioning on Android

### ISSUE THREAD

**Issue by sadikyalcin** [TheWidlarzGroup/react-native-video#2046]
# Bug

Video not centred vertically & horizontally on Android. Regardless of using flex or absolute positioning. Same behaviour when rotating the orientation as well.

It works perfectly fine on iOS and version 4.4.5. You can replicate the problem on v5+.

## Platform
* Android ExoPlayer

## Environment info
`react-native: 0.61.5`
Android: 9 & 10
Library version: 5.0.0+

## Steps To Reproduce

1. Create a flex container and centre children
2. Put the video component inside.

## Expected behaviour

1. Video to be centred
2. Video to resize and be centred on orientation change.

## Reproducible sample code

    <SafeAreaView style={styles.container} forceInset={{top: 'always'}}>
        <StatusBar
            backgroundColor={themeVars.black}
            barStyle="light-content"
        />
        <View style={styles.videoWrapper}>
            <Video
                source={{uri: source.uri}}
                style={styles.video}
                controls={true}
            />
        </View>
    </SafeAreaView>

    const styles = StyleSheet.create({
        container: {
            width: '100%',
            height: '100%',
            backgroundColor: 'black',
        },
        videoWrapper: {
            flex: 1,
            justifyContent: 'center',
            alignContent: 'center',
            alignItems: 'center',
        },
        video: {
            width: '100%',
            height: '100%',
        },
    });

## Video sample

Version 4.4.5:

![ezgif-1-18c8e5820b0c](https://user-images.githubusercontent.com/8109619/84383202-bde44100-abe3-11ea-923b-c44c0ab19ad4.gif)

Version: 5.0.2

![ezgif-1-49c727cd4a1c](https://user-images.githubusercontent.com/8109619/84383581-714d3580-abe4-11ea-87e2-1ab6ef3baa71.gif)

Version: 5.0.2 on iOS

![ezgif-1-a816e817be34](https://user-images.githubusercontent.com/8109619/84383939-1f58df80-abe5-11ea-931f-45d844598d74.gif)

**Comment by jensellfors** [comment]
it looks like you're not using Exoplayer... The seeker bar is white with Exo, green with MediaPlayer. The video size is fine for me on latest master and Exoplayer

**Comment by sadikyalcin** [comment]
> it looks like you're not using Exoplayer... The seeker bar is white with Exo, green with MediaPlayer. The video size is fine for me on latest master and Exoplayer

Forgive my ignorance but how do we define which player to use? Can't see anything in the docs...

**Comment by jensellfors** [comment]
Check under https://github.com/react-native-community/react-native-video#android-installation
Default is MediaPlayer, you need to update your settings.gradle. We are going to default to ExoPlayer in coming release.

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by sadikyalcin** [comment]
> Check under https://github.com/react-native-community/react-native-video#android-installation
> Default is MediaPlayer, you need to update your settings.gradle. We are going to default to ExoPlayer in coming release.
> 
> ```
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> ```

Perfect. Thanks for your help. I'll try it in a bit.

**Comment by jensellfors** [comment]
Ah it could have been due to the js fullscreen hack. I just merged this PR to master, can you try to replicate using the latest master version?

https://github.com/react-native-community/react-native-video/pull/2013

**Comment by sadikyalcin** [comment]
Good news; nope I can't. Cloned the repo and it's working perfectly fine now.

**Comment by jensellfors** [comment]
Woop woop 🙌

**Comment by vipycm** [comment]
add `resizeMode={"contain"}` work for me
