### ISSUE TITLE
picture in picture is not working

### ISSUE THREAD

**Issue by GilHogan** [TheWidlarzGroup/react-native-video#2049]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
    Memory: 7.35 GB / 20.93 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

### on ipad mini 2 version: 12.4.5
1. Enable automatic invocation of Picture in Picture in Settings > Home Screen & Dock > Multitasking > Picture in Picture.  [Refer](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_standard_player?language=objc)
2. Enable Background Audio on Xcode. [screenshot](https://drive.google.com/file/d/13M6ZpLLmgVToTZPXpwLSD_GrIEVDRiLe/viewg)
3. Set the pictureinpicture property to true
4. Open video to play （picture in picture not work）
5. video doesn't enter PiP mode when you press the Home button
### It's the same on the iPhone 7 version: 13.5.1

...

## Expected behaviour

1. Picture in Picture is working

## Reproducible sample code

```
import React, { Component } from 'react';
import {
  View,
} from 'react-native';
import { Button } from '@ant-design/react-native';
import Video from 'react-native-video';


class VideoTest extends Component {
  static navigationOptions = ({ navigation }) => ({
    header: null,
  });

  constructor (props) {
    super(props);

    this.state = {
      pictureInPicture: true
    };
  }

  render () {

    const { pictureInPicture } = this.state;

    return (
      <View style={{ paddingTop: 5, backgroundColor: 'white', flex: 1 }}>
        <Video source={{ uri: "..." }}   // Can be a URL or a local file.
          ref={(ref) => {
            this.player = ref
          }}
          pictureInPicture={pictureInPicture}
          playInBackground={true}
          controls={true}
          style={{ height: 220, width: '100%' }} />
        <Button
          onPress={() => {
            this.setState({ pictureInPicture: !pictureInPicture });
          }}>
          button
        </Button>
      </View>
    );
  }
}

export default VideoTest;

```

## Video sample
no

**Comment by GilHogan** [comment]
Can someone help me please

**Comment by GilHogan** [comment]
By calling [isPictureInPictureSupported](https://developer.apple.com/documentation/avkit/avpictureinpicturecontroller/1614693-ispictureinpicturesupported) method,I find that my device may not support picture-in-picture, and I find [ios14](https://www.apple.com/ios/ios-14-preview/features/)  has good support for picture-in-picture. Finally, I use [react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings) to make a floating window to achieve the same effect as picture-in-picture.

Sorry, my english is poor  : )

**Comment by illl48** [comment]
@guhuangjin 
Would like to know how you called isPictureInPictureSupported method? Appreciate!

**Comment by jadayash** [comment]
> By calling [isPictureInPictureSupported](https://developer.apple.com/documentation/avkit/avpictureinpicturecontroller/1614693-ispictureinpicturesupported) method,I find that my device may not support picture-in-picture, and I find [ios14](https://www.apple.com/ios/ios-14-preview/features/) has good support for picture-in-picture. Finally, I use [react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings) to make a floating window to achieve the same effect as picture-in-picture.
> 
> Sorry, my english is poor : )

Hello

Can you provide an example please?

Regards

**Comment by fukemy** [comment]
@HoganGolden [react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings) not working anymore
