### ISSUE TITLE
fullscreen prop not working on ios as per documentation

### ISSUE THREAD

**Issue by bittu1028** [TheWidlarzGroup/react-native-video#2051]
```
<Video
                source={..someurl} // Can be a URL or a local file.
                ref={(ref) => {
                    this.player = ref;
                }} // Store reference
                resizeMode="contain"
                ignoreSilentSwitch={'ignore'}
                controls
                fullscreen
                fullscreenAutorotate
                style={{
                    flex:1,
                    backgroundColor: 'black',
                }}
            />
```

I have above settings and the video is not presented on fullscreen on play

**Comment by softmastx** [comment]
Same here.

**Comment by ericlifs** [comment]
Same here, any news on this?

Thanks!

**Comment by JerakRus** [comment]
I am facing the same problem. Moreover, none of the callbacks and methods associated with fullscreen works.


I am not good at native code for iOS, but I tried to see what's wrong. It seems that the nativeProps `_fullscreen` which we pass is not used in any way and is not processed in RCTVideo.m
There is also an `applyModifiers` method that sets the repetition pause and other parameters, but not fullscreen. Hopefully my little research will help someone else find a solution for all of us.

@jenshandersson сould you give some official answer on this topic?

**Comment by zabojad** [comment]
Neither `fullscreen` nor `fullscreenAutorotate` nor `fullscreenOrientation` nor `controls` seems to work on iOS...

**Comment by ghost** [comment]
In addition `dismissFullscreenPlayer` doesn't seem to work at all on iOS. Does anybody have the same problem? It's interesting because `presentFullscreenPlayer` works as expected, but `dismissFullscreenPlayer` doesn't and both methods use `setNativeProps({ fullscreen: true/false });` and one works while other doesn't.

**Comment by Metroxe** [comment]
Any update on this?

**Comment by mariodev12** [comment]
anyone found a solution about this?
