### ISSUE TITLE
Get rid of 35 issues/warnings on iOS

### ISSUE THREAD

**Issue by Monte9** [TheWidlarzGroup/react-native-video#2052]
# Bug

When installing this library in our iOS app, we see 35 new warnings that are generated from this project. Curious if there is any motivation to clean this up and bring it down to zero?

I have an iOS background myself, so if the team is interested in this, I can submit a few PR's to remove the iOS warnings.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 510.97 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
```

Library version: 5.0.2

## Steps To Reproduce

1. Install `react-native-video` in an iOS project using auto-linking
2. Look at the warnings tab on Xcode.
3. You'll see there are around 35 deprecation warnings for this library on iOS

## Expected behavior

There should be no warnings

## Reproduction

<img width="377" alt="Screen Shot 2020-06-17 at 1 57 08 PM" src="https://user-images.githubusercontent.com/7840686/84875172-3c892480-b0a3-11ea-81eb-fe50974788cc.png">

**Comment by jensellfors** [comment]
Been wanting to refactor/clean up a lot in the iOS project but haven't gotten to it. Feel free to open a PR with some cleanup and I will merge! 🙌

**Comment by Monte9** [comment]
@jenshandersson for sure! I'll take a stab at it.

There are a couple ways we can go about it:
- I see that you have a PR that makes a lot of changes to this project structure: https://github.com/react-native-community/react-native-video/pull/2005
What's the ETA for getting that merged and released? Ideally, I'll be able to submit a PR once that into master so that changes are isolated.
- I can submit a PR to your existing fork/PR - @jenshandersson/newexample and it will be part of the big release above for PR 2005.

Let me know which one you prefer!

**Comment by Monte9** [comment]
@benoitdion thoughts?

**Comment by benoitdion** [comment]
@Monte9 I'd prefer a new PR if possible

**Comment by Monte9** [comment]
For sure, the last time I tried to run this project locally, I had a whole bunch of xcode errors during build. 

Is there a guide/contributing section on how I can run this project locally? Maybe worth adding to the Readme

**Comment by benoitdion** [comment]
Unfortunately, nothing up to date at this time :(.
