### ISSUE TITLE
Is it possible to share Video component between multiple screens?

### ISSUE THREAD

**Issue by wlukla** [TheWidlarzGroup/react-native-video#2056]
### Description
I have 3 screens all of which should show same player with same playback state, video file and progress. When navigating I have 3 players running with different state

### Expected behavior
I want to share same Video component between all of those 3 screens

**Comment by jfbn** [comment]
Did you come up with a solution for this @wlukla ?

**Comment by wlukla** [comment]
@jfbn hi!
Unfortunately, no. I used redux action on `onProgress` to store video player playback state and called `seekTo()` on each video player render

I hope that better solution exists 😉

**Comment by siddharthkr** [comment]
Any solution guys?
@wlukla @jfbn
