### ISSUE TITLE
Switching to headphones not working (on Android)

### ISSUE THREAD

**Issue by nxz91** [TheWidlarzGroup/react-native-video#2058]
# Bug

When plugging my cable headphones into the device, the volume changes but the audio is not routed to the headphones but still plays over speaker. Should be a fairly basic bug but I cannot find anything.

## Platform
- Android 

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 47.17 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.3.2 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 24, 26, 27, 28
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
```

Library version: 5.0.2

## Steps To Reproduce

Make a fresh install of RNVideo, run a video on it and plug in your headphones.

**Comment by Ashwin-Mothilal** [comment]
Have you tried this method? [onaudiobecomingnoisy](https://github.com/react-native-community/react-native-video#onaudiobecomingnoisy)
