### ISSUE TITLE
There's no video on iOS 14

### ISSUE THREAD

**Issue by legion-zver** [TheWidlarzGroup/react-native-video#2059]
# Bug

There's no video on iOS 14 Dev

## Platform
iOS
Which player are you experiencing the problem on:
iOS

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 746.20 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1 
    react: ~16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 4.4.5 and 5.0.2

**Comment by nbennink** [comment]
I experience the same problem. I can try to post a more detailed device log and code snippet later. Do you have a device running the iOS 14 beta? I found this issue on the Apple forum that might indicate that this is an issue with the simulator.
https://developer.apple.com/forums/thread/650741

EDIT: Can confirm that it appears to work in the iPadOS 14 beta for me on a real device.
