### ISSUE TITLE
Flicker/Lag on rendering component.

### ISSUE THREAD

**Issue by gravitinos** [TheWidlarzGroup/react-native-video#206]
On Android, the video component flickers (shows the background) before rendering because it takes time to render. It seems it's taking ~250ms to load the video component, and ~250ms to load the asset (rendering the same video twice resolves in ~250ms instead of the total ~500ms).

I'm wondering if there is/can be a way we can preload an asset so the user doesn't have to wait for the asset to load. Anything we can look into to get the component to load quickly and consistently?

**Comment by mangogogos** [comment]
Did you ever come up with a workaround for this?

**Comment by gravitinos** [comment]
@mangogogos I ended up changing my implementation. It was a difficult workaround, but I ended up modifying react-native-router-flux using tabbed routes, then rendering the video, THEN showing the video component once it's done loading. Although I couldn't get the videos to load at a consistent time.

**Comment by mangogogos** [comment]
Glad you found something that kind of works for you! Too bad you couldn't find a more elegant solution but oh well. I am also changing my implementation to avoid state changes that cause flickering

**Comment by gravitinos** [comment]
Let me know how it goes! Image has a prefetch function, it'd be nice if we could have a prefetch/preload function here.

**Comment by mattapperson** [comment]
@xvalentino could you expound on that in a new/edited ticket that I could flag as an enhancement request?

**Comment by mattapperson** [comment]
ill re-open if you decide to edit

**Comment by nikhilgoswami** [comment]
I am using  ImageBackground component on a login form and changing any state of form field or when the from receives props the image flickers, at first I thought it might be due to me using high resolution image but changing resolution did not solve the issue.

**Comment by fchenchen** [comment]
Just in case someone has similar issue, onReadyForDisplay should solve this.
