### ISSUE TITLE
Subtitles not working for me (android & ios)

### ISSUE THREAD

**Issue by Shabnam-Veranloo** [TheWidlarzGroup/react-native-video#2061]
# Bug
Subtitles not working for me (android & ios)

react-native @0.62.2
react-native-video @4.4.5

`
                <Video source={{uri:LINK}}   // Can be a URL or a local file.
                ref={refVideo}            
                onLoad={onLoad}
                // onSeek={onSeek}
                onProgress={onProgress}
                resizeMode={'cover'}
                paused={pause}
                selectedTextTrack={{
                    type: 'title',
                    value: 'English',
                }}
                textTracks={[
                    {
                        title: 'English',
                        language: 'es',
                        type: TextTrackType.VTT,
                        uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
                    },
                ]}
            />
`

**Comment by ghost** [comment]
For me subtitles are working on react-native@0.61.5. They stopped working on Android after upgrade to 0.62.2. Maybe downgrading to 0.61.5 (if it is possible in your case) would be a temporary fix for you.

**Comment by jesspinklet** [comment]
is this fixed on 0.64?
