### ISSUE TITLE
buffer next video when one video is playing currently   ?

### ISSUE THREAD

**Issue by waqaramjad** [TheWidlarzGroup/react-native-video#2063]
I have multiple lists of videos that are playing one by one I want to buffer next video while one video is playing so that we can minimize the buffer time, is it possible?

**Comment by nivas412** [comment]
Having the same issue.

**Comment by aliasad106** [comment]
@waqaramjad  You'll need to have a bigger window size if you're using a flat list or scrollview and have multiple instances of <Video> component.

**Comment by freeboub** [comment]
You can also add 2 <video with the second in pause, and swap the view when you want ...
