### ISSUE TITLE
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.

### ISSUE THREAD

**Issue by nagaraj8652** [TheWidlarzGroup/react-native-video#2065]
i am getting below error 

/Users/gl.dev/Desktop/Test Data/test1/node_modules/react-native-video/Video.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.

**Comment by Sumonil** [comment]
Same problem

**Comment by SpiritLing** [comment]
🆘 I also have this problem。

**Comment by adamelmohamad** [comment]
is this still not fixed?

**Comment by Bheemrav9014108066** [comment]
Hi, 
I am getting below error on adding linear gradient 

 web  Compiled with warnings.
A:/Projects/client/mobile/native/vendore/node_modules/react-native-linear-gradient/common.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.

Do anyone got fix

**Comment by kamal-mobile-dev** [comment]
Hii,
I am getting error on adding react-native-fast-image
./node_modules/react-native-fast-image/dist/react-native-fast-image.esm.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

Please help.

**Comment by DavidVargas1213** [comment]
is this still not fixed?

**Comment by t1gu1** [comment]
That bug only seems to append with expo commands.
That doesn't append when I use `react-native run-ios` or `react-native run-android`.

That would be awesome if it works cause we can't use anything related to web.

**Comment by AlecWGreene** [comment]
I'm having the issue still, I've commented out every reference to the import, and it still breaks even if the only reference to the package is the import line. I've reinstalled everything using expo, no luck. This is the console output

```
 web  Compiled with warnings.
C:/Users/alecw/Code/Portfolio-React/alec-greene-portfolio/node_modules/react-native-video/Video.js  
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.

C:/Users/alecw/Code/Portfolio-React/alec-greene-portfolio/node_modules/react-native-video/Video.js  
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.
```

**Comment by adamelmohamad** [comment]
I am also getting the exact same error as Alec: Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.

**Comment by karim-coder** [comment]
same error

**Comment by Slim-Kasraoui** [comment]
I think this might solve the issue : 

Looks like its a bug that arises due to a mismatch in lib version & expo version. 
So make it a practice to install all the libs with expo instead of npm or yarn. 
To fix this bug install all your libraries using the cmd expo install <lib>

ex: expo install react-native-web

PS: I found this solution on stackoverflow (last answer by R.K)
https://stackoverflow.com/questions/60184592/how-to-fix-import-error-requirenativecomponent-from-react-native-web

**Comment by taj567** [comment]
./node_modules/react-native-fbsdk/lib/module/FBLoginButton.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

am facing the same issue after converting react-native o react-native-web.
