### ISSUE TITLE
4k movies are not playing

### ISSUE THREAD

**Issue by SandeepKharbanda** [TheWidlarzGroup/react-native-video#2074]
# Bug
I am not able to play 4K movies on my android tv project. I am getting an error `{"error":{"extra":-61,"what":1}}` while playing the video. So, could you please suggest to me what additional information should we need to add to play this video.

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:
"react-native-video": "4.4.5"
```bash
 // paste it here
```

Library version: 4.4.5

## Reproducible sample code

<Video
                source={{ uri: item.url }}
                paused={paused}
                ref={(ref) => {
                    this.player = ref
                }}
                volume={1.0}                                    // Store reference
                onBuffer={this.onBuffer}                // Callback when remote video is buffering
                onError={this.onError}               // Callback when video cannot be loaded
                onLoad={this.onLoad}
                onLoadStart={this.onLoadStart}
                bufferConfig={{
                    minBufferMs: 0,
                    maxBufferMs: this.maxBuffer,
                    bufferForPlaybackMs: this.maxBuffer,
                    bufferForPlaybackAfterRebufferMs: this.maxBuffer
                }}
                onProgress={this.onProgress}
                onBandwidthUpdate={this.onBandwidthUpdate}
                repeat={false}
                onEnd={this.onEnd}
                resizeMode={"contain"}
                style={{
                    position: 'absolute',
                    aspectRatio: SCREEN_WIDTH / SCREEN_HEIGHT,
                    width: "100%"
                }}
            />

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by SandeepKharbanda** [comment]
Any update on this?

**Comment by freddieerg** [comment]
You need to include a link to the video you're trying to play otherwise it's extremely hard to offer help. Have you definitely specified ExoPlayer over the default Android Media Player in your project?

**Comment by SandeepKharbanda** [comment]
@freddieerg I am trying to play this URL i.e http://tivix.eu:8000/movie/demo4/1SVHifcnbO/88814.mkv but I am getting an error while playing this URL

**Comment by Shashank2406** [comment]
> You need to include a link to the video you're trying to play otherwise it's extremely hard to offer help. Have you definitely specified ExoPlayer over the default Android Media Player in your project?

Tried with ExoPlayer doesn't work

**Comment by Shashank2406** [comment]
@freddieerg Any update?

**Comment by vladpuz** [comment]
+1

**Comment by samandarkuchkarov** [comment]
@freddieerg Any update?

**Comment by malnajdi** [comment]
is this solved ?
