### ISSUE TITLE
Error => {"extra": -2147483648, "what": 1}

### ISSUE THREAD

**Issue by rananajam1** [TheWidlarzGroup/react-native-video#2078]
# Bug
Error while playing videos from specific URLs. I get the following log for onError function:-
**{"error": {"extra": -2147483648, "what": 1}}**

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
* **Haven't tested on IOS yet**

## Environment info

React native info output:

```bash
 OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.06 GB / 15.88 GB
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

**Comment by rmaharba** [comment]
Same issue

**Comment by gauthamilango** [comment]
+1

**Comment by gauthamilango** [comment]
@rananajam1 @Darkiring I researched it a bit. These are the error codes from the Android Media player. https://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener

MEDIA_ERROR_SYSTEM (-2147483648) - low-level system error.

**Comment by rmaharba** [comment]
> @rananajam1 @Darkiring I researched it a bit. These are the error codes from the Android Media player. https://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener
> 
> MEDIA_ERROR_SYSTEM (-2147483648) - low-level system error.

I saw the solution in another issue, add something to the metro.config and it worked for me.

Although not 100%, I still notice errors with some videos.

**Comment by gauthamilango** [comment]
> > @rananajam1 @Darkiring I researched it a bit. These are the error codes from the Android Media player. https://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener
> > MEDIA_ERROR_SYSTEM (-2147483648) - low-level system error.
> 
> I saw the solution in another issue, add something to the metro.config and it worked for me.
> 
> Although not 100%, I still notice errors with some videos.

Okay, It will be really helpful if you can share it. 

And I was just trying to stream an mp3 file, It works fine for me while debugging. But when I make a release variant. It stop working for me and throws this error.

**Comment by rmaharba** [comment]
> > > @rananajam1 @Darkiring I researched it a bit. These are the error codes from the Android Media player. https://developer.android.com/reference/android/media/MediaPlayer.OnErrorListener
> > > MEDIA_ERROR_SYSTEM (-2147483648) - low-level system error.
> > 
> > I saw the solution in another issue, add something to the metro.config and it worked for me.
> > 
> > Although not 100%, I still notice errors with some videos.
> 
> Okay, It will be really helpful if you can share it. 
> 
> And I was just trying to stream an mp3 file, It works fine for me while debugging. But when I make a release variant. It stop working for me and throws this error.

Give a minute

**Comment by rmaharba** [comment]
@gauthamilango This is the solution: 
https://github.com/react-native-community/react-native-video/issues/1894#issuecomment-584832293

But how he did it didn't work for me. The same thing mentioned in the metro.config of the project. 

Like this: 
 
```
/**
* Metro configuration for React Native
* https://github.com/facebook/react-native
*
* @format
*/

 module.exports = {
   transformer: {
     getTransformOptions: async () => ({
       transform: {
         experimentalImportSupport: false,
         inlineRequires: false,
       },
     }),
   },
 dependencies: {
     'react-native-video': {
       platforms: {
         android: {
           sourceDir: './node_modules/react-native-video/android-exoplayer',
         },
       },
     },
   },
 };
```

**Comment by rmaharba** [comment]
I added this to the file: 

```
dependencies: {
     'react-native-video': {
       platforms: {
         android: {
           sourceDir: './node_modules/react-native-video/android-exoplayer',
         },
       },
     },
   },
```

**Comment by gauthamilango** [comment]
> I added this to the file:
> 
> ```
> dependencies: {
>      'react-native-video': {
>        platforms: {
>          android: {
>            sourceDir: './node_modules/react-native-video/android-exoplayer',
>          },
>        },
>      },
>    },
> ```

Thanks! But still its not working for me.

**Comment by rmaharba** [comment]
> > I added this to the file:
> > 
> > ```
> > dependencies: {
> >      'react-native-video': {
> >        platforms: {
> >          android: {
> >            sourceDir: './node_modules/react-native-video/android-exoplayer',
> >          },
> >        },
> >      },
> >    },
> > ```
> 
> Thanks! But still its not working for me.

Not problem!

**Comment by rmaharba** [comment]
> > I added this to the file:
> > 
> > ```
> > dependencies: {
> >      'react-native-video': {
> >        platforms: {
> >          android: {
> >            sourceDir: './node_modules/react-native-video/android-exoplayer',
> >          },
> >        },
> >      },
> >    },
> > ```
> 
> Thanks! But still its not working for me.

Do you check the another issue?

**Comment by gauthamilango** [comment]
I tried this https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-531736338 and then it threw unrecognised media format error. And then I used usesCleartextTraffic to make it work. Finally got it working.

**Comment by rananajam1** [comment]
> I tried this [#1747 (comment)](https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-531736338) and then it threw unrecognised media format error. And then I used usesCleartextTraffic to make it work. Finally got it working.

usesCleartextTraffic as a prop to the react-native-video component?

**Comment by gauthamilango** [comment]
> > I tried this [#1747 (comment)](https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-531736338) and then it threw unrecognised media format error. And then I used usesCleartextTraffic to make it work. Finally got it working.
> 
> usesCleartextTraffic as a prop to the react-native-video component?

No. Sorry for being blunt. That was supposed to go into AndroidManifest.xml in the application tag

Like this `android:usesCleartextTraffic="true"`

**Comment by rananajam1** [comment]
> I added this to the file:
> 
> ```
> dependencies: {
>      'react-native-video': {
>        platforms: {
>          android: {
>            sourceDir: './node_modules/react-native-video/android-exoplayer',
>          },
>        },
>      },
>    },
> ```

This worked for me <3

**Comment by rmaharba** [comment]
> I tried this https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-531736338 and then it threw unrecognised media format error. And then I used usesCleartextTraffic to make it work. Finally got it working.

I will try with this, thanks 👍🏻

**Comment by RobinBobin** [comment]
I solved it by modifying my `settings.gradle` as mentioned in the setup guide (Android installation):

include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

I didn't modify any other files.

"react-native": "0.63.3"
"react-native-video": "^5.1.0-alpha8"

**Comment by FacundoM1** [comment]
> I tried this [#1747 (comment)](https://github.com/react-native-video/react-native-video/issues/1747#issuecomment-531736338) and then it threw unrecognised media format error. And then I used usesCleartextTraffic to make it work. Finally got it working.

Worked for me!!

**Comment by brunolcarlos** [comment]
I have a similar error and they close my issue

https://github.com/expo/expo/issues/16403

**Comment by zenjedi** [comment]
I had `usesCleartextTraffic` already as true. It looks like Android Media Player doesn't like HTTP URI links. I am now able to see videos as long as they have HTTPS links.

**Comment by rubbishCoder** [comment]
try using a `https` url instead of `http`

**Comment by MinhQuyImobility** [comment]
> ct-native-video').projectDir =

This works for me !! Thank you.

**Comment by MinhQuyImobility** [comment]
> ct-native-video').projectDir =

This works for me !! Thank you.

**Comment by rohantneuro** [comment]
i try to add it in react-native congif it give me error 
 'react-native-video': {
        platforms: {
          android: {
            sourceDir: './node_modules/react-native-video/android-exoplayer',
          },
        },
      },
