### ISSUE TITLE
react-native-video package to play audio/video  from Blob data

### ISSUE THREAD

**Issue by chinthakaK** [TheWidlarzGroup/react-native-video#2079]
# Bug
I am using react-native-video package to play audio/video on my App.
I have some audio/video files saved in a DB as blob data.  But it fail to play them.
Is there a another way ?

var audioURL =  "data:audio/mp3;base64," + this.state.dataSource[i].contentData ; 
// This content data has whats comming from db
 <Video source={{uri:  audioURL  }}

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by YousefMohsen** [comment]
Did you find a solution to this?
