### ISSUE TITLE
Video inside ForeignObject (Component from svg) audio playing but video not showing

### ISSUE THREAD

**Issue by fouad1994** [TheWidlarzGroup/react-native-video#2081]
I tried to change Video component to Image component it works but video is not working

![image](https://user-images.githubusercontent.com/35866405/87226821-c80f8000-c3d9-11ea-93c8-f5a2899001e5.png)

**Comment by clemensmol** [comment]
@fouad1994 did you find a fix/workaround for this?

**Comment by cjmaret** [comment]
I have the exact same issue

**Comment by freeboub** [comment]
Seems to be relates to this issue: https://github.com/react-native-svg/react-native-svg/issues/1461
Looks liké a react-native-svg issue.

**Comment by freeboub** [comment]
Is it possible to provide a sample code please ? Code screenshot is not usable ...
