### ISSUE TITLE
version 5.0.2 does not parse tracks correctly (works with version 4.4.5)

### ISSUE THREAD

**Issue by cgranetgithub** [TheWidlarzGroup/react-native-video#2083]
# Bug

onLoad does not return tracks (audio/video/text) details.
selectedTextTrack parameter does not work (subtitles not effectively selected).

Here is an example of the 'onLoad' payload I receive:
{"canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 5170, "naturalSize": {"height": 540, "orientation": "landscape", "width": 960}}

You can see that audioTracks, textTracks and videoTracks are missing.

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
I have not tested on other platforms, might fail too.

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 2.33 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
```

Library version: 5.0.2

## Steps To Reproduce

Add a console print of the payload returned by onLoad

## Expected behaviour

Payload should include audioTracks, textTracks and videoTracks

## Video sample
https://d1v7aopt5pctsj.cloudfront.net/HLS-TopKnotchDetective/TKD_FEATURE_MASTER_2017_LCR_CINEMA_20171201_STEREO(Created+by+Vince).m3u8
https://d1v7aopt5pctsj.cloudfront.net/HLS-Chrieg/CHRIEG_11062015_TV_grading_prores4444_HD1080_24P_STEREO.m3u8

## IMPORTANT NOTE 

it works fine with library version 4.4.5 !

**Comment by edferreira** [comment]
I'm facing this same issue with onLoad. 
As a workaround I'm using an external m3u8 parser for now.

What's exactly the problem with selectedTextTracks? If you can paste your code I can try to help

**Comment by gurbela** [comment]
also 4.4.5 version not working  correctly

**Comment by crwecker** [comment]
We were having this same issue after upgrading our app to RN 0.60 to 0.63 and thought it was because we also upgraded react-native-video. Turns out that, for whatever reason our app had switched to using Android's mediaPlayer instead of the exoPlayer like it was before upgrading. ymmv.

**Comment by pedromarta** [comment]
@edferreira Would you be able to shed some light on what layer you implemented the external m3u8 parser workaround?
