### ISSUE TITLE
Audio not playing on iOS 10.3.4

### ISSUE THREAD

**Issue by DavideValdo** [TheWidlarzGroup/react-native-video#2084]
# Bug
Player is rendered, minute goes on but no audio is played. The device's audio is working, tested with YouTube videos. Audio is being played correctly on updated iOS simulator. I'm trying to stream a .mp3 URL, trying with a local asset now.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 35.85 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 5.0.2

## Steps To Reproduce

1. Run the app in debug mode on a real iPhone 5 running iOS 10.3.4
...

## Expected behaviour

1. Audio should be played

**Comment by nikodem-wrona** [comment]
same issue.

**Comment by Alejo-Garcia** [comment]
Check that your iPhone Ring/Silent switch is on! You can use ignoreSilentSwitch={'ignore'}.
