### ISSUE TITLE
HLS Adaptive Bitrate Streaming

### ISSUE THREAD

**Issue by michaelmaitland** [TheWidlarzGroup/react-native-video#2087]
I have a .m3u8 file that supports multiple bitrates. Is there a way for `react-native-video` to work with a playlist file that has multiple bitrates based off of the network speed on the device?

**Comment by ShakeelAhmad-dev** [comment]
Any solution  ? 
how you solve or manage this issue ?

**Comment by shyamvala** [comment]
Hi, just checking on this issue if this is closed because its already supported or not supported. I am facing a similar issue, trying to play a master manifest which has multiple bitrates specified but not seeing any video come up. Any ideas ? This is for an Android TV platform.

**Comment by coucoseth** [comment]
Any solution to this?
