### ISSUE TITLE
Some videos are playing well some videos are not playing i am unable to understand whats the issue 

### ISSUE THREAD

**Issue by nivas412** [TheWidlarzGroup/react-native-video#2088]
# Bug

Some videos are playing well some videos are not playing unable to understand the issue

ex:  http://febbler.com/assets/upload/12.mp4 this video is not playing why ??

## Platform
Android

Which player are you experiencing the problem on:

* Android MediaPlayer

## Environment info

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz
    Memory: 1.42 GB / 5.90 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 14.0.1
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found
React native info output:

    react-native: 0.63.1 => 0.63.1
Library version: "^4.4.5",

## Steps To Reproduce

1. Open some while scroll some videos are playing some are not
2. Taking a long time to play
...

## Expected behavior

1. It should play quickly
2. it should play immediately

## Reproducible sample code

 <Video
                        source={{ uri: post.videoUrl }}
                        onBuffer={this.onBuffer}
                        onLoad={this.onLoad}
                        onError={this.videoError}
                        progressUpdateInterval={750}
                        onProgress={play => this.props.currentPosition(play, post)}
                        onEnd={() => this.endVideo()}
                        ref={(ref) => {
                            this._player = ref
                        }}
                        resizeMode='contain'
                        repeat={true}
                        style={{
                            flex: 1 // backgroundColor: 'green',  // width: '100%'
                        }}
                    // controls={true}
                    ></Video>
## Video sample
http://febbler.com/assets/upload/12.mp4

**Comment by AxayDixit** [comment]
Hey, even i'm facing the same issue since today morning. I use a dummy video url to test but it's not working. Found anything on this issue?

**Comment by nivas412** [comment]
For me, it's working fine now because of the large size of data those videos not played.

**Comment by e3bmo3ty** [comment]
same issue, dont know what is the problem
