### ISSUE TITLE
Drm Video is not playing

### ISSUE THREAD

**Issue by bgity** [TheWidlarzGroup/react-native-video#2090]
I am using react-native-video library for playing DRM content on android.I am using below code to play drm video.Video is not playing showing blank screen.

<Video
          source={{
            uri:
              'https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd',
            drm: {
              type: 'widevine',
              licenseServer:
                'https://drm-widevine-licensing.axtest.net/AcquireLicense',
              headers: {
                'X-AxDRM-Message':
                  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImZpcnN0X3BsYXlfZXhwaXJhdGlvbiI6NjAsInBsYXlyZWFkeSI6eyJyZWFsX3RpbWVfZXhwaXJhdGlvbiI6dHJ1ZX0sImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.FAbIiPxX8BHi9RwfzD7Yn-wugU19ghrkBFKsaCPrZmU',
              },
            },
          }}
          style={styles.backgroundVideo}
        />

**Comment by hannojg** [comment]
Maybe it's the same issue as I have #2089. The headers you provided are maybe not attached to the request.
Can you log the network request and verify that?
