### ISSUE TITLE
Not working in android release mode

### ISSUE THREAD

**Issue by puneetkansal04** [TheWidlarzGroup/react-native-video#2092]
I am using your library and it is working fine on android debug as well on IOS. But when i create a android release mode it stops working. it is showing me a black screen, i am using a modal to show video. Also getting video in debug mode. but not working in release mode, i am using a video url with mp4 format

**Comment by luknoj** [comment]
Any solutions?

**Comment by adamsolomon1986** [comment]
+1

**Comment by geente** [comment]
I got the same issue

**Comment by khanof89** [comment]
Please get it fixed, this bug really eliminates the purpose of the library. On release mode hosted mp4 files e.g http://example.com/movie.mp4 does not plays at all.

**Comment by khanof89** [comment]
it is working, make sure your videos are using SSL e.g https://example.com/movie.mp4

**Comment by cauyyl** [comment]
I have tested by "https://stream7.iqilu.com/10339/upload_transcode/202002/18/20200218114723HDu3hhxqIT.mp4", but still not working on andriod release version. Anyone have the same issue?

**Comment by cauyyl** [comment]
> I have tested by "https://stream7.iqilu.com/10339/upload_transcode/202002/18/20200218114723HDu3hhxqIT.mp4", but still not working on andriod release version. Anyone have the same issue?

in my case , add "android:hardwareAccelerated="true" to AndroidManifest.xml
[Black screen on Android X](https://github.com/react-native-video/react-native-video/issues/1924#issuecomment-589945582)
