### ISSUE TITLE
Video Url does not contain how to get poster

### ISSUE THREAD

**Issue by prasad456** [TheWidlarzGroup/react-native-video#2093]
### Current behavior
Videos list need to show thumbnail or poster but using video url as thumb image not working.

### Reproduction steps
giving video url for poster to load thumb image

### Expected behavior
for all list video need to have thumb image from video url

### Video sample
video  pushed from mobile to s3 server

**Comment by yuripinage** [comment]
Same issue here. Did you solve it?

**Comment by MarvanN** [comment]
Same issue here. Did you find a solution.

**Comment by prasad456** [comment]
> Same issue here. Did you solve it?

Not Solved still

**Comment by chesovnik** [comment]
Same issue here

**Comment by KrisLau** [comment]
same here

**Comment by haifahrul** [comment]
same here

**Comment by freeboub** [comment]
Sorry but this is ticket is not clear of what is expected.
No sample, no expectation no API proposal ...
