### ISSUE TITLE
Video repeats after reaching the end

### ISSUE THREAD

**Issue by khattab93** [TheWidlarzGroup/react-native-video#2095]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:
Library version: 5.0.1

## Steps To Reproduce

1. Load a local video 
2. Play it
3. When it reaches the end, I seek it to start

## Expected behaviour

1. The plying should stop when reaching the end.

## Reproducible sample code
```
<Video
            ref={this.setVideoPlayerRef}
            style={styles.videoPreview}
            source={{ uri: Image.resolveAssetSource(require(`./test.mp4`)).uri }}
            resizeMode={"cover"}
            paused={paused}
            onLoad={this.getVideoDuration}
            onProgress={this.onProgress}
            onEnd={this.endPlaying}
          />

  private onProgress = ({ currentTime }): void => {
    if (currentTime >= this.state.trimmingEnd) {
      this.endPlaying()
    }
  }

  private endPlaying = (): void => {
    if (this.videoPlayer) this.videoPlayer.seek(0)
    this.setState({ paused: true })
  }
```

## Video sample
https://drive.google.com/file/d/17hZnL8tUUSXW8PARIZpujKUW3FovZvqu/view?usp=sharing

**Comment by hengkx** [comment]
same problem

**Comment by kraj011** [comment]
Same problem. Pausing works just fine before the video ends, but once the video ends and I update my paused state to true, the video still continues playing. I also have repeat={false} as a prop, which clearly is not working as intended. Might have something to do with the seek method (i.e. this.player.seek(0))? Not sure.

**Comment by kr396** [comment]
Same issue

**Comment by dev-fuad** [comment]
I had the same issue
this is the workaround I used
```
    const onEnd = useCallback(() => {
      player.current.seek(0);
      setTimeout(() => {
        setIsPaused(true);
      }, 100);
    }, []);
```

**Comment by kr396** [comment]
> I had the same issue
> this is the workaround I used
> 
> ```
>     const onEnd = useCallback(() => {
>       player.current.seek(0);
>       setTimeout(() => {
>         setIsPaused(true);
>       }, 100);
>     }, []);
> ```

I will try this. Thnak you.

**Comment by uglen** [comment]
> I had the same issue
> this is the workaround I used
> 
> ```
>     const onEnd = useCallback(() => {
>       player.current.seek(0);
>       setTimeout(() => {
>         setIsPaused(true);
>       }, 100);
>     }, []);
> ```

You can do this without delay by setting `rate` prop to `0`:
```
onEnd = () => {
  this.videoPlayer.seek(0);
  this.setState({
    rate: 0,
  });
}

render() {
...
  <Video
    ...
    onEnd={this.onEnd}
    rate={this.state.rate}
  />
...
}
```

**Comment by MarvanN** [comment]
Thanks it works for me

**Comment by msimon** [comment]
> I had the same issue this is the workaround I used
> 
> ```
>     const onEnd = useCallback(() => {
>       player.current.seek(0);
>       setTimeout(() => {
>         setIsPaused(true);
>       }, 100);
>     }, []);
> ```


This has a major caveat, is that the video will indeed starts and stop later. While the user will probably not see anything, the audio will be captured by the video which will stop other audio or even break recording.

I just spent 3 days trying to figure out why some of my customer's video did not have sound randomly. And it was when seek was being called in the background.

**Comment by Salman-Raj** [comment]
> I had the same issue this is the workaround I used
> 
> ```
>     const onEnd = useCallback(() => {
>       player.current.seek(0);
>       setTimeout(() => {
>         setIsPaused(true);
>       }, 100);
>     }, []);
> ```

Same issue im facing with ios ,But this code snippet doesn't worked for me


check my code


handleVideoEnd = () => {
    console.log("video ended")
    try{
    if (this.videoRef.current) {
      this.videoRef.current?.setState({paused: true})
      this.videoRef.current?.seek(0);
      setTimeout(()=>{
      this.setState({videoPaused:true,videoEnded:true,playPuse:true})
      },100)
    }
    }
    catch(error:string|unknown){
    console.log(error)
    }
  };



<Video
              volume={1.0}
              ref={this.videoRef}
              source={{ uri: source }}
              style={(Platform.OS === "android" && fullscreen) ? styles.videoFullscreen : styles.video}
              resizeMode="contain"
              onProgress={this.onProgress}
              onLoad={this.onLoad}
              paused={videoId}
              fullscreen={fullscreen}
              onLoadStart={this.onVideoLoadStart}
              onReadyForDisplay={this.onReadyForDisplay}
              playInBackground={false}
              playWhenInactie={false}
              onBuffer={this.onVideoBuffer}
              repeat={false}
              rate={1.0}
              loop={false}
              onEnd={this.handleVideoEnd}
              shouldPlay={!this.state.videoEnded}
              playWhenInactive={false}
              ignoreSilentSwitch="ignore"
              onPlaybackStatusUpdate={this.handlePlaybackStatusUpdate}
              />
