### ISSUE TITLE
Android asset does not play

### ISSUE THREAD

**Issue by JunoVW** [TheWidlarzGroup/react-native-video#2096]
# Bug
I want to play a video that is saved in my assets folder `/android/app/src/main/assets/videos/bunny.mp4`. I do this by giving `source={{ uri: 'file:///android_asset/videos/bunny.mp4' }}` to the video player.

I have attempted several other ways to get the video to play (including combinations without .mp4) such as:
```
source={{ uri: 'assets://videos/bunny.mp4' }}
source={{ uri: 'assets:///videos/bunny.mp4' }}
source={{ uri: '/videos/bunny.mp4' }}
source={{ uri: 'videos/bunny.mp4' }}
source={{ uri: 'file:///videos/bunny.mp4' }}
```

However none of these seem to work, and none of these seem to generate any form of error or console message, the same if I just fill in a random path for the uri.

Extra:
Using `react-native-fs` I can confirm there exists a `videos/bunny.mp4` in the assets.
The issue solution provided in #1826 does not seem to work either.

## Platform

Which player are you experiencing the problem on:
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 18.10 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v8.11.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: `"react-native-video": "^5.0.2"`
Problem also occurs on 4.4.5.

## Steps To Reproduce

1. Create a new react-native project via `npx react-native init TestProject`
2. Install react-native-video `npm install --save react-native-video@5.0.2`. (or @4.4.5))
3. Save a video to the location `/android/app/src/main/assets/videos/bunny.mp4`. You could download the exact video I'm using from the url: https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4
4. Change the default App function in `app.js` to the example given in the reproducible sample code.
5. Connect to a device and start your new project with `npx react-native start` and `npx react-native run-android`.

## Expected behaviour

1. Video plays or an error shows up

But right now neither happens.

## Reproducible sample code

```
import Video from 'react-native-video';

const App: () => React$Node = () => {
  return (
    <Video
      style={{width: '100%', height: '100%'}}

      // source={{uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4'}}
      source={{uri: 'file:///android_asset/videos/bunny.mp4'}}
      onBuffer={(e) => {
        console.log('Buffering: ', e);
      }}
      onError={(e) => {
        console.log('Error: ', e);
      }}
      muted
      repeat
      resizeMode={'cover'}
    />
  );
};
```
## Video sample
https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

**Comment by brendan1809** [comment]
try changing the style to `width:300,height:300`

**Comment by JunoVW** [comment]
> try changing the style to `width:300,height:300`

Unfortunately styling is not the problem, as with a network url the video does show. Changing it to 300x300 had the same result where the local asset didn't play.

**Comment by freeboub** [comment]
I just find this ticket, but the way to proceed is to use require() instead of accessing directly to the folder. The only use case you can want to do that is if you share this video with other native code... Please clarify why you need to do that ?!

**Comment by JunoVW** [comment]
> I just find this ticket, but the way to proceed is to use require() instead of accessing directly to the folder. The only use case you can want to do that is if you share this video with other native code... Please clarify why you need to do that ?!

Based on the documentation in the readme I thought using file:// was possible. I must have missed the part where require is also an option, thank you for responding!

**Comment by PruebasCedum** [comment]
why this is closed?, still dont have any way to play video from java assets

**Comment by freeboub** [comment]
because it works, pleas read documentation....
Something like:
src={require('./video.mpg')}

**Comment by t104360088** [comment]
I have the same issue.
In my case, I must to read the video from android asset folder.
I don't want to open another question because it's the same.

This is my code, Does anyone can help me? 

```
source={{ uri: 'file:///android_asset/test.mp4' }}
source={{ uri: 'asset:/test.mp4' }}
```

Related References：

[Using file path in react-native-video](https://github.com/react-native-video/react-native-video/blob/master/API.md#file-path-file)
[Path of Android asset folder](https://stackoverflow.com/a/7325290/17364139)
[The same issue but he fix it by adjusting source code](https://github.com/react-native-video/react-native-video/issues/379)
[Read the video from android raw folder but not my case](https://github.com/react-native-video/react-native-video/pull/103#issuecomment-157237650)
