### ISSUE TITLE
on Ios not show some videos 

### ISSUE THREAD

**Issue by Jacklol** [TheWidlarzGroup/react-native-video#2097]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
0.61.4
```

Library version: 5.1.0-alpha5

## Steps To Reproduce

1.
   <Video source={{ uri: 'https://api.empiflow.com/v1/mediaStream?file_id=9111.mp4' }} .. />
2. video play on android , but no play on ios
3. error:
code: -1
domain: "NSURLErrorDomain"

**Comment by corners-summer** [comment]
同问

**Comment by corners-summer** [comment]
I have the same problem, do you have a solution?

**Comment by zoultrex** [comment]
I also have this problem, is there a solution for this?
