### ISSUE TITLE
BufferValue

### ISSUE THREAD

**Issue by MwareSolutons** [TheWidlarzGroup/react-native-video#2098]
hi All,

I think this is a feature request but maybe its already there we want to show the BufferValue in our Scrubber but we can not find the event for the buffered amount

Thanks in advance

Regards Sander

**Comment by Serzhs** [comment]
On `progress` event you can get `playableDuration` value

**Comment by mym0404** [comment]
This issue should be closed. The @Serzhs 's answer is correct.
