### ISSUE TITLE
Landscape orientation in fullscreen mode (*only*)

### ISSUE THREAD

**Issue by dwaligora** [TheWidlarzGroup/react-native-video#210]
Hey Guys,

After several sleepless nights, I don't have any more ideas how to do what I am trying to do.

In short words, I am trying to allow my fullscreen video to be accessible in all orientations (landscape and portrait). This is the only place in the app where I want to allow that. All other views are locked to portrait.

My idea was to delegate fullscreen enter / exit event and in that place, programmatically set orientation allowance, so on fullscreen enter, unlock landscape additionally and on fullscreen exit, lock back only to portrait. Everything works fine apart from the one crucial part...I can not delegate fullscreen enter/exit event (delegating those events was my idea but I might be completely wrong and that should be managed in completely different way)

Thanks in advance for any help!

**Comment by dwaligora** [comment]
ok guys, that was my fault. Everything works as it supposed to work with fullscreen mode ( 👍 ) . I only extended the RCTVideo [here](https://github.com/dwaligora/react-native-video/commit/d1d3ad576c6ae760262a92873f06407b2df7f270) by triggering dismiss event anytime user click "Done". Somehow it isnt triggered for this action, which in my case was required because I have to perform some action on video close. 

I know it is not elegant solution but I am quite rush and newbie in iOS. I am leaving that here because maybe someone could point me out what I did wrong or it might be used as a hint for someone who will experience the same problem.

**Comment by anabil-symbyo** [comment]
@dwaligora what about Android?

**Comment by Gregoirevda** [comment]
Same issue on android.

**Comment by luutruong** [comment]
Hello @dwaligora . Can you share your solution? I want to same behavior but not found any solution yet :(
