### ISSUE TITLE
Android ) seek does work inaccurately

### ISSUE THREAD

**Issue by pyeonjaesik** [TheWidlarzGroup/react-native-video#2100]
Which player are you experiencing the problem on:

* Android ExoPlayer

## Environment info

React native info output:

    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 307.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.0, 28.0.3, 29.0.0, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

Library version: 0.61.5

## Steps To Reproduce

seek does not work accurately. for example when I seek to 10.0 s my video seeks to 8.0s.

how to seek to accurate timestamp?

ios works well

**Comment by bird-xiong** [comment]
same problem

**Comment by bird-xiong** [comment]
> Which player are you experiencing the problem on:
> 
> * Android ExoPlayer
> 
> ## Environment info
> React native info output:
> 
> ```
> OS: macOS 10.15.4
> CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
> Memory: 307.86 MB / 16.00 GB
> Shell: 3.2.57 - /bin/bash
> ```
> 
> Binaries:
> Node: 12.18.2 - /usr/local/bin/node
> Yarn: 1.22.4 - ~/.yarn/bin/yarn
> npm: 6.14.5 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> iOS SDK:
> Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
> Android SDK:
> API Levels: 23, 25, 26, 27, 28, 29
> Build Tools: 25.0.0, 28.0.3, 29.0.0, 29.0.2
> System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
> IDEs:
> Android Studio: 3.4 AI-183.6156.11.34.5522156
> Xcode: 11.5/11E608c - /usr/bin/xcodebuild
> npmPackages:
> react: 16.9.0 => 16.9.0
> react-native: 0.61.5 => 0.61.5
> npmGlobalPackages:
> react-native-cli: 2.0.1
> react-native-rename: 2.4.1
> 
> Library version: 0.61.5
> 
> ## Steps To Reproduce
> seek does not work accurately. for example when I seek to 10.0 s my video seeks to 8.0s.
> 
> how to seek to accurate timestamp?
> 
> ios works well

Use ExoPlayer instead of Android Player. It works!
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

**Comment by pyeonjaesik** [comment]
@bird-xiong I already used Exoplayer.
