### ISSUE TITLE
The m3u8 ts url has a signature. How to pass the signature method to the player?

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#2107]
xx.m3u8

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10,
SZurkTT6.ts
```

url:  `xxx.xxx/SZurkTT6.ts?signature=xxxxxx`

The `signature` of each `ts` is different. The `signature` is calculated based on the original URL. How do I pass the `signature` to the player?

**Comment by singhravi1** [comment]
Hey @BAE86AEC1946B6AB60CCD7452DC811F0 ,

First you'd need to make sure that the signature you've would work for all the parts of the stream as well.
If you're using cloudfront, you'd need to generate custom policy signature and you'll receive policy, signature, keyid in the params/cookies.
Then you'd need to set that in the cookie for each video while you're providing the url of the playback source. This is described [here](https://stackoverflow.com/questions/59363691/react-native-video-cookies).
