### ISSUE TITLE
Video isn't showing from my video url on iOS

### ISSUE THREAD

**Issue by annie-elequin** [TheWidlarzGroup/react-native-video#2112]
### Current behavior
Describe what happens when you encounter this issue.

The Video component will not show my video. The video url is `https://matrix.ditto.chat/_matrix/media/r0/download/ditto.chat/gHLSYpcjbfZDUEonYJHdHCTY`.  I also pass type, and the type is `video/mp4`.

Here is the component (no error is shown from onError) 
```
<Video
            source={{ uri: content.url, type: content.type }}
            style={{
              width,
              height,
              backgroundColor: '#ddd',
            }}
            onError={console.warn}
          />
```

Video component result: 
![image](https://user-images.githubusercontent.com/20155539/90294688-a6783d00-de4c-11ea-83e0-fc2ced51c428.png)

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

1. Create new react native project 
2. Install react-native-video, place a video component in the view with my props 
3. Video won't work 

### Expected behavior
Describe what you wanted to happen

Video should play in the view 

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

[https://matrix.ditto.chat/_matrix/media/r0/download/ditto.chat/gHLSYpcjbfZDUEonYJHdHCTY](https://matrix.ditto.chat/_matrix/media/r0/download/ditto.chat/gHLSYpcjbfZDUEonYJHdHCTY
)

**Comment by genyaonipko** [comment]
any updates? i have same problem...
