### ISSUE TITLE
selectedTextTrack with system type is not working with Android Exoplayer

### ISSUE THREAD

**Issue by SachArora** [TheWidlarzGroup/react-native-video#2114]
# Bug

I want to enable Captions for hearing impaired people. I already enabled the Captions from device settings but still, captions are not displaying on the video player.

Video player

                        <Video
                            source={{ uri: this.state.playerUrl, headers: { 'origin': '*******' } }}
                            ref='player'
                            paused={this.state.isPaused}
                            controls={false}
                            currentTime={this.state.currentDuration}
                            rate={this.state.speed}
                            minLoadRetryCount={10}
                            progressUpdateInterval={1000}
                            useTextureView={false}
                            playInBackground={false}
                            seek={this.state.seek}
                            onLoad={(data) => this.onVideoLoad(data)}
                            selectedTextTrack={{type: 'system'}}
                            selectedVideoTrack={this.state.selectedVideoTrack}
                            onProgress={(progress) => this.updateProgress(progress)}
                            onBuffer={(buffer) => this.setState({ isBuffering: buffer.isBuffering })}
                            style={{ backgroundColor: 'black', position: 'absolute', top: 0, left: 0, bottom: 0, right: 0 }}
                        />

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
   React Native Environment Info:
    System:
      OS: macOS 10.15.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 102.05 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by awinograd** [comment]
My text track also isn't showing with `selectedTextTrack={{type: 'system'}}` and system settings for captions enabled. If I change it to `{type: "index", index: 0}` it shows properly

**Comment by awinograd** [comment]
This is the following patch in the referenced PR that resolves this issue for me:

```
diff --git a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index 1edb8c7..d564253 100644
--- a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -985,7 +985,7 @@ class ReactExoplayerView extends FrameLayout implements
                     }
                 }
             }
-        } else if (rendererIndex == C.TRACK_TYPE_TEXT && Util.SDK_INT > 18) { // Text default
+        } else if (trackType == C.TRACK_TYPE_TEXT && Util.SDK_INT > 18) { // Text default
             // Use system settings if possible
             CaptioningManager captioningManager
                     = (CaptioningManager)themedReactContext.getSystemService(Context.CAPTIONING_SERVICE);
```

**Comment by Polarisation** [comment]
@awinograd Thank you, I had the same issue and the patch works.
