### ISSUE TITLE
Picture in Picture is closing immediately

### ISSUE THREAD

**Issue by rogerkerse** [TheWidlarzGroup/react-native-video#2118]
# Bug

Whenever I set the app to the background, it shows Picture in Picture for a sec and then closes, but audio stays playing.

## Platform
iOS 14 iPhone 11 Pro Max

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 20.34 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /var/folders/5_/_h4s11pj2jv0rx1jqyjm8tbm0000gn/T/yarn--1597768022577-0.53173374147208/node
    Yarn: 1.22.4 - /var/folders/5_/_h4s11pj2jv0rx1jqyjm8tbm0000gn/T/yarn--1597768022577-0.53173374147208/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.0-alpha7

## Steps To Reproduce

1. Open video
2. Move the app to the background

console log that i get is -> 'PIP STATE CHANGE', {target: 6167, isActive: true}
and immediately after that -> 'PIP STATE CHANGE', {target: 6167, isActive: false} <-- why it turns off, no idea
...

## Expected behaviour

1. Video stays playing in Picture in Picture mode

## Reproducible sample code

I have background mode for Picture in Picture enabled.

```
<Video
     style={styles.fill}
     source={{ uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' }}
     ignoreSilentSwitch="ignore"
     playWhenInactive
     playInBackground
     pictureInPicture
     onPictureInPictureStatusChanged={(props) => console.log('PIP STATE CHANGE', props)}
/>
```

## Video sample
https://photos.app.goo.gl/gHWSc9MfwpSHRyT97

**Comment by andymerryman** [comment]
@rogerkerse from here it looks like `playInBackground` nullifies / conflicts with the expected behaviors of `playWhenInactive` `pictureInPicture`. 

For me, when `playInBackground` is set, I get the behavior you are observing (it shows Picture in Picture for a sec and then closes, but audio stays playing). When `playInBackground` is unset, and `playWhenInactive`/ `pictureInPicture` are set, PiP works as expected. 

What I am trying to figure out is how to blend these so that 
- PiP works as expected when the device is unlocked
- Audio plays in the background when the device is locked.

**Comment by marf** [comment]
Hello @andymerryman have you found a solution?
We have the exact same problem.

Thank you,
Marco

**Comment by luis-f-lins** [comment]
I am also having this problem. Has anyone found a solution?

**Comment by mbrimmer83** [comment]
Do any of you have picture in picture working with IOS 14? I see people using this feature on IOS 13, but I have not been able to get picture in picture working at all.

**Comment by iamchrispham** [comment]
Definitely getting this bug as well on iOS14. Picture in Picture does work on iOS 14, however, when PiP is set to false, playInBackground is set to true, there are some instances where PiP will populate when the app is in the background and will immediately close. 

This is a guess but I think it may have to do with how AVPlayer is detecting whether or not it's detached from from an app; when it detects it's detached from the moment the app goes into the background, PiP will populate.

An odd workaround for when I had PiP set to false (the default) and playInBackground set to true, was adjusting the dimensions of the video from inside the app. After that, PiP stopped triggering when my app would go into the background.

**Comment by fengjiankang** [comment]
how to resolve the problem

**Comment by fengjiankang** [comment]
Have you solved the problem yet

**Comment by maliotti** [comment]
I am also curious about this. We would like to implement both `playInBackground` and `pictureInPicture` capabilities in our app, but are holding off until this has been resolved. Any thoughts?

**Comment by KingAmo** [comment]
https://github.com/react-native-video/react-native-video/issues/2177#issuecomment-770474082

this step works for me

**Comment by MaxJadav** [comment]
@rogerkerse  @andymerryman  @all
Any one have soultion?
-PiP works as expected when the device is unlocked
-Audio plays in the background when the device is locked.

> [#2177 (comment)](https://github.com/react-native-video/react-native-video/issues/2177#issuecomment-770474082)
> 
> this step works for me

https://github.com/react-native-video/react-native-video/issues/2177

@KingAmo  I try this solution but not working. Audio not playing when you lock screen.

When I set both true then pip not work.
```
pictureInPicture={true}
playInBackground={true}
```

PiP is working but Lock Screen not play audio
```
pictureInPicture={true}
playInBackground={false}
```

Pip not working. Able to play audio in Lock Screen.
```
pictureInPicture={false}
playInBackground={true}
```

**Comment by Jim-Yang** [comment]
```
pictureInPicture={true}
playInBackground={false}
playWhenInactive={true}
```

These combination of props seems to make PiP and background play work for me.

**Comment by watadarkstar** [comment]
> pictureInPicture={true}
> playInBackground={false}
> playWhenInactive={true}

This worked for me. Thank you!
