### ISSUE TITLE
[Android] Won't play the same video more than once (even if it's not in direct sequence)

### ISSUE THREAD

**Issue by filiphosko** [TheWidlarzGroup/react-native-video#2123]
# Bug

I have a React component that acts as a media player/viewer - it either shows a static image or plays video. For the video part, it uses this library. In this component, I switch between rendering an image and the Video component based on the type of data that comes in. The data structure is like this:

```
[
   {
      duration: null,
      file: 'file:///data/user/0/com.myapp.debug/cache/media/ad 1.mp4',
      type: 'video',
    },
    {
      duration: null,
      file: 'file:///data/user/0/com.myapp.debug/cache/media/ad 1.mp4',
      type: 'video',
    },
    {
      duration: 10,
      file: 'logo.png',
      type: 'image',
    },
]
```

As you can see, both videos are the same file (same video). What happens (now) is when the first video stops playing (`onEnd` is triggered), I pass the props for the next video (same file) but it just won't play (I'm sure the parent Media component re-renders, I checked that). The problem is that even if I remove the "direct sequence" (I remove the second video) after the image is rendered, it will go back to the video (since this is a loop of ads) and it still won't play. As if it would check that it's the same file and it won't play - I'm not sure. But what I'm sure about is that with 4.4.0 this wasn't happening.

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 1.37 GB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
```

Library version: was able to reproduce with 5.0.2 and 5.0.1

## Steps To Reproduce

1. Try to play the same video twice in a sequence (per the example above) - after the first video will trigger `onEnd`, pass the second set of props to the Video component (second item from an array).
2. The second video won't play.

## Expected behaviour

1. Try to play the same video twice in a sequence (per the example above) - after the first video will trigger `onEnd`, pass the second set of props to the Video component (second item from an array).
2. The video will play even if it's the same file as before (as it did with 4.4.0).

## Reproducible sample code

```typescript
function MediaView(props: Props) {
  const {style, onStop, type, duration, file, onError} = props;

  const fileUri = Platform.OS === 'android' ? `file://${file}` : file;

  const timer = useRef<NodeJS.Timer | null>(null);

  useEffect(() => {
    return () => {
      if (timer.current) {
        global.clearTimeout(timer.current);
        timer.current = null;
      }
    };
  }, []);

  if (type === 'image') {
    if (typeof duration === 'number') {
      timer.current = global.setTimeout(() => {
        onStop();
      }, duration);
    }

    return (
      <View style={style}>
        <Image
          style={{flex: 1}}
          source={{
            uri: fileUri,
          }}
        />
      </View>
    );
  }

  return (
    <View style={style}>
      <Video
        style={{flex: 1}}
        source={{
          uri: fileUri,
        }}
        onError={onError}
        onEnd={onStop}
        resizeMode="cover"
        controls={false}
        repeat={false}
        muted={false}
        paused={false}
      />
    </View>
  );
}
```

**Comment by Krunal-K-SimformSolutions** [comment]
@filiphosko: Yes, I have the same problem with Android MediaPlayer. so I am switching to ExoPlayer and working fine.

**Comment by unnikrishnan-anil** [comment]
I had a similar problem. But I was using URLs to play the videos. How I worked around it is by introducing a counter variable and passing it to the URL like so: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_30MB.mp4?counter=<counterValue> . Increment the counter after every run. That way the video url stays unique.

**Comment by briantical** [comment]
Thanks @CatsNipYummy 
I further implemented it using the file path. My implementation

```javascript
...
const [count, setCount] = useState(0);
...
<Video
 source={{
   uri: `file://${filepath}?counter=${count}`,
 }}
 onEnd={() => {
   setCount(Math.random());
  }}
/>

```
