### ISSUE TITLE
Not getting selectedVideoTrack on load complete

### ISSUE THREAD

**Issue by santanu07** [TheWidlarzGroup/react-native-video#2129]
# Bug
after loading complete of my video I am not getting video tracks array

## Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

Library version: 5.1.0-alpha8

## Steps To Reproduce

 const onLoadComplete = (data) => {
    console.log( data.videoTracks); // getting blank
  }

 <Video source={{ uri: "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8" }}
        ref={videoRef}
        resizeMode="cover"        
        onLoadStart={()=>alert('hi')}
        onLoad={onLoadComplete}
/>

pls solve this issue asap, and save me

**Comment by alliverslakinov** [comment]
Hey did you ever figure out the issue? I am having the same problem. There's not even an empty array for videoTracks. no property at all. same for the audio tracks and text tracks as well which also are supposed to be there as per the docs.

**Comment by skfaisal93** [comment]
Having same issue
