### ISSUE TITLE
preventsDisplaySleepDuringVideoPlayback is not working on android when set to false

### ISSUE THREAD

**Issue by Monte47** [TheWidlarzGroup/react-native-video#2132]
When I set `preventsDisplaySleepDuringVideoPlayback={false}` and then play my media, my android device will never go to sleep. Is there something I'm missing here?

**Comment by sharifhh** [comment]
Which version you have? the problem is the documentation is for the alpha version, preventsDisplaySleepDuringVideoPlayback were introduced in 5.1.0-alpha6

**Comment by Monte47** [comment]
@sharifhh That seems to have worked. Thanks!
