### ISSUE TITLE
Play .m3u8 video file

### ISSUE THREAD

**Issue by prdvrs** [TheWidlarzGroup/react-native-video#2133]
# Bug

I want to play the .m3u8 video file in video player which have the source system as both local and remote

## Platform
iOS and Android

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

## Environment info

System:
    OS: macOS 10.15.5
SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 

React native info output:
 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Library version: 5.1.0-alpha8

## Steps To Reproduce
Execute the above code in ios/android simulator

## Expected behaviour
Video should play with out any issues

## Reproducible sample code

<View style={styles.container}>
<Video
  source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
  rate={1.0}
  volume={1.0}
  isMuted={false}
  resizeMode="cover"
  shouldPlay
  isLooping
  style={{ width: 300, height: 300 }}
/>react-native info
</View>

**Comment by PaulosSouza** [comment]
I've got the same problem :(
