### ISSUE TITLE
No videoTracks in onLoad and maxBitRate not working

### ISSUE THREAD

**Issue by Pauly24** [TheWidlarzGroup/react-native-video#2134]
# Bug

videoTracks in onLoad is not being displayed for HLS file and maxBitRate is not working.
Because of this I cannot define the correct bitrate and the mobile app is eating all the bandwidth costing $$$

Fresh init of react native with below details
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-video": "^5.1.0-alpha8"
  },

The issue occurs on iOS and Android

## Steps To Reproduce

`        
<Video
          source={{
            uri:
              'https://urltohlsfile.m3u8'
          }}
          style={styles.backgroundVideo}
          maxBitRate={1000000}
          controls={true}
          onLoad={(e) => console.log('e', e)}
        />`

## Video sample
https://d1u4oz0uuj663i.cloudfront.net/output/hls/dev/best.m3u8

edit: I think the maxBitRate is working, how can you check if you can't print out the current stream that's playing?

**Comment by alikazemkhanloo** [comment]
Also no TextTracks and AudioTracks. It was working a few months ago. :|

**Comment by tirrth** [comment]
Anyone has any solution for modifying the maxBitrate!!

**Comment by sakthinaveenm** [comment]
Why it doesn't displays audio tracks in mkv files also

**Comment by praveens96** [comment]
any update on this? I am too facing similar issue, no videoTracks data is being received in onLoad. Any hints what the issue could be also helps. thanks in advance

**Comment by orange-brother** [comment]
+1

**Comment by orange-brother** [comment]
no video traks in data. Only texttracks and audiotracks, so frustrating..

**Comment by tushar-singhal** [comment]
android is working fine for me, I dont get `videoTracks` on iOS

**Comment by LordNahi** [comment]
Bump. Is there any alternative method for selecting HLS tracks?

**Comment by skfaisal93** [comment]
Facing the same issue. Anyone got answer??????

**Comment by sannjayy** [comment]
+1

**Comment by freeboub** [comment]
This issue is still valid. I would also add that there is an api issue here. 
Video, text and audio tracks can change during playback (ADS use case). It would be a better feature to remove tracks handling from onload and to handle them as separated events !
