### ISSUE TITLE
[Android] DRM video invisible in resizeMode cover

### ISSUE THREAD

**Issue by rogerkerse** [TheWidlarzGroup/react-native-video#2138]
# Bug

Only on Android.
Only with DRM videos.
When video is fully covering the screen and resizeMode is 'cover' then video is transparent. Sometimes if flickers visible for a sec.
When resizeMode is contain, then everything is fine and video is fully visible.

## Platform
* Android ExoPlayer

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.08 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.2 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 5.1.0-alpha7

## Steps To Reproduce

Only happens with DRM videos.
When video is fully covering the screen and resizeMode is 'cover' then video is transparent. Sometimes if flickers visible for a sec.
...

## Expected behaviour

expected the player to be visible.

## Reproducible sample code

.

## Video sample
.

**Comment by muxbert** [comment]
I am having the same issue, have solved your issue @rogerkerse
