### ISSUE TITLE
Spaces in uri filename not working on iOS

### ISSUE THREAD

**Issue by moulie415** [TheWidlarzGroup/react-native-video#2140]
# Bug

When passing in uri with a file that has a space in it e.g. `${ROOT_URL}/file name.mp3` it doesn't work however it does work on android the solution for me was just to replace the space with an underscore but thought I should flag this up, I'm not sure if this is just an issue with audio or if it effects video files as well

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 291.43 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.0.1

## Steps To Reproduce

Pass a uri string where the filename has a space in it as the uri source and you will get a AVFoundationErrorDomain

## Expected behaviour

Audio plays without error

## Reproducible sample code

Here's the code for an Audio component I made 

```
import React, {FunctionComponent} from 'react';
import Video from 'react-native-video';
import AudioProps from '../../types/Audio';
import {Alert} from 'react-native';

const Audio: FunctionComponent<AudioProps> = ({paused, uri, onBuffer}) => {
  return (
    <Video
      paused={paused}
      audioOnly
      source={{uri}} // uri = `${ROOT_URL}/file name.mp3`
      onBuffer={onBuffer}
      onError={(error) => {
        __DEV__
          ? console.warn(error.error.errorString)
          : Alert.alert('Error', error.error.errorString);
      }}
      playInBackground
      playWhenInactive
      ignoreSilentSwitch="ignore"
    />
  );
};

export default Audio;
```

**Comment by pinnaaiengineer** [comment]
Hi @moulie415  you can just use.     source={{uri: uri.replace(/ /g, '%20')}} 
spaces in url not work in iOS
