### ISSUE TITLE
How to get buffer progress while paused?

### ISSUE THREAD

**Issue by nickfujita** [TheWidlarzGroup/react-native-video#2141]
# Feature Request

Provide a way to access buffer progress while video is paused.

## Why it is needed

There are cases where users with slower connections will pause the video, and wait until they can see that their buffer indicator has progressed a self determined amount before starting playback.

This does not appear to be possible, as the only place where buffered state appears to be accessible is via the `onProgress` event. Based on the documented description, the `onProgress` event should be fired every `progressUpdateInterval`. However in both the documentation for `onProgress` and `progressUpdateInterval`, there does not appear to be any mention of whether this event should be fired when the player is paused.

While using the player on Android with the exoplayer version, the `onProgress` event does not fire at all while paused. Therefore we are not able to get the `playableDuration` value to show the user buffer progression while paused.

## Possible implementation

1. Update the `onProgress` event to fire even while the player is paused. This will help to provide on progress updates for the buffer state.
2. Provide a separate `onBufferProgress` event which will fire on an interval with the latest `playableDuration` to indicate buffer progress no matter if the player is playing or paused
3. Provide a method which allows the client to request the buffer state `playableDuration` at any given time. This should be accurate to the latest buffer position no matter the play/pause state of the player.

**Comment by ChrisCodeCole** [comment]
+1, could be useful for me as well

**Comment by cobarx** [comment]
We should update the `onBuffer` event as this is already present and people are using it. We just need to get it documented and make sure we know which platforms it works on and what the payloads are.

**Comment by KingAmo** [comment]
it seems that video stop buffering when in pause state

**Comment by Navipro70** [comment]
It's very useful thing. PR is opened, any updates for it?

**Comment by ghost** [comment]
+1, This would be very useful for me as well.

**Comment by freeboub** [comment]
This issue shall be reopened ! as it is still here :)
The onProgress callback shall be sent even if playback is in pause.
This is important for UI especially when you are playing live contents !

Notice that linked PR is not the good fix.
I have a small patch for this, I will try to on PR with it.

**Comment by freeboub** [comment]
```
index d2fc693..743048b 100644
@@ -178,9 +178,7 @@ public class AndroidExoplayerView extends AndroidPlayerItf implements
             switch (msg.what) {
                 case SHOW_PROGRESS:
                     if (player != null
-                            && player.getPlaybackState() == Player.STATE_READY
-                            && player.getPlayWhenReady()
-                            ) {
+                            && player.getPlaybackState() == Player.STATE_READY ) {
                         long pos = player.getCurrentPosition();
                         long bufferedDuration = player.getBufferedPercentage() * player.getDuration() / 100;
                         eventEmitter.progressChanged(pos, bufferedDuration, player.getDuration());


```

**Comment by hueniverse** [comment]
@freeboub thanks!

**Comment by freeboub** [comment]
I tries to reintegrate this patch, but It seems it is not enough.
I will double check
