### ISSUE TITLE
Show poster until play is triggered

### ISSUE THREAD

**Issue by janpe** [TheWidlarzGroup/react-native-video#2142]
# Feature Request

I noticed that the poster is removed when the video has loaded. Could it be possible to add an option to have the poster and play button visible until the user hits play?

## Why it is needed

The first frame of the video isn't necessarily something that looks very good. It'd be nice to be able to show a well designed thumbnail until the user hits play.

## Possible implementation

I guess `_onReadyForDisplay` could check a specific prop that would leave the poster visible. Play button would have to be shown as well. I'm not too familiar with the code in this project so I don't have any ideas about implementing that.

**Comment by KPS250** [comment]
Yes we need a thumbnail preview for this library

**Comment by GoktuqCan** [comment]
I aggree

**Comment by dawidchyrzynski** [comment]
Any update on this?

**Comment by MaazF94** [comment]
I agree this would be great! Expo Video has a boolean prop called usePoster. I had to switch over to RN Video due to integrating DRM but, that's one feature I miss.

**Comment by rizbud** [comment]
agree

**Comment by arjun1194** [comment]
any updates on this ?

**Comment by SourceCipher** [comment]
Poster should be showing by default before video can be played (if the poster prop not provided). Not sure why its not showing. Also seems like if you pause the video and switch the tabs (even tho the component is not remounted), video no longer displays a poster (or that current view).

**Comment by oreporan** [comment]
+1

**Comment by amie-wilt** [comment]
+1

**Comment by freeboub** [comment]
I think you expect react native video to implement UI in place of the app. Not sure this is a good idea to put this feature in react native video :/

**Comment by amie-wilt** [comment]
I expect it to have the same behavior as `poster` on  HTML `<video />`.  To me, `poster` !== loading state. If it's not going to act as a `poster`, why have it at all? It's a little confusing. Seems like the functionality should be updated to reflect `poster` or `poster` should be renamed `loader` and accept a component or something.

**Comment by pamela-encora** [comment]
+1

**Comment by mariana-encora** [comment]
+1

**Comment by freeboub** [comment]
This is a pure UI request. This shall be handled by application.
The good way to implement it is:
- display the poster in the same time you change source
- hide the poster onReadyToDisplay

**Comment by oferRounds** [comment]
@freeboub why did you close it? it‘s not a pure-ui request - it relates to a functionally how the poster behaves  – it’s not changing color or adding a border. Notice that also media management tools such as [Cloudinary](https://cloudinary.com/) are smartly pick the poster frame, instead of the first frame – to say that this is a desired behaviour. 

Can we reopen it with the goal of adding this behaviour as an optional property?

**Comment by freeboub** [comment]
Ok understood, but what is blocking implementation from application side ? I think I implement similar feature without patching react native video...

**Comment by disrae** [comment]
It certainly does seem possible to force the implementation in our own app, but the implementation would look like an ugly patch. This is open source, I understand if you don't want to implement it, I'm just not sure that it *shouldn't* be handled by the library.
