### ISSUE TITLE
Clarification on using headers prop

### ISSUE THREAD

**Issue by gabrielkuettel** [TheWidlarzGroup/react-native-video#2145]
I'm seeking some clarification on the `headers` prop. https://github.com/react-native-community/react-native-video#headers

1. Is this intended to be used with iOS? I'm using it in iOS without any problems, although the docs specify that it's to be used with the Android ExoPlayer. 

2. Should the definitions for the source object in `@types/react-native-video` be updated to include support for the `headers` property? Currently, the `source` definition only supports the `uri` property . For a temporary fix, I've edited the type definitions in `node_modules` as follows: `source: { uri?: string, headers: HeadersInit } | number`. I was planning on making a PR to `@types/react-native-video` to add this, but I'm not clear if that's the correct approach.

**Comment by gkuettel** [comment]
I made a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47530) to `@types/react-native-video` to add support for the missing `headers` property.
