### ISSUE TITLE
Android. Audio repeat playback does not work.

### ISSUE THREAD

**Issue by gHashTag** [TheWidlarzGroup/react-native-video#2147]
Audio repeat playback does not work. react-native-video. When I click on the button, I call the method:
```javascript
playerRef.current?.seek(0)
```
It works for ios, but not for android. Any ideas how to fix it?

![Screenshot_1600148248](https://user-images.githubusercontent.com/6774813/93170852-6ead2f80-f741-11ea-8273-962ebf817b3f.png)

**Comment by anshul-kai** [comment]
+1

**Comment by gHashTag** [comment]
Solved the problem on this [screen](https://github.com/fullstackserverless/Sumerian/blob/18f494024eff277f8652c8805e48eb5dea73efb3/src/screens/TabBottom0/Tab0/Tab0Test.tsx#L170), its implementation.

**Comment by anshul-kai** [comment]
@gHashTag Your fix is a hack, not a solution. You should keep this ticket open for the authors of the library to fix this the right way.

**Comment by gHashTag** [comment]
@a-koka ok
