### ISSUE TITLE
RTMP Video Streming

### ISSUE THREAD

**Issue by mygu** [TheWidlarzGroup/react-native-video#215]
How to play RTMP streaming of video? HLS latency is too high, around 30 seconds, can you give me some advice?

Now, I use`{{uri: 'http://<Address>:<Port>/<Application>/<Stream>.m3u8}}` it can work, but the latency is too high.
I want to use, `{{uri: 'rtmp://<Address>:<Port>/<Application>/<Stream>}}` it does'n work.

**Comment by mygu** [comment]
Somebody help me?

**Comment by mattapperson** [comment]
The iOS SDK and Android API don't support the RTSP protocol. Thus a 3rd party library must be used. While adding support for such things would be accepted as a PR, it's not within the current scope of the project. Also, if you wish to create a feature request for this (or reword your comment as such) I will be more then happy to re-open this

**Comment by gabrielfarah** [comment]
Hi, was this ever opened as a PR or was implemented in any way?

**Comment by mattapperson** [comment]
@gabrielfarah hes, this was changed when the android video solution was swapped out

**Comment by gabrielfarah** [comment]
@mattapperson Thanks for such a  fast response. Any chance to find some doc into how make it work? If I try something like: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov then it does not work. However, with every other kind of video (like: https://dwknz3zfy9iu1.cloudfront.net/uscenes_h-264_hd_test.mp4 ) or even streamed audio (like: http://live-aacplus-64.kexp.org/kexp64.aac ) does work like a charm.

**Comment by mattapperson** [comment]
@gabrielfarah sorry, RTMP exactly does not work HLS however does. Android now uses exoplanet so anything it supports can work here

**Comment by gabrielfarah** [comment]
Thank you, just tested it with HLS and works ok.
