### ISSUE TITLE
Videos in m3u8 format do not play correctly in IOS 

### ISSUE THREAD

**Issue by SergioSosaGonzalez** [TheWidlarzGroup/react-native-video#2150]
I'm trying to play m3u8 videos, when I tried with android I didn't have any problem but in IOS something curious happens. When I enter the app for the first time and select any video, it played but when I select another one, the react-native-video component "loads" the video, but the screen stays black and does not send any error, it is as if something is blocking it. I already specified in the source type property that it is m3u8, pass the cookies that are requested and remove the cache prop, if someone has passed something similar, it would be helpful, thanks.

**Comment by oshtman** [comment]
I'm experiencing the same problem. Possibly related to #1725?
