### ISSUE TITLE
Help me! If the frame height and width are not enough, the full screen cannot be achieved

### ISSUE THREAD

**Issue by Shuo-Mr** [TheWidlarzGroup/react-native-video#2160]
# Bug

When I use the style to play full screen on Android, when the machine size is 1080 * 1920, the video frame height and frame width are 1080 and 1920 respectively, the full screen is normal, but if the frame height and width of the video are lower than the machine size, the video will shrink to a corner.

wrong：
![image](https://user-images.githubusercontent.com/50469430/94116136-37dfc380-fe7d-11ea-8a3f-a7cb7882823c.png)
normal：
![image](https://user-images.githubusercontent.com/50469430/94116238-5cd43680-fe7d-11ea-9f26-4c5641e2177b.png)

I'm not sure whether it's my style or the video frame. It's confusing. But I guess it's about video frames.

## Platform

Android TV
All Android devices

## Environment info

    "react-native": "0.63.2",
    "react-native-video": "^4.4.5"

## Expected behaviour

1.Full screen playback

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
1、http://vjs.zencdn.net/v/oceans.mp4
2、https://vd4.bdstatic.com/mda-kdqhq0gq47n2zkvs/sc/mda-kdqhq0gq47n2zkvs.mp4

**Comment by Shuo-Mr** [comment]
Rescemode can solve this problem

**Comment by Shuo-Mr** [comment]
Rescemode can solve this problem

**Comment by paddy57** [comment]
@Shuo-Mr what is Rescemode ?

**Comment by IceDev-xyz** [comment]
"resizeMode"
