### ISSUE TITLE
Error Handling - AVFoundationError

### ISSUE THREAD

**Issue by enigmablue** [TheWidlarzGroup/react-native-video#2161]
Hi during the onError when i try to console it, all I get is

 { error: { code: -11800, domain: 'AVFoundationErrorDomain' },
  target: 209 }

Does anyone have a better way to find out whats causing it? I can't find any good way to JSON it
According to some google 11800 is just operation not completed.

**Comment by abdi4** [comment]
It looks like its a simulator issue, try using a different sim.
