### ISSUE TITLE
Could not play aacPlus radio streams 

### ISSUE THREAD

**Issue by InesR21** [TheWidlarzGroup/react-native-video#2164]
### Current behavior
Describe what happens when you encounter this issue.
I'm using react-native-video library for a Radio App, in order to play continuous MP3 and HE-AAC (aacPlus) audio streams over HTTP and HTTPS. 

### Reproduction steps
I set an HTTP or HTTPS URL on 'source' variable.as described below.

It works fine when playing MP3 streams, after a little buffering it starts to play audio. 

When playing aacPlus streams, it starts to download the continuous file but it doesn't play it. Just in case I interrupt the stream from the server side or if I disconnect the phone from the network, connection closes and the downloaded file starts to play immediately.

### Expected behavior
I want audio to start playing as soon as it start to download from server.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

### Video sample
http://streams.cloudradio.co/radio/8000/stream.aac
https://streams.cloudradio.co/radio/8000/stream.aac

**Comment by InesR21** [comment]
Problem was solved on Android forcing the use of ExoPlayer :)

**Comment by nguyenvanphuc2203** [comment]
how to forcing the use of ExoPlayer??
