### ISSUE TITLE
not working on android app release

### ISSUE THREAD

**Issue by geente** [TheWidlarzGroup/react-native-video#2165]
# Bug

 While in debug mode there is no problem with this, but when the android application is released this library doesn't work

**Comment by befirst** [comment]
@geente Have you found the reason?

**Comment by befirst** [comment]
duplicate https://github.com/react-native-video/react-native-video/issues/2092
the solution is to use SSL, for example use `https://somelink.com` instead of `http://somelink.com`

**Comment by ravi-roxiler** [comment]
@befirst the solution is not working.
