### ISSUE TITLE
Two videos play/pause at same in scrollview

### ISSUE THREAD

**Issue by Magudeshwaran** [TheWidlarzGroup/react-native-video#2169]
# Bug

Two videos play/pause at same in scrollview.
## Platform

Which player are you experiencing the problem on:
*Android 

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x
"react-native-video": "^4.4.5",
## Steps To Reproduce

1.Two or more videos in scrollview play/pause at same time returns overlapping of sound in each video.

...

## Expected behaviour

1. Current video in the screen needs to be played, other video should be paused.

## Reproducible sample code

 <ScrollView bounces={false} showsVerticalScrollIndicator={false}>
        {videos.map((video) => (
          <View
            key={video.id}
            style={{
              flex: 1,
              height: Dimensions.get('window').height,
              backgroundColor: '#010101',
            }}>
            <Video
              style={styles.backgroundVideo}
              source={video.url}
              resizeMode="cover"
              onTouchStart={() => setPaused(!paused)}
              paused={paused}
              playInBackground={false}
              playWhenInactive={false}
              repeat
            />
/>
## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by anshul-kai** [comment]
+1

**Comment by luisfuertes** [comment]
I have this method on FlatList. `cell` is react-native-video ref inside each cell.
But react-native-video doesn't have method play or pause :s 

```
  _onViewableItemsChanged = ({ viewableItems, changed }) => {
    console.log('viewableItems: ', viewableItems)
    console.log('changed: ', changed)

    changed.forEach(item => {
      const cell = this.playerRefs[item.key]
      console.log('cell: ', cell)
      if (cell) {
        if (item.isViewable) {
          console.log('item visible ', item.key)
          cell.play && cell.play()
        } else {
          console.log('item not visible ', item.key)
          cell.pause && cell.pause()
        }
      }
    })
  }
```

**Comment by Lyubomyr** [comment]
For me it's also strange that in video player there are no play/pause methods. Are there plans to add them?
