### ISSUE TITLE
building android fails

### ISSUE THREAD

**Issue by yonatanmn** [TheWidlarzGroup/react-native-video#217]
Hi, I have react-native@0.25.1
tried to install it with rnpm - changes to myApp/android/... were done,
when I do `~ react-native run-android`
I get: 

```

/Users/yonatan/avgenMobile/android/app/src/main/java/com/avgenmobile/MainActivity.java:4: error: cannot find symbol
import com.brentvatne.RCTVideo.ReactVideoPackage;
                              ^
  symbol:   class ReactVideoPackage
  location: package com.brentvatne.RCTVideo
/Users/yonatan/avgenMobile/android/app/src/main/java/com/avgenmobile/MainActivity.java:39: error: cannot find symbol
            new ReactVideoPackage()
                ^
  symbol:   class ReactVideoPackage
  location: class MainActivity
2 errors

```

**Comment by yonatanmn** [comment]
apparently the rnpm is broken. 
changed some files from 'react-native-video' to 'RCTVideo' and it's working

**Comment by mroswald** [comment]
For every wondering how to solve without touching node_modules:
Check `android/app/src/main/java/com/netoptv/MainActivity.java` and change

```
import com.brentvatne.RCTVideo.ReactVideoPackage;
```

to 

```
import com.brentvatne.react.ReactVideoPackage;
```

**Comment by ivanzhang** [comment]
@mroswald , thanks, it works

**Comment by beebase** [comment]
@mroswald , thanks! (wish I had read this 2 hours earlier)

**Comment by ducchungtx** [comment]
@mroswald thanks :)

**Comment by maygjor** [comment]
I have the same issue I couldn't find a solution, Please I need help.

`import com.brentvatne.react.ReactVideoPackage;
                                               ^
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactVideoPackage(),
                    ^
            new Interactable(),
            new VectorIconsPackage()
      );
    }
  };`

**Comment by arasemami** [comment]
Hi guys, I have the same issue,
package.json  -->

```  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-video": "^3.2.1",
    "react-native-video-controls": "^2.2.3"
  },
```

MainApplication.java ----->

```
import com.brentvatne.react.ReactVideoPackage;
```

```   @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactVideoPackage()
      );
    }```


settings.gradle ---->

`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
`
