### ISSUE TITLE
TextTracks are not being loaded on iOS

### ISSUE THREAD

**Issue by jfbn** [TheWidlarzGroup/react-native-video#2170]
# Bug

Setting textTracks via the textTracks prop does not correctly load.
The exact same implementation works on Android. 

## Platform
Bug is only present on iOS.

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.17 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ^0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.4.5

## Steps To Reproduce

1. Load textTracks to component like so:
```
<VideoPlayer 
  ....
  textTracks={[{title: 'english cc', language: 'en', uri: <a link to the subtitle>, type: TextTrackType.VTT}]}
  .... />
```

2. Verify it by checking the output from onLoad prop
```
onLoad={(e) => {
   console.log(e);
}}
```
The output on iOS: 
`{"audioTracks": [], "canPlayFastForward": false, "canPlayReverse": false, "canPlaySlowForward": false, "canPlaySlowReverse": false, "canStepBackward": false, "canStepForward": false, "currentTime": 0, "duration": 366.7200012207031, "naturalSize": {"height": 1080, "orientation": "landscape", "width": 1920}, "target": 3935, "textTracks": []}`

The output on Android: 
`{"audioTracks": [{"bitrate": "", "index": 0, "language": "und", "title": "2", "type": "audio/mp4a-latm"}], "canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 193.08, "naturalSize": {"height": 540, "orientation": "landscape", "width": 960}, "textTracks": [{"index": 0, "language": "en", "title": "N0tail_ep2.srt", "type": "text/vtt"}, {"index": 1, "language": "zh-Hans", "title": "EP02D.zh-si.zh.srt", "type": "text/vtt"}, {"index": 2, "language": "th", "title": "N0tail_ep2 (3).srt", "type": "text/vtt"}, {"index": 3, "language": "ru", "title": "N0tail EP02.ru.srt", "type": "text/vtt"}], "videoTracks": [{"bitrate": 0, "codecs": "", "height": 540, "trackId": "1", "width": 960}]}`

According to the documentation, sidecar textTracks are not supported on iOS for HLS streams. I don't think I am using HLS streams, as I am just feeding a .mp4 uri to the source prop to stream the video. I might be wrong. Its not specified anywhere in the documentation wether or not the default is HLS or whatever the alternative is.

**Comment by flexgrip** [comment]
No. If you're just popping in an mp4, then it's not HLS. HLS is not mp4. Well, at least not exactly.

**Comment by jfbn** [comment]
> No. If you're just popping in an mp4, then it's not HLS. HLS is not mp4. Well, at least not exactly.

Thanks for taking your time to reply to my issue. I'm glad to hear that I was correct in my assumption regarding HLS / Non-HLS.

Sadly I still cannot load textTracks on my iOS app. I don't know what else I can do to test at this point. I am on the verge of trying to create my own .srt reader component.

**Comment by flexgrip** [comment]
Have you tried using vtt? I will try this at some point too with my entire video library. Seems like all of the subtitle creation companies only like srt and all of the video players only like vtt.

**Comment by jfbn** [comment]
Same thing for .vtt.
It's interesting that neither the audioTracks nor the videoTracks load correctly on iOS either.

**Comment by flexgrip** [comment]
When I had other, unrelated issues with rnv, I tried downgrading a few versions.

It was a weird process. One time I tried downgrading, the thing I wanted to work was fixed, but then something else didn’t work. Finally found a working version after a few attempts.

I can’t remember. Does rnv have a textTrack example in the examples directory?

**Comment by jfbn** [comment]
I will resort to trying out different downgrades. Thanks for your feedback @flexgrip

**Comment by jfbn** [comment]
I don't suppose there are any updates on this? Downgrading has proven to be a unviable option for us.

**Comment by rogerkerse** [comment]
I have same problem, onLoad doesn't give textTracks on iOS. I have a hack solution that on iOS I render custom SRT overlay on top of the video.
This is definitely a bug.

**Comment by cinohub** [comment]
@rogerkerse  how did you do that. Can you give me some example load srt overlay. I have trouble when play srt subtitle in IOS device.

**Comment by shiprasharma12** [comment]
@rogerkerse Can you please tell me how did you load srt overlay?
