### ISSUE TITLE
Android Exoplayer won't play more than 1 video at once

### ISSUE THREAD

**Issue by DTX-Elliot** [TheWidlarzGroup/react-native-video#2171]
# Bug

Attempting to play more than 1 video using android exoplayer results in only the last rendered video playing and the previous rendered videos all to pause. This happens within 1 screen in a flatlist, across multiple components in a screen and also across multiple screens. 

## Platform
* Android ExoPlayer

## Environment info
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 15.17 GB / 31.94 GB
  Binaries:
    Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: Not Found
    Python: 2.7.18 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1
    react-native: ^0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.0-alpha8

## Steps To Reproduce

1. Create a blank react native app and install react-native-video with exoplayer
2. Create a screen containing a video with props 'Repeat = true' and 'Paused = false'. This video should auto play when navigating to this screen
3. On the same screen as above, create a button that takes you to another screen with a video on it with the same props as above. This video should also play. 
4. Navigate back to the original screen and the video will have paused. This behaviour doesn't happen with the standard android media player.

Also, the app I am trying to make has a horizontal flatlist on a page that renders a video in each flatlist item. Every time I add another item to the flatlist, the previous video will pause and sometimes rotates the paused video 90 degrees anticlockwise. No idea why and won't fix itself until a full app reload. Doesn't happen all the time. 

EDIT: The video rotation is caused by an Android Emulator issue and does not happen in production on a physical device so this can be discounted. 

## Reproducible sample code

code for each video: 

`    <Video
      source={{
        uri: 'video.mp4',
      }}
      repeat={true}
      muted={true}
      paused={paused}
      playWhenInactive={true}
      playInBackground={true}
      resizeMode={'cover'}
      style={{
        height: '100%',
        width: '100%',
      }}
    />`

Thanks for your time, hope someone can help me!

**Comment by janpe** [comment]
Our team is having this issue as well.

**Comment by DTX-Elliot** [comment]
I fixed it by rolling back to react-native-video^4.4.5 but the problem still persists in the latest version 5 release

**Comment by anshul-kai** [comment]
+1

**Comment by alexstroukov** [comment]
Im having the similar issues issue but rolling back to 4.4.5 does not fix it.

In my case I have about 3 or 4 `<Video />` elements rendered. And they work initially. But using `seek` causes them to stop buffering and no longer calls `onProgress`. If i start using one of the other 3 rendered `Video` elements it kicks it back into gear and continues buffering and playing.

The issue does not happen if only one `Video` is rendered

edit:
the issue does not happen with .m3u8 videos

**Comment by kartavyaparekh96** [comment]
+1

**Comment by caijiami** [comment]
> 我有类似的问题，但是回滚到4.4.5不能解决。
> 
> 就我而言，我`<Video />`渲染了大约3或4个元素。他们开始工作。但是使用`seek`会导致它们停止缓冲并且不再调用`onProgress`。如果我开始使用其他3个渲染`Video`元素之一，它将使其重新适应并继续缓冲和播放。
> 
> 如果仅`Video`渲染一个，则不会发生此问题
> 
> 编辑：
> .m3u8视频不会发生此问题

Have you solved it? I've had this problem too

**Comment by afilp** [comment]
I have the same problem, anyone knows any fix? Thanks!
