### ISSUE TITLE
Hello, How to play local m3u8 video on iPhone？

### ISSUE THREAD

**Issue by SemperChen** [TheWidlarzGroup/react-native-video#2172]
# Bug

## IPhone can't read local m3u8 video
`<Video

                    ref={ref => this.video = ref}
                    muted={false} //控制音频是否静音
                    repeat={false} //确定在到达结尾时是否重复播放视频。
                    onEnd={this._onEnd} //视频播放结束时的回调函数
                    paused={this.state.paused} //暂停
                    rate={rate[this.state.rateIndex]}//播放速率
                    repeat={false}
                    playInBackground={false}
                    allowsExternalPlayback={false}
                    ignoreSilentSwitch={'ignore'}
                    onSeek={this._onSeek}
                    onProgress={this._onProgress} //视频播放过程中每个间隔进度单位调用的回调函数
                    onBuffer={this._onBuffer} //远程视频缓冲时的回调
                    onLoadStart={this._onLoadStart}
                    onLoad={this._onLoad} //加载媒体并准备播放时调用的回调函数。
                    onError={this._onError}               // 播放失败后的回调
                    resizeMode="contain" //缩放模式
                    controls={false}
                    style={{ width: videoWidth, height: videoHeight, backgroundColor: 'black' }} //组件样式
                    // source={url}
                    source={{uri:'file:///var/mobile/Containers/Data/Application/864B4C59-A2AB-4C5E-BE75-3FE5ECC7B9E4/Library/ColaApp/20180706/17936_ff747f2d/index.m3u8', type: 'm3u8'}}
                >
</Video>`
## Expected behaviour
How to play local m3u8 video on iPhone？

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 2.33 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    "react-native-video": "^5.1.0-alpha8",

**Comment by ignaciosantise** [comment]
@SemperChen i had the same issue, try removing the `paused` prop. I think there's a bug with that prop

**Comment by SemperChen** [comment]
> @SemperChen i had the same issue, try removing the `paused` prop. I think there's a bug with that prop

Hello, can IOS play local m3u8 video？If not, is there a native solution？

**Comment by SemperChen** [comment]
@ignaciosantise  Hello, can IOS play local m3u8 video？If not, is there a native solution？

**Comment by ignaciosantise** [comment]
Hello @SemperChen , i think it should play them good, but i really dont know. The documentation says this in relation to local videos:

`Note: Your app will need to request permission to read external storage if you're accessing a file outside your app.`

**Comment by Strate** [comment]
iOS don't play local m3u8 videos. You should use mp4

**Comment by timothysantos** [comment]
> @SemperChen i had the same issue, try removing the `paused` prop. I think there's a bug with that prop

Hi @ignaciosantise , have you really managed to play .m3u8 file from local on iOS? if so, do you mind sharing how was it done?
