### ISSUE TITLE
my stream format MPEG-ts  not work 

### ISSUE THREAD

**Issue by polo13999** [TheWidlarzGroup/react-native-video#2174]
# Feature Request
 
 My stream format is MPEG-ts react-native-video   seems  not to support

  https://clawfun.online/video/1

### Code sample

        //  const uri = 'wss://clawfun.online/nof1'    <---   not work
        //  const uri = { uri: 'http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8' }  <--- it's work

            const player = <Video source={uri} ref={(ref) => { this.player = ref }} />

**Comment by evilchis94** [comment]
I'm using react-native-video@5.1.0-alpha8 playing HLS videos from my server and it's working on both Android and iOS, be sure your server content type response is **application/x-mpegURL** for your m3u8 files and **video/mp2t** for your ts files.

**Comment by polo13999** [comment]
does need any setup in the source? 
ex.
    const uri = {
            uri: 'https://claw.fun/nof1',
            header :{type or other...}
        }
