### ISSUE TITLE
@arslan-akh have you tried the basic example : https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk/examples/basic ?

### ISSUE THREAD

**Issue by cbawebdesign** [TheWidlarzGroup/react-native-video#2186]
Hi Robby,

thank you so much for this branch. I just cant seem to get the basic example working. 

I simply just clone it and run Yarn in the main directory correct?

Do I have to do anything as far as linking? or doing anything with the pod files. 

Your help would be greatly appreciated. Thank you!!

**Comment by robbywh** [comment]
Hello @cbawebdesign, you can just clone it, and go to the `examples/basic` directory, and yarn it  from there,

btw what platform do you want to test ?

**Comment by pragathi765** [comment]
why it is not supported to drm encrypted videos?
