### ISSUE TITLE
onPictureInPictureStatusChanged method is not working

### ISSUE THREAD

**Issue by NazarKuryl0** [TheWidlarzGroup/react-native-video#2187]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 1023.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 21, 27, 28, 29
      Build Tools: 26.0.2, 27.0.2, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-21 | Android TV Intel x86 Atom, android-21 | Intel x86 Atom_64, android-27 | Android TV Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.0-alpha8

## Steps To Reproduce

1. Init new react-native project
2. Add react-native-video (year add react-native-video)
3. npx pod-install
4. Add in Xcode background modes with PIP 
5. Create component like in reproducible sample code
6. run it on iOS
7. When tap on button for switching into PIP mode, onPictureInPictureStatusChanged method is not called

## Expected behaviour

When tap on button for switching into PIP mode, onPictureInPictureStatusChanged method i called

## Reproducible sample code

<SafeAreaView style={{flex: 1}}>
    <Video
        style={{width: '100%', height: 350}}
        controls
        source={{uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'}}
        ignoreSilentSwitch="ignore"
        pictureInPicture
        onPictureInPictureStatusChanged={(props) =>console.log('PIP STATE CHANGE', props)}
    />
</SafeAreaView>

Any ideas, why onPictureInPictureStatusChanged method is not working?

**Comment by pmayer** [comment]
I'm having the same issue. Is it somehow possible to get the picture in picture status differently?

**Comment by vstoyanoff** [comment]
Same here. The event does not fire at all.

**Comment by pmayer** [comment]
Just for information –  onPictureInPictureStatusChanged only works if controls = false

**Comment by vstoyanoff** [comment]
But if there are no controls how to get into PiP mode? Or I am missing something :/

**Comment by angleneo** [comment]
the same problem...

**Comment by fielddaychurch** [comment]
Tracking this issue. We're having the same issue.

**Comment by therveux** [comment]
I'm facing the same issue did you find something ?

**Comment by megabayt** [comment]
Any update on this?

**Comment by CDBridger** [comment]
bump, still have this issue

**Comment by Mass812** [comment]
bump, have issue v5.2.0

**Comment by sonal-maniya** [comment]
still facing this issue
 any update?
