### ISSUE TITLE
Seek method not working on Android

### ISSUE THREAD

**Issue by ignacioiglesias43** [TheWidlarzGroup/react-native-video#2188]
# Bug

Hi, I am trying to make an audio player, everything works fine except for the seek () method.

I am using redux to manage the state, as you can see in the screenshots below.

The problem occurs when I try to call the seek () method, it does nothing, it just continues to play the audio, and then ignores the _paused_ prop, I've already checked if _paused_ is changing, and it does.

I don't know if I am doing something wrong or what is happening.

Screenshots:
![image](https://user-images.githubusercontent.com/51436771/96792729-3d66f580-13b8-11eb-91bb-533540475a3f.png)
![image](https://user-images.githubusercontent.com/51436771/96792752-48ba2100-13b8-11eb-8626-b5966686a7e4.png)

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.32 GB / 7.86 GB
  Binaries:
    Node: 12.18.3 - ~\AppData\Local\Temp\yarn--1603318474735-0.16065955500628037\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1603318474735-0.16065955500628037\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    Visual Studio: 16.3.29409.12 (Visual Studio Community 2019)
  Languages:
    Java: 12.0.1
    Python: 3.8.5
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^5.1.0-alpha8

**Comment by tomislav-s** [comment]
Having a similar problem - in my case every time the `seek` function is called on Android it just restarts the video from 00:00. It works fine on iOS.

React Native version: 0.63.3
Library version: 5.1.0-alpha8

**Comment by ignacioiglesias43** [comment]
> Having a similar problem - in my case every time the `seek` function is called on Android it just restarts the video from 00:00. It works fine on iOS.
> 
> React Native version: 0.63.3
> Library version: 5.1.0-alpha8

If you find a solution please share it :( thx

**Comment by k-cactus** [comment]
same problem with android, ios works perfect...

**Comment by androidparth90** [comment]
I have the same problem as well. It seems from other threads that the solution for this is to update Exo player. Any idea how this can be done?

**Comment by BadtzMaru** [comment]
Same problem with android, ios works perfect!

**Comment by freeboub** [comment]
I never saw such issue.
Can you provide a sample stream ? Are you able to reproduce on sample from the project on master branch ?
