### ISSUE TITLE
Audio Not On Working On IOS 13.7

### ISSUE THREAD

**Issue by nescroft** [TheWidlarzGroup/react-native-video#2190]
Reported to me by one of our testers. They can't hear anything even with the silence switch off and volume turned up. I am unable to replicate the issue on ios 14. They said someone they were testing with had the same issue. Anyone have the same issue?

**Comment by ghost** [comment]
same issue here. I also opened #2197 wondering if you are experiencing that. Have you found any work around for any?

**Comment by nescroft** [comment]
@joserenev i am able to play videos fine and i am not using player controls so i wouldn't know. i just had the audio problem. but i have not found any work around mostly because i am unable to replicate the issue at the moment. it was just reported to me.

**Comment by mauricioac** [comment]
We are also having this issue. Testers reporting the problem, but devs unable to replicate the issue.
