### ISSUE TITLE
Video not showing on iOS

### ISSUE THREAD

**Issue by harrymash2006** [TheWidlarzGroup/react-native-video#2195]
I am trying to display video which was working fine until I upgraded to Xcode 12.1 or React native 0.63.3. It is showing blank. Please help urgently.

**Comment by khuccui2002** [comment]
![image](https://user-images.githubusercontent.com/48780373/97677924-9b38c300-1ac5-11eb-968e-52222280f2a7.png)
No play button.

I had the same problem with you, It seems like the play button doesn't show with iOS 14.1. All good with 14.0 and below.
I was using 4.4.4 and tried with 5.0.0 but no luck with me. Please check.
Thanks.

**Comment by harrymash2006** [comment]
I tried with all iOS 14.1, iOS 13.7, iOS 12.x but none of it works.

*Thanks,*
*Hardik Mashru*
Providing freelance services in Android, iOS, React Native, Java, J2EE,
Restful Web Services, Core PHP, Struts, Hibernate

**Comment by dharmikumbhani** [comment]
Any solutions? Facing the same issue on iOS 14 after upgrading to react-native 0.63.3 from 0.61.4. Currently using react-native-video 4.4.5

**Comment by khuccui2002** [comment]
For now, you can turn on autoplay and it works

**Comment by dharmikumbhani** [comment]
Autoplay isn't really a viable option for my app. Weird that the maintainers haven't even acknowledged this issue, or am I missing something.

**Comment by khuccui2002** [comment]
This is a bug on iOS 14, I hear about it works again with iOS 14.2 (not sure). 
You can trigger video to stop after auto play is on or wait until the owner fixes this bug.

All good with iOS 13 and below.

**Comment by dharmikumbhani** [comment]
Can confirm, it's working perfectly fine with iOS 14.2. Thanks a lot @khuccui2002 !

**Comment by josevalb** [comment]
is this related to #2197 ?
