### ISSUE TITLE
Video not showing on Android (RN 0.60.6)

### ISSUE THREAD

**Issue by joshua-augustinus** [TheWidlarzGroup/react-native-video#2196]
# Bug

Video not showing on Android. Using react-native 0.60.6

## Platform
Android

## Environment info

react-native-video version: 5.1.0-alpha8
```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 2.06 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1. See sample code and minimal git repo below.

## Expected behaviour

Video shows

## Reproducible sample code

https://github.com/joshua-augustinus/rn-training-video

```
const VIDEO_URL = "https://filesamples.com/samples/video/mp4/sample_1280x720.mp4";

const VideoContainer = ()=>{
    const onBuffer=()=>{}
    const videoError=()=>{}

    return (<Video source={{uri: VIDEO_URL}}   
                                      
    onBuffer={onBuffer}                
    onError={videoError}               
    style={styles.backgroundVideo} />
)
}

export {VideoContainer}

// Later on in your styles..
var styles = StyleSheet.create({
    backgroundVideo: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      backgroundColor:'blue'
    },
  });
```

## Video sample
N/A

**Comment by joshua-augustinus** [comment]
OK I think I might know the issue. Even though autolinking should work on RN 0.60 do I still need to some manual steps for Android?

**Comment by joshua-augustinus** [comment]
Needed to do manual steps

**Comment by leandro-faria** [comment]
@joshua-augustinus what are the manual steps you had to do for Android? I'm still facing this issue, but only for some videos, of certain urls. This example you posted `https://filesamples.com/samples/video/mp4/sample_1280x720.mp4` still doesn't work, but some urls do work

**Comment by joshua-augustinus** [comment]
If you go to: https://github.com/react-native-video/react-native-video
then go to Android installation there will be some manual steps listed. It is listed under: _"Or if you have trouble, make the following additions to the given files manually:"_

Also that video file I used takes a while to load so try waiting a fair bit.
