### ISSUE TITLE
Play Button from controls is disappearing. Not able to play videos

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#2197]
Play button hides shortly after rendering the video. I am setting controls={true} and paused={true}. version 5.0.2. Help

iOS 14+ simulator

**Comment by kiritm-nimblechapps** [comment]
Yes, I have same issue, I can't play the in iOS 14+, In older version it's working.

**Comment by 0x41rtur** [comment]
I have same issue, I can't play the in iOS 14+, In older version it's working.

**Comment by djpane** [comment]
Same issue here. Doing a pinch to zoom on the video component will reveal the play button. Other issues suggest that iOS 14.2.+ fixes this problem. Will try that.
