### ISSUE TITLE
How to hide ios controls in full screen mode

### ISSUE THREAD

**Issue by vinothkumartyson** [TheWidlarzGroup/react-native-video#2198]
I want to hide ios controls in fullscreen mode. When i run video in potrait mode default ios control is not displaying but if i change Landscape mode, It shows ios controls

**Comment by MattHorriganSunrise** [comment]
I was wondering the same, because I am building all custom controls. The way I accomplished this is `isFullScreen` conditional CSS, have a container on your video.

```
width: Dimensions.get('window').width,
height: Dimensions.get('window').height,
```
may also be useful, its a pain but it works.
