### ISSUE TITLE
Document how to use Example

### ISSUE THREAD

**Issue by brianchirls** [TheWidlarzGroup/react-native-video#22]
I'd appreciate an explanation, either here or in the README, of how to use the included Example. It looks like it includes a project file that references another RCTVideo project file which in turn references .h and .m files that don't exist.

Ideally, the example would somehow refer to the RCTVideo sources at the top of the repo so it could be used for testing/developing those files. I'm trying to figure it out and will advise if I come up with anything.

**Comment by brentvatne** [comment]
@brianchirls - hm I must have done something weird there, I'll fix it if you haven't already

**Comment by brentvatne** [comment]
@brianchirls - did you do `npm install` from the example project directory?

**Comment by brianchirls** [comment]
Okay, I just pulled the latest version, and now it's working. Thanks.

Looks like the example is using the version of `react-native-video` from npm. Is there a way to get it using the one in the repo?

**Comment by brentvatne** [comment]
@brianchirls - you could remove it from package.json and do `npm install path-to-your-local/react-native-video` :smile:

**Comment by brentvatne** [comment]
@brianchirls - some people find it easier to use `npm link`, but there is a bit more set up involved in getting that going in the first place

**Comment by brentvatne** [comment]
Closing the issue, feel free to re-open if problem re-arises!

**Comment by brianchirls** [comment]
`npm link` works great for a second, but it throws off XCode at some point.

**Comment by brentvatne** [comment]
@brianchirls - ah, I personally just do `npm install` with the path to the repo on my local machine

**Comment by brianchirls** [comment]
Yeah, that works too, but it's not very good for developing. You have to delete and re-install the package every time you make a change.

**Comment by brentvatne** [comment]
@brianchirls - I typically just work from the `node_modules` package directory and then copy that back into the project directory

**Comment by brentvatne** [comment]
If you find out a better way, let me know :smile:

**Comment by brianchirls** [comment]
I've tried a few different ways, and none of them have been good. XCode and the react-native webserver don't update symlinked files, presumably because the timestamps don't change when the original gets modified. working out of `node_modules` is the least bad option so far, but that extra step is pretty annoying.

I think the problem with referring to the sources in the parent directory is that it throws off XCode's includes. Maybe there's a way to shift the directory structure around so neither the main project file nor the example project files are at the top level, so neither is inside the other. I think that's how [react-native](https://github.com/facebook/react-native) does it.
