### ISSUE TITLE
super expression must either be null or a function, not undifined

### ISSUE THREAD

**Issue by andyfen** [TheWidlarzGroup/react-native-video#220]
getting this message when i copy over the example code, looks like its coming from Video.js ?

any suggestions ?
<img width="365" alt="screen shot 2016-05-19 at 16 26 27" src="https://cloud.githubusercontent.com/assets/5710962/15412705/7d04b468-1dde-11e6-813d-176ec7afef5d.png">

**Comment by andyfen** [comment]
i don't think this is specific to this module, think its a RN issue. Closed

**Comment by zimplexing** [comment]
@andyfenelon are you solved this problem?  if solved,how to solved? i also had this problem

**Comment by andyfen** [comment]
i really can't remember sorry.
