### ISSUE TITLE
when prop called repeat is true，the onEnd is not called

### ISSUE THREAD

**Issue by xiaozhu188** [TheWidlarzGroup/react-native-video#2202]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by el-lsan** [comment]
I am facing the same issue.
onEnd won't be called on Android when repeat props is true.
However on IOS it works fine.
Any solution ?
