### ISSUE TITLE
Building react native app as Android module embedded in another Android app does not play video

### ISSUE THREAD

**Issue by thaddavis** [TheWidlarzGroup/react-native-video#2204]
I am trying to build a react-native module in my Android app using the technique outlined here:

https://reactnative.dev/docs/integration-with-existing-apps

I am able to build a screen where I can browse through a list of movies and when I click a movie title I launch that video in react native video. But launching the video crashes my Android app and causes the app to restart.

Does react-native only autolink properly in standalone Android React native apps or is there a way to make it work in Android modules?

**Comment by gauravsbagul** [comment]
I have the same issue, I want to show the embedded video in the player, but it gives error. 
```
<Video
          style={styles.videoPlayerWrapper}
          videoStyle={styles.videoStyle}
          CustomVideoWrapper={TouchableWithoutFeedback}
          playInBackground={false}
          playWhenInactive={false}
          disableFullscreen
          disableBack
          showOnStart={false}
          source={{
            isNetwork: true,
            uri:
              "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/TXZHugREvDqMygARpeSdvTVC",
            type: "MOV",
          }}
        />
```
