### ISSUE TITLE
Error when install Video with caching

### ISSUE THREAD

**Issue by vinhtran6921** [TheWidlarzGroup/react-native-video#2207]
# Bug

I install video with caching as document mention. But I can't install pod
<img width="883" alt="Screen Shot 2020-11-11 at 14 24 58" src="https://user-images.githubusercontent.com/53859772/98782254-3d439e00-242a-11eb-8a79-f829db34f126.png">
<img width="765" alt="Screen Shot 2020-11-11 at 14 24 33" src="https://user-images.githubusercontent.com/53859772/98782271-43397f00-242a-11eb-9d74-1c171bad0931.png">

**Comment by steventilator** [comment]
@vinhtran6921 You have to include the line above `use_native_modules!`

```
target 'AppName' do

  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
  
  config = use_native_modules!

  # rest

end
```
