### ISSUE TITLE
After Pick a video or capture the video it goes stretched for no reason iOS

### ISSUE THREAD

**Issue by summonerriftofficial** [TheWidlarzGroup/react-native-video#2211]
# Bug

After Pick a video or capture the video it goes stretched for no reason

![image](https://user-images.githubusercontent.com/52756966/99364344-e9700380-28c6-11eb-8596-1e112d0e900b.png)

it happens in iOS 14.1

my code

```
          <Video source={{ uri: this.state.uri }}
            onLoad={this._onLoad}
            ref={(ref) => {
              this.player = ref
            }}
            resizeMode="cover"
            repeat
            style={{
              position: 'absolute', 
              top: 0,
              left: 0,
              bottom: 0,
              right: 0,
            }} />
```

**Comment by yernandus** [comment]
same issue

**Comment by yernandus** [comment]
> # Bug
> After Pick a video or capture the video it goes stretched for no reason
> 
> ![image](https://user-images.githubusercontent.com/52756966/99364344-e9700380-28c6-11eb-8596-1e112d0e900b.png)
> 
> it happens in iOS 14.1
> 
> my code
> 
> ```
>           <Video source={{ uri: this.state.uri }}
>             onLoad={this._onLoad}
>             ref={(ref) => {
>               this.player = ref
>             }}
>             resizeMode="cover"
>             repeat
>             style={{
>               position: 'absolute', 
>               top: 0,
>               left: 0,
>               bottom: 0,
>               right: 0,
>             }} />
> ```

did you find a solution?

**Comment by yernandus** [comment]
@summonerriftofficial did you find a solution?

**Comment by iphonic** [comment]
@hueniverse Was this issue fixed? It still happens especially on iOS.
