### ISSUE TITLE
Play multiple videos not Working or Autoplay option 

### ISSUE THREAD

**Issue by Deep-CB** [TheWidlarzGroup/react-native-video#2214]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 "react-native": "0.63.2",
  "react-native-video": "^5.1.0-alpha8",


## Steps To Reproduce

<!--
 Issues without reproduction steps or code are likely to stall.
-->

1.
2.
...

## Expected behaviour

1.currently play singe uri video 
need multiples videos will play after completing one by one 

## Reproducible sample code

<!--
 Please add to your issue a repro, a fresh codebase with the minimal changes so that the bug can be tested in isolation
-->

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by jphim281** [comment]
I have also multiple videos in flatlist. But If I use autoPlay then all videos plays automatically. If I use paused:{true} then No video information such as thumbnail. I am not uploading thumbnail with video uloading. I am stuck here. 
Using: react native hooks, react-native-video. Any solution?
Like only that video should be play which is on screen, Not all.

**Comment by mdmidulhosen** [comment]
Use these props

disableFocus={true}
playWhenInactive={true}
playInBackground={true}

**Comment by AmirXpertPrime** [comment]
this solution work for me
