### ISSUE TITLE
Possible to go full screen when video inside FlatList without having to buffer again?

### ISSUE THREAD

**Issue by joshua-augustinus** [TheWidlarzGroup/react-native-video#2217]
# Feature Request

What I want is the ability to go full screen when the video is inside a FlatList. I can't go full screen while the component is inside the FlatList so I need a new screen for the full screen video. If I were to create a new screen to place the full screen video in, I lose whatever I buffered when the video was in the FlatList.

## Why it is needed

Scenario: 
You present a feed of videos to the user. You have a button on each video to go full screen. The user presses the button and the user should be presented with the fullscreen video but shouldn't have to re-download/buffer the video again.

## Possible implementation

Is it possible for components on seperate screens to share the same buffered video?

**Comment by orzhtml** [comment]
The same problem

**Comment by roycehe** [comment]
+1

**Comment by roycehe** [comment]
The same problem

**Comment by rzinnatullin** [comment]
Yes, please, any solution?

**Comment by iljaiwjew** [comment]
+1

**Comment by imamark** [comment]
+1

**Comment by marlti7** [comment]
The same problem, any solution?

**Comment by freeboub** [comment]
This feature is still needed... Can be linked to pip also, but needs architecte changes and Big changes on apps i think.
I explain the pip use case on Android:
When you go to pip, the whole activity goes to pip.
User wants to put the video in pip but continue browsing app catalog. Here we 2 activities... So the need is go be able to detach the player from an activity and reattach it to a second one...
A tricky use case, but usefull
