### ISSUE TITLE
QUESTION: shouldCache and isNetwork?

### ISSUE THREAD

**Issue by tjlondon-npauctions** [TheWidlarzGroup/react-native-video#2218]
Hey folks,

Sorry if this is covered somewhere, but I couldn't find anything in the docs or searching.

I see the `source` prop accepts a few fields, specifically `shouldCache` and `isNetwork`.

Does anyone have an explanation of how these work, are they platform specific and can they be used? 

Thanks for everyones hard work, great package!

**Comment by nikohpng** [comment]
in video.js, you will find this。`const shouldCache = !source.__packager_asset;` if your source come from network, `shouldCache `will be `true`
