### ISSUE TITLE
On ios, if you put the app in the background for a few seconds and then put it in the foreground, the video goes black for a few seconds

### ISSUE THREAD

**Issue by caijiami** [TheWidlarzGroup/react-native-video#2221]
On ios, if you put the app in the background for a few seconds and then put it in the foreground, the video goes black for a few seconds

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 182.68 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v13.13.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by caijiami** [comment]
@jsierles @danhodos @peterblazejewicz @qingfeng

**Comment by VenAug** [comment]
I had the same problem

**Comment by irekrog** [comment]
Bug still occurs (on older iOS systems such as iOS 15, on iOS 18 it is fine).
