### ISSUE TITLE
Pass the decryption key to the video directly

### ISSUE THREAD

**Issue by florinlazau** [TheWidlarzGroup/react-native-video#2223]
Hello, 

We are working on a streaming application and we want to have AES encrypted streaming. The video source is already streaming in an encrypted format using all streaming protocols DASH, HLS, and Smooth. We have the encryption key and the initialize vector but I couldn't find a way to pass them to the Video component.  

We have discovered the [DRM](https://github.com/react-native-video/react-native-video/blob/master/DRM.md#type) support but we would prefer not to go with a license server that seems to be more time-consuming. 

Any help would be appreciated. 

Many thanks, 
Florin

**Comment by TheNaman047** [comment]
Any update on this?
