### ISSUE TITLE
VideoPlayer crashed in IOS when I load video from CameraRoll

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [TheWidlarzGroup/react-native-video#2224]
My Environment Seeting
**MacOS BigSur 
Node 15 
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-video": "^5.1.0-alpha8",
**

Here is my code to reproduce the Iuuse. 
`import React from 'react';
import {View,Text, StyleSheet, Dimensions, Platform} from 'react-native';
import Video from 'react-native-video';
import { heightPercentageToDP as hp, widthPercentageToDP as wp,} from 'react-native-responsive-screen' 

  const { width } = Dimensions.get('window');
    const videoplayer = ({route}) =>{
      return (
          <View style={{height:'100%', backgroundColor:"black",width:'100%'}}>
            <Text style={{color:"#fff"}}>{route.params.file}</Text>
              <Video
                  rate={ 1.0 }
                  volume={ 1.0 }
                  muted={ false }
                  controls={Platform.select({ ios: true, android: false })}
                  paused={false }
                  resizeMode={ 'cover' }
                  repeat={ false }
                  playInBackground={ false }
                  playWhenInactive={ false }
                  onLoadStart={() => console.log('On Load Start') }
                  onLoad={ () => console.log('On Loaded') }
                  onProgress={ () => console.log('On Progress') }
                  onEnd={ () => console.log('On Ended')}
                  onError={ () => console.log('On Error')}
                  ignoreSilentSwitch={ "ignore" } 
                  source={{uri:`${route.params.file}`}}
                  controls={Platform.OS === 'ios'?true:false}
              />
          </View>
      )
    }
export default videoplayer ;
const styles = StyleSheet.create({ 
  
  overlay: {
    ...StyleSheet.absoluteFillObject,
    position:'absolute', 
    bottom:hp(1), 
    alignItems:"center", 
    justifyContent:"flex-end", 
    flex:1, 
    backgroundColor:'rgba(0,0,0,.3)'
  },
  
  overlaySet: {
    flex: 1,
    flexDirection: 'row'
  },

  control:{
  //  position:"absolute", 
    flexDirection:"row", 
    justifyContent:'space-between',
    paddingHorizontal: 5,
    alignItems:'flex-start' ,
    bottom:10,  
    width:('100%')
  },

  icon: {
    color: 'white',
    flex: 1,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize:20
  },
  
  sliderCont: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 40,
    height:40,
  },
  timer: {
    width: '95%',
    alignSelf:'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
    // bottom:60
  },
  video: { 
    width, 
    height: width * .6, 
    backgroundColor: 'black'
  },
  fullscreenVideo: {
    backgroundColor: 'black',
     height:150,
     elevation: 1
  }
});`

Her bus the iuuse 
![WhatsApp Image 2020-11-27 at 10 38 34 AM](https://user-images.githubusercontent.com/72066902/100415067-14174480-309d-11eb-90b4-1472d83dc50b.jpeg)
![WhatsApp Image 2020-11-27 at 10 38 42 AM](https://user-images.githubusercontent.com/72066902/100415081-1a0d2580-309d-11eb-8de0-a4c2f131444b.jpeg)
![WhatsApp Image 2020-11-27 at 10 38 47 AM](https://user-images.githubusercontent.com/72066902/100415092-1ed1d980-309d-11eb-8bc5-9af2771c1fde.jpeg)
![WhatsApp Image 2020-11-27 at 10 38 52 AM](https://user-images.githubusercontent.com/72066902/100415098-21ccca00-309d-11eb-95e2-9fb2ec8d2439.jpeg)

Here is my video object : `{ key: '1606394256.4853153',
    size: '2.22 MB',
    date: '26-Nov-2020',
    uri: 'ph://1351317F-49BA-4F96-9F1E-C1FB7D8FDADB/L0/001',
    name: 'FB_VID_1606394256438.mp4' }`

**Comment by IkeyBenz** [comment]
@aftabaminzoobiapps I was having the same problem, I used `react-native-convert-ph-asset` to convert the video uri from camera roll to have the supported 'file://' prefix.

See more here: https://github.com/jzyds/react-native-convert-ph-asset#usage

**Comment by seancheung** [comment]
> @aftabaminzoobiapps I was having the same problem, I used `react-native-convert-ph-asset` to convert the video uri from camera roll to have the supported 'file://' prefix.
> 
> See more here: https://github.com/jzyds/react-native-convert-ph-asset#usage

This copies the video which is not the best option

**Comment by IkeyBenz** [comment]
> > @aftabaminzoobiapps I was having the same problem, I used `react-native-convert-ph-asset` to convert the video uri from camera roll to have the supported 'file://' prefix.
> 
> > 
> 
> > See more here: https://github.com/jzyds/react-native-convert-ph-asset#usage
> 
> 
> 
> This copies the video which is not the best option

Yep, it turned out to be way too u performant to use in production. Ended up killing it and opting for the native gallery picker instead.

**Comment by hueniverse** [comment]
Consolidated into #2652
