### ISSUE TITLE
iOS 14.2 video stops when receive a phone call

### ISSUE THREAD

**Issue by rcpassos** [TheWidlarzGroup/react-native-video#2225]
# Bug

I've been facing an issue in iOS 14.2 when I'm playing a video and receive a phone call (top call notification), the video stops. 
I'm using the last version of this library.

## Platform

Which player are you experiencing the problem on:
* iOS 14.2

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 21.53 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.0.2

## Steps To Reproduce

1. Start a video
2. Receive a phone call
3. Video will stop

## Expected behaviour

1. Start a video
2. Receive a phone call
3. Video continues playing

**Comment by fabiocarreto** [comment]
Hi,

I have the same issue, any news about it?

**Comment by rp-pipecodes** [comment]
I have the same issue. Any news about this? More info needed?

**Comment by ghost** [comment]
have anyone resolved this issue?
@rcpassos
