### ISSUE TITLE
Switch from ExoPlayer to MediaPlayer

### ISSUE THREAD

**Issue by guillaume-g** [TheWidlarzGroup/react-native-video#2226]
### Current behavior
Hi,

I am using the latest version of react-native-video.
I would like to know how do I switch from using ExoPlayer to MediaPlayer ?

I need to read a video in a specific format, which is not supported by ExoPlayer.
I see that you always specify "Android MediaPlayer", but how do we switch ?

Thanks in advance,

**Comment by Rileyp33** [comment]
Check out this section in the readme: https://github.com/react-native-video/react-native-video#androidsettingsgradle
