### ISSUE TITLE
Video does not continue to play in background in ios 14+

### ISSUE THREAD

**Issue by saraband** [TheWidlarzGroup/react-native-video#2228]
# Bug

Video does not continue to play while in background even though props are set so it should:

```
playInBackground={true}
playWhenInactive={true}
ignoreSilentSwitch="ignore"
```

I also verified xcode target capabilities
<img width="466" alt="Screenshot 2020-11-30 at 09 38 33" src="https://user-images.githubusercontent.com/39649144/100586844-0efe0380-32f0-11eb-813d-0578b7369817.png">

## Platform

I witnessed this bug in iOS 14.0 (from the Xcode simulator - Iphone 11); This bug does not seem to be occurring on iOS < 14

## Environment info

```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.44 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.63.3

## Steps To Reproduce

1. Launch an app with a video that should be allowed to play in the background in >= iOS 14

```
import Video from 'react-native-video';

<Video
  source={{ uri }}
  controls={true}
  paused={false}
  playInBackground={true}
  playWhenInactive={true}
  ignoreSilentSwitch="ignore"
/>
```

2. Go to home screen/let the app run in the background, the video will stop playing

## Expected behaviour

1. The video should be playing in the background

## Reproducible sample code

I recreated a project from scratch, changed the target capabilities so background mode is activated, re-built with xcode, then inserted a simple video that should have been allowed to play in the background, eg:

```
<Video
  source={{ uri: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4' }}
  style={{ aspectRatio: 16 / 9, width: '100%' }}
  controls={true}
  paused={false}
  playInBackground={true}
  playWhenInactive={true}
  ignoreSilentSwitch="ignore"
/>
```

## Video sample

Occurs with any video, this one for example https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4

**Comment by iacocesar** [comment]
for curiosity if you set ignoreSilentSwitch="ignores" works fine and not get a yellow message =/
