### ISSUE TITLE
Can't stop video if AppState was changed to "background" on Android

### ISSUE THREAD

**Issue by nikuz** [TheWidlarzGroup/react-native-video#223]
Hi,

This take no effect on Android:

```
AppState.addEventListener('change', () => {
  this.state({
    paused: true
 });
});
```

I still hear sound of movie. But if change AppState back to `active`, finally video will stopped.
Seems that after APP was pushed to `background` state, JS can't affect to props of `react-native-video`.

Please, help to solve this.

**Comment by donnguyen** [comment]
Same here

**Comment by donnguyen** [comment]
@sjchmiela should we consider to implement this feature on our module view here https://github.com/brentvatne/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java, I don't think we can achieve what @nikuz (maybe many others out there, like me) wanted on a higher level like **nikuz** did above. You know it is very annoying when the app goes to background but MediaPlayer keep playing.

**Comment by mattapperson** [comment]
@nikuz @donnguyen does this work as expected on iOS? (assuming the "right" props are set in your info.plist)

**Comment by donnguyen** [comment]
@mattapperson yes it does work as expected on iOS

**Comment by swaroopa94** [comment]
I too have the same issue.
For me the following did not work for me.
AppState.addEventListener('change', () => {
  this.state({
    paused: true
 });
});

can u help me how to solve this

**Comment by mmailhos** [comment]
Anyone found a solution here?

**Comment by DenisIzmaylov** [comment]
Hi! How is going with this issue?

**Comment by DenisIzmaylov** [comment]
@brentvatne ?

**Comment by mattapperson** [comment]
Sorry, I really have no clue what's causing this :(

**Comment by mattapperson** [comment]
I can't seem to reproduce the issue

**Comment by swaroopa94** [comment]
Ya after updating my react native version them my issue was resolved

Thanks
