### ISSUE TITLE
seek function doesn't work on Android

### ISSUE THREAD

**Issue by tomislav-s** [TheWidlarzGroup/react-native-video#2230]
# Bug

When the `seek` function is used on Android it always skips to the start of the video

## Platform
* Android ExoPlayer

## Environment info
React Native version: 0.63.3
Library version: 5.1.0-alpha8

## Steps To Reproduce

1. Run `seek` function with any argument on Android
2. The video seeks to 00:00

## Expected behaviour

1. The video should seek to the desired time

**Comment by kaioduarte** [comment]
I tried it today with 5.1.0-alpha8 and indeed the seek function still not working properly with Android MediaPlayer, but it works with ExoPlayer.

## Sample Code

I tested it with three different videos (one local file and two from Internet).

<details>
  <summary>Click to expand</summary>

```js
import React from 'react';
import {StyleSheet, View} from 'react-native';
import Video from 'react-native-video';

export default () => (
  <View style={styles.container}>
    <Video
      source={{
        uri:
          'https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4',
      }}
      controls
      onSeek={(data) => console.log('onSeek', data)}
      style={styles.video}
    />
  </View>
);

const styles = StyleSheet.create({
  container: {flex: 1},
  video: {width: '100%', height: 220},
});
```
</details>

## Default behavior

### Android MediaPlayer (imprecise `seek`)
https://user-images.githubusercontent.com/11046907/103314418-f120dd00-4a1a-11eb-814a-929077256ba4.mp4

### ExoPlayer (`seek` seems to be working fine)
https://user-images.githubusercontent.com/11046907/103313934-6db2bc00-4a19-11eb-9861-32b542d3873f.mp4


## Fix for Android MediaPlayer
Currently, this lib use [`seekTo` without mode param](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(int)) and I played around the [other modes available](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(long,%20int)) and the one that seeked properly was `SEEK_CLOSEST` (pay attention to its description).

So the change done was in `android/src/main/java/com/brentvatne/react/ReactVideoView.java` on the line 640:
```java
- super.seekTo(msec);
+ super.mMediaPlayer.seekTo(msec, MediaPlayer.SEEK_CLOSEST);
````

I'm aware that's not look too to access a super class member attribute, but we just have access to the [`seekTo` method with a single parameter](https://github.com/yqritc/Android-ScalableVideoView/blob/master/library/src/main/java/com/yqritc/scalablevideoview/ScalableVideoView.java#L227-L229).

Here is the same sample as above with the fix.

https://user-images.githubusercontent.com/11046907/103313932-6db2bc00-4a19-11eb-9439-9b01a2f71971.mp4

**Comment by kaioduarte** [comment]
Related issues
- #1476 
- #1550 
- #1717
- #1908

**Comment by Abdullah1428** [comment]
I needed to show the exact time of the video to the user according to the sliding of the trim slider. 
I was facing a similar issue and I got to manage a workaround in my case. I hope it's helpful to anyone facing a similar issue.

```
const [check, setCheck] = useState(true)
onProgress = {onProgress}

const onProgress = ({currentTime}) => {
    if (Math.round(currentTime) === 0 && checked) {
      if (player) {
        player.current.seek('jump to your desired value');
        setChecked(false);
      }
    }

   if (Math.round(currentTime) > 0) {
      if (checked) {
      } else {
        setChecked(true);
      }
    }
}
```

**Comment by Aarvis** [comment]
> I tried it today with 5.1.0-alpha8 and indeed the seek function still not working properly with Android MediaPlayer, but it works with ExoPlayer.
> 
> ## Sample Code
> I tested it with three different videos (one local file and two from Internet).
> 
> Click to expand
> ## Default behavior
> ### Android MediaPlayer (imprecise `seek`)
>  video_2020-12-29_21-14-58.mp4 
> ### ExoPlayer (`seek` seems to be working fine)
>  video_2020-12-29_21-04-12.mp4 
> ## Fix for Android MediaPlayer
> Currently, this lib use [`seekTo` without mode param](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(int)) and I played around the [other modes available](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(long,%20int)) and the one that seeked properly was `SEEK_CLOSEST` (pay attention to its description).
> 
> So the change done was in `android/src/main/java/com/brentvatne/react/ReactVideoView.java` on the line 640:
> 
> ```java
> - super.seekTo(msec);
> + super.mMediaPlayer.seekTo(msec, MediaPlayer.SEEK_CLOSEST);
> ```
> 
> I'm aware that's not look too to access a super class member attribute, but we just have access to the [`seekTo` method with a single parameter](https://github.com/yqritc/Android-ScalableVideoView/blob/master/library/src/main/java/com/yqritc/scalablevideoview/ScalableVideoView.java#L227-L229).
> 
> Here is the same sample as above with the fix.
> 
>  video_2020-12-29_21-04-15.mp4

Yeah @kaioduarte, just to add on to your nice workaround. I noticed that there already exists a separate mMediaPlayer object in ReactVideoView.java, so we could write:

`mMediaPlayer.seekTo(msec,3);  // 3 or MediaPlayer.SEEK_CLOSEST`

instead of accessing from the super class.

**Comment by freeboub** [comment]
If someone wants to open a PR, that would be great !

**Comment by monahans** [comment]
@freeboub just created one: https://github.com/react-native-video/react-native-video/pull/2712

**Comment by farid-itpath** [comment]
> > I tried it today with 5.1.0-alpha8 and indeed the seek function still not working properly with Android MediaPlayer, but it works with ExoPlayer.
> > ## Sample Code
> > I tested it with three different videos (one local file and two from Internet).
> > Click to expand
> > ## Default behavior
> > ### Android MediaPlayer (imprecise `seek`)
> > video_2020-12-29_21-14-58.mp4
> > ### ExoPlayer (`seek` seems to be working fine)
> > video_2020-12-29_21-04-12.mp4
> > ## Fix for Android MediaPlayer
> > Currently, this lib use [`seekTo` without mode param](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(int)) and I played around the [other modes available](https://developer.android.com/reference/android/media/MediaPlayer#seekTo(long,%20int)) and the one that seeked properly was `SEEK_CLOSEST` (pay attention to its description).
> > So the change done was in `android/src/main/java/com/brentvatne/react/ReactVideoView.java` on the line 640:
> > ```java
> > - super.seekTo(msec);
> > + super.mMediaPlayer.seekTo(msec, MediaPlayer.SEEK_CLOSEST);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm aware that's not look too to access a super class member attribute, but we just have access to the [`seekTo` method with a single parameter](https://github.com/yqritc/Android-ScalableVideoView/blob/master/library/src/main/java/com/yqritc/scalablevideoview/ScalableVideoView.java#L227-L229).
> > Here is the same sample as above with the fix.
> > video_2020-12-29_21-04-15.mp4
> 
> Yeah @kaioduarte, just to add on to your nice workaround. I noticed that there already exists a separate mMediaPlayer object in ReactVideoView.java, so we could write:
> 
> `mMediaPlayer.seekTo(msec,3); // 3 or MediaPlayer.SEEK_CLOSEST`
> 
> instead of accessing from the super class.

Do we have same solution in iOS?
