### ISSUE TITLE
[Question] How to properly stop the video?

### ISSUE THREAD

**Issue by mango009** [TheWidlarzGroup/react-native-video#2233]
Sorry for the newbie question. To properly stop the video from playing, is it done by  changing the 'paused' property to true?

**Comment by 0x41rtur** [comment]
yes

**Comment by afilp** [comment]
I have a weird problem with the `paused` property. While I turn it (through state) to `true` and then I do a `seek` to a specific minute, the video goes there but refuses to start playing... And the weird part is that after I do another pause, then It may work, as if it needs 2 pauses.

**Comment by Julious1994** [comment]
I also having same problem.
