### ISSUE TITLE
Unable to resolve module './DRMType'

### ISSUE THREAD

**Issue by pvn** [TheWidlarzGroup/react-native-video#2235]
# Bug

Unable to resolve module './DRMType'

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
 Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: javac 12 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.0.0

### Step 1:
Installed the [5.0.0](https://github.com/react-native-video/react-native-video/releases) with locked version in my package.json

<img width="112" alt="Screenshot 2020-12-08 at 23 23 54" src="https://user-images.githubusercontent.com/506406/101521935-81d04400-39ac-11eb-9ac2-67f5f8ffc613.png">

_package.json_
"react-native-video": "^5.0.0",

Error:
### _Unable to resolve module './DRMType'_

<img width="305" alt="unable-to-resolve" src="https://user-images.githubusercontent.com/506406/101521007-3cf7dd80-39ab-11eb-91d0-2b63a82d3ee7.png">

### Step 2:
Then I tried installing with the following command **without specifying any version:**
`npm install --save react-native-video`

It got installed with **"react-native-video": "^5.1.0-alpha8",**

I can not even find this version in both the pages
Releases (https://github.com/react-native-video/react-native-video/releases)
Tags (https://github.com/react-native-video/react-native-video/tags)

We do not even know which version is officially released from documentation.
...

## Expected behaviour

1. We should not get error Unable to resolve module './DRMType'
2. We do not even know which version is officially released from documentation.

Let me know, if you require more info to understand this issue which I might have missed to point out here.

**Comment by josepichu** [comment]
same here, any update ?

**Comment by VladLegkowski** [comment]
Any update on this issue? @pvn, did you manage to resolve it?

**Comment by hugoh59** [comment]
Same issue here.
