### ISSUE TITLE
Play video only when visible in viewport.

### ISSUE THREAD

**Issue by nickpricks** [TheWidlarzGroup/react-native-video#224]
I am showing multiple videos in scroll and want to play that video when show in screen and pause when they are off the screen.

**Comment by getnashty** [comment]
I think the best way to accomplish this, would be putting your videos in a [ListView](https://facebook.github.io/react-native/docs/listview.html#content), and then using onChangeVisibleRows to tell the visible video to play.

**Comment by tomprogers** [comment]
We've done exactly what @getnashty suggests. It mostly works, although there appears to be a bug in the react-native ListView javascript implementation of `onChangeVisibleRows`. It's a pretty hairy algorithm, and we haven't yet tried seriously to debug it.

**Comment by getnashty** [comment]
agreed @tomprogers, the onChangeVisibleRows definitely seems to only kind of work.. I've used this component around my video https://github.com/yamill/react-native-inviewport to have a better idea of when its really in-view. Although, when removeClippedSubviews is set to true on the Listview, its doesn't work at all. 

So to recap:
- https://github.com/yamill/react-native-inviewport wrapped around the video (i use redux to make sure only 1 video can play at a time based on storing whatever is in view in the global state)
- ListView removeClippedSubviews={false}

**Comment by mattapperson** [comment]
This is not really within the scope of this project, so I am going to close the issue, but feel free to continue its discussion

**Comment by dpatel** [comment]
> anyone was able to figure this out for a flatlist that continuously updates with posts?
> 
> I try to use onlayout but it doesn't seem to trigger

Did you find out any solution?

**Comment by DISKONEKTeD** [comment]
@dpatel  I did, using "ref" in the flatlist. I don't remember the specifics off the top of my head, I'd have to look for it to recall. But I currently have something working in my app. I'll try to do a follow up later

edit: i think this post covers it: https://stackoverflow.com/questions/48287658/play-pause-download-video-in-flatlist i didn't delve too much but i saw that it uses ref in it
