### ISSUE TITLE
Can not show media control in background

### ISSUE THREAD

**Issue by congtt17** [TheWidlarzGroup/react-native-video#2241]
I am playing music using react native video.

when I run this app in background (still  playing music) but media control of device (player control outsite) can not displayed. Can you help me resolve it?

**Comment by Aayushi-React-Native** [comment]
Same here.
Android also.
When we play app and put app in background controls not showing.
in both ios and android devices.
controls={true}

**Comment by killua8p** [comment]
Same issue +1
