### ISSUE TITLE
The loading speed of network video is too slow, can you optimize it

### ISSUE THREAD

**Issue by caijiami** [TheWidlarzGroup/react-native-video#2244]
The loading speed of network video is too slow, can you optimize it

**Comment by caijiami** [comment]
@jsierles @danhodos @peterblazejewicz @qingfeng Thank you very much for your work

**Comment by antonellil** [comment]
@caijiami I have noticed this as well, regardless of network quality there seems to be some additional delay which is especially noticeable when on cellular data and not wifi (noticeable on iOS).

**Comment by caijiami** [comment]
> @caijiami我也注意到了这一点，无论网络质量如何，似乎都有一些额外的延迟，这在蜂窝数据而非wifi上尤为明显（在iOS上值得注意）。
And if it is a video list, after watching more than ten videos, the video will not play

**Comment by baronha** [comment]
+1

**Comment by chismadalina** [comment]
any updates?
