### ISSUE TITLE
CRASH ON iOS : com.apple.coreaudio.AQClient (66): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by adamsolomon1986** [TheWidlarzGroup/react-native-video#2247]
# Bug

The app crashes randomly on iOS when using multiple instances of react-native-video in a flatlist. 
Does not happen on android.

## Platform
iOS 12.2

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 818.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native: 0.62.0

Library version: 4.4.5

## Steps To Reproduce

It's hard to produce as you can do refresh a flat list with multiple video instances (auto playing) few times.

The error I'm getting is 

**com.apple.coreaudio.AQClient (66): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)**

**Comment by oleksii-lyhun** [comment]
I have same issue. Any ideas how to resolve it?

**Comment by algokano** [comment]
same issue

**Comment by bogdandevlpr** [comment]
I also get this error on iOS 13.7: **com.apple.audio.IOThread.client (65): EXC_BAD_ACCESS (code=1, address=0x0)**
The issue is not reproducing on iOS 14.4

Also, this issue doesn't seem to be reproducing on iPhone 7 Plus - iOS 13.7

react-native@0.62.2
react-native-video@5.1.1

**Comment by maoapp** [comment]
same here

**Comment by hueniverse** [comment]
Merged into #2668
