### ISSUE TITLE
callback when user click the volume to mute / unmute the full screen IOS

### ISSUE THREAD

**Issue by cenaHara** [TheWidlarzGroup/react-native-video#2248]
Hello everyone 
pls for me know how to get callback when user click the volume to mute / unmute the full screen IOS

**Comment by kp47** [comment]
I also need a callback when user toggles mute button so that I can pass it to defaultMuted method to mute/unmute all the other videos in the list.

**Comment by Andriiklymiuk** [comment]
Has anyone figured it out?
