### ISSUE TITLE
Video preview in android

### ISSUE THREAD

**Issue by zongjingyao** [TheWidlarzGroup/react-native-video#225]
MediaPlayer cannot show a preview image in android.

**Comment by twillzy** [comment]
Hopefully this helps.

Just wrap the videoUri inside an image component like this: 

`<Image ref="image"
             source={{uri: this.state.videoUri}}/>`

**Comment by febobo** [comment]
@twillzy  hi , I try on Video add Image component , but it no preview

**Comment by superandrew213** [comment]
@febobo Image works on Android. Make sure you give the image height and width.

**Comment by mattapperson** [comment]
New APIs coming that should help with this too...
