### ISSUE TITLE
mixWithOthers should be work on Android as well.

### ISSUE THREAD

**Issue by RNTop** [TheWidlarzGroup/react-native-video#2253]
# Feature Request
mixWithOthers should be work on Android as well.

## Why it is needed
Ducking issue is normal for the playing of advanced music and video. iOS is working perfectly. 
But this sdk does not support for Android.

## Possible implementation

import android.media.AudioManager.OnAudioFocusChangeListener;
import android.media.MediaMetadataRetriever;
import android.media.MediaPlayer;
import android.media.MediaPlayer.OnCompletionListener;
import android.media.MediaPlayer.OnPreparedListener;

 afChangeListener = new OnAudioFocusChangeListener() {
          public void onAudioFocusChange(int focusChange) {
              if (focusChange == AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK) {
                  if(m!=null) {
                      m.setVolume(0.3f, 0.3f);
                  }
              } else if (focusChange == AudioManager.AUDIOFOCUS_GAIN) {
                  if(m!=null) {
                      m.setVolume(1.0f, 1.0f);
                  }
              } else if (focusChange == AudioManager.AUDIOFOCUS_LOSS) {
              }

          }

**Comment by nttuywn** [comment]
Have you have any solution yet?
