### ISSUE TITLE
how to use ExoPlayer ？

### ISSUE THREAD

**Issue by KingAmo** [TheWidlarzGroup/react-native-video#2255]
the doc do not have a guide on how to enable ExoPlayer, any help please?

**Comment by KingAmo** [comment]
react native info:
```
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 128.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.0-rc.2 => 0.64.0-rc.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by MBakhtiyor** [comment]
Hi.
You need to create react-native.config.js file on your root project folder with this part of code:

`module.exports = {
    dependencies: {
        'react-native-video': {
            platforms: {
                android: {
                    sourceDir: '../node_modules/react-native-video/android-exoplayer',
                },
            },
        },
    },
};
`

**Comment by frostykdev** [comment]
> Hi.
> You need to create react-native.config.js file on your root project folder with this part of code:
> 
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, }; `

You're life saver)

**Comment by kr396** [comment]
> Hi.
> You need to create react-native.config.js file on your root project folder with this part of code:
> 
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`

Save my day. Thanks!

**Comment by ShivamJoker** [comment]
Why this is not added in Readme yet ? Should I make a PR ?

**Comment by sathishsubramani-2103** [comment]
> Hi.
> You need to create react-native.config.js file on your root project folder with this part of code:
> 
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, }; `

Without knowing this I've wasted my 48hrs. AWESOME.

**Comment by Najaf-Rai** [comment]
Hi, 
Thank you for solution but my app is crashing randomly without any error logs while i'm playing any video in flat list?
I think may be some memory issue. Kindly guide me

**Comment by RonaldNgarombo** [comment]
> Hi. You need to create react-native.config.js file on your root project folder with this part of code:
> 
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, }; `

Thanks a lot man...

**Comment by lamlengend98** [comment]
![image](https://user-images.githubusercontent.com/37770203/190121244-a29c5d6c-47f1-40e4-932f-e099e56553cd.png)
Cannot be enable. How should I do next steps like re-run: yarn start, yarn android or something like that

**Comment by freeboub** [comment]
Yes, you need to rebuild the app after switching to exoplayer

**Comment by santi-andracchi** [comment]
> Hi. You need to create react-native.config.js file on your root project folder with this part of code:
> 
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, }; `

This helped me with react-native-video-player as well.
