### ISSUE TITLE
Disable iPhoneX Home indicator

### ISSUE THREAD

**Issue by nikesh8** [TheWidlarzGroup/react-native-video#2257]
## Feature: 
1. While the video playing with custom controls I have to hide the home indicator for full-screen layout.

## Why it is needed:
- As we need to hide the home indicator while video playing in full-screen.

### Attempts:
- I have tried with AVPlayer controls and it will hide the home indicator but while I am trying with custom controls UI it will not hide the home indicator. I have to use custom controls mandatory and also need to hide the home indicator while the player plays videos in full-screen.

**Can you please help me out? I have attempted so many tricks but not able to get rid out of them.**

Thanks in advance.

**Comment by nikesh8** [comment]
@hueniverse Please refer this screen shot
![IMG_971E507CA5CF-1](https://github.com/react-native-video/react-native-video/assets/55312626/75bab109-e357-4609-81c4-45c0b50919cc)

**Comment by nicolaosm** [comment]
@nikesh8 I don't think this is an issue anymore.

Attached a screenshot below:
iPhone 14 Pro Max | iOS 16.6 | Native controls | Landscape mode.

![IMG_2187](https://github.com/react-native-video/react-native-video/assets/4417369/14e30c3b-3a14-4950-ba36-a3f6d5347209)

For custom scrub bar, I think you can move it up to avoid conflict with the Home bar.

@freeboub maybe close this if not relevant anymore? Thanks
