### ISSUE TITLE
local video not playing in IOS

### ISSUE THREAD

**Issue by JosePatricio** [TheWidlarzGroup/react-native-video#2258]
# Bug

Local video not playing in IOS, it works in Android .

Version
"react-native-video": "^5.0.2",

Code

 <Video  source={require('./../assets/video.mp4')}/>

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 11.0
    CPU: (2) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.67 GB / 12.56 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by ghost** [comment]
Same issue in ios.
@JosePatricio Did you found any solution to it ?

**Comment by adamawang** [comment]
Also running into the same issue. Videos are playing fine in debug on iOS, but do not play at all in release builds. 

> "react-native-video": "^5.1.0-alpha8",
"react": "^16.13.1",
"react-native": "^0.63.4",


Edit: ended up being user error, asset files were not getting bundled correctly.

**Comment by victoriaSh** [comment]
Had the same issue. Check this https://github.com/facebook/react-native/issues/29279#issuecomment-740041741 
That's react-native issue.

**Comment by lukasrobertsson** [comment]
> Also running into the same issue. Videos are playing fine in debug on iOS, but do not play at all in release builds.
> 
> > "react-native-video": "^5.1.0-alpha8",
> > "react": "^16.13.1",
> > "react-native": "^0.63.4",
> 
> Edit: ended up being user error, asset files were not getting bundled correctly.

@adamawang how did you solve it?
