### ISSUE TITLE
Refs not working

### ISSUE THREAD

**Issue by dnish** [TheWidlarzGroup/react-native-video#226]
When I add a video component like this:

```
 <TouchableHighlight>
    <Video
     ref="test"
     source={{uri:"...."}}
     muted={this.state.muteVideo}
     paused={this.state.pauseVideo} />
</TouchableHighlight>
```

I only get an empty object if I call <code>console.log(this.refs);</code>. It seems like the ref isn't working within TouchableHighlight. I'm using RN 0.25.1

**Comment by ghost** [comment]
@dnish have you tried adding a `<View>` wrapper around the `Video` component within the `TouchableHighlight`?

**Comment by mattapperson** [comment]
Closing this issue due to age and lack of feedback. Please re-open if this is still an issue

**Comment by prakasa1904** [comment]
same issue
