### ISSUE TITLE
onError is not working Android

### ISSUE THREAD

**Issue by EdDevs2503** [TheWidlarzGroup/react-native-video#2260]
# Bug

I am developing a feature in my project for download a video when it fail. For that logic, I use onError callback in react-native-video for do something when it fail. In IOS it working fine, but in Android onError is not called but the` <Video />` don't play anything. Basically, onError event on Android is not working.

## Platform

Android 

Which player are you experiencing the problem on:

(I am not sure about this)

* Android ExoPlayer
* Android MediaPlayer

## Environment info

System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 190.20 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.0-alpha8

## Steps To Reproduc

1. Give to <Video /> an incorrect source on Android
2. Set a log at onError prop
3. Run it and verify if onError is executed

## Expected behaviour

1. onError must be called with a parameter with the error
2. `<Video />` will no reproduce anything

## Reproducible sample code

`
          <Video
            source={{uri: "video.mp4"}}
            onError={(error) => console.log(error)}
          />
`

**Comment by rodriguezmanu** [comment]
+1

**Comment by aniket-dalvi** [comment]
Any update on this? Have you able to get the errors in the callback for android?

**Comment by enesbildiren95** [comment]
Any solution?

**Comment by SanjanaTailor** [comment]
I am facing this problem when Internet is unavailable, onError is not calling. Please provide any alternate solution for same.

**Comment by freeboub** [comment]
This issue is linked to the uri parameter which is invalid... You should use require(file) to play local file. (And outside of uri prop)

**Comment by uttu-316** [comment]
> is not calling. Plea

+1

**Comment by freeboub** [comment]
There is a real issue here.
If user provide an invalid uri parameter, the source is just ignore.
The expected behavior would be at least to stop current streaming and throw an error (source not supported)

**Comment by freeboub** [comment]
A fix is available for this issue : https://github.com/react-native-video/react-native-video/pull/2857
An ios and windows review is welcome.
