### ISSUE TITLE
react-native-video on windows app

### ISSUE THREAD

**Issue by kandabior** [TheWidlarzGroup/react-native-video#2261]
### Current Bug
The solution Code doesn't compile after including the "winrt/ReactNativeVideoCPP.h"  in pch.h file:
error: cannot open the source file "winrt/ReactNativeVideoCPP.h".

### Reproduction steps

**windows/myapp.sln
                    Add the ReactNativeVideoCPP project to your solution.**
                    
**Open the solution in Visual Studio 2019**
          Right-click Solution icon in Solution Explorer > Add > Existing Project Select node_modules\react-native-video\windows\ReactNativeVideoCPP\ReactNativeVideoCPP.vcxproj
          windows/myapp/myapp.vcxproj
          
**Add a reference to ReactNativeVideoCPP to your main application project. From Visual Studio 2019:**
          
Right-click main application project > Add > Reference... Check ReactNativeVideoCPP from Solution Projects.

Modify files below to add the video package providers to your main application project

**pch.h**
          Add #include "winrt/ReactNativeVideoCPP.h".
          
**app.cpp**
          Add PackageProviders().Append(winrt::ReactNativeVideoCPP::ReactPackageProvider()); before InitializeComponent();

### Platform
* Windows

**Comment by SonPH088** [comment]
+1 issue. did you find how to run react-native-video on the windows app?

update: u can add #include "winrt/ReactNativeVideoCPP.h" on app.cpp and compile, it's work find on debug mode, but got blank screen in release mode.

**Comment by itsaberi** [comment]
same issue
