### ISSUE TITLE
5.1.1 is not on npm OSS 

### ISSUE THREAD

**Issue by KingAmo** [TheWidlarzGroup/react-native-video#2262]
i see a new release of `v5.1.1` on [github release](https://github.com/react-native-video/react-native-video/releases)

but it seems that it is not on npm OSS :
https://www.npmjs.com/package/react-native-video

![image](https://user-images.githubusercontent.com/29938227/104441652-eba4c480-55ce-11eb-9f70-aa241e0428de.png)

@nickfujita

**Comment by nickfujita** [comment]
version 5.1.1 is now published to npm as well.
