### ISSUE TITLE
Picture in Picture functionality not working on RN Video

### ISSUE THREAD

**Issue by loria33** [TheWidlarzGroup/react-native-video#2264]
# Bug
Picture in Picture functionality not working on RN Video

IOS : RN 0.63.4
"react-native-video": "^5.1.0-alpha8",

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

## Environment info

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 41.28 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

When tapping on Pip icon and setting PictureInPicture to true nothing happens

## Expected behaviour

1.Video moves to PictureInPicture mode

## Reproducible sample code
Video
                ref={videoRef}
                source={{
                  uri: manifestUrl,
                }}
                controls={false}
                paused={chromeCastStarted ? true : playVideoStatus}
                volume={1.0}
                resizeMode="contain"
                style={style}
                progressUpdateInterval={isSeeking ? 10000 : 900}
                onProgress={handleProgress}
                onLoad={onLoadPlayer}
                onError={onError}
                onSeek={onSeekDone}
                playWhenInactive
                playInBackground={isbackGroundPlay}
                onEnd={onEnd}
                rate={Number(currentSpeed)}
                allowsExternalPlayback
                pictureInPicture={pictureInPictureMode}
                selectedTextTrack={
                  currentSubtitles && showSubtitles
                    ? { type: 'title', value: currentSubtitles.title }
                    : { type: 'disabled' }
                }
                onBuffer={onBuffer}
                onBuff
                selectedAudioTrack={
                  currentAudioTrack
                    ? {
                        type: 'language',
                        value: currentAudioTrack.language,
                      }
                    : { type: 'system' }
                }
              />

Debugging code this function does not initialize the PiP due to this warning :
'AVPictureInPictureController' is only available on iOS 9.0 or newer **although our project is set to ios 9. both in Xcode and pod file** 

react-native-video/video/RCTVideo.m
- (void)setupPipController {

  if (!_pipController && _playerLayer && [AVPictureInPictureController isPictureInPictureSupported]) {
    // Create new controller passing reference to the AVPlayerLayer
    _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer:_playerLayer];
    _pipController.delegate = self;
  }
}

Workaround that is currently optional is in the pod file running target change for all pods. Problem is having two post install pod scripts running as the one implemented now is for FLIPPER.

**Comment by fielddaychurch** [comment]
Running into the same issue as well. Watching this issue.

**Comment by MaStep92** [comment]
Same problem :(
