### ISSUE TITLE
onBuffer event is not fired

### ISSUE THREAD

**Issue by Taiyab123** [TheWidlarzGroup/react-native-video#2265]
# Bug
There is onBuffer props in react native video but it never fired when video is buffering.

#Platform 
  Android
#Using react-native-video 
#Code  
const onBuffer = ({isBuffering}) => {
    setIsLoading(isBuffering ? true : false);
  };
<Video
            source={{
              uri: currentVideo.videoUrl,
            }}
            ref={(ref) => (videoPlayer.current = ref)}
            onBuffer={onBuffer}
            onError={() => {
              '';
            }}
            onEnd={onEnd}
            onLoad={onLoad}
            onLoadStart={onLoadStart}
            posterResizeMode={'cover'}
            onProgress={onProgress}
            paused={paused}
            style={styles.backgroundVideo}
            resizeMode="cover"
          />

**Comment by AndresTIY** [comment]
i recently went back, remove this package and reinstalled without the manual steps and onBuffer didn't work. after follow the steps listed here https://github.com/react-native-video/react-native-video#android-installation it seemed to work just fine.

if that doesn't work, you can use a work around. during the `onProgress` event, take a look at `data.playableDuration` vs `data.currentTime`. if duration is less than current time, it should be buffering.

```
const onProgress = (data) => {
    if (data.playableDuration !== 0 && data.playableDuration < data.currentTime){
    setIsBuffering(true)
    } else {
    setIsBuffering(false)
    }

}

<Video onProgress={onProgress}/>
```

**Comment by Taiyab123** [comment]
Hi,
Thanks for your update.
I will check it out and let you know.

Thanks
Taiyab

**Comment by Taiyab123** [comment]
Hi onBuffer is not working, even it is not triggered

**Comment by laurenceunmind** [comment]
@Taiyab123 Which android video player are you using? `onBuffer` only gets triggered if you're using exoplayer.

**Comment by lucasftcruz** [comment]
@laurenceunmind I'm facing the same issue:

- RN 0.60.4
- react-native-video v.5.0.0 and 5.1.1
- Yes, I'm using ExoPlayer
- Tried a clean install of the library
- Tried manually config Android as @AndresTIY recommended and also the onProgress method which did not work for me as well

I'm testing IOS and Android the same way, by throttling the network. On iOS onBuffer is called, on Android onBuffer is not called and the video freezes for some time before continuing.

Similar, the onProgress workaround is never buffering as playableDuration is always > currentTime. Is it something related to how I'm testing it on Android?

Thanks for the support so far!

**Comment by NeerajaaG** [comment]
any update on  this issue

**Comment by lucasftcruz** [comment]
+1

**Comment by paddy57** [comment]
+1

```
 <Video
                source={{ uri: video_url }}
                resizeMode={'cover'}
                posterResizeMode={'stretch'}
                ref={videoRef}
                onProgress={(data) => onProgress(data)}
                onBuffer={(meta) => onBuffer(meta) }
/>
```

```
function onBuffer(meta) {
        console.log('bufferingMeta', meta);
        setIsBuffering(meta.isBuffering)
    }
```
here onBuffer never triggers. 

 "react-native-video": "^5.1.1",
 "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by ghost** [comment]
The same issue here. For me it works on Android as expected. But on iOS onBuffer is called only once after video loads, then it's never called again during playback.

**Comment by kotoyama** [comment]
Same. I'm using ExoPlayer, and `onBuffer` never triggers.

**Comment by ghost** [comment]
> if (data.playableDuration !== 0 && data.playableDuration < data.currentTime){
>     setIsBuffering(true)
>     } else {
>     setIsBuffering(false)
>     }

thank you for this , worked for me I was using rn track player and video player parallelly and using Exo player for buffering was making the track player crash. This solution helped me thank a lot

**Comment by adembacajdev** [comment]
Still experiencing this issue in v6.0 alpha.3. If anyone wants a temporary fix, you can do it in the following way: 


```
let bufferingTimeout = null; //out of the class/function

const [isBuffering, setIsBuffering] = useState<boolean>(false);

useEffect(() => {
setIsBuffering(false);
if(bufferingTimeout) clearTimeout(bufferingTimeout);
bufferingTimeout = setTimeout(() => {
setIsBuffering(true);
}, 1500)
}, [currentVideoProgress])
```

**Comment by ToshKoevoets** [comment]
Are you sure you are on the Expoplayer for Android?
