### ISSUE TITLE
{"error": {"extra": -1010, "what": 1}}

### ISSUE THREAD

**Issue by MaliahRajan** [TheWidlarzGroup/react-native-video#2266]
# HD Videos are not getting played. Instead getting error as  {"error": {"extra": -1010, "what": 1}}

## Platform - Android 10
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

"react-native-video": "^5.1.0-alpha8",
"react-native-video-controls": "^2.6.0"

## Video sample
https://cutt.ly/WjS7BJv

**Comment by gaboro-moove-it** [comment]
I've got the same error in Android, this started happening this week. I've got this issue using m3u8 files and hls with https contexts 
this url doesn't work on android 
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8
 and the same url using http works 
http://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8


the app works without any problem in IOS

**Comment by ithustle** [comment]
I solved this issue making a downgrade from 5.1.1 from 5.0.1

**Comment by fernandopascoalbr** [comment]
@MaliahRajan How you solve this?

**Comment by shrynshjn** [comment]
Hey, anyone able to solve the error? 
I am getting this error, on both 5.1.1 and 5.0,1
 {"error": {"extra": -2147483648, "what": 1}}

**Comment by jocelNardi** [comment]
> Hey, anyone able to solve the error?
> I am getting this error to, on both 5.1.1 and 5.0,1
> {"error": {"extra": -1, "what": 1}}

**Comment by freeboub** [comment]
Not reproduced on master...
Let close this issue, please reopen with a logcat for more investigation
