### ISSUE TITLE
selectedVideoTrack prop for iOS

### ISSUE THREAD

**Issue by Freire71** [TheWidlarzGroup/react-native-video#2268]
Hi, I'm trying to make available switching between a variety of video quality. 
On the documentation, there is a prop name **selectedVideoTrack** but it is only available on Android. 
Is there any alternative on iOS to achieve the same functionality? I've tried it on Android and it works like a charm

**Comment by arjunnikolaev** [comment]
Please make it work on iOS as well!

Right now I have to change the source of the video to change resolution, which is very slow and looks bad
On Android Exoplayer it looks perfect

**Comment by skfaisal93** [comment]
It does not work in android too.
