### ISSUE TITLE
error messsage: stateless function components cannot have refs

### ISSUE THREAD

**Issue by chetankumar01** [TheWidlarzGroup/react-native-video#227]
Using react-native-video 0.8.0-rc and react-native 0.26.1

When I am removing a video player which has a ref attached to it, I am getting this error

**Comment by mattapperson** [comment]
@chetankumar01 is this still an issue with the latest react-native releases?

**Comment by chetankumar01** [comment]
No.. it's not. Thanks  

Sent from [Nylas N1](https://link.nylas.com/link/aob6oa4m5qlfh8p2ytxjy3nty
/local-7eb70fbb-7dfa/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVw
bHkrMDAxODRjZmI2NjUzNDk3MDE4Yzk2ZjdhMjI3OGIwNGI1YjYzOWFmNmZlMGMwY2I3OTJjZjAwMD
AwMDAxMTNkYzQ1YTk5MmExNjljZTA5NTc1NWZjQHJlcGx5LmdpdGh1Yi5jb20=), the
extensible, open source mail
client.![](https://link.nylas.com/open/aob6oa4m5qlfh8p2ytxjy3nty/local-
7eb70fbb-7dfa?r=cmVwbHkrMDAxODRjZmI2NjUzNDk3MDE4Yzk2ZjdhMjI3OGIwNGI1YjYzOWFmNm
ZlMGMwY2I3OTJjZjAwMDAwMDAxMTNkYzQ1YTk5MmExNjljZTA5NTc1NWZjQHJlcGx5LmdpdGh1Yi5j
b20=)
