### ISSUE TITLE
Audio session interruptions behaviour while phone calling on iOS

### ISSUE THREAD

**Issue by zhulduz** [TheWidlarzGroup/react-native-video#2277]
# Bug

I noticed that the player has vary behaviour on different iOS devices.

Tests on the same build but on different devices:
1. **For example we use iPhone SE, iPhone7 + iOS > 14.2:** 
The player automatically pauses when phone calls - good.
After phone calling the player doesn't resume automatically - why?

2. **For example we use iPhone 11 + iOS > 14.2:** 
The player DOENS'T automatically pauses when phone calls - bad.
After phone calling the player doesn't resume automatically - why?

## Platform
we tested only on iOS 14.4, 14.3
iPhone7, iPhone SE, iPhone 11

Library version: 5.1.1

Guys, can you please explain what should be correct for default behaviour?

As I assume, the player should automatically pause when another app starts playing, then the player should automatically resume.
Moreover [we have tried ](https://github.com/AlphaOTT/react-native-video/commit/d48ce81030b15687bd33c6877e4a77d7c4dcdac9)to use notification `AVAudioSessionInterruptionNotification` to force play/pause when audio session is interrupted, but on iPhone 11 + ios 14.3 that  solution doesn't work.

I would be grateful for help!

**Comment by rcpassos** [comment]
Same issue https://github.com/react-native-video/react-native-video/issues/2225 ?
