### ISSUE TITLE
Get played time

### ISSUE THREAD

**Issue by OleksandrFomin** [TheWidlarzGroup/react-native-video#2280]
Is there an API that I can use to get how much of the video was played by the user (if the user watches the same part of the video twice or fast-forward the time does not add up to the total count)?  
I know there is a  `player.played` property on HTML5 `<video>` component that gives you exactly that, so I wonder if there is something similar that I can do with react-native-player ?

**Comment by jfbn** [comment]
Did you find a solution @OleksandrFomin?

I am not sure if I understand your question correctly, in particular this part:
> if the user watches the same part of the video twice or fast-forward the time does not add up to the total count)
Do you want to add time spent watching the same parts to the total count or not? 

If you're looking to count the total amount of seconds watched, even with the user going back or fast forwarding, you can get a pretty rough estimate (probably not entirely accurate) by hooking into the `onProgress` prop. The `onProgress` event will fire according to the value you give to the `progressUpdateInterval` prop (the prop accepts a number which represents how often the progress update should trigger in milliseconds).

**Comment by OleksandrFomin** [comment]
My goal is to prevent the user from going forward in the UI unless he watched 90% or more of the video. 
So I have to keep track of the watched time. Let's say I have a 100 seconds video. The user has to watch at least 90. But if you watch it for 30 seconds and then rewind to the very beginning, the counter won't start counting again until you reach the 30 seconds mark. 
I hope it makes sense :)

**Comment by grousseva** [comment]
Hi @OleksandrFomin, I am trying to do something similar! Did you find a solution to this? 

Any help would be greatly appreciated! :)

**Comment by sobanarshad85** [comment]
@grousseva @OleksandrFomin any solution did you guys find?

**Comment by freeboub** [comment]
Application responsibility, should be implemented with onProgress handling...
I close the ticket, feel free to reopen it!

**Comment by adnen-chouibi** [comment]
Any suggestion please ?

**Comment by freeboub** [comment]
@adnen-chouibi read my comment 🤷
