### ISSUE TITLE
Video audio not stopped even component unmounts

### ISSUE THREAD

**Issue by syedibrahimt** [TheWidlarzGroup/react-native-video#2281]
# Bug

## Platform

* Windows UWP

## Environment info

React native info output:

```bash
 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 9.76 GB / 15.87 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: ^0.63.11 => 0.63.19
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

```
const [videoPlayer, setVideoPlayer] = useState(undefined); 
useEffect(() => {
    return () => {
      setisVisible(false);
      videoPlayer;
    };
  }, []);
 return (
            <Video
              ref={(videoPlayer) => setVideoPlayer(videoPlayer)}/>
           );
```

## Expected behaviour

1. When moving to other screens using react-navigation, video should stop
2. Also the audio for video

## Whats Happening

1) Even when the component unmounts i can hear the audio

**Comment by TomVuillemin** [comment]
I don't have an answer, but one related information that could help you. When you are navigating to a new screen with react-navigation, the first screen is not unmounted, but just put in background.
See this React navigation documentation page : https://reactnavigation.org/docs/navigation-lifecycle/

**Comment by agniuks** [comment]
@TomVuillemin is right, we're seeing this cause performance issues in the RNW gallery [(Gallery#123)](https://github.com/microsoft/react-native-gallery/issues/123) and I believe we are planning on adding windows support for react-native-screens which would likely help here. 

There was also a [recent change](https://github.com/microsoft/react-native-windows/pull/7363) in RNW for fixing XAML Visibility behavior for the display:none property which is used by navigation.  If the `<Video />` Component is configured to pause when visibility is set to collapsed, then the display:none fix should be enough to address this issue. It will be included in the upcoming 0.65 release, but we could also backport it to 0.64 if needed. 

@jonthysell -- Do you know if the video would pause if collapsed?

In the mean time, a potential workaround would be to use the 'useFocusEffect' hook from navigation along with the 'paused' prop in `<Video />` to make the Video pause when the page is out of focus. For an example, check App.tsx in https://github.com/AgneLukoseviciute/react-navigation-repro on how this workaround was used to make the `<TextInput />` un-editable when leaving a page in react-navigation.

**Comment by zchwyng** [comment]
I'm having the same issue, where the video component is unmounted and the sound keeps playing.

**Comment by macsj200** [comment]
I am also seeing this behavior. I don't believe it's related to navigation because I see this even when staying on the same screen and manually refreshing the page contents.

**Comment by zchwyng** [comment]
I found a hackish work around with using a timeout. Basically 1. make sure video is paused 2. set a timeout that will unmount the component.

**Comment by stepas-dev** [comment]
i am having the same issue, video component unmounts and audio keeps playing. Also happens when you change key of video component. Any solution to this ?

**Comment by zchwyng** [comment]
I believe this is solved in the new alpha version.

**Comment by stepas-dev** [comment]
actually i was using alpha but reverted back to 5.2.0, now it is fine at least on IOS

**Comment by alexfoxy** [comment]
I have fixed with this component:
```
import React from 'react'
import RNVideo from 'react-native-video'

let ref: RNVideo | null

const Video = (props: RNVideo['props']) => {
  return <RNVideo
    ref={r => {
      if (!r) {
        // @ts-ignore setNativeProps does not exist on 'Video' .. but it does!
        if (ref?.setNativeProps) ref.setNativeProps({ paused: true })
      } else {
        ref = r
      }
    }}
    {...props}
  />
}

export default Video
```

**Comment by mexysfr** [comment]
> actually i was using alpha but reverted back to 5.2.0, now it is fine at least on IOS

I can confirm that downgrading from [v6.0.0-alpha.3](https://github.com/react-native-video/react-native-video/releases/tag/v6.0.0-alpha.3) to [5.2.1](https://github.com/react-native-video/react-native-video/releases/tag/v5.2.1) worked for me

**Comment by 3kwtloo** [comment]
A downgrade to 5.2.0 did not work for me but maybe this helps to reproduce the issue:

I only perceive this on an iPhone mini 13 (not sure if this plays a role) on iOS 15.5 on other devices / iOS versions it works. But you can set your Simulator the configuration and you will see it happening.

**Comment by quocbaovu15101996** [comment]
in my case, am using the code below to fix that

  const navigation = useNavigation();

  useEffect(() => {
    navigation.addListener('beforeRemove', () => {
      videoRef.current?.setNativeProps({ paused: true });
    });
  }, []);

<Video ref={videoRef}... />

hope this help

**Comment by quocbaovu15101996** [comment]
in my case, am using the code below to fix that

```
const navigation = useNavigation();

useEffect(() => {
navigation.addListener('beforeRemove', () => {
videoRef.current?.setNativeProps({ paused: true });
});
}, []);

<Video ref={videoRef.current} .../>
```

hope this help

**Comment by bilal-korir** [comment]
I'm using the latest version `v6 alpha-8`. The solution that works for me. Thanks to @quocbaovu15101996 for the hint. [Check ReactNavigation docs here for more info](https://reactnavigation.org/docs/preventing-going-back/) . I had to add the `setTimeout` for 1 seconds in order to fix it. In our case this bug exist only on `iPhone 7`, it seems to work fine on other devices.

```
useEffect(() => {
    navigation.addListener('beforeRemove', e => {
      if (!paused) {
        e.preventDefault()

        setPaused(true)

        setTimeout(() => {
          navigation.dispatch(e.data.action)
        }, 1000)
      } else {
        navigation.dispatch(e.data.action)
      }
    })
  }, [navigation])
```

**Comment by interstates21** [comment]
Still have this issue in ^6.0.0-beta.4

**Comment by bilal-korir** [comment]
> Still have this issue in ^6.0.0-beta.4

The same issue on my side with `^6.0.0-beta.6`, and using `ReactNative 0.71.17`.

**Comment by sahloulmouhib** [comment]
> in my case, am using the code below to fix that
> 
> ```
> const navigation = useNavigation();
> 
> useEffect(() => {
> navigation.addListener('beforeRemove', () => {
> videoRef.current?.setNativeProps({ paused: true });
> });
> }, []);
> 
> <Video ref={videoRef.current} .../>
> ```
> 
> hope this help

this has worked for me 

```
const navigation = useNavigation();

  useEffect(() => {
    navigation.addListener('beforeRemove', () => {
      videoRef.current?.pause();
    });
  }, []);
```
