### ISSUE TITLE
Support for Youtube video

### ISSUE THREAD

**Issue by syedibrahimt** [TheWidlarzGroup/react-native-video#2282]
# Feature Request

## Why it is needed

1) Support to play youtube videos

## Possible implementation

1) When user copies url from youtube video, we must be able to play the video using this component.

**Comment by Desintegrator** [comment]
any solutions?

**Comment by freeboub** [comment]
There is react-native-youtube as a workaround.
https://www.npmjs.com/package/react-native-youtube

There topic as dailymotion ticket i just comment: Can be implemented with :
https://developers.google.com/youtube/iframe_api_reference
