### ISSUE TITLE
Cannot pass local image as poster to Video component

### ISSUE THREAD

**Issue by mobhupath** [TheWidlarzGroup/react-native-video#2283]
# Cannot pass local image as poster to Video component

Assuming we have a requirement to display a single video and local image as poster, here we can't pass, because video component accepts only URL, in master/Video.js
**<Image style={posterStyle} source={{ uri: this.props.poster }} />**

**Comment by sara-elbanna** [comment]
same issue

**Comment by AliZgheib** [comment]
just add an absolute image on top of the player (set the player as paused = true), and when you want to play the video, just remove/hide the image then change paused to false.

**Comment by akharshita** [comment]
> just add an absolute image on top of the player (set the player as paused = true), and when you want to play the video, just remove/hide the image then change paused to false.

@AliZgheib , Sorry for the late reply, this solution will not generate the video reference when the Video component is hidden and the image is visible. It Will not work when trying to replay video using reference and the video is hidden.
Still looking for better solution.
