### ISSUE TITLE
Frame drop on m3u8 (from vimeo) videos

### ISSUE THREAD

**Issue by SarathKannan** [TheWidlarzGroup/react-native-video#2285]
### Current behavior
Frame drop on m3u8 (from vimeo) videos on redmi phones. No issue in samsung phones

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer
* Redmi, Vivo android devices
* React native video 5.1.1
* React native 0.63

#### Current behavior

https://user-images.githubusercontent.com/35830880/107676881-a227c200-6cbf-11eb-90b5-6e4c8cc4ac42.mp4

#### Expected

https://user-images.githubusercontent.com/35830880/107676911-ab189380-6cbf-11eb-8d16-2a60bcb7af76.mp4

**Comment by official-bharat** [comment]
I also get this same error on the physical Device not in the simulator.
