### ISSUE TITLE
AVFoundationErrorDomain - code -11800

### ISSUE THREAD

**Issue by carlosedof** [TheWidlarzGroup/react-native-video#2286]
# Bug

I have an app that uses AWS url to reproduce videos, at first when i installed react-native-video it worked as expected, but suddenly, without any changes by me, it stoped working and gave me the error: 
"AVFoundationErrorDomain" code -11800
Ive tried a lot of approaches but unsuccessful. It seem to start randomly. There is A LOT of posts relating the same problem, i dont understand why the f* most of them are already closed since NO ONE COULD CONSISTENTLY FIX IT and NO ONE ANSWER WTF is going on. Could PLEASE someone from the lib dev team put some effort on this to get this fixed to help me and the tons of ppl that are having the same issue?

## Platform
IOS
Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 538.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /Users/caduolivera/.sdkman/candidates/java/current/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.1

## Steps To Reproduce

1. start a fresh rn project
2. Install react-native-video lib
3. try any public url video as source: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4
...

## Expected behaviour

1. The video should play or be playable

## Reproducible sample code

```
 <Video
            source={{
              uri: data.arquivo.nm_url,
            }}
            onBuffer={(e) => console.log('buffer video', e)}
            onError={(e) => console.log('err video', e)}
            style={styles.video}
            controls
            paused={true}
          />

```
## Video sample
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4

----- **EDIT** -----

I have new information about this. 
I tried to replace the video component for a webview using react-native-webview, same error, video loads first screen but does not play.
I also tried to open the same video at safari, pasting link url directly... same error. 

Conclusion: That makes me think this issue is not related to this lib. But this does not mean we could work together on tests and research to figure it out, in case some of you still have this issue.

**Comment by alichacha3** [comment]
lots of live tv not working. Black screen is coming and -11800 error. Can this be fixed please?

**Comment by carlosedof** [comment]
This does not seem to be a react-native-video issue, it's a IOS issue. I installed Xcode 12 beta and managed to build to a new emulator, now it works. I don't have this problem on release version or testing in a real phone. This is not a consistent issue and there is no definitive answer yet from either apple or react-native-video lib developers.

**Comment by alichacha3** [comment]
I saw one app iSTB player where same channel is playing in IOS 14. Don’t know what they have used. Not sure how they are doing.

**Comment by Andarius** [comment]
Have you tried using an https url ?

**Comment by llauderesv** [comment]
Any update on this? I was experiencing this issue also.

**Comment by alichacha3** [comment]
Not really.

**Comment by gulsher7** [comment]
same here

**Comment by mitesh-db** [comment]
Have you found out anything? @carlosedof

**Comment by jacobleejones422** [comment]
I am facing the same issue here. Now trying to load the https video file but getting 11800 error and not playing the video

**Comment by MinhThu100200** [comment]
same here. Any update on this? I still played but now I cannot

**Comment by gulsher7** [comment]
> same here. Any update on this? I still played but now I cannot

try this

https://github.com/react-native-video/react-native-video/issues/2250#issuecomment-851316603
