### ISSUE TITLE
_ref.seek(time) not working in IOS

### ISSUE THREAD

**Issue by abdallaemadeldin** [TheWidlarzGroup/react-native-video#2289]
hello there i have a problem with seek() method it's not working fine it always return to the previous time before seeking and i don't know how to fix this issue any help?!
here is a video to know what i'm talking about [here](https://streamable.com/bsz8q)
@jsierles @danhodos @peterblazejewicz @qingfeng @arjan

**Comment by nth-chile** [comment]
I'm experiencing this issue too

**Comment by abdallaemadeldin** [comment]
@nth-chile do you solve the problem?

**Comment by nth-chile** [comment]
Nevermind, actually I was trying to seek past the duration of the video 🙂

**Comment by rdgoutiyama** [comment]
Same here.

**Comment by rdgoutiyama** [comment]
An old iOS version works. But on iOS 14+ does not work.
