### ISSUE TITLE
When multiple video , UI is freeze and main thread is block for few seconds

### ISSUE THREAD

**Issue by sagar-chhatrola** [TheWidlarzGroup/react-native-video#2293]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android MediaPlayer

## Environment info

React native info output:

```bash
 OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 19.74 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      Android NDK: 21.0.6113669
  IDEs:
    
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4
```

Library version: 5.1.1

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by caijiami** [comment]
Same as above. Any good solutions? Thank you very much @sagar-chhatrola @jsierles @danhodos @peterblazejewicz @qingfeng

**Comment by osliver** [comment]
it's still freezing 
I have simple screen with blocks, and on press on block I'm navigating to other screen where 8 video components, all components have same uri:
```js
const videoUri = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
```

https://user-images.githubusercontent.com/97607365/167074889-f0291164-19e0-498c-8b8e-6e0fa078177a.mov

here is Video component implementation:
```js
<Video
style={{width, aspectRatio: 16 / 9}}
source={{uri: videoUri}}
paused
controls
fullscreenOrientation={'landscape'}
resizeMode={'cover'}
/>```

**Comment by hueniverse** [comment]
@osliver please fork https://github.com/react-native-video/react-native-video-test and change it to reproduce your issue. When that is ready, please open a new issue and you can reference this one. Thanks!

**Comment by uttu-316** [comment]
any solution here?

**Comment by vaibhavgehani** [comment]
Its still same, UI is freeze while loading the Video
