### ISSUE TITLE
Error when loading local video file.

### ISSUE THREAD

**Issue by ctliu3** [TheWidlarzGroup/react-native-video#23]
Hi, @brentvatne 

I come across some problem when using the local video (mp4) file. It also occurs when running the  example code in `Examples/VideoPlayer`. I'm definitely sure the local video file exists. 
Here is the error message.

![image](https://cloud.githubusercontent.com/assets/1178241/7152155/83182d96-e368-11e4-9bd7-d71611fa2207.png)

If I use the remote resources, it works well.
Thanks.

**Comment by ctliu3** [comment]
It fixed. 
It seems that I should add the video files by `Add files to <project_name>` first.

**Comment by brentvatne** [comment]
Yup :) glad you got it working!

**Comment by johanneslumpe** [comment]
@brentvatne We should really think about catching that error and maybe displaying a "broken video image or something I think.
