### ISSUE TITLE
Video gets auto zoom in when you click on 15sec forward option in fullscreen mode - iOS

### ISSUE THREAD

**Issue by mobhupath** [TheWidlarzGroup/react-native-video#2300]
Video gets automatically zoom in when you click on 15sec forward option in fullscreen mode - iOS

## Observation: 
Happens only when video is about to complete in less than 15sec, let's say my video length duration is 40 sec, when i try to click on 15sec forward option initially it works moves forward, let say my current time is 28sec, if i try to click now, it'll end the video in zoom mode
## iOS
Which player are you experiencing the problem on:
* iOS

**Comment by mtflud** [comment]
Found that this is only happening when you set `resizeMode='cover'`. Setting it to `contain` prevents that behavior while on fullscreen. Also, iOS 15 beta is not having this issue.
