### ISSUE TITLE
VP9 Support

### ISSUE THREAD

**Issue by benjaminfiliatrault** [TheWidlarzGroup/react-native-video#2303]
# Feature Request

Add support for VP9 Codec on iOS https://developer.apple.com/documentation/coremedia/kcmvideocodectype_vp9 that will be useful for 4k video and to improve the codec support.

## Why it is needed

As VP9 is supported natively on Android adding that support on iOS will improve the video player capabilities. It will also provide up to 8k capabilities.

## Possible implementation

https://developer.apple.com/documentation/coremedia/kcmvideocodectype_vp9
https://chromium.googlesource.com/chromium/src/+/master/media/gpu/mac/vt_video_decode_accelerator_mac.cc#194

**Comment by SunnyAureliusRichard** [comment]
hi @hueniverse , is vp9 support enabled now?

**Comment by mehthabux** [comment]
is it enabled now @SunnyAureliusRichard  ?

**Comment by freeboub** [comment]
I don't think so ...

**Comment by Jamim** [comment]
> I don't think so ...

_Hello @freeboub and @hueniverse,_

Why is this issue closed as completed while VP9 support is not implemented for iOS?
