### ISSUE TITLE
audio track not changing.

### ISSUE THREAD

**Issue by bajpai244** [TheWidlarzGroup/react-native-video#2309]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 118.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  
 Library version: 5.1.1

## Steps To Reproduce

 ```
<Video
          source={{
            uri:
              'https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8',
          }}
          style={{
            width: 500,
            height: 500,
          }}
          controls={true}
           onLoad={(video) => {
            console.log(video);
          }}
        />
        
```

## Expected behavior

1. On changing track in iOS player audio should change

## Reproducible sample code

```
import React, {useState, useRef, useEffect} from 'react';
import SoundPlayer from 'react-native-sound-player';

import {SafeAreaView, StyleSheet, Text, View} from 'react-native';

import Video from 'react-native-video';

export default () => {
  return (
    <View style={{alignItems: 'center', flex: 1, justifyContent: 'center'}}>
      <Text>My video project!</Text>
      <View>
        <Video
          source={{
            uri:
              'https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8',
          }}
          style={{
            width: 500,
            height: 500,
          }}
          controls={true}
          onLoad={(video) => {
            console.log(video);
          }}
         />
      </View>
    </View>
  );
};

```
## Video sample
 
 https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8

**Comment by ShaneMckenna23** [comment]
Use the `selectedAudioTrack` prop to change the language. I do not see this in the sample code above.
