### ISSUE TITLE
Slight lag on seeking backwards, but not forward

### ISSUE THREAD

**Issue by polymorpher** [TheWidlarzGroup/react-native-video#2310]
# Bug

On iOS, seek() works smoothly when I advance to any position ahead of the player's current position. This is hardly any noticeable delay even when seek is called on every minuscule finger-touch movement event. The player can follow finger-touch movement event and display the corresponding frame right away. However, when seek is called to go backward (e.g. on a position less than the player's current position), some delay occurs. The player can no longer smoothly follow touch movement events. Several hundreds of ms of lag can be noticed.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 24.27 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.4 - /usr/bin/javac
    Python: 3.7.9 - /Users/polymorpher/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.0 => 17.0.0 
    react-native: ^0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 5.1.1

## Steps To Reproduce

1. Load a simple 5 second video with this library while setting buffer to maximium. Listen to touch movement event (e.g. via `react-native-gesture-handler`) and call seek on duration_of_the_video * percentage_of_the_movement_length_to_screen_width. Add or subtract duration_of_the_video if needed.
2. Move fingers on screen forward and backward and observe the issue as described above.
...

## Expected behaviour

1. There should be no lag going backward 

## Reproducible sample code

TODO

## Video sample

TODO

**Comment by manuelbieh** [comment]
I am currently experiencing the same issue. Have you found a solution or workaround for that?

**Comment by polymorpher** [comment]
I converted all videos to H.264 encoding. The issues went away. It is not working consistently for H.265
