### ISSUE TITLE
Play-button disappears first time pressing Pause-button using Android-ExoPlayer

### ISSUE THREAD

**Issue by zinnen** [TheWidlarzGroup/react-native-video#2313]
# Bug

Standard installation of react-native-video using react-native.config.js to configure ExoPlayer. The video loads and starts correctly with paused={false}. The controls are displayed correctly when starting. Pressing the pause button, the video stops. Instead of replacing the Pause-Button with the Play-button, no button is shown. After opening the controls again, everything is fine and will be fine onwards. 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/9108609/111002674-22584a80-8386-11eb-9d26-789373798af8.png">

## Platform
Android Exoplayer

Which player are you experiencing the problem on:
* Android ExoPlayer, Android phone Google Pixel 4a and emulator

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 524.88 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.11.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: "react-native-video": "^5.1.1"

## Steps To Reproduce

1. open React-native project
2. use react-native.config.js to configure ExoPlayer

module.exports = {
    dependencies: {
        'react-native-video': {
            platforms: {
                android: {
                    sourceDir: '../node_modules/react-native-video/android-exoplayer',
                },
            },
        },
    },
};

3. add video component, with pause={false} and controls={true}
4. Open Video, and press pause -> the button will disappear, and not replaced by play
...

## Expected behaviour

1. after Pause-button disappears, Play-button should appear

**Comment by tonyjeffrey** [comment]
reLayout(playerControlView); // reLayout before playControlView show in two place 
playerControlView.show();

**Comment by ateeq4112** [comment]
@tonyjeffrey  can you elaborate above answer??

**Comment by C0rren** [comment]
Not my proudest work, but if someone wants a hack that fixes this issue without altering the package, I found that adding this...

```
onReadyForDisplay={() => {
    // This "hack" causes the video to play for a split second a couple of times, fixing the play/pause button disappearing on first click bug
    if (!hasBeenInitialized) {
        setHasBeenInitialized(true);
        // Play the video
        setIsPaused(false);
        // Wait 50ms
        setTimeout(() => {
            // Pause the video
            setIsPaused(true);
            // Wait 150ms
            setTimeout(() => {
                // Play the video
                setIsPaused(false);
                // Wait 50ms
                setTimeout(() => {
                    // Pause the video
                    setIsPaused(true);
                    // Wait 150ms
                    setTimeout(() => {
                        // Show the video
                        setIsPlayerVisible(true);
                    }, 150);
                }, 50);
            }, 150);
        }, 50);
    }
```

...makes this issue disappear. If you want autoplay behaviour just invert the isPaused state from my example. In case it's unclear, `isPaused` and `isPlayerVisible` are boolean values which control the paused state of the player. You can use the `isPlayerVisible` boolean to hide the video (opacity: 0) until the play/pausing is done, so that the user doesn't have to see it. Maybe it's possible to remove some of the timeouts, experiment on your own. Simply waiting for single event loops (0ms timeouts) didn't work for us. I think it's also worth noting that the behaviour was different in the debug build, so make sure you don't test this in debug.

**Comment by chiragramimi** [comment]
I am also getting this issue with the same steps.
