### ISSUE TITLE
How to cater for portrait videos to go fullscreen on different screen sizes?

### ISSUE THREAD

**Issue by chai86** [TheWidlarzGroup/react-native-video#2314]
I'll be loading mostly vertical (portrait) videos. I would like this to occupy the FULL screen. setting `fullscreen={true}` doesn't work.

How do I ensure that for each video size that comes in, the video can cater for the different video sizes on different screen resolutions?

**Comment by irwing-reza** [comment]
Have you tried setting the resizeMode prop https://github.com/react-native-video/react-native-video#resizemode ?
