### ISSUE TITLE
Unmute does not work.

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#232]
I tried to change `muted` property based on state (to create mute / unmute button). Changing from `false` to `true` works and video is muted. OTOH, changing it back to `false` does not resume the sound.

Android 4.2.2, RN 0.26, react-native-video 0.8.0-rc.

[Read "changing" as "calling `setState` in parent and rerendering the `Video` as a result, with different `muted` prop value]

**Comment by ghost** [comment]
@ghost I see this has been open for a while. Any luck?

**Comment by mattapperson** [comment]
Closing due to lack of feedback, if this is still an issue please feel free to re-open 😊
