### ISSUE TITLE
Phone Goes to Sleep and Audio/Video stops even with preventsDisplaySleepDuringVideoPlayback={true}

### ISSUE THREAD

**Issue by codasana** [TheWidlarzGroup/react-native-video#2323]
I'm using version 5.1.0-alpha8.

And have set preventsDisplaySleepDuringVideoPlayback={true}

On Android, it works file, i.e., while the audio is playing, the phone doesn't sleep.

However, on iOS it's not working that way. The phone still goes to sleep and the audio stops after a few seconds of playing. How can I correct this?

Thanks!

**Comment by albmin** [comment]
not a solution to this specific library issue, but if you need a workaround I'd suggest using [react-native-keep-awake](https://www.npmjs.com/package/react-native-keep-awake)
