### ISSUE TITLE
Is it possible to play a video from a stream?

### ISSUE THREAD

**Issue by Billmike** [TheWidlarzGroup/react-native-video#2324]
I have a video in the following URL [here](https://watch.cloudflarestream.com/64efd68a065f09d4df8622beeae55f1f). It's to be played from a CDN as a stream and doesn't end in the typical `.mp4` extension. I tried passing this as the video uri, but it doesn't work on Android. When I console the error in the `onError` method, this is what is logged to the console

```
{"error": {"extra": -2147483648, "what": 1}}
```

Any idea what's wrong here?

**Comment by KrzysztofGastolek** [comment]
Try this https://stackoverflow.com/questions/63234718/unable-to-play-drm-video-with-react-native-video-drm-fork-in-android
