### ISSUE TITLE
Blank screen after multiple videos loads (Android)

### ISSUE THREAD

**Issue by ALexandreM75013** [TheWidlarzGroup/react-native-video#2325]
# Bug

I have a flatlist that only shows one item at the time which is a `<Video />`, and after multiple scroll in the Flatlist to see the other videos, they do not load anymore and I have a blank screen instead.  If I scroll up to go back to the videos previously shown, they also have now a blank screen for every of them.

The only way to see again the videos is to restart the app.

My videos are coming from an URL and are not stored on the device. The videos are small (3mb).

Note : after several minutes while the blank screen is shown on the device and not touching at all, the videos restart to play. If I scroll again to see several videos, the problem restart after viewing multiple videos.

## Platform
Android Exoplayer

Which player are you experiencing the problem on:

* Android ExoPlayer

## Environment info

Node: 12.18.4
Yarn: 1.2.1
npm: 6.13.4
react: 17.0.1
react-native: 64

Library version: 5.1.1

Tested on a real device (Samsung S10)

I did not test on IOS

## Steps To Reproduce

1. Make a Flatlist with videos. Make sure to render the video only for the visible item on screen. All the videos outside the screen must be unmount.
2. Scroll in the list. For each scroll you should render a new video. After several `<Video />` rendered, you will a have blank screen for all the videos.

## Expected behaviour

1. There should be no blank screen.

## Reproducible sample code

```
class App extends Component {

...

renderItem = ({ item, index }) => {
    if (index === this.state.index_on_screen) {
      return (
        <Video source={{ uri: "XXXXXXXXXXXXXXX.mp4" }}
          ref={(ref) => {
            this.player = ref
          }}                                      // Store reference
          onBuffer={this.onBuffer}                // Callback when remote video is buffering
          onLoadStart={this.onLoadStart}
          onLoad={this.onLoad}
          onError={this.videoError}               // Callback when video cannot be loaded
          style={styles.VideoStyle}
          onSeek={this.onSeek}
          repeat
        />
      )
    }
    return (
      <View style={styles.VideoStyle}>
        <Text style={{ color: '#fff' }}>
          {index}
        </Text>
      </View>
      );
    }


  render() {
    return (
      <FlatList
        style={{ flex: 1 }}
        pagingEnabled
        onViewableItemsChanged={this.onViewableItemsChanged} //This will set this.state.index_on_screen with the correct index
        data={[{ item: 1 }, { item: 2 }, { item: 3 }, { item: 4 }]}
        renderItem={this.renderItem}
      />
    );
  }
```

**Comment by enigmablue** [comment]
I have something similar, but i use viewpager and then react-native-video.
I checked the logs and i can see that its stuck on isBuffering.

 I/ReactNativeJS: 'videoload starting buffer ', { isBuffering: true }
 I/ReactNativeJS: 'videoload on load start', {}

Is there a way to track the buffeering?

**Comment by sheshnathiicmr** [comment]
I have similar in flatlist, now and then it shows a blank screen

**Comment by facundomoreno** [comment]
Having the same issue 🙋‍♂️

**Comment by SiddigHope** [comment]
any solution yet? I'm facing the same problem

**Comment by zchwyng** [comment]
+1

**Comment by shubhamverma27** [comment]
Hey Guys,
I am facing the same issue when using react native video with exoplayer inside a flat list.
From what I was able to deduce is that this is happening due to the following reason:- 
Every element in the flat list creates a new ReactExoplayerView which further creates a new ExoPlayerView which further creates a new SimpleExoPlayer object for each element inside our flat list.
Now even though we render only one element inside react native, somehow the native ExoPlayerView doesn't get removed and when a lot of such objects come in memory they block all the HTTP calls for the app, and all further videos or even images stop loading.

**Comment by scvgoe** [comment]
+1

**Comment by GustavPS** [comment]
Same issue, though I only have one Video element on a page, works a few times but after I change the video (re-render the component) 5-10 times it stoppes working and onLoad is event is never fired. I am using a HLS source (m3u8)

**Comment by GustavPS** [comment]
I think it has something to do with memory usage. I tried this with the Memory profiler enabled and when this happens the RAM usage stays the same (about 500MB). If I wait long enough (some minutes) it actually starts playing, but the RAM usage spikes up to 2GB and then the app crashes

**Comment by manthanshah23** [comment]
+1

**Comment by RioAU** [comment]
> Same issue, though I only have one Video element on a page, works a few times but after I change the video (re-render the component) 5-10 times it stoppes working and onLoad is event is never fired. I am using a HLS source (m3u8)

Hey @GustavPS , Did you found any better solution , I am facing same issue and trying to solve since last couple of day.

**Comment by GustavPS** [comment]
> > Same issue, though I only have one Video element on a page, works a few times but after I change the video (re-render the component) 5-10 times it stoppes working and onLoad is event is never fired. I am using a HLS source (m3u8)
> 
> Hey @GustavPS , Did you found any better solution , I am facing same issue and trying to solve since last couple of day. 

No, I've kind off accepted this issue since this won't really happen so much for my users. I mostly see this issue when I'm debugging and opening the same video multiple times

**Comment by brunolcarlos** [comment]
This is a FlatList bug, I keep trying to fix the same bug.
