### ISSUE TITLE
Offline M3U8 file is not running in IOS

### ISSUE THREAD

**Issue by Rishabh6211** [TheWidlarzGroup/react-native-video#2331]
# Bug
I am trying to run offline streaming file using react-native-video in iOS but its not supporting.

<Video
         source={{uri:require('./video/chunklist_w79586375.m3u8')}}
          style={{ width: 350, height: 300 }}
          muted={true}
          repeat={true}
          resizeMode={"cover"}
          volume={1.0}
          rate={1.0}
          ignoreSilentSwitch={"obey"}

**Comment by puneetkansal04** [comment]
@Rishabh6211  any success?

**Comment by Rishabh6211** [comment]
Yup @puneetkansal04 I am using react native jw media player

**Comment by puneetkansal04** [comment]
Hi @Rishabh6211 I tried to play .m3u8 from local folder and also tried with save a video folder in the mobile location. But it is not playing. Can you provide me some more details that how can i use it.

file: `file://${RNFS.MainBundlePath}/videolist/video.m3u8` this is not worked for me
also i tried by adding a folder within project.

can you please provide me some details regarding it.

**Comment by moskalakamil** [comment]
Hey all!

We can’t simply save the `.m3u8` file as-is, but we’ve recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=2331) that lets you download and play video content offline - including DRM-protected streams.  
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:  
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=2331)

**Comment by manssorr** [comment]
@moskalakamil

Is there any way to save hls/m3u8 for offline? with out DRM? (free, with out the offline SDK)
