### ISSUE TITLE
selectedVideoTrack by "index" does not work

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [TheWidlarzGroup/react-native-video#2332]
# Bug

Hi everyone, i'm using react-native-video 5.1.1 in my android app and I'm having the following problem: when I try to change the video quality (720p,480p,360p) by using the prop selectedVideoTrack using the type:"index" with value: 0,1 or 2 the video does not change the quality...when using type:"resolution" with value: 360, 480 or 720 it works.

There is anyone with the same problem?

## Platform
Android

Which player are you experiencing the problem on:

* Android ExoPlayer

## Environment info

react-native-video: 5.1.1

**Comment by siddharthkr** [comment]
@JoaoCEAlmeida did you got the solution ?

**Comment by GustavPS** [comment]
Having the same problem

**Comment by JoaoCEAlmeida** [comment]
Try this:

![image](https://user-images.githubusercontent.com/9196047/147939234-91c934ba-dcfb-42df-b85f-596437b0a276.png)

**Comment by skfaisal93** [comment]
@JoaoCEAlmeida can you share your code how you are doing with type:'resolution'. In my case it does not work atall

**Comment by JoaoCEAlmeida** [comment]
@skfaisal93 I'm doing it by index with the change I printed.

**Comment by skfaisal93** [comment]
@JoaoCEAlmeida you made changes in java file. Is there any way we can do this by making changes in js file?

**Comment by JoaoCEAlmeida** [comment]
@skfaisal93 No.

You can make use of this to change the java file: https://www.npmjs.com/package/patch-package
