### ISSUE TITLE
Voice not working in some .m3u8 HLS streams

### ISSUE THREAD

**Issue by CarlosBM18** [TheWidlarzGroup/react-native-video#2335]
I'm trying to build an IPTV stream app. I have some .m3u8 streams to show in the app, and the problem is that for almost all of them the audio is not working. It's weird because the are some of them that work fine. I tested the links that have no voice in the VLC Media Player and the audio is working fine. So I suppose that is a problem with the library.

I tested it on Android MediaPlayer and Android ExpoPlayer and none of them works.

This is were I'm running it on:
`System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 3.43 GB / 15.92 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-windows: Not Found`

Library version: 5.1.1

You can try it with this two URL's: 
http://zornitio.online:8080/live/FvWjsLJjCt/NDDfaSSgWN/135456.m3u8 // audio works
http://zornitio.online:8080/live/FvWjsLJjCt/NDDfaSSgWN/135463.m3u8 // audio not works
## Reproducible sample code

`<Video
            source={{uri: url}} // Can be a URL or a local file
            style={{
    width: '100%',
    height: 200,
  }}
            resizeMode={'contain'}
          />`

I hope that you can help me! Thank you :)

**Comment by redefinered** [comment]
it doesn't even play m3u8 on android. have you tried?

**Comment by redefinered** [comment]
the 2 example url strings you listed are identical BTW

**Comment by vivkikkk** [comment]
@CarlosBM18   how to
