### ISSUE TITLE
Blanck screen on Windows

### ISSUE THREAD

**Issue by maribeiroleya** [TheWidlarzGroup/react-native-video#2336]
Hi, iam problems with the library in react-native on windows.
In debug mode run. But in release mode appears a black screen.

I need the solution for this problem, please.

Environment:

OS: windows 10
OS version: 19042.746
react-native version:0.64.0
react-native-windows version:0.64.0-0
react-native-video version:5.1.1

**Comment by hondek** [comment]
I have same issue, everything is fine in debug, but on release react app crash after render Video component.

**Comment by hondek** [comment]
On 
```
"react-native": "0.63.4",
"react-native-video": "^5.1.1",
"react-native-windows": "^0.63.0-0"
```

everything is fine,

but on RN 0.64.0 and RNW 0.64.0 on Release not work.

**Comment by SonPH088** [comment]
+1 issue. Did u find how to fix this? thanks.

Here is my environment:
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.97 GB / 15.81 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-cli: ^2.0.1 => 2.0.1
    react-native-windows: ^0.64.14 => 0.64.14
  Installed UWP SDKs:
    10.0.18362.0
    10.0.19041.0

**Comment by maribeiroleya** [comment]
No, i don’t find the solution.

**Comment by SonPH088** [comment]
I found issue  #2399. He can play video at release mode by change the video path to URI. I also try this but not work :( 

Did u found other ways to play videos on windows?

**Comment by maribeiroleya** [comment]
Try with a webview

**Comment by SonPH088** [comment]
I can play video in release mode now. Turn out, It only works in react native ver 0.63 and react-native-windows ver 0.63 also. You should try this.

**Comment by Boiko33** [comment]
Same issue with react-native 0.66.1 and react-native-windows 0.66.1

**Comment by jensonstack** [comment]
+1 
Blank screen in windows release mode. Work fine in debug mode

```
System:
    OS: Windows 10 10.0.20348
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 3.18 GB / 8.00 GB
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\2\yarn--1637145464397-0.6832947000591538\node.CMD
    Yarn: 1.22.15 - ~\AppData\Local\Temp\2\yarn--1637145464397-0.6832947000591538\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0, 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31729.503 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.0 => 0.64.3
    react-native-windows: 0.64.25 => 0.64.25
  npmGlobalPackages:
    *react-native*: Not Found
```


   ```
"react-native": "^0.64.0",
  "react-native-video": "^5.2.0",
   "react-native-windows": "0.64.25"
```

**Comment by Boiko33** [comment]
Hi, @jensonstack ! I solved that issue by install react-native-video from pull request. You could try this
`"react-native-video": "github:react-native-video/react-native-video#pull/2296/head"`

For me it started working after I fully reinstalled this library and made a rebuild.

**Comment by jensonstack** [comment]
Thanks, @Boiko33 It woked. You saved my day.
For me, it started working after I fully reinstalled this library and made a rebuild, and changes were made in assigning source
```
const splashVideo = Platform.OS === 'windows' ? {uri: 'ms-appx:///Assets/video.mp4'} : require('../../../assets/videos/video.mp4'); 
<Video source={splashVideo} // Can be a URL or a local file.
   ref={refVideo} // Store reference
   //onBuffer={this.onBuffer} // Callback when remote video is buffering
   onError={onVideoError} // Callback when video cannot be loaded
   paused={isPaused}
   onEnd={() => onVideoEnd()}
   style={styles.backgroundVideo} />
```
Please note I placed the videos in the Asset folder like #2399 and add to Asset folder in Visual Studion Solution
<img width="715" alt="Screen Shot 2021-11-18 at 11 23 41 AM" src="https://user-images.githubusercontent.com/93758752/142362278-ff9b6667-a408-4e78-9aa9-dd48a1b1331a.png">
