### ISSUE TITLE
Sound from video link does not play on iOS

### ISSUE THREAD

**Issue by khuongsatou** [TheWidlarzGroup/react-native-video#2339]
# Bug
I to try android it working, but when  to try it not working IOS, can you tell me know why IOS not play sound. Please.

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. Link video: https://kidbox.vn/media/2021/4/6/akidbox-video0-1617691890_1617691892821.mp4
2. Sound not play 
...

## Expected behaviour

1.
2.

## Reproducible sample code

![image](https://user-images.githubusercontent.com/44874881/113701189-04220800-9702-11eb-8a98-c60f0d6cafef.png)

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by iljaiwjew** [comment]
I have the same bug, ios 14, react-native 0.64, react-native-video 5.1.1

**Comment by ssancheza227** [comment]
I have a similar problem, in my case, I set Uri in source but it doesn't display the video... :/ any idea?
react-native-video: 5.1.1
react-native: 0.63.4
@khuongsatou in IOS, you just installed the library? or configure anything more?

**Comment by ssancheza227** [comment]
I already have the answer, my problem was that I tried display a video from youtube but react-native-video support generally .mp4, so I will use react-native-youtube-iframe or react-native-webview. good day :D
More info: https://stackoverflow.com/questions/57413156/play-youtube-video-in-react-native-video

**Comment by khuongsatou** [comment]
> I have a similar problem, in my case, I set Uri in source but it doesn't display the video... :/ any idea?
> react-native-video: 5.1.1
> react-native: 0.63.4
> @khuongsatou in IOS, you just installed the library? or configure anything more?

I found the reason that the video link opened by safari didn't play the sound, so I asked the "team backend" to decode the link and play the video on safari it also worked with react webview.

**Comment by ghacosta** [comment]
Hey I'm having this video [https://stream.mux.com/fHTBBwJGJT44eTVqHhp6zp1htrGmmZ99dzAI01aySibU.m3u8](https://stream.mux.com/fHTBBwJGJT44eTVqHhp6zp1htrGmmZ99dzAI01aySibU.m3u8) which shows OK in no time but without any sound, I tested on safari and VLC and audio is there.

This is happening on iOS, "react-native": "0.64.3", "react-native-video": "^5.2.0",

**Comment by amie-wilt** [comment]
@ghacosta I was having the same issue. I noticed in the issuer's screenshot he's using an `ignoreSilentSwitch='ignore'` prop. That worked for me, might wanna give it a shot.
