### ISSUE TITLE
[ANDROID]can hear audio but cannot see video

### ISSUE THREAD

**Issue by void117** [TheWidlarzGroup/react-native-video#234]
if i use a local path,such as /sdcard/video/... 
i can not see the video,but if i change the uri,use the video in raw,plays well.

**Comment by bcalik** [comment]
This issue started happening to me.
The weird thing is; I switch to another app, then switch back to my app, now I can see the video.

**Comment by bcalik** [comment]
After an hour I figured out the issue. If you try to resize video after it is already loaded, like using flex: 1 within a View, it won't work. So my workaround is; when I need to resize, I delete the video component then recreate another one.

**Comment by alessandro-bottamedi** [comment]
I have the same issue, i can see the video only when Video is not a child of a View component... 
(video is in raw dir)

**Comment by duyluandethuong** [comment]
same here :D

**Comment by duyluandethuong** [comment]
Just figure out that the video DOES PLAY on a real device. The emulator seems not to be able to run the video. So, move on now guys.

**Comment by kvnvelasco** [comment]
if you're using hot-reloading on an emulator try reloading it. on android it's cmd+m then clicking reload. 

Does it for me.

**Comment by ghost** [comment]
Closing as comments indicate this is an issue with the emulator or procedure used.

**Comment by MariusGarbea** [comment]
Still happening to me, both on emulator and physical device. Tried rendering only the Video component right in the root and with different URIs (a mp4: https://falcon479.startdedicated.com/files/round_boxes.mp4 and a mp3: http://feeds.soundcloud.com/stream/328711565-bucurestiultinerilor-podcast-bucurestiul-tinerilor-1-ce-este-si-ce-urmeaza.mp3). Can only hear the audio.

My component looks like this: `<Video source={{uri: "https://falcon479.startdedicated.com/files/round_boxes.mp4"}}/>`
