### ISSUE TITLE
[iOS] Changing source URI causes sound of first video to continue playing

### ISSUE THREAD

**Issue by jfbn** [TheWidlarzGroup/react-native-video#2345]
# Bug

Changing the source of the video player will keep the audio from the first video running, even when the next video has been loaded into the view.

## Platform
* iOS

## Environment info

React native info output:

```bash
System:
  OS: macOS 11.2.3
  CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Memory: 34.64 MB / 8.00 GB
  Shell: 5.8 - /bin/zsh
 Binaries:
  Node: 14.15.1 - /usr/local/bin/node
  Yarn: Not Found
  npm: 6.14.8 - /usr/local/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
 Managers:
  CocoaPods: 1.10.1 - /Users/gamerzclassmabook/.rvm/rubies/ruby-2.6.5/bin/pod
 SDKs:
  iOS SDK:
   Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  Android SDK: Not Found
 IDEs:
  Android Studio: Not Found
  Xcode: 12.4/12D4e - /usr/bin/xcodebuild
 Languages:
  Java: Not Found
  Python: 2.7.16 - /usr/bin/python
 npmPackages:
  @react-native-community/cli: Not Found
  react: 17.0.1 => 17.0.1 
  react-native: 0.64.0 => 0.64.0 
  react-native-macos: Not Found
 npmGlobalPackages:
  *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Start a video with audio 
2. Programatically update the source URI
3. Listen as the audio from the first video continues

## Expected behaviour

1. Start a video with audio
2. Programatically update the source URI
3. Listen as the only audio you hear is from the new video

**Comment by SquirrelMobile** [comment]
I have the same issue, how to solve it please ?

**Comment by freeboub** [comment]
@SquirrelMobile This issue shall be fixed on last V6 release
