### ISSUE TITLE
onLoad gets called but video won't play on poor connections

### ISSUE THREAD

**Issue by 3DJakob** [TheWidlarzGroup/react-native-video#2346]
# Bug

When running this module on poor connections (steps to simulate connection listed below) the onLoad will fire after a while but the video will simply not get passed frame 1. My understanding of the onLoad is that the whole video should be loaded in. Tested using video from uri with a 10MB file.

## Platform
iOS

Which player are you experiencing the problem on:
* iOS

## Environment info

"react-native-video": "^4.4.5",

React native info output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 218.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.3 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1.  Make a simple video component like this:
```
<Video
            source={{
              uri: CDNLink
            }}
            style={{
              width: 100,
              height: 200,
            }}
            fullscreen
            repeat
            paused={false}
            onLoad={(e) => console.log('Im done loading!')}
/>
```
2. On the iOS test device go to settings -> developer -> Network link conditioner
3. Select the 3G preset and turn on the Enable toggle. (Before doing this it might be useful to start the app and load the bundle to speed things up)
4. Look for the console log. In my case, the log will appear after a while but the video won't start playing.

## Expected behaviour

The video starts playing when the log appears.

**Comment by mizefsl** [comment]
Any update on this issue? Here, using iOS, `onLoad` is fired before the video is ready to play, sometimes few seconds before

**Comment by Bogdastotel** [comment]
did someone solve this issue?

**Comment by freeboub** [comment]
@Bogdastotel ios implementation has been rewritten in V6, is it still reproduced with V6 ?

**Comment by Bogdastotel** [comment]
@freeboub Hmm currently I am using 5.1.1 ... thanks
