### ISSUE TITLE
Color changes in some devices

### ISSUE THREAD

**Issue by mbuenaventurac** [TheWidlarzGroup/react-native-video#2347]
# Bug

I am trying to play an mp4 video with the same background as the screen background so that there is no difference between inside and outside the video container. In some devices it works as expected since the color of the video is the same (or very similar) to the expected one. However in other devices there is a significant difference on the color of the video. 

<img src="https://user-images.githubusercontent.com/24354919/114618448-a5343400-9ca9-11eb-8242-f3646a85f328.png" height="400">
<img src="https://user-images.githubusercontent.com/24354919/114618438-a06f8000-9ca9-11eb-97c1-4e46d31ac55e.png" height="400">

Does anyone know why could this be happening? 
I have already tried to fix the resolution and to use SurfaceView instead TextureView but it didn't fix the issue.

## Platform

Which player are you experiencing the problem on:
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.35 GB / 7.86 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: 23.0.7123448-beta1
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.0-alpha8

## Steps To Reproduce

1. Copy code to App.js
2. Create 'images' folder and copy video in there
3. Run and check if color video is changed
Note: difficult to test with only one device, may not have the issue in that specific device.

https://user-images.githubusercontent.com/24354919/114627229-352bab00-9cb5-11eb-8cf3-a1b8b091a876.mp4

## Expected behaviour

1. Video should play automaitcally at app init
2. Video color should be the same as the background

## Reproducible sample code

```
import React from 'react';
import { Platform, StatusBar, StyleSheet, View, Text } from 'react-native';
import Video from 'react-native-video';

export default function App(props)
{
  console.log('APP STARTED AS CONTAINER');
  return (
    <View style={styles.container}>
    <View style={styles.videoView}>
      <Video
        source={require('./images/video.mp4')} // Can be a URL or a local file.
        ref={(ref) => { this.player = ref }}  // Store reference
        style={styles.videoStyle}
        paused={false}
        resizeMode={"contain"} />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#6b31a5',
  },
  videoStyle: {
    width: 290,
    height: 290,
    alignSelf: 'center',
    alignItems: "center",
    justifyContent: "center",
  },
  videoView: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by iamharky** [comment]
Same problem here..

**Comment by emilstepanian** [comment]
Same issue here

**Comment by tbergeron** [comment]
The same happens for me. For example I have this color #FF6666 in a video and when it's being played I see #f3576a which is a totally different color. Why would that even happen?

**Comment by coucoseth** [comment]
any fix to this issue?, my videos display a different color on android tv
