### ISSUE TITLE
Should we consider to have a section on README to list apps using the lib?

### ISSUE THREAD

**Issue by donnguyen** [TheWidlarzGroup/react-native-video#235]

**Comment by gravitinos** [comment]
I don't see why not. I vote yes.

**Comment by ghost** [comment]
@donnguyen that would be pretty difficult to maintain when the info is stored in near realtime on GitHub.

https://github.com/search?l=json&q=react-native-video&type=Code&utf8=✓

**Comment by mattapperson** [comment]
If a major app uses it we would want to show it off to give devs more confidence. Other then that @jhabdas would be correct... too much to maintain, even though it is a nice idea 😊
