### ISSUE TITLE
Close Button problem with Modal

### ISSUE THREAD

**Issue by nammiharika** [TheWidlarzGroup/react-native-video#2354]
Hi All,

I am trying to open a video through modal and using controls={true} but when click on the  Close Icon player is closing but still modal isvisible variable is settings to true only,after that I am unable to click on any things on my screen

Could any one please suggest me any idea how we need to go ahead with this issue please...

**Comment by pragadeeshk** [comment]
I am facing the same issue. I also noticed the close button is shown only if the video view is placed in the modal.

**Comment by maendamedia** [comment]
Any updates on this?

**Comment by LeQuy-123** [comment]
currently I am custom my own controls and don't show the close button but it will be great if there is event callback when click this close button

**Comment by anatooly** [comment]
Any updates on this?

**Comment by freeboub** [comment]
I am not sure to understand the issue, but the modal shall control the player, not the opposite.

**Comment by freeboub** [comment]
I am not sure to understand the issue, but the modal shall control the player, not the opposite.

**Comment by anatooly** [comment]
@freeboub unpossible hide close button or nothing callback for this. After press close button, modal hide but app freeze & not scrollable. All people who solve this problem use other package for custom controls.
