### ISSUE TITLE
Feature Request  Upgrade Exoplayer dependency to 2.13.0 or newer

### ISSUE THREAD

**Issue by santiberruti1** [TheWidlarzGroup/react-native-video#2356]
**Upgrade Exoplayer dependency to 2.13.0 or newer**

**Why it is needed**
We are working on a project to test Low Latency HLS on different players. 
Exoplayer in react-native-video currently works with version 2.11.4 and it does not support LL-HLS.
The first realse of Exoplayer to support LL-HLS is 2.13.0.

Thanks,
Santiago

**Comment by santiberruti1** [comment]
Finally, I made a fork and did it myself. I don't know if its possible to merge the changes I made in my fork with the real project again, but if someone can help me I would be glad to do it. Just answer this comment and I will give you my mail or something.

**Comment by JulianPenaBwired** [comment]
> Finally, I made a fork and did it myself. I don't know if its possible to merge the changes I made in my fork with the real project again, but if someone can help me I would be glad to do it. Just answer this comment and I will give you my mail or something.

Did you find a way to update the dependency?, Im having some issues with my app and I think is the exoplayer version is too old If you can help me it will be appreciated.

**Comment by santiberruti1** [comment]
Sorry for the late reply @JulianPenaBwired, 
Maybe you can install my fork: https://github.com/santiberruti1/react-native-video
and check if your problem is resolved with version 2.13.3 of ExoPlayer.

Use this in the terminal:
npm uninstall react-native-video
npm install git+https://github.com/santiberruti1/react-native-video

If you resolve your issues you can make your own fork or use mine. :)

**Comment by androidparth90** [comment]
Hi @santiberruti1 : thanks for the fork. Can your fork help resolve this issue https://github.com/react-native-video/react-native-video/issues/2381. Are your videos getting buffered properly? I am using the latest version of react-native-video with an older version of exo player at the moment

**Comment by jasmeet447** [comment]
HI @santiberruti1, I experienced a similar kind of issue and needed to update the exoplayer on react native video. Therefore I installed the videoplayer from your repo and I'm getting the video response now but the player crashes unexpectedly, leading to the app crash. I can't see anything on the logs and don't know what to do. Can you please check it out?
