### ISSUE TITLE
Video won't be displayed only when set paused = true

### ISSUE THREAD

**Issue by DIGITALSQUAD** [TheWidlarzGroup/react-native-video#2358]
# Bug

I've upgraded react native from 59.9 to 63.3 and react-native-video from 4.4.1 to 5.1.1.    
It worked fine before but video won't be displayed only when set paused = true after upgrading.

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 100.85 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/tahara_satoshi/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Select video from gallery

## Expected behaviour

1. The first frame of the video should be displayed 
## Reproducible sample code
```
// variables medium, data and index is passed as argument.
<Video
  style={{
    width: 50,
    height: 50,
    marginRight: 5
  }}
  source={{ uri: medium['path'] }}
  paused={true}
  resizeMode='contain'
  muted={true}
  onLoad={data => { this.checkVideo(data, index) }}
/>,
```
**Displayed successfully when paused = false**
![paused-false](https://user-images.githubusercontent.com/6149827/115536036-49366480-a2d4-11eb-93ff-e0851b95ce6e.png)

**Not displayed when paused = true**
![paused-true](https://user-images.githubusercontent.com/6149827/115536045-4cc9eb80-a2d4-11eb-98dd-e8c0de417cb4.png)

**Comment by DIGITALSQUAD** [comment]
Managed to display paused video set paused as false and added **rate** as **0.0**, but sill can't display when set paused as true.

**Comment by vivianlys90** [comment]
Having same issue for Android. Working well in iOS. Any workaround / solution for this issue ?

**Comment by vivianlys90** [comment]
> Managed to display paused video set paused as false and added **rate** as **0.0**, but sill can't display when set paused as true.

Hi, can I take a look on your code for setting paused as false and added rate as 0.0 ? I doing the same thing but not able to pause the video.

Here is my code:
`<Video
        source={{
          uri: fileURL,
        }}
        style={{
          ...styles.viewContainer,
          ...style,
          ...{
            height: height,
            width: width,
            minWidth: normalizePixel(100),
            minHeight: normalizePixel(100),
          },
        }}
        ref={(ref) => (videoViewRef.current = ref)}
        onBuffer={videoBuffer} // Callback when remote video is buffering
        onError={(error) => videoError(error)} // Callback when video cannot be loaded
        resizeMode="cover"
        // paused={pauseVideo}
        paused={false}
        rate={0.0}
        onLoad={(data) => setVideoOnError(false)}
        onFullscreenPlayerDidDismiss={() => onFullScreenDismiss()}
        onEnd={() => onLoadEnd()}
        repeat={true}
      />`

**Comment by DIGITALSQUAD** [comment]
Would you please indent your code correctly? It's hard to read.
I'm not sure, but you set paused attributes twice. The result might be affected if **pauseVideo** value is true or something string.
I've just set paused as false and added rate 0.0, that's all.
```
paused={pauseVideo} 
paused={false}
```

**Comment by sommesh** [comment]
Any workarounds?
Still getting the same issue.

**Comment by AxayDixit** [comment]
@DIGITALSQUAD you found anything related to this? I'm facing this on iOS. In my case android is good.

**Comment by dominicdev** [comment]
still having issue here.. any workaround?

**Comment by nikoloz110** [comment]
I am also having same issue

**Comment by tuananh24a** [comment]
still having issue ...

**Comment by Mujtaba-Ali21** [comment]
2024 still same, anybody found any solution?

**Comment by Mujtaba-Ali21** [comment]
Hi again, I just found a workaround:

```
const [isPaused, setIsPaused] = useState(false);

<Video
paused={isPaused}
onLoad={() => { setIsPaused(true); }}
/>
```

**Comment by freeboub** [comment]
just tested in the sample app in the repo, it works fine on V6 ...
