### ISSUE TITLE
error: {extra: -2147483648, what: 1}.

### ISSUE THREAD

**Issue by SupriyaGo** [TheWidlarzGroup/react-native-video#2359]
Hi, I am using react native video lib on my project. When implementing a video through uri: I am getting this error from the onError method - 
error: {extra: -2147483648, what: 1}.

Could not get any lead regarding this issue, can anybody help
TIA

**Comment by LamkasDev** [comment]
+1

**Comment by LamkasDev** [comment]
I solved this by adding a `react-native.config.js` file to root of my project with:
`module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`

**Comment by SupriyaGo** [comment]
@LamkasDev whenever I am trying to use exo player, my app is crashing on the same page contains video player

**Comment by Afzal-shaikh** [comment]
> I solved this by adding a `react-native.config.js` file to root of my project with:
> `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`

After doing this i get the following error

{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404", "errorString": "Unrecognized media format"}}

**Comment by nitrosalat** [comment]
@Afzal-shaikh Try another video format. I used webm for android but it seems that Exoplayer does not support this format. I tried mp4 and it finally works

**Comment by LamkasDev** [comment]
> > I solved this by adding a `react-native.config.js` file to root of my project with:
> > `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`
> 
> After doing this i get the following error
> 
> {"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404", "errorString": "Unrecognized media format"}}

It depends on a lot of factors, like codec and container of the video. You can see supported formats for Exo Player in [this link](https://exoplayer.dev/supported-formats.html). The combination I use is H.264 video with AAC audio in mp4 container, because that seems to be supported on all platforms/devices.

**Comment by Hamza6244** [comment]
Is anyone found the solution for this error?

**Comment by pratik007kumar** [comment]
i am having same issue .
{"error": {"extra": -2147483648, "what": 1}}

**Comment by Hamza6244** [comment]
This issue is in your steaming video url as you can test it by pasting your streaming url in safari browser so you will see your video will not play.So you will have to fix this issue in server side





On Friday, January 28, 2022, 6:53 PM, Pratik kumar ***@***.***> wrote:




i am having same issue .
{"error": {"extra": -2147483648, "what": 1}}

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Leena-Sharma-rsys** [comment]
hi, 
facing same issue {"error": {"extra": -2147483648, "what": 1}} 
with all mpd and hls video files.
also i think its not linking exoplayer with android studio 

<img width="295" alt="video" src="https://user-images.githubusercontent.com/96762905/152146788-78dd975f-e9a5-4779-9e9c-1afd184b9419.png">

**Comment by pratik007kumar** [comment]
what is your video url?
it must be url end with .mp4. or so it can buffer.
you can try some public mp4 URL

**Comment by Leena-Sharma-rsys** [comment]
'https://dash.akamaized.net/dash264/TestCases/5a/nomor/1.mpd
it was working fine earlier, also the library supports exoplayer , which supports mpd and hls .
btw, mp4 url is working fine

**Comment by pratik007kumar** [comment]
your url is not playing in browser it should be play.

**Comment by Leena-Sharma-rsys** [comment]
@pratik007kumar  
thanks for the quick reply, i think browser dosn't support mpd file to play directly, thats why its not playing 
you can check this on https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html

also i would like to add it was working earlier, in similar project. but now its not

**Comment by wanderhungerbuhler** [comment]
> I solved this by adding a `react-native.config.js` file to root of my project with: `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`

This solution resolved for me today. Thanks my bro!

**Comment by iamsaadMehmood** [comment]
> I solved this by adding a `react-native.config.js` file to root of my project with: `module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`

resolved my issue Today. Thank You
