### ISSUE TITLE
Please support multiple video qualities through options

### ISSUE THREAD

**Issue by cisplRejjak** [TheWidlarzGroup/react-native-video#2360]
Please support multiple video qualities through options and also customizable with our own

**Comment by jesspinklet** [comment]
+1

**Comment by DevineDecrypter** [comment]
i am using a m3u8 video format to stream the movie from a hls link , but there is no option to choose the quality of the video .

**Comment by jannisringwald** [comment]
+1

**Comment by JSteegmueller** [comment]
+1

**Comment by DevineDecrypter** [comment]
The onLoad has a call back function which is supposed to have a payload consisting of properties listed [here](https://github.com/react-native-video/react-native-video#onload) :
`{"canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 596.52, "naturalSize": {"height": 360, "orientation": "landscape", "width": 640}}`
try this for yourself like this : 
`<Video 
    //...
    onLoad={(meta) => console.log(meta)}
 />`

if you are not getting videoTracks,textTracks,audioTracks add this to your `react-native.conifg.js` :
`module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer', }, }, }, }, };`
(thanks to [this ](https://github.com/react-native-video/react-native-video/issues/2349#issuecomment-826162967)comment)

**Comment by Kuljeet-123** [comment]
@DevineDecrypter  I have tried with that approach but its not working in my case.....can you please tell any other way to do this

**Comment by DevineDecrypter** [comment]
> @DevineDecrypter  I have tried with that approach but its not working in my case.....can you please tell any other way to do this

Make sure you are using HLS files for this to work, and make sure you have created the react-native.config.js and put the code i gave above in there.

**Comment by Kuljeet-123** [comment]
@DevineDecrypter  basically I'm using .m3u8 extension files but still not working.

**Comment by DevineDecrypter** [comment]
> @DevineDecrypter  basically I'm using .m3u8 extension files but still not working.

Can you provide the code for your <video /> component and the structure of your project?

**Comment by freeboub** [comment]
This feature has to be implemented in sample !
