### ISSUE TITLE
seek() is not accurated

### ISSUE THREAD

**Issue by lamlengend98** [TheWidlarzGroup/react-native-video#2361]
I created a video player by using slider, but when i moved the track to ~7s, seek video to same value and click play to resume, the video seeked to ~6s or 5s and then resume like my log is below. Why does it happen?? What should i do to fix it?
"react-native-video": "^5.1.1",
![image](https://user-images.githubusercontent.com/37770203/115853943-eec41200-a453-11eb-8c06-a93098a920b6.png)

**Comment by JowelTisso** [comment]
I am facing the same issue....

**Comment by Romick2005** [comment]
Can you please provide an example to reproduce the problem.

**Comment by mauhammadadnan** [comment]
i'm also facing same issue when ever you upload video then its not wokring fine(Especially for short video seek not working fine) when ever you drop seek at some specific seconds it go back to inital state(00:00) or sometime to above of range and some to lower of the range? IS IT ANY SOLUTION???@Benoit Dion

**Comment by androidparth90** [comment]
facing same problem as well. Did anyone find a solution?

**Comment by DevAhmad7** [comment]
go to path 'android/src/main/java/com/brentvatne/react/ReactVideoView.java' on the line 640:
and change this
```
- super.seekTo(msec);
+ super.mMediaPlayer.seekTo(msec, MediaPlayer.SEEK_CLOSEST);
```
work with me

**Comment by DevAhmad7** [comment]
go to path node_modules then react-native-video then
'android/src/main/java/com/brentvatne/react/ReactVideoView.java'
on the line 640: and change this
```java
- super.seekTo(msec);
+ super.mMediaPlayer.seekTo(msec, MediaPlayer.SEEK_CLOSEST);
```
work with me

> I created a video player by using slider, but when i moved the track to ~7s, seek video to same value and click play to resume, the video seeked to ~6s or 5s and then resume like my log is below. Why does it happen?? What should i do to fix it? "react-native-video": "^5.1.1", ![image](https://user-images.githubusercontent.com/37770203/115853943-eec41200-a453-11eb-8c06-a93098a920b6.png)

**Comment by alaindresse** [comment]
@DevAhmad7 , thank you for your patch that fixed the issue on my side as well.
I used [patch-package](https://www.npmjs.com/package/patch-package) to have that patched applied if I reinstall the node package.

Would be great if that could be merged into the package. What is the process for this to happen ?

**Comment by mhackeras** [comment]
Can you merge this with main so we can all enjoy this solution without having patches libs to added ? :) 
That would be so cool! :)
