### ISSUE TITLE
Fairplay DRM Error getting license

### ISSUE THREAD

**Issue by MaazF94** [TheWidlarzGroup/react-native-video#2364]
# Bug

I'm testing Fairplay from my application on a physical iOS device and receiving the error "Error getting license from skd://${ContentIdValue}, HTTP status code 403". With these exact same three URLs (source URI, license server, and certificate URL), this video does play from Shaka Player Demo.

I had no issues implementing Widevine. I've integrated ExpressPlay DRM with AWS MediaPackage. MediaPackage is where I get the source URL from. I stored my fairplay certificate in an s3 bucket, which is the URL I refer to. I call an API from expressplay to generate a license server URL. I know these are all fine because as mentioned, they work from Shaka Player Demo.

## Platform
iOS
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 271.01 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.0.14 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Pass your source URI, license certificate URL, and license server URL as props.

## Expected behaviour

1. Video should play

## Reproducible sample code

```
      <Video
        source={{
          uri: Source_URI,
        }}
        drm={{
          type: "fairplay",
          certificateUrl: Cert_URI,
          licenseServer: ExpressPlay_License_Acquisition_URL,
          headers: {
            "content-type": "application/octet-stream",
          },
        }}
        style={{ width: width, height: height }}
        resizeMode="contain"
        rate={1.0}
        volume={1.0}
        ref={videoRef}
        poster={movie.img}
      />
```

**Comment by MaazF94** [comment]
I've narrowed the issue down a bit further. I was debugging within RCTVideo.m and found on line 1798 is where my issue occurs.

`              
NSData *spcData = [loadingRequest streamingContentKeyRequestDataForApp:certificateData contentIdentifier:contentIdData options:nil error:&spcError];
`

I can confirm my certificateData is populated from the URL that I pass. I've tried passing different contentId's such as the KID (Resource ID from AWS Media Package), the Id of the asset, and the Id of the packaging group. I always receive an empty response with an error in spcError:

spcError	NSError *	domain: @"AVFoundationErrorDomain" - code: 18446744073709539816	0x00000002825df360

Which is probably the 403 forbidden error. When I looked the error code up in the Apple docs, it says Unknown Error, so not very helpful. Still not sure why this isn't working from my player but, works from shaka player demo.

Below is where the error is actually thrown:

`

                        NSLog(@"Error getting license from %@, HTTP status code %li", url, (long)[httpResponse statusCode]);
                        NSError *licenseError = [NSError errorWithDomain: @"RCTVideo"
                                                                    code: RCTVideoErrorLicenseRequestNotOk
                                                                userInfo: @{
                                                                            NSLocalizedDescriptionKey: @"Error obtaining license.",
                                                                            NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:@"License server responded with status code %li", (long)[httpResponse statusCode]],
                                                                            NSLocalizedRecoverySuggestionErrorKey: @"Did you send the correct data to the license Server? Is the server ok?"
                                                                            }

`

**Comment by matiasrodriguezbegueri** [comment]
Hi, how did you solve that?

**Comment by MaazF94** [comment]
I switched from ExpressPlay to PallyCon and had no issues. Tried everything I could for ExpressPlay and even worked with their support team
