### ISSUE TITLE
React-Native-Video Crash app problem

### ISSUE THREAD

**Issue by Mathieu-ROS** [TheWidlarzGroup/react-native-video#2365]
### Current behavior
I have my application that crashes when I use a local video ( '../Video/exemple.mp4' ) and I don't have a video that is displayed with an external link like Youtube.

PS: I would also like to know if Expo is compatible with react-native-video because when I use expo I have this error
" undefined is not an object (evaluating 'RCTVideoInstance.Constants') "

my code :

```
import React from 'react'
import { StyleSheet, View } from 'react-native'
import FilmList from '../Components/FilmList'
import { connect } from 'react-redux'
import Avatar from './Avatar'
import Video from 'react-native-video'

class Favorite extends React.Component {
  render(){
    return (
      <View style={styles.main_container}>
        <Video
        source={{uri: 'https://www.youtube.com/watch?v=z_gzUnskYO8'}}
        ref={(ref) => {
        this.player = ref
        }}
        onBuffer={this.onBuffer}
        onError={this.videoError}
        style={styles.backgroundVideo}
       />
      </View>
    )
  }

}

const styles = StyleSheet.create({
  main_container: {
    flex: 1,
  },

  avatar_container: {
    alignItems: 'center'
  },

  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
})

const mapStateToProps = state => {
  return {
    favoritesFilm: state.favoritesFilm
  }
}

export default connect(mapStateToProps)(Favorite)

```

### Expected behavior
I want to play video on my react-native application on iOS & Android.

### Platform
Which player are you experiencing the problem on:
* iOS : 14.5 On simulateur iOS
* Xcode : 12.5
* Mac OS: 11.3.1
* react-native : 0.64.1
* react-native-cli : 2.0.1

### Video sample

https://user-images.githubusercontent.com/47150660/117305491-187f2f00-ae7f-11eb-912c-4973015ba223.mp4

https://user-images.githubusercontent.com/47150660/117305510-1cab4c80-ae7f-11eb-87f5-8e14fd7375be.mp4

**Comment by gulsher7** [comment]
its sucks some video play some not i'm fully frustrated this module i'm try another library that library better than this shit. 
guyz using this libray its libray like charm.

1. https://www.npmjs.com/package/expo-av
2. https://docs.expo.io/bare/installing-unimodules/ --->>> this package dependancy, installed too


here is the example: https://docs.expo.io/versions/latest/sdk/video/

https://user-images.githubusercontent.com/56266123/118703171-6e66b600-b833-11eb-8794-d5b2c3e2ac0c.mp4

**Comment by fukemy** [comment]
> its sucks some video play some not i'm fully frustrated this module i'm try another library that library better than this shit. guyz using this libray its libray like charm.
> 
> 1. https://www.npmjs.com/package/expo-av
> 2. https://docs.expo.io/bare/installing-unimodules/ --->>> this package dependancy, installed too
> 
> here is the example: https://docs.expo.io/versions/latest/sdk/video/
> 
>  Untitled2.mp4

bro can u share the better lib than this shit? I do not using expo

**Comment by freeboub** [comment]
expo-av is a diffrent implementation, out of scope here ...

**Comment by freeboub** [comment]
youtube videos are not (yet) supported by react-native-video
you cannot use: 

`       source={{uri: 'https://www.youtube.com/watch?v=z_gzUnskYO8'}}
`

**Comment by hueniverse** [comment]
I don't think Expo supports this module as they have their own way of handling native code.
