### ISSUE TITLE
[iOS] undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

### ISSUE THREAD

**Issue by lsps9150414** [TheWidlarzGroup/react-native-video#237]
Getting this error when I navigate to a scene containing the Video component under ios.
However, this only happens when I started the simulator with `react-native run-ios`. If I run with Xcode, everything works fine.

react native version: react-native@0.25.1

![2016-06-03 1 51 49](https://cloud.githubusercontent.com/assets/5022617/15769937/622c9c54-2992-11e6-8671-fa8482245353.png)

**Comment by brettpappas** [comment]
I'm having the same problem.

**Comment by zaynyatyi** [comment]
I have same too

**Comment by zaynyatyi** [comment]
happens to me only when content is bundled

**Comment by ghost** [comment]
Same error but building from Xcode doesn't help.

**Comment by nikhildaga** [comment]
Facing the same problem on android

**Comment by nikhildaga** [comment]
Has anyone been able to solve this?

**Comment by StellwagJo** [comment]
Same issue here on Android
Using react-native 0.23.1

**Comment by alessandro-bottamedi** [comment]
Same issue react-native 0.29 on iOs

EDIT:
resolved re-launching "rnpm link react-native-video" command...

**Comment by arilitan** [comment]
im getting this same error on Android, anyone have any luck?

re-launching "rnpm link react-native-video" didnt help

**Comment by keung725** [comment]
same issue

**Comment by vgurbuxani** [comment]
thanks everyone, this command worked: resolved re-launching "rnpm link react-native-video" command.. i was having the same issue. you just saved me another few hours of banging my head against the wall

**Comment by kevin-xiong** [comment]
You can do it yourself
1.in the project navigator, right click Libraries, add RCTVideo.xcodeproj to your project
2.select your project,select Build Phases -> Link Binary With Libraries,add libRCTVideo.a
3. re-launching "react-native run-ios"

**Comment by nikhildaga** [comment]
This issue has not been resolved. Why is it closed?

**Comment by mattapperson** [comment]
@nikhildaga sorry, others had commented that running 'rnpm link react-native-video' fixed the issue (or otherwise linking manually. Have you done this and are still having issues?

**Comment by StellwagJo** [comment]
Still having this issue. Also rnpm or manually linking didn't work for me.
React-Native: 0.29.2
Android: 6.0.2
@mattapperson can you please re-open this issue. thx

**Comment by mattapperson** [comment]
Please try deleting the node_modules directory, 'npm cache clear' and 'npm install'. Once that is done run 'rnpm link react-native-video'

**Comment by StellwagJo** [comment]
Hi @mattapperson,
could fix this issue by going into the /android folder and use 

> gradlew.bat clean

Keep in mind to not run the packager and delete the old imports of the Video Component at the MainActivity.java if you are using >= 0.29 RN

**Comment by RafalWilinski** [comment]
I'm also facing this issue. Removed `node_modules`, cleaned cache, ran `rnpm link react-native-video`, checked that `libRCTVideo.a` is linked in build phase and still nothing. I've also ran `cd ios && xcodebuild clean`, didn't help.

react-native-cli: 1.0.0
react-native: 0.32.0
node: 6.0.0
npm: 3.8.6

Update:
I had to run project from Xcode and enable developer mode...

**Comment by talibasya** [comment]
Hey every one. I got this error, caused missing:
```
Note: In react-native >= 0.29.0 you have to edit MainApplication.java

MainApplication.java (react-native >= 0.29.0)

On top, where imports are:

import com.brentvatne.react.ReactVideoPackage;
Under .addPackage(new MainReactPackage()):

.addPackage(new ReactVideoPackage())
```

and it help me. Good luck
The `rnpm` doesn't write it automatically ;)

**Comment by lxfriday** [comment]
rnpm link react-native-video  will help

**Comment by lxfriday** [comment]
and then rebuild from xcode

**Comment by bharatraichur** [comment]
I am currently facing this issue on Android, its working fine on iOS. I am new to React, any info would be helpful

**Comment by zb1006801184** [comment]
select your project,select Build Phases -> Link Binary With Libraries,add libRCTVideo.a

**Comment by arhmnsh** [comment]
For Android, this should work: https://github.com/react-native-community/react-native-video/issues/184#issuecomment-244913381

For iOS, close the packager, and then rerun the Xcode project.

**Comment by zhangzeyan** [comment]
I'm also facing this issue and has not been resolved. Has anyone been able to solve this?

**Comment by liangzhm** [comment]
I am also facing this problem,and it still has not been resolved,has anybody can help me solve this issue?

**Comment by developer239** [comment]
This issue goes on for a YEAR! How is that even possible? I am unable to use `react-native-video` on android.

**Comment by developer239** [comment]
- `rm rf node_modules`
- `yarn cache clean`
- `yarn install`
- `react-native link react-native-video` (already linked)
- `yarn start`
- `react-native run-android`

I get following screen:
![sdafsdafsadf](https://user-images.githubusercontent.com/14946081/28076134-fc883048-665d-11e7-9258-e3c4c144f5d7.png)

Thank you for your help.

**Comment by yangmingtao** [comment]
at first i failed but at last i success android我认为ios比android好集成这个

**Comment by custam** [comment]
I solved it by installing react-native-video with pods :
1) install pods
2) add this to your podfile is ios folder of your project : 
`pod 'react-native-video', path: '../node_modules/react-native-video'`
3) launch pod install
4) maybe delete the "-obj" in the "target support files" of file "pods". You can find it by opening your xcworkspace file in xcode.
5) rerun your project

**Comment by RohitRox** [comment]
Removing derived data and restarting simulator fixed this issue for me (ios).

**Comment by fabianunger** [comment]
For me the following worked for me:

- **yarn add react-native-video**  - OR - npm install --save react-native-video
- **then link manually:** Open Project in XCode -> right click Libraries -> Add Files to 'ProjectName' -> find RCTVideo.xcodeproj in node_modules 
- include both libRCTVideo.a in the **Build Phases** of the Project (you can get there under the Targets)
(**libRCTVideo.a :** one is within RCTVideo.xcodeproj,the other in RCTVideo.xcodeproj > Products)
- **DO NOT include pod** 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec' in the pod file.

**Comment by haoshuanqin** [comment]
> You can do it yourself
> 1.in the project navigator, right click Libraries, add RCTVideo.xcodeproj to your project
> 2.select your project,select Build Phases -> Link Binary With Libraries,add libRCTVideo.a
> 3. re-launching "react-native run-ios"



> You can do it yourself
> 1.in the project navigator, right click Libraries, add RCTVideo.xcodeproj to your project
> 2.select your project,select Build Phases -> Link Binary With Libraries,add libRCTVideo.a
> 3. re-launching "react-native run-ios"

successfully solve.
