### ISSUE TITLE
pictureInPicture={false} is not working

### ISSUE THREAD

**Issue by nealwwilliams** [TheWidlarzGroup/react-native-video#2373]
I have pictureInPicture set to false but the setting is ignored. When I swipe up the app goes to background and video goes to picture-in-picture. I have picture-in-picture enabled in xcode only because I also need background audio for other features of the app. I have pictureInPicture, playInBackground both set to false. iOS 14.5

				<Video source={this.state.videoSrc} 
					ref={(ref) => { this.player = ref }}                                     
					resizeMode={'cover'}
					style={styles.video}
					onProgress={this.videoProgress}
					controls={true}
					pictureInPicture={false}
					playInBackground={false}
				/>

Library version: 5.1.1

**Comment by chungmarcoo** [comment]
Same issue, when I click the home button on my iPad and intented to back to home screen. The video turns into "picture-in-picture" mode even set `pictureInPicture={false}`.

**Comment by zchwyng** [comment]
+1

**Comment by annndev** [comment]
`+ 1`, any update guys?

**Comment by yev-yev-yev** [comment]
+1 Same here

**Comment by jeffbonasso-ambifi** [comment]
+1

**Comment by jeffbonasso-ambifi** [comment]
It's not an ideal user experience because you see it closing in the top right and when go to task manager still says in picture in picture but it does not keep it in picture in picture if you set all these like this...

```
playInBackground={true}
playWhenInactive={true} 
ignoreSilentSwitch="silent"
pictureInPicture={false}

```

**Comment by vmseba** [comment]
I'm experiencing this issue on an iOS app, looking at the source code it seems that `setupPipController` is not checking if `pictureInPicture` has been enabled or not. I've been able to fix this by patching the library and adding that check.

**Comment by Artem2001S** [comment]
This change helped me
https://github.com/react-native-video/react-native-video/pull/2297/commits/48f524c488d86f0edaebbb7e760bf388662981ee

**Comment by jcksncllwy** [comment]
Version 5.2.1

I'm using the video player as a screen background and unfortunately the video pops out into picture-in-picture whenever a user opens the App Switcher. It seems like I should be able to prevent this behavior with the `pictureInPicture` prop, but it's not working.

I think this issue may have resurfaced. It looks like maybe the `pictureInPicture` prop was left by the wayside during the Swift conversion? https://github.com/react-native-video/react-native-video/pull/2527

**Comment by dianamelga** [comment]
@hueniverse I'm having this same issue on v5.2.1

**Comment by Hanuman-Ghawade** [comment]
I am facing the same issue. Please help out if there is any solution.
