### ISSUE TITLE
[iOS] Video keeps playing even after setting pause to false 

### ISSUE THREAD

**Issue by Md-Mudassir** [TheWidlarzGroup/react-native-video#2374]
# Bug
 
I'm trying the pause the video by calling a pause function to show a question modal on certain duration.. in android it works as expected but it iOS it displays the paused icon but the video keeps on playing.. but when i manually click on the pause button then it works.

Sometimes it also replays when the video ends and it automatically starts playing again even though the pause is set to true

## Platform

* iOS
* Android ExoPlayer

## Video sample

[Watch the sample video](https://drive.google.com/file/d/1jYc6fT4xGvz2mFE5izek0JdL0kx1buqF/view?usp=sharing)

Library version: 5.1.1
React-native: 0.64.0
"react-native-modal": "^11.9.0",

## Reproducible sample code

Video Player Code
```
//State
  const [state, setState] = useState({
    fullscreen: false,
    play: true,
    currentTime: 0,
    duration: 0,
    error: false,
    showControls: false,
    isStretched: false,
    buffering: true,
    animated: new Animated.Value(0),
  });

//Player
     <Video
            ref={videoRef}
            source={{
              uri: currentVideo.videoUrl,
            }}
            style={state.fullscreen ? styles.fullscreenVideo : styles.video}
            onReadyForDisplay={calculatePlaybackTime}
            onLoadStart={onLoadStart}
            resizeMode={state.isStretched ? 'cover' : 'contain'}
            posterResizeMode="cover"
            onLoad={onLoadEnd}
            onVideoBuffer={handleBuffer}
            rate={speed}
            onError={handleError}
            onBuffer={handleBuffer}
            onProgress={onProgress}
            onEnd={onEnd}
            paused={!state.play}
          />
         
//Pause Function
  function handlePlayPause() {
    // If playing, pause and show controls immediately.
    if (state.play) {
      setState({...state, play: false, showControls: true});
      return;
    }

    setState({...state, play: true});
    setTimeout(() => setState((s) => ({...s, showControls: false})), 2000);
  }


//Modal Trigger, Triggering the modal to pop up when the timing is 00:05
  function onProgress(data) {
    setState((s) => ({
      ...s,
      currentTime: data.currentTime,
    }));
    console.log(getMinutesFromSeconds(data.currentTime), state.play);
    if (getMinutesFromSeconds(data.currentTime) === videoQuestions.duration) {
      handleQuestionPopModal();
    }
  }

// Calling the modal & pause function
  const handleQuestionPopModal = () => {
    setQuestionPopVisible(!questionPopVisible);
    handlePlayPause();
  };


```

**Comment by jonitef** [comment]
Same here, if paused prop is set to true, it does not play.
But if using state to toggle paused prop between true and false, it does not pause the video.

**Comment by andrew-huang** [comment]
I'm having the same issue on iOS where if I update the paused state to true, the video continues to play. I got around it by setting rate to 0.0 which does work.

**Comment by luisfuertes** [comment]
If i set "paused=true" on state programmatically before change scene, i dont know when user press "Play" button to set "paused" state to false.

I try to set "paused=false" in "onProgress" function, but if i do that, video dont pause when i change scene with "paused=true". I think onProgress is called after i set "pause=true".

maybe if you remove "onProgress" function your "paused" will work, but then you will have my bug
