### ISSUE TITLE
getting error NSURLErrorDomain -1102 - iOS | HLS

### ISSUE THREAD

**Issue by SachArora** [TheWidlarzGroup/react-native-video#2376]
### Current behavior
Working fine with Android & with other url, but not working with HLS.

Error from player onError method
`{error: {domain: "NSURLErrorDomain", code: -1102}, target: 11785}`

Player Code
```
              <Video
                    source={{ uri: props.url, headers: { 'origin': 'https://www.****** } }}
                    ref={videoPlayer}
                    paused={paused}
                    controls={false}
                    rate={props.speed}
                    currentTime={durations.currentDuration}
                    minLoadRetryCount={10}
                    progressUpdateInterval={1000}
                    resizeMode='contain'
                    useTextureView={false}
                    fullscreen={false}
                    playInBackground={false}
                    onLoad={(data) => onVideoLoad(data)}
                    onError={(error) => console.log(error)}
                    selectedTextTrack={{type: 'system'}}
                    selectedVideoTrack={props.selectedVideoTrack}
                    onProgress={(progress) => updateProgress(progress)}
                    onEnd={()=> props.nextLesson()}
                    onBuffer={(buffer) => setBuffering(buffer.isBuffering)}
                /> 
```

I have tried to add HLS url domains in App Transport Security Settings's Exception Domains. but no luck
<img width="866" alt="Screenshot 2021-05-20 at 5 47 00 PM" src="https://user-images.githubusercontent.com/22761374/118977964-62463a00-b994-11eb-9c83-c8d1009b30d2.png">

### Platform
Which player are you experiencing the problem on:
* iOS

 **"react-native-video": "^4.4.5"**

***React Native Info***
System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 42.38 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by trotters** [comment]
I got this error too. 
Does anybody know the meaning of the Error code: -1102?

**Comment by takeerdevs** [comment]
I am also getting the same error.. and i am using cloudfront too.. have you found a fix..? thanks :)

**Comment by teamseamive** [comment]
I think you need to add Domains with HTTP or HTTPS, just plain domains

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>unique.cloudfront.net</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by matiasrodriguezbegueri** [comment]
Hi, you were able to solve this?

**Comment by delltrak** [comment]
Hello Brother. did you solve ? thank you.

**Comment by teamseamive** [comment]
Try the above solution and it should work fine for you guys. You should add it in App Transport Security Settings for iOS.
This worked for me https://github.com/react-native-video/react-native-video/issues/2376#issuecomment-874757879

**Comment by weebsproject** [comment]
still getting the error.

> Try the above solution and it should work fine for you guys. You should add it in App Transport Security Settings for iOS. This worked for me [#2376 (comment)](https://github.com/react-native-video/react-native-video/issues/2376#issuecomment-874757879)

**Comment by freeboub** [comment]
Anyone to update document ?

**Comment by SamerOrfali22** [comment]
still facing the issue, any update?

**Comment by jagdeepChicmic** [comment]
i'm facing same issue on version 5.2.1 anyone please help me to find the solution.

**Comment by okinawaa** [comment]
i'm facing same issue  .. help me 
but I got -1004 error not -1102
