### ISSUE TITLE
Unable to instantiate decoder

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [TheWidlarzGroup/react-native-video#2377]
# Bug

Video fails to load. it happens while playing multiple videos one by one using flat list

Which player are you experiencing the problem on:

* Android ExoPlayer
* react-native-video

## Environment info

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 213.68 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
![Screenshot 2021-05-20 at 6 49 02 PM](https://user-images.githubusercontent.com/56159166/118986401-f5836d80-b99c-11eb-8315-ec86e5571d98.png)

React native info output:

```bash
Unable to instantiate decoder OMX.qcom.video.decoder.avc
```

Library version: ^5.1.1

**Comment by gulsher7** [comment]
same here did you find any solution ?

**Comment by gulsher7** [comment]
same here @mur did you find any solution ?

**Comment by guillaume-g** [comment]
Same here @gulsher7 @Murugeshrockey-RN, any updates ?

**Comment by Sahejmaharjan1** [comment]
Same here @guillaume-g were you able to solve it?

**Comment by gustavolsilvano** [comment]
Did anyone found a solution for this? I see that if you load only one video at a time it will work. But it results in a bad user experience, i.e: when user goes from one video to the other, it will need to reload the video from scratch.

**Comment by Murugeshrockey-RN** [comment]
I solved this issue by using the **expo-av** https://docs.expo.dev/versions/latest/sdk/av/ **library**. Please avoid this react-native video. expo-av has lots of video options and I didn't face that **Unable to instantiate decoder** issue in expo-av. 

Note: Before installing expo-av, we need to install **react -native unimodules**  first(https://docs.expo.dev/bare/installing-unimodules/) library

**Comment by Takesizmail** [comment]
Have the same on real device v5.2.1

**Comment by SymntxHomendra51** [comment]
@Murugeshrockey-RN  Thanks will try that sure
