### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by codthing** [TheWidlarzGroup/react-native-video#2378]
# Feature Request

**Comment by systemride** [comment]
Have you tried this?
```
yarn add @types/react-native-video
```

**Comment by ShivamJoker** [comment]
> Have you tried this?
> 
> ```
> yarn add @types/react-native-video
> ```
Seems to work but it should come with library by default

**Comment by ku8ar** [comment]
> Seems to work but it should come with library by default

why?

**Comment by freeboub** [comment]
@hueniverse I think you are on this topic ?!

**Comment by hueniverse** [comment]
We are moving the project to TS as soon as the big native PRs are merged.

**Comment by jpike88** [comment]
That's great news, with lack of types am flying a little blind, rather not use @types that could go out of date

**Comment by BasixKOR** [comment]
Could we open this issue to track TS rewrite progress?

**Comment by jpike88** [comment]
THANKYOU. Glad TS is being taken seriously now. Take it all the way!

**Comment by freeboub** [comment]
Finnally full typescript support has been implemented here https://github.com/react-native-video/react-native-video/pull/3266
Will be available in 6.0.0-alpha.9
