### ISSUE TITLE
onEnd being called twice, if muted property missing, or source has dynamically changed

### ISSUE THREAD

**Issue by getnashty** [TheWidlarzGroup/react-native-video#238]
when I log something to the console, I'm seeing onEnd being called twice when the video ends... anyone else getting this behavior?

**Comment by getnashty** [comment]
To be clear, I tested the example repo and couldn't reproduce this. But a minimal test in my own app still resulted in it being called twice.

Heres what I tested in my repo

`<Video
  source={{uri: 'https://media.w3.org/2010/05/sintel/trailer.mp4' }}
  style={styles.videoPlayer}
  paused={false}
  onEnd={() => {
    console.log('Video ended');
    }}
  repeat={true}
/>`

here are my versions

"dependencies": {
  "react": "^0.14.7",
  "react-native": "^0.22.2",
  "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
  "react-native-emoji": "^1.1.2",
  "react-native-image-picker": "^0.18.15",
  "react-native-sortable-listview": "0.0.6",
  "react-native-swiper": "^1.4.3",
  "react-native-video": "^0.8.0-rc",
  "react-redux": "^4.4.2",
  "redux": "^3.4.0",
  "redux-logger": "^2.6.1",
  "redux-thunk": "^2.0.1",
  "reselect": "^2.3.0"
},

**Comment by getnashty** [comment]
I updated my react to 14.8, and react native to 0.23.0 (as in the example), removed node_modules and NPM installed, and I'm still seeing the "Video ended" logged in the console twice.

**Comment by getnashty** [comment]
Using just `<Video source={{uri: 'https://media.w3.org/2010/05/sintel/trailer.mp4' }} style={styles.videoPlayer} paused={false} onEnd={() => { console.log('Video ended'); }} repeat={true} />` in the example repo I was able to reproduce that onEnd is called twice on video end.

**Comment by getnashty** [comment]
Seems like it has to do with the "muted" property existing or not. Although, my original <Video> instance did have muted defined, so still digging.

**Comment by getnashty** [comment]
Ok. That definitely seemed to be the original issue. 

However, after the source changes (at least one time), the onEnd callback will be called twice after each play. This only seems to happen after the source changes, so I imagine somewhere there are two instances that exist.

**Comment by getnashty** [comment]
It seems if I play two separate video instances (source doesn't need to be changed), onEnd is still called twice

**Comment by getnashty** [comment]
I somehow forgot about debounce, so - anyone who might experience this in the future, don't forget about that.

**Comment by stereodenis** [comment]
@getnashty how you solve this issue?

**Comment by getnashty** [comment]
@stereodenis I just included `import debounce from 'lodash.debounce';`

and then  `onEnd={debounce(this.myFn, 100)}`

that seems to do the trick!

**Comment by stereodenis** [comment]
@getnashty why you close issue? I think this issue is actual and debounce is a hack
@brentvatne what do you think?

**Comment by rclai** [comment]
Yeah, I'm trying to get multiple videos playing in succession and I'm getting this issue as well. I guess debouncing will have to do lol.

**Comment by getnashty** [comment]
Thats also what I'm doing @rclai, there are plans to add official support for playing multiple videos back to back, but until then this hack seems to work.

**Comment by orange-brother** [comment]
+1
