### ISSUE TITLE
Setting value of prop, `playInBackground` to true doesnt works  

### ISSUE THREAD

**Issue by kg-kartik** [TheWidlarzGroup/react-native-video#2382]
# Bug
Audio stops playing on pressing back button despite of setting playInBackground prop to true.

## Platform
Android

React Native version : 0.63.4
Library version: 5.1.1

**Comment by androidparth90** [comment]
are you using Android exoplayer or media player?

**Comment by kg-kartik** [comment]
Android exoplayer

**Comment by androidparth90** [comment]
I tried to reproduce it in my project as well. It is not working for me as well. I am also using exoplayer &  the latest version of this library. I am now trying to manually update the exo player but it seems there are too many breaking changes in exo player that this library needs to be incorporate. Someone needs to merge this PR https://github.com/react-native-video/react-native-video/pull/2317

**Comment by kg-kartik** [comment]
Yea I tried looking for that only, but yea it may break things. Would be good if it get fixed in the react-native-video library itself.

**Comment by androidparth90** [comment]
Yes true but I think that would take time since there are no active maintainers over here. If it's super critical for you just like me we can create a fork and then make necessary changes. What are your thoughts?

**Comment by kg-kartik** [comment]
We still have to make changes in our locally installed library, as due to same reason of no active maintainers, the PR wont be merged.

**Comment by androidparth90** [comment]
Yes your right. Then we have to wait and watch :(

**Comment by androidparth90** [comment]
any luck in finding a fix for this @kg-kartik  ? I feel we need to use this link https://developer.android.com/guide/topics/media-apps/audio-focus#java to modify the source code. I feel it could be a permission issue with the new changes that have happened at Android API level

**Comment by kg-kartik** [comment]
I dont think so audio focus will do the work as it only controls and manages the audio between multiple apps
Need to make the player run as a part of a background service process which keeps playing the audio despite of pressing the back button.

**Comment by androidparth90** [comment]
In that case we would a need something similar to a Foreground service

**Comment by kg-kartik** [comment]
Yea um actually, playing of audio should be a foreground process.

**Comment by androidparth90** [comment]
I tried but I am not able to find a good solution. Are u able to solve this issue ? This functionality is quite critical in my app @benoitdion : can you please help us?

**Comment by androidparth90** [comment]
@benoitdion : can you please help ?

**Comment by kg-kartik** [comment]
@androidparth90 I made it work luckily
Actually in my case i was using nested stack navigator inside bottom navigation 
I dont know the reason tho , but figured it out it was due to that only, so I moved my audio component in the screen which was actually the root child for the bottom navigator as my player was initially in the nested stack.

**Comment by Nesh108** [comment]
This is happening to me on both iOS and Android (on `6.0.0-alpha.3`), so this ticket should definitely be opened back up.

What's happening is that the system sees the app in background and, after some seconds, decides to terminate it.
I found that there is a way for Android:

**Android**

Creating a Foreground service for the audio/video being played (https://developer.android.com/guide/components/services#Foreground) or asking the user to set the battery optimization to off.
An interesting comment from thread on this: https://stackoverflow.com/a/53096282/1214469

-------------------

Nothing for iOS so far. The `ignoreSilentSwitch` is set to `ignore` and the background modes (audio/airplay and background fetch and background processing are ticket). Not even this: https://github.com/react-native-video/react-native-video/issues/797#issuecomment-374826812 helped.
