### ISSUE TITLE
Multiple videos on one screen not playing simultaneously on Android

### ISSUE THREAD

**Issue by pepemiso16** [TheWidlarzGroup/react-native-video#2384]
# Bug

* FlatList becomes slow and the app crash when using the Android MediaPlayer if there are multiple videos in one screen. (Used Android ExoPlayer instead)
* Using ExoPlayer and with multiple videos, iOS works fine but Android can only play one video

## Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer - Can only play one video
* Android MediaPlayer - Too slow and crashes the app

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 343.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Install react-native-video via npm or yarn
2. Configure Android to use Android ExoPlayer
3. Create an array with video URLs
4. Insert this array on a FlatList
5. Run the app on android device
6. If you use the old video player, the app will becomes too slow and it will crash the app
7. If you use the Android ExoPlayer, it will only run one video at a time

...

## Expected behaviour

1. Using the Android ExoPlayer, it will play multiple videos simultaneously which is already happening in iOS
2. Android MediaPlayer will not become too slow

**Comment by OXReactDev** [comment]
I am facing same issue in Android, in iOS all good, If I play video using ExoPlayer it crahses the app after finished with one video.

**Comment by mirceaciu** [comment]
What configurations do you guys use? I had this working at some point, I remember it was a particular set of props that needed to be set.

Might be wrong but you need SurfaceView (so disable TextureView) and you need to set `playInBackground`. Give it try, tell me if it works.
```
useTextureView={false}
playInBackground={true}
disableFocus={true}
```

**Comment by OXReactDev** [comment]
I have tried all 3 properties but still facing same issue,

My React native library info

System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 310.88 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 25, 27, 28, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: ^0.64.0 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by anshul-kai** [comment]
Same here. MediaPlayer works but ExoPlayer doesn't.

**Comment by SAnatoliiS** [comment]
> What configurations do you guys use? I had this working at some point, I remember it was a particular set of props that needed to be set.
> 
> Might be wrong but you need SurfaceView (so disable TextureView) and you need to set `playInBackground`. Give it try, tell me if it works.
> 
> ```
> useTextureView={false}
> playInBackground={true}
> disableFocus={true}
> ```

I had the same problem on android. It was `disableFocus={true}` that helped. Thanks a lot!

**Comment by brunolcarlos** [comment]
The problem still there and the better solution but not perfect is react-native-big-list
