### ISSUE TITLE
crash App

### ISSUE THREAD

**Issue by Sandeep9768** [TheWidlarzGroup/react-native-video#2388]
I am getting following error after using exo player with dual audio and video
Please help me 

AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.google.android.exoplayer2.mediacodec.MediaCodecInfo.name' on a null object reference

**Comment by rohitninawe** [comment]
+1

Device: `Mediatek MT8183 Tablet (kukui)`

Error: `Attempt to read from field 'java.lang.String com.google.android.exoplayer2.mediacodec.MediaCodecInfo.name' on a null object reference`

Stacktrace: `ReactExoplayerView.java:1029 com.travelxp.exoplayer.ReactExoplayerView.onPlayerError	
ExoPlayerImpl.java:812 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$2$ExoPlayerImpl$PlaybackInfoUpdate	
Unknown:2 com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$fI_Ao37C4zouOtNaX7xHdRfgmVc.invokeListener	
BasePlayer.java:182 com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke	
ExoPlayerImpl.java:845 com.google.android.exoplayer2.ExoPlayerImpl.invokeAll	
ExoPlayerImpl.java:43 com.google.android.exoplayer2.ExoPlayerImpl.access$000	
ExoPlayerImpl.java:812 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run	
ExoPlayerImpl.java:736 com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners	
ExoPlayerImpl.java:710 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo	
ExoPlayerImpl.java:652 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo	
ExoPlayerImpl.java:595 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent	
ExoPlayerImpl.java:127 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage	
Handler.java:106 android.os.Handler.dispatchMessage	
Looper.java:193 android.os.Looper.loop	
ActivityThread.java:6971 android.app.ActivityThread.main	
Method.java:-2 java.lang.reflect.Method.invoke	
RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run	
ZygoteInit.java:865 com.android.internal.os.ZygoteInit.main`

**Comment by pdsouza** [comment]
@Sandeep9768 @rohitninawe I have a fix in #2575. I had the same error when playing a video with AC3 audio. Feel free to test my patch and see if it fixes your crashes!

**Comment by zhulduz** [comment]
Are there any opportunity to merge this fix on stable 5.x version?
