### ISSUE TITLE
iOS FairPlay DRM custom license request NOT WORKING

### ISSUE THREAD

**Issue by aholyly** [TheWidlarzGroup/react-native-video#2389]
# Bug

I need custom license request to get license.  But certificate and license requests are not sent. URL's are tested on Safari and it works.
I found a similar comment [here](https://github.com/react-native-video/react-native-video/pull/2208#issuecomment-756715934), I use fixed version 5.1.1 version of react-native-video and working on physical device.

## Platform
iOS

## Environment info
ract-native -> 7.13.0
react-native-video -> 5.1.1

### My Code
```javascript
<Video
  controls={true}
  source={{
    uri: playUrl,
    type: 'm3u8',
  }}
  drm={
    drmOpts
  }
/>
```
My objects
```javascript
const drmOpts = {
  type: 'fairplay',
  certificateUrl: certificaUrl,
  getLicense: (spcBase64, contentId, licenseUrl) => {
    console.log("spc: ", spcBase64); // <- this never logs out
    console.log("content ID: ", contentId);
    
    return fetch(
      _licenseUrl,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          CustomData: customData.current,
        },
        body: `spc=${spcBase64}&assetId=${encodeURIComponent(contentId)}&KeyID=${encodeURIComponent(contentId)}`,
      },
    )
      .then((r) => r.text())
      .catch((error) => {
        setErrorMessage(error.toString());
      });
  },
}
```

I couldn't see the logs in getLicense function in Xcode logger. Please help.

**Comment by matiasrodriguezbegueri** [comment]
you solved the problem?
