### ISSUE TITLE
Video freeze for sometimes and start it again

### ISSUE THREAD

**Issue by AparnaManjalavil** [TheWidlarzGroup/react-native-video#2391]
I am using this for video playing in my app. But it seems to be freeze for some time and start it again. When I add bufferConfig in Video component ,it works fine for iOS ,but still issue is facing on android

                <Video
                    key={videos[index].videoId}
                    style={styles.backgroundVideo}
                    ref={(ref) => {
                        setPlayer(ref);
                    }}
                    ignoreSilentSwitch={"ignore"}
                    posterResizeMode={'contain'}
                    resizeMode={'contain'}
                    source={{
                        uri: videoUrl,
                        type: 'mp4',
                    }}
            
                        bufferConfig={{
                            minBufferMs: Platform.OS === 'ios' ? 1500 : 1500,
                            maxBufferMs: Platform.OS === 'ios' ? 5000 : 50000,
                            bufferForPlaybackMs: 5000,
                            bufferForPlaybackAfterRebufferMs: 5000,
                        }}
             />
react-native-video version - 5.1.1
react-native-version - 0.63.4
Please help me

**Comment by caijiami** [comment]
+1

**Comment by kotoyama** [comment]
Any updates?

**Comment by nusjose** [comment]
Any updates?
