### ISSUE TITLE
Video player opens and closes suddenly. Video not playing in Android

### ISSUE THREAD

**Issue by Magudeshwaran** [TheWidlarzGroup/react-native-video#2394]
# Bug

When I open the video player it gets closed suddenly . Duration of the video is displayed and closes suddenly. Working fine on iOS but not working on Android. I am getting empty data on onLoad function.
Below is my code: 

`<Video
          repeat={true}
          // hideShutterView={true}
          onEnd={this.onEnd}
          onLoad={this.onLoad}
          onLoadStart={this.onLoadStart}
          onError={(e)=>console.log('error playing  ',e)}
          onProgress={this.onProgress}
          paused={this.state.paused}
          ref={(videoPlayer) => (this.videoPlayer = videoPlayer)}
          resizeMode={this.state.screenType}
          //   fullscreen={true}
          onFullScreen={this.state.isFullScreen}
          source={{
            uri: this.state.localUri,
          }}
          style={styles.mediaPlayer}
          volume={.1}
          selectedVideoTrack={{
            type: 'resolution',
            value: 240,
          }}
        />`
## Platform

Which player are you experiencing the problem on:

  Android `Pie`

## Environment info

React native info output:

```bash
react-native": "0.63.4",
react-native-video": "^5.1.0-alpha8",
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
description not clear.
Sample missing, let's close this issue...
