### ISSUE TITLE
selectedAudioTrack   not working  in react-native-video

### ISSUE THREAD

**Issue by MahboobAhmed** [TheWidlarzGroup/react-native-video#2397]
selectedAudioTrack   not working  in react-native-video . 
here is code that i am using
 <Video
            source={{ uri: `my video url ` }}
            ref={(component) => (this.player = component)} // Store reference
            controls={true}
            resizeMode={"contain"}
            onError={this.videoError}
            paused={this.state.paused}
            onLoad={this.onLoad}
            onAdsLoaded={this.onAdsLoaded}
            onAdStarted={this.onAdStarted}
            onAdsComplete={this.onAdsComplete} // Callback when video cannot be loaded
            style={{
              ...styles.backgroundVideo,
              height: scrheight,
              aspectRatio: 640 / 360,
            }}
            onProgress={this.handleProgress}
            onAdError={this.onAdError}
            onEnd={this.handleEnd}
            ignoreSilentSwitch={"ignore"}
            repeat={true}
            selectedAudioTrack={{
              type: "title",
              value: "English",
            }}
            audioTracks={ [
        {
          index: 0,
          title: "Hindi",
          language: "hi",
          type: "audio/mp3",
          uri: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
        },
        {
          index: 1,
          title: "English",
          language: "en",
          type: "audio/mp3",
          uri: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
        },
      ]}
          />

**Comment by freeboub** [comment]
I reproduce similar issue on master, I don't even see side loaded audio tracks ...
To be investigated

**Comment by freeboub** [comment]
recently fixed, shall be reproduced on 6.0.0-beta.7. let's close this one
