### ISSUE TITLE
need support for captions

### ISSUE THREAD

**Issue by mylovelycodes** [TheWidlarzGroup/react-native-video#24]
thanks, it's big help for us!

**Comment by brentvatne** [comment]
:+1: will do cc. @johanneslumpe

**Comment by lukasredev** [comment]
@dengjiuhong you can capture videos with [reat-native-camera](https://github.com/lwansbrough/react-native-camera) ...

**Comment by eduedix** [comment]
@lukasreichart: caption != capture

**Comment by lukasredev** [comment]
Oh sorry, probably read this to fast ... :/

**Comment by brentvatne** [comment]
hehe :smile:

Pretty low bandwidth right now but totally welcome someone to jump in and take a crack at this!

**Comment by sungjkim34** [comment]
I've opened up a PR for support of captions within HLS #972.  
Would appreciate any comments/support! Thanks.

**Comment by cobarx** [comment]
This will be ready once #1049 gets merged.
