### ISSUE TITLE
Function to retrieve current volume level of the video/audio being played

### ISSUE THREAD

**Issue by AlbertoMeQ** [TheWidlarzGroup/react-native-video#2400]
# Feature Request

The goal is to easily be able to the get current volume level of the video/audio being played, as it is being played.

## Why it is needed

This is commonly found and used to enable effects relying on the sound levels. I am not thinking of precise histograms but mainly an indicator of audio activity (and its amplitude). This is available, for example, in Unity.

## Possible implementation

On each platform there is a way to request the current volume of the stream being played. The only caveat is to have a reference of the media player being used.

**Android**: https://developer.android.com/reference/android/media/AudioManager.html#getStreamVolume%28int%29

**iOS**: https://stackoverflow.com/questions/32848763/ios-query-current-audio-volume

**Windows**: https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudiostreamvolume-getallvolumes

### Code sample

Ideally one would have the reference of the reference of the VideoPlayer as:

```
<Video source={{uri: this.myAudioSource}}
 ref={(ref) => {
     this.player = ref;
  }}
  ...
  />
```

And to access the current volume, one could simply poll (every x millisecond or so) a function such as:

```
this.player.getCurrentOutputVolume();
```

That would return either a number between 0 and 1 for all channels combined (or split for each channel). 

0 = silence
1 = full volume

The number would depend on the platform but they should all return 0-1 ranges. If not, they can be normalized to that range.

**Comment by freeboub** [comment]
Can also make sens with media session on Android
