### ISSUE TITLE
302 redirection on HLS not keeping base url on Android

### ISSUE THREAD

**Issue by SandorAstarita** [TheWidlarzGroup/react-native-video#2401]
# Bug
I have a server redirection to process signedUrl for indexes and segments. The server redirect the url with 302 status. The first request works fine and the m3u8 list is received properly. But the subsequents requests for segments are sendind to the second server, as if it were a 301 response code. Aditionaly, when the segments request fail, the library repeat te request on m3u8 list infinitley.

## Platform
I am working on macOS 11.4 and Android Exoplayer. Not tested on IOS.

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:
```bash
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 714.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/hernun/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.1, 28.0.3, 29.0.2, 30.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Create a react-native app and install the library
2. Return video tag with the url https://serve.nqv.com.ar/force/test2.m3u8 will fail because of signing URL. 
3. Return video tag with the url https://serve.nqv.com.ar/force/test.m3u8 will work requesting the redirected url for segments

## Expected behaviour

1. both urls would work requesting the base url

## Reproducible sample code
https://github.com/SandorAstarita/test/blob/main/App.js

## Video sample
https://serve.nqv.com.ar/force/test2.m3u8

**Comment by freeboub** [comment]
Video are not available anymore ...
Anyway I have a similar use case in my project, the solution is to resolve the redirection outside of react-native-video and provide the redirected url to exoplayer.
I was not able to resolve redirection in JS I had to develop a small native JAVA function...

I think we can close the ticket.
please reopen it if needed

**Comment by samad324** [comment]
I'm currently facing a situation similar to yours, where our server's restrictions limit us from using multiple URLs for streaming. I'm aiming to ensure that the video streaming remains confined to a single URL rather than making requests to multiple URLs for individual segments. In a previous project, we managed to accomplish this successfully by utilizing `react-player`'s `hlsOptions` feature. However, I've yet to discover a similar solution within the `react-native-video` library.

If anyone has encountered and resolved a similar issue, I'd greatly appreciate it if you could share your solution here. Your insights could be extremely helpful.
