### ISSUE TITLE
Getting full meta data with old android mediaplayer (videoTracks , subtitleTracks , audioTracks)

### ISSUE THREAD

**Issue by DevineDecrypter** [TheWidlarzGroup/react-native-video#2403]
# Feature Request
I want to access the full meta of a m3u8 file which is hosted on a server.
setting the react-native-video to use exoPlayer in android/settings.gradle works and gives all the information such as videoTracks , subtitleTracks and audioTracks .
but when its set to use the android mediaPlayer , it wont give the full meta of the m3u8 file.

## Why it is needed
this feature is needed to support old devices for options like setting the video quality , or changing the audio tracks of a video while using the android mediaPlayer not the exoPlayer.

**Comment by skfaisal93** [comment]
Can you share your Video component with the package version you are using?
