### ISSUE TITLE
Android video got stuck.

### ISSUE THREAD

**Issue by aniket-dalvi** [TheWidlarzGroup/react-native-video#2407]
I am handling video playing state on the basis of navigation listener. Initially pause caused the video stuck. If I do it for a second time it is working as expected. The problem seems to happen on the initial change of video playing state change.

**Comment by talharshad** [comment]
I am also facing same issue in react-native-video 5.1.1. Any solution for this?

**Comment by lomoalapimienta** [comment]
hi @talharshad @aniket-dalvi! Did you manage to solve this issue? any clues?
