### ISSUE TITLE
Video not working on device phisycal

### ISSUE THREAD

**Issue by jocelNardi** [TheWidlarzGroup/react-native-video#2408]
video work fine on android version 11 emulator only but does not work on android version 11 physical device or other.
can anyone help me with this problem please?
i use this package for video hls
library version: V5.0.1

i have some log on progress function :
 
 E/MediaPlayerNative: error (1, -2147479551)
E/MediaPlayer: Error (1,-2147479551)
E/MediaPlayerNative: error (1, -38)
E/MediaPlayer: Error (1,-38)
 E/MediaPlayerNative: error (1, -2147479551)
E/MediaPlayerNative: error (1, -38)
E/MediaPlayer: Error (1,-2147479551)
 E/MediaPlayer: Error (1,-38)
{ seekableDuration: -0.001, playableDuration: 0, currentTime: 0 }
{ seekableDuration: -0.001, playableDuration: 0, currentTime: 0 }
{ seekableDuration: -0.001, playableDuration: 0, currentTime: 0 }

**Comment by KrzysztofGastolek** [comment]
Can you provide all settings passed to video component?

**Comment by carltian** [comment]
> Can you provide all settings passed to video component?

"react-native": "0.63.2",
"react-native-video": "^5.1.0-alpha8",

`
import Video from 'react-native-video';

<Video
            key={uri}
            source={{ uri }}
            poster={posterUri}
            ref={this.videoInstance}
            paused={videoPaused}
            resizeMode="cover"
            posterResizeMode="cover"
            onLoad={() => {}}
            onEnd={this.afterEndVideo}
            style={this.styles.Image}
          />
`
