### ISSUE TITLE
Display mpd and m3u8 offline

### ISSUE THREAD

**Issue by williamtdepaula** [TheWidlarzGroup/react-native-video#2410]
Can i display offline videos with mpd and m3u8 extension?  My videos also use DRM, can I play offline?

**Comment by puneetkansal04** [comment]
Hi @williamtdepaula get any success in video offline play?

**Comment by moskalakamil** [comment]
Hey all!
We've recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=2410) that lets you download and play video content offline - including DRM-protected streams.  
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=2410)
