### ISSUE TITLE
Video PIP causes modal to close automatically

### ISSUE THREAD

**Issue by adhip94** [TheWidlarzGroup/react-native-video#2413]
# Bug

In the video attached, I have shown a modal that consists of a video. The modal opens and the video plays fine. But when i click the Picture-in-Picture button, the PIP view appears and the modal automatically closes. I don't understand why the modal automatically closes. At the end of the video I click on the video multiple times to open the modal, the modal doesn't open, but I can hear the video playing in the background. I have to kill the app and open it again for it to work. I am able to reproduce the same issue even if I put the app in background while the video is playing.

I have tried this with the default Modal of react-native as well as the NPM package react-native-modal.

## Platform

Which player are you experiencing the problem on:
* iOS 14 and above

## Environment info

React native info output:

System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 17.03 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/adhiprebello/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.1

## Steps To Reproduce

Mentioned above

## Expected behaviour

1. Modal should not automatically close when PIP is enabled.
2. Provide a prop to disable the PIP button on iOS devices.

## Video sample
https://user-images.githubusercontent.com/20703483/123553625-e95bae80-d799-11eb-8224-ae70f3aee805.MOV

**Comment by keyberth-rengel** [comment]
how's it going? Hey, how could you do picture-in-picture? I've been trying for many months but I haven't found any information. Could you help me?

**Comment by umangloria** [comment]
> how's it going? Hey, how could you do picture-in-picture? I've been trying for many months but I haven't found any information. Could you help me?
![Screenshot 2022-04-14 at 4 34 37 PM](https://user-images.githubusercontent.com/22933346/163378802-ca56aba3-1fd8-4a1f-8ca7-014ab2f54bf1.png)

It is very simple, Enable background modes from Xcode first:
then select the first option as shown in SS.
Once done, set pictureInPicture option in the video component as true, run it on a physical device, start playing video, switch to fullscreen, and put the app in the background.

**Comment by vishalhyperspace** [comment]
Hello 
I am enabling background modes and select first option but still pictureInPicture modal close autometically. 
Please help me to fixed it.

**Comment by vmsilva** [comment]
same here! I'm beta version
