### ISSUE TITLE
Issue with React Native video Exoplayer with FlatList

### ISSUE THREAD

**Issue by shubhamverma27** [TheWidlarzGroup/react-native-video#2414]
# Bug

Hey Guys,
I am facing an issue when using react native video with exoplayer inside a flat list.
The videos stop rendering after some x no of videos are rendered. (similar to  [#2325)](https://github.com/react-native-video/react-native-video/issues/2325)
From what I was able to deduce is that this is happening due to the following reason:-
Every element in the flat list creates a new ReactExoplayerView which further creates a new ExoPlayerView which further creates a new SimpleExoPlayer object for each element inside our flat list.
Now even though we render only one element inside react native, somehow the native ExoPlayerView doesn't get removed and when a lot of such objects come in memory they block all the HTTP calls for the app, and all further videos or even images stop loading.

## Platform
Android ExoPlayer

## Environment info

React native info output:
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 98.10 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.5.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.1.1

## Steps To Reproduce

1. Create a flat list with video element as render item (with pagination true in flat list)
2. Now scroll fast and try to render as many items as possible.
3. Even though you would be rendering the video element only for currentIndex and not all, still the threads would get blocked and not released.
...

## Expected behaviour

1. Only the currently Active Video element should take up buffering and others should be released from memory

## Reproducible sample code

refer https://github.com/react-native-video/react-native-video/issues/2325

I have created this bug again as it is causing big trouble for me and I have been able to find out the root cause but would need your help solving it.

**Comment by h-kumbi** [comment]
I'm having the same issue

**Comment by parwan-as** [comment]
I have the exact same issue, I think it's an issue with the exo player resources not being released. Does anybody have an Idea how to fix this?

**Comment by holywater-dev** [comment]
Also facing the same issue

**Comment by OXReactDev** [comment]
Any update? I am facing same issue.

**Comment by gustavolsilvano** [comment]
Any fix? This issue is causing a lot of trouble for me.

**Comment by GustavPS** [comment]
Exact same issue

**Comment by GustavPS** [comment]
When this happens I can see the following in logcat:
```
01-06 21:32:33.217   471   471 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
01-06 21:32:33.217   471   471 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
```

This does not show those times the video is working

**Comment by GustavPS** [comment]
I think it has something to do with this exoplayer issue: https://github.com/google/ExoPlayer/issues/2703
Sounds very similar, they solved it by using "DummySurface" instead of creating a new surface each time. Might be related to this. Not sure how to test it though

**Comment by eo-sdev** [comment]
same issue. any updates?

**Comment by brunolcarlos** [comment]
Same issue with expo video
h.f.c.d.o0.b$a: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, null, -1, null, [606, 1078, -1.0], [-1, -1])

**Comment by Bhavin-hyperspace** [comment]
Same issue with android exoplayer when i load multiple videos in flatlist. Please help me if anybody have the solution.

**Comment by hueniverse** [comment]
Consolidated into #2668

**Comment by omairwaleed** [comment]
is there any solution for that issue?
