### ISSUE TITLE
Video should display black screen

### ISSUE THREAD

**Issue by codal-mpawar** [TheWidlarzGroup/react-native-video#2416]
Hey guys,

We found one issue when we are uploading video on s3 bucket and generate .m3u8 video url at that time when we load video url on video player it is showing black screen in video player. so is there any specific version to not showing video and why its showing a black screen.
@armadilio3  
@zchwyng 
@milansusnjar 
@jonthysell 
@wildseansy 
@asklar 

Guys please help i am stuck here.
![IMG_0286](https://user-images.githubusercontent.com/46340921/124719157-78985d00-df24-11eb-8155-214076d15044.PNG)

**Comment by DevineDecrypter** [comment]
did you try with mp4 to see if you set it up correctly or not?

**Comment by wildseansy** [comment]
@codal-mpawar - for video types, if `.m3u8` isn't in the url `react-native-video` won't know it's an hls stream. You must manually specify the type of video using:

```typescript
<Video
   source={{ uri: myVideoUrl, type: "m3u8" }}
/>
```

Hope this helps

**Comment by nelsonchen5** [comment]
+1, adding types does not appear to fix the issue

**Comment by codal-mpawar** [comment]
@zchwyng @ShaneMckenna23 @nickfujita 
@wildseansy Solution not working. please provide me solution as much as possible. It's a blocker for me to release the app.

**Comment by zchwyng** [comment]
Hey, please try the latest prerelease (5.2.0-alpha1) and see if it helps.

**Comment by sajorahasan** [comment]
Facing the issue in 5.2.0, has anyone found a solution?

**Comment by codal-mpawar** [comment]
@zchwyng @ShaneMckenna23 @nickfujita
@wildseansy Are we have any solution?

**Comment by thanhthanchuc** [comment]
I faced the same problem :(

**Comment by junbeomheo** [comment]
I found a solution. But how do I commit my bugfixes?

**Comment by tironiigor** [comment]
@codal-mpawar try the current version 6.0.0-alpha1 (latest master) and pass `hideShutterView` to the video component. That might fix it!

**Comment by amitkumarcoding** [comment]
> I found a solution. But how do I commit my bugfixes?

what is the solution?
