### ISSUE TITLE
onLoad is not supported in ALL PLATFORMS

### ISSUE THREAD

**Issue by DevineDecrypter** [TheWidlarzGroup/react-native-video#2419]
in the doc it says that the [onLoad ](https://github.com/react-native-video/react-native-video#onload)prop is supported in all platforms , but it clearly doesn't work with mediaPlayer and only gives a little info . no audio tracks , no text tracks and no video tracks are some of the huge missing informations.

**Comment by sannjayy** [comment]
Same here
