### ISSUE TITLE
Video url with authorization headers is not loading

### ISSUE THREAD

**Issue by kamranaashiq** [TheWidlarzGroup/react-native-video#2423]
# Bug

I am using react-native-video for streaming video from remote url along with this library for caching the video, react-native-video-cache . However the remote url i am using in reac-native-video require authorization header i.e jwt token. But react-native-video is throwing error:

` {"error": {"code": -1001, "domain": "NSURLErrorDomain", "localizedDescription": "The request timed out.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 11469}`

## Platform
Ios/Android
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

## Environment info

React native info output:

System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.30 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 3.7.9 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: "^5.1.1"

## Steps To Reproduce

1. Add required authorization headers.
2. Use react-native-video-cache for video caching i.e uri: convertToProxyURL(originalURL)
3.  Run the app on both android/ios
4. Video does not load

...

## Expected behaviour

Video should load and play with valid authorization headers

## Reproducible sample code

```
source={{
               uri: convertToProxyURL(http://url/video.mp4),
               headers: {
                 'Authorization': 'jwt '+loggedInUser.token
               }
            }}
```

**Comment by castalonirenz** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/13584669/127693206-129a6a7f-ef3f-431e-ab75-39c0258a4556.png)

**Comment by Eigilak** [comment]
Any update?

**Comment by jmotta-ea** [comment]
Bump, same issue

**Comment by freeboub** [comment]
@jmotta-ea do you have same error ?
I agree to reopen but this kind of issue is impossible to reproduce as we need some token.
I can help you to find the good way to investigate if you need

**Comment by jmotta-ea** [comment]
@freeboub Unfortunately I can't really provide anything from my end for reproduction, but I can explain a bit more detail, maybe you can see something from this?

I'm able to get the video via Postman & Curl just fine using nothing but my internally hosted URL and the Authorization header, but unable to load this video on iOS/Android using the below config.

### Package Version:
"react-native-viedeo": "5.2.0",

### System Info:
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 429.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 30.0.2, 32.0.0, 32.1.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_321 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found

### iOS Error Code:
`{ error: {
code: -1008
domain: "NSURLErrorDomain"
localizedDescription: "resource unavailable"
localizedFailureReason: ""
localizedRecoverySuggestion: ""
}}`

### Android Error Code;
`{"error": {"extra": -2147483648, "what": 1}}`

### Video Source Code
`source={{
            uri: videoUrl,
            headers: {
              Authorization: 'Bearer <token>',
            },
 }}`

**Comment by freeboub** [comment]
It's not clear what is the error, it looks like a http error...
I think the easiest way to debug the issue is to setup a charles proxy to know exactly which http request fails (and why)

**Comment by jmotta-ea** [comment]
I'm using react-native-debugger to watch network, but not seeing any outbound network requests for the video player. Does react-native-video use its own internal http config? If so, how can I access those logs?

**Comment by freeboub** [comment]
Yes you are right you cannot see them in flipper nor react-native-debugger.

I wrote a doc this evening to explain debugging step with such issue: https://github.com/react-native-video/react-native-video/pull/2858/files#diff-9fa4dcc25e1fc8a7090d48886806cb2864680129b924fe8cb8fa39ea239a9250

Spoiler, you will need to try charles proxy !

**Comment by jmotta-ea** [comment]
Will take a look. Thanks for the prompt feedback!
