### ISSUE TITLE
Video is not viewing but audio is hearing

### ISSUE THREAD

**Issue by swaroopaillinda** [TheWidlarzGroup/react-native-video#2426]
Hi 

I am using react native video for dislaying video based on s3 bucket url with authorization header

when I add android:hardwareAccelerated="false" thi sline in my manifest file the video is playing but the video is not displaying but audio is hearing

I want the hardwearaccelerated to be in manifest file for other issue
so can anyone help me how to solve this issue

**Comment by Damithijse** [comment]
same here, Any solution?
