### ISSUE TITLE
video error {"error": {"extra": -1005, "what": 1}}   help me please .....

### ISSUE THREAD

**Issue by keyone957** [TheWidlarzGroup/react-native-video#2430]
Videos are loading indefinitely on Android and ios 
I get the error on console ==> {"error": {"extra": -1005, "what": 1}}
i can't find extra:-1005 error anywhere......
how can i solve this problem....plz help me
files are MOV file

**Comment by Desintegrator** [comment]
Were you finally able to play mov videos on Android?
