### ISSUE TITLE
current time vs actual audio, which i hear not accurate when use method seek()

### ISSUE THREAD

**Issue by vietdung97** [TheWidlarzGroup/react-native-video#2431]
# Bug
I have a large file .mp3 ~ 4920 seconds. I seek from 0 to 4903. But the sound which I hear at 4903 seconds doesn't match. It should be exactly the sound at 4911 seconds.
I try running this file using VLC Media Player and it's fine.
Why is there such a difference when seek() ?

## Platform
Android

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
 System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 4.15 GB / 15.89 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | 
Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 11.0.9 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0
    react: 17.0.1 => 17.0.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: "react-native-video": "^5.1.1"

**Comment by aliberski** [comment]
I'm facing the same issue only on iOS. On android it works with ExoPlayer

**Comment by vuotnguyen** [comment]
me too but I have this problem in android platform, about 2-3s

**Comment by mitchdowney** [comment]
Not sure if it is related, but audio is not working for me on iOS 15 after I seek anywhere in a video. If I wait a long time (~1 minute) while the video plays with no audio, eventually the audio begins playing. The audio also does not sync up with the video. Anyone have ideas what could be going wrong?

**Comment by mitchdowney** [comment]
Update: it appears this issue is only happening for me with very large video files. Specifically I was testing with "Club Random with Bill Maher", and the video files can be between 500MB and 2.5GB. I'll create a separate issue for this if I can't find one created already.

**Comment by freeboub** [comment]
This issue cannot be related to react native video itself. If someone wants to investigate, you should first test with a standalone player implementation...
