### ISSUE TITLE
Play video from filesystem on IOS

### ISSUE THREAD

**Issue by lcevasco-antorcha** [TheWidlarzGroup/react-native-video#2432]
# Bug
https://github.com/react-native-video/react-native-video/issues/644
I think the issue its similar to that topic. I can make it work on android with "file://" but on iOS I can't use filesystem saved videos. Im testing on iOS emulator.

## Platform

Which player are you experiencing the problem on:
* iOS

React native info output:

```bash
 {"error": {"code": -1100, "domain": "NSURLErrorDomain"}, "target": 1377}
```

Library version: 4.3.2

## Steps To Reproduce

1. download .mp4 video  (I use RNBackgroundDownloader and  rn fs)
2. check if exists
3. use it in source
...

**Comment by hamoody-omar** [comment]
Any update on this? I can't play videos on ios because of the return URI prefixed with `ph://`

**Comment by hueniverse** [comment]
Consolidated into #2650 2652
