### ISSUE TITLE
running the examples

### ISSUE THREAD

**Issue by olgunkaya** [TheWidlarzGroup/react-native-video#2435]
Hi,

i would like to get the example projects up and running in my android studio but could not find a proper way to import the project. could not find more info in the Readme too. Can someone point me a document or step by step guide to run the example projects. 

thanks.

**Comment by freeboub** [comment]
android sample updated in examples/basic
other platform shall also be checked / aligned with android one

**Comment by hueniverse** [comment]
We don't have one but you should be able to follow the normal RN setup instructions and use the examples or the test repo https://github.com/react-native-video/react-native-video-test
