### ISSUE TITLE
onProgress slow other components

### ISSUE THREAD

**Issue by Girum** [TheWidlarzGroup/react-native-video#2438]
Hi everyone!

I`m using the onProgress, to catch the progress of the video, and send to show the time passed, and the time remaining. Also, i used to put in the react-native-elements Slider.

But I have other components, like anohter episodes (like an series). But when I try to click in the other things, because the speed of useState to show the components I mentioned, the click works 2/10 times... When I paused the video, everything goes ok.

Someone with the same problem, and can help? I cannot see another solution to maintain both the features

**Comment by sidferreira** [comment]
@Girum iOS or Android?

**Comment by freeboub** [comment]
@sidferreira I reproduce the same issue on android (not tested on ios).
I saw that on every callback invocation (onProgress, onLoad, ...), the parent view is refreshed.
On my side, it is problematic when I start a playback.

**Comment by Girum** [comment]
@sidferreira both OS. I can reduce the slow using map instead flatlist... But another Components I have tô use flatlist to get the layout width and height.

When use the vídeo with not many Components, it works well. But if its increases...

**Comment by hueniverse** [comment]
Is this a problem with the frequency of updates and renders, or an actual logic in the video module?

**Comment by sidferreira** [comment]
@hueniverse I believe it can be addressed if one tweaks `progressUpdateInterval`. We use it a lot and our app works OK...

**Comment by hueniverse** [comment]
Thanks @sidferreira. Closing for now. If someone can show that this performance issue is present with a reasonable interval, we can revisit.

**Comment by freeboub** [comment]
please notice that there is an issue with : progressUpdateInterval on android (at least).
You cannot change the value on runtime.
To reduce refresh on Video parent view I change this value on runtime and it is not immediatly taken in account

**Comment by hueniverse** [comment]
@freeboub that's another issue. Feel free to open a new one.
