### ISSUE TITLE
Showing a poster, hides the controls

### ISSUE THREAD

**Issue by daihovey** [TheWidlarzGroup/react-native-video#2439]
# Bug
Showing a poster, hides the controls. I would like to be able to show both. Ideally, the controls are positioned over the poster.

Which player are you experiencing the problem on:
* iOS

## Environment info
React native info output:

```bash
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.68 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

```typescript
<Video
         style={styles.videoPlayer}
          source={{
            uri: uri,
          }}
          repeat={true}
          resizeMode={'cover'}
          audioOnly={true}
          poster={request.media.image?.uri}
          posterResizeMode={'cover'}
          controls={true}
        />
```

**Comment by daihovey** [comment]
Out of interest, why doesnt the lib utilise the `HTMLVideoElement.poster` property?

**Comment by J6ey** [comment]
It shows the controls for me I'm not able to scrub from it.

**Comment by freeboub** [comment]
This is a big change ... Poster is implemented in JS so it covers the whole view (controls included as they are 'native'.
Not sure someone what to fix that... 
In my point of view, controls should be implemented outside of RNV.
@hueniverse what do you think out this point ?!

**Comment by hueniverse** [comment]
Controls should be added. I am thinking of adding a basic set of controls the way I did in https://github.com/react-native-video/react-native-video-test. But we are not going to solve this issue when using native controls.
