### ISSUE TITLE
onEnd prop doesnt work 

### ISSUE THREAD

**Issue by kg-kartik** [TheWidlarzGroup/react-native-video#2442]
# Bug

onEnd prop doesnt work. The callback function being passed doesnt run when the media ends.

## Platform
Android

React Native version : 0.63.4
Library version: 5.1.1

**Comment by walkerzhy** [comment]
same issue

**Comment by walkerzhy** [comment]
u can try  repeat={false}  i solve it

**Comment by kg-kartik** [comment]
@walkerzhy It didn't work for me

**Comment by Sciuttomatias** [comment]
I'm having the same problem, and I noticed that on IOS the callback function indeed executes (not the same luck with Android devices). So I added an extra line of code for the thing I was trying to achieve..

Platform.OS === 'ios' ? 'doSomething' : 'doSomethingElse'

**Comment by kg-kartik** [comment]
> I'm having the same problem, and I noticed that on IOS the callback function indeed executes (not the same luck with Android devices). So I added an extra line of code for the thing I was trying to achieve..
> 
> Platform.OS === 'ios' ? 'doSomething' : 'doSomethingElse'

Yea working with Android, so I have to manually compare timestamp if the audio has reached the last sec :)
