### ISSUE TITLE
Play Subtitle File Without Video 

### ISSUE THREAD

**Issue by SonPH088** [TheWidlarzGroup/react-native-video#2443]
Hi everyone!

I'm working on a play video demo app that shows two modals, one play video and the other show subtitle on another point, outside the video box.
is there any way to play subtitle files without play video? 

Thanks all!

**Comment by freeboub** [comment]
This is not supported and I don't think this is feasible easilly.
Subtitle tracks can have positionning information embded.
So playing only subtitle would requirement a second video view anyway...

**Comment by preetparm** [comment]
Can we just start a timer and match with subtitle timing to play srt file standalone?
