### ISSUE TITLE
when i use m3u8 format and vtt/srt textracks the player does not display textracks.

### ISSUE THREAD

**Issue by iSued** [TheWidlarzGroup/react-native-video#2446]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

* Android MediaPlayer

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by iSued** [comment]
https://github.com/react-native-video/react-native-video/issues/1887 this issued opened in the past and actually closed represents the problem i'm facing. 

```
`const onLoad = () => {
    setSelectedTextTrack({ type: 'index', value: 0 })
    setTextTracks({
        [
            {index: 0, language: 'en', type: TextTrackType.VTT, uri: captions.english },
            {index: 1, language: 'es', type: TextTrackType.VTT, uri: captions.spanish },
        ]
    })
}



<Video 
    ....
    onLoad={onLoad}
    selectedTextTrack={selectedTextTrack}
    textTracks={textTracks}
/>`

```


the code snippet above taken from the previous issue, actually closed, represents the pattern i'm using. 
I also tried with an mp4 source and it works quite well.


Thank you for attention.

**Comment by freeboub** [comment]
textTrack shall be configured before onLoad, this is not a dynamic configuration...
Let's close the issue then.
feel free to reopen it if needed
