### ISSUE TITLE
How to remove bottom controls from react-native-video

### ISSUE THREAD

**Issue by Jay-Bruh** [TheWidlarzGroup/react-native-video#2447]
Currently I have a react-native-video component that is taking my video from my local file. I have a problem with my current Video component. My current layout is in such a way that the videos controls(play, pause, forward) are overlapping with my bottom text. So I want to have those controls fit inside my actual video: This is how it currently looks:

![image](https://user-images.githubusercontent.com/50700356/129014561-42b3d511-608d-4a65-84f8-9864e92f79fd.png)

And this is the current code:

```
<Video
            resizeMode='contain'
            source={fishVideo}
            style={{width: 457, height: 264}}
            controls={true}
            ref={ref => {
              this.player = ref;
            }}
            // hideControls:true
    />
```

**Comment by hondek** [comment]
set controls={false}

**Comment by juansirone** [comment]
To avoid touchable issues you can put the buttons over the video layout and change controls to false
