### ISSUE TITLE
How to add http Referer header source to URL request

### ISSUE THREAD

**Issue by hinet** [TheWidlarzGroup/react-native-video#245]
How to add http "Referer" header source to URL request?Video server has Referer check

**Comment by mattapperson** [comment]
Simply put you can't. You could however download the video using normal network requests and then load the video locally

**Comment by Zeke0n** [comment]
I also have this demand too, has any solution there?

**Comment by mattapperson** [comment]
@u0x01 I posted the only solution in my comment

**Comment by uday5162** [comment]
It's 2019.. did anybody found an alternative solution?

**Comment by shawbin** [comment]
a o

**Comment by shawbin** [comment]
@mattapperson  it's 2020 ...
