### ISSUE TITLE
Is there a way to switch the decoding mode, hard decoding or soft decoding.

### ISSUE THREAD

**Issue by A-ANing** [TheWidlarzGroup/react-native-video#2451]
Like the title, some videos require specific decoding, otherwise the sound and picture will cause out-of-sync problems or other problems

**Comment by A-ANing** [comment]
I have a lot of m3u8 videos here. The sound is a few seconds behind the video, that is, the sound is out of sync with the picture. When the video is played for a few seconds, it will pause for a while, and then there will be such a problem.

**Comment by freeboub** [comment]
You can try to enable surfaceview on Android.

Please give a better description (platform and sample url) and reopen if needed.
