### ISSUE TITLE
Video component crashes on Windows.

### ISSUE THREAD

**Issue by KarkaLT** [TheWidlarzGroup/react-native-video#2452]
# Bug

Video component crashes when rendering on Windows. Works fine on Android.

Error:
```js
TypeError: Cannot read property 'Constants' of null

This error is located at:
    in Video (at VideoScreen.js:61)
    in RCTView (at View.windows.js:52)
    in View (at VideoScreen.js:60)
    in RCTView (at View.windows.js:52)
    in View (at VideoScreen.js:58)
    in VideoScreen (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.windows.js:52)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.windows.js:52)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.windows.js:52)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.windows.js:52)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in Dummy (at Card.tsx:549)
    in RCTView (at View.windows.js:52)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at createAnimatedComponent.js:278)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.windows.js:52)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.windows.js:52)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.windows.js:52)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RCTView (at View.windows.js:52)
    in View (at CompatNativeSafeAreaProvider.tsx:28)
    in CompatNativeSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.windows.js:52)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at App.js:13)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at App.js:12)
    in Soap2Day (at renderApplication.js:47)
    in RCTView (at View.windows.js:52)
    in View (at AppContainer.js:107)
    in RCTView (at View.windows.js:52)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
```

## Platform

Windows UWP

## Environment info

React native info output:

```bash
 System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 966.36 MB / 7.89 GB
  Binaries:
    Node: 12.18.3 - ~\AppData\Local\Temp\yarn--1629209779765-0.44972621526909196\node.CMD
    Yarn: 1.22.11 - ~\AppData\Local\Temp\yarn--1629209779765-0.44972621526909196\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    Visual Studio: 16.10.31515.178 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-windows: ^0.64.0-0 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

1. Create a react native project on windows
2. Install react-native-video
3. Use `<Video />` component

## Expected behaviour

1. Video component plays video without any errors.

## Reproducible sample code

```js
<Video
          controls={true}
          resizeMode="contain"
          style={styles.videoPlayer}
          source={{ uri: videoUrl }} />
```

## Video sample
Happens with all videos.

**Comment by SonPH088** [comment]
I got the same issue last week. You have to link the react-native-video manual follow the docs and the video will play well on debug mode. 
Now I'm stuck in release mode :(

**Comment by KarkaLT** [comment]
@SonPH088 I have tried linking manually, but my app crashed without any errors, maybe I linked something incorrectly?

**Comment by SonPH088** [comment]
@KarkaLT I also follow the docs but change a little bit. Add #include "winrt/ReactNativeVideoCPP.h" in app.cpp instead of pch.h and it work. You should try this way.

**Comment by KarkaLT** [comment]
Thanks, I'll try your solution when I get back home.

**Comment by KarkaLT** [comment]
@SonPH088 I have tried to add #include "winrt/ReactNativeVideoCPP.h" in app.cpp, but my app still crashes without any errors. What could be the problem?

**Comment by hondek** [comment]
It look like you can only run this on:
```
"react-native": "0.63.4",
"react-native-windows": "^0.63.0-0",
```

i think this bug in inside react-native-windows not react-native-video

**Comment by KarkaLT** [comment]
@hondek I have tried on react-native-windows 0.63.0-0, it makes no difference.

**Comment by SonPH088** [comment]
@KarkaLT 
For me it's work. Did you follow all the steps in the docs or just add the #include "winrt/ReactNativeVideoCPP.h" in app.cpp? If not, maybe your problem is in another setup environment.
@hondek 
it's working on debug but in release, it's only working with:
"react-native": "0.63.x",
"react-native-windows": "^0.63.0-0",

see #2399

**Comment by KarkaLT** [comment]
@SonPH088 I have followed all of the steps in the docs and included `#include "winrt/ReactNativeVideoCPP.h"` in app.cpp instead of pch.h.

**Comment by SonPH088** [comment]
@KarkaLT For me, It's work. You should run windows with --logging to see what is the problems.

**Comment by KarkaLT** [comment]
@SonPH088 could you share your `package.json` file? Maybe the problems are with my other dependencies.

**Comment by hondek** [comment]
Hi i have project with working videos in Release.
Here is package.json:
```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.2",
    "@react-native-community/checkbox": "^0.5.7",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-picker/picker": "^1.16.3",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "axios": "^0.21.1",
    "club-react-native-google-analytics": "^1.4.1",
    "lodash": "^4.17.21",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-drag-sort": "^2.4.2",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-windows": "^0.63.0-0",
    "sanitize-filename": "^1.6.3",
    "styled-components": "^5.2.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/jest": "^25.2.3",
    "@types/react-native": "^0.63.2",
    "@types/react-native-vector-icons": "^6.4.6",
    "@types/react-native-video": "^5.0.4",
    "@types/react-test-renderer": "^16.9.2",
    "@types/styled-components-react-native": "^5.1.1",
    "@types/lodash": "^4.14.170",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },
```

**Comment by SonPH088** [comment]
here is mine, it's also work in debug and release mode:

"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.1.1",
    "react-native-windows": "0.63"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },

**Comment by KarkaLT** [comment]
I have finally figured it out. I have been passing empty string in `source={{ uri: "", type: "mp4" }}`. Now it works perfectly, thank you everyone.

**Comment by jensonstack** [comment]
@SonPH088 can you please help, How did you resolve the issue in release mode? In my case video work fine in debug mode but blank screen in release mode(Not even load background view or other components) No error logs.

 ```
   "react-native-video": "^5.2.0",
    "react-native-windows": "0.64.25"
```
    
  ### EDIT UPDATE
  Thanks to @SonPH088 and @Boiko33 
  I solved the issue. Please see below comment
  https://github.com/react-native-video/react-native-video/issues/2336#issuecomment-972570742
