### ISSUE TITLE
tvOS Language Menu not Supported

### ISSUE THREAD

**Issue by ShaneMckenna23** [TheWidlarzGroup/react-native-video#2457]
# tvOS Language Menu not Supported

I have a video stream that contains multiple languages. tvOS has an audio menu that allows users to select thier desired language. This menu does not work. 

I assume it is because the default value for `selectedAudioTrack` is `system`. Therefore it always opts for the language set on the device. 

I'm able to load and play different audio tracks by providing a specific value to this prop, such as: 
`selectedAudioTrack={type: 'language', value: 'fr'}` 

But I have not found a way of hooking into the tvOS audio menu to detect if a user has selected a different language.

I believe that this is a bug, as the user-selected language should overwrite the default system language. 

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 5.1.0-alpha8

## Steps To Reproduce

1. Play video with multiple language audio tracks
2. Try to change the language using the tvOS menu 
3. Language defaults back to the system language. 
...

## Expected behavior

1. Language should change to the user-selected audio track

## Video sample
https://user-images.githubusercontent.com/18077159/130159078-642b5532-e747-4f08-873a-a2cb7182c017.mov

**Comment by freeboub** [comment]
Looks like done.
Should be retested on master branch !
Please reopen if reproduced
