### ISSUE TITLE
Video pause not working using reference 

### ISSUE THREAD

**Issue by vishalparmar22091989** [TheWidlarzGroup/react-native-video#2458]
<Video source={{ uri: item.url }}   // Can be a URL or a local file.
                          // ref={(ref) => videoRef2 = ref} 
                          ref={videoRef2}
                          onBuffer={() => {
                            console.log("in buffering");
                          }
                          } // Callback when remote video is buffering   
                          key={index}
                          onError={
                            (err: any) => {
                              console.log("on error", err);
                            }
                          } // Callback when video cannot be loaded  
                          style={styles.backgroundVideo}
                          poster={item.thumbUrl}
                          posterResizeMode="cover"
                          resizeMode="cover"
                          controls={true}
                          minLoadRetryCount={5}
                          repeat={true}
                          disableFocus ={true}
                          paused={isPaused}
                          onLoad={() =>setPaused(true)}
                        />

i try like  but its not working just picture pause but audio and timer continue on 

videoRef2.current.paused = true;

**Comment by Joshmatjjen** [comment]
@vishalparmar22091989  ...  use hooks to control your pause and play :-  useState

```
const [isPaused, setIsPaused] = useState(true)
```
use this rather 👇
```
 setIsPaused(!isPaused);       OR       setIsPaused(true);
```

**Comment by vishalparmar22091989** [comment]
@Joshmatjjen  but i am using this component in flatlist. let me know proper way for pause

**Comment by Joshmatjjen** [comment]
@vishalparmar22091989 share your code here... let me see the structure of your component, so I can see a better approach you can make to fix this.

**Comment by pepemiso16** [comment]
Is there a way to do this? I am trying to use useRef to pause and play videos dynamically but it seems that this is not working
`videoref.current.paused = false;`

Any ideas on how to achieve this? Thanks

**Comment by ferasabufares** [comment]
@vishalparmar22091989  did you manage to solve this problem

**Comment by martis900** [comment]
You can use setNativeProps
`videoref.current.setNativeProps({ paused: false })`

**Comment by priyak-sdei** [comment]
> 

That works for me thanks

**Comment by ayyunmufti** [comment]
> You can use setNativeProps `videoref.current.setNativeProps({ paused: false })`

worked Like a chram thanks

**Comment by freeboub** [comment]
@hueniverse can be closed

**Comment by andresfelipe3112** [comment]
videoRef2.current?.setState({ muted: true})

**Comment by Jagadeesh-g-p** [comment]
> 

It worked for me , Thanks a lot Sir

**Comment by bmitioglov** [comment]
it doesn't work for me :(

**Comment by bmitioglov** [comment]
I tried all these 
```videoRef.current?.setState({ paused: true})
videoRef.current.paused = true;
videoRef.current.setNativeProps({ paused: false })```
and no luck

**Comment by wolfxpertlab** [comment]
@martis900 how can I use this in react native video version 5.2.1

I want to pause video using reference

**Comment by freeboub** [comment]
@wolfxpertlab 5.2.1 not supported anymore

**Comment by wolfxpertlab** [comment]
@freeboub thank you for this help
