### ISSUE TITLE
React native Video not play on ios 14 

### ISSUE THREAD

**Issue by AlStartlight** [TheWidlarzGroup/react-native-video#2459]
# Bug

Working on Android device but not working in IOS 14.7

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info
  "react-native-video": "^5.1.1",
  "react-native": "0.64.2",
 "react-native-swift": "^1.2.3",
  npm:"^6.14.13"

React native info output:

```bash
 // paste it here
```

Library version: 5.1.1

## Steps To Reproduce
I install react-native-video with npm 
cd ios && npx pod install
add 
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
to podfile
i change from " pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'"
to ^" pod 'react-native-video', :path => '../node_modules/react-native-video' " because npx pod install have error says" There are multiple dependencies with different sources for `react-native-video` in `Podfile`:"

##podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TSReader' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'Permission-Notifications', :path=>"#{permissions_path}/Notifications"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  use_react_native!(:path=>config["reactNativePath"])
  target 'TSReaderTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.75.1' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      flipper_post_install(installer)
     
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
      if ['react-native-track-player'].include? target.name
        target.build_configurations.each do |config
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end
end
  

## Expected behavior

1.working in ios 14
2.show video and audio player
3.can play video and audio player

## Reproducible sample code

import Video from 'react-native-video';

<Video
                    source={{ uri:'http://file.com/file.mp3' }}
                    style={{
                        width:'100%',
                        height:230,top:20,
                    }}
                    resizeMode='cover'
                    controls={true}
                    repeat={true}
                    // playWhenInactive={true}
                    autoplay={true}
                    resizeMode="cover"
                    ref={(ref) => {
                        myRef.current = ref
                    }}/>

**Comment by AlStartlight** [comment]
close issue because duplicate

**Comment by hugoh59** [comment]
Where is the duplicate ? I have the same issue.
