### ISSUE TITLE
Adding mp4 as React Native asset / AVFoundationErrorDomain

### ISSUE THREAD

**Issue by mroswald** [TheWidlarzGroup/react-native-video#246]
Hi,

I tried to play from local assets:

```
<Video source={require('../Assets/SampleVideo_720x480_2mb.mp4')} /* ... */ />
```

having the file in the right directory. React Native resolves the file and serves it or copies it to `assets` in the `ios/build` folder (depending on using bundled or served js).

I managed to get the video playing using `resolveAssetSource` (taken from [here](https://github.com/facebook/react-native/blob/0.27-stable/Libraries/Image/Image.ios.js#L205)) while wrapping `<Video />` in another component which does the resolving of `source`

```
    let source = resolveAssetSource(props.source) || {};
    return <Video {...props} source={source} />;
```

Bundle the JS and building the app works, but when the JS is served from `localhost:8081`, I get an error:

```
error: {
  code: -11850,
  domain: "AVFoundationErrorDomain"
}
```

calling the resolved asset url on my local browser works. Replacing `localhost` with my local IP does not resolve the issue.

Any ideas?

**Comment by mroswald** [comment]
Maybe it's an bug or insufficiency of the React Native [Server](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Server/index.js#L396-404)? It has no http headers like `Content-Type` or `Content-Length` (which does both not resolve the issue), nor it accepts range-based http requests. Maybe @martinbigio can help out?

**Comment by mroswald** [comment]
Ok, that's it. I will prepare an PR to React Native.

**Comment by VietChaien** [comment]
I get same issue with react-native-video@3.1.0 and react-native@0.55.4 on ios real device. Does anyone help me, please

**Comment by OmarBasem** [comment]
Why is this closed
