### ISSUE TITLE
How can I force react-native-video to use Exoplayer ?

### ISSUE THREAD

**Issue by qhoarau** [TheWidlarzGroup/react-native-video#2461]
# Feature Request

I would like to be able to specify which player to use for android (Exo Player or MediaPlayer)

I followed the android installation but it's always Media Player that is being used.

## Why it is needed

It is needed because I want to be able to watch video streams (using HLS/DASH) and Exo player is better for those kind of data

**Comment by wishfulthinkerme** [comment]
Hey,
you might try to change react-native.config.js to

```
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir:
            '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
  ```

**Comment by OXReactDev** [comment]
> Hey,
> you might try to change react-native.config.js to
> 
> ```
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir:
>             '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> ```

I have used this code but in flat list app is getting crashed. Can you please help me?

**Comment by kotoyama** [comment]
> > Hey,
> > you might try to change react-native.config.js to
> > ```
> >   dependencies: {
> >     'react-native-video': {
> >       platforms: {
> >         android: {
> >           sourceDir:
> >             '../node_modules/react-native-video/android-exoplayer',
> >         },
> >       },
> >     },
> >   },
> > ```
> 
> I have used this code but in flat list app is getting crashed. Can you please help me?

Same. Have you found any solution?

**Comment by kotoyama** [comment]
@OXReactDev Same. Have you found any solution?

**Comment by OXReactDev** [comment]
@kotoyama still not, update here please if you will find anything.

**Comment by ghost** [comment]
Can you elaborate on what the crash message is? I'm using exoplayer in a flatlist and it seems to work fine for me.

**Comment by OXReactDev** [comment]
@krayong App crashes with out any error messages and it shows App (i.e. app name) isn't responding with two button Close app and wait.

For exoplayer I have added one file (i.e. react-native.config.js) at root and and this file contains below content,


module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer'
        },
      },
    },
  },
};

Apart from this Do I need to do change?

**Comment by wishfulthinkerme** [comment]
Few questions are:

- does it work with using a normal player, not an exoplayer?
- if you're using exoplayer, does it work without flatlist?
- it would be the best if you could share the source code

**Comment by OXReactDev** [comment]
(1) does it work with using a normal player, not an exoplayer?
Yes, with normal player it works fine, but in media player there is video thumbnail issue and when we play video till some interval and then scroll to bottom to play another video and then scroll up to play first video it starts from 0 second it should start where we left, in iOS this works fine.


(2) if you're using exoplayer, does it work without flatlist?
Yes, even in flat list it works but when we play more than one video (i.e. 2 video or sometimes 3 video) it crashes without any errors.

(3) it would be the best if you could share the source code.

react-native-config.js
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer'
        },
      },
    },
  },
};

Video code

<Video
          key={postId}
          source={{uri:uri}}
          poster={thumbnailPhoto}
          posterResizeMode={'cover'}
          autoPlay={true}
          repeat={true}
          onError={videoError}
          resizeMode={'cover'}
          ref={videoRef}
          muted={isMute}
          style={styles.videoView}
          onLoadStart={onLoadStart}
          onLoad={onLoad}
          onProgress={onProgress}
          paused= paused
          ignoreSilentSwitch={'ignore'}
          bufferConfig={{
            minBufferMs: 50000,
            maxBufferMs: 500000,
            bufferForPlaybackMs: 25000,
            bufferForPlaybackAfterRebufferMs: 50000,
          }}
        />

**Comment by kotoyama** [comment]
@OXReactDev Hi, take a look at [my solution](https://github.com/react-native-video/react-native-video/issues/2497#issuecomment-931722809), it might be helpful for you.

**Comment by yasir-syed** [comment]
> (1) does it work with using a normal player, not an exoplayer? Yes, with normal player it works fine, but in media player there is video thumbnail issue and when we play video till some interval and then scroll to bottom to play another video and then scroll up to play first video it starts from 0 second it should start where we left, in iOS this works fine.
> 
> (2) if you're using exoplayer, does it work without flatlist? Yes, even in flat list it works but when we play more than one video (i.e. 2 video or sometimes 3 video) it crashes without any errors.
> 
> (3) it would be the best if you could share the source code.
> 
> react-native-config.js module.exports = { dependencies: { 'react-native-video': { platforms: { android: { sourceDir: '../node_modules/react-native-video/android-exoplayer' }, }, }, }, };
> 
> Video code
> 
> <Video key={postId} source={{uri:uri}} poster={thumbnailPhoto} posterResizeMode={'cover'} autoPlay={true} repeat={true} onError={videoError} resizeMode={'cover'} ref={videoRef} muted={isMute} style={styles.videoView} onLoadStart={onLoadStart} onLoad={onLoad} onProgress={onProgress} paused= paused ignoreSilentSwitch={'ignore'} bufferConfig={{ minBufferMs: 50000, maxBufferMs: 500000, bufferForPlaybackMs: 25000, bufferForPlaybackAfterRebufferMs: 50000, }} />

did you find any solution?

**Comment by ghost** [comment]
> Hey, you might try to change react-native.config.js to
> 
> ```
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir:
>             '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> ```

This is working, But I am using react-native-track-player parallelly  , and adding this ia making track player crash ..

**Comment by remigallego** [comment]
If anyone is still stuck with this, there's a way to force Exoplayer that's documented on the README of the project: 

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by stereodenis** [comment]
@remigallego thanks. It works
But I have another issue:
`react-native-video` and `react-native-track-player` use exoplayer under the hood. With this force usage I have no sound in videos.

**Comment by freeboub** [comment]
@stereodenis i don't see easy way to disable exoplayer import in react-native-track-player... This is not advice, but can can remove implementation of exoplayer in react-native-video.

**Comment by stereodenis** [comment]
still facing issue with react-native-video@5.2.0 + react-native-track-player@3.0.0
https://gist.github.com/stereodenis/8ffe0a7e22a403f94746161253ec9dbb

**Comment by Champkinz** [comment]
> If anyone is still stuck with this, there's a way to force Exoplayer that's documented on the README of the project:
> 
> ```
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> ```

Add this to settings.gradle if anyone is wondering.

**Comment by freeboub** [comment]
@Champkinz in V6 exoplayer is the default implementation! :)

**Comment by Champkinz** [comment]
> @Champkinz in V6 exoplayer is the default implementation! :)

Thank you, Yes i implemented that, but my videos seem to get stuck (buffer lag) on Samsung S10e and Samsung S22 only, every other device it works perfectly fine, if you have any thoughts on this please share.

**Comment by nageshvarmak** [comment]
> Hey, you might try to change react-native.config.js to
> 
> ```
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir:
>             '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> ```

How can we confirm our project is using android-exoplayer after making this change in react-native config??and not from the existing folder?

**Comment by freeboub** [comment]
@Varmakswiggy you can read the logcat to see if exoplayer is used. adb logcat | grep -i exoplayer
