### ISSUE TITLE
OnLoad returns wrong naturalSize

### ISSUE THREAD

**Issue by RiccardoBdgl** [TheWidlarzGroup/react-native-video#2463]
OnLoad callback returns this payload:
 {"canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 20.053, "naturalSize": {"height": 0, "orientation": "portrait", "width": 0}}
 
 With this payload, the player doesn't start the video, but only audio? Any Solution?

**Comment by cristin** [comment]
+1
