### ISSUE TITLE
New things have been merged to master but no new releases on npm??

### ISSUE THREAD

**Issue by shercoder** [TheWidlarzGroup/react-native-video#2466]
The last release was in January for version 5.1.1 but since then there has been a lot of PRs merged that some of us could use in our projects but I do not see any new releases on npm.

Please create a new release on npm. For now I will access commit SHA directly in my package.json

**Comment by zchwyng** [comment]
I've recently gotten access to NPM and will soon release an alpha version. Really busy ATM but expect it in coming weeks.
