### ISSUE TITLE
player switching to audio-only mode when the bandwidth is low

### ISSUE THREAD

**Issue by praveens96** [TheWidlarzGroup/react-native-video#2471]
# Bug

I am using react-native-video to play HLS streams. Its working fine when network is good but in mobile data, its mostly switching to audio only mode and not returning to audio+video.

![image](https://user-images.githubusercontent.com/8864727/131289647-718de41d-daff-4cb9-931c-6579a55a6270.png)

I want it to play audio+video always. is it possible?  

## Platform
This I have observed in both iOS & Android.

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 29.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.4.5

## Steps To Reproduce

1. in Mac use Network Link Conditioner.prefPane tool and set to EDGE or 3G speed.
2. now play a sample HLS stream in the player, its turning to audio only automatically with in seconds.
...

## Expected behaviour

1. it should be buffering and playing in video+audio mode.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by praveens96** [comment]
As far as I have seen, its reproducing in safari as well. any help on this is highly appreciated.

**Comment by poojasolanki9569** [comment]
It is reproduced to me for android and ios. Can anyone help into this?
