### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by olgunkaya** [TheWidlarzGroup/react-native-video#2472]
hi,

I would like to contribute for android library. But I can not import the android-exoplayer project to my android studio. It keeps saying that 

A problem occurred evaluating root project 'android-exoplayer'.
> Plugin with id 'com.android.library' not found.

How can I  fix this issue ?

**Comment by 1280103995** [comment]
Other solutions: 
create a new RN project, and ```yarn add react-native-video```. Then open its android project with Android Studio, you can modify the source code in it, and when you finish debugging, copy the code to this repository.

Haha, hope it helps.

**Comment by freeboub** [comment]
Please check on master branch. Should be ok....
Please also upgrade android studio !
