### ISSUE TITLE
Request to upgrade exoplayer

### ISSUE THREAD

**Issue by olgunkaya** [TheWidlarzGroup/react-native-video#2474]
Current exoplayer version is 2.13.2 but only place containing it is jcenter which has been shutdown. Exoplayer started to publish it's own releases via google maven repository starting with **2.13.3**

https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2133-2021-04-14

Better to update exoplayer asap.

**Comment by ChristiaanScheermeijer** [comment]
It looks like our AppCenter builds are affected by this since today. 

```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalStagingRelease'.
> Could not resolve all artifacts for configuration ':app:productionDebugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/runner/.m2/repository/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
     Required by:
         project :app > project :react-native-video
   > Could not find com.google.android.exoplayer:extension-okhttp:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/runner/.m2/repository/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/runner/work/1/s/node_modules/react-native/android/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/runner/work/1/s/node_modules/jsc-android/dist/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
     Required by:
         project :app > project :react-native-video
```

**Comment by olgunkaya** [comment]
Hi there, When I opened this issue, it was obviously a problem. I also highlighted this issue on exoplayer repo too. 
https://github.com/google/ExoPlayer/issues/9362
as per the guy's help on exoplayer repo I got it working. 

1. adding jcenter() in gradle config worked for me. 
2. exoplayer has some internal calender items for following up this and moving the old versions to google() repo.

**Comment by flo-sch** [comment]
Hi @olgunkaya, how exactly did you get it to work?
Did you add a global `jcenter()` in `android/build.gradle`? Or is it possible to configure it for only specific packages required for exoplayer (if yes, which one are needed)?

**Comment by flo-sch** [comment]
Alright well, seems like I managed to make this package (v5.1.1) work (exoplayer) with react-native v0.65 using the following config:

1. Ensure the project uses the exoplayer

```js
// ./react-native.config.js
module.exports = {
  // ...
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```

2. Configure Gradle to load exoplayer plugins from jcenter instead of maven (can be removed later once they are moved to mavenCentral)

```gradle
// ./android/build.gradle
// ...
allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()

        // jcenter repository is deprecated: https://developer.android.com/studio/build/jcenter-migration
        jcenter() {
            content {
                // however, react-native-video's native packages have not been migrated yet, so we keep this config for now
                includeModule("com.yqritc", "android-scalablevideoview")
                includeModule("com.google.android.exoplayer", "extension-okhttp")
                includeModule("com.google.android.exoplayer", "exoplayer")
                includeModule("com.google.android.exoplayer", "exoplayer-core")
                includeModule("com.google.android.exoplayer", "exoplayer-dash")
                includeModule("com.google.android.exoplayer", "exoplayer-hls")
                includeModule("com.google.android.exoplayer", "exoplayer-smoothstreaming")
                includeModule("com.google.android.exoplayer", "exoplayer-ui")
            }
        }

        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by olgunkaya** [comment]
> Alright well, seems like I managed to make this package (v5.1.1) work (exoplayer) with react-native v0.65 using the following config:
> 
> 1. Ensure the project uses the exoplayer
> 
> ```js
> // ./react-native.config.js
> module.exports = {
>   // ...
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> };
> ```
> 
> 1. Configure Gradle to load exoplayer plugins from jcenter instead of maven (can be removed later once they are moved to mavenCentral)
> 
> ```groovy-gradle
> // ./android/build.gradle
> // ...
> allprojects {
>     repositories {
>         mavenCentral()
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
> 
>         // jcenter repository is deprecated: https://developer.android.com/studio/build/jcenter-migration
>         jcenter() {
>             content {
>                 // however, react-native-video's native packages have not been migrated yet, so we keep this config for now
>                 includeModule("com.yqritc", "android-scalablevideoview")
>                 includeModule("com.google.android.exoplayer", "extension-okhttp")
>                 includeModule("com.google.android.exoplayer", "exoplayer")
>                 includeModule("com.google.android.exoplayer", "exoplayer-core")
>                 includeModule("com.google.android.exoplayer", "exoplayer-dash")
>                 includeModule("com.google.android.exoplayer", "exoplayer-hls")
>                 includeModule("com.google.android.exoplayer", "exoplayer-smoothstreaming")
>                 includeModule("com.google.android.exoplayer", "exoplayer-ui")
>             }
>         }
> 
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> ```

Sorry I was busy that I could not get you there faster but glad you managed it.

**Comment by ObidosDev** [comment]
```
        // jcenter repository is deprecated: https://developer.android.com/studio/build/jcenter-migration
        //noinspection JcenterRepositoryObsolete
        jcenter() {
            content {
                // however, react-native-video's native packages have not been migrated yet, so we keep this config for now
                includeModule("com.yqritc", "android-scalablevideoview")
                includeModule("com.google.android.exoplayer", "extension-okhttp")
                includeModule("com.google.android.exoplayer", "exoplayer")
                includeModule("com.google.android.exoplayer", "exoplayer-core")
                includeModule("com.google.android.exoplayer", "exoplayer-dash")
                includeModule("com.google.android.exoplayer", "exoplayer-hls")
                includeModule("com.google.android.exoplayer", "exoplayer-smoothstreaming")
                includeModule("com.google.android.exoplayer", "exoplayer-ui")
                includeModule("com.google.android.exoplayer", "exoplayer-extractor")
                includeModule("com.google.android.exoplayer", "exoplayer-common")
                includeModule("com.google.android.exoplayer", "exoplayer-transformer")
            }
        }
```
