### ISSUE TITLE
Get the currently playing level information on adaptive bitrate playback

### ISSUE THREAD

**Issue by ramiro-r** [TheWidlarzGroup/react-native-video#2476]
# Feature Request

I didn't find a way to accomplish a requirement of tracking which is the quality of the level/track of the manifest the user is actually seeing while playing a stream. Is this possible to achieve with the current version of the lib? Maybe I didn't find a way to do it.

## Why it is needed

It would be nice to get metrics of quality levels for some clients. They need to know sometimes which is the quality the user is getting and how much time they're able to get the highest quality possible.

**Comment by Fedeorlandau** [comment]
Hi, This would be great. Any updates?

**Comment by freeboub** [comment]
So sure this should be closed, it is an interesting feature !

**Comment by hueniverse** [comment]
It has been open for over 6 months an no one showed any interest in working on it. I don't want to have hundreds of open issues that are legitimate requests when we don't have the resources to do anything about it. If someone wants to work on this I would be happy to reconsider.
