### ISSUE TITLE
onPlaybackRateChange is not fired

### ISSUE THREAD

**Issue by c0m1t** [TheWidlarzGroup/react-native-video#2478]
# Bug

`onPlaybackRateChange` callback is not fired on android when player is paused or played.

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 21.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12 => 16.12.0
    react-native: github:jitsi/react-native#891986ec5ecaef65d1c8a7fe472f86cf84fe7551 => 0.61.5-jitsi.2
```

Library version: 5.1.1

## Expected behaviour

1. `onPlaybackRateChange` callback must be fired when user plays or pause the video.

**Comment by tushar-singhal** [comment]
I am facing the same issue as well.

**Comment by Saikedo** [comment]
Same issue on Android, 

Also on iOS there are multiple similar calls coming in one after another, not sure if that is expected.

**Comment by Aaron46** [comment]
I'm not an Android dev so I can't say this is super correct, but this is what I changed to get this to work. I used [patch-package](https://www.npmjs.com/package/patch-package)  to install.
```diff --git a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index 482ff93..6998417 100644
--- a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -1270,8 +1270,10 @@ class ReactExoplayerView extends FrameLayout implements
         if (player != null) {
             if (!paused) {
                 startPlayback();
+                eventEmitter.playbackRateChange(rate);
             } else {
                 pausePlayback();
+                eventEmitter.playbackRateChange(0);
             }
         }
     }

**Comment by jrhager84** [comment]
> I'm not an Android dev so I can't say this is super correct, but this is what I changed to get this to work. I used [patch-package](https://www.npmjs.com/package/patch-package) to install.
> 
> ```diff
> index 482ff93..6998417 100644
> --- a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> +++ b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
> @@ -1270,8 +1270,10 @@ class ReactExoplayerView extends FrameLayout implements
>          if (player != null) {
>              if (!paused) {
>                  startPlayback();
> +                eventEmitter.playbackRateChange(rate);
>              } else {
>                  pausePlayback();
> +                eventEmitter.playbackRateChange(0);
>              }
>          }
>      }
> ```

This fixed it for me as well!

**Comment by hueniverse** [comment]
@jrhager84 care to submit a PR?
