### ISSUE TITLE
We cannot make react-native-video player to play a video from a API file service

### ISSUE THREAD

**Issue by hakanlekesizfeux** [TheWidlarzGroup/react-native-video#2479]
# Bug
Postman or android devices play it nicely, but on iOS platform we are facing the problem. Basically, a user logs in the application and makes a call to API service which returns the mp4 video.Postman header info is also attached. Any help is appreciated.

```
<Video
            source={{
              uri: "https://api.xxxx.org/v1/files/7afbd0c3-ab0e-4cfb-910a-10c058a07b20"
            }}
            // Can be a URL or a local file.
            controls={true}
            fullscreen={true}
            resizeMode="contain"
            ref={(ref) => {
              this.player = ref
            }}    
/>
```
![Capture](https://user-images.githubusercontent.com/65661926/132328144-b0e95284-46d0-4f8a-9f96-3fbe08208cd6.PNG)

## Platform
 
* iOS

**Comment by Sanglepp** [comment]
Can confirm that the issue exists.

Woks well on android and in postman. On iOS it gives an error stating that the server is not configured correctly. 

`The server is not correctly configured. - The AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain".`

Have tried adding different content-type type to return headers and even tried accessing remote file with the correct file extension. The video still doesn't play. 

This probably isn't an issue with the library though but seems to be an issue with AVPlayer module for iOS which is used in this library.

**Comment by MadhavNasit** [comment]
@Sanglepp Same issue, Found any solution?

**Comment by Sanglepp** [comment]
> @Sanglepp Same issue, Found any solution?

The issue was on server side configuration.

If you try accessing the file in the browser, does the video start playing in the browser (I tried in chrome) or will it automatically download the video? 

Seems that iOS doesn't play videos that have Content-Dispositon: "attachment" header.

**Comment by mattgle** [comment]
Same issue any solutions?

**Comment by mattgle** [comment]
Hi guys I've found a workaround, this might not work for everyone but still I'm posting it for the ones that need this urgent.

The thing is that like @Sanglepp said "Seems that iOS doesn't play videos that have Content-Dispositon: "attachment" header." so I decided to download the file locally and then pass that local video to the `<Video/>` component.

This approach worked for my because I have small videos on repeat (like "gifs") so I didn't have any problems downloading those videos and then showing them.

I've created a hook using `rn-fetch-blob` that downloads the video and returns the path where is located.

```
import { useEffect, useState } from 'react';
import RNFetchBlob from 'rn-fetch-blob';

function useFileDownload(uri) {
  const [path, setPath] = useState(null);
  useEffect(() => {
    RNFetchBlob.config({
      fileCache: true,
      appendExt: 'mp4',
    })
      .fetch('GET', uri)
      .then(res => {
        setPath(res.path());
      });
  }, []);

  if (path) {
    return path;
  }
}

export default useFileDownload;
```

and then I call that hook to get the working uri like this:

```
  const newUrl = useFileDownload(url);
  ...
        <Video
        repeat
        onLoad={hideSpinner}
        resizeMode="cover"
        source={{ uri: newUrl }}
        style={{ ...styles.image, height: 165, width: 165 }}
      />
```

**Comment by sushilbansal** [comment]
i think i might have a solution if you control the video upload yourself on your server. Try this metadata while uploading video on the server:
`contentType: 'application/gzip'`
and do not set any encoding. Not sure if you do not control the videos uploading then how it can be managed.

**Comment by nborkhataria** [comment]
@sushilbansal  , Issue is with streaming video on iOS device from server, not with uploading to server. Are you able to stream video from server to iOS device ?

**Comment by sushilbansal** [comment]
yes, i am able to stream video on ios device. In my case i was in charge of uploading the video and not just any random video link. What worked for me eventually was: 

// for images while uploading
createWriteStream({
  gzip: true
}),

// for video while uploading
createWriteStream({

})

**Comment by nborkhataria** [comment]
Hey @sushilbansal , Thanks for the response. Will you be able to share more details on streaming video in iOS side? 
I have raised a question with service side code and video component code extracts that I am using in our app, where I am returning 206 HTTP status code with bytes of video in chunks as a response. Below is the link with details :
[https://github.com/react-native-video/react-native-video/issues/2586]

**Comment by TalMars** [comment]
If you are using nestjs try this code
``` 
async downloadFile(id: string, request: RequestExpress, response: ResponseExpress) {
    const getContentDisposition = require('content-disposition');
    const mime = require('mime-types');
    const doc = await this.get(id);
    const file = await FileHelper.getFile(doc.path);
    const videoRange = request.headers.range;
    const contentDisposition: string = getContentDisposition(doc.name);
    const contentType = mime.contentType(doc.name);
    const path = DocumentHelper.fullPath(doc.path);
    if (videoRange) {
      const stat = statSync(path);
      const fileSize = stat.size;
      const parts = videoRange.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
      const chunksize = end - start + 1;
      const readstream = createReadStream(path, { start, end });
      const head = {
        'Content-Range': 'bytes ${start}-${end}/${fileSize}',
        'Accept-Ranges': 'bytes',
        'Content-Length': chunksize,
        'Content-Type': 'video/mp4',
      };
      response.status(206);
      response.set(head);
      return new StreamableFile(readstream);
    } else {
      const readstream = createReadStream(DocumentHelper.fullPath(doc.path));
      // response.status(200);
      response.set({
        'Accept-Range': 'bytes',
        'Content-Type': contentType,
        'Content-Length': file.length,
        'Content-Disposition': contentDisposition,
      });
      return new StreamableFile(readstream);
    }
  }
  ```
