### ISSUE TITLE
Video is Playing in background in Android

### ISSUE THREAD

**Issue by swaroopa94** [TheWidlarzGroup/react-native-video#248]
Hi,
This is Swaroopa Working on React Native.
I am using htis module but has a issue in playing video in Android.
The issue is while the video is playing when we go to background or click on home button  thenn the video is not stopping i.e., playing in background .
I used the property  
              playInBackground={false}
    but it is not working for android. Please what can i do for this.

Please reply fastly as it is very urgent.

**Comment by alessandro-bottamedi** [comment]
Same for me on android (RN 0.29) local video still play when app go in background with playInBackground={false}

**Comment by mattapperson** [comment]
Can one of you please provide some sample code to help reproduce this issue?

**Comment by swaroopa94** [comment]
yes,
`<TouchableOpacity style={styles.fullScreen} onPress={() => {this.setState({paused: !this.state.paused})}}>
          <Video
            source={{uri:uri}}
            style={styles.fullScreen}
            rate={this.state.rate}
            paused={this.state.paused}
            volume={this.state.volume}
            muted={this.state.muted}
            resizeMode={this.state.resizeMode}
            onLoad={this.onLoad}
            onProgress={this.onProgress}
            onEnd={() => {this.setState({paused: !this.state.paused})}}
            repeat={false}
            playInBackground={false} 
            controls={this.state.controls}
          />
        </TouchableOpacity>`

This is my code please help me how to solve this.

**Comment by caomaoxiaozi** [comment]
@swaroopa94  I set 'controls={true}' is ok in ios.

**Comment by swaroopa94** [comment]
It's Working in IOS but in android its not working.
In Android video is playing in background in IOS it is not Playing.

**Comment by bruel-gabrielsson** [comment]
+1

**Comment by CrazyStoneJy** [comment]
+1

**Comment by swaroopa94** [comment]
Please respond as its urgent

**Comment by airman00** [comment]
Anyone had any success with this?

**Comment by mattapperson** [comment]
Has anyone tried v1.0 of the module to see if it fixes this?

**Comment by swaroopa94** [comment]
I just upgraded my react native version to 0.39 and its working fine now.

**Comment by jameshuynh** [comment]
It is still an issue for me on react native 0.50. The video does not pause when go to background mode even though I set the paused flag to be true before the app goes to background

**Comment by stoner2497** [comment]
sometimes react-native-community sucks

**Comment by mattapperson** [comment]
Comment deleted, we ask that you please remember that this is a community project, of people donating their time to the project. If there is a long standing issue, fix it or don’t use the project. This is what open source is.

**Comment by pawanm09** [comment]
I am still facing the issue on Android Device in

react-native: 0.61.5
react-native-video: 5.0.2

**Comment by Dev-Suthar** [comment]
We can use Appstate for stopping Background Video....
this example will help to detect Background state of application..  
https://reactnativecode.com/detect-app-is-in-background/ 
then you can put your method into that state...if nextAppstate === 'background' then setstate your Pausemethod() into this condition 
Hope it will help you.....

**Comment by purut18** [comment]
@Dev-Suthar Thanks! That works.

Code:

```
    handleAppStateChange = (appstate) => {
        this.setState({
            paused: appstate == "active" ? false : true
        })
    }

    componentDidMount = () => {
        AppState.addEventListener('change', this.handleAppStateChange);
    }
    
    componentWillUnmount = () => {
        AppState.removeEventListener('change', this.handleAppStateChange);
    }
```

**Comment by iamabdulhaseeb** [comment]
If you dont want to play video in background, you can check the app state first then you can add a listener

  useEffect(() => {
        AppState.addEventListener('change',handleAppState);
    },[]);

    const handleAppState = (state) => {
        console.log(state);
        setPaused(true);
        console.log(paused);
        if(state == 'background') {
            setMuted(true);
        } else {
            setMuted(false)
        }
    }   
    AND THEN HERE YOU CAN ADD MUTED AND PAUSED VALUES IN VIDEOPLAYER.
    <VideoPlayer
                       muted={muted}
                       paused={paused}
                     
                   />
