### ISSUE TITLE
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### ISSUE THREAD

**Issue by sezhilarasan** [TheWidlarzGroup/react-native-video#2480]
Hi 

i am new to react native,just a beginner. am unable to build my project after installing dependency 
npm-install-react-native-video.its showing below errors. in my previous project it was working fine,
i have autolinked as well. my project version details are mentioned below.
is this npm deprecated. if i uninstall this npm its building fine.

pls someone help me,am strugglind for the last 2 weeks due to this.

> Task :app:checkDebugAarMetadata FAILED
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

Execution failed for task ':app:checkDebugAarMetadata'.

  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-video": "^5.1.1",
    "react-native-video-controls": "^2.8.1"
  },

App.js:

import React from 'react';
import {View,Text} from 'react-native';
import VideoPlayer from 'react-native-video-controls';
import Video from 'react-native-video';

const Video =()=>{
  return(
   <View style={{flex:1,alignItems:'center',justifyContent:'center'}}>
    <Video
      source={{uri:'https://www.w3schools.com/html/mov_bbb.mp4'}}
    />
    </View>
  )
}

export default Video;

**Comment by sezhilarasan** [comment]
can anyone help me out of this issue?

**Comment by ferencik-f** [comment]
In RN 0.65, jcenter() in android/build.gradle was deleted. Add it to app/build.gradle 

Solution [#2462. ](https://github.com/react-native-video/react-native-video/pull/2462#issuecomment-907750528)
