### ISSUE TITLE
TypeError: Cannot read property 'Constants' of null

### ISSUE THREAD

**Issue by Nirmit04** [TheWidlarzGroup/react-native-video#2481]
# Bug

After Installing the package when tried to use the Video component the app crahsed and in the console following error was shown:
**TypeError: Cannot read property 'Constants' of null**
Since i am using react-native version 0.65.1 so autolinking is supported, but due to this error tried manual linking as well for android and still the same error.

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:
```bash
 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.01 GB / 15.90 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: 31
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: Not Found
  Languages:
    Java: 11.0.5
  npmPackages:
    react: 17.0.2
    react-native: 0.65.1
    react0-native-video:5.1,1
```
**Library version: 5.1.1**

**Comment by liquidvisual** [comment]
@Nirmit04 Did you ever figure this out?

**Comment by freeboub** [comment]
As no sample app is provided, this issue cannot be investigated... Not sure how someone can handle such issue ...

**Comment by Mr-BAKH** [comment]
hey guys
I thing this is not a big deal, you can rebuild your project with android studio then handle this error. I did this way and it works!
![Untitled2](https://github.com/react-native-video/react-native-video/assets/109528129/88f277f8-7119-4cd4-993e-4069ac173647)
