### ISSUE TITLE
Switching paused in the flat list is not smooth.

### ISSUE THREAD

**Issue by yjunya** [TheWidlarzGroup/react-native-video#2482]
I'm using react-native-video in the flat list, and controlling the video to play by switching paused when scrolling, but it's not smooth. (It is laggy when switching paused).
Is there a good solution?

**Comment by pepemiso16** [comment]
Looks like there's no support for this feature

**Comment by marco-guida** [comment]
Same issue here. Trying to calculate if it's in the viewport within the container of the video component to see if that will help instead of passing it down through props from the flat list. Doubtful that this will help.

**Comment by yjunya** [comment]
@iwantadventureinthegreatwidesomewhere 
Thank you for your reply. Please tell me the link of the issue.

**Comment by stefanahman** [comment]
@yjunya @iwantadventureinthegreatwidesomewhere did you end up solving this? it's still a problem
