### ISSUE TITLE
hideShutterView prop doesn't work

### ISSUE THREAD

**Issue by KyoungHwanLee** [TheWidlarzGroup/react-native-video#2483]
# Bug

Even when set `hideShutterView` to true, the shutter view is not hidden.

https://github.com/react-native-video/react-native-video/blob/bf11502fdb83751ad826f3e4b448732075292805/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java#L131-L149
https://github.com/react-native-video/react-native-video/blob/bf11502fdb83751ad826f3e4b448732075292805/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java#L196-L210
142th line and 209th line ignore `hideShutterView` prop and force the visibility of shutter view to VISIBLE.
These codes should be replace to `this.updateShutterViewVisibility();`

## Platform
* Android ExoPlayer

## Environment info

Library version: 5.1.1

## Steps To Reproduce

Just set `hideShutterView` to true.

## Expected behaviour

1. Shutter view should be hidden

**Comment by ldabiralai** [comment]
Looks like this was fixed as part of https://github.com/react-native-video/react-native-video/commit/6d74eb686f9c97924cd33dee288d4fd7a258944d any idea when this will be released? 🙏

**Comment by tironiigor** [comment]
@ldabiralai I'm not sure, but you can always use the latest changes in your project!
