### ISSUE TITLE
When re-run video after End, onProgress not fire

### ISSUE THREAD

**Issue by Girum** [TheWidlarzGroup/react-native-video#2485]
Hi. I`m trying to re-reun the video after it ends. I put the setPaused to true (ok). When I set Play, the video re-runs, but the onProgress Callback doesn't fire anymore. How to proceed? (because of it, my progressBar dont fill anymore).

Edit: in iOS, qhen i click agian in Play, the video not re-rerun

**Comment by NiuGuohui** [comment]
hey, you can use `video.current?.seek(0, 0);` to reset currentTime.

**Comment by tackanoway35** [comment]
Issue on Android, IOS work perfectly.
I want to replay this song when it's end but I see onProgress Callback doesn't fire after onEnd fires.
So that my progressBar can't run, current time have no change.
How can i resolve this problem.
Thanks!
