### ISSUE TITLE
How to play only one video at a time

### ISSUE THREAD

**Issue by ferasabufares** [TheWidlarzGroup/react-native-video#2488]
in my flat list i need to play one video at a time 

how to make it work ??

**Comment by itershukov** [comment]
The same question here.

**Comment by ferasabufares** [comment]
@itershukov  i manage to make it work like this 

      <Video
            ref={async ref => {
              this.player = ref;
            }}
            source={{
              uri: this.props.source,
            }}
            style={styles.Sound_audioStyle}
            controls={false}
            resizeMode={'contain'}
            onLoad={this.onLoadEnd}
            onProgress={this.onProgress}
            onEnd={this.onEnd}
            paused={this.props.user.voicId == this.props.voicId ? false : true}
            audioOnly={true}
          />

        paused={this.props.user.voicId == this.props.voicId ? false : true}

so when i press on play button i put voicId to current video   so it will play and stop all the other video
          
          
          this.props.voicId  it is refer to current video 
          this.props.user.voicId  i put this value when i press play

**Comment by ghost** [comment]
If you are using redux in your application, you can use selectors and reducers to store the current playing video and set paused to false only if the current playing video from selectors is same as the current video.

**Comment by WenLonG12345** [comment]
@ferasabufares can I know when you set `voicId` ?

**Comment by ferasabufares** [comment]
@WenLonG12345  when i press play

**Comment by WenLonG12345** [comment]
yea but which line of code that detech when you press play?

**Comment by zchwyng** [comment]
This is not an issue in the library, so I'm closing this.
