### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by Hamiltontx** [TheWidlarzGroup/react-native-video#249]
Error setting property 'src' of RCTVideo with tag #9: Exception thrown while executing UI block: **\* -[NSURL initFileURLWithPath:]: nil string parameter
on RN 0.24.1

working like a charme on Android (just put the file on /raw)

**Comment by Hamiltontx** [comment]
My bad.

IOS OK. Just insert the mp4 in Xcode project ... sorry.

**Comment by Surreal9** [comment]
How do you do this in xcode?
