### ISSUE TITLE
player not playing 3gp video 

### ISSUE THREAD

**Issue by vazgengalstyan** [TheWidlarzGroup/react-native-video#2492]
i try to play 3gp video but take error -11800

**Comment by devproivansurzhenko** [comment]
I am experiencing the issue also. Same video is playing correctly at `Files` app. Sample video is attached.

RNV version: 5.2.0 (also tested 5.0.2)
RN: 0.66.2
iOS version: tested as on 15 as on 13.x. Not tested on Android.

[89915993-34ea-4123-9601-2d689432e093.3gp.zip](https://github.com/react-native-video/react-native-video/files/7567020/89915993-34ea-4123-9601-2d689432e093.3gp.zip)
 (Sorry, github declines 3gp as attachment)

**Comment by AdnanAshraf-gol** [comment]
any update on this ?
