### ISSUE TITLE
can't play format .m3u8  stream have ID3 tags audio only in iOS 15

### ISSUE THREAD

**Issue by hendradedis** [TheWidlarzGroup/react-native-video#2496]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. put url .m3u8 format tags id3 
2. run -> play audio,  no sound comes out

## Expected behaviour

1.sound on , and i get response metaData id3
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
url example : https://db2.indexcom.com/bucket/ram/00/05/05.m3u8

**Comment by MuhammadMuzammilQadri** [comment]
I have the exact same issue. Everything is working fine on iOS 14 but no sound on iOS 15

**Comment by ghacosta** [comment]
Hey guys did you solve this issue? I'm have same issue on iOS with this video [https://stream.mux.com/fHTBBwJGJT44eTVqHhp6zp1htrGmmZ99dzAI01aySibU.m3u8](https://stream.mux.com/fHTBBwJGJT44eTVqHhp6zp1htrGmmZ99dzAI01aySibU.m3u8)
