### ISSUE TITLE
App with ExoPlayer builds successful but crashes without any errors

### ISSUE THREAD

**Issue by kotoyama** [TheWidlarzGroup/react-native-video#2497]
# Bug

I'm trying to configure `react-native-video` to use ExoPlayer. I followed the instructions in readme, so my app builds successfully. But when I start my app, it crashes without any feedback like errors/logs (see a video below).

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 3.37 GB / 15.91 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    Visual Studio: Not Found
  Languages:
    Java: 11.0.12 - C:\Program Files\Java\jdk-11.0.12\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.1.1

## Steps To Reproduce

Just follow the instructions in [Readme.md](https://github.com/react-native-video/react-native-video#android-installation) for ExoPlayer.

## Expected behaviour

App runs without crashes.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

https://user-images.githubusercontent.com/26006369/134701329-9a206a04-f809-431b-ab77-519621580e1f.mp4

**Comment by DiogoAbu** [comment]
When it crashes like this it's probably an error on the native side. Look up how to use "adb logcat" to get the android logs

**Comment by kotoyama** [comment]
Resolved this issue by removing [this](https://github.com/react-native-video/react-native-video/issues/2461#issuecomment-904399554) part of code from the `react-native.config.js` file. Android ExoPlayer configuration should be as described in [README](https://github.com/react-native-video/react-native-video#android-installation).

**Comment by JassiSingh08** [comment]
> Resolved this issue by removing [this](https://github.com/react-native-video/react-native-video/issues/2461#issuecomment-904399554) part of code from the `react-native.config.js` file. Android ExoPlayer configuration should be as described in [README](https://github.com/react-native-video/react-native-video#android-installation).

Hey, I am trying to implement react native video, it is working correctly in dev but the video player is not visible in the build apk, I tried congif part but then it gives me javadebugkotlin failed error. 

Can you please help me out?
