### ISSUE TITLE
Integrate cronet network stack

### ISSUE THREAD

**Issue by pkpardeep482** [TheWidlarzGroup/react-native-video#2499]
Hi, we want to use cronet network stack in videos. i can see exo-player is also available inside the library but problem is we are using <Videos/> and we are dependant on its events.  so now my query is 

1. Is it possible to embed cronet into existing implementation of video? if yes then please provide support for that. 
2. If not ,then how can i  use exoplayer instead of <Video/>, without impacting existing functionality. 

Thanks

**Comment by freeboub** [comment]
I confirm this is not support yet:
Doc to integrate it is available here:
https://exoplayer.dev/network-stacks.html
This is a new feature to be implemented...
Let us know if you plan to integrate it
