### ISSUE TITLE
Make react-native a peer dependency

### ISSUE THREAD

**Issue by johanneslumpe** [TheWidlarzGroup/react-native-video#25]
Having it as a dependency could cause issues, if the consumer has a different version than the required one installed. In that case react-native-video will install a local version for react-native as well - undesireable. Since this is a "plugin"  for react-native we should mark it as peer dependency with an according semver range I think.

Thoughts?

**Comment by brentvatne** [comment]
@johanneslumpe - yup, this is very true, we should absolutely do this!

**Comment by johanneslumpe** [comment]
Fixed with 6ffdf4ac0c2978ddde350fc2eea6e23c962759e3
