### ISSUE TITLE
Android - Could not find com.google.android.exoplayer:exoplayer:2.11.4.

### ISSUE THREAD

**Issue by WenLonG12345** [TheWidlarzGroup/react-native-video#2500]
Hi, I am recently using this library in my RN project. It works fine in iOS devices, but when comes to android, I can't build success. Here is the error log. 

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/teowenlong/.m2/repository/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/teowenlong/rn-visitor-app/node_modules/react-native/android/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - file:/Users/teowenlong/rn-visitor-app/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.pom
     Required by:
         project :app
         project :app > project :react-native-video
   > Could not find com.google.android.exoplayer:extension-okhttp:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/teowenlong/.m2/repository/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/teowenlong/rn-visitor-app/node_modules/react-native/android/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - file:/Users/teowenlong/rn-visitor-app/node_modules/jsc-android/dist/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/extension-okhttp/2.11.4/extension-okhttp-2.11.4.pom
     Required by:
         project :app > project :react-native-video
```

It keeps saying that `exoplayer` is not found. but I had follow exactly the installation steps stated in main page. What had I done wrongly?

**Comment by WenLonG12345** [comment]
Finally I found the solution. 
In RN 0.65, `jcenter()` in Android was deleted. 
Add it back to `app/build.gradle` and it works all fine :)

I get the solution from #2462. Any further question may ask in here.

**Comment by brocodedude** [comment]
This fix isn't working for me :( I'm using RN 0.66

**Comment by karthikkncs14** [comment]
Not working for me as well RN 0.66.4

Could not find com.google.android.exoplayer:exoplayer:2.9.2.
Required by:
    project :expo-av
Search in build.gradle files

**Comment by bodrius** [comment]
same issue

**Comment by stevehs17** [comment]
Worked for me with RN 0.67.2.

I was able to fix this by adding the line `jcenter()` to **android**/build.gradle (rather than android/**app**/build.gradle). Here is the context:
```
allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        // I ADDED THE NEXT LINE:
        jcenter() 
        maven { url 'https://www.jitpack.io' }
        maven {
            // expo-camera bundles a custom com.google.android:cameraview
            url "$rootDir/../node_modules/expo-camera/android/maven"
        }
    }
}

```

**Comment by shelzTimesignature** [comment]
> Worked for me with RN 0.67.2.
> 
> I was able to fix this by adding the line `jcenter()` to **android**/build.gradle (rather than android/**app**/build.gradle). Here is the context:
> 
> ```
> allprojects {
>     repositories {
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
>         mavenCentral {
>             // We don't want to fetch react-native from Maven Central as there are
>             // older versions over there.
>             content {
>                 excludeGroup "com.facebook.react"
>             }
>         }
>         google()
>         // I ADDED THE NEXT LINE:
>         jcenter() 
>         maven { url 'https://www.jitpack.io' }
>         maven {
>             // expo-camera bundles a custom com.google.android:cameraview
>             url "$rootDir/../node_modules/expo-camera/android/maven"
>         }
>     }
> }
> ```

its not app/build.gradle its android/build.gradle

**Comment by stevehs17** [comment]
Android has two build.gradle files, one located at android/build.gradle, the other at android/app/build.gradle. You have to modify the right one (android/build.gradle).

**Comment by JDMathew** [comment]
To prevent this from conflicting with marvenCentral it's better to add the following to `android/app/build.gradle` under 

```
allprojects { 
  repositories {
  
  // Add jcenter **********

  jcenter() {
            content {
                includeGroup("com.google.android.exoplayer")
            }
        }

  // **********
      
    }
}
```

**Comment by penghouho** [comment]
jcenter is deprecated now..

> WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.

not sure how to get the com.google.android.exoplayer:exoplayer:2.11.4 out of jcenter in future.

**Comment by Manil-SoftNEP** [comment]
> Finally I found the solution. In RN 0.65, `jcenter()` in Android was deleted. Add it back to `app/build.gradle` and it works all fine :)
> 
> I get the solution from #2462. Any further question may ask in here.

This workaround works but it causes the app to crash on devices with low width. For me it was Samsung Galaxy M 62. Does anyone know how to fix this?

**Comment by mihaislobozeanu** [comment]
The proper solution can be found at #2611, no jcenter() as it will be obsolete.
