### ISSUE TITLE
HTTPS Audio Stream Not Playing

### ISSUE THREAD

**Issue by AydenSchultz** [TheWidlarzGroup/react-native-video#2501]
Hi, I'm working on creating a streaming app for the radio station I work for and I'm having trouble getting a certain audio stream to play. During development we switched hosting services and I had to switch the audio uri for the stream I'm using. The old streaming uri plays without issue, but this new uri doesn't want to play through my app. No errors are thrown when trying to play the new stream. Both streams play without issue when opened in a browser. Currently developing in Android Exoplayer. I'm very new to react native and app development in general so I'm not sure if I'm just missing something obvious or what. Here is the code for the player object I'm using:

import React from 'react';
import Video from 'react-native-video';
import {
  View,
  TouchableOpacity,
  StyleSheet,
  Text,
  ActivityIndicator,
} from 'react-native';

export default class Player extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      totalLength: 1,
      currentPosition: 0,
      selectedTrack: 0,
	  isLoading: false,
	  video: <Text/>,
    };
  }
  

  setDuration(data) {
    this.setState({totalLength: Math.floor(data.duration)});
  }

  setTime(data) {
    this.setState({currentPosition: Math.floor(data.currentTime)});
  }

  seek(time) {
    time = Math.round(time);
    this.refs.audioElement && this.refs.audioElement.seek(time);
    this.setState({
      currentPosition: time,
      paused: false,
    });
  }
  
   onLoad = () => {
	   console.log("loaded ding ding");
   }

  render() {
	  
	  console.log("playing");
	  console.log(this.state.paused);
    const track = this.props.tracks[this.state.selectedTrack];
	const video = <Video source={{uri: track.audioUrl}} // Can be a URL or a local file.
        paused={this.state.paused}               // Pauses playback entirely.
        onLoad={this.onLoad()}    // Callback when video loads
        onProgress={this.setTime.bind(this)}    // Callback every ~250ms with currentTime
		playInBackground={true}
		playWhenInactive={true}
		audioOnly={true}
	  />
	  
	if(this.state.isLoading) {
		
		return (
			<View>
				<Text>Loading...</Text>
			</View>
			);
			
	} else {
		
		return (
			<View style>
				{video}
			</View>
			);
			
	}
  }
}

The old uri I passed in: http://stream.studio.wsum.wisc.edu/wsum128

The new uri I'm trying to pass in: https://ice23.securenetsystems.net/WSUMFM

**Comment by freeboub** [comment]
https streaming needs a new flag to configure in manifest.
please read updated doc which indicates that
