### ISSUE TITLE
How to ensure I'm using ExoPlayer or MediaPlayer?

### ISSUE THREAD

**Issue by kotoyama** [TheWidlarzGroup/react-native-video#2503]
How to ensure I'm using ExoPlayer or MediaPlayer? It looks like nothing changes if I modify `settings.gradle` file.

**Comment by ekremay** [comment]
@kotoyama I think key point is `onBuffer` event. If your app using ExoPlayer, onBuffer event will work properly. 
This event doesn't work on old MediaPlayer. Try to use onBuffer event. If it works, you are using ExoPlayer.
