### ISSUE TITLE
Vídeo container not showing on iPhone X

### ISSUE THREAD

**Issue by Girum** [TheWidlarzGroup/react-native-video#2504]
Hi. I teste the app in vários iphone models, but only in iPhone X, Xr the vídeo dont show. It freezer the screen, and after download the vídeo,it not appears. Can anyone help?

**Comment by zchwyng** [comment]
Please provide more info.

**Comment by Girum** [comment]
I set the video for Dimensions.get('window').width, and height for Dimensions.get('window').width/1.777 (to maintain the 16:9. 

When I open the page or modal, the screen frezzes for a while (the video not appear at all, so, all the content padding up). After like 5 seconds, the video appears, but breaks all the content and stays up the content (continue breaking the page style). I tested in Android phones and various Iphone models (iPhones 7, 8, 11, 12...), but it happens only in iPhone X models (simulators and real devices).

The problem is it no generates any errors.
