### ISSUE TITLE
tvOS 15, options menu not clickable. 

### ISSUE THREAD

**Issue by blytung** [TheWidlarzGroup/react-native-video#2507]
# Bug

When using react-native-video with tvOS 15, you are not able to change audio tracks or subtitles. The menu buttons is showing up (apples new UI) but you can't click them. 

## Platform
* tvOS

## Environment info

Library version: react-native-tvos@0.63.1-4

## Steps To Reproduce

1. Open a video with tvOS 15 simulator, try to hit the icons above the timeline for the video. (previous swipe down)

## Expected behaviour

1. Show controls

**Comment by kwarismian** [comment]
I can confirm this behavior as I have been chasing it for a few days now.  To replicate you can use the Apple HLS test stream as the video URI (contains captions):
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

I can also confirm that caption selection works perfectly with the swipe-down menu on TVOS 14.3 or earlier, but on 15 the buttons for both captions and audio selection appear but when selected the UIMenu does not present as expected.

**Comment by NazarKurylo** [comment]
same problem, any updates?

**Comment by ashnfb** [comment]
This is being caused by setFullscreen and setControls being called in RCTVideo.m before setSrc has created the _player object.  The _player object is required for setFullscreen to present a full-screen videocontroller on tvOS.  But setSrc is not creating the _player object until a later time (dispatch_after)

Quick fix: comment out the dispatch_after (just the single line,  and not the whole block) in setSrc, and the options menu will work on tvOS.

**Comment by NazarKurylo** [comment]
doesn't work for me

**Comment by ashnfb** [comment]
@NazarKurylo, I had the same problem and fixed it on an older version of the repo.
Have a look at commits #5f19b4f and #60ae02c in this branch
https://github.com/nfb-onf/react-native-video/commits/4.4.7-tv

**Comment by NazarKury1o** [comment]
@ashnfb, hey - tried your changes on same old version of repo and it doesn't work for me. Subtitles and audio options **are not clickable**. Tested on device (tvOS 15.1.1) and emulator (tvOS 15.0).
mb I'm missing something in App.js file?

> import React, {Component} from 'react';
> import Video from 'react-native-video';
> export default class App extends Component{
>  render() {
>     return (
>         <Video
>           controls
>           style={{flex:1}}
>           source={{uri: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8'}}
>         />
>     )
>   }
> }

**Comment by ashnfb** [comment]
@NazarKury1o , here's what I have.  Fullscreen is required.  Also, pay attention to  onFullscreenPlayerWillDismiss and onEnd, as I had to also call navigation.dispatch(StackActions.pop()) to exit the video player component in my app.

` <Video style={{ flex: 1 }}
          source={{ uri: '....m3u8' }}
          ref={(ref) => {
            this.videoContainer = ref;
          }}
          paused={this.state.paused}
          onEnd={this.onEnd}
          onFullscreenPlayerWillDismiss={this.fullScreenWillDismiss}
          fullscreen={true}
          controls={true}
          selectedTextTrack={this.state.selectedTextTrack}
        />`

**Comment by NazarKury1o** [comment]
@ashnfb 
Thanks! It work!
Missed, that fullscreen is required.
