### ISSUE TITLE
"Player is accessed on the wrong thread"

### ISSUE THREAD

**Issue by BatRisbec** [TheWidlarzGroup/react-native-video#2508]
# Bug

Hi there,

I have encountered an issue in my Crashlytics report on Android with the last react-native-video version that I never saw before, probably linked to the recent ExoPlayer update:

Fatal Exception: java.lang.IllegalStateException
Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread

Does anyone have any input on this?

Thanks in advance!

"react": "16.13.1",
 "react-native": "0.63.4",
"react-native-video": "^5.2.0-alpha1",
  Platform: Android
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

**Comment by zchwyng** [comment]
Thanks for reporting! Is anyone else experiencing this?

**Comment by freeboub** [comment]
to be retested with master branch.
I don't see such issue for now.
can you provide a full logcat and reopen the issue please ?

**Comment by RythzLab** [comment]
Getting same issue with the below stack trace under Firebase Crashlytics,

Fatal Exception: java.lang.IllegalStateException
Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread

com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread (SimpleExoPlayer.java:1959)
com.google.android.exoplayer2.SimpleExoPlayer.getPlayWhenReady (SimpleExoPlayer.java:1477)
com.brentvatne.exoplayer.ReactExoplayerView.pausePlayback (ReactExoplayerView.java:631)
com.brentvatne.exoplayer.ReactExoplayerView.onAudioFocusChange (ReactExoplayerView.java:693)
android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage (AudioManager.java:3136)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:255)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:228)
java.lang.Thread.run (Thread.java:923)

"react": "18.2.0",
"react-native": "0.68.2",
"react-native-video": "^5.2.0",
Platform: Android
buildToolsVersion = "31.0.0"
minSdkVersion = 24
compileSdkVersion = 31
targetSdkVersion = 31

Please help with the solution.

**Comment by TatuUlmanen** [comment]
Getting the same error when unmuting and muting several videos in a row, using 6.0.0-alpha.1 and RN 0.69.5.

```I MediaFocusControl: requestAudioFocus() from uid/pid 10509/24210 clientId=android.media.AudioManager@bab050bcom.brentvatne.exoplayer.ReactExoplayerView{4cf2d89 V.E...... ........ 0,0-1080,2260 #945} callingPack=myapp req=1 flags=0x0 sdk=30
I myapp: WaitForGcToComplete blocked Explicit on ProfileSaver for 21.327ms
I myapp: Waiting for a blocking GC Explicit
D MediaFocusControl: end and return AUDIOFOCUS_REQUEST_GRANTED
E OMX_COMMON:  Invalid key : -22 Cannot find key in map
D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@bab050bcom.brentvatne.exoplayer.ReactExoplayerView{6c3bb73 V.E...... ........ 0,0-1080,2260 #8af}
D CCodec  : allocate(c2.android.aac.decoder)
E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
E AndroidRuntime: Process: myapp, PID: 24210
E AndroidRuntime: java.lang.IllegalStateException: Player is accessed on the wrong thread.
E AndroidRuntime: Current thread: 'mqt_native_modules'
E AndroidRuntime: Expected thread: 'main'
E AndroidRuntime: See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2595)
E AndroidRuntime:        at com.google.android.exoplayer2.ExoPlayerImpl.getPlayWhenReady(ExoPlayerImpl.java:739)
E AndroidRuntime:        at com.brentvatne.exoplayer.ReactExoplayerView.pausePlayback(ReactExoplayerView.java:837)
E AndroidRuntime:        at com.brentvatne.exoplayer.ReactExoplayerView.onAudioFocusChange(ReactExoplayerView.java:899)
E AndroidRuntime:        at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2974)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:233)
E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
I CCodec  : Created component [c2.android.aac.decoder]
D CCodecConfig: read media type: audio/mp4a-latm```

**Comment by oye-eduardo** [comment]
Hi, getting the same error in Firebase Crashlytics within my app:

`Fatal Exception: java.lang.IllegalStateException: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
       at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1953)
       at com.google.android.exoplayer2.SimpleExoPlayer.getPlayWhenReady(SimpleExoPlayer.java:1475)
       at com.brentvatne.exoplayer.ReactExoplayerView.pausePlayback(ReactExoplayerView.java:631)
       at com.brentvatne.exoplayer.ReactExoplayerView.onAudioFocusChange(ReactExoplayerView.java:693)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:764)`


"react": "18.2.0",
"react-native": "0.70.6",
"react-native-video": "5.2.1",
Platform: Android
buildToolsVersion = "31.0.0"
minSdkVersion = 24
compileSdkVersion = 31
targetSdkVersion = 31
