### ISSUE TITLE
Getting Error while trying to play video : An unknown error occurred (1852797029)

### ISSUE THREAD

**Issue by qburst-subins** [TheWidlarzGroup/react-native-video#2515]
localizedDescription: The operation could not be completed
localizedFailureReason: An unknown error occurred (1852797029)

iOS device

**Comment by zchwyng** [comment]
What version of react-native-video are you using? What device?

**Comment by qburst-subins** [comment]
@zchwyng  OS:iOS
OS Version: 14.8
"react-native-video": "^5.1.0-alpha8",

**Comment by zchwyng** [comment]
Please try with the latest version of react-native-video (5.2.0)

**Comment by mhtchawlaAntino** [comment]
Any update on same, having same issue. not working on ios
