### ISSUE TITLE
presentFullscreenPlayer() doesn't work properly on iOS. (only audio is played)

### ISSUE THREAD

**Issue by Tony0205** [TheWidlarzGroup/react-native-video#2520]
# Bug

I have some Issue,
In iOS, when `presentFullscreenPlayer()` of video ref is executed, it becomes fullscreen, but the video stops after 2-3 seconds and only audio is played.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info
- IOS Simulator (I haven't tested it on a device yet. But it seems to be the same.)

React native info output:
```bash
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.50 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.4 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1. using `<Video/>` component, and add `Ref`. (set `controls` property is `false`)
2. When I click custom fullscreen button, fullscreen player open, the video is stop after 2~3 seconds in IOS (but, the video's audio is running continue)
3. I've tried using both the `fullscreen` property of `<Video/>` and `presentFullscreenPlayer()` but it's the same issue in IOS.
4. The full screen function using the controls property works fine, but the above issue occurs when using `presentFullscreenPlayer()`.

...

## Expected behaviour
1. Using `presentFullscreenPlayer()` should play the video normally.

## Reproducible sample code

```javascript
const presentFullScreen = () => {
    // setIsPause(true)
    videoPlayer.current?.presentFullscreenPlayer()
    videoPlayer.current?.seek(0)
}

return (
<Video
        ref={videoPlayer}
        source={{
          uri: videoUri,
        }}
        paused={isPause}
        playInBackground={false}
        style={{
          width: videoWidth,
          height: videoHeight,
        }}
        controls={false}
        repeat={true}
        // fullscreen={isFullScreen} it's same issue
      />
)
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by Tony0205** [comment]
I found someone having the same problem as me:
https://github.com/react-native-video/react-native-video/issues/323#issuecomment-256629472

**Comment by Aaron46** [comment]
@Tony0205 I have this only on a simulator. I've never had this issue on a real device.

**Comment by longb1997** [comment]
same here! I just tested on Simulator

**Comment by Ben8823** [comment]
I have exactly the same issue on iOS. Both on simulator and device.

**Comment by VahanLab** [comment]
Same here. Only tested on simulator

**Comment by luco** [comment]
@hueniverse , not stale. Having this issue on the latest version.

**Comment by ChourasiyaPriyanshi27** [comment]
> I have exactly the same issue on iOS. Both on simulator and device.

The problem is on simulator only not in real device
