### ISSUE TITLE
Videos (in gif and mp4 formats) don't play on physical Android devices. Not Expo

### ISSUE THREAD

**Issue by solomonik07** [TheWidlarzGroup/react-native-video#2524]
Everything works fine on IOS and Android emulator. But on a real Android devices videos do not play.
Does anyone know possible reasons for such behaviour?

**Comment by shivam-pandey99** [comment]
I’m also facing the same issue

**Comment by SontranBK** [comment]
I'm having the same issue? Any ideals?

**Comment by rubenLooplan** [comment]
Same issue
