### ISSUE TITLE
undefined is not an object (evaluating 'RCTVideoInstance.Constants')

### ISSUE THREAD

**Issue by anhminh10a2hoa** [TheWidlarzGroup/react-native-video#2525]
I'm running on my real iphone but it was not running, the title of error is 'Render Error' and the description is "undefined is not an object (evaluating 'RCTVideoInstance.Constants')"

```
TypeError: undefined is not an object (evaluating 'RCTVideoInstance.Constants')

This error is located at:
    in Video (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

**Comment by jonathanredford** [comment]
Running `npx react-native link react-native-video` in the project root and then `pod install` in the `ios` directory fixed it for me.

**Comment by anhminh10a2hoa** [comment]
@jonathanredford thank you for your help, I ran ```pod install``` in the ios dir but it still has this problem. I created the project by expo so I moved to use expo-av instead of react-native-video

**Comment by teewuane** [comment]
I'm having the same issue. Here is my code. I'm trying to load a remote video like `https://somedomain.com/somepath/a-video.mp4`

**Comment by bilalyaqoob** [comment]
I am getting same error, any solution for this issue

**Comment by fukemy** [comment]
@teewuane  where is ur code?
