### ISSUE TITLE
On Android, part of the video starts playing and the video stops for 3 to 5 seconds

### ISSUE THREAD

**Issue by one-god** [TheWidlarzGroup/react-native-video#2526]
onProgress callback console.log
onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 0, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.246, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 8.174, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 9.895, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 9.895, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 9.895, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 9.895, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 9.895, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 10.755, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 10.755, "seekableDuration": 21.51}
 LOG  _onProgress {"currentTime": 0.018, "playableDuration": 10.755, "seekableDuration": 21.51}

**Comment by Krish143git** [comment]
@one-god 1) I also faced this issue Keep this lines in react-native.config.js file  5.1.1(no idea exact video version)
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  dependencies: {
          "react-native-video": {
              platforms: {
                  android: {
                      sourceDir: "../node_modules/react-native-video/android-exoplayer",
                  },
              },
          },
      },
}; 2) also try with 5.2.0 with out above lines it is working from my end

**Comment by hueniverse** [comment]
@Krish143git Thanks for the suggestion.

FYI, if you wrap your code example in three ` before and after it will show up nicer.
