### ISSUE TITLE
React native 0.28 run-android error

### ISSUE THREAD

**Issue by febobo** [TheWidlarzGroup/react-native-video#253]
![image](https://cloud.githubusercontent.com/assets/9276376/16300791/52c5b07e-3974-11e6-9fe2-76ae931dacbd.png)

but rnpm is  already linked
![image](https://cloud.githubusercontent.com/assets/9276376/16300806/69e6f862-3974-11e6-8b75-80c2ef6ed464.png)

**Comment by alessandro-bottamedi** [comment]
Try to go in this file:
`/android/app/src/main/java/com/<AppName>/MainActivity.java`
and replace this line:
`import com.brentvatne.RCTVideo.ReactVideoPackage;`
with this:
`import com.brentvatne.react.ReactVideoPackage;`

I think its an rnpm error...

**Comment by febobo** [comment]
thx,already fix
