### ISSUE TITLE
Media controll center image and title

### ISSUE THREAD

**Issue by vargajacint** [TheWidlarzGroup/react-native-video#2530]
Right now if i play a video the active media name is the app name, and no image available.
![image](https://user-images.githubusercontent.com/42407460/140623716-61f5c05a-7d0c-4d27-bb03-fb63ba13c2c5.png)

![image](https://user-images.githubusercontent.com/42407460/140623717-8cf26878-7032-4a35-b4a4-786f7f41d511.png)

**Comment by ghost** [comment]
Any update?

**Comment by CDBridger** [comment]
bump, I too would like to know this. (And also possible prevent it showing at all as it is conflicting with react native track player)
