### ISSUE TITLE
[ANR] Android API 11/10 Not responding when no internet connection

### ISSUE THREAD

**Issue by UberMC** [TheWidlarzGroup/react-native-video#2536]
# Bug

[ANR] Android API 11/10 Not responding when no internet connection

## Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer?

## Environment info

RN 65.1
Android API 11/10

Library version: 4.4.5 - 5.2.0

## Steps To Reproduce
Android Device API 11/10
Turn off wifi on simulator, or internet connection on app
Load app
navigate to where a remote video will play, app does not respond, try it a couple times.

## Expected behaviour

Video doesn't load?

## Video sample
`<Video source={{ uri: directVideo[multipleVideoIndex].url }}   // Can be a URL or a local file.
            style={{ flex: 1, alignItems: 'center', aspectRatio: 1, borderWidth: 0 }}
            repeat={videoType !== 'multiple'}
            resizeMode='contain'
            onLoadStart={() => {
              setLoading(true)
            }}
            onLoad={() => {
              setLoading(false)
            }}
            onEnd={() => {
              
            }}
          />`

`
11-16 00:18:59.792  8098  8098 W MediaPlayer: java.io.FileNotFoundException: No content provider: https://abucket.s3-us-west-2.amazonaws.com/avideo.mp4
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1673)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1420)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1101)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1073)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1097)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.yqritc.scalablevideoview.ScalableVideoView.setDataSource(ScalableVideoView.java:143)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:300)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:254)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:98)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.view.Choreographer.doFrame(Choreographer.java:721)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.os.Handler.handleCallback(Handler.java:883)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.os.Looper.loop(Looper.java:214)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-16 00:18:59.792  8098  8098 W MediaPlayer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-16 00:18:59.792  8098  8098 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@e7a3a31): Cookies: null
11-16 00:18:59.794  1850  7184 D NuPlayerDriver: NuPlayerDriver(0xf6222680) created, clientPid(8098)
11-16 00:18:59.796  1850  7184 I Codec2Client: Creating a Codec2 client to service "software"
11-16 00:18:59.796  1850  7184 I Codec2Client: Client to Codec2 service "software" created
11-16 00:18:59.798  8098  8183 V MediaHTTPService: makeHTTPConnection: CookieManager created: java.net.CookieManager@aabe516
11-16 00:18:59.798  8098  8183 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@e7a3a31): cookieHandler: java.net.CookieManager@aabe516 Cookies: null
11-16 00:18:59.807  1850  1850 D NuPlayerDriver: reset(0xf6222680) at state 3
`
This results in about 1% of users crashing overall but is increasing as API 11/10 are adapted more over time

**Comment by freeboub** [comment]
you don't use exoplayer but media player according to trace...
Please try with exoplayer and reopen the ticket if needed. (it looks like a Mediaplayer issue)

11-16 00:18:59.792 8098 8098 W MediaPlayer: at android.view.Choreographer.doFrame(Choreographer.java:721) 11-16 00:18:59.792 8098 8098 W MediaPlayer: at
