### ISSUE TITLE
Prevent flashing effect on repeat/ pause/ play

### ISSUE THREAD

**Issue by bitfused** [TheWidlarzGroup/react-native-video#254]
I am trying to configure my Video view in a way so that it doesn't have this flashing effect on repeat/ pause or play with no success. Is there any way to do that? Or is this happening because we are modifying state which makes react to re-render the component? 

Thanks!

**Comment by mattapperson** [comment]
Can you provide any sample code/video of the issue so we can better diagnose the issue please?
