### ISSUE TITLE
Distorted video on Android Exoplayer with HLS (h264 (High 10) ([27][0][0][0] / 0x001B), yuv420p10le)

### ISSUE THREAD

**Issue by enigmablue** [TheWidlarzGroup/react-native-video#2541]
# Bug

Hi, I have a bunch of HLS videos. They are processed via ffmpeg to hls prior to display. 

The ones that do not play (info according to ffprobe) are showing a distorted green screen, or blank (screenshot below):
Video: h264 (High 10) ([27][0][0][0] / 0x001B), yuv420p10le, 640x360, 30 fps, 30 tbr, 90k tbn, 60 tbc

Ones that play (info according to ffprobe):
Video:  h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 640x360, 30 fps, 30 tbr, 90k tbn, 60 tbc

Only Android is broken. I am using exoplayer. IOS is fine. The video is also fine when i play it on <video> on HTML web.

My command during the ffmpeg 
```
ffmpeg(file.path)
      .addOption('-hls_time', 10)
      .addOption('-hls_list_size', 0)
      .addOption('-f', 'hls')
      .addOption('-format', 'yuv420p')
      .addOption('-preset', 'fast')
```

Any recommendations?

Green screen distortion example
![image](https://user-images.githubusercontent.com/35584085/142867994-041db236-fb60-4797-93eb-914b292061d8.png)

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

 "react-native-video": "5.0.1",
  "react-native": "0.63.3",

React native info output:

```bash
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 31.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.6 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.14.0 
    react: ^17.0.1 => 17.0.2 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by nabilfreeman** [comment]
I also have this problem with videos converted from `.mov` (screen recordings) to .mp4 using:

```
for file in ./*.mov; do ffmpeg -i "$file" -c:v libx264 -preset slow -crf 23 -c:a aac -b:a 128k "${file%.mov}.mp4"; done 
```

Videos are fine on iOS. Looking for a more stable codec for Android
