### ISSUE TITLE
Exoplayer config not working

### ISSUE THREAD

**Issue by tackanoway35** [TheWidlarzGroup/react-native-video#2542]
# Bug
I want to use Exoplayer's property "disableFocus"
I configured follow Readme but Exoplayer is not configured, MediaPlayer still is used

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer
## Environment info

React native info output:

```bash
React native: 0.63.2
```

Library version: 5.1.1

## Steps To Reproduce

1. Config react-native-config.js
 dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir:
            '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
2. Config settings.gradle
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
## Expected behaviour

1. Exoplayer is used

**Comment by tackanoway35** [comment]
Here is my code after configuring exoplayer. I can't see exoplayer java code
<img width="317" alt="Screen Shot 2021-11-24 at 14 48 02" src="https://user-images.githubusercontent.com/17925217/143199079-ae050458-a863-4635-9714-4bf5643adf7f.png">

**Comment by FrailWords** [comment]
Try moving the configuration after the `include :app` line in `settings.gradle`.  This worked for me.  Something like - 

```
include ':app'
include ':react-native-video'
project(':react-native-video').projectDir = file('../node_modules/react-native-video/android-exoplayer')
```

in addition to the other changes for adding to `app/build.gradle` - 

`implementation project(path: ":react-native-video")` in the `dependencies` section.

And in the `MainApplication.java`, make sure you've added the react video package - 

```
        @Override
        protected List<ReactPackage> getPackages() {
            List<ReactPackage> packages = new PackageList(this).getPackages();
            packages.add(new ReactVideoPackage());
            return packages;
        }
```

**Comment by yasir-syed** [comment]
@tackanoway35  any luck , I am facing same issue, tried @FrailWords ' s steps, still no luck ,  my app always gets crashed, nothing in logs

**Comment by SMhdAsadi** [comment]
No need to use react-native-config.js anymore. Just follow the installation guide on [README](https://github.com/react-native-video/react-native-video#Android-installation).

If your app crashes after using ExoPlayer, maybe this is because another library uses some other version of ExoPlayer. Use [Flipper](https://fbflipper.com/) to see why your app crashes.

**Comment by yasir-syed** [comment]
@SMhdAsadi thanx man, but the problem was bufferConfig, i think this property is not supported, removing that worked.

 bufferConfig={{
              minBufferMs: 1000,
              maxBufferMs: 5000,
              bufferForPlaybackMs: 250,
              bufferForPlaybackAfterRebufferMs: 5000,
              }}
