### ISSUE TITLE
Video stopped working after sometime in android react native video

### ISSUE THREAD

**Issue by rishavpathania** [TheWidlarzGroup/react-native-video#2547]
Hi,
I am using react-native-video, after upgrading it to 5.2.0 the video stopped working after some time in android. we have integrated it with hls video streaming. So if i wait for exactly 6-7 minutes the video started working itself and even if I restart the app the video player starts working.

**Comment by wesbelonci** [comment]
mesmo problema. alguma solução?

**Comment by wesbelonci** [comment]
same problem. Any solution?

**Comment by mzyisbest** [comment]
+1

**Comment by rishavpathania** [comment]
working fine after degarding to 5.1.1

**Comment by luke-ringier** [comment]
+1 same problem in our app. When can we expect a fix? We cannot downgrade, because the previous version lacks some other functionality.

**Comment by rishavpathania** [comment]
> +1 same problem in our app. When can we expect a fix? We cannot downgrade, because the previous version lacks some other functionality.

Hi, can you please elaborate what functionality is lacking in pervious version
