### ISSUE TITLE
Can not play .mov or .mp4 urls, *sometimes*

### ISSUE THREAD

**Issue by deniswells59** [TheWidlarzGroup/react-native-video#255]
I'm using the component in one view to play a video from a .mp4 url. Also from a .mov filepath in the tmp directory. But on a large feed it won't display either a .mov or .mp4 url. I'm not receiving any errors, but with no 'resizeMode' prop, and the height and width set, I get a black box. Otherwise, it is blank.

Right now the <Video /> component (that doesn't work) is nested three components deep. Including a <ListView />, then a <ScrollView />, and then another <ListView /> that renders each row as a video component. Not sure if that's relevant, but it's the only distinction from the functioning use cases.

**Comment by ndao** [comment]
I am also trying to load a a .mp4 URL, also getting a black box when width & height are set. In addition, i have an error that doesn't tell me anything.

![image](https://cloud.githubusercontent.com/assets/8940740/16890373/9605bd72-4aa2-11e6-943e-2d10099b02da.png)

**Comment by deniswells59** [comment]
I ended up using [Cloudinary](http://cloudinary.com/) to just convert my videos to a gif. Although, I did have a different view that rendered a picture-in-picture of two mp4's on top of each other, playing in sync. I'm not sure why it worked there as opposed to where I was just receiving a black screen.

**Comment by arjunsss** [comment]
I'm running into the same issue at the moment. I'm getting a black box for both remote as well as local MP4. Any resolution on this one ?

**Comment by ndao** [comment]
@arjunsss, found a solution. checkout #275

**Comment by uc-asa** [comment]
How can I play youtube, Vimeo or any embedded video using react native video. Any idea?

**Comment by gauravsbagul** [comment]
> How can I play youtube, Vimeo or any embedded video using react native video. Any idea?

hey, hi, did you find any solution for this?

**Comment by dushmantha** [comment]
Did you find solution?
