### ISSUE TITLE
[Android] exoplayer-2.13.2.pom is disappear in maven repository

### ISSUE THREAD

**Issue by jane00700** [TheWidlarzGroup/react-native-video#2553]
# Bug

Could not find com.google.android.exoplayer:exoplayer:2.13.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom

## Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info
"react-native": "0.66.3"
"react-native-video": "^5.2.0"

**Comment by yahacom** [comment]
same issue

**Comment by kyle-belle** [comment]
Damn. Same here. No solutions yet? i tried updating the repo to 2.16.1 but that comes with other issue:

`
import com.google.android.exoplayer2.video.VideoListener;
                                          ^
  symbol:   class VideoListener
  location: package com.google.android.exoplayer2.video
C:\Users\User 1\Documents\Pregame\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ExoPlayerView.java:217: error: cannot find symbol
    private final class ComponentListener implements VideoListener,
                                                     ^
  symbol:   class VideoListener
  location: class com.brentvatne.exoplayer.ExoPlayerView
C:\Users\User 1\Documents\Pregame\node_modules\react-native-video\android-exoplayer\src\main\java\com\brentvatne\exoplayer\ReactExoplayerView.java:33: error: cannot find symbol
import com.google.android.exoplayer2.ExoPlayerFactory;
  .... many more errors below                                  ^
  `

**Comment by kyle-belle** [comment]
Found a solution that builds. 
Go to file: node_module/react-native-video/android-exoplayer/build.gradle

change all references of 2.13.2 to 2.13.3

i recommend making a note of this in case you are doing the project on other computers as well.

Also Is there a way to override this with editing the node_module contents? i'm not too familiar with android/gradle build system.

**Comment by kyle-belle** [comment]
i see a pull request which already makes this fix. It  would be nice if someone accepts it

**Comment by enigmablue** [comment]
same +1

**Comment by dmydry** [comment]
+1

**Comment by cryptic-dev** [comment]
> Found a solution that builds. Go to file: node_module/react-native-video/android-exoplayer/build.gradle
> 
> change all references of 2.13.2 to 2.13.3
> 
> i recommend making a note of this in case you are doing the project on other computers as well.
> 
> Also Is there a way to override this with editing the node_module contents? i'm not too familiar with android/gradle build system.

thanks alot

**Comment by amithrai-trane** [comment]
+1

**Comment by geakk** [comment]
+1

**Comment by AidenMontgomery** [comment]
Thanks for the help, this seems to have made the build error go away.

> Also Is there a way to override this with editing the node_module contents? i'm not too familiar with android/gradle build system.

There is a tool called [patch-package](https://github.com/ds300/patch-package)

Add it as a dev dependency. `npm install --dev patch-package`
Make your changes to the package in _node_modules_
Record the patch `npx patch-package react-native-video`
To make sure that the patch is applied every time packages are installed add a post install script in _package.json_
 ```
 "scripts": {
 +  "postinstall": "patch-package"
 }
```

**Comment by geakk** [comment]
Yup, I second on that! Very useful tool! :) 

> Thanks for the help, this seems to have made the build error go away.
> 
> > Also Is there a way to override this with editing the node_module contents? i'm not too familiar with android/gradle build system.
> 
> There is a tool called [patch-package](https://github.com/ds300/patch-package)
> 
> Add it as a dev dependency. `npm install --dev patch-package` Make your changes to the package in _node_modules_ Record the patch `npx patch-package react-native-video` To make sure that the patch is applied every time packages are installed add a post install script in _package.json_
> 
> ```
> "scripts": {
> +  "postinstall": "patch-package"
> }
> ```

**Comment by freeboub** [comment]
already fixed in this PR: https://github.com/react-native-video/react-native-video/pull/2317
@hueniverse You can close this ticket
