### ISSUE TITLE
Dolby Atmos not working on iPhones using iOS 15 

### ISSUE THREAD

**Issue by ericlifs** [TheWidlarzGroup/react-native-video#2554]
# Bug
After we upgraded our iPhone devices to the latest iOS 15, we noticed that the Dolby Atmos feature stopped working. This feature is working perfectly on iPad devices using iOS 15 and even on iPhone devices that are using a previous iOS (14.7 for example).

There are two different possible outcomes audio wise:
* Purely static audio => **Non Atmos audio**
* Two steps static audio that alternate each 1 second => **Atmos audio**

The expected behavior is to get the latter on all iPhone devices (that have this feature enabled like iPhone X, 11,  12, 13) regardless of the iOS they are using.

## Platform
Which player are you experiencing the problem on:
* iOS 15
* iPhone X and above

## Reproducible sample code
```
const { width } = Dimensions.get('window');

const App = () => {

  return (
    <Video
        style={{ width, height: (width * 9) / 16 }}
        source={{
          uri: 'https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.5/Test_Signals/muxed_streams/HLS/Manifest_fMP4/Audio_ID_720p_50fps_h264_special_6ch_640kbps_ddp_joc.m3u8',
        }}
        muted={false}
        paused={false}
        repeat
     />
  )
}
```

## Video sample
You can use the following asset for testing https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.5/Test_Signals/muxed_streams/HLS/Manifest_fMP4/Audio_ID_720p_50fps_h264_special_6ch_640kbps_ddp_joc.m3u8

**Comment by Fedeorlandau** [comment]
I'm able to replicate this. Thank you for raising this bug.

**Comment by Fedeorlandau** [comment]
We found out that this is an iOS 15 issue not related to react-native-video. People at Apple broke spatial audio even in safari.

We've raised a bug report and sent it their way.

**Comment by Fedeorlandau** [comment]
PR: https://github.com/valtech-sd/react-native-video/pull/11
