### ISSUE TITLE
Terminating app on ios due to uncaught exception nil string parameter

### ISSUE THREAD

**Issue by Shahrukh0396** [TheWidlarzGroup/react-native-video#2560]
what can we do for remote urls?? i am rendering remote videos.

_Originally posted by @Shahrukh0396 in https://github.com/react-native-video/react-native-video/issues/316#issuecomment-996718803_

**Comment by arvind-inasquare** [comment]
you should check the url. It should not have any spaces.

in my case a there were a couple spaces in the URL from the API which caused this issue in IOS only not on android.

I hope this helps you.
