### ISSUE TITLE
Video doesn't show controls when it is used inside a modal

### ISSUE THREAD

**Issue by SandipJawaleRN** [TheWidlarzGroup/react-native-video#2563]
### Current behavior

Place Video inside Modal

### Reproduction steps

Play video inside Modal with controls

### Expected behavior

Video controls play, seek, etc needs to show on top of modal

### Platform

* Android MediaPlayer

### Video sample

Controls are rendering behind modal
![Untitled](https://user-images.githubusercontent.com/94618389/147272337-fcaf76a0-a3a3-456b-b1c8-dcf819662866.png)

**Comment by SandipJawaleRN** [comment]
> 

![image](https://user-images.githubusercontent.com/94618389/147337315-98325ec1-7f2b-4650-85fe-98298af95209.png)
problem with only Android media player not with ExoPlayer

**Comment by yorickshan** [comment]
same issue

**Comment by yorickshan** [comment]
any solution？

**Comment by yorickshan** [comment]
**use ExoPlayer**

As of now ExoPlayer is not autolinked with react-native-video. To link it with your project and use it, create a file named react-native.config.js in your project root. Then add the following code in the file:

module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer'
        }
      }
    }
  }
}

reference: https://stackoverflow.com/questions/59542183/use-exoplayer-in-react-native

**Comment by yorickshan** [comment]
use ExoPlayer

As of now ExoPlayer is not autolinked with react-native-video. To link it with your project and use it, create a file named react-native.config.js in your project root. Then add the following code in the file:

`module.exports = {
dependencies: {
'react-native-video': {
platforms: {
android: {
sourceDir: '../node_modules/react-native-video/android-exoplayer'
}
}
}
}
}`

reference: https://stackoverflow.com/questions/59542183/use-exoplayer-in-react-native

**Comment by yorickshan** [comment]
**use ExoPlayer**

As of now ExoPlayer is not autolinked with react-native-video. To link it with your project and use it, create a file named react-native.config.js in your project root. Then add the following code in the file:

```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer'
        }
      }
    }
  }
}
```

reference: https://stackoverflow.com/questions/59542183/use-exoplayer-in-react-native
