### ISSUE TITLE
Video does not hide status bar completely, annoyingly obstructs view on Android

### ISSUE THREAD

**Issue by pateljoel** [TheWidlarzGroup/react-native-video#2564]
When playing a fullscreen video on Android, the status bar gets in the way and does not go away.

<img width="852" alt="status_bar_still_there_fullscreen" src="https://user-images.githubusercontent.com/64401775/147278372-fee53268-5b81-4a81-a94d-521facd5971b.png">

**Comment by orange-brother** [comment]
Should hide statusbar manually 

`import {
  StatusBar,
} from 'react-native';`

`StatusBar.setHidden(false);`

**Comment by pateljoel** [comment]
Thanks! @patissier-boulanger This works although it should be:

```js
StatusBar.setHidden(true)
```

**Comment by mkbhdana** [comment]
I am setting statusbar hidden using useEffect and it works. But i am facing an issue if i keep repeat true and when video ends then statusbar stays hidden but if repeat is false and when video gets end statusbar stays visible always.

**Comment by freeboub** [comment]
@mkbhdana open a new ticket if you reproduce it on V6 please ! It seems that your use case is easier to understand. Thanks

**Comment by kevin-roan** [comment]
> I am setting statusbar hidden using useEffect and it works. But i am facing an issue if i keep repeat true and when video ends then statusbar stays hidden but if repeat is false and when video gets end statusbar stays visible always.

show the statusbar when component unmounts,
