### ISSUE TITLE
Video not showing on Android 12

### ISSUE THREAD

**Issue by fengmin2611** [TheWidlarzGroup/react-native-video#2565]
# Bug
I have tested and found that the video shows fine on Android 11 and earlier. But with Android 12 all is just a blank screen.
Anyone encountered this problem yet? 
Thank you

Media Codec :  AAC, MPEG-4 Video
React-native : 0.59.7
Device : Pixel 
Logcat : 01-04 10:41:45.556   463  7453 E NuPlayerDecoder: Failed to create video/mp4v-es decoder
01-04 10:41:45.557   463  7444 E NuPlayer: received error(0x80000000) from video decoder, flushing(0), now shutting down

**Comment by Snowcrash5** [comment]
I saw a similar error when I tried playing a video from local path

```java.io.IOException: setDataSourceFD failed.: status=0x80000000```

This is running on old android but API level is 31.

in ReactVideoView line 257
`    public void setSrc(final String uriString, final String type, final boolean isNetwork, final boolean isAsset, final ReadableMap requestHeaders, final int expansionMainVersion, final int expansionPatchVersion) {
`


In line 306, a call to `setDataSource(uriString);`

This flows through `ScalableVideoView` into a call to android `MediaPlayer.java` at line 1174:
`    private void setDataSource(String path, Map<String, String> headers, List<HttpCookie> cookies)`

But this function is 
`@UnsupportedAppUsage(maxTargetSdk = Build.VERSION_CODES.R, trackingBug = 170729553)`

Maximum version is `VERSION_CODES.R`, Android 11..

When debugger is attached, instead of going into the intended function, it does into `MediaPlayer.java` at line 1056:
`    public void setDataSource(@NonNull Context context, @NonNull Uri uri,
            @Nullable Map<String, String> headers, @Nullable List<HttpCookie> cookies)`

and fails as no URI is passed...
```throw new NullPointerException("uri param can not be null.");```

**Comment by mikeshuttjuvo** [comment]
Same issue here, received the Android 12 update yesterday and now I am unable to view some videos on a Samsung S21.  Same videos were viewable on this same device before the update.  Exception is

com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.sec.mpeg4.decoder, Format(1, null, null, video/mp4v-es, null, -1, null, [1080, 1920, 14.99954], [-1, -1])

**Comment by lillian56** [comment]
Same issue here。
 We tested several android 12 machines, and only one of them worked properly。
Media Codec : AAC, MPEG-4 Video
React-native: 0.66.0
Device : Pixel、Xiaomi mix4

We can only hear the sound, can't see the picture。

**Comment by sharan-SKY** [comment]
Hi there, We are facing a similar issue when users upgrade to android 12. Has there been a resolution on this yet?

**Comment by CinerBilgiGrubu** [comment]
I have same issue. When I play m3u8 video on Android 12, I observe only sound and black screen. I run on m1 processor arm64 macbook pro.

**Comment by sedatb** [comment]
I have same issue. When I play m3u8 video on Android 12, I observe only sound and black screen. I work on m1 processor arm64 macbook pro. Mp4 videos are working fine.

**Comment by shohan177** [comment]
We are facing a similar issue when install apk in android version 12 devices, not showing any videos . Has there been a resolution on this yet?. it's very important for us

**Comment by aktaruzzamanjoti97** [comment]
I have same similar issue. While install apk in android version 12 devices, It has not shown any videos. Please I need solution..

**Comment by alaminhossain171** [comment]
In android 12 video not working. Any solution yet?

**Comment by A-Kaiyum** [comment]
I am also facing a similar issue when install apk in android version 11 .

**Comment by Apurbo-cse** [comment]
I have same problem. Any Solution plz??????????

**Comment by parthatfp** [comment]
I face same problem in some days ago. Still I can't get good solution.

**Comment by MonirHossen** [comment]
please solve this issue as only as possible.

**Comment by Arafat7616** [comment]
I am using android version 12 but after installing apk it doesn't work.

**Comment by imdadulhaque1** [comment]
I have faced the same issue on Android version 12. Is there any solutions  to fixed this issues? Please confirm us, otherwise We will used another npm packages to complete the project.

**Comment by HessiPard** [comment]
Same issue here

**Comment by ZhminkoRoman** [comment]
The same issue. Works fine on iOS and in developer mode for Android, but get black screen on release mode, but If you use http protocol of video, please, add android:usesCleartextTraffic="true" to your AndroidManifest.xml

**Comment by shohan177** [comment]
[ZhminkoRoman](https://github.com/ZhminkoRoman)  thanks it's works

**Comment by Mani1124** [comment]
Same issue here

**Comment by freeboub** [comment]
@Mani1124  we need more information, this ticket seems to be closed without any 'real' issue in the package...

**Comment by ahsanbhatti98** [comment]
I'm facing this issue in pixel and motorola devices with OS 12 and above. Only audio is playing.And also onReadyForDisplay callback doesn’t works too.

**Comment by stas44812** [comment]
> I'm facing this issue in pixel and motorola devices with OS 12 and above. Only audio is playing.And also onReadyForDisplay callback doesn’t works too.

hey, did you figured out the solution? facing the same issue on the 'Moto g play 2023 (os. 12) physical', but works perfectly on the google pixel emulator.

**Comment by PrudhviBanki** [comment]
why this issue closed android:usesCleartextTraffic="true" not working debug working release getting black screen still

**Comment by freeboub** [comment]
> why this issue closed android:usesCleartextTraffic="true" not working debug working release getting black screen still

It is a 3yo ticket ...
