### ISSUE TITLE
Unable to update textTracks dynamically

### ISSUE THREAD

**Issue by Sri-A** [TheWidlarzGroup/react-native-video#2568]
# Bug

If we have textTracks loaded dynamically after the video player is loaded the text tracks are not showing up. If we redraw video by changing the URL(By appending some queryparams to url), it does re-render and showing the text tracks, but this method causing the video to re-render. Is there anyway to have dynamic text tracks support?

## Platform
iOS

Which player are you experiencing the problem on:
* iOS

## Environment info
React native info output:

```bash
info
  React Native Environment Info:
    System:
      OS: macOS 11.6.2
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 16.98 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      npm: 7.6.3 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.3, 30.0.1, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

Library version: 4.4.4

## Steps To Reproduce

1. Load the video player with some video url without any text tracks or empty array for text tracks
2. After sometime update text tracks only without updating video url

## Expected behaviour

Should able to see the text tracks loaded after update

**Comment by december1990** [comment]
@hueniverse how did you solve this problem? I experience the same issue, I thought that parent component was causing the issue but this happened for a memoized hardcoded textTracks array!

**Comment by freeboub** [comment]
> @hueniverse how did you solve this problem? I experience the same issue, I thought that parent component was causing the issue but this happened for a memoized hardcoded textTracks array!

It is not possible to change them dynamically during playback. It is a exoplayer/avplayer limitation.
