### ISSUE TITLE
Video waiting for download entire video file. Can we make like instead start after just download few frames.

### ISSUE THREAD

**Issue by HirenTariwala** [TheWidlarzGroup/react-native-video#2569]
# Bug

 I've notice that player wait to download entire video once it is downloaded it start playing video that will take too much time.

is there any way to start video after just download few frames ?

**Comment by chenshaxuanjing** [comment]
+1

**Comment by MagicAce1988** [comment]
for sure I am wondering the same thing...it takes so long

**Comment by HirenTariwala** [comment]
Yes @MagicAce1988 bcoz it wait to download all frames instead start after just download few frames.

**Comment by thiendt1** [comment]
+1

**Comment by khlling** [comment]
A common solution is to use HTTP Live Streaming or HLS. This solution slices your video into 10s (for example) chunks which are downloaded sequentially and therefore gives you a buffering effect when watching a video. You will need to:

1. Convert you video file e.g. mp4 into .m3u8 (playlist file) and .ts
2. Host these files together on your storage solution of choice e.g. AWS S3
3. Point react-native-video at the .m3u8 file url

**Comment by HirenTariwala** [comment]
@khlling Yes looking for the same solution right now I've sliced video into multiple files from but to merge on front end again again an issue for me so let me try this as well thanks for help

**Comment by ahmedelsayed11** [comment]
> from

You mean if we converted the mp4 file to m3u8 and save to and give the url to react-native-video component it will solve the problem ?

**Comment by Saad-Bashar** [comment]
Same question :(

**Comment by khlling** [comment]
> > from
> 
> You mean if we converted the mp4 file to m3u8 and save to and give the url to react-native-video component it will solve the problem ?

Exactly 👍. You can use something like ffmpeg to do the conversion (https://ffmpeg.org/).
