### ISSUE TITLE
RN: 0.66.4 can't build react-native-video

### ISSUE THREAD

**Issue by VegaChen-BadtzMaru** [TheWidlarzGroup/react-native-video#2571]
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

**Comment by dibeling** [comment]
Yes, for a while the fix here worked: https://github.com/react-native-video/react-native-video/pull/2462

But, no longer seems to be working as jCenter() is down. A solution to this would be great

**Comment by edmataDotDev** [comment]
Any update for this? I'm getting the same problem.

**Comment by edmataDotDev** [comment]
Hey, there is some light at the end, check this comment https://github.com/yqritc/Android-ScalableVideoView/issues/52#issuecomment-1013824489

**Comment by dibeling** [comment]
Yep, this seems to work.

**Comment by hellogbg** [comment]
Didn't work for me.

**Comment by rastapasta** [comment]
> Didn't work for me.

@avenyproduction didn't work for me until a ```gradlew clean``` was commanded - good luck!
