### ISSUE TITLE
Issues with Video Playback on Android

### ISSUE THREAD

**Issue by MarkoAndrew** [TheWidlarzGroup/react-native-video#2572]
Hey guys,

I've added **react-native-video** to my React Native project and I've created a separate component which would handle Video Playback. There are multiple Videos within project that have to be played sequentially (I can't have a single Video file as User needs to have control over Videos by using Previous/Next/Pause buttons that have been added separately). Basically, the Video plays with component render, and then when it's over, the next Video gets loaded automatically (or the next one starting when User touches the 'Next' button) - the **source** of the video getting updated when this happens. 
The issue I'm having is that Videos are lagging when they switch (having delay when switching Videos - previous Video getting frozen until the next one gets loaded) - this happening **only on Android** (it works properly on iOS). These Videos don't have large filesizes (all videos being under 1Mb). 
I've done some research and I've configured it to use ExoPlayer instead (based on [this](https://github.com/react-native-video/react-native-video/issues/2255#issuecomment-752655803)) and now Videos are no longer lagging and they switch properly. However, now there is another issue - when Video source gets updated, there is a black background appearing for a second (like a blink). It seems to be the ShutterView from ExoPlayer. Even if I set **hideShutterView={true}**, I still get this black background when Videos switch.

```
react-native-video: 5.2.0
react-native-cli: 2.0.1
react-native: 0.63.3
```

I would like to ask you - is there any workaround for this ? What could I do in my case ?
Thank you in advance!

**Comment by GustavPS** [comment]
Freel free to let me know if you solve this, have a similar issue

**Comment by AnandKumar1989** [comment]
i set  playInBackground={true} in my react native android app. but it is not playing the video in background. @[MarkoAndrew](https://github.com/MarkoAndrew) please let me know user configuration.

Thanks
