### ISSUE TITLE
iOS DRM Capabilities

### ISSUE THREAD

**Issue by jspizziri** [TheWidlarzGroup/react-native-video#2573]
# Feature Request

I'm a complete n00b when it comes to DRM and AVPlayer so please forgive my ignorance and thanks for all the work on this package! 

Succinctly: Is it possible to support ClearKey encryption on iOS? I've done some poking around at the AVPlayer documentation (which is scant in my opinion) and I couldn't find any good documentation on DRM in general but specifically nothing about ClearKey.

If it's possible I'd happily jump all over the implementation.

Thanks again!

**Comment by jspizziri** [comment]
Please don't close! I'm still interested but haven't heard anything.

**Comment by hueniverse** [comment]
Unfortunately I can't help you with this question/request and no one else has responded to it in 3 months which suggests we don't have the resources needed to address it. I'll leave it open for a bit longer but will close if no one else steps forward with a suggestions. Sorry but that's the reality of community driven open source...
