### ISSUE TITLE
Play .m3u8 video from a location.

### ISSUE THREAD

**Issue by puneetkansal04** [TheWidlarzGroup/react-native-video#2574]
i am using react-native-video.
And i am saying .m3u8 file. But it just saved a text file. So i need to know how can i save full .m3u8 stream and play it from a local location.

**Comment by LordNahi** [comment]
I think I can interpret what you want, and I think you'll want to study up on the [FFMPEG api](https://www.ffmpeg.org/)

Which lets you do stuff like this `ffmpeg -i link/to/video.m3u8 -c copy -bsf:a aac_adtstoasc output.mp4`

Then, assuming you'd like to integrate this with your app, you might want to try something like [this](https://github.com/tanersener/ffmpeg-kit)

**Comment by puneetkansal04** [comment]
Hi @LordNahi  Let me know if we can connect so that i can explain you what i want. I want to Save offline videos in the app and want that will play only from the generated app.
