### ISSUE TITLE
Video Quality Options

### ISSUE THREAD

**Issue by nikunjdhamelia** [TheWidlarzGroup/react-native-video#2576]
### Platform
Which player are you experiencing the problem on:
* iOS
* Android

How to set video quality options on android and IOS on both sides?

**Comment by luis-filipe-tc** [comment]
You can't. React-native-video doesn't have this feature. What you can do is change the quality changing the URL.

**Comment by CastFX** [comment]
My company had the same problem and we fixed by forking react-native-video-controls and adding a togglable option to set the video quality.
https://github.com/corsi-it/react-native-video-controls

**Comment by FazilMuhammed** [comment]
@CastFX hello brother..
 I need set video quality option in iOS can you please help me.or can you share code ??

how to play video with sending prop videoSources and videoResolution from parent component
can you give one example please

**Comment by CastFX** [comment]
```
<VideoPlayer
          skipTime={0}
          toggleResizeModeOnFullscreen={false}
          controlAnimationTiming={200}
          doubleTapTime={250}
          seekColor={Colors.red}
          skipIconColor={Colors.black}

          onVideoResolutionChange={res => console.log(res)}
          videoResolution={'480p'}
          videoSources={[{videoResolution: '480p': uri: 'uri_sd'}, {videoResolution: '720p': uri: 'uri_hd'}, {videoResolution: '1080p': uri: 'uri_fhd'}]}

          rates={[1, 1.25, 1.5, 2]}
          rate={1}
          controls={false}
          ignoreSilentSwitch={'ignore'}
          disableFocus={false}
          progressUpdateInterval={1000}
          fullscreenAutorotate={true}
          fullscreenOrientation={'all'}
          automaticallyWaitsToMinimizeStalling={true}
          preventsDisplaySleepDuringVideoPlayback={true}
          playWhenInactive={false}
          resizeMode="contain"
        />
```

This is how we use it, videoSources requires an array of objects:
`[{videoResolution: '480p': uri: 'uri_sd'}, {videoResolution: '720p': uri: 'uri_hd'}, {videoResolution: '1080p': uri: 'uri_fhd'}]`

videoResolution props is the initial resolution. Internally it will be changed if you tap on the button and you will be notified if you subscribe to `onVideoResolutionChange`

**Comment by FazilMuhammed** [comment]
Thank you :)

**Comment by Melber17** [comment]
@CastFX in api we dont have field **videoSources**. Where did you get that?

**Comment by EugeniuszX** [comment]
@CastFX I didnt find field **videoSource**. Where can I find it?

**Comment by CastFX** [comment]
@Melber17
There is no **videoSource**, you need to use videoSource**s** like this

`videoSources={[{videoResolution: '480p': uri: 'uri_sd'}, {videoResolution: '720p': uri: 'uri_hd'}, {videoResolution: '1080p': uri: 'uri_fhd'}]}`

**Comment by EugeniuszX** [comment]
@CastFX  my bad, thank you!

**Comment by EugeniuszX** [comment]
@CastFX but in any api I dont see field **videoSources**. Can you share link?

**Comment by CastFX** [comment]
@Melber17 
You need to use our fork @ https://github.com/corsi-it/react-native-video-controls

You can see the props used in defaultProps @ https://github.com/corsi-it/react-native-video-controls/blob/master/VideoPlayer.js
