### ISSUE TITLE
video still paly when page exit in ios ,  react native 0.61 

### ISSUE THREAD

**Issue by lbyzju** [TheWidlarzGroup/react-native-video#2584]
# Bug
when navigate to another page, video still play .  android is ok , ios is bad

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:
System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.69 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 26.0.1, 28.0.3, 29.0.3, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4720617
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by vargajacint** [comment]
Interesting bug. Temp solution is check the screen focused state with `useIsFocused` hook. If it's not focused render null.

Something similar
`
const isFocused = useIsFocused();
if(!isFocused) return null
`

**Comment by dwamianm** [comment]
@lbyzju ... if you are still having issues with this and the focus checks didn't work for you as they didnt for me, I solved this by awaiting the state update in a method and then navigating after that

example
<pre>
  const handleGoBack = useCallback(async () => {
    await setShowVideo(false); //this generally shouldn't work but was the ONLY fix that addressed this issue
    navigation.goBack();
  }, [navigation]);
</pre>

**Comment by hueniverse** [comment]
Close dur to lack of steps to reproduce. If you are able to submit a sample app where we can see this issues, we can revisit. You can use https://github.com/hueniverse/react-native-video-test as a template by forking it and making changes.

**Comment by rdjuric** [comment]
You need to take care of mounting/unmounting the `<Video>` component yourself. Depending on the way your navigation works, the current screen might not unmount when navigating to a different one. 

If you use `react-navigation`, the `useFocusEffect ` hook might come in hand. I use something similar to this in my app
```
	useFocusEffect(() => {
		// Resume the video when this screen is focused
		if (ref.current) ref.current.setNativeProps({ paused: false });
		return () => {
                       // Pauses the video when this screen is unfocused
			if (ref.current) ref.current.setNativeProps({ paused: true });
		};
	});
```

**Comment by alexfoxy** [comment]
I have fixed with this component:
```
import React from 'react'
import RNVideo from 'react-native-video'

let ref: RNVideo | null

const Video = (props: RNVideo['props']) => {
  return <RNVideo
    ref={r => {
      if (!r) {
        // @ts-ignore setNativeProps does not exist on 'Video' .. but it does!
        if (ref?.setNativeProps) ref.setNativeProps({ paused: true })
      } else {
        ref = r
      }
    }}
    {...props}
  />
}

export default Video
```

**Comment by dmarcogabriel** [comment]
I've made a work around here that worked for me: https://github.com/react-native-video/react-native-video/issues/2448#issuecomment-1481670779
