### ISSUE TITLE
Can I use react-native-video in Expo Bare project?

### ISSUE THREAD

**Issue by joaolnpr** [TheWidlarzGroup/react-native-video#2585]
# Feature Request

Can I use react-native-video in Expo Bare project?

## Why it is needed

N/A

## Possible implementation

N/A

### Code sample

N/A

**Comment by gufril15** [comment]
@joaolnpr Have you tried using `react-native-video` with EAS Build?

**Comment by Aaron46** [comment]
Yes - but what's wrong with expo-av?
