### ISSUE TITLE
Jest unit tests gives "TypeError: Cannot read property 'Constants' of undefined"

### ISSUE THREAD

**Issue by acceh** [TheWidlarzGroup/react-native-video#2591]
# Bug

When writing tests for my components with react-native-video i am getting an error saying "TypeError: Cannot read property 'Constants' of undefined". Everything works on both Android and iOS when running normally, the problem only occurs when trying to run unit component tests with jest.

## Platform

Locally with Jest.

Which player are you experiencing the problem on:

None.

## Environment info

React native info output:

System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/{USER}/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 28.0.3, 30.0.2, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.0

## Steps To Reproduce

1. Run a unit test with jest incorporating a component using react-native-video.
2. Test fails with "TypeError: Cannot read property 'Constants' of undefined"

## Expected behaviour

1. Run a unit test with jest incorporating a component using react-native-video.
2. Test passes

## Reproducible sample code

`
describe('Video', () => {
  it('should render a video-view', () => { 
    const { getByTestId } = render(
      <VideoView
        videoUrl={mockUrl}
      />
    )
    expect(getByTestId("video-view")).toBeTruthy()
  })
})
`

## Video sample
---

**Comment by dilarakirn** [comment]
I think you should mock the library with `jest.mock('react-native-video', () => 'Video');`

**Comment by acceh** [comment]
That resolved it! Thanks!
