### ISSUE TITLE
Video starts playing without sound if on the device mute mode

### ISSUE THREAD

**Issue by Rostyslow** [TheWidlarzGroup/react-native-video#2598]
# Bug

Is it possible to override the silent mode on the device and start playing video with sound?

## Platform iOS and Android

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

Library version: 5.2.0

**Comment by RichardKruemmel** [comment]
You can set the prop ignoreSilentSwitch to "ignore". I have only tested it for iOS so far.
<Video ignoreSilentSwitch="ignore" />
