### ISSUE TITLE
Cannot able to pause the video when switching the stack screen

### ISSUE THREAD

**Issue by prasanthvenkatachalam** [TheWidlarzGroup/react-native-video#2608]
### Current behavior
I am using Flatlist to render multiple videos. when I press the play button, Video starts but I cannot able to get back the player status (whether it's playing or not ). I am using the viewabilityConfig prop of Flatlist to auto-play video. When autoplay began, if I switch to another stack screen I can able to pause the video automatically using paused in Video props. If I press the play button, the video starts playing, but when I switch to another stack screen, I cannot able to pause the video.    

### Reproduction steps
List multiple videos using flatlist and press any video play button and switch the stack screen. Now video still playing 

### Expected behavior
Video needs to be paused after switching the  stack screen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

**Comment by wagmi-admin** [comment]
You can check if the screen is in focus or not. Based on focused screen you can set RNVideo paused flag. 

Link to check about [useFocusEffect](https://reactnavigation.org/docs/use-focus-effect/)
