### ISSUE TITLE
[Android] start called in state 0

### ISSUE THREAD

**Issue by stereodenis** [TheWidlarzGroup/react-native-video#261]
Can't play hls stream
uri: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

```
E/MediaPlayer: start called in state 0
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: Error (-38,0)
```

maybe this can help
@brentvatne http://stackoverflow.com/questions/17724987/android-mediaplayer-error-38-0-stop-called-in-state-0

**Comment by vishalsiddhi** [comment]
Hello @mattapperson ,

Is this fixed or not?

I am getting error when running app on device with low memory.

Currently I had added exception for this.
