### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer:2.13.2

### ISSUE THREAD

**Issue by erfanshekari** [TheWidlarzGroup/react-native-video#2611]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-video@5.2.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-video/android-exoplayer/build.gradle b/node_modules/react-native-video/android-exoplayer/build.gradle
index d005a58..6a9922b 100644
--- a/node_modules/react-native-video/android-exoplayer/build.gradle
+++ b/node_modules/react-native-video/android-exoplayer/build.gradle
@@ -28,7 +28,7 @@ android {
 
 dependencies {
     implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
-    implementation('com.google.android.exoplayer:exoplayer:2.13.2') {
+    implementation('com.google.android.exoplayer:exoplayer:2.13.3') {
         exclude group: 'com.android.support'
     }
 
@@ -37,7 +37,7 @@ dependencies {
     implementation "androidx.core:core:1.1.0"
     implementation "androidx.media:media:1.1.0"
 
-    implementation('com.google.android.exoplayer:extension-okhttp:2.13.2') {
+    implementation('com.google.android.exoplayer:extension-okhttp:2.13.3') {
         exclude group: 'com.squareup.okhttp3', module: 'okhttp'
     }
     implementation 'com.squareup.okhttp3:okhttp:${OKHTTP_VERSION}'
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by aliraza944** [comment]
Solved my issue. Thanks.

**Comment by kimyundunov** [comment]
How to let developers know about this problem?

**Comment by pk936** [comment]
Please tell the solution in steps.

**Comment by stigi** [comment]
The culprit for this is likely that exoplayer 2.13.2 is not available on the maven repo: https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer

2.13.3 is though.

@erfanshekari could you open a PR with that change?

**Comment by pk936** [comment]
Also, the latest version of exoplayer is 2.17.1 which exists. But if you use this version in this file, 

**_/node_modules/react-native-video/android-exoplayer/build.gradle b/node_modules/react-native-video/android-exoplayer/build.gradle_**

then it also will not work.

It seems like react-native-video is written only for 2.13 or lesser version.

**Comment by longb1997** [comment]
thanks, please open a PR

**Comment by adityapatadia** [comment]
It seems there is no need for PR. This file already has 2.13.3 version: https://github.com/react-native-video/react-native-video/blob/master/android-exoplayer/build.gradle

Can you release new version for this package? This is a painful issue.

**Comment by freeboub** [comment]
@hueniverse this ticket can be closed ! :)

**Comment by adityapatadia** [comment]
@hueniverse please also release a new version so this is fixed.

**Comment by hueniverse** [comment]
I'll see if I can do a quick patch.

**Comment by flo-sch** [comment]
Hey, is a 5.2.1 patch still planned?
(The patch-packages hack is still needed until a new version is released)

**Comment by hueniverse** [comment]
Unfortunately no patch is planned. This will have to wait until we have a v6 released due to lack of resources to put together a properly tested branch off 5.2.0. Until then, local patching is the way to go (I am using one myself for my projects).

**Comment by constantinos-yiasemi** [comment]
That solved my issue! Thank you!

**Comment by adityapatadia** [comment]
@hueniverse any timelines on v6? The problem is that patching is fine for testing etc but as part of our product we ask clients to install this package. They going thorough this entire flow is not ideal. Moreover the incremental testing of updating ExoPlayer to a patch version should be minimal. I suggest you consider also making a patch release.

**Comment by hueniverse** [comment]
Probably first cut of a v6 pre-release in 1-2 weeks.

**Comment by mashad6** [comment]
@hueniverse any luck on v6?

**Comment by hueniverse** [comment]
@mashad6 I am no longer involved with the project.

**Comment by mashad6** [comment]
@hueniverse  who else is looking after this now? can you please mention them

**Comment by freeboub** [comment]
I should take the lead, but unfortunately, I have no time available yet ...

**Comment by mashad6** [comment]
Has this been resolved in 5.2.1?

**Comment by freeboub** [comment]
@mashad6 yes

**Comment by Mohsinraza880** [comment]
Media controls are floating on screen on android. Please help me.
