### ISSUE TITLE
Variable version value needs to use double quotes. Fails lint check.

### ISSUE THREAD

**Issue by vincecoleman** [TheWidlarzGroup/react-native-video#2613]
https://github.com/react-native-video/react-native-video/blob/63f12eaed666ebddf9a506889bf99232c2ea6c20/android-exoplayer/build.gradle#L48

**Comment by jackyleehong** [comment]
Issue reproducible starting from v6.0.0-alpha.1 onwards

**Comment by freeboub** [comment]
Here is the patch ! https://github.com/react-native-video/react-native-video/pull/2891/files

**Comment by freeboub** [comment]
Fix will be available in 6.0.0.alpha.4
