### ISSUE TITLE
How can I access embedded subtitles data after the initial load?

### ISSUE THREAD

**Issue by rhd-chris** [TheWidlarzGroup/react-native-video#2617]
Hi,

I am using this library for a stream with embedded subtitles. After finding [this post](https://stackoverflow.com/questions/63897506/react-native-get-available-text-tracks) I found I can access the subtitles data using the onLoad parameter, but since the stream changes programmes, and therefore subtitles, how can I access this data periodically? Or better yet, is there a way to detect a change in the embedded subtitles so I don't need to polling for it?

Any help appreciated!

**Comment by freeboub** [comment]
This is not currently possible.
The fix would be to split onLoad event into 3 different events (audioTracks, textTracks, videoTracks).
And then you wil be able to receive onTextTrackChanged when it is updated

**Comment by freeboub** [comment]
@hueniverse I will propose fix for this issue !

**Comment by ChaTho7** [comment]
> @hueniverse I will propose fix for this issue !

@freeboub Is there any progress about this issue ? Because, i need to get soft subtitles from a mkv file.

**Comment by freeboub** [comment]
@ChaTho7 I will try to open a PR next week !

**Comment by freeboub** [comment]
@ChaTho7 the backport was a little bit more trick than I was expecting ...
here it is for android: https://github.com/react-native-video/react-native-video/pull/2806
Still need to be implemented on ios

**Comment by ChaTho7** [comment]
@freeboub 
I'm able to get the textTracks inside onLoad function right now, thanks for your work. So, is there any way to fetch the texts from that textTrack ? (export as string or etc.)

**Comment by freeboub** [comment]
@ChaTho7 : in this PR: https://github.com/react-native-video/react-native-video/pull/2806 I added new events to notify application that audio/text/video tracks has been updated. You will just need to move the code from onLoad to onAudioTracksChanged.
I implemented it only on android

**Comment by freeboub** [comment]
@ChaTho7 sorry, no, there is no way to retrive the subtitle content in text format (and I think this is not a good idea, it may slow down your app)

**Comment by freeboub** [comment]
I will close this ticket, let's continue in : https://github.com/react-native-video/react-native-video/issues/2683
