### ISSUE TITLE
HLS Playlist issue "Unable to instantiate decoder OMX.MTK.VIDEO.DECODER.AVC"

### ISSUE THREAD

**Issue by pandiarajanvp** [TheWidlarzGroup/react-native-video#2618]
# Bug

## Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.6.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 215.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.4 - /usr/local/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/opt/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 24, 26, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0, 33.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_311 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1. Play HLS playlist in flatlist after 10 to 15 videos its getting error
2. if one video getting error ,upcoming video can't play 

## Expected behavior

1.
3.

## Reproducible sample code

  <Video
                  id={uuid.v4()}
                  ref={ref => {
                    this.video = ref;
                  }}
                  source={{
                    uri:"https://vz-602a2693-e0f.b-cdn.net/c496b51c-8216-4c71-9935-d158caf8a26a/playlist.m3u8"
                  }}
                  style={[styles.fullScreen, {height: '100%'}]}
                  rate={this.state.rate}
                  //paused={this.state.paused}
                  paused={this.state.paused}
                  // useNativeControls
                  volume={this.state.volume}
                  muted={this.state.muted}
                  resizeMode={this.state.resizeMode}
                  onLoad={this.onLoad}
                  onProgress={this.onProgress}
                  progressUpdateInterval={250.0} //IOS
                  onEnd={this.onEnd}
                  onAudioBecomingNoisy={this.onAudioBecomingNoisy}
                  onAudioFocusChanged={this.onAudioFocusChanged}
                  onLayout={
                    this.props.onLayout
                  }
                  repeat={false}
                  fullscreenOrientation="portrait"
                  fullscreen={false}
                  poster={thumbnail}
                  posterResizeMode="cover"
                  controls={false}
                  onError={this.onError}
                  playInBackground={false}
                  disableFocus={false}
                  playWhenInactive={false}
                  onBuffer={
                    this.videoBuffer
                  }
                  reportBandwidth={false}
                  bufferConfig={{
                    minBufferMs: 5000,
                    maxBufferMs: 10000,
                    bufferForPlaybackMs: 2500,
                    bufferForPlaybackAfterRebufferMs: 5000,
                  }}
                />

## Error sample
Video Play Error:  {"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4D401F, 1400000, null, [842, 474, -1.0], [-1, -1]), format_supported=YES", "errorString": "Unable to instantiate decoder OMX.MTK.VIDEO.DECODER.AVC"}}

**Comment by freeboub** [comment]
Mediacodec issues are generally linked to hardware compatibility.
You should check this isuse with an exoplayer sample first.
Can you try ?

**Comment by nikesh8** [comment]
Anyone have found the fix for this issue?

**Comment by rohitsingh2410** [comment]
> # Bug
> ## Platform
> 
> Android
> 
> Which player are you experiencing the problem on:
> 
>     * Android ExoPlayer
> 
> 
> ## Environment info
> 
> React native info output:
> 
> ```shell
> System:
>     OS: macOS 11.6.4
>     CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
>     Memory: 215.01 MB / 16.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.18.1 - /usr/local/bin/node
>     Yarn: 1.22.17 - /usr/local/bin/yarn
>     npm: 8.5.4 - /usr/local/bin/npm
>     Watchman: 2022.01.31.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.2 - /usr/local/opt/ruby/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
>     Android SDK:
>       API Levels: 23, 24, 26, 27, 28, 29, 30, 31
>       Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0, 32.0.0, 33.0.0
>       System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2021.1 AI-211.7628.21.2111.8139111
>     Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_311 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2 
>     react-native: 0.66.3 => 0.66.3 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> Library version: 5.2.0
> ## Steps To Reproduce
> 
>     1. Play HLS playlist in flatlist after 10 to 15 videos its getting error
> 
>     2. if one video getting error ,upcoming video can't play
> 
> 
> ## Expected behavior
> 
> 
> ## Reproducible sample code
> 
> <Video id={uuid.v4()} ref={ref => { this.video = ref; }} source={{ uri:"https://vz-602a2693-e0f.b-cdn.net/c496b51c-8216-4c71-9935-d158caf8a26a/playlist.m3u8" }} style={[styles.fullScreen, {height: '100%'}]} rate={this.state.rate} //paused={this.state.paused} paused={this.state.paused} // useNativeControls volume={this.state.volume} muted={this.state.muted} resizeMode={this.state.resizeMode} onLoad={this.onLoad} onProgress={this.onProgress} progressUpdateInterval={250.0} //IOS onEnd={this.onEnd} onAudioBecomingNoisy={this.onAudioBecomingNoisy} onAudioFocusChanged={this.onAudioFocusChanged} onLayout={ this.props.onLayout } repeat={false} fullscreenOrientation="portrait" fullscreen={false} poster={thumbnail} posterResizeMode="cover" controls={false} onError={this.onError} playInBackground={false} disableFocus={false} playWhenInactive={false} onBuffer={ this.videoBuffer } reportBandwidth={false} bufferConfig={{ minBufferMs: 5000, maxBufferMs: 10000, bufferForPlaybackMs: 2500, bufferForPlaybackAfterRebufferMs: 5000, }} />
> ## Error sample
> 
> Video Play Error: {"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4D401F, 1400000, null, [842, 474, -1.0], [-1, -1]), format_supported=YES", "errorString": "Unable to instantiate decoder OMX.MTK.VIDEO.DECODER.AVC"}}

Did you found any solution?

**Comment by jucoAllison** [comment]
please what is the solution???

**Comment by freeboub** [comment]
please check this thread: https://github.com/react-native-video/react-native-video/issues/2984
