### ISSUE TITLE
All Pixel Devices keep skipping video

### ISSUE THREAD

**Issue by pateljoel** [TheWidlarzGroup/react-native-video#2619]
# Bug

If you play any video on an Android Pixel phone, the video will always keep skipping throughout video playback.

## Platform

Any Google Pixel Phone.

Which player are you experiencing the problem on:

* Android ExoPlayer

Library version: 5.1.1

## Steps To Reproduce

Play any video with React Native Video.

## Expected behaviour

1. Video should play without skipping.

## Reproducible sample code

Any Example

**Comment by priyanu17** [comment]
Happening with me as well

**Comment by priyanu17** [comment]
Any clue how to fix this ?

**Comment by freeboub** [comment]
Not enough info to understand the issue...
