### ISSUE TITLE
Play m3u8 from the local iphone files

### ISSUE THREAD

**Issue by puneetkansal04** [TheWidlarzGroup/react-native-video#2620]
I want to save video in the mobile phone then i want to play this video. So i wanted to know that how can i download video in the mobile storage and play in the react native video player.

**Comment by AlaminPu1007** [comment]
by rnfetch blob you can download your media file both platform.

`
import {PermissionsAndroid, Platform, ToastAndroid} from 'react-native';

import GetImageUrl from '../GetImageUrl';
// Import RNFetchBlob for the file download
import RNFetchBlob from 'rn-fetch-blob';

const DownloadFile = async ({data, hook}) => {
  // Function to check the platform
  // If iOS then start downloading
  // If Android then ask for permission

  //   first check media is present or not
  if (data.media.length) {
    if (Platform.OS === 'ios') {
      downloadImage({data, hook});
    } else {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title: 'Storage Permission Required',
            message: 'App needs access to your storage to download Photos',
          },
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          // Once user grant the permission start downloading
          downloadImage({data, hook});
        } else {
          // If permission denied then show alert
          showToastWithGravityAndOffset('Storage Permission Not Granted');
        }
      } catch (err) {
        // To handle permission related exception
        if (__DEV__) {
          // console.log(err);
        }

        showToastWithGravityAndOffset('Permission problem');
      }
    }
  } else if (__DEV__) console.log('media is not found');
};

const showToastWithGravityAndOffset = text => {
  ToastAndroid.showWithGravityAndOffset(
    text,
    ToastAndroid.LONG,
    ToastAndroid.BOTTOM,
    25,
    50,
  );
};

const downloadImage = ({data, hook}) => {
  // Main function to download the image
  const {globallToastValue} = hook;
  // To add the time suffix in filename
  let date = new Date();
  // get url, which we want to download
  let {imageUri, videoUri, audioUri, pdfUrl, docxUrl, textUrl} = GetImageUrl({
    data: data,
  });

  // if (__DEV__) console.log(data.media[0], 'media types');

  /* if download media type is image */
  if (imageUri) {
    // Getting the extention of the file
    let ext = getExtention(imageUri);
    ext = '.' + ext[0];
    // Get config and fs from RNFetchBlob
    // config: To pass the downloading related options
    // fs: Directory path where we want our image to download
    const {config, fs} = RNFetchBlob;
    let PictureDir = fs.dirs.PictureDir;
    let options = {
      fileCache: true,
      // need this extension for ios
      appendExt: data.media[0].types2,
      addAndroidDownloads: {
        // Related to the Android only
        useDownloadManager: true,
        notification: true,
        path:
          PictureDir +
          '/image_' +
          Math.floor(date.getTime() + date.getSeconds() / 2) +
          ext,
        description: 'Image',
      },
    };
    config(options)
      .fetch('GET', imageUri)
      .then(res => {
        if (Platform.OS === 'ios') {
          RNFetchBlob.ios.previewDocument(res.path());
          if (__DEV__) {
            // console.log(res.path(), 'image downloaded path\n', Platform.OS);
          }
        } else {
          if (__DEV__) {
            // console.log(res.path(), 'image downloaded path\n', Platform.OS);
          }
        }
      })
      .catch(err => {
        if (__DEV__) {
          // console.log(err.message, 'image downloaded error message\n');
        }
      });
  } else if (videoUri) {
    /* if user download media type is video */
    /* if download media type is image */
    // Getting the extention of the file
    let ext = getExtention(videoUri);
    ext = '.' + ext[0];
    // Get config and fs from RNFetchBlob
    // config: To pass the downloading related options
    // fs: Directory path where we want our image to download
    const {config, fs} = RNFetchBlob;
    let PictureDir = fs.dirs.PictureDir;
    let options = {
      fileCache: true,
      // need this extension for ios
      appendExt: data.media[0].types2,
      addAndroidDownloads: {
        // Related to the Android only
        useDownloadManager: true,
        notification: true,
        path:
          PictureDir +
          '/video_' +
          Math.floor(date.getTime() + date.getSeconds() / 2) +
          ext,
        description: 'video',
      },
    };
    config(options)
      .fetch('GET', videoUri)
      .then(res => {
        if (Platform.OS === 'ios') {
          RNFetchBlob.ios.previewDocument(res.path());
          if (__DEV__) {
            // console.log(res.path(), 'video downloaded path\n', Platform.OS);
          }
        } else {
          if (__DEV__) {
            // console.log(res.path(), 'video downloaded path\n', Platform.OS);
          }
        }
      })
      .catch(err => {
        if (__DEV__) {
          // console.log(err.message, 'video downloaded error message\n');
        }
      });
  } else if (audioUri) {
    /* if user download media type is audio */
    /* if download media type is image */
    // Getting the extention of the file
    let ext = getExtention(audioUri);
    ext = '.' + ext[0];
    // Get config and fs from RNFetchBlob
    // config: To pass the downloading related options
    // fs: Directory path where we want our image to download
    const {config, fs} = RNFetchBlob;
    let PictureDir = fs.dirs.PictureDir;
    let options = {
      fileCache: true,
      // need this extension for ios
      appendExt: data.media[0].types2,
      addAndroidDownloads: {
        // Related to the Android only
        useDownloadManager: true,
        notification: true,
        path:
          PictureDir +
          '/audio_' +
          Math.floor(date.getTime() + date.getSeconds() / 2) +
          ext,
        description: 'audio',
      },
    };
    config(options)
      .fetch('GET', audioUri)
      .then(res => {
        if (Platform.OS === 'ios') {
          RNFetchBlob.ios.previewDocument(res.path());
          if (__DEV__) {
            // console.log(res.path(), 'audio downloaded path\n', Platform.OS);
          }
        } else {
          if (__DEV__) {
            // console.log(res.path(), 'audio downloaded path\n', Platform.OS);
          }
        }
      })
      .catch(err => {
        if (__DEV__) {
          // console.log(err.message, 'audio downloaded error message\n');
        }
      });
  } else if (pdfUrl) {
    // show toast user
    if (Platform.OS === 'android') {
      showToastWithGravityAndOffset('download is not available');
    } else {
      globallToastValue('download is not available');
    }
  } else if (docxUrl) {
    // show toast user
    if (Platform.OS === 'android') {
      showToastWithGravityAndOffset('download is not available');
    } else {
      globallToastValue('download is not available');
    }
  } else if (textUrl) {
    // show toast user
    if (Platform.OS === 'android') {
      showToastWithGravityAndOffset('download is not available');
    } else {
      globallToastValue('download is not available');
    }
  } else {
    if (__DEV__)
      console.log(
        'image, audio, video, pdf, text, docx, download method is added till,other will be added later',
      );
  }
};

const getExtention = filename => {
  // To get the file extension
  return /[.]/.exec(filename) ? /[^.]+$/.exec(filename) : undefined;
};

export default DownloadFile;
`

**Comment by ahmadsyed** [comment]
Hi @AlaminPu1007 @puneetkansal04 , I am also having same situations. Will this solution save m3u8 video files too ?
If yes, then will this library be able to play it from locally save m3U8 if yes how ?

**Comment by moskalakamil** [comment]
Hey all!

We can’t simply save the `.m3u8` file as-is, but we’ve recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=2620) that lets you download and play video content offline - including DRM-protected streams.  
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:  
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=2620)
