### ISSUE TITLE
NSURLErrorDomain -1002 VideoCaching with Firebase

### ISSUE THREAD

**Issue by AntonBorovoi** [TheWidlarzGroup/react-native-video#2624]
# Bug

I am building the app using the firebase packages and video caching provided by VideoCaching pod
Faced with the issue on iOS that video is not showing and throwing the error 
 code: -1002
 domain: "NSURLErrorDomain"
 localizedDescription: "unsupported URL"

## Platform
iOS

Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 308.44 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.0

## Steps To Reproduce
1. install firebase package `"@react-native-firebase/app": "14.5.0"`
2. enable it on AppDelegate.m by `#import <Firebase.h>` and  `[FIRApp configure];` on `didFinishLaunchingWithOptions`
3.  install video package `"react-native-video": "5.2.0"`
4. enable video caching by `pod 'react-native-video/VideoCaching', :path => "../node_modules/react-native-video/react-native-video.podspec"` on podfile
5. 
 ```
<Video
          onError={(e) => console.log(e) }
          source={{ uri: remoteVideoUri }}
          style={{ flex: 1 }}
        />
```

All is working as expected when:
1. skip step 2
or
2. disable caching by using `pod 'react-native-video', :path => "../node_modules/react-native-video/react-native-video.podspec"`

## Expected behaviour
1. Should play a video without errors

**Comment by vargajacint** [comment]
Can u share the `remoteVideoUri`  value?

**Comment by freeboub** [comment]
No url provided since March, let's close
