### ISSUE TITLE
[Query]Latency Optimization - video play back start up time.

### ISSUE THREAD

**Issue by skusuj** [TheWidlarzGroup/react-native-video#2629]
# Question

We are using react-native-video for video playback on Android app. we determine video playback start up time (Play To First Frame) by capturing the moment when user clicks on play button and the moment when we receive onReadyForDisplay event from native player. To better understand where most of the time spent we further break it up as player initialization time (user click to video load start event), Video Load duration (video load start event to video load event) and player ready duration (video load event to onReadyForDisplay). As part of latency optimization we are now passing buffer config with 'bufferForPlaybackMs' as 1500ms so that play back starts earlier. Our hypothesis was buffer config optimization would reduce video load duration and the overall start time will be reduced. But what we see is though over all start up time has reduced but video load time has regressed. We are unable to understand this behavior. Could please help me understand why is video load duration regressing and even after this regression how are we seeing over all start up time gain? 

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

  React Native Environment Info:
    System:
      OS: macOS 11.6.2
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 106.40 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
      npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.3, 30.0.2, 31.0.0, 32.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8

### Exoplayer Library version: 2.11.4

**Comment by freeboub** [comment]
Setting buffering config will stop and restart playback:

    public void setBufferConfig(int newMinBufferMs, int newMaxBufferMs, int newBufferForPlaybackMs, int newBufferForPlaybackAfterRebufferMs) {
        minBufferMs = newMinBufferMs;
        maxBufferMs = newMaxBufferMs;
        bufferForPlaybackMs = newBufferForPlaybackMs;
        bufferForPlaybackAfterRebufferMs = newBufferForPlaybackAfterRebufferMs;
        releasePlayer();
        initializePlayer();
    }

Can it be the issue ?
Do you always keep these props  available in the Video View ?

**Comment by skusuj** [comment]
Does the playback starts before setting client passed props onto the player? Isn't prop setting and player initialization happening on Main Thread only?  which first sets all the props and then starts playback.

**Comment by hueniverse** [comment]
@freeboub can you review @skusuj questions?

**Comment by freeboub** [comment]
The bufferConfig change has finally be implemented on 6.8.2.
Let's close this ticket
