### ISSUE TITLE
OnBuffer is not calling because of not having exoplayer.

### ISSUE THREAD

**Issue by pk936** [TheWidlarzGroup/react-native-video#2632]
The video player shows green seek bar. So, I think it is not **exoplayer**.

But I have already added following line in **android/settings.gradle**
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
And I have 

```
"react-native": "0.68.0",
"react-native-video": "^5.2.0",
```

I am still not  sure whether I am using old media player or exoplayer.

**Comment by pk936** [comment]
fixed the issue on my own.

The settings in **android/settings.gradle** did not work for me. So I added **react-native.config.js** in root folder of the project and added following lines:
```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```
**_Note: Green track ball on seek bar means it's old media player. White track ball means it's exoplayer._**

**Comment by puneetkansal04** [comment]
@pk936 app is crashing on video play if i am using this above code in the react-native-config file. Also there is a package of react-native-splash over. So please let me know if you know this crash as i got crash that value of value is not able to convert to double this.
