### ISSUE TITLE
Repeat option super laggy on android

### ISSUE THREAD

**Issue by pierroo** [TheWidlarzGroup/react-native-video#2635]
# Bug

I am using the repeat props on a video.
Even just a 5 seconds video makes the repeat super laggy at the end of playing:
- video buffers
- video plays, and ends
- video get stuck on last frame for 4-5 seconds before finally looping

Since it is so slow, I am even worried that the library actually re-download the video each time it repeats?
that seems surprising, but would justify why it's so long; since the delay before repeat is nearly the same as initial download for each repeat.

Here is my code component:

 ```
<Video
          source={{ uri: video_uri }}
          poster={thumb_uri}
          style={StyleSheet.absoluteFill}
          paused={isPaused}
          resizeMode="cover"
          posterResizeMode="cover"
          allowsExternalPlayback={false}
          automaticallyWaitsToMinimizeStalling={false}
          disableFocus={true}
          repeat={true}
          useTextureView={false}
          controls={false}
          playWhenInactive={true}
          ignoreSilentSwitch="ignore"
          onReadyForDisplay={onMediaLoadEnd}
          onError={displayError}
        />
```

## Platform
Haven't tested yet on iOS, for now it's android only.
I haven't configured anything related to exoplayer, so I guess by default I'm on mediaplayer?

React-native: 0.66.0
Library version: 5.2.0

**Comment by ValentineCodes** [comment]
Facing same issue. Any fix?

**Comment by danbjork** [comment]
I'm having a similar issue. I'm using a sound that is supposed to be repeated. On Android there's a noticeable lag when the sound is being repeated

**Comment by ceres-quangd** [comment]
I was wondering if you could help me out with a similar issue that I am currently facing. I am not sure what to do and any guidance you can provide would be greatly appreciated. Thanks in advance!

**Comment by freeboub** [comment]
on V6.0.0 we only use exoplayer, so I think we can close the issue.
I tried with the sample app, it looks good to me.
Let me know if you still have the issue !
