### ISSUE TITLE
New Library Recruit

### ISSUE THREAD

**Issue by JasonCareter** [TheWidlarzGroup/react-native-video#2638]
Since this project was abandon. Perhaps we can re-open a fresh new project .
I can write java ,kotlin, oc and swift  and I've made some research on JSI recently, you can find it on my personal profile .
Anyone's interest on this ?

**Comment by hueniverse** [comment]
@yaaliuzhipeng I have joined the maintainers team this week and will be starting to clean things up. I am going to post a new bug report process that will significantly improve the speed in which bugs can be verified and hopefully fixed. While you are welcome to fork or start a new project, you are welcome to contribute here and I promise to be more prompt in reviewing pull requests. I am still getting things ready (and have a big release I need to finish) but I plan to bring this module back to health over the next few months.
