### ISSUE TITLE
video should be paused by default if the user has "reduced motion"/"remove animations" enabled in settings

### ISSUE THREAD

**Issue by Adnan-Bacic** [TheWidlarzGroup/react-native-video#2644]
# Feature Request

video should be paused by default if the user has "reduced motion"/"remove animations" enabled in settings

## Why it is needed

recently, i was made aware that a video we are showing is still playing if the user has enabled "reduced motion" on ios and "remove animations" on android. this is _maybe_ bad UX as these people would probably wish that videos didnt play.

## Possible implementation

from the react-native side that would probably be the "paused" prop:

https://github.com/react-native-video/react-native-video#paused

right now it defaults to `true`. i would suggest it would be `false` if the user has disabled animations, and otherwise `true`.

of course this could easily be implemented with an if statement on our side, but i feel like the library should do this. as many probably will not think about adding this.

to get the users preference we would use:

https://reactnative.dev/docs/accessibilityinfo#isreducemotionenabled

i would assume this requires changes to the native code too. which im sadly not knowledgeable about. i could be wrong however.

**Comment by hueniverse** [comment]
I don't think the video player should be responsible for this.
