### ISSUE TITLE
Remove Windows support

### ISSUE THREAD

**Issue by hueniverse** [TheWidlarzGroup/react-native-video#2646]
I am considering dropping support for Windows.

Keeping it would require having a few names I can ping when there are issues and to review PRs. So far I have @namrog84 listed. If you care about Windows support and are able to lend a hand when needed please reply.

**Comment by namrog84** [comment]
100% interested in keeping windows support. I will talk to a few folks who have appropriate experience and see if I can get them to step up, sign up, and help here.

**Comment by adamgorMSFT** [comment]
We use react-native-video in multiple apps in a critical way for both Android and Windows.  We need to keep windows support going for it. (Note: I am namrog84 under work github account).  I will help rally support through work to get more people to help review PRs and such to keep windows support.

**Comment by aschultz** [comment]
I can help review Windows support.

**Comment by hueniverse** [comment]
Thank you @namrog84  and @aschultz! My plan is to compile a list of those willing to contribute to supporting Windows and tag them on upcoming issues and PRs. If we get enough reviews we'll merge and fix issues. If after a few months this problem is still present, we'll revisit. Will keep this open to  let more people raise their hand for helping out.

**Comment by kelset** [comment]
@hueniverse just my 2c$: potentially you could add a CODEOWNERS file to the .github repo and add the folks that want to be involved as owners of the windows folder, so that GH will automatically "tag them" when a PR touches the folder - more details [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

**Comment by vmoroz** [comment]
@hueniverse, you can count me in too: I am working on the NativeModule API implementation for RN Windows and should be able to help with the correct use of the APIs.

**Comment by shanelile** [comment]
I can also help review Windows support.

**Comment by hueniverse** [comment]
@namrog84 Can you email me at eran@sideway.com?

**Comment by hueniverse** [comment]
Thanks everyone! What's the state of the Windows player? Is it working well? Anything you want us to fix/change/prioritize?

**Comment by hippiejuice** [comment]
@hueniverse Hi! I would love to be able to use custom controls for the Windows player. Currently, I'm not able to turn the built in controls off.

**Comment by Okelm** [comment]
Hi! Bumping up the topic. There has been nearly no further development and maintenance for Windows for the last year. And, unfortunately, it's not TWG (@KrzysztofMoch ) or @freeboub priority right now, so there are no plans for active development in this area. In case any of you need this support please let us know 🙏

**Comment by stmoy** [comment]
👋 - hello from the RN team at Microsoft. This module is still important for our broader team though we aren't tracking any active requests/issues at the moment. You can poke @chrisglein or the folks above (@vmoroz @kelset) if there are important/necessary requests for Windows/macOS specifically.
