### ISSUE TITLE
How to handle the self signed https URL on iOS,  the self signed certification URL can't be played

### ISSUE THREAD

**Issue by jinxuesong** [TheWidlarzGroup/react-native-video#2649]
access the URL of the self signed certificate on iOS
the error is :
'error:', { error: 
   { localizedDescription: 'The certificate for this server is invalid.',
     domain: 'NSURLErrorDomain',
     localizedFailureReason: '',
     localizedRecoverySuggestion: 'Would you like to connect to the server anyway?',
     code: -1202 },
  target: 112909 }

when I try to use the http or CA signed https url, it can be played on iOS. Only the self signed certification url can't be played

Who know the solutions？

**Comment by freeboub** [comment]
Issue is not clear ... It look like your certificate url is not accessible.
More log is needed, or reproduction step...
I close the issue feel free to reopen it if new information available

**Comment by lh99998888** [comment]
I meet the same problem. When I what to play a video asset stored in self signed certificate server, it shows error as "The certificate for this server is invalid.". Is there any way to ignore certificate validation?
When request data from self signed cert server with NSURLSession, I can ignore cert validation using following code
```
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler {
    NSURLCredential *credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
    completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
}
```
How can I do this in this component?

**Comment by emreer94** [comment]
I got the same problem in iOS with the exact same logs, I used self-signed SSL certificate to play my videos. Also, this is my info.plist to configure app transport security
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionAllowsInsecureHTTPLoads</key>
		<true/>
		<key>NSExceptionRequiresForwardSecrecy</key>
		<false/>
		<key>NSIncludesSubdomains</key>
		<true/>
	</dict>
```
how can I resolve this? Any updates? @jinxuesong  @lh99998888
