### ISSUE TITLE
Memory Leak in Android

### ISSUE THREAD

**Issue by gravitinos** [TheWidlarzGroup/react-native-video#265]
I seem to have found a memory leak in unmounting the video component on Android, which I think is related to this, although they might be two separate problems I'm running into at once.

I ran into it running my app overnight, which switched through images and videos every 5-30 seconds. I was able to replicate this within a few hours by changing it to every second it switches.

I avoided it by never unmounting the Video component, but updating it (so I don't rebuild the component, ONLY update it).

Overtime, the CPU slowly builds up. Depending on the device, it would max out and make the app run horribly (but with no crash, maybe leveling out at about 50% CPU).

Running a systrace, I could see the process that was taking up the CPU usage was the UI thread.

TLDR: It seems unmounting the Video Component on Android doesn't totally get rid of all processes.

Here's the example I have that took me about 30 min of running to run into this error, while hitting about 30% CPU usage in dev mode. https://github.com/xvalentino/react-native-video-leak/blob/master/index.android.js

**Comment by arilitan** [comment]
I'm running into a similar issue. I have a ListView of video components, when a video scrolls off view I unmount the component. However I am encountering an edge case where sometimes the react component is Unmounted but the video is still playing in the background and not properly being flushed from memory.

Let me know if you've come up with any solutions

**Comment by gravitinos** [comment]
@arilitan I remember running into something similar to that before. If you console.log onProgress does it continue to log after unmounting? I remember I also did something like setting a ref to the video, and calling something like React.unmountComponentAtNode in the componentWillUnmount function. I'd try that to see if that works for your purposes, but as far as I know this was never resolved, and the cleanup seems to not flush everything of the video from memory.

**Comment by arilitan** [comment]
@xvalentino thanks so much for this tip! I was able to debug this with a console.log in the onProgress function. The players indeed were not getting deallocated like I assumed they were. I refactored the component and now able to better flush everything manually

**Comment by mattapperson** [comment]
Perhaps this is something we should document?

**Comment by mattapperson** [comment]
Closing this due to @nharlow89's PR. Issue now solved

**Comment by c-moyer** [comment]
> @xvalentino thanks so much for this tip! I was able to debug this with a console.log in the onProgress function. The players indeed were not getting deallocated like I assumed they were. I refactored the component and now able to better flush everything manually

How did you fix this issue? I'm having the same problem on the latest version. Memory just eventually runs out after you render a large number of videos consecutively.
