### ISSUE TITLE
Minimum React Native version support

### ISSUE THREAD

**Issue by hueniverse** [TheWidlarzGroup/react-native-video#2655]
I would like to only support RN versions from the past year. The thinking is that if you are not upgrading your RN app for more than a year, you are also probably not upgrading core dependencies like this one. This would put us at **RN v0.64**.

This means publishing patches to older major versions if the latest has more recent requirements. For example, if we decide that v7 only supports RN 0.68 with new architecture, we will continue to support v6 for RN versions up to a year old.

Thoughts?

**Comment by freeboub** [comment]
I agree it can be problematic to maintain old react-native version.
In all RN modules I saw, they said they don't support of version ...
Now with turbo module and new architecture, I am not sure of the exact impact in terms of dependancies.
maybe @[douglowder](https://github.com/react-native-tvos/react-native-tvos/commits?author=douglowder) can give some clues

**Comment by Adnan-Bacic** [comment]
react-native-maps already does something similar, even more strict actually: https://github.com/react-native-maps/react-native-maps#compatibility

they only officially support the latest version.
