### ISSUE TITLE
Audio out of sync after seeking when playing some video files (iOS only)

### ISSUE THREAD

**Issue by mitchdowney** [TheWidlarzGroup/react-native-video#2659]
# Bug

While testing our app, I discovered that the video podcast "Club Random with Bill Maher" does not play audio after I seek within a video. It turns out this issue seems to only happen with *huge* video files (2GB+).

Is this a known issue? Are there any workaround that can help us play huge video files more reliably?

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 767.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.14.16 - ~/Repos/podverse-rn/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

This video file is over 2GB:
https://traffic.libsyn.com/secure/63b0ddcf-964a-4f83-8e07-2304ebecd351/CR_Judd_Apatow_460x360_040322.mp4?dest-id=3350918

And while the audio plays if I play the video from the beginning, as soon as I try seeking in the file, the audio no longer plays, while the video continues (although it seems to sputter).

This other video for the show is ~500MB:
https://traffic.libsyn.com/secure/63b0ddcf-964a-4f83-8e07-2304ebecd351/CR_Quetin_Tarantino_CUT_4_FINAL_OUTPUT_VIDEO_360x640_032722.mp4?dest-id=3350918

## Expected behaviour

Audio for the video should play whenever the video is playing.

**Comment by mitchdowney** [comment]
After further testing, I'm not sure file size is the problem. Perhaps some kind of encoding/decoding related issue? The audio falls out of sync on seek for some videos and not others.

For example, this is a smaller video (2 mins, less than 100MB) and the audio also falls out of sync on seek with it.

Any advice or recommendations for things I should investigate would be greatly appreciated.

**Comment by mitchdowney** [comment]
Whoa. I can reproduce the issue with those same videos by loading them in MacOS Safari 😧

That's wild...this has to be a well-known issue right? I'm struggling to find search results about it.

Video demo: https://noagendatube.com/videos/watch/d1fffb9f-8391-4473-8796-765e7e48cc0a

**Comment by hueniverse** [comment]
Can you try this on iOS 14.x and 15.0? Apple made some video player changes in iOS 15.3+ that might be related.

Also, can you try and fork https://github.com/react-native-video/react-native-video-test to recreate the issue? It would be helpful to try and narrow it down.

**Comment by mitchdowney** [comment]
So I keep trying to download iOS Simulator 14.5 and 15.0, and it keeps timing out 🤦 I'm not sure I'm going to be able to get this to work.

In any case, I'm able to reproduce the issue using the default video URL in react-native-video-test.

Video demo: https://peertube.podverse.fm/w/s1hLSBcMyk7NytwTkgWqSo

Default video URL: https://cdn81168665.blazingcdn.net/timeline/hartley-e001-s001a-01-2b6d4c/stream/index.m3u8

Other video URL, which doesn't have the audio syncing issue, but stalls: https://content.pwc-networks.com/dtns/DTNS20220429.mp4

**Comment by hueniverse** [comment]
I am unable to reproduce this issue. I'll leave this open for a bit longer in case someone else can reproduce and add new details.

**Comment by mitchdowney** [comment]
@hueniverse hmm I'm not having the problem either on web or mobile Safari products...maybe Apple fixed it with an update? In any case that's good news, and I'll close this issue.

**Comment by hueniverse** [comment]
@mitchdowney Thanks for following up.
