### ISSUE TITLE
Base64 string for source?

### ISSUE THREAD

**Issue by bpolonia** [TheWidlarzGroup/react-native-video#266]
Hi, can the source take a base64 string for the URI? I know `<Image />` can. Was wondering if this had the same capability.

**Comment by mroswald** [comment]
I'm not sure about base64, but for inlining small videos without adding them to the xcode project, there's (hopefully) a feature upcoming: https://github.com/brentvatne/react-native-video/pull/251

**Comment by bpolonia** [comment]
Ok Thanks!

**Comment by freddiecabrera** [comment]
Hey @bpolonia were you able to get the player to take the base64 string for the URI?

**Comment by hadrienbbt** [comment]
Hello, did someone find a way to play base64 encoded videos ?

**Comment by TylerNoblett** [comment]
Hey @hadrienbbt ! What did you do in your situation? I could use base64 encoded video playback as well

**Comment by TylerNoblett** [comment]
@hadrienbbt Thanks for the insight - I really appreciate your speedy response!

**Comment by ryemcc** [comment]
You can write the Base64 encoded content to a file using [react-native-fs](https://github.com/itinance/react-native-fs), naming the file xxxx.mp4. Then pass the Video component the path as the uri, prefixed with 'file://'.

```javascript	
import RNFS from 'react-native-fs'
const downloadToFile = (base64Content, contentId) => {
	const path = `file://${RNFS.DocumentDirectoryPath}/${contentId}.mp4`
	RNFS.writeFile(path, base64Content, 'base64')
	.then(success => {
		console.log('FILE WRITTEN: ', versionId)
	})
	.catch(err => {
		console.log('File Write Error: ', err.message)
	})
}
```
Then in the video component, you can retrieve the file by its contentId:

```jsx
<Video source={{ uri: `file://${RNFS.DocumentDirectoryPath}/${contentId}.mp4`}} />
```

**Comment by jothikannan** [comment]
> react-native-fs

Is this really works for you??? For me not working

**Comment by RottenKiwi** [comment]
Any solution?

**Comment by raymondjacobson** [comment]
@RottenKiwi https://github.com/react-native-community/react-native-video/pull/1842

**Comment by dev4funs** [comment]
Is there any way to play the base64 mp4 file without saving the string as a file in local ？

**Comment by tamangsuresh** [comment]
Did any one have found its solution?

**Comment by JowelTisso** [comment]
@tamangsuresh @EmilioDeng98 @RottenKiwi Yes, The solution is there in this PR #1842 but has not been merged yet, So if you want to use it... You can implement those changes in your node_modules yourself and use it... Its working for me...
