### ISSUE TITLE
Video not playing on Android (image is freezed), only audio is on

### ISSUE THREAD

**Issue by NelsonMkrtchyan** [TheWidlarzGroup/react-native-video#2661]
# Bug

Using a simple example of a Video component from react-native-video, copied from the official documentation. The problem is that on Android the image is freezed and only audio is playing. The same is working excellent in ios.

**Comment by freeboub** [comment]
We cannot investigate such issue.... Do you have at least the stream url you use ?

**Comment by NelsonMkrtchyan** [comment]
This is the video I used http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

**Comment by NelsonMkrtchyan** [comment]
It seems the issue is only actual on Android simulators, on the actual physical device it works pretty well.

**Comment by hueniverse** [comment]
@NelsonMkrtchyan have you tried different versions of the simulator? Are there any network differences?

**Comment by meowchownow1** [comment]
+1 same issue

**Comment by freeboub** [comment]
I just try on simlator androidTV 1080p APi 30, It work pretty fine...
Do you think we can close this issue ?

**Comment by hueniverse** [comment]
Closing for now. If this is still an issue after v6 is released we can revisit.

**Comment by eramudeep** [comment]
> It seems the issue is only actual on Android simulators, on the actual physical device it works pretty well.

not worked for me, showing black screen with audio

**Comment by bap-truongnv2** [comment]
Did you solve this issue @eramudeep ?
All my devices working well, except for the Xiaomi device

**Comment by pblab-dev** [comment]
same here
