### ISSUE TITLE
MaxBitRate is ignored in Android

### ISSUE THREAD

**Issue by evkwan** [TheWidlarzGroup/react-native-video#2665]
# Bug

Problem: 
After setting MaxBitRate property, Android Exoplayer is seen to ignore this value and continues downloading/playing the video track with highest bitrate in the HLS playlist.

## Platform

* Android ExoPlayer

## Environment info

```json
"react-native": "0.66.4",
"react-native-video": "5.2.0",
```

## Steps To Reproduce

1. Play a video with HLS list (.m3u8 format), having a few resolutions and set MaxBitRate to a value such that it should only qualify 3 tracks.

Example master manifest file:
```
#EXT-X-STREAM-INF:BANDWIDTH=2516370,AVERAGE-BANDWIDTH=2516370,CODECS="mp4a.40.2,avc1.640020",RESOLUTION=720x1280,CLOSED-CAPTIONS=NONE

#EXT-X-STREAM-INF:BANDWIDTH=1640580,AVERAGE-BANDWIDTH=1640580,CODECS="mp4a.40.2,avc1.640020",RESOLUTION=540x960,CLOSED-CAPTIONS=NONE


#EXT-X-STREAM-INF:BANDWIDTH=4755240,AVERAGE-BANDWIDTH=4755240,CODECS="mp4a.40.2,avc1.64002a",RESOLUTION=1080x1920,CLOSED-CAPTIONS=NONE


#EXT-X-STREAM-INF:BANDWIDTH=994068,AVERAGE-BANDWIDTH=994068,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=360x640,CLOSED-CAPTIONS=NONE


#EXT-X-STREAM-INF:BANDWIDTH=697078,AVERAGE-BANDWIDTH=697078,CODECS="mp4a.40.2,avc1.64001e",RESOLUTION=270x480,CLOSED-CAPTIONS=NONE

```
With the list, above, set `maxBitRate={1640580}`

2. Observe on Android Exoplayer, it still downloads the highest resolution chunks to play after the initial chunk. You can cross check the downloaded chunk url belongs to the manifest of the highest resolution.

## Expected behaviour

After setting MaxBitRate, Android Exoplayer should be downloading/playing only video tracks that honour the max bitrate set. 

## Reproducible sample code
```
<Video
source={{ uri: 'https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8' }}
style={{ width: 300, height: 300 }}
maxBitRate={1062000}
} />
```

## Video sample
You may try with 
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

## Comments
Not sure if this was intentional but digging through the Exoplayer code it seems that the culprit of this behaviour stems from the `videoLoaded()` function in ReactExoPlayerView.java when `onPlayerStateChanged()` is called with Player.STATE_READY.

```
private void videoLoaded() {
        if (loadVideoStarted) {
            loadVideoStarted = false;
            setSelectedAudioTrack(audioTrackType, audioTrackValue);
            setSelectedVideoTrack(videoTrackType, videoTrackValue); // <--- this creates a default selectionOverride
            setSelectedTextTrack(textTrackType, textTrackValue);
            Format videoFormat = player.getVideoFormat();
            int width = videoFormat != null ? videoFormat.width : 0;
            int height = videoFormat != null ? videoFormat.height : 0;
            String trackId = videoFormat != null ? videoFormat.id : "-1";
            eventEmitter.load(player.getDuration(), player.getCurrentPosition(), width, height,
                    getAudioTrackInfo(), getTextTrackInfo(), getVideoTrackInfo(), trackId);
        }
    }
```

The `setSelectedVideoTrack()` called inside videoLoaded will lead to Exoplayer creating default selectionOverride which includes all tracks, making all of them available for ABR when we really only want those tracks that meets the MaxBitRate set. Every subsequent call to check track selection will use the overridden tracks instead.

If videoLoaded() is required, then perhaps another way around this is to offer user a means to configure the param `forceHighestSupportedBitrate`, which will then give the expected behaviour as discussed via [this issue](https://github.com/google/ExoPlayer/issues/6756) in Exoplayer official thread.

**Comment by freeboub** [comment]
can you try to add this line in videoLoaded, just after setSelectedVideoTrack(videoTrackType, videoTrackValue);:

                    trackSelector.setParameters(trackSelector.buildUponParameters()
                            .setMaxVideoBitrate(maxBitRate == 0 ? Integer.MAX_VALUE : maxBitRate));

Just as a workaournd ...

**Comment by evkwan** [comment]
@freeboub I tried out your suggestion, it does not work. The root cause is because of `setSelectedVideoTrack(videoTrackType, videoTrackValue)` being called with videoTrackType being `null`. See the images below as reference:

![image](https://user-images.githubusercontent.com/14858904/165884056-19c25c76-b923-4dce-ac43-a39f05e24a0b.png)

![image](https://user-images.githubusercontent.com/14858904/165884096-028bb527-ef8b-4c25-aa30-c69c77d061f4.png)

Because of that the list of all the tracks is being generated and overridden into the trackSelector regardless of the max bitrate set.

This however works:
```
	private void videoLoaded() {
		if (loadVideoStarted) {
			loadVideoStarted = false;
			if (audioTrackType != null) {
				setSelectedAudioTrack(audioTrackType, audioTrackValue);
			}
			if (videoTrackType != null) {
				setSelectedVideoTrack(videoTrackType, videoTrackValue);
			}
			if (textTrackType != null) {
				setSelectedTextTrack(textTrackType, textTrackValue);
			}
```
It does not make sense to update the track selections if the type is not available anyway. What do you think?

I'd be happy to help get a PR in if you think this is acceptable.
