### ISSUE TITLE
FlatList Support

### ISSUE THREAD

**Issue by hueniverse** [TheWidlarzGroup/react-native-video#2668]
This issue consolidates multiple reports of problems with rendering multiple videos in a FlatList: #908, #2667, #2414, #2325, 
#1636, #1318, #433, #2247

**Comment by hueniverse** [comment]
It seems to be specific to Android, but would be good to get confirmation on that.

**Comment by freeboub** [comment]
Thanks for opening this 'master ticket', i am wondering if someone tryed to change surfaceview / textureview props ?

https://github.com/react-native-video/react-native-video#usetextureview

**Comment by swikars1** [comment]
I think many other multiple issues are connected to exoplayer being outdated, I have not faced much issue with IOS but its a mess in android. I am using it with flipkart's recycler list view. 

- My errors persists while using the surface view as well. 
- Some time audio keeps playing but video is frozen
- Some videos simply doesn't play at all and throws this error: `{"e": {"error": {"extra": -1004, "what": 1}}}`

**Comment by hueniverse** [comment]
@swikars1 we have a VIP PR to upgrade to the latest version. We need help with getting it finished.

**Comment by doublex** [comment]
This worked for me:
https://github.com/react-native-video/react-native-video/issues/2384#issuecomment-927177083

**Comment by swikars1** [comment]
@hueniverse I wish I could help man, I'm from Javascript world and everything here seems so alien to me.

**Comment by dancixx** [comment]
@hueniverse  #2667 issue appears on ios too. I spent a lot of time investigating this issue, and I found, that the iOS AV pipeline will be full and can't detach from the memory, and if the app creates too many player instances then won't mount any new videos.

**Comment by rahulpandey** [comment]
For me following implementation working fine  for flatlist. I don't find any issue so for 

https://gist.github.com/rahulpandey/b7c8a6964d753bd482daea153341b465.

`"react-native-video": "^5.2.0"`

**Comment by siddharthkr** [comment]
Hi @hueniverse,

Just asking, what do you think, by when this issue will be resolved? 🙂

**Comment by hueniverse** [comment]
@siddharth-kt No clue. No one has offered to work on this.

**Comment by huzaifaaak** [comment]
Attaching my error log.

<img width="742" alt="Screenshot 2022-07-05 at 11 15 25" src="https://user-images.githubusercontent.com/52660166/177294623-65d71d4a-bc04-4d4b-a8df-1e00ee884d4d.png">

**Comment by siddharthkr** [comment]
🙁 Sad to hear that, I wanted to contribute but can't due to no knowledge in native.
but thanks for answering.

**Comment by Lakston** [comment]
I don't have the flatlist issue rendering black in alpha 3 but the videos are choppy, the playback is long to start, it seems like the videos are not buffering properly

**Comment by mhtchawlaAntino** [comment]
> @hueniverse #2667 issue appears on ios too. I spent a lot of time investigating this issue, and I found, that the iOS AV pipeline will be full and can't detach from the memory, and if the app creates too many player instances then won't mount any new videos.

found any solution yet?

**Comment by vemarav** [comment]
@hueniverse playing multiple videos at once is a hardware limitation, thats why youtube also preview one video at a time when in focus. To give better experience one can show thumbnail where video paused and resume from there by remounting video component.

https://github.com/react-native-video/react-native-video/pull/3153

If still facing avc decoder failure then replace ReactExoplayerViewManager dropViewManager instance with

```java
    // ReactExoplayerViewManager.java
    @Override
    public void onDropViewInstance(ReactExoplayerView view) {
        view.release();
    }
```

then define release() method inside ReactExoplayerView.java

```java
    // ReactExoplayerView.java
    public void release() {
        player.release()
    }
```

**Comment by brunolcarlos** [comment]
This package works better than FlatList but its not perfect
react-native-big-list

**Comment by vemarav** [comment]
@brunolcarlos try this https://github.com/Flipkart/recyclerlistview

**Comment by wolfxpertlab** [comment]
same issue here my report is https://github.com/react-native-video/react-native-video/issues/3251#issuecomment-1735350075

please tell me how can I solved it some time not play video and also check alpha version

**Comment by vemarav** [comment]
@wolfxpertlab setup a meet for vemarav@outlook.in, maybe I can help 🙂

**Comment by davidgvf** [comment]
any solution??

crash my app 

<FlatList
                            ref={FlatlistRef}
                            data={feed}
                            windowSize={8}
                            showsVerticalScrollIndicator={false}
                            getItemLayout={getItemLayout}
                            pagingEnabled
                            decelerationRate={'fast'}
                            onViewableItemsChanged={onViewRef.current}
                            viewabilityConfig={viewConfigRef.current}
                            keyExtractor={keyExtractor}
                            refreshControl={refreshControl}
                            ListFooterComponent={
                                isLoading ? (
                                    <View style={{ paddingVertical: 20 }}>
                                        <ActivityIndicator
                                            size={'large'}
                                            color={colors.white.c100}
                                        />
                                    </View>
                                ) : null
                            }
                            renderItem={renderItem}
                        />
                        
                        my renderItem:
                         <Video
                paused={props.paused}
                style={[styles.backgroundVideo, props.styles]}
                resizeMode={props.resizeMode || ResizeMode.COVER}
                source={{
                    uri: convertToProxyURL(internalVideo.uri),
                    type: getTypeVideo(internalVideo.uri)
                }}
                repeat={props.repeat}
                playInBackground={true}
                bufferConfig={
                    props.bufferConfig || {
                        minBufferMs: 125,
                        maxBufferMs: 25000,
                        bufferForPlaybackMs: 120,
                        bufferForPlaybackAfterRebufferMs: 122
                    }
                }
                onBuffer={e => {
                    e.isBuffering !== isBuffering && setIsBuffering(e.isBuffering);
                }}
                onError={e => {
                    console.info('video error: ', e);
                }}
                onLoad={() => setIsLoading(false)}
            />

**Comment by freeboub** [comment]
For people how stuck on decoder error, Can you try following patch: https://github.com/react-native-video/react-native-video/pull/3416
It should improve behavior in case of decoder issue

**Comment by freeboub** [comment]
To be retested on beta.6

**Comment by vishalhyperspace** [comment]
Any solution? 
I am getting black screen when using video inside flatlist.
Please help
Thanks in advance.

**Comment by avencat** [comment]
@vishalhyperspace which version are you using? @freeboub said v6.0.0-beta.6 should fix this issue (though you could install the latest version to date which is v6.0.0-rc.0

**Comment by longphi97** [comment]
@avencat  I'm having the same problem as @vishalhyperspace

**Comment by avencat** [comment]
@longphi97 on which version?

**Comment by longphi97** [comment]
@avencat  version 6.1.2

**Comment by avencat** [comment]
Ok @freeboub do you think @longphi97 should open a new issue with more information?

**Comment by avencat** [comment]
In the meantime, @longphi97 maybe you should try to open a snack where you reproduce this error! 😉

**Comment by shivnath17** [comment]
Is there any update on the blank screen thing in android? 

I'm using the latest version v6.8.1 Still getting the blank screen in flatlist on scroll.

**Comment by thiennhank9** [comment]
> Is there any update on the blank screen thing in android?
> 
> I'm using the latest version v6.8.1 Still getting the blank screen in flatlist on scroll.

Same here, use the latest version, still get the blank screen if the video is under the flatlist, and is not in the current viewport while scrolling
