### ISSUE TITLE
Video start playing when autoPlay ={False}

### ISSUE THREAD

**Issue by SanjanaTailor** [TheWidlarzGroup/react-native-video#2669]
Hello, 

I am facing the issue Video start playing when autoPlay = {false} 
below is my Video component and onError is not calling. 
<Video
            style={styles.backgroundVideo}
            fullscreenOrientation="all"
            //onBuffer={this.onBuffer} // Callback function
            onError={videoError}
            source={{
              uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            }}
            thumbnail={{
              uri: 'https://html.com/wp-content/uploads/flamingo.webp',
            }}
            resizeMode="contain"
            rate={1}
            volume={10}
            muted={false}
            ignoreSilentSwitch={null}
            fullscreen={false}
            repeat={false}
            //controls={true}
            autoplay={false}
            preventsDisplaySleepDuringVideoPlayback={false}
            paused={false}
          />

**Comment by hueniverse** [comment]
Why `paused` is not set to `true`?

**Comment by freeboub** [comment]
> Why `paused` is not set to `true`?

I agree, autoPlay is not a supported prop !

**Comment by hharsh0** [comment]
> Why `paused` is not set to `true`?

Even if we make paused=true autoplay still doesn't stop

**Comment by seyedmostafahasani** [comment]
@hharsh0 
What is version of your library?

**Comment by hharsh0** [comment]
> @hharsh0 What is version of your library?

I'm sorry, I was doing something wrong, I have deleted my previous message.
