### ISSUE TITLE
add supported video file formats to README

### ISSUE THREAD

**Issue by masterkrang** [TheWidlarzGroup/react-native-video#267]

**Comment by mattapperson** [comment]
Perhaps it is better to simply link to each platforms support doc on this topic? But yea its not a bad idea

**Comment by Ivshti** [comment]
@masterkrang @mattapperson correct me if I'm wrong, but on iOS, it's simply what AVFoundation supports, but on Android it's a bit more complicated as `react-native-video` uses exoplayer ?

**EDIT**: oops, [another project](https://github.com/xeodou/react-native-player) uses exoplayer. Nevermind

**Comment by mattapperson** [comment]
Yup

**Comment by AndrewJack** [comment]
ExoPlayer (android-exoplayer in this project) will support:
> Supports formats such as MP4, M4A, FMP4, WebM, MKV, MP3, Ogg, WAV, MPEG-TS, MPEG-PS, FLV and ADTS (AAC).
https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/README.md

**Comment by hungdev** [comment]
@AndrewJack on IOS seem not support .mkv

**Comment by AndrewJack** [comment]
iOS uses the native video player, so it only supports H.264 video (and H.265 for [iOS 11](https://support.apple.com/en-gb/HT207022)), in .m4v, .mp4, and .mov file formats. 
https://stackoverflow.com/questions/1535836/video-file-formats-supported-in-iphone

**Comment by HereChen** [comment]
on Android seems not support flv.

**Comment by hungdev** [comment]
i changed to this lib: https://github.com/xuyuanzhou/react-native-yz-vlcplayer
it supported a lot of files type

**Comment by ahsanihsan** [comment]
Hi,

Is there any update related to AVI videos? Its not playing on android and iOS both!

**Comment by rintsyman** [comment]
> j'ai changé pour cette lib: https://github.com/xuyuanzhou/react-native-yz-vlcplayer
> il supportait beaucoup de types de fichiers

this library needs a MobileVLCKit.framework file that has 1.7Gb, after the buid your IPA is in how many GB?

**Comment by Prince-AppsTango** [comment]
hls link support or not in react native video (android) please help me

**Comment by freeboub** [comment]
@okay00 yes hls should be supported.
For detail information you can refer to avplayer doc for ios or exoplayer doc for Android

**Comment by Prince-AppsTango** [comment]
vimeo hls link support or not  react native video (android) , i am using vimeo hls link then show error 
 error {"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}
this is my link
https://player.vimeo.com/play/fd4fb856-8956-4ed9-8ec5-c25ab5b9d4e2/hls?s=722187116_1657040505_f3fa516ad90312118fec59aabf1b3f7c&context=Vimeo%5CController%5CApi%5CResources%5CVideoController.&oauth2_token_id=1581373569

**Comment by freeboub** [comment]
@okay00 not sure exoplayer is able to detect you stream is HLS.
you should try to add type='m3u8'
See: 'Explicit mimetype for the stream' section in api documentation

**Comment by Prince-AppsTango** [comment]
thanks @freeboub

**Comment by fomichova** [comment]
Where I can find the list of supported formats for react-native-video?

**Comment by ikedj** [comment]
Where I can find the list of supported formats for react-native-video?
