### ISSUE TITLE
Android ExoPlayer, Can't seek audio file

### ISSUE THREAD

**Issue by samouds** [TheWidlarzGroup/react-native-video#2673]
Hello, I am using "react-native-video": "^5.2.0" and each time I call seek method the track goes back to 0.

It only happens on Android. iOS works perfectly.

**Comment by hueniverse** [comment]
This is not enough information to help. Please fork https://github.com/react-native-video/react-native-video-test and reproduce your issue so that we can look further. Closing this for now, but will reopen once we have something to work with.

**Comment by khushal87** [comment]
Facing the same issue on Android. I am able to seek mp3 files but not aac. On iOS everything works fine.

**Comment by phazei** [comment]
Same issue for me on android, we're using aac as well, iOS is good.

@hueniverse

**Comment by phazei** [comment]
There are other related tickets that keep getting ignored with this issue:
https://github.com/TheWidlarzGroup/react-native-video/issues/2832
https://github.com/TheWidlarzGroup/react-native-video/issues/1476

The player is broke with seeking AAC audio on Android.  It works fine on iOS.
