### ISSUE TITLE
Can't play specific Video URL 

### ISSUE THREAD

**Issue by afacar** [TheWidlarzGroup/react-native-video#2674]
# Bug

I am having trouble while trying to play specific Tiktok URLs. Two URL example below refers to the same video on Tiktok, 1st one extracted from Homepage, and 2nd one is extracted from video's page. While the first URL plays on the Video component, the second URL doesn't play and gives the below error. And both URLs are working fine on the browser. Any help is appreciated!
```
error: {
extra: -1005
what: 1
}
```

OK_URL = "https://v16-webapp.tiktok.com/1a763058292a2dffcfa56a791dd1b682/627469e7/video/tos/useast2a/tos-useast2a-pve-0037-aiso/46a1cb1a76164b4a8b2e887be59243fd/?a=1988&br=1330&bt=665&cd=0%7C0%7C1%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=eXd.6H5zMyq8ZhHKmwe2N.ZQml7Gb&l=2022050518192701024402622911520A2D&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M2pwcDc6ZnQ4OzMzZjgzM0ApZ2Q0aGY4NmQ8N2YzaTpnOWcyYmBhcjRfYGhgLS1kL2Nzc2AyYzEvNmFjYGBeM2BhXjM6Yw%3D%3D&vl=&vr="
NOT_OK_URL = "https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0037-aiso/46a1cb1a76164b4a8b2e887be59243fd/?a=1988&br=1330&bt=665&cd=0%7C0%7C1%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1651796536&ft=lcQHiH5zMyq8ZLGKmwe2N1kPml7Gb&l=20220505182049010245013038095E8D22&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=3&qs=0&rc=M2pwcDc6ZnQ4OzMzZjgzM0ApZ2Q0aGY4NmQ8N2YzaTpnOWcyYmBhcjRfYGhgLS1kL2Nzc2AyYzEvNmFjYGBeM2BhXjM6Yw%3D%3D&signature=8106599cafa24201fb0220d41e3cfbd0&tk=0&vl=&vr="

## Platform

Which player are you experiencing the problem on:
* Android MediaPlayer

## Environment info

React native info output: 
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 23.81 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.0/12A8189n - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```bash
 // paste it here
```

Library version: "react-native-video": "^5.2.0"

## Steps To Reproduce

1. Install react-native-video based on the Android installation [guide](https://github.com/react-native-video/react-native-video#android-installation) 
2. Use the NOT_OK_URL as in source={{uri: NOT_OK_URL}}
...

## Expected behaviour

1. Play video

**Comment by hueniverse** [comment]
Can you reproduce the problem by forking https://github.com/react-native-video/react-native-video-test and only changing the video url? This will allow us to isolate the problem faster.

**Comment by vargajacint** [comment]
The provided videos can not play in web browser also. I think the problem is the url. As I can see the url not pointing to any video file, maybe it's just a proxy.

**Comment by hueniverse** [comment]
@vargajacint Thanks for looking into it.
