### ISSUE TITLE
Switching video freezes

### ISSUE THREAD

**Issue by Maplejay** [TheWidlarzGroup/react-native-video#2675]
my program is set on XIAOMI tv,when i switching the video,program，the program will freeze

**Comment by Maplejay** [comment]
> my program is set on XIAOMI tv,when i switching the video,program，the program will freeze

my program is set on XIAOMI tv,when i switching the video，the program will freeze

**Comment by hueniverse** [comment]
There is no useful info in here to help you out. If you want help please provide enough technical details and code sample to reproduce the problem.
