### ISSUE TITLE
Cookies based hls url

### ISSUE THREAD

**Issue by Rinzin2018** [TheWidlarzGroup/react-native-video#2676]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 

-->

```bash
 sending double cookies with hls url
```

Library version: 5.2.0

**Comment by hueniverse** [comment]
This is not enough information to debug. Please submit more technical details and a way to reproduce.
