### ISSUE TITLE
ViewPropTypes will be removed from React Native

### ISSUE THREAD

**Issue by kdawgwilk** [TheWidlarzGroup/react-native-video#2680]
```
  console.warn
    ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

      3 | import { useSafeAreaInsets } from 'react-native-safe-area-context';
      4 | import Icon from 'react-native-vector-icons/Feather';
    > 5 | import Video, {
        | ^
      6 |   OnLoadData,
      7 |   OnPlaybackRateData,
      8 |   OnProgressData,

      at Object.ViewPropTypes (node_modules/react-native/index.js:470:13)
      at Object.<anonymous> (node_modules/react-native-video/Video.js:509:6)
      at Object.<anonymous> (src/components/VideoPlayer.tsx:5:1)
```

**Comment by freeboub** [comment]
PR already available here: https://github.com/react-native-video/react-native-video/pull/2625#pullrequestreview-973002734

**Comment by BKDeveloper007** [comment]
Still getting this warning when i use below import
 import Video from "react-native-video";

using version 
"react-native-video": "^5.2.0"

warning message:

 ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

**Comment by stevehanson** [comment]
I [opened a new issue](https://github.com/react-native-video/react-native-video/issues/2748) requesting that the fix be released as a v5 patch.
