### ISSUE TITLE
Autolink support

### ISSUE THREAD

**Issue by freeboub** [TheWidlarzGroup/react-native-video#2682]
# Feature Request

Enable autolink support

## Why it is needed

To simplify integration of react-native-video (like all up to date package)

## Possible implementation

I can implement it on android :)

### Code sample

Will remove some of the gradle integration on android

**Comment by hueniverse** [comment]
Can you elaborate on what is needed to get this done? Does it require code for each platform?

**Comment by freeboub** [comment]
the upgrade of react native implement this feature. i close the ticket
