### ISSUE TITLE
Split AudioTracks, VideoTracks & TextTracks events notification from onLoad to have dedicated events 

### ISSUE THREAD

**Issue by freeboub** [TheWidlarzGroup/react-native-video#2683]
# Feature Request

Split AudioTracks, VideoTracks & TextTracks events notification from onLoad to have dedicated events.
- remove Audio / Text / Video Tracks fields from onLoad event
- Create a new event (or 3 different events) to handle these message 

## Why it is needed

Dash implementation allows to have multiple Period.
see: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Period.html
This period management can be used to do server side ads insertion.
But ads inserted may not have the same track configuration that original content.
To allow dynamic update of tracks from an external UI, It is needed to dynamically update tracks configuration 

## Possible implementation

- remove Audio / Text / Video Tracks fields from onLoad event
- Create a new event (or 3 different events) to handle these message

**Comment by hueniverse** [comment]
Why not keep the current event as-is and add the new events in addition?

**Comment by freeboub** [comment]
Yes for sure !

**Comment by freeboub** [comment]
First implementation for android available here: https://github.com/react-native-video/react-native-video/pull/2806

**Comment by ChaTho7** [comment]
> First implementation for android available here: #2806


I asked that https://github.com/react-native-video/react-native-video/issues/2617#issuecomment-1207268335 because i thought that we can customize the subtitle view (backgroundColor, textColor, fontSize, fontFamily, paddings, etc...) **completely** by adding a prop that request a view component. I'm curios about this feature if it's possible to do, **unless decrease the performance significantly**.

**Comment by freeboub** [comment]
There is a misunderstanding. The feature you request starts with this PR https://github.com/react-native-video/react-native-video/pull/2759 i merged this afternoon :) but I agree, it needs to be enhanced to support more styling !

This ticket is about update of track list during playback. This is another topic.

**Comment by freeboub** [comment]
This has been merged, will be available in 6.0.0-alpha.5
