### ISSUE TITLE
`isPlayerPlaying` API for Android Native ExoPlayer

### ISSUE THREAD

**Issue by custadian** [TheWidlarzGroup/react-native-video#2684]
### Current behavior
I don't see such API for Android.

### Expected behavior
By using this API, I can check if the Player is currently Playing or not.

### Platform
Specifically looking for 
* Android ExoPlayer

Is there any API where I can check if the Player is playing or not ?

**Comment by freeboub** [comment]
on master there is now : onPlaybackStateChanged : {isPlaying}
Let close this issue as done !
