### ISSUE TITLE
Controls visible callback

### ISSUE THREAD

**Issue by brantleyenglish** [TheWidlarzGroup/react-native-video#2686]
# Feature Request
Callback for when controls show and hide. 
Similar to `onShowControls` and `onHideControls` on `react-native-video-controls`. 

## Why it is needed
I need to add a custom button to the video controls. This callback would allow hiding and showing it. 

I looked at `react-native-video-controls` and `react-native-media-controls` for solving this need, but I also need subtitle support that `react-native-video` has baked in.

**Comment by coucoseth** [comment]
just a question here, how can i hide/show my custom controls

**Comment by ashnfb** [comment]
Implemented here for Android:
https://github.com/ashnfb/react-native-video

This isn't possible for iOS without a hack, as there's no public methods provided by Apple

**Comment by freeboub** [comment]
implementation for android will be included in 6.3.0
