### ISSUE TITLE
Change AudioTrack when onload Event fired

### ISSUE THREAD

**Issue by mahmood** [TheWidlarzGroup/react-native-video#2691]
hi, i have a question 
we have anyway to change audio track when onload event fired?

example:
check the available audio tracks on .m3u8 source and then decide to select which one or show a list of available tracks to user with interface and play user's choice

**Comment by freeboub** [comment]
you should be able to set audio track value before starting the playback, but you need to know what is the 'prefered' audio track for user ...
I close the issue, please reopen it if you need more informations
