### ISSUE TITLE
currentTime over duration after seek m3u8 video in android

### ISSUE THREAD

**Issue by huuanhopp** [TheWidlarzGroup/react-native-video#2692]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour
![Screen Shot 2022-05-25 at 14 36 29](https://user-images.githubusercontent.com/67584177/170207264-dd9f54ce-1175-4002-9f79-b340f9cf8c92.png)

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Any sample stream ?

**Comment by freeboub** [comment]
Which player ?

**Comment by hueniverse** [comment]
Closing as this contains no useful information at all. If you want to open a new issue with all the required details, we can look at it then. Issues like this are a waste of resources.
