### ISSUE TITLE
Move startup props into a single configuration

### ISSUE THREAD

**Issue by armands-malejevs** [TheWidlarzGroup/react-native-video#2693]
# Feature Request

Create a new prop where all current props that are only used during initialisation and cannot be changed during runtime into a single configuration prop.

## Why it is needed

This will make it more clear to developer as to which props can be changed during runtime and which props can only be provided when creating the player. This will also simplify the initialisation logic to get rid of `postDelayed` calls etc.

## Tasks

- [x] textTracks (external subtitle tracks)
- [x] contentStartTime
- [X] drm
- [x] Ads props
- [x] bufferConfig
- [x] minLoadRetryCountModifier

**Comment by wood1986** [comment]
@freeboub and @armadilio3. Could you guys please come a list of props which is only for the player initialization? Any change to these props will be ignored after the initialization

`fullscreen`
`controls`

**Comment by wood1986** [comment]
I prefer breaking the people build in alpha after fixing this. I mean throw an exception when people still using original fullscreen and controls. Do you guys have any concerns?

**Comment by freeboub** [comment]
@wood1986 I already flag following props as 'startProps':
- textTracks (external subtitle tracks)
- bufferConfig
- contentStartTime
- drm
- header
- useTunnelingPlayback (a change from my working branch I need to backport)

The good news is that we should be able to implement this change without changing external API.
in Video.js, we can get public input paramters and reformat then to provide it to native.
That's my plan, but I have a lack of time :)

**Comment by freeboub** [comment]
+ localSourceEncryptionKeyScheme for ios shall be moved to source.drm.localSourceEncryptionKeyScheme

**Comment by freeboub** [comment]
> * localSourceEncryptionKeyScheme for ios shall be moved to source.drm.localSourceEncryptionKeyScheme

Done in: https://github.com/TheWidlarzGroup/react-native-video/pull/4136 thank you @KrzysztofMoch

**Comment by freeboub** [comment]
reviewing the description of the ticket, and it seems that headers property implementation is missing: https://thewidlarzgroup.github.io/react-native-video/component/props#headers
I cannot find implementation :/
