### ISSUE TITLE
Improve bufferProgress event

### ISSUE THREAD

**Issue by armands-malejevs** [TheWidlarzGroup/react-native-video#2695]
# Feature Request

Currently `bufferProgress` always sets the start position at 0 which is not the case when playback has moved further than the back buffer. So we need to implement a way to get the real buffer start position.

## Why it is needed

We have `onProgress` that provides basic information about the buffer but in cases where you need to know exactly where the buffer starts and ends we need a way to provide this information. This is useful to prevent making any request or disabling seeking outside of buffer or displaying the actual buffer size and position on the scrub bar.

**Comment by hueniverse** [comment]
@armadilio3 was this fully implemented in the Crunchyroll PR?
