### ISSUE TITLE
Provide a way to specify minimum DRM level for Widevine

### ISSUE THREAD

**Issue by armands-malejevs** [TheWidlarzGroup/react-native-video#2696]
# Feature Request

We need a way to provide a min allowed DRM level. Currently we will fallback to lower level of security if anything fails.

## Why it is needed

This is needed to comply with DRM security level specifications in licensing contracts, since right now we will always fall back to Widevine L3 which might not be allowed in some contracts.

Continued from https://github.com/react-native-video/react-native-video/pull/2689#discussion_r879821439

**Comment by freeboub** [comment]
Following PR may help (or not, but it seems related) https://github.com/react-native-video/react-native-video/pull/2740

**Comment by KrzysztofMoch** [comment]
You can get now widevine level via `VideoDecoderProperties.getWidevineLevel()`
