### ISSUE TITLE
How to float a View layer in the video?

### ISSUE THREAD

**Issue by qingfeng** [TheWidlarzGroup/react-native-video#27]
thanks :beer:

**Comment by brentvatne** [comment]
@qingfeng - you should just be able to use `position: absolute` to position any view over top of the video. Check out the [VideoPlayer](https://github.com/brentvatne/react-native-video/tree/master/Examples/VideoPlayer) example and rotate it to landscape to see that the controls are overlayed :smile:

**Comment by qingfeng** [comment]
OK! thanks :beer:
