### ISSUE TITLE
Make Video player minimize if user go to another screen

### ISSUE THREAD

**Issue by puneetkansal04** [TheWidlarzGroup/react-native-video#2700]
I am looking for a functionality so that if user will go to another screen video still play in a modal screen way. and user can move it anywhere. I need a overview on it that how can i make it. Or is it available in the react-native-video?

**Comment by hueniverse** [comment]
That's outside the scope of this module. You can use the video player component inside a RN component and then manipulate that.

**Comment by freeboub** [comment]
@puneetkansal04 maybe this ticket can help : https://github.com/react-native-video/react-native-video/issues/2605
