### ISSUE TITLE
IOS native player visible three dots menu (controls={true})

### ISSUE THREAD

**Issue by nikunjdhamelia** [TheWidlarzGroup/react-native-video#2702]
Hi,

I am trying to how to visible the ios side three dots menu but not visible, so how to show this menu?

attached screenshot please find and check.

Platform: IOS

Thanks.
![IosDots](https://user-images.githubusercontent.com/30178834/170811861-62045b0b-bd29-4f99-8e6a-aee43177f17a.jpeg)

**Comment by KrzysztofMoch** [comment]
This controls are specific for web - I don't think so we can do it with AVPlayer
