### ISSUE TITLE
App Crashing when running it 'Could not find method compile()'

### ISSUE THREAD

**Issue by Leotheluck** [TheWidlarzGroup/react-native-video#2703]
Hello,

I have a React Native App where I just installed react-native-video, I followed the steps and added 
`compile project(':react-native-video')
    implementation "androidx.appcompat:appcompat:1.0.0"`
to the android/app/build.gradle file inside dependencies, when I do npx react-native run-android it crashes and throws this error:
`A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [project ':react-native-video'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

The two lines I showed are located inside the build.gradle file (android/app/build.gradle) and are at the very end of dependencies {}

Help with this would be very much appreciated, thanks! 🙌

**Comment by hueniverse** [comment]
Have you looked at the examples in this repo and the test project in the same org?

**Comment by zekoliman** [comment]
I do everything exactly, I get this error

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [project ':react-native-video'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by freeboub** [comment]
@zekoliman i think you should check builtool version... Which version of react native and react native video do you use ?

**Comment by himanshuthakurmagictym** [comment]
i am facing same issue.

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [project ':react-native-video'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by aristech** [comment]
Same

**Comment by song2park** [comment]
compile has been deprecated since gradel 7.0. try 'implementation' instead of 'compile'.

**Comment by song2park** [comment]
Plus, if you have an error that failed to resolve scalablevideoview after that above, add jcenter() in allprojects/repositories in android/build.gradle. refer to [this](https://github.com/react-native-video/react-native-video/issues/2454)
