### ISSUE TITLE
Player switching to audio-only version, and a black screen will be displayed with text 'Due to low bandwidth, you are now experiencing the audio-only version of this video' 

### ISSUE THREAD

**Issue by poojasolanki9569** [TheWidlarzGroup/react-native-video#2704]
## Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

## Expected behaviour

1. video should be buffer during low bandwidth
2. it should not go audio-only version during low bandwidth

**Comment by freeboub** [comment]
Can you provide video url ?

**Comment by poojasolanki9569** [comment]
@freeboub Thanks for responding,
not a specific url, seeing this issue in .mp4 files,
this screen will be visible,
can you suggest any fix?

<img width="599" alt="Screenshot 2022-06-01 at 5 06 06 PM" src="https://user-images.githubusercontent.com/80685761/171395826-0a39296a-798e-4c78-a74d-9ea41025646c.png">

**Comment by freeboub** [comment]
I think this is a feature of your stream in fact :)
Without the url, i cannot confirm...

**Comment by poojasolanki9569** [comment]
@freeboub  
this is not a feature of stream, we are using the same stream on other platforms and player also, this issue is not there
this is the sample url : [https://cdn2.percipio.com/secure/b/1654177860.bde132c21c200691b0ba82afb340a76314fa57ee/eot/c2e17197-4fe5-4549-a0a5-a005a96c355e/720_2200kps.mp4](url)

can you please check

**Comment by freeboub** [comment]
I cannot access to the stream:

Error 410 signature expired
signature expired

Error 54113
Details: cache-cdg20783-CDG 1654283721 3498987820

Varnish cache server

**Comment by freeboub** [comment]
Any possibility of reproduction? Or can I close this issue ?
