### ISSUE TITLE
ERROR | attributes: Missing required attribute `authors` on master

### ISSUE THREAD

**Issue by t1gu1** [TheWidlarzGroup/react-native-video#2705]
# Bug

Version: On the last master only.

## To reproduce
- Be sure to cleanup all your lock files and pod .lock file too.
- Use master on your package.json `"react-native-video": "react-native-video/react-native-video#master",`
- Install packages
- do a pod install in the IOS folder

## Description

Since a change, a pod install don't works anymore.

I got that error message:
```
[!] The `react-native-video` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | description: The description is equal to the summary.
```

That was a bug fixed in 2016.
Ref: https://github.com/gre/gl-react-native-v2/issues/94

## The bug source / file

The change that cause the bug: https://github.com/react-native-video/react-native-video/commit/4eeabe4e221e3b812bb9d6e30bdc5bf5e5cc1c14

## Solution
Add the `authors` field back.

---

@hueniverse, I'll let you close this bug I guess if you do the changes.

**Comment by hueniverse** [comment]
Thanks but next time please search for existing issues as this was already reported and a PR submitted.

**Comment by t1gu1** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/12479055/171219068-96959fec-6acd-4e8f-8d58-0f74a28c3d0d.png">

I guess i'll remove `is:issue` next time I search.
