### ISSUE TITLE
Not able to play normal mp4 video when passed to uri.

### ISSUE THREAD

**Issue by AkashGoindi** [TheWidlarzGroup/react-native-video#2707]
### Current behavior
Video not getting played when passed to uri as a string.  Sample video is working on web. Also when passing video source from local directory, it works.

### Reproduction steps
 * Install react-native-video
* copy the basic example from github repo and change the source to video string. eg... http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

### Expected behavior
It should play as it is getting played with local path video.

### Platform
Which player are you experiencing the problem on:
* iOS
* 
### Video sample
[If possible, include a link to the video that has the problem that can be streamed or downloaded from.](http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4)

My basic code:

export default RewardsScreen = () => {
  return (
    <Video source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
      ref={(ref) => {
        this.player = ref
      }}
      controls={true}
      poster='https://baconmockup.com/300/200/'
      paused={false}
      onBuffer={this.onBuffer}
      onError={this.videoError}
      style={{
        height: 350,
        width: 400
      }} />
  )
}

**Comment by kim8823** [comment]
Does audio play for you?
Seems like I've run into the same issue, nothing shows on screen but audio still plays.

**Comment by AkashGoindi** [comment]
I actually got it resolved couple of hours back. In info.plist i have appended - Allow Arbitrary Loads to true and it worked!
And to answer your question, no the audio wasn't playing either.

**Comment by imamabdulazis** [comment]
For the context that @AkashGoindi mentioned,
add this to your `Info.plist`.

```
     <!-- Load local video uri -->
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
```
