### ISSUE TITLE
How to provide an array of urls with diffrent resolution of same video to play the one according to the updating internet bandwidth

### ISSUE THREAD

**Issue by manglesh-0605** [TheWidlarzGroup/react-native-video#2711]
### Current behavior
Could not find the implimentation

### Reproduction steps
no an issue as such may be i am missing some docs , i tried but could't find any implimentaion.

### Expected behavior
To give an aarray of urls and update url while playing video with updating internet bandwidth

### Platform
Which player are you experiencing the problem on:
All

**Comment by freeboub** [comment]
This is not supported... It is easier to use dash or HLS to support such feature!
I close the ticket as it is not an easy task (and not very useful in my opinion), but if you want to open a PR, it is welcome

**Comment by kelvin-at-nova** [comment]
use corsi-it/react-native-video-controls, they have modified the code to allow you to change to different resolutions.
The way to use it: put an array of videos with different resolutions into it, with the HLS being the first item in the array, set its resolution to 'Auto', others to '720p', '1080p'...etc, then set videoResolution={'Auto'} so it displays 'Auto' when you play the video, but when user presses it, it turns into '720p', '1080p'...etc

**Comment by ylli2000** [comment]
use corsi-it/react-native-video-controls, they have modified the code to allow you to change to different resolutions.
The way to use it: put an array of videos with different resolutions into it, with the HLS being the first item in the array, set its resolution to 'Auto', others to '720p', '1080p'...etc, then set videoResolution={'Auto'} so it displays 'Auto' when you play the video, but when user presses it, it turns into '720p', '1080p'...etc
