### ISSUE TITLE
[andorid]undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

### ISSUE THREAD

**Issue by emisty** [TheWidlarzGroup/react-native-video#272]
react-native 0.29.2
react-native 0.8.0 
how to solve this

**Comment by josh-deprogram** [comment]
Trying to resolve this also. Rolled back to react-native 0.28 still the same issue. Is this supported on these builds? Have tried rnpm linking and manually adding in xcode to build phases but no joy :(

**Comment by emisty** [comment]
i resolve this, add new videopackage()  in mainactivty

**Comment by arilitan** [comment]
@jzhbiao can you please paste the exact line of code. I'm getting the same error, would really help! thanks

**Comment by timvanp** [comment]
```
    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactVideoPackage()
        );
    }
```

also running ./android/gradlew clean helped me :D

**Comment by ghost** [comment]
#284

**Comment by ghost** [comment]
I have the same problem.
Was it a fix?
