### ISSUE TITLE
iOS 15 player not working.

### ISSUE THREAD

**Issue by KestasVenslauskas** [TheWidlarzGroup/react-native-video#2725]
# Bug
I tried running [react-native-video-test](https://github.com/react-native-video/react-native-video-test).
On android it works fine. But i get this error on iOS:
`{"error": {"code": -11800, "domain": "AVFoundationErrorDomain", "localizedDescription": "The operation could not be completed", "localizedFailureReason": "An unknown error occurred (-1022)", "localizedRecoverySuggestion": ""}, "target": 73}`

**I managed to make it work by creating iOS emulator with iOS 14.4**

## Platform
iOS 15.5

## Environment info
[react-native-video-test](https://github.com/react-native-video/react-native-video-test)

Library version: 5.2.0 (also tried 6.0.0+)

## Steps To Reproduce
1. Checkout repo: [react-native-video-test](https://github.com/react-native-video/react-native-video-test)
2. yarn
3. run ios

## Expected behaviour
1. Player showing video

## Video sample
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

**Comment by hueniverse** [comment]
What about other v15.x versions?

**Comment by KestasVenslauskas** [comment]
@hueniverse On v15.x iOS versions I only get onError callback from Video component with error mentioned above.

**Comment by kelvinvincit** [comment]
Make sure you have Erased All Content and Settings if you are using the iOS simulator after installation.
Also, a https url link is a must. Turns out using http link is the reason this error shows up.

Try `https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4` instead

[https://github.com/react-native-video/react-native-video/issues/1940#issuecomment-682687761](url)

**Comment by ghost** [comment]
The same problem here.
```
{
  error: {
    code: -11800,
    domain: AVFoundationErrorDomain,
    localizedDescription: The operation could not be completed,
    localizedFailureReason: An unknown error occurred(560557684),
    localizedRecoverySuggestion:
  },
  target: 16259
}
```
I have no idea what causes this problem. It occured on both platforms iOS 15.5 and Android 12.

**Comment by rahulje9** [comment]
I am getting the same error on iOS 15 and below. working fine on iOS 16

**Comment by pietroanello** [comment]
Same error here! Has anyone found a solution?

**Comment by mohamed2m2018** [comment]
same issue

**Comment by Vishal-V12** [comment]
Same issue face

**Comment by gaganpreet-scalex** [comment]
Any fix for this issue?

**Comment by mohamed2m2018** [comment]
What fixed it for me was just to restart the simulator

**Comment by sanduluca** [comment]
Had the same problem. Just replaced http with **https**. 
I guess you have to allow insecure load for ios and android. Something like this, dont remember exactly
```xml
<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
<true/>
```
