### ISSUE TITLE
Could not play local video file on Windows platforms

### ISSUE THREAD

**Issue by ChingHong19980819** [TheWidlarzGroup/react-native-video#2726]
When I try to parse local file to source, it could not play it.

**Code**

<Video
          source={{
            uri: 'file:///D:/Hello World.mp4',
          }}
          style={{width: 300, height: 300}}
          controls={true}
/>

Versions-**5.2.0**
Platform-**Windows**

**Comment by luisruelas** [comment]
Is there any update on this? I am having the same problem.
BoradFilesystem permissions granted.
Version 5.2.1
Windows

**Comment by ghost** [comment]
I'm not certain, but this might be related to the special permissions that UWP applications require to access the file system. Could you provide the error logs?
