### ISSUE TITLE
Build failing on iOS after upgrading to v6.0.0-alpha.2, "CompileSwift normal x86_64"...

### ISSUE THREAD

**Issue by mitchdowney** [TheWidlarzGroup/react-native-video#2727]
# Bug

Trying to upgrade from 5.2.0 to react-native-video 6.0.0-alpha.0 to build in our project, but I'm running into a build error everytime. I've tried cleaning and reinstalling numerous times. Any ideas what could be going wrong?

```bash
The following build commands failed:
        CompileSwift normal x86_64 /Users/mitch/Repos/podverse-rn/node_modules/react-native-video/ios/Video/RCTVideoManager.swift (in target 'react-native-video' from project 'Pods')
        CompileSwift normal x86_64 /Users/mitch/Repos/podverse-rn/node_modules/react-native-video/ios/Video/RCTVideoPlayerViewController.swift (in target 'react-native-video' from project 'Pods')
        CompileSwift normal x86_64 /Users/mitch/Repos/podverse-rn/node_modules/react-native-video/ios/Video/RCTVideoPlayerViewControllerDelegate.swift (in target 'react-native-video' from project 'Pods')
        CompileSwift normal x86_64 /Users/mitch/Repos/podverse-rn/node_modules/react-native-video/ios/Video/Features/RCTVideoSave.swift (in target 'react-native-video' from project 'Pods')
        CompileSwift normal x86_64 /Users/mitch/Repos/podverse-rn/node_modules/react-native-video/ios/Video/Features/RCTVideoUtils.swift (in target 'react-native-video' from project 'Pods')
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'react-native-video' from project 'Pods')
(6 failures)
```

## Platform
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 373.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/Repos/podverse-rn/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.2

## Steps To Reproduce

I don't have time to create a test repo at the moment...but here is a link to the Podfile I am attempting to use: https://gist.github.com/mitchdowney/ced43e3a235a6af889a744673f78b934

## Expected behaviour

App should build for iOS.

**Comment by mitchdowney** [comment]
Oh, I'm using react-native v0.66.1 but docs say:

> Version 6.x recommends react-native >= 0.68.2. For older versions of react-native, [please use version 5.x](https://github.com/react-native-video/react-native-video/tree/v5.2.0).

I'll try to see if upgrading react-native fixes the build issue.

**Comment by hueniverse** [comment]
Did you follow the static linking instructions here: https://github.com/react-native-video/react-native-video/blob/master/API.md#enable-static-linking-for-dependencies-in-your-ios-project-podfile

**Comment by mitchdowney** [comment]
@hueniverse sorry, we're stuck at the moment because we aren't on react-native >= 0.68.2. I tried upgrading a while ago and ran into issues. I'm going to close this issue since I didn't complete the minimum requirements, so it might not be a real bug. Thanks though

**Comment by vaibhavgehani** [comment]
I faced the same issue and resolved using
Run sudo arch -x86_64 gem install ffi

and then goto ios folder and run arch -x86_64 pod install.
It will work.
