### ISSUE TITLE
Support fast seek (Video is not seeking while sliding the control slider without touching up.)

### ISSUE THREAD

**Issue by bolan9999** [TheWidlarzGroup/react-native-video#2728]
# Feature Request

Video is not seeking while sliding the control slider bar without touching up.

## Why it is needed

I'd like to preview when sliding the bar， at least in the short video.

## Possible implementation

Is it possible to support it on android and iOS?  Maybe Animated Value can do it? Just like `progress` in `lottie-react-native`

### Code sample

Not at this moment.

**Comment by hueniverse** [comment]
This is best implemented in a custom scrubber.

**Comment by bolan9999** [comment]
But how？The `seek` method is not fast, I can't do it.

**Comment by hueniverse** [comment]
Have you looked at [react-native-video-controls](https://www.npmjs.com/package/react-native-video-controls)?

**Comment by bolan9999** [comment]
I'd like to preview when sliding the bar. it does not fit me.

**Comment by hueniverse** [comment]
Use `scrubbing`
