### ISSUE TITLE
IOS app crash due to increase in CG Raster Data

### ISSUE THREAD

**Issue by hrishi-neo** [TheWidlarzGroup/react-native-video#2731]
I've a flatlist in which i'm loading videos with react-native-video. On Android its working perfect but in Ios it seems to crash after scrolling a bit. When I checked with Instruments the CG Raster Data was shooting up to 800mb+ which was resulting in ios app crash.
Can anyone help me with this? Thanks in advance!

**Comment by hueniverse** [comment]
Flatlist are a known issue. See https://github.com/react-native-video/react-native-video/issues/2668
