### ISSUE TITLE
Port react-native-video-controls

### ISSUE THREAD

**Issue by hueniverse** [TheWidlarzGroup/react-native-video#2732]
There are many requests for improved controls (as well as many issues about controls not working correctly). A simple solution is to port https://github.com/itsnubix/react-native-video-controls into this module and make it a bit more customizable. This will be an optional controls layer that's consistent across iOS and Android, implemented in RN/JS.

**Comment by freeboub** [comment]
I fully agree, butI think it make sense to keep it outside of react native video...
In my mind RNV, should handle only video part, not controls... But when reviewing ticket, I feel a lot of people uses embedded controls :/ 
In fork I use, I moved all exoplayer calls in a dedicated thread, (I implement custom controls) but when I try to reactivate controls it was not possible because it works only if exoplayer is instantiated in UI thread:/

**Comment by KestasVenslauskas** [comment]
What about lock screen controls?

**Comment by vargajacint** [comment]
I can relate the MediaControl aka "lock screen" control implementation. Right now I using the `react-native-media-controll` package

**Comment by LunatiqueCoder** [comment]
@hueniverse  Hello!

I've completely rewritten react-native-video-controls to [react-native-media-console](https://github.com/criszz77/react-native-media-console) with TypeScript, solved all the issues I could find and also added tvOS support. Check it out.

**Comment by freeboub** [comment]
@criszz77 for your information, I open this PR to promote your package ;) https://github.com/react-native-video/react-native-video/pull/2858/files#diff-e10860e1f3d00aa77abf419e46d6653ab8a1a1709982b6b244038fe8d93803da
Feel free to complete description

**Comment by LunatiqueCoder** [comment]
@freeboub Thank you very much! Really appreciate it :) Cheers

**Comment by sam1463** [comment]
> I can relate the MediaControl aka "lock screen" control implementation. Right now I using the `react-native-music-control` package

Unfortunately that library was archived yesterday, with the author suggesting switching to react-native-track-player. That works great for audio playback but I don't think it will work for this use case of lock screen controls for video played with this library.
Any other suggestions for lock screen controls? Would that be something to consider supporting as part of this library as well?
Also might want to update the docs for this library to either remove the reference to that music-controls library or update it to point out that the library is now archived and not maintained.

Happy to create a separate issue for this if I'm muddying the waters, I just saw this issue when searching for existing issues related to lock screen support.

**Comment by freeboub** [comment]
@sam1463 Thank you for the info !
Maybe a good thing to do is to import repository of react-native-music-control in react-native-video community ?!
Unfortunnatly, I don't have better library to use, and as you said, react-native-track-player doesn't play video and it is in conflict with react-native-video as it also use exoplayer...

**Comment by freeboub** [comment]
Notice I am also wondering importing a unified video player UI in react-native-video community would be a good thing.
Controls between each platform are not unified and are a nighmare to maintain where react-native-video should handle only video. (that is only my point of view)
