### ISSUE TITLE
Build failing (after successful npm installation)

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [TheWidlarzGroup/react-native-video#2735]
# Bug
On react native version 0.66.4, I installed react-native-video 5.2.0, but while taking the build (on android), getting this error:
<img width="1307" alt="Screenshot 2022-06-22 at 4 36 57 PM" src="https://user-images.githubusercontent.com/82080446/175014532-4216b5fe-94f3-49fb-8094-29fe8e93bd69.png">
<img width="1371" alt="Screenshot 2022-06-22 at 4 37 28 PM" src="https://user-images.githubusercontent.com/82080446/175014631-558d797f-1c6a-48d8-9bc1-507a671a4521.png">

## Platform
Android emulator

## Environment info
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found

Library version: 5.2.0

**Comment by freeboub** [comment]
Please refer to this issue for a temporary solution: https://github.com/react-native-video/react-native-video/issues/2729

**Comment by vinaygregoryjohn183** [comment]
@freeboub The temporary fix didn't solve my issue.
