### ISSUE TITLE
No sound on iOS 16 

### ISSUE THREAD

**Issue by matinzd** [TheWidlarzGroup/react-native-video#2736]
# Bug
This bug is a bit weird since if you switch between apps and then come back, sometimes sound will also come back but normally audio is not working on early versions of iOS 16. Not sure if it's OS-level problem but let's have this issue opened.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info
iOS Version: 16

React native info output:

```bash
 // paste it here
```

Library version: 6.0.0-alpha.1

## Steps To Reproduce
1. Start playing video on iOS 16 device
 
## Expected behaviour
Have sound 

## Reproducible sample code
<Video source={{ uri: 'example.com' }} />

## Video sample
Any video

**Comment by matinzd** [comment]
UPDATE:
@hueniverse 
It was because silent mode was active and I have to set `ignoreSilentSwitch={'ignore'}`.

**Comment by hueniverse** [comment]
@matinzd thanks for following up!

**Comment by khushal87** [comment]
Do you guys, by any chance, face this issue where if you hard refresh the app and if your silent mode is on, the audio is not audible?
