### ISSUE TITLE
Build failing (after successful npm installation) 

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [TheWidlarzGroup/react-native-video#2738]
# Bug
On react native version 0.66.4, I installed react-native-video 5.2.0, but while taking the build (on android), getting this error:
<img width="1307" alt="Screenshot 2022-06-22 at 4 36 57 PM" src="https://user-images.githubusercontent.com/82080446/175209514-65830f2a-41a0-4baa-977b-d0ac20b0a4bf.png">
<img width="1371" alt="Screenshot 2022-06-22 at 4 37 28 PM" src="https://user-images.githubusercontent.com/82080446/175209528-fb8c5e75-5697-4bb8-8f83-257d2362ef07.png">

## Platform
Android emulator

## Environment info
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 32.0.0, 32.1.0
      System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-32 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found

Library version: 5.2.0

**Comment by vinaygregoryjohn183** [comment]
The fix suggested in: https://github.com/react-native-video/react-native-video/issues/2735#issuecomment-1163012729 didn't fix my issue.

**Comment by freeboub** [comment]
@vinaygregoryjohn183 can you clarify the new error please ?

**Comment by surajheadsup** [comment]
Hello, I am getting the same Error

**Comment by freeboub** [comment]
@surajheadsup so the fix is not well applied... I can propose you to try the V6 pre release which doesn't have this issue.

**Comment by vinaygregoryjohn183** [comment]
@freeboub @surajheadsup The error was due to a dependency conflict mentioned in: https://githubhot.com/repo/Netvent/storyly-mobile/issues/158. I removed the storyly package, and the build was successful.

**Comment by freeboub** [comment]
Thank you for the update! Let's close the ticket
