### ISSUE TITLE
Documentation???

### ISSUE THREAD

**Issue by iKronyck** [TheWidlarzGroup/react-native-video#2739]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
The documentation is in readme.md file.
You can find main entry here https://github.com/react-native-video/react-native-video
