### ISSUE TITLE
Native component for "RCTVideo" does not exist

### ISSUE THREAD

**Issue by ramsestom** [TheWidlarzGroup/react-native-video#274]
On android (5.1.1), my app crash with this error:

Native component for "RCTVideo" does not exist

I followed the install process exept that in my "MainActivity.java" file, I didn't add 
`.addPackage(new ReactVideoPackage())`
Under 
`.addPackage(new MainReactPackage()):`

as there is no `.addPackage(new MainReactPackage()):` in my "MainActivity.java" file....

Here is the content of my  "MainActivity.java" file:

```
package com.testapp;

import com.facebook.react.ReactActivity;
import com.brentvatne.react.ReactVideoPackage;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "TestApp";
    }
}
```

don't know if my issue is related to this missing "addPackage" call or not.

**Comment by jondbm** [comment]
I had this issue and I think I've fixed it - I think the docs are out of date for the latest RN versions.
Instead of making changes to MainActivity.java, make changes to MainApplication.java

At the top, add:
import com.brentvatne.react.ReactVideoPackage;

Then in the getPackages section, add this to the list:
new ReactVideoPackage()

I don't know if that is the actual fix, but it worked for me anyway!

**Comment by magicspon** [comment]
I've also got this issue.

managed to fix using @jondbm method. For anyone who doesn't write Java (like me) the getPackages() bit should look something like this

```
protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ReactVideoPackage()
      );
    }
```

**Comment by ghost** [comment]
See solution from @johndbm. This can be closed.

**Comment by arasemami** [comment]
Hi guys, I have the same issue,
package.json  -->

```  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-video": "^3.2.1",
    "react-native-video-controls": "^2.2.3"
  },
```

MainApplication.java ----->

```
import com.brentvatne.react.ReactVideoPackage;
```

```   @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactVideoPackage()
      );
    }```


settings.gradle ---->

`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
`
