### ISSUE TITLE
Could you mention that react-native-video never support youtube url?

### ISSUE THREAD

**Issue by DonRyu** [TheWidlarzGroup/react-native-video#2742]
# Feature Request
Mention that this library can't run youtube url

## Why it is needed

Could you mention that react-native-video never support YouTube URL?
I spent a lot of time to play youtube video using this library
This library document just say video URL
There is no mention that this library can't run youtube url
Please mention it if you can't

**Comment by freeboub** [comment]
Please open a documentation pull request
