### ISSUE TITLE
Full screen button is missing, paused property does not stop the video, and "Unrecognized media format" error in android exoplayer.

### ISSUE THREAD

**Issue by liellevibob** [TheWidlarzGroup/react-native-video#2745]
# Bug
Hello, Im facing 3 problems with react-native-video, with android platform.
1. I want to watch the video in full screen, but the full screen button does not appear (picture attached),  any ideas how to watch in full screen?
![Screenshot_20220626-164103_Bob](https://user-images.githubusercontent.com/104358608/175818363-45c9912b-7a4d-4b37-990c-449ec0243695.jpg)

3. Trying to stop a video (that has already started by clicking Play) by changing its state with `this.setState({ paused: false })`, **works well on iOS but on Android does not**, any ideas?

4. Mp4 video runs and works well but throws the following error: `{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}} `  from onError callback, does anyone have any idea why this error is thrown?

For all these I'm using android **exoplayer android**, here is my <Video /> component: 

```
          <Video
                    ref = { this.onGetVideoPlayerRef }
                    paused = { this.state.paused}
                    fullscreen = { true }
                    source = {{ uri: videoItem?.url }}
                    poster = { videoItem?.thumbnailUrl || '' }
                    controls = { true }
                    resizeMode = 'cover'
                    pictureInPicture = { false }
                    onError = { (error) =>  this.ignoreSomeErrorInReactNativeVideo(error.error.errorString) && this.setState({ showVideoError: true }) }
                />

```
## Platform

* Android - GalaxyS21
## Environment info
react-native: "0.67.4"
react-native-video: "5.2.0"

**Comment by Prince-AppsTango** [comment]
please help me , i am facing same problem

**Comment by cejuo** [comment]
The third problem is happening to me too. Doesn't show video.
```json
{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}
```
Any ideas?

EDIT:
I've downgraded to version `5.1.1` and now this error happens:

```json
{
  "error": {
    "errorException": "com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403",
    "errorString": "ExoPlaybackException type : 1"
  }
}
```

I'll leave here the `<Video...` props in case someone wants to try:

```tsx
<Video
  repeat
  source={{
    uri: item.manifestPath,
  }}
  drm={{
    type: DRMType.WIDEVINE,
    licenseServer: item.licenseServer,
    headers: {
      "X-AxDRM-Message": item.licenseToken,
      "Transfer-Encoding": "Chunked",
      "Content-Type": "application/octet-stream",
    },
  }}
  ref={(ref) => {
    //@ts-ignore
    this.player = ref;
  }}
  onBuffer={(buffer) => console.log(JSON.stringify(buffer))} // Callback when remote video is buffering
  onError={(error) => console.log(error)} // Callback when video cannot be loaded
  style={{
    aspectRatio: 16 / 7,
    width: "100%"
  }}
/>
```

**Comment by freeboub** [comment]
@cejuo error 403 is an HTTP error (back issue), not related to this issue. and not an issue in react-native-video

**Comment by freeboub** [comment]
1/ please test following PR for full screen button: https://github.com/react-native-video/react-native-video/pull/2763
2/ please test on master branch I think this is already fixed
3/ seems like a type is missing in source

**Comment by freeboub** [comment]
Fullscreen button added in 6.0.0-alpha.2
