### ISSUE TITLE
Prop pictureInPicture not working as we expect

### ISSUE THREAD

**Issue by irion94** [TheWidlarzGroup/react-native-video#2746]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-video@5.2.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-video/ios/.DS_Store b/node_modules/react-native-video/ios/.DS_Store
new file mode 100644
index 0000000..d1a9544
Binary files /dev/null and b/node_modules/react-native-video/ios/.DS_Store differ
diff --git a/node_modules/react-native-video/ios/Video/RCTVideo.m b/node_modules/react-native-video/ios/Video/RCTVideo.m
index a757c08..e6b8e50 100644
--- a/node_modules/react-native-video/ios/Video/RCTVideo.m
+++ b/node_modules/react-native-video/ios/Video/RCTVideo.m
@@ -907,7 +907,8 @@ static int const RCTVideoUnset = -1;
 }
 
 - (void)setupPipController {
-  if (!_pipController && _playerLayer && [AVPictureInPictureController isPictureInPictureSupported]) {
+//    setup Pip controller only when _pictureInPicture === true
+  if (_pictureInPicture && !_pipController && _playerLayer && [AVPictureInPictureController isPictureInPictureSupported]) {
     // Create new controller passing reference to the AVPlayerLayer
     _pipController = [[AVPictureInPictureController alloc] initWithPlayerLayer:_playerLayer];
     _pipController.delegate = self;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Solution is not perfect cause it's not reactive ( once we render VideoPlayer we cant change this prop ) but give us possibility to permanently turn of pip.

[EDIT]
Steps to reproduce. 
I'm using Video as the application background. So I want to use playInBackground, playWhenInactive to true, and pictureInPicture to false.
In the above case when I move the app to the background PiP is showing for a while and disappears.

**Comment by Isaiah-Simon** [comment]
I am also seeing this issue on 5.2.0 as well as on 6.0.0-alpha.0 and 6.0.0-alpha.1. It says it was previously fixed [here](https://github.com/react-native-video/react-native-video/pull/2645) but I think that was overwritten by the [swift migration](https://github.com/react-native-video/react-native-video/pull/2527) as the check for `_pictureInPicture` no longer exists in [setupPipController](setupPipController) in swift.

**Comment by Deodes** [comment]
Same issue I met on 5.2.0. Added checking for `_pictureInPicture` in `setupPipController`, now there is no window with video on my screen, when I go background. But when I manually change `pictureInPicture` prop, nothing happens..

**Comment by Deodes** [comment]
I did research on it. And I have 1 idea, how it is possible to implement this feature right. We can setupPipController and clean it when we set pictureInPicture to true/false. I've tried to do it recently, and it works. But I met a problem, that it starts working on third state change: 

**false(default) --> true(nothing happens) --> false(clean pipController) --> true(now it works)**

**Comment by codebin-pune** [comment]
`pictureInPicture={false}` is also not working for me.

**Comment by tsheaff** [comment]
For me this works on `6.0.0-alpha.4`, but wasn't working on `5.x`

**Comment by jcksncllwy** [comment]
This was an issue for me in `5.2` but is now working fine on `6.0.0-alpha.6`

**Comment by freeboub** [comment]
work on 6.0.0, so let's close this issue
