### ISSUE TITLE
No PictureInPicture button

### ISSUE THREAD

**Issue by moseslucas** [TheWidlarzGroup/react-native-video#2749]
# Bug

I am using react-native-video `5.1.1` and would like to use `pictureInPicture`. 
I added it in the props but the button for **pip** is not showing on both simulator and actual iPhone device iOS 15.

But it's working on iPad simulator with iOS 15

## Platform
Both simulator and actual iPhone device iOS 15.

Which player are you experiencing the problem on:
* iOS

## Environment info
 react-native-video `5.1.1`
 react-native `0.64.0`

Library version:  `5.1.1`

## Steps To Reproduce

```
        <Video
          source={{uri}}
          controls
          posterResizeMode="center"
          pictureInPicture
          onPictureInPictureStatusChanged={() => alert('pip')}
        />
```

## Expected behaviour

1. Atleast show the PIP button from the player controls

## Photo sample
![IMG_2463](https://user-images.githubusercontent.com/30344224/176088335-0c24e6b9-ec34-41cb-b841-d0fa0358fbe9.PNG)

**Comment by tbaustin** [comment]
We have done the same thing and don't see a PiP button either. We tried manually making a button that was attached to state and that didn't seem to work either. We are kind of stuck here. Just going through the source code atm to see if we can find anything. 

@moseslucas any luck on this?

**Comment by watadarkstar** [comment]
Same issue here, @moseslucas any luck?

**Comment by Amzlov123** [comment]
This is expected according to this StackOverFlow post: https://stackoverflow.com/questions/68939003/is-picture-in-picture-possible-on-ios-simulator

AVPictureInPictureController.isPictureInPictureSupported() always returns false on the iPhone simulator, but PiP is always available on iPad simulators

**Comment by freeboub** [comment]
Thank you @Amzlov123 So let's close this ticket.
@moseslucas  @KrzysztofMoch  If you disagree, I can reopen it.
