### ISSUE TITLE
Meet "AVFoundationErrorDomain" error when loading a remote url

### ISSUE THREAD

**Issue by beside4ever** [TheWidlarzGroup/react-native-video#275]
Here's my code:
`source={{uri: "http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4"}}`

Then it triggered loadError function which shows error object like this:
`{ error: { domain: 'AVFoundationErrorDomain', code: -11800 },
      target: 14 }
`

I've made a huge search and still have no idea.

**Comment by mroswald** [comment]
Look at the xcode log / `react-native log-ios` if there is any warning about http and insecure load of urls or any other hint.

**Comment by ndao** [comment]
i'm getting the same error. nothing in log.

i had to NSLog(@"%@", _playerItem); in RCTVideo.m to print out the real error
`Transport security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file`

and found the solution here. basically you have to enable http or use https
http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by ghost** [comment]
This can be closed.

**Comment by kaixinfu** [comment]
i also have the same error

**Comment by mishudark** [comment]
here the same error, in the logs only 

```
Jan 28 10:48:57 AFSPT-4 com.apple.CoreSimulator.SimDevice.9C33E4E2-7519-408C-93AF-396121899EC3[54635] (com.apple.videosubscriptionsd[1165]) <Warning>: Service exited with abnormal code: 1
Jan 28 10:48:57 AFSPT-4 com.apple.CoreSimulator.SimDevice.9C33E4E2-7519-408C-93AF-396121899EC3[54635] (com.apple.videosubscriptionsd) <Notice>: Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by OmarBasem** [comment]
same error

**Comment by ghost** [comment]
> This can be closed.

I take it back. LOL. Man, I feel for you guys. Anyone have a resolution?

**Comment by laurent22** [comment]
Same error too when loading an https URL. Haven't found the reason yet.

**Comment by ghost** [comment]
I also can't play https video URLs. Getting this kind of error objects:
```javascript
{
    error: {
        domain: "AVFoundationErrorDomain", 
        code: -11828
    },
    target: 109
}
```

**Comment by CHaNGeTe** [comment]
11828 = AVErrorFileFormatNotRecognized

Can you share your stream url?
Probably it has no extension, or server is not sending the appropiate Content-Type header

**Comment by CHaNGeTe** [comment]
Closing the issue until more info

**Comment by gfpacheco** [comment]
I'm also facing this issue, I'm using this video:

https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

It seems they're sending all the correct headers:

```
accept-ranges: bytes
access-control-allow-origin: *
access-control-expose-headers: origin, range
alt-svc: quic=":443"; ma=2592000; v="46,43,39"
cache-control: public, max-age=3600
content-length: 158008374
content-type: video/mp4
date: Tue, 06 Aug 2019 20:16:19 GMT
etag: "cab08b36195edb1a1231d2d09fa450e0"
expires: Tue, 06 Aug 2019 21:16:19 GMT
last-modified: Thu, 05 Dec 2013 18:43:53 GMT
server: UploadServer
status: 200
```

**Comment by JeffJassky** [comment]
I was still having this issue but this solved it

source={{
    uri: "your uri here",
    type: 'mp4'
}}

**Comment by ancyrweb** [comment]
Had the same problem when reading a file fetched with RNFetchBlob. The issue was the missing extension. RNFetchBlob by default doesn't save the file with an extension because it doesn't know it, hence the `appendExt` flag. Without the extension, RNVideo (using AVFoundation) wont be able to load your video properly, somehow. 
When I've put the extension in the file name, it just worked.

**Comment by chrisozgo99** [comment]
I'm getting this same issue. Have tried everything and nothing works. It only happens on iOS when I reference a video that was uploaded by an Android device to my AWS S3 server. Videos uploaded by iOS device work fine. If anyone has found a solution I would love to hear it!

**Comment by OmarBasem** [comment]
@chrisozgo99 download the video file, and cache it, then play it locally.

**Comment by chrisozgo99** [comment]
@OmarBasem I tried this. Genius idea honestly! However still only displaying videos from iOS and for videos sent from an Android device still displaying the same error: 
```
error:
code: -11800
domain: "AVFoundationErrorDomain"
```
This problem is crucial for me to solve...if anyone has tried any other solutions that work for this issue please let me know!

**Comment by wsrast** [comment]
@OmarBasem I was having the exact same error message myself and managed to fix at least the Red Screen of Death using @JeffJassky 's suggestion to add the `type: 'mp4'` to the source prop. This does *not* get the video to play in the iOS simulator, though. All I'm getting is a blank video window, which makes me believe that the video is still failing to load. Here's my full tag:

```
      <RNVideo
        ref={mediaRef}
        source={{
          uri: source,
          type: 'mp4'
        }}
        paused={!isPlaying}
        playInBackground
        ignoreSilentSwitch={'ignore'}
        playWhenInactive
        resizeMode="contain"
        style={style}
        onBuffer={onBuffer}
        onError={onVideoError}
        rate={playbackSpeed}
        onProgress={info => onProgress(info.currentTime)}
      />
``` 
One thing to note is that there were no code changes from me on this for quite some time--it just suddenly broke with the -11800 error. Previously, it was working without the `type` value.
