### ISSUE TITLE
Apple airplay is not working with secured video from CloudFront.

### ISSUE THREAD

**Issue by isuru102** [TheWidlarzGroup/react-native-video#2751]
### Current behavior
Airplay is not working with secured video from CloudFront.

Same video is playing on the IOS device as expected without any issue. But when using airplay option to play the video, it is not playing. Seems like header cookie is not passing when the video is playing on the other device.

### Reproduction steps
Here is a sample code.

```
<Video
    key={`video-${mediaUrl}`}
    ref={videoRef}
    source={{
      uri: mediaUrl,
      headers: {
        cookie: mediaCookieString,
      },
    }}
    ignoreSilentSwitch={'ignore'}
    repeat={true}
    controls={false}
    resizeMode={'contain'}
    fullscreenAutorotate={true}
    fullscreenOrientation={'all'}
    style={styles.fullHeight}
    paused={paused}
    onReadyForDisplay={() => setIsBuffering(true)}
    poster={imageUrl}
    posterResizeMode="contain"
    volume={volumeLevel}
    onProgress={throttledSetProgressData}
    muted={
      assetTrack?.trackState === 1 && !assetTrack?.trackPaused
    }
  />
```

### Expected behavior
Video should be playing on the connected device while using Airplay.

### Platform
* iOS

**Comment by rukshanw-xino** [comment]
same issue for me

**Comment by ghost** [comment]
Same issue
Can't airplay private HLS stream

**Comment by luisfuertes** [comment]
Hello, any update?

**Comment by philipbrady13** [comment]
same issue here, i can see the player load on my apple tv device but there is a red disabled icon on the progress bar and playback never begins. has anyone been able to resolve this?

**Comment by philipbrady13** [comment]
im not sure if this will be helpful, but instead of using cookies to access secure videos from cloudfront, we tried using signed urls and airplay is now working great. this may not be an option for everyone, but it solved the problem for us
