### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'resizeMode' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [TheWidlarzGroup/react-native-video#2752]
# Bug

 ERROR  TypeError: Cannot read property 'resizeMode' of undefined, js engine: hermes

  posterResizeMode: Image.propTypes.resizeMode,

## Platform
 android  

Which player are you experiencing the problem on:
* Android

## Environment info

react-native :0.69.1
react : 18.2.0

Library version: x.x.x
    "react-native-video": "^5.2.0",

## Steps To Reproduce

Updated  to react-native 0.69.1

 

## Expected behaviour

work fine

**Comment by drplauska** [comment]
Also getting this error on iOS.

**Comment by drplauska** [comment]
Also getting this on iOS without Hermes.

edit: 
upgrading to `v6.0.0-alpha.1` fixes the problem, just not sure about backwards compatibility.
`yarn add react-native-video@v6.0.0-alpha.1`

**Comment by freeboub** [comment]
I confirm this issue is linked to react-native 0.69 and has been fixed on master (V6.0.0-alpha.1) let's close this ticket

**Comment by Zestpond** [comment]
But android video has been black screen

**Comment by freeboub** [comment]
@Zestpond this is another issue...

**Comment by acuervov** [comment]
I still have this issue on iPhone. I get the same error and I'm using this version (V6.0.0-alpha.1)

**Comment by freeboub** [comment]
I have find a way to reproduce the issue. I will investigate

**Comment by freeboub** [comment]
Ok, i confirm that this issue is fixed in last releases. This was due to imagePropType which is deprecated

**Comment by rodrigobertolottizinsp** [comment]
Im still facing this issue with react 0.70.5 and  v6.0.0-alpha.1

**Comment by freeboub** [comment]
@rodrigobertolottizinsp upgrade react native video please
