### ISSUE TITLE
Unable to play next videos after finishing current video.

### ISSUE THREAD

**Issue by teefortayyab** [TheWidlarzGroup/react-native-video#2754]
# Bug

I have been using react-native-video for playing multiple videos in my application. In the first time, the video is loaded and playing perfectly fine. but when the URI of the video is changed via State after the current video is completely finished, It is unable to load and play the video. Previously it was working fine but Now it's not working.

## Platform

- iOS
- Android

Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 173.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.12.1 - ~/Desktop/Devigital/spotlove/node_modules/.bin/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: "react-native-video": "^5.2.0"

## Steps To Reproduce

1. After completing the first video, the URI of Video component must be changed, So that it will play the next video.

## Expected behaviour

1.After completing the First video, Video component should render/load the second video after dynamically change the URI.

**Comment by freeboub** [comment]
Need more info to reproduce the issue. It works fine on basic sample, at least on Android...
