### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.resizeMode')

### ISSUE THREAD

**Issue by Amancoder006** [TheWidlarzGroup/react-native-video#2755]
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.resizeMode')

**Comment by freeboub** [comment]
Fixed in V6

**Comment by paprikka** [comment]
@freeboub Are there plans to include the fix in v5.x or are we waiting for v6 to be released?

**Comment by hueniverse** [comment]
There are no resources to work on a 5.x release so 6.x is the only focus.
