### ISSUE TITLE
sometimes  time is slow than real playback time  on onprogress callback.

### ISSUE THREAD

**Issue by wuchuifeng** [TheWidlarzGroup/react-native-video#2756]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Ticket without description nor reproduction step and platform are not valid ...
