### ISSUE TITLE
No matching configuration of project :react-native-video was found

### ISSUE THREAD

**Issue by sanju280696** [TheWidlarzGroup/react-native-video#2758]
recently i have updated react native version 0.69.1 for i need to upgrade video player but found this issue.

No matching configuration of project :react-native-video was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1' but:
- None of the consumable configurations have attributes.

React Native Version : 0.69.1
Gradle : 7.2.1

**Comment by freeboub** [comment]
Do you use v6 pre release?
V5 is not compatible with react 0.69
And there is still a known issue on ios with react 0.69 ...

**Comment by sanju280696** [comment]
I'm using v6.0.0-alpha.1

**Comment by freeboub** [comment]
Thanks, i have no clue with this issue... But to confirm this issue is linked to react native video, it would be wonderful to upgrade basic sample in the repository to react native 0.69.1 !

**Comment by AlirezaHadjar** [comment]
Same here. Even alpha.0 is ok. This only happens in alpha.1

**Comment by lightrow** [comment]
same here, unable to run project with 6.0.0 alpha1 on Android with RN 0.69.2

**Comment by iledzka** [comment]
I managed to fix this error by updating my settings.gradle file. For example, the old version was pointing to ../node_modules/react-native-video/android-exoplayer and v6 uses exoplayer by default. Try checking out the Installation Docs to ensure your settings.gradle is in order :)

**Comment by lightrow** [comment]
ah, indeed, in my case it's the react-native.config.js

**Comment by freeboub** [comment]
Look like a documentation issue.
As integration has change, we just remove notes in doc, but it may need to add a 'porting from 5.2 to 6.0' section.
I think @iledzka tips is the good solution for this issue.

> I managed to fix this error by updating my settings.gradle file. For example, the old version was pointing to ../node_modules/react-native-video/android-exoplayer and v6 uses exoplayer by default. Try checking out the Installation Docs to ensure your settings.gradle is in order :)

**Comment by freeboub** [comment]
@lightrow @AlirezaHadjar @iledzka @sanju280696 
I open following PR to clarify the fix, let me know if this is Ok for you. Or propose a different wording if it doesn't look clear ! :) 
https://github.com/react-native-video/react-native-video/pull/2796/files

**Comment by ahmedelsayed11233** [comment]
Hey I am using `  "react-native-video": "^6.0.0-alpha.3"`
And I get duration like -9223372036854776 in android only but in iOS its working, 
So please I had been stuck for a week and hope if anybody can help me.

**Comment by freeboub** [comment]
@ahmedelsayed11233 please open a new ticket with sample url. This issue ia for build problem

**Comment by ahmedelsayed11233** [comment]
> @ahmedelsayed11233 please open a new ticket with sample url. This issue ia for build problem

#2902 please check.

**Comment by usmahm** [comment]
> ah, indeed, in my case it's the react-native.config.js

My react-native.config.js was correct.
What I did was follow [this](https://github.com/react-native-video/react-native-video/issues/1747#issuecomment-531736338) to assign a custom project directory
