### ISSUE TITLE
crash app when choose type youtube

### ISSUE THREAD

**Issue by phamhieu1412** [TheWidlarzGroup/react-native-video#2764]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
 react-native: 0.64.0
 react-native-youtube: ^2.0.1
```

## Steps
1. choose and click a video
2. have 2 type of youtube (video example is youtube and youtube avanced)
3. click outside modal choose type youtube

## Expected behaviour

1. app not crash

## Video sample

https://user-images.githubusercontent.com/48906710/178963564-5b4866c9-7136-41a2-80fe-90242e9536d1.mp4

**Comment by freeboub** [comment]
"react-native-youtube" are you sure of this issue ?
this project is react-native-video ...
