### ISSUE TITLE
Unable to build example/basic on iOS

### ISSUE THREAD

**Issue by wood1986** [TheWidlarzGroup/react-native-video#2769]
![image](https://user-images.githubusercontent.com/5212215/179069660-4eb29e23-cb35-4093-8c41-60dba693d2ae.png)

**Comment by hueniverse** [comment]
@freeboub can you take a look?

**Comment by magic3584** [comment]
#2787

**Comment by freeboub** [comment]
sorry but I am not necesary the best guy to handle this issue. maybe @nickfujita which port to swift can have a quick look ?

**Comment by wood1986** [comment]
if you revert this PR #2720, it works

**Comment by freeboub** [comment]
@matinzd @wood1986 @nickfujita can you please clarify the issue together ?
Not sure what is the root cause of this issue Xcode version ? react-native version ? or something else ?

**Comment by wood1986** [comment]
In the main branch, you cannot run the iOS example. If you revert the commit, you can run it.

**Comment by matinzd** [comment]
It seems that we need to revert that PR.

**Comment by freeboub** [comment]
OK, thank you for the feedback, please approve following PR: https://github.com/react-native-video/react-native-video/pull/2854/files
(I also fix last entry in changelog)

**Comment by freeboub** [comment]
Thank you for the investigations,  I just publish an alpha.3 release
