### ISSUE TITLE
Invariant Violation: View config getter callback for component `RCTVideo` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by hemaljoshi** [TheWidlarzGroup/react-native-video#2772]
# Bug

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 150.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0
## Steps To Reproduce

1. installed and configured as mentioned in documentation 
2. then got this error
    [#2770](https://github.com/react-native-video/react-native-video/issues/2770)
    in Video.js file 
    + import {ViewPropTypes} from 'deprecated-react-native-prop-types'
3. added deprecated-react-native-prop-types package
4. re-builded and got error like
    Invariant Violation: View config getter callback for component `RCTVideo` must be a function (received `undefined`).

## Expected behaviour

1. error should not be there
![Simulator Screen Shot - iPhone 11 - 2022-07-18 at 17 22 28](https://user-images.githubusercontent.com/100120373/179505568-264efb45-e4c8-416d-a52a-2b7ea497fa86.png)

**Comment by freeboub** [comment]
This is strange, on which version did you test the patch ?
Notice that I opened following PR to backport react 0.69.X fixed on 5.2 release
https://github.com/react-native-video/react-native-video/pull/2795

**Comment by pacman899** [comment]
I'm getting this too.  @joshihemal  did you find a workaround or know of any progress of this?

**Comment by hemaljoshi** [comment]
@pacman899 no didn't found any resolution

**Comment by freeboub** [comment]
It looks like the js file is not found ...
If you create a very basic project to reproduce the I can have a look
