### ISSUE TITLE
v6 iOS: Controls set to true crashes app

### ISSUE THREAD

**Issue by zawesh** [TheWidlarzGroup/react-native-video#2773]
# Bug
When `controls` are set to `true`, app is crashing and we're getting

`react_native_video/RCTVideo.swift:636: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`
## Platform
ayer are you experiencing the problem on:
* iOS

## Environment info
```bash
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 286.57 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.asdf/installs/nodejs/16.2.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/installs/nodejs/16.2.0/.npm/bin/yarn
    npm: 7.13.0 - ~/.asdf/installs/nodejs/16.2.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.0 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Library version: 
6.0.0-alpha.1

## Steps To Reproduce
1. Fresh install
2. `yarn add react-native-video/react-native-video`

## Expected behaviour
1. iOS app should not crash when mounting `Video` component with `controls` set to `true`
2.

## Reproducible sample code
```js
      <Video
        paused
        fullscreen
        controls // when removed works fine
        resizeMode="cover"
        source={{ uri: path }}
        onLoad={calculateDimensions}
        style={[styles.video, style]}
      />
      ```

**Comment by jonsherrard** [comment]
I am also experiencing this issue 

 `"react-native-video": "^6.0.0-alpha.1"`

I'm on RN 0.69.3

I specifically get this error when the controls Boolean is set to `true` and component unmounts. 
 
 ```sh
react_native_video/RCTVideoPlayerViewController.swift:22: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

The code in question:
```swift
   override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        rctDelegate.videoPlayerViewControllerWillDismiss(playerViewController: self)
        rctDelegate.videoPlayerViewControllerDidDismiss(playerViewController: self)
    }
```

**Comment by freeboub** [comment]
@nickfujita can you have a look to this issue please ?

**Comment by daanlenaerts** [comment]
I am getting the same error when navigating away from the page on which the video is displayed.

**Comment by jonsherrard** [comment]
This has been fixed but not released yet: You can get the code Installing `npm install react-native-video@react-native-video/react-native-video#master` (direct from git), until 6.0.0-alpha.2 is released: https://www.npmjs.com/package/react-native-video

(Yes that is three `react-native-video`'s in the install command)

**Comment by daanlenaerts** [comment]
Ha wow, thanks, that does work. Thank you very much!

**Comment by freeboub** [comment]
ok, so let's close, thank you
