### ISSUE TITLE
Cant build 6.0.0-alpha.1 in react-native 0.69.1, Abort trap: 6 (in target 'react-native-video' from project 'Pods'), 

### ISSUE THREAD

**Issue by prakashbokati** [TheWidlarzGroup/react-native-video#2774]
Environment info:
System:
    OS: macOS 11.5
    CPU: (8) arm64 Apple M1
    Memory: 631.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/react-native/thehub-mobile/node_modules/.bin/npm
    Watchman: 2022.05.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4

Podfile looks like this
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
use_frameworks! :linkage => :static

install! 'cocoapods', :deterministic_uuids => false

target 'TheHub' do
  # React Native Maps dependencies
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!


  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"


  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Here is the error log in detail**
[issuelog.txt](https://github.com/react-native-video/react-native-video/files/9137980/issuelog.txt)
 ### I reproduced this issue in a brand new boilerplate project created with npx react-native init command

**Comment by Danny7fold** [comment]
I'm having similar issue how did you resolve it
?

**Comment by diego-ensolvers** [comment]
Same issue, in release mode build fine, but fails in debug build

**Comment by diego-ensolvers** [comment]
Same issue, in release mode builds fine, but build fails in debug mode

**Comment by prakashbokati** [comment]
> I'm having similar issue how did you resolve it
> 
> ?

Updated macos and xcode the project builds now. I was on big sur and xcode 12.5.1 before

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 138.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/react-native/thehub-mobile/node_modules/.bin/npm
    Watchman: 2022.05.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-32 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac

**Comment by diego-ensolvers** [comment]
I can confirm. Build successfully after update

**Comment by Danny7fold** [comment]
thnx

**Comment by vaibhavgehani** [comment]
Run sudo arch -x86_64 gem install ffi

and then goto ios folder and run arch -x86_64 pod install.
It will work.
