### ISSUE TITLE
Android: Playback of m38u url fails

### ISSUE THREAD

**Issue by dlavrantonis** [TheWidlarzGroup/react-native-video#2779]
# Bug
Attempt to play m3u8 url -it is a feed from ip camera- results to {"error":{"extra":-1007,"what":1}}
Same url works fine on an external player e.g. VLC
Im on RN 0.68.2. Same code works on RN 0.64.0

## Platform
React native 0.68.2

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 25.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 23.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.0

## Steps To Reproduce

1. attempt to play an m38u url

**Comment by dlavrantonis** [comment]
Issue is fixed on master branch. 
https://github.com/react-native-video/react-native-video/issues/2723

npm needs to be built from github. ( "react-native-video": "react-native-video/react-native-video", in package.json)

**Comment by freeboub** [comment]
Ok so, let's close this issue.
Thank you
