### ISSUE TITLE
No audio on iOS, already tried ignoreSilentSwitch :) 

### ISSUE THREAD

**Issue by davidsalib** [TheWidlarzGroup/react-native-video#2780]
# Bug
Playing videos on iOS doesn't play any audio. 
On Android, the audio works as expected. 

## Platform
* iOS

Library version: 5.2.0

## Video sample
https://drive.google.com/file/d/1uqvRKYlkq6Y7K8SOht_rwaKoWcvazr2Q/view?usp=sharing

I have tried:
* ignoreSilentSwitch={'ignore'}
* setting `muted={false}`
*  adding `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; `

For context, I also have React Native Track Player installed, which could be causing a conflict?

**Comment by royaladvice** [comment]
Hello same here, iOS does not play audio, tried some configurations but no luck

**Comment by yasirrafiq786** [comment]
The audio starts playing for a second or two if I change the playback speed. The problem prop is textTracks actually.
