### ISSUE TITLE
intercepting DRM request to add header

### ISSUE THREAD

**Issue by stepas-dev** [TheWidlarzGroup/react-native-video#2781]
Trying to play HLS stream with DRM protection, after loading the stream, the player using stream request response immediately automatically sends a request for license (observed via flipper logs), the problem is I need to modify headers to add token to license request which I can't figure it out how to do. The `drm` prop in Video component is completely ignored, so adding header through there isn't an option. Also adding headers in `source` prop works but it also adds header to the stream request, so it is a security problem for our project. Is there a way to expose functionality that can intercept only license server request and modify headers ?

Also we managed to make it work using video.js in javascript, so it looked something like this:

```
function myFunction() {
        videojs.Vhs.xhr.beforeRequest = function(options) {
          if (options.uri.startsWith(<license_url>)){
              <ADD TOKEN HERE>
          }
          return options;
        };
	var player = videojs('vid1');
	player.src({
	  src: "<stream_url>/index.m3u8"
	});
	player.play();
}
```
Maybe something similar can be implemented in react-native-video ?

**Comment by freeboub** [comment]
I confirm you should use drm property object:
https://github.com/react-native-video/react-native-video/blob/master/docs/DRM.md

And to define a custom header, the headers property
[headers](https://github.com/react-native-video/react-native-video/blob/master/docs/DRM.md#headers)

Notice that you must define a licenseUrl, like in the headers sample.

Let me know if it is Ok for you.

(I guess this question is android only)
