### ISSUE TITLE
version update and regarding web

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [TheWidlarzGroup/react-native-video#2782]
Hi,

I wanted to use this library with react native web, I have forked this library. Now I wanted to add some packages and update the version of react native and react using diff-purge so that react-native-web which uses react version 17.0.2  will become compatible.

Problem while updating react version:
I am not able to find certain files, that need to be updated i.e - 
-AppDelegate.mm
-AppDelegate.h 
And many others based on this diff purge version update : https://github.com/react-native-community/rn-diff-purge/compare/release/0.61.5..release/0.69.0

**Comment by hueniverse** [comment]
A lot of files have moved or deleted. The entire iOS code has been rewritten. The only suggestion I have is to do a diff against the version of master you forked off, and then manually apply all your local changes to current master.
