### ISSUE TITLE
I want to change subtitle and audio track on run time please help, how we can do this

### ISSUE THREAD

**Issue by rsys2022** [TheWidlarzGroup/react-native-video#2783]
# i am unable to change subtitle and audio track on run time 
Please let me know how we can achieve this. 
 i am able to integrate subtitle with mp4 but not with .m3u8 or hls or mpd formates.

**Comment by freeboub** [comment]
Need more info or a sample...
Mdp is working on Android sample ...

**Comment by rsys2022** [comment]
<Video
        controls
        fullscreen={true}
        style={{flex: 1,backgroundColor:'red'}}
        source={require('../../component/videos/MIB2.mp4')}
        selectedTextTrack={{
          type: "title",
          value: "English CC"
        }}
        textTracks={[
          {
            title: "English CC",
            language: "en",
            type: TextTrackType.VTT, // "text/vtt"
            uri: "https://rsysdemo-b7be9.web.app/MIB2-subtitles-pt-BR.vtt"    // "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
          },
          {
            title: "Spanish Subtitles",
            language: "es",
            type: TextTrackType.VTT, // "application/x-subrip"
            uri: "https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt" 
          }
        ]}
      />

i have integrated text tracks but how to change text tracks on run time and how to integrate text tracks with .m3u8 formates and also how to integrate audio tracks in it

**Comment by rsys2022** [comment]
@freeboub  Please look above code and let me know how to change text tracks and audio tracks dynamically

**Comment by freeboub** [comment]
@rsys2022 you have local file in you sample, nobody will be able to reproduce the issue ...
Addtionnally on which platform do you have the issue ?

**Comment by rsys2022** [comment]
<Video
controls
fullscreen={true}
style={{flex: 1,backgroundColor:'red'}}
source={{ uri: 'https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8', type:'m3u8' }}
selectedTextTrack={{
type: "title",
value: "English CC"
}}
textTracks={[
{
title: "English CC",
language: "en",
type: TextTrackType.VTT, // "text/vtt"
uri: "https://rsysdemo-b7be9.web.app/MIB2-subtitles-pt-BR.vtt" // "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
},
{
title: "Spanish Subtitles",
language: "es",
type: TextTrackType.VTT, // "application/x-subrip"
uri: "https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt"
}
]}
/>

**platform :** ios
**video formate:** HLS (m3u8)
**issue:**.   Unable to change text track (subtitle) and audio track and also text track is not working in HLS formate
@freeboub please look in to it

**Comment by freeboub** [comment]
subtitle selection by title was buggy on ios. fix ongoing here: https://github.com/TheWidlarzGroup/react-native-video/pull/4129
