### ISSUE TITLE
Player goes to buffering state after playing SSAI ads instad of the playing the content 

### ISSUE THREAD

**Issue by Lilsax** [TheWidlarzGroup/react-native-video#2784]
# Bug

after implementing  SSAI logic the player plays the Ads then after playing the ad the function `player.getCurrentPosition()` starts to return random value as -1658671026284 then it goes to buffering state instead  of playing the content

## Platform
this issue happens on Android onlu

**Comment by Lilsax** [comment]
@hueniverse what do you mean by triage needed ? is there anything needed from my side?

**Comment by Lilsax** [comment]
sorry i closed it by mistake

@hueniverse 
and what does triage needed mean ?
is there anything needed from my side ??

**Comment by freeboub** [comment]
@Lilsax I confirm that a sample stream would be useful !
Additionally did you test on v6 alpha or only on 5.2 ?
Thank you

**Comment by Lilsax** [comment]
the issue turned out to be with the audio the playout contain audio source different from the video source which leaded to a buffering issue
