### ISSUE TITLE
HLS .m3u8 format, audio always plays first without video with slow network

### ISSUE THREAD

**Issue by ylli2000** [TheWidlarzGroup/react-native-video#2785]
## Bug
What - play a HLS .m3u8 for example from Vimeo, the audio always plays first then get stuck loading, the video happens about 1~2 seconds later. 
When - the network is slow, becomes very obvious at ADSL or ADSL2 speed (you can simulate it with Charles proxy throttle) 
 
## Platform
Tried it on Android, iOS phones and Smulators

## Environment info
Throttled ADSL, ADSL2 speed
Library version: 5.2.0

## Steps To Reproduce
Play a HLS .m3u8 from Vimeo

## Expected behaviour
Video / Audio should wait for each other and play together, at slow network environment.

## Actual behaviour
Audio always plays 1 or 2 sec ahead without waiting for video. Only then the waiting loading starts. Then another 1 or 2 sec later, finally video & audio play together.

**Comment by paytmmloyal** [comment]
Same problem happing with us!!

**Comment by jadiaheno** [comment]
I have exactly the same issue.

**Comment by alexbudin** [comment]
Same issue here. Not to mention that now since iOS 16.4 we have more problems with m3u8:
more here:
https://github.com/react-native-video/react-native-video/issues/3107

**Comment by wolfxpertlab** [comment]
also same error on android exoplayer

this is error

{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.42E015, 484444, null, [480, 360, -1.0], [-1, -1]), format_supported=YES", "errorString": "Unable to instantiate decoder OMX.MTK.VIDEO.DECODER.AVC"}}

how can I solved it any solution
