### ISSUE TITLE
Video disappears after putting the app to background and returning back

### ISSUE THREAD

**Issue by qeorqer** [TheWidlarzGroup/react-native-video#2786]
# Bug

After the video finished playing, if the app goes to background the video disappears.

## Platform
IOS

## Environment info

React native info output:

System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 49.71 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.1 - ~/.nvm/versions/node/v16.4.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.4.1/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.1/bin/npm
    Watchman: 2022.02.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: ^5.2.0

## Steps To Reproduce

https://user-images.githubusercontent.com/48507659/180932041-405be103-7bf5-4c93-81ee-6ce6a2d8aa09.mp4

Shown in the video

<img width="274" alt="image" src="https://user-images.githubusercontent.com/48507659/180931872-34965a47-c6cd-45b9-ad0f-f94bb275b518.png">

**Comment by danilobuerger** [comment]
This happens to me as well. However on a real device when you get to the foreground again, the player is gone but shortly after appears with the last frame. On the simulator, the player stays gone.

**Comment by t104360088** [comment]
I am also facing the same problem, does anyone have an idea how to solve this?

**Comment by E-Guozhi** [comment]
Same Problem.
But it only happens when APP to background the video playing end。
It seems in iOS video does not keep the last frame When APP to background.

**Comment by freeboub** [comment]
can you clarify if this issue is reproduced on last V6.0.0 version ?

**Comment by rustygloves** [comment]
> can you clarify if this issue is reproduced on last V6.0.0 version ?

We have just started experiencing this, it is related to iOS 17, and I have confirmed the by in V6

**Comment by ghost** [comment]
@rustygloves the issue was created more than a year ago which cannot be related to iOS 17.0.3

**Comment by rustygloves** [comment]
> @rustygloves the issue was created more than a year ago which cannot be related to iOS 17.0.3

I am not claiming that this issue was caused by iOS 17.0.3, merely that we are experiencing an issue of the same description that began occurring because of an update to 17.0.3.

I didn't want to create a new issue because this library is already burdened with plenty of those. I was merely trying to be helpful indicating that this issue does in fact occur in version 6 of this library in certain circumstances.

**Comment by rustygloves** [comment]
> @rustygloves the issue was created more than a year ago which cannot be related to iOS 17.0.3

That's not what I was claiming. I didn't want to open a new issue when the same issue was happening on iOS 17 with version 6 of this library, but I've removed my comment and won't bother next time.

**Comment by ghost** [comment]
This was fixed within https://github.com/react-native-video/react-native-video/commit/be8cdfdd3386f0d219c8f10a212cc55fe9becfc6

I just noticed that there was a `!` missing there, was going to submit a PR and noticed that it was fixed in the master branch already. I suppose it should go to the next alpha release

**Comment by ghost** [comment]
Another similar issue is addressed in my PR: https://github.com/react-native-video/react-native-video/pull/3326

**Comment by dvelasquezTC** [comment]
I confirm I'm still facing this issue even after using `playWhenInactive={true}` When the video ends, I go to background and refocus the app, the video is gone.

**Comment by dvelasquezTC** [comment]
I fix it by listening to the `AppState`. Whenever the app comes to foreground, it seeks 0 and resumes the video.

```javascript
import { AppState } from 'react-native';
import Video, { VideoRef } from 'react-native-video';

const Video: React.FC = () => {

const playbackInstance = useRef<VideoRef>(null);
const appState = useRef(AppState.currentState);

useEffect(() => {
    const subscription = AppState.addEventListener('change', nextAppState => {
      if (
        appState.current.match(/inactive|background/) &&
        nextAppState === 'active'
      ) {
        playbackInstance.current?.seek(0);
        playbackInstance.current?.resume();
      }
      appState.current = nextAppState;
    });
    return () => {
      subscription.remove();
    };
  }, []);

return ( 
  <Video
      ref={playbackInstance}
/// rest of the component
```

**Comment by brolly301** [comment]
I'm a bit late to this but if you add - 

repeat={true}

It should then work. My video was around 10 seconds long and after 10 seconds it disappeared when switching between screens. After looping/repeating the video, it reset it every time the video finished and so stop disappearing.
