### ISSUE TITLE
Setting Maintenance Expectations

### ISSUE THREAD

**Issue by hueniverse** [TheWidlarzGroup/react-native-video#2788]
#### I would like to set some clear expectations for those using or looking to use this project. This is based on my experience with it as a maintainer over the last 4 months.

This project - the only viable open source video solution for RN outside of Expo - is severely under resourced. Despite many good intentions, it is currently unsustainable. It has exhausted every person who tried to maintain it or contribute over the past few years because with very few exceptions, the community has failed to contribute back.

To demonstrate - a few months ago we put a governance system in place where most decisions are made democratically. This means a PR can get merged with approval from 1-3 people very quickly. Reviews are open to anyone, not just maintainers. However, in contrast to the dozens or people who show up to complain, no one has volunteered a review. We have 8 open pull requests that are almost ready to be merged and all waiting for someone to validate them.

IF YOU WANT TO HELP please don't just reply to this issue and make promises because that's pointless. Instead start actually contributing:
- Test out a pull request and either post feedback or approve it. You don't even need to understand the code - you just need to run it in a real app and confirm it is working as expected and doesn't break anything.
- Help triage an issue. There are over 30 open issues waiting for someone to confirm them: https://github.com/react-native-video/react-native-video/issues?q=is%3Aissue+is%3Aopen+label%3A%22triage+needed%22. Again, you just need to spend some time reproducing it and report back if the issue is real.
- Answer some questions. Most issues are closed after a few months because no one bothers to chime in. If you are using this module, you must have figured out how to overcome some problems - why not share that knowledge with others?
- Help with housekeeping. Review issues and pull requests and try to make sense of them. Look for similar issues and link them. Ask people for more information to save time on follow ups. I was able to help for 4 months without having any understanding of native code by simply contributing to the process and helping with housekeeping.
- Test the latest v6 alpha release and master and report back of any problems - or that it's working well! So far only a handful of people reported anything at all.

#### If you show up asking for help without contributing something back, you are the problem. You are the reason why this project is failing. If you only care about the one issue you are having, you are making it worse and hurting those trying to maintain it.

---

Unfortunately, the project I was working on that used react-native-video is no longer in active development and I cannot justify spending more time on this module. I will stick around to help with a transition if someone else steps forward but will no longer work on issues or release new versions. I am happy to give admin access to those who show up and put real effort.

I'd like to sincerely thank @cobarx, @freeboub, @nickfujita, and @armadilio3 for their significant efforts and contributions over the past 4 months. Any progress made in the last few months has only been achieved because of their contributions - I was just the admin.

**Comment by jeremyspritelyco** [comment]
It's sad.

**Comment by nickfujita** [comment]
Thank you so much on your help with this module over the past months @hueniverse !

@freeboub 
Also, sorry I haven't responded to the latest tags in some of the issues, as I'm in the middle of a role transition. So unfortunately I'm also no longer working on a project actively using this module, so will not be able to dedicate time here.

Please contact @cobarx for assistance, as his team is still working on the project which is actively making improvements to this repo ✌🏼

**Comment by matinzd** [comment]
I am working on two projects which heavily depends on video module.
Now I have some ideas to keep it alive.
First thing I did was to start upgrading examples, specifically migrating to RNTA for better testing and development. 
You can reach out to me by email or linkedin:
zadehdolatabad@gmail.com

If there is any slack channel, add me there. 

@freeboub

**Comment by freeboub** [comment]
let close this issue and follow up in the other pin ticket and in discussion section. thank you @hueniverse
