### ISSUE TITLE
Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by MinhazK12** [TheWidlarzGroup/react-native-video#2789]
# Bug

#react-native-video  #react #react-native
![react native video error](https://user-images.githubusercontent.com/106460925/181514864-74349984-d03e-493a-9be9-3129cf92a0d6.png)

**Comment by MinhazK12** [comment]
While building I'm getting this error in Run gradlew file ->

Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/android

Downloading https://services.gradle.org/distributions/gradle-7.3.3-all.zip

10

%.

20%.

30%

40%.

50%.

60

%

70%.

80

%.

90%.

100%

Welcome to Gradle 7.3.3!

Here are the highlights of this release:

 - Easily declare new test suites in Java projects

 - Support for Java 17

 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.

Daemon will be stopped at the end of the build

Unable to list file systems to check whether they can be watched. Assuming all file systems can be watched. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

> Task :react-native-gradle-plugin:compileKotlin

'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (155, 32): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (161, 31): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (169, 36): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with rootto point to your root project and reactNativeDir to point to the folder of the react-native NPM package

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 51): 'BaseVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'ApplicationVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (132, 12): 'LibraryVariant' is deprecated. Deprecated in Java

w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :react-native-gradle-plugin:compileJava

[stderr] Note: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.

[stderr] Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gradle-plugin:pluginDescriptors

> Task :react-native-gradle-plugin:processResources

> Task :react-native-gradle-plugin:classes

> Task :react-native-gradle-plugin:inspectClassesForKotlinIC

> Task :react-native-gradle-plugin:jar

> Configure project :app

Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo-eas-client

Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo-structured-headers

Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo-updates-interface

Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo

Using expo modules

  - react-native-google-signin-google-signin (8.0.0)

  - expo-application (4.1.0)

  - expo-constants (13.1.1)

  - expo-dev-client (1.0.1)

  - expo-dev-launcher (1.0.1)

  - expo-dev-menu (1.0.1)

  - expo-eas-client (0.2.1)

  - expo-error-recovery (3.1.0)

  - expo-file-system (14.0.0)

  - expo-font (10.1.0)

  - expo-json-utils (0.3.0)

  - expo-keep-awake (10.1.1)

  - expo-linear-gradient (11.3.0)

  - expo-manifests (0.3.0)

  - expo-modules-core (0.9.2)

  - expo-splash-screen (0.15.1)

  - expo-structured-headers (2.2.1)

  - expo-updates (0.13.3)

[stderr] FAILURE: Build failed with an exception.

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-video/android/build.gradle' line: 20

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':react-native-video'.

[stderr] > Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 3m 6s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

6 actionable tasks: 6 executed

Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)

Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

I would like to mention that the app is running smoothly in development. 

#react-native #react-native-video #eas #expo

**Comment by freeboub** [comment]
I don't think this repo is compatible with repo. I know there is repo-video project.
If you really need more investigation, can you create a very small sample project with repo please?
Additional question, is it working on ios ?

**Comment by freeboub** [comment]
Closed due to inactivity. Please reopen if needed

**Comment by Mudasir1406** [comment]
Same Error here this error can be resolve by replacing Provided and compile method with implementation in 
projectrootfolder\node_modules\react-native-video\android\build.gradle

under the dependencies like 
`dependencies {
    //noinspection GradleDynamicVersion
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.yqritc:android-scalablevideoview:1.0.4'
}
`
@freeboub @MinhazK12 @jsierles @mlc @danhodos

**Comment by samrat-gupta** [comment]
I'm also getting this error while trying to build using eas...
![image](https://user-images.githubusercontent.com/93257829/215017646-b2a35200-454c-4cf9-a7d7-9e007651942b.png)
can anyone help with this...?
Thanks in Advance.

**Comment by freeboub** [comment]
@samrat-gupta This issue is linked to react-native-orientation ...

**Comment by samrat-gupta** [comment]
> @samrat-gupta This issue is linked to react-native-orientation ...
Yes, I know @freeboub .
I can change that dependency in my local node_modules but how can I fix this in eas build....?

**Comment by freeboub** [comment]
If you found a workaround, the easiest way to integrate the patch is to use patch-package : https://www.npmjs.com/package/patch-package

**Comment by Mohamed-akmal0** [comment]
im also getting the same issue here on android.. im using react native bare cli and when i tried to run the project giving this error => A problem occurred evaluating project ':react-native-video'.
> Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
