### ISSUE TITLE
onError fires on Android 9 or lower (Only in production)

### ISSUE THREAD

**Issue by jeffmon** [TheWidlarzGroup/react-native-video#2792]
# Bug

When attempting to play a video on an Android 9 or lower device (In a production build), `onError` fires, which returns as `true`. No other error messages appear. When running locally via `react-native run-android`, the error doesn't happen and the video plays normally.

## Platform
Android OS 9 or lower (Only in production)

## Environment info

```bash
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.19 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Users/jeffmon/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.66.4 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1. Set up the video player within an app
2. Package the app for production
3. Test the video player on an Android device OS 9 or lower

## Expected behaviour

1. The video should play properly with no error

Thanks in advanced for any help with this!

**Comment by freeboub** [comment]
Do you have a logcat of the issue please ?

**Comment by jeffmon** [comment]
Sorry for the late response @freeboub, is there a way to get a logcat on a release build?

**Comment by freeboub** [comment]
Same than on debug, you just need to use 'adb logcat'

**Comment by jeffmon** [comment]
@freeboub 
Sorry for the late response, I was able to run `adb logcat` on production using Browserstack:

```
08-09 18:51:14.722 E/MediaPlayerNative(31963): error (1, -2147483648)
08-09 18:51:14.722 E/MediaPlayerNative(31963): error (1, -2147483648)
08-09 18:51:14.722 E/MediaPlayerNative(31963): error (1, -2147483648)
08-09 18:51:14.722 E/MediaPlayerNative(31963): error (1, -2147483648)
08-09 18:51:14.730 E/MediaPlayer(31963): Error (1,-2147483648)
08-09 18:51:14.730 E/MediaPlayer(31963): Error (1,-2147483648)
08-09 18:51:14.755 E/MediaPlayerNative(31963): isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
08-09 18:51:14.755 E/MediaPlayerNative(31963): isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
```

This is the only errors that pop up when trying to play a video.

**Comment by freeboub** [comment]
Nothing we can investigate :/ you should try exoplayer implementation!

**Comment by jeffmon** [comment]
Thanks for responding, @freeboub!

**Comment by freeboub** [comment]
I close this ticket  as legacy media player implementation has been dropped on V6
