### ISSUE TITLE
React Native 0.69 not working

### ISSUE THREAD

**Issue by billnbell** [TheWidlarzGroup/react-native-video#2793]
This is not working on rN 0.69.*

**Comment by freeboub** [comment]
You can try this PR: https://github.com/react-native-video/react-native-video/pull/2795
But I close this ticket as no information has been provided to understand the issue

**Comment by stasguma** [comment]
RN 0.69.1 works for me. Thanks.

don't forget delete this line `new MainReactPackage()` in `MainApplication.java`
and this `import com.facebook.react.shell.MainReactPackage;` if earlier added
