### ISSUE TITLE
It takes long time to play live stream on android only

### ISSUE THREAD

**Issue by Robiullah2244** [TheWidlarzGroup/react-native-video#2798]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android
## Environment info

Library version: 5.2.0

## Steps To Reproduce

1. Paste a live stream URL to source={{uri: 'https://23023.live.streamtheworld.com/AFN03_S01AAC.aac '}}
2. It takes 20-30 seconds to play.

## Expected behaviour

1. Normally it takes 2 seconds to play on the web.

## Reproducible sample code
```
    <Video
          ref={videoRef}
          source={{uri: 'https://23023.live.streamtheworld.com/AFN03_S01AAC.aac'}}
          poster={'https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg'}
          bufferConfig={{
            minBufferMs: 5000,
            maxBufferMs: 10000,
          }}
          style={{ width: 400, height: 400}}
          muted={false}
          repeat={false}
          // resizeMode={"cover"}
          volume={1.0}
          rate={1.0}
          ignoreSilentSwitch={"ignore"}
          playWhenInactive={true}
          playInBackground={true}
          controls={true}
          paused={pause}
          onLoadStart={() => {
            console.log('onLoadStart');
          }}
          onLoad={() => {
            console.log('onLoad');
          }}
          onBuffer={() => {
            console.log('onBuffer');
          }}
          onProgress={() => {
            console.log('onProgress');
          }}
        />
```

**Comment by freeboub** [comment]
I have an error 403 when requesting the url:
 ➢  wget https://23023.live.streamtheworld.com/AFN03_S01AAC.aac                                                                                                                                                      130    [1min32sec] 21:39
--2022-08-02 21:39:03--  https://23023.live.streamtheworld.com/AFN03_S01AAC.aac
Resolving 23023.live.streamtheworld.com (23023.live.streamtheworld.com)... 208.80.54.107
Connecting to 23023.live.streamtheworld.com (23023.live.streamtheworld.com)|208.80.54.107|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-08-02 21:39:05 ERROR 403: Forbidden.

**Comment by Robiullah2244** [comment]
> I have an error 403 when requesting the url: ➢ wget https://23023.live.streamtheworld.com/AFN03_S01AAC.aac 130 [1min32sec] 21:39 --2022-08-02 21:39:03-- https://23023.live.streamtheworld.com/AFN03_S01AAC.aac Resolving 23023.live.streamtheworld.com (23023.live.streamtheworld.com)... 208.80.54.107 Connecting to 23023.live.streamtheworld.com (23023.live.streamtheworld.com)|208.80.54.107|:443... connected. HTTP request sent, awaiting response... 403 Forbidden 2022-08-02 21:39:05 ERROR 403: Forbidden.

I am sorry. The URL I provided is accessible from certain countries like Italy, and Japan.

You can use any of the audio live stream URLs. I tested now using https://us4.internet-radio.com/proxy/douglassinclair?mp=/stream. It also takes almost 30 seconds to play. I tested using several live URLs randomly taken from internet radio. The same issue was found on android. iOS working fine

**Comment by Robiullah2244** [comment]
@freeboub Did you find this issue?

**Comment by freeboub** [comment]
@Robiullah2244 I have just test on master, it works fine on android.
Notice that master always uses exoplayer.
I can propose you to switch on exoplayer implementation (or switch to V6 alpha version, but not sure ios version works fine).
Let me know if it also fix your issue !

**Comment by ycdaskin** [comment]
in my case when i try to stream video from my aws s3 storage, it takes terribly long time to start the video. but any other public video resource on the web starts immediatly.

**Comment by freeboub** [comment]
you should have a look to this page in case of similar issues: 
https://github.com/react-native-video/react-native-video/blob/master/docs/DEBUGGING.md

let's close this issue
