### ISSUE TITLE
Resolution change is not working

### ISSUE THREAD

**Issue by ArvindKrPrajapati** [TheWidlarzGroup/react-native-video#2805]
I am trying to change resolution to 480p using selectedVideoTrack but there is no change in resolution

selectedVideoTrack={{
  type="resolution",
  value:480
}}

**Comment by freeboub** [comment]
android or ios ? on android do you use exoplayer version ? which RNV version ?

**Comment by ArvindKrPrajapati** [comment]
> 

It's in android , yes I am using exoplayer version of RNV  v5.2.0

**Comment by freeboub** [comment]
no clue, It seems to be implemented in exoplayer implementation ...
I think you need to check on master branch and put some code instrumentation in java ...
Notice that as the stream is not provided in the ticket. The issue is not reproducible...
