### ISSUE TITLE
iOS app crashes on call to presentFullScreenPlayer

### ISSUE THREAD

**Issue by rafamanzo** [TheWidlarzGroup/react-native-video#2808]
# Bug

When calling `presentFullScreenPlayer` in an iOS device/emulator (android is working perfectly) there is the following error:

```
Exception thrown while executing UI block: Application tried to present modally a view controller <RNSScreen: 0x7faff9950470> that has a parent view controller <RNScreensViewController: 0x7faff6a8fc50>.
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1201
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
```

Which seem to me related to:

* https://github.com/react-native-video/react-native-video/issues/1568
* https://github.com/react-native-video/react-native-video/issues/2178
* https://github.com/react-native-video/react-native-video/issues/2623

Our **workaround** for this currently is to not call the function at all in iOS and keep the controls enabled (`controls={true}`) which will provide a button to go fullscreen.

## Platform

* iOS

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 29.54 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 31
      Build Tools: 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0.alpha1 (also tested in the top of master commit f32da092b17b912f013da611358302addcea310d)

## Steps To Reproduce

1. call `presentFullScreenPlayer` on the video ref 

...

## Expected behaviour

1. Present the fullscreen video

## Reproducible sample code

```typescript
videoRef?.presentFullScreenPlayer()
```

**Comment by ngima** [comment]
For me I am getting same issue when `controls={true}`.

**Comment by jffun** [comment]
For me, I export [AVPlayerViewController+Fullscreen](https://github.com/nfb-onf/react-native-video/blob/master/ios/Video/AVPlayerViewController%2BFullscreen.m) 
and in RCTVideo.swift, add _controls check in setFullscreen method before present viewController

```
if _controls {
                    _playerViewController?.removeFromParent()
                    _playerViewController?.goFullscreen { [weak self] in
                        self?._playerViewController?.showsPlaybackControls = true
                        self?._playerViewController?.autorotate = self?._fullscreenAutorotate
                    }
                } else {
                viewController.present(viewController, animated:true, completion:{
                    self._playerViewController?.showsPlaybackControls = true
                    self._fullscreenPlayerPresented = fullscreen
                    self._playerViewController?.autorotate = self._fullscreenAutorotate
                    self.onVideoFullscreenPlayerDidPresent?(["target": self.reactTag])
                })
}
```

fixed this case

**Comment by bulkinav** [comment]
@jffun maybe you can to create Pull request with your fixes?

**Comment by samonov22** [comment]
if viewController != nil {
                _presentingViewController = viewController
                
                self.onVideoFullscreenPlayerWillPresent?(["target": reactTag as Any])
                
                viewController.present(_playerViewController!, animated:true, completion:{
                    self._playerViewController?.showsPlaybackControls = true
                    self._fullscreenPlayerPresented = fullscreen
                    self._playerViewController?.autorotate = self._fullscreenAutorotate
                    self.onVideoFullscreenPlayerDidPresent?(["target": self.reactTag])
                })
            }

**Comment by samonov22** [comment]
Changed viewController.present() functions argument  from '_**viewController**_' to '_**_playerViewController!**_' in setFullscreen method. Works for me.

```
@objc
    func setFullscreen(_ fullscreen:Bool) {
        if fullscreen && !_fullscreenPlayerPresented && _player != nil {
            // Ensure player view controller is not null
            if _playerViewController == nil {
                self.usePlayerViewController()
            } ...
```


```
if viewController != nil {
                _presentingViewController = viewController
                
                self.onVideoFullscreenPlayerWillPresent?(["target": reactTag as Any])

-               viewController.present(viewController, animated:true, completion:{                
+               viewController.present(_playerViewController!, animated:true, completion:{
                    self._playerViewController?.showsPlaybackControls = true
                    self._fullscreenPlayerPresented = fullscreen
                    self._playerViewController?.autorotate = self._fullscreenAutorotate
                    self.onVideoFullscreenPlayerDidPresent?(["target": self.reactTag])
                })
            }
        } ...
```
Path: node_modules/react-native-video/ios/Video/RCTVideo.swift
version: 6.0.0-alpha.3

**Comment by sahilcodedrill12** [comment]
@samonov22  there is lines as well can you please tell me about this as well?

 var _playerViewController:UIViewController! = self.firstAvailableUIViewController()
            if (_playerViewController == nil) {
                let keyWindow:UIWindow! = UIApplication.shared.keyWindow
                _playerViewController = keyWindow.rootViewController
                if _playerViewController.children.count > 0
                {
                    _playerViewController = _playerViewController.children.last
                }
            }

**Comment by bulkinav** [comment]
Hi,

Can anyone confirm now that the problem is reproducible on iOS with the latest commits in master?

I can't reproduce the crash, but the player doesn't go to fullscreen either (how is this expected) - https://bulkin.me/files/ios_player.mov

This is very similar to the problem from #2864

My code:

```
const videoRef = useRef(null)

useEffect(() => {
        if (videoRef && videoRef?.current && videoRef?.current?.presentFullscreenPlayer) {
            videoRef?.current?.presentFullscreenPlayer()
        }
    }, [])

return (
        <View style={styles.container}>
            <Video
                ref={videoRef}
                source={{ uri }}
                onProgress={handleProgress}
                onEnd={handleEnd}
                controls={isNeedControls}
                fullscreen
                fullscreenOrientation="landscape"
                pictureInPicture
                style={StyleSheet.absoluteFill}
            />
        </View>
    )
```

**Comment by somersets** [comment]
Hi, I had the same problem with the same version
@samonov22 and your suggestion helped me!

> Changed viewController.present() functions argument from '_**viewController**_' to '_**_playerViewController!**_' in setFullscreen method. Works for me.
> 
> ```
> @objc
>     func setFullscreen(_ fullscreen:Bool) {
>         if fullscreen && !_fullscreenPlayerPresented && _player != nil {
>             // Ensure player view controller is not null
>             if _playerViewController == nil {
>                 self.usePlayerViewController()
>             } ...
> ```
> 
> ```
> if viewController != nil {
>                 _presentingViewController = viewController
>                 
>                 self.onVideoFullscreenPlayerWillPresent?(["target": reactTag as Any])
> 
> -               viewController.present(viewController, animated:true, completion:{                
> +               viewController.present(_playerViewController!, animated:true, completion:{
>                     self._playerViewController?.showsPlaybackControls = true
>                     self._fullscreenPlayerPresented = fullscreen
>                     self._playerViewController?.autorotate = self._fullscreenAutorotate
>                     self.onVideoFullscreenPlayerDidPresent?(["target": self.reactTag])
>                 })
>             }
>         } ...
> ```
> 
> Path: node_modules/react-native-video/ios/Video/RCTVideo.swift version: 6.0.0-alpha.3

**Comment by johnbillion** [comment]
@samonov22 @somersets This fix is working for us on alpha 4. Thank you! Do you want to open a PR?

**Comment by somersets** [comment]
@johnbillion Yes, I would like to open a PR
