### ISSUE TITLE
onEnd callback is not fired on Android if repeat is enabled

### ISSUE THREAD

**Issue by duyluandethuong** [TheWidlarzGroup/react-native-video#281]
In both my app and example app, the onEnd event does not fired when running on Android (emulator and real device). The video did repeat itself, but for some reason that callback does not print out or do anything. On iOS this issue does not happen. Any workaround guys?

**Comment by mattapperson** [comment]
@duyluandethuong can you by any chance post some sample code to reproduce this issue? It would help us to more rapidly reproduce and fix the issue.

**Comment by amitaigat** [comment]
Just in case anybody else runs into this issue, it happened to me when "repeat" was set to true. Setting "repeat" to false fixed the issue.

**Comment by annelorraineuy** [comment]
onEnd callback doesn't work for me either on iOS. My video autoplays and on complete, don't even fire the callback. Here is my code:

```
class SplashAnimated extends Component {
    _onEnd() {
        console.log('done playing video');  <-- doesn't log
        this.props.setPlayed(true);
    }

    render() {
        const { containerStyle, splashView, splashVideo } = styles

        return (
            <View style={containerStyle}>
                <View style={splashView}>
                    <Video
                        source={require('./../assets/splash/splash.mp4')}
                        ref={(ref) => {
                         this.splashPlayer = ref
                       }}
                        repeat={false}
                        style={splashVideo}
                        onEnd={this._onEnd.bind(this)}
                    />
                </View>
            </View>
        )
    }
}
```

**Comment by pawlowskim** [comment]
Same here, if repeat = true onEnd is not triggered on Android.
"react-native-video": "1.0.0"
"react-native": "0.44.0"

**Comment by agumack** [comment]
Hi all, I also have same problem.

**Comment by zhanghqgit** [comment]
the same to me . when repeat = true, onEnd is not triggered on Android!
RN 0.54.0
react-native-video 2.0.0

**Comment by KaoPengHsiang** [comment]
the same to me . when repeat = true, onEnd is not triggered on Android!
> RN 0.57.4
> react-native-video "3.2.1"

**Comment by OXReactDev** [comment]
Yes I am facing same issue if repeat props is true then onEnd is not getting triggered in Android, in iOS it working fine.

**Comment by OXReactDev** [comment]
HI all,
I have some workaround for this issue.

In iOS if repeat props is true then also onEnd is getting triggered but in Android if repeat props is false then only onEnd is getting called.


So I have applied repeat property as false so onEnd is getting called, and in onEnd method we need to set seek(0).

setTimeout(() => {
          videoRef.current.seek(0);
        }, 0);


So now when video ends it will start from 0 again and onEnd method is called everytime when video finished.
