### ISSUE TITLE
onProgress run wrong Android

### ISSUE THREAD

**Issue by jayden-vu** [TheWidlarzGroup/react-native-video#2810]
env: Vinsmart Aris - android11
**while I watching a video suddenly the video freezes and only sound is heard. When I check value of the currentTime is back to 0 and keep runing**
[
<img width="126" alt="image" src="https://user-images.githubusercontent.com/49259557/183547715-a41a3c94-cc16-4c1c-b03d-acf49a7bcb99.png">
](url)

**Comment by freeboub** [comment]
any sample ? is this 100% of time ?

**Comment by jayden-vu** [comment]
> value of the currentTime

Hi freeboud

I have a video that is 60s long, but I watched it for the first time, no problem, but when I watch the next time when I am watching the video, there is a phenomenon that the video image is frozen but the sound is still playing. Which I tried to check and found out that currentTime value running 23rd second suddenly goes back to 2nd even though I don't use seekTo function

Thank you

**Comment by freeboub** [comment]
Can you share this video ? And or check if you reproduce the issue on sample for this git repo ? (Folder sample/basic)

**Comment by freeboub** [comment]
no feedback let's close

**Comment by yoohaso** [comment]
Same here

**Comment by freeboub** [comment]
@yoohaso any additional info ?
