### ISSUE TITLE
Text-Tracks not parsed on iOS

### ISSUE THREAD

**Issue by saringer** [TheWidlarzGroup/react-native-video#2811]
# Bug

Subtitles listed in _textTracks_ are null when utilizing _version 6.0.0-alpha.1_. This issue does not exist on the latest stable release 5.2.0.

## Platform

Tested on iPhone 12 Simulator

## Environment info

Library version: 6.0.0-alpha.1

## Steps To Reproduce

Fetch the available textTracks from data provided via the onLoad-Event.

<img width="356" alt="Screenshot 2022-08-09 at 16 07 22" src="https://user-images.githubusercontent.com/7473273/183670399-e2914e13-8349-44f4-be21-0a1e29323d18.png">

## Video sample

https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by awinograd** [comment]
Potentially related error being thrown:

```
   Signal 4 was raised                                                                                                     
    (                                                                                                                       
        0   Detox                               0x0000000109c2fc15 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 3
7                                                                                                                           
        1   Detox                               0x0000000109c32670 __DTXHandleCrash + 464                                   
        2   Detox                               0x0000000109c32db1 __DTXHandleSignal + 59                                   
        3   libsystem_platform.dylib            0x00007fff701bddfd _sigtramp + 29                                           
        4   ???                                 0x6176206c616e6f69 0x0 + 7022836318794051433                                
        5   libswiftCore.dylib                  0x00007fff309c684b closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()
 in closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> () in Swift._assertionFailure(_: Swift.StaticString, _: Swift.Sta
ticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 267                            
        6   libswiftCore.dylib                  0x00007fff309c663d closure #1 (Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()
 in Swift._assertionFailure(_: Swift.StaticString, _: Swift.StaticString, file: Swift.StaticString, line: Swift.UInt, flags:
 Swift.UInt32) -> Swift.Never + 333                                                                                         
        7   libswiftCore.dylib                  0x00007fff309c61b5 Swift._assertionFailure(_: Swift.StaticString, _: Swift.S
taticString, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never + 309                          
        8                                       0x0000000104530c81 static react_native_video.RCTPlayerOperations.setMediaSel
ectionTrackForCharacteristic(player: Swift.Optional<__C.AVPlayer>, characteristic: __C.AVMediaCharacteristic, criteria: Swif
t.Optional<react_native_video.SelectedTrackCriteria>) -> () + 1457                                                          
        9                                       0x0000000104550bf9 react_native_video.RCTVideo.setSelectedTextTrack(Swift.Op
tional<react_native_video.SelectedTrackCriteria>) -> () + 409                                                               
        10                                      0x00000001045509ec react_native_video.RCTVideo.setSelectedTextTrack(Swift.Op
tional<__C.NSDictionary>) -> () + 92                                                                                        
        11                
```

**Comment by alexejh** [comment]
The main issue is that we pass a custom class array in a react native event. I had not time yet to make a PR, but could successfully test it with this line change.

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/17852273/189372238-6d7ceeaa-396e-4110-b376-f153694daa3b.png">

**Comment by jemise111** [comment]
We're facing this issue too (on 6.0.0-alpha3) but I believe the cause is different.

We're passing a `.m3u8` source with a `selectedTextTrack`. It looks like [setSelectedTextTrack](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L557) is called immediately because the prop is set. This calls [RCTPlayerOperations.setMediaSelectionTrackForCharacteristic](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/Features/RCTPlayerOperations.swift#L131) which relies on `_player` to not be `nil`... but during the initial render it **is** `nil` since it is not instantiated until [this line](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L283) (which intentionally has a built in delay and some setup code first).

And so it is crashing on [this line](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/Features/RCTPlayerOperations.swift#L140) because `group` is `nil`.

This ^ crash also lines up with the stack trace provided by @awinograd.

We were able to fix this by simply adding a guard against `group` being `nil`.

```
static func setMediaSelectionTrackForCharacteristic(player:AVPlayer?, characteristic:AVMediaCharacteristic, criteria:SelectedTrackCriteria?) {
    let type = criteria?.type
    let group:AVMediaSelectionGroup! = player?.currentItem?.asset.mediaSelectionGroup(forMediaCharacteristic: characteristic)
    var mediaOption:AVMediaSelectionOption!

    guard group != nil else { return }  // <======= HERE

    if (type == "disabled") {
        // Do nothing. We want to ensure option is nil
    } else if (type == "language") || (type == "title") {
    ....
    ....
    ....
```

And I believe this fix might be a good one since `setSelectedTextTrack` is called again immediately after `_player` is instantiated (via [applyModifiers](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L288)). If anyone has more insight and agrees I'm happy to put up a PR

**Comment by Polarisation** [comment]
This fix provided by @alexejh in https://github.com/react-native-video/react-native-video/issues/2811#issuecomment-1242044046 worked for me 👍

Edit: I had to also apply the fix by @jemise111 in https://github.com/react-native-video/react-native-video/issues/2811#issuecomment-1279502277 for the case where subtitles are enabled by default when the video is loading.

**Comment by freeboub** [comment]
Can you open a PR with the changes please ?

**Comment by kadamwhite** [comment]
In 6.0.3 we are seeing textTracks render, but on iOS specifically only the first line shows—the subtitles do not advance as the video plays. And if you jump forward and then back, the subtitle does not re-render. I was intending to open this as a new issue but felt it would be best to first comment here as it seems possibly related?

**Comment by fatoldsun00** [comment]
> If anyone has more insight and agrees I'm happy to put up a PR

@jemise111 your solution works well, can you submit a PR please ? Thank you

**Comment by jemise111** [comment]
@fatoldsun00 @freeboub @Polarisation PR is up with (my portion of) the fix https://github.com/react-native-video/react-native-video/pull/2935

**Comment by fatoldsun00** [comment]
Thanks a lot

**Comment by freeboub** [comment]
Fix will be available in alpha.4
