### ISSUE TITLE
React native video tries to hog control centre notification widget. iOS

### ISSUE THREAD

**Issue by CDBridger** [TheWidlarzGroup/react-native-video#2815]
When pausing video then playing a track using react-native-track-player, the react native video still responds to commands from the control center when they are sent to the audio track. 

There doesn't seem to be any way of preventing react native video displaying widget once play has been pressed . 

It would be good if there was something like player.clear(), so it doesn't display the widget or try and respond to events from the control center.

(Also as a side note it would be nice to be able to set Title and Image in the control center widget).

RN 0.69.4
React-Native-Video 5.2

**Comment by CDBridger** [comment]
also is there a discord server?

**Comment by freeboub** [comment]
@CDBridger no, but a slack channel. send me a mail at freeboub@gmail.com, and I think I can invite you !

**Comment by freeboub** [comment]
But this issue rely to react-native-track-player...
Should be reported here : 
https://github.com/doublesymmetry/react-native-track-player
