### ISSUE TITLE
Allow focusable={false} on Video tag

### ISSUE THREAD

**Issue by evoactivity** [TheWidlarzGroup/react-native-video#2819]
# Feature Request

A way to configure the focusable property of the video view.

## Why it is needed

My app is targeted at TV devices, I do not want android to automatically make the video view focusable. With a `<View />` component you can pass `focusable={false}`.

## Possible implementation

I have already made my app work as expected by altering `ReactExoPlayerView.java` using `setFocusable` which can be seen here. https://github.com/evoactivity/react-native-video/commit/06329705c6a5368aa0c63f08620792e5a7a97a2e

I'm happy to provide a PR but would need some guidance on how to setup a prop to pass into the native component. This is my first react native project so I'm still learning.

### Code sample
```jsx
<Video
  source={{
    uri: videoSource,
  }} 
  ref={player}
  focusable={false} 
/>
```

**Comment by freeboub** [comment]
Hello @evoactivity,
I agree this patch make sense!
My advice is to search for similar pull request in the merged PRs
Here is one sample which is not a too big change.
I think you can more or less replicate this change to add a new property 'focusable'
https://github.com/react-native-video/react-native-video/pull/2759/files
Thank you!

**Comment by evoactivity** [comment]
That's a great example for me to learn from! Thank you, this is a side project so I work on it as I can, but I should have a PR ready for this soon :)
