### ISSUE TITLE
player.getCurrentPosition() returns a wrong value for live streams and keep looping through it

### ISSUE THREAD

**Issue by Lilsax** [TheWidlarzGroup/react-native-video#2822]
# Bug

when ever call getCurrentPosition() returns a wrong value then start looping through it as you can see in the image 
 getCurrentPosition started at 48 seconds and then went back to the same value

![image](https://user-images.githubusercontent.com/70263901/185756198-e00cd0b4-b91b-4b34-b0c1-5ce7075a58ea.png)

## Platform
Android TV

Which player are you experiencing the problem on:
* Android

Library version: 5.2

## Steps To Reproduce

just play any LiveStream reproducible DASH and HLS

## Expected behaviour

getCurrentPosition returns value starting from 0 Like for VOD

**Comment by freeboub** [comment]
This is the expected behavior...
0 is the start of your available playback buffer. (I guess you have 1min of buffer in your manifest) 
Every time the manifest is updated, you see the position going in the past as the 0 has also move.

I agree this not the best behavior. Last exoplayer release had some improvements regarding to live playback position, but i didn't experiment it yet.

**Comment by Lilsax** [comment]
@freeboub thank you for getting back to me 
is there anything i can do to get it as i want??

Because I'm working on SSAI project and i need this value to determine if an ad started or no

**Comment by freeboub** [comment]
I cannot find easy workaround... This will need code change to detect ads on exoplayer level, and forward onAdBreakStart / onAdStart to application...

**Comment by Lilsax** [comment]
@freeboub Thank you sir

**Comment by Lilsax** [comment]
@freeboub hello agian! sorry for disturbing but i have a question, is there anyway to read the current segment url ? that is being played right now ??

Thank you

**Comment by freeboub** [comment]
@Lilsax sorry, no there is no easy way to get it.
you have 2 ways to implement this feature:
- get manually the manifest, see getVideoTrackInfoFromManifest in exoplayer implementation (I don't recommand this)
- implement a custom manifest parser in exoplayer -> I think this is the prefered solution with exoplayer, but I don't think this can be done for ios ...

I would say the best solution is to have a separate data track in you playlist... but it needs changes on server side.

**Comment by freeboub** [comment]
here is exoplayer doc: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html
There is maybe an easy way to get ads playback state with one of these accessors: isCurrentMediaItemDynamic or isCurrentWindowLive or isPlayingAd

**Comment by Lilsax** [comment]
@freeboub thank you so much for the reply! anyway i have tried all the possible easy way ( player methods / player listener ) nothing worked for me unfortunately :(

i think i have to implement **custom manifest parser** so do you have a good sample for this? been looking online i didnt find anything related 

thank you agian 
have a good day

**Comment by freeboub** [comment]
maybe in this project ?
https://github.com/MahmoudAlyuDeen/SmartTubeNextFork/blob/1f05ee5c4ae67be280832925e8f2beff41deec61/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/exoplayer/LiveDashManifestParser.java

I searched ```"extends DashManifestParser"``` in github ;)

**Comment by Lilsax** [comment]
Thank you so much sir <3

sorry for the late reply have a good day <3

**Comment by Lilsax** [comment]
@freeboub  Sorry i had to reopen this i have a question 😅❤️
is there anyway to read those values inside the manifest ??
thank you
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/70263901/185903643-cd7eede3-d1d1-47a5-965d-4c1adb426551.png">

**Comment by freeboub** [comment]
Sure, custom manifest parser is a xml parser. But I cannot give you move clues...
When i implemented a custom manifest parser, I did step by step debugging in exoplayer code... It helps me !

**Comment by Lilsax** [comment]
Thank you sir

**Comment by Lilsax** [comment]
@freeboub another question, is there a way to get the manifest in string format ??? Thank you
because i had a solution where i can get the manifest in string and extract the values i want from that value

**Comment by freeboub** [comment]
@Lilsax you can directly download it for JS, but i don't think it woll be accurate in time ..
