### ISSUE TITLE
Read the video from android asset folder

### ISSUE THREAD

**Issue by t104360088** [TheWidlarzGroup/react-native-video#2825]
I must to read the video from android asset folder, so using `require` or putting the video in `android/raw` doesn't suit my needs.
I know this issue has been reported, but it doesn't seem to actually fix it. Hope someone can help me, thanks.

Below are the paths I've tried, but unfortunately none of them work.
```
source={{ uri: 'file:///android_asset/test.mp4' }}
source={{ uri: 'asset:/test.mp4' }}
```

Related References：
[Using file path in react-native-video](https://github.com/react-native-video/react-native-video/blob/master/API.md#file-path-file)
[Path of Android asset folder](https://stackoverflow.com/a/7325290/17364139)
[The same issue but he fix it by adjusting source code](https://github.com/react-native-video/react-native-video/issues/379)
[Read the video from android raw folder but not my case](https://github.com/react-native-video/react-native-video/pull/103#issuecomment-157237650)

The same issue：
#2096, #1826

**Comment by rohitsingh2410** [comment]
try like `require('../../assets/video.mp4')`

`<Video
      ref={(ref) => {
        this.player = ref
      }} 
    source={videoURL}
    style={{
      position: 'relative',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0, width:"100%",height:"100%",
    }} />`

**Comment by t104360088** [comment]
> try like `require('../../assets/video.mp4')`
> 
> `<Video ref={(ref) => { this.player = ref }} source={videoURL} style={{ position: 'relative', top: 0, left: 0, bottom: 0, right: 0, width:"100%",height:"100%", }} />`

Thank you for your answer, but please clarify my problem first, my file is not in the top-level directory, but in the compiled asset directory of android. Your answer is for files placed in the top-level directory.

**Comment by freeboub** [comment]
According java code, it asset:// should be a valid uri to use it. but I didn't find the 'full' implementation (I was expecting specific implementation).
As a workaround you should be able to use file:///data/data/<yourPackageName>/test.mp4 
But depending on installation place of the app this path can change...

According to this:
https://stackoverflow.com/questions/51853695/play-video-with-exoplayer-through-a-folder-in-the-assets-folder

You can also try to use the uri asset:///test.mp4

Please let me know if you find a solution.

**Comment by freeboub** [comment]
did you try with : assets-library:// ?

**Comment by evoactivity** [comment]
This will need a new loader adding to support loading files from assets.

An example of this being done in exoplayer can be seen [here](https://github.com/mattiaferigutti/ExoPlayer-Usage-Sample/blob/2434f9308bb18ca7044bb5befc814bc8cb94e62c/app/src/main/java/com/studio/mattiaferigutti/exoplayertest/ExoPlayerUtil.kt#L33)

We'd essentially want to add a detection for an asset:// type and add a new loader here https://github.com/react-native-video/react-native-video/blob/66b2ba3fcfd4efb7863530da76950ba397ebde85/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L722

**Comment by t104360088** [comment]
@freeboub I tried the way you provided, but unfortunately it doesn't work
