### ISSUE TITLE
Please publish a new npm patch release to fix jcenter with this already commited fix

### ISSUE THREAD

**Issue by francois-pasquier** [TheWidlarzGroup/react-native-video#2826]
👋🏽 I read about the state of the project maintainers wise.

If you guys have some time, could you deploy a 5.2.1 with this fix? (Before 6.0.0)
https://github.com/react-native-video/react-native-video/commit/fd821d2c5cb9d2bc8d52396250993f965886b567

In the current state, the project does not work on android without this simple fix and it may look broken for new users.

If it's too time consuming, maybe pinning an issue telling users to install the repo with the master branch would be beneficial.

**Comment by ckaznable** [comment]
you can try this PR #2795

**Comment by freeboub** [comment]
5.2.1 published, let me know if it is OK
