### ISSUE TITLE
Support React Native 0.68

### ISSUE THREAD

**Issue by vicary** [TheWidlarzGroup/react-native-video#2829]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-video@5.1.0-alpha8` for the project I'm working on.

`ViewPropTypes` has been removed from `react-native`, they recommend importing from `deprecated-react-native-prop-types` in https://github.com/facebook/react-native/issues/33557.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-video/Video.js b/node_modules/react-native-video/Video.js
index 6b84021..e929f68 100644
--- a/node_modules/react-native-video/Video.js
+++ b/node_modules/react-native-video/Video.js
@@ -1,6 +1,7 @@
+import { ViewPropTypes } from "deprecated-react-native-prop-types";
 import React, { Component } from 'react';
 import PropTypes from 'prop-types';
-import { StyleSheet, requireNativeComponent, NativeModules, View, ViewPropTypes, Image, Platform, findNodeHandle } from 'react-native';
+import { StyleSheet, requireNativeComponent, NativeModules, View, Image, Platform, findNodeHandle } from 'react-native';
 import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
 import TextTrackType from './TextTrackType';
 import FilterType from './FilterType';
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by freeboub** [comment]
Thank you for the patch, this change is integrated in 5.2.1 and 6.0.0-alpha.2
