### ISSUE TITLE
Upgrade ExoPlayer to 2.18.1 on v6.0.0-alpha.1

### ISSUE THREAD

**Issue by gabriel-rivero** [TheWidlarzGroup/react-native-video#2831]
# Feature Request

Google released a major ExoPlayer version [r2.18.0](https://github.com/google/ExoPlayer/releases/tag/r2.18.0) and a patch [r2.18.1](https://github.com/google/ExoPlayer/releases/tag/r2.18.1)
Between both versions, there are some DRM improvements like (https://github.com/google/ExoPlayer/issues/10274) and several stability fixes

## Why it is needed

To avoid big refactors when upgrading many versions it's better to upgrade as soon as a major version drops
Several stability and bugfixes for all projects depending on this one

## Possible implementation

I'll handle the upgrade, basically, it's upgrading the dependencies and fixing some Track-related deprecation problems

**Comment by Surinder1922** [comment]
I also looking for updated version of ExpoPlayer in react-native-video to have a try with latest react-native-track-player@3..1.0 to support both audio and video media with full features and controls.

**Comment by se09deluca** [comment]
Me too. A lot of us are using both repos (react-native-video) and (react-native-track-player), with react native 0.68 (or newer) based projects. There are many issues also on rn-track-player repo (see [rntp#1678](https://github.com/doublesymmetry/react-native-track-player/issues/1678), [rntp#1694](https://github.com/doublesymmetry/react-native-track-player/issues/1694)).
It's a common need have this package works on the same version. 
Hope this version gap will be filled shortly, not sure if this point resolution is planned to be resolved with the stable version 6.0 of this package.

**Comment by freeboub** [comment]
PR : https://github.com/react-native-video/react-native-video/pull/2846
Thank you !

**Comment by freeboub** [comment]
will be available in 6.0.0-alpha.2
