### ISSUE TITLE
`.aac` source uri is not seekable

### ISSUE THREAD

**Issue by chulanovskyi-bs** [TheWidlarzGroup/react-native-video#2832]
# Bug
`.aac` files are not `seek`able, means the position can't be controlled by the controls, nor by the ref.seek() method. 

## Platform
Which player are you experiencing the problem on:
* Android
* iOS (probably, but not sure, don't have ability to check)

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.11 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 5.65 GB / 31.29 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.60.6 => 0.60.6
```

Library version: `4.4.5` (but tried also on `5.2` and the latest `6.0.0-alpha.1`)

## Steps To Reproduce

1. [Fetch this](https://github.com/chulanovskyi/react-native-video/tree/aac-issue-example), `react-native-video` fork, repository. It's based on the original one, but with an addition of a helper button and the link to the `.aac` file.
2. Navigate to `examples/basic`.
3. Install packages
4. Launch the project. (used the default `react-native run-android` in my case, having the physical device connected).
5. Press the "Jump to 5 sec" button.
6. Observe that the audio start from the beginning.
...

## Expected behavior

The `seek` function works properly for `.aac` files. In this case - pressing the "Jump to 5 sec" plays the audio starting from 5th second

## Video sample
(per request)

**Comment by freeboub** [comment]
sample stream: https://filesamples.com/samples/audio/aac/sample3.aac

I don't know why, but this url doesn't seem to be seekable.
I cannot even seek with VLC on linux. I suspect an issue with http server...
To be double checked but I am pretty sure this url is not seekable with standard exoplayer sample.
Then, I will close the ticket as this is not related to react-native-video.

Let me known if additionnal info / request is expected.

**Comment by khushal87** [comment]
Hey @freeboub, it still doesn't work for android. Can you help here, or have any suggestions?
