### ISSUE TITLE
Video Not playing in V6 

### ISSUE THREAD

**Issue by keshav-raj** [TheWidlarzGroup/react-native-video#2833]
# Bug

## Platform
Mac 
Which player are you experiencing the problem on:
* Android

## Environment info
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 29.89 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
    Watchman: 2022.08.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 6.0.0-alpha.2

## Steps To Reproduce
After porting to v6 from v5 On initiating it is throwing error saying 
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/trackselection/ExoTrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~hKqs_068ZY8CVDTdtG4OkA==/com.learnyst.learnyststudio-LTX0ZKi-aQwOhQ_Hp3GZjw==/base.apk!classes2.dex)

<img width="1084" alt="Screenshot 2022-08-30 at 4 40 32 PM" src="https://user-images.githubusercontent.com/30136742/187423220-e87a02d6-bd2e-4191-a972-7627549fae1b.png">

**Comment by ceddybi** [comment]
@keshav-raj - I have the same bug on android, were you able to fix it?

**Comment by freeboub** [comment]
Did you try to clean your node_module directly?

**Comment by ceddybi** [comment]
@freeboub looks like it's linked with this issue https://github.com/doublesymmetry/react-native-track-player/issues/1694

**Comment by freeboub** [comment]
@ceddybi in ticket description it is never said that 2 exoplayer version is used ... @keshav-raj can you please clarify ?
for sure, we can add : safeExtGet("exoPlayerVersion", '2.17.0') but I Think this is a false good idea as exoplayer apis are often changing...

Anyway, if you can build a basic sample with the issue, It can help.
Notice that the 'collide' dependency with react-native-track-player cannot be fixed ... (I don't see any easy solution for that except align both exoplayer versions)
Thank you.
