### ISSUE TITLE
tvOS - Default Player controls - change video metadatas (title)

### ISSUE THREAD

**Issue by MathieuHERY** [TheWidlarzGroup/react-native-video#2835]
# Bug

 Hi, 

I'm developing an app for tvOS and i'm using react-native video library to display video content to users. 
When the video is playing, i would like to know how it's possible to change the title which appears once default (native) player controls are displayed (screenshot below). 

Thanks for your help :)

## Platform

tvOS 

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 98.55 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.2-4 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Play video on TvOS device
2. Display native player controls

## Screenshot

<img width="1457" alt="Capture d’écran 2022-08-31 à 17 29 36" src="https://user-images.githubusercontent.com/81353097/187719864-39955314-8f4e-42fc-9682-f3bd695b06de.png">

**Comment by vishalhyperspace** [comment]
I have the same issue. Do you find a solution for it?

**Comment by MathieuHERY** [comment]
@vishalhyperspace as for now, i didn't find any solution for that

**Comment by evoactivity** [comment]
I'm not 100% sure, but I think we could use https://developer.apple.com/documentation/avfoundation/avplayeritem/1627623-externalmetadata on `AVPlayerItem` which would allow us to construct a way to send through a custom title by setting `commonKeyTitle`

I *think* that title would be displayed instead.

If no one implements this though you can try [react-native-media-console](https://github.com/criszz77/react-native-media-console) which supplies a UI with tvOS support, you can fork it and add your own title component.

**Comment by freeboub** [comment]
On V6.0.0-alpha.8 new source sub properties has been added:

[Overriding the metadata of a source](https://github.com/react-native-video/react-native-video/blob/master/API.md#overriding-the-metadata-of-a-source)
Provide an optional title, subtitle, customImageUri and/or description properties for the video. Useful when to adapt the tvOS playback experience.

Example:

source={{ 
    uri: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8', 
    title: 'Custom Title', 
    subtitle: 'Custom Subtitle', 
    description: 'Custom Description',
    customImageUri: 'https://pbs.twimg.com/profile_images/1498641868397191170/6qW2XkuI_400x400.png'
  }}
Platforms: tvOS


Is it matching your expectation ?

**Comment by freeboub** [comment]
no feedback, let's close the issue as done.

**Comment by syed-zuhair-raza** [comment]
Hey , which video player are you using , I used react native video but I don’t get a play pause option rather it auto plays and I can’t pause or do anything
