### ISSUE TITLE
HTTP link not play in react-native-video

### ISSUE THREAD

**Issue by shihabmilky1** [TheWidlarzGroup/react-native-video#2836]
<Video source={{uri: 'http://live.tvdhaka.com:30443/Channel-1/tracks-v1a1/chunks.m3u8'}} 
           style={{width:'100%',height:'100%',  backgroundColor:'#000'}} 
   
                      
           />

How can i play http link in react native video please help me

**Comment by freeboub** [comment]
Did you add usesCleartextTraffic in your manifest?
Please provide more information, it is hard to help without more logs or description of what happen...

**Comment by shihabmilky1** [comment]
thank you for you help i add usesCleartextTraffic in androidmainfest and its working
