### ISSUE TITLE
Error playing m3u8 files from Azure media streaming service

### ISSUE THREAD

**Issue by davidteejay** [TheWidlarzGroup/react-native-video#2844]
# Bug
I'm trying to play videos from Azure media streaming service. The videos come in the `m3u8` format. They played well on iOS devices, but on Android devices, I got `{"error":{"extra":-1007,"what":1}}`.

According to [#2779](https://github.com/react-native-video/react-native-video/issues/2779), the issue has been fixed in master, and I switched from `"react-native-video": "^5.2.0"` to `"react-native-video": "react-native-video/react-native-video"`, but now, I' getting this:

```
{"error": {"errorCode": "23003", "errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorStackTrace": "com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
", "errorString": "ExoPlaybackException: ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED"}}
```

and builds are failing on iOS:
<img width="1141" alt="Screenshot 2022-09-05 at 9 16 11 AM" src="https://user-images.githubusercontent.com/19327099/188401885-cbd586f8-8943-4133-963f-12c25e40f0b1.png">
<img width="1141" alt="Screenshot 2022-09-05 at 9 16 32 AM" src="https://user-images.githubusercontent.com/19327099/188401951-eadf262d-3773-40a7-905d-e7d8581d10f3.png">

## Platform
* iOS
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 122.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    Watchman: 2022.08.29.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0, react-native-video/react-native-video

## Steps To Reproduce

1. Try to play an m3u8 file

**Comment by freeboub** [comment]
Please check you are able to download the content manually ( with wget ).
This is typically a token issue in headers

**Comment by davidteejay** [comment]
I am able to download the content manually.

<img width="995" alt="Screenshot 2022-09-05 at 11 19 32 PM" src="https://user-images.githubusercontent.com/19327099/188517064-b7ee41b3-6d2f-4e0d-ba38-1253863cdd25.png">

**Comment by freeboub** [comment]
You may need to force stream type to dash also

**Comment by davidteejay** [comment]
I've fixed it. I added a patch to `5.2.0`:

```
diff --git a/node_modules/react-native-video/android-exoplayer/build.gradle b/node_modules/react-native-video/android-exoplayer/build.gradle
index d005a58..6a9922b 100644
--- a/node_modules/react-native-video/android-exoplayer/build.gradle
+++ b/node_modules/react-native-video/android-exoplayer/build.gradle
@@ -28,7 +28,7 @@ android {

 dependencies {
     implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
-    implementation('com.google.android.exoplayer:exoplayer:2.13.2') {
+    implementation('com.google.android.exoplayer:exoplayer:2.13.3') {
         exclude group: 'com.android.support'
     }

@@ -37,7 +37,7 @@ dependencies {
     implementation "androidx.core:core:1.1.0"
     implementation "androidx.media:media:1.1.0"

-    implementation('com.google.android.exoplayer:extension-okhttp:2.13.2') {
+    implementation('com.google.android.exoplayer:extension-okhttp:2.13.3') {
         exclude group: 'com.squareup.okhttp3', module: 'okhttp'
     }
     implementation 'com.squareup.okhttp3:okhttp:${OKHTTP_VERSION}'
```

And I also added `type: "m3u8"` to the source. I am able to play videos on iOS and Android now.

**Comment by jeroenvanhattem** [comment]
> I've fixed it. I added a patch to `5.2.0`:
> 
> ```
> diff --git a/node_modules/react-native-video/android-exoplayer/build.gradle b/node_modules/react-native-video/android-exoplayer/build.gradle
> index d005a58..6a9922b 100644
> --- a/node_modules/react-native-video/android-exoplayer/build.gradle
> +++ b/node_modules/react-native-video/android-exoplayer/build.gradle
> @@ -28,7 +28,7 @@ android {
> 
>  dependencies {
>      implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
> -    implementation('com.google.android.exoplayer:exoplayer:2.13.2') {
> +    implementation('com.google.android.exoplayer:exoplayer:2.13.3') {
>          exclude group: 'com.android.support'
>      }
> 
> @@ -37,7 +37,7 @@ dependencies {
>      implementation "androidx.core:core:1.1.0"
>      implementation "androidx.media:media:1.1.0"
> 
> -    implementation('com.google.android.exoplayer:extension-okhttp:2.13.2') {
> +    implementation('com.google.android.exoplayer:extension-okhttp:2.13.3') {
>          exclude group: 'com.squareup.okhttp3', module: 'okhttp'
>      }
>      implementation 'com.squareup.okhttp3:okhttp:${OKHTTP_VERSION}'
> ```
> 
> And I also added `type: "m3u8"` to the source. I am able to play videos on iOS and Android now.

For me adding `type: "m3u8"` fixed it
