### ISSUE TITLE
Cannot read Constants error when using exoplayer-android

### ISSUE THREAD

**Issue by swiggyrahulgupta5** [TheWidlarzGroup/react-native-video#2847]
# Bug

Hi,
I am trying to run exoplayer-android but it is throwing me error "Cannot read constants..."
If i add android in settings.gradle it works fine but not working with exoplayer.

## Platform
Android

Which player are you experiencing the problem on:
* Android

Library version: 5.2.0

**Comment by freeboub** [comment]
Please test with V6 release and provide a sample to reproduce.
