### ISSUE TITLE
[Bug] Poster inhibits use of controls (iOS)

### ISSUE THREAD

**Issue by mattmercuri** [TheWidlarzGroup/react-native-video#2851]
# Bug
*Version*: 5.0.2
Having a poster showing in the player does not allow the user to interact with the controls. By this I mean, the user cannot press pause, fullscreen, mute or seek on the timeline. Nothing responds to touch. My use case is playing a network mp3. The problem persists regardless of the audioOnly prop being set to true. This only occurs on iOS, not Android.

## Platform
Just experiencing this on iOS. Behaviour seems to be as intended for Android.

## Environment info
React native info output:

```bash
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 59.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.03.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.0.2

## Steps To Reproduce

Sample code below yields the issue.

## Expected behaviour
Having the audioOnly prop set to true should allow the user to interact with the native controls.

## Reproducible sample code
```jsx
<Video
          source={{ uri: contentSourceUri }}
          poster={posterUri}
          resizeMode="contain"
          posterResizeMode="contain"
          controls
          audioOnly // occurs even without this set
/>
```

**Comment by freeboub** [comment]
This issue cannot be fixed. Controls are on native view, where poster is over the native view...
The only solution is to implement your own custom controls.
I close the ticket as I consider it as is fixable for now

**Comment by mattmercuri** [comment]
> This issue cannot be fixed. Controls are on native view, where poster is over the native view... The only solution is to implement your own custom controls. I close the ticket as I consider it as is fixable for now

Understandable. Thanks!
