### ISSUE TITLE
[Android] cannot run video m3u8

### ISSUE THREAD

**Issue by lamlengend98** [TheWidlarzGroup/react-native-video#2856]
I have a m3u8 link, it runs perfectly on IOS, but cannot run on Android
The exception is ```{"error": {"extra": -1004, "what": 1}}```
I was known that is error from Android's Media Player and the solution is "enable exoplayer"
I tried but cannot use that player
First, I editted react-native.config.js like below
![image](https://user-images.githubusercontent.com/37770203/190123694-2a0bfd33-f2b4-49c8-a4ec-e2a779e803bc.png)
but It's not working
Second, I editted settings.gradle like
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
But there was crash when Video was mounted and the error in logcat is
```
Didn't find class com.google.android.exoplayer2.video.videolistener
```
I don't know what I can do now

```
"react-native": "0.64.0",
"react-native-video": "^5.1.1",
"react-native-video-cache": "^2.0.5",
"react-native-multiple-video-player": "https://github.com/lamlengend98/-lamnt-react-native-multi-video",
```
Here is all video libraries which I'm using

**Comment by lamlengend98** [comment]
Okay, I fixed errors above, but I still cannot run m3u8, the exception is 
```
{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}
```
the source code is
```javascript
    <Video
        controls={true}
        onError={(e) => console.log('====================================', e)}
        source={{
          uri: url,
          type: 'm3u8',
        }}
        style={{ width: 200, height: 200, backgroundColor: 'red' }}
      />
```

**Comment by evoactivity** [comment]
The latest version of the library is not yet available on NPM

Update your package.json to one of these, reinstall and try your app again.
v6 alpha
```json
"react-native-video": "react-native-video/react-native-video",
```
v5.2.1 
```json
"react-native-video": "react-native-video/react-native-video#support/5.2.X",
```

Edit: Looks like this was released on npm
so these will also work
v6 alpha
```json
"react-native-video": "^6.0.0-alpha.3",
```
v5.2.1 
```json
"react-native-video": "^5.2.1",
```

**Comment by lamlengend98** [comment]
> ```json
> 5.2.1
> ```

I tried v5.2.1 but it still be worked

**Comment by lamlengend98** [comment]
> The latest version of the library is not yet available on NPM
> 
> Update your package.json to one of these, reinstall and try your app again. v6 alpha
> 
> ```json
> "react-native-video": "react-native-video/react-native-video",
> ```
> 
> v5.2.1
> 
> ```json
> "react-native-video": "react-native-video/react-native-video#support/5.2.X",
> ```
> 
> Edit: Looks like this was released on npm so these will also work v6 alpha
> 
> ```json
> "react-native-video": "^6.0.0-alpha.3",
> ```
> 
> v5.2.1
> 
> ```json
> "react-native-video": "^5.2.1",
> ```

I tried v5.2.1 but it still be not worked

**Comment by freeboub** [comment]
I didn't notice you use react-native-multiple-video-player. Maybe the issue is in this package.
Can you clarify the <Video import ?
You should also test your url in the basic sample to check if you reproduce the same issue

**Comment by songuyen1816** [comment]
same here, I only install react-native-video and get the same error.

It appear when add
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
instead of 
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

**Comment by lamlengend98** [comment]
> I didn't notice you use react-native-multiple-video-player. Maybe the issue is in this package. Can you clarify the <Video import ? You should also test your url in the basic sample to check if you reproduce the same issue

@freeboub  I import <Video from react-native-video, the component from react-native-multiple-video-player is VideoPlayer, I had tried to remove it before, but it still happens, the problem is not about react-native-multiple-video-player
The issue is that I got the error about format media on my first comment, it worked on IOS but not on Android

**Comment by lamlengend98** [comment]
> same here, I only install react-native-video and get the same error.
> 
> It appear when add
> 
> ```
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> ```
> 
> instead of
> 
> ```
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
> ```

Did you get the crash or error about format media ?

**Comment by songuyen1816** [comment]
> > same here, I only install react-native-video and get the same error.
> > It appear when add
> > ```
> > include ':react-native-video'
> > project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead of
> > ```
> > include ':react-native-video'
> > project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
> > ```
> 
> Did you get the crash or error about format media ?

I'm not sure, I use it because the stream-chat-react-native library requires it to play video. Will it run properly if you don't add source.type?

**Comment by lamlengend98** [comment]
> > > same here, I only install react-native-video and get the same error.
> > > It appear when add
> > > ```
> > > include ':react-native-video'
> > > project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > instead of
> > > ```
> > > include ':react-native-video'
> > > project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
> > > ```
> > 
> > 
> > Did you get the crash or error about format media ?
> 
> I'm not sure, I use it because the stream-chat-react-native library requires it to play video. Will it run properly if you don't add source.type?

No, it don't run even adding source .type or not

**Comment by lamlengend98** [comment]
Okay, by some ways, this ran. I added certificate provided by this video's server to my android xml file.

**Comment by songuyen1816** [comment]
> Okay, by some ways, this ran. I added certificate provided by this video's server to my android xml file.

Can you explain more, what is that file, no need too much detail

**Comment by lamlengend98** [comment]
> > Okay, by some ways, this ran. I added certificate provided by this video's server to my android xml file.
> 
> Can you explain more, what is that file, no need too much detail

@songuyen1816 
I requested my back-end dev a certificate from server and save it to a file "my_ca.crt", put it to android/app/src/main/res folder and create a file "network_security_config.xml" in xml folder like
![image](https://user-images.githubusercontent.com/37770203/190368948-afb04696-c9bb-4412-b1c7-5ec1d57253c3.png)
finally, add a line to AndroidManifest.xml
<application android:networkSecurityConfig="@xml/network_security_config".... />

**Comment by freeboub** [comment]
@lamlengend98 can you explain how did you found the root cause ? Because if you where able to download the content manually, you shouldn't need this certificate? Is the isclearTextTraffic enough? Thank you

Edit I want to complete this PR: https://github.com/react-native-video/react-native-video/pull/2858
