### ISSUE TITLE
mp4 video is brighter color in iOS 16 simulator only

### ISSUE THREAD

**Issue by fitouch** [TheWidlarzGroup/react-native-video#2862]
# Bug

## Platform

iOS

## Environment info

Library version: 6.0.0-alpha.3

## Steps To Reproduce

1. mp4 video is brighter color in iOS 16 simulator only

**Comment by freeboub** [comment]
Thank you for the report, but I don't think anybody will investigate this issue ad it is an emulator issue ...
Can you provide a link to the video ? Or is it happening on all mp4 ?
To investigate I think you should test on a standalone avplayer first...

**Comment by ZukaGap** [comment]
I have same issue
before iOS 16 It's works fine

**Comment by tbergeron** [comment]
The same happens on device. For example I have this color #FF6666 in a video and when it's being played I see #f3576a which is a totally different color. Why would that even happen?

**Comment by ToshKoevoets** [comment]
Im also running into it, seems to be videos recorded with iphones.

It's also on "real" devices an issue.

I've enabled the following for those videos.

filterEnabled={true}
filter={FilterType.FADE}

Which looks better, but not ideal

**Comment by samiullah452** [comment]
Anyone able to solve it?
