### ISSUE TITLE
HTTP headers in iOS

### ISSUE THREAD

**Issue by se09deluca** [TheWidlarzGroup/react-native-video#2865]
# Feature Request
## HTTP headers in iOS

Hello, we want to show to our users personalized video with sensible contents.
We need to use react-native-video with an authorization token, but the headers functionality seems to be an Android only feature as stated from documentation

> #### headers
> Pass headers to the HTTP client. Can be used for authorization. Headers must be a part of the source object.
> 
> Example:
> ```
> source={{
>   uri: "https://www.example.com/video.mp4",
>   headers: {
>     Authorization: 'bearer some-token-value',
>     'X-Custom-Header': 'some value'
>   }
> }}
> ```
> 
> Platforms: Android

## Why it is needed

Adds the ability to render restricted videos that need and authorization

### Code sample
```js
source={{
   uri: "https://www.example.com/video.mp4",
   headers: {
     Authorization: 'bearer some-token-value',
     'X-Custom-Header': 'some value'
   }
}}
```

**Comment by freeboub** [comment]
I just have a look to the code, and I confirm thisis not currently supported.
Here is an interesting discussion if you want to implement it:
https://stackoverflow.com/questions/15456130/add-custom-header-field-in-request-of-avplayer

**Comment by evoactivity** [comment]
@freeboub Looks like this actually should be enabled somehow, the video source struct has requestHeaders https://github.com/react-native-video/react-native-video/blob/68b9db4d1120f2588120ad09883cef676d95190d/ios/Video/DataStructures/VideoSource.swift#L8 which is then added to AVURLAsset here https://github.com/react-native-video/react-native-video/blob/bb6b347ef035574987d492fd1bd8f5406b12b249/ios/Video/Features/RCTVideoUtils.swift#L294

**Comment by freeboub** [comment]
@evoactivity good catch thank you !

@se09deluca did you try to use the field ? or is it just a documentation issue ? if it doesn't work did you double check with charles proxy to ensure the headers are missing ?

Thank you

**Comment by se09deluca** [comment]
Hi, I finally found the time to do some tests.
The headers are sent, I found them with both Flipper and Charles. Here are a couple of screens.
| Inspector / Proxy tool | screenshot  |
| :---:   | :---: |
| With Flipper | <img width="331" alt="flipper" src="https://user-images.githubusercontent.com/53230888/196154382-9c0f13a4-032b-4b70-bd80-72012bd4cb79.png"> |
| With Charles | <img width="1074" alt="charles_contents_headers" src="https://user-images.githubusercontent.com/53230888/196154504-5df37538-fdec-44c5-9898-189d247ea9fb.png"> |


As you can see the response body is empty in Flipper, in Charles we got:
`Failure: Client closed connection before receiving entire response`
as you can read from the below screenshot of charles overview tab
<img width="1070" alt="charles_overview" src="https://user-images.githubusercontent.com/53230888/196155656-ec341ef5-03bc-47df-8690-2b54f14df279.png">
Xcode reports an error like this:
```
   { code: -11850,
     localizedRecoverySuggestion: '',
     domain: 'AVFoundationErrorDomain',
     localizedFailureReason: 'Il server non è configurato correttamente.',
     localizedDescription: 'Operazione interrotta' } }
```


Searching this error i found this old issue, a user suggested to try changing the HTTP method from GET to POST. 
I would like to test it, but i didn't find out how to load video source from a POST Api. Maybe this is not currently possible.. Reading react-native-video's prop types the method is not accepted.

Diving into the AVFoundation's docs i've found the AVURLAsset used in RCTVideoUtils, but it doesn't mention the possibility of specify the HTTP method to use. 

I'll close this issue as the header problem seems to be only a documentation issue. 

The failure message 'Client closed connection before receiving entire response' still is a problem, but a different one. Not sure if strictly related.
