### ISSUE TITLE
source Error unrecognised  media format 

### ISSUE THREAD

**Issue by srinath116** [TheWidlarzGroup/react-native-video#2867]
# Bug

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 34.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
```

Library version: 5.2.0

## Expected behaviour

1. this issue happens when i have recorded my videos on web and serving them from my server, it is happening ocassionally 
2. im able to play the videos in ios and web but getting the issue with android

## Reproducible sample code

<Video
source={{uri:'https://rebelliuz.com:9001/videointro/pL22R0_1663736208667.mp4', type:"mp4"}}
height={200}
width={200}
/>

## Video sample

video Url :https://rebelliuz.com:9001/videointro/pL22R0_1663736208667.mp4

**Comment by freeboub** [comment]
I tried to play the video from my browser, it seems tat format is strange, the player is not able to determine duration at start...
First, Can you try with v6 alpha please ?
If it doesn't work you will need to try on exoplayer standalone sample. 
In the same time, can you provide the error displayed in the logcat ?

**Comment by evoactivity** [comment]
Media Info shows the file is actually an mkv container not an mp4 and the file is truncated. I tried with iOS emulator where it also does not play, and also Firefox is unable to play the video.

It looks like this recording was created using chrome, I assume from a `getUserMedia` session, possibly through webrtc so it's basically just a stream of video and audio data without being finalised and having all metadata written.

Try running your file through ffmpeg to convert to an valid mp4 `ffmpeg -i myfile.mp4 newfile.mp4` and see if it will stream correctly.

**Comment by srinath116** [comment]
@evoactivity  thanks for the response  i will look into it
