### ISSUE TITLE
conflicting with Rive

### ISSUE THREAD

**Issue by Bayramito** [TheWidlarzGroup/react-native-video#2868]
as like i mentioned here in my post on rive github

these 2 libs are conflicting each other on XCode build time.

[https://github.com/rive-app/rive-react-native/issues/145](https://github.com/rive-app/rive-react-native/issues/145)

**Comment by evoactivity** [comment]
I've opened a PR that will fix the collision, can you try installing and testing from the PR and let us know if the issue is resolved, you may need to pod install again.

**Comment by Bayramito** [comment]
I got this error once i renamed the folder and files in it...

i did pod install 
<img width="1269" alt="Ekran Resmi 2022-09-26 10 30 48" src="https://user-images.githubusercontent.com/44513402/192218330-0c6dbcf0-1099-4e6a-8ee8-0a5db8442cb9.png">


EDIT: I managed to make it work by setting under Pods project > React-Core > Requires Only App-Extension-Safe-API to NO 

But i dont know if this affect something other

**Comment by Bayramito** [comment]
Quick UPDATE: The App gets slow when i made these changes... It is like in 30 fps.

**Comment by evoactivity** [comment]
This error is not related to react-native-video at all. If you can install and use the package then I would say the conflict with rive has been fixed. Renaming some files/interfaces isn't going to change the performance of your app.

My project already had `Requires Only App-Extension-Safe-API` set to no by default, so I'm not sure why yours was set to yes to begin with.

To help you debug, you can try changing 
```swift
BOOL interactionEnabled = !UIApplication.sharedApplication.isIgnoringInteractionEvents;
```
to
```swift
BOOL interactionEnabled = !RCTSharedApplication().isIgnoringInteractionEvents;
```
And leave the `Requires Only App-Extension-Safe-API` set to yes, but I don't think the performance problems are from those changes.

I have stable 60fps for both UI and JS threads so I would assume the performance problems are coming from somewhere else in your app.

I've created a PR in react-native with the above change though as I believe usage of `UIApplication.sharedApplication` is an error.
https://github.com/facebook/react-native/pull/34787
