### ISSUE TITLE
Custom seek bar slider control is causing the video to stutter

### ISSUE THREAD

**Issue by AlkenD** [TheWidlarzGroup/react-native-video#2869]
# Bug

As soon as the slider moves [seeks] the video becomes laggy

## Platform
Android

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 517.08 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 28, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.1.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1) I have provided a sample code below to use
2) create a fresh react-native app
3) install react video player and @react-native-community/slider
4) run the application [i used a physical device]

## Expected behaviour

The seeking should be seamless without stuttering

## Reproducible sample code

```
import Slider from '@react-native-community/slider';
import React from 'react';
import { View } from 'react-native';
import Video from 'react-native-video';

const VideoPlayer = (props: any) => {
    const { url } = props;
    const videoRef = React.useRef<any>(null);
    const [player, setPlayer] = React.useState({
        paused: false,
        muted: false,
        seeking: false,
        duration: 0,
        currentTime: 0,
        fullscreen: false,
    });

    const onLoad = (data: any) => {
        setPlayer({ ...player, duration: data.duration, currentTime: data.currentTime });
    };

    const onProgress = (data: any) => {
        setPlayer({ ...player, currentTime: data.currentTime });
    };

    const onSeek = (data: any) => {
        videoRef.current.seek(data);
        setPlayer({ ...player, currentTime: data });
    };

    console.log(player.currentTime);
    return (
        <View style={{ flex: 1 }}>
            <Video
                ref={videoRef}
                onLoad={onLoad}
                paused={player.paused}
                onProgress={onProgress}
                style={{ aspectRatio: 16 / 9 }}
                source={{
                    uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
                }}
            />

            <Slider
                style={{ width: '100%', height: 40 }}
                value={player.currentTime}
                step={1}
                onSlidingStart={() => setPlayer({ ...player, seeking: true, paused: true })}
                onSlidingComplete={() => setPlayer({ ...player, paused: false })}
                onValueChange={onSeek}
                minimumValue={0}
                maximumValue={player.duration}
                minimumTrackTintColor='#FFFFFF'
                maximumTrackTintColor='#000000'
            />
        </View>
    );
};

export default VideoPlayer;
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

[link to the video](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4)

**Comment by evoactivity** [comment]
Your slider runs the `onSeek` function every time the value changes so every time an `onProgress` event fires, the slider is re-rendered with a new value, so `onSeek` is fired, resulting in the video being instructed to seek to current frame.

change 
```tsx
onSlidingComplete={() => setPlayer({ ...player, paused: false })}
```
to
```tsx
onSlidingComplete={() => setPlayer({ ...player, seeking: false, paused: false })}
```

and update your onSeek function to return early if not seeking
```tsx
const onSeek = (data: any) => {
  if (!player.seeking) return;
  videoRef.current.seek(data);
  setPlayer({ ...player, currentTime: data });
};
```

You should see performance improve dramatically since you are not seeking every frame.

I would advise looking at https://github.com/criszz77/react-native-media-console as an example of implementing custom controls.

**Comment by AlkenD** [comment]
> ```tsx
> const onSeek = (data: any) => {
>   if (!player.seeking) return;
>   videoRef.current.seek(data);
>   setPlayer({ ...player, currentTime: data });
> };
> ```

thanks a bunch this solved my issue ill definitely look at the https://github.com/criszz77/react-native-media-console library

**Comment by AlkenD** [comment]
> > ```tsx
> > const onSeek = (data: any) => {
> >   if (!player.seeking) return;
> >   videoRef.current.seek(data);
> >   setPlayer({ ...player, currentTime: data });
> > };
> > ```
> 
> thanks a bunch this solved my issue ill definitely look at the https://github.com/criszz77/react-native-media-console library

btw this caused a new issue the tap to seek doesn’t work anymore the slider doesn’t move when taped on the time line but works perfectly when scrubbed
