### ISSUE TITLE
Video shows in debug build. Doesn't show in release. [6.0.0-alpha.3] [Windows]

### ISSUE THREAD

**Issue by cjhines** [TheWidlarzGroup/react-native-video#2872]
# Bug

## Platform

Which player are you experiencing the problem on:
* Windows UWP

## Environment info

React native info output:

```bash
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 9.30 GB / 15.99 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: 0.69.6 => 0.69.6
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.3

## Steps To Reproduce

```tsx
      <Video
        source={require('./dummy_video.mp4')}
        controls={true}
        style={styles.video}
        onLoad={() => Alert.alert('Loaded')}
        onError={(error) => Alert.alert('Error', JSON.stringify(error))}
        onLoadStart={() => Alert.alert('Loading..')}
        paused={true}
      />
```

**Comment by cjhines** [comment]
Seems similar in symptoms to this issue: https://github.com/microsoft/react-native-windows/issues/7855

However the fix for this was already merged in an earlier version.

**Comment by evoactivity** [comment]
@namrog84 as the last to touch the windows side of things I am hoping you may have some time to help investigate this issue? It's ok if you can't 🙂

**Comment by namrog84** [comment]
I can take a look at it as soon as I get some extra time to.

**Comment by cjhines** [comment]
I got this while running release locally, but the bundled video works fine in debug build. Will try a `uri` source.

<img width="295" alt="Screenshot 2022-09-29 at 09 44 05" src="https://user-images.githubusercontent.com/16542421/192973392-8a904444-8ed9-4c15-90ee-bf3b806d9c51.png">

**Comment by mhunchojack** [comment]
I am having the same problem in Android. I am trying to load a video from RN Asset System, which works perfectly fine in Debug, but fails in Release Build, shows only a black screen.

**Comment by EducoreAPK** [comment]
any update on this bug in Android, I am having a black screen also in Release version. 
I am loading video from local assets
