### ISSUE TITLE
React-native-video reloads when orientation change (react-native-orientation-locker) (Android only)

### ISSUE THREAD

**Issue by Girum** [TheWidlarzGroup/react-native-video#2873]
Hi! I used the react-native-orientation library. Because the new ios16 update, in iOS it not works correctly. So, now I triyng to use the react-native-orientation-locker library instead.

I used that to use with react-native-video. But, always when the orientation change for somehow, the video stops to play and restart (i used something like a miniplayer). Then, when I change the bottom bar, it stops too. This happens only in Android.

With the react-native-orientation this not happens (but I cant maintain the two working, because duplicate errors).

EDIT: i put console.log in onLoad. When I rotate, or even change bottom bar, the onLoad fires again)

Anyone knows how to avoid this behavior?

**Comment by evoactivity** [comment]
Are you able to share a simple reproducible sample?

**Comment by Girum** [comment]
After all hard tests and install and uninstall libraries, for a reason in updates to iOS16, some libraries where given problem in android, so I fixed their version (e.g Reanimated). For that reason, this causes this bug. After a hard work to update Gradle, fix in the PodFile, etc, etc, etc, it resolved the issue.

**Comment by Hyachin** [comment]
i encounter the same issues. Could you tell me how to solve

> After all hard tests and install and uninstall libraries, for a reason in updates to iOS16, some libraries where given problem in android, so I fixed their version (e.g Reanimated). For that reason, this causes this bug. After a hard work to update Gradle, fix in the PodFile, etc, etc, etc, it resolved the issue.

**Comment by nghuymb** [comment]
> After all hard tests and install and uninstall libraries, for a reason in updates to iOS16, some libraries where given problem in android, so I fixed their version (e.g Reanimated). For that reason, this causes this bug. After a hard work to update Gradle, fix in the PodFile, etc, etc, etc, it resolved the issue.

Could you tell me how to solve
