### ISSUE TITLE
Fails to play clearkey encrypted mpeg-dash content

### ISSUE THREAD

**Issue by nunsie** [TheWidlarzGroup/react-native-video#2874]
# Bug
Fails to play clearkey encrypted content, prints the following

```
{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}
```

Additionally, I've noted that it doesn't even call the `licenseServer` url when `clearkey` is specified - however if I try `widevine` for example, it does and works perfectly (obviously providing a widevine protected manifest instead of clearkey one)

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. Install package following this install guide https://github.com/react-native-video/react-native-video/blob/master/API.md#android-installation
2. update gradle config to use exoplayer as outlined here: https://github.com/react-native-video/react-native-video/issues/2461#issuecomment-1154098667

## Expected behaviour

1. Calls licenseServer url when `DRMType.CLEARKEY` is provided as drm type
2. Plays clearkey encrypted content

## Reproducible sample code

```jsx
<Video
  source={{
    uri: "https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd",
  }}
  drm={{
    type: DRMType.CLEARKEY,
    licenseServer: "https://drm-clearkey-testvectors.axtest.net/AcquireLicense",
  }}
  controls={true}
  resizeMode="contain"
  onError={(e) => {
    console.log("error", e)
  }}
/>
```

## Video sample
Manifest: https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd
License: https://drm-clearkey-testvectors.axtest.net/AcquireLicense

**Comment by evoactivity** [comment]
What version of the library are you using?

I am using 6.0.0-alpha.3 and I am watching the source video using your sample code.

edit: I've tried 5.2.1 and it's playing with that version too.

**Comment by nunsie** [comment]
I've patched this locally but not familiar with contribution guidelines yet.
I also know very little java don't know what side-effects this might have for other use-cases.
I will read the guidelines this weekend and open a PR.

But for now here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index fe95fdf..e545a48 100644
--- a/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -483,7 +483,7 @@ class ReactExoplayerView extends FrameLayout implements
         if (Util.SDK_INT < 18) {
             return null;
         }
-        HttpMediaDrmCallback drmCallback = new HttpMediaDrmCallback(licenseUrl,
+        HttpMediaDrmCallback drmCallback = new HttpMediaDrmCallback(licenseUrl,true,
                 buildHttpDataSourceFactory(false));
         if (keyRequestPropertiesArray != null) {
             for (int i = 0; i < keyRequestPropertiesArray.length - 1; i += 2) {
```

From the exoplayer javadoc for [HttpMediaDrmCallback](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.html#%3Cinit%3E(java.lang.String,boolean,com.google.android.exoplayer2.upstream.DataSource.Factory)) - this sets the `forceDefaultLicenseUrl` flag which forces it to use the `licenseServer` url param, which solves for the clearkey issue above

I may have missed some configuration as this is my first time using this package and maybe this isn't an actual bug (just my lack of understanding) and hence no need for a code change, but leaving this issue open for some feedback.

**Comment by nunsie** [comment]
> What version of the library are you using?
> 
> I am using 6.0.0-alpha.3 and I am watching the source video using your sample code.
> 
> edit: I've tried 5.2.1 and it's playing with that version too.

Weird - will try again later in a fresh repo, start from scratch..

I also tried switching out for 5.2.1 for 6.0.0-alpha.3 but get the same result

**Comment by freeboub** [comment]
I also try on master branch on emulator, I don't have the issue.
Notice that there is maybe an issue with the server configuration:

```
 wget https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd
--2022-09-28 23:18:35--  https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd
Resolving media.axprod.net (media.axprod.net)... 52.233.190.107
Connecting to media.axprod.net (media.axprod.net)|52.233.190.107|:443... connected.
GnuTLS: One of the involved algorithms has insufficient security level.
Unable to establish SSL connection.
```

regarding to your patch, it will force usage of DRM url provided in manifest, but it is the same one, so it doesn't explain why it doesn't work...

Usually "Unrecognized media format" is due to content type resolution but with a .mpd it should be OK.
There is maybe more information in the logcat ?

**Comment by freeboub** [comment]
no update since 1 month, let's close. I hope you fix the issue @nunsie ?

**Comment by upgradrh** [comment]
@freeboub  facing this same issue

"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format

**Comment by freeboub** [comment]
@upgradrh any sample to provide ?

**Comment by upgradrh** [comment]
was trying to integrate [brightcove video](https://medium.com/@parthchugh/brightcove-with-react-native-video-d60039db7e41) as per the article

I got an issue and fixed it by [this](https://github.com/react-native-video/react-native-video/issues/2078#issuecomment-659538267) fix

After that, I was getting the above [issue](https://github.com/react-native-video/react-native-video/issues/2874#issuecomment-2034388329).

My video is in mpd format
