### ISSUE TITLE
Community Discord

### ISSUE THREAD

**Issue by evoactivity** [TheWidlarzGroup/react-native-video#2876]
Hello everyone who uses React Native Video

As the only viable open source react native video component, there is a large user base with some big players (👋 @crunchyroll), but as discussed in the [Setting Maintenance Expectations](https://github.com/react-native-video/react-native-video/issues/2788) issue, there is only a small group of active contributors. I would suggest part of the reason for this is because github doesn't lend itself to building communities, it's simply where my tools are.

I've seen talk of a slack for maintainers but I would suggest there are benefits to having an open community discord as an open source project.

1) Discord are rolling out a forum feature, perfect for help to be given in threaded discussions
2) It would be the first stop for troubleshooting and advice from the community which **reduces** the number of issues opened
3) We can co-ordinate maintenance efforts in the open
4) It's **easier** to attract new maintainers from an active community

I believe this package is important enough and there are enough users of it, that creating an active community around the project will be the best way to ensure the survival and ongoing maintenance required by such a vital part of the react native ecosystem.

If it's simply a case of someone setting one up then I would be happy to do that if I see support on this issue for it, so please leave a reaction so I can see if it's worth it 👍

**Comment by freeboub** [comment]
@evoactivity A slack channel is already available, I can invite you for sure ! Please, send me a mail @ freeboub@gmail.com

**Comment by abanobmikaeel** [comment]
Please invite me. I’m interested in the slack channel as well. email is abanobmikaeel@gmail.com

**Comment by freeboub** [comment]
@evoactivity Did you finally create a discord channel ? I would like to put the link in project status discussion.
I personally cannot participate to it. but if other people wants to join, it is welcome !

**Comment by evoactivity** [comment]
@freeboub I didn't see much support for it here so I didn't, if you feel it could be worthwhile I'll set one up (probably in the new year if I'm honest, I have a lot of stuff lined up between now and then)

**Comment by freeboub** [comment]
@evoactivity
Ok, no problem, (I hoped you will do long term maintenance...)
And someone said me that he spoked about RNV on discord.
I will close this ticket.
Thank you anyway !

**Comment by evoactivity** [comment]
My project using RNV will be starting again in the new year so I will become a lot more active in this repo at that point, but I've been doing a lot more web based video work recently instead of react native so my activity here dropped considerably.

**Comment by ahsanbhatti98** [comment]
Can you also add me in slack channel plz ahsanbhatti98@gmail.com

**Comment by evoactivity** [comment]
@freeboub I've sent you a DM on the slack with a link to checkout the discord, if you're happy with it we can update the readme with a discord link and open it to the community.

**Comment by evoactivity** [comment]
@freeboub Are you still interested in having a discord? I set it up last month, just want your approval to begin sharing it.
