### ISSUE TITLE
show custom controls in fullscreen in ios

### ISSUE THREAD

**Issue by RutvinBhanderi** [TheWidlarzGroup/react-native-video#2886]
when is do fullscreen in ios it shows native controls always how can i  show my custom controls in ios?

**Comment by evoactivity** [comment]
This is documented here https://github.com/react-native-video/react-native-video/blob/master/API.md#controls

> **Note on iOS, controls are always shown when in fullscreen mode.** Note on Android, native controls are available by default. If needed, you can also add your controls or use a package like [react-native-video-controls](https://github.com/itsnubix/react-native-video-controls) or [react-native-media-console](https://github.com/criszz77/react-native-media-console), see [Usefull Side Project](https://github.com/react-native-video/react-native-video/blob/master/docs/PROJECTS.md).

**Comment by RutvinBhanderi** [comment]
but if I add my custom control and then I do full screen also it is showing native controls. is there any way to disable controls. I tried controls set to false but it is not working when video is in full screen.

**Comment by evoactivity** [comment]
You will need to implement you own fullscreen mechanisms if you want to use a custom UI. Do not use the fullscreen methods of this library as this will always present a native fullscreen.

Wrap your ui and video with a view, update state to add a fullscreen style to the wrapper, something like
```jsx
fullscreen: {
  position: absolute,
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 1000,
}
```
You can use libraries like [Home Indicator](https://github.com/flowkey/react-native-home-indicator) and [Fullscreen](https://github.com/chzappsinc/react-native-fullscreen-chz) and the react native [StatusBar](https://reactnative.dev/docs/statusbar) module to enable/disable status bars etc

**Comment by RutvinBhanderi** [comment]
thank you so much
