### ISSUE TITLE
Feature: playing audio over earpiece

### ISSUE THREAD

**Issue by liviu-padurariu** [TheWidlarzGroup/react-native-video#2887]
# Feature Request

playing audio over earpiece

## Why it is needed

to be able to play video and audio while keeping a quiet atmosphere.

## Possible implementation

The `Video` component will receive a new prop `audioOutput: PropTypes.oneOf(['speaker', 'earpiece'])` and based on that one can update the audio output on the native side.

### Code sample

`<Video ... audioOutput={'earpiece'} />`

**Comment by freeboub** [comment]
This feature has been merged in 6.0.0-alpha.8 (with regression :/ )

**Comment by opensourcekam** [comment]
What is the state of this change? I noticed the prop is here in [props.md](https://github.com/react-native-video/react-native-video/blob/master/docs/pages/component/props.md#audioOutput) but this still is not configurable in the Video component. Could you share what is happening in the regression?
