### ISSUE TITLE
Custom control issue

### ISSUE THREAD

**Issue by praveen97rss** [TheWidlarzGroup/react-native-video#2889]
# Bug

1.  I face issue when I given controls {true} to iOS platform.
2. Issue is : Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value.

## Platform
iOS
Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info
Library name  "react-native-video"

React native info output:

```bash
 // paste it here
```

Library version: ^6.0.0-alpha.3

## Steps To Reproduce

1. I set {controls} to true I got this issue on iOS platform.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
not enough information to investigate
