### ISSUE TITLE
On IOS the subtitles work perfectly in the emulator, but when I test on a physical iphone it doesn't work

### ISSUE THREAD

**Issue by drdosan** [TheWidlarzGroup/react-native-video#2894]
In my application, I am using player normally, and the subtitles are hosted in an AWS s3 bucket, when I build it in the emulator it works perfectly, but when I send it to the flight test, the subtitles do not load and the subtitles do not load either.

Videos are .mp4 and subtitles are .vtt

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Please provide full reproduction steps and data. and clean ticket description
