### ISSUE TITLE
pictureInPicture={false} is not working

### ISSUE THREAD

**Issue by codebin-pune** [TheWidlarzGroup/react-native-video#2895]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by uguraktas** [comment]
I uncheck `Audio, AirPlayer and picture in picture` option from `Background Modes` on Xcode then pip mode button removed on player. 

I'm having trouble understanding if these props don't work why do you add it to the module and write it in the documentation???
