### ISSUE TITLE
RCTVideo initialized twice?

### ISSUE THREAD

**Issue by qingfeng** [TheWidlarzGroup/react-native-video#29]
I added a log:

``` objc
- (UIView *)view
{
  NSLog(@"RCTVideo init RCTVideo init");
  return [[RCTVideo alloc] initWithEventDispatcher:self.bridge.eventDispatcher];
}
```

result:

```
2015-05-06 02:50:18.218 gouhuo-native[67470:4294635] RCTVideo init RCTVideo init
2015-05-06 02:50:18.218 gouhuo-native[67470:4294635] RCTVideo init RCTVideo init
```

This is probably what is the problem? thanks

**Comment by brentvatne** [comment]
Hi @qingfeng - if you add a breakpoint in there and inspect the stack you will see that one of them is being created for purposes internal to React Native, in fact this happens with all components :smile:

**Comment by qingfeng** [comment]
Really it is. . .
Is react-native problem, but, react-native can load ViewController only one more time?
Because, I encountered a problem, such as a microphone loaded twice if there is a problem

**Comment by brentvatne** [comment]
Check out `createView` on UIManager: https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m

Specifically:
https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L801
and
https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L809

:smile:

**Comment by qingfeng** [comment]
thanks! :beer:

**Comment by brentvatne** [comment]
:smile_cat: no problem @qingfeng
