### ISSUE TITLE
Rate does not work on Android

### ISSUE THREAD

**Issue by jingpeng** [TheWidlarzGroup/react-native-video#290]
Hi, I've tested the rate param that it works on iOS but not working on Android. I've found that Huawei P9 and Google Nexus 5 does not support rate, can you help me check this?

**Comment by ducchungtx** [comment]
same issue. i try with another plugin (react-native-media-kit) but it's not load video.

**Comment by djw27** [comment]
Using `rate` in conjunction with `paused` solved this for me. i.e. `{ rate: 1, paused: false }`

**Comment by alessandro-bottamedi** [comment]
You can use only `{ paused: true }` to pause the video instead of `{ rate: 0 }` works both on android and iOS

**Comment by bharath-kamath** [comment]
`rate 1` works by default, but any other rate like 0.5 is not working `{ rate: 0.5, paused: false }`

Has anybody found any solution to this?

**Comment by fabdrol** [comment]
I'm experiencing this issue as well - but it only happens when I _change the rate_; i.e. if I set rate to `.2` at mount time the rate works fine; if I then change it using `setState` nothing happens.

**Comment by IvanPaulBOB** [comment]
Hi Team. I also experience the same behavior as @fabdrol . Any updates or workarounds?
