### ISSUE TITLE
Expo support with react-native-video

### ISSUE THREAD

**Issue by joec05** [TheWidlarzGroup/react-native-video#2900]
I am interested in react-native-video and as I am currently developing with Expo I was just wondering if this component is usable in Expo.

**Comment by freeboub** [comment]
I don't think so, but you can try ...
Please, let me know what issue you found, I think it would be good to add expo support.
(notice that there is expo-av, but I didn't see regular exoplayer player updates in this project)

**Comment by jeremyspritelyco** [comment]
I am using expo 46 with react native video, no issues at all.
I recommend using react-native-video ver 6 so you have exoplayer player by default without any configurations, same as expo-av
the reason I don't use expo-av is it does not support subtitles yet, react-native-video does.

**Comment by astelmack** [comment]
> I am using expo 46 with react native video, no issues at all. I recommend using react-native-video ver 6 so you have exoplayer player by default without any configurations, same as expo-av the reason I don't use expo-av is it does not support subtitles yet, react-native-video does.

@jeremyspritelyco 
Would you be able to share any details on install of react-native-video in expo?  I am going to be experimenting with it and would be good to know what things to watch out for and the steps required to follow specifically in the expo case.

**Comment by foloinfo** [comment]
It works fine on Expo SDK 47.
Just added `"react-native-video": "^6.0.0-alpha.4"` using ` yarn add react-native-video@alpha `.
You need to [create EAS build](https://docs.expo.dev/development/create-development-builds/), follow the instruction down there. No need for config plugin. It just works.

**Comment by stuckj** [comment]
Same on expo 48. Working for us as well. The 5.2.0 version works as well, but doesn't use exoplayer. We had to use the 6.0.0 alpha to get exoplayer.

**Comment by llwire** [comment]
It seems to well on Expo 48, but has anyone verified if caching is working as expected?

**Comment by waeldeeb** [comment]
react-native-video 5.2.1 doesn't work with me on react native expo. I tried Expo 48 even same problem. I receive error:

> Uncaught Error: Your web project is importing a module from 'react-native' instead of 'react-native-web'.

Any ideas?

**Comment by WinterSunset95** [comment]
react-native-video 6.1.2 doesn't work for me on Expo 51.
```
requiredNativeComponent: "RCTView" was not found in the UIManager.
```

**Comment by freeboub** [comment]
I try to replicate the issue, I think you should use "npx expo run:android" in order to ensure the native code is build once.

**Comment by freeboub** [comment]
I open a Pull request to move the sample to expo: https://github.com/TheWidlarzGroup/react-native-video/pull/3880
I think it will close this discussion

**Comment by HustCoderHu** [comment]
> react-native-video 6.1.2 doesn't work for me on Expo 51.
> 
> ```
> requiredNativeComponent: "RCTView" was not found in the UIManager.
> ```

similar problem, expo 51.0.11,  react-native-video 6.2.0
```sh
ERROR  Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.
```

**Comment by freeboub** [comment]
@HustCoderHu did you try `npx expo run:android` ?

**Comment by Judge-Paul** [comment]
> > react-native-video 6.1.2 doesn't work for me on Expo 51.
> > ```
> > requiredNativeComponent: "RCTView" was not found in the UIManager.
> > ```
> 
> similar problem, expo 51.0.11, react-native-video 6.2.0
> 
> ```shell
> ERROR  Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.
> ```

Same problem Expo 51.0.17, react-native-video 6.3.0
``` bash
invariant violation: requirenativecomponent: "rctvideo" was not found in the uimanager.
```
but it works when i run a development build with `npx expo run:android`
