### ISSUE TITLE
Conflict with React Native Track Player Library

### ISSUE THREAD

**Issue by codasana** [TheWidlarzGroup/react-native-video#2903]
**Describe the Bug**
In my project, I need to use both react-native-track-player and react-native-video. The problem is that when the latest track-player version is installed and react-native-video is already installed, the app crashes on android. It works well on iOS. But on android, it crashes, as soon as we open the app.

**Steps To Reproduce**
If both libraries are installed, the app crashes on android. I've verified it by uninstalling either library and the app works fine. If rntp is installed without react-native-video, the app compiles and runs properly. If react-native-video is installed without rntp, the app compiles and runs smoothly. But if both are installed, then app runs smoothly on iOS but on Android, it compiles but crashes on open.

I've seen earlier threads that talk about conflict in exoplayer versions, but that shouldn't be the case now as I'm using rntp v 3.2.0 which does not have exoplayer dependency.

**Environment Info:**
"react-native-track-player": "^3.2.0"
"react-native-video": "^5.2.1",

Crash on Real Android Device. I tried on both android 11 and android 12.

It crashes without any warnings or error messages.

**Use of exoplayer**

In my project to use exoplayer for react-native-video, I have the following code:

```
  dependencies: {
    "react-native-video": {
      platforms: {
        android: {
          sourceDir: "../node_modules/react-native-video/android-exoplayer",
        },
      },
    },
  },
```
This setup works fine when rntp is not installed. But when I install rntp, the app crashes on android.
If I install rntp, but comment/remove this exoplayer dependency from this file, the app doesn't crash, rntp works fine, react-native-video also works but without exoplayer.

I hope someone can help me resolve this so that I can use both and still use exoplayer version with react-native-video.

**Comment by yanhongchang-1105** [comment]
I face same too.How do you do?

**Comment by codasana** [comment]
You can use react-native-video version 6.0.0-alpha.3. It resolves the issue.
