### ISSUE TITLE
Failed to compile 5.2.0 for Android due missing dependency in maven. 5.2.1 compiles

### ISSUE THREAD

**Issue by daogurtsov** [TheWidlarzGroup/react-native-video#2904]
## Platform

Which player are you experiencing the problem on:
* Android

React native info output:

Library version: 5.2.0

## Steps To Reproduce
1. Compile android debug or release

## Expected behaviour
1. Apk or aab should be created

The issue: starting 31 Oct, can't compile android due some transitive dependency is missing in gradle maven repo.

Was able to compile after updated react-native-video to 5.2.1

**Comment by freeboub** [comment]
Thank you to open an already fixed ticket :) 5.2.1 was created to include this change
