### ISSUE TITLE
Android video content zoomed in

### ISSUE THREAD

**Issue by AbdallaEmadEldinAbdalla** [TheWidlarzGroup/react-native-video#2909]
# Bug

The video is zoomed on android devices.

## Platform
Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/xefi/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

just add video component with url

## Expected behaviour
show video like ios with correct ratio

## Video sample
![Screenshot_1667391622](https://user-images.githubusercontent.com/116554738/199488169-35ad0973-1879-4aec-845b-e6223e238526.png)
![Simulator Screen Shot - iPhone 13 - 2022-11-02 at 16 20 07](https://user-images.githubusercontent.com/116554738/199488205-e02fcdea-0f56-475a-8f1b-c541a277285a.png)

**Comment by felipegmg** [comment]
same issue here

**Comment by awHamer** [comment]
Same issue here, has anyone found a fix?
iOS works just fine, but android suddenly zooms in after the first loop...

Just noticed that it happens with HLS (.m3u8)
**.mp4 works fine.**
