### ISSUE TITLE
Still loading fmp4 video chunks when video track is disabled

### ISSUE THREAD

**Issue by Jadeon-FPM** [TheWidlarzGroup/react-native-video#2918]
# Bug
Our app uses this package for video playback, and I'm prepping an update that allows users to switch to audio-only. It's using an fmp4 video source with separate chunks for the video and audio tracks. When set to audio-only the player is passed `selectedVideoTrack={{ type: 'disabled' }}` as a prop.

The video stops displaying while the audio continues as expected, but in Android Studio's Network Inspector I can see it's still loading the chunks for both audio and video.

Below is a screenshot of the network inspector while playing the video in linked later in this issue. The video chunk requests for this particular video are all 5.6MB and all audio chunks 118KB.

![image](https://user-images.githubusercontent.com/44822784/200967730-4be7491b-e569-4004-a23f-ac6d8b46b13e.png)

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 19.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1 and 6.0.0-alpha.3
Explicitly using ExoPlayer on 5.2.1, Exo is used by default on 6.0.0.

## Steps To Reproduce
1. Play a video with an fmp4 source ([such as this](https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8))
2. Pass the prop `selectedVideoTrack={{ type: 'disabled' }}`

## Expected behaviour
The player should not load video chunks.

## Video sample
```
<Video
    source={{ uri: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8' }}
    selectedVideoTrack={{ type: 'disabled' }}
/>
```

**Comment by Jadeon-FPM** [comment]
This is also the case if I set `audioOnly` and a poster.

**Comment by Jadeon-FPM** [comment]
After further investigation this appears to be an ExoPlayer issue.

**Comment by GunnarMM** [comment]
@Jadeon-FPM do you remember how you fixed the issue?

**Comment by Jadeon-FPM** [comment]
@GunnarMM I didn't. It's an issue with ExoPlayer, where it will continue to load the video chunks even when the video track is disabled. This is only with HLS streams though. It seems to work just fine with DASH streams.

**Comment by GunnarMM** [comment]
Thanks for responding so quickly and for sharing your knowledge! Much appreciated.
