### ISSUE TITLE
Unable to instantiate decoder OMX.hisi.video.decoder.avc

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [TheWidlarzGroup/react-native-video#2920]
# Bug
Unable to instantiate decoder OMX.hisi.video.decoder.avc

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz
    Memory: 6.03 GB / 15.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: 17.2.32630.192 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.12 - C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.2 => 0.65.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1.Unable to instantiate decoder OMX.hisi.video.decoder.avc
2.Unable to instantiate decoder OMX.hisi.video.decoder.avc
...

## Expected behaviour

1.Unable to instantiate decoder OMX.hisi.video.decoder.avc
2.errorException: "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.420029, -1, null, [1920, 1080, 29.601254], [-1, -1]), format_supported=YES"

## Reproducible sample code
errorException: "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.420029, -1, null, [1920, 1080, 29.601254], [-1, -1]), format_supported=YES"

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Should be tested on an exoplayer sample... No sample url provided, this is not something which can be investigated

**Comment by AhmadAl-Ghalban** [comment]
> Should be tested on an exoplayer sample... No sample url provided, this is not something which can be investigated
sample url provided Take Video Sample get for Api aws

**Comment by Vantam1601** [comment]
Any solutions?
