### ISSUE TITLE
How can i show thumbnail preview when forwarding the Video using timeline bar in react native?

### ISSUE THREAD

**Issue by jaferi512** [TheWidlarzGroup/react-native-video#2924]
I'm working on a project and It needs the exact same implementation as a youtube iframe video component for common mp4 videos. I want to ask if that is this possible to create a forward preview along with a progress bar using the react-native-video Library.
I'm using Below Environment:
React Native: "0.70.3"
React = "18.1.0"
I've not seen such a type of implementation using this Library. If there is any way to do such type of work, Please share otherwise I'll request to community to Please add such type of feature to this library.
I've attached a Sample Of the Required Feature. You can check.
Thanks In advance.
<img width="555" alt="z47Bg" src="https://user-images.githubusercontent.com/57745133/202368166-103dbb56-147d-4ab4-a120-a0dcdbc7fea0.png">

**Comment by freeboub** [comment]
Unfortunately this feature is not yet available.

**Comment by vargajacint** [comment]
I did it the following way. 
1. I get the [storyboard](https://docs.mux.com/_next/image?url=%2Fimages%2Fstoryboard.png&w=3840&q=75) from remote and their metadata*! 
2. I chop the storyboard, based on the metadata using `@react-native-community/image-editor`
3. After this when the user is seeking to `x` second, just simple display the closest image to `x`.


I did something like this:
```
  useEffect(() => {
      (async () => {
        try {
          const resp = await fetch(storyboardURL);
          const storyboard = (await resp.json()) as Storyboard;

          if (storyboard && Array.isArray(storyboard.tiles)) {
            const croppedImages: Array<PreviewImage> = [];

            storyboard.tiles.forEach(async (story) => {
              ImageEditor.cropImage(storyboard.url, {
                offset: { x: story.x, y: story.y },
                size: { width: storyboard.tile_width, height: storyboard.tile_height },
                displaySize: { width: 150, height: 75 }
              }).then((url) => croppedImages.push({ url, start: story.start }));
            });

            setImages(croppedImages);
          }
        } catch (error) {}
      })();
  }, []);
```

```
const getClosestPreviewURL = (images: PreviewImage[], val: number): string => {
    return images.reduce((prev, curr) => (Math.abs(curr?.start - val) < Math.abs(prev?.start - val) ? curr : prev), {
        start: 0,
        url: ""
    })?.url
}
```

*resources: https://docs.mux.com/guides/video/create-timeline-hover-previews#add-timeline-hover-previews-to-your-player

Of course this is not the best solution, but unfortunately `react-native-video` does not support WebVTT

**Comment by jaferi512** [comment]
Thanks, @vargajacint.
I'll try this way if possible.

**Comment by vargajacint** [comment]
@freeboub I think you can close this
