### ISSUE TITLE
live video working fine in simulator but not working in ios device.

### ISSUE THREAD

**Issue by RutvinBhanderi** [TheWidlarzGroup/react-native-video#2925]
Playing m3u8 live video
Showing error like this,

{"error": {"code": -11821, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Decode", "localizedFailureReason": "The media data could not be decoded. It may be damaged.", "localizedRecoverySuggestion": ""}, "target": 623}

**Comment by freeboub** [comment]
No url provided.. cannot be investigated

**Comment by Yasir12598** [comment]
Some how the same issue here in android, video plays properly in debug mode, while video does not play in .apk release.

url: http://niaip.xyz:24621/1ievztiwvx82582vf58whxt/uwNad6UpDK/320439

**Comment by alexbudin** [comment]
You are using HTTP. have a look around...there are some settings you need to do in case you use HTTP, but you should switch to HTTPS. Have a search on this github page, you will find some more info. I remember i saw some stuff on this subject some time ago.

Also make sure you specify the type of the video to be m3u8, without it, your video will not work.

like so:

source={{
              uri: videoUrl,
              type: 'm3u8',
            }}


Be aware that on iOS 16.4 video is not showing anymore, just the audio is playing There are already open issues on the matter.

Hope this helps.
