### ISSUE TITLE
Is there any way to mix music to my recorded video like instagram reels

### ISSUE THREAD

**Issue by iasreact1** [TheWidlarzGroup/react-native-video#2928]
I have a query that is there any way to mix music to my recorded video and can play the video with that added music like instagram reels ...if yes ..please help me to get it

**Comment by freeboub** [comment]
I think the only way to do this is to use 2 video views

**Comment by iasreact1** [comment]
@freeboub  Sir can u explain in details...

**Comment by freeboub** [comment]
I mean you there is no built feature for mixing audio and video in 1 <video view. 
But you can use 2 <Video view, 1 playing video, 1 playing audio
