### ISSUE TITLE
Support new architecture

### ISSUE THREAD

**Issue by phalera** [TheWidlarzGroup/react-native-video#2929]
# Bug
The plugin doesn't support new architecture

## Platform
* iOS
* Android

## Environment info

React native info output:
Unimplemented component: <Video>

Library version: 6.0.0.alpha.3

## Steps To Reproduce

1.RCT_NEW_ARCH_ENABLED=1 pod install
2.npm start
...

## Expected behaviour

1. run ok

## Video sample

![Simulator Screen Shot - iPhone 11 - 2022-11-24 at 22 00 31](https://user-images.githubusercontent.com/16587763/203802786-3fcb5134-1d82-4322-832a-70d53358e77a.png)

**Comment by freeboub** [comment]
To be followed in https://github.com/react-native-video/react-native-video/issues/2650

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0
