### ISSUE TITLE
Dynamic HLS playlist created in Backend not working

### ISSUE THREAD

**Issue by lonasozo** [TheWidlarzGroup/react-native-video#2930]
# Bug
Basically I'm dynamic creating the master playlist with my backend, playlist looks like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=688000,RESOLUTION=640x360
https://url/to/file1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1400000,RESOLUTION=842x480
https://url/to/file2.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2800000,RESOLUTION=1280x720
https://url/to/file3.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5000000,RESOLUTION=1920x1080
https://url/to/file4.m3u8

```
Url passed to the player is like: https://link-to-api/1234
(without the m3u8 extension)
I'm using PHP as backend, I'm returning as content-type `application/x-mpegURL` (it works fine on a web player)

## Platform
Mobile

Which player are you experiencing the problem on:
* iOS
* Android

## Environment info
React native info output:

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 693.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found
```

Library version: 5.2.0"

## Steps To Reproduce
1. Dynamic generate master HLS playlist
2. Set link of the API call that create HLS playlist on the player (https://link-to-api/1234

## Expected behaviour
1. Video should start normally

Printed out the error
`{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}`

**Comment by freeboub** [comment]
Please have a look to this page https://github.com/react-native-video/react-native-video/blob/master/docs/DEBUGGING.md

**Comment by lonasozo** [comment]
Thank you, checked.
From my point of view, this issue should not be closed. 

- File exist and is accessible 
- The "direct" file (so the same playlist but took directly as an index.m3u8) is working on the app
- Contents are not protected
- Same endpoint is working fine with others video players

Does not have problems with release/debug mode, I can play hls if I pass the file, if I get the file from an API call, though the content type returned is correct, player seems does not recognize it.

Any other suggestion?
