### ISSUE TITLE
Add support for Bluetooth playback controls

### ISSUE THREAD

**Issue by mitchdowney** [TheWidlarzGroup/react-native-video#2932]
# Feature Request

Add Bluetooth controls for video playback.

## Why it is needed

It would be a nice UX to be able to at least play and pause using Bluetooth controls while watching videos.

## Possible implementation

I'm not sure how to elaborate on this. react-native-video will need to connect to the native APIs for bluetooth playback controls.

**Comment by freeboub** [comment]
I confirm both features make sense.
For Bluetooth following PR is a good start point : https://github.com/react-native-video/react-native-video/pull/2888

For lock screen I have this feature enable in my company fork. I can backport is on master.

Anyway, can you split this ticket as this is 2 ok independent features.
Thank you

**Comment by mitchdowney** [comment]
@freeboub awesome. I just created #2938 for the Lock screen request. Thank you for the excellent library!

**Comment by mitchdowney** [comment]
I ended up using the react-native-track-player remote event listeners to handle Bluetooth playback controls. Seems to work without issues.

**Comment by KrzysztofMoch** [comment]
This should work on latest v6 with `showNotificationControls`, so I will close this - if this will not work for you, please ping me

**Comment by mitchdowney** [comment]
@KrzysztofMoch wonderful. Thank you!
