### ISSUE TITLE
video plays in debug mode, while doesn't play in apk release

### ISSUE THREAD

**Issue by Yasir12598** [TheWidlarzGroup/react-native-video#2936]
# Bug

Platform:
* Android

## Environment info

Package.json:

```bash
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-video": "^5.2.1"
```

## Steps To Reproduce

```
<Video
        source={{ uri: 'http://niaip.xyz:24621/1ievztiwvx82582vf58whxt/uwNad6UpDK/320439'}}
        resizeMode={'contain'}
        style={{ flex: 1 }}
        volume={1}
        onError={(err) => {
          console.log('on error .........<><><> ', err)
        }}
        onBuffer={(data) => {
          console.log('On Buffering111111:--------->   ', data)
        }}
      />
```

video plays in debug mode, while doesn't play in apk release. The problem arise only with this type of uris [ http://niaip.xyz:24621/1ievztiwvx82582vf58whxt/uwNad6UpDK/320439]('http://niaip.xyz:24621/1ievztiwvx82582vf58whxt/uwNad6UpDK/320439'). while I have testes m3u8 works perfectly.

**Comment by freeboub** [comment]
Can you detail the reported ?
Maybe logcat can also helps

**Comment by lonasozo** [comment]
I think this has something similar to my issue https://github.com/react-native-video/react-native-video/issues/2930
I can't play an m3u8 took from an API call like **https://call-api/value**, only by pass to the player directly the file like **https://link/to/file.m3u8**.


I've seen you are using http, @freeboub suggested me to check this: https://github.com/react-native-video/react-native-video/blob/master/docs/DEBUGGING.md#http-playback-doesnt-work-or--black-screen-on-release-build-android

Maybe you can be more lucky.

**Comment by Yasir12598** [comment]
@lonasozo Thanks, It works.

**Comment by freeboub** [comment]
So let s close this issue, thank you!

**Comment by PrudhviBanki** [comment]
why this issue closed android:usesCleartextTraffic="true" not working debug working release getting black screen still

**Comment by zeeshanAvancera** [comment]
same issue bro @PrudhviBanki
