### ISSUE TITLE
Can't finish pod install and can't run my App TvOs Player

### ISSUE THREAD

**Issue by FidyAndria73** [TheWidlarzGroup/react-native-video#2937]
# Bug

## Platform

Which player are you experiencing the problem on:

* tvOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 93.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 2022.10.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mbp/.rvm/rubies/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.68.1-1 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: https://github.com/avencat/react-native-video.git

## Steps To Reproduce

1. I make multiple plate form in my project iOS and tvOS and I want to add Ads in my application

2.When I make pod install I have this error : 
[!] The platform of the target `TestApp-tvOS` (tvOS 12.4) is not compatible with `GoogleAds-IMA-iOS-SDK (3.18.1)`, which does not support `tvOS`.

3.This is my pod file:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :deterministic_uuids => false

target 'TestApp' do

  platform :ios, '12.4'

  config = use_native_modules!
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  use_flipper!({ 'Flipper' => '0.151.0' })
  target 'TestAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'TestApp-tvOS' do

  platform :tvos, '12.4'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes not yet available on tvOS
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # An abosolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )

  target 'TestApp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end

...

**Comment by freeboub** [comment]
Ping @avencat

**Comment by avencat** [comment]
Nice feedback thank you! I never used react native for a tvOS project but I will check that out as soon as I can! 🙂

**Comment by avencat** [comment]
Hi @FidyAndria73 can you please test with the last version on master of https://github.com/avencat/react-native-video.git ? I didn't add tvOS support but with my last commit that should be fixed (it seems that tvOS and iOS IMA SDK share the same API and imports but come from two different dependencies)

**Comment by freeboub** [comment]
as this is done and merged, I close this ticket. let's see on master branch (will be available in alpha.5)
