### ISSUE TITLE
Android blank screen

### ISSUE THREAD

**Issue by Brittognanaraj** [TheWidlarzGroup/react-native-video#2940]
Video plays in Android but showing blank screen, i am able to hear audio. 
In both media player and exo player , I am getting the same issue.

**Comment by freeboub** [comment]
Can you test on master ? And give reproduction steps and / or a sample

**Comment by gizomo** [comment]
I faced the same problem on v6-alpha3 (tested on tv box with android 7.1.2 on board)

Everything is fine with mp4. But urls with m3u8 playing with black screen and audio. Playing some m3u8 starts with showing first frame for a second and then changes to black screen.

Changing "hardwareAccelerated" and "usesCleartextTraffic" in AndroidManifest.xml had no effect.

RNV 5.2.1 also plays mp4 . But I have a success at this version with some m3u8. The m3u8 videos with black screen at v6 are played by 5.2.1 with green screen and graphic artifacts and I hear sound. The ones that start with first frame at v6 are played by 5.2.1 perfectly well.
I also noticed for 5.2.1 if we start playing with "good" m3u8 and then will change source to "bad" m3u8 than the latter will be played also perfectly well.

**Comment by freeboub** [comment]
can you please provide more informations: 
- Provide a sample stream or a sample application to reproduce the issue ?
- clarify if this is a real revice or an emulator issue ?
- double check logcat output to see if something strange is displayed
Thank you

**Comment by Brittognanaraj** [comment]
This one can reproduce in real device and emulators also

**Comment by gizomo** [comment]
> 

Sorry, I can't provide sample stream or an application and logcat output now.
I tested application at real device (HYBROAD tv box with AndroidTV 7.1.2 on board)

**Comment by alexbudin** [comment]
On iOS 16.4 seems to be the same issues since the iOS update:
see here:
https://github.com/react-native-video/react-native-video/issues/3107

**Comment by freeboub** [comment]
stale issue, let's close, no sample and no clue to understand the issue
