### ISSUE TITLE
 No videoTracks values when playing hls format in the onLoad event IOS (works on android)

### ISSUE THREAD

**Issue by AhmedTouti** [TheWidlarzGroup/react-native-video#2941]
# Bug

IM NOT GITTING THE VALUES OF THE "HLS"  videoTracks  in the onLoad event IOS ,  but  it work fine  on android ,
first i was note getting those values in android,so  i searched for a solution and i found and added this :
 - module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
inside of (react-native.config.js) then the iwas able to get the videotraks values ,
My problem is to get those values in onLoad event  ios to be able to do dynamic video quality  resolution change player 

please to help.
 
## Platform
IOS 

Library version: 5.2.1

## Current  behaviour

{"audioTracks": [{"index": 0, "language": "", "title": ""}], "canPlayFastForward": false, "canPlayReverse": false, "canPlaySlowForward": true, "canPlaySlowReverse": false, "canStepBackward": false, "canStepForward": false, "currentTime": 0, "duration": 30.200000762939453, "naturalSize": {"height": 240, "orientation": "landscape", "width": 426.6666564941406}, "target": 13, "textTracks": [{"index": 0, "language": "", "title": ""}]}

## Expected behaviour

{"audioTracks": [{"bitrate": "", "index": 0, "language": "en", "title": "1/15", "type": "audio/mp4a-latm"}], "canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0.056, "duration": 30.2, "naturalSize": {"height": 360, "orientation": "landscape", "width": 640}, "textTracks": [{"index": 0, "language": "", "title": "1/8219", "type": "application/cea-608"}], "trackId": "1", "videoTracks": [{"bitrate": 275000, "codecs": "avc1.42001e", "height": 240, "trackId": "0", "width": 426}, {"bitrate": 880000, "codecs": "avc1.42001e", "height": 360, "trackId": "1", "width": 640}, {"bitrate": 1540000, "codecs": "avc1.42001e", "height": 480, "trackId": "2", "width": 854}, {"bitrate": 2860000, "codecs": "avc1.4d001f", "height": 720, "trackId": "3", "width": 1280}]}

## Reproducible sample code

 <Video
            source={{
              uri: 'https://cdn.api.video/vod/vi5E9z4IKFaBve9WpzHmyVlc/hls/manifest.m3u8',
            }}
            //selectedVideoTrack={res}
            style={styles.VideoPlayer}
            controles={true}
            onError={(err)=>{console.log('err : ' ,err  );}}
            resizeMode="cover"
            onLoad={payload => {
             console.log('PAYLOAD : ', payload);
            // setResols(payload?.videoTracks)
            }}
          /> 

## Video sample
'https://cdn.api.video/vod/vi5E9z4IKFaBve9WpzHmyVlc/hls/manifest.m3u8'

**Comment by LadyBo** [comment]
Hi, everyone) We experience the same problem at our project and cannot implement CC support on iOS devices due to this bug. Is there anything we can do or provide to help fixing this bug?

**Comment by roo12312** [comment]
same here any solution?

**Comment by freeboub** [comment]
Use m3u format...
It is the preferred format for ios.
I am not even sure other players than AVplayer support mdp on ios... I think it due to fairplay restriction

**Comment by roo12312** [comment]
> Use m3u format...
> It is the preferred format for ios.
> I am not even sure other players than AVplayer support mdp on ios... I think it due to fairplay restriction

you mean m3u8?

**Comment by altaywtf** [comment]
I'm not sure what I'm doing wrong but it's the same for android for `react-native-video@6.0.0-alpha.6` for some streams 🤔 

```json
{"type": "m3u8", "uri": "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"}
```

gives me 

```json
{
   "audioTracks":[
      {
         "bitrate":0,
         "index":0,
         "language":"en",
         "selected":true,
         "title":"1/15",
         "type":"audio/mp4a-latm"
      }
   ],
   "canPlayFastForward":true,
   "canPlayReverse":true,
   "canPlaySlowForward":true,
   "canPlaySlowReverse":true,
   "canStepBackward":true,
   "canStepForward":true,
   "currentTime":0,
   "duration":5365,
   "naturalSize":{
      "height":720,
      "orientation":"landscape",
      "width":1280
   },
   "textTracks":[
      {
         "index":0,
         "language":"",
         "selected":false,
         "title":"1/8219",
         "type":"application/cea-608"
      }
   ],
   "trackId":"7",
   "videoTracks":[
      
   ]
}
```

while

```json
{"type": "m3u8", "uri": "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"}
```

has this

```json
{
   "audioTracks":[
      {
         "bitrate":0,
         "index":0,
         "language":"en",
         "selected":true,
         "title":"stereo:English",
         "type":"audio/mp4a-latm"
      },
      {
         "bitrate":0,
         "index":1,
         "language":"dubbing",
         "selected":false,
         "title":"stereo:Dubbing",
         "type":"audio/mp4a-latm"
      }
   ],
   "canPlayFastForward":true,
   "canPlayReverse":true,
   "canPlaySlowForward":true,
   "canPlaySlowReverse":true,
   "canStepBackward":true,
   "canStepForward":true,
   "currentTime":0,
   "duration":888,
   "naturalSize":{
      "height":818,
      "orientation":"landscape",
      "width":1920
   },
   "textTracks":[
      {
         "index":0,
         "language":"de",
         "selected":false,
         "title":"subs:Deutsch",
         "type":"text/vtt"
      },
      {
         "index":1,
         "language":"en",
         "selected":true,
         "title":"subs:English",
         "type":"text/vtt"
      },
      {
         "index":2,
         "language":"es",
         "selected":false,
         "title":"subs:Espanol",
         "type":"text/vtt"
      },
      {
         "index":3,
         "language":"fr",
         "selected":false,
         "title":"subs:Français",
         "type":"text/vtt"
      }
   ],
   "trackId":"6",
   "videoTracks":[
      {
         "bitrate":258157,
         "codecs":"avc1.4d400d",
         "height":180,
         "selected":false,
         "trackId":-1,
         "width":422
      },
      {
         "bitrate":520929,
         "codecs":"avc1.4d4015",
         "height":272,
         "selected":false,
         "trackId":-1,
         "width":638
      },
      {
         "bitrate":831270,
         "codecs":"avc1.4d4015",
         "height":272,
         "selected":false,
         "trackId":-1,
         "width":638
      },
      {
         "bitrate":1144430,
         "codecs":"avc1.4d401f",
         "height":408,
         "selected":false,
         "trackId":-1,
         "width":958
      },
      {
         "bitrate":1558322,
         "codecs":"avc1.4d401f",
         "height":554,
         "selected":false,
         "trackId":-1,
         "width":1277
      },
      {
         "bitrate":4149264,
         "codecs":"avc1.4d4028",
         "height":818,
         "selected":false,
         "trackId":-1,
         "width":1921
      },
      {
         "bitrate":6214307,
         "codecs":"avc1.4d4028",
         "height":818,
         "selected":false,
         "trackId":-1,
         "width":1921
      },
      {
         "bitrate":10285391,
         "codecs":"avc1.4d4033",
         "height":1744,
         "selected":false,
         "trackId":-1,
         "width":4096
      }
   ]
}
```

I also didn't understand why `selected` is `false` for every `videoTrack` above.

**Comment by sanju280696** [comment]
same issue any update? also, I can't change the video quality. any one have alternative solution please tell me

**Comment by mahmood** [comment]
same problem @sanju280696 

we don't have any options to change video quality based on hls link levels

**Comment by sanju280696** [comment]
but there are many applications they are giving that options @mahmood

**Comment by gulsher7** [comment]
Has anyone encountered the issue where changing the selected video tracks in Android causes the video to shrink.

**Comment by roo12312** [comment]
any solution for this problem?

**Comment by KrzysztofMoch** [comment]
"videoTracks" are not supported on iOS so this is not a bug - also I make (very) fast research and it don't seem simple to implement

**Comment by jigarsolanki0212** [comment]
Also facing the same problem
