### ISSUE TITLE
Is react-native-video support LL-HLS on iOS platfroms?

### ISSUE THREAD

**Issue by zhulduz** [TheWidlarzGroup/react-native-video#2944]
Hi guys!

Just couldn't find any info and questions about it.
I have stream with LL-HLS playlist but it doesn't work on iOS platform at all, checked on iOS 15.

So do anybody can the same issue and explanations?

Thanks in advance)

**Comment by freeboub** [comment]
Did you follow this documentation ?
https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_http_live_streaming_hls
It doesn't seem that patch is needed on application side to support it (so react-native-video should already be compliant)
