### ISSUE TITLE
Unable to build on iOS

### ISSUE THREAD

**Issue by hieunc229** [TheWidlarzGroup/react-native-video#2946]
I'm running into similar issue to https://github.com/react-native-video/react-native-video/issues/2769, where `RCTEventDispatcher` is being used as the `_eventDispatcher`.

Error `Cannot find type "RCTEventDispatcher" in scope`

<img width="718" alt="Screen Shot 2022-12-09 at 12 54 03 pm" src="https://user-images.githubusercontent.com/8464869/206634252-9221f33d-b404-4b10-9734-5ea228afc3a7.png">

Seems like this PR is not applied to the 6.0.0-alpha4

**Resolution**

Changing `RCTEventDispatcher` to `RCTEventDispatcherProtocal` seem to fix the issue!

react-native: 0.70.6
react: 18.1.0
react-native-video: 6.0.0-alpha4 (installed from the current github repository)

**Comment by freeboub** [comment]
Can you guys implied in linked issue to ask some help please ?
 It seems to be an environnement issue :/

**Comment by vargajacint** [comment]
same here

**Comment by oleksii-lyhun** [comment]
same problem

**Comment by KrzysztofMoch** [comment]
With 6.0.0-beta.0 I was not able to reproduce the issue - please let me know if still occurs for you
