### ISSUE TITLE
[iOS] Picture In Picture not start automatically while app is in background

### ISSUE THREAD

**Issue by nikesh8** [TheWidlarzGroup/react-native-video#2952]
# Bug

Picture In Picture does not start automatically while the app is in the background on iOS with the latest code merged in the `master` branch.

## Reproducible sample code

My code block is as follows:
In this code, I have used customized controls instead of the usage of controls provided by native players.
```
<Video
              source={{
                uri: videoStore.videoDetails.uri,
              }}
              style={{ width: widthX, height: heightX }}
              ref={ref => {
                videoStore.setPlayerRef(ref);
              }}
              poster={videoStore.videoDetails.thumbnail}
              posterResizeMode={VideoResizeMode.cover}
              controls={false}
              paused={!videoStore.isPlaying}
              rate={videoStore.playBackRate}
              pictureInPicture={true}
              preventsDisplaySleepDuringVideoPlayback={true}
              playInBackground={true}
              progressUpdateInterval={1000}
              ignoreSilentSwitch={'ignore'}
              resizeMode={videoStore.videoResizeMode}
              muted={videoStore.muted}
              maxBitRate={videoStore.bitRate}
              onLoadStart={this.onVideoLoadStart}
              onLoad={this.onVideoLoad}
              onBuffer={this.onVideoBuffer}
              onError={this.onVideoError}
              onProgress={this.onVideoProgress}
              onExternalPlaybackChange={this.onExternalPlaybackChange}
              onEnd={videoStore.onVideoEnd}
              adTagUrl="https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator="
              onReceiveAdEvent={this.onReceiveAdEvent}
            />
```

Library version: 

```
"react-native-video": "git+https://github.com/react-native-video/react-native-video.git"
```
Version in node_modules: **6.0.0-alpha.4**

## Steps To Reproduce
1. Start video playing 
2. Put the application in background mode
3. Audio playing in background mode but picture-in-picture did not start automatically

## Expected behaviour

1. Start video playing 
2. Put the application in background mode
3. Need to start picture-in-picture automatically if the `pictureInPicture` this flag is set to `true`

Please help me out with this. In the previous version v5.x.x, it works fine. But now it won't work. I have to use this version because it supports ads with the video.

Thanks in Advance

**Comment by vishalhyperspace** [comment]
@nikesh8 I have the same issue. Do you find any solution?

**Comment by freeboub** [comment]
I start investigating this issue.
It seems to be broken since swift rewrite of ios implementation.
First point I spotted: 
#if TARGET_OS_IOS
shall be replaced by
#if os(iOS)

I will open a draft PR if someone wants to investigate deeper.

**Comment by tuananh24a** [comment]
> I start investigating this issue. It seems to be broken since swift rewrite of ios implementation. First point I spotted: #if TARGET_OS_IOS shall be replaced by #if os(iOS)
> 
> I will open a draft PR if someone wants to investigate deeper.

thanks you, it work for me

**Comment by paulrinaldi** [comment]
Should this issue be closed? @nikesh8  @freeboub

**Comment by KrzysztofMoch** [comment]
I will close this since there is no more `#if TARGET_OS_IOS` in codebase (probably fixed in some PR)
