### ISSUE TITLE
[iOS] Getting TextTracks array with null values in onLoad method

### ISSUE THREAD

**Issue by nikesh8** [TheWidlarzGroup/react-native-video#2953]
# Bug

Text tracks array getting `null` values array. Please refer below code snippet.
Sample URL: `https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

Platform: **iOS**

Library version:
```
"react-native-video": "git+https://github.com/react-native-video/react-native-video.git"
```
Version in node_modules: **6.0.0-alpha.4**

```
{
  "audioTracks": [
    {
      "index": 0,
      "language": "en",
      "title": "English"
    },
    {
      "index": 1,
      "language": "dubbing",
      "title": "Dubbing"
    }
  ],
  "canPlayFastForward": false,
  "canPlayReverse": false,
  "canPlaySlowForward": true,
  "canPlaySlowReverse": false,
  "canStepBackward": false,
  "canStepForward": false,
  "currentTime": 0,
  "duration": 888,
  "naturalSize": {
    "height": 180,
    "orientation": "landscape",
    "width": 422.7522888183594
  },
  "target": 9,
  "textTracks": [
    null,
    null,
    null,
    null
  ]
}
```
Please help.

Thanks in advance :)

**Comment by fatoldsun00** [comment]
Hi, same here, on ios i get textTracks: Array [ null ] while on android i get an array of object. Therefore subtitle works well when video loaded but i haven't any sound (on ios)

**Comment by MrAdisson** [comment]
Same here on iOs. 
![image](https://user-images.githubusercontent.com/28817674/209121657-d8f9e1df-3e74-46ed-8921-71fe1953de1f.png)
And as @fatoldsun00 I receive no audio too.

**Comment by duspada** [comment]
+1

**Comment by manueleirea** [comment]
Hi, we had the same problem as @nikesh8 and @MrAdisson, getting a textTracks array with null values using the 6.0.0-alpha.4 version.

### Possible solution

We got it working by modifying the function handleReadyToPlay in the /ios/Video/RCTVideo.swift file, changing the line
```
"textTracks": _textTracks ?? RCTVideoUtils.getTextTrackInfo(_player),
```
to
```
"textTracks": _textTracks ?? RCTVideoUtils.getTextTrackInfo(_player).map({ textTrack in return textTrack.json }),
``` 
Doing so, we turn textTracks from an array of values of type TextTrack to an array of NSDictionary, which is also the type that's already being used for the audioTracks.

**Comment by freeboub** [comment]
I opened A PR which should fix the issue: https://github.com/react-native-video/react-native-video/pull/3019
Can you please check with externally loaded subtitle tracks

**Comment by manueleirea** [comment]
@freeboub We tested the PR with subtitles embeded in the playlist and it's working. However, with externally loaded subtitles it doesn't seem to work, the list of text tracks is empty in the onLoad method, and for some reason the audio tracks too, although the video still plays audio.

**Comment by samuka1010** [comment]
@freeboub Same here. It loads the embeded subtitles, but will not show any externally loaded subtitle.

**Comment by freeboub** [comment]
Do you have some sample I can integrate in sample app ?

**Comment by manueleirea** [comment]
Sure, we tested it with the sample video found [here](https://server15700.contentdm.oclc.org/dmwebservices/index.php?q=dmGetStreamingFile/p15700coll2/15.mp4/byte/json), and it's subtitles, available [here](https://cdmdemo.contentdm.oclc.org/utils/getfile/collection/p15700coll2/id/18/filename/video2.vtt).

**Comment by brycnguyen** [comment]
I'm still having this same issue where onLoad does not respond with any of the externally loaded subtitles

**Comment by freeboub** [comment]
I think this issue can be closed and retested on the next 6.0.0-beta.7.
Let me know if you still have issues in this release !

**Comment by ngima** [comment]
I am still having this issue in latest version  v6.0.0-beta.8 in iOS 

``` javascript
<Video
    source={source}
    onLoad={onLoad}
    ignoreSilentSwitch={'ignore'}
    controls={true}
    style={styles.backgroundVideo}
    textTracks={[
        {
            title: "English CC",
            language: "en",
            type: TextTrackType.VTT, // "text/vtt"
            uri: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"
        }
    ]}
    selectedTextTrack={{
        type: SelectedTrackType.TITLE,
        value: "English CC"
    }}
/>
```


```
//onLoad log
{
  "textTracks": [],
  "canStepForward": true,
  "canPlayFastForward": true,
  "canPlaySlowReverse": true,
  "audioTracks": [],
  "currentTime": 0,
  "canPlayReverse": true,
  "duration": 417.1199951171875,
  "canPlaySlowForward": true,
  "target": 48489,
  "canStepBackward": true,
  "naturalSize": {
    "height": 480,
    "width": 854,
    "orientation": "landscape"
  }
}
```

**Comment by ngima** [comment]
Created new issue: #3680
