### ISSUE TITLE
Error stopping more time viewing menu than reality android

### ISSUE THREAD

**Issue by cuongid** [TheWidlarzGroup/react-native-video#2957]
# Bug
150 / 5,000
Translation results
I play a recipe video. When the video is shown to the recipe, on android devices the pause time is longer than in reality

## Platform
Android
Which player are you experiencing the problem on:
* Android
## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Can you please clarify? Give reproduction steps please ?

**Comment by cuongid** [comment]
Link video: https://d3s55hky34e9q1.cloudfront.net/menu-item%2Fvideo%2F1667551830131IMG_0016.mp4
This is the original video. From time 4 - 8 (4s) is showing ingredients. But if running on a normal device android, the dwell time here can be up to 12s. but when i run it again it's normal
@freeboub

**Comment by freeboub** [comment]
I reproduce the issue on my desktop. It seems to be linked to the video or the server transfer.
You should have a look to network transfer with charles proxy and/or reproduce with a unit test exoplayer.
Nothing react-native-video project can fix.

Anyway you can try to change bufferConfig props

**Comment by cuongid** [comment]
Under normal circumstances, sometimes an error occurs when onLoad is done. But when I use seek(0) to add thumnail on android, this error occurs frequently. On ios it's fine. I checked multiple devices and found no network problems. Only the types of videos that have a break for users to watch will happen like this @freeboub
