### ISSUE TITLE
onEnd is running twice on android  

### ISSUE THREAD

**Issue by Nikunj-Bisht12** [TheWidlarzGroup/react-native-video#2958]
# Bug

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: 5.1.1

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
is it reproduced on 6.0.0 alpha ?

**Comment by freeboub** [comment]
I reproduce the issue on my desktop. It seems to be linked to the video or the server transfer.
You should have a look to network transfer with charles proxy and/or reproduce with a unit test exoplayer.
Nothing react-native-video project can fix

**Comment by freeboub** [comment]
You can also try to play with bufferConfig props ...

**Comment by Ljubixonovich** [comment]
Yeah, onEnd is called twice. We had a problem with this too on our project.

**Comment by Nikunj-Bisht12** [comment]
@Ljubixonovich did you came up with a solution?

**Comment by Nikunj-bisht** [comment]
> Yeah, onEnd is called twice. We had a problem with this too on our project.

when some props is getting changes then onEnd is running twice

**Comment by mohamed2m2018** [comment]
Same issue

**Comment by Nikunj-Bisht12** [comment]
> Same issue

i just debug the issue it happens only when some props gets changed like pause

**Comment by freeboub** [comment]
Just test on 6.0.0-alpha.6, this issue seems to be fixed. Let me know if this is still reproduced and provide a sample
