### ISSUE TITLE
Does react-native-video supports pseudo streaming of MP4 ?

### ISSUE THREAD

**Issue by Not-Qualified** [TheWidlarzGroup/react-native-video#2964]
### Current behavior
I'm creating tiktok like application where I want to serve user uploaded video within flatlist in swipe able list, I'm using Amazon S3 Bucket to Store MP4 Video and using AWS Cloudfront as CDN, I've checked that AWS Cloudfront supports Pseudo Streaming of MP4

- Pseudo Streming where Video only gets downloaded as video progresses through playing otherwise it won't get downloaded
- Pseudo Streaming where player requests chunks of video from source

I'm checking on my devices and video gets fully downloaded whether we watch the whole video or not

I'm using MP4 in such way that I've moved MOOV ATOM to the beginning of file, So, it's stream ready

### Reproduction steps
You can use Video within Flatlist

### Expected behavior
I wanted that video gets downloaded as user watch it, not when user just watch a little bit still it's downloads the full video

### Platform
Which player are you experiencing the problem on:
* Android

**Comment by Not-Qualified** [comment]
@freeboub , Do You have any insight about this ?

**Comment by yanhongchang-1105** [comment]
Do You have any insight about this ?

**Comment by freeboub** [comment]
I am sorry, but I don't really understand the issue ...
Your issue is that the video is downloaded mulitple times while playing it in loop ?
Or is it that the video is fully downloaded even if not fully watched ?

**Comment by Not-Qualified** [comment]
> I am sorry, but I don't really understand the issue ...
> Your issue is that the video is downloaded mulitple times while playing it in loop ?
> Or is it that the video is fully downloaded even if not fully watched ?

Video gets fully downloaded yet it's not fully watched that's what the issue is

And, also it's taking a time to start playing a video until it gets fully downloaded

I'm using MP4 videos served with cloudfront

@freeboub
