### ISSUE TITLE
Stop the video

### ISSUE THREAD

**Issue by somias** [TheWidlarzGroup/react-native-video#2967]
Hi guys, so Im looking for a way to stop the video.

I already seen the solution with using focus with react-navigation, but my issue is little bit different. When using provided solution it would play the video when focused and pause it when it's not, but when the user goes back to the screen with the video it resumes it self instantly, and it bugs me also it's not what I'm looking for. 

My question is how to make it like this:
1. Video should be paused initially
2. If the user plays it and navigates to the other screen it would then have to pause itself
3. When the user goes back to the screen with video, it should still be paused until user resumes it

Is there perhaps other way to do it besides with focus method.

All help is appreciated, thanks in advance :)

**Comment by maciejsiiminski** [comment]
You have a paused prop. If you want the video to be paused initially just set it as a state with default state false. Then you can just change the state accordingly to your needs, set it to false when the navigate is called inside the video component, and set it to true based on some param passed to the navigate function when you go back to the video screen.

**Comment by somias** [comment]
> You have a paused prop. If you want the video to be paused initially just set it as a state with default state false. Then you can just change the state accordingly to your needs, set it to false when the navigate is called inside the video component, and set it to true based on some param passed to the navigate function when you go back to the video screen.

Yes, but what if I have Video on Home tab (tab navigator), and switch to other tab ? It would still play the video when Im on different tab screen.

**Comment by freeboub** [comment]
The best way to stop (and then unload the player) is to remove uri props.
But here I think you only want to pause playback, so @maciejsiiminski tips is good for me.
Be carefull of device capabilities, you cannot keep too much paused playback in the same time

**Comment by jotilohana** [comment]
@freeboub is there any other better solution?

**Comment by freeboub** [comment]
No I think that is the good way to proceed...
