### ISSUE TITLE
IMA SDK Interactive Ads

### ISSUE THREAD

**Issue by sametcl2** [TheWidlarzGroup/react-native-video#2968]
# Bug

Hi!, First of all, I want to thank for this library. I want to use Interactive ads with IMA SDK,
I used this code for the test, like this [PR](https://github.com/react-native-video/react-native-video/pull/2923)
` <Video
      adTagUrl='https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/vmap_ad_samples&sz=640x480&cust_params=sample_ar%3Dpremidpostoptimizedpodbumper&ciu_szs=300x250&gdfp_req=1&ad_rule=1&output=vmap&unviewed_position_start=1&env=vp&impl=s&cmsid=496&vid=short_onecue&correlator='
      onReceiveAdEvent={onReceiveAdEvent}
      source={{ uri: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8' }}
      style={{ flex: 1 }}
    />`

But ads not showing up. 

Library version: 5.1.2

**Comment by freeboub** [comment]
Ima sdk has been merged on master and is not yet included in any release. You must use master branch for now

**Comment by sametcl2** [comment]
Hi, I'm trying to use it with the master branch but when compiling in ios, it gives me this error in Xcode.

`node_modules/react-native-video/ios/Video/RCTVideoPlayerViewController.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

As I see, there is RCTVideoPlayerViewController.swift file. How can I correct this.

Thanks again.

**Comment by EmilianoMorghen** [comment]
@freeboub As of today, do we have any release that support IMA SDK (both on iOS and Android)? 

I'm trying to use [v6.0.0-alpha.5](https://github.com/react-native-video/react-native-video/tree/v6.0.0-alpha.5) but with no luck. 
I've tried feeding the component some of [Android test links](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags) but none of them works.

**Comment by sametcl2** [comment]
Hi @EmilianoMorghen. Yes, it seems there is currently no support for IMA SDK, I tried too. Luckily, I pulled master branch a while ago, It works with test links, [here](https://github.com/sametcl2/react-native-video).

**Comment by freeboub** [comment]
Last 6.0.0 supports IMA. But you must enable it in gradle !
This is explained in documentation (in install section).
It is currently enabled by default on ios, it will be disabled soon.
Notice I was able to test it on sample app after doing some small modifications (patch gradle + ad adtag in xml)

**Comment by sametcl2** [comment]
After enabling it, it works thank you. In adTagUrl section of the documentation, there is a link about it but points nowhere. Maybe that's why we are confused. I will open a PR to fix that in the documentation. Thanks again @freeboub

**Comment by EmilianoMorghen** [comment]
It works for me too! Thanks guys
