### ISSUE TITLE
[Android] Change selected text or audio track not working properly

### ISSUE THREAD

**Issue by facugu1998** [TheWidlarzGroup/react-native-video#2973]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.96 GB / 15.50 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: ^0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.4

## Steps To Reproduce

1. Store in state audioTracks and textTracks on load. Audio languages are: en, es, pt.
2. Select on “onLoad” a different audioTrack, for example, pt.
3. The audio is playing on “pt”.
4. Change audio to "es".
5. The audio is playing on "es".
6. Change back to "pt".
7. The audio keeps playing on "es".

## Expected behaviour

1. The audio should be "pt".

## Possible solution

Modifying function `setSelectedTrack` on file /[android](https://github.com/react-native-video/react-native-video/tree/master/android)/[src](https://github.com/react-native-video/react-native-video/tree/master/android/src)/[main](https://github.com/react-native-video/react-native-video/tree/master/android/src/main)/[java](https://github.com/react-native-video/react-native-video/tree/master/android/src/main/java)/[com](https://github.com/react-native-video/react-native-video/tree/master/android/src/main/java/com)/[brentvatne](https://github.com/react-native-video/react-native-video/tree/master/android/src/main/java/com/brentvatne)/[exoplayer](https://github.com/react-native-video/react-native-video/tree/master/android/src/main/java/com/brentvatne/exoplayer)/ReactExoplayerView.java.

Original code block: 

```[java]
DefaultTrackSelector.Parameters selectionParameters = trackSelector.getParameters()
            .buildUpon()
            .setRendererDisabled(rendererIndex, false)\
            .addOverride(selectionOverride)
            .build();
```

Solution:

```[java]
DefaultTrackSelector.Parameters selectionParameters = trackSelector.getParameters()
            .buildUpon()
            .setRendererDisabled(rendererIndex, false)
            .clearOverridesOfType(selectionOverride.getType())
            .addOverride(selectionOverride)
            .build();
```

**Comment by rohitninawe** [comment]
+1 same problem.

The above Solution works for me.
```

DefaultTrackSelector.Parameters selectionParameters = trackSelector.getParameters()
            .buildUpon()
            .setRendererDisabled(rendererIndex, false)
            .clearOverridesOfType(selectionOverride.getType())
            .addOverride(selectionOverride)
            .build();
            
```

Thank you. @facugu1998

**Comment by freeboub** [comment]
Thank you for the patch, I open the corresponding PR Here: https://github.com/react-native-video/react-native-video/pull/2979
Can you please validate it ?

**Comment by facugu1998** [comment]
@freeboub It looks ok. Thanks!

**Comment by freeboub** [comment]
will be available in alpha.5
