### ISSUE TITLE
Black screen while initiating player on Android Devices

### ISSUE THREAD

**Issue by ajayr82** [TheWidlarzGroup/react-native-video#2974]
# Bug

While initializing the player for playback a black screen appears for a moment - the duration depends on the device type. The below code seems to be causing this issue. Commenting the same seems to fix the issue. 

https://github.com/react-native-video/react-native-video/blob/master/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java:77

Can the background be set to transparent? Or perhaps prop can be provided to set the bg color

Which player are you experiencing the problem on:
* Android

**Comment by hassenlazli** [comment]
Same issues

**Comment by freeboub** [comment]
For sure, it make sens to be able to make background color configurable.
You will need to create a property dedicated to this feature.

**Comment by moGeekHex** [comment]
+2

**Comment by rmyr** [comment]
Having the same issue using the latest alpha. Kinda need to upgrade to the alpha as well, cause seeking is not working well in 5.2 (Android).

This is a major issue for our app, cause you can switch quickly between videos, so the black flicker becomes very noticable.

**Comment by pgpankajbigstep** [comment]
Any solution for this issue?

**Comment by brunoro** [comment]
Also seeing here when using the exoplayer on 5.2

**Comment by brunoro** [comment]
@pgpankajbigstep the solution is to delete that line that sets the shutter background color on ExoPlayerView

**Comment by wolfxpertlab** [comment]
same issue please tell me any solution for this issue

please help me

**Comment by barghi** [comment]
shutterColor="transparent" prop
fixed the issue for me

**Comment by freeboub** [comment]
Thank you @barghi . This ticket can be closed
