### ISSUE TITLE
How to access seek()? Refs don't appear to be returned.  

### ISSUE THREAD

**Issue by benjamincarp** [TheWidlarzGroup/react-native-video#298]
I am trying to get a reference to my player by passing `ref={component => this._videoPlayer = component}` to it but that doesn't appear to ever be called so I don't have a reference to the component to call .seek() on.

```
if (!!this._videoPlayer) {
      this._videoPlayer.seek(val);
    }
```

Is the ref functionality broken or am I misunderstanding how I should call seek()?

**Comment by benjamincarp** [comment]
I dug into this a bit more and the ref functionality definitely is not working.  I haven't figured out why just yet though.  If I use my same ref code on a simple component I made rather than this video component it returns a ref just fine.  

The `ref={this._assignRoot}` line inside the RCTVideo component of Video.js is triggering but the ref property of the parent Video component seems to be doing nothing.

**Comment by TheSisb** [comment]
My app is crashing on ref, so there definitely is something amiss.
![image](https://cloud.githubusercontent.com/assets/1592327/17751932/4de34186-647e-11e6-8510-e3dc9848be9e.png)

**Comment by TheSisb** [comment]
Fixed by following the advice here (https://github.com/react-native-community/react-native-video/issues/226) and wrapping it in a View

**Comment by m3vaz** [comment]
Does it still not work even passing a callback instead of using the string syntax?

https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by mattapperson** [comment]
@benjamincarp pinging for feedback

**Comment by benjamincarp** [comment]
With regard to @m3vaz's question, I am using the callback. It is never called.   

As for @TheSisb's suggestion, I have not tried wrapping it in a view but my understanding is that this would result in a reference to the view when what I really need is access to the seek() method of the VideoPlayer component.

If anyone has sample code of them getting to and calling seek(), I would love to see a working version of it.

**Comment by heatnode** [comment]
Just a note since I came across this looking for seek usage examples. Refs seem to work now. I'm using RN 0.33. The code below works and is based on the example VideoPlayer class:

```
//added this to one of the control sections
  renderSeekControl() {
      const isSelected = false;
      return (
          <TouchableOpacity onPress={() => {this.handleSeekClick() } }>
              <Text style={[styles.controlOption, { fontWeight: isSelected ? "bold" : "normal" }]}>
                  Seek Test
              </Text>
          </TouchableOpacity>
      )
  }

  handleSeekClick() {
      // seek test
      if (this._videoRef !== null) {
          console.log("seeking");
          this._videoRef.seek(0);
      }
  }
renderCustomSkin() {
...
    return (
      <View style={styles.container}>
        <TouchableOpacity style={styles.fullScreen} onPress={() => {this.setState({paused: !this.state.paused})}}>
          <Video
            ref={(ref) => this._videoRef = ref}
            style={styles.fullScreen}
...
```

**Comment by bsiddiqui** [comment]
I'm on 0.31.0 and ref doesn't appear to be working

**Comment by benjamincarp** [comment]
Wrapping the Video component in a View component did seem to make the ref work.  I don't understand it at all, but it worked. 

```
 <View style={styles.container}>
        <TouchableHighlight style={styles.fullScreen} onPress={() => {this.setState({paused: !this.state.paused})}}>
          <View style={styles.fullScreen}><Video
            source={{uri: uri}}
            style={styles.fullScreen}
            rate={this.state.rate}
            paused={this.state.paused}
            volume={this.state.volume}
            muted={this.state.muted}
            resizeMode={this.state.resizeMode}
            onLoad={this.onLoad}
            onProgress={this.onProgress}
            onEnd={() => {this.state.paused = true}}
            repeat={true}
            ref={(component) => {this._videoPlayer = component}}
          /></View>
        </TouchableHighlight>
        {controls}
        <BackButton style={{position: 'absolute', top: 10, left: 10 }}/>
      </View>
```

Get rid of the view between the TouchableHighlight and Video and Ref no longer works.  Strange.

**Comment by bsiddiqui** [comment]
@benjamincarp `TouchableHighlight` expects a native RN component to be a child. I've noticed you get unexpected behavior if you use something else, like `Video` without wrapping in a `View`

**Comment by johnwylie70** [comment]
ref is definitely not returning a value, its undefined. Did it become broken at some point?

if it just the <video> tag that don't return a ref?

I can look at the objective c code, but not sure where I'm looking

**Comment by pologonzalo** [comment]
I have just used and it worked as expected!
