### ISSUE TITLE
The fullscreenOrientation attribute is not work in react-native-video@6.0.0-alpha.4, for Android only

### ISSUE THREAD

**Issue by saurabh297** [TheWidlarzGroup/react-native-video#2981]
how can we support fullscreenOrientation attribute for android?
please help me if anyone idea how to do that.

**Comment by freeboub** [comment]
Why not using external package like https://github.com/wonday/react-native-orientation-locker ?
Let me know if it works for you !

**Comment by saurabh297** [comment]
ok I will try and let you know it is working or not because i don’t support landscape mode in app that why i strict set              android:screenOrientation="portrait"
so is this library work with this?

**Comment by freeboub** [comment]
I think so, you should try 🤷

**Comment by samihabuawadSL** [comment]
I can confirm that having android:screenOrientation="portrait" on MainActivity prevent the orientation, for android-native developers can this behavior be changed somehow or we need a dedicated activity? or maybe for video can it be wrapped on his dedicated Activity that can be customized maybe?
