### ISSUE TITLE
Video restart on paused state change only on Android

### ISSUE THREAD

**Issue by douzal34** [TheWidlarzGroup/react-native-video#2982]
# Bug

Happy new year to all !

I am the creator of SoSkills app which is available on **Apple** and **Android**
**SoSkills** is a video sharing community application in the gaming ecosystem.
More info here [https://soskills.io](url)

Users can swipe up and down in order to see videos about gaming.
When user swipe to the bottom and comeback to the top the video has paused state change (true => false in order to play the current video)
When state change, video start but restart from the beginning without seek method. I need seek method on IOS in order to comeback to the beginning but not with Android.
If you want to let video active, change tab menu and comeback, video will restart and start from his initial position.
I would like to know why this behavior happen on Android

## Platform
- Android with Redmi Note 10S phone
- IOS with Iphone 12 pro

## Environment info

<img width="914" alt="Screenshot 2023-01-04 at 15 42 58" src="https://user-images.githubusercontent.com/3983160/210583406-107084d9-2906-4b06-9341-17c1626d661f.png">

React native info output:

Library version: [v6.0.0-alpha.4]

## Steps To Reproduce

Create a Flatlist with swipe (pagingEnabled to true), swipe top / bottom, comeback and set paused state to the video in order to set paused from true to false
Video will restart at this beginning

## Reproducible sample code

SoSkills is a private company, code is not open source so can't do that but i shared screenshot and video

## Expected behaviour

Video is pause / unpause without comeback to the beginning

## Video sample

https://user-images.githubusercontent.com/3983160/210583353-6088c574-086c-4281-9dbb-4c74a09e7fa9.mp4

**Comment by rohity32** [comment]
dependencies: {
        "react-native-video": {
            platforms: {
                android: {
                    sourceDir: "../node_modules/react-native-video/android-exoplayer",
                },
            },
        },
    },



add above code in your react-native.config.js file which basically means use android exoplayer to play video
