### ISSUE TITLE
Video freeze on resizeMode only on Android

### ISSUE THREAD

**Issue by douzal34** [TheWidlarzGroup/react-native-video#2983]
# Bug

**Happy new year to all !**

I am the creator of SoSkills app which is available on **Apple** and **Android**
**SoSkills** is a video sharing community application in the gaming ecosystem.
More info here [https://soskills.io](https://github.com/react-native-video/react-native-video/issues/url)

When user swipe to the bottom on the first render, we can see video which is freezing before going to the mid place naturally after.
**UI** is frozen and i want to be able to not having this effect for having better experience.

**ResizeMode** is not set, i keep default behavior cause contain is almost the same thing with padding.
**Style** is of the video is all the screen except the bottom menu so **93.5%** of the height and **100%** of the width.
When **react-native-video** init with the **uri**, freeze is happening and i can't hide this effect, even with **poster** attribute or **reanimated 2** with image during the load cause freeze is so quick.

I have tried to set an image in front of the video during the loading in order to not see the freeze but the only case which is working is when i wait until the first onProgress event, which is not good for user experience.

On Apple, everything is working fine, no freeze, so nice. 

## Platform
- Android with Redmi Note 10S phone
- IOS with Iphone 12 pro

## Environment info

<img width="771" alt="Screenshot 2023-01-04 at 15 44 00" src="https://user-images.githubusercontent.com/3983160/210586781-b6a06757-89af-4b50-94b5-0f5a7d073b31.png">
<img width="914" alt="Screenshot 2023-01-04 at 15 42 58" src="https://user-images.githubusercontent.com/3983160/210586802-9c4e802b-d0c4-4d18-b7c5-0f583eeca513.png">

React native info output:

React native: 0.67.3
Library version: [v6.0.0-alpha.4]

## Steps To Reproduce

Create a Flatlist with swipe (pagingEnabled to true), swipe to the bottom and see how video is resized during the rendering

## Expected behaviour

Video resize without freeze

## Reproducible sample code

SoSkills is a private company, code is not open source so can't do that but i shared screenshot and video

## Video sample

https://user-images.githubusercontent.com/3983160/210587388-4e26b9d0-faec-4e66-8c31-9fe84c25ab0e.mp4

**Comment by pgpankajbigstep** [comment]
Hey @douzal34  did you get the solution ?

**Comment by douzal34** [comment]
Yes i found my own solution @pgpankajbigstep !

I do not wait library to do the job to place the video according to the dimension height / width.
I have information about the video in database so i know at the start the dimension.

**Case height > width**
Video will be in fullscreen of the device as on Instagram short so i let **93.5%** on the height and **100%** on the width. Moreover i set resizeMode to cover on rnv.
Sometime users upload videos with same width / height, I put the same configuration too.
 
**Case height < width**
I set height to **28%** and width to **100%** and i pass this style to the video component. Parent View which take 93.5% of the height will only justifyContent center the video component. By doing this, video component from rnv will not have to preload in fullscreen and change dimension cause my height **28%** is smaller than the width !
So do not set height **93.5 %** for all the cases, handle height according to the dimensions of yours videos.
Note that in this mode, i set resizeMode to none on video component.

I also use reanimated on video component and i apply style to the component without re rendering state, job is done by UI thread.
I use Animated.createAnimatedComponent(VideoPlayer) for doing this.

I let you some screenshot about my stylesheet, and the animated style of the component.
Note that animated style is changing according to the rotation of the device cause with SoSkills, you can see video in portrait and in horizontal mode !

<img width="988" alt="Screenshot 2023-02-22 at 19 18 09" src="https://user-images.githubusercontent.com/3983160/220724905-4e02a6dd-3d82-4cac-8bc8-25180d956790.png">
<img width="513" alt="Screenshot 2023-02-22 at 19 18 19" src="https://user-images.githubusercontent.com/3983160/220724884-343d2b1d-db5a-434d-9cee-fd671cc0486e.png">

Enjoy !
