### ISSUE TITLE
Video freeze UI until video is loaded on IOS, scroll is stuck

### ISSUE THREAD

**Issue by douzal34** [TheWidlarzGroup/react-native-video#2986]
# Bug

Happy new year to all !

I am the creator of **SoSkills** app which is available on **Apple** and **Android**
**SoSkills** is a video sharing community application in the gaming ecosystem.
More info here [https://soskills.io](https://github.com/react-native-video/react-native-video/issues/url)

Keep in mind user can swipe through videos on the Home page with FlatList as Instagram short, TikTok etc

When user swipe to the bottom, app is going to load new videos by doing a request to the server for having videos object from BDD with uri property which is the path of the video on Amazon, so the file is not get by my server but directly with react-native-video (uri is with https)
So when user swipe, new item in the Flatlist are rendered and Video component start to init video with new uri from Amazon.
Request take some time when there's an average connexion or bad connexion, UI will freeze, app will be stuck and user can't do anything on the app until video is loaded by react-native-video.

No hidden process or work is doing during the scroll, just react-native-video is blocking the JS thread and UI freeze

## Platform

- Android with Redmi Note 10S phone
- IOS with Iphone 12 pro

## Environment info
<img width="914" alt="Screenshot 2023-01-04 at 15 42 58" src="https://user-images.githubusercontent.com/3983160/210594011-88fdd8be-67b0-4164-b6a5-1d83c337cc43.png">

React native: 0.67.3
Library version: [v6.0.0-alpha.4]

## Steps To Reproduce

Use average connexion or bad connexion which is the best scenario.
Create a FlatList with with 3 item where item is taking all the viewport so one item by viewport.
Get new data when item + 1 === item.length and get new data, ui will freeze.

## Expected behaviour

UI with no freeze, scroll still possible even if Video component is loading the video as Android with their video player.
On Android, if video is not loaded, user has just to wait but if he wants to scroll he can, without being stopped.

## Reproducible sample code

**SoSkills** is a private company, code is not open source so can't do that but i shared screenshot and video

## Video sample

This example is done with my Iphone 12 pro on 4g which is average so if you don't have good connexion, it's really not good ! 

https://user-images.githubusercontent.com/3983160/210596138-0d291326-06ba-4cae-bfcc-85e260be4add.mp4

**Comment by parnaudd** [comment]
Hi ! 

Did you find a solution about this problem ? I got the same issue, tried many thing that not working.

Thanks! :)

**Comment by MrSolimanKing** [comment]
For me I downgraded to `5.2.1` from `6.0.0-alpha.4` and every thing works well, till they release update to fix this problem on iOS

**Comment by Avi00001** [comment]
Hi

I have also facing the same issue with 6.0.0-alpha.4 and Did you find a solution about this problem ?

**Comment by MrSolimanKing** [comment]
My solution was just to downgrade `react-native-video` to version `5.2.1` and everything works fine the freezing didn't happen again, it looks like the problem is coming from the new version of `react-native-video`

**Comment by Zeigfreid** [comment]
Same with version 6.0.0-alpha.1

**Comment by azuluaga-hu** [comment]
any other solution? I can't downgrade because 6.0.0-alpha.5 fixed another problem for me

**Comment by azuluaga-hu** [comment]
This solution, is working for me
https://github.com/react-native-video/react-native-video/issues/2744#issuecomment-1237459473

**Comment by freeboub** [comment]
@zuluHumand be careful, it is not thread safe, that is why it has been reverted

**Comment by Trashpants** [comment]
Also facing this issue - and relying on a newer update that works well with android devices in the newer alphas - as the given solution is somewhat dangerous is there any safer way through this issue?

**Comment by himanshut230** [comment]
facing this issue in (v6.0.0, v6.1.2) versions. In v6.0.0-alpha.7 it is working fine but there are other issues in this version and it is not stable.

**Comment by gerson** [comment]
I'm having the issue in (v6.0.0, v6.1.2) versions. In v6.0.0-alpha.7 it is working fine cannot go back since there are another issues in this version and I would like to use the stable one. I think this issue has to be re-opened since is happening on the latest stable releases

**Comment by Ritik5Prasad** [comment]
> I'm having the issue in (v6.0.0, v6.1.2) versions. In v6.0.0-alpha.7 it is working fine cannot go back since there are another issues in this version and I would like to use the stable one. I think this issue has to be re-opened since is happening on the latest stable releases

Is it working fine with Android also???

**Comment by Navipro70** [comment]
I have the same issue on `"react-native-video": "^7.0.0-alpha.12"` the UI became blocked while video player is initializing
