### ISSUE TITLE
Video is constantly choppy on Android

### ISSUE THREAD

**Issue by SDK-Nattule** [TheWidlarzGroup/react-native-video#2988]
# Bug
Watching the video on Android we see that it cuts out constantly, I'm sure it's a buffer configuration issue, but I can't find the correct configuration, can you help me with the code. Sorry for my bad English.

## Platform
Android

## Environment info

react-native: 0.69.4
react-native-video: ^6.0.0-alpha.1

## Reproducible sample code

              `<Video
                    ref={videoPlayer}
                    source={{uri: url}}
                    poster={imagen}
                    audioOnly={tipo == 'audio' ? true : false}
                    posterResizeMode='cover'
                    paused={pause}
                    style={fullscreen ? styles.fullscreen : styles.videoPlayer}
                    buffered={true}
                    resizeMode="cover"
                    ignoreSilentSwitch={"ignore"}
                    playInBackground={true}
                    playWhenInactive={true}
                    onLoad={(data) => {
                        setTotalDuration(data.duration);
                    }}
                    onProgress={(e) => {
                        const currentTime = e.currentTime
                        if (currentTime > totalDuration) {
                            setProgress(0);
                        } else {
                            const progress = (currentTime / totalDuration);
                            setProgress(progress);  
                            setActualTime(currentTime);  
                        }
                    }}
                    onEnd={() => { setPause(true); }}
                />
`

## Video sample
https://files.fm/u/cerpvvkzp

**Comment by vargajacint** [comment]
It's not a solution, but may cause your issue.  In the `onProgress ` function you set two state every 300ms(default value).

**Comment by freeboub** [comment]
@SDK-Nattule do you have the issue if remove the onProgress callback ?

**Comment by pateljoel** [comment]
This is still happening on all Android devices for me and seems to be a severe issue.

@SDK-Nattule I cannot see the video sample, can you re-upload it onto GitHub directly?

**Comment by bfricka** [comment]
FWIW, I had this same issue until I switched to ExoPlayer on Android.

**Comment by freeboub** [comment]
Should be retested on V6.0.0-RC.0 or RC.2 (comming next week).
I will close the issue, let me know if it is reproduced !

**Comment by bfricka** [comment]
@freeboub For me, this doesn't occur on 6.0.0-rc.0 since it uses ExoPlayer
