### ISSUE TITLE
Video not being de-allocated upon refresh of jsBundle

### ISSUE THREAD

**Issue by arilitan** [TheWidlarzGroup/react-native-video#299]
When a video is playing in debug mode on a simulator or another device, whenever the jsBundle is recompiled and reloaded the video is still playing in the background (iOS only).

Anyone know if theres a way to listen for the jsBundle being reloaded and intercept to instruct the video to be de-allocated from memory?  Normally this isn't an issue in production, but I am using a code-push deployment and thus need to be able to do this when a new jsBundle is downloaded to the production app

**Comment by mattapperson** [comment]
This would be something better asked of the ReactNative project itself, or perhaps of code-push.
