### ISSUE TITLE
Entering fullscreen view removes all KeyboardAvoidingView children

### ISSUE THREAD

**Issue by jwillingham789** [TheWidlarzGroup/react-native-video#2991]
# Bug

Anything wrapped inside of a KeyboardAvoidingView disappears from the screen after video enters fullscreen. Views are still gone after closing out of fullscreen. Not sure if theres a collision in UI VIews or what.

## Platform

 IOS

## Environment info

    react: 17.0.2 
    react-native: 0.68.4 
    react-native-video: 5.2.1

## Reproducible sample code

```
import {KeyboardAvoidingView} from 'react-native';
import Video from 'react-native-video';

<>
  <Video source={{uri}} controls />
  <KeyboardAvoidingView behavior="padding">{children}</KeyboardAvoidingView>
</>

```

**Comment by freeboub** [comment]
The the initial step (ui hidden when going to Fullscreen) I think it is the expected behavior. ( I am sure, It is, on Android).
But when you close Fullscreen your ui should come back !
Is it reproduced also on Android?
