### ISSUE TITLE
Full-screen setting not working on iOS

### ISSUE THREAD

**Issue by joel-acedo** [TheWidlarzGroup/react-native-video#2993]
# Bug

When we set the video player with full screen setting to true, the video seems to not load on full screen because the left corner button shows the "Go to full screen" button and not the "Close" one.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 57.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /var/folders/rk/w5687n4178jd6sr8jlmw8gmm0000gn/T/yarn--1673292890332-0.3231251354929108/node
    Yarn: 1.22.10 - /var/folders/rk/w5687n4178jd6sr8jlmw8gmm0000gn/T/yarn--1673292890332-0.3231251354929108/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2022.02.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

React version: 0.67.5
Library version: 5.2.1

## Steps To Reproduce

1. Add fullscreen property to Video component
2. Launch on iOS device (Tested on iOS simulator)
3. The video loads correctly, but the left corner button shows the icon to go to full screen instead of the close button.

## Expected behaviour

The icon should be the close icon and not the "Go to full screen" button if the fullscreen property is set to true when Video component renders.

## Reproducible sample code

```js
import React, { FunctionComponent, useRef } from 'react'
import Video from 'react-native-video'

interface Props {
    videoUri: string
}

export const VideoActivity: FunctionComponent<Props> = ({ videoUri }) => {
    const VideoRef = useRef(null)

    return (
        <Video
            ref={VideoRef}
            style={{ height: '100%' }}
            source={{ uri: videoUri }}
            controls
            resizeMode={'contain'}
            fullscreen={true}
        />
    )
}

```

## Video sample

<img src="https://user-images.githubusercontent.com/102149069/211398146-8e5a2444-55b4-4952-934c-f8f72b591571.png" width="400" />

<img src="https://user-images.githubusercontent.com/102149069/211398182-c39f236b-78f7-4c35-934b-43d5a4b39d1c.png" width="400" />

Thanks a lot in advance!

**Comment by philipbrady13** [comment]
i ran into this issue as well. i ended up having to call `player.presentFullscreenPlayer()` to launch the player in full screen mode. i then used the `onFullscreenPlayerWillDismiss` prop to navigate to a different screen when the user closes out full screen. its not perfect but it works for now

**Comment by joel-acedo** [comment]
Thanks a lot @philipbrady13, I tried that, but unfortunately, it didn't solve the problem. However, I have managed to make the video work in full screen by launching it in a new view of the react-navigation in modal mode. It seems that if we launch the Video component inside a modal, iOS detects that and shows the close button directly.
