### ISSUE TITLE
{"error": {"extra": -2147483648, "what": 1}}

### ISSUE THREAD

**Issue by roo12312** [TheWidlarzGroup/react-native-video#2994]
hi,
 I'm getting  `{"error": {"extra": -2147483648, "what": 1}}`
on mpd files

**Comment by pgpankajbigstep** [comment]
Hey @rohankm : Did you get any solution of this error ?

**Comment by roo12312** [comment]
> Hey @rohankm : Did you get any solution of this error ?

Hi, use m3u8 instead of mpd it works both on ios and android.

**Comment by rubbishCoder** [comment]
try using a `https` url instead of `http`

**Comment by utkuimd** [comment]
Local mp4 file work fine in android but it didnt work remote mp4 file, so
I added these in my react-native.config.js file
dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
then removed my app and install again. Its worked, maybe its work for mpd.

Sample remote mp4 file link: https://samplelib.com/lib/preview/mp4/sample-5s.mp4
