### ISSUE TITLE
subtitleStyle -  paddingBottom crops the text

### ISSUE THREAD

**Issue by zainkhas** [TheWidlarzGroup/react-native-video#2997]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 44.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 19.0, macOS 10.15, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 12.1.1/12A7605b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: v6.0.0-alpha.4

## Steps To Reproduce

1. Add subtitleStyle prop 
2. paddingBottom's value to 50
...

## Expected behaviour

1. After adding the padding the position of text should change instead of being cropped.

## Reproducible sample code

```
<Video
        source={{uri: url}}
        ref={player}
        onError={onError}
        onProgress={onProgress}
        progressUpdateInterval={500}
        muted={isMuted}
        paused={!isPlaying}
        onLoadStart={onLoadStart}
        onLoad={onLoad}
        fontSizeTrack={30}
        preventsDisplaySleepDuringVideoPlayback={fullScreen}
        textTracks={subtitleTracks}
        selectedTextTrack={{
          type: 'title',
          value: subtitle,
        }}
        subtitleStyle={{paddingBottom: 50}}
        fullscreen
      />
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

![WhatsApp Image 2023-01-10 at 9 48 43 PM](https://user-images.githubusercontent.com/54834436/211612734-d690b913-68ab-4779-a52c-f51f97ce28a1.jpeg)

**Comment by freeboub** [comment]
Thank you for this ticket, can you please clarify which subtitle type you use ? (TTML / WEBVTT ...) and confirm this is side loaded text tracks ?

**Comment by zainkhas** [comment]
> Thank you for this ticket, can you please clarify which subtitle type you use ? (TTML / WEBVTT ...) and confirm this is side loaded text tracks ?

It's a VTT file, and yes, sideloaded via another URL.

**Comment by freeboub** [comment]
Just tested on 6.0.0-beta.6, on a sample provided in another ticket (tested on emulator). I don't reproduce the issue.
I close the ticket, please let me know if you still have the issue and provide a detailed sample.

          textTracks={[
            {
                title: 'test',
                language: 'en',
                type: TextTracksType.VTT,
                uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
              },
          ]}
          selectedTextTrack={{
              type: 'title',
              value: 'test'
          }}
          source={{ uri: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8' }} // this is sample video, my actual video file is MP4
          subtitleStyle={{paddingBottom: 50}}
