### ISSUE TITLE
Add `hardware` parameter to `isCodecSupported` to avoid CPU decoding

### ISSUE THREAD

**Issue by gtebbutt** [TheWidlarzGroup/react-native-video#2998]
# Feature Request

## Why it is needed

Even on devices where a decoder exists, it's useful to know whether it's done in hardware or software - the extra CPU load and battery drain of using h.265 on a device that only has a dedicated chip for h.264 can more than offset the benefits the user gets from file size/quality gains, for example. It's likely to become even more fragmented as AV1 becomes more common, and the tradeoffs there are greater as well. 

## Possible implementation

Open question whether it'd be best to have an additional input flag on `isCodecSupported` to only check for hardware support, whether to modify it to return an enum value for hardware/software/unsupported rather than a boolean, or whether to add a `getDecoderInfo(mimetype, width, height)` method to just return the full details and let the developer decide what to do from there. 

Any of the above should be pretty similar to the existing code, just adding a call to [`getCodecInfos`](https://developer.android.com/reference/android/media/MediaCodecList#getCodecInfos())() on `mRegularCodecs`, although [`isHardwareAccelerated`](https://developer.android.com/reference/android/media/MediaCodecInfo#isHardwareAccelerated()) was only added in API level 29. There are fallback options for older android versions, but they seem less reliable: https://github.com/google/ExoPlayer/issues/5377

iOS is easier in general since there are far fewer possible devices to account for, and it looks like [`VTIsHardwareDecodeSupported`](https://developer.apple.com/documentation/videotoolbox/2887343-vtishardwaredecodesupported) would do the job here.

**Comment by freeboub** [comment]
will be available in v6.0.0-alpha.9
