### ISSUE TITLE
Video doesn't resume from the same time it was paused at, if it stays paused for a few seconds.

### ISSUE THREAD

**Issue by fluorescent23** [TheWidlarzGroup/react-native-video#2999]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android (Reproducible on both the media players available for android)

## Environment info

React native info output:

```bash
 System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 120.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

I have a video which is about 45 seconds long. I have created a component somewhat similar to Whatsapp stories.
When I press and hold on the screen the video pauses. But, with this particular longer video, the video seeks back/forward to some position different from the position I paused the video on if it stays paused for longer than around 5 seconds. If I release the tap the video resumes from that wrong position. If I release the tap sooner than around 5 seconds, it works as expected.

1. Start playing a video.
2. Keep it paused for longer than around 5 seconds, and the video abruptly skips to some other position, different from what it was paused on.
3. If the video is unpaused now, it will resume from that wrong position.
4. It works as expected if the video is unpaused before it has the chance to skip to a different position.
5. It also works as expected on smaller videos.

## Expected behaviour

1. The video shouldn't skip to some different position if it is paused.

## Reproducible sample code
Should probably work with a simple implementation with a longer video.

Here is my slightly trimmed down implementation.
```
<Video
    source={{uri: media_url}}
    resizeMode="contain"

    // This is toggled to true when I long press on the screen, and toggled to false when the touch is released.
    paused={pauseAutoStoryChange}

    onLoadStart={() => {
        setMediaLoading(true);
    }}
    onLoad={videoData => {
        setVideoDuration(videoData.duration * 1000);
        setMediaLoading(false);
    }}
/>
```

## Video sample
Any video longer than 45 seconds.

**Comment by dr1verrr** [comment]
6.0.0-alpha.4 fixed seek behavior on android

**Comment by abir701** [comment]
@dr1verrr I have been facing this issue on iOS while playing HLS stream. The behaviour is same as mentioned. If we wait some time while pausing the video and when we resume its not starting from the paused position. But android is ok. 
Do you have any idea how can i fix it. i have tried to seek from exact pause position but does not work.
