### ISSUE TITLE
undefined is not an object (evaluating 'contentModes.ScaleAspectFill')

### ISSUE THREAD

**Issue by Benmidi** [TheWidlarzGroup/react-native-video#3]
On line 39 of Video.ios.js.

I've ran through all of the steps, not sure what the problem is...

**Comment by brentvatne** [comment]
Hi there @Benmidi! I suspect that `libRCTVideo.a` has not been linked - can you show me a screenshot of your `Link Binary With Libraries` list is?

**Comment by brentvatne** [comment]
Closing as I haven't heard back from you and cannot reproduce this issue, feel free to re-open if the above suggestion doesn't help! :smile:

**Comment by Benmidi** [comment]
You called it, I had added it initially but when I changed the path to where I was loading the library I forgot to update Build Phases. Thanks
