### ISSUE TITLE
How to set thumbnail and title on background mode

### ISSUE THREAD

**Issue by Odkhuu17** [TheWidlarzGroup/react-native-video#3003]
How to set thumbnail and title on background mode

![IMG_1312](https://user-images.githubusercontent.com/13804272/213607912-fcb12e4d-933c-4412-b690-4abe454514a7.PNG)

**Comment by vargajacint** [comment]
https://github.com/react-native-video/react-native-video/issues/2938#issuecomment-1387182324

According to this discussion, I suggest you to try [react-native-music-control](https://www.npmjs.com/package/react-native-music-control) or `react-native-track-player`

**Comment by freeboub** [comment]
Thank you @vargajacint. I think we should follow up in linked ticket

**Comment by Alexadru** [comment]
@Odkhuu17 just pass them in the source with `metadata`

Here's an example

`<Video source={{uri:#URL, metadata:{title:#TITLE, imageUri:#thumbnailURL} }} />`

**Comment by ToshKoevoets** [comment]
@Alexadru  what version? doesn't seem to work.
