### ISSUE TITLE
Cannot find type 'RCTEventDispatcher' in scope

### ISSUE THREAD

**Issue by Aggroid** [TheWidlarzGroup/react-native-video#3004]
# Bug cannot find type 'RCTEventDispatcher' in scope

## Platform

Which player are you experiencing the problem on:
* iOS
* Android

React native info output:

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 669.03 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 7.0.4 => 7.0.4 
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version:  "react-native-video": "v6.0.0-alpha.4",

## Steps To Reproduce

1. npm install react-native-video
2. pods install
3. react-native run-ios
...

## Expected behaviour

1. To run the application

**Comment by freeboub** [comment]
RCTEventDispatcher is part of React-Core.
I don't have the issue on react-native 0.64 version
And I don't think this is reproduced on basic sample from this repo.

RCTEventDispatcher is included in : RCTEventDispatcherProtocol

Let me know if it helps, It is not the first time this issue is reported

**Comment by Aggroid** [comment]
Hey, by the documentation it says that we need to be on > 0.68.2 react-native to use 6.alpha.4 . I saw that in some commits it's fixed but is this fix in the last version? Not sure about that. What do you suggest with that " RCTEventDispatcher is included in : RCTEventDispatcherProtocol " ?

**Comment by Aggroid** [comment]
Sadly i cannot sent demo because our code is private. The application is being used by 250k users overall  with around 20m users total.

**Comment by freeboub** [comment]
I don't want your full application :) maybe to start investing, do you reproduce the issue on master branch, with basic sample included in the repo ?

**Comment by Aggroid** [comment]
Yes, sorry. So I was using 5.2.0 and just updated to the latest one because I'm facing another issue which I want to investigate with the latest version. The issue is when the user is on full screen on iOS and there is a notification, modal or pop up ( just example how we bug it is we connect the phone to the charger and the pop up "Trust device" comes up) the phone is freezing and the only way to get out is to kill the app or restart the phone. Black screen is appearing. So I Just updated to the latest version which is : "react-native-video": "v6.0.0-alpha.4" .  npm version 6.14.4.

Using pure component and import of VIdeo from react-native-video. 

`  <TouchableOpacity style={loggedContainer} onPress={onVideoPress}>
                            <Video
                              source={{ uri: streamUrl }}
                              muted={mutePlayer}
                              onFullscreenPlayerDidDismiss={onExitFullScreen}
                              ref={(ref) => {
                                  this.player = ref;
                              }}
                              resizeMode="cover"
                              pictureInPicture={false}
                              fullscreen={isFullScreen}
                              style={videoStyle}
                            />

                        </TouchableOpacity>`

When I run pod install i do get : 

Installing PromisesSwift (2.1.1)
Installing react-native-video 6.0.0-alpha.4 (was 5.2.0)

When I run the application I receive : 

node_modules/react-native-video/ios/Video/RCTVideo.swift:98:26: cannot find type 'RCTEventDispatcher' in scope

    init(eventDispatcher:RCTEventDispatcher!) {

node_modules/react-native-video/ios/Video/RCTVideo.swift:24:34: cannot find type 'RCTEventDispatcher' in scope

    private var _eventDispatcher:RCTEventDispatcher?

Thank for you fast replies, I appreciate them .

**Comment by freeboub** [comment]
please don't mix issues :)
So you still have the same issue on 6.0.0-alpha.4. It is strange...
I am a newbie in ios dev, but I merge master with my corporate fork and I don't have this issue...

On my laptop I also have the same xcode version:
 % xcodebuild -version
Xcode 14.2
Build version 14C18

notice that this issue is a duplicated of: https://github.com/react-native-video/react-native-video/issues/2946

**Comment by freeboub** [comment]
maybe you can try this : https://stackoverflow.com/questions/42204295/integrating-existing-app-ios-react-rcteventdispatcher-h-file-not-found-on-reac

**Comment by Aggroid** [comment]
I did tried this and i'm receiving the same : 

  /Users/roberto.tsvetanov/Documents/All-Repositories/Janus/janus-frontend-mobile/node_modules/react-native-video/ios/Video/RCTVideo.swift:98:26: cannot find type 'RCTEventDispatcher' in scope

    init(eventDispatcher:RCTEventDispatcher!) {

Sadly. Well I can use 5.2.1 but still cannot get 6 version working :(

**Comment by WookieFPV** [comment]
I had the same issue.
Wasn't able to reproduce it properly in a clean repo.

A workaround was to patch the package by adding the import to `#import "RCTEventDispatcher.h"` in the `ios/Video/RCTVideo-Bridging-Header.h` file.

```diff --git a/ios/Video/RCTVideo-Bridging-Header.h b/ios/Video/RCTVideo-Bridging-Header.h
index 77815e4e48403a71431aa0df5383ef7c5ae795b9..586eec111034c6488fe928c11a86189cd5ce2f2c 100644
--- a/ios/Video/RCTVideo-Bridging-Header.h
+++ b/ios/Video/RCTVideo-Bridging-Header.h
@@ -1,5 +1,6 @@
 #import <React/RCTViewManager.h>
 #import "RCTVideoSwiftLog.h"
+#import "RCTEventDispatcher.h"

 #if __has_include(<react-native-video/RCTVideoCache.h>)
 #import "RCTVideoCache.h"
```

**Comment by sean-pearson** [comment]
I am also experiencing this issue. When building via yarn ios I get this error.

The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ react_native_video (in target 'react-native-video' from project 'Pods')
(1 failure)

but building on xcode I get the RCTEventDispatcher.h not found.

building with:
Xcode 14.2
Build version 14C18
"react-native": "0.71.3",

**Comment by KrzysztofMoch** [comment]
I am not able to reproduce it with XCode 15 and react-native-video@6.0.0-beta.0 (rn 0.68 & 0.72)

**Comment by KrzysztofMoch** [comment]
Feel free to reopen ticket if it still occurs for you

**Comment by VKR981** [comment]
> I had the same issue. Wasn't able to reproduce it properly in a clean repo.
> 
> A workaround was to patch the package by adding the import to `#import "RCTEventDispatcher.h"` in the `ios/Video/RCTVideo-Bridging-Header.h` file.
> 
> ```diff
> index 77815e4e48403a71431aa0df5383ef7c5ae795b9..586eec111034c6488fe928c11a86189cd5ce2f2c 100644
> --- a/ios/Video/RCTVideo-Bridging-Header.h
> +++ b/ios/Video/RCTVideo-Bridging-Header.h
> @@ -1,5 +1,6 @@
>  #import <React/RCTViewManager.h>
>  #import "RCTVideoSwiftLog.h"
> +#import "RCTEventDispatcher.h"
> 
>  #if __has_include(<react-native-video/RCTVideoCache.h>)
>  #import "RCTVideoCache.h"
> ```

is this necessary ```b/ios/Video/RCTVideo-Bridging-Header.h```

**Comment by WookieFPV** [comment]
> > I had the same issue. Wasn't able to reproduce it properly in a clean repo.
> > A workaround was to patch the package by adding the import to `#import "RCTEventDispatcher.h"` in the `ios/Video/RCTVideo-Bridging-Header.h` file.
> > ```diff
> > index 77815e4e48403a71431aa0df5383ef7c5ae795b9..586eec111034c6488fe928c11a86189cd5ce2f2c 100644
> > --- a/ios/Video/RCTVideo-Bridging-Header.h
> > +++ b/ios/Video/RCTVideo-Bridging-Header.h
> > @@ -1,5 +1,6 @@
> >  #import <React/RCTViewManager.h>
> >  #import "RCTVideoSwiftLog.h"
> > +#import "RCTEventDispatcher.h"
> > 
> >  #if __has_include(<react-native-video/RCTVideoCache.h>)
> >  #import "RCTVideoCache.h"
> > ```
> 
> is this necessary `b/ios/Video/RCTVideo-Bridging-Header.h`

I only changed the import and then created a path using [patch-package](https://www.npmjs.com/package/patch-package).
This is how patch-packages patches look like.
 
 1. do the code change
 2. create patch-package patch (`npx patch-package react-native-video`)
 3. setup patch-package (https://www.npmjs.com/package/patch-package#set-up)
