### ISSUE TITLE
Playback speed is not changing

### ISSUE THREAD

**Issue by AshotManukyan** [TheWidlarzGroup/react-native-video#3008]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. Press the button on the right bottom corner of video player
2. Select Playback speed and choose a value from the list
...

## Expected behaviour

1. Video is expected to play with selected playback speed value
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by AshotManukyan** [comment]
![IMG_6680](https://user-images.githubusercontent.com/49652916/213805710-3b39417d-1bce-4b47-8b7a-77f417a07a24.PNG)

**Comment by AshotManukyan** [comment]
After selecting value from the list, react native video does not change playback speed according to the value selected from the list. This issue exists only on ios. Does anyone has an idea how to fix this or just how to change playback speed on ios?

**Comment by AshotManukyan** [comment]
react-native version - 0.70.5
react-native-video version - 5.2.1

**Comment by freeboub** [comment]
Hello, this behaviour can change depending of type of content you play. can you provide the url you are playing ?

**Comment by tlin967** [comment]
> Hello, this behaviour can change depending of type of content you play. can you provide the url you are playing ?

I am also having this issue on iOS with this url https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4. I would like to add that when you manually set the prop: rate to 0. The playback speed change will be applied after changing the playback speed, but it will not have the auto play video functionality.

**Comment by irmakcosarsahna** [comment]
Same issue

**Comment by sohanpc** [comment]
@AshotManukyan share your code. need to check the code. what approach you are following

**Comment by vorlovsky** [comment]
Same thing for me, but I've been trying to change the "rate" value, it does not work properly (at least on iOS). I've tested it on several videos (mp4, 25fps to 150 fps). Any value below 1.0 result in the same playback speed, presumably the same as for rate=0.5. Values above 1.0 (tried 2.0...6.0) produce more or less identical result - static frame for a few seconds, then burst of several frames, then static frame again.

**Comment by eedeebee** [comment]
The UI for speed control doesn't work for me at all.  I load HLS and it plays at 1.0 speed.

**Comment by himanshut230** [comment]
Same issue

**Comment by KrzysztofMoch** [comment]
I've tested it and in v6 it's working fine

**Comment by gulsher7** [comment]
can you provide the code guyz how you speed up the video

**Comment by eedeebee** [comment]
@KrzysztofMoch I'll try to get you a reproducible case.  This is definitely live for me.

**Comment by eedeebee** [comment]
I have it working in v6 now, too!

**Comment by eedeebee** [comment]
Would be great to get feature parity for this on Android.
