### ISSUE TITLE
DRM NOT WORKING - _resouceLoaderDelegate destroyed accidentally

### ISSUE THREAD

**Issue by PierluigiCod** [TheWidlarzGroup/react-native-video#3009]
### Current behavior
When i try to play a DRM content, RCTVideo._resouceLoaderDelegate is accidentally destroyed when func RCTVideo.removePlayerLayer() is called.

### Reproduction steps
Instantiate Video player with drm object.

### Expected behavior
RCTVideo._resouceLoaderDelegate is destroyed only in deinit.

### Platform
* iOS

**Comment by freeboub** [comment]
will be included in 6.0.0-alpha.5
