### ISSUE TITLE
Duplicate Module Errors on Android build

### ISSUE THREAD

**Issue by mljlynch** [TheWidlarzGroup/react-native-video#3011]
# Bug

Hi, I recently installed react-native-video 5.2.1 in my react-native app (v0.63.4). I'm able to build the iOS app and everything is working great! 

However, on android, I'm getting the following error:

> * What went wrong:
> Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > 1 exception was raised by workers:
>   java.lang.RuntimeException: Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0.jar

The code suggests opening [this doc](https://developer.android.com/studio/build/dependencies#resolution_errors), but I haven't manually overriden a dependency before and I don't see any other issue where there has come up

## Platform

* Android
## Environment info

Note: This issue also repros on CircleCI and AppCenter, but this is my system version

System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.77 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
    Python: 3.10.3 - /Users/Jake/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.5 => 0.63.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
React native info output:

Library version: 5.2.1

## Steps To Reproduce

1. npm install react-native-video@5.2.1
2. npx react-native run-android

## Expected behaviour

Build succeeds. 

Happy to provide more info or logs if helpful!

**Comment by freeboub** [comment]
Not sure how we can help... You have similar issue than this discussion: https://stackoverflow.com/questions/60662357/duplicate-class-kotlin-classes-kotlin-version-1-3-70

You need to identify why this library is duplicated in your project.
If you can provide a very basic sample, I can have a look

**Comment by mljlynch** [comment]
Thanks for the quick reply @freeboub. A few follow-ups.

1. I was unclear from the docs if I need to add anything to the `/android` folder for the new package. 

My suspicion is that it's conflicting with `react-native-purchases` both are using:

```
- apply plugin: 'kotlin-android'
```

**Comment by mljlynch** [comment]
I opened a generic react-native issue - it probably is unrelated to this package https://github.com/facebook/react-native/issues/35979. 

I just HAPPENED to try to build this on android at the exact same time. 

Sorry :D

**Comment by freeboub** [comment]
@mljlynch if there is a mismatch kotlin version libraries , it is possible to add a safeExtGet to allow application to force kotlin version used !

**Comment by mljlynch** [comment]
Thanks for the suggestion! 

when I add:

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
...
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet('kotlin_version', '+')}"
```

to my `android/build.gradle`. 

I get the following error:


> Could not find method safeExtGet() for arguments [kotlin_version, +] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by freeboub** [comment]
@mljlynch Yes I would have done something like this, but there is no explicite kotlin dependancy in react native video.
I suspect this is the exoplayer dependancy ...
I have no other clue :/ 
Don't hesitate to post the solution here if you find it ! Thank you

**Comment by mljlynch** [comment]
This comment has an answer:

https://github.com/facebook/react-native/issues/35979#issuecomment-1405377512

Turns out quite a few people were having this issue.
