### ISSUE TITLE
Not able to play MPD files on ios

### ISSUE THREAD

**Issue by roo12312** [TheWidlarzGroup/react-native-video#3014]
Hi,
The Dash MPD files are playing fine in android but not able to play in ios.
I'm getting this error `{"error": {"code": -11828, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Open", "localizedFailureReason": "This media format is not supported.", "localizedRecoverySuggestion": ""}, "target": 449}`

**Comment by freeboub** [comment]
It simply not supported by ios player 🤷
