### ISSUE TITLE
iOS Black Screen when pull top menu from the phone or if notification or modal pops

### ISSUE THREAD

**Issue by Aggroid** [TheWidlarzGroup/react-native-video#3020]
# Bug

## Platform
React-Native iOS
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

info Fetching system and libraries information...
(node:10018) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 145.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 7.0.4 => 7.0.4 
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.1

## Steps To Reproduce

1. Open Video
2. Swipe Menu from the top of the iphone
3.  Blackscreen and cannot get out of the video i need to force quit the application

## Expected behaviour

1. Open Video
2. Swipe menu from the top
3. Video play still playing

## Reproducible sample code
Can't because it's private repo

**Comment by Aggroid** [comment]
Up. I'm still facing that issue and cannot resolve it. Anyone had the same issue?

**Comment by evoactivity** [comment]
Without a reproduction it's going to be difficult for anyone to help diagnose or fix.

Your reproduction doesn't need to be lifted from your companies private repo. Since this is affecting you, you should put the work in to create a basic reproduction that can be shared.

**Comment by freeboub** [comment]
fix wil be available in next release 6.0.0-alpha.9
