### ISSUE TITLE
selectedTextTrack props not working on Android devices

### ISSUE THREAD

**Issue by antoniocarlosraposo** [TheWidlarzGroup/react-native-video#3021]
# Bug

The video player does not show **any** closed captions on **Android** devices when selectedTextTrack uses **language** or **title** as type.

**Index** type is working as expected.

This happens only on Android. 
The expected behavior is seem on IOS.

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 58.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.1 - /var/folders/bg/g53z50rd17152pzlbsbhq6040000gn/T/yarn--1675203103474-0.8726523211689434/node
    Yarn: 1.22.19 - /var/folders/bg/g53z50rd17152pzlbsbhq6040000gn/T/yarn--1675203103474-0.8726523211689434/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

 "react-native-video": "6.0.0-alpha.3",

## Steps To Reproduce

1. Pass selectedTextTrack = {
        type: "language",
        value: "en-US",
      };
to the video component.
2. subtitles not seem.
...

## Expected Behaviour

1.1. Pass selectedTextTrack = {
        type: "language",
        value: "en-US",
      };
2. english subtitles should be seem.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by kveerapen** [comment]
I'm still getting this bug on `"react-native-video": "^6.0.0-alpha.6"`

I'm being forced to use the `index` type in `selectedTextTrack` rather than `language` or `title`, @antoniocarlosraposo did you fix it somehow?

FYI, this is an Android issue, on iOS i can use `language` or `title` types
