### ISSUE TITLE
How to exit from Picture in Picture mode

### ISSUE THREAD

**Issue by ipnet-me** [TheWidlarzGroup/react-native-video#3023]
### Hello,

I have a question. I am using  in my video player "picture in picture" feature.

pictureInPicture={true}

It works perfectly. But when i back again to my app, video still in PiP mode. It there anything that can return to normal mode, if you back manual to app?

**Comment by Aggroid** [comment]
You can catch the lifecycle onFocus or something to trigger fullscreen true

**Comment by ipnet-me** [comment]
> You can catch the lifecycle onFocus or something to trigger fullscreen true

Здравей!

Thanks for advise,

i call method presentFullscreenPlayer() on app back

Now i got video fullscreen but pic in pic still in up layer. So it plays two videos same time

**Comment by Aggroid** [comment]
Maybe after the fullscreen is triggered you can try to destroy the player for PiP. Using ref for the player to destroy PiP and then re-create in full screen ?

**Comment by ipnet-me** [comment]
> Maybe after the fullscreen is triggered you can try to destroy the player for PiP. Using ref for the player to destroy PiP and then re-create in full screen ?

Thanks for reply, i will try it

**Comment by tomyates** [comment]
@ipnet-me did you get anywhere with this? I'm facing the same issue.
