### ISSUE TITLE
The decoder required for this media is busy

### ISSUE THREAD

**Issue by tomscheney** [TheWidlarzGroup/react-native-video#3024]
# Bug

{"error": {"code": -11839, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Decode", "localizedFailureReason": "The decoder required for this media is busy.", "localizedRecoverySuggestion": "Stop any other actions that decode media and try again."}, "target": 25813}

## Platform

Which player are you experiencing the problem on:
* iOS

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 118.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/eagle/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected behaviour

1.  [RCTVideo dealloc ] , it is not excuted  

## Video sample
<Video
        ref={(ref) => {
          setVideoRef(ref)
        }}
        style={comStyles.wHFull}
        ignoreSilentSwitch="ignore"
        playWhenInactive={true}
        automaticallyWaitsToMinimizeStalling={false}
        source={{ uri: videoCache(url) }}
        // source={{uri: url}}
        paused={!isPlay}
        muted={muted}
        poster={poster}
        posterResizeMode="cover"
        resizeMode="cover"
        repeat={true}
        onLoadStart={_onLoadStart}
        onLoad={_onLoad}
        onEnd={_onEnd}
        onProgress={_onProgress}
        onError={_onError}
        {...rest}
      />

**Comment by freeboub** [comment]
Is this something reproduced on V6 ?

**Comment by tomscheney** [comment]
> Is this something reproduced on V6 ?

yes, it is

**Comment by NaciyeCelenliEco** [comment]
I get this error too

**Comment by KrzysztofMoch** [comment]
No demo - if the error continues to occur submit a demo

**Comment by VanDinh18** [comment]
@tomscheney I display list of video from cache using Flatlist. Sometime video is blank. I faced to this issue. How fix it?
