### ISSUE TITLE
Android Distorted video in the emulator. Work fine with a physical device.

### ISSUE THREAD

**Issue by mohito12** [TheWidlarzGroup/react-native-video#3026]
For some reason the videos is distorted on Android emulator. It works fine on a physical device. The video is in an mp4 format.

## Platform
Which player are you experiencing the problem on:
* Android

Library version: 5.2.1 (also tried 6.0.0+)

## Reproducible sample code
```
    <View style={{flex: 1}}>
      <Video
        source={{
          uri: uri,
        }}</View>
        style={{height: '100%'}}
        controls
        resizeMode={'contain'}
      />
    </View>
```
![Screenshot_1675767148](https://user-images.githubusercontent.com/30976417/217227737-07601e49-3ac6-4fcc-9b83-9550c4cc2728.png)

**Comment by freeboub** [comment]
Sorry, but nobody will fix this issue ... 
The basic sample in the app works fine with local mp4 video.
I think this is an interoperability issue with the emulator and you mp4 file.
Let's close this ticket
