### ISSUE TITLE
Orientation issue when changing tabs with react-navigation on a video recorded on a Pixel 4

### ISSUE THREAD

**Issue by cody-young** [TheWidlarzGroup/react-native-video#3031]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android
Edit: The plot thickens. I can't reproduce it on my physical device Pixel 4a running Android 13 (API 33), but I can reproduce it on my emulated Pixel 2 running Android 10 (API 29).

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 12.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 295.48 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.4.0 - /usr/local/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.1 => 0.71.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.4

## Steps To Reproduce
1. Click tabTwo - Wait until video loads at normal orientation
2. Click tabOne
3. Click tabTwo - !video has loaded at an incorrect orientation
...

## Expected behaviour
1. After returning to tabTwo the video should load at the correct orientation

## Reproducible sample code
https://github.com/cody-young/videotest

## Video sample
https://sivideo.sfo3.cdn.digitaloceanspaces.com/output.mp4

## Screenshots
![image](https://user-images.githubusercontent.com/4195563/217925384-b408a4f3-8419-453c-a82f-cd39156b1326.png)
![image](https://user-images.githubusercontent.com/4195563/217925444-827a4ef1-7ffd-49c3-aff8-1c3483f63c85.png)

**Comment by freeboub** [comment]
shall we investigate the issue or is it cancelled as linked to emulator ?
I close the issue, let me know if I need to reopen it !
