### ISSUE TITLE
[V6-alpha] Why has GoogleAds been added to the dependencies?

### ISSUE THREAD

**Issue by hatem-72** [TheWidlarzGroup/react-native-video#3035]
Hello,

I've just upgraded the package to the latest `6.0.0-alpha.5` and noticed that a new GoogleAds dependency was added both to the Android and Ios native dependencies.

I mean, I understand that adding support for CSAI could be useful for some projects, but making it a mandatory dependency for the whole library seems to take us away from the main purpose of this library.

Maybe I haven't notice something so feel free to correct me 😅

**Comment by samihabuawadSL** [comment]
this block iOS publishing for me getting "non-public selector..." referencing the ads GoogleAds as blocker 

I'm  NOT using the ads feature, so I expect this to be an optional deps like many others 

pls help, thx

**Comment by freeboub** [comment]
Ok I did the job on Android, someone also need to do it also on ios.
I will not have time to do this week (not sure for the week after). Quick solution is to downgrade on previous version.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment]
Here is a fix for this issue: https://github.com/react-native-video/react-native-video/pull/3062
Please met let know if it is Ok for you, Thank you
