### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by rsys2022** [TheWidlarzGroup/react-native-video#3037]
# Bug

`react-native-video-tvOS` does not specify a Swift version and none of the targets (`HelloWorld-tvOS` and `HelloWorld-tvOSTests`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

getting this error during install pod
## Platform

Which player are you experiencing the problem on:
 iOS

## Environment info

React native info output:
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 144.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.2 - /opt/homebrew/bin/npm
    Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-2 
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.3 is now available (your project is running on v0.69.6-2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.3.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6-2.

Library version:   "react-native-video": "^6.0.0-alpha.5"

## Steps To Reproduce

1. npm install
2. pod install

**Comment by freeboub** [comment]
Why don't you configure it in you podspec ? Isn't it enough?

**Comment by rsys2022** [comment]
> Why don't you configure it in you podspec ? Isn't it enough?

can you let me know how to configure it in podspec ?   i have tried it many times but did not get success

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment]
I think this issue can be closed, let me know if it still persist (last version: V6.0.0-beta.6)
