### ISSUE TITLE
lot of issues on Android

### ISSUE THREAD

**Issue by beebase** [TheWidlarzGroup/react-native-video#304]
I've build a video player for iPhone but when I open the same codebase on Android, a lot of functionality is broken. Preview images don't show. Stop doesn't work, Rate (slow motion) doesn't work. Videos keep playing when navigating away.

Before I start filing issues, am I suppose to build a separate player for Android? Are there known issues on Android? Other people experiencing similar issues using one codebase  for both platforms?
Thanks.

"react": "^15.2.1",
"react-native": "0.30.0",
"react-native-video": "^0.8.0",

**Comment by afilp** [comment]
I also have similar problems, I hope Android issues can be solved soon. Thanks!

**Comment by mattapperson** [comment]
@beebase There are a number of android issues open at the moment, I would recommend perhaps searching the known issues, and for any issues you don't see, please feel free to open individual issues for the problems you are seeing.
