### ISSUE TITLE
[Bug] Fullscreen broken on iOS due to #3017

### ISSUE THREAD

**Issue by jspizziri** [TheWidlarzGroup/react-native-video#3040]
# Bug

The [check for `_controls == true` introduced here](https://github.com/react-native-video/react-native-video/commit/2032a36969a022c57232baa8f3b9746eff103c28#diff-1536a22e8e888a1d8bccd1916bfec1af06373dd52ddb442c09544718e06a7193R617) results in fullscreen presentation not working on iOS unless the `controls={true}` prop is passed to the video player. Perhaps this was intentional, however, if that is the case when setting that prop [the RNSScreen parent view controller](https://github.com/react-native-video/react-native-video/issues/2808) bug manifests itself.

I'm digging into it now but insights would be appreciated (first look under the hood at this library).

## Platform

iOS

## Environment info

Library version: `6.0.0-alpha.5`

## Steps To Reproduce

1. Embed a Video view on iOS
2. set `controls={true}`
3. Attempt to trigger fullscreen mode
4. Also, see that with `controls={false}` fullscreen presentation fails quietly due to [no `_playerViewController` being instantiated.](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L639)

## Expected behaviour

1. Video player presents fullscreen correctly on iOS.

**Comment by jspizziri** [comment]
To add to the above, it appears that when `controls = false` there is no crash resulting from the `RNSScreen` exception. So it appears that the combination of requiring `controls = true` AND the crash when presenting due to `controls = true` is what renders fullscreen entirely broken on iOS. If you revert to `v6.0.0-alpha.4` and apply [the patch issued here](https://github.com/react-native-video/react-native-video/pull/2971/files) AND have `controls = false` THEN fullscreen presentation works on iOS.

As a result and [along with this issue](https://github.com/react-native-video/react-native-video/issues/3035), I've ended up reverting to `alpha.4` and applying a patch for now.

Here's the `alpha.4` patch in case anyone is interested: [react-native-video+6.0.0-alpha.4.patch](https://github.com/react-native-video/react-native-video/files/10785110/react-native-video%2B6.0.0-alpha.4.patch)

**Comment by kyle-ssg** [comment]
After playing around with this, it seems that the following fixes this issue in ``RCTVideo.swift``:

```
      if let playerViewController = _playerViewController {
                    if(_controls) { //Necessary for preventing crash
                        self._playerViewController?.removeFromParent()
                    }

                    viewController.present(_playerViewController!, animated:true, completion:{
                    ....
```

I have no idea if this is good practice or not but it fixes the issue for me.

**Comment by kyle-ssg** [comment]
Looking into this more, I think this performs even better?

```
 if fullscreen && !_fullscreenPlayerPresented && _player != nil {
            let selectorName: String = {
                if #available(iOS 11.3, *) {
                    return "_transitionToFullScreenAnimated:interactive:completionHandler:"
                } else if #available(iOS 11, *) {
                    return "_transitionToFullScreenAnimated:completionHandler:"
                } else {
                    return "_transitionToFullScreenViewControllerAnimated:completionHandler:"
                }
            }()
            let selectorToForceFullScreenMode = NSSelectorFromString(selectorName)

            if self._playerViewController!.responds(to: selectorToForceFullScreenMode) {
                self._playerViewController!.perform(selectorToForceFullScreenMode, with: true, with: nil)
            }
        }
```

**Comment by luisfuertes** [comment]
@kyle-ssg in which line should we add your last code?

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment]
will be available in next alpha.7 or beta
