### ISSUE TITLE
Views not being counted on Vimeo videos.

### ISSUE THREAD

**Issue by peagace** [TheWidlarzGroup/react-native-video#3044]
Hi guys!

I have the react-native-video implemented on a React Native app both for iOS and Android and I'm using it to reproduce Vimeo videos. The app itself is published and beeing used by a bunch of people for around 6 months. 

Recently I entered on my Vimeo account to see how the videos were performing then I realized that the videos didn't have any views at all!

I made some tests and debugging and my conclusion is that the react-native-video is not counting any views on my Vimeo videos. I tried all options to fix this problem on the video settings directly on Vimeo but couldn't get the desired result.

Is this a know issue?

**Comment by freeboub** [comment]
There is no analytics implemented in RNV... I checked on vimeo api web site, I don't find any references on analytics or statistics management. Do you know how they count views ? 

I suspect something like a user agent issue ( to be checked with Charles proxy)

**Comment by peagace** [comment]
@freeboub Thanks for the reply!

In thoery, Vimeo adds a view every time a user hits the play button.

Here's the Vimeo documentantion about how they count views and impressions:

https://vimeo.zendesk.com/hc/en-us/articles/115004386887-Video-Settings-analytics-panel#:~:text=We%20count%20an%20impression%20every,by%20its%20audience%20and%20exposure

Maybe this problem is something related to the autoplay option?

**Comment by freeboub** [comment]
The issue is that rnv don't use vimeo player I think ... It can explain why it doesn't count the play count. I think you need to contact vimeo support or change to Vimeo player if you really need these statistics.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0
