### ISSUE TITLE
V6 Alpha - iOS CI builds cannot resolve Pod dependencies

### ISSUE THREAD

**Issue by cjhines** [TheWidlarzGroup/react-native-video#3050]
# Bug

I have the V6 alpha installed my project and although it builds locally it is failing on CI.

For some reason, the dependency `PromisesObjC` is appearing twice in the Podfile.lock, even when I delete this file and the `Pods` directory before running `pod install` and `pod update`. There is no other dependency importing these, if I uninstall `react-native-video` these dependencies are gone.

```
  - PromisesObjC (2.2.0)
  - PromisesSwift (2.2.0):
    - PromisesObjC (= 2.2.0)
```

When I try and build this project on CI I get the following issue:

```
[!] CocoaPods could not find compatible versions for pod "PromisesObjC":
  In snapshot (Podfile.lock):
    PromisesObjC (= 2.2.0)
  In Podfile:
    PromisesSwift was resolved to 2.2.0, which depends on
      PromisesObjC (= 2.2.0)
None of your spec sources contain a spec satisfying the dependencies: `PromisesObjC (= 2.2.0), PromisesObjC (= 2.2.0)`.
```

How does this make any sense? Both versions are identical and yet it cannot resolve them.

I've also tried disintegrating the project and reinstalling with no luck.

## Platform
iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.1
    CPU: (6) x[64] Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 3.92 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: v6.0.0-alpha.4

## Steps To Reproduce

1. `npm ci` on CI build
2. Installation fails

## Expected behaviour

1. Pod installation complete!

## Reproducible sample code

```
    - bundle install
    - npm ci
```

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment]
Can you provide you package.json and a sample project. I suspect collision between dependencies...

**Comment by cjhines** [comment]
Issue was resolved by ensuring CI pipeline always ran `pod install --repo-update`
