### ISSUE TITLE
Why is it necessary to set the rate to 0 when the video is paused?

### ISSUE THREAD

**Issue by felipegmg** [TheWidlarzGroup/react-native-video#3052]
### Current behavior
Constantly when I play a video the rate stays at 0 due to the previous pause behavior

### Reproduction steps
1. Play vídeo
2. Pause vídeo
3. Change a source, enter fullscreen or press any control
4. play vídeo

### Platform
Which player are you experiencing the problem on:
* iOS
* Android

I would like to know why it is necessary to set the rate to 0 on both platforms? Is it some technical limitation or lib redundancy mechanism?

Thanks!

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment]
@felipegmg I am not sure to understand the issue.
BTW: I think rate should never be set to 0. I think your issue is somewhere else.
Can you please clarify ?
