### ISSUE TITLE
setting video controls to true in android crash the app

### ISSUE THREAD

**Issue by ziadashraf0** [TheWidlarzGroup/react-native-video#3054]
### Current behavior
App crash

### Reproduction steps
 1- play a video 
 2- navigate back 
 3- play the video again   ===> app crashh ! 

### Platform
* Android

**Comment by freeboub** [comment]
Any sample to reproduce? Any version ? Any logs ?

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by ghost** [comment]
@ziadashraf0 

We have a solution check below

Validate your control boolean value with the source param name
  const [videoSource, setVideoSource] = useState(String);

  <Video
                source={{
                  uri: `file://'${videoSource}`,
                }}
                controls={videoSource ? true : false}
              />

try this it will work.....Worked for me...

**Comment by ghost** [comment]
This worked for me too

**Comment by ghost** [comment]
This worked for me too i was struggling eith it for days
thanks you saved my day.
