### ISSUE TITLE
When use url audio or url video 1080 , file size be duplicated

### ISSUE THREAD

**Issue by memberwebm** [TheWidlarzGroup/react-native-video#3057]
![Simulator Screen Shot - iPhone 14 - 2023-03-09 at 16 51 28](https://user-images.githubusercontent.com/110653846/223985221-7377f6ea-0eae-4025-bace-245540c2b5f8.png)
![Simulator Screen Shot - iPhone 14 - 2023-03-09 at 16 51 47](https://user-images.githubusercontent.com/110653846/223985265-c94fd512-c6b9-4f82-8385-0b442bb40d1a.png)
url audio: https://rr7---sn-8pxuuxa-nbozs.googlevideo.com/videoplayback?expire=1678377179&ei=e6wJZNzrNtG34t4Pjs-auAk&ip=13.213.66.17&id=o-AAfMJWPxOiEZApZCZDu_nfJ7GZsMGvq_EkxduTutiSXS&itag=140&source=youtube&requiressl=yes&ctier=SH&spc=H3gIhrQpq8GekA9Sf5xHKFsOENkrZLA&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=871813&dur=53.823&lmt=1677721586026422&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMn-C1mOrE_lKg9eNC769vqtmZxLIlWGyRc7PTMmVTwvAiEAx98L1j_z3SW2-BjveH_zZgNGRJ78s_9TdVVTJy969EY%3D&redirect_counter=1&rm=sn-npo667s&req_id=4b3fe8527170a3ee&cms_redirect=yes&cmsv=e&ipbypass=yes&mh=bd&mip=2402:800:63eb:d81a:69c8:3ea0:7c39:1a1f&mm=31&mn=sn-8pxuuxa-nbozs&ms=au&mt=1678355342&mv=m&mvi=7&pcm2cms=yes&pl=48&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pcm2cms,pl&lsig=AG3C_xAwRAIgCKFXYy8g7NUjAVeIKVPms2I_Ru8_HnrQRUZaE9FyB8kCICVxGeH907H-X04ZE3FPbEf9ssr46q3g0-kmT90brSaI                                                                                                                                                                                  
                  
video url: https://rr3---sn-npoldn7l.googlevideo.com/videoplayback?expire=1678377178&ei=eqwJZMahA-y_4t4P__-CwAM&ip=13.213.66.17&id=o-AOnJcqJwrCZXX3qa1LwAF47lL4sCncwbvB7Rcn9EI0pl&itag=18&source=youtube&requiressl=yes&mh=bd&mm=31%2C26&mn=sn-npoldn7l%2Csn-30a7rner&ms=au%2Conr&mv=m&mvi=3&pl=23&ctier=SH&initcwndbps=792500&spc=H3gIhgT_8T9qekmUOKHigVln_QU1nZ4&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=4021556&ratebypass=yes&dur=53.824&lmt=1677722371777093&mt=1678355102&fvip=2&fexp=24007246&c=ANDROID&txp=5530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANFQcXqriqXE3jJbAWYUCqXx9s54Cu5zplI2h3D9HoRBAiBmGV2VsbHMob-0sazSvDfHynSpQzO4gdwciuW-meDh2Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTQ2ZFPuJF9g05-tyihARFdtgEWzIt_J05HQVbET_W_4CIH-qkLxt5W7PRV-kf0hlM9iCY88cl4DHHtJXEJ3arGq1

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by memberwebm** [comment]
> Điều này sẽ giúp https://www.youtube.com/watch?v=vVI7ZAZq5e0
i only bug ios not android , please help me :((

**Comment by freeboub** [comment]
I don't understand the issue . Video is too small ?
