### ISSUE TITLE
handlePlaybackLikelyToKeepUp swift implementation

### ISSUE THREAD

**Issue by tironiigor** [TheWidlarzGroup/react-native-video#3060]
# Bug

handlePlaybackLikelyToKeepUp swift implementation is different from ObjectC implementation. I think this is causing the video not to start playing after hitting the unbuffered zone.

Objective-C
```obj-c
      // Continue playing (or not if paused) after being paused due to hitting an unbuffered zone.
      if ((!(_controls || _fullscreenPlayerPresented) || _playerBufferEmpty) && _playerItem.playbackLikelyToKeepUp) {
        [self setPaused:_paused];
      }
      _playerBufferEmpty = NO;
      self.onVideoBuffer(@{@"isBuffering": @(NO), @"target": self.reactTag});
```

Swift
```swift
    // Continue playing (or not if paused) after being paused due to hitting an unbuffered zone.
    func handlePlaybackLikelyToKeepUp(playerItem:AVPlayerItem, change:NSKeyValueObservedChange<Bool>) {
        if (!(_controls || _fullscreenPlayerPresented) || _playerBufferEmpty) && ((_playerItem?.isPlaybackLikelyToKeepUp) != nil) {
            setPaused(_paused)
        }
        _playerBufferEmpty = false
        onVideoBuffer?(["isBuffering": false, "target": reactTag as Any])
    }
```

Instead of checking for `isPlaybackLikelyToKeepUp != nil` the swift version should be checking for `isPlaybackLikelyToKeepUp == true`

## Platform

Which player are you experiencing the problem on:

* iOS

## Environment info

Any version that is using the swift implementation

## Steps To Reproduce

N/A

## Expected behaviour

The video should start playing when it `isPlaybackLikelyToKeepUp` is true

## Reproducible sample code

N/A

## Video sample

N/A

**Comment by freeboub** [comment]
I am completely sure to understand the issue you have. We you seek to live point the playback doesn't restart ? If it fixes your issue, a PR is welcome! :)

**Comment by tironiigor** [comment]
@freeboub yes, the issue is that the video is paused automatically and will be stuck on pause afterwards. I'll open a PR later with the change so everybody can test! We're using it and it seems to be working.

**Comment by freeboub** [comment]
@tironiigor where is the PR ? :D 
Seriously, if you use a custom patch it would be interesting to merge it in the main repo !
Thank you
