### ISSUE TITLE
Issue: [Android bug] unexpected response when onProgress callback revoke

### ISSUE THREAD

**Issue by iita71737** [TheWidlarzGroup/react-native-video#3067]
# Bug

```
 const handleProgress = ({ currentTime, playableDuration, seekableDuration }) => {
    setCurrentTime(currentTime);
    setDuration(playableDuration)
  };
```
when I got the .mp4 video , the duration I check it is 10s,
then I try to use `onProgress` props in <Video/>

`onProgress` callback return normally on iOS
![Screenshot 2023-03-15 at 6 04 20 PM](https://user-images.githubusercontent.com/11864209/225276226-6a7c1e6a-0489-4867-9f5c-205c7d046b1c.png)

but it return weird on Android
I got unexpected error on Android.
![Screenshot 2023-03-15 at 6 05 15 PM](https://user-images.githubusercontent.com/11864209/225276536-b9a1bfb8-86d4-4265-9118-b5b2fd811f6f.png)

If I didn't setDuration
```
 const handleProgress = ({ currentTime, playableDuration, seekableDuration }) => {
    setCurrentTime(currentTime);
    // setDuration(playableDuration)
  };
```
It return correct `currentTime` on Android.
It happened when I setDuration() 
the `onProgress`  return incorrect `currentTime` on Android

but all of above is not happened on iOS, It only happened on Android.

## Platform

Which player are you experiencing the problem on:
* iOS IPhoneXR
* Android 
![Screenshot 2023-03-15 at 6 02 15 PM](https://user-images.githubusercontent.com/11864209/225275580-19388a43-2c42-4ad2-b563-5618816dd1a0.png)

## Environment info

React native info output:

```bash
"react-native": "0.69.7",
"react-native-video": "6.0.0-alpha.5",
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Question: do it happen on real device ? Do you play with a url or a local video file ?

**Comment by iita71737** [comment]
Yes, It occurred on real device. 
The video is from a url.

**Comment by freeboub** [comment]
I don't reproduce the issue with the sample, can you provide a sample please ?

**Comment by freeboub** [comment]
no feedback, let's close
