### ISSUE TITLE
'UIInterfaceOrientationMask' is unavailable in tvOS

### ISSUE THREAD

**Issue by crewtaylorfd** [TheWidlarzGroup/react-native-video#3069]
# Bug

I am seeing a build error in xCode when I try to build a tvOS project using `react-native-tvos`. See the screen shot below for more detail. The error I am seeing is `'UIInterfaceOrientationMask' is unavailable in tvOS`. There are compiler target conditionals to avoid this code for tvOS but for whatever reason xCode is failing because of this code in `RCTVideoPlayerViewController.swift`
## Platform

Which player are you experiencing the problem on:
* tvOS

## Environment info

React native info output:

```bash
 System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 47.46 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/crew.taylor/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-31 | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.5

## Steps To Reproduce

1. Create a `react-native-tvos` project
2. Install `react-native-video@alpha` using installation guide in Docs
...

## Expected behaviour

1. Builds successfully

## Photo sample
![Screen Shot 2023-03-15 at 2 55 00 PM](https://user-images.githubusercontent.com/91975959/225453252-d8404e75-3ee8-43d7-952e-c94fe46f8117.png)

**Comment by freeboub** [comment]
Thank you for the reporting!
According to: https://developer.apple.com/forums/thread/21340

There is an issue in swift rewrite with the macro. I think there are simular issues with pip support on ios.
Can you try to change the #if please ?

**Comment by crewtaylorfd** [comment]
I changed the `#if` and added a couple `if #available(tvOS 10.0, *)` that were also required. Now I am getting the following error on build. 

```
clang: error: no such file or directory: 
'/Users/crew.taylor/Library/Developer/Xcode/DerivedData/<PROJECT_NAME>-gkoffhepubulxxdhxzwcxvagvsey/Build/Products/Debug-appletvsimulator/libRCTVideo.a'

**Comment by freeboub** [comment]
There is a strange <PROJECT_NAME> is the path ...

**Comment by crewtaylorfd** [comment]
> There is a strange <PROJECT_NAME> is the path ...

I replaced my actual project name with `<PROJECT_NAME>` when pasting the error

**Comment by freeboub** [comment]
Should have been fixed by this PR: https://github.com/react-native-video/react-native-video/pull/3207
will be delivered in 6.0.0-apha.8
