### ISSUE TITLE
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.

### ISSUE THREAD

**Issue by aliza-khu** [TheWidlarzGroup/react-native-video#3075]
# Bug
package="com.brentvatne.react" found in source AndroidManifest.xml

## Platform
  * Android

## Environment info

React native info output:

```bash
npmPackages:
  react: 18.2.0 => 18.2.0
  react-native: 0.71.4 => 0.71.4
npmGlobalPackages:
  react-native: 0.71.4
```

Library version: 5.2.1

## Steps To Reproduce

1. Try to generate the release APK of the project.

## Expected behaviour

1. The build should succeed without ant failure.

## Reproducible sample code

https://react-native-community.github.io/upgrade-helper/?from=0.70.0&to=0.71.4#RnDiffApp-android-app-src-main-AndroidManifest.xml
https://react-native-community.github.io/upgrade-helper/?from=0.70.0&to=0.71.4#RnDiffApp-android-app-build.gradle - check namespace

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by Amir-Heydari** [comment]
hi,i have the same problem.any solutions?

**Comment by freeboub** [comment]
This namespace has been removed on 6.0.0-alpha.8.
If the problem still present, should patch file manifest.xml in the repo to remove the namespace
