### ISSUE TITLE
Vimeo protected videos are not playing on a tvOS device 

### ISSUE THREAD

**Issue by soj** [TheWidlarzGroup/react-native-video#3076]
Hi all! 

I am not sure that this is the perfect place to ask, but I don't know where to ask it anymore :) 
Today I tried to play a Vimeo video with the URL like that -  https://player.vimeo.com/external/3254222.m3u8?s=s1s2fd3f3g5 ...dddd333f&oauth2_token_id=123456767 - and it doesn't work for me on the actual AppleTV device but works fine in tvOS Simulator. 

Is this URL supported, or is it a bug or my lousy implementation?

**Comment by freeboub** [comment]
We need more info on the issue...
Which branch do you use ? Do you have more information on the issue (log from xcode) ?
