### ISSUE TITLE
GoogleAds IMA SDK pod dependency

### ISSUE THREAD

**Issue by clairestolp** [TheWidlarzGroup/react-native-video#3079]
### Current behavior
Describe what happens when you encounter this issue.

Installing `react-native-video` v6.0.0.alpha.5 installs `GoogleAds-IMA-iOS-SDK` pods in iOS. 

### Expected behavior
Describe what you wanted to happen

If the the `adTagUrl` is passed a value and they do not have `GoogleAds-IMA-iOS-SDK` installed the player should throw an error that the dependency should be installed to use the prop instead of installing it by default

There are a few reasons why installing this dependency by default could be a problem 
- For users who do not need or want ads in their videos it is installing additional dependencies, making the app bundle size larger. even if it is small, it does increase bundle size which could be important for some organizations
- While I'm not sure how this will work at the present, this could cause problems for Apps in the Apple App Store when they are in review who's rules are configured to assert that they do not serve ads. Especially if reviewers are looking at pod files

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

**Comment by freeboub** [comment]
Hello, by chance, I merge a fix for this yesterday :) I will build a release soon (alpha.6) !

**Comment by clairestolp** [comment]
That is great! Thank you so much! 🙌
