### ISSUE TITLE
Video doesn't play when loaded through asset system,  and triggers error when screen sleeps

### ISSUE THREAD

**Issue by mwiley** [TheWidlarzGroup/react-native-video#308]
I'm using a Samsung Galaxy S6 edge, and the video won't load for me.  When the screen sleeps, I get this an an error: 

```
{ error: { extra: 0, what: -38 } }
```

I also get the same error from this issue: https://github.com/react-native-community/react-native-video/issues/264

It works on iOS for me, with everything else exactly the same. I'm trying to play an mp4 file I converted from mov with ffmpeg.

**Comment by mwiley** [comment]
I uploaded the video to S3 instead of using a local source with the asset system, and now it's working. So the problem seems to be with the asset system on Android.

**Comment by mattapperson** [comment]
@mwiley when you say working, does it continue playing or stop without crashing?

**Comment by mattapperson** [comment]
@mwiley and can you post any sample code to help us reproduce and hopefully help fix this?

**Comment by mwiley** [comment]
@mattapperson Yes, I'll work on some sample code and a video file that I can share that reproduces my issue.

**Comment by mwiley** [comment]
@mattapperson Here's a sample app. It's actually happening for iOS too. It works if the file is included in the build with Xcode though.

https://github.com/mwiley/react-native-video-test-app

EDIT: On iOS, I'm getting an error but it doesn't look the same. The way it acts is the way though. It looks like this:

```
Sep  6 09:25:40 Masons-MacBook-Pro Unknown[33257] <Error>:
Sep  6 09:25:40 Masons-MacBook-Pro assertiond[33257] <Error>: assertion failed: 15G1004 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
```

I can change the path to some file that doesn't exist, and I'll get a crash.

**Comment by mkdotcom** [comment]
Same issue (using 0.9.0), it works fine if the file is on a web server :
source={{uri: "http://aaaaaa.com/video.mp4"}}

Doesn't work with :
source={require("./assets/video.mp4")}

Note:
onLoadStart is called
onError is not

---> i updated reactnative to 0.33.0 and it's now working fine!

**Comment by yogeshj-aloha** [comment]
> I'm using a Samsung Galaxy S6 edge, and the video won't load for me. When the screen sleeps, I get this an an error:
> 
> ```
> { error: { extra: 0, what: -38 } }
> ```
> 
> I also get the same error from this issue: #264
> 
> It works on iOS for me, with everything else exactly the same. I'm trying to play an mp4 file I converted from mov with ffmpeg.

I am also getting the same issue
