### ISSUE TITLE
Video glitches on Motorola Moto G stylus devices

### ISSUE THREAD

**Issue by tharwi** [TheWidlarzGroup/react-native-video#3081]
# Bug

<img width="309" alt="Screenshot 2023-03-31 at 12 27 00" src="https://user-images.githubusercontent.com/108951960/229047007-54c4e635-de06-4d47-821a-ebee9f3bc57f.png">

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 66.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.7 => 0.70.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. Play a video using React Native Video package (video hosted on s3)

## Expected behaviour

1. Video should be playing without any issues

## Reproducible sample code

```
<Video
  muted={muted}
  onEnd={handleOnEnd}
  onLoad={handleOnLoad}
  onLoadStart={handleOnLoadStart}
  onProgress={handleOnProgress}
  paused={!playing}
  playInBackground={false}
  rate={1}
  ref={videoRef}
  repeat={false}
  resizeMode={'contain'}
  source={currentVideoSource}
  style={styles.videoScreenPlayer}
  volume={videoSoundVolume}
/>
```

## Video information

```
Kind: MPEG-4 movie
Dimensions: 640 × 360
Codecs: H.264, AAC
```

**Comment by freeboub** [comment]
Do you have a sample url ?
Which player do you use (exoplayer or mediaplayer) ?
Did you reproduce the issue on V6 version ?

**Comment by tharwi** [comment]
@freeboub  Can I give a sample url by uploading the same video to a dummy project in Firebase storage if it is okay?

I have not explicitly configured the library to use ExoPlayer. 
I just used `yarn add react-native-video` to install the package.

This issue is happening to one of our user devices, which we don't have access to. So cannot tell whether this is reproducible in V6.

**Comment by freeboub** [comment]
Not something we can fix in RNV. let's close this issue.
notice that, it can be an issue with:
- exoplayer (switching to V6 can fix it as it was updated)
- the device -> motorolla issue
- video issue -> encoding issue
