### ISSUE TITLE
video player not playing videos from URL in release apk

### ISSUE THREAD

**Issue by coucoseth** [TheWidlarzGroup/react-native-video#3083]
Which player are you experiencing the problem on:
* Android

React native info output:

```bash
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 28.18 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.1.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. npm i react-native-video
2. import Video from 'react-native-video';
3. <Video source={{uri: "URL"}}   // Can be a URL or a local file.
       ref={(ref) => {
         this.player = ref
       }}                                      // Store reference
       onBuffer={this.onBuffer}                // Callback when remote video is buffering
       onError={this.videoError}               // Callback when video cannot be loaded
       style={styles.backgroundVideo} />
...

## Expected behaviour

1. Expected videos from url's to load and play but it stays loading without end in release build, however it is working fine in development build

**Comment by freeboub** [comment]
Not enough information investigate...
What is the error ? What happen in the logcat ? Did you check the url is https and not http ?

**Comment by coucoseth** [comment]
In development mode, the video plays as expected, there is no error, but in release apk, the video does not play at all, the app stays on loading the video. and the url is https, same url works in development mode but not in release apk. i'm not sure how to get logcat ?

**Comment by efkann** [comment]
> In development mode, the video plays as expected, there is no error, but in release apk, the video does not play at all, the app stays on loading the video. and the url is https, same url works in development mode but not in release apk. i'm not sure how to get logcat ?

Can you also post the source video url you're trying to play ? Did you also reproduce this issue with other reliable sources like Google's demo assets ? If you didn't can you also try these and share the result here ?


https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

**Comment by coucoseth** [comment]
After i was able to view logcat information i realised that production api was sending http and not https url to the video player, It is finally working after i changed url from http to https. thanks for the help.
