### ISSUE TITLE
Stable Release of v6.0.0

### ISSUE THREAD

**Issue by Cowner** [TheWidlarzGroup/react-native-video#3086]
I am using this package in a project and have had an issue raised around a black screen displaying on the Android version of the Application. This is being caused by the ShutterView prop [hideShutterView](https://github.com/react-native-video/react-native-video/blob/master/API.md#hideshutterview) not functioning correctly in version 5.2.1, resulting in a black screen prior to the video loading. I have discovered that this issue has been resolved in version [6.0.0-alpha.5](https://github.com/react-native-video/react-native-video/releases/tag/v6.0.0-alpha.5).

I am interested in knowing when a stable build of version 6.0.0 will be available with the fix in place, as my project avoids the use of alpha/experimental versions of packages. Could you please provide me with an estimate on the timeline for this release?

I'm not sure who I should be contacting for this sort of query, @freeboub would you have any indication on timelines?

Thank you for your assistance in this matter.

**Comment by freeboub** [comment]
Hello,

Unfortunately, I cannot give you any fixed timeline.
I maintain this repo as it was dying and I think it is very important for the community.
I try to backport changes I made in my company fork, but it is a very huge job, but I don't have enough time to fully achieve it.

I try to tag critical issue to go to beta release :
https://github.com/react-native-video/react-native-video/issues?q=is%3Aissue+is%3Aopen+label%3A%22critical+for+release%22

(not so much for now in fact)
 
I know some users already use the 6.0.0 version for production.

Thank you.

**Comment by Cowner** [comment]
Thank you @freeboub for your prompt response. I appreciate the information! 😄
