### ISSUE TITLE
i have a 5 hour audio file how can i play it, it always stops when i play it

### ISSUE THREAD

**Issue by memberwebm** [TheWidlarzGroup/react-native-video#3090]

**Comment by freeboub** [comment]
Ok but why is it stopping? Did you check logcat ?

**Comment by memberwebm** [comment]
i dont know , how to check logcat?

https://user-images.githubusercontent.com/110653846/230292520-670f5784-c522-4856-9f3a-df6d4c44d18f.mov

**Comment by freeboub** [comment]
please don't report issue if you don't follow up
