### ISSUE TITLE
RCTVideo is not fabric compatible yet.

### ISSUE THREAD

**Issue by Hidayat017** [TheWidlarzGroup/react-native-video#3094]
# Bug

## Platform
* Android
## Environment info

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 77.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Library version: 6.0.0-alpha.6

RCTVideo is not fabric compatible yet

**Comment by freeboub** [comment]
duplicate of: https://github.com/react-native-video/react-native-video/issues/2650

**Comment by shubhamkr5557** [comment]
solution?

**Comment by KrzysztofMoch** [comment]
You can use Interop Layer (https://github.com/reactwg/react-native-new-architecture/discussions/135) which was introduced in react-native 0.72

for more information checkout this discussion https://github.com/react-native-video/react-native-video/issues/2650#issuecomment-1936034853
