### ISSUE TITLE
Bug when use audio m4a, duration be duplicate

### ISSUE THREAD

**Issue by memberwebm** [TheWidlarzGroup/react-native-video#3095]
<Video
              automaticallyWaitsToMinimizeStalling={false}
              source={{
                uri: url,
              }}
              onBuffer={onBuffer}
              playInBackground={true}
              ref={ref => (player = ref)}
              muted={mute}
              controls={false}
              paused={paused}
              repeat={repeat}
              audioOnly={!isEnabledModeVideo ? true : false}
              posterResizeMode={'cover'}
              poster={thumbnail}
              onEnd={onEndAudio}
              onLoad={e => {
                handleLoad(e);
              }}
              onLoadStart={onLoadStart}
              onProgress={e => {
                processTime(e);
              }}
              resizeMode={'contain'}
              style={[
                state.fullscreen ? styles.fullscreenVideo : styles.video,
                {
                  aspectRatio: !stateScreen.fullscreen ? 16 / 9 : 1280 / 720,
                },
              ]}
            />
real time: 3:04<img width="471" alt="Screenshot 2023-04-13 at 11 18 38" src="https://user-images.githubusercontent.com/110653846/231651912-9bb56cc6-6e44-4d69-b197-f2a0e88608d1.png">

time when react native video runs: 6:09, it be duplicate <img width="508" alt="Screenshot 2023-04-13 at 11 17 37" src="https://user-images.githubusercontent.com/110653846/231651767-f6b163e7-786b-4376-b8fb-1893ca125e16.png">

**Comment by freeboub** [comment]
missing info in description
- version of RNV
- environment (ios / android ?)
- sample m4a file...
