### ISSUE TITLE
Playback not resumed after call ends

### ISSUE THREAD

**Issue by tomscheney** [TheWidlarzGroup/react-native-video#3099]
# Feature Request

### Code sample

<!--
  
 [[NSNotificationCenter defaultCenter] addObserver:self
                                               selector:@selector(audioSessionWasInterrupted:)
                                                   name:AVAudioSessionInterruptionNotification
                                                 object:nil];

- (void)audioSessionWasInterrupted:(NSNotification *)notification
{
    NSLog(@"%s: %@", __func__, notification);
    if (AVAudioSessionInterruptionTypeBegan == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        // 暂停
//        [self setPaused:YES];
    }
    else if(AVAudioSessionInterruptionTypeEnded == [notification.userInfo[AVAudioSessionInterruptionTypeKey] intValue])
    {
        // 恢复
        [self setPaused:_paused];

    }
}

**Comment by freeboub** [comment]
No version no platform. A ticket is not just a title ...
