### ISSUE TITLE
Add playWhileMuted property

### ISSUE THREAD

**Issue by mattapperson** [TheWidlarzGroup/react-native-video#310]
On iOS there are multiple AVAudioSessionCategory options for audio when playing a video. 
We only really need to care about 2 of them, so we don't need to fully expose the API.

Issue: 
Currently if the sound toggle switch is muted, the videos audio is muted.

Requested feature:
set `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];` if `playWhileMuted` prop is set to true. default should be false.

**Comment by mattapperson** [comment]
Note about this ticket added to readme

**Comment by anshul-kai** [comment]
The suggestion to add `  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];` at the bottom of `didFinishLaunchingWithOptions` no longer seems to be working. Any ideas?

**Comment by zyonnetworks** [comment]
+1

**Comment by larryranches** [comment]
Any momentum on this feature?

**Comment by mattapperson** [comment]
A PR was made here but needs work https://github.com/react-native-community/react-native-video/pull/403

**Comment by GeoffreyPlitt** [comment]
My company has created a $200 bounty for this issue. https://www.bountysource.com/issues/37409911-add-playwhilemuted-property

**Comment by duhseekoh** [comment]
This ticket should be closed, given the merge of #403 .
