### ISSUE TITLE
HDR Support

### ISSUE THREAD

**Issue by GustavPS** [TheWidlarzGroup/react-native-video#3102]
Hi!

Does this support HDR/HDR10/HDR10+ playback? I'm currently trying to play a HDR x265 video, but my TV (using a Nvidia Shield) does not recognize it as HDR content.

In the logs I can see this:
```
04-19 23:26:12.412  3570  6432 D NvOsDebugPrintf: WARNING! HDRStatic info being set, even for non SMPTE 2084 case
04-19 23:26:12.412  3570  6432 D NvOsDebugPrintf: WARNING! This media may play as non HDR
```

**Comment by GustavPS** [comment]
Managed to answer this myself. It does support HDR. I had to set 
`useTextureView={false}` to make it use a surfaceView, which recognizes it as HDR content. Might be worth updating the documentation :)

**Comment by freeboub** [comment]
Thank you for the follow up ! This is (or should be) part of exoplayer documentation, i don't think it makes sense to clone it here ...
