### ISSUE TITLE
IMA workflow

### ISSUE THREAD

**Issue by NazarKuryl0** [TheWidlarzGroup/react-native-video#3103]
## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:
   

```bash
  "react": "18.2.0",
  "react-native": "0.71.7",
  "react-native-video": "^6.0.0-alpha.6"
```

Library version: 6.0.0-alpha.6

## Steps To Reproduce

1. Init RN app
2. Add react-native-video package

## Reproducible sample code

```bash
 <Video
        source={{uri: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8'}}
        adTagUrl={'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='}
        style={{width: '100%', height: 300}}
        controls={true}
        />
```

# Expected behaviour
As I see in lib - there is Google IMA implementation, but adTagUrl prop doesn't work. Am I missing some additional steps? URLs for IMA was getting here https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

**Comment by jonathankiefer** [comment]
I'm having the same issue of not seeing any ads (or ad events) after adding the "adTagUrl" prop to the Video tag and adding "$RNVideoUseGoogleIMA = true" to both my iOS target and tvOS targets in the Podfile, as well as, "RNVUseExoplayerIMA = true" to my build.gradle.

On a related note, but not specific to this project or under the control of this project, the Typescript type definition available for react-native-video doesn't have an "adTagUrl" prop in its "VideoProperties" interface:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-video/index.d.ts

Edit: 
I found the solution. I had to upgrade from the latest release (5.2.1) to the alpha release (6.0.0).

**Comment by freeboub** [comment]
Thank you @jonathankiefer !
@NazarKuryl0 did you enable it in gradle and podfile ? Are you using the V6 version?

I think there is missing info for ios in readme. I will double check

**Comment by NazarKuryl0** [comment]
how i should enable it in gradle and podfile? what changes should be done?

**Comment by NazarKuryl0** [comment]
i missed that
with "$RNVideoUseGoogleIMA = true" ads playing, but just with controls={true}, is that requiered? and could ads play with controls={false}? 

Also when press on Learn More on ads we navigate to browser and when go back - ads stop and we could do nothing with them and playback

**Comment by freeboub** [comment]
@NazarKuryl0 yes ads can be played without controls !

**Comment by NazarKuryl0** [comment]
@freeboub  but with controls={false} ads didn't play, see just black screen. Tested on device and emulator

**Comment by freeboub** [comment]
@NazarKuryl0 ok... Do you have the issue on both android and ios ? I recently tested on Android without issue 🤔

**Comment by jonathankiefer** [comment]
I'm able to play ads with controls={false} on iOS, tvOS, Android and Android TV.

**Comment by freeboub** [comment]
Ok @NazarKuryl0 @jonathankiefer I think I caN close this issue then. 

Just a small request, can you create a PR to fix Apple TV build ? I think some people are struggling with this.

Thank you!

**Comment by NazarKuryl0** [comment]
@freeboub its just on iOS

**Comment by YoungYanchi** [comment]
> I'm having the same issue of not seeing any ads (or ad events) after adding the "adTagUrl" prop to the Video tag and adding "$RNVideoUseGoogleIMA = true" to both my iOS target and tvOS targets in the Podfile, as well as, "RNVUseExoplayerIMA = true" to my build.gradle.
> 
> On a related note, but not specific to this project or under the control of this project, the Typescript type definition available for react-native-video doesn't have an "adTagUrl" prop in its "VideoProperties" interface: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-video/index.d.ts
> 
> Edit: I found the solution. I had to upgrade from the latest release (5.2.1) to the alpha release (6.0.0).

Hi, could you share the configuration under the file? And detail the steps if not difficult. I am facing the same problem in v6. There is not even a hint of event processing. I added a line to the podfile, added a test ad tag from google. Do I need to install additional packages for IMA? I would be grateful for any information!
