### ISSUE TITLE
Not show video image of .m3u8 when update to iOS 16.4

### ISSUE THREAD

**Issue by Girum** [TheWidlarzGroup/react-native-video#3107]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android
* Windows UWP
* Windows WPF

## Environment info

React native info output:

```bash
None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
     |                                   ^
  18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
  19 | import typeof FlatList from './Libraries/Lists/FlatList';
  20 | import typeof Image from './Libraries/Image/Image';
```

Library version: 5.1.1

After update to iOS 16.4, I cannot build with the CLI. I have to build with Xcode, in device Rosetta mode (like Iphone 14 (Rosetta). When I go trought the app, I receive variou messagens like the bash, with problemas with DatePiCkerIOS, etc.

When I go to the video screen, if the video is mp4, for example, it goes ok. But when the video is .m3u8, the video not apperas (oly audio).

Anyone with his problem?

**Comment by Girum** [comment]
> # Bug
> ## Platform
> Which player are you experiencing the problem on:
> 
> * iOS
> * Android
> * Windows UWP
> * Windows WPF
> 
> ## Environment info
> React native info output:
> 
> ```shell
> None of these files exist:
>   * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
>   * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx|.native.svg|.svg)
>   15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
>   16 | import typeof Button from './Libraries/Components/Button';
> > 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
>      |                                   ^
>   18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
>   19 | import typeof FlatList from './Libraries/Lists/FlatList';
>   20 | import typeof Image from './Libraries/Image/Image';
> ```
> 
> Library version: 5.1.1
> 
> After update to iOS 16.4, I cannot build with the CLI. I have to build with Xcode, in device Rosetta mode (like Iphone 14 (Rosetta). When I go trought the app, I receive variou messagens like the bash, with problemas with DatePiCkerIOS, etc.
> 
> When I go to the video screen, if the video is mp4, for example, it goes ok. But when the video is .m3u8, the video not apperas (oly audio).
> 
> Anyone with his problem?

Aparentelly it occurs in simulators. When install in physical devices, it goes ok ...

**Comment by poojasolanki9569** [comment]
facing the same issue, can someone help?

**Comment by c4sio** [comment]
Same for me..
<img width="534" alt="Screenshot 2023-04-25 at 15 04 45" src="https://user-images.githubusercontent.com/5386625/234377549-ac6e498f-2242-45db-98e6-75e908f4c75e.png">

source={{
          uri: 'http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8',
          type: 'm3u8' }
        }

**Comment by justintoth** [comment]
Same issue here when loading a m3u8 file in the video player, only since upgrading to iOS 16.4.

<img width="448" alt="Screenshot 2023-04-25 at 10 02 38 PM" src="https://user-images.githubusercontent.com/1443831/234447171-8457ad81-c4ce-4b77-9d60-1bfec430959f.png">

**Comment by freeboub** [comment]
Did anyone test on V6 version?

**Comment by justintoth** [comment]
@freeboub Yes I'm on 6.0.0-alpha.6 and the issue exists.

**Comment by Lakston** [comment]
Confirming this on ios simulator v16.4, and it works on a real device (alpha6)

**Comment by justintoth** [comment]
Same here, I should have mentioned that it only occurs for me on iOS simulator as well, a physical iOS device works fine.

**Comment by daveslutzkin** [comment]
Happening here too on both versions 5 and 6 alpha, m3u8s only.

The DatePickerIOS noise in the original post is an unrelated react-native issue https://github.com/facebook/react-native/issues/36794.

**Comment by daveslutzkin** [comment]
Audio works but video doesn't display. Nothing in the logs, error callbacks not called. If I step through the swift code then it reaches the end and calls `handlePlayerItemDidReachEnd` successfully.

I'm not familiar enough with the code to understand the specifics of what's going on with AVPlayer here unfortunately.

**Comment by resonancce** [comment]
I also have such a problem

**Comment by alexbudin** [comment]
Same problem.

**Comment by alexbudin** [comment]
Audio is playing, everything seems to be working fine, but video is not showing. there are no errors. Seems to be working on a real device, but not on the simulator.

**Comment by alexhernandez** [comment]
I had the same video playback issue on latest v16.4 iOS simulator.

Temp fix was to install old simulators from v16 via XCode Preferences > Platforms Tab (formerly Components Tab)

**Comment by gramosukaj** [comment]
I confirm than I had the same issue: 
- Black video but audio working
- Appears only on the simulator (currently on iOS 16.4)

Building the app on physical device seems to be OK!

**Comment by freeboub** [comment]
Issue with simulator. Let's close this issue

**Comment by michaelknoch** [comment]
@freeboub the issue still exists. I understand that it has lower priority if it _only_ occurs in simulators and not on real devices, but this developer experience is far away from being great. AFAIK there is no general problem with AVPlayer on iOS 16.4, so I'm guessing this bug is related to react-native-video. I kindly ask to open the ticket again.

**Comment by nugmanoff** [comment]
@michaelknoch I think based on this thread https://forums.developer.apple.com/forums/thread/727288?page=2 it can clearly be stated that was some system bug on Apple's side. Which is now fixed in latest Xcode/Simulator versions.

cc @freeboub

**Comment by michaelknoch** [comment]
I can confirm it's working again on the latest xcode version @nugmanoff
