### ISSUE TITLE
Android: `OnProgress` fires with incorrect currentTime value on React Native 0.71.4 and above

### ISSUE THREAD

**Issue by samitha9125** [TheWidlarzGroup/react-native-video#3108]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 100.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.5 - ~/Documents/Projects/Sample/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. Setup a fresh React Native project with `npx react-native init sample --version 0.71.4`
2. install `react-native-video` `yarn add react-native-video && nox pod-install`
3. Import the module and run the below snippet.

```js
import Video from 'react-native-video';

 <Video
    ref={videoRef}
    source={{
       uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
    }} // Can be a URL or a local file.
   onProgress={console.log}
 />
```
...

## Expected behaviour

1. currentTime value should be incrementing when the video plays.
2. videoRef.current.seek(0) does not work.

## Expected behaviour

1. currentTime is reported as 0 or 0.16 continuously. But the video plays without any issue.
2. videoRef.current.seek(0) should seek to the beginning of the video.

## Reproducible sample code

```js
import Video from 'react-native-video';

 <Video
    ref={videoRef}
    source={{
       uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
    }} // Can be a URL or a local file.
   onProgress={console.log}
 />
```

**Comment by freeboub** [comment]
Is it reproduced with V6 ?

**Comment by neha-1012** [comment]
Getting same issue. Any solution for this? @samitha9125

**Comment by samitha9125** [comment]
@neha-1012 Actually this was an issue with my emulator (Might be a caching issue or something else). Each version results in the same output and resetting the emulator made this work.

**Comment by neha-1012** [comment]
Thank you @samitha9125 for the answer but getting this issue in android physical device. 
And @freeboub i have tried with V6, still getting same issue.

**Comment by mohamed2m2018** [comment]
still having the same issue
