### ISSUE TITLE
SubtitleStyle Doesn't Work Android

### ISSUE THREAD

**Issue by Erenner** [TheWidlarzGroup/react-native-video#3112]
# Bug

## Platform
* Android

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Stop opening issue with out description
