### ISSUE TITLE
RCTVideo is not Fabric compatible yet

### ISSUE THREAD

**Issue by 1ZvEzD1K1** [TheWidlarzGroup/react-native-video#3116]
# Bug
I use  "react-native-video": "^5.2.1", "@types/react-native-video": "^5.0.14",  "react-native": "0.71.4"

the component has the following structure
```
import Video from 'react-native-video';

<View style={globalStyles.container} {...panResponder.panHandlers}>
    <Video
            source={{
              uri: testlink,
            }}
            style={{width: '100%', height: 150}}
            resizeMode="contain"
            controls={true}
    />
</View>
```
but I get the error "RCTVideo is not Fabric compatible yet"
and in the description it is indicated that this version of the library and react native support fabric
![зображення_2023-05-03_140958851](https://user-images.githubusercontent.com/66206894/235900052-70ab9f4c-904f-4cd1-9494-3634f1133a80.png)

**Help solve the problem**

**Comment by antoadam** [comment]
You can turn off the new architecture in the file `/android/gradle.properties` by setting the `newArchEnabled` property to false.

**Comment by ucheNkadiCode** [comment]
same issue! It would be great if we didn't have to disable fabric just to get it to work. Fabric really helps with the performance of my app

**Comment by jiyong1** [comment]
could you please take a look at this [PR](https://github.com/react-native-video/react-native-video/pull/3122)

**Comment by freeboub** [comment]
shoudl be followed in: https://github.com/react-native-video/react-native-video/issues/2650

**Comment by jessiemblack** [comment]
Having this issue still with RN 0.72.6
