### ISSUE TITLE
(0 , _reactNative.requireNativeComponent) is not a function error while using react-native-video

### ISSUE THREAD

**Issue by ishkash69** [TheWidlarzGroup/react-native-video#3117]
i am getting the error:(0 , _reactNative.requireNativeComponent) is not a function while trying to use this package

My code is:

import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Video from "react-native-video";

function App() {
  return (
    <View style={styles.app}>
      <Video
        source={{
          uri:
            "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
        }}
        // ref={ref}
        // style={{ height: 95, width: 95 }}
        // resizeMode="cover"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  app: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center"
  }
});

export default App;

**Comment by BasixKOR** [comment]
_reactNative.requireNativeComponent is a RN component and if it isn't defined it indicates a configuration error on your end.

**Comment by freeboub** [comment]
Not enough info to progress. Let us know if you need more support!

**Comment by Deepika1024** [comment]
But when I install "npx pod-install" it shows CocoaPods is only supported on darwin machines

**Comment by freeboub** [comment]
should be "cd ios && pod install"

**Comment by Ramon-Balaguer** [comment]
I have the same problem with web :s 
![image](https://github.com/user-attachments/assets/2e9d70c3-b1bf-45a0-86d7-6ae4a8d86510)

**Comment by freeboub** [comment]
> I have the same problem with web :s 
> ![image](https://github.com/user-attachments/assets/2e9d70c3-b1bf-45a0-86d7-6ae4a8d86510)
> 

Web is currently not supported, but there is an open pr to support it

**Comment by LarryKarani** [comment]
> I have the same problem with web :s ![image](https://private-user-images.githubusercontent.com/11381646/350910444-2e9d70c3-b1bf-45a0-86d7-6ae4a8d86510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODc1NTgsIm5iZiI6MTcyNzc4NzI1OCwicGF0aCI6Ii8xMTM4MTY0Ni8zNTA5MTA0NDQtMmU5ZDcwYzMtYjFiZi00NWEwLTg2ZDctNmFlNGE4ZDg2NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDEyNTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMDRiOTVlYmI4N2RhZjBjODZlMDcxMTgyNDRhZGU3MWZmYjA0MWFjOWUzYzI4ZDkxOTg2OWY4ZWU2ZDkzNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dmxt8Wwj5AmhAyLBoxE3CbdLS1u3wvD0kDbwpRig2_o)

How did you fix this on web? I'm having a similar error when I try using  "react-native-skeleton-placeholder"

**Comment by mrgonzales-dev** [comment]
anybody found a solution to this?
cant import a video using react-native-video: 

Static Rendering Error (Node.js)
(0 , react_native_1.requireNativeComponent) is not a function
Call Stack
factory
node_modules/react-native-video/lib/Video.js
loadModuleImplementation
node_modules/metro-runtime/src/polyfills/require.js
guardedLoadModule
node_modules/metro-runtime/src/polyfills/require.js
metroRequire
node_modules/metro-runtime/src/polyfills/require.js
factory
assets/wrapper/VideoPlayer.tsx
loadModuleImplementation
node_modules/metro-runtime/src/polyfills/require.js
guardedLoadModule
node_modules/metro-runtime/src/polyfills/require.js
metroRequire
node_modules/metro-runtime/src/polyfills/require.js
factory
screens/videoScreens.tsx
loadModuleImplementation
node_modules/metro-runtime/src/polyfills/require.js
Collapse all 10 frames
