### ISSUE TITLE
Playing backwards (rate = -1) very sluggish

### ISSUE THREAD

**Issue by canpoyrazoglu** [TheWidlarzGroup/react-native-video#3118]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.28 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.6

## Steps To Reproduce

1. Observe 30FPS video playing smoothly at normal (1x) forward speed
2. Have the video seek anywhere (as we can't play backwards from beginning)
3. Set rate to -1
4. Observe video playing backwards. It plays backwards very sluggish (e.g. around ~8 FPS)
...

## Expected behaviour

1. Video should play backwards just as it plays forward, at 30 FPS.

## Reproducible sample code

This code plays the video normally, and when it finishes, pauses, seeks to some point, sets the rate, and unpauses (as otherwise it won't trigger playing again and stay finished for some reason). It _does_ start playing backwards but unacceptably sluggish. 

```
    const ref = useRef<Video>(null);
    const [rate, setRate] = useState(1);
    const [paused, setPaused] = useState(false);
    const onEnd = () => {
        setPaused(true);
    };
    useEffect(() => {
        if(paused){
            ref.current?.seek(5)
            setRate(-1);
        }
    }, [paused]);
    useEffect(() => {
        if(rate < 0){
            setPaused(false);
        }        
    }, [rate]);
    return (
        <Video
            source={path to my local video with require(...)}
            resizeMode="cover"
            muted
            paused={paused}
            rate={rate}
            onEnd={onEnd}
            ref={ref} // Store reference
            style={StyleSheet.absoluteFillObject}
        />
    );
```

## Observations

I've also tried setting different negative playback rates like -2. It plays much more smoother at -2x which is weird because I'd expect it to consume more resources at -2x compared to -1x but -2x is, while still not 30FPS, considerably smoother.

**Comment by freeboub** [comment]
As explained in various article, having a playing backward is not something expected.
The feature has been removed from exoplayer (and then from this repo on android).
This is definitivelly something we cannot fix in react native video.
This should be reproduced on an ios sample and investigate by apple directly.
