### ISSUE TITLE
Picture not showing in video

### ISSUE THREAD

**Issue by uc-asa** [TheWidlarzGroup/react-native-video#312]
Hello team

I'm using react-native-video library for playing video but in android only run audio picture are not showing what can I do

**Comment by mattapperson** [comment]
This can be a common issue with an improperly converted video. Can you confirm that your video plays correctly when just run in the android (not chrome) web browser? If not its an issue with the video

**Comment by BranoMatan** [comment]
Is your problem is that the video object is only playing sound?
I had this problem, and adding width and height properties to the video object style rules solved this for me.

**Comment by cobarx** [comment]
Chances are you're missing the width and height.
