### ISSUE TITLE
Fabric not supported on latest RN Video (react-native-video 6.0.0-alpha.6)

### ISSUE THREAD

**Issue by ucheNkadiCode** [TheWidlarzGroup/react-native-video#3120]
Hello! I love this react-native-video package! Right now I'm aiming to use React Native Fabric but I see that even the latest alpha-6 doesn't support Fabric. I'm on React Version 0.71.7 which has made enabling Fabric much easier. Understandably, this is a super complex package. Fabric has made my app so much faster. So it would be great if this package adopted it. 

So it looks like this on Android and iOS

react-native-video": "^6.0.0-alpha.6"

<img width="312" alt="Screenshot 2023-05-06 at 8 43 57 PM" src="https://user-images.githubusercontent.com/20650058/236656511-9d641781-0101-45af-a9c1-8044576a1272.png">

Are there plans to support Fabric in this package? There isn't really another "non-expo" option and It's such a major help to the React Native community

**Comment by mczernek** [comment]
I'd also love to know the plans here. I think I should be able to help with that if any help is needed :)

**Comment by jiyong1** [comment]
could you please take a look at this [PR](https://github.com/react-native-video/react-native-video/pull/3122)

**Comment by freeboub** [comment]
should be followed in: https://github.com/react-native-video/react-native-video/issues/2650
