### ISSUE TITLE
maxbitrate is not working and unable to restrict resolution based on bitrate

### ISSUE THREAD

**Issue by chaitanya71998** [TheWidlarzGroup/react-native-video#3121]
# Bug
I am using Adaptive streaming to play videos. I am giving a DASH link for my android react native app. For the video url, there were multiple bit rates in the manifest. i want to restrict streaming to max 720p, in my video manifest file the bitrate for 720p is 2mb.
so i have given maxBitrate to 2000000, the video player is not considering it and stil continuing playing in highest available quality. 
For working with adaptiveStreaming, i am using exo player config like mentioned in this comment https://github.com/react-native-video/react-native-video/issues/2461#issuecomment-904399554
## Platform
Android

Which player are you experiencing the problem on:
* Android
* ios(not checked yet)

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.31 GB / 15.04 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_362 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Expected behaviour

1. when giving maxbitrate the player should not fetch for higher quality bitreate videos

How can i restrict streaming more than specfic resoultion

**Comment by freeboub** [comment]
detailed explanation provided in the ticket. Sorry for the long time to handle this ticket ...
