### ISSUE TITLE
[IOS][6.0.0-alpha.6] TextTrack not loading and muting the video when I use .vtt url with queryParams

### ISSUE THREAD

**Issue by santiagogarzon** [TheWidlarzGroup/react-native-video#3125]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 106.67 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.8 => 0.70.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.6

## Steps To Reproduce

1. Add textTracks in my video implementation 
2. Run it on IOS

...

## Expected behaviour

1. Video played and sound is on(It's not in silent mode)
2. Subtitles are displayed

## Reproducible sample code

							<Video
								source={{ uri: "videoUrl" }}
								style={styles.videoPlayer}
								controls={true}
								textTracks={[
									{
										title: "English CC",
										language: "en",
										type: TextTrackType.VTT,
										uri: "captionUrl", //THIS URL HAS SOME QUERY PARAMS INTO IT IN ORDER TO ACCESS TO THE FILE
									},
								]}
								selectedTextTrack={{ type: "language", value: "en" }}
								ignoreSilentSwitch="ignore"
							/>

## .VTT example
[example](https://bcbolt446c5271-a.akamaihd.net/media/v1/text/vtt/clear/1510329453001/5dc7a3d1-5052-4487-925b-caaae980d0a0/d68b7464-6c19-4d0c-932b-b6cab67576c0/text.vtt?akamai_token=exp=1684272829~acl=/media/v1/text/vtt/clear/1510329453001/5dc7a3d1-5052-4487-925b-caaae980d0a0/d68b7464-6c19-4d0c-932b-b6cab67576c0/text.vtt*~hmac=c0d546eac70fa21a4812b0c781a6fae2a3d1dbe9ac5359fbdbb49e3a6e7f460)

**Comment by freeboub** [comment]
This issue seems to be a duplicated of: https://github.com/react-native-video/react-native-video/issues/3642
I tested on sample vtt uri with query parameter works fine in the sample.
The issue you describe seems to be linked to m3u url (we cannot add external subtitle tracks with that format)

See following PR for the ongoing fix: https://github.com/react-native-video/react-native-video/pull/3690

Let me know I need to reopen the issue
