### ISSUE TITLE
High resolution video not playing on certain Android devices

### ISSUE THREAD

**Issue by rmyr** [TheWidlarzGroup/react-native-video#3126]
# Bug

On certain devices (e.g. Xiaomi-Redmi-Smartphone-128GB-2201117SY), the video is not being played back when the resolution is high. A 720p video with aspect ratio 21:9 is being played back, a 1080p video with the same aspect ratio is not. Both work fine on stock Android.

I think the problem might be with the widescreen resolution, as other videos in 1080p work.
Edit: I tried a widescreen with 900p, that works, so I guess its really just the high pixel count or something?

In Logcat I can see the following errors, but the library itself doesn't report any error (just nothing happens):

2023-05-20 15:24:09.667  8059-8079  MediaPlayerNative  E  error (1, -2147479547)
2023-05-20 15:24:09.671  8059-8079  MediaPlayerNative  E  error (1, -38)

## Platform
* Android

## Environment info

React Native Video: 5.2.1 (also tested with the latest alpha, same issue)

React native info output:

System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 39.97 GB / 62.73 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
  npmGlobalPackages:
    *react-native*: Not Found

## Player configuration

```
<Video
    paused={false}
    style={{position: "absolute", width: "100%", height: "100%", left: 0, top: 0, zIndex: 20, backgroundColor: "transparent"}}
    source={{uri: videoPath}}
    onError={(e) => setVideoError(e.error.errorString)}
    resizeMode={props.resizeMode || "cover"}
    progressUpdateInterval={1000}
    repeat={true}
    muted={true}
    controls={false} // Disable controls in fullscreen.
    disableFocus={true} // Allow other audio from apps in the background to play.
    playInBackground={false}
/>
```

## Video sample
https://drive.google.com/drive/folders/1HIn3Evrq3Sz9Lnz3eiGOR8IX20PcNZHY?usp=sharing

**Comment by ferasabufares** [comment]
hello @rmyr  
i have the same problem did you fix this

**Comment by rmyr** [comment]
Hey, not really. Had to downscale all my videos to 900p.

**Comment by davidboerger99** [comment]
Are there any news regarding this problem?

**Comment by rmyr** [comment]
After downscaling the videos (which fixed it on some devices), we are still getting reports (aka bad reviews) from users with Samsung Galaxy A02s experiencing the same problem. This is a pretty major issue, as videos are an integral part of our app. I hope someone from the maintainers will look into this soon.

**Comment by vaibhavgadekar** [comment]
I also have the same issue but in my case video was encoded in h.265 which is the latest video codec format unfortunately most of the devices not supported this file type yet, But videos which are encoded in h.264 is working fine on all device. Please check your video format once.

**Comment by rmyr** [comment]
Thanks for the suggestion, unfortunately in my case the videos are H.264

**Comment by rmyr** [comment]
Hey, anything on this? We keep getting 1 star reviews because of this issue. Videos are not playing on certain devices still, despite already having lowered the resolution.

**Comment by davidboerger99** [comment]
@rmyr It's a Problem with ffmpeg not react-native-video. I Would recommend to use the Google Cloud Transcoder API. It's faster and more reliable

**Comment by freeboub** [comment]
A complementary test you can do is to try a playback with an exoplayer standone.
If they don't play, you need either to transcode the video or use another player (I am thinking of vlc)

**Comment by freeboub** [comment]
I don't think this issue can be fixed in react native video, this is a end to end integration issue.
Let's close this ticket
