### ISSUE TITLE
react-native-video for m3u8 going blank only voice playing

### ISSUE THREAD

**Issue by githubvisiontrek** [TheWidlarzGroup/react-native-video#3128]
i cannot see video playing in react-native-video
Only voice playing but cant see any audio please help in ios only android its working dine

**Comment by VaibhavValere** [comment]
Faced the same issue on ios simulator(16.4) but works fine on ios device

**Comment by alexhernandez** [comment]
Had the same issue. Seems to be OS related. Workaround posted here:

https://github.com/react-native-video/react-native-video/issues/3107#issuecomment-1566472863

**Comment by avencat** [comment]
Yes, this is an [iOS simulator issue](https://developer.apple.com/forums/thread/727677), you should be ok running on physical devices ! 😉
