### ISSUE TITLE
Cookies not getting added to request

### ISSUE THREAD

**Issue by benmoose** [TheWidlarzGroup/react-native-video#313]
We have to send authentication cookies with our video URI request. I am confident that the cookies have been successfully set in react, but the cookies don't appear to be sending with the request.

Any ideas?

**Comment by djw27** [comment]
Note we're seeing this in iOS. Cookies seem to be working as expected with Android (#211 to see implementation)

**Comment by mattapperson** [comment]
Can you post some code showing what you are doing?

**Comment by djw27** [comment]
#345 should fix this!

**Comment by harrydema** [comment]
@benmoose Can you show some code of how you implemented the cookies on Android and IOS?

**Comment by djw27** [comment]
@harrydema we use a separate cookie manager package, e.g. https://github.com/joeferraro/react-native-cookies

As long the domain of the cookie matches the domain of your video URL, `react-native-video` will automatically add cookies to the request.

You can see here how iOS uses a shared cookie storage, and this storage is used  as the source of cookies by `react-native-video` https://github.com/react-native-community/react-native-video/blob/master/ios/Video/RCTVideo.m#L500
