### ISSUE TITLE
Unable to achieve background playback and picture in picture

### ISSUE THREAD

**Issue by CongHaipeng** [TheWidlarzGroup/react-native-video#3131]
# Bug

## Platform

* iOS

## Environment info

Library version:

"react": "18.1.0",
 "react-native": "0.70.6",
 "react-native-video": "^5.2.1"

## Steps To Reproduce

**- When creating the<Video>component, set pictureInPicture to true, run the program without any response, click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented
- When creating the<Video>component, set pictureInPicture to false, add onPress click, and when clicked, switch pictureInPicture to true, but there is still no response. Click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented
- When creating the<Video>component, set playInBackground to true, run the program without any response, click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented**

## Reproducible sample code

`const [isPictureInPicture, setIsPictureInPicture] = `useState(false)``

```
onPress={()=>{
    
         setIsPictureInPicture(true)
     
      }}
```

```
<Video
          style={{flex:1}}
          posterResizeMode='cover'
          resizeMode='cover'
          bufferConfig={{
            minBufferMs: 1000*60,
            bufferForPlaybackMs: 1000*60,
            bufferForPlaybackAfterRebufferMs: 1000*60,
          }}
          ref={videoRef}
          source={playlistSelectedVideo?{uri:playlistSelectedVideo.url}:source}
          paused={isPaused}
          pictureInPicture={isPictureInPicture}
          // 在适当的时机添加事件监听
          onPictureInPictureStatusChanged={handlePictureInPictureStatusChanged1}
          muted={isMuted}
          rate={videoRate}
          selectedVideoTrack={{
            type:'resolution',
            value: videoQuality
          }}
          volume={videoSound}
          playInBackground={playInBackground}
          onLoad={videoData=>{
            if (videoRef.current) {
              videoRef.current.seek(15); // 跳转到指定的时间（以秒为单位）
              // videoRef.current.play(); // 开始播放
              setIsPaused(false);
            }
            setVideoDuration(videoData.duration)
            setIsVErrorInLoadVideo(false)
          }}
          onProgress={videoData=>{
            setCurrentVideoDuration(videoData.currentTime)
            currentprogressblock(videoData.currentTime)

          }}
          /*onSeek={()=>{
            if(Platform.OS=='android'){
              setIsVideoSeeked(true)
            }
          }}
          onReadyForDisplay={()=>{
            console.log("onReadyForDisplay")
            setIsVideoSeeked(false)
            setIsVErrorInLoadVideo(false)
          }}*/
          onError={(videoData)=>setIsVErrorInLoadVideo(true)}
          onEnd={()=>{
            console.log("on end")
            setIsVideoEnd(true)
            setIsPaused(true)
            if(playList.length>0){
              setIsShowVideoPlaylist(true)
            }
          }}
          />

```
```
 const handlePictureInPictureStatusChanged1 = (event) => {
    const { isActive } = event;

    setIsPictureInPicture(isActive);

    if (isActive) {
      // 画中画激活状态
      // 在这里执行你的自定义逻辑
    } else {
      // 画中画非激活状态
      // 在这里执行你的自定义逻辑
    }
  };

```

**Comment by CongHaipeng** [comment]
- When creating the<Video>component, set pictureInPicture to true, run the program without any response, click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented
- When creating the<Video>component, set pictureInPicture to false, add onPress click, and when clicked, switch pictureInPicture to true, but there is still no response. Click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented
- When creating the<Video>component, set playInBackground to true, run the program without any response, click home (slide up) to return to the desktop, playback stops, and picture in picture is not implemented

**Comment by freeboub** [comment]
will be fixed in 6.0.0-alpha.8

**Comment by talal-tilted** [comment]
hello @freeboub is this fixed ? I am using the 6.0.0-alpha.8 and still not working. Thanks a lot for your work by the way !

**Comment by guihendias** [comment]
Yeah, same for me. It's not showing PiP and the video is paused when the app goes to the background.

I'm setting pictureInPicture, playInBackground, and playWhenInactive as true.

**Comment by Duell10111** [comment]
Bump, It still not working for me on the latest version.
Does anyone have a working example?
