### ISSUE TITLE
Support for swapping Auth header tokens while streaming HLS (.m3u8) without stoping or restarting video.

### ISSUE THREAD

**Issue by alexhernandez** [TheWidlarzGroup/react-native-video#3132]
# Feature Request
Hi All 🤙,

First and foremost I enjoy your package and all the work you've done. 🔥🔥🔥

I would like to see if support for swapping Auth header tokens while streaming .m3u8 could be added without stoping or restarting a video.

(Also, if this already has a solution could someone point me to it?)

## Why it is needed
Currently, if you're streaming an HLS video chances are your Auth headers may expire mid stream. If you try to update the headers it causes your video to stop and restart from the beginning.

My guess is updating the `source` prop is also accidentally updating the `source.uri` which causes a re-render resulting in a restart of the video component which isn't an ideal viewing experience.

## Possible implementation
A possible solution could be to do a comparison of the previous and new values inside source so only those value update.

**Comment by freeboub** [comment]
to be follow up in: https://github.com/TheWidlarzGroup/react-native-video/issues/2884
