### ISSUE TITLE
[iOS] [6.0.0-alpha.6] The operation couldn’t be completed. (CoreMediaErrorDomain error 1718449215.)

### ISSUE THREAD

**Issue by DanielRiera** [TheWidlarzGroup/react-native-video#3134]
# Bug
When play a m3u list, work fine on android, but not on iOS, some list not play.

The operation couldn’t be completed. (CoreMediaErrorDomain error 1718449215.)

This error is show on "onError".

Something strange is that when it gives this error and I press the button to play it by AirPlay on the Airplay target device it plays correctly.

Note, this list redirects to another url to show the video, android works correctly.

## Platform
* iOS

## Environment info
React native info output:

```bash
 System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 11.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.5.6 - /usr/local/bin/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/danielriera/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 33, 33
      Build Tools: 30.0.3, 33.0.0, 33.0.1
      System Images: android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.6, alpha.5 and 5.x.x same problem

**Comment by DanielRiera** [comment]
I try [React Native VLC Player](https://github.com/razorRun/react-native-vlc-media-player) and work fine, but it does not have all the features, ex. allowsExternalPlayback.

**Comment by freeboub** [comment]
Here is the doc of AVPlayer error:
https://developer.apple.com/documentation/audiotoolbox/1577851-audio_format_error_codes/kaudioformatunsupporteddataformaterror/
I think this issue is linked to the video you try to stream.

I close the issue but I can reopen it if you really find an issue linked to the library itself
