### ISSUE TITLE
format_supported=npm i react-native-videoNO_EXCEEDS_CAPABILITIES"

### ISSUE THREAD

**Issue by Nikunj-bisht** [TheWidlarzGroup/react-native-video#3135]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1. Video should play with small resolution
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Issue without description...
