### ISSUE TITLE
preventsDisplaySleepDuringVideoPlayback on Android is preventing phone to sleep even when video is not being played

### ISSUE THREAD

**Issue by ayman-kouzayha** [TheWidlarzGroup/react-native-video#3136]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 25.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/rq/dtkvj5r13_b8g1vvxb3_g6fc0000gn/T/yarn--1685715701667-0.20377518657480187/node
    Yarn: 1.22.19 - /var/folders/rq/dtkvj5r13_b8g1vvxb3_g6fc0000gn/T/yarn--1685715701667-0.20377518657480187/yarn
    npm: 9.6.5 - /usr/local/bin/npm
    Watchman: 2023.01.09.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 31, 32, 33
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-21 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Users/aymankouzayha/.sdkman/candidates/java/11.0.15-tem/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.10 => 0.69.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.1

## Steps To Reproduce

1. Setup the video player with a local file from the resources
2. Do not specify preventsDisplaySleepDuringVideoPlayback (default is true based on docs)
3. Open the view that contains the video tag but do not play the video

## Expected behaviour

1. On Android, the phone screen should sleep after waiting the configured time in the phone settings

## Reproducible sample code

<Video source={require('@myproject/resources/videos/test-video.mp4')}
                             onError={handleOnError}
                             paused={paused} //state
                             onLoad={handleOnLoad}
                             resizeMode={'contain'}
                             onEnd={moveToNextPage}
                             innerRef={(player) => {videoRef.current = player}}
                />
## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

## Workaround
As a workaround for this issue we have manually set the preventsDisplaySleepDuringVideoPlayback prop to be the negated value of the state flag we used to track if the video is paused.

**Comment by freeboub** [comment]
to be follow up in: https://github.com/react-native-video/react-native-video/issues/3552
