### ISSUE TITLE
How to properly install and use react-native-video

### ISSUE THREAD

**Issue by shaftwin** [TheWidlarzGroup/react-native-video#314]
Hi everyone,

I had just installed react-native-video, and i want to clarify some points.
To make this module working, you have to do some configurations:
- related to #274 @jondbm you have to add few lines to MainApplication.java in android folder

After that you have two choices:
- using uri with secure adresse 'https'
- using local file. For that please read the @jhabdas last answer in #279 (the example code was really helpfull and up to date !)

Please understand that this post is not an issue, but just a bunch of help for the newcomers like me.

Ps:
If like me you have build error, remember to react-native upgrade.
And don't forget to rnpm link.

EDIT:
- For android device (lollipop) you have to store your local videos in android/src/main/res/raw and call it with `source={{ uri: videoName }}` without any path
  #125 @isair 

Hope this will help

**Comment by diehell** [comment]
Do you test yours on the device or on simulator. I think it would help newcomers by linking to this [IOS Simulator Bug](https://github.com/react-native-community/react-native-video/issues/179)

**Comment by shaftwin** [comment]
Actually i work on IOS simulator and everything is fine but I have trouble with android device.
I will update this after i found where it come from.

**Comment by mattapperson** [comment]
@shaftwin would you consider a PR to update the docs with this information?

**Comment by ghost** [comment]
The docs call out some manual needs for Android after a specific version and seemed clear once discovered. Not sure if it's the same thing but it seems like automating the root cause would be a good spawn once we find out. I can help take this on once we get some additional feedback.

**Comment by jhabdas** [comment]
Reference documentation and implementation to keep track of when sending up a PR: https://github.com/auth0/react-native-lock

**Comment by peacechen** [comment]
This information really should be in the Readme.

**Comment by ghost** [comment]
@brentvatne thoughts as to opening up the Wiki on this repo?

**Comment by cparjaszewski** [comment]
Sometimes the video is working in Simulator, so I doubt this is a Simulator bug, I'd say it's still something missing in the library itself, that's my personal opinion.
