### ISSUE TITLE
Video sometimes pauses if a native alert is displayed

### ISSUE THREAD

**Issue by canpoyrazoglu** [TheWidlarzGroup/react-native-video#3140]
# Bug

## Platform
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 99.34 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.6

## Steps To Reproduce

1. Have a video playing set up with the following props:
```
 <Video
                source={source} // local source from app package, not remote.
                resizeMode="cover"
                muted
                onEnd={props.onFinish}
                style={styles.video} // absolute fill. if it matters.
            />
```
2. Have an alert (e.g. `Alert.alert` default React Native alert) while video is playing.
3. Video will, **sometimes**, _not always_, pause. I couldn't reproduce an exact pattern of when it happens.

## Expected behaviour

Video should keep playing regardless of the alert.

## Observations

If I take the app to background (e.g pressing home/swiping up from bottom etc) and take it back to foreground it starts playing. Also, finish handler is not called unless video really finishes playing (while it's kind of obvious, reporting just in case it helps).

**Comment by freeboub** [comment]
A sample app with reproduction would be useful. you can also have a look into native code to understand what happen

**Comment by Tring-Karunamoorthy** [comment]
Any update on this issue? I am also facing this issue on IOS only.

**Comment by ihidzhov** [comment]
Hi,

any updates? It happens on many iOS devices even with version 6.0.0-alpha.8

**Comment by KrzysztofMoch** [comment]
Cloud you check if you have this issue in 6.0.0-beta.0 ? I think this PR https://github.com/react-native-video/react-native-video/pull/3326 fixes it. Also I cloud not reproduce it on 6.0.0-beta.0 (iOS 17.0)

**Comment by KrzysztofMoch** [comment]
No response nor activity - let's close this one
