### ISSUE TITLE
MP4 video is not playing on mobile devices for Reactjs Website | React V.17.0.2

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#3141]
Version: React V.17.0.2 and Node V.16.13.0

We have developed a site using React-js, HTML, CSS. And stored data in JSON. Currently facing an issue for the video frame for our landing page.

` 
  <video id='myVideo' autoPlay loop muted>
         <source src={clip} type='video/mp4' />
   </video>
`

Now the issue is, This video plays well on local server on all devices whereas only on laptops for live server but mobile devices.

We have tried several npms to make the video autoplay on mobile device but none of them seem to be working.

npms tried: react-native-video, video-player, react-video

Please suggest me the perfect solution for the issue which i am facing in my react app.

**Comment by freeboub** [comment]
use shakra player or Video.js, react native web support has been dropped on V6.0.0
