### ISSUE TITLE
Hi, in swiper flatlist i detect slowing scroll When the video weighs about 75 megabytes, does anyone know how I can optimize this?

### ISSUE THREAD

**Issue by davidgvf** [TheWidlarzGroup/react-native-video#3142]
# Feature Request
When the video weighs about 75 megabytes, does anyone know how I can optimize this?

### Code sample
<Video
                ref={videoRef}
                paused={!props.isFocus}
                style={[styles.backgroundVideo]}
                resizeMode={'cover'}
                source={{
                    uri: 'https://assets.mixkit.co/videos/download/mixkit-countryside-meadow-4075.mp4'
                }}
                repeat={true}
                playInBackground={true}
            />

**Comment by freeboub** [comment]
When video is not display you should set source=undefined. (works on V6.0.0, but I am not sure it works fine on 5.2.1)
