### ISSUE TITLE
When i was scrubbing the video. The video is not smooth and strucked.

### ISSUE THREAD

**Issue by elamaruthue** [TheWidlarzGroup/react-native-video#3144]
### Current behavior
When i was scrubbing the video. The video is not smooth and strucked.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
[Screencast from 09-06-23 12:07:18 PM IST.webm](https://github.com/react-native-video/react-native-video/assets/84459820/a8d050c7-ee1a-4229-8730-192245b686b1)

**Comment by freeboub** [comment]
webm not supported on ios, so description is not correct.
Do you use a real device or emulator ?
Can you provide a link to the video also ?
Did you try to reproduce it with exoplayer sample app ?
which version of react native video do you use ?

**Comment by freeboub** [comment]
no update let's close
