### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by kozhinas** [TheWidlarzGroup/react-native-video#3145]
# Bug

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: 5.2.0

## Steps To Reproduce

1.download video from dvr
2.play video 
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by dehimer** [comment]
I have same problem for local video on iOS

**Comment by freeboub** [comment]
not enough information to investigate...

**Comment by kozhinas** [comment]
I think the point is that this is a mov format

**Comment by freeboub** [comment]
@kozhinas it would be usefull to have a sample url and a first analysis of logcat to start any investigation...

**Comment by kozhinas** [comment]
what information is needed? I take the player, I take the video and there is no sound, what else should I describe, the mov format is the android platform
