### ISSUE TITLE
Amazon functionality validation faild due to video play in background in sleep mode in FireTV stick 

### ISSUE THREAD

**Issue by vishalhyperspace** [TheWidlarzGroup/react-native-video#3147]
Hello
I have submitted my react-native-tvos app to the Amazon store but they give a functionality validation error.
Here I attached a screenshot of the error. please help me to fix this issue.
I have used below version of tvos and react native video.

"react-native": "npm:react-native-tvos@0.69.8-1",
"react-native-video": "^5.2.1"

## Platform
* Amazon (Android)

## Device 
* Amazon Fire TV Cube
* Amazon Fire TV Stick 4K
* Amazon Fire TV Stick 4K
## Environment info

React native info output:

```bash
System:
OS: macOS 13.2.1
CPU: (8) x64 Apple M1
Memory: 31.08 MB / 8.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 19.4.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.2.0 - /usr/local/bin/npm
Watchman: 2023.01.02.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
Android SDK: Not Found
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9514443
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
Languages:
Java: 19.0.1 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.0.0 => 18.0.0
react-native: Not Found
react-native-macos: Not Found
react-native-tvos: 0.69.8-1
npmGlobalPackages:
react-native: Not Found

```

## Steps To Reproduce

1. Install and launch the app
2. Play any video
3. Long press Home button to invoke HUD (Heads UP Display) overlay
4. Select Sleep to put the device to Sleep mode
5. Select any button to come out of sleep mode and relaunch the app
Actual Result: observe that app audio continues to play in background

## Expected behaviour

Returning back from sleep mode should not result in inconsistent behavior of the app

## Reproducible sample code
here is my react-native-video code.

      <Video
        ref={setPlayer}
        subtitle={true}
        source={{
          uri: configuration.url,
        }}
        title={title}
        subTitleText={subtitle}
        style={[styles.playerLoaded]}
        paused={pausedRef.current}
        onLoad={handleLoad}
        resizeMode={'contain'}
        rate={playerRate}
        onProgress={handleProgress}
        onError={onError}
        onLoadStart={onLoadStart}
        onSeek={handleSeek}
        onReadyForDisplay={onReadyForDisplay}
        onEnd={onEndVideo}
        playInBackground={false}
        playWhenInactive={false}
      />

![Screenshot 2023-06-12 at 12 55 17 PM](https://github.com/react-native-video/react-native-video/assets/66292321/c2a39af6-3bcb-4f42-9eb9-1d5736f5dd19)
![Screenshot 2023-06-12 at 12 55 25 PM](https://github.com/react-native-video/react-native-video/assets/66292321/8a9c2e47-3463-4a18-9717-bc165e523e94)
![Screenshot 2023-06-12 at 12 55 08 PM](https://github.com/react-native-video/react-native-video/assets/66292321/b2c21123-0c57-4d8f-83ad-feb34edd2f49)

**Comment by freeboub** [comment]
I think you should be able to handle this is case with following lib: https://github.com/eliasrodeloso/react-native-lock-detection

You should be able to stop playback when screen is off

**Comment by freeboub** [comment]
No update since long time, let's close.
Ping me if reproduced on 6.0.0
