### ISSUE TITLE
Not play video on ios having error "The server is not correctly configured".

### ISSUE THREAD

**Issue by ahmedShaheer3** [TheWidlarzGroup/react-native-video#3150]
# Bug
Hey there i am using react native video of version 5.2.1 and this following is the url i am trying to play its working fine in android but not in ios 
 https://a41.chat.agora.io/41909830/1147502/chatfiles/1c4ba910-0c33-11ee-b19d-0b7dfceb0053.  
giving me error 
{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 19249}
is this the library issue or the server. also what's the cause of issue. i am stuck badly 

Platform
ios 
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 134.06 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/algoacepc/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.1

this is my code 

        <Video
          source={{
            uri: `${videoUrl}`,
            type: 'mp4',
          }} // Can be a URL or a local file.
          ignoreSilentSwitch={'ignore'}
          onLoadStart={e => console.log('Video Load Start', e)}
          onBuffer={() => {
            console.log('this is bufferering');
          }} // Callback when remote video is buffering
          onError={e => {
            console.log('error', e);
            Toast.show('file lost or corrputed', Toast.LONG);
          }}
          onLoad={() => {
            console.log('this is onLoad');
            setLoading(false);
          }}
          minLoadRetryCount={5}
          onReadyForDisplay={() => {
            console.log('this is onReady for display');
            setLoading(false);
          }}
          hideShutterView={true}
          controls={true}
          resizeMode={'contain'}
          style={styles.videoPlayerStyle} // Store reference
        />
i am stuck for severals days thanks in advance

**Comment by freeboub** [comment]
You need to check why your server return a http error. I guess an error linked to http header.

The server is not correctly configured.

Doesn't seem related to react native video.

I advise to check network communication with Charles proxy.

**Comment by ahmedShaheer3** [comment]
@freeboub  need help: i am new need help. kindly guide me how do i know which header to include because i am using a third party tool. any suggestion or there is a way debug which header i need to include?

**Comment by freeboub** [comment]
https://github.com/react-native-video/react-native-video/blob/master/docs/DEBUGGING.md

**Comment by ahmedShaheer3** [comment]
hey there its streaming fine in android but in ios its giving above error

**Comment by ahmedShaheer3** [comment]
@freeboub  thanks for your guidence i have tried the charles proxy and when i excute requet of video url i.e
https://a41.chat.agora.io/41909830/1147502/chatfiles/1c4ba910-0c33-11ee-b19d-0b7dfceb0053

the header i found from content tab is 

  | HTTP/1.1 200 OK
-- | --
Date | Thu, 22 Jun 2023 06:04:48 GMT
Content-Type | application/octet-stream
Content-Length | 499458
Server | nginx/1.16.1
Vary | Origin
Vary | Access-Control-Request-Method
Vary | Access-Control-Request-Headers
Access-Control-Allow-Origin | *
Vary | Origin
Vary | Access-Control-Request-Method
Vary | Access-Control-Request-Headers
Content-Disposition | attachment; filename="CECF4482-370E-4657-9D4D-01B2A9A4305B.mp4"; filename*=UTF-8''CECF4482-370E-4657-9D4D-01B2A9A4305B.mp4
Connection | keep-alive

and this overview 

URL | https://a41.chat.agora.io/41909830/1147502/chatfiles/1c4ba910-0c33-11ee-b19d-0b7dfceb0053
-- | --
Method | GET
Status | Complete
Response Code | 200 OK
Content-Type | application/octet-stream
Client Address | -
Remote Address | a41.chat.agora.io/99.83.189.183:443
Protocol | HTTP/1.1
Tags | -
Kept Alive | No
SSL | TLSv1.2 (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
Connection |  
Timing |  
Request Start Time | 6/22/23 11:04:47
Request End Time | 6/22/23 11:04:48
Response Start Time | 6/22/23 11:04:48
Response End Time | 6/22/23 11:04:49
Duration | 1.61 s
DNS | 1 ms
Connect | 27 ms
TLS Handshake | 745 ms
Request | 1 ms
Response | 502 ms
Latency | 338 ms
Speed | 317.90 KB/s
Request Speed | 2.33 MB/s
Response Speed | 1,017.34 KB/s
Size |  
Request | 2.38 KB (2,440 bytes)
Response | 510.71 KB (522,963 bytes)
Total | 513.09 KB (525,403 bytes)


but i still didnt get its returning me 200 ok status but when i try to play in ios its giving me error of this. 
{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 19249}

 i didnt get it can you please help me out?
![Screenshot 2023-06-22 at 11 29 58 AM](https://github.com/react-native-video/react-native-video/assets/122429039/48ed5242-fd85-48bb-bf13-6c4a51ec2750)


also i test it in fliiper network tab

**Comment by freeboub** [comment]
Ok, and did you try to record network trace with your iphone ?

**Comment by ahmedShaheer3** [comment]
currenlty i am using emulator on my mac and this is emulator reponse when i try to play video

URL | https://a41.chat.agora.io

Method | CONNECT
Status | Complete
Notes | SSL Proxying not enabled for this host: enable in Proxy Settings, SSL locations
Response Code | 200 Connection established
Content-Type |  
Client Address | 127.0.0.1:56556
Remote Address | a41.chat.agora.io/99.83.189.183:443
Protocol | HTTP/1.1
Tags | -
Kept Alive | No
SSL | TLSv1.2 (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
Connection |  
Timing |  
Request Start Time | 6/22/23 11:40:00
Request End Time | -
Response Start Time | -
Response End Time | 6/22/23 11:41:01
Duration | 1 m 1 s
DNS | 2 ms
Connect | 111 ms
TLS Handshake | 732 ms
Request | -
Response | -
Latency | -
Speed | 3.77 KB/s
Request Speed | -
Response Speed | -
Size |  
Request | 3.37 KB (3,448 bytes)
Response | 228.59 KB (234,077 bytes)
Total | 231.96 KB (237,525 bytes)

this is content 

CONNECT a41.chat.agora.io:443 HTTP/1.1

Host | a41.chat.agora.io
Proxy-Connection | keep-alive
Connection | keep-alive

and this is header tab

<html>
<body>


  | HTTP/1.1 200 Connection established
-- | --



</body>
</html>

**Comment by ahmedShaheer3** [comment]
@freeboub  i have tried to give header of content type but still its giving me same error

**Comment by Mohamed-akmal0** [comment]
@ahmedShaheer3 @freeboub I got the same issue here .. i checked the headers of the URL that im using to display video and the header looks like this => HTTP/1.1 206 Partial Content
Date: Thu, 14 Mar 2024 06:01:43 GMT
Server: Apache/2.4.52 (Ubuntu)
X-Powered-By: Express
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Content-Range: bytes 0-1/1053887
Content-Type: video/mp4
Transfer-Encoding: chunked

**Comment by vpodolyan** [comment]
For those who are still having this issue, you probably need to implement HTTP byte-range requests support on the backend. Please see https://bunny.net/academy/http/what-are-http-range-and-byte-range-requests/
