### ISSUE TITLE
Compile error with Xcode 17 Beta

### ISSUE THREAD

**Issue by samuelscheit** [TheWidlarzGroup/react-native-video#3154]
# Bug

When compiling any react-native app with react-native-video for iOS, Xcode 17 Beta fails with the following error
```
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
```
in [RCTVideo.swift Line 249](https://github.com/react-native-video/react-native-video/blob/master/ios/Video/RCTVideo.swift#L249)

## Platform
Xcode 17 Beta
macOS 13.5

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.5
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 5.16 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /var/folders/hh/fkjg0fwj3ds_rfg6lz1phl500000gn/T/yarn--1687080660596-0.2869588346903893/node
    Yarn: 1.22.19 - /var/folders/hh/fkjg0fwj3ds_rfg6lz1phl500000gn/T/yarn--1687080660596-0.2869588346903893/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.71.7 => 0.71.7 
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 2.85s.
```
^ The Xcode version is wrong, because I'm using the Xcode Beta, which react-native info does not detect

Library version: `^6.0.0-alpha.5`

## Steps To Reproduce

1. Download Xcode Beta 17
2. Create a new react-native project and add react-native-video
3. Compile it (it fails with the above error)

## Solution

put the setSrc async code section in a separate closure and pass it to the DispatchQueue:
```swift

let dispatchClosure = {
// the code that was previously inside of async {}
}

DispatchQueue.global(qos: .default).async(execute: dispatchClosure)
```

**Comment by freeboub** [comment]
Can you please provide a patch / pull request with the fix you did ?

**Comment by hengkx** [comment]
same error

**Comment by zhankit** [comment]
@freeboub 
This patch script from the solutions might help. 👯 
[react-native-video+6.0.0-alpha.6.patch](https://github.com/react-native-video/react-native-video/files/11932302/react-native-video%2B6.0.0-alpha.6.patch)

**Comment by freeboub** [comment]
I just push following PR, can you review and approuve it ?
Thank you for the patch!

**Comment by MikeAlvarado** [comment]
Any updates on here?
Its still ocurring on the stable build of Sonoma

**Comment by MikeAlvarado** [comment]
I can confirm that the solution presented above works. 

> ```
> let dispatchClosure = {
> // the code that was previously inside of async {}
> }
> 
> DispatchQueue.global(qos: .default).async(execute: dispatchClosure)
> ```

Edit: This is happening on the stable release of MacOS Sonoma.

**Comment by CS6** [comment]
The Solution you provided works great. Thanks!

**Comment by freeboub** [comment]
This fix has been integrated for 6.0.0-alpha.9

**Comment by freeboub** [comment]
This fix has been integrated for 6.0.0-alpha.9

**Comment by digitalthjarta** [comment]
When will alpha.9 be released to NPM?

**Comment by freeboub** [comment]
I don't know, still few regression to fix ...
