### ISSUE TITLE
Webm not supporting in react-native-video package

### ISSUE THREAD

**Issue by Vijayakumarktm** [TheWidlarzGroup/react-native-video#3155]
I'm using react-native - 0.67.5 & react-native-video - v5.2.0.

If I try to run the webm file format video. It says "This media format is not supported."

**Comment by freeboub** [comment]
In 5.2.0, you need to configure exoplayer integration to play webm. Did you enable it ?

**Comment by Vijayakumarktm** [comment]
It's not working in IOS device.

**Comment by freeboub** [comment]
I confirm avplayer on ios doesn't support webm... I found it is recommended to use vlc to play webm on ios ...

**Comment by Vijayakumarktm** [comment]
I need to view the webm video file in React Native app (ios device).

Right now, I'm using react-native-video package.

**Comment by KrzysztofMoch** [comment]
`react-native-video` implements `AVPlayer` on iOS. `AVPlayer` does not support webm, which means that `react-native-video` doesn't support it either
