### ISSUE TITLE
preventsDisplaySleepDuringVideoPlayback option not working on v6.0.0-alpha.6

### ISSUE THREAD

**Issue by efkan** [TheWidlarzGroup/react-native-video#3156]
# Bug

When I use `v6.0.0-alpha.6` preventsDisplaySleepDuringVideoPlayback prop seems dysfunctional. 
I can see that the prop works as expected on `v5.2.1`.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 210.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/efkan/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-23 | Google APIs ARM 64 v8a, android-27 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Intel x86_64 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: v6.0.0-alpha.6

## Steps To Reproduce

I have a carousel component that has videos in its slide items. With the `5.2.1` version, our app allows the screen to sleep even if a video is being played on the carousel component. With the `6.0.0-alpha.6` version and the same code the screen never sleeps.

**Comment by stepas-dev** [comment]
bump

having same issue on android, but only when watching in fullscreen mode, tried to use react-native-keep-awake, but it doesn't help

**Comment by freeboub** [comment]
The issue is not clear, we tried to reproduce the issue with @KrzysztofMoch but unfortunnelly we were not able to reproduce it.
I will remove critical for release tag, please let me know if you can reproduce the issue with a sample app

**Comment by freeboub** [comment]
no update let's close this issue
