### ISSUE TITLE
Could not find com.yqritc:android-scalablevideoview:1.0.4

### ISSUE THREAD

**Issue by voortexx** [TheWidlarzGroup/react-native-video#3159]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS
* Android <-----
* Windows UWP
* Windows WPF

## Environment info

React native info output:

`0.68.2`
Library version: 5.2.0

## Steps To Reproduce
- Everything was working fine this morning, i did an Android build with our CI. And this evening I didn't change anything but suddenly our CI give us this error: `Could not find com.yqritc:android-scalablevideoview:1.0.4`
We already have this fix:
```
jcenter() {
            content {
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
```

What happened ? Why doesn't it work any more if we haven't changed anything?

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by jdicami** [comment]
Same happened with us, got it to work with this patch

```
diff --git a/node_modules/react-native-video/android/build.gradle b/node_modules/react-native-video/android/build.gradle
index 2fb8dfd..b508c95 100644
--- a/node_modules/react-native-video/android/build.gradle
+++ b/node_modules/react-native-video/android/build.gradle
@@ -22,5 +22,5 @@ android {
 dependencies {
     //noinspection GradleDynamicVersion
     implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
-    implementation 'com.yqritc:android-scalablevideoview:1.0.4'
+    implementation 'com.github.MatrixFrog:Android-ScalableVideoView:v1.0.4-jitpack'
 }
```

**Comment by freeboub** [comment]
The 5.2.1 release shall already contain a fix for this issue. Can you double check please?

**Comment by voortexx** [comment]
Ok it's good ! Thanks 😄 
Sorry I didn't check the patch version, I just couldn't understand why it had suddenly stopped working

**Comment by freeboub** [comment]
@voortexx I think your old version of this deps has been removed from your graddle cache !
So let's close this this issue
