### ISSUE TITLE
process drm prep and sign license request failed

### ISSUE THREAD

**Issue by unubold1** [TheWidlarzGroup/react-native-video#3165]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

### The following error occurs and the audio stops.

```
2023-07-04 18:11:54.296 772-28548/? E/wv_dash: Trustlet did not send a valid return code: 7
2023-07-04 18:11:54.297 772-28548/? E/wv_dash: process drm prep and sign license request failed
```

1. The first time you play a song, it won't play because of the above error.
2. Changing the link and trying to play. Then, after 2-3 minutes while playing, the song stops due to the above error.

**Comment by freeboub** [comment]
The error log shows wv dash, but you say it is m3u8. You should clarify what kind of stream you use...

**Comment by freeboub** [comment]
Link to the other issue in exoplayer: https://github.com/google/ExoPlayer/issues/11238
Do you have the issue on all android devices ?

**Comment by freeboub** [comment]
not something we can handle in react native video
