### ISSUE TITLE
How to fullscreen on android 

### ISSUE THREAD

**Issue by duonghungit24** [TheWidlarzGroup/react-native-video#3169]
how to fullscreen on android device. i don't find any solution for it

**Comment by freeboub** [comment]
There is a fullscreen flag, you can also setup the style or use function presentFullscreenPlayer()
In any case, read the documentation

**Comment by duonghungit24** [comment]
I have a case error when using function presentFullscreenPlayer() with "controls = true" on ios, on android worked
