### ISSUE TITLE
Can not continue play next when app in background

### ISSUE THREAD

**Issue by apolkingg8** [TheWidlarzGroup/react-native-video#317]
I build an music player app on [https://github.com/demiurga/react-native-music-player](https://github.com/demiurga/react-native-music-player) and I find an issue. My app can auto continue play next song on end(see [there](https://github.com/demiurga/react-native-music-player/blob/master/app/components/player/Player.js#L96-L99)), it works fine when app is running, but throw Error when app run in background. Error here:
![image](https://cloud.githubusercontent.com/assets/4033753/18222605/574e0cac-71cf-11e6-93f4-573816365653.png)
![image](https://cloud.githubusercontent.com/assets/4033753/18222615/7bee50a8-71cf-11e6-92ae-12df813d401b.png)
![image](https://cloud.githubusercontent.com/assets/4033753/18222618/9088aea0-71cf-11e6-9e7a-a6cc76a638cb.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/164690378836821/176558495552525)

**Comment by smkhalsa** [comment]
@demiurga, did you find a workaround for this? I'm facing the same issue.

**Comment by codesinghanoop** [comment]
I think i can help you, what you need to do is send props which would be an array of urls from video component to video.js then video.js will map array to native component.

**Comment by nhoclove9x** [comment]
same error when play audio in background play next error.

**Comment by duansailong** [comment]
same issues :((

**Comment by freeboub** [comment]
I think this issue is still valid !
We need to add a way to control player behavior with lifecycle... This issue Can be relates to pip behavior. Currently it's not possible to keep background playback.
