### ISSUE TITLE
**Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.    > Could not resolve project :react-native-video.      Required by:          project :app       > No matching configuration of project :react-native-video was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute**

### ISSUE THREAD

**Issue by akpatilmindstack** [TheWidlarzGroup/react-native-video#3171]
#Bug
**Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-video.
     Required by:
         project :app
      > No matching configuration of project :react-native-video was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute**
      #platform
       #Android
       **package.json**
       {
  "name": "newapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^18.1.0",
    "@react-native-firebase/auth": "^18.1.0",
    "@react-native-firebase/functions": "^18.1.0",
    "@react-native-firebase/in-app-messaging": "^18.1.0",
    "@react-native-firebase/messaging": "^18.1.0",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/elements": "^1.3.18",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.0.11",
    "deprecated-react-native-prop-types": "^4.1.0",
    "doctor": "^0.3.0",
    "patch-package": "^7.0.0",
    "react": "18.2.0",
    "react-native": "^0.72.1",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.6.3",
    "react-native-screens": "^3.22.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^2.3.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-video-player": "^0.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.7",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.5",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0"
  },
  "engines": {
    "node": ">=16"
  }
}
**settings.gradle**
rootProject.name = 'newapp'
// apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
// include ':app'
// includeBuild('../node_modules/@react-native/gradle-plugin')
// include ':react-native-video'
// project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

include ':app'
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
includeBuild('../node_modules/@react-native/gradle-plugin')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

**android/app/build.gradle**
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
//apply plugin:"com.google.gms.google-services"

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US. Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.newapp"
    defaultConfig {
        applicationId "com.newapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")
    implementation project(':react-native-video')

//    implementation(platform("com.google.firebase:firebase-bom:32.1.1"))
//    implementation("com.google.firebase:firebase-analytics-ktx")
      implementation(':react-native-video')
      implementation "androidx.appcompat:appcompat:1.0.0"
       implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

project.ext.react = [
        enableHermes: true,
        bundleInDebug: true
]

// also add this to force rebuild reanimated:
project.ext.reanimated = [
        buildFromSource: true
]
// project.ext.video=[
//     buildFromSource: true
// ]
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

**android/build.gradle**
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
   repositories {
    google()
    mavenCentral()
    
    //jcenter()
    // maven { url "https://maven.google.com" }
    //  mavenLocal()
        jcenter() {
            content {
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
        maven {
            url 'https://maven.google.com'
        }
    //     maven {
    //         // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
    //         url "$rootDir/../node_modules/react-native/android"
    //     }
    //      maven { url "https://google.bintray.com/exoplayer" }
}

    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
         //    classpath ("com.google.gms:google-services:4.3.15")
    }
    allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
}
**nodemodules/react-native-video/android-exoplayer/build.gradle**
apply plugin: 'com.android.library'

android {
    compileSdkVersion = 33
    buildToolsVersion = "33.0.0"

    defaultConfig {
        minSdkVersion = 21
        targetSdkVersion = 33
    }
}

dependencies {
    implementation'com.facebook.react:react-native:+'
    implementation 'com.google.android.exoplayer:exoplayer:2.7.3'
    implementation('com.google.android.exoplayer:extension-okhttp:2.7.3') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
    implementation 'com.squareup.okhttp3:okhttp:3.9.1'
    }
I tried all available solution please let me kow what else I can do I have tried cleaning gradle it is getting cleaned bud when I go for npm run android it's giving above error

**Comment by akpatilmindstack** [comment]
https://stackoverflow.com/q/76661173/22208884

**Comment by Aaron46** [comment]
I had this issue after I upgraded from 5.2.0. I also had a react-native.config.js  file to be able to resolve exo player. Once I deleted that file I got passed this error.

**Comment by freeboub** [comment]
"react-native-video": "^2.3.1" 😢 
please update to 5.2.1 at least!

**Comment by freeboub** [comment]
don't forget to "gradlew clean" when changing version of react native video.
I will close this issue, let me know you still have some issue.

**Comment by akpatilmindstack** [comment]
I'm using it on pure React-native Cli no expos,while I tried  cleaning gradlew multiple times .I rechecked properly all dependencies as per mentioned in npm
