### ISSUE TITLE
After being in background for more than 20 secs (approx.) video gets dark, freezes and only starts playing again after some delay

### ISSUE THREAD

**Issue by i-vivdich** [TheWidlarzGroup/react-native-video#3174]
# Bug

On iOS when video player is in background for long time, after switching back to app - firstly, video is not displayed at the state it was left, it actually is dark. Then, after some delay (couple of seconds) - video starts playing again.
## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-alpha.6
Device: iPhone XS, iPhone 11

## Steps To Reproduce

1. Open screen <Video /> components resides.
2. Start playing video.
3. Put app into background for ~30 - 60 seconds.
4. Open app again.
5. Video is **DARK** (Dark screen) for couple of seconds, freezes and only then it starts playing.

## Expected behaviour

1. Open screen <Video /> components resides.
2. Start playing video.
3. Put app into background for ~30 - 60 seconds.
4. Open app again.
5. Video is not getting DARK and it starts playing right after coming back to app (as soon as possible).

## Code 

    const renderVideoComponent = useCallback(() => {
    const display = loading ? 'none' : 'flex';

    return (
      <Video
        repeat
        resizeMode="cover"
        ignoreSilentSwitch="ignore"
        source={{
          uri: videoUrl,
          type: 'm3u8',
        }}
        muted={isMuted}
        ref={videoRef}
        onLoadStart={onLoadStart}
        onLoad={onLoad}
        onEnd={handleOnEnd}
        onProgress={handleProgress}
        onError={(e: Error) => setErr(e)}
        style={[styles.backgroundVideo, { display }]}
        paused={paused}
      />
    );
    }, [videoUrl, paused, isMuted, loading]);

## Video sample
Self-explanatory.

**Comment by ihidzhov** [comment]
Hi,

any solution for that bug or fix?
It happens on many iOS devices with version 6.0.0-alpha.8.
The same issue but video does not start at all(sometimes only sound).
