### ISSUE TITLE
How to play a HLS stream from USB camera

### ISSUE THREAD

**Issue by MatteoBuffo** [TheWidlarzGroup/react-native-video#3178]
Hello. I have a USB camera that serves a HLS stream on its own private network. That is, the URL of the source is something like `http://[private address]:[port]/?[URL parameters]` and it has no extension.

I can play this stream by connecting to the WiFi network provided by the camera and opening the URL on the browser or VLC app.

How can I view it also on my Expo app (with bare workflow and react-native-video installed)?

I managed to play it by installing the react-native-vlc-media-player library, but that one causes my EAS builds to be very large (way more than 100 MB).

With react-native-video I get the "None of the available extractors could read the stream" error in the `onError` method.

Any hint? Thanks in advance.

**Comment by freeboub** [comment]
I think you need to ensure the type is well specified in source like this, and it should work.

`source={{ uri: 'http://[private address]:[port]/?[URL parameters]', type: 'm3u8' }}`


Did you try android and ios ?
Don't forget to allow http (and not https only) in your app
