### ISSUE TITLE
get image from video

### ISSUE THREAD

**Issue by kkesley** [TheWidlarzGroup/react-native-video#318]
Hi! I want to ask if it's possible to retrieve an image (like a screenshot) from <Video/> given either seek time or take the current state

Thanks!

**Comment by mattapperson** [comment]
@kendrickkesley Not at the moment. That said I am in the middle of adding that and it should be supported on iOS tomorrow.

**Comment by mattapperson** [comment]
@kendrickkesley not finished, but here is a first pass... I welcome any feedback on the API
https://github.com/react-native-community/react-native-video/tree/getFrames

Please note that you can only currently get frames of a video that has played for at least 300ms. This is a bug I plan to fix ASAP

**Comment by kkesley** [comment]
@mattapperson Thanks a lot! will you add this feature on android too? :)

**Comment by mattapperson** [comment]
@kendrickkesley At this time, no. Android we ran into issues with memory getting all the frames of longer videos. Hopefully down the road someone smarter then me will figure it out ??

[--- Commented from Asana.com
#commenter Matt Apperson
---[aa]

**Comment by kkesley** [comment]
Oh okayy thankss!
Still awesome anyway!

**Comment by jephtta** [comment]
Is the getFrames branch getting merged anytime soon?

**Comment by mattapperson** [comment]
Not as such. We have an updated API for android and iOS that we will be merging soon

**Comment by sjmueller** [comment]
@mattapperson that's exciting! But which branch is this on so that we can take a look? I was checking out the [new-api branch](https://github.com/react-native-community/react-native-video/tree/new-api) but that looks way to old too be what you're referring to...

**Comment by jephtta** [comment]
Thanks @mattapperson. If i may ask, does it include the "get image from video" functionality?

**Comment by mattapperson** [comment]
@jephtta yes.

**Comment by mlg87** [comment]
@mattapperson did this (or something similar) ever get added? just logged the props and i dont see anything along these lines

**Comment by mattapperson** [comment]
In its own branch yes. Never matured enough for master

**Comment by Lesliesibbs** [comment]
@mattapperson looking for this as well where can i find this?

**Comment by mattapperson** [comment]
https://github.com/react-native-community/react-native-video/tree/getFrames

**Comment by rnowm** [comment]
Any updates on that? Would love to add it to my project

**Comment by vs-lance** [comment]
I'm with @rnowm - any chance of this getting into the master branch?

**Comment by Lesliesibbs** [comment]
The example is not working...help anyone?

**Comment by thillin** [comment]
Hey @mattapperson, what would you suggest is needed for this branch to be considered mature enough to be merged into master? (Beyond updating it to bring it in line with master of course)

Depending on what's involved, I may be able to work on a PR for this if that'd be helpful?

**Comment by mattapperson** [comment]
@thillin there are some perf issues with hitting that api too quickly... my plan was to build a queue. But as I am no longer using the feature I dropped it. That said, I not sure that’s truly needed to be merged

**Comment by n1ru4l** [comment]
did you check out https://www.npmjs.com/package/react-native-thumbnail?

**Comment by sorin-f-wiredelta** [comment]
@mattapperson So is there functionality to get a thumbnail from the video ? I really do not want to install another package that does this...It seems that rn-video should be totally capable of doing this. thank you

**Comment by codervss** [comment]
> did you check out https://www.npmjs.com/package/react-native-thumbnail?

But this doesn't give us thumbnail for urls.
Any Solution for that?

**Comment by n1ru4l** [comment]
On iOS this could be done with [`AVAssetImageGenerator`](https://developer.apple.com/documentation/avfoundation/avassetimagegenerator).

@codervss You could create a pull request that adds such a feature.

**Comment by maomeiqi** [comment]
Does it happen now?

**Comment by n1ru4l** [comment]
> You could create a pull request that adds such a feature.

@maomeiqi Please do not spam this issue.

**Comment by ghost** [comment]
> did you check out https://www.npmjs.com/package/react-native-thumbnail?

It just works for Youtube Links not for videos from own server.

**Comment by taschik** [comment]
is there any update on this issue? Perhaps someone has found a workaround or other solution to this?

**Comment by mikeyrt16** [comment]
Any updates? I'd love to use something like `react-native-view-shot` but `react-native-video` isn't currently supported... 😢

**Comment by adelbeke** [comment]
https://docs.expo.dev/versions/latest/sdk/video-thumbnails/ :)
