### ISSUE TITLE
Is there a way to stop loading video?

### ISSUE THREAD

**Issue by zahrat** [TheWidlarzGroup/react-native-video#3180]
### Current behavior
I really have no idea about current behavior. but It seems there is no prop in react native video that stop load video.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
I am using react native video in a flatList, items are combination of images and videos like Instagram, so it's possible an item itself contains multiple video. I want to stop loading video if another video is playing. Is this possible? now I handle this in this way: If video is not playing I use Image component that shows video thumbnail, my problem with this method is that if I scroll in the list each time video start loading from beginning. Also I tried using react-native-video-cache to resolve this issue, but in that way some video couldn't play. I think its because of caching. am I wrong?

### Platform
Which player are you experiencing the problem on:
* iOS
* Android

**Comment by freeboub** [comment]
I think the easiest way to implement this is to set the source to undefined. This is working on 6.0.0 but I am not sure it works fine on 5.2 branch.

**Comment by zahrat** [comment]
@freeboub  If a video loaded and then user scroll in the list and as you said I set the source to undefined then if user scroll again to that video does it start loading again?

**Comment by freeboub** [comment]
You need to set the source with the uri to restart loading !
Each <Video will use a video decoder, setting the source to undefined will release it
