### ISSUE TITLE
m3u8 video always takes 2-3 seconds for video to load so always it shows black screen

### ISSUE THREAD

**Issue by shikhar119911** [TheWidlarzGroup/react-native-video#3181]
Bug
m3u8 video always takes 2-3 seconds for video to load so always it shows black screen

Platform
Which player are you experiencing the problem on:
iOS and android

**Comment by TDUser91** [comment]
Facing the same issue with live content (with and without DRM protection), also Android on iOS

**Comment by freeboub** [comment]
It is expected to have loading time ...
Let's close this issue
