### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'Constants' of undefined.

### ISSUE THREAD

**Issue by yuosuf1** [TheWidlarzGroup/react-native-video#3196]
This my first time trying this library, sadly i got this error, TypeError: Cannot read property 'Constants' of undefined.
without any complexity my code is:
 `import Video from "react-native-video";
const PlayerScreen = () => {
  return (
    <Video
      source={{
        uri: "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
      }}
    />
  );
};
export default PlayerScreen;
`
screen rendered from navigation
`<Tab.Screen
            name="Player"
            component={PlayerScreen}
            options={{
              tabBarStyle: { display: "none" },
              tabBarButton: () => null,
            }}
          />`
my Dependencies: 
`"dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "deprecated-react-native-prop-types": "^4.2.1",
    "expo": "~49.0.5",
    "expo-video-player": "^2.2.0",
    "nativewind": "^2.0.11",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-video": "^6.0.0-alpha.7",

  }`
on ios ( Expo Client )

**Comment by freeboub** [comment]
Why do you also have expo-video-player ? It may lead to some conflicts ...
Can you also detail the call stack ? I am not sure which Constant is problematic.
I assume you have correctly rebuild the app and restart metro

**Comment by yuosuf1** [comment]
> Why do you also have expo-video-player ? It may lead to some conflicts ... Can you also detail the call stack ? I am not sure which Constant is problematic. I assume you have correctly rebuild the app and restart metro


i deleted the expo-video-player and reset cache but still the same issue,
**i tried with fresh expo app and also did not work with same error**

this is the stack:
![IMG_5747](https://github.com/react-native-video/react-native-video/assets/22305785/66507b5c-9fc5-4bbf-be32-a22b17660e27)

**Comment by yuosuf1** [comment]
_**UPDATE:**_ i think the problem that RCTVideo not registered, i tried to console log UIManager['RCTVideo'] it is undefined, i anyone help me with this

**Comment by Dror-Bar** [comment]
Had this issue because I forgot to run npx pod-install

**Comment by javiermanzano** [comment]
> npx pod-install

Documentation should reflect this, right? At least I haven't found it

**Comment by glennin-codes** [comment]
> Had this issue because I forgot to run npx pod-install

actualy it doesnt work for us using expo go. Any one found the solution yet
