### ISSUE TITLE
TypeError: Cannot read property 'Constants' of null

### ISSUE THREAD

**Issue by rohero6** [TheWidlarzGroup/react-native-video#3197]
How do I fix this error？ Run at expo go
This error is located at:
    in Video (created by PlayVideo)
    in TouchableWithoutFeedback (created by PlayVideo)
    in RCTView (created by View)
    in View (created by PlayVideo)
    in RCTView (created by View)
    in View (created by PlayVideo)
    in PlayVideo (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

code:
export default function PlayVideo() {
    return (
            <View>
    
                    <Video source={{ uri: "https://vjs.zencdn.net/v/oceans.mp4" }}
                    />
            </View>
    )
}

"dependencies": {
    "@expo/webpack-config": "^18.0.1",
    "@react-navigation/native": "^6.1.7",
    "expo": "~48.0.18",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.71.8",
    "react-native-paper": "^5.9.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^6.0.0-alpha.7",
    "react-native-web": "~0.18.11",
    "react-native-webview": "11.26.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "@types/react-native": "^0.72.2",
    "@types/react-native-video": "^5.0.15",
    "cheerio": "^1.0.0-rc.12",
    "express": "^4.18.2",
    "request": "^2.88.2",
    "typescript": "^4.9.4"
  },
  "private": true
}

**Comment by rohero6** [comment]
export default function PlayVideo() {
    return (
            <View>
    
                    <Video source={{ uri: "https://vjs.zencdn.net/v/oceans.mp4" }}
                    />
            </View>
    )
}

**Comment by rohero6** [comment]
return (
            <View>
                    <Video source={{ uri: "https://vjs.zencdn.net/v/oceans.mp4" }}/>
            </View>
    )

**Comment by freeboub** [comment]
No lib version no platform, cannot investigate. Let me know if you are still stuck

**Comment by oxeedo-lang** [comment]
pls i need help on these am trying to play video in the background with react native app but got the error below
cannot read property 'constants' of null 
![image](https://github.com/react-native-video/react-native-video/assets/147073786/b1d129cb-7ef1-4568-9b4d-c3d48c974e5c)

**Comment by ahoang2502** [comment]
hey I got the same error

**Comment by libcthorne** [comment]
Try using Expo development build instead of Expo Go.

**Comment by glennin-codes** [comment]
any one who has solved the error yet. .One said we use expo-av instead i have used it and it has worked 
but I do prefer the react-native-video.

**Comment by aryanagarwal15** [comment]
encountering same error, what can be the error here?
