### ISSUE TITLE
textTracks crash on iOS with m3u8 video

### ISSUE THREAD

**Issue by clementnv** [TheWidlarzGroup/react-native-video#3200]
# Bug

When **textTracks** is enable on video `.m3u8`, crash on iOS device, 

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-alpha.6
Device: iPhone 14

## Steps To Reproduce

Reproducible sample code
```
    <Video
          source={{
            uri: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
          }}
          textTracks={[
            {
              title: 'English CC',
              language: 'en',
              type: TextTrackType.VTT,
              uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
            },
          ]}
          selectedTextTrack={{
            type: 'language',
            value: 'en',
          }}
        />
```

You got an error:
```
react_native_video/RCTVideoUtils.swift:190: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2023-08-09 23:00:52.007849+0200 KephyreTraining[3788:328590] react_native_video/RCTVideoUtils.swift:190: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

<img width="857" alt="Capture d’écran 2023-08-09 à 23 02 17" src="https://github.com/react-native-video/react-native-video/assets/36882039/a20eb7b2-3295-4bd9-8239-1a4bf70621df">

...

## Expected behaviour

1. No crash of app

Thank you for your help 🙏

**Comment by nicolaosm** [comment]
Experiencing that too! Appreciate any help on this.

**Comment by mikmedina** [comment]
same issue

**Comment by nicolaosm** [comment]
`textTracks` also applied on `.mp4` videos will lead to an iOS crash on alpha 7. Not just `.m3u8`

**Comment by GhayoorUlHaq** [comment]
I'm also experiencing the same issue, and here are my findings:
- Latest alpha release ([v6.0.0-alpha.7](https://github.com/react-native-video/react-native-video/releases/tag/v6.0.0-alpha.7)) will crash when we define `textTracks` for both `.m3u8` and `.mp4`.
- Last stable release ([5.2.1](https://github.com/react-native-video/react-native-video/releases/tag/v5.2.1)) is not crashing but when we define `textTracks` with `selectedTrack`, `.mp4` is working fine even though I can see the subtitles, but`.m3u8` is not loading.

**Comment by zaferatli** [comment]
Because RCTVideo 314. line send asset url only, then RCTVideoUtils 190 line cannot get assets.timeRange.duration item and return error. We need to send video object from RCTVideo 314 line then crash gonna fix

[RCTVideo 314 Line](https://github.com/react-native-video/react-native-video/assets/54990817/c908198b-7643-4e81-842d-9d0f4d53a875)

**Comment by freeboub** [comment]
@zaferatli but how to fix the issue and make sideloaded subtitles working? :) I started investigations, but I didn't find trivial fix ...

**Comment by zaferatli** [comment]
actually there is func calculatePlayableDuration in RCTVideoUtils when i use this func its return 0, if we get duration of video then we can pass.

**Comment by timvvoodman** [comment]
Having the same issue, m3u8 on iOS trying to load text tracks crashes the video player. Due to Accessibility concerns we are having to use a different solution for iOS, would ideally like to use this package for both.

**Comment by zaferatli** [comment]
@timvvoodman @freeboub 
[Image](https://github.com/react-native-video/react-native-video/assets/54990817/aa667b31-da8a-4e3f-aebf-664147b4125f) i am pretty close to pr. Probably tomorrow pr will be open

**Comment by wolfxpertlab** [comment]
android not play m3u8 how can I solved it

when navigation 1 screen to another video screen video not play and show exceptionerror

**Comment by matteodanelli** [comment]
> @timvvoodman @freeboub [Image](https://github.com/react-native-video/react-native-video/assets/54990817/aa667b31-da8a-4e3f-aebf-664147b4125f) i am pretty close to pr. Probably tomorrow pr will be open

Any news?

**Comment by mykappevolve** [comment]
hi sorry to bother, any news on the PR? thank you

**Comment by freeboub** [comment]
The crash has been fixed for next release (alpha.11 or beta.1)
unfiortunnetlly this feature doesn't work as expected (like on 5.2 branch, confirmed by @KrzysztofMoch). 
linked PR: https://github.com/react-native-video/react-native-video/pull/3330
