### ISSUE TITLE
16MB video taking up 133MB of memory on Android

### ISSUE THREAD

**Issue by MetaBenji** [TheWidlarzGroup/react-native-video#3202]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 5.2.1
Device: LG V50S ThinQ
Android OS: 10

## Steps To Reproduce

1. Run the android app with react native in release mode so the react native debugger and metro server doesn't take up additional memory
2. Play a video from a remote source
3. Measure how much memory is being used via `adb shell dumpsys meminfo | grep spatial`.  Take 5 measurements and use the average as memory fluctuates 
4. Unmount the video component
5. Take 5 more memory measurements 
6. 
...

## Expected behaviour

I would expect a 16MB video to take up much less than 133MB of memory 

Memory measurements with a single 16MB video playing: 
1085.87 MB
1099.95 MB
1095.68 MB
1082.40 MB
1081.24 MB
1086.70 MB
1099.29 MB
1098.62 MB
1098.21 MB
1079.91 MB
1075.90 MB
**Average 1089MB**

Memory measurements without the video component mounted
958.40 MB
954.20 MB
949.72 MB
952.87 MB
956.19 MB
957.41 MB
959.46 MB
**Average 955MB**

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

[video link](https://dd2cgqlmnwvp5.cloudfront.net/hero-carousel/Team_Hoops_Carousel.mp4)

**Comment by MetaBenji** [comment]
@brentvatne any ideas?

**Comment by freeboub** [comment]
@MetaBenji can you clarify which kind of video format you use ? 
Not sure what is "spatial" memory. when I profile I usually use PSS level.
Notice also that video decoder can take memory, It can also repend of the device.
A cross test can be to play the video with an exoplayer standalone sample to see if you have the same behavior
