### ISSUE TITLE
Android app stuck at white screen if source is set

### ISSUE THREAD

**Issue by canpoyrazoglu** [TheWidlarzGroup/react-native-video#3205]
# Bug

If `source` is set to anything, the whole application (not only the player) hangs if source is set with a completely white (sometimes with ANR) state. My screen or video player's background is NOT white, not video player is fullscreen (it is absolutely positioned and container view's background can be seen when source isn't set, but the whole screen is white when source is set so the whole app seems to crash and it's not a "fullscreen blank player".

## Platform

* Android

## Environment info

Library version: 6.0.0-alpha.7, 6.0.0-alpha.6, 5.2.1 (happens on all of them)
Device: Android 8 emulator (I don't have access to a physical Android device)

## Steps To Reproduce

1. Install the library as instructed.
2. Have a `<Video>` object with a `source property set to anything, either a local (`require`) video or a remote H.264 MP4 video.
3. Launch the app. App crashes. 
4. Kill the app process.
5. Comment out `source` prop. App launches (though of course with no video playing).

## Expected behaviour

The player should not crash and instead should display the video when `source` is set.

## Notes

Also, poster URL image doesn't seem to work regardless of source being set. Things work perfectly normal on iOS, it's only the Android version that's problematic.

I've put console logs on `onPlaybackStalled` and `onError` events. They don't seem to fire except `onError` only fires if the `source` is invalid (e.g. something nonsense like `source={'a'}`) in the first place with the error: `{"error": {"errorCode": "INVALID_URL", "errorString": "invalid url, player will stop"}}`, but still showing the white blank screen anyway.

**Comment by canpoyrazoglu** [comment]
After further investigation I've found out that this happens on earlier Android versions.

I'm having the error on Android 8.0 (API Level 26) emulator, whereas everything works perfectly on Android 13.0 (API Level 33)

**Comment by freeboub** [comment]
can you please detail logcat error ? It is maybe an issue with emulator ...
