### ISSUE TITLE
Repeated Requests and High Bandwidth Usage - Seeking Solutions for Caching Optimization - v6.0.0-alpha.7

### ISSUE THREAD

**Issue by oshriza** [TheWidlarzGroup/react-native-video#3209]
### Current behavior
When using the react-native-video library with the repeat prop set to true, three requests are being made to the server every time the video restarts. One with status 200 and two with status 206. This results in redundant network requests.

### Reproduction steps
 1. Use `"react-native-video": "v6.0.0-alpha.7"` to play a remote video file.
 2. Set the repeat prop to true.
 3. Observe the network requests using a tool like Android Studio's Network Inspector.
 4. Notice that three requests are made every time the video repeats.

### Expected behavior
When the `repeat` prop is set to **true**, the video should restart without making additional network requests, utilizing cache or already buffered data.

### Platform
Android (I haven't tested other platforms)

### Video sample
videos that exist in my Firebase storage.

## Code

```
import React, { FC, useEffect, useRef } from 'react';
import { Dimensions, ViewStyle } from 'react-native';
import Video from 'react-native-video';

import { AppEvent } from './types';

const $backgroundVideo: ViewStyle = {
  position: 'absolute',
  top: 0,
  left: 0,
  bottom: 0,
  right: 0,
};
const EventVideo: FC<{ event: AppEvent; activeIndex: number; index: number }> = React.memo(
  ({ event, activeIndex, index }) => {
    const playerRef = useRef(null);
    const videoEndedRef = useRef(false);

    const videoSource =
      typeof event.videoUrl === 'string' ? { uri: event.videoUrl } : event.videoUrl;

    function checkReady() {
      console.log('ready to play');
      console.log('event id: ' + event.id);
    }

    return (
      <Video
        source={videoSource}
        style={$backgroundVideo}
        poster={event.posterUrl}
        resizeMode="cover"
        posterResizeMode="cover"
        playInBackground={false}
        playWhenInactive={false}
        repeat
        paused={index !== activeIndex}
        onError={(error) => {
          console.error('Video loading error', error);
        }}
        onReadyForDisplay={checkReady}
      />
    );
  }
);

export default EventVideo;
```

**### Additionally, I would like to know if anyone has found a solution for caching videos locally or using a CDN to avoid high bandwidth and redundant requests. Any insights or guidance on optimizing video playback in react-native-video would be greatly appreciated.**

**Comment by freeboub** [comment]
Video caching has been integrated in 6.0.0-RC.1 for android. It works only with mp4 videos.
I hope it will solve your issue.
Let's close this one.
Note that other tickets has been open to request caching on dash/hls but not yet implemented
