### ISSUE TITLE
Video takes much time to Buffer

### ISSUE THREAD

**Issue by swaroopa94** [TheWidlarzGroup/react-native-video#321]
Hii ,
I am using this module to play videos in my application but the video takes so much time to buffer in android especially. I am retrieving the video from the amazon s3 server.
Please give me any suggestion to less the buffering time in android. as it is urgent.

**Comment by bsiddiqui** [comment]
@swaroopa94 buffering is going to be dependent on your internet connection, size of the video, etc. If you don't want to have a buffering issue, you can try fully downloading the video before playing.

**Comment by ManiSJ** [comment]
@bsiddiqui I am playing video(.mp4) from local. The Video size 32 MB. Its still buffer for me. Is it because of Video Size? What must be min video size u would advice me for my app.

**Comment by ghost** [comment]
👉 http://stackoverflow.com/questions/tagged/react-native
