### ISSUE TITLE
Switching between a video and image causes UI on top to flicker

### ISSUE THREAD

**Issue by MetaBenji** [TheWidlarzGroup/react-native-video#3210]
# Bug

When switching between an `<Image />` component  and a `<Video />` component, the UI that I have absolutely positioned on top flashes.  I'm using the video in a carousel from `react-native-reanimated-carousel` and am changing from an image to a video when the slide becomes the current slide.  I'm doing this because there is a bug where Exoplayer can't instantiate more than one or two videos at a time and also to conserve memory. 

I've tested without `react-native-reanimated-carousel` and have included a basic example below where you can toggle between a video and image component with a button.  When toggling between a image component and any other react native component, the UI doesn't flicker.  

This loom video shows an example of the flicker with the carousel.  The same flicker happens with the barebones example below.

https://www.loom.com/share/fc726d7ad15b427193c4081d313cf894?sid=5d3ec8ee-842e-4128-9cdf-71542e6726cc

## Platform
Which player are you experiencing the problem on:

[x] Android

## Environment info

Library version: 5.2.1
Device: LG V50S ThinQ

## Steps To Reproduce

1. Load the component under "Reproducible sample code" which switches between an image and a video when pressed.  
2. Press to switch between a video and an image 
3. You'll see the components rendered on top of the video/image not to flicker
...

## Expected behaviour

1. The UI shouldn't flicker

## Reproducible sample code

```
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react"
import { Animated, Image, Platform, Pressable, Text, View } from "react-native"
import { StyleSheet } from "react-native"
import Video from "react-native-video"

export default memo(function FeaturedCarouselSlide() {
  const [isVideoPausedLocal, setIsVideoPausedLocal] = useState(true)

  const onVideoLoaded = useCallback(() => {
    setIsVideoPausedLocal(false)
  }, [setIsVideoPausedLocal])

  const isPaused = isVideoPausedLocal

  const poster = "https://dd2cgqlmnwvp5.cloudfront.net/hero-carousel/Team_Hoops_Carousel.jpg"


  const [isVideo, setIsVideo] = useState(true)

  const videoFormat = Platform.OS === "android" ? "webm" : "mp4"

  return (
    <Pressable
      style={styles.container}
      onPress={() => {
        setIsVideo(!isVideo)
      }}
    >
      {isVideo ? (
        <Video
          style={[styles.video]}
          paused={isPaused}
          source={{
            uri: `https://dd2cgqlmnwvp5.cloudfront.net/hero-carousel/Team_Hoops_Carousel.${videoFormat}`,
          }}
          resizeMode={"cover"}
          poster={poster}
          posterResizeMode="cover"
          repeat
          muted
          onLoad={onVideoLoaded}
        />
      ) : (
        <View style={[styles.video, { flex: 1 }]}>
          <Image style={{ width: "100%", height: "100%", borderRadius: 16 }} source={{ uri: poster }} />
        </View>
      )}
      <View style={styles.overlay} pointerEvents="box-none">
        <View style={styles.spaceInfoContainer}>
          <Text numberOfLines={2} style={styles.title}>
            Title Here
          </Text>
          <View style={styles.creatorAndStats}>
            <Text numberOfLines={1} style={styles.name}>
              Name here
            </Text>
          </View>
        </View>
      </View>
    </Pressable>
  )
})

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "transparent",
  },
  video: {
    position: "absolute",
    // width: "100%",
    // height: "100%",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 16,
  },
  overlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: "100%",
    height: "100%",
    borderRadius: 16,
  },
  spaceInfoContainer: {
    width: "100%",
    position: "absolute",
    bottom: 0,
    padding: 16,
  },
  title: {
    paddingVertical: 8,
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: {
      width: 0,
      height: 4,
    },
    textShadowRadius: 10,
  },
  creatorAndStats: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  name: {
    marginLeft: 4,
    maxWidth: 180, 
  },

})
```

## Video sample

Its included in the component above, however it's not specific to any one particular video.  It's happening with webm and mp4 files

**Comment by MetaBenji** [comment]
@brentvatne any ideas?

**Comment by freeboub** [comment]
You should have video.js file in the repo to understand how poster works. It is a very basic JavaScript file.
Anyway, I don't understand this implementation, why do you need to switch between poster and image ?
It would be better to use only poster (if implementation is ok for you or only the image and change its opacity

**Comment by MetaBenji** [comment]
I'm switching between an Image and Video component because when I have more than one Video component at a time, I frequently get the error below and videos don't play.  That's the main problem I'm trying to solve and the issue I posted above was a result of this change.

```
{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/x-vnd.on2.vp8, null, -1, en, [2560, 996, -1.0], [-1, -1]), format_supported=YES", "errorString": "Unable to instantiate decoder OMX.qcom.video.decoder.vp8"}}
```

My understanding is this is an Exoplayer error and the cause is having more than one Exoplayer instance instantiated at a time or potentially trying to re-instantiate it.  

I'm using the poster so when it switches from Image to Video, there is no black flash in between and it shows the poster immediately, instead of waiting for the first frame of the video.

I may be going down the wrong track.  If so, I'd love to get your advice on a better approach

**Comment by vemarav** [comment]
Wrap the component inside react.memo to avoid flicker and pass shutterColor transparent if its happening on android

**Comment by MetaBenji** [comment]
Which component are you referring to?  The component I posted is already wrapped in react.memo.  I ended up fixing it.  I had to set a `zIndex` on the overlay `View`.  @freeboub any idea why I need a zIndex on this?  Is there something that would cause the `Video` component to temporarily have a higher zIndex or elevation?

**Comment by freeboub** [comment]
@MetaBenji The good way to handle this feature is to use only react native video.
on V6.0.0 if you set a null source, the player will be stopped correctly (unfortunately not on 5.2).
Then you should be able to play with the 2 parameters source and poster to achieve your needs.
I think this is indirectly answer to this question: https://github.com/react-native-video/react-native-video/issues/3214
6.0.0 is still tagged alpha as there are mainly regression on subtitles/audio track on ios, but this has similar feture/stability level than 5.2

**Comment by MetaBenji** [comment]
Thanks for all your help @freeboub!  How exactly should I be setting the source to null?

When I look at the type of the `source` prop, it has the following type, which doesn't include `null`. 

```
    source: { uri?: string | undefined, headers?: {[key: string]: string } | undefined, type?: string | undefined } | number;
```

This is working for me but the existing type for `source` doesn't allow `uri` to equal `null` and also triggers the `onError` callback with ` {"error": {"errorCode": "INVALID_URL", "errorString": "invalid url, player will stop"}} `.  Can you confirm this is the correct way to do it?

```
// this is the index for the slide currently displa
const isCurrentSlide = slideIndex === currentIndex
<Video 
source={{uri: isCurrentSlide ? "http://....." : null}}
shutterColor="transparent"
poster="http://..."
/>

**Comment by freeboub** [comment]
@MetaBenji use undefined it will be ok !

**Comment by freeboub** [comment]
@MetaBenji did you solve / workaround this issue ?
