### ISSUE TITLE
Black screen when playing FairPlay video on iOS

### ISSUE THREAD

**Issue by JustJoostNL** [TheWidlarzGroup/react-native-video#3213]
# Bug
Black screen while playing a FairPlay protected video.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: Tested on both 5.2.1 and 6.0.0-alpha.7
Device: Tested on both iPhone 14 Pro Max and iPhone 12

## Steps To Reproduce

1. Load in a stream with Fairplay DRM protection.
2. Make sure to use the reproducible sample code.
...

## Expected behaviour

1. It should play the DRM stream correctly. (No black screen)

## Reproducible sample code

```tsx
<Video
      source={{
        uri: sourceUri,
      }}
      muted
      paused={false}
      ignoreSilentSwitch={"ignore"}
      selectedTextTrack={{
        type: "disabled"
      }}
      drm={
        {
          type: drmType === "widevine" ? DRMType.WIDEVINE : DRMType.FAIRPLAY,
          certificateUrl: drmType === "fairplay" ? "cert-url-here" : undefined,
          async getLicense(spcString: string) {
            if (!drmUrl || !entitlementToken || !config.subToken) return "";
            const body = "spc=" + spcString + "&assetId=asset-id-here";
            const res = await fetch(drmUrl, {
              method: "POST",
              body: body,
              headers: {
                "Content-Type": "application/octet-stream",
                entitlementtoken: entitlementToken,
                ascendontoken: config.subToken,
              },
            });
            return await res.text();
          }
        }
      }
    />
```

## Further explanation
I debugged myself using Postman, and I can confirm that all the license request's did pass successfully. (Status code 200, and a valid response.) Subtitles do work. Audio and video don't (black screen), so it probably has something to do with the decoding of the video/audio itself.

**Comment by whalemare** [comment]
What version of iOS?

**Comment by JustJoostNL** [comment]
I tested on both iOS 16.6 and iOS 17 Beta.

**Comment by JustJoostNL** [comment]
Alright, so it turns out my assetId was wrong, it's working correctly now.
