### ISSUE TITLE
[Discussion] Do you recommend 6.0.0-alpha or 5.2.1

### ISSUE THREAD

**Issue by MetaBenji** [TheWidlarzGroup/react-native-video#3214]
Thanks to everyone involved in maintaining the library!

Does the team maintaining the library recommend using 6.0.0-alpha or 5.2.1 for a production react native application?

I know that's a very general question, so I also listed our how we're using video in our application below: 

- Play one video at a time in `react-native-reanimated-carousel` with auto advancing to the next carousel slide once the video finishes playing
- Have a second carousel of videos rendered on screen at the same time with one video in this carousel also playing 
- Components absolutely positioned on top of videos 
- Videos muted 
- small buffer on Android to decrease memory usage

**Comment by freeboub** [comment]
clearly 6.0.0 :) let's close this topic
