### ISSUE TITLE
can it play youtube videos

### ISSUE THREAD

**Issue by sandeep-autviz** [TheWidlarzGroup/react-native-video#3219]
i just want to ask quick question can i give youtube video url and play that ?

**Comment by freeboub** [comment]
No, you cannot use YouTube web link.
You need to integrate youtube api to get m3u8 or mp4 and provide it to react native video.
If you just have a youtube web link, you can use react-native-youtube.

**Comment by sandeep-autviz** [comment]
sir is there any way to play youtube video directly in my app . i am using react-native-youtube iframe library but is doesnt let me disable the share button which is my main requirement

**Comment by freeboub** [comment]
No, I don't have any better solution...
