### ISSUE TITLE
onLoad triggered but video not playing

### ISSUE THREAD

**Issue by tuxtux00** [TheWidlarzGroup/react-native-video#322]
Hi there,

I am using this component and I noticed that when I simulate a bad connection, the onLoad callback is triggered even if the video is not loaded. A black screen is shown but not the video.
The video is coming from an url and not local assets

Is it a bug or did I miss something ? 

Cheers

**Comment by tonyrewin** [comment]
same here, is it compatable with react-native 0.33? 

i ve tried both - local assets and url, onLoad(data) recieved an object, but still i ve never seen a video playing with this lib

also i did not find any assets in generetaed ios app content, where i should place this videofile exactly?

**Comment by roysG** [comment]
+1

**Comment by tuxtux00** [comment]
I use onProgress for now as a wokraround.
I guess this has a performance issue but at least solve my problem

**Comment by quadsurf** [comment]
i get the same black/blank video screen, and all i did was copy and paste (note that i am pretty  comfortable integrating these types of plugins)... everything else loads properly though, like the custom &/or non-customer player skins/controls, etc. I double-checked in browser that Video URI works and that it's accessed via ssl's https, and I'm running RN 0.32.

I also tried onProgress suggested by @tuxtux00 but that didn't work for me either.

please help!

**Comment by Robiullah2244** [comment]
I am faceing the same issue.

"react-native": "0.70.6",
"react-native-video": "^5.2.1"
