### ISSUE TITLE
Changing source URL doesn't play subsequent video

### ISSUE THREAD

**Issue by MetaBenji** [TheWidlarzGroup/react-native-video#3222]
# Bug

When I switch the video source from one valid url to another, the second video fails to play.  This also happens for all other subsequent videos.  In the code below, the user press a button in the parent component that causes `step` to change. 

## Platform
Which player are you experiencing the problem on:
* Android however I haven't tested iOS yet

## Environment info

Library version: 6.0.0-alpha.7
 - I also notice this bug on 5.2.1
Device: LG V50S ThinQ

## Steps To Reproduce

1. Play first video
2. User action that changes the URL
3. Second video renders the first frame but fails to play even though the `onLoad` callback fires
...

## Expected behaviour

1. The second video should play

## Reproducible sample code

```
import { captureException } from "@sentry/react-native"
import { memo, useCallback, useMemo } from "react"
import { Text, View } from "react-native"
import Config from "react-native-config"
import Video from "react-native-video"


export type TutorialStep = {
  title: string
  subtext: string
  videoName: string
}
export type TutorialSlideProps = {
  step: TutorialStep
}

export const TutorialSlide = memo(function TutorialSlide({ step }: TutorialSlideProps) {
  const { title, subtext, videoName } = step

  const styles = createStyles(isLandscape())

  return (
    <View style={styles.tutorialCard}>
      <View style={styles.titleContainer}>
        <Text style={styles.titleText}>{title}</Text>
      </View>
      <View style={styles.videoContainer}>
        <Video
          style={styles.video}
          repeat
          source={{ uri: `${Config.PUBLIC_ASSETS_BASE_URL}/mobile-tutorial/${videoName}.mp4` }}
          bufferConfig={{
            minBufferMs: 2500,
            maxBufferMs: 5000,
            bufferForPlaybackAfterRebufferMs: 2500, // if this is greater than minBufferMs, the app will crash
            bufferForPlaybackMs: 2500,
          }}
          onLoad={() => console.log("BBenji tutorial loaded")}
        />
        <Text style={styles.subText}>{subtext}</Text>
      </View>
    </View>
  )
})
```

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
1.  https://dd2cgqlmnwvp5.cloudfront.net/mobile-tutorial/dance.mp4
2.  https://dd2cgqlmnwvp5.cloudfront.net/mobile-tutorial/camera.mp4

**Comment by freeboub** [comment]
I am surprised by this issue, the sample basic app on the master branch in the repo acts like your sample...
Can you triple check and compare with the sample app please ?

**Comment by MetaBenji** [comment]
will do!  Thanks so much for the quick response!

**Comment by freeboub** [comment]
@MetaBenji any update ?
