### ISSUE TITLE
 Why can't I require a video  in m3u8 format 

### ISSUE THREAD

**Issue by zhanshihua** [TheWidlarzGroup/react-native-video#3223]
when i use react-native-video in react-native 
![image](https://github.com/react-native-video/react-native-video/assets/67133914/f6747bb7-2d44-4629-9d01-96699ef2db05)
![image](https://github.com/react-native-video/react-native-video/assets/67133914/ca02f2af-ca2b-4ebb-add7-762fce77976b)
![image](https://github.com/react-native-video/react-native-video/assets/67133914/1e126025-5b19-4fd7-92e2-16dc323cc285)

**Comment by freeboub** [comment]
The issue is linked to your require, not react native video...
To debug it, you need to extract the require call outside of <Video tag and understand the root cause in order to get a valid id...
