### ISSUE TITLE
onVideoTracks, selectedVideoTrack and maxBitRate not working

### ISSUE THREAD

**Issue by coucoseth** [TheWidlarzGroup/react-native-video#3224]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 5.2.1
Device: Android Tv

## Steps To Reproduce

1.<Video
                  source={{uri: videoUrl}}
                  ref={onVideoPlayerRef}
                  onBuffer={buff => {
                    console.log('buffer', buff);
                  }}
                  maxBitRate={currentBitrate}
                  selectedVideoTrack={{
                    type: 'resolution',
                    value: 720,
                  }}
                  onVideoTracks={res => console.log('res changed', res)}
                  onError={err => {
                    console.log('movie err', err);
                  }}
                  videoResolution={currentVidRes}
                  style={styles.backgroundVideo}
                  resizeMode="cover"
                  paused={player.paused}
                  onLoad={onLoad}
                  onProgress={onProgress}
                  onEnd={onEnd}
                  poster={movieData.poster}
                  minLoadRetryCount={3} // retry internet conn 3 times before throwing err
                  disableDisconnectError
                  fullscreen
                />
...

## Expected behaviour

1. When playing an .mpd file, i expect video quality resolution to change when i change maxBitRate value, but the player seems to continue playing video at highest available resolution, i then used the selectedVideoTrack however, no effect to player, i then tried to log when resolution changed using onVideoTracks and found out that this is not firing

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
can you please double check on V6.0.0-alpha version please ? 
for sure: onVideoTracks is not support on 5.2.1
regarding to : selectedVideoTrack I am not sure this is also working fine.
Let me know
