### ISSUE TITLE
I cannot disable captions

### ISSUE THREAD

**Issue by birosrichard** [TheWidlarzGroup/react-native-video#3228]
# Bug

I'm experiencing issues with the HLS source. The source includes 1 textTrack, and I want to disable its visibility. However, attempting to use "selectedTextTrack" does not produce the expected results. The captions are still visible.

When I adjust the tvOS settings to Accessibility > Subtitles and Captioning > Closed Captions and SDH > OFF, it does not display the captions. However, I require the ability to override the tvOS settings and suppress the display of captions.

## Platform
Which player are you experiencing the problem on:
* iOS - tvOS

## Environment info
Library version: 5.2.1
Device: tvOS

## Steps To Reproduce
Load an HLS source that includes captions.

## Expected behaviour

1. Captions should not be visible.

## Reproducible sample code

```
import Video from 'react-native-video';
<Video
            {...props}
            ignoreSilentSwitch="ignore"
            muted={false}
            paused={playerStore.isPaused}
            playInBackground={true}
            playWhenInactive={true}
            pictureInPicture={true}
            controls={false}
            ref={playerStore.setPlayer}
            onError={playerStore.onError}
            onVideoError={playerStore.onVideoError}
            onProgress={playerStore.onProgress}
            onLoad={playerStore.onLoad}
            onEnd={playerStore.onEnd}
            rate={playerStore.rate}
            source={{ uri: playerStore.url ?? undefined }}
            style={[{
                backgroundColor: 'black',
                height: '100%',
                width: '100%',
            }, props.style]}
            selectedTextTrack={{
                type: 'disabled',
            }}
        />
```

**Comment by freeboub** [comment]
can you test on version 6.0.0 please ?
