### ISSUE TITLE
[Android] When controls is false, the presentFullscreenPlayer() does not work.

### ISSUE THREAD

**Issue by nicolaosm** [TheWidlarzGroup/react-native-video#3231]
# Bug
## Platform
Which player are you experiencing the problem on:
* Android

## Environment info
Library version: V6 - Alpha 7
Device: Android Pixel 4

## Steps To Reproduce
1. set controls={false}
2. call presentFullscreenPlayer()
...

## Expected behavior
Video goes into full screen mode - Same as it would when we press on native Full Screen Icon.

**Comment by nicolaosm** [comment]
@freeboub I believe this issue is critical for release. Please review. Thanks

**Comment by freeboub** [comment]
I review behaviour between 5.2 & 6.0.0 it seems coherent, anyway I agree with you that the 'usage' is not really logic.
I think we should define the expected behaviour for next major release.
We can either discuss about it here on on slack if you want.

**Comment by nicolaosm** [comment]
Sure, please add me to slack on this email: nicolaosmoubayed@gmail.com

Talk soon @freeboub
