### ISSUE TITLE
Video stop playing in ios

### ISSUE THREAD

**Issue by HemangiVekaria** [TheWidlarzGroup/react-native-video#3236]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 5.2.1
Device: all ios devices

## Steps To Reproduce
When set uri to player it works ok in android but in ios it play for 2 second and then stop playing. On click of video i added this code videoRef.current.seek(0); and by using this code it start playing from starting and then it works in repeated mode without any issue for that same video. But again if i play any other video it stop after 2 second and on click it works without any issue.  The same thing wok on on ios simulator

 <Video
                ref={videoRef}
                source={videoUri}
                style={getVideoViewStyles()}
                controls={false}
                resizeMode={'contain'}
                onLoad={onLoadEnd}
                onProgress={onProgress}
                onEnd={onEnd}
                ignoreSilentSwitch={'ignore'}
                paused={paused}
                // repeat={true}
            />

## Expected behaviour
Video should play without stopping

**Comment by HemangiVekaria** [comment]
Can anyone have any solution for this?

**Comment by freeboub** [comment]
can you reproduce on 6.0.0-alpha.8 ?
You should have a look to system trace to get more informations and also catch onError message, it can bring interesting informations

**Comment by HemangiVekaria** [comment]
I did't change anything in the library but now i fix it by adding timeout in screen to load video. I am loading video controller after one second and video is playing without any issue.

**Comment by freeboub** [comment]
Thank you, so we can close this issue ?

**Comment by dhaval-radadia** [comment]
Yes, You can. thanks

**Comment by HemangiVekaria** [comment]
Yes Sure, Thanks
