### ISSUE TITLE
Subtitles not working with Vimeo VTT files

### ISSUE THREAD

**Issue by aguilanegra** [TheWidlarzGroup/react-native-video#3242]
I am using react-native-video 6.0.0-alpha.7. I am attempting to enable subtitles in my video, but for some reason they are not showing. I am using the below implementation:

<Video
  ref={playerRef}
  source={{uri: selectedVideo}}
  style={styles.videoPlayer}
  resizeMode="cover"
  controls={true}
  paused={isPaused}
  onProgress={onProgress}
  rate={selectedPlaybackRate}
  selectedTextTrack={{
    type: 'title',
    value: 'English CC',
  }}
  textTracks={[
    {
      title: 'English CC',
      language: 'en',
      type: TextTrackType.VTT,
      uri: selectedVideoCaptionFile,
    },
  ]}
/>

where selectedVideoCaptionFile = "https://captions.cloud.vimeo.com/captions/100860111.vtt?expires=1695002951&sig=5d130679090960aaef3949d434732655ec77afc2&cta.vtt" (this link is only good for a certain amount of time, but it does resolve well). 

I've tested against "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt", and it works well, but with the aforementioned VTT file URL, for whatever reason the audio is muted, and no subtitles are showing.

Any suggestions?

System:
  OS: macOS 13.5.2
  CPU: (12) arm64 Apple M2 Pro
  Memory: 804.48 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.8.1
    path: ~/.nvm/versions/node/v19.8.1/bin/node
  Yarn: Not Found
  npm:
    version: 9.7.1
    path: ~/.nvm/versions/node/v19.8.1/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/lib/ruby/gems/3.2.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /Users/.jenv/shims/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

Library version: 6.0.0-alpha.7
Device: iOS, Android

**Comment by aguilanegra** [comment]
I solved this issue by downloading the file and storing it locally as a .vtt file, now the captions are working. I then delete the file when the video player is closed.

**Comment by rameshep1989** [comment]
@aguilanegra
How you are handling controls in Android, as I want to integrate controls in Android.

**Comment by aguilanegra** [comment]
@rameshep1989 Which controls are you referring to specifically? At present my implmentation is using controls={true} and these are working well for Android, at least on my emulator.
