### ISSUE TITLE
[6.0.0-alpha.8] Black screen if you set "selectedVideoTrack={type: 'auto'}" twice

### ISSUE THREAD

**Issue by hitman249** [TheWidlarzGroup/react-native-video#3244]
# Bug

Black screen if you set "selectedVideoTrack={type: 'auto'}" twice

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0-alpha.8
Device: Android STB

## Reproducible sample code

```
constructor() {
  this.state.selectedVideoTrack = {type: 'auto'}; // init value
}

render() {
  return <Video selectedVideoTrack={this.state.selectedVideoTrack}/>;
}

...

setTimeout(() => {
  // change {type: 'auto'} to {type: 'auto'} -> broken video
  this.setState({selectedVideoTrack: {type: 'auto'}}); 
}, 10);
```

**Comment by wolfxpertlab** [comment]
please help me same issue here I am very stuck also get black screen in android

https://github.com/react-native-video/react-native-video/issues/3251#issue-1909825593

**Comment by freeboub** [comment]
Ok, but your sample is not a real life sample...
This is a similar issue open (I cannot find it currently) when you refresh to rapidly the <Video the player stuck with a black screen. I suspect this is the same issue.
Can you clarify if this is happening if you increase the timer (10sec for exemple) and / or if it causes a player reload ?

**Comment by wolfxpertlab** [comment]
In my application video is played in more than one screen one screen is in fullscreen and one screen is https://github.com/react-native-video/react-native-video/issues/3251#issue-1909825593 is from github plz help me how to play video smooth cam in android

I have not seen any timer used explain me

**Comment by wolfxpertlab** [comment]
any solution ?? video is black screen in android and not play smoothly how can I solved it please tell me information about this issue.

**Comment by freeboub** [comment]
@wolfxpertlab you should have a look to this discussion: https://github.com/react-native-video/react-native-video/issues/2984
But I think you will need to switch on V6.0.0-alpha to support the correct player release when video is outside of the screen

**Comment by wolfxpertlab** [comment]
Ok I will try to change which version use in alpha?

and exoplayer not work in alpha versions in android

**Comment by azuluaga-hu** [comment]
same error, black screen when video is in fullscreen

**Comment by azuluaga-hu** [comment]
i have same error in IOS, I fixed, I set controls false for IOS

**Comment by freeboub** [comment]
Issue retested on 6.5.0, I don't reproduce it.
Let me know if this is still reproduced, let's close the ticket for now
