### ISSUE TITLE
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### ISSUE THREAD

**Issue by tapz** [TheWidlarzGroup/react-native-video#3249]
# Bug

Please update the Kotlin version to 1.6.20.

```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-video' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

---

build.gradle:

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

buildscript {
    def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') :
            (project.properties['RNSAC_kotlinVersion'] ? project.properties['RNSAC_kotlinVersion'] : "1.6.10")
```

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0-alpha.8
Device:

**Comment by brianlenz** [comment]
It looks like this is the cause of the issue:

https://github.com/react-native-video/react-native-video/commit/19c8134dbc29c5e25ca4e55d20ac2e297b66c420

I see this issue was marked as completed, but I don't see any changes to [build.gradle](https://github.com/react-native-video/react-native-video/blob/master/android/build.gradle) for it yet?

**Comment by tapz** [comment]
@brianlenz  I closed this because the react-native-video build.gradle primarily uses the value from the root project's build.gradle. So, I was able to solve this by adding the ext variable `kotlinVersion` to my build.gradle. I only had `kotlin_version` and that's why it was using the default 1.6.10. Of course it would make sense to update the default value too.

**Comment by freeboub** [comment]
@tapz do you think something shall be update in the package ? Maybe I should add support of version with _? Or maybe just a documentation update ?
I am afraid a lot of users will fall into the same issue

**Comment by VMBindraban** [comment]
Also had this problem, had to add the following like @tapz suggested:

```
buildscript {
    ext {
        kotlinVersion = "1.6.20"
    }
}

```
