### ISSUE TITLE
android black screen

### ISSUE THREAD

**Issue by wolfxpertlab** [TheWidlarzGroup/react-native-video#3251]
android very stuck not play video how can I solved it 

please help me 

![Screenshot_1695472783](https://github.com/react-native-video/react-native-video/assets/124674978/f2a6b265-08e0-4ba3-b2ec-2d4fed6478ce)
![Screenshot_1695472854](https://github.com/react-native-video/react-native-video/assets/124674978/03a480d3-08a9-46cc-854e-0b69a66a1be3)

above home image and podcast screen image

it is my podcastvideoscreen

 <TouchableOpacity style={styles.videoMainView} activeOpacity={1} onPress={() => {
                    setViewableIndex(index)
                    setPause(!pause)

                }}>

                    <Video
                        resizeMode='cover'
                        paused={index === viewableIndex ? pause : true}
                        style={styles.videoView}
                        automaticallyWaitsToMinimizeStalling={false}
                        source={{ uri: item.video }}
                        shutterColor='transparent'
                        ignoreSilentSwitch='ignore'
                        bufferConfig={{
                            minBufferMs: 150,
                            maxBufferMs: 3000,
                            bufferForPlaybackMs: 100,
                            bufferForPlaybackAfterRebufferMs: 100,
                        }}
                        // useTextureView={false}
                        progressUpdateInterval={200}
                        onError={(error) => console.error('Video error:', error)}
                        repeat
                    />

                    {/* {
                        index == videoIndx && pause == true
                            ?
                            <Image style={styles.plyImg} source={playImg} />
                            :
                            null
                    } */}

                </TouchableOpacity>
                
                my package.json is
                  "react-native-video": "^5.2.1",
                  "react": "18.2.0",
                 "react-native": "^0.71.3",

    it is my setting.gradle
    include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

and also add main application.java add new reactnativeVideo package

  @freeboub  please help me I am very stuck

**Comment by freeboub** [comment]
No version, no sample video url no log

**Comment by freeboub** [comment]
Start by reproducing the issue in a basic sample and have a look to the logcat.
You may also need to enable exoplayer in 5.2
You can also try with V6.0.0 alpha version

**Comment by wolfxpertlab** [comment]
please tell me how to enable exoplayer

**Comment by freeboub** [comment]
https://github.com/react-native-video/react-native-video/blob/v5.2.0/README.md

**Comment by wolfxpertlab** [comment]
I have been configured all these steps for both android and iOS then also sometimes get black screen, 
please tell me @freeboub  , what can I do

**Comment by wolfxpertlab** [comment]
Please tell me how can I solved it I am very stuck
