### ISSUE TITLE
alpha.8 iOS regression: audio does not work with headphones

### ISSUE THREAD

**Issue by CoffeeFlux** [TheWidlarzGroup/react-native-video#3258]
# Bug

After bumping to alpha.8, videos no longer properly use headphones when plugged in. In this case, it's been reproduced on a recent iPhone and recent iPad with both Airpods and USB-C wired headphones.

It used to work correctly on alpha.7, using the airpods if connected and otherwise the device speakers. Setting `audioOutput` does not seem to affect this behavior either way.

[This line](https://github.com/react-native-video/react-native-video/commit/0bf7f70e24649777679976c5581f2ab6e99a2f0b#diff-11b570d57686048495c3b4ee0acb3d24e480a6a470a09d5a2a790b4f470f5455R200) is the cause. Most people consuming this package probably do not want category type playAndRecord - I think playback was the correct default, and playAndRecord has other side effects that mean it should be opt-in only.

For now I'm running off a fork that effectively reverts https://github.com/react-native-video/react-native-video/commit/0bf7f70e24649777679976c5581f2ab6e99a2f0b.

cc: @freeboub @mysport12 @liviu-padurariu

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0@alpha.8
Device: Model: iPad mini (5th generation)
iOS 16.6

## Steps To Reproduce

1. Create video object with video stream
2. Play video while headphones are connected

## Expected behaviour

1. Audio plays through Airpods

## Reproducible sample code

Just a \<Video\> element, settings don't seem to matter.

## Video sample

Video doesn't seem to matter.

**Comment by facugu1998** [comment]
We are facing the same problem. Changing `playAndRecord` to `playback` works. Thanks!

**Comment by mysport12** [comment]
@CoffeeFlux I will do my best to look into it this week. I think there is likely an easy enough fix to appease all scenarios.

**Comment by freeboub** [comment]
@mysport12  @facugu1998  if you can add the feature to sample app in this repo, it would be wonderful !
Question, is there something missing with audioOutput ? I think there you be an automatic mode (to be configured by default)
This mode would use speaker by default, and earpiece when available.

Is android also affected ?

**Comment by freeboub** [comment]
@mysport12 Did you find time to have a look ?

**Comment by mysport12** [comment]
I finally got a bit of time this morning. Can you take a look at my fork and see if that resolves the issue. [mysport12/react-native-video](https://github.com/mysport12/react-native-video)

**Comment by f1multiviewer** [comment]
> I finally got a bit of time this morning. Can you take a look at my fork and see if that resolves the issue. [mysport12/react-native-video](https://github.com/mysport12/react-native-video)

Can confirm this fixes the issue observed. Thank you.

**Comment by freeboub** [comment]
Thank you for the patch @mysport12 .
Fix will be included in 6.0.0-alpha.9
