### ISSUE TITLE
Fullscreen option missing in MediaController

### ISSUE THREAD

**Issue by flexdhana** [TheWidlarzGroup/react-native-video#326]
Displays MediaController over the Video screen if enabled (ANDROID), but its missing fullscreen button. I followed #270. please advise me.. thanks

<img width="275" alt="screen shot 2016-09-13 at 4 37 55 pm" src="https://cloud.githubusercontent.com/assets/19851520/18471907/ae0591c8-79d1-11e6-81ec-c7894c4d7f67.png">

Code:

```
               <View style={styles.vcontainer}>
                    {spinner}
                    <Video
                        source={{uri: this.state.currentVideo}}
                        style={styles.video}
                        paused={false}
                        controls={true}
                        resizeMode={this.state.resizeMode}
                        onLoadStart={this._onLoadStart.bind(this)} 
                        onLoad={this._onLoad.bind(this)}
                      />
                </View>
```

**Comment by muvv** [comment]
Need help:
Can i get example of implementing controls in android
i added controls={true} prop ,but i am not getting control options in android. It could be better if i can get a example in android

**Comment by flexdhana** [comment]
@muvv did you made changes listed in the link below?

https://github.com/react-native-community/react-native-video/pull/270/commits/7c2ebfba0017172890d3dbc8fd0ccfef42aebd26

**Comment by xiaomilii** [comment]
@flexdhana Did you solve this problem?

**Comment by flexdhana** [comment]
@xiaomilii Still not..

**Comment by IbrahimSulai** [comment]
@flexdhana 

Now you can use Android Exoplayer. Since it has both controls and also having full-screen functionality.

Opened a PR (#1730) for full-screen support in Android Exoplayer.

**Comment by ShivamJoker** [comment]
@IbrahimSulai I mean is there a fullscreen button by default in Android Exoplayer ? Like iOS
