### ISSUE TITLE
Video Stop Playing inside a Flatlist on Android

### ISSUE THREAD

**Issue by satyabrata-dash5** [TheWidlarzGroup/react-native-video#3264]
# Bug

1-Video Stops playing inside the flat list after some videos play
2- Black screen between 2 videos

## Platform
Which player are you experiencing the problem with:

* Android

## Environment info

 "react-native-video": "^5.2.1",
Device: All

Code Sample 
 <Video
          ref={videoRef}
          source={source}
          paused={currentIndex !== index || paused}
          muted={props?.isGlobalMute}
          volume={volume}
          progressUpdateInterval={500}
          useTextureView={false}
          playInBackground={false}
          playWhenInactive={false}
          minLoadRetryCount={5}
          preventsDisplaySleepDuringVideoPlayback={true}
          // onLoad={onBuffer}
          onProgress={onProgress}
          ignoreSilentSwitch="ignore"
          onLoad={onLoad}
          // onBuffer={onBuffer}
          onError={onError}
          onTouchStart={showControls}
          onEnd={onEnd}
          poster={cover_photo}
          resizeMode="contain"
          posterResizeMode="cover"
          style={styles.video}
          repeat={true}
          preload={true}
          controls={false}
          hideShutterView={true}
          maxBitRate={1000}
          bufferConfig={{
            minBufferMs: 1000,
            maxBufferMs: 5000,
            bufferForPlaybackMs: 250,
            bufferForPlaybackAfterRebufferMs: 500,
          }}
        />

## Video sample

https://github.com/react-native-video/react-native-video/assets/57708184/9495cf53-b3f0-40cf-8bd0-9adf30165843

**Comment by wolfxpertlab** [comment]
please explain how can you play video smoothly please help me I have not play video smoothly. android not play smoothly 

I am very stuck please help me

**Comment by Kadir-prog** [comment]
hi @wolfxpertlab are you using flatlist to list video view

**Comment by Kadir-prog** [comment]
can you please share your flatlist code so we will check

**Comment by freeboub** [comment]
Here is a flatList sample which seems working fine with V6.2.0: https://github.com/freeboub/react-native-video-flatlist-sample

I think your initial issue as due to missing `disableFocus={true}`
I close the issue, let me know if I need to reopen it
