### ISSUE TITLE
React-native-video reloads when orientation change (react-native-orientation-locker) (Android only)

### ISSUE THREAD

**Issue by nghuymb** [TheWidlarzGroup/react-native-video#3267]
# Bug
I use the react-native-orientation-locker library to change the application's orientation. But after changing the orientation, the video is reloaded while playing (this only happens on Android. iOS still works normally).
Anyone knows how to avoid this behavior?

## Platform
* Android

## Environment info

"react-native-video": "^5.2.0",
"react-native-orientation-locker": "^1.4.0",

**Comment by hasan642** [comment]
same issue, Is any solution?

**Comment by freeboub** [comment]
I cannot reproduce the on V6.0.0-beta.6. I tried to call`Orientation.lockToPortrait();` and `Orientation.lockToLandscape();` in the sample, but video doesn't restart. may also be linked to react native version.
can you reproduce it on V6 and check react-native version please ?
