### ISSUE TITLE
audio not repeating if longer than 1min 25 sec

### ISSUE THREAD

**Issue by BarkhaArora** [TheWidlarzGroup/react-native-video#3268]
## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info
Library version: 6.0.0-alpha.7
Device: ios

## Steps To Reproduce
Repeat audio that has length more than 1 minute and 25 seconds. It does not repeat even after setting repeat true

## Expected behaviour

1. Should repeat until repeat is set false

**Comment by xueling794** [comment]
## Platform

Android

## Enviroment info
"react-native-video": "6.0.0-beta.5"

## The same problem
More then 1 min video repeat not work ,but less then 10 secs repeat is ok.
