### ISSUE TITLE
Error occurred: The operation couldn’t be completed. (OSStatus error -50.)

### ISSUE THREAD

**Issue by mihailapuste** [TheWidlarzGroup/react-native-video#3270]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: v6.0.0-alpha.8
Device: 
- iphone 15
- ios 17.1 
- react native 72.5

## Steps To Reproduce
- After upgrading to react native 72.5, it seems that  react native video (v6.0.0-alpha.8) causes the video component to pause unexpectedly. The error observed in the xcode log `Error occurred: The operation couldn’t be completed. (OSStatus error -50.)` seems to indicate an error related to AVFoundation or other Apple media frameworks.

```js
    <Video
      ref={audioPlayerRef}
      // This property only affects android
      bufferConfig={
        {
          minBufferMs: maxAudioDuration * 1000,
          maxBufferMs: 3 * maxAudioDuration * 1000,
          bufferForPlaybackMs: maxAudioDuration * 1000,
          bufferForPlaybackAfterRebufferMs: maxAudioDuration * 1000,
          maxHeapAllocationPercent: 0.2,
          minBackBufferMemoryReservePercent: 0.2,
          minBufferMemoryReservePercent: 0.15,
        } as VideoProperties['bufferConfig'] & {
          maxHeapAllocationPercent?: number;
          minBackBufferMemoryReservePercent?: number;
          minBufferMemoryReservePercent?: number;
        }
      }
      source={trackQueue[0] as VideoProperties['source']}
      paused={isPaused && !isCardFlipped}
      repeat={false}
      // audioOnly mode required a poster image. We'll use a 10x10 white square,
      // as it's never actually shown
      poster={"***"}
      audioOnly
      onEnd={playNextTrackInQueue}
      onError={(error) => console.log('ERROR:', error)}
      disableFocus
      mixWithOthers={'mix'}
      muted={muted}
    />
```

<img width="837" alt="image" src="https://github.com/react-native-video/react-native-video/assets/33971581/e3bc6b3c-9334-495f-99d5-38c23b307d49">

**Comment by braincore** [comment]
@mihailapuste How did you resolve this? It appears to work in the simulator, but not on device.

**Comment by wjbeau** [comment]
@mihailapuste I'm seeing this too, did you do something to resolve it?

**Comment by giantslogik** [comment]
This still happens in v6.2.0 + iOS 15.
The error happens in _RCTVideo_ `try AVAudioSession.sharedInstance().overrideOutputAudioPort(AVAudioSession.PortOverride.speaker)`.

 _RCTVideo_  calls it when category is `AVAudioSession.Category.playback` as per the documentation it should not.

   ```
 /*This method is only valid for a session using PlayAndRecord category. 
    */
    @available(iOS 6.0, *)
    open func overrideOutputAudioPort(_ portOverride: AVAudioSession.PortOverride) 
```

Does not seem to be causing a problem.

**Comment by MTPL0005-AbhishekDube** [comment]
@giantslogik I'm getting this too, did you find something to resolve it?

**Comment by giantslogik** [comment]
@MTPL0005-AbhishekDubey  this isn't causing any issues or failures within react-native-video. (The operation No-ops with that message.) So there is no need to resolve.

I think Apple has removed the error return on newer iOS (i tried 17.x), so I didn't bother to PR a fix.

I had locally patched out the line causing the error. (on iOS 15/17) `AVAudioSession.sharedInstance().overrideOutputAudioPort(AVAudioSession.PortOverride.speaker)`,  it isn't doing anything as session  category is `AVAudioSession.Category.playback`.  I haven't tested on VisionOS etc.

**Comment by MTPL0005-AbhishekDube** [comment]
@giantslogik I'm getting another line in the log **RNV:setSrc Stopping playback**
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/110587704/e5aa5dc6-f0c8-4481-ae56-b5a3bda5ac89)

**Comment by giantslogik** [comment]
@MTPL0005-AbhishekDubey If you are running v6.2.0  , that error can only come from one place `RCTVideo:776` i.e. within setAudioOutput . ( Search  for`"Error occurred:` in the project to see where the error came from) . In that case setSrc is likely somewhere in the stack.
