### ISSUE TITLE
[6.0.0.alpha.8] iOS Picture-in-Picture Issues

### ISSUE THREAD

**Issue by brianlenz** [TheWidlarzGroup/react-native-video#3271]
# Bug
It would appear the PIP changes from #3221 have introduced some iOS instability in `6.0.0.alpha.8`. We are experiencing an issue with our (very simple) video code that we've been using successfully for the previous alphas. `6.0.0.alpha.6` and `6.0.0.alpha.7` do not have this issue, so it appears to be caused by the latest alpha release.

Specifically, the issues we are having are:

1. When the app is backgrounded while a video is playing, the video temporarily shows in picture-in-picture before it stops. PIP is supposed to be disabled by default (and we haven't set `pictureInPicture` on our `Video` component), so that is a problem.
2. When the app is subsequently foregrounded, the video no longer displays. We can tap our play button to get playback to continue, at which point, audio can be heard, but the video itself is just a black screen.

## Platform
Which player are you experiencing the problem on:
* **iOS**

## Environment info

Library version: `6.0.0.alpha.8`
Device: iPhone 12 (physical device)

## Steps To Reproduce
1. Play a video in iOS.
2. Background the app.
3. Observe PIP briefly before it disappears.
4. Re-open app.
5. Play video.
6. Observe video never appears again.

## Expected behaviour
3. PIP should not appear. It's supposed to be disabled by default.
4. On re-opening the app, the video should be visible.

## Reproducible sample code
We have a very basic Video component usage:

```
<Video
  key={videoProps.uri}
  source={{
    uri: videoProps.uri,
  }}
  rate={1.0}
  volume={1.0}
  muted={!canPlay}
  paused={!canPlay || paused}
  resizeMode="contain"
  controls={false}
  onError={(err) => {
    handleError(err);
  }}
  poster={videoProps.posterUri}
  repeat={true}
  onEnd={() => {
    setPaused(true);
  }}
  style={styles.video}
/>
```

## Video sample
Should work with any video. Ours is a very simple and short (60s) MP4.

**Comment by KrzysztofMoch** [comment]
Hey @brianlenz, i was trying to reproduce your issue but i was unable to do it. (I will mark here, that i try to do it on build from master). 

My Component:
```jsx
<Video
   key={videoProps.uri}
   source={{
     uri: videoProps.uri,
   }}
   rate={1.0}
   volume={1.0}
   muted={false}
   paused={false}
   poster={videoProps.posterUri}
   resizeMode="contain"
   controls={true}
   onError={err => {
      handleError(err);
   }}
   repeat={true}
   style={s.video}
/>
```
tested on iPhone 13 iOS 17.0.3

https://github.com/react-native-video/react-native-video/assets/83216158/23db281a-6ef7-4035-90bb-e93d1c78a6bd

**Comment by brianlenz** [comment]
@KrzysztofMoch sorry for the delay! I'm planning to test this on `master` and get back to you. It's definitely an issue on `alpha.8` (making it unusable for us), so it would be great if it were fixed in future alphas. I realize you need more details from me, so I'll get them to you as soon as I can (hopefully this week). We are just in a time crunch leading up to a big launch, so I haven't had time as of yet. Thanks for your patience and understanding! 🙏

**Comment by brianlenz** [comment]
@KrzysztofMoch it looks like the issue is fixed on `master`! I tested on `alpha.7` to confirm everything works as expected (it does). I upgraded to `alpha.8` and confirmed the same issue I described here occurs. Then, I switched to the `master` branch, and everything works! Thus, it appears the issue was in fact already fixed on `master`, and that's the difference between our tests.

I don't know if this makes any difference to you or not, but here's the definition of the `canPlay` variable from the sample code I posted before:

```
const appState = useAppState();
const canPlay = appState === 'active';
```

We're using this to automatically stop the video from playing when the app is backgrounded.

**Comment by Pnlvfx** [comment]
@brianlenz 

I'm still seeing this issue on alpha11, 

    <Video
      style={styles.video}
      source={{
        uri: video,
        type: 'mp4',
        headers: {
          range: 'bytes=0',
        },
      }}
      repeat
      //playWhenInactive={false}
      pictureInPicture={false}
      resizeMode={ResizeMode.COVER}
      paused={videoIsPaused}
      muted
      ignoreSilentSwitch={IgnoreSilentSwitchType.IGNORE}
      volume={0}
      playInBackground={false}

**Comment by vmsilva** [comment]
Same problem with pip here! beta version "react-native-video": "^6.0.0-beta.3",

**Comment by iamksjodha** [comment]
I am facing same problem with pip here.
Beta Version: "react-native-video": "^6.0.0-beta.5".
