### ISSUE TITLE
Android: Old Media Player is used in version 5.2.1 with Autolinking.

### ISSUE THREAD

**Issue by omar-diop** [TheWidlarzGroup/react-native-video#3273]
# Improvement

Using RN >0.60 and autolinking the old Media Player implementation is used even if the library should  use the new ExoPlayer.

I managed to fix it by manually forcing it as stated in the documentation. 

I would like to open a PR in which i edit the README to inform users that with autolinking the old Media Player is used.

## Platform
* Android

## Environment info

Library version: 5.2.1
RN version: 0.71.13

## Steps To Reproduce

1.  Install react-native-video
2. Run on the device

## Expected behaviour

1. react-native-video should work with ExoPlayer

**Comment by freeboub** [comment]
It has been merged, thank you
