### ISSUE TITLE
Large Video on 4gb RAM device played only audio, video black screen

### ISSUE THREAD

**Issue by amserhii** [TheWidlarzGroup/react-native-video#3278]
# Bug

## Platform
* Android

## Environment info

Library version: 6.0.0-alpha.8
react-native 0.71.5
Device: OneNord Plus 4gb RAM 11 Android

## My Code

video.path - local uri video picker by react-native-image-picker

  <Video
          source={{ uri: video.path }}
          repeat={true}
          hideShutterView={true}
          playInBackground
          onLoad={() => {
            setLoaded(true);
          }}
          style={{
            height: height,
            width: width,
          }}
          muted={!played}
          paused={!played}
          resizeMode="cover"
        />

## Expected behaviour

1. Video played with audio

## Video sample
<img width="287" alt="image" src="https://github.com/react-native-video/react-native-video/assets/129414758/eeb890ff-c65f-4613-82a6-1714dcfd481c">

Mp4 2:52m 4k 4gb

**Comment by YINGCHAO-98** [comment]
Hello, have you solved this problem

**Comment by soadtechdev** [comment]
Same problem, any solution?

**Comment by amserhii** [comment]
not solved, Did compression on BE side for videos
