### ISSUE TITLE
why my ios simulator cannot launch the app

### ISSUE THREAD

**Issue by haichongsihao** [TheWidlarzGroup/react-native-video#328]
I want use react-native-video to make app for TV live,I paster my code  in below, i only use the video with one attribution,but it cannot run,the app auto exit

```
import React, { Component } from 'react';
import {
AppRegistry,
StyleSheet,
Text,
View
} from 'react-native';
import Video from 'react-native-video'


class njuTV extends Component {
render() {
return (

<View style={styles.container}>
<Video
style={styles.backgroundVideo} />

</View>
);
}
}

const styles = StyleSheet.create({

backgroundVideo: {
position: 'absolute',
top: 25,
left: 0,
bottom: 0,
right: 0,
},

});

AppRegistry.registerComponent('njuTV', () => njuTV);
```

**Comment by haichongsihao** [comment]
after init the project ,i have installed react-native-video in my project and the project have no error report, I only change is add the <Video/> element  in index.ios.js, and if I delete the <Video/> element  ,everything is OK

**Comment by mattapperson** [comment]
Is it correctly linked?

**Comment by quadsurf** [comment]
it crashes for me to when i use the syntax their docs say to use:
import Video from 'react-native-video';

try putting curly braces around your Video component module... like this:
import { Video } from 'react-native-video';
it should stop crashing after that... but can any one explain to me why this happens? i thought curly braces were if you were just importing a subset of the module, and no curly braces if importing the entire module, no???

**Comment by haichongsihao** [comment]
@mattapperson i already have linked it,the info is below.thanks you reply
![image](https://cloud.githubusercontent.com/assets/5416694/18737012/33c73a20-80bf-11e6-82cf-ebfb7bba1e00.png)

**Comment by mattapperson** [comment]
@haichongsihao what error do you get when it crashes?

**Comment by haichongsihao** [comment]
@quadsurf thanks your reply, after I add curly braces around my Video  component,the simulator don't crashes,but report an another error,like this:
![image](https://cloud.githubusercontent.com/assets/5416694/18737052/b895f1d8-80bf-11e6-9a2d-dda5a6d8fbbc.png)

**Comment by haichongsihao** [comment]
@mattapperson  I don't know how to catch the error,when i launch the app,it crash

**Comment by tioback** [comment]
@haichongsihao looks like you're having curly braces problems. Try testing each of the components you're importing. Either removing from the ones that have, or adding to the ones that don't have. Works every time for me.

@quadsurf no curly braces mean "import default". With curly braces, you may import whatever is being exported by the module.

**Comment by openmynet** [comment]
`<Video>` must set the `source`  attribute,  and to ensure that the value is valid.

``` javascript
  renderVideo(src){
    if (src&&(/^http(s)?:\/\//.test(src)||require(src))) {
      return (
        <Video source={{uri: src}} />
      )
    }
    return (
      <MockVideo/>
    )
  }
```

**Comment by haichongsihao** [comment]
@openmynet I add src,but it still report the same error(got undefined),the background is a local source,I google MockVideo,but get little information,what's the meaning of it?

`class njuTV extends Component {
  render() {
   return (<Video source={{uri: "background"}}/>)
   }
}`

**Comment by tioback** [comment]
@haichongsihao I believe @openmynet meant to suggest you create something to mock the video in case there's no valid source available. Could be an image, or whatever you felt like. `<MockVideo />` is something you yourself can create in the React way. Something like:

```
const MockVideo = () => (<View><Text>No video available</Text></View>);
```

**Comment by haichongsihao** [comment]
@tioback get it,thank you !!!
