### ISSUE TITLE
Video is not showing to full screen in landscape

### ISSUE THREAD

**Issue by HemangiVekaria** [TheWidlarzGroup/react-native-video#3283]
# Bug

I am using this library to play video in screen. I have one video in landscape and when play that in landscape it's not showing in full screen. It shows black space to the start and end. If add resizeMode stretch then video is getting stretched.

## Platform
Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

Library version: 5.2.1
Device: All Devices

I want is to show video in full screen without stretching video

It shows space
![image](https://github.com/react-native-video/react-native-video/assets/17717369/f8056a2b-fdac-4c59-a663-7c3be98046a9)

when set resizeMode="stretch" it looks like this

![image](https://github.com/react-native-video/react-native-video/assets/17717369/aa22a06d-f334-4edc-b3ae-267a9a703119)

**Comment by KrzysztofMoch** [comment]
Hey @HemangiVekaria, did you try use `cover` resizeMode ?

**Comment by HemangiVekaria** [comment]
Hey,

Yes i used cover mode but in that video is getting cut form all side. I can't see full video

**Comment by KrzysztofMoch** [comment]
If I understand you correctly you want to display the video so that it covers the entire screen without "stretching" and without cutting it off (tell me if I understand this wrong) .... But that doesn't seem possible. If you want to cover the whole screen and not stretch it, the video must be cropped so that the video keeps its aspect ratio and is not stretched

**Comment by HemangiVekaria** [comment]
@KrzysztofMoch Yes you understand it correctly. The video must be cropped in which ratio?. Currently have video in 16:9 ratio with 1920x1080 size.

**Comment by KrzysztofMoch** [comment]
To cover whole screen the video need to be same ratio as phone screen

**Comment by HemangiVekaria** [comment]
@KrzysztofMoch Do you have any idea about https://github.com/react-native-video/react-native-video/issues/3272 this issue? can you able to help for this?

**Comment by KrzysztofMoch** [comment]
I will look at it
