### ISSUE TITLE
onVolumeChange event required

### ISSUE THREAD

**Issue by ycdaskin** [TheWidlarzGroup/react-native-video#3293]
Is it possible to add the 'onVolumeChange' event to trigger when the volume value changes?

In my project, multiple videos can be played in different components. Users have to adjust the volume for each video when they start it. I want to store the volume value as a global variable and set it as the initial value for each video player when it's changed in any of them.

I tried to achieve this by creating a ref and an interval function for a video player to periodically get the volume value from the video player's props. However, it always returns the initial volume value, even if I change the volume value from the player controls.

This is necessary when controls={true}. user can change the volume with UI, but application is not informed

```
 useEffect(() => {
        const interval = setInterval(() => {
            if (videoRef.current) {
                const volume = videoRef.current.props.volume
                console.log("volume:", volume)
            }
        }, 1000);
        return () => clearInterval(interval)
    }, [])
```

<img width="125" alt="image" src="https://github.com/react-native-video/react-native-video/assets/41010080/01990fb9-53bd-4703-bf8e-91f730b5d9a1">

**Comment by freeboub** [comment]
Shall be implemented on exoplayer with onVolumeChanged callback : 
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onVolumeChanged(float)

onAVPlayer I think it should be integrated in a similar way like: rate change event (to be confirmed):
        _playerRateChangeObserver = player.observe(\.rate, changeHandler: _handlers.handlePlaybackRateChange)
