### ISSUE TITLE
Native controls detect play or pause

### ISSUE THREAD

**Issue by mezalejandro** [TheWidlarzGroup/react-native-video#3295]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
* Android
* Windows

## Environment info

Library version: ^6.0.0-alpha.8
Device: iPhone 15 pro

## Steps To Reproduce

1. Using native controls I need to detect when the user press play or pause

## Expected behaviour

1. Detect play/pause for analytics using native controls

## Reproducible sample code

```
const onExitFullscreen = () => {
    Orientation.lockToPortrait();
  };

  return (
    <Video
      ref={playerRef}
      source={{uri: props.url}}
      style={styles.container}
      controls
      ignoreSilentSwitch="obey"
      onFullscreenPlayerDidDismiss={onExitFullscreen}
      pictureInPicture={true}
    />
```

**Comment by KrzysztofMoch** [comment]
Hey @mezalejandro, you can use `onPlaybackStateChanged` but for now it is implemented **only for android**. You can try also use `onPlaybackRateChange` - it will be `0` if video is paused and `1` if video is playing

**Comment by KrzysztofMoch** [comment]
Btw just created [PR](https://github.com/react-native-video/react-native-video/pull/3307) that implement `onPlaybackStateChanged` on iOS

**Comment by mezalejandro** [comment]
Hello @KrzysztofMoch thank you!
Another question, do you know why headers are only on android? 
Do you know another way to use it on iOS?
Thanks

**Comment by KrzysztofMoch** [comment]
I know it's sound weird, but cloud you try use headers in iOS ? in code there is implementation 🤷

**Comment by KrzysztofMoch** [comment]
if it doesn't work then you can open a ticket for the feature request
