### ISSUE TITLE
Duration not being reported properly in example

### ISSUE THREAD

**Issue by brentvatne** [TheWidlarzGroup/react-native-video#33]
Always returns `1`, not the actual duration. Any idea what's going on here @johanneslumpe?

**Comment by johanneslumpe** [comment]
In fact I do - fixed with 9900a9c51d84e10f40aeae2512812f94d9d1b64b
I bumped the version to 0.3.4 - `npm publish` that when you get the time :)

Source of this bug: fb6be0e3663a918fdcb130ca6c94ee250348dbea

**Comment by brentvatne** [comment]
@johanneslumpe - doh, should have tested that before merging, my bad. Deployed `0.3.5` which includes your work here and on the seeking branch :smile:
