### ISSUE TITLE
[Q] Does the video downloaded in full length before it's played?

### ISSUE THREAD

**Issue by anniewey** [TheWidlarzGroup/react-native-video#3302]
As I observed UI freeze in step 1 when tapping on the button on the simulator. After a while, the navigation only continues to bring me to new screen with this video player. 

My flow is:
1. Show `<Flatlist/>` with button selection
2. Upon clicking the button, navigate to new screen with this lib component to play the video.

So I was wondering does the player waits for the entire video to complete download before playing it?
If yes, how do I configure to allow buffering while video is playing? Instead of waiting the full length of video to be downloaded.

**Comment by freeboub** [comment]
I think this issue is on the application side. RNV shouldn't block the js thread.
Please review your implementation with flipper first. Each setState is very costly in react native. Without more information or a sample I cannot help more.
