### ISSUE TITLE
-[NSArray(NSKeyValueObserverRegistration) removeObserver:fromObjectsAtIndexes:forKeyPath:] in iOS

### ISSUE THREAD

**Issue by yokesh-n** [TheWidlarzGroup/react-native-video#3308]
# Bug

Following is the crashlytics log found: 
`Fatal Exception: NSInternalInconsistencyException
<UIScrollViewPanGestureRecognizer: 0x10697a350; state = Possible; enabled = NO; delaysTouchesEnded = NO; view = <UIFieldEditor: 0x107047800>; target= <(action=handlePan:, target=<UIFieldEditor 0x107047800>)>>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled. Key path: playbackLikelyToKeepUp Observed object: <AVPlayerItem: 0x281f67ca0, asset = <AVMutableComposition: 0x281dfe120 tracks = ( "<AVMutableCompositionTrack: 0x281de5140 trackID = 1, mediaType = vide, editCount = 1>", "<AVMutableCompositionTrack: 0x281de7b60 trackID = 2, mediaType = soun, editCount = 1>", "<AVMutableCompositionTrack: 0x281ded760 trackID = 3, mediaType = text, editCount = 1>" )>> Change: { kind = 1; } Context: 0x0`

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 5.2.1
Device: iOS 16.6.1

## Steps To Reproduce

1. Play video player

**Comment by freeboub** [comment]
The implementation has been rewritten in swift on V6.0.0 would be interesting to know if it is reproducible on this new branch.
It is understood, this issue comes from crashlytics. 
Thank you for the report

**Comment by yokesh-n** [comment]
I can only see v6.0.0 in alpha stage. May I know when can we expect stable version?

**Comment by KrzysztofMoch** [comment]
@yokesh-n We are in beta now! You can try and check if it's good for you

**Comment by intmain** [comment]
+1
