### ISSUE TITLE
Subtitle is not working in Android

### ISSUE THREAD

**Issue by HarshDev56** [TheWidlarzGroup/react-native-video#3309]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 
 "react-native": "0.72.1",
"react-native-video": "^5.2.1",
Device: Redmi Note 9 Pro (Android 12) & Moto G73 5G (Android 13)

## Expected behaviour

1.  Subtitle Should show

## Reproducible sample code

```Javascript

import Video, { TextTrackType } from 'react-native-video';

  <Video
                ref={(ref) => {
                    this.player = ref
                }}

                textTracks={[
                    {
                        title: 'test',
                        language: 'en',
                        type: TextTrackType.VTT,
                        uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
                        index: 0,

                    },
              
                ]}
                selectedTextTrack={{
                    type: 'title',
                    value: 'test'
                }}
                paused={this.state.paused}
                style={{ width: "100%", height: "100%" }}
                source={{ uri: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8' }} // this is sample video, my actual video file is MP4
                repeat={true}
                resizeMode={this.state.resizeMode}
                controls={true}
                onLoad={this.onLoad}
                onLoadStart={this.onLoadStart}
                onError={this.onError}
               

                subtitleStyle={{ fontSize: 35, color: "black", }}

                seekColor={global.blueColor}
                volume={10}
          

            />
          
```

## Video sample

https://github.com/react-native-video/react-native-video/assets/87370920/c9c42ce8-51d5-4953-bb1d-dfe3bd76dc85

**Comment by freeboub** [comment]
reproduced on V6.0.0-alpha.8

**Comment by LewisAlderman** [comment]
I also cannot get subtitles on Android to work. Tried both v5.2.1 and the v6.0.0-alpha.11.

Having tried VTT and SRT formats, I came across [this issue](https://github.com/react-native-video/react-native-video/issues/1815#issuecomment-563114186) which suggests that perhaps switching the default player from AndroidPlayer => ExoPlayer might be a fix.

**(Expo)**

In my specific case; I'm using a managed Expo workflow, so have been struggling with how to change this setting, although I think it has to do with [BuildProperties](https://docs.expo.dev/versions/latest/sdk/build-properties/), or perhaps more generally a form of [plugin/mod](https://docs.expo.dev/config-plugins/plugins-and-mods/).

Any help/pointers would be appreciated!

**Comment by freeboub** [comment]
@LewisAlderman I was reviewing this issue, and I wonder if it can come from the fact that selectedTextTrack is set before playback start up. would be interesting to decorelate both props.
- Put selectedTextTrack in a state.
- Once you receive onTextTracks callback, update the selectedTextTrack state to apply selected track.

would be great if you can test this proposal

Notice that V6 uses exoplayer by default (Media player support has been dropped)

**Comment by paulrinaldi** [comment]
> I also cannot get subtitles on Android to work. Tried both v5.2.1 and the v6.0.0-alpha.11.
> 
> Having tried VTT and SRT formats, I came across [this issue](https://github.com/react-native-video/react-native-video/issues/1815#issuecomment-563114186) which suggests that perhaps switching the default player from AndroidPlayer => ExoPlayer might be a fix.
> 
> **(Expo)**
> 
> In my specific case; I'm using a managed Expo workflow, so have been struggling with how to change this setting, although I think it has to do with [BuildProperties](https://docs.expo.dev/versions/latest/sdk/build-properties/), or perhaps more generally a form of [plugin/mod](https://docs.expo.dev/config-plugins/plugins-and-mods/).
> 
> Any help/pointers would be appreciated!

It states in the documentation of Expo that exoplayer is the default player. See "Expo uses ExoPlayer implementation by default." within paragraph https://docs.expo.dev/versions/latest/sdk/av/#avplaybacksource. After searching in Google I do not see a way to tell if my expo app is actually running ExoPlayer or not, so I am assuming that I am considering what the docs say.

I am also experiencing this problem. I am also using a managed expo workflow. I've noticed that onTextTracks is getting called in my app 3 times per second of video at least. I've tried VTT and I do however use a `file://...` as the uri (though I have also observed `https://` vtt on a webserver to not display). I've also set subtitleStyle to `{ fontSize: 16, paddingBottom: 50 }`

@freeboub Does Expo truly use ExoPlayer V5 instead of MediaPlayer by default on Android? I can see subtitles on iOS. Is there a way to determine which is being used?

**Comment by freeboub** [comment]
Issue not reproduced on 6.0.0-beta.6 
@paulrinaldi don't reference expo-av documentation, there is nothing related to this package in react-native-video

**Comment by paulrinaldi** [comment]
As for the answer to the last question of mine, if you're debugging in this library, use android debugging and see if a debugging point stops in the exoplayer java files. That should be the simple answer; I have not tried this.
