### ISSUE TITLE
Must stop iOS 10 animated scaling to fill

### ISSUE THREAD

**Issue by JBerendes** [TheWidlarzGroup/react-native-video#331]
To Reproduce:
- use a video that is smaller than the container it will fill
- load and immediately start playing the video

Outcome:
- The video quickly and in an animated way(as if it were zooming in) scales up to fill the space

Preferred: Off by default. Only scale the video to fill when a property has been passed.

Related issue #297

**Comment by mattapperson** [comment]
Closing as dupe of #330
