### ISSUE TITLE
Bandwidth Report doesn't work

### ISSUE THREAD

**Issue by gizomo** [TheWidlarzGroup/react-native-video#3310]
# Bug

1)  bandwidthReport method emits event with object {bitrate: number, height: number, width: number, id: string}. The VideoNativeComponent.ts export OnBandwidthUpdateData as {bitrate: number}
2) bandwidthReport binded to onVideoBandwidthUpdate props callback while Video.tsx waits onBandwidthUpdate

**Comment by freeboub** [comment]
Thank you for the feedback, I include these changes as part of : https://github.com/react-native-video/react-native-video/pull/3304
will be included in 6.0.0-alpha.9
