### ISSUE TITLE
all android device playing no sound

### ISSUE THREAD

**Issue by tianzige666** [TheWidlarzGroup/react-native-video#3313]
# Bug
i change react-native version to 0.72 and install the react-native-video v6.0.0-alpha.8, running on all of my android device and smulator, the video can playing good but no sound , i try to set muted attr to false, its not work for me

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: v6.0.0-alpha.8
Device: google pixel2, huawei, simulator

## Steps To Reproduce
i change react-native version to 0.72 and install the react-native-video v6.0.0-alpha.8, running on all of my android device and smulator, the video can playing good but no sound , i try to set muted attr to false, its not work for me

1.
2.
...

## Expected behaviour

1. when playing video also have sound play

## Reproducible sample code
<Video
        onEnd={onEnd}
        onLoad={onLoad}
        onLoadStart={onLoadStart}
        onProgress={onProgress}
        paused={paused}
        playWhenInactive={true}
        muted={false}
        ref={ref => (videoPlayer.current = ref)}
        resizeMode={resizeMode || 'cover'}
        source={{
          uri: props.url,
        }}
        // repeat
        style={styles.mediaPlayer}
        volume={0.0}
      />
      <MediaControls
        isFullScreen={isFullScreen}
        duration={duration}
        isLoading={isLoading}
        mainColor="rgba(0, 0, 0, 0.5)"
        onFullScreen={!hideFullscreen ? noop : null}
        onPaused={onPaused}
        onReplay={onReplay}
        onSeek={onSeek}
        onSeeking={onSeeking}
        showOnStart={true}
        playerState={playerState}
        progress={currentTime}>
        <MediaControls.Toolbar>
          {/*<View style={styles.toolbar}>*/}
          {/*<Text> </Text>*/}
          {/*</View>*/}
        </MediaControls.Toolbar>
      </MediaControls>

**Comment by tianzige666** [comment]
i fixed it

**Comment by RajeshSenapti** [comment]
could you please share what works for you @tianzige666 ?

**Comment by khushal87** [comment]
@tianzige666 how did you fix it?
