### ISSUE TITLE
Seek leads to crash on iOS

### ISSUE THREAD

**Issue by gizomo** [TheWidlarzGroup/react-native-video#3316]
# Bug

## Platform
* iOS

## Environment info

Library version: 6.0.0-alpha8 #master
Device: ios simulator iPhone 15 Pro

## Steps To Reproduce

1. start play VOD
2. start seek(time)
3. app crashed

## Expected behaviour

1. start play VOD
2. start seek(time)
3. seek ends play resume from new position

![изображение](https://github.com/react-native-video/react-native-video/assets/2512011/4aa3e423-ff94-442f-81fd-a003df52ad1a)

**Comment by freeboub** [comment]
@gizomo Is this reproduced by implementing a resume feature ? (maybe you seek before playback is fully started)
If I check master branch, the crash seems to be in:
        let item:AVPlayerItem? = _player?.currentItem
which doesn't make sense to me ...

**Comment by gizomo** [comment]
> Is this reproduced by implementing a resume feature ? (maybe you seek before playback is fully started)

Nope. Video plays normally after start playing. App is crashed only I try to call seek.

![изображение](https://github.com/react-native-video/react-native-video/assets/2512011/3262dfe8-0746-4622-9a43-a62e958c89fe)

The crash seems to be related to some optional value. I guess 'tolerance'.

**Comment by gizomo** [comment]
I checkout to f85983ba9c57c1e31709b424297d43f858834bad - and seek works fine

**Comment by gizomo** [comment]
I' ve set seekTolerance to 0 and build app. The seek works fine!
Before shift to TS at Video.js argument 'tolerance' of seek callback was optional but with default value 100.
So set default 100 for tolerance will solve seek problem
![изображение](https://github.com/react-native-video/react-native-video/assets/2512011/a0875948-bed6-43e5-b40a-08e1642446fd)

**Comment by freeboub** [comment]
@gizomo thank you very much for your beta testing.
I was able to reproduce the issue on sample, I pushed a fix in this branch: https://github.com/react-native-video/react-native-video/pull/3304
Fix will be available in alpha.9.
Thank you again !
