### ISSUE TITLE
Can't reproduce ads 

### ISSUE THREAD

**Issue by tenet-angelstrizioli** [TheWidlarzGroup/react-native-video#3319]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
* Android
* tvOS
* AndroidTV

## Environment info

Library version: 
- react-native-video@6.0.0-alpha.8
- "react-native": "npm:react-native-tvos@0.71.12-0",
Device: iPhone 15 pro max, Samsung A52, apple TV 4k, chromecast gen 2.

## Steps To Reproduce
Try to add a Video tag with the param adTagUrl and getting params errors. Seems that adTagUrl is not available in VideoProperties. I can't see the property here 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-video/index.d.ts

## Expected behaviour
adTagUrl appears in the VideoProperties and can play ads on my Video.

## Reproducible sample code
<Video
          source={{ uri: asset.url }}
          style={styles.video}
          controls={true}
          onError={handleError}
          fullscreenAutorotate={true}
          fullscreenOrientation="landscape"
          poster={asset.poster}
          ref={ref => {
            this.player = ref;
          }}
          paused={isPaused}
          playInBackground={false}
          ignoreSilentSwitch="ignore"
          onLoad={handleOnLoad}
          adTagUrl={
            'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
          }
        />

Asset url format: m3u8
I've added "$RNVideoUseGoogleIMA=true" on my pod file

**Comment by tenet-angelstrizioli** [comment]
I come from the 5.2.1 version of react-native-video because seeing some post says the new alpha version fix this error but updating the library doesn't work for me, I tried with all alpha versions(from 0 to 8, latest installed) and in all of them I'm getting the same adTagUrl property doesn't exist error

**Comment by freeboub** [comment]
You are right, you must use the last V6 alpha version. I don't understand which error you are talking about. If it is a typescript error, it is due to missing ts support. It will be added in the next alpha version.

**Comment by tenet-angelstrizioli** [comment]
6.0.0-alpha.8 It’s not the latest version?

**Comment by freeboub** [comment]
Yes yes, it means that ts error is normal. But it doesn't explain why ads are not displayed ...

**Comment by tenet-angelstrizioli** [comment]
Because the property doesn’t exist. When I pass adTagUrl to the Video tag doesn’t do anything

**Comment by tenet-angelstrizioli** [comment]
i can make this work with this steps: 
- delete node_modules (i suspect that was version 5.2.1 cached here)
- delete pods
- reintall node_modules then cd ios && pod install
- reboot my devices (physical and emulators)
