### ISSUE TITLE
Can't build react-native app on tvOS with latest version of react-native-video@6.0.0-alpha.8

### ISSUE THREAD

**Issue by tenet-angelstrizioli** [TheWidlarzGroup/react-native-video#3321]
# Bug

## Platform
Which player are you experiencing the problem on:
* tvOS

## Environment info

Library version: 
- react-native-video@6.0.0-alpha.8
- "react-native": "npm:react-native-tvos@0.71.12-0",
Device: 
Apple TV 4k
## Steps To Reproduce
Create a tvOS repo with react native, install react-native-video@6.0.0-alpha.8 version and try to run the app and you should be getting build erros.
We update minimum version to 14.0 and above and we still getting this erros.
## Expected behaviour
App works properly with the latest version of react-native-video in tvOS (iOS/android working fine)

## Image sample
![image (2)](https://github.com/react-native-video/react-native-video/assets/140423003/ba6e0653-ac5c-47bb-8bec-0440dcad1615)
![image (1)](https://github.com/react-native-video/react-native-video/assets/140423003/0453d02f-1831-40dd-9488-d18f22783b17)
![image](https://github.com/react-native-video/react-native-video/assets/140423003/7ac870ba-3567-41ce-bf7f-e6bdd98d9974)

We should patch the library changing this things or it will be a update with this errors corrected?

**Comment by KrzysztofMoch** [comment]
Hey @tenet-angelstrizioli, I was able to reproduce bug 👍
Also checked master build and it is already patched - so it will be fixed by next alpha release (alpha-9)

**Comment by tenet-angelstrizioli** [comment]
So will be closing this issue when alpha-9 is released and tested

**Comment by freeboub** [comment]
alpha.9 has been released ! so let's close this issue
