### ISSUE TITLE
Crash in ios video link mp4 version 6.0.0 alpha 8

### ISSUE THREAD

**Issue by megabeehothanhminh** [TheWidlarzGroup/react-native-video#3325]
static func prepareAsset(source:VideoSource) -> (asset:AVURLAsset?, assetOptions:NSMutableDictionary?)? {
        guard let sourceUri = source.uri, sourceUri != "" else { return nil }
        var asset:AVURLAsset!
        let bundlePath = Bundle.main.path(forResource: source.uri, ofType: source.type) ?? ""
        let url = source.isNetwork || source.isAsset
        ? URL(string: source.uri ?? "")
        : URL(fileURLWithPath: bundlePath)
        let assetOptions:NSMutableDictionary! = NSMutableDictionary()
        
        if source.isNetwork {
            if let headers = source.requestHeaders, headers.count > 0 {
                assetOptions.setObject(headers, forKey:"AVURLAssetHTTPHeaderFieldsKey" as NSCopying)
            }
            let cookies:[AnyObject]! = HTTPCookieStorage.shared.cookies
            assetOptions.setObject(cookies, forKey:AVURLAssetHTTPCookiesKey as NSCopying)
          
            asset = AVURLAsset(url: url!, options:assetOptions as? [String : Any]) // error in here 
        } else {
            asset = AVURLAsset(url: url!)
        }
        return (asset, assetOptions)
    }

**Comment by KrzysztofMoch** [comment]
Could you describe the issue in more detail and include the demo ?

**Comment by megabeehothanhminh** [comment]
<img width="788" alt="Screenshot 2023-10-30 at 17 54 12" src="https://github.com/react-native-video/react-native-video/assets/90604279/3c677264-e04b-477f-881e-01da6afda7ee">

**Comment by megabeehothanhminh** [comment]
> Could you describe the issue in more detail and include the demo ?

<img width="795" alt="Screenshot 2023-10-30 at 17 54 48" src="https://github.com/react-native-video/react-native-video/assets/90604279/ca7ac77d-8255-4cee-9ab3-bf08d80e68cb">

**Comment by megabeehothanhminh** [comment]
sorry, i fixed. Because my link url have accented characters.
