### ISSUE TITLE
Fatal Exception: NSRangeException

### ISSUE THREAD

**Issue by yokesh-n** [TheWidlarzGroup/react-native-video#3328]
# Bug

**Following is the crashlytics log found:**

Fatal Exception: NSRangeException
0   CoreFoundation                 0xec860 __exceptionPreprocess
1   libobjc.A.dylib                0x2bbe0 objc_exception_throw
2   CoreFoundation                 0xf7ccc -[__NSArray0 objectEnumerator]
3   AVKit                          0x3ba34 -[AVMobileChromelessContentTabsViewController _activeContentTab]
4   AVKit                          0x3b940 -[AVMobileChromelessContentTabsViewController scrollViewDidEndDecelerating:]

react-native-video is the only library I can see in my project that is using AVKit, so I suspect this crashlytics log is from react-native-video library

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 5.2.1
Device: iPadOS 17.2.0

**Comment by KrzysztofMoch** [comment]
probably related with #3329

**Comment by KrzysztofMoch** [comment]
Issue not related with react-native-video. Will be fixed with next react-native-screens release
