### ISSUE TITLE
android: resizeMode="cover" doesn't seems to work with portrait video

### ISSUE THREAD

**Issue by mkdotcom** [TheWidlarzGroup/react-native-video#333]
resizeMode="cover" doesn't seems to work with portrait video (it's like "contain")
it does work for landscape video

**Comment by bsiddiqui** [comment]
sounds like it could be related to #330 if you're on iOS 10

**Comment by bsiddiqui** [comment]
@mkdotcom posted a temporary fixe in #330

**Comment by mkdotcom** [comment]
thanks
i'm closing this one, duplicate of #330
