### ISSUE TITLE
Android: Video Continues Playback on source update

### ISSUE THREAD

**Issue by elirichey** [TheWidlarzGroup/react-native-video#3340]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0-alpha.9
Device: Galaxy S23 Ultra

## Steps To Reproduce

1. Use example
2. Add a button that changes video source on click
3. onClick => pause video first
4. useEffect trigger from pause to change source value
6. New video should display paused

## Expected Behavior

1. Video should remain paused. Video auto-plays instead.

**Comment by freeboub** [comment]
Sorry but I don't understand the description.
I double check the basic example, if I 
* start playback
* pause
* do a channel UP
--> video is started in pause, So it looks good to me
