### ISSUE TITLE
Android crash in 6.0.0-alpha.9

### ISSUE THREAD

**Issue by antoinerousseau** [TheWidlarzGroup/react-native-video#3343]
# Bug

## Platform
Android

## Environment info

React Native: 0.71.8
Library version: 6.0.0-alpha.9
Device: Pixel 6a (Android 14)

## Steps To Reproduce

Integrate an autoplay video (see below)

## Expected behaviour

To play the video

## Actual behaviour

When the video is about to start, the app crashes with the following error:

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.shotguntheapp.android.development, PID: 26934
E AndroidRuntime: java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/~~hn6MgOAUK1YfhHkA1D6g1w==/com.shotguntheapp.android.development-4zP9qKyDZ2ycc2YBnj1BsQ==/base.apk)
E AndroidRuntime: 	at com.brentvatne.receiver.AudioBecomingNoisyReceiver.setListener(AudioBecomingNoisyReceiver.java:29)
E AndroidRuntime: 	at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerCore(ReactExoplayerView.java:653)
E AndroidRuntime: 	at com.brentvatne.exoplayer.ReactExoplayerView.-$$Nest$minitializePlayerCore(Unknown Source:0)
E AndroidRuntime: 	at com.brentvatne.exoplayer.ReactExoplayerView$7.run(ReactExoplayerView.java:560)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

## Reproducible sample code

```tsx
<RNVideo
  poster={undefined}
  source={{uri: "https://res.cloudinary.com/shotgun/video/upload/v1699355465/staging/artworks/afterlife-video_sjy9ic.mov"}}
  resizeMode="cover"
  onLoad={handleLoad}
  onProgress={handleProgress}
  // video
  automaticallyWaitsToMinimizeStalling
  controls={false}
  repeat={repeat}
  useTextureView={false}
  maxBitRate={2500000} // 2.5M
  // audio
  disableFocus={true}
  mixWithOthers="mix"
  muted={true}
  // others
  style={{
    flex: 1,
    backgroundColor: "black",
  }}
  paused={false}
/>
```

## Video sample

https://res.cloudinary.com/shotgun/video/upload/v1699355465/staging/artworks/afterlife-video_sjy9ic.mov

**Comment by freeboub** [comment]
Can you give the version of android on the device please?

**Comment by antoinerousseau** [comment]
@freeboub sure sorry, it's Android 14

**Comment by freeboub** [comment]
I am not sure to be able to help without a full sample app. It seems to be linked to androidx dependences.
Did you test with alpha.8 ?
I can point you 2 Prs which may have cause this issue:
https://github.com/react-native-video/react-native-video/pull/3334
https://github.com/react-native-video/react-native-video/pull/3327

I think you should check you use at least kotlinVersion=1.7.0

I am interested to know the solution !

**Comment by antoinerousseau** [comment]
@freeboub I did test with the alpha.8 and it works, so we pinned our dependencies to it in order to release our app (thanks btw for the project!)

in our `android/build.gradle` I see `kotlinVersion = "1.8.0"` in `ext`, not sure what I can try?

**Comment by freeboub** [comment]
@antoinerousseau not sure what is the best way to proceed... I think going to alpha.9 and rolling back the 2 PRs I pointed would be the easiest way to progress. I can also request a sample app which reproduces the issue to help you but I am afraid I will take more time than direct investigations...

**Comment by antoinerousseau** [comment]
Just tried applying #3334 and reverting #3327 and didn't help!

**Comment by freeboub** [comment]
@antoinerousseau are you able to provide a sample ? Or in the basic sample ? I don't know how to investigate more for now 😒

**Comment by freeboub** [comment]
@antoinerousseau Did you find a solution ?

**Comment by ikurowski** [comment]
I had the same error. I changed 

`resolutionStrategy { force 'androidx.core:core:1.8.0' }`

to

`resolutionStrategy { force 'androidx.core:core:1.9.0' }`

in android/app/build.gradle and it worked.

**Comment by antoinerousseau** [comment]
@freeboub sorry I was quite busy, didn't have time to respond

@ikurowski thank you very much, it works! Even with alpha.11 :)
