### ISSUE TITLE
 Cannot find module 'react-native-video'

### ISSUE THREAD

**Issue by alan-nakagiri** [TheWidlarzGroup/react-native-video#3346]
# Bug

Cannot find module 'react-native-video' when running tests and eslint for versions v.6.0.0-alpha9 or alpha10.

It looks like some changes were made to the "main" directory listed in `package.json`. The package.json file points to `lib/index.js` however I do not see a lib directory in the repo when pulling from npm.

Do I need to add something to my config files to resolve this or was the build command not run before publishing?

**Comment by freeboub** [comment]
Hi, someone reports me on slack that the alpha.10 package is not usable. I will try to fix it tonight.
But alpha.9 should be ok.

**Comment by chayin** [comment]
I had this problem with video caching and here is my fix

in `react-native-video.podspec`

```
- ss.source_files = "ios/Video/**/*.{h,m,swift}" "ios/VideoCaching/**/*.{h,m,swift}"
+ s.source_files = "ios/*/**/*.{h,m,swift}"
```

I likewise fixed another video caching issue in `/ios/VideoCaching/RCTVideoCachingHandler.swift`
```
-    func dvAssetLoaderDelegate(loaderDelegate:DVAssetLoaderDelegate!, didLoadData data:NSData!, forURL url:NSURL!) {
+    func dvAssetLoaderDelegate(_ loaderDelegate: DVAssetLoaderDelegate!, didLoad data: Data!, for url: URL!) {
         _videoCache.storeItem(data as Data?, forUri:url.absoluteString, withCallback:{ (success:Bool) in
             DebugLog("Cache data stored successfully 🎉")
         })
      }
```

Plus, `canImport(RCTVideoCache)` doesn't work and i have absolutely no idea.

@freeboub

**Comment by freeboub** [comment]
@alan-nakagiri I Just rebuild alpha.11 with an additional fix to ensure package is properly build.
Test on the sample successfully on ios & android.
Let me know if this is Ok for you

**Comment by freeboub** [comment]
@chayin Thank you very much for the report.
Can we just follow up in this ticket please: https://github.com/react-native-video/react-native-video/issues/3217 
Thank you, and let's close this issue

**Comment by alan-nakagiri** [comment]
@freeboub Looks like the new release works thanks!
