### ISSUE TITLE
onProgress callback is not triggering when playing hls stream on ios 10

### ISSUE THREAD

**Issue by asskovalev** [TheWidlarzGroup/react-native-video#335]
rnv 0.9.0
iphone6 emulator (ios 10)
Video.onProgress callback is not triggering
android OK

issue is actual for variant playlist:

> $ curl http://127.0.0.1:8080/H264.83H50-05a7eac1fa/index.m3u8
> # EXTM3U
> # EXT-X-STREAM-INF:RESOLUTION=2592x1944,CODECS="avc1.4d0032",BANDWIDTH=2052000
> 
> tracks-v1/index.m3u8
> 
> $ curl http://127.0.0.1:8080/H264.83H50-05a7eac1fa/tracks-v1/index.m3u8
> # EXTM3U
> # EXT-X-ALLOW-CACHE:NO
> # EXT-X-TARGETDURATION:6
> # EXT-X-VERSION:3
> # EXT-X-MEDIA-SEQUENCE:38420
> # EXTINF:6.000,
> 
> 2016/09/22/11/57/23-06000.ts
> # EXTINF:6.000,
> 
> ......

monobitrate playlist:

> $ curl http://127.0.0.1:8080/H264.83H50-05a7eac1fa/mono.m3u8
> # EXTM3U
> # EXT-X-ALLOW-CACHE:NO
> # EXT-X-TARGETDURATION:6
> # EXT-X-VERSION:3
> # EXT-X-MEDIA-SEQUENCE:38432
> # EXTINF:6.000,
> 
> 2016/09/22/11/58/35-06000.ts
> # EXTINF:6.000,
> 
> 2016/09/22/11/58/41-06000.ts
> .....

and 'rewindable' playlist:

> $ curl http://127.0.0.1:8080/test-2/index-1474545952-now.m3u8
> # EXTM3U
> # EXT-X-ALLOW-CACHE:NO
> # EXT-X-PLAYLIST-TYPE:EVENT
> # EXT-X-TARGETDURATION:5
> # EXT-X-VERSION:3
> # EXT-X-MEDIA-SEQUENCE:0
> # EXTINF:5.000,
> 
> 2016/09/22/12/05/51-05000.ts
> # EXTINF:5.000,
> 
> 2016/09/22/12/05/56-05000.ts
> ....

but works well with this one:

> $ curl http://127.0.0.1:8080/test-2/index-1474545252-5.m3u8
> # EXTM3U
> # EXT-X-ALLOW-CACHE:YES
> # EXT-X-PLAYLIST-TYPE:VOD
> # EXT-X-TARGETDURATION:5
> # EXT-X-VERSION:3
> # EXT-X-MEDIA-SEQUENCE:0
> # EXTINF:5.000,
> 
> 2016/09/22/11/54/11-05000.ts
> # EXTINF:5.000,
> 
> 2016/09/22/11/54/16-05000.ts
> # EXT-X-ENDLIST

**Comment by jameshartt** [comment]
We're finding on iOS10 that the callbacks are broken entirely. Admittedly we're on a RC of React Native and it could have been broken in there.

But _none_ of the events are being called back on the Video.js class in iOS.

The Obj-C code does use the deprecated `RCTBridge` methods and generally does do a funky (assuming it's just early RN stuff) Object.assign way of binding methods to events.

Would be a considerable refactor to use the newer `RCTEventEmitter` architecture or using `RCTDirectEventBlock`s or `RCTBubblingEventBlock`. I hacked something together along the former lines and it did work. Need to rope in my Android colleagues to get a worthy PR together though.

**Comment by AndrewJack** [comment]
If you are using`0.38.0-rc.0` then this commit may be causing this issue.
https://github.com/facebook/react-native/commit/aa4428cd132bb0d0dbc950b66d3b5f2a3c5b9322

Used in this library at this line - https://github.com/react-native-community/react-native-video/blob/6b62119ce0bacfd990cb6ab3b0486feeb603d2be/ios/RCTVideoManager.m#L19

**Comment by asskovalev** [comment]
Thanks for your reply
I had to change player in my app to ijkplayer because of playback issues with some streams - chinese IP cams sends incorrect SEI which causes even device restarts
Also changed protocol to rtmp for more realtime playback

**Comment by aleklund92** [comment]
Hi!

Really like this library and it has worked great, but we are also experiencing this issue with ios 10.
The onProgress callback isn't working, so we dont have any way of tracking the progress in the video.

Is this issue being worked on? if not, maybe someone could say where the problem most likely occurs and we could make a fix for it and do a pull request  :)

**Comment by AndrewJack** [comment]
#381 should fix this.

**Comment by neegqi** [comment]
i have seem problem too
