### ISSUE TITLE
iOS - Playback stops when returning from a phone call

### ISSUE THREAD

**Issue by habovh** [TheWidlarzGroup/react-native-video#336]
## Issue

Just discovered today that if the video is playing, and you receive a phone call, when you return to the app (either by declining the call, or ending it), the video playback is stopped, and does not start unless the app is exited and launched again.
### Research

I tried other weird cases to see if playback stops when coming back from sleep, notification center or control center, and everything (except receiving a phone call) works great.
### Environment

I discovered the issue under iOS 10.0.1

**Comment by mattapperson** [comment]
This is I think a failing in iOS 10. You need to detect calls yourself and restart playback when a call ends. If there is another workaround I'm yet to find it 😕

**Comment by habovh** [comment]
As it is not a huge deal for me right now, I'm not likely to spend time on a fix for this. I mostly wanted to raise the issue so we can gather information and see if we can identify the problem properly upon fixing it.

**Comment by larryranches** [comment]
I'm also been experiencing this issue for ios. The strange thing is that this isn't happening on Android as it resumes playback when declining or hanging up on a call.

Is this something that's still being looked at being fixed soon?

**Comment by zachrnolan** [comment]
Also experiencing the same issue. I tried looking for a good way to detect phone calls, but haven't found any good solutions for React Native.

Does anyone have any pointers for detecting calls in RN?

**Comment by axelphunter** [comment]
Hey guys, I came across the same problem. I found a solution to this. If you create an AppState listener you can resume the video when the application comes back into the foreground. Docs are here: https://facebook.github.io/react-native/docs/appstate.html. Hope this helps!

**Comment by benvium** [comment]
@axelphunter How did you restart the video? There doesn't seem to be a `resume` method.

**Comment by axelphunter** [comment]
Create a ref on the video player and an AppState listener using the docs I mentioned above. Within the listener do something similar to the following:

```
handleAppStateChange(nextAppState) {
    if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
        if (this.player) {
            this.player.setNativeProps({
                rate: 1
            });
        }
    }
    this.setState({ appState: nextAppState });
}
```

Easy!

**Comment by benvium** [comment]
Thanks @axelphunter!

I ended up using pretty much what you have above except with `setNativeProps({paused: false});`
