### ISSUE TITLE
Component Causes App To Crash

### ISSUE THREAD

**Issue by griffinbaker12** [TheWidlarzGroup/react-native-video#3360]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0 alpha 11
Device:  iPhone 15 Pro Max

## Steps To Reproduce

1. Put some videos in the feed
2. Scroll or click around
3. App crashes
...

## Expected behaviour

1. App not to crash 

## Reproducible sample code

    return <Video
        source={{ uri }}
        style={[
            styles.video,
            dynamicStyles
        ]}
    />

**Comment by freeboub** [comment]
Can you detail the crash please? Crash on js or native side ?

**Comment by griffinbaker12** [comment]
The app freezes when either:
1) Navigating between a feed and thread view which contains a video
2) When scrolling rapidly in the feed

**Comment by freeboub** [comment]
No clue to investigate on that issue...
No call stack, no demo.
This issue will be closed soon
