### ISSUE TITLE
ios 17.2 Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

### ISSUE THREAD

**Issue by kozhinas** [TheWidlarzGroup/react-native-video#3364]
## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-alpha.11
Device: iphone 12
"react-native": "0.66.5",

## Steps To Reproduce

Hello, cant play mp4 stream video, get a error Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager. How fix it? thx

**Comment by kozhinas** [comment]
pods installed

**Comment by kozhinas** [comment]
I saw in the recommendations that you need rn 68+, I’ll try to update and let you know

**Comment by kozhinas** [comment]
updated, still the same error, but I had to install packages from rosetta

**Comment by freeboub** [comment]
look like a linking issue. you should investigate around that.
The best would be having a sample to re create the isssue

**Comment by kozhinas** [comment]
> look like a linking issue. you should investigate around that. The best would be having a sample to re create the isssue

oh this will be difficult, I had to install vlc(
