### ISSUE TITLE
Crash multiple videos into flatlist

### ISSUE THREAD

**Issue by davidgvf** [TheWidlarzGroup/react-native-video#3366]
# Bug
I am using react native video within a flatlist, I have realized that if I go up and down very quickly in the flatlist if I exceed 20 elements, the application crashes and stays stuck. If I remove the video and do the same it never creates

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: v6.0.0-beta.0
Device: 
Iphone 14 pro
## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Reproducible sample code
 <FlatList
                            ref={FlatlistRef}
                            data={feed}
                            windowSize={4}
                            maxToRenderPerBatch={2}
                            initialNumToRender={0}
                            removeClippedSubviews
                            showsVerticalScrollIndicator={false}
                            getItemLayout={getItemLayout}
                            pagingEnabled
                            decelerationRate={'fast'}
                            onViewableItemsChanged={onViewRef.current}
                            viewabilityConfig={viewConfigRef.current}
                            keyExtractor={keyExtractor}
                            refreshControl={refreshControl}
                            ListFooterComponent={
                                isLoading ? (
                                    <View style={{ paddingVertical: 20 }}>
                                        <ActivityIndicator
                                            size={'large'}
                                            color={colors.white.c100}
                                        />
                                    </View>
                                ) : null
                            }
                            renderItem={renderItem}
                        />
                        
                        
                        render item:
                        <Video
                paused={props.paused}
                style={[styles.backgroundVideo, props.styles]}
                resizeMode={props.resizeMode || ResizeMode.COVER}
                source={{
                    uri: internalVideo.uri,
                    type: getTypeVideo(internalVideo.uri)
                }}
                repeat={props.repeat}
                playInBackground={true}
                bufferConfig={
                    props.bufferConfig || {
                        minBufferMs: 125,
                        maxBufferMs: 25000,
                        bufferForPlaybackMs: 120,
                        bufferForPlaybackAfterRebufferMs: 122
                    }
                }
                onBuffer={e => {
                    e.isBuffering !== isBuffering && setIsBuffering(e.isBuffering);
                }}
                onError={e => {
                    console.info('video error: ', e);
                }}
                onLoad={() => setIsLoading(false)}
            />

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
to be followed in https://github.com/react-native-video/react-native-video/issues/2668
