### ISSUE TITLE
Android Video reset to zero if we scroll the video or navigate

### ISSUE THREAD

**Issue by amm4ryous4f** [TheWidlarzGroup/react-native-video#3367]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0 beta 0
Device: 
All android
## Steps To Reproduce

1. Videos are in Flatlist
2. I play one video.
3. scroll down and scroll back to that playing video, it will start playing from 0.
4. even when i pause the video and then scroll down and scroll back to that video, the same case appears.

## Expected behaviour

 When I scroll back to that video it should have playing continuesly.

**Comment by freeboub** [comment]
Did you check if the Video component is unmounted?

**Comment by KrzysztofMoch** [comment]
@amm4ryous4f  Flatlist unmounts elements that are not in viewport. When Video component is unmounted it restarting video state. You can try set [`removeClippedSubviews`](https://reactnative.dev/docs/flatlist#removeclippedsubviews) to false but it will increase memory usage. 

Support for Flatlist is planed in [Roadmap](https://github.com/react-native-video/react-native-video/discussions/3351)

**Comment by freeboub** [comment]
No update, let's close this issue
