### ISSUE TITLE
Error when build with beta.0 version with IMA enable

### ISSUE THREAD

**Issue by maxinminax** [TheWidlarzGroup/react-native-video#3370]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0-beta.0

## Steps To Reproduce

1. enable google ima `RNVUseExoplayerIMA = true`
2. build app
3. error
`error: package com.google.android.exoplayer2.ext.ima does not exist`
`error: package ImaAdsLoader does not exist`

**Comment by avencat** [comment]
I have the same issue on my project, if you want to fix it before this PR is merged you can use `patch-package` to apply the fix on your code: https://github.com/react-native-video/react-native-video/pull/3372

**Comment by avencat** [comment]
My bad my PR wasn't really fixing the issue but this does! 🙂 https://github.com/react-native-video/react-native-video/commit/fa23442268d048c36672901c876275bec80b9956

**Comment by freeboub** [comment]
@maxinminax I just finish another pull request, if you want to have a look at it 🙏

**Comment by freeboub** [comment]
beta.1 has been released. This issue shall now be fixed !
