### ISSUE TITLE
Android - Video is not playing on release apk

### ISSUE THREAD

**Issue by giladartzi** [TheWidlarzGroup/react-native-video#338]
RN 0.34
Using asset system (`source={require('../path/to/video.mp4')}`)
Working great on iOS and Android debug (`app-debug.apk`)
But not working on Android release APK

Any thoughts?

**Comment by jasonfma** [comment]
I'm not seeing it run in debug on my simulator as well. Loading video from a url.

RN `0.34.1`
Android emulator `KitKat`

logcat error

```
09-28 15:28:01.537 2342-2342/appName_redacted E/MediaPlayer: Should have subtitle controller already set
09-28 15:28:01.557 1135-2986/? I/NuCachedSource2: new range: offset= 0
09-28 15:28:01.627 1135-2986/? I/ChromiumHTTPDataSource: Reconnecting...
09-28 15:28:01.667 1135-2986/? I/NuCachedSource2: retrying a previously failed read succeeded.
09-28 15:28:01.667 1135-2987/? E/SoftAVC: Decoder failed: -2
09-28 15:28:01.667 1135-2988/? E/OMXCodec: [OMX.google.h264.decoder] ERROR(0x80001001, -1007)
09-28 15:28:01.667 1135-2989/? I/SoftAAC2: Reconfiguring decoder: 0->22050 Hz, 0->1 channels
09-28 15:28:01.667 1135-2985/? D/AudioSink: bufferCount (4) is too small and increased to 12
09-28 15:28:01.667 2342-2353/appName_redacted E/MediaPlayer: error (1, -2147483648)
09-28 15:28:01.677 2342-2342/appName_redacted E/MediaPlayer: Error (1,-2147483648)
09-28 15:28:02.907 2342-2342/appName_redacted E/MediaPlayer: start called in state 0
09-28 15:28:02.907 2342-2342/appName_redacted E/MediaPlayer: error (-38, 0)
09-28 15:28:02.907 2342-2342/appName_redacted E/MediaPlayer: Error (-38,0)
```

**Comment by youngern** [comment]
The code can't find the video with react native assets. Try putting the video in res/raw/<video-name.mp4> then source={uri:'video-name'}

**Comment by pennyandsean** [comment]
Getting the same thing. res/raw solution didn't work.  Tried [this](https://github.com/facebook/react-native/commit/91ff6868a554c4930fd5fda6ba8044dbd56c8374) also didn't work.  

Getting this in logcat:

10-19 17:04:41.137 29193 29193 W ResourceType: No package identifier when getting value for resource number 0x00000000
10-19 17:04:41.137 29193 29193 W System.err: android.content.res.Resources$NotFoundException: Resource ID #0x0

**Comment by arjan** [comment]
The react packager puts the `.mp4` file in the `drawable-mdpi` folder in the final android package.
To find it there I needed to change [this line](https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L263) to `"drawable"`.

@mattapperson is this a viable fix? I'm happy to submit a PR.
Or should the packager be changed so the video is put in the `raw` folder (which seems more logical to me but requires changes in RN itself)

**Comment by jhen0409** [comment]
@arjan I have already submitted a PR at #429. 😂

**Comment by AndrewJack** [comment]
The main issue here is the react native asset manager placing a video in a drawable folder. It should be placed in the raw or asset directories.

**Comment by chrisknepper** [comment]
Just FYI for anyone who sees `E/SoftAVC: Decoder failed: -2` in logcat and is using a version of Android < 5, this is because [Android only supports the "baseline profile" of H.264 before Lollipop](https://developer.android.com/guide/topics/media/media-formats.html#video-formats) (5.0, API 19), so this error gets output and the video will not be visible or play.

You may re-encode the video with the baseline H.264 profile using a tool like [Handbrake](https://handbrake.fr/) (see attached screenshot).
<img width="1058" alt="screen shot 2017-01-30 at 3 21 42 pm copy" src="https://cloud.githubusercontent.com/assets/4976096/22440101/26947f5a-e700-11e6-81e9-c155fa22d866.png">

Perhaps `E/SoftAVC: Decoder failed: -2` should trigger a `console.warn` so the dev knows that it's a codec problem, not a problem with the library?

**Comment by xiongpinli** [comment]
@pennyandsean   I have the same problem, it's can play but Getting this in logcat:

10-19 17:04:41.137 29193 29193 W ResourceType: No package identifier when getting value for resource number 0x00000000

**Comment by a-morenovalls** [comment]
@chrisknepper you are my hero! That's the solution, after change Main profile to Baseline it works on Android < 23. Thanks!

**Comment by austinsk8s** [comment]
How about a solution to videos loaded via a URL? Works great in dev mode but it's not working for me in release mode...

**Comment by sajorahasan** [comment]
@austinsk8s I'm facing the same issue, if you have found any solution can you please share?
Thank you

**Comment by arya-man** [comment]
I had the same error - video working perfectly fine in debug mode but not in release mode. The issue is that http videos did not work in release, so I made my video links https and it worked like a charm
