### ISSUE TITLE
Getting white notch in android 

### ISSUE THREAD

**Issue by rigi-anubhavgithub** [TheWidlarzGroup/react-native-video#3388]
BUG

My app.js is wrapped with safeareaview, I have given background color black but when navigatiing to child video screen i am hiding status bar after that white notch is visible in video screen

Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 5.2.0
Device: realme

**Comment by freeboub** [comment]
should not be related to react native video. Let me know if there is a way to reproduce. Let's close for now
