### ISSUE TITLE
How to control player from lock screen/Bottom tray iOS and android.

### ISSUE THREAD

**Issue by codesinghanoop** [TheWidlarzGroup/react-native-video#339]
Hi Team,

I am creating a music app so i am not able to control player from lock screen/Bottom tray (iOS) as i am able to see controls in iphone but not able to perform action from there I know there is a code to do in objective c/ swift but i am not finding anything in react native.

In android i am not able to see controls (on lock screen and notification tray).

please let me know how to implement in react native.

Thanks in advance

**Comment by sampurcell93** [comment]
I'd check out [react-native-music-control](https://github.com/tanguyantoine/react-native-music-control). You can bind arbitrary callbacks to lock screen events.

**Comment by dininski** [comment]
Yup, but literally as per [the first issue](https://github.com/tanguyantoine/react-native-music-control/issues/1) in react-native-music-control it has a crippled Android support...

**Comment by sampurcell93** [comment]
Ah! Good point. Sorry about that oversight.

**Comment by cubanjon** [comment]
Hey @codesinghanoop, Any luck with this issue? What did you end up doing?

**Comment by codesinghanoop** [comment]
@jda-dws I end up coding on native side and then bridged both platforms.

**Comment by aakashgolui** [comment]
@codesinghanoop can you give a sample project of this.

**Comment by el-lsan** [comment]
@codesinghanoop Could you please share your solution if it's possible ?

Thanks

**Comment by codesinghanoop** [comment]
@el-lsan @aakashgolui sure, I will share the module with you.

**Comment by singh100ful** [comment]
> @el-lsan @aakashgolui sure, I will share the module with you.

Can you share the module, stuck on this issue for a while ?

**Comment by shawnFallon** [comment]
@codesinghanoop Can you share the module with me as well!

**Comment by MaxJadav** [comment]
@codesinghanoop  @el-lsan  @aakashgolui 
Could you please share your solution if it's possible ?

**Comment by codesinghanoop** [comment]
@shawnFallon @MaxJadav what challenge you are facing to implement ?
