### ISSUE TITLE
No VideoTracks for iOS but Android is fine

### ISSUE THREAD

**Issue by venky145** [TheWidlarzGroup/react-native-video#3390]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version:     "react-native-video": "^6.0.0-alpha.6",

Device:  iPhone 13 mini

## Steps To Reproduce

1. OnLoad callback i dont see any videoTracks except audio/text tracks. Even i noticed there no video tracks passing in OnVideoLoad in RCTVideo(swift file).
`if _videoLoadStarted {
            let audioTracks = RCTVideoUtils.getAudioTrackInfo(_player)
            let textTracks = RCTVideoUtils.getTextTrackInfo(_player).map(\.json)
            onVideoLoad?(["duration": NSNumber(value: duration),
                          "currentTime": NSNumber(value: Float(CMTimeGetSeconds(_playerItem.currentTime()))),
                          "canPlayReverse": NSNumber(value: _playerItem.canPlayReverse),
                          "canPlayFastForward": NSNumber(value: _playerItem.canPlayFastForward),
                          "canPlaySlowForward": NSNumber(value: _playerItem.canPlaySlowForward),
                          "canPlaySlowReverse": NSNumber(value: _playerItem.canPlaySlowReverse),
                          "canStepBackward": NSNumber(value: _playerItem.canStepBackward),
                          "canStepForward": NSNumber(value: _playerItem.canStepForward),
                          "naturalSize": [
                            "width": width != nil ? NSNumber(value: width!) : "undefinded",
                            "height": width != nil ? NSNumber(value: height!) : "undefinded",
                            "orientation": orientation
                          ],
                          "audioTracks": audioTracks,
                          "textTracks": textTracks,
                          "target": reactTag as Any])
        }
        _videoLoadStarted = false
        _playerObserver.attachPlayerEventListeners()
        applyModifiers()
    }
`
2. I need this for bitrates so how do i get bitrates
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by KrzysztofMoch** [comment]
`VideoTracks` are available only for android for now 😕 - you can add this to [Roadmap proposal](https://github.com/react-native-video/react-native-video/discussions/3351) if it isn't there already
