### ISSUE TITLE
`allowsExternalPlayback` missing on `ReactVideoProps`

### ISSUE THREAD

**Issue by fax1ty** [TheWidlarzGroup/react-native-video#3396]
# Bug

https://react-native-video.github.io/react-native-video/component/props#allowsexternalplayback

not presented here
https://github.com/react-native-video/react-native-video/blob/master/src/types/video.ts#L173-L224
but 
https://github.com/react-native-video/react-native-video/blob/master/src/VideoNativeComponent.ts#L271

**Comment by freeboub** [comment]
will be fixed in 6.0.0-beta.2
