### ISSUE TITLE
BUG | Incompatible QOS 

### ISSUE THREAD

**Issue by omerts** [TheWidlarzGroup/react-native-video#3397]
# Bug

## Platform
All platforms

## Environment info

Library version: 1.0.0
Device: Ubuntu 22.04

## Steps To Reproduce
1. Install ROS2 Humble 
2. Stream data from a camera
3. Open the camera stream using a url such as: http://localhost:8080/stream?topic=/base_camera/image_raw&type=ros_compressed
4. The following error shows in console:
```
New subscription discovered on topic '/base_camera/image_raw/compressed', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
```
As a camera is a sensor, modern camera drivers should create a topic with the SENSOR_DATA as the QOS profile, as this is the profile for sensors. 
 

## Expected behaviour

1. Stream should register to the camera topic using the correct QOS profile.

**Comment by freeboub** [comment]
No library version provided. 

Moreover the linked project is not a react native package, I don't know how it will be possible to investigate... Are you sure the issue is in react native video and not in the linked project ?
