### ISSUE TITLE
short videos not playing in ios from remote url

### ISSUE THREAD

**Issue by AdnanAshraf-pro** [TheWidlarzGroup/react-native-video#3400]
Its working fine with videos of length greater than 5 sec but having issue while playing videos with length 2 or 3 seconds .
Facing this issue on IOS device .Its working fine on android .

## Platform

* iOS

## Environment info

Library version: 5.2.1
Device: Iphone 8 (ios 16.7.2)

## Steps To Reproduce

1.Use this link to play video => https://av5.io/TZonWU_20231116_015134-1.mp4
2. Its a 3 sec video and wont play on ios devices 

## Expected behaviour

1.Video shows loading and then blank screen 

## Reproducible sample code

<Video
style={{width:200,height:200}}
 source={{ uri: 'https://av5.io/TZonWU_20231116_015134-1.mp4' }}
/>

## Video sample
https://av5.io/TZonWU_20231116_015134-1.mp4

**Comment by freeboub** [comment]
I think this is a video format issue.
When I use it in the sample, I get following error:
ConverterFactory.cpp:53 unable to find converter that supports given formats
It seems to be a correct H264 file, but fps is 28.814416 dixit vlc, this framerate looks strange to me...
I tested only on emulator

**Comment by AdnanAshraf-pro** [comment]
but the videos of same format with duration longer than 5 sec are playing.
am facing this issue of real ios device .

**Comment by KrzysztofMoch** [comment]
@AdnanAshraf-pro did you try to play it with `6.0.0-beta` version ?

**Comment by AdnanAshraf-pro** [comment]
@KrzysztofMoch  i tried with ```6.0.0-beta-3``` videos of 3 seconds are playing but videos of 1 second are not .. For example [this](https://alive5cdn.s3.amazonaws.com/images/bandwidthattachments/-w11703615134964./ad68f031-8dde-448d-996d-ad3b380290c3/1/20231226_122517.mp4) video ... it continuously shows loading

**Comment by joshbroton** [comment]
I attempted to play a 2s video with 6.0.0-beta-5. It was unsuccessful, but a 4.6s video played just fine.

**Comment by KrzysztofMoch** [comment]
Did you try to set buffer config to make it less then duration of video ? (Not sure if it will help)

**Comment by AdnanAshraf-gol** [comment]
yes i have tried setting buffer config but still not luck

**Comment by freeboub** [comment]
Just tried with the sample on simulator, all provided videos are working with the sample ...

https://alive5cdn.s3.amazonaws.com/images/bandwidthattachments/-w11703615134964./ad68f031-8dde-448d-996d-ad3b380290c3/1/20231226_122517.mp4 or https://av5.io/TZonWU_20231116_015134-1.mp4

Can you clarify if you also have the issue on emulator or is it limited to real devices ?
maybe some props can create the issue ...
This ticket needs to be clarified

**Comment by joshbroton** [comment]
@freeboub I believe this issue should be reopened. The bug was limited to physical iOS devices in our testing.

**Comment by noma4i** [comment]
I face the same issue on real iOS devices

**Comment by noma4i** [comment]
Ensure this bug does not become stale.
