### ISSUE TITLE
Is react-native-video supports HLS video format in android ?

### ISSUE THREAD

**Issue by iasreact1** [TheWidlarzGroup/react-native-video#3402]
Is react-native-video supports Hls video in android ?
or what to do for playing hls video from aws s3 bucket using react-native-video?please help

**Comment by freeboub** [comment]
Yes

**Comment by iasreact1** [comment]
@freeboub  is  there anything extra to add ?

**Comment by freeboub** [comment]
No it should work ...
test in the sample please, this is a sandbox
