### ISSUE TITLE
Cannot resolve symbol 'DRMType'

### ISSUE THREAD

**Issue by bulkinav** [TheWidlarzGroup/react-native-video#3404]
# Bug

In latest release the error `'Cannot resolve symbol 'DRMType'` appears if use this type:

```
import Video, { DRMType, TextTrackType } from 'react-native-video'
```

But worked correctly in react-native-video v6.0.0-alpha.9 (I immediately switched from alpha.9 to beta.1).

## Platform
* doesn't matter

## Environment info

react-native-video v6.0.0-beta.1

**Comment by freeboub** [comment]
Thank you for the report, I confirm this is an unexpected API change between 5.2 and 6.0.
I push a branch to revert the change.
Please see description if you want a workaround. You can also approve the PR if it is ok for you, I will generate a release once merged

**Comment by freeboub** [comment]
change reverted on 6.0.0-beta.2
