### ISSUE TITLE
Video failing to load and play on android (ERROR: Unable to instantiate decoder OMX.qcom.video.decoder.avc)

### ISSUE THREAD

**Issue by manjunath-nuveb** [TheWidlarzGroup/react-native-video#3405]
# Bug
I have a single video component. I get this error when I navigate between screens or when I put the app in the background and then bring it back to the foreground.

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 5.2.1
Device: emultaor

## Steps To Reproduce
Let's say there are 2 pages Home and Video. From Home navigate to Video, Video is playing as expected. go back to Home or put the app in background. 

## Video sample
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by freeboub** [comment]
can you provide a sample please ?

**Comment by freeboub** [comment]
Can you try following patch: https://github.com/react-native-video/react-native-video/pull/3416
It should improve behavior in case of decoder issue
