### ISSUE TITLE
DRM getLicense function is not working properly anymore

### ISSUE THREAD

**Issue by KrzysztofGastolek** [TheWidlarzGroup/react-native-video#3406]
# Bug

Custom `getLicense` function does not work anymore on iOS devices. Function is invoked, but after resolving promise with CKC data, nothing happens. The request is then repeated a couple of times which returns an error (too many retries). 
This function stopped working after 6.0.0-alpha.8 version. I've compared the code and it seems like from alpha 8 to alpha 9 there was a rewrite of the logic. The setLicenseResult function from `RCTVideoManager` now takes `licenseUrl` as an argument. 

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.1
Device: iPhone 11 

## Steps To Reproduce

Declare `getLicense` function and add it as a prop to the video component.

## Expected behaviour

Set license result after resolving promise with CKC data in `getLicense` function.

## Reproducible sample code

Can't give sample code without exposing private data I am using for the player. Happy to help with testing or even make changes to the code and test them myself, just need a suggestion what could be the issue. I do not know switf language and have no experience with writing native code for iOS.

**Comment by freeboub** [comment]
Thank you for the report, This is highly critical for official release.
Would you be able to find a sample on apple web site maybe ?
Thank you

**Comment by KrzysztofGastolek** [comment]
@freeboub 

Unfortunately there is no freely available test content for fairplay DRM. Maybe I could prepare something, but I would rather send this data in private message than post it for everyone to see - hope you'll understand. Are you responsible for this functionality? I think a code comparison between alpha 8 and 9 solution would be enough to find the problem for someone who is fluent in iOS native code.

**Comment by freeboub** [comment]
@KrzysztofGastolek you can have a look to this PR, I this the regression comes from here:  https://github.com/react-native-video/react-native-video/pull/3261/files

**Comment by KrzysztofGastolek** [comment]
@freeboub 

I think I found the error. 

In `ios/Video/Features/RCTResourceLoaderDelegate.swift` function `loadingRequestHandling`

```
 var requestKey: String = loadingRequest.request.url?.absoluteString ?? ""

_loadingRequests[requestKey] = loadingRequest
```

sets loading request under key which in my case is skd://{contentid}

Then in ` setLicenseResult` 

```
guard let loadingRequest = _loadingRequests[licenseUrl] else {
    setLicenseResultError("Loading request for licenseUrl \(licenseUrl) not found", licenseUrl)
    return
}
```

it looks for `loadingRequest` using `licenseUrl` (it's a standard url like https://license-server.url) as a key - does not find it because it is a different value than original requestKey (skd://...) and sets error. For testing purposes I've set requestKey value in both functions to be "aaa" string, and that resolved the issue (video plays normally). So to resolve this issue for requestKey you need to use different value, which is available both in `loadingRequestHandling` and `setLicenseResult` function.

**Comment by KrzysztofGastolek** [comment]
Can anyone confirm this error? @freeboub Have you looked into this?

**Comment by freeboub** [comment]
@KrzysztofGastolek no ... And I will not be available the 2 next weeks

**Comment by kamildryk** [comment]
@freeboub Any update to this issue?

**Comment by freeboub** [comment]
finally done here:  https://github.com/react-native-video/react-native-video/pull/3578
can you please test if this PR fix your issue please ?

**Comment by freeboub** [comment]
pull request merged to master, will be available in beta.6
