### ISSUE TITLE
Not Working with react-native 0.27.2

### ISSUE THREAD

**Issue by waleedarshad-vf** [TheWidlarzGroup/react-native-video#341]

**Comment by apatel-systango** [comment]
I am using react native 0.27.2 and its working can you tell me a specific error you are getting

**Comment by codesinghanoop** [comment]
I am using react native 0.27.2 and its working can you tell me a specific error you are getting

**Comment by waleedarshad-vf** [comment]
@codesinghanoop no errors is displaying screen just remain white or blank. nothing running. logcat shows much information that i am unable to figure out.

debugging in chrome does not show any error :(
what can i do, and did you test it recently? may be latest commit have any issue with 0.27.2

**Comment by waleedarshad-vf** [comment]
I have create project in 0.33.1 and after configuration i got this

JS server already running.
Running adb -s LGH812a6734905 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/waleed/Documents/projects/VideoDemo/android/app/build.gradle' line: 129
- What went wrong:
  A problem occurred evaluating project ':app'.
  
  > Project with path ':react-native-video' could not be found in project ':app'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

https://github.com/waleedarshad-vf/VideoDemo
Let me what i did wrong here

**Comment by waleedarshad-vf** [comment]
OK i missed these lines but after adding these i got just blank screen
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')

https://github.com/waleedarshad-vf/VideoDemo please rectify it if you can

**Comment by waleedarshad-vf** [comment]
Another project https://github.com/waleedarshad-vf/zigTest but got just black screen same is the case with 0.27.2 :(

**Comment by codesinghanoop** [comment]
I think problem is in app/build.gradle (compile "com.facebook.react:react-native:+" change this to compile 'com.facebook.react:react-native:0.27.2')

**Comment by waleedarshad-vf** [comment]
@codesinghanoop 0.27.2 is another thing. it is not working even with 0.33.1. did you try running the above project

**Comment by cobarx** [comment]
Closing since this is very old.
