### ISSUE TITLE
Sometime video does not loads  on IOS  when  i  downloaded video from URL  

### ISSUE THREAD

**Issue by toorandroidmaster** [TheWidlarzGroup/react-native-video#3419]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
## Environment info

Library version: 6.0.0-alpha.11
Device: 
IPhone 13 Pro Max
## Steps To Reproduce

1. I downloaded videos to local storage  and played from local path
2. When my app goes to background state  and after sometime when i opened the app then video throwing error 
3. After kill the app and reopened then video start  loading  perfect 
...

## Expected behaviour

1. videos should play  even i opened the app from background after sometime
2.On Flatlist multiple video rendering issue generating sometime on some video not all

## Sample Demo

https://github.com/react-native-video/react-native-video/assets/41903153/b183bd72-2e25-4b7d-86dd-b19e23085332

**Comment by freeboub** [comment]
A sample is needed to be able to investigate ...

**Comment by toorandroidmaster** [comment]
> A sample is needed to be able to investigate ...

@freeboub  please check video demo

**Comment by freeboub** [comment]
Old ticket, I think this is fixed on last V6.2.0.
Let me know if reproduced on this version

**Comment by freeboub** [comment]
you can also find a flatList integration sample here: https://github.com/freeboub/react-native-video-flatlist-sample
