### ISSUE TITLE
(IOS) App Freeze on handleAVPlayerAccess function [v6.0.0-beta.2]

### ISSUE THREAD

**Issue by douzal34** [TheWidlarzGroup/react-native-video#3424]
# Bug

I'm the developer of the app SoSkills, video sharing app in gaming available on Apple and Android.
I saw there's some updates on this package and i have decided to upgrade it from v6.0.0-alpha.7 to v6.0.0-beta.2 in order to get fix, update and improvment.
After some tests, i have just met one big issue where the app was freezing, note that i let you some screenshots with clear error message, maybe it can help in order to have a stable version.

## Platform
IOS

## Environment info

Library version: v6.0.0-beta.2
Device: Iphone 12 pro max

## Steps To Reproduce

Create a FlatList with some videos, swipe (during the process stop the old video, start the new one and so on). After some swipe the library will crash. I want to let you know one more time that v6.0.0-alpha.7 is working fine.

## Expected behaviour

React Native video not freezing at all
<img width="1792" alt="Screenshot 2023-12-17 at 11 40 57" src="https://github.com/react-native-video/react-native-video/assets/3983160/dd74e7a0-21c6-4c69-89c6-0039fea2bb1e">
<img width="1047" alt="Screenshot 2023-12-17 at 11 41 08" src="https://github.com/react-native-video/react-native-video/assets/3983160/8b9fa08b-bce7-47a7-b3ef-fe1a73a3638d">
<img width="671" alt="Screenshot 2023-12-17 at 17 05 32" src="https://github.com/react-native-video/react-native-video/assets/3983160/eb5d2e06-c2c0-48ff-a95b-fbd6b27b1468">

**Comment by toorandroidmaster** [comment]
i am also facing same error

**Comment by raphaelssampaio** [comment]
Same for me

**Comment by nicolaosm** [comment]
I think thats critical for release @KrzysztofMoch

**Comment by douzal34** [comment]
Any news about it ? @KrzysztofMoch

**Comment by gkueny** [comment]
I tried to reproduce the issue here: https://github.com/gkueny/VideoHandleAVPlayerAccessFreezeReproduction
But unsuccessfully for now.

The issue seem to be that https://developer.apple.com/documentation/avfoundation/avplayeritem/1388499-accesslog can return `nil` and that not handled.

`v6.0.0-alpha.7` do not have the issue because issue has been introduced by https://github.com/react-native-video/react-native-video/commit/9054db35d7d5e4e6d54739fc9349576c03522d7c on `v6.0.0-alpha.10`

https://github.com/react-native-video/react-native-video/pull/3549 should fix the issue. Can you confirm it @douzal34 ?

**Comment by douzal34** [comment]
Hi @gkueny, firstly thanks for checking this issue.

I will check your branch tomorrow and i'll comeback to you !

**Comment by douzal34** [comment]
> I tried to reproduce the issue here: https://github.com/gkueny/VideoHandleAVPlayerAccessFreezeReproduction But unsuccessfully for now.
> 
> The issue seem to be that https://developer.apple.com/documentation/avfoundation/avplayeritem/1388499-accesslog can return `nil` and that not handled.
> 
> `v6.0.0-alpha.7` do not have the issue because issue has been introduced by [9054db3](https://github.com/react-native-video/react-native-video/commit/9054db35d7d5e4e6d54739fc9349576c03522d7c) on `v6.0.0-alpha.10`
> 
> #3549 should fix the issue. Can you confirm it @douzal34 ?

Your branch fix this issue, no more freeze, thanks @gkueny !
I am looking forward to see this fix on the next release @KrzysztofMoch
