### ISSUE TITLE
[bug][Android] duplicate UA bug regression?

### ISSUE THREAD

**Issue by lovegaoshi** [TheWidlarzGroup/react-native-video#3426]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0 beta 2
Device: Android 14 emulator / samsung S21

## Steps To Reproduce

seems like a regression of https://github.com/react-native-video/react-native-video/issues/1616 since v6; the last functional version is 5.2.1.

1. [set a custom header (UA) in the source prop](https://github.com/lovegaoshi/azusa-player-mobile/blob/dev/src/components/background/MainBackground.tsx#L102)
2. monitor the https request with HTTPToolkit
3. here is an example request with the extra UA, ReactNativeVideo/2.12.5 (Linux;Android 14) AndroidXMedia3/1.1.1:
```
METHOD: GET
URL
https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/30/43/1124324330/1124324330_nb3-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1702936104&gen=playurlv2&os=aliovbv&oi=1185180348&trid=f814d3d1a324436bb35e143fc9265429u&mid=0&platform=pc&upsig=0a26a630bcdb0129194b7c50d13dff93&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&f=u_0_0&agrr=1&bw=28250&logo=80000000
HEADERS
Accept-Encoding:
identity
Connection:
Keep-Alive
Host:
upos-sz-mirroraliov.bilivideo.com
Icy-MetaData:
1
referer:
https://www.bilibili.com/
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46
User-Agent:
ReactNativeVideo/2.12.5 (Linux;Android 14) AndroidXMedia3/1.1.1
```

For my purposes I removed https://github.com/react-native-video/react-native-video/blob/master/android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java#L90 to prevent setting this RNV UA at all.

## Expected behaviour

No extra UA

## Reproducible sample code

https://github.com/lovegaoshi/react-native-video/tree/bug-dup-ua, basic example, first video with a custom UA set

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by KrzysztofMoch** [comment]
Hey @lovegaoshi,
I think we can check if headers include "custom" UA and don't add "default" UA in this situation. 
You can open PR for it or I can look into it next week

**Comment by freeboub** [comment]
Will be integrated in 6.0.0-beta.2
