### ISSUE TITLE
iOS: Since Beta 6.0.0-beta.1 specifc HLS Video urls not playing anymore

### ISSUE THREAD

**Issue by Duell10111** [TheWidlarzGroup/react-native-video#3430]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
* tvOS

## Environment info

Library version: 6.0.0-beta.2
Device: iPhone 15 Pro / tvOS Apple TV

## Steps To Reproduce

I adapted the tvOS example in this branch to pull a HLS url from youtubei to play.
https://github.com/Duell10111/react-native-video/tree/video-issues

After opening on iOS Simulator the player loads forever and a NSURLError is thrown.

{"error": {"code": -1102, "domain": "NSURLErrorDomain", "localizedDescription": "You do not have permission to access the requested resource.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 13}

## Expected behaviour

When running the same example on the 6.0.0-beta.0 version the video plays fine.
https://github.com/Duell10111/react-native-video/tree/video-url-test-beta.0

## Reproducible sample code

Repo can be found above in the fork urls.

## Video sample
Video sample url generated in tvos example app

**Comment by nicolaosm** [comment]
Yes, happening with us too on Beta2

**Comment by nicolaosm** [comment]
@Duell10111 Is this happening to secure HLS links only or to public ones too? Can you share one please? Thanks

**Comment by JustJoostNL** [comment]
This is happening for me too on the latest beta. I am using a plain HLS stream.

Example URL: `https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/6057949432001/0b4728f1-e551-49c5-b381-a18e1bc8e1b2/10s/master.m3u8?fastly_token=NjU4NWY1NDlfMjk2OGZiMGExNzg1Njg4N2E4NzQ2MDZiYzA5NjRiNzZjMGM2YTAyZmY3NjA3NmYxNTI2Nzc0MWExODUxYjUzZg%3D%3D` (not sure if valid for a long time)

**Comment by Duell10111** [comment]
> @Duell10111 Is this happening to secure HLS links only or to public ones too? Can you share one please? Thanks

@nicolaosm 
A HLS Link can be generated through the reproduction code base and running the tvOS example app.
The app logs the VideoUrl in the Metro Console.

Here is a example url, but I think this will expire soon. :/

https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1703304759/ei/1wmGZaC0FpnNi9oPmJ65gAE/ip/87.249.132.181/id/5b00bb8ca61435c0/source/youtube/requiressl/yes/xpc/EgVo2aDSNQ%3D%3D/playback_host/rr4---sn-n02xgoxufvg3-2gbz.googlevideo.com/mh/4D/mm/31%2C29/mn/sn-n02xgoxufvg3-2gbz%2Csn-4g5ednsr/ms/au%2Crdu/mv/m/mvi/4/pl/24/hfr/1/demuxed/1/tts_caps/1/maudio/1/initcwndbps/2306250/vprv/1/go/1/mt/1703282709/fvip/3/nvgoi/1/short_key/1/ncsapi/1/keepalive/yes/fexp/24007246/dover/13/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Chfr%2Cdemuxed%2Ctts_caps%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AJfQdSswRAIgEsxOnYrAS1h9tcE1vhYvMBqUG28evxJLzR-0Do8J4JcCIDyfWVozIC1vrNLp4dRMf0Mo7AfgPS_eYlRLL6XfuEuM/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AAO5W4owRAIgbfJQ9eGngNKG_SHzZxFNzdbvn8JEpZFTBvFZ9bWsNZUCIE7ssGMTvH6171kmGsxyOaomIps-tRQRLhZTjXDfLVu3/file/index.m3u8

**Comment by freeboub** [comment]
Hello,
Looks like critical, I don't have time to handle it now, but I highly suspect this change: https://github.com/react-native-video/react-native-video/pull/3384

**Comment by Duell10111** [comment]
> Hello, Looks like critical, I don't have time to handle it now, but I highly suspect this change: #3384

Hi @freeboub,
I reverted the change you mentioned locally in my setup and now it works again.
Seems that already percent encoded url parts get encoded twice which causes the urls to break. :/

Another question is if you a passing an invalid url to the Video Property by containing spaces is it really necessary to fix this on library side.

**Comment by Duell10111** [comment]
You could fix this by first removing percentage encoding and than again add it, but it just looks wrong from my POV. 😂

<img width="834" alt="image" src="https://github.com/react-native-video/react-native-video/assets/1345122/e3592651-fa53-4cc3-9ca8-178f761c78d1">

**Comment by freeboub** [comment]
I will revert it and build a release soon and add a note in documentation

**Comment by Duell10111** [comment]
> I will revert it and build a release soon and add a note in documentation 

Thank you very much 🙏

**Comment by Duell10111** [comment]
@freeboub I created a PR for you, we may only add a note in documentation to that problem.

https://github.com/react-native-video/react-native-video/pull/3440

**Comment by freeboub** [comment]
Thank you for the PR !
It is already merged, I complete the doc with following comment also: https://github.com/react-native-video/react-native-video/pull/3441
Let's include the change in 6.0.0-beta.3
I will build it now.

**Comment by sleekLancelot** [comment]
Hello everyone, please what was the resolution for this. I get this exact same error and it's preventing my videos from auto-playing.
`{"error": {"code": -1102, "domain": "NSURLErrorDomain", "localizedDescription": "You do not have permission to access the requested resource.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 9735}`

**Comment by freeboub** [comment]
@sleekLancelot It was an url issue, ensure you pass encoded url please ! (and you use the last V6.X)

**Comment by YasirAliAlgoace** [comment]
@freeboub  hi brother i am facing same issues same time my video work fine but same time i am getting this error how to fix this issues kindly guide me  {"code": -1102, "domain": "NSURLErrorDomain", "localizedDescription": "You do not have permission to access the requested resource.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 1379}

**Comment by freeboub** [comment]
> @freeboub  hi brother i am facing same issues same time my video work fine but same time i am getting this error how to fix this issues kindly guide me  {"code": -1102, "domain": "NSURLErrorDomain", "localizedDescription": "You do not have permission to access the requested resource.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 1379}
> 

Please give your url and version you use

**Comment by efstathiosntonas** [comment]
hey folks, got this issue today, check if the .ts files in the m3u8 are using a proper path.  Open the m3u8 link on Safari and check the network tab in developer tools. In my case the m3u8 had `video0.ts` instead of the path in the S3 bucket after the bucket url: 

example .m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:9
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:8.566667,
users/LJDJjXPamtggdN/videos/94aa12c486aa6b12/video0.ts <-- this was video0.ts previously
#EXT-X-ENDLIST
```

The browser/react-native-video will look for .ts files in the top domain level (taken from the m3u8 url) so instead of looking at `https://my.bucket.com/users/LJDJjXPamtggdN/videos/94aa12c486aa6b12/video0.ts` it was looking for the .ts file in `https://my.bucket.com/video0.ts` thus throwing the -1102 error.

If you're using `ffmpeg` then you can set the path of the .ts file by appending this to the `ffmpeg` commands: 

`-hls_base_url users/${userId}/videos/${randomId}/ ${outputUri}` (or whatever your paths are)

**Comment by efstathiosntonas** [comment]
@freeboub I realized that this might not be ~the case~ working well between browser/react-native. The .m3u8 works fine on react-native-video if I follow the pattern above but it will break on Safari. 

If I add `users/LJDJjXPamtggdN/videos/94aa12c486aa6b12/video0.ts` in the .m3u8 instead of just `video0.ts` the url is translated as `https://my.bucket.com/users/LJDJjXPamtggdN/videos/94aa12c486aa6b12/video0.ts/users/LJDJjXPamtggdN/videos/94aa12c486aa6b12/video0.ts` on Safari which is really weird. Why the same .m3u8 won't play on Safari but it plays on react-native-video? 🤔 

I've also used an extension on Firefox to play hls streams just in case Safari is masturbating as always but no luck, it throws the same error.

**Comment by efstathiosntonas** [comment]
Just tested with expo-av and it played just fine with just `video0.ts` in the .m3u8.

**Comment by abanobmikaeel** [comment]
Seeing similar issues on latest. An example url I tried was really any MP4 even, 

```json
{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 713}
```

Charles traffic yields the same error basically. Running on iOS 17.5, iPhone 15 Pro Max, 
```jsx
  <Video
    source={{
      uri: 'https://www3.cde.ca.gov/download/rod/big_buck_bunny.mp4',
      type: 'mp4',
    }}
    resizeMode={ResizeMode.COVER}
    fullscreenOrientation="landscape"
    style={styles.video}
    paused={!isPlaying}
    controls={showControls}
    repeat={true}
    onLoadStart={onLoadStart}
    onError={(error) => {
      console.log(error, 'video playback error');
    }}
    onReadyForDisplay={onLoadEnd}
  />
```

```
"react-native-video": "6.3.0",
"react-native-video-controls": "^2.8.1",
```
