### ISSUE TITLE
Android Fullscreen doesn't remove android navigation bar

### ISSUE THREAD

**Issue by tdjlando** [TheWidlarzGroup/react-native-video#3431]
# Bug
Version ^6.0.0-alpha.11
When opening to fullscreen the android navigation bar will not be removed. Even using a package like react-native-navigation-bar-color to hide the bar using hideNavigationBar() the bar persists with default color. Changing nav bar color in native code still persist with default color.

## Platform
Which player are you experiencing the problem on:

* Android

## Environment info

Library version: x.x.x
Device: SM-S908U - 13

## Steps To Reproduce

1. Open fullscreen on android 
2. Android Nav bar persist 
...

## Expected behaviour

1.Open fullscreen
2. nothing shows but the video 

## Video sample

[screenshot.pdf](https://github.com/react-native-video/react-native-video/files/13721736/screenshot.pdf)
[screenshot2.pdf](https://github.com/react-native-video/react-native-video/files/13721737/screenshot2.pdf)

**Comment by KrzysztofMoch** [comment]
Hey, did you try to use [`presentFullscreenPlayer`](https://react-native-video.github.io/react-native-video/component/methods#presentfullscreenplayer) & [`dismissFullscreenPlayer `](https://react-native-video.github.io/react-native-video/component/methods#dismissfullscreenplayer)? [Those are ref functions](https://react-native-video.github.io/react-native-video/component/methods#example-usage)

**Comment by nicolaosm** [comment]
@tdjlando Where you able to fix this using the functions that @KrzysztofMoch recommended above?
I tried on beta 3 and it's fine on my end. Can you try on latest beta please?

**Comment by tdjlando** [comment]
I ended up implementing react-native controls for a workaround. However, let me try it and get back to you all. Thank you

**Comment by YoungYanchi** [comment]
> I ended up implementing react-native controls for a workaround. However, let me try it and get back to you all. Thank you

@tdjlando 

Hello, encountered the same problem when using the default full screen mode. Could you please tell me more about the solution, I would be very grateful! Have you used a custom fullscreen?
