### ISSUE TITLE
Documentation Issue: Docs mention "audioOutput" prop, but not configured in v6.0.0 beta.

### ISSUE THREAD

**Issue by ChristopherGabba** [TheWidlarzGroup/react-native-video#3442]
No reproducible code. Title states details.

Tried using the audioOutput prop, as it would serve a great need in my application, but the Video component does not support it. 

Solution:
Either:
A.) Add the feature to the Video component,
B.) Update docs to reflect actuality.

Hopefully I am not making a stupid mistake. The react-native-video component is working excellently. Want to thank the open source community for this great package..

Thanks,
Chris

**Comment by KrzysztofMoch** [comment]
Fixed, will be available in `6.0.0-beta.4`
