### ISSUE TITLE
When I set prop ignoreSilentSwitch as 'ignore', always show pictureInPicture

### ISSUE THREAD

**Issue by Hanuman-Ghawade** [TheWidlarzGroup/react-native-video#3445]
Bug
I'm trying to create a video player, and when I set prop ignoreSillentSwitch as 'ignore', no matter if prop pictureInPicture is false or not, always show pictureInPicture

Platform
Which player are you experiencing the problem on:

iOS

**Comment by KrzysztofMoch** [comment]
Hey @Hanuman-Ghawade, I wasn't able to reproduce it on `6.0.0-beta.4`

**Comment by Hanuman-Ghawade** [comment]
Hello @KrzysztofMoch Thanks for update but there is no **6.0.0-beta.4** version available.

**Comment by KrzysztofMoch** [comment]
My bad, sorry I mean `6.0.0-beta.3` 😅

**Comment by Hanuman-Ghawade** [comment]
No problem😅. But I have tried on 6.0.0 beta. 3 versions also. but there was a picture in picture showing for seconds after that; it did disappear ,but still the background voice is coming. I have already set playInBackground to false.

**Comment by KrzysztofMoch** [comment]
Huh, cloud you show me your "Video" component ?

**Comment by Hanuman-Ghawade** [comment]
**Here is my video component**
```
        <Video
          ref={ref}
          paused={paused}
          playInBackground={false}
          playWhenInactive={true}
          ignoreSilentSwitch="ignore"
          resizeMode="cover"
          onProgress={x => handleProgress(x)}
          source={{uri: helpfulTipAudio?.url}}
          onLoadStart={() => setIsBuffering(true)}
          onload={() => ref?.current?.seek(ZERO)}
          style={styles.videoContainer}
          onEnd={() => onVideoEndCallback(true)}
        />
```


**Environment info**
Library version: react-native-video : 5.2.1
Device: iOS

**Steps To Reproduce**
1.Start video playing
2.Press the home button
3. Video enters into PIP mode

**Expected behaviour**
1.Start video playing
2.Press the home button
3. Video should be minimised

**Comment by AnsOfficial** [comment]
Hi, tried it on 6.0.0-beta.4, same issue. PIP shows up for a sec and then disappears. this only happens when ignoreSilentSwitch is set to 'ignore'.
Is it marked as Bug (Yet)?
@KrzysztofMoch
