### ISSUE TITLE
react native 0.72.7 & react-native-video 6.0.0-beta.3 Android build failed

### ISSUE THREAD

**Issue by vohoangankhanh** [TheWidlarzGroup/react-native-video#3446]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info
Library version: 6.0.0-beta.3
Device: 

## Steps To Reproduce
android studio => sync => build failed
![image](https://github.com/react-native-video/react-native-video/assets/13093106/ead7c53c-9291-4615-b00b-17d7a5d89778)

**Comment by KrzysztofMoch** [comment]
Hey, @vohoangankhanh - I was not able to reproduce this error with clean app (`npx react-native@0.72.7 init MyApp`)

**Comment by vohoangankhanh** [comment]
because 1 project's private dependency need that lib so I put this one into build.gradle then it's working now `implementation(
"androidx.lifecycle:lifecycle-process:2.6.2"
)`
