### ISSUE TITLE
react native 0.72.7 & react-native-video 5.2.1 Android crash

### ISSUE THREAD

**Issue by vohoangankhanh** [TheWidlarzGroup/react-native-video#3447]
# Bug

after finishing playing video, app crash with this error (logcat)

## Platform
Which player are you experiencing the problem on:
* Android
## Steps To Reproduce
![HOJAvWV - Imgur](https://github.com/react-native-video/react-native-video/assets/13093106/aec2dc45-3e34-4a64-b07c-e3f67a4cf0d2)

<img width="235" alt="image" src="https://github.com/react-native-video/react-native-video/assets/13093106/5a71bd39-c434-4a12-877e-b4c45f3f4472">

**Comment by KrzysztofMoch** [comment]
version `5.2.1` is no more supported - I recommend to use v6

**Comment by mittalkamal29** [comment]
Same issue to me, Did you find any solution for same?

**Comment by tuannguyen1902** [comment]
> version `5.2.1` is no more supported - I recommend to use v6

v6 still Error.  Did you find any solution?

**Comment by KrzysztofMoch** [comment]
Tested with `6.0.0-beta.3` and I am not able to reproduce this crash. @tuannguyen1902 if issue still occurs in latest beta please open new issue.

@vohoangankhanh Sorry but I can't do anything about it as we no longer support version `5.2.1` please use latest beta

**Comment by vohoangankhanh** [comment]
I'm using new architect with legacy component for RNVideo, ver 6 still has this error

**Comment by vohoangankhanh** [comment]
update: this error occur only when I switch to new architect, with old architect it's still working

**Comment by KrzysztofMoch** [comment]
react-native-video does not support new architecture yet
