### ISSUE TITLE
[windows] The fullscreen mode activates native player controls

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#3451]
# Bug
The issue arises when using the fullscreen method on Windows, as the native controls overlay my video player, and this is definitely not ideal for the end user.

The native method is:

```cpp
void ReactVideoView::Set_FullScreen(bool fullScreen) {
  m_fullScreen = fullScreen;
  IsFullWindow(m_fullScreen);

  if (m_fullScreen) {
    Set_Controls(true); // full window will always have transport control enabled
  }
}
```

Specifically, the excerpt:
```cpp
if (m_fullScreen) {
  Set_Controls(true); // full window will always have transport control enabled
}
```
Is there any underlying rationale behind this behavior?

## Platform
Which player are you experiencing the problem on:
- [ ] iOS
- [ ] Android
- [x] Windows

**Comment by KrzysztofMoch** [comment]
Hey @Victor0814gui, but isn't showing controls in full screen the default behaviour ? (can't test it because I don't have windows)

**Comment by ghost** [comment]
I believe so, but only if customizing the controls isn't an option. There are some flows that I've considered, such as:

| without custom controls: | with custom controls: |
| --- | --- |
| The flow works normally as expected: | When exiting fullscreen, the player reverts to native controls: |
| V |  https://github.com/react-native-video/react-native-video/assets/92493696/7742e07b-e5a2-4d1b-b573-39130ab79c3f |

I ran some tests, and what resolved it was this. It seems that the ideal solution would be to use:

```tsx
       ApplicationView view = ApplicationView::GetForCurrentView();
       view.IsFullScreenMode();
```
What would change the screen behavior to fullscreen and not the player, but I believe this would require a more elaborate planning.

For now, I'm using the 'react-native-custom-window' library that adds the 'fullscreen' property to the screen, and this way, I can display my customized controls. However, this doesn't seem very practical to me in terms of multiplatform usage
