### ISSUE TITLE
On Android, this video plays with optimized visuals but no sound, while on iOS, it cannot be played

### ISSUE THREAD

**Issue by john-dududu** [TheWidlarzGroup/react-native-video#3454]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

Library version: 6.0.0-beta.3
Device: iPhone 11, 14 Pro Max, google pixel 6a 

## Reproducible sample code
  <Video
                        source={{
                            uri: 'http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001029/index.m3u8',
                        }}
/>

## Video sample
http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001029/index.m3u8

On Android, this video plays with optimized visuals but no sound, while on iOS, it cannot be played：

{"error": {"code": 1718449215, "domain": "CoreMediaErrorDomain", "localizedDescription": "The operation couldn’t be completed. (CoreMediaErrorDomain error 1718449215.)", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 2619}

**Comment by KrzysztofMoch** [comment]
Hey @john-dududu, link that you provide don't work for me

**Comment by john-dududu** [comment]
> Hey @john-dududu, link that you provide don't work for me

This is an IPv6 link. Does your network support IPv6?

**Comment by KrzysztofMoch** [comment]
Not sure... @freeboub cloud you look here ?

**Comment by Trongtv47** [comment]
I have the same problem
