### ISSUE TITLE
Video shows in debug build. Doesn't show in release [5.2.1] [Android] [RN0.72]

### ISSUE THREAD

**Issue by mhunchojack** [TheWidlarzGroup/react-native-video#3455]
I am having the problem in Android. 

I am trying to load a video from RN Asset System, which works perfectly fine in Debug, but fails in Release Build, shows only a black screen.

I tried:
const videoBackground = require('../assets/1.mp4');
 <Video source={videoBackground} ... />
 
and

 <Video source={require('../assets/1.mp4')} ... />
 
 
 Stuck with this for long, no other solutions on the internet, Need help

**Comment by KrzysztofMoch** [comment]
Hey @mhunchojack, `5.2.1` is unsupported, cloud you try on `6.0.0-beta` ?

**Comment by mhunchojack** [comment]
Yes working fine with 6.0.0-beta. Thank you for help. 

also at first it wasnt able to detect the package.

removing implemenntation from build AND settins.gradle got it going

https://github.com/react-native-video/react-native-video/issues/3203 helped

**Comment by KrzysztofMoch** [comment]
Nice 🙌 as v6 is working, I am closing this issue
