### ISSUE TITLE
Sick play

### ISSUE THREAD

**Issue by uc-asa** [TheWidlarzGroup/react-native-video#346]
I need to play video when click on video progress bar how plz suggest 

![image](https://cloud.githubusercontent.com/assets/16412197/19188493/9f057210-8caf-11e6-9531-e12b98458965.png)

**Comment by cq920702** [comment]
I have the same issue,have you solved this issue?

**Comment by cq0702** [comment]
use seek(seconds)  method
Seeks the video to the specified time (in seconds). Access using a ref to the component

**Comment by uc-asa** [comment]
let videoUrl = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';

<TouchableOpacity activeOpacity={0.9} style={[styles.fullScreen]}  onPress={() => this.toggleCancel ()}>
                    <Video source={{uri: videoUrl}}
                        style={[styles.videopane]}
                        ref="videoPlayer"  // Add this line for get refrence
                        rate={this.state.rate}
                        paused={this.state.paused}
                        volume={this.state.volume}
                        muted={this.state.muted}
                        resizeMode={this.state.resizeMode}
                        onLoad={this.onLoad}
                        onProgress={this.onProgress}
                        onEnd={() => { console.log('Done!') }}
                        repeat={false} 
                    />
                    <View style={styles.paused}>{this.renderPaused()}</View>
                </TouchableOpacity>

```
 //Add slider for slide video
                             <Slider
                            style={styles.progressSlider}
                            onSlidingComplete={this.seekVideo}
                            maximumValue={Math.floor(this.state.duration)}
                            value={Math.floor(this.state.currentTime)}
                            trackStyle={styles.track}
                        />
```

//Add this function for sick video
seekVideo(value) {
        _this.refs.videoPlayer.seek(value);
    }

**Comment by cq0702** [comment]
Yes,it works.Thanks a lot!
