### ISSUE TITLE
[iOS] Display subtitle with HLS and contol={false}

### ISSUE THREAD

**Issue by clementnv** [TheWidlarzGroup/react-native-video#3462]
# Bug
Hello,
I want to display subtitle with HLS video on iOS and `control={false}`.

On iOS if you have `contol={true}` you have a native button that you can select your subtitle (by default no selected sutitle). But when you have `control={false}`, I have no solution to display subtitle on my video.

Maybe there is a way to display it?
Thank you.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.3
Device: iPhone on iOS 16/17

**Comment by KrzysztofMoch** [comment]
Does [`selectedTextTrack`](https://react-native-video.github.io/react-native-video/component/props#selectedtexttrack) prop will work for you ?

**Comment by clementnv** [comment]
Okay, I made a mistake during my test. 
Tahnk's @KrzysztofMoch ! 🙏
