### ISSUE TITLE
Support DRM streams on VisionOS

### ISSUE THREAD

**Issue by KrzysztofMoch** [TheWidlarzGroup/react-native-video#3467]
## Feature Request

Add support for DRM streams in visionOS

## Context

current function `streamingContentKeyRequestData(forApp:, contentIdentifier:, options:)` is deprecated and not supported on visionOS 

## Support

If this functionality is important to you and you need it, contact [TheWidlarzGroup](https://thewidlarzgroup.com) - [`hi@thewidlarzgroup.com`](mailto:hi@thewidlarzgroup.com)

**Comment by freeboub** [comment]
@KrzysztofMoch can we close this issue ?

**Comment by KrzysztofMoch** [comment]
Yes!
