### ISSUE TITLE
Feedback for “Configurable props”

### ISSUE THREAD

**Issue by AmmuRamasubramanian** [TheWidlarzGroup/react-native-video#3473]
### Current behavior
Video is not playing with specific URLs which are actually working good when checked in HLS online player

### Reproduction steps
1.The video actually works perfectly fine when tried with public url..For specific URLs it is not working.This is my video component <Video
            // ref={(ref) => {
            //     player.current = ref
            // }}     
            source={{
                uri: 'https://live-par-2-cdn-alt.livepush.io/live/bigbuckbunnyclip/index.m3u8',
                type: 'm3u8'
            }}
            debug={{
                enable: true,
                thread: true,
              }}
            controls={true}
            style={styles.video}
            resizeMode="contain"
            paused={!isActive}
            onError={(error)=>console.log(error)}  
            onLoad={()=>console.log("loadingggggggggggggggggggggggggggggggggggggg")}
        /> 

### Expected behavior
Describe what you wanted to happen

### Platform
I am facing this problem on Android

### Video sample
Tried with (https://vz-319bb95e-6eb.b-cdn.net/c6e446f6-9533-49ed-a0db-efc3a85fd4f0/playlist.m3u8) which is playing in online player but not in app.I have added include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer') in my settings.gradle.

**Comment by freeboub** [comment]
Did you try to analyze the logcat to understand the issue ?
