### ISSUE TITLE
Installation problem in RN 0.34.1

### ISSUE THREAD

**Issue by mytc** [TheWidlarzGroup/react-native-video#348]
How do I install this module in the latest RN version (0.34.1)? 
In the documentation 

> Note: In react-native >= 0.29.0 you have to edit MainApplication.java
> 
> MainApplication.java (react-native >= 0.29.0)
> 
> On top, where imports are:
> 
> import com.brentvatne.react.ReactVideoPackage;
> Under .addPackage(new MainReactPackage()):
> 
> .addPackage(new ReactVideoPackage())

But the thing is there are no addPackage in the file and I added the package like this:

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ReactVideoPackage()
      );
    }
```

But still not working. 
I tried with manual install without rnpm, but when in **MainActivity.java** file, once again there are no more `.addPackage(new MainReactPackage()):`  , and I don't  how to go on from here. 

By the way, I wonder this module support url from youtube embed url? Or other streaming site iframe url?

**Comment by openmynet** [comment]
``` javascript
react-native link react-native-video
```

**Comment by mytc** [comment]
@openmynet ,
tried, but still not working.

**Comment by openmynet** [comment]
@mytc 

edit /android/settings.gradle

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

edit /android/app/build.gradle

```
dependencies {
    ***
    compile project(':react-native-video')
    ***
}
```

and You need to pay attention #328

**Comment by cobarx** [comment]
@mytc You need to run `react-native link react-native-video` like @openmynet said. Make sure you have the entries in the gradle files that he mentions.
