### ISSUE TITLE
RTSP Support

### ISSUE THREAD

**Issue by AlejandroAguilar99** [TheWidlarzGroup/react-native-video#3481]
I've seen there's a pull request for this subject, tried to apply the required changes manually but didn't have success, when will RTSP streams supported?

**Comment by KrzysztofMoch** [comment]
Support for RTSP is possible only for android and it's on roadmap #3351

**Comment by freeboub** [comment]
feature implemented here : https://github.com/react-native-video/react-native-video/pull/3677
will be available in 6.0.0-beta.9
