### ISSUE TITLE
Programmatic play on iOS: video plays somewhere else when Fabric is enabled and package is being ignored 

### ISSUE THREAD

**Issue by fractalscape13** [TheWidlarzGroup/react-native-video#3482]
# Bug
This bug happens when the app has Fabric (new architecture) enabled, but I am ignoring the video component in my react-native-config.js to allow it to work using the old arch.  (see new renderer interop layer info: https://github.com/reactwg/react-native-new-architecture/discussions/135) 
When using a custom play button, the play button causes the audio track of the video to start playing.  I can then press on the built-in video controls and start the actual video player playing, which makes it so that there are 2 audio tracks of the same video playing at the same time.  I can pause the visible video but the audio track from the mystery video player is still playing in the background.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info
Freshly created rn app: 
npx react-native@latest init TestProject

Library version: 
"react-native": 0.73.2
"react-native-video": ^5.2.1

Device: Physical iPhone 14, simulator iPhone 15, simulator iPhone 15 Pro

## Steps To Reproduce
1. Init new React Native app: npx react-native@latest init TestProject
2. Enable Fabric (new architecture): cd ios && bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
3. Add react-native-video package: yarn add react-native-video
4. Pod install: cd ios && pod install
5. Add react-native.config.js file to ignore video package since it is not supported by new arch/fabric:
module.exports = {
  project: {
    android: {
      unstable_reactLegacyComponentNames: [
        "Video", // react-native-video
      ],
    },
    ios: {
      unstable_reactLegacyComponentNames: [
        "Video", // react-native-video
      ],
    },
  },
};
6. Run app: yarn ios

## Expected behaviour

1. Clicking on custom "play" button sets useState hook "videoPlaying" to true, which unpauses the video: paused={!videoPlaying}
2. Clicking on custom "play" button sets useState hook "initialPlayPressed" to true which hides the button
3. Video should be playing with no custom button visible

## Reproducible sample code
App.tsx
```

import React, {useState} from 'react';
import {
  SafeAreaView,
  Text,
  TouchableOpacity,
} from 'react-native';
import Video from 'react-native-video';

function App(): React.JSX.Element {
  const [videoPlaying, setVideoPlaying] = useState<boolean>(false);
  const [initialPlayPressed, setInitialPlayPressed] = useState<boolean>(false);
  const handlePlay = () => {
    setInitialPlayPressed(true);
    setVideoPlaying(true);
  };
  return (
    <SafeAreaView
      style={{
        height: '100%',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <Video
        source={{
          uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        }}
        resizeMode="cover"
        controls={initialPlayPressed}
        paused={!videoPlaying}
        style={{
          height: '85%',
          width: '95%',
          borderWidth: 1,
        }}
      />
      {!initialPlayPressed && (
        <TouchableOpacity
          onPress={handlePlay}
          style={{
            position: 'absolute',
            top: '55%',
            zIndex: 99,
            borderWidth: 5,
            padding: 10,
            borderColor: 'red',
            borderRadius: 99,
            backgroundColor: 'white',
          }}>
          <Text style={{fontSize: 30}}>PLAY</Text>
        </TouchableOpacity>
      )}
    </SafeAreaView>
  );
}

export default App;

```

## Video sample

https://github.com/react-native-video/react-native-video/assets/45412175/d50890ad-0af0-480b-8708-1842547a2de0

**Comment by KrzysztofMoch** [comment]
Cloud you test v6 beta ?

**Comment by fractalscape13** [comment]
6.0.0-beta.4 ?

**Comment by KrzysztofMoch** [comment]
Yes

**Comment by fractalscape13** [comment]
i believe the verison upgrade has solved the issue

**Comment by fractalscape13** [comment]
v6 beta works on ios but causes android to immediately crash

**Comment by KrzysztofMoch** [comment]
Okay, will look at it

**Comment by KrzysztofMoch** [comment]
Hey issue seems to be fixed in latest version - I have tested android and iOS and they worked. I will close this one, but if issue still persist please let me know
