### ISSUE TITLE
Audio channel from video keeps playing after reload

### ISSUE THREAD

**Issue by enfipy** [TheWidlarzGroup/react-native-video#3483]
# Bug

This is similar to [this issue](https://github.com/react-native-video/react-native-video/issues/107) that occurs on versions `5.2.1` and `6.0.0-beta.4` of `react-native-video`.

The audio keeps playing even after reloading.

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.4 and 5.2.1
Device: iPhone 12, iOS 16.6.1
Expo Dev Client version: 2.4.2
Expo SDK: 49

## Steps To Reproduce

1. Init empty Expo project.
2. Add `react-native-video` package.
3. Add this code that results in the described issue:
```tsx
<Video
	paused={false}
	mixWithOthers="duck"
	ignoreSilentSwitch="ignore"
	source={{ uri: "https://i.imgur.com/k8NQpGl.mp4" }}
	repeat
	muted={false}
	resizeMode="cover"
/>
```

## Expected behaviour

1. Stop audio on reload.

## Reproducible sample code

```tsx
<Video
	paused={false}
	mixWithOthers="duck"
	ignoreSilentSwitch="ignore"
	source={{ uri: "https://i.imgur.com/k8NQpGl.mp4" }}
	repeat
	muted={false}
	resizeMode="cover"
/>
```

## Video sample

https://imgur.com/gallery/1MDB2D4

**Comment by freeboub** [comment]
I think this should be fixed on 6.2.0. I will close the issue, let me know if I need to reopen ot
