### ISSUE TITLE
In  iOS, playing a video in m3u8 format only has sound but no picture

### ISSUE THREAD

**Issue by john-dududu** [TheWidlarzGroup/react-native-video#3484]
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: last version
Device: iPhone 14 Pro Max

## Video sample

 http://38.96.178.201/live/Disney/index.m3u8

If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by KrzysztofMoch** [comment]
Your stream does not work for me for any player I tried...

**Comment by john-dududu** [comment]
> Your stream does not work for me for any player I tried...

on android is ok, you can try in safari. 

You can try accessing it directly in Safari, but there is only sound without video

**Comment by KrzysztofMoch** [comment]
Hmm... Maybe it's issue with stream if it isn't working in safari ?

**Comment by nicolaosm** [comment]
Video stream link not working on safari browser on Mac or iOS. So probably issue is with the stream itself.

**Comment by alexcwikla** [comment]
Try that one. Adjust key_int and G to be twice your FPS 

`#!/bin/bash

# Define the input file and base output file path
INPUT_FILE="input.mp4"
BASE_OUTPUT_FILE="output"

# Define the resolutions
resolutions=("640x360" "854x480" "1280x720" "1920x1080" "2560x1440" "3840x2160")
fragmented_files=()

# Loop over each resolution
for R in "${resolutions[@]}"; do
    echo "Encoding for resolution: $R"
    encoded_file="${BASE_OUTPUT_FILE}_${R}.mp4"
    fragmented_file="${BASE_OUTPUT_FILE}_${R}_fragmented.mp4"

    # Encode video with specified aspect ratio and starting from time zero
    ffmpeg -i "$INPUT_FILE" -s "$R" -c:v libx265 -aspect 16:9 -ss 0 -keyint_min 50 -g 50 -sc_threshold 0 -force_key_frames 'expr:gte(t,n_forced*2)' -hls_flags split_by_time "$encoded_file"
    
    # Fragment video
    mp4fragment --fragment-duration 2000 "$encoded_file" "$fragmented_file"

    # Append to the list of fragmented files for HLS conversion
    fragmented_files+=("$fragmented_file")
done

# Convert all fragmented files to HLS in one step
if [ ${#fragmented_files[@]} -eq 0 ]; then
    echo "No fragmented files found."
else
    mp4dash --hls --use-segment-timeline -o "${BASE_OUTPUT_FILE}_hls" "${fragmented_files[@]}"
    echo "HLS conversion complete for all resolutions."
fi
`

**Comment by castdrian** [comment]
yeah this happens to us as well, hls streams sometimes play with video on ios but 90% just sound

**Comment by crewtaylorfd** [comment]
Seeing this as well
