### ISSUE TITLE
onLoad() never get called for exoplayer but if I use default player then only black screen with sound.

### ISSUE THREAD

**Issue by ckswopnera** [TheWidlarzGroup/react-native-video#3485]
for version 5.2.1 if I use default player then video sometimes was playing but black screen only the audio was coming. but if I use exoplayer then onload() never get called.  I also tried to do manual linking but no progress.

**Comment by KrzysztofMoch** [comment]
version 5.2.1 is deprecated and is no longer supported - I encourage you to test v6

**Comment by ckswopnera** [comment]
> version 5.2.1 is deprecated and is no longer supported - I encourage you to test v6

But my react native version is 0.67.2

**Comment by KrzysztofMoch** [comment]
Unfortunately I can't do anything about it. It is recommended to update react-native https://github.com/reactwg/react-native-releases
