### ISSUE TITLE
onPictureInPictureStatusChanged isActive called twice

### ISSUE THREAD

**Issue by nick-mccomb-easygo** [TheWidlarzGroup/react-native-video#3501]
# Bug
When changing `pictureInPicture` to `true` `onPictureInPictureStatusChanged` is called and `isActive` is `true`.

When exiting PIP mode (by pressing the restore button on the PIP video) `onPictureInPictureStatusChanged` is called and `isActive` is `false`.

Then, straight away, `onPictureInPictureStatusChanged` is called and `isActive` is `true`, even though the video is not in PIP mode.

How to stop `onPictureInPictureStatusChanged` firing twice when `pictureInPicture` is set to `false`?

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.4
Device: iPhone 15 Pro Max (real device)

## Steps To Reproduce

1. Make video go into PIP mode by setting `pictureInPicture` to `true`
2. Make video return from PIP mode by pressing the restore button on the PIP video
3. Observe the `isActive` prop in `onPictureInPictureStatusChanged` (it fires twice)

## Expected behaviour

1. `onPictureInPictureStatusChanged` should fire once when video goes into PIP mode and `isActive` should be `true`
1. `onPictureInPictureStatusChanged` should fire once when video goes out of PIP and `isActive` should be `false`
1. `onPictureInPictureStatusChanged` should not be called again (until `pictureInPicture` is set to true again)

**Comment by gkueny** [comment]
I reproduce the issue too.
I will try to investigate what happen

**Comment by gkueny** [comment]
See https://github.com/gkueny/PiPStatusChangedFireTwice for reproduction.

I have a fix. I will submit a PR this weekend

**Comment by gkueny** [comment]
@KrzysztofMoch fixed by https://github.com/react-native-video/react-native-video/pull/3601

**Comment by KrzysztofMoch** [comment]
Thanks ❤️, let's close
