### ISSUE TITLE
iOS - Picture in picture preventing video instances being released after unmount, eventually crashes

### ISSUE THREAD

**Issue by james-cohen** [TheWidlarzGroup/react-native-video#3505]
# Bug

I am using a VirtualizedList to show videos. In my code, the video component is only mounted if its list item is in view - the item above and below show an Image preview. Consequently, there is only one Video player instance mounted at any one time.

However, after swiping down the list approximately 10 times (the exact number varies), the video player crashes and I get this error:

```
Error Domain=AVFoundationErrorDomain Code=-11819 "Cannot Complete Action" UserInfo={NSLocalizedRecoverySuggestion=Try again later., NSLocalizedDescription=Cannot Complete Action, NSUnderlyingError=0x283cf3d80 {Error Domain=NSOSStatusErrorDomain Code=-16978 "(null)"}}
```

I have found this error occurs when the maximum number of AV instances is breached on iOS. The same issue has been raised in [another bug report](https://github.com/react-native-video/react-native-video/issues/3399) where the author proposed this solution which solves the issue:

>After looking into this for a while i noticed that the issue is caused by the PIP IOS support. I managed to fix the issue on the latest releases by commenting this line on native as I was not using PIP: 
https://github.com/react-native-video/react-native-video/blob/01d7bedb4160a2be55708d45721eb7b12407519d/ios/Video/RCTVideo.swift#L143

When this line is commented out, the problem goes away. So there is something about PIP that is prevent video instances from being released, even if PIP is not in use.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.4 (has been an issue in all 6.0.0 beta versions
Device: iPhone 11, iOS 17. Also iPhone 15 simulator, iOS 17

## Steps To Reproduce

1. Create a FlatList and mount a Video instance on each list item
2. Hide the Video instance when the list item is not in view
3. Scroll through the list
4. Video crashes

## Expected behaviour

1. Video player does not crash

**Comment by KrzysztofMoch** [comment]
I will try to fix this - this also should allow us to fix memory leak 🙌

**Comment by KrzysztofMoch** [comment]
Hey @james-cohen I have created PR, but cloud test if it work for you ?
Here is patch:
```diff
diff --git a/node_modules/react-native-video/ios/Video/RCTVideo.swift b/node_modules/react-native-video/Video/RCTVideo.swift
index 2fd5db9..a46341e 100644
--- a/ios/Video/RCTVideo.swift
+++ b/ios/Video/RCTVideo.swift
@@ -140,7 +140,14 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
         _eventDispatcher = eventDispatcher
 
         #if os(iOS)
-            _pip = RCTPictureInPicture(self._onPictureInPictureStatusChanged, self._onRestoreUserInterfaceForPictureInPictureStop)
+            _pip = RCTPictureInPicture(
+                { [weak self] in
+                    self?._onPictureInPictureStatusChanged()
+                },
+                { [weak self] in
+                    self?._onRestoreUserInterfaceForPictureInPictureStop()
+                }
+            )
         #endif
 
         NotificationCenter.default.addObserver(
@@ -193,6 +200,7 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
     deinit {
         NotificationCenter.default.removeObserver(self)
         self.removePlayerLayer()
+        _pip = nil
         _playerObserver.clearPlayer()
     }
 
@@ -531,6 +539,7 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
             } else {
                 _pictureInPictureEnabled = false
             }
+
             _pip?.setPictureInPicture(pictureInPicture)
         #endif
     }
```

**Comment by james-cohen** [comment]
Apologies, I've been away for the past week so haven't been able to test. Unfortunately this hasn't worked, I updated to the newest beta release without the patch and the problem has returned

**Comment by nicolaosm** [comment]
@KrzysztofMoch Issue still happening on my end too on Beta 5 :(

**Comment by bilal-korir** [comment]
Hi Nicola, the same was happening on my side, with beta 5 and 6. Commenting out these lines seems to work for me, not sure why, give it a shot. Check code at line 144. @nicolaosm 

```
// #if os(iOS)
//    _pip = RCTPictureInPicture({ [weak self] in
//      elf?._onPictureInPictureStatusChanged()
//   }, { [weak self] in
//       self?._onRestoreUserInterfaceForPictureInPictureStop()
//   })
// #endif
```
