### ISSUE TITLE
google promises install issue 

### ISSUE THREAD

**Issue by YLbobo** [TheWidlarzGroup/react-native-video#3507]
Installing PromisesObjC (2.3.1)

[!] Error installing PromisesObjC
[!] /usr/bin/git clone https://github.com/google/promises.git /var/folders/93/6154_ksx6ydg0kd03r7zxcj40000gn/T/d20240130-51230-k12phj --template= --single-branch --depth 1 --branch 2.3.1

Cloning into '/var/folders/93/6154_ksx6ydg0kd03r7zxcj40000gn/T/d20240130-51230-k12phj'...
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 7890
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

cd iOS  然后pod install，一直失败，Xcode版本 14.2.

**Comment by KrzysztofMoch** [comment]
I think it's issue with your firewall, it's working for me 🤔

**Comment by YLbobo** [comment]
和防火墙没有关系的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "react-native-video/react-native-video"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 晚上7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [react-native-video/react-native-video] google promises install issue  (Issue #3507)





 
I think it's issue with your firewall, it's working for me 🤔

**Comment by freeboub** [comment]
> 和防火墙没有关系的。
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "react-native-video/react-native-video"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年1月30日(星期二) 晚上7:30
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [react-native-video/react-native-video] google promises install issue  (Issue #3507)
> 
> 
> 
> 
> 
>  
> I think it's issue with your firewall, it's working for me 🤔
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


Please translate before putting some comment...
