### ISSUE TITLE
Property 'play' does not exist on type 'VideoRef'

### ISSUE THREAD

**Issue by ascot21** [TheWidlarzGroup/react-native-video#3508]
# Bug

I get the error `Property 'play' does not exist on type 'VideoRef'` when trying to use videoRef.current.play();

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

Library version: 6.0.0-beta.4
Device: iOS

## Steps To Reproduce
Use the `.play()` function as outlined in the official docs. https://react-native-video.github.io/react-native-video/component/methods#play

## Expected behaviour

Expect to be able to call .play() and for the video to start playing.

## Reproducible sample code

```typescript
const videoRef = useRef<VideoRef>(null);
 
const someCoolFunctions = async () => {
  if(!videoRef.current) {
    return;
  }
 
  // pause or play the video
  videoRef.current.play();
};
 
return (
  <Video
    ref={videoRef}
    source={{ uri: 'https://www.w3schools.com/html/mov_bbb.mp4' }}
  />
);
```

## Notes

I can't find the play function in the source code. Was it ever implemented? Maybe it was removed? Not sure why it'd be in the docs but not the code.

Thanks!

**Comment by KrzysztofMoch** [comment]
Hey @ascot21 there is mismatch in docs... it should be `resume` in stand of `play` - made PR to update docs
