### ISSUE TITLE
android获取总时间的方法： playableDuration seekableDuration

### ISSUE THREAD

**Issue by ycg520520** [TheWidlarzGroup/react-native-video#351]
在android上开发获取file开头的本地视频总时间修改方法
[详见：http://coding.imooc.com/learn/questiondetail/2553.html](http://coding.imooc.com/learn/questiondetail/2553.html)

**Comment by jan-happy** [comment]
I also had to use this fix to get the playableDuration right on Android...

**Comment by jan-happy** [comment]
Why is there still no fix for this? seekableDuration is totally unusable on Android.

**Comment by poberwong** [comment]
You can get total time named "duration" in params of callback function "onLoad"

**Comment by cobarx** [comment]
This has been fixed in 2.1.0
