### ISSUE TITLE
IOS 返回上个页面，video组件无法被销毁，后台还有声音，

### ISSUE THREAD

**Issue by duansailong** [TheWidlarzGroup/react-native-video#3510]
# Bug
In video playback, when clicking the button to return to the previous page, the sound continues playing. The sound only pauses after sliding the bottom navigation of the Apple device. This issue does not occur on Android devices or most iOS devices. This issue has only been identified on iPhone 12 at the moment.
视频播放中，点击按钮返回上个页面，声音还在播放，滑动一下苹果底部导航后声音才能暂停。Android设备和大部分ios设备是好的，

## Platform
* iOS

## Environment info

Library version: 5.2.1
Device: iphone12   iOS 15.3.1  

>The method in the iOS native code was also executed but didn't take effect.

https://github.com/react-native-video/react-native-video/assets/23208491/00d20dba-be1f-4182-9b1e-7eac69aa6979

- (void)dealloc
{
  [[NSNotificationCenter defaultCenter] removeObserver:self];
  [self removePlayerLayer];
  [self removePlayerItemObservers];
  [_player removeObserver:self forKeyPath:playbackRate context:nil];
  [_player removeObserver:self forKeyPath:externalPlaybackActive context: nil];
}

## Video sample
   <Video
            source={{
              uri:'https://vjs.zencdn.net/v/oceans.mp4',
            }}
            style={videoStyle}
            paused={false}
            muted={false}
            pictureInPicture={false}
            ignoreSilentSwitch={'ignore'}
            onEnd={() => {
              Alert.alert('Done!');
            }}
          />

**Comment by KrzysztofMoch** [comment]
I can only accept the issue in English. 🙏 Please create a new one!

**Comment by chenqi777** [comment]
I also encountered this problem. It will appear in iOS 15, but there is no problem in iOS 17. I can only manually call the pause() method to pause playback when the component is unmounted. This problem still exists in version 6.0.0-beta.5
