### ISSUE TITLE
How to customize the method of getting data from server

### ISSUE THREAD

**Issue by 1871847400** [TheWidlarzGroup/react-native-video#3511]
# Feature Request
Custom loader

## Why it is needed
when video fragment is encryptd with base64 or others, I need decrypt it before load.

### Code sample  ----from hls.js document
loader: customLoader,
fLoader: customFragmentLoader,
pLoader: customPlaylistLoader,

class pLoader extends Hls.DefaultConfig.loader {
  constructor(config) {
    super(config);
    var load = this.load.bind(this);
    this.load = function (context, config, callbacks) {
      if (context.type == 'manifest') {
        var onSuccess = callbacks.onSuccess;
        callbacks.onSuccess = function (response, stats, context) {
          response.data = process(response.data);
          onSuccess(response, stats, context);
        };
      }
      load(context, config, callbacks);
    };
  }
}

**Comment by freeboub** [comment]
It is not possible for now.
we cannot send all video data to JS, it will cause performances issues. As it seems to be a very specific request, I advise you to implement it in your own fork.
BTW, in my knowledge, I don't think this is possible on ios
