### ISSUE TITLE
Error while changing video source (with DRM)

### ISSUE THREAD

**Issue by kamildryk** [TheWidlarzGroup/react-native-video#3512]
# Bug

When a `Video` component is initialized it works correctly, however when I try to change video source taking another source from the list in my app, it throws this kind of error:

![react-native-error](https://github.com/react-native-video/react-native-video/assets/97893340/c7072bb0-4a32-46ff-abbb-0923431cf7d5)

The problem showed up after update from version 5 to 6.0.0-alpha-3 but I tested it also on 6.0.0-beta.4 and it fails in the same way.

Rerender `Video` component whenever video source is changed solve this problem in some way but it creates problems with performance. Probably it also create another MediaCodec instance which crash whole app on some android devices.

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

Library version: 6.0.0-beta.4
Device: Samsung Galaxy A14, Realme 8

## Steps To Reproduce

Change dynamically value in 'source' prop.

## Expected behaviour

Load another video source.

**Comment by KrzysztofGastolek** [comment]
Any updates on this issue?

**Comment by freeboub** [comment]
can it be a duplicate of https://github.com/react-native-video/react-native-video/issues/3082 ?

**Comment by kamildryk** [comment]
Yes, I've checked and removing this part of the code solve the problem
![image](https://github.com/react-native-video/react-native-video/assets/97893340/217fa925-7ecf-4d60-aeb6-4850f67ed8bd)

**Comment by kamildryk** [comment]
@freeboub Any updates or plans to implement solution to this issue?

**Comment by freeboub** [comment]
Should be retested on last release at least 6.6.0
