### ISSUE TITLE
Controlbar misplaced when video list get scrolled 

### ISSUE THREAD

**Issue by iasreact1** [TheWidlarzGroup/react-native-video#3519]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

when video list get scrolled the control bar get misplaced, for the first time it positioned at the last of the video view, but if user scroll down during playing & showing control bar, the video gets down but controlbar remain at its position until the video stops & next video played & next video control bar starts showing at the last.Please help how to fix it?

### Reproduction

render the list & scroll the video list

**Comment by iasreact1** [comment]
https://github.com/react-native-video/react-native-video/assets/118831987/f875631b-5fd9-49e7-ad03-180b1baf2484

Please check the video @freeboub

**Comment by KrzysztofMoch** [comment]
Does this issue occurs also without enabled interop layer ?

**Comment by iasreact1** [comment]
yes , i havenot enabled any interop layer

**Comment by iasreact1** [comment]
please help to solve ....

**Comment by KrzysztofMoch** [comment]
I am debugging this 🙂

**Comment by iasreact1** [comment]
@KrzysztofMoch any update regarding this issue?

**Comment by KrzysztofMoch** [comment]
@iasreact1 For me it's working correctly 

https://github.com/react-native-video/react-native-video/assets/83216158/1e73d536-c88c-4490-a60b-929c5af55d60

**Comment by iasreact1** [comment]
@KrzysztofMoch which version of react-native-video u have used & i have to enable/or disable interop layer and how ? 
Please help
