### ISSUE TITLE
video controls progress is not visible on IOS

### ISSUE THREAD

**Issue by cq0702** [TheWidlarzGroup/react-native-video#352]
I add controls={true} but the video controls progress is not visible on IOS,there is nothing on Video.Is anyone knows how to solve this?

**Comment by latimesmike** [comment]
@cq920702  how did you solve this? I too added controls={true} but I can't get anything to show up...

**Comment by cq0702** [comment]
@latimesmike There is no video controls progress  and you need to add the custom progress by yourself.
