### ISSUE TITLE
[BUG]: The video is still playing after the component is unmounted

### ISSUE THREAD

**Issue by chenqi777** [TheWidlarzGroup/react-native-video#3522]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

The component is still playing after it is unmounted. It will appear in iOS 15, but there is no problem in iOS17. I can only manually call the pause() method to pause the playback when the component is unmounted. Both versions 5.2.1 and 6.0.0-beta.5 This problem exists.

### Reproduction

This person also encountered this problem [https://github.com/react-native-video/react-native-video/issues/3510](url)

**Comment by KrzysztofMoch** [comment]
Hey @chenqi777, Unfortunately I can't access iOS 15 - cloud you check if this patch will work for you ? (with 6.0.0-beta.5)
```diff
diff --git a/node_modules/react-native-video/ios/Video/RCTVideo.swift b/node_modules/react-native-video/ios/Video/RCTVideo.swift
index 70ae6e8..1b1283e 100644
--- a/ios/Video/RCTVideo.swift
+++ b/ios/Video/RCTVideo.swift
@@ -201,6 +201,7 @@ class RCTVideo: UIView, RCTVideoPlayerViewControllerDelegate, RCTPlayerObserverH
         self.removePlayerLayer()
         _pip = nil
         _playerObserver.clearPlayer()
+        _player = nil
     }
 
     // MARK: - App lifecycle handlers
```

**Comment by interstates21** [comment]
@KrzysztofMoch didn't work for me 🥲

**Comment by smourey** [comment]
Hi @KrzysztofMoch,  thanks for your help.
I am experiencing same issue (and I guess this is the same: https://github.com/react-native-video/react-native-video/issues/3523). Unfortunately, `deinit` method is not being called when the component is unmounted, so the suggested fix does not work. Any other idea?

**Comment by ZubairovSalim** [comment]
Experiencing same issue on iOS 15.x. Reproduced on 6.0.0-alpha.11. On ios 16.x and higher works good.

**Comment by Arise-cn** [comment]
same

**Comment by enricsa** [comment]
same here

**Comment by freeboub** [comment]
are you able to reproduce the issue with the emulator and the sample ?
I just try with ios 15.0 & 15.5.
15.0 -> crash on emulator launch
15.5 -> crash on app launch (before any react native invocation)

**Comment by haonguyendirox** [comment]
Same here, it works fine on iOS 16.x and 17.x, but it has issues on iOS 15. Do you have any solutions to address it?

**Comment by giantslogik** [comment]
can confirm its broken on iOS 15 with v6.2.0. I'm not using new architecture.

**Comment by tdammy92** [comment]
This is the only thing that gives me headache with this library. you continue hearing sounds from components that have been unmounted.  😭

**Comment by husseinTalal2** [comment]
Same issue here and I'm on android, any updates?

**Comment by sentinelweb** [comment]
I also see the issue on iOS 17.2 (sim) but not on Android.

**Comment by amit-6thstreet** [comment]
any update on this.

**Comment by sentinelweb** [comment]
easy fix is to use an `useLayoutEffect` hook to pause the video

**Comment by ogtfaber** [comment]
> easy fix is to use an `useLayoutEffect` hook to pause the video

this works

```
useLayoutEffect(() => {
    return () => {
      player.pause();
    };
  }, []);`
```
