### ISSUE TITLE
[BUG]: After destroying the player on iOS, the sound continues playing.

### ISSUE THREAD

**Issue by duansailong** [TheWidlarzGroup/react-native-video#3523]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

Library version: 5.2.1
Device: iphone12 iOS 15.3.1
RN 0.70.0

In video playback, when clicking the button to return to the previous page, the sound continues playing. The sound only pauses after sliding the bottom navigation of the Apple device. This issue does not occur on Android devices or most iOS devices. This issue has only been identified on iPhone 12 at the moment.

https://github.com/react-native-video/react-native-video/assets/23208491/046787a9-6930-4812-82ba-5eee4c4bc7e9

The method in the iOS native code was also executed but didn't take effect.

(void)dealloc
{
[[NSNotificationCenter defaultCenter] removeObserver:self];
[self removePlayerLayer];
[self removePlayerItemObservers];
[_player removeObserver:self forKeyPath:playbackRate context:nil];
[_player removeObserver:self forKeyPath:externalPlaybackActive context: nil];
}

### Reproduction

//demo

<Video
source={{
uri:'https://vjs.zencdn.net/v/oceans.mp4',
}}
style={videoStyle}
paused={false}
muted={false}
pictureInPicture={false}
ignoreSilentSwitch={'ignore'}
onEnd={() => {
Alert.alert('Done!');
}}
/>

**Comment by KrzysztofMoch** [comment]
Hey @duansailong, cloud you check if this issue exist also on v6 ?

**Comment by interstates21** [comment]
@KrzysztofMoch doesn't work on 6.0.0-beta.5

**Comment by smourey** [comment]
Experiencing same issue here, on several devices on iOS 15.x exclusively. Can also be reproduced on 6.0.0-beta.5.

**Comment by ZubairovSalim** [comment]
Experiencing same issue on iOS 15.x. Reproduced on 6.0.0-alpha.11. On ios 16.x and higher works good.

**Comment by keval7838** [comment]
Experiencing the same issue in ios only. version: 6.0.0-alpha.8

https://github.com/react-native-video/react-native-video/assets/159753559/24f0e56f-c06c-4225-b68d-ca5864f82b1a

**Comment by freeboub** [comment]
on V6, looks like duplicate of https://github.com/react-native-video/react-native-video/issues/3568

**Comment by freeboub** [comment]
linked ticket close, to be retest with V6.0.0-RCX.
Let's close this ticket
