### ISSUE TITLE
[BUG]: iOS – After returning to active after Mirroring, video auto-restarts

### ISSUE THREAD

**Issue by mikefogg** [TheWidlarzGroup/react-native-video#3532]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

Instead of Airplay – which doesn't support streaming audio over a video – we use Mirroring to help our users share their video to a TV or External Display. 

When they connect, it works great. When they disconnect – the video flickers black and then restarts. onReadyForDisplay also fires again.

### Reproduction

Step to reproduce this bug are: 

1. Start a video
2. Let it run for a few seconds
3. Mirror it to any external display (with the real device, not a simulator's "External Display")
4. Disable mirroring on your device and return to the app from the control center
5. The video will restart.

**Comment by mikefogg** [comment]
Also may be good to note, I can temporarily make this usable by automatically seeking the video again when it comes back from backgrounding – but this still goes black before seeking and isn't the best solution (it shouldn't be needed).

```
React.useEffect(() => {
    const subscription = AppState.addEventListener('change', (nextAppState) => {
      if (appState.current.match(/inactive|background/) && nextAppState === 'active') {
        videoRef.current?.seek(currentVideoProgress.current)
        videoRef.current?.resume()
      }

      appState.current = nextAppState
    })

    return () => subscription.remove()
  }, [])
  ```

**Comment by TairRod** [comment]
The same is happening to me with Airplay
