### ISSUE TITLE
[BUG]: Video's not playing (black screen) specifically on iOS 17.0.2

### ISSUE THREAD

**Issue by JeffreyVanelderenACA** [TheWidlarzGroup/react-native-video#3533]
### Version

v6 (Beta)

### What platforms are you having the problem on?

- iOS 17.0.2, could not test on previous versions
- "react-native-video": "^6.0.0-beta.4" (probably same issue on beta5 as well)
- "react-native": "0.72.5",

### Architecture

Old architecture

### What happened?

I had a user on iOS 17.0.2 which could not play the videos. He then upgraded his iOS device from **17.0.2** to **17.2** and he was then able to see the videos on the **same build** without any changes.

### Reproduction

- Try to watch video on iOS 17.0.2, you should see a black view
- Upgrade to 17.2, run the same app
- Videos play as expected

**Comment by keval7838** [comment]
"I'm experiencing the same issue. However, if I go back and navigate to the video screen again, the video will appear. In some rare cases, though, it may not."

**Comment by bsbimalbose** [comment]
I'm having the same issue on Android, but it starts playing when i remount the component with same URL. Its intermittent though.

**Comment by fredrifoUni** [comment]
I ran into the issue as well on the iOS simulator. I believe the major react-native upgrade was the thing that fixed it (0.73.x).

Also, xCode printed a few error messages related to the video player. Might be worth checking it out if you want to avoid upgrading react-native.

**Comment by rahulnainwalttn** [comment]
I'm experiencing the same issue. Using **6.0.0-rc.0** version in ios. In android, stream is playing but in ios black screen is appearing with audio. Happening with some stream URL.

**Comment by fredrifoUni** [comment]
> I'm experiencing the same issue. Using **6.0.0-rc.0** version in ios. In android, stream is playing but in ios black screen is appearing with audio. Happening with some stream URL.

Are you running into this on a physical device as well?

**Comment by rahulnainwalttn** [comment]
Yes @fredrifoUni

**Comment by fredrifoUni** [comment]
@rahulnainwalttn 
My fork is synced up with the latest beta version and I'm not seeing this issue. I will let you know if the issue re-appears when I sync it up with the release candidate. 

If you haven't tried it already, what fixed it for me the last time was upgrading react-native to 0.73.

**Comment by rahulnainwalttn** [comment]
OK @fredrifoUni - Not sure if it is specific to my stream URL? Because it is happening with only this one which we get from our client recently.

**Comment by fredrifoUni** [comment]
@rahulnainwalttn Yeah, it could definitely be related to that specific stream. I haven't looked much into how the native code handles it, but you could try to play around with the source prop: 
``source={{ uri: streamURL, type: "m3u8" }}``

Also, are you getting any video errors in the xCode logs?

**Comment by rahulnainwalttn** [comment]
Thanks @fredrifoUni. Will try it.

**Comment by rahulnainwalttn** [comment]
Just to confirm, this seems to be an issue with the current version of the player (**6.0.0-rc.0**). I reverted back to version 5.2.1, and the same video plays without any problems.

@freeboub I can share the stream URL privately.

**Comment by rahulnainwalttn** [comment]
> @rahulnainwalttn
My fork is synced up with the latest beta version and I'm not seeing this issue. I will let you know if the issue re-appears when I sync it up with the release candidate.



Indeed, it seems that the issue is related to React Native. I was on **react-native 0.69** and now moved to **react-native 0.71.7** where it is working fine.
