### ISSUE TITLE
[BUG]: requireNativeComponent: "RCTVideo" was not found in the UIManager

### ISSUE THREAD

**Issue by genesy** [TheWidlarzGroup/react-native-video#3534]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

I get this when trying to mount a video component. 

I followed the instructions on ios installation on the documentation. Build succeeds and I see it installs the module in the podfile.

react-native 0.69.7 not using new architecture.

I also had issues with `use_frameworks! :linkage => :static` with some modules so i had to exempt them.
 
```
  pre_install do |installer|
    # Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if pod.name.eql?('vision-camera-code-scanner') || pod.name.eql?('VisionCamera') || pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end
```

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
are you able to reproduce the issue on a sample ?
I don't see any issue with this informations

**Comment by KrzysztofMoch** [comment]
> I also had issues with `use_frameworks! :linkage => :static` with some modules so i had to exempt them.

@genesy seems like we need to update docs 😅
`use_frameworks! :linkage => :static` is not needed any more (in v6), so you can remove it, if it makes issue

Also I created clean react-native@0.69.7 app and it's working fine

**Comment by genesy** [comment]
I got it working by also adding `use_modular_headers!` but i'll have to give it another try without the `use_frameworks` line

**Comment by farzeen00** [comment]
Hey everyone I am facing same issue for ios, firebase suggest to have this line use_frameworks! :linkage => :static, i don't know how to figure it out, @genesy @freeboub @KrzysztofMoch could you help me out please on this

**Comment by braincore** [comment]
I'm also having this issue starting with v6 rc.0 including the most recent rc.2. It does not happen with beta.8. @genesy Can you clarify how you added `use_modular_headers!`?

**Comment by braincore** [comment]
Nevermind, this was resolved in #3737 with the solution being to bump the min ios version to 13.

**Comment by abdulmateentechbits** [comment]
Android +1

**Comment by anasvemmully** [comment]
Android +1 for v6.4.2

**Comment by ArronJLinton** [comment]
Try downgrading to `react-native-video: ^5.2.1`. 

Worked for me and I'm on `react-native: 0.74.3`
