### ISSUE TITLE
[BUG]:v6 beta don‘t load mp4

### ISSUE THREAD

**Issue by 18482048531** [TheWidlarzGroup/react-native-video#3537]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
Hey, I'm on vacation until the end of the week, I'll see what I can do when I get back

**Comment by nicolaosm** [comment]
Which beta is that @18482048531 ? Im on Beta 5 and it seems to be working fine.

Can you please share:
* Your library version
* Device Info
* MP4 URL

Thanks!

**Comment by freeboub** [comment]
no url, no details, let's close
