### ISSUE TITLE
[BUG]: v6  don't load Internet source mp4 style file,but local source mp4 and other file style can be loaded

### ISSUE THREAD

**Issue by 18482048531** [TheWidlarzGroup/react-native-video#3538]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
Hey, I'm on vacation until the end of the week, I'll see what I can do when I get back

**Comment by freeboub** [comment]
to be followed in: https://github.com/react-native-video/react-native-video/issues/3537
