### ISSUE TITLE
[BUG]: multi audio selection 

### ISSUE THREAD

**Issue by jigarsolanki0212** [TheWidlarzGroup/react-native-video#3546]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

A bug happened! I am trying to implement multi audio from the m3u8 URL it is working on the web but not on mobile i am selecting the audio track after onload,

I want to change the audio from this URL also it does not play the default selected audio on this player 

URL : https://video.gumlet.io/65bce2937b739aad127489d4/65d5aa5b1150436a0cdffb28/main.m3u8

### Reproduction

Step to reproduce this bug are:

**Comment by keval7838** [comment]
having the same issue but only in ios

**Comment by freeboub** [comment]
can you detail how you select the track ?
Did you try to reproduce the issue in sample from the project ?

**Comment by freeboub** [comment]
no update, audio track change works fine with basic sample. let's close

**Comment by jigarsolanki0212** [comment]
it's working

**Comment by jigarsolanki0212** [comment]
But the video selection only working in android, in IOS didn't get any video tracks from onLoad method

**Comment by freeboub** [comment]
> But the video selection only working in android, in IOS didn't get any video tracks from onLoad method

Yes, I think we need to have a deep thinking on video track selection due to ABR. 

Thank you for the feedback

**Comment by jigarsolanki0212** [comment]
Sure, @freeboub could you please provide me with a timeline for when the feature will be available?
