### ISSUE TITLE
[Feature]: Privacy Manifest for Promises SDK

### ISSUE THREAD

**Issue by LydGol90** [TheWidlarzGroup/react-native-video#3548]
### Description

Hi there, 

This lib makes use of Promises SDK which is on the list of Apple's "Privacy Impacting SDKs" that require a manifest and signing by Spring 2024.

The Promises SDK has now implemented a Privacy Manifest in their latest version 2.4.0 (not yet released).
https://developer.apple.com/support/third-party-SDK-requirements/
https://github.com/google/promises/pull/226

Will it be possible for this lib to update to use 2.4.0 as soon as it is released so that apps using this lib can comply with Apple policy rules? This may have already been on your radar but just wanted to check!

Many thanks,
Lydia

### Why it is needed ?

For Apple Privacy compliance for all apps using this lib

**Comment by KrzysztofMoch** [comment]
Hey @LydGol90, 
I have this on my mind - I am also waiting for it because, it will include support for visionOS (https://github.com/google/promises/pull/224)

**Comment by freeboub** [comment]
@KrzysztofMoch can we close this issue, or must we remove PromiseSwift dependency ?

**Comment by KrzysztofMoch** [comment]
We can close this once we remove this dependency

**Comment by tdraper-dev** [comment]
@KrzysztofMoch 
It seems like that dependency has been removed -> https://github.com/react-native-video/react-native-video/pull/3631

Are there any plans to release a new version w/ this change, given Apple's Privacy Manifest requirement is set to start in about 2 weeks?

**Comment by KrzysztofMoch** [comment]
Yes, I think we can make release this or at start of next week 
I will also look if we need manifest for our library

**Comment by mayur-bhandari** [comment]
Hi,

This library uses [Spotify Persistent Cache](https://github.com/spotify/SPTPersistentCache) which has a Privacy Manifest file of it's own. So if i use this library in my own React Native library which used by others via NPM, do i have to include the Privacy Manifest from Spotify? Or will this library include the Privacy Manifest? What if i use this libraries code as a custom Native Module, do i then have to specify it in my Privacy Manifest or will Apple traverse through the dependencies and find the Privacy Manifest which is added by Spotify Persistent Cache?

**Comment by aliza-khu** [comment]
> Yes, I think we can make release this or at start of next week I will also look if we need manifest for our library

@KrzysztofMoch, Any Update?

**Comment by tdraper-dev** [comment]
@KrzysztofMoch 

Bumping aliza's question? Any hopes of getting this cut this week, since the Apple May 1st deadline is around the corner? Thanks so much for all your efforts!

**Comment by KrzysztofMoch** [comment]
Yes! I will do it tonight/tomorrow

**Comment by mayur-bhandari** [comment]
@KrzysztofMoch Since this library uses [Spotify Persistent Cache](https://github.com/spotify/SPTPersistentCache), they need to add their Privacy Manifest but it looks like they have stopped uploading new versions on Pods.

**Comment by KrzysztofMoch** [comment]
I saw this, but it's optional when you use cache video (disabled by default) and even if you use it you can copy manifest from them

**Comment by freeboub** [comment]
> I saw this, but it's optional when you use cache video (disabled by default) and even if you use it you can copy manifest from them 

I agree this can be an app responsibility!
Not sure on how manifest merging works, but adding some notes on how to integrate it in doc can be enough (with a link to manifest from Spotify)

**Comment by KrzysztofMoch** [comment]
Sure, will add it

**Comment by mayur-bhandari** [comment]
@freeboub There's no information on how the manifests are merged in the app bundle so there are a lot of questions. I guess adding manifests in sample app will resolve the issue.

**Comment by aliza-khu** [comment]
> Yes! I will do it tonight/tomorrow

@KrzysztofMoch, It's 3 weeks spent. Still no update.

**Comment by freeboub** [comment]
Privacy manifest is automatically added when upgrading react native version.
I did the update in the sample here: https://github.com/TheWidlarzGroup/react-native-video/pull/3776
@KrzysztofMoch any idea why this is not compiling ?

**Comment by KrzysztofMoch** [comment]
@freeboub Yes - as always when we upgrading react-native Pods are taken from cache and install is failing - I will do fix for it (somehow not sure how yet) 
Workaround is to remove all cache from actions (~~I will do it and re-run~~ fixed and merged)

**Comment by freeboub** [comment]
I think we can close this topic. let me know if I need to reopen
