### ISSUE TITLE
Error details unusable on Android

### ISSUE THREAD

**Issue by GeoffreyPlitt** [TheWidlarzGroup/react-native-video#355]
Hello,

On Android, I'm testing a video URL that fails with response code 400, and has errors embedded in the headers of the HTTP response.

When I load that video with this module, and subscribe to the onError, I get the following strange context which isn't very useful:
 {"extra":-1004,"what":1}

Instead, I would expect that we get the full HTTP response object, or at least the HTTP code and response body. Bonus for returning the response headers, because that's where the true error string is found in my case (I'm loading Cloudinary CDN'ified MP4s).

**Comment by gergob** [comment]
I agree with having the possibility of getting the full HTTP Response object once there is an error in accessing the stream URL, but there is no way to support/parse the error messages from a server response, these can have different formats.

**Comment by GeoffreyPlitt** [comment]
Right, but some event should fire with 2 pieces: HTTP status, and text of response

**Comment by GeoffreyPlitt** [comment]
Any update?

**Comment by sajjadrad** [comment]
I have this error too, what means that?

`error: { extra: -19, what: 1 }  `

**Comment by rossvz** [comment]
@sajjadrad I am seeing the same error now as well. I have two videos loading, the first loads without problem, the second one shows similar `error: { extra: -38, what: 1 }`

**Comment by ezranbayantemur** [comment]
This might be help https://developer.android.com/reference/android/media/MediaPlayer#MEDIA_ERROR_IO

**Comment by KingAmo** [comment]
any help please?

**Comment by m4r00p** [comment]
The issue for me was that the server was sending the bad content type. So make sure that the video is send with the proper content type: video/mp4
