### ISSUE TITLE
[BUG]: shutterColor not typed in Typescript

### ISSUE THREAD

**Issue by dr-thca** [TheWidlarzGroup/react-native-video#3550]
### Version

v6alpha7 

A bug happened! 
It seems like `shuttercolor` was introduced here as a supported prop here https://github.com/react-native-video/react-native-video/pull/3179 but the type declaration was not added in Typescript. This should probably be added

### Reproduction

1. try adding shutterColor prop
2. See that VSCode complains
3. ????
4. Profit

Edit:
It seems like this added in the beta? We just havent made the switch yet.

**Comment by dr-thca** [comment]
https://github.com/react-native-video/react-native-video/pull/3266 I dont see it here?

**Comment by KrzysztofMoch** [comment]
Ops indeed it's missing type 😅 - Do you want to create PR, or I should do it ? 😄

**Comment by dr-thca** [comment]
Hi, sorry for the slow response. Thanks for fixing it! 😄
