### ISSUE TITLE
[BUG]: codepush + RNV6, TypeError: Cannot read property 'ScaleAspectFill' of undefined 

### ISSUE THREAD

**Issue by lovegaoshi** [TheWidlarzGroup/react-native-video#3553]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

I pinned down enabling codepush will trigger` TypeError: Cannot read property 'ScaleAspectFill' of undefined ` on my app, only on release + after the first app launch; the first launch is fine. subsequent launches will trigger this error and result in a white screen. error code is
```
TypeError: Cannot read property 'ScaleAspectFill' of undefined

This error is located at:
    in p
    in Unknown
    in RNCSafeAreaProvider
    in Unknown
    in RNGestureHandlerRootView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in v, js engine: hermes, stack:
value@3444:6744
Ul@297:58354
Ll@297:58148
Ta@297:96569
yi@297:86585
vi@297:86487
mi@297:86252
ci@297:83185
pt@297:27170
ri@297:79805
sl@297:49408
tryCallOne@53:15
anonymous@139:26
anonymous@115:1470
T@115:418
p@115:691
callReactNativeMicrotasks@115:2861
value@54:2896
anonymous@54:983
value@54:2528
value@54:941
value@54:876
```

tbf it's codepush shenanigans I don't quite understand.

rnv 5.2.1 works fine.

### Reproduction

Step to reproduce this bug are: 
i'll try to set up a codepush example app; but for now my app:
https://github.com/lovegaoshi/azusa-player-mobile/tree/096e9f530d02878b2f43039ba3446450b6cc37b5
works and 
https://github.com/lovegaoshi/azusa-player-mobile/tree/a0bb33e8d0b530054956a3538748da59ec56ba09
doesnt work.

**Comment by KrzysztofMoch** [comment]
Huh... what beta version are you using? 
If I search project for "ScaleAspectFill" it's showing only in windows native code... (on master branch, but I think in beta.5 it same)

**Comment by lovegaoshi** [comment]
beta5 and alpha11 both

**Comment by freeboub** [comment]
I agree @KrzysztofMoch This is looking very strange...
@lovegaoshi as you don't use windows, can you just try to remove function:

`winrt::Microsoft::ReactNative::ConstantProviderDelegate ReactVideoViewManager::ExportedViewConstants() noexcept {`

I expect it will fix your issue, but I don't really understand why you have it ...

**Comment by genesy** [comment]
This is also happening for me when upgrading to 6.3.0 with production build. Code only belongs on windows but affects android build somehow.

**Comment by gmantuanrosa** [comment]
Why was this closed @lovegaoshi ? 

I just tested from the latest 6.4.3 version, when debugging the app, the video plays fine but after bundling an Android version the app has an error screen `TypeError: Cannot read property 'ScaleAspectFill' of undefined`. 

It doesn't seem to have been resolved after checking other issues

**Comment by lovegaoshi** [comment]
bc sadly codepush is being deprecated by msft

**Comment by gmantuanrosa** [comment]
> bc sadly codepush is being deprecated by msft

I don't know how but I am getting impacted on Android production build by this very same issue 😞

**Comment by 0xtun4** [comment]
Same issues!!!
Everything works fine on debug, but it fails on release.
I’ve already done a full clean (node_modules, Android build, cache, ...), and it’s still exits.
