### ISSUE TITLE
[BUG]: React Native Video Player Crashes on iOS and Apple TV with Invalid URL

### ISSUE THREAD

**Issue by vanapallipremkumar** [TheWidlarzGroup/react-native-video#3556]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS, Apple tvOS

### Architecture

Old architecture

### What happened?

When attempting to play a video using the react-native-video library on iOS devices and Apple TV by passing an invalid URL (such as a random website URL), the video player crashes unexpectedly. This issue seems to occur specifically when the provided URL does not point to a valid video file.

### Reproduction

1. Install and integrate react-native-video library into a React Native project.
2. Use the library to create a video player component.
3. Pass an invalid URL (e.g., a random website URL) to the video player component as the video source.
4. Attempt to play the video on an iOS device or Apple TV.

**Example url:** https://www.youtube.com

**Expected Behavior:** The video player should handle the invalid URL gracefully and ideally display an error message or fallback content indicating that the provided URL is not valid.

**Actual Behavior:** The video player crashes when attempting to load the invalid URL, resulting in an unexpected app or system crash on iOS devices and Apple TV.

**Additional Information:**

- This issue seems to be specific to iOS devices and Apple TV, as it has not been observed on other platforms.

- Providing a valid video URL results in the video playing correctly, indicating that the crash occurs specifically when handling invalid URLs.

- It's crucial to handle invalid URLs gracefully to prevent app crashes and provide a better user experience.

**Environment:**

- [ ] React Native version: 0.71.14
- [ ] react-native-video version: 5.2.1

**Comment by KrzysztofMoch** [comment]
Hey @vanapallipremkumar, we don't support 5.x version any more, please try v6 beta

**Comment by vanapallipremkumar** [comment]
> Hey @vanapallipremkumar, we don't support 5.x version any more, please try v6 beta

@KrzysztofMoch May I know when are you planning to release V6 stable?

**Comment by KrzysztofMoch** [comment]
I guess we need to fix some bugs first 😅 We don't have specific date, but we are doing everything to make it as fast as possible 🙌

**Comment by vanapallipremkumar** [comment]
Thank you @KrzysztofMoch !
I've tried V6 and it is working fine with invalid URL. Excitedly waiting for the stable release.

Thanks again!
