### ISSUE TITLE
[iOS] Native component for "RCTVideo" does not exist

### ISSUE THREAD

**Issue by fu24d** [TheWidlarzGroup/react-native-video#356]
After following the installation instructions, I am running into this warning: "Native component for "RCTVideo" does not exist" when I try to run my app on the iOS simulator. When I navigate to the view, I get the error _"undefined is not an object (evaluating '_reactNative.NativeMOdules.UIManager.RCTVideo.Constants)_

I have tried: deleting my node_modules and clearing the cache, then running "rnpm link react-native-video", but nothing seems to work. 

When I looked in my Libraries folder in XCode I didn't see a RCTVideo.xcodeproj folder, but when I tried adding it manually and linking libRCTVideo.a, I get a build error saying "RCTVIewManager.h
 file not found. " 

I've tried following what other people have done to solve their problems that were similar to mine, however nothing seems to be working. Any help would be appreciated!

**Comment by pennyandsean** [comment]
I did get this but `react-native link react-native-video` followed by killing the package manager, followed by `react-native run-ios` did the trick. Sorry that probably doesn't help.

**Comment by shilpan** [comment]
@fu24d @pennyandsean I tried the solution you mentioned but I doesn't seem to work. I am on `rn 0.32.0`

**Comment by diehell** [comment]
I got it to work on my IOS Simulator at last. The require makes it work rather than using uri={{myvideo}}

```
<Video
        repeat
        resizeMode='cover'
        source={require('./assets/myvide.mp4')}
        style={styles.backgroundVideo}
      />
```

**Comment by abbreviatedman** [comment]
Is there a way to use require to set the source to a web url?

**Comment by arash-hacker** [comment]
-1 when using `react-native link` it shows an error like this ![screen shot - - at](https://user-images.githubusercontent.com/6451804/37159265-a3a45e0e-2302-11e8-8a01-a101b2a863ac.png)

-2 and when i want add libRCTvidoe.a, it doesn't apear in linkages so let start hacking :)

i cloned project and use libRCTvideo.a in project , droped to my project and walla.. now librctvideo apears and i added to my project and it worked !

**Comment by shiv0403** [comment]
You just need to `cd ios` and remove `Podfile.lock`  from there. Then run `pod install`.
This solved the issue for me
