### ISSUE TITLE
[BUG]: video continues playing when app goes to the background or navigate to another page

### ISSUE THREAD

**Issue by keval7838** [TheWidlarzGroup/react-native-video#3568]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

video continues playing when app goes to the background or navigate to another page only in ios

### Reproduction

 <Video
                muted={muted}
                ref={videoRef}
                source={videoUri}
                style={getVideoViewStyles()}
                controls={false}
                resizeMode={resizeMode}
                onLoad={onLoadEnd}
                onProgress={onProgress}
                onEnd={onEnd}
                ignoreSilentSwitch={'ignore'}
                automaticallyWaitsToMinimizeStalling={true}
                paused={paused}
                repeat={isFromDetail ? true : isPlatformIOS() ? true : false}
                onBuffer={bufferdata => {}}
                playInBackground={false}
             
            />

**Comment by freeboub** [comment]
@KrzysztofMoch This is a regression from: https://github.com/react-native-video/react-native-video/pull/3357

**Comment by KrzysztofMoch** [comment]
Okay, will look at it 👀

**Comment by freeboub** [comment]
@KrzysztofMoch I did some investigations yesterday
orignal code: `((_playerItem?.isPlaybackLikelyToKeepUp) != nil)`
I think this condition shall be always true as isPlaybackLikelyToKeepUp can be true or false ...

In apple doc, they say the value of isPlaybackLikelyToKeepUp shall checked with [isPlaybackBufferFull](https://developer.apple.com/documentation/avfoundation/avplayeritem/1388852-isplaybackbufferfull)

I think a revert would be enough for now. The orignial ticket was not clear on what is really the issue ...

**Comment by KrzysztofMoch** [comment]
But if we leave `((_playerItem?.isPlaybackLikelyToKeepUp) != nil)` we will return to "not working version" with false positive if statement. 
What if we add check for `_playInBackground` to don't play it in background

**Comment by freeboub** [comment]
((_playerItem?.isPlaybackLikelyToKeepUp) != nil) -> I think this is always true...
isPlaybackLikelyToKeepUp is false in this case, I don't understand what was the original issue from: https://github.com/react-native-video/react-native-video/issues/3060
Was this something yo where able to reproduce easily ?
