### ISSUE TITLE
Back-to-back videos: onLoad called multiple times, onEnd called a different number of times than onLoad (2 probs)

### ISSUE THREAD

**Issue by GeoffreyPlitt** [TheWidlarzGroup/react-native-video#357]
We're doing a multi-video flow where the video component stays shown while we wait for onEnd to set the src to a new URI, over and over, to make it show an array of videos one after another.

One of the problems we're seeing is that onLoad is happening twice sometimes for a single URI. Has anyone seen this before? What could cause it?

Another problem we're seeing is that onEnd is NOT called multiple times when onLoad happens multiple times.

If either onLoad was clamped to never happen more than once, or onEnd matched the number of times onLoad happened, things would be consistent. But at the moment, these 2 disparities leave things very inconsistent.

Please advise, thanks.

**Comment by GeoffreyPlitt** [comment]
Update: I have a hunch about what could be causing this. There might just be a race condition when one video ends and the next begins, where their events aren't happening in quite the right order (the 2nd video fires "begin" events before the 1st video fires its "end" events). I'll bet using a simple in-memory lock/semaphore would solve this. Wondering if this project has tests for back-to-back yet?

**Comment by alexpareto** [comment]
It's a little bit of a hack but using debounce as suggested in #238 can solve it until a better solution comes along.

**Comment by smkhalsa** [comment]
@GeoffreyPlitt did you figure out a solution to this? I'm running into this issue now, and I'd prefer to resolve the root as opposed to hacking it with debounce.

**Comment by GeoffreyPlitt** [comment]
We did not, and we are currently using a debounce workaround, which kinda sucks. Hope this gets fixed.

**Comment by phil4lif** [comment]
Closed as completed?  I'm not trying to show multiple videos, just one, but it seems my onLoad is being called three times.
