### ISSUE TITLE
You tube video

### ISSUE THREAD

**Issue by uc-asa** [TheWidlarzGroup/react-native-video#358]
Hi,

I need to play youtube video how.
Give an example .

**Comment by Liroo** [comment]
You have to understand this: [link to youtube video](https://www.youtube.com/watch?v=_m3VoYvpkOg) is not a video url. That is just a web page, you can pass through the source an remote mp4 video such as [link to player only](https://r4---sn-25ge7nlz.googlevideo.com/videoplayback?key=yt6&signature=D89E9E248AA6AFD993A98508C8B28C51F77E4774.6FC46CE1875BED7DD6E32CFC3AFFAF70D37F7056&nh=IgpwcjAzLnBhcjAxKg4yMDkuODUuMTcyLjE1MQ&requiressl=yes&lmt=1472228177080607&source=youtube&dur=237.006&ratebypass=yes&upn=qE6Bw-sSbOI&expire=1477316177&itag=22&id=o-ABxiehrKAVUZ86xKS27ISu7vjFJCEzzy4Xdt6vL6GndD&mm=31&mn=sn-25ge7nlz&pl=21&ip=193.248.47.248&ei=8bkNWJesHJW7cIPgvdgF&ms=au&mt=1477294456&mv=m&ipbits=0&initcwndbps=857500&mime=video%2Fmp4&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire)...
The only way I found to get this link is to use youtube-dl but it's unusable on react-native, only on a remote server :/
Or you could create an project using youtube native component

**Comment by gergob** [comment]
@uc-asa what might work is to have a `webview` within the react-native app and load the youtube url there. Since youtube supports HTML5 players, this should work on mobile platform integrated browsers. On Android Chrome supports it, also Safari is good at it on iOS.

**Comment by Liroo** [comment]
Use a webview as video player is not the purpose of react-native, on top of that you're going to have problems from the navigation of webview. :/ If you are ok with native technologies, you could create a youtube video component for both platform and let it open source.

Either way, @gergob is right, you can use webview as a last resort
