### ISSUE TITLE
[BUG]: native volume controller is broken when layout direction is rtl

### ISSUE THREAD

**Issue by ravi-khinchi** [TheWidlarzGroup/react-native-video#3581]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

hey, when `ThemeManager.RTL` is `true`, volume control UI is broken in case of rtl layout on IOS

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:  
* make layout `RTL`  
* set `controls` to `true` on player 
*  swipe on volume control
<img width="500" src="https://github.com/react-native-video/react-native-video/assets/120457879/6290ae9f-bce3-4864-951e-12104047bbe6" />

**Comment by freeboub** [comment]
@ravi-khinchi can you please add more details ?
- re upload the screenshot ?
- did you enable rtl from the system ?

**Comment by ravi-khinchi** [comment]
> @ravi-khinchi can you please add more details ?
> 
> * re upload the screenshot ?
> * did you enable rtl from the system ?

hey @freeboub bro, my bad
1. uploaded the snap again, 
2. no i dont do it from system, I use `I18nManager` n we force RTL, but since u mentioned it, I tried changing it from system n omg, it works, but Idk why its not working when we do `I18nManager.forceRTL(true)` n restart the app, 
I also tried setting,  `writingDirection: "rtl"` on the container that holds `Video` player

**Comment by freeboub** [comment]
I cannot reproduce the issue on the basic exemple on emulator...

I just add this in the sample:
```
    useEffect(() => {
      I18nManager.forceRTL(true);
    }, []);
```

Any clue on how to reproduce the issue ?

Wait, I am working with last 6.0 ! do you have the issue on this version ?

**Comment by ttanjiro** [comment]
hey, this is bit of a work
this article might be helpful, https://medium.com/@p.nasirimehr/adding-rtl-support-to-an-existing-react-native-app-in-2020-3264d035cb49

on ios, we need to set this additional prop `writingDirection`, 
wait is 6.0 working ???, I tried some 6.0.0.-x version, can't remember, was not working so I gave up

**Comment by freeboub** [comment]
@ttanjiro yes V6 is better and better :) we are hunting regressions ;) 
I know that rtl management, but here is seems the issue on native side (as player UI is native).

**Comment by ravi-khinchi** [comment]
@freeboub btw I cant get my `ios` build on v6, it throws lots of warnings, 
I'm trying beta 4 rt n actually I even tried alphas 11 also same problem

is there anything I need to configure in xcode ??
this is `npx react-native info`

`info Fetching system and libraries information...
System:
  OS: macOS 13.6.3
  CPU: (8) arm64 Apple M1 Pro
  Memory: 115.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/rkhinchi/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-30 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-31 | Intel x86 Atom_64
      - android-31 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/rkhinchi/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
` 

<img width="620" alt="Screenshot 2024-03-14 at 6 16 44 PM" src="https://github.com/react-native-video/react-native-video/assets/120457879/22594bcb-158c-4111-bbf0-67d11daf6ce2">

**Comment by freeboub** [comment]
@ravi-khinchi which xcode version are you using ?
BTW, are you able to build the sample in the project ?

**Comment by ravi-khinchi** [comment]
@freeboub I'm on Version 15.1 (15C65)
naa, I didn't do that, le me actually try this real quick

**Comment by ravi-khinchi** [comment]
@freeboub yea its works, I needed to use swift 5 for complier
btw I was wondering, we don't currently have callbacks exposed when we play/pause the player with native controls yea?
