### ISSUE TITLE
Crash on iOS: com.apple.audio.IOThread.client crash using with Flatlist

### ISSUE THREAD

**Issue by ankitpunchh** [TheWidlarzGroup/react-native-video#3588]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

When using react-native-video with flatlist and once we played the video and close the video player. Then after a certain time if we left the app as it is the application gets crashed (looks like due to memory leakage).  Attaching screenshot:
<img width="1440" alt="Screenshot 2024-03-14 at 10 12 06 AM" src="https://github.com/react-native-video/react-native-video/assets/96620964/a665c39b-11e8-4ff3-8a52-650b0a649c2c">

### Reproduction

1. Use react-native-video in flatlist.
2. Play any video from the list and close it.
3. Leave the app for a certain amount of time. Application will get crashed. Already attached the screenshot above.

**Comment by freeboub** [comment]
Can you clarify which beta version and if reproduced on last version please (6.0.0-beta.8)?

**Comment by ankitpunchh** [comment]
No its on the version: "react-native-video": "^6.0.0-beta.4"

**Comment by freeboub** [comment]
@ankitpunchh can you please test on the last release please (6.2.0) ?
I just create a flatList sample : https://github.com/freeboub/react-native-video-flatlist-sample
I didn't seee this issue on emulator (I don't have real iphone)

**Comment by freeboub** [comment]
Let's close this issue, should be fixed on 6.2.0
