### ISSUE TITLE
[Feature]: Picture In Picture within App

### ISSUE THREAD

**Issue by pateljoel** [TheWidlarzGroup/react-native-video#3590]
### Description

I'm trying to find a way to do Picture in Picture within the app I am working on, I don't mean Picture in Picture _outside_ of the app, but rather inside.

I'm assuming react-native-video has a way of doing this but I cannot find anywhere where this is shown, unless I am missing something.

### Why it is needed ?

Because I'm multitasking always inside of the app, but don't want to be locked into watching the video when I can be doing something else inside of the app, e.g. watching a recipie video inside of the app and following instructions at the same time in PiP.

**Comment by gkueny** [comment]
Hello @pateljoel 

PiP is not available for Android now.

For iOS you can check these ressources that can help (with Beta version):
- https://github.com/react-native-video/react-native-video/discussions/3540
- https://react-native-video.github.io/react-native-video/component/props#pictureinpicture
- https://react-native-video.github.io/react-native-video/component/events#onpictureinpicturestatuschanged
- https://react-native-video.github.io/react-native-video/component/events#onrestoreuserinterfaceforpictureinpicturestop
- https://react-native-video.github.io/react-native-video/component/methods#restoreuserinterfaceforpictureinpicturestopcompleted
-

**Comment by gkueny** [comment]
@pateljoel if that answers your question I'll let you close that issue.

If not, you also can open a discussion here https://github.com/react-native-video/react-native-video/discussions. It will better fit than an issue

**Comment by pateljoel** [comment]
Hi @gkueny, are you trying to say that it's not possible for a floating window inside of an app for Android? Is there a way around this that works? Is there code available for this?

**Comment by gkueny** [comment]
> that it's not possible for a floating window inside of an app for Android?

It's will be hard to have it in this library because of how Android manage PiP (when you enter PiP mode, all the current `Activity` go to PiP. And because `react-native` use only one `Activity`, all app go to PiP.)

A PR is open to enable PiP mode for android but only outside of your app. (because of limitation mentioned). 
See https://github.com/react-native-video/react-native-video/pull/3385

> Is there a way around this that works?

Yes, you can create a floating view in your app with video inside. It's how we implemented it in my company, but you have to setup all interaction yourself

> Is there code available for this?

No for now as I'm aware

**Comment by KrzysztofMoch** [comment]
Hey @pateljoel, PiP is possible only possible for iOS now, but we will merge android PiP PR Soon™

As @gkueny said it already possible to do it with current library state but, to accomplish it would require quite some time to implement an example for you. Therefore if you need, we can do that as part of TheWidlarzGroup services. Feel free to contact us here: https://www.thewidlarzgroup.com/

**Comment by costalu** [comment]
So from what I've read, it doesn't seem like PiP **within** app works, even for iOS, without a custom solution - is that correct?

**Comment by gkueny** [comment]
> So from what I've read, it doesn't seem like PiP **within** app works, even for iOS, without a custom solution - is that correct?

pip within app work for iOS. 

But not for android indeed

**Comment by costalu** [comment]
> pip within app work for iOS.

I'm using version `6.0.0-rc.1`, and PIP works well when I leave the app. But as soon as I navigate away from the parent screen within the app, the video disappears. Any idea / common causes why that could be the case?

**Comment by gkueny** [comment]
@costalu 
> I'm using version 6.0.0-rc.1, and PIP works well when I leave the app. But as soon as I navigate away from the parent screen within the app, the video disappears. Any idea / common causes why that could be the case?

Not sure if it's your issue, but your video instance is linked to `<Video>` component.
So, when your `<Video>` component is unmounted, your video instance is not referenced anymore by `react-native-video` and it explain why le video disappears when you navigate away from the parent.

In my app, we render only one video at the time (in different page) so we manage to have:
- a global `<Video>` component 
- we show/hide this component when we need it 
- we use `absolute` position to show at the right place one the app
- we manage which video to show with some global state

See the context here: https://github.com/TheWidlarzGroup/react-native-video/discussions/3540

**Comment by costalu** [comment]
appreciate the help @gkueny! I think the issue was exactly this, unmounting the `<Video>` component. 

I'm not too well versed with navigation, but I had the video in a nested screen, which was getting destroyed every time I tried to go back to the main stack. I was able to expose the main stack navigation in this nested screen, and PiP within the app is working well now 👍🏾
