### ISSUE TITLE
[BUG]: Video does not fit the height and width of parent 

### ISSUE THREAD

**Issue by manjunath-nuveb** [TheWidlarzGroup/react-native-video#3599]
### Version

v6 (Beta)

### What platforms are you having the problem on?

IOS and Android

### Architecture

Old architecture

### What happened?

The video does not scale to the height and width of the parent when the resolution is less than the parent's width/height.
Video is not stretching to fit the parent width. 
When I'm streaming HLS video with different resolutions, selecting a resolution with a height of 180 causes the video to shrink and not take up the width of the parent. In the attached screenshot, the background loads the first frame and keeps flickering, while the actual video plays on only a quarter of the screen. 

![Screenshot_1711131117](https://github.com/react-native-video/react-native-video/assets/138149089/18e3ae02-52fc-4598-9e18-fa07a9bae148)

### Reproduction

repository link

### Reproduction

When streaming HLS/DASH video choose video height less than viewport height/width

**Comment by freeboub** [comment]
Please give more details, the sample in this repo works fine

**Comment by manjunath-nuveb** [comment]
this is happening only on emulator not on device

**Comment by freeboub** [comment]
This is an emulator issue. I also reproduce it with exoplayer sample app.
Let's close this ticket
