### ISSUE TITLE
License

### ISSUE THREAD

**Issue by myuller** [TheWidlarzGroup/react-native-video#36]
Hi,
Sorry if it's been covered already, but I can't find a license anywhere in the repository. Is there one?

**Comment by brentvatne** [comment]
@myuller - oops, consider it MIT licensed, will add that when I get the chance. if that somehow prohibits you from using this module, let me know which license would work best for you

**Comment by myuller** [comment]
MIT is great, thanks a lot!

**Comment by myuller** [comment]
oops, wrong button...
