### ISSUE TITLE
[Android] _reactNative.NativeModules.UIManager.RCTVideo.Constants

### ISSUE THREAD

**Issue by movetosun** [TheWidlarzGroup/react-native-video#360]
ios is ok.when i use it in Android,throw this error:undefined is not an object(evaluating ' _reactNative.NativeModules.UIManager.RCTVideo.Constants')

**Comment by gergob** [comment]
@movetosun you need to follow these steps: https://github.com/react-native-community/react-native-video#android

Also you can check the setup of the `react-native-video` component here: https://github.com/gergob/rent/blob/master/android/settings.gradle

Also in your `MainApplication.java` you need add the `ReactVideoPackage` package in the `getPackages()` method:

``` java
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage(),
            new ReactVideoPackage()
      );
    }
```

**Comment by bharatraichur** [comment]
Hi,
  I have followed all the steps mentioned and verified all the files for configuration. But the error persists. iOS is working without any issues. Could you please guide what could be the issue?

**Comment by jlemoscds** [comment]
react-native link is not working right. You need to do the configurations manually.
