### ISSUE TITLE
[BUG]: the link to the changelog from your docs is a 404

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3600]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

A bug happened!  the link to the change log from your docs is a 404

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by eedeebee** [comment]
I tried to file a bug via your form and it made an empty bug - weird.  Well here the subject line says all

**Comment by freeboub** [comment]
@eedeebee just checked, I don't have any issue. Can you explain Which link is problematic?

**Comment by freeboub** [comment]
It is here: https://github.com/react-native-video/react-native-video/blob/master/CHANGELOG.md
BTW, if you can provide which link is problematic, we can fix it

**Comment by eedeebee** [comment]
https://react-native-video.github.io/react-native-video/ has an underlined link that says Changelog that points here: 
https://react-native-video.github.io/react-native-video/CHANGELOG - 404 for me.

**Comment by eedeebee** [comment]
I would re-open this for you but I can't see how @freeboub

**Comment by freeboub** [comment]
@eedeebee I open this pull request to fix a changLog link: https://github.com/react-native-video/react-native-video/pull/3693
I am sorry but the link you found is still not clear for me. The fix concern the link in "Version 6.0.0 breaking changes" section
