### ISSUE TITLE
[BUG][iOS]: Crash on specialized RCTVideo.applicationWillEnterForeground(notification:)

### ISSUE THREAD

**Issue by ashwanihundwani1986** [TheWidlarzGroup/react-native-video#3607]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

<img width="1420" alt="Screenshot 2024-03-26 at 10 41 19 AM" src="https://github.com/react-native-video/react-native-video/assets/105865354/3995c1e8-f655-42a8-9c25-dd7fb0e547b6">

Getting above crash in iOS 16 in production. 

Stack Trace:
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0x1af0a8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1abad0 -[__NSArrayM insertObject:atIndex:].cold.2
4  CoreFoundation                 0x13f90 -[__NSArrayM insertObject:atIndex:]
5  AVFCore                        0x17e58 __22-[AVPlayer _addLayer:]_block_invoke
6  libdispatch.dylib              0x3fdc _dispatch_client_callout
7  libdispatch.dylib              0x13574 _dispatch_lane_barrier_sync_invoke_and_complete
8  AVFCore                        0x17548 -[AVPlayer _addLayer:]
9  AVFCore                        0x17400 -[AVPlayerLayer _setPlayer:forPIP:]
10 Foundation                     0x3f814 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
11 Foundation                     0x3f590 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
12 Foundation                     0x3eb24 _NSSetObjectValueAndNotify
13 AVFCore                        0x176bc -[AVPlayer _addLayer:]
14 AVFCore                        0x17400 -[AVPlayerLayer _setPlayer:forPIP:]
15 Foundation                     0x3f814 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
16 Foundation                     0x3f590 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
17 Foundation                     0x3eb24 _NSSetObjectValueAndNotify
18 AlJazeeraMobile                0xc96974 specialized RCTVideo.applicationWillEnterForeground(notification:) + 238 (RCTVideo.swift:238)
19 AlJazeeraMobile                0xc87994 @objc RCTVideo.applicationWillEnterForeground(notification:) (<compiler-generated>)
20 CoreFoundation                 0x37404 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
21 CoreFoundation                 0xde474 ___CFXRegistrationPost_block_invoke
22 CoreFoundation                 0xc1724 _CFXRegistrationPost
23 CoreFoundation                 0x4ba08 _CFXNotificationPost
24 Foundation                     0x5cffc -[NSNotificationCenter postNotificationName:object:userInfo:]
25 UIKitCore                      0x1a4cf0 -[UIApplication _sendWillEnterForegroundCallbacks]
26 UIKitCore                      0x1a482c __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2
27 UIKitCore                      0x9e600 _UIScenePerformActionsWithLifecycleActionMask
28 UIKitCore                      0x3e0918 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
29 UIKitCore                      0x290fa4 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
30 UIKitCore                      0x290dcc -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
31 UIKitCore                      0x29097c -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
32 UIKitCore                      0x290848 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
33 UIKitCore                      0x972fa8 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]
34 UIKitCore                      0xa0bf98 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
35 UIKitCore                      0x13c958 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
36 UIKitCore                      0x5af7a8 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.214
37 UIKitCore                      0x20f0b8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
38 UIKitCore                      0x20ef28 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
39 UIKitCore                      0x20ed68 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
40 FrontBoardServices             0x3cdc -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
41 FrontBoardServices             0x3b18 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
42 FrontBoardServices             0x7294 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
43 FrontBoardServices             0x71b0 __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
44 libdispatch.dylib              0x3fdc _dispatch_client_callout
45 libdispatch.dylib              0x7a5c _dispatch_block_invoke_direct
46 FrontBoardServices             0x113b0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
47 FrontBoardServices             0x10f4c -[FBSSerialQueue _targetQueue_performNextIfPossible]
48 FrontBoardServices             0x1372c -[FBSSerialQueue _performNextFromRunLoopSource]
49 CoreFoundation                 0xd5f54 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
50 CoreFoundation                 0xe232c __CFRunLoopDoSource0
51 CoreFoundation                 0x66210 __CFRunLoopDoSources0
52 CoreFoundation                 0x7bba8 __CFRunLoopRun
53 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific
54 GraphicsServices               0x1368 GSEventRunModal
55 UIKitCore                      0x3a23d0 -[UIApplication _run]
56 UIKitCore                      0x3a2034 UIApplicationMain
57 AlJazeeraMobile                0x4a78 main + 8 (main.m:8)
58 ???                            0x1df6d8960 (Missing)

### Reproduction

repository link

### Reproduction

As per crash it occurs when app comes back to foreground.

**Comment by freeboub** [comment]
Is this reproduced on 6.2.0 or next version ?
