### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by uc-asa** [TheWidlarzGroup/react-native-video#361]
When I open a mp4 file which URL is not exits so how can check and provide a proper msg.
Its loading and continuously loading and not response any thing

**Comment by gergob** [comment]
maybe you can try the `onError` callback, but I am not sure if that will raise an error if the video cannot be loaded, but I would assume so.

**Comment by GeoffreyPlitt** [comment]
Still happening for me, sometimes (with certain errors), onError() is not even called, just blank white rectangle.
