### ISSUE TITLE
[BUG]: iOS can't play video with uri "ph://"

### ISSUE THREAD

**Issue by haonguyendirox** [TheWidlarzGroup/react-native-video#3611]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

A video player is unable to play videos from iOS photos with the format 'ph://'. 
This issue has arisen in the latest version. I suspect it is related to 'isSetSourceOngoing' in RCTVideo.swift

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
Play any asset with uri format start with "ph://"

**Comment by freeboub** [comment]
@haonguyendirox you mean it works with 6.0.0-beta.5 and not with beta.6 ?

**Comment by haonguyendirox** [comment]
> @haonguyendirox you mean it works with 6.0.0-beta.5 and not with beta.6 ?

Exactly, this v6 doesn't work, specifically it can't play videos from the iOS device library. After debugging, I suspect the issue stems from updating the code in RCTVideo.swift, leading to the isSetSourceOngoing flag not functioning correctly in cases where the URI starts with ph://

**Comment by freeboub** [comment]
@haonguyendirox can you check following please ?
can you try to remove following lines:
```
self.isSetSourceOngoing = false
self.applyNextSource()
```
from here: https://github.com/react-native-video/react-native-video/blob/89ae8438fa1d90700a462b117aa9af42780c6268/ios/Video/RCTVideo.swift#L354

I really think this is the issue!

**Comment by haonguyendirox** [comment]
> @haonguyendirox can you check following please ? can you try to remove following lines:
> 
> ```
> self.isSetSourceOngoing = false
> self.applyNextSource()
> ```
> 
> from here:
> 
> https://github.com/react-native-video/react-native-video/blob/89ae8438fa1d90700a462b117aa9af42780c6268/ios/Video/RCTVideo.swift#L354
> 
> I really think this is the issue!

Right, perhaps the issue stems from there
I'm working around it by put self.isSetSourceOngoing = true within the closure of RCTVideoUtils.preparePHAsset

**Comment by freeboub** [comment]
> > @haonguyendirox can you check following please ? can you try to remove following lines:
> > 
> > ```
> > self.isSetSourceOngoing = false
> > self.applyNextSource()
> > ```
> > 
> > from here:
> > 
> > https://github.com/react-native-video/react-native-video/blob/89ae8438fa1d90700a462b117aa9af42780c6268/ios/Video/RCTVideo.swift#L354
> > 
> > I really think this is the issue!
> 
> Right, perhaps the issue stems from there
> I'm working around it by put self.isSetSourceOngoing = true within the closure of RCTVideoUtils.preparePHAsset

I think that fix would be enough, in that case the playback start up is still ongoing, so no need to try to restart next playback request! Let me know, I can be integrated for the next release!

**Comment by freeboub** [comment]
@haonguyendirox any update on my proposal ? I would like to integrate it in next release !

**Comment by haonguyendirox** [comment]
> @haonguyendirox any update on my proposal ? I would like to integrate it in next release !

I think that's enough to address the issue, thank you!

**Comment by freeboub** [comment]
has been merged in 6.0.0-beta.7
