### ISSUE TITLE
[BUG]: Cannot see any acitivity in debugger Network Tab

### ISSUE THREAD

**Issue by Michota** [TheWidlarzGroup/react-native-video#3614]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I cant see any activity in network tab in the one that look like Chrome Devtools, and neither with usage of Reactotron. 
Video plays as it should, but i can't track it with network tab!

### Reproduction

As described in _What happened?_ section.

**Comment by freeboub** [comment]
From the documentation:
You need to record network trace to ensure communications with server is correct. Charles proxy is a simple and useful tool to sniff all http/https calls. With this tool you should be able to analyze what is going on with network. You will see all access to content and DRM, audio / video chunks, ...

Your point may need to be added in the documention
