### ISSUE TITLE
[BUG]: iOS blank video

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3621]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

`npm i react-native-video@6.0.0-beta.6`
`npx react-native run-android` - then CTRL C out
`npx react-native run-ios` - then CTRL C out
`cd ios && pod install && cd ..`
`npm start`
`a`

Observed video playing in android but not in ios, blank white screen in ios.

### Reproduction

https://github.com/paulrinaldi/rnv-simple-sample

### Reproduction

General startup.

Observed video playing in android but not in ios, blank white screen in ios.

**Comment by gkueny** [comment]
@paulrinaldi can you test with a video over `https` ?

Apple do not allow communication without `https` (see https://stackoverflow.com/questions/60862693/how-to-play-unsecure-video-in-avplayer-in-ios-13 & https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/)

**Comment by paulrinaldi** [comment]
> @paulrinaldi can you test with a video over `https` ?
> 
> Apple do not allow communication without `https` (see https://stackoverflow.com/questions/60862693/how-to-play-unsecure-video-in-avplayer-in-ios-13 & https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/)

This worked, thank you so much!
