### ISSUE TITLE
[BUG]: Duplicate interface definition for class 'RCTEventDispatcher'

### ISSUE THREAD

**Issue by gaberogan** [TheWidlarzGroup/react-native-video#3622]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

At random times when rebuilding the project with XCode, the build fails with the issue you see below. In theory, nothing should have changed because I ran Build once and then again 10 minutes later and then it fails.

The only way to fix the issue I've found is to `yarn remove react-native-video && pod install && yarn add react-native-video@6 && pod install`. This fixes it every time, but only temporarily until it pops up again a day later.

<img width="238" alt="Screenshot 2024-03-27 at 9 38 25 AM" src="https://github.com/react-native-video/react-native-video/assets/58148287/c849d532-885c-48e6-a882-c060e57180e9">

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: unclear, perhaps build an app with react-native-video and then wait a day and build again. I am happy to debug if anyone has recommendations.

**Comment by hesselbom** [comment]
I'm having the same issue but seems to have been fixed by using patch-package to reverse this https://github.com/react-native-video/react-native-video/issues/3004#issuecomment-1429490797

Or in other words, changing `node_modules/react-native-video/ios/Video/RCTVideo-Bridging-Header.h` to:
```
// #import "RCTEventDispatcher.h"
#import "RCTVideoSwiftLog.h"
#import <React/RCTViewManager.h>

#if __has_include(<react-native-video/RCTVideoCache.h>)
#import "RCTVideoCache.h"
#endif
```

Then running `npx patch-package react-native-video`

Unsure as of yet if it will have unknown side effects but compiles now.

**Comment by freeboub** [comment]
@hesselbom I don't think there will be side effects (it is just some includes changes, not a real code change).
BTW, is it possible to provide a sample to reproduce the issue ?
It may be linked to you r react native version or another external dependency I think ...

**Comment by hesselbom** [comment]
> BTW, is it possible to provide a sample to reproduce the issue ? It may be linked to you r react native version or another external dependency I think ...

It could very well be related to something else. It's an old React Native project for a client with a bunch of dependencies. Unfortunately don't have the time to create a reproducible sample but for what it's worth I was upgrading React Native from version 0.66.5 to version 0.73.6
