### ISSUE TITLE
[BUG]: player freez when the speed is changed (iOS only)

### ISSUE THREAD

**Issue by krifamed** [TheWidlarzGroup/react-native-video#3623]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

When the `rate` attribute changes, the player freezes until the play/pause button clicked again or apply another rate.

https://github.com/react-native-video/react-native-video/assets/15787351/82fb5fb4-d8c3-42db-8fbe-695385b321d4

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

- Set dynamic rate to the Video player
- Change the rate value when the video is playing

Code example: 

```const videoRef = useRef(null);
  const [rate, setRate] = useState(1);
  const [paused, setPaused] = useState(false);
  const onEnd = () => {
    setPaused(true);
  };

  const onPress = () => {
    const rates = [0.25, 0.5, 1, 1.25, 1.75, 2];
    setRate(rates[Math.floor(rates.length * Math.random())]);
  };

  return (
    <View>
      <Video
        source={source}
        resizeMode="cover"
        paused={paused}
        rate={rate}
        onEnd={onEnd}
        ref={videoRef}
        style={StyleSheet.absoluteFillObject}
      />
      <Button title={"chnage Rate"} onPress={onPress} />
    </View>
  );```

**Comment by KrzysztofMoch** [comment]
Cloud you check if issue is present in v6 ?

**Comment by krifamed** [comment]
@KrzysztofMoch I managed to reproduce it on `v6.0.0-beta.6`

**Comment by freeboub** [comment]
@krifamed I checked with the sample app on simulator.
switching between 0.25 & 0.5 reproduce the issue.
If I switch from 0.25 to 1 and 0.5, I don't have the issue.
Is it workarounding the issue on a real device ? (I don't have one)

**Comment by krifamed** [comment]
@freeboub you mean to call setRate two times ? Even with this the issue still persist.
A real use case is to set the speed of the video and persist it, so that next time the video will be played with the saved speed

**Comment by freeboub** [comment]
Understood, But I don't know what we can do in react native video side. Looks like an issue linked to AVPLayer ...
please test on the sample, to understand my assumptions.
I think, the workaround would be
```TS
setRate(1)
setTimeout(() => {
    setRate(0.5)
), 100)
```
It can make send to integrate this workaround in the repo.

**Comment by krifamed** [comment]
@freeboub the workaround works fine 🎉

**Comment by Phecda** [comment]
I have this problem at 6.7.0 (RN 0.74, iPhone 12, iOS 17.5.1). Finally I resolve it like this:
```tsx
const [currentRate, setCurrentRate] = useState(1);

<Video
  onLoadStart={() => {
    setCurrentRate(1);
  }}
  onProgress={(e) => {
    if (e.playableDuration) {
      setCurrentRate(EXPECTED_RATE);
    }
  }}
  rate={currentRate}
/>
```
