### ISSUE TITLE
[BUG]: onEnd callback is not triggered specifically on iOS 17.4.1 devices

### ISSUE THREAD

**Issue by nikesh8** [TheWidlarzGroup/react-native-video#3627]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

While playing any video till the end, the onEnd Callback is not triggered on the specific iOS version > v17.4

"react-native": "0.68.7"
"react-native-video": "5.2.1"

### Reproduction

repository link

### Reproduction

Steps to reproduce this bug are: 

1. Play any video on iOS device which has iOS v17.4.1
2. Reach the end of the video and check that it won't trigger an `onEnd` callback. (I have tried to add alert to checking it is working or not.)

Device: iPhone 11, iPhone 12 mini, iPhone 15 pro max
iOS version: **17.4.1**

Please provide the solutions to overcome this problem.

Thanks in advance :)

**Comment by KrzysztofMoch** [comment]
Cloud you check if issue is present in v6 ?

**Comment by nikesh8** [comment]
> Cloud you check if issue is present in v6 ?

Since it needs to be reimplemented into the current player, I actually need to check in with the v5.

**Comment by whalemare** [comment]
Can reproduce on iPhone 11 iOS 17.4.1 in `6.0.0-beta.6` (latest supported for this model)
