### ISSUE TITLE
[BUG]: Unresolved reference: fabricUIManager

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#3633]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

facing this issue while compiling build on latest update v6.0.0-beta.7

react-native-video/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt:21:41 Unresolved reference: fabricUIManager

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: compile app with this latest version v6.0.0-beta.7

**Comment by KrzysztofMoch** [comment]
What react-native version are you using ?

**Comment by mkbhdana** [comment]
react native v0.73.6

**Comment by KrzysztofMoch** [comment]
@mkbhdana I have made PR that fixes it, cloud you confirm if this change works for you ? Thanks

**Comment by mkbhdana** [comment]
@KrzysztofMoch the issue is resolved now. Build successful.

**Comment by KrzysztofMoch** [comment]
Great, so I guess for now you can make patch or rollback to beta.6 - I will try make release with fix in 2-3 days

**Comment by freeboub** [comment]
Fix integrated on master, will be available on 6.0.0-beta.8

**Comment by eedeebee** [comment]
Also awaiting this fix, thanks for filing!

**Comment by KrzysztofMoch** [comment]
Guys `6.0.0-beta.8` is now available 🙌
