### ISSUE TITLE
[BUG]: Poster not working on android

### ISSUE THREAD

**Issue by LunatiqueCoder** [TheWidlarzGroup/react-native-video#3640]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

When using the `poster` prop, it works for a few seconds at the beginning, and then we have a blank screen.

### Reproduction

N/A

### Reproduction
N/A

### Solution: 
```diff
diff --git a/node_modules/react-native-video/src/Video.tsx b/node_modules/react-native-video/src/Video.tsx
index e496efc..5a97630 100644
--- a/node_modules/react-native-video/src/Video.tsx
+++ b/node_modules/react-native-video/src/Video.tsx
@@ -376,7 +376,7 @@ const Video = forwardRef<VideoRef, ReactVideoProps>(
     );
 
     const _onReadyForDisplay = useCallback(() => {
-      setShowPoster(false);
+      setShowPoster(!!poster);
       onReadyForDisplay?.();
     }, [setShowPoster, onReadyForDisplay]);
```

**Comment by freeboub** [comment]
Thank you for the patch, I will clarify the expected behavior soon. (But if you want to have a poster instead of the video, you should do it on the app side)

**Comment by freeboub** [comment]
I open a PR to fix the issue. I think you should be able to test it !
changing source without remount didn't reset the setShowPoster value

**Comment by LunatiqueCoder** [comment]
Hey @freeboub this seems to be reproducing on the latest version as well (v6.4.3) 😢

**Comment by LunatiqueCoder** [comment]
@freeboub This is how I managed to fix it: 

```diff
diff --git a/node_modules/react-native-video/src/Video.tsx b/node_modules/react-native-video/src/Video.tsx
index 49ca1e9..5cc196c 100644
--- a/node_modules/react-native-video/src/Video.tsx
+++ b/node_modules/react-native-video/src/Video.tsx
@@ -452,7 +452,7 @@ const Video = forwardRef<VideoRef, ReactVideoProps>(
     );
 
     const _onReadyForDisplay = useCallback(() => {
-      hasPoster && setShowPoster(false);
+      setShowPoster(hasPoster);
       onReadyForDisplay?.();
     }, [setShowPoster, hasPoster, onReadyForDisplay]);
 ```

Let me know if you want me to open a PR with this, it would be my pleasure to contribute.

**Comment by moskalakamil** [comment]
Hi @LunatiqueCoder, I see that this issue is still active. We would be grateful for your PR!

**Comment by Gautham495** [comment]
@moskalakamil Please solve this for android. @LunatiqueCoder It worked for android thank you!

**Comment by LunatiqueCoder** [comment]
I’m happy it worked for you. I’ll create a PR on Monday

**Comment by Gautham495** [comment]
@LunatiqueCoder Sorry it did not work properly for videos which has posters. I made a custom solution to tackle this issue.

**Comment by freeboub** [comment]
I tested again on the last version, I don't reproduce the issue.
Let's close this old ticket, please reopen a new one if needed

**Comment by LunatiqueCoder** [comment]
Hello @freeboub . This is still happening on the latest version :( I can provide a reproduction repository if needed. The patch I provided before still works for me.

**Comment by moskalakamil** [comment]
@LunatiqueCoder would you have a free 5 min to create a PR?

**Comment by LunatiqueCoder** [comment]
@moskalakamil Done. 
- https://github.com/TheWidlarzGroup/react-native-video/pull/4478
