### ISSUE TITLE
[BUG]: Build failed

### ISSUE THREAD

**Issue by projectninjatech** [TheWidlarzGroup/react-native-video#3641]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Task :react-native-video:compileDebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.      
182 actionable tasks: 11 executed, 171 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

e: file:///C:/Users/pnt/OneDrive/Desktop/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt:21:41 Unresolved reference: fabricUIManager

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-video:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
info Run CLI with --verbose flag for more details.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
To be followed here - https://github.com/react-native-video/react-native-video/issues/3633
