### ISSUE TITLE
[BUG]: basic sample project in repo on iOS doesn't show textTracks

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3642]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

I ran the basic sample app (on `master`) and was trying to find a working example of the textTracks on iOS since I can't get it to work on my own sample repo.
I expected to see subtitles/captions since the title of this one says subtitles.

<img width="387" alt="Screenshot 2024-04-02 at 2 43 02 PM" src="https://github.com/react-native-video/react-native-video/assets/107127397/a11bbe87-fb6e-4390-8430-8a7fd3f0a8a3">

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
1. Run `git clean -xdf && yarn xbasic install && cd examples/basic/ios && pod install && cd - && yarn xbasic ios`*
* At this point I noticed my `Podfile.lock` had some differences with git diff `COCOAPODS: 1.15.2`
2. Click channel up until reaches 'sintel with sideLoaded subtitles', watch until audio occurs.

Observe no captions/subtitles.

**Comment by paulrinaldi** [comment]
@freeboub am I correct that this video in the sample should display textTracks? I am just presuming based off its title.

**Comment by paulrinaldi** [comment]
Additional info:
iOS simulator used: iPhone SE (3rd Generation) iOS 17.4
MacOs Sonoma 14.4.1, Apple M1 Pro

**Comment by paulrinaldi** [comment]
I can confirm that `this.srcList[this.state.srcListId]?.textTracks` is equal to `[{"language": "en", "title": "test", "type": "text/vtt", "uri": "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"}]` on render
And I can confirm that
`this.state.selectedTextTrack` is equal to `undefined`

**Comment by freeboub** [comment]
> @freeboub am I correct that this video in the sample should display textTracks? I am just presuming based off its title.

Yes I think it should and I also think this was working on 5.2 version

**Comment by paulrinaldi** [comment]
Even when I set `selectedTextTrack={{type: 'index', value: 0}}`, it does not show them.

**Comment by paulrinaldi** [comment]
Same result for `selectedTextTrack={{ type: SelectedTrackType.INDEX, value: 0 }}`

**Comment by coofzilla** [comment]
@paulrinaldi are you able to see the text tracks on the dragon video? its the sintel one.

**Comment by paulrinaldi** [comment]
> @paulrinaldi are you able to see the text tracks on the dragon video? its the sintel one.

I do not. (sintel with subtitles)
iPhone 15 iOS 17.2

https://github.com/react-native-video/react-native-video/assets/107127397/7eb24310-a315-47d0-ad61-e930c3fbea86

Logging:
```
console.log('[[');
console.log('this.state.srcListId', this.state.srcListId);
console.log('textTracks={', this.srcList[this.state.srcListId]?.textTracks, '}');
console.log(']]');
```
in the `renderVideoView()` before the return results in:
```
[[
  this.state.srcListId 7
  textTracks={ undefined }
]]
```
while playing the sintel video (dragon) (sintel with subtitles)

-
Even when replacing 
`textTracks={this.srcList[this.state.srcListId]?.textTracks}`
 with 
 ```
 texTracks={[{
            title: 'test',
            language: 'en' as ISO639_1,
            type: TextTrackType.VTT,
            uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
          },]}
```
and  replacing
```
selectedTextTrack={this.state.selectedTextTrack}
```
with
```
selectedTextTrack={{type: SelectedTrackType.INDEX, value: 0}}
```
no text tracks are displayed on the sintel track (dragon) (sintel with subtitles)

**Comment by paulrinaldi** [comment]
(sintel with sideLoaded subtitles) also does not show subtitles
<img width="410" alt="Screenshot 2024-04-03 at 10 15 25 AM" src="https://github.com/react-native-video/react-native-video/assets/107127397/aba9017a-a51e-43aa-9e74-77d4b9675328">
with
`textTracks={this.srcList[this.state.srcListId]?.textTracks}`
`selectedTextTrack={{type: SelectedTrackType.INDEX, value: 0}}`

Logs:
 LOG  [[
 LOG  this.state.srcListId 8
 LOG  textTracks={ [{"language": "en", "title": "test", "type": "text/vtt", "uri": "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt"}] }
 LOG  ]]

**Comment by coofzilla** [comment]
Are you able to use `SelectedTrackType.Language value: 'en'` ? or do you _have_ to use the index?

**Comment by freeboub** [comment]
I started to investigate yesterday, looks like a regression from swift promise removal ( ping @KrzysztofMoch ) I will push my changes today even if I am not sure everything works fine. (I will have very limited time next week).
I am talking about the " sintel with subtitles " the sideloaded subtitles also don't work but it is another issue, I didn't find the root cause yet

**Comment by freeboub** [comment]
I just push a branch with a first fix. Still need to understand why side loaded textTracks cannot be selected

**Comment by KrzysztofMoch** [comment]
@freeboub @paulrinaldi I have good news - I have fixed sideload for subtitles! I will make PR soon. One thing that is very important is that sideload subtitles will not work for HLS streams (m3u8)

**Comment by freeboub** [comment]
> @freeboub @paulrinaldi I have good news - I have fixed sideload for subtitles! I will make PR soon. One thing that is very important is that sideload subtitles will not work for HLS streams (m3u8)

I was also able to make it work on MP4 local file. There is a test to avoid adding sideloaded text tracks on m3u. I don't understand why this limitation has been introduced, and I cannot confirm from google or apple documentation that this feature is not feasible... @KrzysztofMoch did you find such information ?
I would like to test the behavior with 5.2, but I didn't find time yet ...

**Comment by KrzysztofMoch** [comment]
We do some magic with `AVMutableCompositionTrack` to add subtitles to video - and we cannot use streams such as HLS. I found this information going through the forums like stackoverflow & apple forum (not sure if it is somewhere in docs)

**Comment by freeboub** [comment]
> We do some magic with `AVMutableCompositionTrack` to add subtitles to video - and we cannot use streams such as HLS. I found this information going through the forums like stackoverflow & apple forum (not sure if it is somewhere in docs)

Ok, thanks! Your looks good, I think you should add this information in documentation (for the m3u) !
Btw , please let me cross check the behavior on 5.2

**Comment by KrzysztofMoch** [comment]
It's already here 
![CleanShot 2024-04-19 at 13 57 53@2x](https://github.com/react-native-video/react-native-video/assets/83216158/82d36943-4b2a-4a0f-821d-98b95e003b9a)
