### ISSUE TITLE
[BUG]: Video is Playing even after video is reached its end , in IOS

### ISSUE THREAD

**Issue by Salman-Raj** [TheWidlarzGroup/react-native-video#3644]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

I started playing one Video in iOS Simulator, and even if the video reached its end, it played again continuously, in android, it is working fine

this is my code

class VideoPlayer extends PureComponent<VideoPlayerProps, IState> {

  private videoRef = React.createRef<Video>();
    blurListener: any;
  playerRef: any;
  subscription: any;
  focusSubscription: any;
  constructor(props: VideoPlayerProps) {
    super(props);
    this.videoRef = React.createRef();
    this.state = {
      videoPaused: false,
      playPuse: true,
      duration: "00:00",
      unformatedcurrentTime: "",
      unformatedDuration: responsiveWidth(49),
      currentDuration: 0,
      currentTime: "00:00",
      fillPrecentage: 0,
      videoControls: true,
      fullscreenAndroid: false,
      videoPercentage: 0,
      currentPlayingVideoId: 0,
      currentTimeUnformated: 0,
      loading: false,
      fullyWatched: false,
      orientation: Dimensions.get('screen').width > Dimensions.get('screen').height ? 'landscape' : 'portrait',
      videoEnded:false,
      appState: AppState.currentState
    }
  }

  handleFullScreen = () => {
    this.props.setFullScren?.(this.props.source, true, this.props.index);
  };

  handleExitFullScreen = () => {
    this.props.setFullScren?.(null, false, this.props.index);
  };

  onReadyForDisplay = () => {
    this.setState({ loading: false });
  };

  handleVideoEnd = () => {
    console.log("video ended")
    try{
    if (this.videoRef.current) {
      this.videoRef.current?.setState({paused: true})
      this.videoRef.current?.seek(0);
      setTimeout(()=>{
      this.setState({videoPaused:true,videoEnded:true,playPuse:true})
      },100)
    }
    }
    catch(error:string|unknown){
    console.log(error)
    }
  };

  render() {
    const { videoControls,unformatedDuration, currentTime,currentTimeUnformated } = this.state;
    const { source, fullscreen, videoId } = this.props
    return (
              <Video
                volume={1.0}
                ref={this.videoRef}
                source={{ uri: source }}
                style={(Platform.OS === "android" && fullscreen) ? styles.videoFullscreen : styles.video}
                resizeMode="contain"
                onProgress={this.onProgress}
                onLoad={this.onLoad}
                paused={videoId}
                fullscreen={fullscreen}
                onLoadStart={this.onVideoLoadStart}
                onReadyForDisplay={this.onReadyForDisplay}
                playInBackground={false}
                playWhenInactie={false}
                onBuffer={this.onVideoBuffer}
                repeat={false}
                rate={1.0}
                loop={false}
                onEnd={this.handleVideoEnd}
                shouldPlay={!this.state.videoEnded}
                playWhenInactive={false}
                ignoreSilentSwitch="ignore"
                onPlaybackStatusUpdate={this.handlePlaybackStatusUpdate}
              />
               );
  }
}

const mapStateToProps = (state: RootState) => {
  return {
    videoProgress: state.MyCourses.videoProgress,
    eachTopic: state.courses.eachTopic,
    currentVideoProgress: state.MyCourses.currentVideoProgress,
    sendingProgress: state.MyCourses.sendingProgress,
    videoLoader: state.courses.loadingforvideos
  }
}

export default connect(mapStateToProps)(VideoPlayer);

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Hello, thank you for the report, but the sample is too complicated to be able to investigate...
1-can you simplify it or reproduce the issue with example/basic app?
2- can you provide a git repository with the sample ?
3- which beta version do you use ?
Thank you

**Comment by Salman-Raj** [comment]
Hi React-Native-Video/React-Native-Video

I'm working on video component, Im uploading videos to server and rendering
those videos to watch, but the issue is once video is clicked for playing,
it is playing continuously in ios device/simulator, but i didn't get issue
with Android device it is working fine.

Expected result is video should be paused after reached its end.

 handleVideoEnd = () => {
    console.log("video ended")
    try{
    if (this.videoRef.current) {
      this.videoRef.current?.setState({paused: true})
      this.videoRef.current?.seek(0);
      setTimeout(()=>{
      this.setState({videoPaused:true,videoEnded:true,playPuse:true})
      },100)
    }
    }
    catch(error:string|unknown){
    console.log(error)
    }
  };



<Video
              volume={1.0}
              ref={this.videoRef}
              source={{ uri: source }}
              style={(Platform.OS === "android" && fullscreen) ? styles.videoFullscreen : styles.video}
              resizeMode="contain"
              onProgress={this.onProgress}
              onLoad={this.onLoad}
              paused={videoId}
              fullscreen={fullscreen}
              onLoadStart={this.onVideoLoadStart}
              onReadyForDisplay={this.onReadyForDisplay}
              playInBackground={false}
              playWhenInactie={false}
              onBuffer={this.onVideoBuffer}
              repeat={false}
              rate={1.0}
              loop={false}
              onEnd={this.handleVideoEnd}
              shouldPlay={!this.state.videoEnded}
              playWhenInactive={false}
              ignoreSilentSwitch="ignore"
              onPlaybackStatusUpdate={this.handlePlaybackStatusUpdate}
              />

**Comment by freeboub** [comment]
Man, I cannot debug your app.

what is the usage of following states : playPuse and videoPaused:
`this.setState({videoPaused:true,videoEnded:true,playPuse:true})`

in Video you pass: `paused={videoId}` why ? you want to be paused when you have a valid video ?

What is the purpose of handleVideoEnd handler ? if you seek to 0, the video is no more at the end !

you can also investigate what is happening in 
```
    @objc
    func setSeek(_ info: NSDictionary!) {
```
function.

**Comment by Salman-Raj** [comment]
Hello,
I Have Multiple Videos, based on videoId, and we are Pausing video, I tried with states to pause the video, But that didn't work, The onEnd function is not triggered at the Video Ending, So Basically, How video can be paused in iOS, It should be paused at Video ends.

**Comment by Salman-Raj** [comment]
@freeboub Please check this link, video is playing multiple times in iOS device

https://drive.google.com/file/d/11EZrSQhh0pKG2igKiljlSiR0JS2YD4Y3/view?usp=drivesdk

**Comment by freeboub** [comment]
@Salman-Raj can you confirm this:
1- At the end of the video you want to rewind to the beginning and pause playback
2- Such code shall be the easiest way to achieve it:

```
  onEnd = () => {
    if (this.video) {
      this.setState({paused: true});   // -> will set the prop paused to true
      this.video?.seek(0);
    }
  };
``` 
This code is not working as expected currently, but this is something easy to fix.

**Comment by freeboub** [comment]
@Salman-Raj If my understanding is correct, following PR shall fix the issue: https://github.com/react-native-video/react-native-video/pull/3650

**Comment by Salman-Raj** [comment]
@freeboub 
I tried with this code

  onEnd = () => {
    if (this.video) {
      this.setState({paused: true});   // -> will set the prop paused to true
      this.video?.seek(0);
    }
  };
  
  Still, it is not resolved, it is working fine in Android, issue is with iOS devices only.

**Comment by freeboub** [comment]
@Salman-Raj do you also use the new branch with the fix for ios ?

**Comment by Salman-Raj** [comment]
@freeboub nope, I'm working on one branch only, I haven't created any new branch, particularly for iOS.

**Comment by freeboub** [comment]
fix will be included in 6.0.0-beta.9

**Comment by Salman-Raj** [comment]
@freeboub When  this version will be available?

**Comment by Salman-Raj** [comment]
@freeboub  My Issue is resolved
