### ISSUE TITLE
[BUG]: onPlaybackRateChangeData is missing in 6.0.0-beta.6 and not documented as a breaking change

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3645]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

onPlaybackRateChangeData appears missing ; this was in 5.2 on iOS the only way to detect start and stop of the video reliably and now it's gone.  I can try out OnPlaybackStateChange

### Reproduction

repository link

### Reproduction

The event is missing.

**Comment by freeboub** [comment]
The types was not correct, this PR fixes the onPlaybackRateChangeData type https://github.com/react-native-video/react-native-video/pull/3651

**Comment by freeboub** [comment]
linked Pr merge, to be retested on 6.0.0-beta.9
