### ISSUE TITLE
[BUG]: onPlaybackRateChange and onPlaybackStateChange not called  iOS or Android when the user stops and restarts the video via native controls.  

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3646]
### Version

v6 (Beta)

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: just wire up these callbacks and see they don't ever get called.  I'd be happy to see an existence proof that they work.

**Comment by freeboub** [comment]
added in the sample from this PR: https://github.com/react-native-video/react-native-video/pull/3651
seems to work on android and ios

**Comment by freeboub** [comment]
PR merged, to be retested on V6.0.0-beta.9
