### ISSUE TITLE
Components with playWhenInactive={false} do not start playing again upon closing of control center

### ISSUE THREAD

**Issue by ryanscottaudio** [TheWidlarzGroup/react-native-video#365]
Or notification center or multi-task view.

**Comment by byohay** [comment]
This also happens when an alert pops up while the video is playing.

**Comment by amsul** [comment]
I guess the decent workaround is mentioned here: https://github.com/react-native-community/react-native-video/issues/336#issuecomment-305855250

**Comment by chesovnik** [comment]
> I guess the decent workaround is mentioned here: [#336 (comment)](https://github.com/react-native-video/react-native-video/issues/336#issuecomment-305855250)

Fortunately, in my case, `handleAppStateChange` not fired when the user activates the notification center or control center.

The issue isn't solved yet
