### ISSUE TITLE
[BUG]: playInBackground does not work on iOS in basic example project

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3652]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

6.0.0-beta.7

Enable playInBackground as noted in the [docs](https://react-native-video.github.io/react-native-video/component/props#playinbackground), including ignoreSilentSwitch='ignore'. I checked the background audio in Xcode for the project.
 
 I drag the app upwards to background it and the video stops. I expected audio to continue.
 
 When using breakpoints and logs in Xcode, I do not see any problems with the function `applicationDidEnterBackground` since it correctly does not set the player to nil and I didn't see anything else run to set the rate to 0 or pause the video, I'm very confused as to what causes the video player's audio to stop. 
 
 Perhaps the audio session type is wrong?

### Reproduction

https://github.com/paulrinaldi/react-native-video

### Reproduction

Step to reproduce this bug are: 
Pull the forked project (or get a diff and apply it), run
`git clean -xdf && yarn xbasic install && cd examples/basic/ios && pod install && cd - && yarn xbasic ios`
^ if this fails to create the bundler (which it does for me), I then open `examples/basic/ios/videoplayer.xcworkspace` in Xcode and hit play.

Let video load, drag app upward to background the app, observe the audio (video's audio) stop. When you open the app up again in the simulator, you'll notice it continues to play.

**Comment by paulrinaldi** [comment]
<img width="355" alt="Screenshot 2024-04-03 at 3 31 10 PM" src="https://github.com/react-native-video/react-native-video/assets/107127397/998b4c4d-4551-4dca-af2c-1a14fd0ab311">
On backgrounding the app, these logs are generated^

**Comment by KrzysztofMoch** [comment]
I can't remember if in example app we enabled background activity in Xcode - will check out this and back to you

**Comment by paulrinaldi** [comment]
<img width="728" alt="Screenshot 2024-04-03 at 3 40 10 PM" src="https://github.com/react-native-video/react-native-video/assets/107127397/0a501af5-3c67-47f8-8ea9-00133d6a3e1f">
I believe it is since I see this in Xcode?

**Comment by KrzysztofMoch** [comment]
Oh yes it is - will check it, why it is not working (I remember it work last time when I was testing it 😅)

**Comment by paulrinaldi** [comment]
Observed today:
If I refresh the app while it is in the background (via r in result of npx react-native start), the video will start playing without the app in the foreground! However if I background the app, then the video pauses. And then if I then foreground it (e.g. by opening it from the homescreen), the video continues (without us having to press play).

**Comment by paulrinaldi** [comment]
I've only debugged and looked into `RCTVideo.swift` and not the other files.

**Comment by paulrinaldi** [comment]
I checked the `AVAudioSession.sharedInstance().category.rawValue`, it is `AVAudioSessionCategoryPlayback` in `applicationDidEnterBackground` so that is correct... not sure what could be going wrong.

f28bf0ae3318d104c4088bb79b819ba948013607 is the last commit the fork came from (chore release beta8)

**Comment by paulrinaldi** [comment]
I fixed it by setting:
```
if #available(iOS 15.0, *) {
    _playerLayer?.player?.audiovisualBackgroundPlaybackPolicy = .continuesIfPossible
}
```
, it used to be `.automatic` in that method
https://developer.apple.com/documentation/avfoundation/avplayer/3787548-audiovisualbackgroundplaybackpol 
@KrzysztofMoch 
Now I need to make it still pause when other audio plays...

This may then only work for iOS 15+...
Some data on worldwide use of iOS versions: https://www.statista.com/statistics/565270/apple-devices-ios-version-share-worldwide/

**Comment by KrzysztofMoch** [comment]
This make sense will try to make PR with this

**Comment by paulrinaldi** [comment]
Any idea on how to ensure audio/video pauses when other audio starts?

I've tried some solutions without success:
Checking `AVAudioSession.sharedInstance().isOtherAudioPlaying` after 5 seconds of backgrounding the app
Adding observers for `AVAudioSession`'s `name: AVAudioSession.silenceSecondaryAudioHintNotification` and `name: AVAudioSession.interruptionNotification` but neither of them are triggered when I play youtube in safari while the video/audio is playing in the background in the RNV basic sample app.

**Comment by paulrinaldi** [comment]
I've got background audio working now in my expo project that uses RNV 6 beta 8 on iOS and Android. On iOS, the app video goes to PiP and on Android the app audio keeps playing in background as the app is backgrounded respectively(even though PiP prop is is not set) inspired by the patch above with some additional code:

[react-native-video+6.0.0-beta.8.patch](https://github.com/react-native-video/react-native-video/files/15153621/react-native-video%2B6.0.0-beta.8.patch)

Now I am working to get the audio to stop when other audio is playing in iOS e.g. player is in PiP/background audio and user opens safari and starts a youtube video -> expected behavior: app audio/video pauses. Looking forward to a fix though for this in the future without my patch.

I suspect not all users will desire this patch since not all user experiences are desired to be this way and thankfully iOS lets users set different types of video playback.

Background audio stops when in Android and youtube video plays.

Cheers.

**Comment by amayanga** [comment]
I'm having the same issue on iOS. Will this be fixed anytime soon?

**Comment by paulrinaldi** [comment]
I'm still using a patch, I haven't spent time figuring out a solution for iOS14 and below.

**Comment by paulrinaldi** [comment]
I no longer think I need to use the patch for 6.2.0. I tested youtube safari and phone interruption for video in background on iOS v15 and the video responded appropriately in my expo app. I would assume it works correctly in the example as well.

My app does however pause live video on load but that's an issue likely from my own set up.

**Comment by freeboub** [comment]
@paulrinaldi Sorry we didn't handle this issue... Is this still requested / a problem on your side ?

**Comment by paulrinaldi** [comment]
I'm still using a patch and haven't had time to test without it. We can
close this and if I see a problem without the patch, I'll make a new issue.

**Comment by freeboub** [comment]
Thank you @paulrinaldi !
