### ISSUE TITLE
[BUG]: ResizeMode render video before applying the style props

### ISSUE THREAD

**Issue by douzal34** [TheWidlarzGroup/react-native-video#3653]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I am the creator of SoSkills App which is available on Apple and Android (more info on https://soskills.fr)

Since beta 6 version is introduced and ExoPlayer is deprecated, i struggled to get resizeMode working as on Alpha version.

Older behavior was to have resizeMode _contain_ when video.height < video.width and a resizeMode _cover_ when video.height > video.width. Both resizeMode allow to me to either center the video or cover the video in fullscreen.
Since beta version, resizeMode _cover_ / _contain_ / _none_ is doing a pre render on the video and only applying style after which generate a resize when the video is appearing on the screen, especially during the loading of the video.

On Alpha version, video was loading with resizeMode and style in the same time, not with some delay.

My best option is to set resizeMode to _stretch_ in order to control the style myself but i admit that this option is not the best cause _cover_ and _contain_ are really useful for scaling the video.

https://github.com/react-native-video/react-native-video/assets/3983160/3a248256-9904-42b5-8ac2-ba6c8530daf4

### Reproduction

repository link

### Reproduction

Create a FlatList with some videos and try to swipe through videos with resizeMode _contain_ / _none_ / _cover_ on a Android phone.

When you swipe to the next video, set paused props to false and load video: you will see resizeMode applied and style be setted just after.

**Comment by kosmokoks** [comment]
Did you find any solution?

**Comment by haonguyendirox** [comment]
I've encountered a similar issue as well.
Do we have any solution to prevent the video from scaling during the initial loading phase? This issue only seems to occur on Android

**Comment by douzal34** [comment]
As i said on my initial message, set resizeMode to _stretch_ allow me to scale the videos according to theirs dimensions but sometime i got something more stretched than expected @kosmokoks @haonguyendirox.
So if a fix can be apply to have the same behavior as IOS, could be great.

**Comment by freeboub** [comment]
@douzal34 This issue shall be fixed on 6.0.0 !

**Comment by douzal34** [comment]
My app on production has the version 6.0.0, issue is fixed on Android, good job ! @freeboub
