### ISSUE TITLE
[BUG]:  Inconsistent Video Looping Across Devices due to Audio Format

### ISSUE THREAD

**Issue by Owe1n** [TheWidlarzGroup/react-native-video#3661]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### Environment:
- **Device with issue**: iPhone 11 (Emulator), iPad (Physical)
- **Working device**: Android Pixel 7 (Physical)
### Description:
I am encountering a problem where the `repeat` prop in a `Video` component, intended for looping videos, behaves inconsistently across different devices. Specifically, the looping functionality works flawlessly on an Android Pixel 7 device but exhibits issues on an iPhone 11 (emulator) and an iPad (physical device). On these iOS devices, certain videos only loop twice before throttling and restarting, rather than looping seamlessly.

Upon investigation, the issue appears to be related to the audio format of the videos. Videos with MPEG-4 AAC audio at 44100 Hz loop without any problems. However, videos recorded with my Pixel 7 that have MPEG-4 AAC audio at 48000 Hz do not loop correctly. Muting the sound of a problematic video results in proper looping, further suggesting that the audio format or characteristics may be at the root of the issue.

### Code Sample:
```jsx
<Video
  key={componentKey}
  source={{
    uri: videoUri,
    headers: {
      Authorization: `Bearer ${token}`,
    },
  }}
  repeat={true} // For looping the video
  resizeMode="cover"
  style={style}
  onEnd={onEnd}
  playWhenInactive={true}
  paused={!shouldVideoPlay}
  {...otherProps}
/>
```
### Reproduction

Step to reproduce this bug are: 
Play a video with MPEG-4 AAC, 48000 Hz audio on an iOS device using the above component.
Observe that the video does not loop seamlessly after two iterations, unlike videos with 44100 Hz audio or muted audio.

**Comment by freeboub** [comment]
format/device specific issue, I think the only solution is to enable ffmeg integration, to be followed in : https://github.com/TheWidlarzGroup/react-native-video/issues/3106
