### ISSUE TITLE
[Feature]: Allow to configure styles for subtitle track

### ISSUE THREAD

**Issue by Sumeeth-24** [TheWidlarzGroup/react-native-video#3662]
### Description

Presently, our subtitle tracks lack the functionality to incorporate custom styles. Consequently, users encounter an inconvenience when attempting to pinch zoom to full screen, as the subtitle style becomes cropped and renders the subtitle track unreadable. For instance, if there are three lines of subtitles, upon entering full screen mode, only one line remains visible while the remaining two lines disappear below the screen. To address this issue, we require a solution that enables control over various configurations such as padding bottom, top, and other attributes. Additionally, implementing features like automatically centering subtitles when the video controller appears and shifting them downward when the controller is hidden would significantly enhance user experience. Therefore, the primary focus should be on introducing the basic feature of custom style customization for subtitle tracks.

### Why it is needed ?

Users encounter an inconvenience when attempting to pinch zoom to full screen, as the subtitle style becomes cropped and renders the subtitle track unreadable. For instance, if there are three lines of subtitles, upon entering full screen mode, only one line remains visible while the remaining two lines disappear below the screen.

### Possible implementation

Probably need additional props and make changes in native code.

### Code sample

Code sample

**Comment by freeboub** [comment]
did you try using : https://thewidlarzgroup.github.io/react-native-video/component/props#subtitlestyle ?

**Comment by freeboub** [comment]
@Sumeeth-24 Is the linked PR answer to your issue ?

**Comment by Sumeeth-24** [comment]
Hi Team,
Yes, the above PR has solved the issue and thanks everyone for the support
and effort put into it. Now the only obstacle or problem which we are
facing is of PipMode in Android. We are not able to play/pause the video in
pipmode and also not able to click on cross icon to close the video. Need
fix for this issue.

**Comment by freeboub** [comment]
fix will be available in 6.1.3

**Comment by freeboub** [comment]
Please see last merged PR. The proposed change was causing a regression, the original behavior has been restored, so in next release you will have to add a prop to configure it.
