### ISSUE TITLE
[BUG]: Adding external subtitles restarts video

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#3665]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

A bug happened!

whenever adding external subtitles video restarts from position 0 or if startPosition is set than it will start video from that position.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

add external subtitles while playing video.

**Comment by freeboub** [comment]
This is an exoplayer limitation, the fix would be to move it source prop
