### ISSUE TITLE
[BUG]: [iOS] presentFullscreenPlayer crash

### ISSUE THREAD

**Issue by kesha-antonov** [TheWidlarzGroup/react-native-video#3671]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

Hi,

`presentFullscreenPlayer` method is not working. It's either crashes or not doing anything. I need to show video in fullscreen mode in modal
https://react-native-video.github.io/react-native-video/component/methods#presentfullscreenplayer

<img width="303" alt="Screenshot 2024-04-11 at 00 26 15" src="https://github.com/react-native-video/react-native-video/assets/11584712/75fb691d-225c-49f7-a758-1d23dd1f71ea">
<img width="1197" alt="Screenshot 2024-04-11 at 00 26 06" src="https://github.com/react-native-video/react-native-video/assets/11584712/9ac97aa8-a84b-4e1f-98a6-42c85f05eb57">

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

```
const videoRef = useRef<VideoRef>()

const videoOnLoad = useCallback(() => {
    console.log('videoOnLoad', videoRef.current)
    videoRef.current?.presentFullscreenPlayer()
  }, [])
  
  ....

    <Modal isVisible={isModalVisible} onClose={toggleModal}>
        <View style={[styles.videoInModal, { width: deviceWidth, height: 500 }]}>
          {
            isModalVisible && (
              <Video
                source={{ uri: currentMessage.video }}
                ref={videoRef}
                style={{
                  flex: 1,
                  flexGrow: 1,
                  flexShrink: 1,
                }}
                muted={false}
                paused={false}
                controls
                fullScreen
                onLoad={videoOnLoad}
                onFullscreenPlayerWillDismiss={toggleModal}
              />
            )
          }
        </View>
      </Modal>
```

**Comment by KrzysztofMoch** [comment]
Yep, seem like we cant use fullscreen in modal - I have tried to create workaround for this but nit successfully

**Comment by bfricka** [comment]
We've had this issue since 5.x. Our "FullscreenModal" has a prop `hasVideo`, which, if true on iOS, we set `transparent={false}`. The combination of `presentationStyle="fullScreen"` and `transparent={true}` causes this crash. Setting transparent to false fixes the issue. If you absolutely need `transparent={true}`, then unfortunately, I'm unsure.
