### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Geneonosis** [TheWidlarzGroup/react-native-video#3674]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

The HLS .m3u8 media stream on iOS allows for closed caption, both iOS and Android SHOW the closed captions. However only iOS gives me the option of changing the state of the captions, i.e. selecting "off" "default" or "English" or other languages. Android's Media player does not seem to allow me select the caption state. I've tried everything including setting up text tracks hard coded. but the playback controls for Android still do not show a way to select a CC language. 

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

`npm install react-native-video@beta`

configure the media player to point to a .m3u8 media stream

iOS shows closed captions and shows caption selector
Android shows closed captions but does not show a caption selector!

**Comment by KrzysztofMoch** [comment]
AFAIK `m3u8` streams does not support external captions on iOS

**Comment by freeboub** [comment]
@Geneonosis can you please:
- add a title to the ticket
- provide sample to replicate the issue (I didn't clearly understand the description)
Thank you
