### ISSUE TITLE
[BUG]: IOS- keeps buffering

### ISSUE THREAD

**Issue by roo12312** [TheWidlarzGroup/react-native-video#3675]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

After seeking the hls video in ios is just stuck buffering and never plays back.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Any way to reproduce? Are you able to reproduce with the sample included in the repo ?

**Comment by roo12312** [comment]
> Any way to reproduce? Are you able to reproduce with the sample included in the repo ?

Hi, I'm working with Fairplay DRM.. I'm not quite sure how to send a reproducible example

**Comment by roo12312** [comment]
video with lesser duration plays fine but not with more duration(30 mins +). The player is stuck buffering

**Comment by roo12312** [comment]
the issue still persists in the latest version

**Comment by roo12312** [comment]
@freeboub the issue still exists for the DRM videos on ios... videos without DRM work fine.

**Comment by freeboub** [comment]
Not sure how we can help here ...
Do you have issues in xcode logs ? Did you try to record a charles trace to ensure network communications work fine ?

**Comment by roo12312** [comment]
@freeboub the network communication is fine and there are no xcode logs.. it's just the video buffers forever. `{"isBuffering": true, "target": 6819}`

Im currently testing with ios 14.8

**Comment by roo12312** [comment]
@freeboub I tested on a newer device with the latest ios but the problem still exists... probably can we connect on discord and I will share the DRM content so that you can check it from your end also.

**Comment by roo12312** [comment]
adding `maxBitRate={3000000}` the video loads perfectly

**Comment by KrzysztofMoch** [comment]
So probably not an library issue ?

**Comment by roo12312** [comment]
> So probably not an library issue ? 

I really don't understand what exactly is the issue.. or how do I even debug the issue

**Comment by KrzysztofMoch** [comment]
Maybe I will add to docs (in debug section) to try set `maxBitRate` in such case - let's close this as I see that this worked for you

**Comment by roo12312** [comment]
setting `maxBitRate={0}` also works fine

**Comment by roo12312** [comment]
@freeboub @KrzysztofMoch reopening the issue as setting `maxBitRate` just lowers the video quality. Also, i tested with `expo-video` and it works fine... I don't know what the issue is with react-native-video with DRM videos. Is there any steps to debug this buffering issue?

**Comment by Meet-Kapadiya** [comment]
Same problem still persists in 6.2.0, You can check by logging "isBuffering", It never returns false

**Comment by Meet-Kapadiya** [comment]
``` jsx 
 useEffect(() => {
    if (Platform.OS === 'ios' && loading) {
      setTimeout(() => {
        setLoading(false);
      }, 2500);
    }
  }, [loading]);
```
For temporary workaround you can do this

**Comment by roo12312** [comment]
We cannot use this hack in production... The bug should be fixed

**Comment by freeboub** [comment]
If you want to investigate here are some inputs:
 handlePlaybackBufferKeyEmpty and handlePlaybackLikelyToKeepUp are good starting points.
relevant documentation is here: https://developer.apple.com/documentation/avfoundation/avplayeritem/1390348-isplaybacklikelytokeepup

**Comment by Meet-Kapadiya** [comment]
[react-native-video+6.1.2.patch](https://github.com/TheWidlarzGroup/react-native-video/files/15431981/react-native-video%2B6.1.2.patch)

I made the patch, it works fine, but at the beginning when I start playing the video, the buffering takes time to return false is proportional to the length of the video.

**Comment by roo12312** [comment]
@Meet-Kapadiya are you testing with drm videos or normal?

**Comment by Meet-Kapadiya** [comment]
HLS streams

**Comment by Meet-Kapadiya** [comment]
> [react-native-video+6.1.2.patch](https://github.com/TheWidlarzGroup/react-native-video/files/15431981/react-native-video%2B6.1.2.patch)
> 
> I made the patch, it works fine, but at the beginning when I start playing the video, the buffering takes time to return false is proportional to the length of the video.

To solve this you can set 

- preferredForwardBufferDuration={15} (In Seconds)
- Default value is 0, So player will choose an appropriate level of buffering

**Comment by maksymhcode-care** [comment]
It seems that it only happens with HLS/m3u8 format, please take a look at that @freeboub

**Comment by suritkandel** [comment]
The MPEG-TS & m3u8 video does not work at all but for HLS the video works for 30 seconds and you get a error.

HLS Error at 30 seconds:
{"error": {"code": -12312, "domain": "CoreMediaErrorDomain", "localizedDescription": "The operation couldn’t be completed. (CoreMediaErrorDomain error -12312.)", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 10675} error

 Let me know if you need a url to try to replicate this?  @freeboub 
     
I appreciate your help.

Video Code Below:
<Video
            paused={paused}
            source={{
              uri: url,
            }}
            onLoadStart={() => setIsLoading(true)}
            onLoad={() => setIsLoading(false)}
            ref={ref}
            fullscreen={fullScreen ? true : false}
            bufferConfig={bufferConfig}
            // bufferConfig={{
            //   minBufferMs: 15000, // Minimum buffer in milliseconds
            //   // maxBufferMs: calculateBufferSize(1000000), // Maximum buffer size based on bitrate
            //   maxBufferMs: 50000,
            //   bufferForPlaybackMs: 5000, // Buffer needed for playback start
            //   bufferForPlaybackAfterRebufferMs: 20000, // Buffer needed after rebuffering
            // }}
            preferredForwardBufferDuration={15}
            selectedVideoTrack={{
              type: 'resolution',
              value: 1080,
            }}
            onProgress={handleProgress}
            // onError={handleVideoError}
            style={{width: '100%', height: fullScreen ? '100%' : 250}}
            resizeMode={fullScreen ? 'cover' : 'contain'}
            playInBackground={true}
            pictureInPicture={true}
            muted={mute}
            fullscreenAutorotate={true}
            ignoreSilentSwitch={'ignore'}
            minLoadRetryCount={5} // retry 5 times
            mixWithOthers={'duck'}
          />
           

     Example Video Below:
     https://github.com/TheWidlarzGroup/react-native-video/assets/123834956/ad208e09-5bc0-4f60-8725-652cefd8e535

**Comment by maksymhcode-care** [comment]
@freeboub @KrzysztofMoch Please try any m3u8/hls test url you prefer. onBuffer will return true even if video is playing
https://ottverse.com/free-hls-m3u8-test-urls/

**Comment by edenmoyal1** [comment]
It happens to me too.
I used onPlaybackStateChanged and set isBuffering to false when the video is playing.

**Comment by maksymhcode-care** [comment]
> It happens to me too. I used onPlaybackStateChanged and set isBuffering to false when the video is playing.

But what if video is playing and buffering at the same time?

**Comment by maksymhcode-care** [comment]
It's a work around, but i can suggest to try this:

`  const onPlaybackStateChanged = ({ isPlaying }) => {
      setIsLoading(!isPaused.current && !isPlaying);
    };
`

Basically isPlaying  from onPlaybackStateChanged return false, but you did not paused the video it means it's loading

**Comment by roo12312** [comment]
@moskalakamil  can you help me debug the issue? there are no error logs... it's just the video keeps on buffering at random spots... especially with longer-length videos

**Comment by moskalakamil** [comment]
> @freeboub the issue still exists for the DRM videos on ios... videos without DRM work fine.

Hi @rohankm, could you please check the changes from #4136? If the issue is related to DRM, it has been rewritten there.

**Comment by roo12312** [comment]
> > @freeboub the issue still exists for the DRM videos on ios... videos without DRM work fine.
> 
> Hi @rohankm, could you please check the changes from #4136? If the issue is related to DRM, it has been rewritten there.
> 

Hi sure I'm checking it..

**Comment by roo12312** [comment]
> > @freeboub the issue still exists for the DRM videos on ios... videos without DRM work fine.
> 
> Hi @rohankm, could you please check the changes from #4136? If the issue is related to DRM, it has been rewritten there.

@moskalakamil  @KrzysztofMoch thank you so much for the rewrite... the videos that used to be stuck buffering on seek seem to play seamlessly now.. probably this issue is solved. I will be testing it for a day more and let you know the updates.

**Comment by moskalakamil** [comment]
Sure! Kudos to @KrzysztofMoch for rewriting it. It’s great to hear that it solved your issue!
