### ISSUE TITLE
Resize video on dynamic animated components

### ISSUE THREAD

**Issue by proProbe** [TheWidlarzGroup/react-native-video#368]
Hello!

I currently need to somehow resize a video during an animation. Im changing the videoplayers size with a Layoutanimation which makes the video stretch.

So my question is if it is possible to resize the video somehow so it fits to the new height and width of the container? Reloading the video is also a plausible solution but Im not sure how to even do this.

Should also notice that this is mainly on Android and not on IOS

**Comment by arjan** [comment]
Hi, I stumbled into this as well and fixed it (for Android), the PR is here: https://github.com/react-native-community/react-native-video/pull/432

**Comment by awitherow** [comment]
Does anyone have the iOS experience to duplicate the changes for this as well? Our application is using this package and we have this problem on iOS.

**Comment by arjan** [comment]
On iOS it should not happen. However, make sure you specify the `muted` attribute! Otherwise iOS does not follow the `resizeMode` specifier.

**Comment by DanielMSchmidt** [comment]
@arjan That worked for us in iOS, just opened a PR, because this behaviour is kind of weird and unintuitive. Thanks for your help, we really appreciate that you took the time! 👍

**Comment by arjan** [comment]
NP :) I also found this out more or less by accident.

**Comment by proProbe** [comment]
great this seems to be fixed! thanks everyone!

**Comment by hamzaouhssain1993** [comment]
I think i have a similar problem
I have this code 
`<Video

                    ref={this.attachVideoRef}
                    source={{ uri: this.mediaShowed.displayPath() }}
                    onEnd={this.handleVideoEnd}
                    paused={this.isPaused}
                    style={s.mediaViewerDefault}
                    onVideoError={$warn}
                    onError={$warn}
                    resizeMode="contain"
                />`
and 
`    mediaViewerDefault: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },`

but when I change the Url to another video, only in android the size kept is the one from the previous video so the results come with a stretched video

**Comment by Foukz** [comment]
@hamzaouhssain1993 
I've had a similar issue. Rerendering <Video /> component after data change worked for me. You can do it for instance by key property


```
<Video
     source={{
        uri: videoData.path,
     }}
     key={videoData.path}
     style={{ height: '100%', width: '100%' }}
     resizeMode="contain"
 />
```

**Comment by hamzaouhssain1993** [comment]
Yes it worked with the Key! Thank you!
