### ISSUE TITLE
[BUG]: Youtube url not wokring

### ISSUE THREAD

**Issue by raisingh22** [TheWidlarzGroup/react-native-video#3684]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Any sample url ?

**Comment by zalatechnous** [comment]
@freeboub :
Plz check below link

https://www.youtube.com/watch?v=twiUttJ47AY

**Comment by freeboub** [comment]
This is expected, this is a web page url, not a video url. Use react-native-youtube-iframe instead
https://www.npmjs.com/package/react-native-youtube-iframe
