### ISSUE TITLE
[Feature]: 网络异常处理

### ISSUE THREAD

**Issue by codeAndylau** [TheWidlarzGroup/react-native-video#3689]
### Description

当网络异常后，无法加载视频资源，视频就被暂停了。但是当网络状态被恢复后，希望能够自动播放，或者是当网络异常的时候，能够给用户提示一下，当前网络状态较差！

### Why it is needed ?

我们项目有一个场景：
 需要让客户去看一个学习视频，但是用户的使用场景大部分都是在网络较差的情况下使用我们的app，就会收到部分客诉，视频播放到快要结束了，视频被暂停了，用户啥也做不了，当网络被恢复了也会造成卡住的现象。则希望在网络恢复后自动播放，给一个良好的体验。谢谢

### Possible implementation

Technical POV how to do it

### Code sample

Code sample

**Comment by KrzysztofMoch** [comment]
Please create new one in english and detail which platform is affected
