### ISSUE TITLE
"controls" support for ios & "fullscreen" support for Android

### ISSUE THREAD

**Issue by louislai** [TheWidlarzGroup/react-native-video#369]
Right now, react-native-video supports opening a fullscreen player on ios using `presentFullScreenPlayer`, but this option is missing in android. Similarly, I can toggle a native player controls using the `controls` prop, but this only works on Android.
Would be really nice if someone can implement native controls in iOS, and fullscreen player for Android inside the react-native-video package.

I tried to hack together a fullscreen player for android by creating a new Activity with a SurfaceView to display the video output. To stop the video from reloading I store the MediaPlayer object as a singleton https://github.com/louislai/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/FullScreenVideoActivity.java
However, I hope that someone can give a more general and proper solution.

**Comment by louislai** [comment]
Added a $100 bounty for this, because I really need these features https://www.bountysource.com/issues/38797648-controls-support-for-ios-fullscreen-support-for-android

**Comment by facejiong** [comment]
https://github.com/yamill/react-native-orientation may help you

**Comment by ShariqMush** [comment]
@louislai Please check, i have finally made fullscreen work on android, check your bounty page

**Comment by treemore** [comment]
controls={true} in android can work...  i write the control code by myself.  
and add controls={true} can not see the controlbar

**Comment by ghost** [comment]
Is this bounty still up for taking?

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.
