### ISSUE TITLE
[BUG]: onSeek function not called when user seeks the video using native controls

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3691]
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

When showing the native controls, when the user seeks the video to a new location, the onSeek function is not called.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
Edit the sample app, and simply add a console log to the onSeek handler:
```

onSeek = (data: OnSeekData) => {
    this.setState({currentTime: data.currentTime});
    this.updateSeeker();
    console.log('SEEK', data);
  };
```

Then run the example, show the controls, stop the video, scroll around with the scrubber, and see no console logs.

**Comment by freeboub** [comment]
I pushed a fix for android, but I don't think this is something feasible on ios.
onSeek is managed as a callback to seek function, as the ios UI is handling the seek, I don't see any good solution to catch the seek finish event.
@KrzysztofMoch any comment ? or better idea ? I can add a note iun documentation to explain that !

**Comment by freeboub** [comment]
Reopened to add a comment in doc for ios

**Comment by eedeebee** [comment]
Assuming rnvideo is built on top of AVPlayer on iOS, could you use https://developer.apple.com/documentation/avfoundation/avplayer/1385829-addperiodictimeobserverforinterv?language=objc along with some additional state to know what the current rate is and whether this is a seek or just the player playing?  It's a typicall use case to need to know the current time of the video.   

My use case is that I need to track whether someoneo has watched 10s or more - so I need to know where the video is when they start playing so I can get this right.  I'd be ok with an API that would tell me the current time of the video whenever the rate changes from 0-> nonzero. as well; if currenttime came in the rate change data, that would work for me for example.

**Comment by eedeebee** [comment]
Here's what gpt had to say on the subject... if this is helpful: 

```objective-c
#import <AVFoundation/AVFoundation.h>
#import <UIKit/UIKit.h>

@interface ViewController : UIViewController

@property (strong, nonatomic) AVPlayer *player;
@property (strong, nonatomic) AVPlayerItem *playerItem;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Setup the player with a video URL
    NSURL *videoURL = [NSURL URLWithString:@"https://example.com/path/to/video.mp4"];
    self.playerItem = [AVPlayerItem playerItemWithURL:videoURL];
    self.player = [AVPlayer playerWithPlayerItem:self.playerItem];
    
    // Add observer for the player item
    [self.player addObserver:self 
                  forKeyPath:@"timeControlStatus" 
                     options:NSKeyValueObservingOptionNew 
                     context:nil];

    // Setup AVPlayerLayer if you need to display the video
    AVPlayerLayer *playerLayer = [AVPlayerLayer playerLayerWithPlayer:self.player];
    playerLayer.frame = self.view.bounds;
    [self.view.layer addSublayer:playerLayer];

    // Play the video
    [self.player play];
}

- (void)dealloc {
    [self.player removeObserver:self forKeyPath:@"timeControlStatus"];
}

// KVO callback
- (void)observeValueForKeyPath:(NSString *)keyPath 
                      ofObject:(id)object 
                        change:(NSDictionary<NSKeyValueChangeKey,id> *)change 
                       context:(void *)context {
    if (object == self.player && [keyPath isEqualToString:@"timeControlStatus"]) {
        if (self.player.timeControlStatus == AVPlayerTimeControlStatusPaused) {
            // Log the current time of the video after scrubbing
            CMTime currentTime = self.player.currentTime;
            float currentSeconds = CMTimeGetSeconds(currentTime);
            NSLog(@"Scrubbed to time: %f seconds", currentSeconds);
        }
    }
}

@end
```
