### ISSUE TITLE
[BUG]: Live stream on android can not get correct currentTime onProcess method

### ISSUE THREAD

**Issue by hieppd79** [TheWidlarzGroup/react-native-video#3695]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

onProgress method can not get correct currentTime on android with livestream  .m38u
but work well with .m38u (not streaming)

### Reproduction

<img width="471" alt="image" src="https://github.com/react-native-video/react-native-video/assets/161000547/90cd6b61-6892-49f6-8f7c-808f0849b4a8">

**Comment by freeboub** [comment]
That is expected your manifest should be very small (30sec I think) then the position in the stream always stays around 15sec. There is no automatic back buffer integration. 
Don't you have the same behavior on ios ?

**Comment by freeboub** [comment]
Please also see this link for more information about time management on android:  https://developer.android.com/media/media3/exoplayer/live-streaming

**Comment by hieppd79** [comment]
> That is expected your manifest should be very small (30sec I think) then the position in the stream always stays around 15sec. There is no automatic back buffer integration. Don't you have the same behavior on ios ?

No i dont have same behavior on ios, what should i do to solved this case?

**Comment by freeboub** [comment]
But sure how we can help without sample stream ...
