### ISSUE TITLE
[BUG]: Full-screen button not showing in android while using FlatGrid

### ISSUE THREAD

**Issue by Bindu009** [TheWidlarzGroup/react-native-video#3699]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I can not see the fullscreen button while the video is playing on Android, and I am also using FlatGrid to show the video.

### Environment Info
Library version: 5.2.1
Devices: Android version 13

### Reproducible sample code

```
<FlatGrid
                        itemDimension={140}
                        data={imagePreview.filter(item => (["video/mp4"].includes(item.type)))}
                        style={styles.gridView}
                        spacing={10}
                        renderItem={({ item, rowIndex }) => (
                            <TouchableOpacity key={item.uniqueId} onLongPress={() => this.selectAction(item)} disabled={!displaySelectionButton} activeOpacity={0.9}>
                                <View style={[styles.itemContainer, { backgroundColor: "grey" }]}>
                                    <Video
                                        source={{ uri: (imageBasePath + item.path), cache: "web" }}
                                        style={[styles.listImage, {
                                            opacity: item.selected && displaySelectionButton ? 0.5 : 1,
                                            borderWidth: displaySelectionButton ? .1 : 0,
                                            borderColor: item.selected && displaySelectionButton ? "grey" : null,

                                        }]}
                                        controls={true}
                                        ref={(ref) => {
                                            this.player = ref
                                        }}
                                    />

                                    {item.selected && displaySelectionButton &&
                                        <Icon
                                            name="check-circle"
                                            size={25}
                                            color={"white"}
                                            style={{ position: 'absolute', top: 15, left: 10 }}
                                            family="fontawesome"
                                        />
                                    }
                                </View>
                            </TouchableOpacity>
                        )}
                    />
```

### Image sample
![android](https://github.com/react-native-video/react-native-video/assets/167747153/c1ff829d-dcee-4bf3-b548-080a13f28f89)

### Reproduction

repository link

### Reproduction

I can not see the fullscreen button while the video is playing on Android, and I am also using FlatGrid to show the video.

**Comment by KrzysztofMoch** [comment]
There is no enough space for those controls so it seems like you will need to create custom controls to handle it

**Comment by Bindu009** [comment]
Hi @KrzysztofMoch 
Please find the screenshot below. Even though we have space, I am not getting the full-screen button.
![Screenshot_1713882825](https://github.com/react-native-video/react-native-video/assets/167747153/fdadcbcc-fc9c-4a72-adc0-d60502b26068)

**Comment by KrzysztofMoch** [comment]
@freeboub I guess we need to update/fix controls layout?

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch do you agree that we should change the position of the full-screen button? For instance, we could move it to the top-right. What do you think?

**Comment by KrzysztofMoch** [comment]
We cloud be this is not an issue - I think there is something wrong with (controls) layout - or maybe only for small views we should move it to top-right

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch, I agree with you. We must change the position of the full-screen button to the top-right on a small view screen.
I will do it in a new PR.
