### ISSUE TITLE
When video is resized, the player is animated to the new size.

### ISSUE THREAD

**Issue by nemophrost** [TheWidlarzGroup/react-native-video#37]
This is most obvious (and annoying) when shrinking the size of the video (take your demo code and say, change right: 0 -> right: 200 programmatically and you will see the right edge of the video cut off for a split seconds while it animates into the correct location.

I tried poking around in the ObjC Class for a bit, but not being a skilled native iOS dev, I didn't make any progress.

Let me know if that doesn't make sense or if I can provide more info. Thanks for a great library!

**Comment by brentvatne** [comment]
@nemophrost - interesting! I can have a look at this when I have some free time, or if anyone else would like to the help would be welcome :smile:
