### ISSUE TITLE
Crashes with 4k video on Android

### ISSUE THREAD

**Issue by kennedc** [TheWidlarzGroup/react-native-video#370]
I'm using react-native-camera to record a video, which i then preview with react-native-video. If i record the video in 4k i can only make the video a couple of seconds long otherwise react-native-video crashes.

**Comment by proProbe** [comment]
I have the same problem. Not sure how to go around it. We're currently disabling video for now

**Comment by mattapperson** [comment]
This is an Android issue, to get around this (and many android issues) we really need to move to a 3rd party video SDK under the hood such as ffmpeg)

**Comment by BangGRF** [comment]
I got the same error when using version "^6.0.0-alpha.11". Resolved in version 5.2.1
