### ISSUE TITLE
[BUG]: Unrecognized media format while HTTP live streaming (HLS | m3u8)

### ISSUE THREAD

**Issue by mukesh-simform** [TheWidlarzGroup/react-native-video#3700]
### Version

v5 (Stable)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Player is flickering and stoping streaming again and again, with following error in Android. However it's working fine in iOS.

`{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}`

**Same issue is there with v6 as well.**

### Reproduction

- Use react native video (v5 and v6) library to stream with a URL ending with .m3u8

**Comment by freeboub** [comment]
Can it be an issue with your video format/encoding ?
Can you provide a sample url?
Are you able to stream it with the sample app ?

**Comment by mukesh-simform** [comment]
@freeboub Here is a sample URL (Not the exact which I'm using, it's just for reference only). As mentioned it's working in iOS so not sure is it something related to exo player support to this HLS URL. And Yes tested in sample app as well but same issue in Android. It start streaming but then start that again and again with the mentioned error

`https://t-678.kinesisvideo.us-west-2.amazonaws.com/hls/v2/getList.m3u8?SessionToken=CiBOaiVH4k~
`

`
{"error": {"errorException": "com.google.android.exoplayer2.ExoPlaybackException: Source error", "errorString": "Unrecognized media format"}}`

**Comment by freeboub** [comment]
@mukesh-simform I cannot access to the url:

olivier@OrdinateOlivier react-native-video % ping t-678.kinesisvideo.us-west-2.amazonaws.com
ping: cannot resolve t-678.kinesisvideo.us-west-2.amazonaws.com: Unknown host

looks like domain name is not correct ...

**Comment by mukesh-simform** [comment]
@freeboub I'm attaching some error logs, I will see if I can set up one of the URLs and share that here. The earlier shared URL is not working, that was just for a reference purpose only

<img width="1171" alt="Screenshot 2024-04-23 at 11 45 50 AM" src="https://github.com/react-native-video/react-native-video/assets/56827526/fc9af081-cab9-4792-b9c9-8c98ba7cc05b">
<img width="1165" alt="Screenshot 2024-04-23 at 11 46 09 AM" src="https://github.com/react-native-video/react-native-video/assets/56827526/01ed7325-54a0-43e4-a333-b1f28730761c">
<img width="825" alt="Screenshot 2024-04-23 at 11 46 28 AM" src="https://github.com/react-native-video/react-native-video/assets/56827526/44cf208f-7e91-4c2e-ac83-395fedf54458">

**Comment by freeboub** [comment]
But, this is not the same error, here you have a 'behind live window' error. It means that you cannot read your content fast enough. Possible solution:
- increase your live buffer on server side
- double check you don't have network latency with your server: if the server is too slow to provide video chunks, the player will delay the playback and you will fall in that case.
- try to change bufferConfig to increase buffer size.

**Comment by mukesh-simform** [comment]
Yes, so we're getting `behind the live window error` with sample example in the repo, and that previously mentioned error `"Unrecognized media format"`, we're getting that with stable version v5.2.1

Let us check with your recommendation, Thank you for your prompt responses.

**Comment by freeboub** [comment]
Let's close this issue, ping me if you think it needs to be reopened !
