### ISSUE TITLE
[BUG]: Fullscreen (immersive mode) is automatically dismissed after video ends.

### ISSUE THREAD

**Issue by lou-shy** [TheWidlarzGroup/react-native-video#3703]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Fullscreen mode should not be automatically dismissed, or at least there should be an option (prop) to disable this behavior.
Currently I use repeat={true} to prevent this from happening.

References to related issues:
#2550
#2509

### Reproduction

When video ends, fullscreen (immersive mode) is dismissed and navigation bar appears.

**Comment by freeboub** [comment]
Do you use controls ?

**Comment by lou-shy** [comment]
@freeboub I'm not using controls (prop).

**Comment by mkbhdana** [comment]
i also faced this bug since long but switched to different alternate to avoid this issue

**Comment by ayushgkt** [comment]
Also facing this same issue. Activating again immersive onclose fixes it but its still glitchy to see navigation bar for sometime

**Comment by freeboub** [comment]
Hi, I found the root cause of this issue yesterday, I can also reproduce it in the sample.
Let's try to find the good fix (but not found yet).
Edit: wait I reproduce it in ios, not tested on android ...

**Comment by mkbhdana** [comment]
> Hi, I found the root cause of this issue yesterday, I can also reproduce it in the sample. Let's try to find the good fix (but not found yet). Edit: wait I reproduce it in ios, not tested on android ...

on android have  you kept repeat mode true or false

**Comment by seyedmostafahasani** [comment]
@LouShy, @ayushgkt  please update react-native-video to the latest version and test it again.

**Comment by lou-shy** [comment]
@seyedmostafahasani I tried updated version, it works fine now, without exiting after video ends.

**Comment by seyedmostafahasani** [comment]
@freeboub @KrzysztofMoch I think we can close this issue.
