### ISSUE TITLE
[BUG]: Getting Wrong Orientation In onLoad- naturalSize

### ISSUE THREAD

**Issue by sagaraanjna** [TheWidlarzGroup/react-native-video#3705]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

In onLoad naturalsize, orientation of video is wrong, showing landscape for portrait video and portrait for landscape, same with height and width of video

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: onLoad

**Comment by freeboub** [comment]
I opened a pull request to fix an issue on ios, but I don't reproduce the issue on android.
If you have the issue on android, can you provide a sample video which have the issue please ?

**Comment by sagaraanjna** [comment]
Yes in android, My videos Orientation is Portrait but getting landscape.
 expected output:  "Height" : 1280, "Width" : 720 , "Orientation": "Portrait"
![console](https://github.com/react-native-video/react-native-video/assets/132884906/0b7a8450-6011-453e-bf10-ea3bd186fc97)

@KrzysztofMoch @freeboub

**Comment by freeboub** [comment]
@sagaraanjna Can you share a sample video please ?

**Comment by sagaraanjna** [comment]
video how? like what should i record in it.

**Comment by freeboub** [comment]
I need a link to a sample video to be able to reproduce the issue. I recorded a video on my phone and integrate it in the sample and I have no issue on sample app.

**Comment by sagaraanjna** [comment]
first video is recorded in landscape mode (height, width, orientation is

https://github.com/react-native-video/react-native-video/assets/132884906/bc88ed38-7adf-4fa1-8a13-7b2131a461b3

 ok for it) but the second video is recorded in portrait mode but its showing landscape in onLoad naturalSize and Width and height is also not correct , 
expected orientation Portrait , Height : 1920, and Width : 1080,
hope you understood :)

**Comment by freeboub** [comment]
Yes I understand, but I have no idea on how to reproduce the issue without the video ...
Did you test with the basic sample in the repo ?
if you can open a branch with your sample video, it would allow me to reproduce the issue !

**Comment by sagaraanjna** [comment]
try recording a video in portrait mode and check its naturalSize -> height width and orientation

**Comment by Abdul-SS** [comment]
I'm facing the same kind of issue. If I have added the textTracks then my portrait video orientation got changed to landscape mode.

Without textTracks it works as expected. Any solution?
