### ISSUE TITLE
[BUG]: Forward or rewind setting currentTime to 0

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#3706]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

A bug happened!

in previous version when I do multiple forward or rewind quickly, progress was properly updated

but with latest version when I do multiple forward or rewind quickly, progress sets to zero position.
on single tap its fine when waited to resolve.

Also you can observe currentTime even when single tapping currentTime gets 0 and update to latest position

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

Add rewind and forward functionality to app and the quickly tap forward or rewind and then see the issue video gets to 0 position

**Comment by mkbhdana** [comment]
@freeboub @KrzysztofMoch sorry for false alarm. onSeekData I get seekTime and currentTime and i was using seekTime where value was correct but in new version seekTime has 0 value. Is seekTime not supported anymore or am I missing something

**Comment by KrzysztofMoch** [comment]
If I remember correctly we removed `seekTime` in this version as it was not used anymore
ping @freeboub

**Comment by freeboub** [comment]
@mkbhdana I don't reproduce the issue you are reporting ...
I found an issue in onLoad for live content on ios (duration is not valid, I will replace is by seekableTime). But currentTime and  seekTime are always good.
Do you use a live or a VOD content ? Are you able to reproduce it with the emulator ? can it be linked to slow network (or slow server) ?

**Comment by mkbhdana** [comment]
@freeboub issue is seekTime is getting 0 value always inside onSeekData with this new update which was not a problem in previous version now i switched to currentTime which resolved the issue. Currently I am streaming google videos via api with headers.

**Comment by freeboub** [comment]
Linked PR close, let's close this issue then
