### ISSUE TITLE
[Feature]: Ad Tag Support to show pre roll ads 

### ISSUE THREAD

**Issue by asmitha16** [TheWidlarzGroup/react-native-video#3709]
### Description

Currently it doesn't support ads and for someone working with monetization, it would greatly help to show ads on the app for shows or videos. 

### Why it is needed ?

Increase monetization & marketing.

**Comment by freeboub** [comment]
but, this is supported on V6. see https://react-native-video.github.io/react-native-video/component/props#adtagurl
