### ISSUE TITLE
Does Not Play Cloud-Hosted Video, Only Plays Local Files

### ISSUE THREAD

**Issue by quadsurf** [TheWidlarzGroup/react-native-video#371]
Issue #275 claims to solve this simply by adding http exceptions to info.plist (as seen here at [stackoverflow](http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http)), but this does not solve the issue for me.

Is there a way to play remotely-hosted mp4s on https?

Works great with local mp4s, but for mp4s securely hosted in the cloud, it's just a black blank screen, almost like there's no bridge or webview support for remotely hosted mp4s at https URIs. Please help.

Again, https://github.com/react-native-community/react-native-video/issues/275 does not solve the issue!

**Comment by gergob** [comment]
@quadsurf for me the `http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4` does play back OK on Android (cannot check iOS now).

As I can see the only difference is `https` vs `http`. I'll give it a shot with `https` and get back to you

### UPDATE:

I checked it now, and the playback does work on Android. Check how I use the player here: https://github.com/gergob/rent/blob/master/src/components/pages/Player.js

![screenshot_20161103-212238](https://cloud.githubusercontent.com/assets/1750322/19983859/040454b2-a20c-11e6-8ea0-c459bc70f5e6.png)

Have you tried to link/unlink the binaries?
I will test on iOS too

**Comment by quadsurf** [comment]
@gergob thanks a ton for looking into this... i did indeed try to link and unlink the binaries, but to no avail. An RN upgrade from  .32  to  .37  did do the trick though, although I'm still unsure why/how that solved it.
![image](https://cloud.githubusercontent.com/assets/18299175/20417580/16099504-ad0c-11e6-8892-91760119459c.png)
http://weknowmemes.com/wp-content/uploads/2012/09/my-code-doesnt-work-i-have-no-idea-why.jpg
