### ISSUE TITLE
[BUG]: Not able to see the video component in iOS version 16.0

### ISSUE THREAD

**Issue by Bindu009** [TheWidlarzGroup/react-native-video#3727]
### Version

5.2.1

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

I am trying to get the video, but I not able to get the video play using the iOS OS version 16.0
but which can play in OS version 17

### Reproduction

repository link

### Reproduction

 Not able to get the video in iOS version 16.0

**Comment by freeboub** [comment]
please try on V6, V5.2 is not supported anymore

**Comment by AlexandrBol** [comment]
@freeboub getting same issue with  version "6.0.0-rc.1"

iOS 17.2
"react-native": "0.71.7",

**Comment by freeboub** [comment]
I don't reproduce the issue with the sample app on iOS 16.0 ...
No sure on how to proceed :/
