### ISSUE TITLE
[Feature]: pause notification au audio focus lost

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3729]
### Description

`onPausedByExternalAudio = (paused) => {}` would be a prop on the VideoPlayer 

### Why it is needed ?

This would allow developers to sync external video player controls properly when external audio like youtube playing while video player was playing in the background.
Some of the work for this feature could build some work that will be reused when building media panel controls.

### Code sample

```typescript
<VideoPlayer
  onPausedByExternalAudio={(paused) => {
    updateControls(paused);
  }
/>
```

**Comment by freeboub** [comment]
@paulrinaldi I think you should use onplaybackstatechanged to be able to achieve that feature: https://react-native-video.github.io/react-native-video/component/events#onplaybackstatechanged
Can you confirm if it feats to your use case ?

**Comment by paulrinaldi** [comment]
Yes, this worked, thank you!
