### ISSUE TITLE
[Feature]: How do I trigger ads in intervals (IMA, adtagurl)

### ISSUE THREAD

**Issue by venky145** [TheWidlarzGroup/react-native-video#3731]
### Description

I would like to implement interval midrolls/ads (May be same ad should play for every five minutes)
how can we trigger? does it support VMAP?

### Why it is needed ?

Because it is cool!

### Possible implementation

I am trying to set adurl at OnProgress for every 120 sec but it is not triggering

### Code sample

Code sample

**Comment by freeboub** [comment]
You must set the adTagUrl at playback start (because you can have preRoll ads) !
I am not sure google IMA supports VMAP, I think it should be VAST url.
In the sample app you can try the adTagUrl usage. Maybe you can try with the sample ?!

**Comment by freeboub** [comment]
I think it supports VMAP, 
A lot of sample are available here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags?hl=fr

**Comment by rajgupta027** [comment]
Any updates on this?
In my case, changing "adTagUrl" on the fly is not working in android, however its working fine on IOS.
@venky145 use IMA sample tags for different use cases (pre-roll, pre-roll+mid-roll, post-roll and so on) from here.
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

Am using react native video version 6.1.2

**Comment by KrzysztofMoch** [comment]
@rajgupta027 changing "adTagUrl" on the fly is not supported on android (from what I see from code)

**Comment by YoungYanchi** [comment]
> Any updates on this? In my case, changing "adTagUrl" on the fly is not working in android, however its working fine on IOS. @venky145 use IMA sample tags for different use cases (pre-roll, pre-roll+mid-roll, post-roll and so on) from here. https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags
> 
> Am using react native video version 6.1.2

Hi, can you tell me how you achieved the swap on the fly? I have three advertising links, I'm trying to substitute them depending on the viewpoint I need, but only the first link works - pre roll. When I reach the mid-roll point, the link in the props changes, but the ads are not called. If you put the same link first on the pre-roll, it works.

@KrzysztofMoch @venky145
