### ISSUE TITLE
[BUG]: Several fullscreen-related issues

### ISSUE THREAD

**Issue by bfricka** [TheWidlarzGroup/react-native-video#3732]
### Version

6.0.0-rc.0

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

On both Android and iOS, entering fullscreen has issues. I'll try to lay them out here.

### Reproduction

**Issue 1: Entering Fullscreen Programmatically**

If you programmatically enter fullscreen on either Android and iOS, and the user dismisses fullscreen, you cannot again enter fullscreen mode programmatically.

Since the `onFullscreenPlayerDidDismiss` event is always called as expected when the user dismisses fullscreen, I hypothesized that some internal state / lifecycles were not being handled properly, and decided to add `videoRef.current?.dismissFullscreenPlayer()` in this event. This fixes the issue and allows the video to be opened in fullscreen again.

Clearly, if the user dismisses fullscreen, the video should handle its internal state and allow

**Issue 2: Cannot Enter Fullscreen on Android w/ Controls Disabled**

Android requires controls to be enabled, otherwise, it will not properly enter fullscreen. With controls enabled, entering fullscreen programmatically properly shows the video in a fullscreen with a black background. With controls disabled, the video just starts playing.

**Issue 3: Programmatically Entering Fullscreen on iOS with Controls Enabled Crashes the App**

If controls are enabled on iOS, entering fullscreen mode programmatically crashes the app. I'm doing this from a fullscreen modal, which has had issues on iOS in fullscreen mode in 5.x. However, that could be fixed by setting `transparent={false}` on the modal. Now, iOS always crashes when trying to programmatically enter fullscreen mode with controls enabled.

**Comment by seyedmostafahasani** [comment]
@bfricka please update the library to the latest version and test it with `setFullScreen` method.

**Comment by KrzysztofMoch** [comment]
No response or activity - let's close this one
