### ISSUE TITLE
[BUG]: Cannot select sideLoaded text tracks by index

### ISSUE THREAD

**Issue by freeboub** [TheWidlarzGroup/react-native-video#3736]
### Version

6.0.0-RC.0

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

Follow this change : https://github.com/react-native-video/react-native-video/pull/3728
It was discovered that sideloaded text tracks doesn't report index.
Then it is not possible to select tracks by index

### Reproduction

N/A - can be reproduced with sample

### Reproduction

set selection by index in the sample app.
Try to select a textTrack with sample content which use sideLoaded text tracks

**Comment by lucasBessaBairesDev** [comment]
If you are using VTT subtitles, yeah it bugs the player out on iOS. You should be able to still select subtitles. I'm able to anyway.

**Comment by lucasBessaBairesDev** [comment]
Check #3468 out
