### ISSUE TITLE
[BUG]: requireNativeComponent: "RCTVideo" was not found in the UIManager

### ISSUE THREAD

**Issue by ZakirBangash** [TheWidlarzGroup/react-native-video#3737]
### Version

React-native-video 6.0.0-rc.0
React Native 0.71.14

### What platforms are you having the problem on?

IOS

### Architecture

Old architecture

### What happened?

When video component start mounting, we are getting this error, folks have suggested to remove this line use_frameworks! :linkage => :static , but we don't think it would be safe to remove, as we are using firebase , and firebase recommends through it's doc to have this line

### Reproduction

Install 6.0.0-rc.0 
Run IOS, 
when video start mounting , we are getting this error

**Comment by ZakirBangash** [comment]
![Screenshot 2024-05-06 at 12 42 15 PM](https://github.com/react-native-video/react-native-video/assets/66157395/5a78c217-24c5-4d6e-93c5-9804c73982a5)

**Comment by baddda** [comment]
It seems the issue came up with this PR.
https://github.com/react-native-video/react-native-video/pull/3631

**Comment by baddda** [comment]
Removing `Podfile.lock` and running pod install shows the following error:

> Specs satisfying the \`react-native-video (from \`../node_modules/react-native-video\`)\` dependency were found, but they required a higher minimum deployment target.

Adding  `platform :ios, '13.0'` to your project Podfile, setting Minimum Deployment to 13 in Xcode and setting iOS Deployment Target to 13 fixes the issue for me.

**Comment by ZakirBangash** [comment]
Are you using firebase? if you are using you would have  this line   use_frameworks! :linkage => :static in podFile, I saw somewhere where folk suggested to remove this, but no luck with me,  can you confirm did you have this in podFile

**Comment by ZakirBangash** [comment]
Thank you @freeboub for your suggestions , I did remove flipper configuration and remove use_frameworks! :linkage => :static then I can't able to build the app, it give me error undefined symbol facebook::jsi::HostObject,

Let me share my podFile.

**Comment by ZakirBangash** [comment]
link to podFile https://drive.google.com/file/d/1aTpmD0yh57_Si9hyb-ybkkbq-crRP6R_/view?usp=drive_link

**Comment by freeboub** [comment]
> Removing `Podfile.lock` and running pod install shows the following error:
> 
> > Specs satisfying the `react-native-video (from `../node_modules/react-native-video`)` dependency were found, but they required a higher minimum deployment target.
> 
> Adding `platform :ios, '13.0'` to your project Podfile, setting Minimum Deployment to 13 in Xcode and setting iOS Deployment Target to 13 fixes the issue for me.

@baddda do you correctly remove the lines from your podfile ?
see: https://react-native-video.github.io/react-native-video/updating

**Comment by freeboub** [comment]
@ZakirBangash I will try to add firebase in the sample app.
BTW: are you able to reproduce with a very basic sample ? If yes, it would be usefull to provide it

**Comment by jeandiasl** [comment]
I also use Firebase and managed to solve the problem by adding this snippet in PODFILE to replace the minimum version for compilation.

MIN_IOS_OVERRIDE = '13.0'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
    min_ios_version_supported = MIN_IOS_OVERRIDE
end
# existing code
platform :ios, min_ios_version_supported

**Comment by ZakirBangash** [comment]
@jeandiasl thank you bro it worked for me too 🙌
cc: @freeboub

**Comment by KrzysztofMoch** [comment]
So this is not an library issue - library requires now iOS >= 13.0 (I think from RN 0.73 this is also required) so you need to bump this in your app

**Comment by vadim-snitkovsky** [comment]
> Removing `Podfile.lock` and running pod install shows the following error:
> 
> > Specs satisfying the `react-native-video (from `../node_modules/react-native-video`)` dependency were found, but they required a higher minimum deployment target.
> 
> Adding `platform :ios, '13.0'` to your project Podfile, setting Minimum Deployment to 13 in Xcode and setting iOS Deployment Target to 13 fixes the issue for me.

THANK YOU!!!!  This fixed it for us.  Let's add this to documentation.

**Comment by KrzysztofMoch** [comment]
I will add this to docs (in updating section) and maybe to README

**Comment by shahjahanpak** [comment]
`platform :ios, '13.0'` yields this list of errors with react native@0.63.3, react-native-video@6.0.0.
<img width="1170" alt="Screenshot 2024-05-21 at 5 05 53 PM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/47810605/b02f1440-e1f4-46b2-9f5c-67ca2882db36">

**Comment by freeboub** [comment]
> `platform :ios, '13.0'` yields this list of errors with react native@0.63.3, react-native-video@6.0.0.
> <img width="1170" alt="Screenshot 2024-05-21 at 5 05 53 PM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/47810605/b02f1440-e1f4-46b2-9f5c-67ca2882db36">
> 

Which xcode version do you use ?

**Comment by shahjahanpak** [comment]
14.2

**Comment by freeboub** [comment]
@shahjahanpak You need to update your xcode !

**Comment by prajwal0231** [comment]
I am facing this issue in android, not iOS

**Comment by ayushkumarbhadani** [comment]
> I am facing this issue in android, not iOS

Me too!

**Comment by prajwal0231** [comment]
> > I am facing this issue in android, not iOS
> 
> Me too!

Hey, this issue was coming because of mismatch of react-native-video version with react-native. In Expo, we cant update the required version ourselves, but in native build environment, I set the following versions and it started working smoothly.
    "react": "^18.2.0",
    "react-native": "^0.72.1",
    "react-native-video": "^5.2.1",
    "react-native-svg": "13.9.0"

**Comment by hpanwar521** [comment]
I am facing this issue in android my react native version is 0.73.5 and react-native-video version is 6.4.5 how can I solve this please help

**Comment by freeboub** [comment]
@hpanwar521 @prajwal0231 can you provide a sample reproducing the issue ?

**Comment by Ariiio** [comment]
Facing the same issue on android

**Comment by hpanwar521** [comment]
I resolved the issue related to RCTVideo not being found in UIManager. Initially, I was performing a Gradle sync, but react-native-video was not showing up in the dependencies:

<img width="324" alt="Screenshot 2024-08-30 at 8 14 39 AM" src="https://github.com/user-attachments/assets/405d5967-4ba4-4141-aca8-d6403a56e007">

I was repeatedly encountering this error. To resolve it, I closed all applications, shut down Android Studio, removed the project from recent files, and then reopened the project from scratch. This allowed the dependencies to be properly mapped, and react-native-video started appearing in the packages. After creating a fresh build, the project started working fine. The issue is now resolved.

**Comment by natemartins** [comment]
> I also use Firebase and managed to solve the problem by adding this snippet in PODFILE to replace the minimum version for compilation.
> 
> MIN_IOS_OVERRIDE = '13.0' if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported) min_ios_version_supported = MIN_IOS_OVERRIDE end
> 
> # existing code
> platform :ios, min_ios_version_supported


This works, but when you run `pod update` or `pod install`, you get this warning at the end
```
[!] Automatically assigning platform `iOS` with version `15.6` on target `Gotedo` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`
```

To fix this warning update as follows:

### Existing Code
```
MIN_IOS_OVERRIDE = '13.0'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
min_ios_version_supported = MIN_IOS_OVERRIDE
end
```

### Updated Code
```
MIN_IOS_OVERRIDE = '13.0'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
platform :ios, min_ios_version_supported = MIN_IOS_OVERRIDE
end
```
