### ISSUE TITLE
[BUG]: Video first frame do flickering when player load video and start playing, Demo Attached

### ISSUE THREAD

**Issue by ZakirBangash** [TheWidlarzGroup/react-native-video#3740]
### Version

react-native-video: ^6.0.0-rc.0

react-native: 0.71.14

Video URL: HLS m3u8

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I have a TikTok-like app where, on the home screen, when we try to scroll the video, there is a flickering issue. While this problem was not present in the previous version (v5), it has appeared now. I have recorded a demo video demonstrating this issue, and it is attached

### Reproduction

repository link

### Reproduction

Steps to reproduce this bug are:  Swipable videos like TikTok, and swiping the video, a flicker will appear. like when we swipe to video, the first frame is small having black spaces, then suddenly remove black spaces, goes to full mode

**Comment by ZakirBangash** [comment]
### **v6 with flickering issue**

https://github.com/react-native-video/react-native-video/assets/66157395/f30bf1bf-8c52-4fe4-92a6-2742fd39201d

### **v5 with smooth scroll*

https://github.com/react-native-video/react-native-video/assets/66157395/57a37e89-7f40-4c54-b5eb-33b8ba87dd51

**Comment by ZakirBangash** [comment]
@KrzysztofMoch @freeboub You guys are doing a really good job, Thank you for your contribution, the latest v6 has made our lives easier, and only a few issues currently we are facing, Let me know if you need anything else from my end 🙌

**Comment by tdammy92** [comment]
@ZakirBangash mind if we connect, working on somthing similar.

**Comment by ZakirBangash** [comment]
Yeah sure Let's connect

**Comment by MdAbubakar** [comment]
@ZakirBangash You can use the react-native-video@6.0.0-alpha.11 this solves for me.

Now I request the maintainers to fix this issue this happens when we change the video quality or change the video on the fly.
So, please fix this issue The flickering is not happening in v6.0.0-alpha.11 and I tried it in v6.0.0-beta.4 and there also the flickering happens so please do this as it's in v6.0.0-alpha.11 so this will be fixed.

Thanks in advance.

**Comment by freeboub** [comment]
In my mind (maybe I am wrong) there is no change regarding to View management between alpha.11 & next release.
Not sure where you investigated, but I think the fix shall be around shuttterView management.
I had a look, but I did find anything relevant yet ...

**Comment by freeboub** [comment]
@MdAbubakar @tdammy92 @ZakirBangash I think I have found a solution to fix this issue.
can you please test linked PR ? I tested it sucessfully with the sample, but I think this is safer to test it with a real life app !

**Comment by ZakirBangash** [comment]
> @MdAbubakar @tdammy92 @ZakirBangash I think I have found a solution to fix this issue. can you please test linked PR ? I tested it sucessfully with the sample, but I think this is safer to test it with a real life app !

Thank you @freeboub for prompt attention to this matter, I think it is part of new release, Let me see it

**Comment by ZakirBangash** [comment]
Hi @freeboub I just tried the latest release @6.0.0-rc.1, which contains this PR, this time player does not even load the video

**Comment by freeboub** [comment]
@ZakirBangash can you try to revert my last change please ?

**Comment by ZakirBangash** [comment]
@freeboub I reverted the last changes related to shuttterView management and created PR, but I have verify it, then will let you know

**Comment by ZakirBangash** [comment]
@freeboub I reverted the last changes and created PR, tested it out, and the video is loading now.

**Comment by tdammy92** [comment]
@freeboub  @ZakirBangash which version is more stable now , @6.0.0-rc.1 or v6.0.0-alpha.11 ?

**Comment by MdAbubakar** [comment]
@tdammy92 for this flickering issue the v6.0.0-alpha.11 is more stable.

**Comment by freeboub** [comment]
Notice this is a duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/3653

**Comment by freeboub** [comment]
I just push another version of the fix, can you please test it ? Thank you

**Comment by ZakirBangash** [comment]
I will test it on Monday morning, I will let you know then, as I'm away from the keyboard atm 🙏

**Comment by ZakirBangash** [comment]
Hey @freeboub I tested it, The flickering is gone, but only the first frame of the video plays,then the rest of the frames paused, and the video frame movements stopped, but the audio is still going on,  and most of the time the first frame is also not playing .  Let me share the recording

**Comment by freeboub** [comment]
Please share a sample url !

**Comment by ZakirBangash** [comment]
We are using m3u8, I will share few m3u8 urls as well 

https://github.com/TheWidlarzGroup/react-native-video/assets/66157395/ad4be56c-aa9d-46fc-96f7-4b2bb6073c63

**Comment by ZakirBangash** [comment]
**Video URL :**  https://stream.mux.com/GBhY017Qx3X3PlDyQAx201Y3kTSADrOm4nMuD00YeLV602g.m3u8
**thumbnail URL:** https://image.mux.com/GBhY017Qx3X3PlDyQAx201Y3kTSADrOm4nMuD00YeLV602g/thumbnail.webp?time=0

**Comment by freeboub** [comment]
@ZakirBangash I am too far to peint your wall to a normal color 😆 
BTW, I don't reproduce the issue with the sample ...
The video play well when switching between streams (you video included)
Can it be linked to any other props like poster ? I suppose you use it as you provided thumbnail url.
Can you please try to simplify your usage of <Video and maybe identify if another prop make the issue ?
Did you try to reproduce it with the sample included in the repo ? (the video freeze)

**Comment by ZakirBangash** [comment]
@freeboub  When I remove poster prop, it works fine then, can you guide me what should I do?

i have poster prop and directly giving thumbnail URL. wondering how could i replace poster

**Comment by freeboub** [comment]
Can you please try to apply following patch locally.
It is just a test to see if it work better.

```diff
diff --git a/src/Video.tsx b/src/Video.tsx
index 7cdbc211..aebda7ee 100644
--- a/src/Video.tsx
+++ b/src/Video.tsx
@@ -130,6 +130,7 @@ const Video = forwardRef<VideoRef, ReactVideoProps>(
           posterResizeMode && posterResizeMode !== 'none'
             ? posterResizeMode
             : 'contain',
+        opacity: 0.9,
       }),
       [posterResizeMode],
     );
```

**Comment by freeboub** [comment]
another solution can be to change (in the same file) how poster display is done.
Instead of hiding it when `onLoad` is thrown, try to move it in `onReadyForDisplay` callback

**Comment by Honggilseong** [comment]
I've encountered the same issue with the poster continuously showing. A simple solution I found is to add onReadyForDisplay to your Video component.
what i've done 
```
        <Video
          onReadyForDisplay={() => {
            console.log("onReadyForDisplay");
          }} //add
          poster={poster}
          posterResizeMode="cover"
          ignoreSilentSwitch="ignore"
        />

```

**Comment by ZakirBangash** [comment]
@freeboub Giving onReadyForDisplay callback works, we just need to give onReadyForDisplay an empty callback, and then it works. 
![carbon](https://github.com/TheWidlarzGroup/react-native-video/assets/66157395/08f671b3-b81a-4857-8f25-44ec4d3494e7)

**Comment by freeboub** [comment]
@ZakirBangash This is a very good clue to understand the issue, I was able to reproduce it with the sample now !
I just push a patch to fix it !
Notice that you can keep the onReadyForDisplay patch to continue using 6.0.0-RC.1 or 6.0.0-RC.2
In fact the poster stayed displayed, it is not the first frame of the video !

**Comment by rayhanmhd123** [comment]
> @freeboub Giving onReadyForDisplay callback works, we just need to give onReadyForDisplay an empty callback, and then it works. ![carbon](https://private-user-images.githubusercontent.com/66157395/330287225-08f671b3-b81a-4857-8f25-44ec4d3494e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODQ4MDIsIm5iZiI6MTcyMTg4NDUwMiwicGF0aCI6Ii82NjE1NzM5NS8zMzAyODcyMjUtMDhmNjcxYjMtYjgxYS00ODU3LThmMjUtNDRlYzRkMzQ5NGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA1MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZjE4YzhlNDkyZThlYmEzMGYxODVmNTRhZTQ0MDU5YzgxYzQ5ZjgxMjBkY2EzNTRkOTRlYTNjYzQ4MzBmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kBM-6wGW7qMs4qaqDwCZSCFTXoGe4V4enr3DKrCwWb0)

@ZakirBangash Can you explain the process of creating a poster using the ‘updateThumbnailWith0Frame’ method?

**Comment by venBharathManjunath** [comment]
Hi @freeboub @KrzysztofMoch 

Although this one is a closed issue, I am facing a issue similar to this when I use `selectedVideoTrack` prop and use `AUTO` options. I specially get the issue in S24 Ultra device. I am using 6.4.5 version and earlier was on 6.0.0 aplha-7 version where this works correctly. 

My manifest have this representation,
<Representation id="9" width="480" height="270" frameRate="25/1" bandwidth="499968" codecs="avc1.4D4015"/>
      <Representation id="10" width="640" height="360" frameRate="25/1" bandwidth="1499968" codecs="avc1.4D401E"/>
      <Representation id="1" width="960" height="540" frameRate="25/1" bandwidth="2499968" codecs="avc1.4D401F"/>
      <Representation id="2" width="1280" height="720" frameRate="50/1" bandwidth="4499968" codecs="avc1.640020"/>
      <Representation id="3" width="1280" height="720" frameRate="25/1" bandwidth="3499968" codecs="avc1.4D401F"/>
      <Representation id="4" width="1920" height="1080" frameRate="50/1" bandwidth="6499968" codecs="avc1.64002A"/>

Could you please let me know if I need to use or specifically set something along with `selectedVideoTrack`
