### ISSUE TITLE
onBuffer & onLoadStart not working properly

### ISSUE THREAD

**Issue by Meet-Kapadiya** [TheWidlarzGroup/react-native-video#3744]
### Version

react-native-video: 6.0.0-rc.0

### What platforms are you having the problem on?

iOS

### What happened?

In android everything working fine, But in IOS onBuffer not working & onLoadStart fired with onLoad

**Comment by KrzysztofMoch** [comment]
Hmm when I am testing it in example it's working ...
![CleanShot 2024-05-08 at 12 27 08](https://github.com/TheWidlarzGroup/react-native-video/assets/83216158/c6022703-ddd8-4ba4-9237-75b83b842469)

**Comment by Meet-Kapadiya** [comment]
I am using IOS 17

**Comment by freeboub** [comment]
> Hmm when I am testing it in example it's working ... ![CleanShot 2024-05-08 at 12 27 08](https://private-user-images.githubusercontent.com/83216158/328854040-c6022703-ddd8-4ba4-9237-75b83b842469.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzYzNTQsIm5iZiI6MTcxNTE3NjA1NCwicGF0aCI6Ii84MzIxNjE1OC8zMjg4NTQwNDAtYzYwMjI3MDMtZGRkOC00YmE0LTkyMzctNzViODNiODQyNDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEzNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MWYyYTI4OGNiYzFkNTM5MWIxZjExMjczNjQxZjRkMjU3ZjRjNTZjODc4MjYzMWNmM2JlNWJmNzU4NTAyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtYPAlDlu1leuHRrAIH4v1Lny8O34t4ij46lamE9RCQ)

there are too much onBuffer events on ios :D

**Comment by freeboub** [comment]
@Meet-Kapadiya please provide detailed informations on how to reproduce the issue. We cannot provide support with so few informations ...

**Comment by Meet-Kapadiya** [comment]
- Android - Pixel 8 Pro

https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/7ae184ad-8e2e-49d6-98cd-00266a3f3ee0

- IOS - iPhone 15 Pro Max

https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/a14fc9c6-2405-4a62-a135-94243239050f

- Code 
``` jsx
  const onLoadStart = useCallback(() => {
    setLoading(true);
  }, []);

  const onLoad = useCallback((data: OnLoadData) => {
    setLoading(false);
    setPlay(true);
    setDuration(data.duration);
    setCurrentTime(data.currentTime);
  }, []);

  const onBuffer = useCallback(({isBuffering}: OnBufferData) => {
    setLoading(isBuffering);
  }, []);

  const onSeek = useCallback((seekTime: number) => {
    videoRef.current?.seek(seekTime);
    setCurrentTime(seekTime);
  }, []);

  <Video
    ref={videoRef}
    style={styles.video}
    source={{
      uri: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    }}
    onLoadStart={onLoadStart}
    onLoad={onLoad}
    onProgress={onProgress}
    onBuffer={onBuffer}
    onEnd={onEnd}
    onError={onError}
    playInBackground={false}
    resizeMode="contain"
    paused={!play}
    rate={speed}
    selectedTextTrack={{
      type: SelectedTrackType.LANGUAGE,
      value: subtitle,
    }}
    textTracks={[
      {
        title: 'English Subtitles',
        language: 'en',
        type: TextTrackType.VTT,
        uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
      },
      {
        title: 'Spanish Subtitles',
        language: 'es',
        type: TextTrackType.SUBRIP,
        uri: 'https://durian.blender.org/wp-content/content/subtitles/sintel_es.srt',
      },
    ]}
  />
```

**Comment by freeboub** [comment]
@Meet-Kapadiya Is it the multiple onBuffer calls which gives you issues ? 
I confirm this is an issue, but with low severity.

I don't fully understand the issue here ...

**Comment by Meet-Kapadiya** [comment]
In IOS, onBuffer not fired while seek forward or backward, I want to show loader while seeking. In android you can clearly see when i move forward or backward through buttons or slider, onBuffer event is fired.

**Comment by Meet-Kapadiya** [comment]
And also in video with loading start and end, i mention time, In IOS both fired at same time.

**Comment by KrzysztofMoch** [comment]
To Summary - on iOS
- there is no buffer event on seeking 
- `onLoadStart` (Load start on your demo) and `onLoad` (Load end on your demo) is triggered in the same time (but in correct order)

Am I right ?

**Comment by Meet-Kapadiya** [comment]
Yes

**Comment by KrzysztofMoch** [comment]
So it seems that onBuffer with seeking will work only for streams (eg. HLS playlists) - try to use HLS playlists as source instead of mp4
example source `https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

**Comment by maksymhcode-care** [comment]
> So it seems that onBuffer with seeking will work only for streams (eg. HLS playlists) - try to use HLS playlists as source instead of mp4 example source `https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

Can you please tell me where can i find function that handle onBuffer on ios? trying to figure out why it keeps returning true even though the video is playing
