### ISSUE TITLE
BUG]: iOS 17.2 and 17.3 mp4 videos uploaded to Url are not playing, keeps on loading.

### ISSUE THREAD

**Issue by saagar71** [TheWidlarzGroup/react-native-video#3745]
### Version

Our app is having a requirement where user is in VOIP session and also we need to play video we are using react-native-video for this it was working fine so far only for specific version of iOS 17.2 and 17.3 its not working, it works well for 17.4 as well.
The player keeps on loading video and never plays, it does not throw any specific error as well.
Some time we see below error/warning.
'Main thread blocked by synchronous property query on not-yet-loaded property (NaturalSize) for HTTP(S) asset. This could have been a problem if this asset were being read from a slow network.'

Any suggestions/inputs will help.
Thanks

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

Sample app works well with iOS 17.3 but its when we play in our app where we have VOIP session the video does not play.
Version info:
"react-native": "0.72.12",
"react-native-video": "5.2.1",

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
I recommend you to try latest v6 as stable version should be released next week (and 5.2.1 is no longer supported)

**Comment by saagar71** [comment]
Tried latest version v6.0.0-rc.1 still observing same for iOS 17.3. Works well with iOS 17.4 quite a strange behaviour.
 Could see the below error for iOS 17.3.
```
>>>>>>>>. onReadyForDisplay
Error processing request from MAD on result: Error Domain=NSOSStatusErrorDomain Code=-128 "Request was canceled" UserInfo={NSLocalizedDescription=Request was canceled} request: <VKCImageAnalyzerRequest: 0x281459590> requestID: 47 madRequestID: 1 cancelled: YES
nw_socket_handle_socket_event [C603.1.1:1] Socket SO_ERROR 54
```

**Comment by KrzysztofMoch** [comment]
iOS development is fun they say... If I have to install all 17.x simulators to debug issue that is only on specific version my disk will die 😅

I will see what can I do

**Comment by freeboub** [comment]
@saagar71  error 54 is: ECONNRESET Connection reset by peer. A connection was forcibly closed by a peer.  This normally results from a loss of the connection on the remote socket due to a timeout or a reboot.
Are you sure this is not a server issue ?
Did you try to debug with charles proxy to see if there is an error on HTTP(S) level ?

**Comment by saagar71** [comment]
Should not be a server issue as it working in android and other iOS versions.
Will try to debug if its https level..

**Comment by faisalkhan-dianapps** [comment]
any updates on this? I am facing the same issue.
