### ISSUE TITLE
[Feature]: Cache HLS/m3u8 

### ISSUE THREAD

**Issue by Michota** [TheWidlarzGroup/react-native-video#3749]
### Description

> [Currently, caching is only supported for URLs that end in a .mp4, .m4v, or .mov extension](https://thewidlarzgroup.github.io/react-native-video/other/caching)

It would be VERY nice to have caching for m3u8 videos. It is very important for me and probably for many others too.

### Why it is needed ?

This will allow small developers (like me!) to save bandwidth and lower costs of serving videos with `m3u8` format.

**Comment by freeboub** [comment]
To be follow up in: https://github.com/TheWidlarzGroup/react-native-video/issues/3712
