### ISSUE TITLE
Full Screen Video not full screen until it loops.

### ISSUE THREAD

**Issue by awitherow** [TheWidlarzGroup/react-native-video#375]
I've got a video that I've made a fullscreen video within a container.

Our team has recently upgraded to ```"react-native": "0.37.0"``` and this bug appeared after.

jsx
```
<Video
    source={video}
    resizeMode="cover"
    repeat
    style={styles.video}
/>
```

styles
```
    container: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    video: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#000',
    },
```

What happens is the video has a small bit of what appears to be margin of about 10px or so around the left and right edges. After the video loops through once, the video does an animation as it stretches to fill the background space.

Any ideas where to start hunting for this?

**Comment by diehell** [comment]
I got this too. Any solution?

**Comment by diehell** [comment]
```
<Video
    muted
    source={video}
    resizeMode="cover"
    repeat
    style={styles.video}
/>

```

Muted works for me, im using it as a background anyways

**Comment by mkdotcom** [comment]
i don't undestand, using "muted" makes this bug to disappear? i tried but it doesn't change anything on my app

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.
