### ISSUE TITLE
[Bug]: Android Dash with fixed resolution doesn't work properly 

### ISSUE THREAD

**Issue by YangJonghun** [TheWidlarzGroup/react-native-video#3755]
### Description

fixed resolution doesn't work

### Why it is needed ?

sometimes fixed resolution needed

### Code sample

```tsx
  const [isAuto, toggleAuto] = useReducer(v => !v, false);

  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Button title={isAuto ? 'fix resolution' : 'auto'} onPress={toggleAuto} />
      <Video
        style={{width: '100%', height: 300, backgroundColor: 'black'}}
        resizeMode={ResizeMode.CONTAIN}
        source={{
          uri: 'https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd',
        }}
        selectedVideoTrack={
          isAuto
            ? {type: SelectedVideoTrackType.AUTO}
            : {
                type: SelectedVideoTrackType.RESOLUTION,
                value: 360,
              }
        }
      />
    </View>
  );
```

**Comment by YangJonghun** [comment]
nit; By the way, the bug report template is missing, is there a reason?

**Comment by freeboub** [comment]
> nit; By the way, the bug report template is missing, is there a reason?

Thank you! I just fix it !

**Comment by freeboub** [comment]
I tried to integrate it in the sample, I confirm it is not working.
I think we will be back to this old PR: https://github.com/TheWidlarzGroup/react-native-video/pull/3324/files

**Comment by YangJonghun** [comment]
This is not a problem related resolution. source was invalid. so I closed this issue
