### ISSUE TITLE
[BUG]: Problem with audioTracks & textTracks

### ISSUE THREAD

**Issue by Meet-Kapadiya** [TheWidlarzGroup/react-native-video#3765]
### Version

6.0.0-rc.0

### Architecture

Old architecture

### What happened?

1.I have one video with multiple audio & one subtitle.

- Android
    Getting only one audio & No subtitle
![Screenshot 2024-05-13 at 5 11 36 PM](https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/3d1dd255-6386-487f-a796-67c75555bab0)

- IOS
   Getting only one audio & One subtitle
![Screenshot 2024-05-13 at 5 09 10 PM](https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/af653622-cb59-4a00-aadb-63267b3a3483)

2.Unable to change audio & subtitle

- IOS
  onChange selectedTextTrack & selectedAudioTrack nothing happened

```jsx
const [audio, setAudio] = useState<string>('0');
const [subtitle, setSubtitle] = useState<string>('');

selectedTextTrack={{
    type: subtitle
      ? SelectedTrackType.INDEX
      : SelectedTrackType.DISABLED,
    value: subtitle,
}}
selectedAudioTrack={{
    type: audio ? SelectedTrackType.INDEX : SelectedTrackType.DISABLED,
    value: audio,
}}
```

**Comment by freeboub** [comment]
please share a sample video !
Or please try to reproduce on the sample app

**Comment by Meet-Kapadiya** [comment]
- Android

https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/60d045a2-9cbf-44b1-a2e0-1ab702979642

- IOS

https://github.com/TheWidlarzGroup/react-native-video/assets/83551362/e9ab6aee-96bf-412c-8fac-4803b6372678

1. In android audio track change successfully, Track1 & Disable Track, But not in IOS
2. In android i got no subtitle, But in IOS there is one (Audio - Listing Of audioTracks received onLoad,  Subtitle - Listing Of textTracks received onLoad)
3. Original video has multiple Audio & Subtitle

- Steps to reproduce

1. Pick video with multiple Audio & Subtitle
2. Check onLoad data (Here i list it)
3. Try to change Audio & Subtitle with selectedTextTrack & selectedAudioTrack (With State or Set Static)

**Comment by freeboub** [comment]
@Meet-Kapadiya I need video sample to reproduce the issue, not video of the issue ...

**Comment by Meet-Kapadiya** [comment]
https://vz-edeac798-1cc.b-cdn.net/7c667fc8-4266-4ad6-9e3d-afc561df4972/playlist.m3u8

**Comment by Meet-Kapadiya** [comment]
Also title & language received as empty or null

**Comment by freeboub** [comment]
I reproduce the issue with vlc. The video doesn't embed these informations.
you can compare the playlist information with this url to debug server side: https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by rajesh2520** [comment]
@freeboub 
My HLS videos audio not working in iOS devices, what's the cause behind this, my video url is
https://nasmstaging.blob.core.windows.net/exercise-media-streams/c43edc50-60f6-11ef-a83f-556ad75e932e/main.m3u8

it is working in browser & vlc but not in iOS platform

**Comment by freeboub** [comment]
@rajesh2520 It works on my side: RNV: 6.5.0. 

You cannot ping anyone on a ticket which have no links original issue !
Open a propers if you reproduce it on last release.

**Comment by rajesh2520** [comment]
@freeboub 
ok, i have created bug
 it's link : https://github.com/TheWidlarzGroup/react-native-video/issues/4151
