### ISSUE TITLE
Trim, Filter Video

### ISSUE THREAD

**Issue by shahen94** [TheWidlarzGroup/react-native-video#377]
Hi! I want to ask if it's possible to trim Video, or add OpenGL shaders .

Thanks!

**Comment by mantap123** [comment]
any update?
@shahen94 you create the editor for iOS?
[https://github.com/shahen94/react-native-video-processing](url)

**Comment by shahen94** [comment]
@mantap123 yes, i am

**Comment by shahen94** [comment]
https://github.com/shahen94/react-native-video-processing

**Comment by ghost** [comment]
Cool module @shahen94. Can this be closed?

**Comment by shahen94** [comment]
@jhabdas sure

**Comment by pierroo** [comment]
I'm sorry to revive such an old topic, but is it now doable from react-native-video library?
The thing with react-native-video-processing mentioned above is that it's a 103Mb package, adding an extra 50Mb to the release bundle size. :/
