### ISSUE TITLE
[BUG]: DOCS: iOS play in background documentation may be outdated now or could be rewritten

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3770]
### Version

6.0.0

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

`
## Play in background on iOS

To enable audio to play in background on iOS the audio session needs to be set to `AVAudioSessionCategoryPlayback`. See [Apple documentation][3] for additional details. (NOTE: there is now a ticket to [expose this as a prop]( https://github.com/react-native-community/react-native-video/issues/310) )
`

This may need to be updated since 310 is closed and might not exactly relate to exposing a prop for playing in the background on iOS.

### Reproduction

repository link

### Reproduction

Viewable on https://thewidlarzgroup.github.io/react-native-video/other/misc#play-in-background-on-ios

**Comment by amayanga** [comment]
My video stops playing when the device is locked on iOS. Is there something I need to change?

**Comment by paulrinaldi** [comment]
Initial issue I posted is fixed. Tested on 6.2.0 iOS 15.

**Comment by paulrinaldi** [comment]
Initial issue I posted is fixed. Tested on 6.2.0 iOS 15.

**Comment by paulrinaldi** [comment]
> My video stops playing when the device is locked on iOS. Is there something I need to change?

Yes, there is a prop, see the wiki. Likely https://thewidlarzgroup.github.io/react-native-video/component/props#playwheninactive.

**Comment by paulrinaldi** [comment]
> Initial issue I posted is fixed. Tested on 6.2.0 iOS 15.

Accidentally closed this issue, this is still an issue from what I'm seeing `playInBackground={true}` is not sufficient on 6.2.0 iPhone 13 Pro Max v15.3.
