### ISSUE TITLE
[BUG]: pod install  error

### ISSUE THREAD

**Issue by Jidahan** [TheWidlarzGroup/react-native-video#3772]
### Version

 "react-native-video": "^6.0.0",

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

A bug happened!
 "react-native-video": "^6.0.0",
 "react-native": "0.72.7",

pod install
Auto-linking React Native modules for target `greenhouse`: BVLinearGradient, RNCAsyncStorage, RNGestureHandler, RNImageCropPicker, RNKeychain, RNReanimated, RNSVG, RNScreens, react-native-ble-manager, react-native-blob-util, react-native-pdf, react-native-safe-area-context, and react-native-video
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
[Codegen] Found rncore
[!] CocoaPods could not find compatible versions for pod "react-native-video":
  In Podfile:
    react-native-video (from `../node_modules/react-native-video`)

Specs satisfying the `react-native-video (from `../node_modules/react-native-video`)` dependency were found, but they required a higher minimum deployment target.

[!] `xcodeproj` was renamed to `project`. Please update your Podfile accordingly.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: null

**Comment by freeboub** [comment]
did you correctly follow this documentation ? https://thewidlarzgroup.github.io/react-native-video/updating
did you remove `pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'` from your podfile ?

**Comment by freeboub** [comment]
Can you try also to force ios 13.0 as a minimum version in your podfile like with this patch:  https://github.com/TheWidlarzGroup/react-native-video/pull/3785/commits/e34d8fe250032f3e250475f46cd3defdcd729872

**Comment by freeboub** [comment]
or maybe bettre, you can also apply this patch: https://github.com/TheWidlarzGroup/react-native-video/issues/3737#issuecomment-2096624471

**Comment by janandaraj** [comment]
> or maybe bettre, you can also apply this patch: [#3737 (comment)](https://github.com/TheWidlarzGroup/react-native-video/issues/3737#issuecomment-2096624471)

This fixed the issue
