### ISSUE TITLE
[BUG]:  Video Player ignores the buffering config. 

### ISSUE THREAD

**Issue by Mohamed-M2M** [TheWidlarzGroup/react-native-video#3773]
### Version

5.2.1

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

The video player ignores the buffering configuration and keeps loading the video far beyond the added limits. It keeps loading too much video at once.

<Video
                    automaticallyWaitsToMinimizeStalling={false}
                    preferredForwardBufferDuration={3}
                    posterResizeMode={resizeMode} 
                    source={videoSource}
                    fullscreenAutorotate={false}
                    onProgress={handleProgress}
                    ignoreSilentSwitch='ignore'
                    onLoadStart={onLoadStart}
                    playInBackground={false}
                    poster={thumbnail} 
                    resizeMode={resizeMode}
                    style={styles.video}
                    autoPlay
                    paused={forcePause}
                    preload={isVisible} 
                    muted={forcePause}
                    onError={onError}
                    onLoad={onLoad}
                    useTextureView 
                    ref={videoRef}
                    bufferConfig={{
                      minBufferMs: 1500,
                      maxBufferMs: 3000,
                      bufferForPlaybackMs: 1500,
                      bufferForPlaybackAfterRebufferMs: 1500
                    }}
                    repeat
                    maxBitRate={1000000}
                  />

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Is it reproduced on 6.0.0 ?

**Comment by Mohamed-M2M** [comment]
> Is it reproduced on 6.0.0 ?

nope, Not yet reproduced on 6.0.0.

**Comment by abbasmoosavi** [comment]
@Mohamed-M2M Buffer config only for android

**Comment by freeboub** [comment]
There is another feature request for ios.
Android works fine on 6.0.0, I think we can close this issue
