### ISSUE TITLE
[iOS] App crash when rendering <Video/> component

### ISSUE THREAD

**Issue by breadadams** [TheWidlarzGroup/react-native-video#378]
Tested this in the example and getting the same result there as in my app, react-native `0.37.0`, react-native-video `0.9.0`. App crashes when trying to load a local file as the source.

```
2016-11-14 22:32:56.362 VideoPlayer[36810:5128476] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010588334b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010439a21e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001058ec265 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000103e8d4c1 -[NSURL(NSURL) initFileURLWithPath:] + 131
	4   VideoPlayer                         0x0000000103b7b620 -[RCTVideo playerItemForSource:] + 624
	5   VideoPlayer                         0x0000000103b7abd5 -[RCTVideo setSrc:] + 117
	6   VideoPlayer                         0x0000000103b21908 __49-[RCTComponentData propBlockForKey:inDictionary:]_block_invoke.227 + 328
	7   VideoPlayer                         0x0000000103b22250 __49-[RCTComponentData propBlockForKey:inDictionary:]_block_invoke.259 + 720
	8   VideoPlayer                         0x0000000103b225c8 __49-[RCTComponentData propBlockForKey:inDictionary:]_block_invoke_2.272 + 40
	9   VideoPlayer                         0x0000000103ababd6 RCTPerformBlockWithLogFunction + 374
	10  VideoPlayer                         0x0000000103abad1d RCTPerformBlockWithLogPrefix + 221
	11  VideoPlayer                         0x0000000103b2252d __49-[RCTComponentData propBlockForKey:inDictionary:]_block_invoke.267 + 445
	12  VideoPlayer                         0x0000000103b22a25 __37-[RCTComponentData setProps:forView:]_block_invoke + 181
	13  CoreFoundation                      0x000000010580a9d6 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	14  CoreFoundation                      0x000000010580a8da -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 202
	15  VideoPlayer                         0x0000000103b2288f -[RCTComponentData setProps:forView:] + 223
	16  VideoPlayer                         0x0000000103b0aab2 __50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke + 162
	17  libdispatch.dylib                   0x0000000109850980 _dispatch_call_block_and_release + 12
	18  libdispatch.dylib                   0x000000010987a0cd _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010985a8d6 _dispatch_main_queue_callback_4CF + 406
	20  CoreFoundation                      0x00000001058474f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	21  CoreFoundation                      0x000000010580cf8d __CFRunLoopRun + 2205
	22  CoreFoundation                      0x000000010580c494 CFRunLoopRunSpecific + 420
	23  GraphicsServices                    0x000000010b172a6f GSEventRunModal + 161
	24  UIKit                               0x0000000107eef964 UIApplicationMain + 159
	25  VideoPlayer                         0x0000000103a2a8cf main + 111
	26  libdyld.dylib                       0x00000001098c668d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

![image](https://cloud.githubusercontent.com/assets/5795227/20283860/08223ba6-aabb-11e6-9fdc-d12d32b3aa9a.png)

**Comment by prananta** [comment]
Seems like the path to the video is `nil`. Which example did you try? I tried the one in `example` directory and it worked.

**Comment by blumanski** [comment]
I experience the same, it works fine in android but on ios the app crashes.

```
2016-11-17 15:25:08.883958 timekap[463:75776] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x17400a510 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1702258e0> (
<NSKeyValueObservance 0x17424c5d0: Observer: 0x100d3ee90, Key path: status, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170252c90>
<NSKeyValueObservance 0x174246900: Observer: 0x100d3ee90, Key path: playbackBufferEmpty, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x17424aec0>
<NSKeyValueObservance 0x1742501a0: Observer: 0x100d3ee90, Key path: playbackLikelyToKeepUp, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x174250290>
)'
*** First throw call stack:
(0x18e2941c0 0x18cccc55c 0x18e294108 0x18ece1df4 0x19595207c 0x18d172a28 0x1009f521c 0x1009fa284 0x18e241f2c 0x18e23fb18 0x18e16e048 0x18fbf1198 0x194148628 0x194143360 0x1000fba90 0x18d1505b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Code i use...
It finds the path, I have tested it, if I change it, it comes up with an error message, file not found.
So, this is not a path problem.

Phone I use is iphone 6
Thanks

```
<Video
     repeat
     resizeMode='cover'
     source={require('../../../assets/video/20161117_151639.mp4')}
     style={styles.backgroundVideo}
 />
```

**Comment by tasarsu** [comment]
Same things happen here. How can we solve this issue

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x1702296a0 of class AVPlayerLayer was deallocated while key value observers were still registered with it.

**Comment by breadadams** [comment]
Just gave this another go now and strange enough, it works fine.

I was using an external url, went ahead and swapped it for `require('path to video')`, and saw my video playing fine.

Try relaunching Xcode / react package manager / simulator after adding the video file to your project. Those are the only things I can think I've *done* since opening the issue that would affect this.

**Comment by tasarsu** [comment]
But I have to load remote video files. And dont know how to solve this issue. 

Video was played at my first try after installing this package. Then gave errors. It doesnt even build from command line now.

**Comment by tasarsu** [comment]
Does this commit https://github.com/react-native-community/react-native-video/commit/b15594e90a9ceebbc74c1aaad943080c67cc3720 solve this issue?

**Comment by nanandn** [comment]
I have the same problem. Will this be fixed soon?

**Comment by scarmuega** [comment]
From what I experience, the same type of exception (observers not correctly removed before deallocation) is appearing in two different cases:

A) for observers of the AVPlayerItem class
B) for observers of the AVPlayerLayer class

For case A, I tried manually applying the changes from the commit mentioned by @tasarsu and it did work. Seems that the code from the current npm package version is prior to that commit.

For case B, setting `controls={true}` in the props of the `<Video />` element seems to avoid rendering the AVPlayerLayer entirely, so the exception never appears.

Just my two cents on the matter.

**Comment by jaggerwang** [comment]
I've the same problem because I unmounted the Video which loaded the local uri, in order to prepare for uploading.

**Comment by liskiew** [comment]
v0.9.0 
@scarmuega and @tasarsu For the AVPlayerLayer observers you should unregister observers just before reinitializing new one:

      **[_playerLayer removeObserver:self forKeyPath:readyForDisplayKeyPath];**
      _playerLayer = [AVPlayerLayer playerLayerWithPlayer:_player];

**Comment by zachrnolan** [comment]
@scarmuega The controls prop did the trick, but I'm now seeing a Quicktime logo flash at the end of the video (on iOS). Do you know how to prevent this?

**Comment by scarmuega** [comment]
@zachrnolan sorry, I haven't seen that behavior and I'm not really an expert on the library. I think you should open a new issue specific for that problem. Good luck!

**Comment by zachrnolan** [comment]
@scarmuega no worries, I created a new issue here in case anyone else has the same problem: #647

**Comment by teameh** [comment]
@tasarsu commented on 23 Nov 2016
> Does this commit b15594e solve this issue?

It seems like this problem is still (or again) present in 4.3.1. There seems to be a lot changed in the codebase since b15594e. Maybe someone with more in depth knowledge of the project then me should check all the listeners again. 

Not sure if this is any help, but here are our crash logs:

While debugging: 

	2019-01-10 17:25:55.950206+0100 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<RCTVideo: 0x10c293e10; frame = (0 0; 984 615); clipsToBounds = YES; alpha = 0; layer = <CALayer: 0x17842cd80>>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
	Key path: playbackBufferEmpty
	Observed object: <AVPlayerItem: 0x17800b080, asset = <AVURLAsset: 0x178429c80, URL = file:///var/mobile/Containers/Data/Application/28E7A37A-6EB9-4FB4-A3AD-E30716BB9752/Library/Caches/3ae9f779664619454a98eee942b97ffc7bb83ab3.mp4>>
	Change: {
	    kind = 1;
	}
	Context: 0x0'
	*** First throw call stack:
	(0x1901e2fd8 0x18ec44538 0x1901e2f20 0x190c9d3a0 0x109005030 0x190be7cb8 0x190be77e0 0x190bd2740 0x197b8be58 0x197ba1eb8 0x109c4da50 0x109c4da10 0x109c52b78 0x1901910c0 0x19018ecdc 0x1900bed94 0x191b28074 0x196370130 0x1000271f8 0x18f0cd59c)
	libc++abi.dylib: terminating with uncaught exception of type NSException
	(lldb) 

Production app: 

	Last Exception Backtrace:
	0   CoreFoundation                	0x1901e2fd8 __exceptionPreprocess + 124
	1   libobjc.A.dylib               	0x18ec44538 objc_exception_throw + 55
	2   CoreFoundation                	0x1901e2f20 +[NSException raise:format:] + 115
	3   Foundation                    	0x190c9d3a0 -[NSObject+ 856992 (NSKeyValueObserving) observeValueForKeyPath:ofObject:change:context:] + 163
	4   Volkskrant-Acc                	0x1003c2d7c 0x1000c8000 + 3124604
	5   Foundation                    	0x190be7cb8 NSKeyValueNotifyObserver + 303
	6   Foundation                    	0x190be77e0 NSKeyValueDidChange + 403
	7   Foundation                    	0x190bd2740 -[NSObject+ 26432 (NSKeyValueObserverNotification) didChangeValueForKey:] + 119
	8   AVFoundation                  	0x197b8be58 -[AVPlayerItem didChangeValueForKey:] + 55
	9   AVFoundation                  	0x197ba1eb8 __avplayeritem_fpItemNotificationCallback_block_invoke + 2567
	10  libdispatch.dylib             	0x18f09a9e0 _dispatch_call_block_and_release + 23
	11  libdispatch.dylib             	0x18f09a9a0 _dispatch_client_callout + 15
	12  libdispatch.dylib             	0x18f09f5e8 _dispatch_main_queue_callback_4CF + 995
	13  CoreFoundation                	0x1901910c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 11
	14  CoreFoundation                	0x19018ecdc __CFRunLoopRun + 1571
	15  CoreFoundation                	0x1900bed94 CFRunLoopRunSpecific + 423
	16  GraphicsServices              	0x191b28074 GSEventRunModal + 99
	17  UIKit                         	0x196370130 UIApplicationMain + 207
	18  Volkskrant-Acc                	0x1000d2150 0x1000c8000 + 41296
	19  libdyld.dylib                 	0x18f0cd59c start + 3

**Comment by wmonecke** [comment]
I fixed this by just implementing it like so (LOCAL VIDEO): 
```
<Video
  source={require('../assets/videos/loginBackgroundVideo.mp4')}
  ref={ref => this.player = ref}                                 
  style={styles.backgroundVideo}
/>
```
**Dont** implement source={{ uri: require('../assets/videos/loginBackgroundVideo.mp4') }}

**Comment by teameh** [comment]
Why would this fix the issue? 

I can't use that, since my url is a dynamic url, downloaded at runtime and stored on disk in the caches folder.. trying to bundle something like this won't work: `source={require(uri)}`. It isn't allowed by the bundler.

**Comment by wmonecke** [comment]
@teameh Yes I forgot to mention the video is already locally available. My bad.

**Comment by laurent22** [comment]
I also had this crash when accidentally loading an empty source `{uri:undefined}` in the player. In that case it would just crash with no useful error. I think the code should check when setting the source if it's undefined and throw a proper error at that time instead of crashing the app later on.

**Comment by iagormoraes** [comment]
I got a crash on emulator 6.0 with CPU x64, but when there is no style, the crash doesn't happen, but no video play also.

**Comment by Skobraf** [comment]
same error, no solution found

**Comment by hansen-simon** [comment]
I got the error when I was switching the source uri property with the following logic:
```
loadAd().then(ad => setAdVideoUrl(ad.videoUrl)

<Video
  source={uri: adVideoUrl | defaultPlaceholderVideoUrl}
...
</Video>
```

replacing the whole video element instead just the uri fixed the error for me. 

The comment from tasursu with error log and the change event within helped me to identify that problem.

> @tasarsu commented on 23 Nov 2016
> ...
> Observed object: <AVPlayerItem: 0x17800b080, asset = <AVURLAsset: 0x178429c80, URL = file:///var/mobile/Containers/Data/Application/28E7A37A-6EB9-4FB4-A3AD-E30716BB9752/Library/Caches/3ae9f779664619454a98eee942b97ffc7bb83ab3.mp4>>
> Change: {
>     kind = 1;
> }
> ...
