### ISSUE TITLE
[BUG]: Audio not playing for some HLS playlists with separated audio and video .ts files, Other HLS media players play audio without issue (using expo).

### ISSUE THREAD

**Issue by m0x02** [TheWidlarzGroup/react-native-video#3788]
### Version

6.0.0

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old Architecture

### What happened?

When passing HLS .m3u8 paths to the Video player, playlists with combined video and audio segments play fine and have sound, while videos that have separated video and audio do not play any sound. 

Here is an example hls path that has this issue:
[https://stacked.b-cdn.net/prod-output/video_clw8yv4b4000001l5xo5fd7vd/2fd5551a-73c8-45f8-a6d4-0329f8c3dbab.m3u8](https://stacked.b-cdn.net/prod-output/video_clw8yv4b4000001l5xo5fd7vd/2fd5551a-73c8-45f8-a6d4-0329f8c3dbab.m3u8)

When I pass this path to VLC media player or into an online HLS player like the one at [https://livepush.io/hls-player/index.html](https://livepush.io/hls-player/index.html) the video has audio as expected, but does not have audio in an expo project that uses the Video component provided. 

Here is the Video component that is passed the hls paths:

```
<Video
  ref={videoRef}
  source={
    videoSourceUrl
      ? {
          uri: videoSourceUrl,
          startPosition: video?.startTime
            ? video.startTime * 1000
            : 0,
        }
      : null
  }
  resizeMode={"contain"}
  posterResizeMode={"contain"}
  poster={`${String(
    Constants?.expoConfig?.extra?.expoPublicBunnyStorageHostname,
  )}/prod_output/${video?.id}/first-frame.jpg`}
  onError={(e) => console.log("error", e)}
  muted={false}
  style={{ flex: 1 }}
  maxBitRate={2000000} // 2 megabits
  paused={!isPlaying}
  rate={playbackRate}
  onLoad={onLoad}
  onProgress={onProgress}
  progressUpdateIntervalMillis={250}
  repeat={!isLong}
  ignoreSilentSwitch={"ignore"}
  useTextureView={false}
  bufferConfig={{
    cacheSizeMB: 50,
  }}
  bufferingStrategy={"DependingOnMemory"}
  selectedAudioTrack={{
    type: "index",
    value: 0,
  }}
/>
```

The  onload function that does the following:
```
    const onLoad = (event) => {
      setDuration(event?.duration || 0);
      if (event?.naturalSize?.width && event?.naturalSize?.height) {
        const videoRatio =
          event?.naturalSize?.width / event?.naturalSize?.height;
        setIsLong(videoRatio > 1);
        setVideoRatio(videoRatio);
        setVideoRatioHook && setVideoRatioHook(videoRatio);
      }
      console.log("AUDIO TRACKS: ", event.audioTracks);
    }
```
    
The audio tracks appear to be fetched correctly and look like this (as returned by the console.log):
`[{"index": 0, "language": "", "selected": false, "title": "audio_6"}, {"index": 1, "language": "", "selected": true, "title": "audio_7"}]`

Also note that this issue persists if I do not set selectedAudioTrack and if I wait for onLoad to finish before setting selectedAudioTrack, and that videos that do not have seperated audio play sound with this same implemetation. 

### Reproduction

Pass this HLS source: [https://stacked.b-cdn.net/prod-output/video_clw8yv4b4000001l5xo5fd7vd/2fd5551a-73c8-45f8-a6d4-0329f8c3dbab.m3u8](https://stacked.b-cdn.net/prod-output/video_clw8yv4b4000001l5xo5fd7vd/2fd5551a-73c8-45f8-a6d4-0329f8c3dbab.m3u8) to a minimal react native environment that uses the Video component provided by this library and you should be unable to get audio to play.

**Comment by freeboub** [comment]
Can you try this patch please ?

During testing the error was: FORMAT_EXCEEDS_CAPABILITIES It was causing issue during tracks selection.

```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index 5392a9ae..dda02e0b 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -1937,6 +1937,9 @@ public class ReactExoplayerView extends FrameLayout implements
 
         DefaultTrackSelector.Parameters selectionParameters = trackSelector.getParameters()
                 .buildUpon()
+                .setExceedAudioConstraintsIfNecessary(true)
+                .setExceedRendererCapabilitiesIfNecessary(true)
+                .setExceedVideoConstraintsIfNecessary(true)
                 .setRendererDisabled(rendererIndex, false)
                 .clearOverridesOfType(selectionOverride.getType())
                 .addOverride(selectionOverride)
```

**Comment by m0x02** [comment]
Thank you, working through trying this now. Having a few issues but I think they may just be expo related and will update if this works. Is there a similar patch that should be applied for iOS devices?

**Comment by freeboub** [comment]
I didn't test ios, good point ...
BTW, I don't think this is expo related

**Comment by m0x02** [comment]
Ah yes you are right, was able to get it working on android with this patch, let me know if there is something similar that can be done on iOS and will close this issue, thank you again for your help.

**Comment by m0x02** [comment]
Have been trying to apply a similar patch to fix iOS and was looking in the track selection logic in /ios/Video/RCTVideo.swift but have been unable to make much progress, are there similar flags that can be applied in this case?

**Comment by freeboub** [comment]
I reopen as it fixes only android part. I am stuck to investigate ios issue. I suspect something linked to the audio stream, but it needs more investigations.

**Comment by m0x02** [comment]
I managed to fix the issue by modifying the HLS manifest such that the `AUDIO` field of each video track is equal to a `GROUP-ID` of an audio track. So for example here is a manifest that does not play audio on iOS: 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",LANGUAGE="en",CODECS="mp4a.40.2",NAME="audio_6",DEFAULT=NO,URI="variant_audio_en_96000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",LANGUAGE="en",CODECS="mp4a.40.2",NAME="audio_7",DEFAULT=NO,URI="variant_audio_en_168000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",LANGUAGE="en",CODECS="mp4a.40.2",NAME="audio_8",DEFAULT=YES,URI="variant_audio_en_197397.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles-en",NAME="subtitle_0",DEFAULT=YES,URI="variant_0_vtt.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=760320,CODECS="avc1.4d401e",RESOLUTION=640x360,SUBTITLES="subtitles-en"
variant_video_en_360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1351152,CODECS="avc1.4d401e",RESOLUTION=854x480,SUBTITLES="subtitles-en"
variant_video_en_480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=3041280,CODECS="avc1.4d401f",RESOLUTION=1280x720,SUBTITLES="subtitles-en"
variant_video_en_720.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=6842880,CODECS="avc1.4d4028",RESOLUTION=1920x1080,SUBTITLES="subtitles-en"
variant_video_en_1080.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=12165120,CODECS="avc1.4d4032",RESOLUTION=2560x1440,SUBTITLES="subtitles-en"
variant_video_en_1440.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=27371520,CODECS="avc1.4d4033",RESOLUTION=3840x2160,SUBTITLES="subtitles-en"
variant_video_en_2160.m3u8
```

And here is a modified one that does play audio on iOS:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",NAME="audio_6",DEFAULT=NO,URI="variant_audio_en_96000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",NAME="audio_7",DEFAULT=NO,URI="variant_audio_en_168000.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="group_audio-en",NAME="audio_8",DEFAULT=YES,URI="variant_audio_en_197397.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles-en",NAME="subtitle_0",DEFAULT=YES,URI="variant_0_vtt.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=760320,CODECS="avc1.4d401e",AUDIO="group_audio-en",RESOLUTION=640x360,SUBTITLES="subtitles-en"
variant_video_en_360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1351152,CODECS="avc1.4d401e",AUDIO="group_audio-en",RESOLUTION=854x480,SUBTITLES="subtitles-en"
variant_video_en_480.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=3041280,CODECS="avc1.4d401f",AUDIO="group_audio-en",RESOLUTION=1280x720,SUBTITLES="subtitles-en"
variant_video_en_720.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=6842880,CODECS="avc1.4d4028",AUDIO="group_audio-en",RESOLUTION=1920x1080,SUBTITLES="subtitles-en"
variant_video_en_1080.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=12165120,CODECS="avc1.4d4032",AUDIO="group_audio-en",RESOLUTION=2560x1440,SUBTITLES="subtitles-en"
variant_video_en_1440.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=27371520,CODECS="avc1.4d4033",AUDIO="group_audio-en",RESOLUTION=3840x2160,SUBTITLES="subtitles-en"
variant_video_en_2160.m3u8
```

I believe this works because of a quirk with AVplayer's handling of split audio tracks with HLS but would have to investigate more to find the specific root. In any case, it would be helpful for this to be patched such that iOS can find the audio without requiring this change to have more parity with other HLS players such as VLC, and having to explicitly set the audio group can interfere with organizing by language.

**Comment by freeboub** [comment]
Thank you for the update, I think the next step would be report the issue to apple...
So let's close the ticket

**Comment by Strate** [comment]
Just encountered to same problem.
For me pasing this prop to Video component helps:

```
selectedAudioTrack={{
  type: "system",
}}
```

omitting selectedAudioTrack forces to play video without sound
