### ISSUE TITLE
how to load video from android_asset

### ISSUE THREAD

**Issue by lee11qian** [TheWidlarzGroup/react-native-video#379]
react-native-cli: 1.0.0
react-native: 0.36.0
react-native-video: 0.9.0

i want to use like this:

`<Video source={{uri: 'file:///android_asset/source/64.mp3'}} .../>`

but logcat tell me:

`Failed to open file '/android_asset/source/64.mp3'. (No such file or directory)`

I guarantee that the file exists.

Can't it be used in this way.

I hope someone tell me how to do.

**Comment by prananta** [comment]
I might be wrong, but according to this [SO](http://stackoverflow.com/a/6036529)

```
MediaPlayer expects an URI and it's impossible to create an URI for an assets file
```

Seems like you need to use `AssetManager` to get file descriptor to the video file and set it as datasource for MediaPlayer. But if you look at the file `ReactVideoView.java`, it doesn't support it.

So _maybe_ not possible to load from android_asset. You could however just use React Native asset system as mentioned in the Readme.

Or pull request? 😄

**Comment by lee11qian** [comment]
Thank you for tell me this. But my project must use file from android_asset. So i change the file `ReactVideoView.java` like this:

```
if (uriString.startsWith("content://")) {
    Uri parsedUrl = Uri.parse(uriString);
    setDataSource(mThemedReactContext, parsedUrl);
} else if (uriString.startsWith("file:///android_asset")) {    // <----- add begin
    AssetFileDescriptor afd = getResources().getAssets().openFd(uriString.replace("file:///android_asset/", ""));
    mMediaPlayer.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
    mEventEmitter.receiveEvent(getId(), Events.EVENT_LOAD_START.toString(), null);
    prepareAsync(this);
    return;                    // <----- add end
} else {
    setDataSource(uriString);
}
```

Is it any errors? I just use it in my project now.

**Comment by afilp** [comment]
Does this still work? Can this be a PR and merged? 
I also need to use `uri: 'file:///android_asset/` because the videos are large and the `code-push` would delay a lot.

How can we do this now? In 2020?
