### ISSUE TITLE
[BUG]: Doc: onSeek Link in seek method dcoumenation doesn't work

### ISSUE THREAD

**Issue by freeboub** [TheWidlarzGroup/react-native-video#3795]
### Version

6.0.0

### Architecture

Old architecture

### What happened?

onSeek Link in seek method documenation doesn't work here: https://thewidlarzgroup.github.io/react-native-video/component/methods#seek

### Reproduction

repository link

### Reproduction

just click on onSeek link

**Comment by seyedmostafahasani** [comment]
@freeboub we can close this issue after merging this [PR](https://github.com/TheWidlarzGroup/react-native-video/pull/3796)
