### ISSUE TITLE
Video cannot be played when updating react-native-video version 6x

### ISSUE THREAD

**Issue by chienvuvan99** [TheWidlarzGroup/react-native-video#3797]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### What happened?

Hello everyone, I am encountering a problem after updating React Native Video from version 5.2 to 6. Here’s the issue:

I have a Screen A that contains a list of videos for users to select and post. Selecting a username will navigate to Screen B, which contains a list of posts by that user. Screen C is the detailed post with an accompanying video. The problem I’m facing is that I can’t play the video on Screen C. Could you please let me know the reason and how to fix it? Thank you.

### react native 
0.72.5

**Comment by freeboub** [comment]
I don't see any easy reason for this issue. Did you check the logcat ?

**Comment by paulrinaldi** [comment]
If using expo, delete your android build and rebuild it. Can also try removing node_modules and reinstalling packages.

**Comment by chienvuvan99** [comment]
> I don't see any easy reason for this issue. Did you check the logcat ?
![Screenshot 2024-05-21 at 14 07 05](https://github.com/TheWidlarzGroup/react-native-video/assets/63105978/8f1c53d2-5dbb-4768-9c83-8ffe8eccb6b5)

I have checked the logcat but couldn’t find any errors or issues. I am using react-navigation v6.

**Comment by chienvuvan99** [comment]
https://github.com/TheWidlarzGroup/react-native-video/assets/63105978/f1cde0f4-2567-4956-b965-f796acf6dd07
here is the video

**Comment by freeboub** [comment]
It looks like react native video doesn't receive source prop...
Are you able to reproduce on a small sample and share it ?

**Comment by chienvuvan99** [comment]
The source prop has a value but it can’t play the video. I’ve tried hardcoding the source but it still can’t play. However, if I use navigation.replace, the video plays normally. This is the URI of a video and the code. 
https://video.fireant.vn/d18efa81-cdae-4b02-96c8-9dc7eeb85789/-ufoko_nSf

<Video
            id={data.postID.toString()}
            ref={refVideo}
            style={{height: '100%', width: '100%'}}
            resizeMode="contain"
            source={{
              uri: data.videoUrl
            }}
            poster={data.videoThumbnailUrl}
            bufferConfig={{
              minBufferMs: 500,
              maxBufferMs: 1000,
              bufferForPlaybackMs: 500,
              bufferForPlaybackAfterRebufferMs: 500,
              backBufferDurationMs: 5000,
              cacheSizeMB: 0
            }}
            // bufferingStrategy="DEPENDING_ON_MEMORY"
            paused={pausedVideo}
            posterResizeMode="contain"
            ignoreSilentSwitch="ignore"
            useTextureView={false}
            playInBackground={false}
            playWhenInactive={true}
            onLoad={onLoad}
            repeat={true}
            disableDisconnectError={true}
            preferredForwardBufferDuration={500}
            onEnd={onEnd}
            onLoadStart={onLoadStart}
            onError={e => console.log('ERROR', e)}
          />

**Comment by freeboub** [comment]
Just try to play with:
```JS
    {
      uri: 'https://video.fireant.vn/d18efa81-cdae-4b02-96c8-9dc7eeb85789/-ufoko_nSf',
      type: 'mp4',
    },
```
It works fine in sample ...
