### ISSUE TITLE
Dependency on audio input device

### ISSUE THREAD

**Issue by d-vine** [TheWidlarzGroup/react-native-video#38]
Hi Brent.

Videos don't work, if the device your are running the iOS simulator on doesn't have a mic (e.g. Mac mini)
When I plugged in a Webcam (and recompiled) it worked. There still is a warning (137: Error '!dat' trying to set the (null) audio devices' sample rate), but no errors.

I'm not sure if you can do anything about this, since it's probably an error within a library, but I thought I raise it here. Other projects seem to have the same issues (http://stackoverflow.com/questions/17318706/avaudioplayer-error-using-ios-simulator)

Thanks for the great work.

Cheers
Georg

**Comment by brentvatne** [comment]
Hi @dvine-multimedia - as you mentioned, I don't think that this is something we can fix, it looks like it's an underlying issue with AVPlayer :( Looks like you found a workaround though! :smile:
