### ISSUE TITLE
[BUG]: Flickering when changing another video

### ISSUE THREAD

**Issue by quangtuan28200** [TheWidlarzGroup/react-native-video#3800]
### Version

6.0.0

### What platforms are you having the problem on?

Android, IOS

### Architecture

Old architecture

### What happened?

The video is flickering when I change another video, it seems that when I switch to another video, it will get the last frame of the previous video but the image is not scaled to resizeMode. 

here is my code:
```
<Video
  source={video}
  resizeMode='contain'
  style={{ width: '100%', height: 200, backgroundColor: '#ccc' }}
  onReadyForDisplay={() => {}}
  useTextureView={true}
  hideShutterView={true}
/>
```

https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/ef01df3d-15ea-4be9-8b8b-2f8d2e53bfe8

### Reproduction

repository link

### Reproduction

In the video above, when I click "prev", the source is a URI video, when I click "next", the source is null, I leave null to clearly see the problem, if it is 1 video you will see the flickering problem

**Comment by freeboub** [comment]
Why do you use hideShutterView ? I think this is the issue here !

**Comment by quangtuan28200** [comment]
oh sorry, my fault, just use `shutterColor="white"`

**Comment by quangtuan28200** [comment]
The problem seems to be better, but users still see flickering when changing videos
With `v5` I don't use `android-exoplayer`, the above problem doesn't happen

```
<Video
  source={video}
  resizeMode='contain'
  style={{ width: '100%', height: 200, backgroundColor: '#fff' }}
  onReadyForDisplay={() => {}}
  useTextureView={true}
  shutterColor='#fff'
/>
```

https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/c1b7ecf9-444a-43e0-8583-0c4f1d798b2a

**Comment by freeboub** [comment]
I am not sure of what you try to achieve... You have small videos and you want no interruptions between the Videos ? Why not building only 1 video server side ?

**Comment by quangtuan28200** [comment]
My app is a workout app, it includes different combos, i want to separate it because i want to combine it together in a custom way, this problem doesn't happen when using v5 and don't use android-exoplayer. Do you have any solution for it?

**Comment by freeboub** [comment]
🤔 If I were you I would try to preload the second video in a second <Video component. and then swap videos when the first one reach the end.

**Comment by freeboub** [comment]
Wait, I am just reviewing the original video.
If you put back hideShutterView={true} and use master branch, I think the resize issue is already fixed !

**Comment by quangtuan28200** [comment]
oh thank u, let me see

**Comment by quangtuan28200** [comment]
It seems to work fine, now it looks smooth, however I checked with IOS it looks like lastframe image is not used, I looked at another ticket https://github.com/TheWidlarzGroup/react-native-video/issues/1801 and he suggested adding the background image manually, but it doesn't seem like a good idea

**Comment by freeboub** [comment]
You should try to implement it with 2 <Video views as I proposed.
I think your need is to define a playlist in fact ...
