### ISSUE TITLE
[BUG]: "muted" Prop Not Working Consistently on Component Mount

### ISSUE THREAD

**Issue by shahjahanpak** [TheWidlarzGroup/react-native-video#3803]
### Version

5.2.1

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

I'm using the react-native-video library in my project, and I'm having an issue with the muted prop. When the video component mounts, the audio is supposed to be muted. However, intermittently, the sound plays for a brief moment (less than a second) before muting. Sometimes the sound doesn't play at all as expected.

Output of `npx react-native info`
```
System:
    OS: macOS 12.7.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 2.58 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
    Python: 2.7.18 - /Users/mac/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: This is a basic Video component trying to play a local video file which is by default playing _(paused = true)_ & muted _(muted = true)_ using states.

**Comment by freeboub** [comment]
Is this something reproduced on V6.0.0 ?

**Comment by shahjahanpak** [comment]
Upgrading to `v6.0.0` results in this exception 
![IMG_0098](https://github.com/TheWidlarzGroup/react-native-video/assets/47810605/b9f3a72d-ccbc-45e4-8709-940a42a5c7cc)

**Comment by freeboub** [comment]
did you follow this doc https://thewidlarzgroup.github.io/react-native-video/updating and clean your ios build ?

**Comment by freeboub** [comment]
I don't reproduce the issue with the sample app. I will close the issue, It must be retested with V6, let me know if I need to reopen the issue.
