### ISSUE TITLE
[BUG]: playback stop when changing selectedVideoTrack value 'resolution'

### ISSUE THREAD

**Issue by anasvemmully** [TheWidlarzGroup/react-native-video#3804]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I'm receiving the following problem while attempting to switch between resolutions of _**DRM protected Video**_ and `selectedVideoTrack` types `resolution` and `index` as well. Without the `selectedVideoTrack` props, everything works perfectly; it's not causing an issue for every device, only certain of them; for me, the device I'm receiving the error for  

**Device Information:**
 - Device: `OPPO Reno 2f`
 - Android Version: `11`
 - adb shell getprop ro.product.model: `CPH1989`
 - adb shell getprop ro.product.manufacturer: `OPPO`
 - adb shell getprop ro.build.version.release: `11`
 - adb shell getprop ro.build.display.id: `CPH1989_11_F.24`

**Expected Behavior:**
The track resolution of the video should need to be changed.

**Actual Behaviour**
The app crashes or phone freezes/restarts after changing the `value` for `selectedVideoTrack`.

NB:- _without `selectedVideoTrack` works fine but why when using/changing `value` of `selectedVideoTrack` freezes_

### Reproduction

https://github.com/anasvemmully/rnvideotest

### Reproduction

The app crashes or phone freezes/restarts after changing the `value` for `selectedVideoTrack`.

Caught through LogCat
```
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer
error, index=1, format=Format(15, null, null, audio/mp4a-latm, mp4a.40.2, 69168, en, [-1, -1, -1.0, null], [1, 24000]), format_supported=YES
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loop(Looper.java:227)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
      at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
      at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
      at
androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:151)
      at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1396)
      at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
      at android.os.Handler.dispatchMessage(Handler.java:103) 
      at android.os.Looper.loop(Looper.java:227) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
```

The following error caught from `onError` 
```javascript
{
    "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, 389802, null, [512, 288, 24.0, ColorInfo(Unset color space, Limited range, Unset color transfer, false)], [-1, -1]), format_supported=YES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:264)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: android.media.MediaCodec$CryptoException: Crypto key not available\n\tat android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)\n\tat android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)\n\tat androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:151)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1396)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 3 more\n",
    "errorCode": "26006",
    "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, 389802, null, [512, 288, 24.0, ColorInfo(Unset color space, Limited range, Unset color transfer, false)], [-1, -1]), format_supported=YES",
    "errorString": "ExoPlaybackException: ERROR_CODE_DRM_SYSTEM_ERROR"
}
```

### **video of the stated issue**
[without selectedVideoTrack prop Mp4](https://github.com/TheWidlarzGroup/react-native-video/assets/69687301/6262c82f-76d7-4633-9513-c94418186a16)
[with selectedVideoTrack prop Mp4](https://github.com/TheWidlarzGroup/react-native-video/assets/69687301/e563edfd-cfd3-405f-858f-64737433d5a6)

**Comment by freeboub** [comment]
I tried to use the sample, I don't have the exact same issue...
Only P1 doesn't work (on emulator). It fails with NO_EXCEEDS_CAPABILITIES which is fixed by: https://github.com/TheWidlarzGroup/react-native-video/pull/3791
But I don't reproduce the DRM error. 

Notice also that following PR: https://github.com/TheWidlarzGroup/react-native-video/pull/3778 can improve the behavior but not sure ...

**Comment by anasvemmully** [comment]
It's working for most of the devices but only a smal fraction of devices are getting this problem, don't know why

This is the video of the device having the issue with the selectedVideoTrack prop

https://github.com/TheWidlarzGroup/react-native-video/assets/69687301/e563edfd-cfd3-405f-858f-64737433d5a6

And this is the video of the same device without having the selectedVideoTrack prop

https://github.com/TheWidlarzGroup/react-native-video/assets/69687301/6262c82f-76d7-4633-9513-c94418186a16

What information should I need to provide to inspect?

**Comment by freeboub** [comment]
You should try to reproduce the issue with the exoplayer/media3 sample! It looks like a device issue. I will close it for now. Ping me if you have info. BTW it would be interesting to retest with the next release (6.1.0)

**Comment by anasvemmully** [comment]
ok, sure
