### ISSUE TITLE
[BUG]: on some video the headers are ignored 

### ISSUE THREAD

**Issue by kiashan** [TheWidlarzGroup/react-native-video#3805]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

if i set header "Referer",but i think if i set a simple header in general the player ignore it. I check previous version and on beta 5 seem to be ok.
It' happen with mp4 video streaming and not with m3u

### Reproduction

it' hard to reproduce cause i've created an url resolver for server like doodstream

**Comment by freeboub** [comment]
Too much "I think" in the ticket... You should record a network trace with Charles proxy to identify if headers are not removed.
I close the ticket for now

**Comment by kiashan** [comment]
OK, tested with charles proxy.
the player makes two calls when it starts, the first in HEAD, I guess to understand the file type, and the next in GET.
the HEAD request has all the headers I enter, even if they are with lower case keys.
The GET request has none of my headers inserted.
In beta version 5 the HEAD request has the lower case headers as in version 6 but has all the headers spelled correctly in the GET request.

I hope I have been helpful

**Comment by freeboub** [comment]
@kiashan Thank you for the feedback, That's clear now !

**Comment by kiashan** [comment]
UPDATE:
the problem is related to cache management.
if I set the cacheSizeMB value to 0 the headers are sent.
it apperar after this #3739

**Comment by freeboub** [comment]
Thank you for the update,
I can point you some potential issue from code review I did:

- getDefaultHttpDataSourceFactory and getDefaultDataSourceFactory will not be refreshed once initialized
I think it make sens to remove the initial test;

in other word, applying this patch:
```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java b/android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java
index 5a037896..83268e24 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/DataSourceUtil.java
@@ -44,16 +44,12 @@ public class DataSourceUtil {
     }
 
     public static DataSource.Factory getDefaultDataSourceFactory(ReactContext context, DefaultBandwidthMeter bandwidthMeter, Map<String, String> requestHeaders) {
-        if (defaultDataSourceFactory == null || (requestHeaders != null && !requestHeaders.isEmpty())) {
-            defaultDataSourceFactory = buildDataSourceFactory(context, bandwidthMeter, requestHeaders);
-        }
+        defaultDataSourceFactory = buildDataSourceFactory(context, bandwidthMeter, requestHeaders);
         return defaultDataSourceFactory;
     }
 
     public static HttpDataSource.Factory getDefaultHttpDataSourceFactory(ReactContext context, DefaultBandwidthMeter bandwidthMeter, Map<String, String> requestHeaders) {
-        if (defaultHttpDataSourceFactory == null || (requestHeaders != null && !requestHeaders.isEmpty())) {
-            defaultHttpDataSourceFactory = buildHttpDataSourceFactory(context, bandwidthMeter, requestHeaders);
-        }
+        defaultHttpDataSourceFactory = buildHttpDataSourceFactory(context, bandwidthMeter, requestHeaders);
         return defaultHttpDataSourceFactory;
     }
```

- notice that defaultHttpDataSourceFactory and defaultDataSourceFactory are static variable, so only one version can be used, so there is a big issue if you want to playback 2 DRM streams in parralel... ping @coofzilla 

- The allocation with cache is done in  `RNVSimpleCache.INSTANCE.setSimpleCache(` call . ping @lovegaoshi

**Comment by lovegaoshi** [comment]
thanks for the catch! no wonder my app doesnt work as intended and ive been just ignoring it. pr submitted

**Comment by freeboub** [comment]
@kiashan I think you can the test the PR from @lovegaoshi ! Thank you !
