### ISSUE TITLE
[BUG]: Android left rewind notification moves playback forward instead of backwards (on sample project and using npm)

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3806]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Open the example/basic app.

Start playing video, click rewind on notif control, observe forward progress on video.

### Reproduction

https://github.com/TheWidlarzGroup/react-native-video/tree/master/examples/basic

### Reproduction

Step to reproduce this bug are: 
`showNotificationControls={true}`
1. Open your app
2. Play a video
3. Drag down the notifications
4. Tap the Rewind button

Actual:
5. Observe the progress bar moving forward

Expected:
5. Observe the progress bar moving backward

**Comment by freeboub** [comment]
fix will be included in 6.1.0
