### ISSUE TITLE
[BUG]: Tapping notification does not foreground the app on Android

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3811]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Similar to Spotify on Android or RNV on iOS, I expected tapping the notification for a RNV video to foreground the app. But it does not. Not sure if this is not built yet or not working.

### Reproduction

Step to reproduce this bug are: 
1. Open app in Android
2. Play a video
3. Slide down the notification dialog
4. Tap the notification dialog

Actual:
5. Nothing occurs

Expected:
5. Observe the App foregrounds

**Comment by paulrinaldi** [comment]
This may be helpful, https://developer.android.com/reference/kotlin/androidx/core/app/NotificationCompat.Builder#setContentIntent(android.app.PendingIntent), I'll start taking a look at where to call this and with which arguments.

**Comment by freeboub** [comment]
@paulrinaldi I think you should use this API:
https://developer.android.com/reference/android/media/session/MediaSession#setSessionActivity(android.app.PendingIntent)

**Comment by paulrinaldi** [comment]
<img width="905" alt="Screenshot 2024-05-22 at 11 34 56 AM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/107127397/a6f5742c-3a2f-4a31-a364-287bcc0fa8fe">
This documentation makes me think otherwise but I'll try it out. 

I am currently determining where in the code to make a change, likely within one or more of: `VideoPlaybackCallback.kt`, `VideoPlaybackService.kt`, and `ReactExoplayerView.java`

**Comment by freeboub** [comment]
linked Pr merged, will be available in 6.1.3
