### ISSUE TITLE
[BUG]: Video Playback stops background music on android

### ISSUE THREAD

**Issue by marcor-a** [TheWidlarzGroup/react-native-video#3812]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

After updating the library from 5.2.1 to 6.0.0 playing music in the background (e.g. Spotify) stops when a video is played via react native video. I also tried the following properties: mixWithOthers, ignoreSilentSwitch, muted and selectedAudioTrack. Nothing seems to have an effect. On iOS it works as expected. The video plays and the background music does not stop and continues playing.

### Reproduction

Step to reproduce this bug are: Embed a video with props:
ignoreSilentSwitch={'ignore'}
mixWithOthers={'mix'}
Build the app for android. Start some audio on android (e.g. spotify)
Open the app.
The music should not stop playing and the video should play.

**Comment by freeboub** [comment]
Did you try [disableFocus](https://thewidlarzgroup.github.io/react-native-video/component/props#disablefocus) ?

**Comment by freeboub** [comment]
To have a good and coherent behavior we would need to add a new prop
I can propose following api:

##  audioFocusStrategy

This property configure how to handle audio focus. 
Available values:

|---|---| 
| normal | will handle audio focus in a standard way. Take audio focus during playback and release it on pause or stop. on audio duck (another app take temporary audio focus) volume will be divided by 2 to be lower |
| never | will never request audio focus |

It allows more flexibility for the future.

We can also thing to following configuration:

| duckMute | normal, but mute volume when intermediate audio comes |

**Comment by marcor-a** [comment]
Thanks a lot. disableFocus worked for me.
