### ISSUE TITLE
[BUG] need to change package.json version for 6.1.0

### ISSUE THREAD

**Issue by YangJonghun** [TheWidlarzGroup/react-native-video#3815]
### Version

6.1.0

### Architecture

Old architecture

### What happened?

need to change package.json version for 6.1.0
(Podfile.lock doesn't change)

### Reproduction

repository link

### Reproduction

.

**Comment by freeboub** [comment]
@YangJonghun Not sure to understand, what is needed ? an issue with package build ? (I confirm we had issues)
Do you download it from npm ?

**Comment by YangJonghun** [comment]
@freeboub 
below code need to update. this code affects the `react-native-video.podspec`
https://github.com/TheWidlarzGroup/react-native-video/blob/v6.1.0/package.json#L3

**Comment by freeboub** [comment]
@KrzysztofMoch can you please create a new release 🙏

**Comment by KrzysztofMoch** [comment]
Sure, I will make 6.1.1

**Comment by KrzysztofMoch** [comment]
Should be fixed now (with 6.1.1)

**Comment by freeboub** [comment]
Ok, let's close now ... thank you @KrzysztofMoch
