### ISSUE TITLE
[BUG]:  Poster image not showing with audioOnly prop in version 6.0.0

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3816]
### Version

6.0.0

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

In previous versions, setting the audioOnly prop to true while playing a video displayed the poster image. In version 6.0.0, the screen goes black, and only the audio plays without showing the poster image.

Environment:
React Native Video Version: 6.0.0
React Version: 17.0.2
React Native: 0.68.2
Device: (e.g., Samsung Galaxy A73)
OS: (Android 14)

Expected Behavior:
The poster image should display while the audio plays.

Actual Behavior:
The screen is black while the audio plays, and the poster image is not visible.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
Open the app.
Play a video with the audioOnly prop set to true.

**Comment by freeboub** [comment]
I confirm this feature has been removed in 6.0.0. The best would be that you reimplement this poster management on app side.

**Comment by amitkumarcoding** [comment]
I can manage this by adding the `<Image />` tag
