### ISSUE TITLE
[BUG]: onLoad method sometimes return wrong naturalSize and I can not get correct height and width of video (IOS only)

### ISSUE THREAD

**Issue by yuriiburov** [TheWidlarzGroup/react-native-video#3817]
### Version

6.1.0

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

`"react-native": "0.72.6",`
`"react-native-video": "6.1.0"`

the link has reverted height and width
[https://bn-dev.fra1.digitaloceanspaces.com/km-tournament/uploads/rn_image_picker_lib_temp_2ee86a27_9312_4548_84af_7fd75d9ad4dd_ad8b20587a.mp4](https://bn-dev.fra1.digitaloceanspaces.com/km-tournament/uploads/rn_image_picker_lib_temp_2ee86a27_9312_4548_84af_7fd75d9ad4dd_ad8b20587a.mp4)

the size should be: `width: 720, height: 1280`
but method `onLoad` return
`{"audioTracks": [], "canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 3.899977684020996, "naturalSize": {"height": 720, "orientation": "landscape", "width": 1280}, "target": 1313, "textTracks": []}`
where in `"naturalSize": {"height": 720, "orientation": "landscape", "width": 1280}` width and height are reverted and orientation is wrong.

### Reproduction

;)

**Comment by freeboub** [comment]
Please check with open pull request, thank you for providing a sample video !

**Comment by yuriiburov** [comment]
it works on `6.1.0`
