### ISSUE TITLE
[Android] Audio can be heard, but video is not seen

### ISSUE THREAD

**Issue by ghprud** [TheWidlarzGroup/react-native-video#382]
I am using RN 0.36 with react-native-video. In a test app I created, I can hear the audio, but can't see the video. Has anyone seen this issue on Android devices?

Thanks

**Comment by glitch003** [comment]
+1 I'm also having this issue on Android 7.1.1, Google Pixel, RN 0.39, trying to play an MP4 from a URI that works on iOS.

**Comment by glitch003** [comment]
I was able to fix this by setting a style on the <Video> view and making sure the element can be seen.  I used   fullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },

**Comment by cobarx** [comment]
Closing this since it's old and a fix has been suggested. It sounds like you need to provide a style. If you're still having issues, please provide more info and reopen.
