### ISSUE TITLE
[BUG]: Issue with volume control

### ISSUE THREAD

**Issue by Mohamed-Ziyad** [TheWidlarzGroup/react-native-video#3823]
### Version

6.1.1

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Video playing but sound os not coming, Im using RN 0.73.4

### Reproduction

repository link

### Reproduction

 <Video
          ref={videoref}
          controls={false}
          source={bunny}
          paused={play === 'pause'}
          resizeMode={'cover'}
          volume={volume}
          muted={false}
          ignoreSilentSwitch={'ignore'}
          onEnd={() => {
            setPlay('repeat');
          }}
          onLoad={({duration}) => {
            _currentTime.value = 0;
            _duration.value = duration;
          }}
          onProgress={handleProgress}
          style={{
            width: '100%',
            height: 220,
            zIndex: 10,
          }}
          onBuffer={i => {}}
       
        />

**Comment by freeboub** [comment]
can you add some reproduction steps, I don't understand the issue

**Comment by Mohamed-Ziyad** [comment]
Hi, Sorry for that. I'm using RN 0.73.6 and RNVideo 6.1.1,  this is my video component
<Video
ref={videoref}
controls={false}
source={bunny}
paused={play === 'pause'}
resizeMode={'cover'}
volume={volume}
muted={false}
ignoreSilentSwitch={'ignore'}
onEnd={() => {
setPlay('repeat');
}}
onLoad={({duration}) => {
_currentTime.value = 0;
_duration.value = duration;
}}
onProgress={handleProgress}
style={{
width: '100%',
height: 220,
zIndex: 10,
}}
onBuffer={i => {}}

    />

volume = 25, 50, 100.

the video file playing with sound in ios, but in android the video playing but the sound not available, I tried with logcat but I couldn't able to find the issue.

**Comment by freeboub** [comment]
25, 50, 100 are out of range... please read the doc... it should be between 0 & 1.0
BTW, I don't reproduce the issue with the sample.
Any clue to reproduce the issue ?

**Comment by Mohamed-Ziyad** [comment]
Okay I'll check it in the docs, but it's works fine in ios, "Any clue to reproduce the issue ?"  I don't know whats reproduce means this will not happen again sorry and Thanks.

**Comment by Mohamed-Ziyad** [comment]
I hope it work

**Comment by freeboub** [comment]
Sorry to be so direct, I just need a way to reproduce the issue. I don't see it in the sample, so I cannot investigate anything 🤷
