### ISSUE TITLE
[BUG]: compilation issue: use -source 16 or higher to enable pattern matching in instanceof

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3825]
### Version

6.1.1

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Getting this error while run on android

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/userName/Documents/projectName/node_modules/react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:1689: error: pattern matching in instanceof is not supported in -source 11
            } else if (entry instanceof EventMessage eventMessage) {
                                                     ^
  (use -source 16 or higher to enable pattern matching in instanceof)
```

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

open the terminal
run android

**Comment by freeboub** [comment]
I changed this line few days ago ...
Can you try to add something like this in your gradle file please ? ()

```gradle
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
```
Or maybe update your java version ?

**Comment by amitkumarcoding** [comment]
@freeboub 

still getting the same error after adding above lines.
I also tried upgrading the Java version, but nothing happened; the issue still exists.

only in version 6.0.1 and 6.1.1  have this issue
in previous version 6.0.0 thing are working fine

**Comment by freeboub** [comment]
@amitmehtacode I just push a fix, if you want to test it before next release

**Comment by amitkumarcoding** [comment]
@freeboub Just check it is woking now🚀🚀🚀
Thank you so much for quick fix

**Comment by saitejavankayala** [comment]
@freeboub I am facing same issue, can you please release this fix 

> @amitmehtacode I just push a fix, if you want to test it before next release

Can you please release this fix, i am also facing same error

**Comment by freeboub** [comment]
@KrzysztofMoch can I build a release ? 😁

**Comment by KrzysztofMoch** [comment]
Sure 👌

**Comment by freeboub** [comment]
It is release in 6.1.2 !
