### ISSUE TITLE
[BUG]: Audio is not sync with video when adjusting the video rate.

### ISSUE THREAD

**Issue by sherbiiny** [TheWidlarzGroup/react-native-video#3826]
### Version

6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

I'm trying to implement a simple custom speed menu to change the rate of the video, but when i change the rate the audio is missing the video and they are not synchronous.

Specifically audio is ahead of the video.

I think it's worth noting that i'm rendering the video from the cloud not the device itself.

### Reproduction

Here is my video player component: 

```tsx
const Player = () => {
  const [rateModalVisible, setRateModalVisible] = useState(false);
  const [rate, setRate] = useState(1);
  
  ....
  
  return (
    <View style={styles.container}>
      <Video
        style={styles.video}
        controls={true}
        source={{uri: videoSrc}}
        resizeMode="contain"
        rate={rate}
      />
      <Button
        title="Speed"
        style={styles.speed}
        onPress={() => setRateModalVisible(true)}
      />
      <SelectRateModal
        isVisible={rateModalVisible}
        dismissRateModal={() => setRateModalVisible(false)}
        videoRate={rate}
        onChangeVideoRate={setRate}
      />
    </View>
  );
};
```

SelectRateModal is just a simple modal to choose the speed.

**Comment by freeboub** [comment]
did you try on a real device or only emulator ?
Can yo reproduce it with the sample ?
which speed value do yo set ?
Honestly, we just provide the value to player, we don't control this behavior... my next proposal would be to test with a sample exoplayer if yo also have the issue...

**Comment by sherbiiny** [comment]
I've tried on my phone and it seems to be working fine.

Thank you.
