### ISSUE TITLE
[BUG]:  Missing title

### ISSUE THREAD

**Issue by samadRopstam** [TheWidlarzGroup/react-native-video#3827]
### Version

6.1.1

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

i am installing the library for the first time and when i run pod install i get the following error (react-native - 0.74.0)

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-video` depends upon `RCT-Folly`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

### Reproduction

repository link

### Reproduction

- react-native - 0.74.0 
- yarn install react-native-video
- pod instll

**Comment by freeboub** [comment]
I am sorry, but I don't understand the issue ...
Maybe I am wrong, but RCT-Folly is used only with newArch.

**Comment by phazei** [comment]
I have the exact same issue on react-native 0.73
