### ISSUE TITLE
[BUG]: onLoad return the Video dimension and orientaion reversed

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [TheWidlarzGroup/react-native-video#3833]
### Version

6.0.0

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

i have a issue when select a video on iPhone then use video uri for display the video on RNVideo.
The UI working good, video able to play.

But and onLoad function return wrong naturalSize. width & heigh & orientation were reversed. 

for example. i use react-native-image-crop-picker to pick a portrait video WxH = 1080x1920 (the right number)
but the onLoad returned naturalSize =  {width: 1920, heigh: 1080, orientation: "landscape"} (the reversed number)

MyCode:
 ```
   const response = await ImageCropPicker.openPicker({
      mediaType: 'video',
    });
    
    console.log('Response', response.height, response.width); 
    // height 1920, width 1080 -> portrait

    setState({source: { uri: response.path }})

    {
      state.source.uri && 
      <VideoPlayer 
        source={{ uri: state.source.uri }}
        onLoad={(data: OnLoadData) => {
          console.log('Orientation', data.natureSize); 
          // {"height": 1080, "orientation": "landscape", "width": 1920}
          // wrong here
        }}
      />
    }
```

i tried to debug somewhere in native code and see the right dimension of video `_playerItem.presentationSize` instead of `videoTrack.naturalSize`

![image](https://github.com/TheWidlarzGroup/react-native-video/assets/30792140/67db9037-4f8f-429f-8249-f99c8bda5ae6)

### Reproduction

repository link

### Reproduction

"react-native": "0.68.7"
"react-native-video": "^6.0.0"
Testing on real device iPhone12 iOS 17.4.1

**Comment by freeboub** [comment]
This is already fixed on 6.1.2 ! Let me know if I should reopen the issue
