### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by mezalejandro** [TheWidlarzGroup/react-native-video#3834]
### Version

^6.1.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

On firebase i get this fatal error, in some devices on Android:
<img width="1120" alt="Screenshot 2024-05-24 at 7 23 18 AM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/568141/1be67428-0214-4858-9a46-c57b6890282d">

I think it's by the notification controls

**Comment by freeboub** [comment]
I also think this issue is linked to notification controls issue.
Maybe this is linked to specific device ? Do you have some sample device where the issue happens ?

**Comment by mezalejandro** [comment]
In firebase show this:

Device: Samsung Galaxy A70
Android:  11
---------------------
Device: Samung A03s
Android: 13

**Comment by lovegaoshi** [comment]
RNTP has seen this error. i thought the solution was to initialize a second channel but it doesnt seem so? anyways, the referred PR:
https://github.com/doublesymmetry/react-native-track-player/pull/1974
https://github.com/doublesymmetry/react-native-track-player/issues/1666#issuecomment-1481534212

**Comment by freeboub** [comment]
It would be interesting to test this patch:
when system is overloaded (or slow) it would make sens to start the service outside of UI thread !

```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index d9d5e2be..9165ff33 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -888,8 +888,7 @@ public class ReactExoplayerView extends FrameLayout implements
 
         Intent intent = new Intent(themedReactContext, VideoPlaybackService.class);
         intent.setAction(MediaSessionService.SERVICE_INTERFACE);
-
-        themedReactContext.startService(intent);
+        new Handler().post(() -> themedReactContext.startService(intent));
 
         int flags;
         if (Build.VERSION.SDK_INT >= 29) {
```

**Comment by mezalejandro** [comment]
Hello,
I removed the showNotificationControls prop but the mistake persists.

**Comment by arsensgitacc** [comment]
I got crashes after adding `showNotificationControls={true}`, using 6.2.0
Not sure yet, but might be OS specific
<img width="563" alt="image" src="https://github.com/TheWidlarzGroup/react-native-video/assets/13656275/2090ffb9-7f5b-4cdf-96c5-2c4bfee2daca">

**Comment by arsensgitacc** [comment]
I found this 

> You have to call startForeground() within 10 seconds of receiving onStartCommand() after starting your service using startForegroundService(), otherwise, the app will crash with the following exception: android.app.ForegroundServiceDidNotStartInTimeException: 
  Context.startForegroundService() did not then call Service.startForeground()

What are analogs of these functions in the lib?

**Comment by ashwanihundwani1986** [comment]
@freeboub Any solutions for this I am still facing this crash on Samsung devices. Android Versions 14,13, & 12

**Comment by ashwanihundwani1986** [comment]
@freeboub How about checking the version and using the latest API? Here is the reference:
https://medium.com/@domen.lanisnik/guide-to-foreground-services-on-android-9d0127dc8f9a
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    themedReactContext.startForegroundService(intent);
} else {
    themedReactContext.startService(intent);
}

**Comment by arsensgitacc** [comment]
@freeboub we have tried this solution
`new Handler().post(() -> themedReactContext.startService(intent));`
It doesn't help with crash.
