### ISSUE TITLE
[BUG]: borderRadius for video not working when resizeMode="cover"

### ISSUE THREAD

**Issue by JieMin27** [TheWidlarzGroup/react-native-video#3847]
### Version

6.1.1

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

`<Video
              source={{
                uri: item.filePath,
              }}
              style={{
                flex: 1,
                aspectRatio: 1,
                borderRadius: 10,
                backgroundColor: 'gray',
                width: "100%",
                height: "100%",
              }}
              controls={false}
              paused={true}
              resizeMode="cover"
            />`

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
To be followed in https://github.com/TheWidlarzGroup/react-native-video/issues/2194
