### ISSUE TITLE
[BUG]: How to use wistia link in react native video?

### ISSUE THREAD

**Issue by yuvrajchaudhari03** [TheWidlarzGroup/react-native-video#3852]
### Version

6.1.2

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

https://alcatrazz-627.wistia.com/medias/42nh9qefdc

how do use this Wistia link in React native video?
will it work if I pass the source?

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
pass above link in source

**Comment by freeboub** [comment]
https://googlethatforyou.com?q=How%20to%20use%20wistia%20link%20in%20react%20native%20app%3F
Seriously, I think you need to integrate this API to retrieve video url https://docs.wistia.com/reference/get_medias
