### ISSUE TITLE
[BUG] Videos Stuttering on Low-Spec Android Devices

### ISSUE THREAD

**Issue by enricsa** [TheWidlarzGroup/react-native-video#3853]
### Version

>= 6.0.0

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

After updating to version 6.0.0, we noticed that the videos started stuttering/glitching. Upon investigation, it appears the issue is related to the Media 3 ExoPlayer update.

Reproducible on the following devices:

Samsung Galaxy Tab A7 Lite with Android 11
Amazon Fire HD 8 (10th generation) with FireOS 7.3.2.9

### Reproduction

Open the app with v5.2.1.
Play a video (it works well).
Update to any version above v6.0.0.
Play a video (it lags).

**Comment by freeboub** [comment]
I reviewed media3 documentation few days ago, and I found following point: https://developer.android.com/media/media3/exoplayer/customization?hl=en#enabling-asynchronous-buffer-queueing
Can you try on your side to enable forceEnableMediaCodecAsynchronousQueueing usage ? 
It may fix your issue... If you want I can create a PR to enable this flag !

**Comment by freeboub** [comment]
@enricsa I open following PR for easier testing: https://github.com/TheWidlarzGroup/react-native-video/pull/3860/files

**Comment by freeboub** [comment]
proposed fix will be integareted in 6.2.0

**Comment by skantus** [comment]
Hey @freeboub, I have been doing several tests on low-specs Android devices, especially on Amazon Fire (HD8) and the issue persists, the video keeps stopping every time, so the fix doesn't seem to work, is there any other potential fix?

**Comment by skantus** [comment]
> proposed fix will be integareted in 6.2.0

Hey @freeboub, I have been testing in low-specs devices, especially Amazon Fire, and it seems the fix is working as expected, Do you have a plan to release the 6.2.0 soon?

**Comment by freeboub** [comment]
@skantus Good news! Yes I have a mandatory PR to merge and I plan to create a new release !
