### ISSUE TITLE
[BUG]: showNotificationControls is visible on iOS even when it is set to false

### ISSUE THREAD

**Issue by MTPL0005-AbhishekDube** [TheWidlarzGroup/react-native-video#3856]
### Version

6.0.0 & 6.1.2

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

`<Video
          bufferConfig={{
            minBufferMs: 15000,
            maxBufferMs: 50000,
            bufferForPlaybackMs: 2500,
            bufferForPlaybackAfterRebufferMs: 5000,
            cacheSizeMB: 0,
          }}
          fullscreen={fullscreen}
          muted={muted}
          onAspectRatio={this.onAspectRatio}
          onAudioTracks={this.onAudioTracks}
          onBuffer={this.onBuffer}
          onEnd={this.onEnd}
          onLoad={this.onLoad}
          onLoadStart={this.onVideoLoadStart}
          onProgress={this.onProgress}
          onReceiveAdEvent={this._onReceiveAdEvent}
          onTextTracks={this.onTextTracks}
          paused={paused}
          playInBackground={false}
          playWhenInactive={false}
          poster={courseImage}
          posterResizeMode="cover"
          preventsDisplaySleepDuringVideoPlayback={true}
          rate={rate}
          ref={(ref) => {
            this.videoPlayerRef = ref;
          }}
          resizeMode={ResizeMode.CONTAIN}
          selectedAudioTrack={selectedAudioTrack}
          selectedTextTrack={selectedTextTrack}
          showNotificationControls={false}
          source={{
            uri: url
          }}
          style={fullscreen ? styles.fullscreen : styles.inlineScreen}
          volume={volume}
        />`

### Reproduction

repository link

### Reproduction

![ss](https://github.com/TheWidlarzGroup/react-native-video/assets/110587704/93bdd8a4-844e-4bae-8c3c-81290e485931)

**Comment by KrzysztofMoch** [comment]
@MTPL0005-AbhishekDubey I made fix for it - https://github.com/TheWidlarzGroup/react-native-video/pull/3861

**Comment by amitkumarcoding** [comment]
@KrzysztofMoch How can we hide 10 sec icon (forward and backward icon)

**Comment by KrzysztofMoch** [comment]
@amitmehtacode I respond you there - https://github.com/TheWidlarzGroup/react-native-video/issues/3822#issuecomment-2139413207
please don't question in issue from it's scope

**Comment by MTPL0005-AbhishekDube** [comment]
@KrzysztofMoch  Thank you for the fix.

**Comment by freeboub** [comment]
will be integrated in 6.2.0

**Comment by MTPL0005-AbhishekDube** [comment]
@freeboub When can we expect the next release?
