### ISSUE TITLE
why do i need source when i only want to play ads?

### ISSUE THREAD

**Issue by spyshower** [TheWidlarzGroup/react-native-video#3863]
### Version

6.1.2

### Architecture

Old architecture

### What happened?

as the title says. do i have to pass a dummy source or what?

also, why the fuck you only wrote 2 lines about ads in the docs? do i have to smell my feet to see how adTagUrl works?

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Congratulations! You are the first user I block !

**Comment by spyshower** [comment]
@freeboub sorry if i hurt your sensitive feelings

**Comment by freeboub** [comment]
@spyshower investigate issue, open pull request instead of crying.
It's not tweeter here. Good luck to find the fix.
