### ISSUE TITLE
[BUG]: autoplay prop is not in the docs and also missing from allowable props in the type defintion but seems to work

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3869]
### Version

6.0.0-beta.8

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

We were using this prop in 5.x.  We used @ts-ignore for it.  We still are using it against 6.0 but it seems the docs don't mention anywhere now and the change log seems silent on it.  It does seem to work still though.  So for me, the bug is 2-part (1) it's not documented and (2) the type should be fixed to accept it.

### Reproduction

repository link

### Reproduction

Should be easy to reproduce in any typescript environment.  Just specify the prop like autoplay={true} or the like.

**Comment by freeboub** [comment]
Hello, There is no autoplay prop implemented... I think you are just using it uselessly ...
The start is pause can be implemented with prop: paused, by default this is false.
As a conclusion, you can just remove the prop ...
