### ISSUE TITLE
[Android] [Bug] Progress doesn't work first few seconds

### ISSUE THREAD

**Issue by jcmandersson** [TheWidlarzGroup/react-native-video#387]
Video starts playing but progress currentTime is 0 the first few seconds even though onProgress is called. After a few seconds the time starts to update but still from 0 even though the video has played for a few seconds. Is this a known bug?

**Comment by prananta** [comment]
I experienced something similar to this. After I stop the debugging, it works ok again. Maybe you can try.

**Comment by ghost** [comment]
@jcmandersson please reopen with more info or 👉 http://stackoverflow.com/questions/tagged/react-native thanks
