### ISSUE TITLE
[BUG]: Is there a way to remove the black screen flickering during video initialization

### ISSUE THREAD

**Issue by xiaowang-web** [TheWidlarzGroup/react-native-video#3878]
### Version

6.0.0-alpha.5

### What platforms are you having the problem on?

Android

### System Version

6.0.0-alpha.5，All Android models

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
First I really advise you to upgrade to the last V6 version, there was some video flickering issue at playback start fixed recently. 
I think you are looking for this prop : https://thewidlarzgroup.github.io/react-native-video/component/props#shuttercolor

**Comment by freeboub** [comment]
This issue should already be solved, let's close.
ping me if I need to reopen it
