### ISSUE TITLE
[Android] Using Navigator: Invariant Violation: Element type is invalid 

### ISSUE THREAD

**Issue by mmailhos** [TheWidlarzGroup/react-native-video#388]
Hello,

I am currently trying to use this module to show a video page.Basically that's the page that comes from a camera and it is given a path to a picture or a video.

The error shown is:

**`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of '.Navigator'. `**

On most topics, it is related to a typo or a missing key parameter in the `<Video>`, which does not look to be the case here. 

```
'use strict';

import React, { Component } from 'react';
import {
  StyleSheet,
  View,
  Image,
  Navigator,
  Dimensions,
} from 'react-native';

var Video = require('react-native-video');

class ImagePreviewPage extends Component {
  constructor(props){
    super(props);
    this.state = { 
            picture: '',
            video: ''
    }
  }

  render() {
    this.state.picture = this.props.picture;
    this.state.video = this.props.video;

    return (
      <Navigator
          renderScene={this.renderScene.bind(this)}
          navigator={this.props.navigator}
          />
    );
  }
  renderScene(route, navigator) {
    return ( 
      <View style={styles.container}>
        { 
          this.state.picture != '' ?
          (
           <Image source={{uri:this.state.picture}} style={styles.backgroundImage} />
           ) : 
          (
           <Video source={{uri:this.state.video}} style={styles.backgroundVideo} resizeMode="cover"  repeat={true}  />
           )  
        }
      </View>);
  }
}
const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: null,
    height: null,
    justifyContent: "center",
    alignItems: "stretch",
  },
  overlay: {
    position: 'absolute',
    padding: 16,
    right: 0,
    left: 0,
    alignItems: 'center',
  },
  container: {
    backgroundColor: 'transparent',
    justifyContent: "center",
    alignItems: "stretch",
    flex: 1,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});


module.exports = ImagePreviewPage;
```

I installed the module like this, went smoothly:
`npm i -S react-native-video && react-native link`.

Anyone met this issue before?

**Comment by prananta** [comment]
i think it's because you're missing a closing curly bracket `}` there. Before `const styles = StyleSheet.create({`

Try using [flow](https://flowtype.org) maybe.

**Comment by mmailhos** [comment]
@prananta : Sorry this was just a typo when I cleaned the code as an example.

Even when trying to simply run:
`      <View>
           <Video />
      </View>);
`

I am receiving: 
`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method`

How can I check that the package is installed and link? This part should be okay though.

**Comment by sunruh** [comment]
I am currently experiencing the same issue. Has anyone been able to reproduce & solve this issue?

**Comment by ghost** [comment]
👉 http://stackoverflow.com/questions/tagged/react-native

**Comment by subelsky** [comment]
In case anyone comes across this, I followed @jhabdas's link to S.O. and then found what I think is [the answer](https://stackoverflow.com/questions/49254781/react-native-invariant-violation), having to do with how `react-native-video` exports the `Video` component, and how you should import it component. 

In my case, I changed from this:
```javascript
import { Video } from 'react-native-video'
```
to this:
```javascript
import Video from 'react-native-video'
```
and it worked!
