### ISSUE TITLE
[BUG]: iOS looping/repeat has noticable gap between playbacks. 

### ISSUE THREAD

**Issue by AlexLerman** [TheWidlarzGroup/react-native-video#3885]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Looping using repeat has an audio gap between tracks. File type is .m4a. No problems on react-native-sound though similar issue on expo-av.  File is 41s long so I don't believe it's a buffering issue. No such gap on Android. 

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

1. Use file type with no gap like .m4a
2. Load file from MainBundle with`'file:/${fs.MainBundlePath}/${filename}'` (Will look something like `file://private/var/containers/Bundle/Application/CCB722FF-4134-463F-8969-C481A84CAE51/{yourapp}/{filename}.m4a`
3. Render Video component, set repeat property to true, wait for file to repeat. 
4. You'll hear a noticeable gap on iOS between the end of you playback and the beginning of the next.

**Comment by freeboub** [comment]
I think this old PR is a good clue to start investigate the issue ... 
https://github.com/TheWidlarzGroup/react-native-video/pull/1799/files

**Comment by KrzysztofMoch** [comment]
This is caused because of "seeking" - when video is ending we seek it to start and it seems to be slow - not sure if we can do anything about it
