### ISSUE TITLE
Error while updating property 'transform' of a view managed by : RCTImageView

### ISSUE THREAD

**Issue by Noor0** [TheWidlarzGroup/react-native-video#389]
I am getting this error in android, don't know why.
[![Screenshot_1479479238.png](https://s17.postimg.org/8kgk0po5r/Screenshot_1479479238.png)](https://postimg.org/image/fnofgbtl7/)

**Comment by swaroopa94** [comment]
@Noor0 I Too Got the same error after upgrading my react native to 0.39.2. Didi You find any solution.

**Comment by iroth** [comment]
check this thread: https://github.com/facebook/react-native/issues/9841
