### ISSUE TITLE
[BUG]: React Native Video cannot play when it's inside NavigationContainer with error code: -11800 (Real device)

### ISSUE THREAD

**Issue by owennguyen3162** [TheWidlarzGroup/react-native-video#3896]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

17

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

I have a screen that displays a list of videos. When you click on a video, it opens a detailed video screen where the video should play. However, it doesn't play and shows an error code: -11800.

When I move the code to the root App.js, it works fine.

<img width="728" alt="Screenshot 2024-06-11 at 21 12 59" src="https://github.com/TheWidlarzGroup/react-native-video/assets/132932982/1673404f-789b-4d14-bef4-ca3109ea8756">

![Screenshot 2024-06-11 at 21 11 21](https://github.com/TheWidlarzGroup/react-native-video/assets/132932982/044a92d7-5965-4e93-b8d1-ec7ed01c2f43)

**Comment by freeboub** [comment]
Can you provide a sample app please ?
Do you have the issue on android also ?

**Comment by owennguyen3162** [comment]
> Can you provide a sample app please ? Do you have the issue on android also ?

My application is built only for the iOS platform, so I'm not sure if the issue occurs on Android.

**Comment by KrzysztofMoch** [comment]
Hey @owennguyen3162 can you create repo with reproduction, so I can debug this ?
