### ISSUE TITLE
Native controls for iOS

### ISSUE THREAD

**Issue by jbkaplan** [TheWidlarzGroup/react-native-video#390]
I believe somewhere after https://github.com/react-native-community/react-native-video/pull/119 native control skins for iOS stopped working.

Currently when I run the example this is what shows for _native_:

<img width="375" alt="no-controls" src="https://cloud.githubusercontent.com/assets/5161002/20443742/b896ab0e-ad93-11e6-9d53-d3a29631cb15.png">

Think it might be related to this block in RCTVideo.m from lines 88-96
```objective-c
- (AVPlayerViewController*)createPlayerViewController:(AVPlayer*)player withPlayerItem:(AVPlayerItem*)playerItem {
    RCTVideoPlayerViewController* playerLayer= [[RCTVideoPlayerViewController alloc] init];
    playerLayer.showsPlaybackControls = NO;
    playerLayer.rctDelegate = self;
    playerLayer.view.frame = self.bounds;
    playerLayer.player = _player;
    playerLayer.view.frame = self.bounds;
    return playerLayer;
}
```

Changing  ```playerLayer.showsPlaybackControls = NO;``` to `YES` fixed this:

![controls](https://cloud.githubusercontent.com/assets/5161002/20443808/1962bdec-ad94-11e6-929d-c70a91d8b602.png)

**Comment by Shenenkaka** [comment]
why not use presentFullscreenPlayer?

**Comment by alizbazar** [comment]
Because sometimes controls are useful when not in full screen. Also, toggling presentFullScreen presents the video by creating a new modal and bringing it up from the bottom. This is not ideal UX if you already have a video playing. Instead I would like to expand the playing video to cover the screen whenever user turns the device into landscape.

**Comment by duhseekoh** [comment]
Agreed. At the very least, it's confusing to have a controls option that has no effect.

Oh, and it might be a nice idea to have the presentFullScreen option in the example app as well.

**Comment by LandonS23** [comment]
@jbkaplan Thanks for the fix!

**Comment by FranciscoG** [comment]
> Changing playerLayer.showsPlaybackControls = NO; to YES fixed this:

confirmed this worked for me.   

Why isn't this something that could be set as an option via a prop?  
```
   <Video
       ...
       controls={true}
      ...
    />
```
I'm creating an iPad app with videos I want embedded into the page and I don't want to play them full screen.  This fix was the only way to get the contols to show

**Comment by euroclydon37** [comment]
@jbkaplan Thank you so much for your post. I was hit with an issue where presenting full screen on tvOS made seeking impossible until you had swiped the info view in and back out at least once. You could pause, but swiping left for right did nothing until the "hoop" was jumped through. lol

Your solution allowed me to manually make the video full screen, and the controls functioned as expected.

Why hasn't a solution to this been presented?
