### ISSUE TITLE
[FEATURE]: iOS notification controls lack functionality related to the progress bar with live playback

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#3902]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

15, 16, 17.5

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When viewing notification controls **on iOS** with a **live** stream, the following do not display:
- Duration/time elapsed
- Progress bar activity
- Circular scrub button

whereas on Android they do.

Observed on real devices (1 physical device on 17.5, 2 devices on Browserstack).

### Reproduction

Step to reproduce this bug are: 
1. Ensure props are set
```
<Video
  source={ uri: 'https://democracynow-hls.secdn.net/democracynow-live/play/democracynow.smil/playlist.m3u8' }
  showNotificationControls={true}
  playInBackground={true}
  />
```
2. Ensure background audio is enabled in XCode (`UIBackgroundModes: ["audio"]` in Expo)
3. Generate an iOS build
4. Run the iOS build on a physical device
5. Play the video player
6. Background the app
7. Scroll down from the top of the screen to see the notification controls
8. Observe the lack of the duration, progress bar activity, and the progress bar scrub button

e.g.

<img width="498" alt="Screenshot 2024-06-12 at 10 56 18 AM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/107127397/78cab568-1346-4a71-baed-7ed1b63ea013">

![iOS Live Control Notif Downward](https://github.com/TheWidlarzGroup/react-native-video/assets/107127397/b110b894-cab1-4d3e-83f8-a4e6f0fb1d90)

**Comment by paulrinaldi** [comment]
From looking at released apps such as CNN, NBC, and Radio on the Apple App Store and what is available in the [documentation](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfopropertyislivestream), it seems the best we can do on iOS is get the control notification banner to say "LIVE" instead of just he weird -- on both sides. This patch is what I think is required and other suggest on the [web (although from 2018)](https://stackoverflow.com/questions/53483705/how-to-display-live-in-the-control-center-swift-ios):

However, after making this change on 6.2.0, I still see the same functionality what is above.
```
class NowPlayingInfoCenterManager {
    static let shared = NowPlayingInfoCenterManager()
    ...
    public func updateMetadata() {
        ...
        nowPlayingInfo[MPNowPlayingInfoPropertyIsLiveStream] = true // todo: add if statement so we only do it on livestreams
    }
}
```

I also was struggling to figure out the best way to determine when to set the `nowPlayingInfo[MPNowPlayingInfoPropertyIsLiveStream] = true` since we should not set when the item being played is not a livestream.

Unfortunately, this can't be tested on a simulator since Apple doesn't show notifications on simulators so debugging what is going wrong is further complicated.

Looking for help/suggestions.

Goal (right side):
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/107127397/7a85ba8f-e7ba-46f8-923d-cf111b0ee472)

**Comment by freeboub** [comment]
@paulrinaldi did you see: [mpnowplayinginfopropertyplaybackprogress](https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfopropertyplaybackprogress) ? moreover the 'timings' are not peridicly refreshed, It also think it should be an issue ... 

maybe you can also try to enable: https://developer.apple.com/documentation/mediaplayer/mpnowplayingsession/4076567-automaticallypublishesnowplaying just to see if time is coming

I don't think live is the good clue, even if it make sens to enable its usage

**Comment by paulrinaldi** [comment]
Playbackprogress doesn't look too helpful in this case.  Unfortunately, apple notes that "If you create an MPNowPlayingSession object, don’t attempt to use it with the AVPlayer that an AVPlayerViewController presents." ([source](https://developer.apple.com/documentation/mediaplayer/mpnowplayingsession) and so it is taking more effort in trying to even test this. Also MPNowPlayingSession is only available in iOS 16+ it seems. 

Still, it is so weird that setting live doesn't work correctly. I may try the basic example.

**Comment by paulrinaldi** [comment]
I got live to work with that key being set in the example/basic, should be able to add a detection mechanism and then send a fix

**Comment by paul-rinaldi** [comment]
Working on iOS in 6.3 now
