### ISSUE TITLE
[Feature]: Document error event details 

### ISSUE THREAD

**Issue by eedeebee** [TheWidlarzGroup/react-native-video#3903]
### Description

I'm looking for documentation for the errors sent to onError

### Why it is needed ?

I want to capture playback errors (to sentry for example), but some errors are expected under normal conditions of use. In particular, I want to be able to differentiate errors caused by the network being inaccessible as those are interesting to me (content is missing or corrupt or whatever other errors I don't actually know since they aren't documented) per se. There are apis that will tell me when the device is on/off line but coordinating those with rnvideo will make it challenging and it would be more practical if rnvideo just documented the errors it sends so I could make a call on what is interesting or not.

### Possible implementation

Docs :)

### Code sample

For example, when I'm calling fetch I can ignore the networking errors this way 

```javascript
if (!(error instanceof TypeError) && (error as Error).name !== "TimeoutError") {    
       Sentry.captureException(error);
}
```

**Comment by freeboub** [comment]
I fully agree and this issue has already be identified, can be followed up in : https://github.com/TheWidlarzGroup/react-native-video/issues/3554 and https://github.com/TheWidlarzGroup/react-native-video/issues/2694
