### ISSUE TITLE
[BUG]: IMA SDK crash

### ISSUE THREAD

**Issue by Ibad9** [TheWidlarzGroup/react-native-video#3904]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

IOS

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I navigated to my video player page and navigated back before the video started playing. It crashes the app on the below lines in RCTVideo.swift

<img width="700" alt="Screenshot 2024-06-13 at 1 42 41 AM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/44775654/c39f9608-1a2c-4a09-ae4d-5bef86bfcbf1">

The error is related to it starts loading ad and the player is not there. 

On version 6.0.0 the same behaviour don't crash my app but it starts playing audio on other screen when I navigate back.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

Navigate to video player page having preroll ads navigate back immediately.

**Comment by freeboub** [comment]
That is very strange ... can you please provide the callstack of the crash ?
I don't see good reason for a crash here.
Additionally, a quick and dirty patch could be to wrap this call in a try / catch, but I am afraid:
- sometimes ads don't display
- what wil be the side effects afteraward

**Comment by Ibad9** [comment]
<img width="1644" alt="Screenshot 2024-06-14 at 5 10 09 PM" src="https://github.com/TheWidlarzGroup/react-native-video/assets/44775654/484b4e0a-a91f-4587-9b2c-c1d802190a35">

I am getting this.

**Comment by freeboub** [comment]
OK, thank you for the screenshot, it is clean to me now. Can you please try to re test your issue with this PR: https://github.com/TheWidlarzGroup/react-native-video/pull/3911 ?

**Comment by freeboub** [comment]
Fix will be included in 6.3.0

**Comment by Ibad9** [comment]
This fixes the crash issue but when I navigate to video page my ad is played even if i navigate back. The player is somehow not removed or cleared.
