### ISSUE TITLE
[Feature]: Need method to destroy player instance.

### ISSUE THREAD

**Issue by Ibad9** [TheWidlarzGroup/react-native-video#3905]
### Description

It will give more control over player instance.

### Why it is needed ?

Because the player instance is not destroyed sometimes on moving from the component.

### Possible implementation

Technical POV how to do it

### Code sample

Code sample

**Comment by freeboub** [comment]
Today you have 2 options to stop the player:
- put source={undefined} -> stop the player but keep the instance and view
- umount <Video component, it will release completely the player.

BTW, on 6.2.0 there sere some fix which may fix your issue ...

**Comment by freeboub** [comment]
I close the issue as what you are requesting is in fact umounting the Video component ...
