### ISSUE TITLE
[BUG]: CoreMediaErrorDomain error -12865 when attempting to play local .m3u8 file

### ISSUE THREAD

**Issue by aliudurim** [TheWidlarzGroup/react-native-video#3907]
### Version

"react-native-video": "^6.0.0-alpha.7"

### What platforms are you having the problem on?

iOS

### System Version

iOS 17

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

**Description:**

I'm experiencing an issue with the react-native-video library when trying to play a local .m3u8 file with its associated .ts segments stored in the DocumentDirectoryPath. The video player throws the following error:

`{"error":{"localizedRecoverySuggestion":"","code":-12865,"localizedDescription":"The operation couldn’t be completed. (CoreMediaErrorDomain error -12865.)","domain":"CoreMediaErrorDomain","localizedFailureReason":""},"target":3639}`

**Expected Behavior**
The video player should successfully play the .m3u8 file with the associated .ts segments.

**Actual Behavior**
The video player throws a CoreMediaErrorDomain error -12865 and fails to play the video.

### Reproduction

**Steps to Reproduce**

1. Place the .m3u8 file and associated .ts segment files in a folder named video-123 inside the DocumentDirectoryPath.
2. Try to play the .m3u8 file using react-native-video.

**Comment by MateoParodi** [comment]
+1

**Comment by KrzysztofMoch** [comment]
It seem like Apple does not support playing m3u8 files from local storage https://forums.developer.apple.com/forums/thread/69357
If you want to save hls streams, you have to download them as mp4 files

**Comment by I-am-Aakash-Jaiswal** [comment]
Is the problem solved? I am facing the same Issue, the .m3u8 file is not not playing in my IOS react native app, it was playing fine in my android app, do anyone have a solution doc it will be great if shared
