### ISSUE TITLE
[BUG]: requireNativeComponent: "RCTVideo" was not found in the UIManager

### ISSUE THREAD

**Issue by iyj6707** [TheWidlarzGroup/react-native-video#3912]
### Version

v6.2.0

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

```
'use client';

import { FC, memo } from 'react';
import Video from 'react-native-video';

import video from '../../../assets/videos/video.mp4';

type DemoComponentProp = {
  handlePress: () => void;
};

const DemoComponent: FC<DemoComponentProp> = ({ handlePress }) => {
  console.log(video);

  return (
    <View className="absolute left-0 top-0" onPress={handlePress}>
      <Video
        source={video}
        style={{ width: '100%', height: '100%' }}
        repeat
        controls={false}
      />
    </View>
  );
};

export default memo(DemoComponent);
```
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/34857550/15f6f175-6bfb-46bc-9fd0-00a432ca01f1)

Above code makes the error 'requireNativeComponent: "RCTVideo" was not found in the UIManager'
How can I fix this bug?

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:  call the <Video> component

**Comment by freeboub** [comment]
There are multiple related closed issues, did you check them ?
Can you please clarify your environment ? (expo, ...)

**Comment by mathoukha** [comment]
I have been trying to solve this error for the last 2 days, but not helpful. I found some answers to make it work but it has to change MIN_IOS_OVERRIDE  to 13 on Podfile in ios folder which I don't have, I've only android folder. But that is not the actual cause, I tried fresh install on react native 0.74.2 with expo and react native video 6.2.0.

**Comment by freeboub** [comment]
@mathoukha this repository uses expo https://github.com/freeboub/react-native-video-flatlist-sample
It works fine on my side ...

**Comment by freeboub** [comment]
@mathoukha maybe can you share your 'fresh install' project ?

**Comment by iyj6707** [comment]
I have already checked closed issues related to Podfile, but my issue pertains to Android. I am using react-native version 0.73.8 with the CLI.

**Comment by ajiehatajie** [comment]
same issue in react native cli in mode releases ios

**Comment by freeboub** [comment]
Guys, without any sample it is almost impossible to investigate. the project supports expo so it should work fine (sample has been move to expo). If you have a way to reproduce the issue please provide the informations here.
I will close the issue for now

**Comment by Kollshai** [comment]
Hi, I still have this problem

Version
v6.3.0

What platforms are you having the problem on?
Android

System Version
Android 14

On what device are you experiencing the issue?
Real device


 **ERROR  Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.**

How fix it?

**Comment by sahinboga** [comment]
Hi, I still have this problem

Version
v0.71.3

What platforms are you having the problem on?
iOS

System Version
iOS 17.2

On what device are you experiencing the issue?
emulator

ERROR Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

How fix it?

**Comment by mehthabux** [comment]
Happening for Android

**Comment by h-dung-95** [comment]
me too, is there any solution here?

**Comment by miloscopic** [comment]
Same problem on Android.

requireNativeComponent: "RCTVideo" was not found in the UIManager.

**Comment by freeboub** [comment]
Issue to follow here: https://github.com/TheWidlarzGroup/react-native-video/issues/4017 Fix ongoing !

**Comment by kaushalpanchal123** [comment]
Use Below Command that might be solve issue:-
npm install --save react-native-video react-native-video-controls

**Comment by rasoulMO** [comment]
have same issue 

"Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager."

**Comment by Enhjino** [comment]
i changed my minimum platform version to 13 and still have this problem

**Comment by luizfelipefalcao** [comment]
I have the same issue on version 6.5.0 RN version "0.68.7"
