### ISSUE TITLE
[BUG]: Notification Control is not visible in 6.2.0

### ISSUE THREAD

**Issue by MTPL0005-AbhishekDube** [TheWidlarzGroup/react-native-video#3917]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

iOS 17.5.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

In the iOS the notification control is not visible when **showNotificationControls** is set **true**.

`        <Video
          bufferConfig={{
            minBufferMs: 15000,
            maxBufferMs: 50000,
            bufferForPlaybackMs: 2500,
            bufferForPlaybackAfterRebufferMs: 5000,
            cacheSizeMB: 0,
          }}
          // fullscreen={fullscreen}
          muted={muted}
          onAspectRatio={this.onAspectRatio}
          onAudioTracks={this.onAudioTracks}
          onBuffer={this.onBuffer}
          onEnd={this.onEnd}
          onLoad={this.onLoad}
          onLoadStart={this.onVideoLoadStart}
          onProgress={this.onProgress}
          onReceiveAdEvent={this._onReceiveAdEvent}
          onTextTracks={this.onTextTracks}
          paused={paused}
          pictureInPicture={false}
          playInBackground={true}
          playWhenInactive={true}
          poster={courseImage}
          posterResizeMode="cover"
          preventsDisplaySleepDuringVideoPlayback={true}
          rate={rate}
          ref={(ref) => {
            this.videoPlayerRef = ref;
          }}
          resizeMode={ResizeMode.CONTAIN}
          selectedAudioTrack={selectedAudioTrack}
          selectedTextTrack={selectedTextTrack}
          showNotificationControls={true}
          source={{
            uri: url,
            metadata: {
              title: title,
              artist: mentorName,
              imageUri: courseImage,
            },
          }}
          style={fullscreen ? styles.fullscreen : styles.inlineScreen}
          volume={volume}
        />`

### Reproduction

repository link

### Reproduction

`        <Video
          bufferConfig={{
            minBufferMs: 15000,
            maxBufferMs: 50000,
            bufferForPlaybackMs: 2500,
            bufferForPlaybackAfterRebufferMs: 5000,
            cacheSizeMB: 0,
          }}
          // fullscreen={fullscreen}
          muted={muted}
          onAspectRatio={this.onAspectRatio}
          onAudioTracks={this.onAudioTracks}
          onBuffer={this.onBuffer}
          onEnd={this.onEnd}
          onLoad={this.onLoad}
          onLoadStart={this.onVideoLoadStart}
          onProgress={this.onProgress}
          onReceiveAdEvent={this._onReceiveAdEvent}
          onTextTracks={this.onTextTracks}
          paused={paused}
          pictureInPicture={false}
          playInBackground={true}
          playWhenInactive={true}
          poster={courseImage}
          posterResizeMode="cover"
          preventsDisplaySleepDuringVideoPlayback={true}
          rate={rate}
          ref={(ref) => {
            this.videoPlayerRef = ref;
          }}
          resizeMode={ResizeMode.CONTAIN}
          selectedAudioTrack={selectedAudioTrack}
          selectedTextTrack={selectedTextTrack}
          showNotificationControls={true}
          source={{
            uri: url,
            metadata: {
              title: title,
              artist: mentorName,
              imageUri: courseImage,
            },
          }}
          style={fullscreen ? styles.fullscreen : styles.inlineScreen}
          volume={volume}
        />`

**Comment by MTPL0005-AbhishekDube** [comment]
Also give following log in Xcode terminal

RNV:setSrc Stopping playback
Error occurred: The operation couldn’t be completed. (OSStatus error -50.)
Error occurred: The operation couldn’t be completed. (OSStatus error -50.)
Error occurred: The operation couldn’t be completed. (OSStatus error -50.)
Error occurred: The operation couldn’t be completed. (OSStatus error -50.)

**Comment by freeboub** [comment]
@MTPL0005-AbhishekDube can it be a duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/3890 ?

**Comment by paulrinaldi** [comment]
I have my notification controls initially and always set to true on `6.2.0` on iOS and the notification show right away when video starts on my physical device using `17.5.1`.

I would suggest simplifying the props you're using on the video player and or try the source you're using in the example/basic. You can build the basic example in xcode into an ipa file and test that on your physical ios device.

**Comment by MTPL0005-AbhishekDube** [comment]
@paulrinaldi I haven't done any changes in by code before it was showing the the notification controls.

**Comment by freeboub** [comment]
@MTPL0005-AbhishekDube can you please test 6.3.0 ? the ticket I linked is fixed in this version.

**Comment by MTPL0005-AbhishekDube** [comment]
@freeboub now it is visible.
