### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Sumeeth-24** [TheWidlarzGroup/react-native-video#3921]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

above 13

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

https://drive.google.com/file/d/1W47ZdguoMQnu85hr5aVNUHIt0AYNcyEo/view?usp=sharing

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
Not supported
