### ISSUE TITLE
[BUG]: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer

### ISSUE THREAD

**Issue by quangtuan28200** [TheWidlarzGroup/react-native-video#3927]
### Version

6.2.0

### What platforms are you having the problem on?

Android

### System Version

95% is Android 12

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

i use `react-native 0.69.7`, this problem occurs when i upgrade `react-native-video` from `v5` to `v6`.

![ScreenShot_20240620220217](https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/b7501771-954b-443e-82a0-d391828f4204)
![ScreenShot_20240620220258](https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/4565fc60-6710-4978-939a-647b1d7c0a6d)
![ScreenShot_20240620220709](https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/7655241f-a826-4b42-9cb9-97d78d390e58)
![ScreenShot_20240620220841](https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/e4be6e3a-8a66-4cda-8caa-e5da89fa91d3)

### Reproduction

repository link

### Reproduction

sorry but i can't reproduce the problem

**Comment by freeboub** [comment]
Why did you close ? Not a rnv issue ?

**Comment by quangtuan28200** [comment]
I'm not sure, I haven't found the cause of the problem at the moment, as you can see, I only found the removeObsever function in the ios directory of react-native-video, the problem only happens with android. Maybe it's from another library, but I didn't upgrade any libraries other than react-native-video in my new version.

**Comment by freeboub** [comment]
@quangtuan28200 Ok, In fact I think you are right, this should not be an issue of react native video ...
I will close the issue don't hesitate to reopen if you have more clue !
