### ISSUE TITLE
[BUG]:  Ad control not working on android

### ISSUE THREAD

**Issue by sankhadeeproy007** [TheWidlarzGroup/react-native-video#3928]
### Version

"react-native-video": "6.1.2"

### What platforms are you having the problem on?

Android

### System Version

Any android version

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

- The ad overlay with play/pause button and skip ad doesn't appear always
- When playing an ad on `android`, the adEvents `PAUSED` and `RESUMED` get triggered, but do not actually pause or resume the ad. The issue is only with ads.

### Reproduction

Step to reproduce this bug are: 
Try any video on android with ads.

**Comment by freeboub** [comment]
do you use controls ?

**Comment by sankhadeeproy007** [comment]
No, controls are off. I am using custom UI for controls.

**Comment by FabrizioCostaMedich** [comment]
there is any update?

**Comment by freeboub** [comment]
You can try this PR for point 1: https://github.com/TheWidlarzGroup/react-native-video/pull/4185
Point 2, I don't reproduce it on sample. do you reproduce it with the sample app or another condition ?
I am trying with the linked PR
