### ISSUE TITLE
Video is not working with TouchableHightlight

### ISSUE THREAD

**Issue by Pegahkeshavarz** [TheWidlarzGroup/react-native-video#393]
when i am trying to wrap the Video inside TouchableHighlight with View Component around it, it wont work, it is only showing a blank page.What i want to do is by clicking on the video, route the app to another page.

 <TouchableHighlight  onPress={() => {this.setState({paused: !this.state.paused})}}>
                <View>
                    <Video
                           source={{uri: background}}   
                           resizeMode="cover"          
                           repeat={false}               
                           key="video2"
                           paused={this.state.paused}
                           onEnd={this.onVideoEnd}      
                           onError={this.onVideoEnd}   
                           style={Style.backgroundVideo} />
                </View>
            </TouchableHighlight>

**Comment by Pegahkeshavarz** [comment]
i fixed my issue by adding right style to TouchableHightlight and removing View component around it. so i am gonna close this issue

**Comment by MwareSolutons** [comment]
what was the right style please share

**Comment by CHaNGeTe** [comment]
Probably flex: 1 should be enough y video style sets its dimensions
