### ISSUE TITLE
[BUG]: Play/Pause icon is not visible on Notification Control

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3930]
![1000175431](https://github.com/TheWidlarzGroup/react-native-video/assets/90309641/d7c37dde-c3e3-43e3-ae13-b55abeeecb44)
### Version

6.1.2

### What platforms are you having the problem on?

Android

### System Version

Android 12, 13, 14

### On what device are you experiencing the issue?

Samsung A73, OnePlus 10R, Oppo

### Architecture

Old architecture

### What happened?

A bug happened!

Play and Pause Icon is not visible when I play any Audio

### Reproduction

Step to reproduce this bug are:

**Comment by amitmehtacode** [comment]
![Uploading 1000175431.jpg…]()

**Comment by freeboub** [comment]
New fix has been integrated in 6.3.0 can you please test this version ?

**Comment by amitkumarcoding** [comment]
@freeboub working fine in 6.3.0
