### ISSUE TITLE
[BUG]: When a component is destroyed in the iOS system, the sound is still playing

### ISSUE THREAD

**Issue by Arise-cn** [TheWidlarzGroup/react-native-video#3937]
### Version

6.2.0

### What platforms are you having the problem on?

iOS

### System Version

iOS 17.2

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: When a component is destroyed in the iOS system, the sound is still playing

**Comment by freeboub** [comment]
not enough information to investigate, you need at least to explain how you reproduce the issue ...

**Comment by zhanshihua** [comment]
same problem , does anyone have a solution
