### ISSUE TITLE
Video Continues to play even in the instance

### ISSUE THREAD

**Issue by swaroopa94** [TheWidlarzGroup/react-native-video#394]
HI,
 I am using this module for video playing.
While video is playing when I click in the instance button the video continous to play.
I also used the code:
`  if(appstate =='background'){
      this.setState({paused:true})
    }`
but when goes to background its playing when again comes to active state its getting paused.
Can anyone help me on solving this.

**Comment by ghost** [comment]
@swaroopa94 might have some luck digging around here: https://github.com/jhabdas/lumpen-radio/tree/master-backup. otherwise please 👉 http://stackoverflow.com/questions/tagged/react-native
