### ISSUE TITLE
[BUG]: In react native 0.74.2 having issue on react-native-video@latest 

### ISSUE THREAD

**Issue by PranabLyk** [TheWidlarzGroup/react-native-video#3946]
### Version

6.3.0

### What platforms are you having the problem on?

Android

### System Version

0.74.2

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-video.
     Required by:
         project :app
      > No matching configuration of project :react-native-video was found. The consumer was configured to find a library for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.2.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Review the variant matching algorithm at https://docs.gradle.org/8.6/userguide/variant_attributes.html#sec:abm_algorithm.
> No matching variant errors are explained in more detail at https://docs.gradle.org/8.6/userguide/variant_model.html#sub:variant-no-match.

### Reproduction

repository link

### Reproduction

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-video.
     Required by:
         project :app
      > No matching configuration of project :react-native-video was found. The consumer was configured to find a library for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.2.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Review the variant matching algorithm at https://docs.gradle.org/8.6/userguide/variant_attributes.html#sec:abm_algorithm.
> No matching variant errors are explained in more detail at https://docs.gradle.org/8.6/userguide/variant_model.html#sub:variant-no-match.

**Comment by freeboub** [comment]
Not sure on how you you go to this point...
Can you please provide a sample app to reproduce the issue ?
Is ios working on your side ?

**Comment by PranabLyk** [comment]
@freeboub  Ios Working fine but android having issue .I have setup for everything for android app .

**Comment by PranabLyk** [comment]
now this issue has been fixed .Actually this issue raise from my side not react-native-video side .Thanks

**Comment by mjunaid1992** [comment]
@PranabLyk Can you please explain what was the issue you found and how did you resolve it. I'm getting the same issue when updating Version from 5.2.1 to 6.2.0

**Comment by PranabLyk** [comment]
@mjunaid1992 you just cross check your setting.gardle file inside react-native-video node module path is corrected or not .
e.g 
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
like that required 
Note: Not other file changes required

**Comment by freeboub** [comment]
This is documented here : https://thewidlarzgroup.github.io/react-native-video/updating#android
