### ISSUE TITLE
[BUG]: Android project no longer builds if useExoplayerHls = false

### ISSUE THREAD

**Issue by EETVApps** [TheWidlarzGroup/react-native-video#3948]
### Version

6.3.0

### What platforms are you having the problem on?

Android

### System Version

Any

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

The fix for #3766 means that any app that doesn't choose to include the Media3 HLS libraries will now fail to build.  This is due to the new requirement for setAllowChunklessPreparation to exist on HlsMediaSource.Factory.

A stub implementation exists in the project to allow code to compile without including the HLS libraries - I believe it just needs to be updated to add the stub method. 

### Reproduction

repository link

### Reproduction

Try to build the app with useExoplayerHls = false

**Comment by KrzysztofMoch** [comment]
Will be fixed in `6.3.1`
