### ISSUE TITLE
Player stopped and not play video when changing video source

### ISSUE THREAD

**Issue by davidstefando** [TheWidlarzGroup/react-native-video#395]
I'm trying to change video source by changing it's source state

----
< Video source={{uri: this.state.videoSource}}   } />

----
I call this function

this.setState({
   return {
      videoSource: 'newVideoSource.mp4'),
   }
});

But instead of played the new video source, the player is hang.
Any ideas how to implement it? it's a bug or it's not implemented yet?

**Comment by jbkaplan** [comment]
You shouldn't need return on `this.setState()` just do:

```javascript
this.setState({
  videoSource: 'newVideoSource.mp4'
});
```

**Comment by ghost** [comment]
👉 http://stackoverflow.com/questions/tagged/react-native
