### ISSUE TITLE
react native video can not play after upgrade react-native@0.38

### ISSUE THREAD

**Issue by oubushixb** [TheWidlarzGroup/react-native-video#396]
the onProgress never execute....but the video placeholder pic is show..

**Comment by pawlowskim** [comment]
Probably it's problem with sendInputEventWithName that is used across whole library. We are using RCTBubblingEventBlock instead right now and our lib looks working fine. Could any contributor confirm it?

**Comment by billdozr** [comment]
This seems to be the cause https://github.com/react-native-community/react-native-video/blob/6b62119ce0bacfd990cb6ab3b0486feeb603d2be/ios/RCTVideoManager.m#L19

If I change `customDirectEventTypes` (which was removed in RN@0.38) to `customBubblingEventTypes`, things work again. But `customBubblingEventTypes` is deprecated.

Luckily there seems to be more of a proper fix here https://github.com/react-native-community/react-native-video/pull/381 awaiting commit.

**Comment by turtec** [comment]
@billdozr works for me!
