### ISSUE TITLE
[BUG]: onProgress on Android only returns integers

### ISSUE THREAD

**Issue by maksymhcode-care** [TheWidlarzGroup/react-native-video#3960]
### Version

6.3.0

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

Method seek can take floating points but after loading is done onProgress return whole number

### Reproduction

Step to reproduce this bug are:  On Android use method seek and give floating point as an argument(35.5 for example), after seek and loading is done onProgress will return whole number 35

**Comment by freeboub** [comment]
@maksymhcode-care can it be a duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/3971 ?

**Comment by maksymhcode-care** [comment]
> @maksymhcode-care can it be a duplicate of #3971 ?

Not sure, seek method works for me if use floating point, so no issue with that, the issue is that after buffering is done onProgress  returns integer. Don't know if your fix will help as of right now

**Comment by freeboub** [comment]
I just tested on master branch, I don't reproduce the issue on both live and VOD, not reproduced. 
I think it was the same issue I was pointing ...

**Comment by freeboub** [comment]
I close the issue, let me know if reproduced on > 6.4.3

**Comment by maksymhcode-care** [comment]
> I close the issue, let me know if reproduced on > 6.4.3
Hope you can also help with this one https://github.com/TheWidlarzGroup/react-native-video/issues/3941
