### ISSUE TITLE
[BUG]: In Apple TV mp4 video is not playing it's only fetching thumbnail of video

### ISSUE THREAD

**Issue by prime-prashant** [TheWidlarzGroup/react-native-video#3966]
### Version

^6.3.0

### What platforms are you having the problem on?

Apple tvOS

### System Version

MAC OS Ventura 13.6.4

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

There aren't any issues in Console or anywhere.
On FireTV it's working fine.
but when we run in AppleTV loads and after loading get paused on first screen.
When we forward 10 seconds it fetches thumbnail of video of 10th second. but video down't plays

### Reproduction

repository link

### Reproduction

Integrate react-native-video package on 
react-native-tvos
both are basic setups 
Run Xcode and Open App in AppleTV or simulator
even sample video is not playing on apple TV.

**Comment by freeboub** [comment]
I recently tested the appleTV sample included in this repo with 6.5.0 I don't have this issue, I can reopen the ticket, plus please provide a sample app which reproduce the issue
