### ISSUE TITLE
failed to find target with hash string 'android-23'

### ISSUE THREAD

**Issue by nanandn** [TheWidlarzGroup/react-native-video#397]
When I run 'react-native run-android' I get this error.
" A problem occurred configuring project ':react-native-video'."
"failed to find target with hash string 'android-23'"

I am using android SDK version 25 for my app.  Does react-native-video work with android 25?

**Comment by ghost** [comment]
👉  http://stackoverflow.com/questions/tagged/react-native

**Comment by pawan8525** [comment]
what 
👉 http://stackoverflow.com/questions/tagged/react-native
no solution found?

**Comment by JTraill** [comment]
Having the same issue here
