### ISSUE TITLE
[BUG]: Seek method in android , only integer seconds can make effect

### ISSUE THREAD

**Issue by zackfly** [TheWidlarzGroup/react-native-video#3971]
### Version

6.3.0

### What platforms are you having the problem on?

Android

### System Version

6.3.0

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

Seek method in android , only support integer number

### Reproduction

1.load any local source
2. use the hook below ,try to keep seeking the video by 0.1 s
```
React.useEffect(() => {
    let index = 0;
    var ref = setInterval(() => {
          index = index +0.1
          console.log(index);
          videoRef?.current?.seek(index);

    }, 100);

    return () => {
      clearInterval(ref);
    };
  }, []);
```
3.then , when the second is 0.1 0.2.... nothing happened,if it come to 1.1  it will play one time . then keep stucked ,util it come to 2.0, 2.1

**Comment by freeboub** [comment]
would this patch be enough ?

```diff
diff --git a/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt b/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt
index 716f337d..b20497ba 100644
--- a/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt
+++ b/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt
@@ -49,7 +49,7 @@ class VideoManagerModule(reactContext: ReactApplicationContext?) : ReactContextB
             return
         }
 
-        val time = ReactBridgeUtils.safeGetInt(info, "time")
+        val time = ReactBridgeUtils.safeGetDouble(info, "time")
         performOnPlayerView(reactTag) {
             it?.seekTo((time * 1000f).roundToInt().toLong())
         }

```

ping @KrzysztofMoch as you are owner of this line of code :)

**Comment by freeboub** [comment]
This code has been changed been moved to float in 6.4.1 I think we can close the ticket
