### ISSUE TITLE
Unable to play video on iOS using remote URL without file extension. 

### ISSUE THREAD

**Issue by nanandn** [TheWidlarzGroup/react-native-video#398]
I am new to react-native. I am trying to use react-native-vidoe to play video using remote URL. The URL does not have file extension or if the mime-type is not set. The video is not playing and I see avfoundationerrordomain code=-11828. The iOS documentation says that this is a 'fileFormatNotRecognized' error. 

I saw some discussions saying that iOS cannot play movies without filename extensions and some workarounds suggested.

http://stackoverflow.com/questions/5501670/how-to-play-movie-files-with-no-file-extension-on-ios-with-mpmovieplayercontroll

http://stackoverflow.com/questions/9290972/is-it-possible-to-make-avurlasset-work-without-a-file-extension

Will the workaround suggested work for react-native-video. I don't know Objective-C. Is this something that can be done in this component?

Anand

**Comment by wandonye** [comment]
I'm having the same problem

**Comment by nanandn** [comment]
I was able to play by setting the content-type to video/quicktime. 
If you are playing a local file you need to use ‘require’ rather than setting a source uri.

Anand

**Comment by cinder92** [comment]
@nanandn  can you share your code please? i can't play videos from youtube...

**Comment by ZionChang** [comment]
+1

**Comment by destinyb-realityi** [comment]
+1

**Comment by andry1001** [comment]
+1

**Comment by 3DJakob** [comment]
> I was able to play by setting the content-type to video/quicktime. If you are playing a local file you need to use ‘require’ rather than setting a source uri. Anand
> […](#)

@nanandn How did you do this? Could you provide a code snippet please?

**Comment by ohmdob** [comment]
### If file size < 200mb you can use RNFetchBlob to write the temporary file

```

  const [file, setFile] = useState('')

  useEffect(() => {
    RNFetchBlob
    .config({
      fileCache : true,
      appendExt : 'mp4'
    })
    .fetch('GET', uri, {
    })
    .then((res) => {
      setFile(res.path())
      console.log('The file saved to ', res.path())
    })

    return () => {
      Orientation.lockToPortrait()
    }
  },[])

  if(file === '')
  return <></>

  return <VideoPlayer
    onExitFullscreen={() => Orientation.lockToPortrait()}
    onEnterFullscreen={() => Orientation.lockToLandscape()}
    source={{uri: file}}
    navigator={navigation}
  />
})
```

**Comment by raghvendra007** [comment]
facing the same issue is there any solution for it
