### ISSUE TITLE
[Feature]: Event listeners for notification controls

### ISSUE THREAD

**Issue by nickmcmillan** [TheWidlarzGroup/react-native-video#3986]
### Description

Thanks to the `showNotificationControls` prop we can use OS-level buttons to control media playback 👍

Would it be possible to add an event listener for when these buttons are pressed?

### Why it is needed ?

It would be useful to respond to playback changes triggered from the notification controls in the UI.

In my specific use case I am playing two separate audio files at the same time (one is spoken dialogue, one is background music). I'd like the notification controls to pause/play both files simultaneously. That's not currently possible because `showNotificationControls` is unique per <Video />.

But my thinking is that if I can add `showNotificationControls` to just one of the <Video /> components, and use a callback to detect when it is played/paused from notifications, I can then inform the second <Video /> to respond accordingly.

### Possible implementation

Perhaps a prop such as:
```
<Video
  showNotificationControls
  onNotificationControlEvent={e => {
   // useful if the event specified which button was pressed
  }}
/>

### Code sample

Code sample

**Comment by freeboub** [comment]
Understood, but not planned. There is another ticket for synchronisation between multiple players but not yet planned...
I don't understand why current events are not enough? You can register events triggered when pause/resume state change and also onSeek processed.
If you don't find them I can provide you the direct link.
The only issue is synchronisation, but regarding the description, I don't think you need synchronisation between the streams.

**Comment by nickmcmillan** [comment]
Are you referring to the `onPlaybackStateChanged` prop? I hadn't considered that it would include state changes triggered by the notification controls. So that actually suits my use case and solves it for me!
