### ISSUE TITLE
[BUG]: Using showNotificationControls - title is referenced from mp3 file metadata, not source.metadata.title

### ISSUE THREAD

**Issue by nickmcmillan** [TheWidlarzGroup/react-native-video#3987]
### Version

6.3.0

### What platforms are you having the problem on?

iOS

### System Version

react native 0.73.6. iOS 17.5.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When playing an mp3 file whilst using `showNotificationControls`, the controls display the "title" value stored in the mp3 file metadata. The value provided in the `source` prop is ignored.

If the mp3 file does not contain "title" metadata it works correctly.

iOS has the issue. Android works as expected.

### Reproduction

Add a value to the "title" metadata field for a given mp3 file (Apple Music is one app where you can do this).
Then specify the `metadata.title` value in `source`. 
In the notification controls, notice that the value encoded in the mp3 takes precedence.

```
const source: ReactVideoSourceProperties = {
      uri: 'file:///example.mp3',
      metadata: {
        title: 'Love Me Do', // if the mp3 file contains "title" metadata, this property is ignored
        artist: 'The Beatles',
      },
    }

return (
  <Video
    source={source}
    showNotificationControls
  />
)
```

**Comment by KrzysztofMoch** [comment]
I will look into this next week 👀

**Comment by KrzysztofMoch** [comment]
Hey @nickmcmillan can you test https://github.com/TheWidlarzGroup/react-native-video/pull/4050 ?

**Comment by nickmcmillan** [comment]
@KrzysztofMoch perfect, thank you 🙏
