### ISSUE TITLE
Square video

### ISSUE THREAD

**Issue by sirgalleto** [TheWidlarzGroup/react-native-video#399]
I'm trying yo record a square video but I dont find how.

**Comment by bsiddiqui** [comment]
@sirgalleto you'll need to edit the video after you finish recording

**Comment by sirgalleto** [comment]
Yeah, I made this. Thanks

**Comment by ksshanu** [comment]
@sirgalleto Can you please tell which method you have used for making video square?

**Comment by roycclu** [comment]
@ksshanu  try this video-processor for react native, looks promising. 
https://github.com/shahen94/react-native-video-processing

@sirgalleto what solution did you find?

**Comment by PankajChaturvediDtechies** [comment]
> Yeah, I made this. Thanks

Can you tell me how did you manage to do that?
