### ISSUE TITLE
undefined is not an object (evaluating 'NativeModules.VideoManager.ScaleAspectFill')

### ISSUE THREAD

**Issue by wheycool** [TheWidlarzGroup/react-native-video#40]
Can you help out?

**I'm getting errors within React's simulator:**
`undefined is not an object (evaluating 'NativeModules.VideoManager.ScaleAspectFill')`

`Video_render`
`Video.ios.js:79`
`...`

I have added "background.mp4" to xcode, within a folder called "assets-library", and have added the mp4 to Copy Bundle Resources.

**Here is the code:**

```
'use strict'

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator,
  TouchableHighlight
} = React;

var Video = require('react-native-video')
var FacebookLoginManager = require('NativeModules').FacebookLoginManager;


var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  background: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
  },
  backgroundOverlay: {
    opacity: 0.5,
    backgroundColor: '#ffffff',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});

var FacebookLogin = React.createClass({
  getInitialState() {
    return {
      result: 'HELLO!'
    }
  },

  componentDidMount() {
    var self = this;
  },

  login() {
    FacebookLoginManager.newSession((error, info) => {
      if (error) {
        this.setState({result: error});
      } else {
        this.setState({result: info});
      }
    });
  },

  render() {
    return (
      <View style={styles.background}>
        <Video source={{uri: "background"}}
               resizeMode="cover" repeat={true} key="video2" 
               style={styles.backgroundVideo} />
      <View style={styles.backgroundOverlay} />

      <View style={styles.container}>
        <TouchableHighlight onPress={this.login}>
          <Text style={styles.welcome}>
            Facebook Login
          </Text>

        </TouchableHighlight>
        <Text style={styles.instructions}>
          {this.state.result}
        </Text>
      </View>
      </View>
    )
  }
})



AppRegistry.registerComponent('FacebookLogin', () => FacebookLogin);

module.exports = FacebookLogin
```

**Comment by brentvatne** [comment]
Hi @wheycool! Which version of react-native are you using? And react-native-video? Thanks for the full example!

**Comment by wheycool** [comment]
Downloaded react-native-video from you today, so the latest I presume. React Native is what NPM is currently providing: v0.1.3

**Comment by brentvatne** [comment]
React Native version should be 0.4.4 :smile:

**Comment by wheycool** [comment]
Sorry, I was mistaken. I just checked out the package.json within the react-native node, and it's 0.4.4.

**Comment by wheycool** [comment]
Fixed it! I just started from scratch with the NPM install. I must have been doing something wrong the first time. Sorry for wasting your time – and thanks for getting back to me! :)

**Comment by brentvatne** [comment]
no problem @wheycool, glad you resolved it!

**Comment by markburns** [comment]
Hey, I am running into this issue too. Still trying to debug it, but re-installing didn't work

**Comment by brentvatne** [comment]
@markburns - react native version? reinstall might require a `npm cache clean` and a `rm -rf node_modules/react-native-video`

**Comment by markburns** [comment]
Just tried that, same problem. Also clean, build, and reset the content and settings on the iOS simulator.

react-native-video 0.4.1
react-native 0.4.4

**Comment by brentvatne** [comment]
@markburns - probably a sign that it's not linking correctly, try going through these steps again: https://github.com/brentvatne/react-native-video#add-it-to-your-project

**Comment by markburns** [comment]
Yeah that was it, thanks.

**Comment by markburns** [comment]
WDYT about having something like:

``` js

if(!NativeModules.VideoManager){
  throw("NativeModules.VideoManager is undefined - ensure you are linking the library correctly " + 
        "https://github.com/brentvatne/react-native-video/issues/40");
}
```

as a fail fast?

I imagine a lot of people who are familiar with JS will be attracted to React Native, and if this is/becomes the defacto video library then it might keep people like me (less familiar with Xcode/native) from making too much noise in the issues.

**Comment by brentvatne** [comment]
@markburns - I like that! can you submit a PR?
