### ISSUE TITLE
[BUG]: AVFoundationErrorDomain

### ISSUE THREAD

**Issue by fernandocortes-sr** [TheWidlarzGroup/react-native-video#4004]
### Version

6.x.x

### What platforms are you having the problem on?

iOS

### System Version

iOS 16/17

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

{"target":6315,"error":{"localizedRecoverySuggestion":"","code":-11850,"domain":"AVFoundationErrorDomain","localizedFailureReason":"The server is not correctly configured.","localizedDescription":"Operation Stopped"}}

### Reproduction

<VideoPlayer source={{ uri: 'https://www.youtube.com/embed/YE7VzlLtp-4?autoplay=1' }} />

**Comment by freeboub** [comment]
Following urls are not video urls, they are web urls. Have a look to react-native-youtube-iframe if you want to use these urls.
