### ISSUE TITLE
[BUG]: onProgress is not updating in android 

### ISSUE THREAD

**Issue by NorbertoStudios** [TheWidlarzGroup/react-native-video#4005]
### Version

6.4.1

### What platforms are you having the problem on?

Android

### System Version

react native 0.73.1-1

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

The OnProgress method is only being trigger once when playing live video 
for the controls it get stuck in the last number received

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
run the app and console log the onprogress method

**Comment by freeboub** [comment]
I just checked on master (6.4.2 ++) I don't reproduce the issue ...
can you provide your sample stream ? maybe it is linked to the stream itself .. is it live ?
