### ISSUE TITLE
[BUG]: hideShutterView does not work

### ISSUE THREAD

**Issue by FrederickEngelhardt** [TheWidlarzGroup/react-native-video#4006]
### Version

6.4.1

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

`hideShutterView` prop for android use to work. I upgraded recently from `6.0.0-alpha.6` to `6.4.1` and ran into the problem where the shutter shows up as a black window (on a white background with a white background video that loads).

```tsx
      <RNVideo
        {...props}
        hideShutterView // should hide blackscreen on load for android (does not work on 6.4.1)
      />
```

## Workaround

Add a colored view overlay until the video player is ready. Interesting part is `onLoaded` and `onReadyForDisplay` still require a debounce of anywhere between 20-200ms for the black screen to not show.

```tsx
import { View, StyleSheet } from 'react-native'
import RNVideo from 'react-native-video'

// or a variant of this, could easily be a simple JS timer.
import debounce from 'lodash.debounce'

const component = () => {
    const [isLoaded, setIsLoaded] = useState(false)

  const debouncedOnLoad = useMemo(
    () => debounce(() => setIsLoaded(true), 200),
    [],
  )

  return (
    <View>
      <RNVideo
        hideShutterView // hides blackscreen
      />
      {!isLoaded && Platform.OS === 'android' && (
        <View
          style={[
            StyleSheet.absoluteFillObject,
            { backgroundColor: 'white', zIndex: 9999 },
          ]}
        />
      )}
    </View>
  )
}
```

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
- Use 6.4.1 on android device. My device was a Note 20 Ultra. But should apply to all android devices using exoplayer

**Comment by freeboub** [comment]
can you try `shuttercolor={'transparent'}` prop ? : https://thewidlarzgroup.github.io/react-native-video/component/props#shuttercolor

**Comment by freeboub** [comment]
I tested hideShutterView in the sample app (6.4.3). It works as expected. I close the issue, but if I need to reopen, please provide a sample app.
and regarding to your expectation, I think you can put `shuttercolor={'white'}` !
