### ISSUE TITLE
onLoad() And onLoadStart() callbacks not working after upgrading RN 0.38.0

### ISSUE THREAD

**Issue by larryranches** [TheWidlarzGroup/react-native-video#401]
Upgrading to React Native 0.38.0 seems to have broken the onLoad() and onLoadStart() callbacks. I'm not to sure what other callback functions are broken but the onEnd() DOES work. 

All is working well when using React Native 0.37.0. These callbacks I think are very important.

Can anyone help fix this issue?

**Comment by rdews** [comment]
We're using this pull request and it works: 
https://github.com/react-native-community/react-native-video/pull/381

**Comment by larryranches** [comment]
@rdews I tested out that branch it still does not work. Also tested master on your guys forked repo and still doesn't seem to fire callbacks stated above.

package.json
`"react-native-video": "git+https://github.com/drivetribe/react-native-video.git#feature/custom-direct-event-type",`

ideas?

**Comment by rdews** [comment]
@larryranches we're pointing directly to the pull request in our package.json and the events fire: 
"react-native-video": "github:react-native-community/react-native-video#dbaea9c0ebf32d8e6f0066d9e02268fb8bdebdf5",

Maybe it didn't install correctly?

**Comment by larryranches** [comment]
@rdews Thanks for your reply. Yes, copied and pasted the npm link you provided. Stil not working but I think its because the code is not being updated in RCTVideo.xcodeproj for some reason. ideas?

**Comment by MadeInMoon** [comment]
updating to RN39 fixed it for me!

**Comment by rikner** [comment]
Also `onEnd()` does not get fired. Is it related to the removal of `customDirectEventType` in https://github.com/facebook/react-native/wiki/Breaking-Changes#038?

**Comment by shahen94** [comment]
+1 for this issue.

RN: 0.39
OS: MacOS
RN-Video: master

**Comment by hellogerard** [comment]
> Stil not working but I think its because the code is not being updated in RCTVideo.xcodeproj for some reason. ideas?

I had to unlink and link the project again.

```
$ react-native unlink react-native-video
$ react-native link react-native-video
```

**Comment by jaggerwang** [comment]
Seems all onX handlers not working.

React Native: 0.39
Platform: iOS, Android unknown

**Comment by joeferraro** [comment]
React Native: 0.38
react-native-video: 0.9.0

As @jaggerwang states above, none of the `on` handlers seem to be working.

**Comment by ghost** [comment]
https://github.com/react-native-community/react-native-video/issues/480
