### ISSUE TITLE
[BUG]: requireNativeComponent: "RCTVideo" was not found in the UIManager

### ISSUE THREAD

**Issue by anasvemmully** [TheWidlarzGroup/react-native-video#4017]
### Version

6.4.2

### What platforms are you having the problem on?

Android

### System Version

13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I get this when trying to mount a video component.

I looked through all possible issues, but it all points to iOS.
I thought this happens only on iOS, I wonder why in android, I got no idea 

I am using     
```
"react-native": "^0.72.4",
```
or "0.72.12" to be exact inside node_modules/

### Reproduction

Run this repo
https://github.com/anasvemmully/rnvtestv642

### Reproduction

Run the repo, if patch not applied automatically, apply manually for RNV V6.4.2

**Comment by anasvemmully** [comment]
if anyone encountered similar problem in android, submit the solution, 
else I will submit an example

**Comment by freeboub** [comment]
> if anyone encountered similar problem in android, submit the solution, 
> else I will submit an example

Yes a sample repository would be appreciated 👍

**Comment by seyedmostafahasani** [comment]
@freeboub I initialized a new app with React Native `version 0.74.2` and then added react-native-video `version 6.4.2`. The sample app works correctly. I think @anasvemmully forgot to run yarn android again after installing the library.

**Comment by surafelbm** [comment]
Same problem on Android with RN 0.71.0, has anyone solved this?

**Comment by inthroxify** [comment]
I was receiving this on android, and I managed to fix it for my instance of this problem. For reference, I am using react-native-tvos, as found in the Ignite TV sample repo, not "pure" react-native.

The literal steps I performed were: 
* in `package.json`, change `"react-native": "npm:react-native-tvos@^0.74.2-0",` to `"react-native": "npm:react-native-tvos@^0.74.3-0",`
* `yarn install`
* instead of running `yarn start` do a `yarn run android`

It might be that the last bullet is the trick. `yarn run android` seems to do a full-on recompile of everything, whereas `yarn start` just bundles things up and serves, I am guessing.

edit: after doing the last bullet, I can just go back to `yarn start`, as the recompile seems to have solved things going forward.

**Comment by anasvemmully** [comment]
Sorry for being late, iam trying to simulate the bug with the exact configs

Here is the sample repo @freeboub 
-> https://github.com/anasvemmully/rnvtestv642

![image](https://github.com/user-attachments/assets/b3bace41-eca5-426c-a5f1-3a7517ca8e3d)


NB:- Make sure to apply the patch for react-native-video v6.4.2 if not applied automatically, when raised for java multi case issue  (for java < v14)

**Comment by anasvemmully** [comment]
> I was receiving this on android, and I managed to fix it for my instance of this problem. For reference, I am using react-native-tvos, as found in the Ignite TV sample repo, not "pure" react-native.
> 
> The literal steps I performed were:
> 
> * in `package.json`, change `"react-native": "npm:react-native-tvos@^0.74.2-0",` to `"react-native": "npm:react-native-tvos@^0.74.3-0",`
> * `yarn install`
> * instead of running `yarn start` do a `yarn run android`
> 
> It might be that the last bullet is the trick. `yarn run android` seems to do a full-on recompile of everything, whereas `yarn start` just bundles things up and serves, I am guessing.
> 
> edit: after doing the last bullet, I can just go back to `yarn start`, as the recompile seems to have solved things going forward.

-1, It doesn't work for me.

**Comment by WaheedRumaneh** [comment]
+1

**Comment by freeboub** [comment]
I think the real issue happen before : 'NativeUIManager.getConstantsForViewManager(\'RCTVideo\') threw an exception.', [Error: Exception in HostFunction: java.lang.UnsupportedOperationException],
Not sure of the root cause yet ...

**Comment by freeboub** [comment]
Issue happen between 6.3.0 and 6.4.0 ...

**Comment by freeboub** [comment]
A first version of patch has created here: https://github.com/TheWidlarzGroup/react-native-video/pull/4022

**Comment by surafelbm** [comment]
> A first version of patch has created here: #4022

installed from the master directly

`"react-native-video": "TheWidlarzGroup/react-native-video#master"`
with the mentioned patch but still same error

**Comment by surafelbm** [comment]
> Sorry for being late, iam trying to simulate the bug with the exact configs
> 
> Here is the sample repo @freeboub -> https://github.com/anasvemmully/rnvtestv642
> 
> ![image](https://private-user-images.githubusercontent.com/69687301/349902305-b3bace41-eca5-426c-a5f1-3a7517ca8e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMzU1MTEsIm5iZiI6MTcyMTMzNTIxMSwicGF0aCI6Ii82OTY4NzMwMS8zNDk5MDIzMDUtYjNiYWNlNDEtZWNhNS00MjZjLWE1ZjEtM2E3NTE3Y2E4ZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDIwNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNTU4MmRiOTViZTkyMTgyYzNmNGYwYTgwMDVhZGQ4YjA1NDQzMDQ5YmNmMzliZTdlOGZjNzAyNDE3NDIzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGMtohQ2FoipIhshyYJFL2okNed-vHKQLjFraNUHVOs)
> 
> NB:- Make sure to apply the patch for react-native-video v6.4.2 if not applied automatically, when raised for java multi case issue (for java < v14)

@anasvemmully , i have already patched that myself but the issues still exists, did you make any other changes?

**Comment by surafelbm** [comment]
i can confirm the PR created fixes this issue.

`"react-native-video": "github:freeboub/react-native-video#chore/fixAppBoot",`

changed my package.json like this and it works

**Comment by anasvemmully** [comment]
@freeboub the fix works +1. Thanks :)

**Comment by anasvemmully** [comment]
> i can confirm the PR created fixes this issue.
> 
> `"react-native-video": "github:freeboub/react-native-video#chore/fixAppBoot",`
> 
> changed my package.json like this and it works

+1

**Comment by freeboub** [comment]
Wait for the merge before closing :)
