### ISSUE TITLE
[BUG]: Subtitle fontsize is not consistent in portrait mode

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#4019]
### Version

6.4.2

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When I run video in portrait mode in fullscreen, the subtiles style is constant and does not change even after I apply subtitleStyle.
![ImportedPhoto_1721284767854](https://github.com/user-attachments/assets/1aadfd76-697c-471c-9c55-1271f2b7a101)

### Reproduction

repository link

### Reproduction

run the basic app from example in portrait mode and subtitle with default style will be seen where fontsize not consistent.

**Comment by freeboub** [comment]
This issue is reproduced on the sample

**Comment by johanndeswardt** [comment]
We are also seeing this issue.

**Comment by freeboub** [comment]
This is a regression coming from this change: https://github.com/TheWidlarzGroup/react-native-video/pull/3830

**Comment by freeboub** [comment]
Will be fixed in next release

**Comment by freeboub** [comment]
6.5.0 has been released
