### ISSUE TITLE
Linking does not work

### ISSUE THREAD

**Issue by mxmtsk** [TheWidlarzGroup/react-native-video#402]
Hey,

I've tried several methods to link the module (react-native link, rnpm link, react-native install) but I'm still getting the "_Cannot read property 'Constants' of undefined_". 

Is there another way to troubleshoot this or other solutions?

**Comment by bsiddiqui** [comment]
@mxmtsk after you run `react-native link react-native-video` go to your app target in xcode

Build Phase -> Link Binary With Libraries 
Check and make sure there's a house next to libRCTVideo.a
<img width="400" alt="screenshot 2016-12-16 11 14 44" src="https://cloud.githubusercontent.com/assets/2721959/21275278/e83c7958-c380-11e6-86a7-92d165a7b4e6.png">

See how all of the packages above have a house except libPods-ramble.a? If your libRCTVideo.a doesn't have a house, then that means it's not linked properly.

Select it and delete. Then drag the file back into this list from Libraries -> RCTVideo.xcodeproj -> Products -> libRCTVideo.a

**Comment by xiaoyangzi** [comment]
you have to link the .a manually if your project has more than one target, the react native link can help you link only one target .  
select one target in 'General' scroll to 'Linked Frameworks and Libraries' and make sure the libRCTViedo.a is on the list(maybe the libRNFS.a is also needed). if not just click the add button to link the .a then check another one.
<img width="873" alt="github issue react native video 402" src="https://cloud.githubusercontent.com/assets/6845793/21488862/6b2693c0-cc1f-11e6-957e-bd47ac4e77b4.png">
hope it will work.

**Comment by ghost** [comment]
@mxmtsk can this be closed?

**Comment by mxmtsk** [comment]
@jhabdas  yes sorry!

**Comment by arash-hacker** [comment]
-1 when using `react-native link` it shows an error like this ![screen shot - - at](https://user-images.githubusercontent.com/6451804/37159265-a3a45e0e-2302-11e8-8a01-a101b2a863ac.png)

-2 and when i want add libRCTvidoe.a, it doesn't apear in linkages so let start hacking :)

i cloned project and use libRCTvideo.a in project , droped to my project and walla.. now librctvideo apears and i added to my project and it worked !
