### ISSUE TITLE
[Feature]: Support for VPAID in IMA

### ISSUE THREAD

**Issue by YoungYanchi** [TheWidlarzGroup/react-native-video#4021]
### Description

Now if you connect in addTagUrl a link that returns VAST or VPAID, in onReceiveAdEvent comes an error - 'player does not support this type of ads', when the ad service returns only VAST, everything works fine. VPAID ads are more effective and there are more of them than VAST ads, any thoughts on implementing VPAID support in the library? 

### Why it is needed ?

VPAID ads are more effective and there are more of them than VAST ads

### Possible implementation

I'm still in the information-gathering phase

### Code sample

-

**Comment by freeboub** [comment]
I am afraid that exoplayer/ ima sdk don't support it : https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/compatibility?hl=fr

**Comment by YoungYanchi** [comment]
> I am afraid that exoplayer/ ima sdk don't support it : https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/compatibility?hl=fr

Oh, really. And what could be the reason why this type of ads are not added to ios and android?

**Comment by freeboub** [comment]
No idea... You should ask on google github to push them to integrate it ...
