### ISSUE TITLE
[BUG]: PIP player gets destroyed when navigating away from Video player screen

### ISSUE THREAD

**Issue by nick-mccomb-easygo** [TheWidlarzGroup/react-native-video#4024]
### Version

6.4.2

### What platforms are you having the problem on?

iOS, Android

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device: iPhone 15 Pro Max

### Architecture

Old architecture

### What happened?

The PIP player gets destroyed when navigating away from the screen it is in.  I have tried so many solutions:

1. `detachInactiveScreens={false}` on `Stack.Navigator`
2. `detachPreviousScreen: false` on every `Stack.Screen`
3. Instead of `navigation.goBack` i've tried `navigation.navigate('PreviousScreen')`
4. Using [react-native-portalize](https://github.com/jeremybarbet/react-native-portalize)

None of the above stops the PIP from being destroyed when navigating away from the screen the `Video` component is on.

The only way i've found is moving the screen the `Video` is on outside of `React Navigation` so that it never gets destroyed, but this is a pretty bad solution imo (can't pass props to it)

Does anyone know how to fix the issue of PIP being unmounted when navigating away from the screen?

I expect to navigate away from the screen the Video player is on, with PIP showing, and not have the PIP view destroyed.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

1. Navigate to video screen: `navigation.navigate('VideoScreen')`
2. Activate PIP
3. Navigate away from video screen: `navigation.goBack()`

**Comment by gkueny** [comment]
Hi @nick-mccomb-easygo , 

I will let @freeboub & @KrzysztofMoch  give their insight, but for me this is a feature request. See https://github.com/TheWidlarzGroup/react-native-video/pull/3385#issuecomment-2242352448

I'm not sure it possible to refactor this lib to allow keep video instance when `<Video />`component is unmounted. It will required a lot of work.

However you can implement this feature with a global `<Video />` instance that will not be destroyed on navigation.

**Comment by freeboub** [comment]
@gkueny I was able to implement what you are describing in my past project.
I declared the <Video component on top of Navigation.Stack.
I means that My Video component was always displayed over the navigation elements, then It make the Video always visible. 
I created a context to be able to move / access to it from everywhere in the product.
Let me know if it is clear ?
Regarding to the android pip PR, it was the initial reason why it was merged. The pip belongs to an Activity not a Video. In my mind the pip for android shall be managed for the whole app (Activity). But It should be merged soon, as for connivence it is easier to manage it from react-native-video package. (moreover testing feedbacks looks good)

**Comment by gkueny** [comment]
@freeboub I can confirm we implement like you did on our side

**Comment by KrzysztofMoch** [comment]
I think we can close this one, as this is not an issue

**Comment by YangJonghun** [comment]
@nick-mccomb-easygo 
- https://reactnavigation.org/docs/7.x/shared-element-transitions/
- https://github.com/IjzerenHein/react-navigation-shared-element

I hope you check above approaches.
However, I am not aware of any internal implementations of these approaches.
(If they do unmount internally, it's hard to apply them to Video).
Hope it works for you.
