### ISSUE TITLE
[BUG]: Metadata mismatch on source change

### ISSUE THREAD

**Issue by blazlew** [TheWidlarzGroup/react-native-video#4032]
### Version

6.4.2

### What platforms are you having the problem on?

iOS

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When changing the video source, the metadata shown in the notification center tend to freeze.
On some occasion it was noticed that metadata updated properly then immediately updated again to the one from previous source.

### Reproduction

1. play a video with metadata (title, artwork)
1. move the app into background observing metadata in the notification center
1. swap video source to different one until issue happens (just a few swaps are enough)

**Comment by KrzysztofMoch** [comment]
Fix will be released in `6.4.4`
