### ISSUE TITLE
Anyone was able to play video from internet URL successfully? 

### ISSUE THREAD

**Issue by wandonye** [TheWidlarzGroup/react-native-video#404]
I tried in my own app, didn't work. Then I simply replaced "broadchurch" in the example with
http://techslides.com/demos/sample-videos/small.mp4

No video was shown. 
Does that mean, react-native-video cannot play video from URL or am I doing it in a wrong way?

Thanks~

**Comment by wandonye** [comment]
Weird. If I rerun with react-native run-ios, the video did show up. Previously I was just doing Control-R.

**Comment by hellogerard** [comment]
Should be closed as dupe of #275. iOS by default prevents access to non-secure remote URLs. You have to configure your project in Xcode to allow.
