### ISSUE TITLE
[BUG]: Changing resize mode to cover causing subtitles crop from bottom.

### ISSUE THREAD

**Issue by rahulnainwalttn** [TheWidlarzGroup/react-native-video#4043]
### Version

6.1.1

### What platforms are you having the problem on?

iOS, Android

### System Version

android 13, ios 15

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: play any video with subtitles and try to change resize mode to cover.

**Comment by KrzysztofMoch** [comment]
On android should be fixed by https://github.com/TheWidlarzGroup/react-native-video/pull/3914

**Comment by KrzysztofMoch** [comment]
I will check iOS but It can be that this will be not possible to fix it :/

**Comment by rahulnainwalttn** [comment]
Is it possible to return a subtitle string to the React Native side and render it in React Native? Using an event like onProgress?

**Comment by KrzysztofMoch** [comment]
Yes you have [`onTextTrackDataChanged`](https://thewidlarzgroup.github.io/react-native-video/component/events#ontexttrackdatachanged) that should work on both platforms

**Comment by rahulnainwalttn** [comment]
We are not using external subtitle files.

**Comment by Khafaga39** [comment]
my react-native version is  "0.74.0", and wanted to add subtitle in video, it worked in ios perfectly but in android not, what should i add @rahulnainwalttn 
     textTracks={[
                  {
                    title: 'English CC',
                    language: 'en',
                    type: 'text/vtt',                
                    //  uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
                  },
                ]}
                selectedTextTrack={{
                  type: showFullScreen ? 'title' : 'disabled',
                  value: showFullScreen ? 'English CC' : '',
                }}

**Comment by freeboub** [comment]
I confirm this is no more reproduce since: https://github.com/TheWidlarzGroup/react-native-video/pull/3830

**Comment by freeboub** [comment]
Please see last merged PR. The proposed change was causing a regression, the original behavior has been restored, so in next release you will have to add a prop to configure it.
