### ISSUE TITLE
[BUG]: Setting textTracks to empty array when playing a mp3 file in videoplayer breaks the player in example/basic

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#4044]
### Version

6.4.3

### What platforms are you having the problem on?

iOS

### System Version

17.4

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

Likely also happens on real devices.

Supply prop `textTracks={[]}`and an mp3 for the source uri, and watch the player behave innapropriately. In my app, I was onProgress was getting called with currentTime equal to the end of the video (on 6.4.2), in the videoplayer example/basic an error was logged and the app navigated back to the first source, and in a sample app I made with expo it seemed to load forever. 

What I would expect to happen is either:
1. The error is caught in js and gets propagated to the user and we see a stacktrace of an error like "mp3 doesn't allow textTracks"
2. RNV's Video player silently ignores texttracks when mp3 is used
And probably:
3. A note in the documentation about not setting textTracks on audio uri's (though mp4a's are handled just fine by iOS with subtitles)

Other notes:
One can supply textTracks={[]} with a source of a mp4a uri and this inappropriate behavior doesn't occur.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
Edit `example/basic`'s `src/constants/general.ts` `srcAllPlatformList` to include:
```
  {
    description: 'mp3 with texttrack',
    uri: 'https://traffic.libsyn.com/democracynow/wx2024-0702_SOT_DeadCalm-LucileSmith-FULL-V2.mxf-audio.mp3', // an mp3 file, necessary for reproduction
    textTracks: [] // necessary for reproduction
  },
```
Navigate to the video, observe:
 LOG  {"error":{"domain":"AVFoundationErrorDomain","localizedFailureReason":"This media format is not supported.","localizedDescription":"Cannot Open","code":-11828,"localizedRecoverySuggestion":""},"target":3}

**Comment by paulrinaldi** [comment]
Solution I'm using right now is to provide `textTracks={undefined}` i.e. not defined textTracks when I'm about to show an audio only AV item.

**Comment by KrzysztofMoch** [comment]
@moskalakamil can you look into it ?

**Comment by moskalakamil** [comment]
Sure! I will take a look this week

**Comment by moskalakamil** [comment]
Hmm, I tried to reproduce this, but i didn't get any error. Can you create a repository or a simple component which trigger the error, please?

**Comment by freeboub** [comment]
@moskalakamil It can be reproduced with the sample app easily ...

**Comment by moskalakamil** [comment]
so idk why i didn't get any error then, great that it is fixed now!

**Comment by freeboub** [comment]
@moskalakamil I just added following code in the source list of the sample app:

  ```
 {
    description: 'mp3 with texttrack',
    uri: 'https://traffic.libsyn.com/democracynow/wx2024-0702_SOT_DeadCalm-LucileSmith-FULL-V2.mxf-audio.mp3', // an mp3 file
    textTracks: [], // empty text track list
  },
``` 

It was working fine on android, not on ios (content is not player, it directly go to the next content, not use it produce an error)
