### ISSUE TITLE
[BUG]: Black screen on Android until video fully loaded

### ISSUE THREAD

**Issue by forchello** [TheWidlarzGroup/react-native-video#4045]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

android 12+

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I have a static photo and wanted to add a "live photo". This is a regular mp4 video that is uploaded via a link and activated.

But the problem is that in the latest versions of the library at the moment of "onLoadStart" a black canvas is called, which is shown until the video is loaded. I saw shutterColor and hideShutterView in the documentation, but using them doesn't solve the problem.

### Reproduction

Step to reproduce this bug are: 
Just try to loaded video from remote uri: for example https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4

**Comment by freeboub** [comment]
Does renderLoader prop solve your issue ? https://thewidlarzgroup.github.io/react-native-video/component/props#renderloader
BTW, I am not 100% to understand the issue.

**Comment by forchello** [comment]
> Does renderLoader prop solve your issue ? https://thewidlarzgroup.github.io/react-native-video/component/props#renderloader BTW, I am not 100% to understand the issue.

https://github.com/user-attachments/assets/a4fcd74c-000f-4c28-a366-63b6fcb5f33b

I mean this dark layout before the video started. 

This is my code: 

<Video 
source={{
          uri: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
          type: 'mp4',
        }}
        style={{
          width: 400,
          height: 300,
        }}
        repeat
        resizeMode={'cover'}
        rate={1}
        playInBackground={false}
        playWhenInactive={false}
        hideShutterView
        shutterColor="transparent"
        renderLoader={null}
        muted
      />

**Comment by moskalakamil** [comment]
Hi @forchello, I'm working on fix that issue - i will keep you updated

**Comment by forchello** [comment]
> Hi @forchello, I'm working on fix that issue - i will keep you updated

Thanks a lot! 

I also noticed that when I use screen video and call modalfy ( react-native-modalfy ) with the same video, I see the screen video on modal ( with dimensions from the screen ). This goes on for a few seconds. When I close the modal, the opposite situation happens

**Comment by moskalakamil** [comment]
Sure, can you describe this in next issue, please?

**Comment by forchello** [comment]
Of course, I'll also attach a video to familiarize you with the problem.

**Comment by forchello** [comment]
> Sure, can you describe this in next issue, please?

I described and demonstrated the problem here: https://github.com/TheWidlarzGroup/react-native-video/issues/4051

**Comment by kavinder123** [comment]
still facing the same issue as i scroll up to load any other video it will first show black screen after that video will play. Please help if any one have any solution regarding this issue.

**Comment by forchello** [comment]
> still facing the same issue as i scroll up to load any other video it will first show black screen after that video will play. Please help if any one have any solution regarding this issue.

now I have a temporary solution: make a wrapper for the video, give the video opacity: 0, and after calling onLoad give the video opacity: 1

P.S. use it for android only, because ios works fine

**Comment by CMLCNL** [comment]
any update for this issue?

**Comment by hohoaisan** [comment]
Although `hideShutterView` is true, the issue is still persist in`"react-native-video": "^6.6.3"`
Have to use workaround by setting Video opacity

PR https://github.com/TheWidlarzGroup/react-native-video/pull/4060

Released log https://github.com/TheWidlarzGroup/react-native-video/releases#:~:text=hide%20surfaceView%20for%20loading%20time

**Comment by pedroscaff** [comment]
I could still reproduce the issue on version 6.16.1, black screen flashes when `hideShutterView` is true.
I could only get it working using the opacity trick combined with `onLoad`. Let me know if I should provide more information but reproduction step should be the same as already described in the thread.

**Comment by rahulnainwalttn** [comment]
Facing the same in 6.16.1
