### ISSUE TITLE
[Feature]: Mute as a method

### ISSUE THREAD

**Issue by maksymhcode-care** [TheWidlarzGroup/react-native-video#4046]
### Description

Any plans to add mute as a method accessible in ref just like we have for pause, resume, seek, etc?

### Why it is needed ?

In my project i updated my pause/play function to only use methods instead of passing property as a props to Video component, wich helps me to prevent unnecessary re-renders.

**Comment by seyedmostafahasani** [comment]
@maksymhcode-care you can use this [method](https://thewidlarzgroup.github.io/react-native-video/component/methods#setvolume).

**Comment by maksymhcode-care** [comment]
> @maksymhcode-care you can use this [method](https://thewidlarzgroup.github.io/react-native-video/component/methods#setvolume).

Thanks
