### ISSUE TITLE
RN 0.39-rc-0 on android trhow Element type is invalid: expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by jbisson** [TheWidlarzGroup/react-native-video#405]
Not sure if it's RN 0.39 related but I can't get this component to work. Pretty simple snippet:

import {Video} from 'react-native-video';
export default class PlayVideoPage extends Component {
    render() {
     return (
            <View style={{flex:1}}>
                <Video
                    repeat
                    resizeMode='cover'
                    source={require('../broadchurch.mp4')}
                    style={styles.backgroundVideo}
                />
                </View>
        );
    }
}
const styles = StyleSheet.create({
    backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
});

12-04 20:52:51.335 31953   592 E ReactNativeJS: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render
 method of `PlayVideoPage`.

**Comment by nschoen** [comment]
Please wrap your code in \`\`\` for better readability.

Try replacing ```import {Video} from 'react-native-video';``` by ```import Video from 'react-native-video';```

**What is the problem?**
The error message says the render method contains a component with the type undefined. The render method's only element is ```<Video />```. Therefor Video should be the element which is ```undefined```. Let's have a look at the import and there we see that it is not imported correctly. You can have a look here to find out the difference if you don't already know it: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/import

**Comment by jbisson** [comment]
thanks, that worked,
