### ISSUE TITLE
[BUG]: getCurrentPosition doesn't return floating point, fix suggested

### ISSUE THREAD

**Issue by CandidlyRed** [TheWidlarzGroup/react-native-video#4052]
### Version

0.6.3

### What platforms are you having the problem on?

Android

### System Version

android 12+

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

On testing getCurrentPosition() in android, a value that returns for example: 1.99 in ios, returns just 1 for android devices.

Suggested fix is below:
in react-native-video/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
change
```
public void getCurrentPosition(Promise promise) {
        if (player != null) {
            double currentPosition = player.getCurrentPosition() / 1000;
            promise.resolve(currentPosition);
        } else {
            promise.reject("PLAYER_NOT_AVAILABLE", "Player is not initialized.");
        }
    }
```
to
```
public void getCurrentPosition(Promise promise) {
        if (player != null) {
            double currentPosition = player.getCurrentPosition() / 1000.0;
            promise.resolve(currentPosition);
        } else {
            promise.reject("PLAYER_NOT_AVAILABLE", "Player is not initialized.");
        }
    }
```

This fixed my issue, apologies for the poor formatting. Hope this helps!

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

call getCurrentPosition() on any video ref in an android device

**Comment by freeboub** [comment]
Can you open a pull request with that change please? Should be fast and easy to integrate.
Thank you

**Comment by maksymhcode-care** [comment]
#3960 just like the issue i described here

**Comment by seyedmostafahasani** [comment]
@freeboub I opened a PR for this issue.

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch 
We can close this issue after releasing the new version.

**Comment by seyedmostafahasani** [comment]
@CandidlyRed 
Please test with the latest version.

**Comment by freeboub** [comment]
should be OK now, let's close this issue. I will reopen if needed
