### ISSUE TITLE
[BUG]: Attempting to have more than one video playing at once doesn't work in Android

### ISSUE THREAD

**Issue by CandidlyRed** [TheWidlarzGroup/react-native-video#4053]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

android 12+

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When trying to render two videos at once, only the first plays. The second video doesn't play or load.

Expected behavior: both videos can play simultaneously. Was wondering if there was a fix or workaround?

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
`
<Video
    ref={videoRef1}
    source={{ uri: url1 }}
    style={{ position: 'absolute', width: width, height: 0.5*height }}
    resizeMode="cover"
    repeat={false}
  />
<Video
  ref={videoRef2}
  source={{ uri: url2 }}
  style={{ position: 'absolute', width: width, height: 0.5*height, top: 0.5*height }}
  resizeMode="cover"
  repeat={false}
/>
`
Just have 2 videos rendered at the same time on android.

**Comment by freeboub** [comment]
Your issue is linked to audio focus management. Please check that!

**Comment by CandidlyRed** [comment]
Thank you very much!
