### ISSUE TITLE
[BUG]: Kotlin warnings with :react-native-video:compileDebugKotlin task

### ISSUE THREAD

**Issue by VMBindraban** [TheWidlarzGroup/react-native-video#4057]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

Mac

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

The `:react-native-video:compileDebugKotlin` task is giving some warnings:

`react-native-video/android/src/main/java/com/brentvatne/common/api/ResizeMode.kt:45:5 This annotation is deprecated in Kotlin. Use '@kotlin.annotation.Retention' instead`

`react-native-video/android/src/main/java/com/brentvatne/common/react/VideoEventEmitter.kt:212:64 Parameter 'i' is never used, could be renamed to _`

`react-native-video/android/src/main/java/com/brentvatne/common/react/VideoEventEmitter.kt:306:43 Parameter 'i' is never used, could be renamed to _`

`react-native-video/android/src/main/java/com/brentvatne/exoplayer/FullScreenPlayerView.kt:64:15 'onBackPressed(): Unit' is deprecated. Deprecated in Java`

`react-native-video/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt:45:45 Parameter 'tolerance' is never used`

### Reproduction

Run `react-native-video:compileDebugKotlin` task

**Comment by KrzysztofMoch** [comment]
Did your build failed or is just gives warnings ?

**Comment by VMBindraban** [comment]
> Did your build failed or is just gives warnings ?

Only warning. It builds just fine.

**Comment by KrzysztofMoch** [comment]
- [x] fix by #4058 
  - `react-native-video/android/src/main/java/com/brentvatne/common/api/ResizeMode.kt:45:5 This annotation is deprecated in Kotlin. Use '@kotlin.annotation.Retention' instead` - 
   -  `react-native-video/android/src/main/java/com/brentvatne/common/react/VideoEventEmitter.kt:212:64 Parameter 'i' is never used, could be renamed to _`
  -  `react-native-video/android/src/main/java/com/brentvatne/common/react/VideoEventEmitter.kt:306:43 Parameter 'i' is never used, could be renamed to _`
  - `react-native-video/android/src/main/java/com/brentvatne/react/VideoManagerModule.kt:45:45 Parameter 'tolerance' is never used`

- [ ]  fix by #4049 
  - `react-native-video/android/src/main/java/com/brentvatne/exoplayer/FullScreenPlayerView.kt:64:15 'onBackPressed(): Unit' is deprecated. Deprecated in Java` -

**Comment by freeboub** [comment]
Linked prs are merged, can be closed
