### ISSUE TITLE
[BUG]: get blank screen in ios while playing video

### ISSUE THREAD

**Issue by kavinder123** [TheWidlarzGroup/react-native-video#4059]
### Version

5.2.1

### What platforms are you having the problem on?

iOS

### System Version

ios-13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When ever we try to load the video, first it show a blank screen after that video will load, as i scroll the screen try to play any other video again it will show blank screen again. 

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
When we upload the video it show blank screen, after that refresh the screen or scroll up or down to play another video. Again it will first show blank screen.

**Comment by RohanBhadke** [comment]
same problem with me

**Comment by KrzysztofMoch** [comment]
Can you please check on `6.4.3` - `5.x` version is deprecated and will not receive more support

**Comment by freeboub** [comment]
issue on 5.2, no feedback, let's close this issue.
