### ISSUE TITLE
[BUG]: iOS: After seeking in notification progress bar while AV is paused, plays (in examples/basic on latest and my app on 6.4.3)

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#4064]
### Version

6.4.3

### What platforms are you having the problem on?

iOS

### System Version

17.5

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Not sure if this should be the behavior but this does differ from Android so I posted as a bug. Since you cannot test notification controls on a simulator, this isn't reproducible on a simulator.

### Reproduction

Step to reproduce this bug are: 
1. `git apply` the patch to the react-native-video library
[iosAfterSeekUnpause.patch](https://github.com/user-attachments/files/16515247/iosAfterSeekUnpause.patch)
2. Open the player (on a physical device)
3. Navigate to any video
4. Scroll down the notification media controls
5. Pause the player (tap the icon)
6. Drag the progress bar and release

Actual:
7. The player unpauses 

Expected:
7. The player remains paused

Build steps if needed:
1. Cd to `examples/basic` and build the videoplayer with `yarn run ios`
2. Open xcode and create a distributable debugging ipa file of the videoplayer project (Product > Archive ... etc.)
3. Upload to browserstack or release to your iOS device

**Comment by moskalakamil** [comment]
Thanks for reporting the issue! This is an issue in example app, right? I think that it can be default iOS behaviour that video unpauses after seeking, and the missing element is that we do not update isPaused state after that - am I right?

**Comment by paulrinaldi** [comment]
Rather, the problem in my eyes is that the progress bar on iOS should
remain in the state it was in after someone seemed in it.

**Comment by moskalakamil** [comment]
Sure, but if it's default iOS behaviour, we shouldn't change it

**Comment by paulrinaldi** [comment]
I do not know if it is iOS's preferred behavior but I do see a .play() getting called nearby the position target:
https://github.com/TheWidlarzGroup/react-native-video/blob/master/ios/Video/NowPlayingInfoCenterManager.swift#L171

This is not default behavior then. And I think we could remove that closure.

See https://chatgpt.com/share/5be5afb2-3b7c-47fb-adb5-12782d4d667b for more details.

**Comment by paulrinaldi** [comment]
I've observed this changes effect on a build of the videoplayer and it solves this issue.

**Comment by paulrinaldi** [comment]
Solved and released in 6.4.4
