### ISSUE TITLE
[BUG]: Video stops playing when loading new videos

### ISSUE THREAD

**Issue by markotrifunovic135** [TheWidlarzGroup/react-native-video#4066]
### Version

6.4.2

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I have a flastlist of videos and when i scroll to the end i am watching a video while new videos are loading with pagination, as soon as the new video gets mounted the last one before pagination stops, why?

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: Load new videos while a current video is playing

**Comment by seyedmostafahasani** [comment]
You can use this prop to handle it: `paused={pauseValue}`, with the default value being `true`. You have two ways to implement it. The first way is to play the video when the user presses it. The second way is to play the video when the user scrolls the list and the item enters a specific position on the screen.

I think you can use these props in flatlist for the second way: `viewabilityConfig ` and `onViewableItemsChanged `.

**Comment by markotrifunovic135** [comment]
I have those viewbaility props implemented and they work the issue is on android when i watching the last video in feed and i call new set of data, the last video stops and wont play until i press on it or scroll it out of view and back into it. Please help

**Comment by seyedmostafahasani** [comment]
Could you please create a simple repository and share your code here?

**Comment by freeboub** [comment]
@markotrifunovic135 Did you check to audio focus management: https://thewidlarzgroup.github.io/react-native-video/component/props#disablefocus

**Comment by markotrifunovic135** [comment]
yes that helped me thanks
