### ISSUE TITLE
[BUG]: URL is working in browser but not in React-Native-Video

### ISSUE THREAD

**Issue by manglesh-0605** [TheWidlarzGroup/react-native-video#4070]
### Version

5.2.1

### What platforms are you having the problem on?

Android

### System Version

Latest

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I have videos hosted over a CDN and they provide a URL to play elsewhere in this format "https://c.themediacdn.com/embed/media/WZsBnS/y4WmJlfTsXX/InMkAYsc1ST_1?preview=1"  this URL is working fine in the browser but when trying to pass this in the URL in react native video  it does not play

### Reproduction

repository link

### Reproduction

Steps to reproduce this bug are: 1. pass this in URI parameter of react-native-video an it will not load. paste it directly in the browser and it will play

**Comment by VMBindraban** [comment]
That is because that isn't a video.

The page tries to load this blob within a HTML video element:
```html
blob:https://c.themediacdn.com/aa92f7ec-78b0-4152-8ac4-cf830d3da3a4
```

**Comment by manglesh-0605** [comment]
Hey @VMBindraban, Thank You for your response. How can I make this work In my react native application? This URL is from a CDN

**Comment by freeboub** [comment]
@manglesh-0605 use react-native-webview to display a web page ...
