### ISSUE TITLE
[BUG]: Resizing Issue with FlashList on Android

### ISSUE THREAD

**Issue by Honggilseong** [TheWidlarzGroup/react-native-video#4071]
### Version

6.4.3

### What platforms are you having the problem on?

Android 13

### System Version

android

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I am currently using FlashList with videos for an infinite scrolling video list on Android. After updating to version 6.4.3, I encountered a strange issue where the resizing of the video cover exceeds the fixed container size. This problem did not occur in the previous version 6.2.0.

Looking at the release logs, it seems that there were some changes related to resizing in version 6.4.3. However, these changes appear to cause issues specifically with infinite scrolling video lists.

Could you please investigate this issue?

### Reproduction

repository link

### Reproduction

Set up a FlashList component with infinite scrolling containing video items on an Android device.
Use version 6.4.3.
Ensure that the video covers are set to resize with a fixed container size.
Scroll through the list to observe the resizing behavior.

**Comment by florian-deroo** [comment]
Same issue how did you fixed it ?

**Comment by efstathiosntonas** [comment]
Did anyone found a fix for this? It still exists on 6.9.1, the module is unusable with Flashlist.  @freeboub @KrzysztofMoch
