### ISSUE TITLE
[BUG]: Video player stutters when streaming HD 60fps video on real iOS device

### ISSUE THREAD

**Issue by stalteri** [TheWidlarzGroup/react-native-video#4073]
### Version

6.1.2

### What platforms are you having the problem on?

iOS

### System Version

17

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

When streaming HD video at 60fps, the video player exhibits stuttering and playback issues on a real iOS device. However, the same stream plays smoothly on an iOS simulator. Notably, streams from a phone at 30fps are played correctly on both the real device and the simulator. This issue seems to be specific to high-frame-rate streams on physical iOS devices.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: play 60fps live stream on real IOS device

**Comment by moskalakamil** [comment]
Hi! Thanks for reporting an issue!

**Comment by moskalakamil** [comment]
Hey @stalteri, did you manage to resolve the problem? If so, could you please share the solution or any insights you gained? This could be really helpful for others who might be facing the same issue.

**Comment by stalteri** [comment]
Hey @moskalakamil, yes, the issue has been resolved by switching to a different video player (https://github.com/razorRun/react-native-vlc-media-player). It turns out the problem wasn't specifically related to the 60fps but was instead tied to streaming from the DJI drone. Streams at 60fps from other phones work fine, but the stream from the drone was stuttering. The new player handles the stream without any stuttering.

**Comment by freeboub** [comment]
Quick note, this library doesn't seem to be maintained... Ping @Okelm for info

**Comment by stalteri** [comment]
> Quick note, this library doesn't seem to be maintained... Ping @Okelm for info

I’m aware of that, and I’ll keep testing this package with new updates regularly in hopes that the issue gets resolved. Just to note, the problem is still present in the latest (6.4.3) version as well.

**Comment by freeboub** [comment]
> > Quick note, this library doesn't seem to be maintained... Ping @Okelm for info
> 
> I’m aware of that, and I’ll keep testing this package with new updates regularly in hopes that the issue gets resolved. Just to note, the problem is still present in the latest (6.4.3) version as well.

Yep, I suspect something linked to avplayer... VLC uses its own decoder so it doesn't use avplayer standard implementation ...
