### ISSUE TITLE
[BUG]: controls are showing on fullscreen when controls=false

### ISSUE THREAD

**Issue by Tech2cool** [TheWidlarzGroup/react-native-video#4075]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

android 11

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened!
default controls are showing on fullscreen when controls=false
this issue on from 6.3.0 to latest 6.4.3 version of react-native-video, using in bare react native
its fine in 6.2.0  version of react-native-video

im using custom controls which works fine, when i upgrade to newer  version of react-native-video from 6.2.0 to any higher there is issue on fullscreen mode even if controls are set to false all time

### Reproduction

repository link 

### Reproduction

Step to reproduce this bug are: 
on from 6.3.0 to 
latest 6.4.3 version of react-native-video in bare react native (dont know about expo),
fullscreen = true
controls=false
with custom controls also without custom controls
![bug-fullscreen-controls-when-controls-false](https://github.com/user-attachments/assets/40222880-ccfd-438e-88bc-9c3bbdf8ac36)
![fullscreen-proper-6-2-0-same-setting](https://github.com/user-attachments/assets/ece88922-fbb9-4ded-987d-66ce2ae1abcc)

**Comment by seyedmostafahasani** [comment]
@Tech2cool 
Please see my comment [here](https://github.com/TheWidlarzGroup/react-native-video/issues/4055#issuecomment-2271949973).

**Comment by KrzysztofMoch** [comment]
It's limitation we cannot disable controls in fullscreen

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch 
We can close this issue.
