### ISSUE TITLE
[BUG]: EXC_BREAKPOINT superview (RCTVideo.handleViewControllerOverlayViewFrameChange(RCTVideo.swift:1551))

### ISSUE THREAD

**Issue by ngima** [TheWidlarzGroup/react-native-video#4081]
### Version

v6.2.0

### What platforms are you having the problem on?

iOS

### System Version

mostly v17.5.1, also v16.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Getting Sentry error for iOS

EXC_BREAKPOINT
Level: Fatal
Unhandled
superview

`RCTVideo.handleViewControllerOverlayViewFrameChange(RCTVideo.swift:1551)`

in `react-native-video v6.2.0`

Screenshot:
![image](https://github.com/user-attachments/assets/107248e1-df9c-4c3e-b382-cee33a0927e1)

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
I have not been able to reproduce it myself but I have been getting it since I upgraded from v6.1.1 to v6.2.0

**Comment by ngima** [comment]
Could be related to https://github.com/TheWidlarzGroup/react-native-video/issues/3889

**Comment by moskalakamil** [comment]
Hi, thanks for reporting issue!

**Comment by ngima** [comment]
@moskalakamil you're welcome,

Thanks for the response

do you think it's something that could have fixed in the latest versions? Or it's still need to be fixed?

If not sure, I will upgrade to the latest version v6.4.5 and wait for the crashlytics.

**Comment by ngima** [comment]
@moskalakamil 

Interesting finding,

I upgraded the app to latest but now I have a weird bug in Android.

I have custom control implementation and I am leveraging following functions to going to fullScreenMode but with my custom controls overlays.

```
videoRef.current?.setFullScreen(true) // in new version
videoRef.current?.presentFullscreenPlayer() // in old version
```

After the change when going to full screen now I get it with full screen without my overlays (seems like it's not possible anymore like in iOS) but with default player controls.

Is it a bug or we're now trying to support fullscreen mode by default within `react-native-video` ?

**Comment by seyedmostafahasani** [comment]
> @moskalakamil
> 
> Interesting finding,
> 
> I upgraded the app to latest but now I have a weird bug in Android.
> 
> I have custom control implementation and I am leveraging following functions to going to fullScreenMode but with my custom controls overlays.
> 
> ```
> videoRef.current?.setFullScreen(true) // in new version
> videoRef.current?.presentFullscreenPlayer() // in old version
> ```
> 
> After the change when going to full screen now I get it with full screen without my overlays (seems like it's not possible anymore like in iOS) but with default player controls.
> 
> Is it a bug or we're now trying to support fullscreen mode by default within `react-native-video` ?

Please see my comment [here](https://github.com/TheWidlarzGroup/react-native-video/issues/4055#issuecomment-2271949973).
