### ISSUE TITLE
[BUG]: Invisible video on screen capture

### ISSUE THREAD

**Issue by VMBindraban** [TheWidlarzGroup/react-native-video#4082]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

7.1.2

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

When trying to make a screenshot of the screen the video stays invisible. Other elements are visible e.g. images and webviews.
`PixelCopy.request` works but only on android 8 or higher. 
We are unable to upgrade certain devices to 8 (🙄) and there is no user interaction.

I tried making a screenshot using `Canvas`:

```kotlin
              val rootView = activity.window.decorView.rootView
              val originalBitmap = Bitmap.createBitmap(rootView.width, rootView.height, Bitmap.Config.ARGB_8888)

                rootView.post {
                    try {
                        rootView.measure(
                            View.MeasureSpec.makeMeasureSpec(rootView.width, View.MeasureSpec.EXACTLY),
                            View.MeasureSpec.makeMeasureSpec(rootView.height, View.MeasureSpec.EXACTLY)
                        )
                        rootView.layout(0, 0, rootView.measuredWidth, rootView.measuredHeight)
                        val canvas = Canvas(originalBitmap)
                        rootView.draw(canvas)
                        processBitmap(originalBitmap, width, height, promise)
                        originalBitmap.recycle()
                    } catch (e: Exception) {
                        promise.reject("E_NATIVE_CAPTURE_FAILED", e)
                        originalBitmap.recycle()
                    }
                }
```

Code that renders the video:

```html
    <Video
      source={{ uri: `file://${baseDir}/${fileName}` }}
      repeat={true}
      disableFocus={true}
      resizeMode={ResizeMode.COVER}
      useTextureView={true}
    />
```

Rendering the video without `useTextureView` results in a black video in the screenshot and a black screen with the error:

```
hwc-drm-display-compositor: Failed to commit pset ret=-28
hwc-drm-display-compositor: Composite failed for display 1
```

### Reproduction

Try to generate screenshot of the video.

**Comment by moskalakamil** [comment]
Hi, Thanks for reporting the issue!

**Comment by freeboub** [comment]
This is an expected behavior, you must use texture view to handle screenshot.
if you want to clarify the behavior you can also try to use `adb screencap`to double check your screenshot implementation

**Comment by VMBindraban** [comment]
> This is an expected behavior, you must use texture view to handle screenshot. if you want to clarify the behavior you can also try to use `adb screencap`to double check your screenshot implementation

The implementation works with screencap. Since this issue is only on android 7 and lower (our devices are rooted we can use `screencap`) this shouldn't be a problem. For android 8 and higher `PixelCopy` works great.

I doubt there are many android < 7 devices still active (< 1.3% worldwide)
