### ISSUE TITLE
[BUG]: In version 6.4.3 paused , mute nothing working controls are showing working but property like mute are not working

### ISSUE THREAD

**Issue by rohanthakran** [TheWidlarzGroup/react-native-video#4085]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

node 20.14.0

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

it muted but still sound is coming and paused is true but when it load video stated to play automatically

      {trainingDetails?.training?.all_trainings?.training_files[0]
                ?.file && (
                <Video
                  source={{
                    uri: videoFile,
                  }}
                  volume={1.0}
                  muted={true}
                  paused={true}
                  repeat={true}
                  playInBackground={false}
                  playWhenInactive={false}
                  onLoadStart={() => {
                    console.log('onLoadStart', new Date());
                  }}
                  onLoad={() => {
                    console.log('onLoad', new Date());
                  }}
                />

              )}

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by rohanthakran** [comment]
Sorry i was editing the code on different screen

**Comment by seyedmostafahasani** [comment]
@rohanthakran 
I've tested it, but I couldn't reproduce it.

**Comment by irekrog** [comment]
still issue
