### ISSUE TITLE
[BUG]: Transform rotation doesn't work properly on Android

### ISSUE THREAD

**Issue by anhquan291** [TheWidlarzGroup/react-native-video#4086]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

Version 14.3 

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

Hi guys, first thank you for this amazing library.
I'm facing a UI issue on Android where the transform rotation property doesn't work correctly. Specifically, when applying a rotation transform to an element, the rotation appears either skewed and does not rendered as expected. This problem occurs inconsistently across different Android devices and OS versions.

Do you have any suggestions or potential fixes for this? Thank you so much for your help; it's really appreciated!

![Screenshot_2024-08-14_at_16 05 51](https://github.com/user-attachments/assets/f78d1fd6-56aa-4cf4-ac8e-2fea87d4a4c5)

### Reproduction

repository link

### Reproduction

```
       <Animated.View
            style={{
              width: videoWidth,
              height: videoHeight,
              transform: [{ rotate: '90deg' }],
            }}
          >
            <Video
              source={{ uri: videoUri }}
              paused={paused}
              ref={videoRef}
              onError={onError}
              onLoad={({ naturalSize, duration }) => {
                videoRef.current?.seek(0);
                const { width, height } = naturalSize;
                setVideoWidth(kWidth);
                setVideoHeight((kWidth * height) / width);
              }}
              onEnd={onEndTopic}
              onProgress={onProgress}
              onSeek={onSeek}
              renderLoader={renderLoader}
              style={[layout.fill]}
              resizeMode="contain"
              selectedTextTrack={{
                type: showSubTitle
                  ? SelectedTrackType.LANGUAGE
                  : SelectedTrackType.DISABLED,
                value: 'en',
              }}
              textTracks={[
                {
                  title: 'English CC',
                  language: 'en',
                  type: TextTrackType.VTT, // "text/vtt"
                  uri: 'https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt',
                },
              ]}
            />
        </Animated.View>

**Comment by seyedmostafahasani** [comment]
@anhquan291 
Please use these libraries to handle landscape mode.

- React-Native-Orientation-Locker
- Expo ScreenOrientation

**Comment by anhquan291** [comment]
@seyedmostafahasani Going to try it now. Will let you know if it works. 
Thank you so much

**Comment by quannguyen291** [comment]
Hi @seyedmostafahasani It works after adding this. Thank you so much. Appreciate it!
Close the issue now!
```
   await ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.LANDSCAPE,
      );

**Comment by anhquan291** [comment]
Hi @seyedmostafahasani It works after adding this. Thank you so much. Appreciate it!
Close the issue now!

   await ScreenOrientation.lockAsync(
        ScreenOrientation.OrientationLock.LANDSCAPE,
      );

**Comment by Sagar911-rn** [comment]
> Hi [@seyedmostafahasani](https://github.com/seyedmostafahasani) It works after adding this. Thank you so much. Appreciate it! Close the issue now!
> 
> await ScreenOrientation.lockAsync( ScreenOrientation.OrientationLock.LANDSCAPE, );

React-Native-Orientation-Locker
Expo ScreenOrientation 
this library doesnt work when using the app in android tv help please!
@seyedmostafahasani

**Comment by zohayk** [comment]
The solution is here!

https://github.com/TheWidlarzGroup/react-native-video/issues/4730#issuecomment-3615075092
