### ISSUE TITLE
[BUG] iOS: Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager

### ISSUE THREAD

**Issue by tacianoscur** [TheWidlarzGroup/react-native-video#4087]
### Version

6.4.3

### What platforms are you having the problem on?

iOS

### System Version

17.2

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

I just upgraded from `5.2.1` to `6.4.3` and worked on android, however whenever the app opens on iOS and render a video, it throws the error.

### Reproduction

Step to reproduce this bug are: 
1. Just render a `Video` component

Code:
```
<Video
            paused={!active}
            source={{ uri: video.assetUri || video.url }}
            focusable={false}
            controls
            repeat
            resizeMode="contain"
          />
```

**Comment by freeboub** [comment]
Do you have a log of the issue ?

**Comment by tacianoscur** [comment]
```
 ERROR  Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

This error is located at:
    in RCTVideo (created by Video)
    in RCTView (created by View)
    in View (created by Video)
    in Video (created by Styled(Video))
    in Styled(Video) (created by VideoThumbnail)
    in RCTView (created by View)
    in View (created by Styled(View))
    in Styled(View) (created by VideoThumbnail)
    in RCTView (created by View)
    in View
    in Unknown
    in Unknown (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by Styled(SafeAreaProvider))
    in Styled(SafeAreaProvider) (created by App)
    in _QueryClientProvider (created by _PersistQueryClientProvider)
    in _PersistQueryClientProvider (created by App)
    in Unknown (created by ThemeContextProvider)
    in ThemeContextProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in gymsesh_mobile(RootComponent), js engine: hermes
```

**Comment by tacianoscur** [comment]
@freeboub any workaround for now? we need to publish updates ASAP and this is currently blocking the release

**Comment by tacianoscur** [comment]
same issue with `6.4.3` and `6.4.1`.
am I doing something wrong?

when upgrading from `5.2.1` to `6.4.3` I had to add this to my Podfile to make it work:
```
pod 'SPTPersistentCache', :modular_headers => true
pod 'DVAssetLoaderDelegate', :modular_headers => true
```

not sure if its connected, but it's the only thing i changed in the iOS side after upgrading

**Comment by tacianoscur** [comment]
okay so I have the `min_ios_version_supported` set to 13.0, but looks like that was not enough, I added the code as per [the docs](https://thewidlarzgroup.github.io/react-native-video/updating) and it's working now.

however, I am getting this warning every time I run `pod install`:
```
[!] Automatically assigning platform `iOS` with version `13.0` on target `gymsesh_mobile` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`
```

any way we could make this go away?

**Comment by ngxhuyhoang** [comment]
Same issue

**Comment by freeboub** [comment]
Can you provide a sample reproducing the issue please ?
