### ISSUE TITLE
[BUG]: contentStartTime crashes app on Android 

### ISSUE THREAD

**Issue by sntg-p** [TheWidlarzGroup/react-native-video#4088]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

14

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

If the `contentStartTime` prop is set, the app crashes before firing the  `onLoad` event. Although the `onProgress` event does fire.

The video should start at the time set and the app should not crash.

### Reproduction

To reproduce, just set the `contentStartTime` prop to a numeric value. I'm using the latest RN 0.74.5.

**Comment by moskalakamil** [comment]
Hi man, thanks for reporting the issue!

**Comment by freeboub** [comment]
do you use contentStartTime to manage server side ads ?
I think this flag shall not be used in fact... It is a bit of unsafe hacking ...
It works only on dash for exemple.
Can you explain me why you need to use this flag ?

**Comment by sntg-p** [comment]
Oh, that dash-only thing sounds like something that should be added to the documentation. 

We are using AWS S3 signed URLs as source (HTTP download), which are configured to have a short expiration time. If the user leaves the video paused past the expiration time and then tries to continue its playback, the player errors when it tries to continue buffering as the URL is no longer valid.

At that point, we ask our backend to generate a new signed URL but the problem is that the video starts from the beginning. Using a `videoRef.current.seek()` call to continue where the user left the video kinda works, but you can see the video starting from the beginning and then jumping to where we want to. That's when I found about the `contentStartTime` prop.

**Comment by freeboub** [comment]
Ok, thank you. So I understand you just want to resume playback at a specific point. For that you should use source.startPosition, not contentStartPosition !

**Comment by sntg-p** [comment]
Thanks for the tip, I'll test when I can and comment here with my results!

**Comment by freeboub** [comment]
ping @sntg-p, were you able to fixing your issue ?

**Comment by sntg-p** [comment]
Yes @freeboub, it is working now with `source.startPosition`. Thanks for the help!
