### ISSUE TITLE
[BUG]: [iOS] Video plays for some time, then randomly starts buffering and stalls

### ISSUE THREAD

**Issue by sntg-p** [TheWidlarzGroup/react-native-video#4089]
### Version

6.4.3

### What platforms are you having the problem on?

iOS

### System Version

17.4

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

It seems that while playing a video on iOS (HTTP download, not streamed, signed AWS S3 URL), at some random point it will start throwing these messages in the console:

```
nw_connection_add_timestamp_locked_on_nw_queue [C30] Hit maximum timestamp count, will start dropping events
```

After these messages with different C-values get thrown, it will at some point log this and fire the `onBuffer` event with `isBuffering: true`:

```
{
  "transportType" : "HTTP Progressive Download",
  "mediaType" : "HTTP Progressive Download",
  "BundleID" : "ReactNativeVideoFreezeBug",
  "name" : "MEDIA_PLAYBACK_STALL",
  "interfaceType" : "Wifi"
}
```

When this happens, the user may invoke the seek method and play already buffered segments in which case it will fire the `onBuffer` event twice: first with `isBuffering: false` and then `isBuffering: true`. This double event fire happens again when it reaches the time where it originally threw the `MEDIA_PLAYBACK_STALL` message, which gets thrown again.

The problem does not appear instantly, it seems that it appears after playing some videos. Similar problems occur if the source URL is changed.

### Reproduction

Step to reproduce this bug are:

Just play two or three videos (HTTP download, AWS S3 signed URLs) until the problem appears.

**Comment by moskalakamil** [comment]
Hi! Thank you for reporting the issue, it would be perfect if you could provide an example videos when the error occurs. Thanks!

**Comment by sntg-p** [comment]
https://github.com/user-attachments/assets/8bdc2e92-9a10-4647-b5ee-cc1fd7092f91

Here I have recorded the moment the problem happens, after about 4 minutes of playback.

**Comment by roo12312** [comment]
i can confirm this isssue... even im facing 
```
nw_connection_add_timestamp_locked_on_nw_queue [C5] Hit maximum timestamp count, will start dropping events
```
probably this is the reason for #3675

**Comment by roo12312** [comment]
also, this problem occurs in certain videos...

**Comment by moskalakamil** [comment]
Hi @sntg-p, do you use DRM for video? This error is not for every video, so it would be perfect if you could you provide a sample

**Comment by sntg-p** [comment]
Hey @moskalakamil, we are currently not using DRM for video.

I was cleaning my sample repo and added a video with long expiration time to share it with you but since updating to RNV to v6.4.5 the video no longer freezes. After this finding I updated it in our app, and again it seems like it works.

It's late here so tomorrow I'll be checking with my team to see if they still have issues on their devices or if we can close this.

**Comment by moskalakamil** [comment]
Sure, thanks for answering. Please let us know after you will check :))

**Comment by sntg-p** [comment]
We no longer have videos freezing on iOS, thanks for your work!
