### ISSUE TITLE
[BUG] Android: Type androidx.media3.exoplayer.dash.DefaultDashChunkSource$Factory is defined multiple times

### ISSUE THREAD

**Issue by tacianoscur** [TheWidlarzGroup/react-native-video#4092]
### Version

6.4.4

### What platforms are you having the problem on?

Android

### System Version

Generating bundle

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

After upgrading from `6.4.3` to `6.4.4` I started getting this error when trying to create a signed bundle:

```
Type androidx.media3.exoplayer.dash.DefaultDashChunkSource$Factory is defined multiple times: [path-to-project]/node_modules/react-native-video/android/buildOutput_a15d4dee7fc4eda61b91308cbb6a2e72/.transforms/c8f30f85078ac0af2a73b555487223f1/transformed/release/androidx/media3/exoplayer/dash/DefaultDashChunkSource$Factory.dex, [path-to-project]/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex
```

It does not happen when running the app on the simulator

### Reproduction

Step to reproduce this bug are: 
Create a signed bundle release with new version 6.4.4

**Comment by freeboub** [comment]
Can you run gradlew clean in your android folder ? I suspect this is just a build issue.

**Comment by seyedmostafahasani** [comment]
What is your Android version?
I think it's 11.

**Comment by Hassan-Naeem-code** [comment]
I am also having the same issue

**Comment by Koykoy200078** [comment]
same issue

**Comment by Koykoy200078** [comment]
i just put:
 implementation(project(':react-native-video')) {
        exclude group: 'androidx.media3', module: 'media3-exoplayer-dash'
    }

in my build.gradle to fix temporary

**Comment by seyedmostafahasani** [comment]
Please follow these steps:

- **Perform a clean build of the project:**
In Android Studio, go to `Build > Clean Project`, then go to `Build > Rebuild Project`.

- **IDE Cache Issues:**
In Android Studio, go to `File > Invalidate Caches / Restart`, and select `Invalidate and Restart`. This will clear the cache and restart the IDE.

- **Remove node_modules:**
In the root of your project, run the command `rm -rf node_modules`, then run `yarn install` to reinstall the dependencies.

**Comment by timostroehlein** [comment]
Im also having the same Issue, I tried to clean the cache and do a fresh install, but that did not help. Downgrading to 6.4.3 resolved the issue for now

**Comment by paulrinaldi** [comment]
Same issue

**Comment by seyedmostafahasani** [comment]
This [PR](https://github.com/TheWidlarzGroup/react-native-video/pull/4097) will fix this issue.

**Comment by freeboub** [comment]
Fix integrated in 6.4.5. The version has been released

**Comment by shoaib-31** [comment]
![Image](https://github.com/user-attachments/assets/1f7d6387-2b7a-4671-94d9-75c39cc8c20a)

Hey everyone, I'm still getting this error in react-native-video 6.8.2. How it was fixed?

**Comment by freeboub** [comment]
> ![Image](https://github.com/user-attachments/assets/1f7d6387-2b7a-4671-94d9-75c39cc8c20a)
> 
> Hey everyone, I'm still getting this error in react-native-video 6.8.2. How it was fixed?

It is another issue, did you try to correctly clean your build folders ?

**Comment by shoaib-31** [comment]
Yeah, I tried building after cleaning every cached thing, even cloned codebase without and built directly. For info, I'm using a expo managed workflow and building with eas.
