### ISSUE TITLE
[BUG]: Vidoe player is not visible inside Modal

### ISSUE THREAD

**Issue by rohanthakran** [TheWidlarzGroup/react-native-video#4095]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

node 20.14.0

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I am not able to see video player if I use it inside the model
          {/* ======================= Modal Code ================ */}
          <Modal
            animationType="slide"
            transparent={true}
            visible={modalVisible}
            onRequestClose={() => {
              setModalVisible(!modalVisible);
            }}>
            <View style={styles?.modalBackground}>
              <Text>dskdamdksak ROhn</Text>
              <View
                style={{
                  flex: 1,
                  backgroundColor: 'orange',
                  borderWidth: 1,
                  borderColor: 'orange',
                  marginTop: 22,
                }}>
               
                  <Video
                    preventsDisplaySleepDuringVideoPlayback={false}
                    controls={true}
                    source={{uri: videoFile}}
                    fullscreenAutorotate={true}
                    fullscreenOrientation="portrait"
                    resizeMode={'contain'}
                    muted={false}
                    paused={true}
                    // fullscreen={true}
                    style={{
                      height: responsive_factor * 200,
                      // width: Dimensions.get('window').width / 1.1,
                      width: '100%',
                    }}
                    repeat={true}
                    hideNavigationBarOnFullScreenMode={false}
                    minLoadRetryCount={5}
                    onError={err => console.log('video playing err', err)}
                    // onFullscreenPlayerWillPresent={() => handleFullScreen(true)}
                    // onFullscreenPlayerWillDismiss={() => handleFullScreen(false)}
                  />
               
              </View>
            </View>
          </Modal>

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by moskalakamil** [comment]
Hi @rohanthakran, thanks for reporting the issue!

**Comment by freeboub** [comment]
can you please setup a sample repo ? I try to wrap the <Video  inside a <Modal in the sample, I don't reproduce the issue ...

**Comment by freeboub** [comment]
no feedback, according to: https://github.com/TheWidlarzGroup/react-native-video/issues/4051 video works in modal. let's close this ticket
