### ISSUE TITLE
[BUG]: Bottom tab push below mobile andriod navigation when we click on full screen button

### ISSUE THREAD

**Issue by rohanthakran** [TheWidlarzGroup/react-native-video#4096]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

node 20.14.0

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When I click on fullscreen it is fullscreen but when i exit and go back to the home screen the bottom navigation pushes down and I am not able to see it 
![12345](https://github.com/user-attachments/assets/9ed42994-765c-446d-b7aa-beabd5b733ca)
![1234](https://github.com/user-attachments/assets/2bd834d7-e43e-4620-8086-1efcb240f8a9)
![123](https://github.com/user-attachments/assets/2adda7e3-7c25-4c82-9647-eba496bde032)
![12345](https://github.com/user-attachments/assets/d4a39aca-9819-44f6-a669-e7c6e7ac8881)
![1234](https://github.com/user-attachments/assets/6f038f9a-7dac-47c9-be8b-d3fd2f420a58)
![123](https://github.com/user-attachments/assets/0c3badc8-6469-45dc-9c84-dd3b85921eb7)

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by moskalakamil** [comment]
Hi, thanks for reporting an issue!

**Comment by freeboub** [comment]
Yes, so fullscreen is fullscreen... you need to avoid using fullscreen if you don't want the video to be fullscreen ...
Not sure what change can be done in the package to support that...
Let us know your opinion please ?

**Comment by rohanthakran** [comment]
But if user want to see the video in fullscreen and comeback to home screen not able to see the bottom navigation , he need to restart the app what is the purpose of having fullscreen mode.

**Comment by tacianoscur** [comment]
@freeboub I believe you misinterpreted the issue here, I believe it's the same issue as [this](https://github.com/TheWidlarzGroup/react-native-video/issues/4107). basically after fullscreen, the android bottom tabs navigation bar "hides", in my case, it moves below the native Android navigation bar (as if suddenly the native navigation bar is not "considered" and is floating on top of everything). looks like a safe area view issue there

**Comment by shawn-kelley** [comment]
Same issue here.  When we come back from fullscreen, our bottom nav is pushed way down.

**Comment by freeboub** [comment]
Can you please try on 6.5.0 released yesterday? I changed a little Fullscreen management

**Comment by shawn-kelley** [comment]
@freeboub 6.5.0 seems to be working for me! Thank you!!

**Comment by freeboub** [comment]
Good news, thank you @shawnkelleydev !
So let's close the issue
