### ISSUE TITLE
[BUG]: Value of optional type 'AVMediaSelectionGroup??' not unwrapped

### ISSUE THREAD

**Issue by gmantuanrosa** [TheWidlarzGroup/react-native-video#4099]
### Version

6.4.3

### What platforms are you having the problem on?

iOS

### System Version

MacOS Sonoma (14.4.1)

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

Hello, 

I am facing some issues when updating my iOS App platform version from `13.0` to `15.0`, this issue was not previously being triggered and it happens when I try to do a normal build on a Simulator

The error and code section is:
```
node_modules/react-native-video/ios/Video/Features/RCTVideoUtils.swift:12:20 Value of optional type 'AVMediaSelectionGroup??' not unwrapped; did you mean to use 'try!' or chain with '?'?
```
![Captura de Tela 2024-08-19 às 11 31 48](https://github.com/user-attachments/assets/e687d21c-35af-4002-bf90-b1d1a6b8c4db)

My Xcode version is 15.4 and the simulator is an iPhone 15 Pro

I already did all pod related stuff like, `deintegrate`, `install -repo-update`, removed all DerivedData and Pods/ folder (also Podfile.lock), deleted the .xcode.env.local, but nothing changes this result

### Reproduction

no repository

### Reproduction

I don't know how you will be able to reproduce this issue since I am adding react-native into a native iOS project and not a common react-native project

**Comment by Fausto95** [comment]
I'm currently facing the same issue.

I've patched the lib locally but would be nice if we could upstream the fix.

**Comment by gmantuanrosa** [comment]
> I'm currently facing the same issue.
> 
> I've patched the lib locally but would be nice if we could upstream the fix.

@Fausto95 Have you applied the fix that Xcode suggests? I did the change and now I am facing another issue related to Undefined symbol: _OBJC_CLASS_$_RCTEventDispatcher...

**Comment by Fausto95** [comment]
> > I'm currently facing the same issue.
> 
> > 
> 
> > I've patched the lib locally but would be nice if we could upstream the fix.
> 
> 
> 
> @Fausto95 Have you applied the fix that Xcode suggests? I did the change and now I am facing another issue related to Undefined symbol: _OBJC_CLASS_$_RCTEventDispatcher...


Yea, i've applied the changes suggested by Xcode:

`try!` instead of `try?`

**Comment by moskalakamil** [comment]
Hi, thanks for reporting the issue @gmantuanrosa and quick fix @Fausto95!

**Comment by Fausto95** [comment]
> Hi, thanks for reporting the issue @gmantuanrosa and quick fix @Fausto95!

Thank you @moskalakamil, really looking forward to land the fix upstream.

@gmantuanrosa have you tried applying the fix in #4101? If you do, tell me how it goes.
On my side it fixed the bug.

**Comment by gmantuanrosa** [comment]
> > Hi, thanks for reporting the issue @gmantuanrosa and quick fix @Fausto95!
> 
> Thank you @moskalakamil, really looking forward to land the fix upstream.
> 
> @gmantuanrosa have you tried applying the fix in #4101? If you do, tell me how it goes. On my side it fixed the bug.

I just did and it fixed the issue. Although I am getting another error of  `Undefined symbol: OBJC_CLASS$_RCTEventDispatcher` it doesn't seem related to the unwrapped value 👍 


**Edit:** 
I added 
```
      if pod.name.eql?('react-native-video')
        def pod.build_type
          Pod::BuildType.static_library
        end
      end
```
and now its building

**Comment by freeboub** [comment]
I don't reproduce the issue on the sample ... I have just upgraded my xcode version.
Do you have a clue to reproduce it with the sample app included in the repo ?

**Comment by Fausto95** [comment]
> I don't reproduce the issue on the sample ... I have just upgraded my xcode version. Do you have a clue to reproduce it with the sample app included in the repo ?

My app is running on the old arch with `react-native@0.69.12` and min platform `13.4`
I run into this issue when building the app, with Xcode `15.2`
