### ISSUE TITLE
Playing sounds when screen is off?

### ISSUE THREAD

**Issue by crysfel** [TheWidlarzGroup/react-native-video#41]
I'm using this component to play mp3 files, I'm streaming the music from one of my servers, everything is great so far. I would like to know if is possible to continue playing the music after the phone gets lock, or if the user leaves the app I would also like to continue playing the music, is this possible?

Regards

**Comment by johanneslumpe** [comment]
Did you try to implement the proper [background mode](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html) for your application? I didn't test it, but theoretically it should work when you add the correct background mode for playing audio to your plist.

**Comment by ghost** [comment]
@crysfel take a look at [StreamingKit](https://github.com/tumtumtum/StreamingKit) for playing audio. It can be installed as a CocoaPod and wired up to play audio over HTTP, backgrounded and locked, and manage audio session interruptions (e.g. incoming calls, Siri and headphone unplug). You should then be able to use the ReaCT bridge to dispatch events to control your video from there using the public API [currently in development](https://github.com/brentvatne/react-native-video/pull/42).

Functional example with detailed commits here (URL subject to change):
https://github.com/jhabdas/react-native-es6-reflux

**Comment by brentvatne** [comment]
Nice one :smile:

**Comment by tmoreton** [comment]
@crysfel I'm doing something similar, were you able to figure out how to play audio in the background using the react-native-video component or did you have to switch to the SteamingKit mentioned

**Comment by jhabdas** [comment]
Hope this helps. Should work either way.

http://slides.com/jhabdas/streaming-audio-react-native/

**Comment by ghost** [comment]
Background playback can be achieved by adding the following to your `AppDelegate`, `ViewController` or other suitable class and updating the `Info.plist` file for _background_ playback:

``` objective-c
@import AVFoundation

- (void)setSharedAudioSessionCategory
{
  NSError *categoryError = nil;
  [[AVAudioSession sharedInstance]
    setCategory:AVAudioSessionCategoryPlayback
          error:&categoryError];
  if (categoryError) {
    NSLog(@"Error setting category!");
  }
}
```

In my project [I used the above](https://github.com/jhabdas/lumpen-radio/blob/653b39a291dc9b50e0a590f73654834e38c9b536/iOS/Classes/AudioManager.m#L154-L164) in my `AudioManager` class and it worked well for background playback. It's could be problematic if this kind of code was added to a React Native Module as it could conflict with the app's actual intentions, and some component authors might define things differently making modules problematic to mix-and-match within an app.

**Comment by brentvatne** [comment]
Thanks for the follow up there @jhabdas :)

**Comment by jamesfzhang** [comment]
@jhabdas I added the code snippet you wrote above to my `AppDelegate` and followed [these instructions](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html) on enabling Background playback. But I still can't get audio to play in the background.

**Comment by ghost** [comment]
@jamesfzhang Did you remember to set up your app for background playback in `Info.plist`?

``` xml
<dict>
    <key>UIBackgroundModes</key>
    <array>
        <string>audio</string>
    </array>
</dict>
```

For a working example of background playback using the above code snippets please feel free to study the source of my [Lumpen Radio](https://github.com/jhabdas/lumpen-radio) app.

**Comment by jamesfzhang** [comment]
@jhabdas Yes I did update `Info.plist`. I was hoping to avoid having to learn Objective C as I wanted to get this app I'm working on out ASAP, but thanks for the help. I'll check it out.

**Comment by jamesfzhang** [comment]
@jhabdas Out of curiosity, what version of XCode & iOS are you using to develop Lumpen Radio?

**Comment by jasecoop** [comment]
Thanks for your help with this @jhabdas.

I'm afraid, like @jamesfzhang, I haven't been able to get this working.

I don't have an AudioClass, where should I put that snippet of code?

James, did you get it working in the end?

**Comment by jhabdas** [comment]
You can just throw the code into AppDelegate.m. Use #pragma marks to help
stay organized. But the secret sauce to the background play black is the
background audio playback setting the Info.plist file.

**Comment by jhabdas** [comment]
@jamesfzhang Xcode 7, iOS 8+

**Comment by jamesfzhang** [comment]
I ended up writing my own AudioPlayer using StreamKit and got it working.

**Comment by ghost** [comment]
@jamesfzhang are you open source by any chance? :angel:  be great to see a few more audio implementations so we could look at creating an audio native module on top of StreamingKit (or similar), possibly using something like [rem](https://github.com/exponentjs/rem).

**Comment by jamesfzhang** [comment]
@jhabdas Unfortunately it is not since it was written for a client. But I would be interested in contributing to a generic full-featured audio player (unlike https://github.com/andreaskeller/react-native-audioplayer)

**Comment by ericraio** [comment]
@jamesfzhang did you ever find a full feature generic audio player? This video lib is the only one that works for me

**Comment by jamesfzhang** [comment]
@ericraio ended up writing my own audio player. It uses https://github.com/tumtumtum/StreamingKit

**Comment by jasecoop** [comment]
@jamesfzhang any chance we could see an example of this in use? I have good experience with react-native but am at a loss when it gets to objective c. This issue a real blocker on my project atm

**Comment by ghost** [comment]
@jasecoop StreamingKit at work in OSS form. README contains links to
slides, posts and a Webcast I gave explaining how it all works. Hope it
helps. Good luck!

https://github.com/jhabdas/lumpen-radio

**Comment by ericraio** [comment]
@jhabdas thanks for contributing all of this! I have a quick question about in lumpen radio. What did you do for AirPlay support?

I am also looking to add an airplay button and allow you to switch the audio to a device like AppleTV

**Comment by ghost** [comment]
@ericraio nothing specifically I can think of. please let us know if you figure it out!

**Comment by ericraio** [comment]
@jhabdas hey good news! When background audio is turned on in xcode which also includes airplay,
after I installed this library, the airplay icon gets displayed.

https://github.com/IFours/react-native-volume-slider

**Comment by ghost** [comment]
@ericraio did the author bundle the AirPlay icon with the slider module so it shows in the UI and not simply the system menus? how does the experience compare to, say, Spotify, if you've used it?

**Comment by ericraio** [comment]
@jhabdas The way I know get the airplay icon to display is you need to use iOS's MPVolumeView and if AirPlay is enabled for the app, the icon will appear next to the slider. Now I think you can disable the slider from displaying but I am not sure.

When Spotify displays the AirPlay icon, I think they render it out and create their own custom element that delegates the event to the airplay icon to trigger the menu.

 (fun fact, I was working at Sony with PlayStation Music & Spotify)

**Comment by arbabi2010** [comment]
Hi. I want to do this on android. How can i use it? I set "playInBackground:true" but not working properly

**Comment by sibigit** [comment]
@arbabi2010  did you fixed the issue in android?

**Comment by arbabi2010** [comment]
> @arbabi2010 did you fixed the issue in android?

Yes. but with some other packages . 
I use this tutorial . and i changed some codes on it
https://reactnativeexample.com/audio-player-to-offline-local-and-online-streaming-audio/

**Comment by sibigit** [comment]
> > @arbabi2010 did you fixed the issue in android?
> 
> Yes. but with some other packages .
> I use this tutorial . and i changed some codes on it
> https://reactnativeexample.com/audio-player-to-offline-local-and-online-streaming-audio/

@arbabi2010  Thanks for replay,can you able to give the changed codes for play the sound when mobile in locked mode

**Comment by abhijeetgiram** [comment]
@crysfel 
I have found one workaround for android which allows you to prevent the screen from going to sleep while your app is active. I have used it for audio and it works for me with the help of **react-native-keep-awake** module.

[https://www.npmjs.com/package/react-native-keep-awake](url)

**Comment by abhijeetgiram** [comment]
I have found the way which allows you to play the track even when screen goes to sleep/locked. I have used @react-native-community/audio-toolkit to implement the same.

e.g.
soundOne = new Player('sound_example.mp3', { continuesToPlayInBackground: true });

Here's the link!
https://www.npmjs.com/package/@react-native-community/audio-toolkit

Thanks!
