### ISSUE TITLE
[BUG]: onEnd not called when repeat={true} in React Native Video 5.2.1 on Android

### ISSUE THREAD

**Issue by noumanali53** [TheWidlarzGroup/react-native-video#4103]
### Version

React Native Video 5.2.1

### What platforms are you having the problem on?

Android

### System Version

react native 0.72.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When using the repeat={true} prop with the React Native Video library (version 5.2.1) on Android, the onEnd callback is not triggered as expected. This issue only occurs on the Android platform, while the behavior works correctly on iOS.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by moskalakamil** [comment]
Hi, thank you for your report. We are no longer supporting version 5.2.1. If you need help with this version or assistance upgrading to the latest version, please contact us at hi@thewidlarzgroup.com. Please check if your issue persists on the latest version. If it still occurs, please create a new issue. I will close this one.
Temp fix: remove repeat={true} and onEnd seek video to the start
