### ISSUE TITLE
[BUG]: Value of optional type 'AVMediaSelectionGroup??' not unwrapped

### ISSUE THREAD

**Issue by numsu** [TheWidlarzGroup/react-native-video#4104]
### Version

6.4.5

### What platforms are you having the problem on?

iOS

### System Version

iOS 17.2

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

Xcode build fails with the following error

`Value of optional type 'AVMediaSelectionGroup??' not unwrapped; did you mean to use 'try!' or chain with '?'?`

This comes from RCTVideoAssetsUtils.getMediaSelectionGroup
<img width="621" alt="image" src="https://github.com/user-attachments/assets/9f47783e-fe98-40ad-8ac2-af7678a8933f">

I've created a patch-package for myself to go around this error by adding error handling.

### Reproduction

1. Add react-native-video to dependencies
2. Build project to a simulator using Xcode

Not sure why I did not find another issue for this, I cannot be the only one?

**Comment by KrzysztofMoch** [comment]
Will be fixed by https://github.com/TheWidlarzGroup/react-native-video/pull/4101 (will be released in `6.4.6`)
