### ISSUE TITLE
[BUG]:  onEnd Callback Not Called When repeat={true} on Android (react-native-video 5.2.1)

### ISSUE THREAD

**Issue by noumanali53** [TheWidlarzGroup/react-native-video#4108]
### Version

React Native Video 5.2.1

### What platforms are you having the problem on?

Android

### System Version

14

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I'm encountering an issue where the onEnd callback function is not called on Android when using repeat={true} with react-native-video version 5.2.1. This issue occurs consistently across multiple Android devices.

### Reproduction Link

repository link

### Reproduction

**Steps to Reproduce:**

1. Create a Video component with repeat={true}.
2. Attach an onEnd callback to the component.
3. Play the video until the end on an Android device.

<Video
  source={{ uri: 'video-url' }}
  repeat={true}
  onEnd={() => console.log('Video ended')}
/>
**Expected Behavior:**
The onEnd callback should be called each time the video ends.

**Actual Behavior:**
The onEnd callback is not called when repeat={true} is used on Android.

**Proposed Solution:**
To resolve this issue, I suggest the following changes:

1. 1. Remove the repeat={true} prop and manually handle the video repeating by calling the onEnd callback and then restarting the video playback.
2. Add the following code to handle playback restart if repeat={true} is desired:

ref.current[item?._id]?.setNativeProps({ paused: false });
ref.current?.setNativeProps({ paused: false });

**Comment by KrzysztofMoch** [comment]
Thank you for your report. We are no longer supporting version 5.2.1. If you need help with 5.2.1 or assistance upgrading to the latest version, please contact us at [hi@thewidlarzgroup.com](mailto:hi@thewidlarzgroup.com). Please check if your issue persists on the latest version. If it still occurs, please create a new issue. I will close this one.
