### ISSUE TITLE
[BUG]: Expo plugin prop `enableBackgroundAudio` has no effect

### ISSUE THREAD

**Issue by blazlew** [TheWidlarzGroup/react-native-video#4125]
### Version

6.4.2, but I believe it's still an issue

### What platforms are you having the problem on?

iOS

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

In expo plugin there is [a prop named enableBackgroundAudio](https://arc.net/l/quote/ftdtpzek), that is supposed to add `audio` to the app background capabilities list.
In case the list is empty, this flag takes no effect.

### Reproduction Link

-

### Reproduction

1. Install the lib in expo managed app
2. play video with `playInBackground` prop set to `true`
3. go to background
4. notice the playback stops

**Comment by freeboub** [comment]
PR merged, it will be included in next release. Thank you for the patch !
