### ISSUE TITLE
RN 0.39 onEnd and onPress does not get trigger

### ISSUE THREAD

**Issue by shaftwin** [TheWidlarzGroup/react-native-video#413]
Hi,

I'm on RN 0.39 and these two event does not get trigger on IOS (android not tested).
I trie the repo on the Pull requests section and nothing new append.
The same problem appear on RN 0.38.
If someone know what i can do to make it work it will be really appreciate !!

Waiting for my Captain !

**Comment by MadeInMoon** [comment]
+1

events are not fired on the iOS simulator but it **works on Android 7.1.1** with RN39

**Comment by mickeyjc** [comment]
+1

**Comment by APiercey** [comment]
+1 here as well. It works on neither iPhone 6 simulator or on a iPhone 6 physical device.

**Comment by Lotuslwb** [comment]
+1

**Comment by onchainguy-btc** [comment]
You should try using the master version by npm installing `git+https://github.com/react-native-community/react-native-video.git#master`

**Comment by BraunreutherA** [comment]
@seb0zz tried this but it doesn't work either.

**Comment by BraunreutherA** [comment]
Had to relink it again.

`$ react-native unlink react-native-video`
`$ react-native link react-native-video`
