### ISSUE TITLE
[BUG]: I can't run the video with expo

### ISSUE THREAD

**Issue by ShaimaaSabry** [TheWidlarzGroup/react-native-video#4131]
### Version

6.4.5

### What platforms are you having the problem on?

iOS, Android

### System Version

Pixel 8

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I have a video component in my app:
`
 <Video 
            source={{
                uri: "https://dvfjyetbqjf38.cloudfront.net/BigBuckBunny.mp4",
            }}
/>
`
When I try to run the app using `npx expo start` I get the following error on ios simulator, android emulator and a real device:
`
Render Error
requireNativeComponent: "RCTVideo" was not found in the UIManager
`

### Reproduction Link

repository link

### Reproduction

- run `npx expo start`
- Press a for android emulator, i for ios simulator, or scan the QR code for real device

**Comment by moskalakamil** [comment]
Hi @ShaimaaSabry, please check if your app is not running on Expo Go. The react-native-video library is a native library, and it requires running in an Expo development build.

**Comment by ShaimaaSabry** [comment]
@moskalakamil Thank you. Fixed the issue.

**Comment by moskalakamil** [comment]
That's great! I will close then
