### ISSUE TITLE
[BUG]: Ad Audio for Previous Video Continues Playing in Background After Switching to another Video

### ISSUE THREAD

**Issue by RMabroukS** [TheWidlarzGroup/react-native-video#4132]
### Version

6.4.5

### What platforms are you having the problem on?

iOS

### System Version

17.5

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

I started playing a video, and an ad was displayed shortly after. While the ad was playing, I opened another video. However, the audio from the ad of the previous video continued playing in the background, even after the new video started.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by Dawwie** [comment]
I'm having the same issue. Looks like something similar has been fixed before -> https://github.com/TheWidlarzGroup/react-native-video/pull/3587

My implementation
```
<Video
  source={{
    uri,
  }}
  onLoadStart={onLoadStart}
  onLoad={onLoad}
  onError={onError}
  style={style}
  ignoreSilentSwitch={IgnoreSilentSwitchType.IGNORE}
  controls
/>
