### ISSUE TITLE
[BUG]: onBandwidthUpdate not working on iOS

### ISSUE THREAD

**Issue by anthonychemaly** [TheWidlarzGroup/react-native-video#4139]
### Version

6.4.5

### What platforms are you having the problem on?

iOS

### System Version

17.4

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

onBandwidthUpdate is not logging anything on iOS. It works on android.
This is the portion of code:

`<Video
        ref={videoPlayer}
        style={styles.video}
        isLooping
        resizeMode="contain"
        paused={paused}
        onEnd={onEnd}
        onLoad={onLoad}
        onProgress={onProgress}
        onBandwidthUpdate={e => {
          console.log(Platform.OS, 'bandwidth', e);
        }}
        source={{
          uri: episode.videos[0].video,
        }}
      />`

I am using HLS streaming (index.m3u8) file. Does that change anything? Is there any setting or permission i should turn on or request from app connect

### Reproduction

Try onBandwidthUpdate prop in react-native-video.

**Comment by freeboub** [comment]
@anthonychemaly I just had a look, can you please test the PR I opened ? Thank you

**Comment by anthonychemaly** [comment]
> @anthonychemaly I just had a look, can you please test the PR I opened ? Thank you

For some reason it is returning on the test app and on my personal app: onVideoBandwidthUpdate {"bitrate": -1, "target": 3}
No value for the bitrate

**Comment by freeboub** [comment]
@anthonychemaly are you sure you are testing with online files ? I think this is expected with local files...

**Comment by anthonychemaly** [comment]
> @anthonychemaly are you sure you are testing with online files ? I think this is expected with local files...

yes i am testing on a 2 minute video in hls format (index.m3u8)?
any significance for -1 flag?

**Comment by freeboub** [comment]
@anthonychemaly I tested again (on master as I merged the PR), I correctly receive the event:
`onVideoBandwidthUpdate {"bitrate": 9760357.076251693, "target": 3}`

I am testing on emulator / iphone 15 pro / ios 17.4
What is your environment ?

**Comment by anthonychemaly** [comment]
same environment. may i know the length of the video you are streaming. is it a big file? does it start with a -1 value before showing this?

**Comment by freeboub** [comment]
it is small video available in the sample...
Notice that I release this morning a version with the patch I made !

**Comment by freeboub** [comment]
I still not seeing the same issue than you ... BTW, I added a complementary fix here: https://github.com/TheWidlarzGroup/react-native-video/pull/4149

**Comment by seyedmostafahasani** [comment]
@anthonychemaly 
Would you please test it with the PR linked here?
