### ISSUE TITLE
[BUG]: (Android) Seeking backward after video ends resumes playback even though player was paused

### ISSUE THREAD

**Issue by paulrinaldi** [TheWidlarzGroup/react-native-video#4146]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

14

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

See title.

### Reproduction Link

[repository link](https://github.com/paulrinaldi/react-native-video/tree/show-seek-issue-after-end)

### Reproduction

Steps to reproduce this bug are:

After a video (using `asset file` mp4) ends in the basic example if you comment out the `onEnd` code, you'll notice these logs:
```
LOG  onPlaybackStateChanged {"isPlaying": false, "isSeeking": false}
LOG  onPlaybackRateChange {"playbackRate": 0}
```
Then when you drag the progress bar back (because it's hard to see, I enable the notification controls and pull it back to about halfway in the video), the video unpauses and you'll notice these logs:
```
LOG  onPlaybackRateChange {"playbackRate": 0}
LOG  onVideoBuffer
LOG  onPlaybackStateChanged {"isPlaying": true, "isSeeking": true}
LOG  onPlaybackRateChange {"playbackRate": 1}
LOG  onReadyForDisplay
LOG  onVideoBuffer
```
You will observe this visually:
https://github.com/user-attachments/assets/f7758612-bd80-43c0-838f-97e4fec50f50

**Comment by paulrinaldi** [comment]
I traced as much as I could in the android code, recorded log files, and scanned through them but I could not find why after seeking, the player resumes.

For now, after seek, if the state of my player is paused, I run playerRef.current.pause() right after playerRef.current.seek() and it does what I need it to do.

**Comment by freeboub** [comment]
I was able to reproduce it in the sample (it uses the prop instead of playerRef.current.pause() but it should be the same).
here is a fix proposal: https://github.com/TheWidlarzGroup/react-native-video/pull/4147

I am not sure of the expected events when you pause after onEnd.
Currently, only a playbackRateChange event is generated

**Comment by paulrinaldi** [comment]
I ran `yarn run ios` to compare but just got an error and white screen. Will try to get it running and compare. I think reflecting what iOS does would be acceptable or what RNV used to do (i.e. what dev's expect).

**Comment by freeboub** [comment]
I tested with the sample on ios, I don't reproduce the issue you describe... I have the same behavior than on android.
And yes I agree we should have the same behavior on android and ios!
