### ISSUE TITLE
Uri of remote video with http not work

### ISSUE THREAD

**Issue by truongthanhtungitvn** [TheWidlarzGroup/react-native-video#415]
Hi,
I'm trying to load remote url on ios.
Video with http does not work,
`  <Video
            source={{uri: "http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4"}}
            style={styles.fullScreen}
            rate={this.state.rate}
            paused={this.state.paused}
            volume={this.state.volume}
            muted={this.state.muted}
            resizeMode={this.state.resizeMode}
            onLoad={this.onLoad}
            onProgress={this.onProgress}
            onEnd={() => { AlertIOS.alert('Done!') }}
            repeat={true}
          />`
Video with https work well.
`<Video
            source={{uri: "https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"}}
            style={videoStyle}
            rate={this.state.rate}
            paused={this.state.paused}
            volume={this.state.volume}
            muted={this.state.muted}
            resizeMode={this.state.resizeMode}
            onLoad={this.onLoad}
            onProgress={this.onProgress}
            onEnd={() => { AlertIOS.alert('Done!') }}
            repeat={true}
            controls={this.state.controls}
          />
        </View>`
Please help me, thanks.

**Comment by redkyo017** [comment]
I got the same issue

**Comment by hellogerard** [comment]
Should be closed as dupe of #275. iOS by default prevents access to non-secure remote URLs. You have to configure your project in Xcode to allow.

**Comment by truongthanhtungitvn** [comment]
@hellogerard thank you, you saved my day.

**Comment by baloot-mobile** [comment]
I have the same problem with android
how can I solve it?
