### ISSUE TITLE
[BUG]: Video should not play onLoad the screen.

### ISSUE THREAD

**Issue by ramangupta1602** [TheWidlarzGroup/react-native-video#4157]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

11

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

Video should not play onLoad the screen. it should be play when user click on play buttton.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
set pause={true} ...
