### ISSUE TITLE
[BUG]: code:-1001, domain:NSURLErrorDomain, target:319

### ISSUE THREAD

**Issue by leeqiangzi** [TheWidlarzGroup/react-native-video#4163]
### Version

5.1.1, 6.0.0

### What platforms are you having the problem on?

iOS, Android

### System Version

ios16.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

点开展示video的view,播放正常，然后关闭销毁view，再次点开播放，连续超过3次后报错，code:-1001, domain:NSURLErrorDomain, target:319

### Reproduction Link

repository link

### Reproduction

点开展示video的view,播放正常，然后关闭销毁view，再次点开播放，连续超过3次后报错，code:-1001, domain:NSURLErrorDomain, target:319

**Comment by freeboub** [comment]
Please reopen in English...
