### ISSUE TITLE
[BUG]: Expo Config Plugin for Notification Controls adds duplicate <service> tag to AndroidManifest on every prebuild

### ISSUE THREAD

**Issue by aminmeshk** [TheWidlarzGroup/react-native-video#4167]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

macOs 14.1

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

When I set `"enableNotificationControls": true` in my `app.json` and run `npx expo prebuild`, it adds the code below to the `AndroidManifest.xml` file:
```xml
    <service android:name="com.brentvatne.exoplayer.VideoPlaybackService" android:exported="false" android:foregroundServiceType="mediaPlayback">
      <intent-filter>
        <action android:name="androidx.media3.session.MediaSessionService"/>
      </intent-filter>
    </service>
```
which is the expected behavior. The issue is that if I run `npx expo prebuild` again, it adds the full tag to the manifest once more! It adds it every time I run `prebuild` without cleaning.

### Reproduction

Step to reproduce this bug are: 
1. Add `react-native-video` package to a Expo project that uses [Prebuild](https://docs.expo.dev/workflow/prebuild/)
2. In `app.json` file, add `"react-native-video"` to the `plugins` array like with `"enableNotificationControls": true` parameter. 
```json
"plugins": [
      [
        "react-native-video",
        {
          "enableNotificationControls": true
        }
      ]
]
```
3. Run `npx expo prebuild`
4. Check `AndroidManifest.xml`. The code below should be added to the manifest:
```xml
    <service android:name="com.brentvatne.exoplayer.VideoPlaybackService" android:exported="false" android:foregroundServiceType="mediaPlayback">
      <intent-filter>
        <action android:name="androidx.media3.session.MediaSessionService"/>
      </intent-filter>
    </service>
```
5. Run `npx expo prebuild` again.
6. Check `AndroidManifest.xml`. You can see there are now two of the exact same tag:
```xml
    <service android:name="com.brentvatne.exoplayer.VideoPlaybackService" android:exported="false" android:foregroundServiceType="mediaPlayback">
      <intent-filter>
        <action android:name="androidx.media3.session.MediaSessionService"/>
      </intent-filter>
    </service>
    <service android:name="com.brentvatne.exoplayer.VideoPlaybackService" android:exported="false" android:foregroundServiceType="mediaPlayback">
      <intent-filter>
        <action android:name="androidx.media3.session.MediaSessionService"/>
      </intent-filter>
    </service>
```
7. If you run prebuild again the tag gets added again.

**Comment by freeboub** [comment]
@KrzysztofMoch maybe you have some good clue on this issue ?!

**Comment by aminmeshk** [comment]
I suppose the issue comes from this block of code in `src/expo-plugins/withNotificationControls.ts` file:
```typescript
    manifest.application.map((application) => {
      if (!application.service) {
        application.service = [];
      }

      application.service.push({
        $: {
          'android:name': 'com.brentvatne.exoplayer.VideoPlaybackService',
          'android:exported': 'false',
          // @ts-expect-error: 'android:foregroundServiceType' does not exist in type 'ManifestServiceAttributes'.
          'android:foregroundServiceType': 'mediaPlayback',
        },
        'intent-filter': [
          {
            action: [
              {
                $: {
                  'android:name': 'androidx.media3.session.MediaSessionService',
                },
              },
            ],
          },
        ],
      });

      return application;
    });
``` 

As you can see in the code above, it pushes the service to the `application.service` array without checking first. I can make a PR to fix that

**Comment by freeboub** [comment]
@aminmeshk yes you are right, you're pointing the good code. I don't think the fix is difficult to implement, if you can open a PR, I would be happy to review it !

**Comment by freeboub** [comment]
Linked PR has been merged, let's close the ticket, thank you @aminmeshk !
