### ISSUE TITLE
[BUG]:  Build error in Android 

### ISSUE THREAD

**Issue by Softkeydel** [TheWidlarzGroup/react-native-video#4170]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

Android Studio Koala

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

com.brentvatne.react.test.ReactVideoPackage not found
Please suggest 

![hello_042945](https://github.com/user-attachments/assets/cb0dc8da-612c-4503-8c50-f529272dc5f9)

![Capture](https://github.com/user-attachments/assets/d7faa3a0-5c9b-49df-9ec7-cc663545acd3)

### Reproduction Link

[repository link](https://github.com/Softkeydel/Reproduce.git)

### Reproduction

Step to reproduce this bug are: 
Create react native project with below versions

```
minSdk 24
compileSdk 34
targetSdk 34
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip
```

```
    "react": "18.2.0",
    "react-native": "0.72.17",
    "react-native-video": "^6.5.0",
```

**Comment by freeboub** [comment]
please provide a sample repository which reproduce the issue...

**Comment by Softkeydel** [comment]
@freeboub 
I'v already shared the repo link in the issue.. 
While trying to build APK from Android Studio Koala got the issue 
[https://github.com/Softkeydel/Reproduce.git](https://github.com/Softkeydel/Reproduce.git)

**Comment by freeboub** [comment]
Sorry, I didn't see the sample, but even without react-native-video it doesn't build...
I just clone the sample, and call yarn && yarn android
If I remove react native video, I have the same issue

olivier@OrdinateOlivier Reproduce % yarn android
yarn run v1.22.22
$ react-native run-android
(node:5041) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info JS server already running.
info Installing the app...

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


error Failed to install the app.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by freeboub** [comment]
Tried to build with android studio and without react native video, I have other errors with react native svg and reanimated.
I think there is another mistake with your project, not linked to react native video

**Comment by Softkeydel** [comment]
Did you tried in with Android Studio Koala??
I've tested the sample project.. The issue is genuine.. Me and my teammates are getting the same issue. Why are you closing the ticket

**Comment by freeboub** [comment]
Because nobody can investigate this issue and this is surely not a react native video issue:
- `yarn android` doesn't even start.
- You are the only project to have the issue
- I have upgraded to koala, I have the issue without react native
I don't have time to make support on you react native integration.
Please create a new project from scratch and add react native video. Let me know if you have the same issue, I will reopen the ticket.

**Comment by freeboub** [comment]
last test I can do, I remove all dependancies of the sample:
```diff
diff --git a/package.json b/package.json
index f8fed71..b55ff74 100644
--- a/package.json
+++ b/package.json
@@ -10,27 +10,9 @@
     "test": "jest"
   },
   "dependencies": {
-    "@react-native-async-storage/async-storage": "^2.0.0",
-    "@react-navigation/drawer": "^6.7.2",
-    "@react-navigation/native": "^6.1.18",
-    "@react-navigation/native-stack": "^6.11.0",
-    "@reduxjs/toolkit": "^2.2.7",
     "react": "18.2.0",
     "react-native": "0.72.17",
-    "react-native-document-picker": "^9.3.1",
-    "react-native-gesture-handler": "^2.19.0",
-    "react-native-linear-gradient": "^2.8.3",
-    "react-native-pager-view": "^6.4.1",
-    "react-native-paper": "^5.12.5",
-    "react-native-paper-dropdown": "^2.3.1",
-    "react-native-reanimated": "^3.15.1",
-    "react-native-safe-area-context": "^4.11.0",
-    "react-native-screens": "^3.34.0",
-    "react-native-svg": "^15.3.0",
-    "react-native-tab-view": "^3.5.2",
-    "react-native-vector-icons": "^10.1.0",
-    "react-native-video": "^6.5.0",
-    "redux-saga": "^1.3.0"
+    "react-native-video": "^6.5.0"
   },
   "devDependencies": {
     "@babel/core": "^7.20.0",

```
Project build correctly.

**Comment by Softkeydel** [comment]
you should use 
npm install then
react-native run-android

This repository I've created separately..This is not my actual project.. I'v created this repository only to reproduce the issue..

If you've any issues with react-native-svg
You can  just remove it

**Comment by Softkeydel** [comment]
@freeboub 
I've updated the repository
You can clone it and replicate the issue

[https://github.com/Softkeydel/Reproduce.git](https://github.com/Softkeydel/Reproduce.git)

I'd request you to please check the repository with same configuration
**node v20.14.0
Use npm install
Then try to build from Android Studio Koala 
Use Android Studio default JDK/JRE**
![IMG-20240918-WA0000](https://github.com/user-attachments/assets/a8147737-8f56-47d6-ba17-38ff2c428dfd)

I've tried multiple times created new project and install only react-native-video but got the issue each & every time.

I'd request you to please check the repository with same configuration

**Comment by Softkeydel** [comment]
@freeboub 
Could you please check

**Comment by freeboub** [comment]
> @freeboub 
> Could you please check 

No.. I tried the update, it works on my side... Please create a sample from scratch and compare with your sample and please double check what is problematic with your environment
