### ISSUE TITLE
[BUG]: startPosition gets reset to 0 when adding external subtitles 

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#4175]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened! when I select external subtitles startPosition gets reset to 0 and it is occuring randomly.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: Add a fixed start position to source andt then add subtitles to video multiple times to see that video will load from start.

**Comment by freeboub** [comment]
A sample to reproduce the issue would be useful, it seems complicated to reproduce...

**Comment by freeboub** [comment]
Do you add textTracks for sideloaded text tracks afterward ?

**Comment by mkbhdana** [comment]
> Do you add textTracks for sideloaded text tracks afterward ?

Yes

**Comment by freeboub** [comment]
@mkbhdana In fact the textTracks shall be provided at playback startup. current behavior is to restart the playback when textTracks changed. Lest week I did a small refactor to move it inside the source property to clarify the behavior: https://github.com/TheWidlarzGroup/react-native-video/pull/4158  (not yet released)
So the best solution is to avoid starting the playback when you didn't have the side loaded text tracks...

**Comment by freeboub** [comment]
let's close the ticket as a 'fix' is already ongoing.
