### ISSUE TITLE
[BUG]: Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

### ISSUE THREAD

**Issue by OskarPrzydatekTapptic** [TheWidlarzGroup/react-native-video#4178]
### Version

6.5.0

### What platforms are you having the problem on?

iOS

### System Version

iOS 17.5

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

Whenever the Video component would be rendered on iOS the `Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.` error appears and crash the app. 

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:
1. Launch the app with Video component on iOS
2. Observe

**Comment by freeboub** [comment]
Please provide a sample... Looks like a build issue

**Comment by moskalakamil** [comment]
Hi! please try to reinstall node modules and pods

**Comment by OskarPrzydatekTapptic** [comment]
Ok is all working! Thangs for your help and have a nice day :D I'm closing the ticket

**Comment by OskarPrzydatekTapptic** [comment]
Ok is all working! Thangs for your help and have a nice day :D I'm closing the ticket
