### ISSUE TITLE
[BUG]: Video's aspect ratio changing on android when restarting with repeat set to true

### ISSUE THREAD

**Issue by ElChawich** [TheWidlarzGroup/react-native-video#4187]
### Version

6.6.1

### What platforms are you having the problem on?

Android

### System Version

Android Version 14 One Ui 6.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

After updating to version 6.6.1, on android when a video repeats its changing the aspect ratio of the video. What was expected to happen is to repeat without affecting the aspect ratio.

https://github.com/user-attachments/assets/fc869482-af39-4baf-ab2e-09ef794d0b44

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: 

> <Video
>       ref={videoRef}
>       source={source}
>       paused={paused || !isActive || !screenIsFocused}
>       playWhenInactive={false}
>       resizeMode={'contain'}
>       muted={muted}
>       playInBackground={false}
>       ignoreSilentSwitch='ignore'
>       style={dynamicStyles.video}
>       onProgress={onProgress}
>       repeat={true}
>       poster={{
>         source: { uri: thumbnail },
>         resizeMode: "contain"
>       }}
>     />

**Comment by Pingou** [comment]
Same issue.

**Comment by freeboub** [comment]
I don't reproduce the issue with the sample app...
Can you give a reproducible sample please ?
Maybe it comes from a specific video url.

**Comment by freeboub** [comment]
Maybe you can try with this patch, I suspect this is the root ause
```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java b/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
index 45624d6f..e8dc92c9 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/ExoPlayerView.java
@@ -275,6 +275,7 @@ public final class ExoPlayerView extends FrameLayout implements AdViewProvider {
                     case 90:
                     case 270:
                         layout.setVideoAspectRatio(format.width == 0 ? 1 : (format.height * format.pixelWidthHeightRatio) / format.width);
+                        break;
                     default:
                         layout.setVideoAspectRatio(format.height == 0 ? 1 : (format.width * format.pixelWidthHeightRatio) / format.height);
                 }
```

**Comment by freeboub** [comment]
I confirm this is the good fix, I will open a PR with this patch

**Comment by Pingou** [comment]
@freeboub merci !

**Comment by jawad-elchawich** [comment]
@freeboub the issue still persists in v6.6.4

**Comment by ElChawich** [comment]
@freeboub the issue still persists in v6.6.4

**Comment by freeboub** [comment]
> @freeboub the issue still persists in v6.6.4

Please provide a sample to reproduce the issue .

**Comment by ElChawich** [comment]
> > @freeboub the issue still persists in v6.6.4
> 
> Please provide a sample to reproduce the issue .

`const isActive = activePage === indexInFeed;
  const [videoOrientation, setVideoOrientation] = useState(VIDEO_ORIENTATION.PORTRAIT);

  const getResizeMode = useMemo(() => {
    if (videoOrientation === VIDEO_ORIENTATION.LANDSCAPE) return 'contain';
    if (windowHeight <= MIN_SCREEN_HEIGHT) return 'cover';
    return 'contain';
  }, [videoOrientation]);

  const isPaused = useMemo(() => {
    return paused || !isActive || !screenIsFocused;
  }, [paused, isActive, screenIsFocused]);

  if (Math.abs(activePage - indexInFeed) > 2 || !source) return null;

  return (
    <View style={dynamicStyles.videoContainer}>
      <Video
        ref={videoRef}
        onLoad={({ naturalSize }) => {
          if (naturalSize && naturalSize.orientation) setVideoOrientation(naturalSize.orientation);
        }}
        source={source}
        paused={isPaused}
        poster={{
          source: { uri: thumbnail },
          resizeMode: getResizeMode
        }}
        playWhenInactive={false}
        resizeMode={getResizeMode}
        style={styles.video}
        muted={muted}
        playInBackground={false}
        ignoreSilentSwitch='ignore'
        onProgress={onProgress}
        repeat={true}
        bufferingStrategy='DependingOnMemory'
        bufferConfig={{
          minBufferMs: 1000,
          maxBufferMs: 10000,
          bufferForPlaybackAfterRebufferMs: 1000,
          bufferForPlaybackMs: 1000
        }}
        onError={error => {
          console.log(error);
        }}
      />
    </View>`

**Comment by ElChawich** [comment]
@freeboub commenting out lines 277 and 280 in ExpoPlayerView.java file fixed the issue. Not sure why this code is being triggered in the first place even though the rotation hasn't changed

**Comment by freeboub** [comment]
Please provide it in a git repository with sample video. It is painful to try to replicate issues...
Or easier for you, just try with the basic sample from the repository with your stream

**Comment by ElChawich** [comment]
@freeboub here is a [repository link](https://github.com/ElChawich/ReactNativeVideoLibraryIssueReplicate.git) where you can reproduce. Please test it on android, the issue happens after the video repeats once or twice

**Comment by freeboub** [comment]
As you see I have reopen the ticket, with this video it is also reproduced with the sample app (Thank you for sharing it !).
I try to fix the issue but I fail in a painfull cycle of regression.
BTW, I think we are in an issue related to this is an exoplayer issue: https://github.com/androidx/media/issues/1207 
It would be interesting handle the issue on Exoplayer side, but I don't think I will have time to handle it ...

But ! There is an issue in your manifest file, if you open the m3u you will see following configuration : 

#EXT-X-STREAM-INF:BANDWIDTH=5000000,AVERAGE-BANDWIDTH=4000000,CODECS="mp4a.40.2,avc1.640028",RESOLUTION=1920x1080,CLOSED-CAPTIONS=NONE

which means you stream is 1920X1080 where it is 1080X1920

You can compare with this stream which is landscape:  https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8 

As a conclusion:
- There is an issue with exoplayer which don't report consistant data
- There is an issue on RNV which doesn't handle consistently aspect ratio. (I will provide a fix for that)
- There is an issue with your stream.

#nightmare 😆
