### ISSUE TITLE
[BUG]: AVPlayer Notifications Crash App When Switching Tracks After Background

### ISSUE THREAD

**Issue by AlexEKoren** [TheWidlarzGroup/react-native-video#4188]
### Version

6.4.5

### What platforms are you having the problem on?

iOS

### System Version

iOS 17

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

After playing a file, locking the screen, unlocking, then changing the track, the following crash occurs:

The app crashes with:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot remove an observer <NSKeyValueObservance 0x30005b600> for the key path "currentItem.videoComposition" from <AVPlayer 0x300dcac00>, most likely because the value for the key "currentItem" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the AVPlayer class.'`

It's unclear why this is only happening after a screen lock. Possibly some other observers are added for background playback that aren't cleaned up correctly?

### Reproduction Link

repository link

### Reproduction

Steps to reproduce:
1. Configure player for offline playback
2. Start playback of a file (we are using DRM protected files, but I don't believe it's relevant for this issue)
3. Let the file play and load
4. Lock the screen then unlock
5. Change the track by setting a new source

**Comment by freeboub** [comment]
Can you reproduce with the last version 6.6.1 ? There was a lot of rework linked to DRM on this version
"Change the track by setting a new source" -> it is not clear to me do you change track or source ?
