### ISSUE TITLE
[BUG]: Throws Error when external subtitle is loaded

### ISSUE THREAD

**Issue by bsbimalbose** [TheWidlarzGroup/react-native-video#4189]
### Version

6.6.1

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

When loading external subtutiles. An error is thrown

Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle application/x-subrip samples (expected application/x-media3-cues).

### Reproduction Link

repository link

### Reproduction

Play a video with an external subtitle in source.textTracks

**Comment by ksetrin** [comment]
I've encountered this problem as well

Error
`
{"error":{"errorStackTrace":"androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:205)\n\tat android.os.Looper.loop(Looper.java:294)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle text/vtt samples (expected application/x-media3-cues).\n\tat androidx.media3.common.util.Assertions.checkState(Assertions.java:100)\n\tat androidx.media3.exoplayer.text.TextRenderer.assertLegacyDecodingEnabledIfRequired(TextRenderer.java:589)\n\tat androidx.media3.exoplayer.text.TextRenderer.onStreamChanged(TextRenderer.java:212)\n\tat androidx.media3.exoplayer.BaseRenderer.replaceStream(BaseRenderer.java:151)\n\tat androidx.media3.exoplayer.BaseRenderer.enable(BaseRenderer.java:125)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderer(ExoPlayerImplInternal.java:2773)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2747)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:1926)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)\n\t... 4 more\n","errorCode":"21004","errorException":"androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error","errorString":"ExoPlaybackException: ERROR_CODE_FAILED_RUNTIME_CHECK"}}
`

**androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error**

HOW TO REPRODUCE
It's very simple

1) Clone this repo https://github.com/TheWidlarzGroup/react-native-video/tree/master/examples/basic
2) yarn install
3) Try to change these lines https://github.com/TheWidlarzGroup/react-native-video/blob/master/examples/basic/src/constants/general.ts#L119-L122 to this
```
  {
    description: '(dash) sintel subtitles',
    uri: 'https://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd',
    textTracks: [
      {
        title: 'test',
        language: 'en' as ISO639_1,
        type: TextTrackType.VTT,
        uri: 'https://bitmovin-a.akamaihd.net/content/sintel/subtitles/subtitles_de.vtt',
      },
    ],
  },
```
4) npx react-native run-android

You should see 5 items in TextTracks
<img width="428" alt="image" src="https://github.com/user-attachments/assets/cd6fbecc-a792-4f44-abf2-3bd5a4a1526b">
0-1-2-3 from the mpd file, BUT 4 from `const srcAndroidList` that you specify for '(dash) sintel subtitles'

5) Select `4` from TextTracks and you will get Error
<img width="395" alt="image" src="https://github.com/user-attachments/assets/465a4775-04ed-461c-abfb-62b82c6eeaff">

So, why vtt works from mpd file and it doesn't work if you specify them as an external source?

**Comment by mkbhdana** [comment]
![ImportedPhoto_1727371868355](https://github.com/user-attachments/assets/039a7059-5085-4972-a139-dee1170eeed3)


adding external subtitles causes runtime error whenadding textracks from source

**Comment by mkbhdana** [comment]
adding external subtitles causes runtime error whenadding textracks from source
![ImportedPhoto_1727371868355](https://github.com/user-attachments/assets/d02172a3-0c49-4b7e-9176-bd7ea0e78b0b)

**Comment by mkbhdana** [comment]
With textracks props in source though blank breaks existing subtiles also which breaks whole app.

**Comment by ksetrin** [comment]
Use `6.5.0` version
As I see subtitle was refactored after that version and currently broken
For `6.5.0` textTracks not in source prop

**Comment by freeboub** [comment]
Issue reproduced with the sample, but NOT with exoplayer sample.. I confirm this is an RNV issue, but I don't think this is linked to the recent refactor. (It is just a data management change no behavior change)

**Comment by freeboub** [comment]
The issue happen after media3 update, commit: e57c7bda5df7d624d90b20620859b8a4eb3f76b7

**Comment by freeboub** [comment]
I confirm this is an API change with media3: see following ticket: https://github.com/androidx/media/issues/1569#issuecomment-2255506625

**Comment by freeboub** [comment]
As fix impact playback startup, let's wait for the merge of this PR: https://github.com/TheWidlarzGroup/react-native-video/pull/4185 to implement a correct fix

And yes the workaround for you is to stay on 6.5.0 for now

**Comment by Jonath-z** [comment]
@freeboub I downgraded and still it does not work

**Comment by ksetrin** [comment]
@Jonath-z check again
for me it woks well (6.5.0)

```
<Video
  ref={videoRef}
  source={{ uri: source }}
  textTracks={subtitles}
  selectedTextTrack={{
    type: 'index',
    value: 0,
  }}
  ...
```

**Comment by Pormons** [comment]
@ksetrin Im also having the same issue even though I have downgraded to 6.5.0

 Video Error: {"error": {"errorCode": "23003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: Source error", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:706)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (TsExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor, AvifExtractor) could read the stream.{contentIsMalformed=false, dataType=1}
        at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:108)
        at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1060)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
", "errorString": "ExoPlaybackException: ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED"}}

**Comment by Pormons** [comment]
any updates on this?
