### ISSUE TITLE
[BUG]: iOS picture in picture closes after app backgrounded

### ISSUE THREAD

**Issue by dgocoder** [TheWidlarzGroup/react-native-video#4193]
### Version

6.6.2

### What platforms are you having the problem on?

iOS

### System Version

17

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When you play a video and background the app the audio continues to play but the picture in picture does not. Even if the prop is enabled it momentarily shows then closes.

### Reproduction Link

https://github.com/dgocoder/react-native-video-error/tree/main

### Reproduction

Step to reproduce this bug are: 
`npm install`
`npm run ios`
background app once video starts playing.

**Comment by felipegmg** [comment]
+1

**Comment by stephenlindauer** [comment]
Was there any update/resolution here? I am also seeing this on 6.8.2, latest iOS.
