### ISSUE TITLE
[BUG]: Video Data reload on basic video operation like play, pause

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#4196]
### Version

6.6.2

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

A bug happened! Performing video actions like play, pause, resize, select tracks cause video to reload data on new architecture.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: build apk on new architecture and perform basic video operaions.

**Comment by freeboub** [comment]
Can you please provide a repository with a sample app ?

**Comment by mkbhdana** [comment]
> Can you please provide a repository with a sample app ?

Ok , will provide in the weekend

**Comment by mkbhdana** [comment]
I used basic sample on new arch to reproduce bug but couldn't until i disable cache first time. Btw i am not using cache in my project where i am facing issue.  Here is the video... 


https://github.com/user-attachments/assets/c0b810d5-cb83-4589-a1b3-78e5a8444dd3

**Comment by freeboub** [comment]
@mkbhdana I am not sure to understand. you mean that unable or disable caching restart playback ?
If that is your point, I know it, I will move cache configuration into source property (we need to configure cache before starting the playback)

**Comment by mkbhdana** [comment]
> @mkbhdana I am not sure to understand. you mean that unable or disable caching restart playback ? If that is your point, I know it, I will move cache configuration into source property (we need to configure cache before starting the playback)

on new arch in my project (**i don't use cache) i faced issue of restart playback on actions like play, pause that's my issue which i logged here. 

***In order to provide repo as asked i used basic example  on new arch but, i faced no issue for what i logged until i found that cache disabling once can reproduce my logged bug.

**Comment by freeboub** [comment]
@mkbhdana I don't think this is an issue with react native video... Please clean your same (remove all props on rnv), then ensure the source does not change and check if it fixes the issue... As you are the only one to have the issue I suspect an issue on your project...

**Comment by mkbhdana** [comment]
> @mkbhdana I don't think this is an issue with react native video... Please clean your same (remove all props on rnv), then ensure the source does not change and check if it fixes the issue... As you are the only one to have the issue I suspect an issue on your project...

yeah you are correct, when i removed enable disable cache functionlity in basic it works well, after that i debug my project again and i see removing bufferConfig resolves problem for me as temp fix. I am using flashlist and react native paper i suspect these two can be a problem, don't know exact reason.

**Comment by freeboub** [comment]
> > @mkbhdana I don't think this is an issue with react native video... Please clean your same (remove all props on rnv), then ensure the source does not change and check if it fixes the issue... As you are the only one to have the issue I suspect an issue on your project...
> 
> yeah you are correct, when i removed enable disable cache functionlity in basic it works well, after that i debug my project again and i see removing bufferConfig resolves problem for me as temp fix. I am using flashlist and react native paper i suspect these two can be a problem, don't know exact reason.

Yep, changing the value of bufferConfig restarts playback, I think it is your issue. It cannot be changed for now, as I said, it will be moved into source property soon !
