### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mariambenhmida** [TheWidlarzGroup/react-native-video#4197]
### Version

6.6.2

### What platforms are you having the problem on?

iOS

### System Version

17.4

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

Getting issue where react-native-video (v6.6.2) is incompatible with my iOS deployment target set to iOS 17.4. When running pod install, I receive an error stating that react-native-video requires a different minimum deployment target. Lowering the target resolves the issue, but I need support for iOS 17.4. Also my React Native version is  0.71.6

**The running pod install crashes with:**
```
> [!] CocoaPods could not find compatible versions for pod "react-native-video": In Podfile: 
react-native-video (from `../node_modules/react-native-video`) 
Specs satisfying the `react-native-video (from ../node_modules/react-native-video)` dependency were found, but they required a higher minimum deployment target.
 
```

**The app crashes with:**
```
> Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.
```
**Steps Tried to Resolve:**
1. Cleaned Pods cache, reinstalled dependencies, and added this line in my Podfile.

iOS/Podfile:
```
>  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
```
2. Running again pod install

```
> [!] There are multiple dependencies with different sources for react-native-video in Podfile:
 
> - react-native-video (from ../node_modules/react-native-video)
> - react-native-video (from ../node_modules/react-native-video/react-native-video.podspec)
```

### Reproduction

1. Add the react-native-video package to a React Native project with iOS deployment target set to 17.4.
2. Run pod install and observe the error about incompatible deployment target.
3. The error suggests that the minimum deployment target supported by the react-native-video package is lower, leading to a conflict.

**Comment by freeboub** [comment]
didi you try to remove: `pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'`
from your podfile ?

**Comment by mariambenhmida** [comment]
Yes I did, back to the same issue which is 

 [!] CocoaPods could not find compatible versions for pod "react-native-video": In Podfile: 
react-native-video (from `../node_modules/react-native-video`) 
Specs satisfying the `react-native-video (from ../node_modules/react-native-video)` dependency were found, but they required a higher minimum deployment target.
