### ISSUE TITLE
RN 0.39 onLoad not fired

### ISSUE THREAD

**Issue by ivpusic** [TheWidlarzGroup/react-native-video#420]
tried it on ios simulator and device (iOS 10)

**Comment by mickeyjc** [comment]
+1

**Comment by larryranches** [comment]
Make sure you get the latest code. Then you might have to unlink and link the library. Thanks to @hellogerard for this.

`$ react-native unlink react-native-video`
`$ react-native link react-native-video`

**Comment by mondoul-goknit** [comment]
Hi @larryranches 
I've had the same issue, running `"react-native-video": "^0.9.0"` and `"react-native": "0.39.2"`.
the unlink / link did'nt work for me, any other idea? 
Thanks

**Comment by ivpusic** [comment]
probably this is fix https://github.com/react-native-community/react-native-video/commit/9bcf70cbb513402622bc114f93da751c28f15303

**Comment by mondoul-goknit** [comment]
Yes, you're right. But I can't get this code when getting the package from npm. 
if I need to clone the repo, how do I include it in my project ?
Thanks

**Comment by larryranches** [comment]
@mondoul I have a PR #419 to change the version number to 0.9.1 so npm will get the latest code.  You want to get this directly from master or fork over the repo.  Make sure it has the latest commit, then unlink and link it again.

EX: `"react-native-video": "github:larryranches/react-native-video",`

**Comment by hellogerard** [comment]
@mondoul Change the line for this package in your `package.json` to:

```
 "react-native-video": "git+https://github.com/react-native-community/react-native-video.git#master",
```

**Comment by mondoul-goknit** [comment]
Thanks, I've forked it but I guess using master directly works well too.

**Comment by Jon-Roby** [comment]
@hellogerard After making that change, and then relinking (and even doing the rm -rf node_modules && npm install... clear cache, etc.) when I go to watch a video the app just closes.

**Comment by ghost** [comment]
Stale. Closing.
