### ISSUE TITLE
[BUG]: HLS is not enable

### ISSUE THREAD

**Issue by Usman-02501** [TheWidlarzGroup/react-native-video#4200]
### Version

 "react-native-video": "^6.6.2",

### What platforms are you having the problem on?

Android

### System Version

22H2

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened! The video is running in my project and Live TV is not running it generate error
"error": {
    "errorStackTrace": "java.lang.IllegalStateException: HLS is not enabled!\n\tat com.brentvatne.exoplayer.ReactExoplayerView.buildMediaSource(ReactExoplayerView.java:1073)\n\tat com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerSource(ReactExoplayerView.java:826)\n\tat com.brentvatne.exoplayer.ReactExoplayerView.lambda$initializePlayer$6(ReactExoplayerView.java:695)\n\tat com.brentvatne.exoplayer.ReactExoplayerView.$r8$lambda$CmLk1POlizDjARVrkea3Gsb1vzc(Unknown Source:0)\n\tat com.brentvatne.exoplayer.ReactExoplayerView$$ExternalSyntheticLambda6.run(Unknown Source:4)\n\tat android.os.Handler.handleCallback(Handler.java:883)\n\tat android.os.Handler.dispatchMessage(Handler.java:100)\n\tat android.os.Looper.loop(Looper.java:264)\n\tat android.app.ActivityThread.main(ActivityThread.java:7581)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)\n",
    "errorCode": "1001",
    "errorException": "java.lang.IllegalStateException: HLS is not enabled!",
    "errorString": "java.lang.IllegalStateException: HLS is not enabled!"
  }
}
guide or give me solution

**Comment by freeboub** [comment]
I think you disable hls renderer in gradle file with : useExoplayerHls=false

**Comment by Usman-02501** [comment]
I am add this array in app.json
 [
        "react-native-video",
        {
          "enableNotificationControls": true,
          "androidExtensions": {
            "useExoplayerRtsp": true,
            "useExoplayerSmoothStreaming": true,
            "useExoplayerHls": true,
            "useExoplayerDash": false,
            "extensionRendererMode": "prefer"
          }
        }
      ]
      and my problem is not solve in expo

**Comment by freeboub** [comment]
did you check that build logs are coherent with your config ?

> Configure project :react-native-video
Kotlin version is correct: 1.9.22
useExoplayerIMA: true
useExoplayerSmoothStreaming: true
useExoplayerDash: true
useExoplayerHls: true
useExoplayerRtsp: true
buildFromSource: false

**Comment by freeboub** [comment]
and notice that extensionRendererMode doesn't exists ...
