### ISSUE TITLE
[BUG]:  Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

### ISSUE THREAD

**Issue by Just9krish** [TheWidlarzGroup/react-native-video#4203]
### Version

6.6.2, 6.5.0 and 6.4.3

### What platforms are you having the problem on?

Android, Windows

### System Version

Windows 10 and Android Mobile

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

When I try to use `react-native-video`, whether it's a local file or a URL hosted on AWS, the app crashes and throws the following error: Invariant Violation: requireNativeComponent: "RCTVideo" was not found in the UIManager.

I have tried different Node versions and different versions of `react-native-video`, but I am still encountering the same issue. I suspect I might be missing something, but I am unsure where the mistake is. I also tried the suggestion from this guide: https://thewidlarzgroup.github.io/react-native-video/other/expo#expo-plugin, but the issue persists.

![image](https://github.com/user-attachments/assets/88b913f5-1938-4567-b36d-4a4f8c9599e9)

### Reproduction Link

https://github.com/Just9krish/react-native-video

### Reproduction

1. Clone the repository using the provided link and install dependencies by running `npm i`.
2. Start the application with the command `npm start`.
3. The error will appear when the app is bundled and loaded.

**Comment by freeboub** [comment]
Your issue is linked to expo go. if you run: `npx expo run:android` the project is rebuilt and the error disappear !
And thank you for the sample !

**Comment by Just9krish** [comment]
I'm new to React Native and Expo, and I was following your suggestion regarding running `npx expo run:android` to fix the "RCTVideo not found in the UIManager" error. When I ran the command, I encountered a few errors. I was able to solve a few of the errors, but now I’m stuck on the following error:

```
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

Could you please elaborate on your comment about "Your issue is linked to Expo Go"? I understand that Expo Go might have some limitations, but I would really appreciate it if you could explain how exactly you resolved this and how to avoid these errors while running in development mode with Expo.

**Comment by Just9krish** [comment]
While running the command `npx expo run:android` I encountered the following error:

```
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

This is the complete log file. Could you please help me resolve this issue? @freeboub 
[logErrors.txt](https://github.com/user-attachments/files/17207101/logErrors.txt)

**Comment by freeboub** [comment]
`./gradlew : The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set.`

you should check that !

```

e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainActivity.kt:18:14 Unresolved reference: R
e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainActivity.kt:35:11 Unresolved reference: BuildConfig
e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainApplication.kt:31:60 Unresolved reference: BuildConfig
e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainApplication.kt:33:52 Unresolved reference: BuildConfig
e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainApplication.kt:34:51 Unresolved reference: BuildConfig
e: file:///C:/Users/desktop/Desktop/test-app/android/app/src/main/java/com/fernandes/developer/testapp/MainApplication.kt:44:9 Unresolved reference: BuildConfig

```

--> looks like an issue in you app ...
