### ISSUE TITLE
App Crashes when Video renders

### ISSUE THREAD

**Issue by shahen94** [TheWidlarzGroup/react-native-video#421]
![screen shot 2016-12-15 at 3 17 08 pm](https://cloud.githubusercontent.com/assets/13334788/21222135/d99b4250-c2d9-11e6-8989-1cc8c0c8be12.png)

Can't render <Video />, since it's crashes on my device.

## Additional information
Device: iPhone 5s (iOS 10)
RN: 0.39.0
RN-Video: master
OS: MacOS

**Comment by carleryd** [comment]
I have the same error, I used
`react-native unlink react-native-video`
`react-native link react-native-video`
as suggested in another issue after updating node_modules/react-native-video

Device: iPhone 5s (iOS 10)
RN: 0.38.1
RN-Video: commit 9bcf70cbb513402622bc114f93da751c28f15303 (https://github.com/react-native-community/react-native-video/commit/9bcf70cbb513402622bc114f93da751c28f15303)
OS: MacOS

**Comment by gevorg15** [comment]
Looks like this is still happening on iPhone 5s

**Comment by ghost** [comment]
👉 http://stackoverflow.com/questions/tagged/react-native
