### ISSUE TITLE
[BUG]: Android device wallpaper show in notch area when switching to landscape mode

### ISSUE THREAD

**Issue by johnxim** [TheWidlarzGroup/react-native-video#4213]
### Version

6.1.1

### What platforms are you having the problem on?

Android

### System Version

android 13

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

When switching the app to landscape mode on Android devices with a notch, the notch area shows the device's wallpaper instead of maintaining the app's background or a consistent color

### Reproduction Link

repository link

### Reproduction

Play a video and switch to landscape mode

**Comment by freeboub** [comment]
There are not enough information to investigate this issue ... moreover you report the issue on a too old version

**Comment by reinismu** [comment]
I just encountered this issues as well. Notch area is ether gray or shows android background

![image](https://github.com/user-attachments/assets/dabb2ee6-62b0-40b1-9151-4479dbed401d)
