### ISSUE TITLE
[BUG]: Doesn't render when React Compiler is enabled

### ISSUE THREAD

**Issue by reinismu** [TheWidlarzGroup/react-native-video#4222]
### Version

6.6.4

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

When using Expo + React Compiler https://docs.expo.dev/preview/react-compiler/ `react-native-video` component is never rendered (When debugging it doesn't even show up in tree).

### Reproduction Link

https://github.com/reinismu/react-native-video-react-compiler-bug

### Reproduction

Step to reproduce this bug are: Run expo app with React Compiler enabled

**Comment by freeboub** [comment]
Can you please provide a sample repository?

**Comment by reinismu** [comment]
> Can you please provide a sample repository?

Create project to reproduce. You can change `app.json` `reactCompiler` to true/false to check
https://github.com/reinismu/react-native-video-react-compiler-bug

**Comment by freeboub** [comment]
Thank you for the sample, I investigated and it looks like an issue linked to the babel plugin.
in App.js from the sample in line:
```JS
import Video from 'react-native-video';
console.log('Video', Video)
```
displays RCTVideo in the console.
It means that the import import directly the native module instead of the JS module

I found a workaround by exporting Video as a not default in the library.
With this patch in react-native-video
```diff
diff --git a/src/index.ts b/src/index.ts
index 575ac839..9446bf83 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -2,4 +2,5 @@ import Video from './Video';
 export {VideoDecoderProperties} from './VideoDecoderProperties';
 export * from './types';
 export type {VideoRef} from './Video';
+export {Video}
 export default Video;
````

Then on sample side, I can play video & ensure fix work with this patch:

```diff
--- a/App.js
+++ b/App.js
@@ -1,11 +1,12 @@
 import React from 'react';
 import { StyleSheet, View } from 'react-native';
-import RNVideo from 'react-native-video';
+import {Video} from 'react-native-video';
 
+console.log('Video', Video)
 export default function App() {
     return (
         <View style={styles.container}>
-            <RNVideo
+            <Video
                 source={{ uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' }}
                 style={styles.video}
                 repeat
```

And log displayed:

` LOG  Video {"$$typeof": Symbol(react.forward_ref), "render": [Function anonymous]}`

I think it would be useful to report the issue to React Compiler team !
I can also integrate the patch, it is not intrusive

**Comment by reinismu** [comment]
Reported the bug to React Compiler team as well https://github.com/facebook/react/issues/31172

Thanks for the quick workaround fix! ;)

**Comment by poteto** [comment]
@freeboub Thanks for reporting. I'm not sure this is a bug with the compiler's babel plugin, we don't rewrite any imports

**Comment by freeboub** [comment]
Hello @poteto Thank you for having a look.

As I was not 100% sure where the issue is, I retested.
In the provided sample, If I disable the the plugin the issue disappear, so it really looks like to be a compiler issue.

Another patch to make the exemple work:

```diff
diff --git a/app.json b/app.json
index 7c746b2..da9c1e7 100644
--- a/app.json
+++ b/app.json
@@ -5,9 +5,6 @@
     "version": "1.0.0",
     "plugins": [
       "react-native-video"
-    ],
-    "experiments": {
-      "reactCompiler": true
-    }
+    ]
   }
 }
```
