### ISSUE TITLE
[BUG]: Rate controls is not visible on iOS version < 17.0

### ISSUE THREAD

**Issue by sherbiiny** [TheWidlarzGroup/react-native-video#4224]
### Version

6.6.4

### What platforms are you having the problem on?

iOS

### System Version

15.0

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

The speed controls are not visible on iOS versions below 17.

Attached is a screenshot from an iPhone running iOS 15.

![image](https://github.com/user-attachments/assets/aecc2f04-4811-49e5-8afc-1bc4b43d620e)

Do you have any tips on how to display the speed controls? If I need to implement a custom solution, do you have suggestions for doing it efficiently?"

### Reproduction Link

repository link

### Reproduction

.

**Comment by freeboub** [comment]
controls are managed by ios. I don't think we can fix it with the built in controls
