### ISSUE TITLE
[Feature]: Paused state from ref

### ISSUE THREAD

**Issue by maksymhcode-care** [TheWidlarzGroup/react-native-video#4226]
### Description

Not crucial, but do you think getting play/pause state from ref can be added?

### Why it is needed ?

Having ability to get this state locally can help with optimization

**Comment by seyedmostafahasani** [comment]
@maksymhcode-care 
You can use these methods: [pause](https://thewidlarzgroup.github.io/react-native-video/component/methods#pause) and [resume](https://thewidlarzgroup.github.io/react-native-video/component/methods#resume)

**Comment by cordovalegacy** [comment]
Yes this would be a great thing to have

**Comment by freeboub** [comment]
This should be implemented on js side. Register on the event in Video.tsx and save the state to a ref. The accessor just needs to return the value on the ref. (Can also be implemented on the app side, but it can but integrated in the package). Ping @seyedmostafahasani I know you start something similar.

**Comment by paulrinaldi** [comment]
Yeah this could be implemented as @freeboub suggests.
The way the exoplayer lets us keep track of state is by `isPlayingChanged` events in any class that implements `Player.Listener` (in rnv, the class `ReactExoplayerView` does). 

I believe you @maksymhcode-care could implement in your video player containing component the following currently though:
```
const videoIsPlaying = useRef(false);

<Video
  onPlaybackStateStateChanged={(data) => videoIsPlaying.current = data.isPlaying}
  />
  ```

**Comment by maksymhcode-care** [comment]
> Yeah this could be implemented as @freeboub suggests. The way the exoplayer lets us keep track of state is by `isPlayingChanged` events in any class that implements `Player.Listener` (in rnv, the class `ReactExoplayerView` does).
> 
> I believe you @maksymhcode-care could implement in your video player containing component the following currently though:
> 
> ```
> const videoIsPlaying = useRef(false);
> 
> <Video
>   onPlaybackStateStateChanged={(data) => videoIsPlaying.current = data.isPlaying}
>   />
> ```

Yeah, something like that would works, thanks
