### ISSUE TITLE
IOS how can continue to play audio mp3 in the lock screen?

### ISSUE THREAD

**Issue by luojinghui** [TheWidlarzGroup/react-native-video#423]
I set the following：
```
<Video
              source={{uri: "https://jnexpert-oss1.oss-cn-beijing.aliyuncs.com/upload/wx_class_voice/132/1480910856819590.mp3"}}
              playInBackground={ true }
              playWhenInactive={ true }
              paused={ this.state.paused }
              onProgress={ this.onProgress.bind(this) }
              onLoad={ this.onLoad.bind(this) }
              ref={(ref) => {
                this.player = ref
              }}
              onEnd={ this.onEnd.bind(this) }
          ></Video>
```
	
issue：
In the android, it is in the lock screen can continue to play mp3
but in the ios, the simulator can continue to play in the lock screen state
when ios real machine test, it can continue to play, this should be how to solve . Thank you

Device: iPhone 5s (iOS 10.2)
RN: 0.37.0
RN-Video: master
OS: MacOS

**Comment by ghost** [comment]
https://www.npmjs.com/package/react-native-audio-streaming
