### ISSUE TITLE
play hls on wrong rctvideo.m line384 ios 10

### ISSUE THREAD

**Issue by neegqi** [TheWidlarzGroup/react-native-video#424]
`  if([keyPath isEqualToString:playbackRate]) {
          self.onPlaybackRateChange(@{@"playbackRate": [NSNumber numberWithFloat:_player.rate],
                                      @"target": self.reactTag});
          if(_playbackStalled && _player.rate > 0) {
              self.onPlaybackResume(@{@"playbackRate": [NSNumber numberWithFloat:_player.rate],
                                      @"target": self.reactTag});
              _playbackStalled = NO;
          }
      }`

**Comment by hellogerard** [comment]
🤔

**Comment by XHTeng** [comment]
iPhone 5 iOS10, has the crash

**Comment by smkhalsa** [comment]
I'm also getting this on iPhone 5 simulator. Anyone track this down yet?

**Comment by hellogerard** [comment]
This is a dupe of #421 and should be closed.
