### ISSUE TITLE
[Feature]: Yarn 3 support

### ISSUE THREAD

**Issue by yungblud** [TheWidlarzGroup/react-native-video#4250]
### Description

I think latest react-native is supporting yarn v3.6.4.
As you can see bottom links.
- https://react-native-community.github.io/upgrade-helper/?from=0.73.6&to=0.76.0-rc.4
- https://react-native-community.github.io/upgrade-helper/?from=0.73.6&to=0.76.0-rc.4#RnDiffApp-package.json

### Why it is needed ?

Get in sync with latest react native yarn version.

### Possible implementation

It's possible but we have to create yarn.lock files in `examples projects` such as "examples/bare" after we set yarn version as 3.6.4 in the root project's package.json. But yarn.lock is gitignored.

Please have a look and test it.
https://github.com/TheWidlarzGroup/react-native-video/pull/4249

$ cd examples/bare
$ yarn install (without yarn.lock is existing)

![스크린샷 2024-10-22 오후 4 37 19](https://github.com/user-attachments/assets/ba129ccc-e3d5-47d9-bdb6-6a58a8c44cae)

But if we have yarn.lock file inside of "examples/bare", yarn install is working.
$ cd examples/bare
$ touch yarn.lock
$ yarn install

I don't know how to solve it right now without yarn workspaces. Maybe need some ideas.

### Code sample

No code sample needed for this issue.

**Comment by Lakston** [comment]
I updated to 75 that also uses yarn 3 and I had no problems with this package. I suggest you check the yarn documentation on [how to upgrade to v3+](https://yarnpkg.com/migration/guide) and verify that you did all the steps.

**Comment by lovegaoshi** [comment]
the yarn ver u referred to is the example app, which quite frankly, has nothing to do with YOU the dev using the lib; u can use [yarn v4 in ur own repo](https://github.com/lovegaoshi/azusa-player-mobile/blob/40e99c3d31def9a45307292e8cdd120d377ff4db/package.json#L178) while importing RNV just fine.

just leave it if its not broken. its not like yarn 1.22 will explode in any foreseeable future.

**Comment by yungblud** [comment]
I will close this issue for now.
as #4255 do similar stuffs. But I think we have to see for yarn 3 support after #4255 has been merged.

**Comment by freeboub** [comment]
For information, my new app at work uses yarn 3 without issues...
