### ISSUE TITLE
[BUG]: Player briefly shows a white content when switching away from and returning to the page

### ISSUE THREAD

**Issue by SeekingLight233** [TheWidlarzGroup/react-native-video#4254]
### Version

6.7.0

### What platforms are you having the problem on?

Android

### System Version

Android 12

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

I upgraded the react-native-video from version 6.1.0 to 6.7.0.

However, I found that when navigating away from and returning to the page using React Navigation, the player content briefly shows a white screen.

This issue did not occur in version 6.1.0, I'm not sure what changes were introduced in the versions between.

This is version 6.1.0, which works as we expected:

https://github.com/user-attachments/assets/427b4edb-1d48-48e3-a72f-53abcc72e399

This is version 6.7.0, and we can see that when navigating away and returning, the player content briefly turns white (we can adjust the playback speed to 0.25x to observe this).

https://github.com/user-attachments/assets/2c3c1ba0-b626-4a85-b5cb-a013b13840e0

### Reproduction Link

https://github.com/SeekingLight233/RnIssuePlayground

### Reproduction

Step to reproduce this bug are: 

1. Clone this project
https://github.com/SeekingLight233/RnIssuePlayground

2. Install dependencies with yarn and run yarn android

**Comment by pateljoel** [comment]
I've been getting this also, but when I rotate the phone with a video playing I also get this. I'm confused how this was introduced and not sure how to fix.

**Comment by sarthak-cars24** [comment]
Same issue can be seen on version: **6.10.2**
This should be reopened.
