### ISSUE TITLE
[BUG]: Duplicate audio and text tracks visible

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#4256]
### Version

6.7.0

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

A bug happened! video data includes duplicate data for audios and text tracks.

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: log tracks data in example app.

**Comment by freeboub** [comment]
can you please give more precision ? which asset asset ?  I don't reproduce the issue...

**Comment by mkbhdana** [comment]
> can you please give more precision ? which asset asset ? I don't reproduce the issue...

can i share you links which contain multiple tracks for audio and subtitles. I am facing this issue only in latest version of react native video
