### ISSUE TITLE
[BUG]: Build errors on iOS 18

### ISSUE THREAD

**Issue by TobiDevloft** [TheWidlarzGroup/react-native-video#4260]
### Version

6.7.0

### What platforms are you having the problem on?

iOS

### System Version

iOS 18 / MacOS 15.0 / Xcode 16.0

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

When I try to build my app on an iOS / emulator device after adding react-native-video, I get the following error:

`RCTPlayerObserver.swift:229:47 Extraneous argument label 'preferredTimescale:' in call`

Anyone experiencing similar issues?

### Reproduction

1. Add react-native-video to your project
2. Build the app on a device running >= iOS 18

**Comment by freeboub** [comment]
I just try to upgrade my xcode to 16.1, I don't have any build issue with bare sample in the repository.
Which react native version do you use ?
Would you be able to provide a small sample in a dedicated repository ?
