### ISSUE TITLE
[BUG]: toggling muted prop causes full rerender on RN 0.76.0

### ISSUE THREAD

**Issue by evoactivity** [TheWidlarzGroup/react-native-video#4261]
### Version

6.7.0

### What platforms are you having the problem on?

Android TV

### System Version

12

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

Toggling the muted prop causes the whole component to rerender and start the video again.

Downgrading RN back to 0.75.2 resolves the issue.

### Reproduction

Toggle the muted prop

**Comment by KrzysztofMoch** [comment]
Thanks for report, it's probably Interop Layer stuff - I am little busy right now but will you know once I check it

**Comment by felipegmg** [comment]
+1, subscribing. When I change the pause prop using state changing approach, it is causing the re-render behavior too. When I use a pause and resume methods, the video not re-render.

**Comment by felipegmg** [comment]
I just noticed a certain pattern regarding component rendering. It happens when any property coming from a state is modified (e.g.: paused, rate, selectedTextTrack, muted...)

**Comment by felipegmg** [comment]
@evoactivity any solution?

**Comment by evoactivity** [comment]
@felipegmg I've just downgraded back to 0.75. If I get some time before @KrzysztofMoch has a chance, I'll dig into the problem more indepth but I feel like it _might_ need proper support for the new architecture.

**Comment by felipegmg** [comment]
@evoactivity, for me it is impossible to downgrade. As I use the paused, muted, rate properties, I will use the ref object and other third-party libraries to manipulate these values. Anyway, thanks for the answer. Good job!

**Comment by evoactivity** [comment]
@felipegmg I don't understand why using those properties would stop you downgrading react native? Or trying without new architecture?

**Comment by freeboub** [comment]
@evoactivity @felipegmg can you confirm that you use bufferConfig prop ? Just to confirm something on my side

**Comment by felipegmg** [comment]
YEEES! And when I remove those props, the refresh not happen! Any solution/workaround to use bufferConfig and avoid this refresh? Thanks!

**Comment by freeboub** [comment]
This patch shall be OK for a quick workaround if you don't use cache on android.
In fact I already identify these lines as problematic and tracked the change to do here: https://github.com/TheWidlarzGroup/react-native-video/issues/2693

BufferConfig is the last remaining one...

```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index 1246d9fd..7d4c55b8 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -2373,8 +2373,6 @@ public class ReactExoplayerView extends FrameLayout implements
         } else {
             useCache = false;
         }
-        releasePlayer();
-        initializePlayer();
     }
 
     @Override
```

**Comment by freeboub** [comment]
I finally provide the good patch ...
