### ISSUE TITLE
the method : onProgress in react-native-video component is no use

### ISSUE THREAD

**Issue by superZchen0701** [TheWidlarzGroup/react-native-video#428]
I have installed the react-native-video component,and the config information in package.json shows here:
 "react": "^15.4.1",
 "react-native": "^0.39.2",
 "react-native-video": "^0.9.0"

And then my code shows here:
var Video=require('react-native-video').default;
                <Video
                        ref='videoPlayer'
                        source={{uri:data.video}}
                        volume={1}
                        paused={this.state.paused} 
                        rate={this.state.rate} 
                        muted={this.state.muted} 
                        resizeMode={this.state.resizeMode} 
                        repeat={this.state.repeat} 
                                    
                        onProgress={this._onProgress} />

_onProgress(data){       
        console.log(data)
        console.log('progress')
    }

Run in the iOS10.1 system,the video could play normally but the console have no printed data and 'progress'.I have tried to use onProgress={()=>this._onProgress}, but also no use.Anyone knows how to solve this?Thanks a lot.

**Comment by sreejithr** [comment]
I'm seeing this too. `onProgress` isn't working. It is central to my app. Was it working in earlier versions? Can I downgrade and get this working temporarily?

**Comment by sreejithr** [comment]
Related: #396

**Comment by larryranches** [comment]
Commit #381 fixes this which is in Master. I have a PR #419 to bump this project's version to have those commits. For a temp solution, you can update your package.json to pull from master.

**Comment by larryranches** [comment]
Commit #381 fixes this which is in Master. I have a PR #419 to bump this project's version to have those commits. For a temp solution, you can update your package.json to pull from master.

**Comment by ghost** [comment]
#480
