### ISSUE TITLE
[BUG]: `onEnd` Infinite Loop When Changing `source.uri`

### ISSUE THREAD

**Issue by JCYDigitalinnov** [TheWidlarzGroup/react-native-video#4280]
### Version

^6.7.0

### What platforms are you having the problem on?

iOS

### System Version

iOS 15

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

When switching video quality by updating `source.uri` (e.g., 480p, 720p, 1080p), the `onEnd` callback enters an infinite loop upon video completion. This issue only arises when `source.uri` is changed dynamically; if the URI remains unchanged, `onEnd` fires only once as expected.

### Reproduction

Step to reproduce this bug are: 
1. Use a state variable to manage the video URL.
2. Change the video URL during playback to switch resolution.
3. Resume the video from `previousCurrentTime`.
4. Observe that `onEnd` is triggered repeatedly after the video ends.

**Comment by freeboub** [comment]
can you share a sample app please ?

**Comment by JCYDigitalinnov** [comment]
> can you share a sample app please ?

Sorry! It was my code that causes the problem. As I try to reproduce the issue on new app, I found out the problem. 

Thank you for quick response!
