### ISSUE TITLE
[BUG]: v6+ causing build issues on iOS

### ISSUE THREAD

**Issue by Sewb21** [TheWidlarzGroup/react-native-video#4286]
### Version

6.7.0

### What platforms are you having the problem on?

iOS

### System Version

Tested on iOS 17 + 18

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

I have updated the react-native-video dependancy from 5.2.1 -> 6.7.0, I've tried fully clearing Pods, cache and DerivedData but I keep getting the following two errors when I build the project.

**Error 1:** `Type 'String' has no member 'playback'` 
**File:**  `NowPlayingInfoCenterManager.swift` - line 28

**Error 2:** `'pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)' has been renamed to 'picture(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)'` 
**File:**  `RCTPictureInPicture.swift` - line 38

### Reproduction Link

N/A

### Reproduction

Have **v6.7.0** of `react-native-video` installed alongside `react-native` **v0.75.4** and try to build the iOS project via Xcode or `react-native run-ios`

**Comment by freeboub** [comment]
can you provide the xcode version you use please ?

**Comment by Sewb21** [comment]
> can you provide the xcode version you use please ?

I am using Xcode version 16.1

**Comment by freeboub** [comment]
Can you provide a sample git repo with the issue ?

**Comment by Sewb21** [comment]
@freeboub So I've span up a project using the same env and deps as the project where we are experiencing the issue and it seems to work fine, there must be an issue on my end that I will debug further. Thanks for your time, I will close the ticket

**Comment by Sewb21** [comment]
This was due to the Swift version being outdated an incorrect, not an issue with the package

**Comment by jreybaylen** [comment]
@salhk how did you fixed this issue?

**Comment by QSJSI** [comment]
Same problem

**Comment by Sewb21** [comment]
> Same problem

My issue as mentioned above was that the version of Swift the project used was outdated and updating resolved it

**Comment by mmehul** [comment]
same issue for me , i am not able to build process and error Type 'String' has no member 'playback'

**Comment by mmehul** [comment]
same issue for me , i am not able to build process and error Type 'String' has no member 'playback'

**Comment by mmehul** [comment]
> > Same problem
> 
> My issue as mentioned above was that the version of Swift the project used was outdated and updating resolved it

what is the version that you are using before and what is the version after upgrading swift?
