### ISSUE TITLE
[BUG]: TypeError: Cannot read property 'bubblingEventTypes' of null

### ISSUE THREAD

**Issue by namikarif** [TheWidlarzGroup/react-native-video#4299]
### Version

6.8.0

### What platforms are you having the problem on?

iOS

### System Version

18.1

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

TypeError: Cannot read property 'bubblingEventTypes' of null

This error is located at:
    in RCTVideo (created by Video)
    in RCTView (created by View)
    in View (created by Video)
    in Video (created by StoryVideo)

### Reproduction Link

repository link

### Reproduction

import React, {useRef} from "react";
import {Dimensions, StyleSheet} from "react-native";
import Video from "react-native-video";

const {width, height} = Dimensions.get('window');

export const StoryVideo = ({url, duration, setLoad}) => {

    const videoRef = useRef<VideoRef>(null);
    return (
        <Video
            source={{
                uri: url,
            }}

            ref={videoRef}
            style={styles.backgroundVideo}
        />
    )
}
const styles = StyleSheet.create({
    video: {
        width,
        height,
        flex: 1
    },
});

"react-native-video": "^6.8.0",
"react-native-reanimated": "~3.16.1",
"react-native": "0.76.2",
 "expo": "~52.0.9",

**Comment by freeboub** [comment]
I have just had the same issue during expo 54 upgrade. strangely it was due compilation issue. react native video was not built into the app... Can you please double check react-native-video is well included in the build and provide a sample git repo if you still reproduce it.

**Comment by miguelpveloso** [comment]
I'm having the same on iOS, using Expo SDK 52. I tried to add the plugin on app.json, tried to "pod install" on /ios folder. No luck. It works on Android, Web but not iOS.

Is there any insight on this?

**Comment by jcubic** [comment]
Same error on Android Emulator, just created new expo project installed react-native-video and used this code:

```jsx
import Video from 'react-native-video';
<Video source={require('@/assets/test.mp4')} />
```

This is stripped example from README.

**Comment by moskalakamil** [comment]
Try the following steps:
```
remove node modules
remove yarn.lock
yarn install
cd ios && pod install && cd ..
cd android && ./gradlew clean && cd ..
yarn start --reset-cache
yarn ios/android
```

**Comment by jcubic** [comment]
I use expo and npm, I don't have android and ios directory.

**Comment by moskalakamil** [comment]
This is native package, you need to `yarn prebuild`

**Comment by jeeva-2311** [comment]
I am having the same error. Just adding  <Video/> throws the error

**Comment by KrisWozy** [comment]
I've got a demo here, basic expo app with Video component added here - [https://github.com/KrisWozy/ExpoDemo/blob/8b92afbf85b29f19b205c3324a1f651a0440a944/app/(tabs)/index.tsx#L53](url) 

Running android emulator via expo go produces the described error.

**Comment by KrisWozy** [comment]
I've got a demo here, basic expo app with Video component added here - https://github.com/KrisWozy/ExpoDemo/blob/8b92afbf85b29f19b205c3324a1f651a0440a944/app/(tabs)/index.tsx#L53

Running android emulator via expo go produces the described error.

**Comment by moskalakamil** [comment]
> Running android emulator via expo go produces the described error.

This is native package - that's mean that you need to prebuild you app first and run it in dev build
=> yarn prebuild --clean && cd ios && pod install && cd .. && yarn ios

You cannot run it with expo go - you have to run it in expo dev build

**Comment by freeboub** [comment]
```shell
git clone https://github.com/KrisWozy/ExpoDemo.git
cd ExpoDemo 
yarn
npx expo run:android 
```

Works also

**Comment by s0llvan** [comment]
> ```shell
> git clone https://github.com/KrisWozy/ExpoDemo.git
> cd ExpoDemo 
> yarn
> npx expo run:android 
> ```
> 
> Works also

Why was this issue closed ?

There is clearly a problem with the latest version of react-native-video because I have the same error, and it is not present in the version of the repository you mentioned.

Could we please reopen the issue ?
That would save me from creating another one.

**Comment by freeboub** [comment]
> > ```shell
> > git clone https://github.com/KrisWozy/ExpoDemo.git
> > cd ExpoDemo 
> > yarn
> > npx expo run:android 
> > ```
> > 
> > Works also
> 
> Why was this issue closed ?
> 
> There is clearly a problem with the latest version of react-native-video because I have the same error, and it is not present in the version of the repository you mentioned.
> 
> Could we please reopen the issue ?
> That would save me from creating another one.

Please provide other reproduction step and I will reopen

**Comment by s0llvan** [comment]
> > > ```shell
> > > git clone https://github.com/KrisWozy/ExpoDemo.git
> > > cd ExpoDemo 
> > > yarn
> > > npx expo run:android 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Works also
> > 
> > 
> > Why was this issue closed ?
> > There is clearly a problem with the latest version of react-native-video because I have the same error, and it is not present in the version of the repository you mentioned.
> > Could we please reopen the issue ?
> > That would save me from creating another one.
> 
> Please provide other reproduction step and I will reopen

Sorry, my mistake

**Comment by dadpenguin** [comment]
so we need ios hardware to fix the issue for development build?

**Comment by Aastha-1008** [comment]
I am also getting the same issue. Any solution ??

**Comment by jeeva-2311** [comment]
You can try updating rn. 
If that doesn't work. Create a new project with any of the expo default templates which comes with reanimated pre-installed. Then port your project to this new project. I know this is a lot of work. But this is the only one I found that definitely works

**Comment by sunkehappy** [comment]
> This is native package, you need to `yarn prebuild`

Finally I get the idea. Just run `npx expo run:ios` Then it would produce the iOS directory. Then the error is gone.

**Comment by ncs-ankur** [comment]
Hi team, thanks for your work on this library.

Just wanted to add that we’re still encountering this issue specifically when running the app with the following command:
```
npx expo run --clear
```
However, when running the app using either of these commands:
```
npx expo run:android
# or
npx expo run:ios
```
…the issue does not appear.

We’ve tried typical fixes like removing `node_modules`, deleting `yarn.lock`, and rebuilding the project, but nothing seems to resolve it.

It might be worth re-opening this issue, as it still affects users under certain conditions.

Thanks again!

**Comment by moskalakamil** [comment]
This is exactly the issue when running the app with those commands @ncs-ankur. When you run `npx expo start`, the app launches with Expo Go, and you **can’t** use native modules. However, if you run `npx expo run:android`, the app launches in a development build, and you **can** use native modules.
