### ISSUE TITLE
Issues removing the component.

### ISSUE THREAD

**Issue by dhrrgn** [TheWidlarzGroup/react-native-video#43]
We are having issues removing a `Video` component.  By removing I mean, It being rendered is dependent on a `state` value.  So, when the value is `false` the Video is not rendered.

If the video was previously rendered, and we remove it (due to a state change), it crashes with the following error:

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <RCTVideo 0x15fe92a00> for the key path "status" from <AVPlayerItem 0x17001ea00> because it is not registered as an observer.'
```

My colleagues and I did some digging this is the line that causes the crash: https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L324

When I setup a breakpoint, I notice something odd: `removeFromSuperview` is getting called twice.  Once when the layout is re-rendered when I remove the Video component (it goes through fine here), and then is called again when I `pop` the current route off of the `navigator`, and this is when it crashes.

i know this is an odd thing, so let me know if that doesn't make sense.

**Comment by dhrrgn** [comment]
I will also note, just in case it means anything, that line is also called here (without issue): https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L99

**Comment by stephenplusplus** [comment]
I'm getting this as well. Have you found any workarounds?

**Comment by brentvatne** [comment]
cc @johanneslumpe

**Comment by brentvatne** [comment]
I think all we have to do here is add a try/catch block around `[_playerItem removeObserver:self forKeyPath:statusKeyPath];`, I'll try this out

**Comment by johanneslumpe** [comment]
@brentvatne Yeah we can try that, but I'm curious why this would happen in the first place. We might as well just set a flag when register for a notification on a player item. And in `removeFromSuperView` we can check whether the flag is set or not, and then we can act accordingly.

**Comment by brentvatne** [comment]
@johanneslumpe - sounds good to me, I'll do that now

**Comment by brentvatne** [comment]
Fixed in `0.4.1`: https://github.com/brentvatne/react-native-video/commit/c5eb6b4fec7a382789fc074c23ef2f7f71d9b010

@stephenplusplus @dhrrgn - give it a try and let me know if you still have the issue

**Comment by johanneslumpe** [comment]
:+1:

**Comment by dhrrgn** [comment]
@brentvatne Works for me
