### ISSUE TITLE
[BUG]: Unintentional player update after switching to a new architecture

### ISSUE THREAD

**Issue by fendermany** [TheWidlarzGroup/react-native-video#4300]
### Version

6.8.0

### What platforms are you having the problem on?

Android

### System Version

Android 13 (API Level 33)

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

On start/pause by changing state the player is reloaded: onLoad, onLoadStart events are fired. 

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: 
Reproducable if bufferConfig parameter is set (even empty) for `<Video/>` component

**Comment by freeboub** [comment]
yep, already tracked here: https://github.com/TheWidlarzGroup/react-native-video/issues/4261
And a workaround was provided. Need to implement a clear fix for sure !
