### ISSUE TITLE
[BUG]: Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

### ISSUE THREAD

**Issue by Ibad9** [TheWidlarzGroup/react-native-video#4309]
### Version

6.8.2

### What platforms are you having the problem on?

Android TV

### System Version

Android 14

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

Whenever i try to render the Video component, I get the following error "Warning: TypeError: Cannot read property 'bubblingEventTypes' of null" and my app crashes. I also tried to toggle off the new architecture but it says in console that expo go has by default turned it on.

### Reproduction Link

repository link

### Reproduction

dependencies: 

"dependencies": {
    "@expo/vector-icons": "^14.0.4",
    "@shopify/flash-list": "1.7.1",
    "expo": "~52.0.2",
    "expo-build-properties": "~0.13.1",
    "expo-constants": "~17.0.2",
    "expo-font": "~13.0.1",
    "expo-image": "^2.0.1",
    "expo-linking": "~7.0.2",
    "expo-router": "~4.0.2",
    "expo-splash-screen": "~0.29.6",
    "expo-status-bar": "~2.0.0",
    "expo-system-ui": "~4.0.2",
    "expo-web-browser": "~14.0.0",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "npm:react-native-tvos@0.76.1-1",
    "react-native-awesome-slider": "^2.5.6",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "4.0.0",
    "react-native-video": "^6.8.2",
    "react-native-web": "~0.19.10"
  },
  
  
  
  Component : 
  
  
  import Home from "@/components/home";
import { StyleSheet, View } from "react-native";
import Video, { ViewType } from "react-native-video";

export default function Index() {

  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#182232",
      }}
    >
      <Video
        source={{ uri: 'https://example.com/video.mp4' }}
        style={[StyleSheet.absoluteFillObject]}
        viewType={ViewType.TEXTURE}
        controls
        focusable
        showNotificationControls={false}
        resizeMode='contain'
      />
    </View>
  );
}

**Comment by Ibad9** [comment]
<img width="564" alt="Screenshot 2024-11-27 at 7 35 53 PM" src="https://github.com/user-attachments/assets/eea7a69b-6725-4b3b-a9b9-19777ef5c700">

**Comment by moskalakamil** [comment]
Hi @Ibad9, make sure you have correctly linked react-native-video library in package.json, then try the following:

- remove node modules
- remove yarn.lock
- yarn install
- cd ios && pod install && cd ..
- yarn start --reset-cache
- yarn ios

**Comment by Ibad9** [comment]
@moskalakamil I am currently running on android only. 

I have also deleted and reinstalled node modules as well as cleared the cache.

**Comment by miguelpveloso** [comment]
I'm having the same on iOS, using Expo SDK 52. I tried to add the plugin on app.json, tried to "pod install" on /ios folder. No luck. It works on Android, Web but not iOS.

Is there any insight on this?

**Comment by freeboub** [comment]
Can someone provide a sample in a git repository to reproduce the issue ?

**Comment by miguelpveloso** [comment]
I cannot share the repo as this is a corporate project but I can provide you with the package.json, app.json and the components where I'm trying to use the video component.

package.json
```javascript
{
  "name": "...",
  "main": "expo-router/entry",
  "license": "0BSD",
  "version": "1.0.0",
  "scripts": {
    "start": "npx expo start",
    "android": "npx expo start --android",
    "ios": "npx expo start --ios",
    "web": "npx expo start --web",
    "test": "jest --watchAll",
    "build:web": "npx expo export -p web"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.7",
    "expo-font": "~13.0.1",
    "expo-linking": "~7.0.2",
    "expo-router": "~4.0.6",
    "expo-splash-screen": "~0.29.11",
    "expo-status-bar": "~2.0.0",
    "expo-system-ui": "~4.0.3",
    "expo-web-browser": "~14.0.1",
    "i18next": "^23.16.5",
    "intl-pluralrules": "^2.0.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-i18next": "^15.1.1",
    "react-native": "0.76.2",
    "react-native-animated-pagination-dot": "^0.4.0",
    "react-native-gesture-handler": "^2.21.1",
    "react-native-reanimated": "^3.16.1",
    "react-native-reanimated-carousel": "^4.0.0-canary.17",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.0.0",
    "react-native-video": "^6.8.2",
    "react-native-web": "~0.19.13",
    "sass": "^1.81.0",
    "sass-loader": "^16.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/react": "~18.3.12",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "prettier": "^3.3.3",
    "react-test-renderer": "18.3.1",
    "typescript": "~5.3.3"
  },
  "private": true
}
``` 

app.json
```javascript
{
  "expo": {
    "name": "...",
    "slug": "...",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "newArchEnabled": true,
    "splash": {
      "image": "./assets/images/splash-icon.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "..."
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "..."
    },
    "web": {
      "bundler": "metro",
      "output": "single",
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": [
      "expo-router",
      [
        "react-native-video",
        {
          "enableNotificationControls": true,
          "androidExtensions": {
            "useExoplayerRtsp": false,
            "useExoplayerSmoothStreaming": false,
            "useExoplayerHls": false,
            "useExoplayerDash": false
          }
        }
      ]
    ],
    "experiments": {
      "typedRoutes": true
    },
    "extra": {
      "router": {
        "origin": false
      },
      "eas": {
        "projectId": "..."
      }
    },
    "owner": "..."
  }
}
```

sceen.tsx
```javascript
const webContainer: ViewStyle = {
  // @ts-ignore: Property 'scrollSnapType' does not exist on type 'ViewStyle'
  scrollSnapType: 'y mandatory',
};

export default function ModalScreen() {
  const [videos, setVideos] = useState([1, 2, 3, 4, 5, 6]);
  const [page, setPage] = useState(1);

  const handleEndReached = () => {
    setPage((prevPage) => prevPage + 1);
  };

  const source = require('@/assets/video/test.mp4');

  return (
    <FlatList
      data={videos}
      renderItem={({ item }) => <VideoPlayer source={source} />}
      keyExtractor={(item, index) => index.toString()}
      onEndReached={handleEndReached}
      onEndReachedThreshold={1}
      pagingEnabled
      showsVerticalScrollIndicator={false}
      snapToInterval={height}
      snapToAlignment="start"
      decelerationRate="fast"
      contentContainerStyle={Platform.OS === 'web' ? webContainer : {}}
    />
  );
}
```

VideoPlayer.tsx
```javascript
import React, { useRef } from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import Video, { VideoRef } from 'react-native-video';

export default function VideoPlayer({ source }) {
  const videoRef = useRef<VideoRef>(null);

  console.log(source);

  return (
    <View style={styles.videoContainer}>
      <Video
        source={{ uri: source }}
        ref={videoRef}
        onBuffer={(e) => console.log(e)}
        onError={(e) => console.log(e)}
        style={styles.backgroundVideo}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  videoContainer: {
    height: Dimensions.get('window').height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundVideo: {
    width: '100%',
    height: '100%',
  },
});
```

**Comment by freeboub** [comment]
Same issue here: https://github.com/Shopify/flash-list/issues/1352

**Comment by Ibad9** [comment]
@freeboub some comments suggest reinstalling the node module but I am not able to run after doing it either. Whenever i try to render Video component same error comes and app crashes.

**Comment by freeboub** [comment]
@Ibad9 you must provide a sample to be able to reproduce the issue. I cannot help more here, But 95% sure this is not linked to the package

**Comment by KrisWozy** [comment]
I'm encountering the same issue. Fresh build with create-expo-app, add a Video component into the project and the Android emulator crashes with "Warning: TypeError: Cannot read property 'bubblingEventTypes' of null". Doesn't seem to have a problem when running in web just android emulator.

**Comment by freeboub** [comment]
Please consider that the expo sample in this repo is working with react 0.76 & new architecture enable. I can only suspect something in your app unless you provide a reproducible sample git repository ...

**Comment by freeboub** [comment]
duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/4299

**Comment by Ibad9** [comment]
@freeboub I don't know what's the issue. But I have managed to run it.

Whenever i get "Warning: TypeError: Cannot read property 'bubblingEventTypes' of null"

I just run "npx expo prebuild --clean" and then "npm run android" and the player starts working. Don't know why it's happening.


My issue is some what resolved as I am able to use the library but not sure about the real issue. I also needed one help regarding the expo video plugin. We only have these properties there.

"enableNotificationControls": true,
        "androidExtensions": {
          "useExoplayerRtsp": false,
          "useExoplayerSmoothStreaming": false,
          "useExoplayerHls": false,
          "useExoplayerDash": false,
        }
        
For using IMA sdk what should I do ?

**Comment by moskalakamil** [comment]
> My issue is some what resolved as I am able to use the library but not sure about the real issue. I also needed one help regarding the expo video plugin. We only have these properties there.
> 
> "enableNotificationControls": true, "androidExtensions": { "useExoplayerRtsp": false, "useExoplayerSmoothStreaming": false, "useExoplayerHls": false, "useExoplayerDash": false, }
> 
> For using IMA sdk what should I do ?

@Ibad9 
"enableADSExtension": true
referring to https://docs.thewidlarzgroup.com/react-native-video/other/expo#expo-plugin-properties

**Comment by freeboub** [comment]
see https://github.com/TheWidlarzGroup/react-native-video/issues/4299 to get the solution

**Comment by Sukomal07** [comment]
> [@freeboub](https://github.com/freeboub) I don't know what's the issue. But I have managed to run it.
> 
> Whenever i get "Warning: TypeError: Cannot read property 'bubblingEventTypes' of null"
> 
> I just run "npx expo prebuild --clean" and then "npm run android" and the player starts working. Don't know why it's happening.
> 
> My issue is some what resolved as I am able to use the library but not sure about the real issue. I also needed one help regarding the expo video plugin. We only have these properties there.
> 
> "enableNotificationControls": true, "androidExtensions": { "useExoplayerRtsp": false, "useExoplayerSmoothStreaming": false, "useExoplayerHls": false, "useExoplayerDash": false, }
> 
> For using IMA sdk what should I do ?

When run app using `npm run start` the issue comes
