### ISSUE TITLE
component refuses to work when Network connectivity is off

### ISSUE THREAD

**Issue by maboelsoud** [TheWidlarzGroup/react-native-video#431]
I try to play a video locally by importing it:
`let sktToddler = require('../../assets/skateboard_toddler.mp4');`

then i use it in the video component:
```
<Video {...props}
          source={sktToddler}
          rate={1.0}
          muted={true}
          resizeMode="cover"
          repeat={true}
          onLoadStart={()=>{console.log("onLoadStart");}}
          onLoad={()=>{console.log("onLoad");}}
          onError={(err)=>console.log("an error has happened!", err)}
          style={{position: 'absolute', top: 0, left: 0, bottom: 0, right: 0}}/>
```

And this works great when the WIFI is on. But when I turn it off i get a bunch of errors (that i log to the console from the `onError` prop), more specifically this:
`{error: { code: -1, domain: "NSURLErrorDomain"}, target: 18}`
and:
`{error: { code: -1, domain: "NSURLErrorDomain"}, target: 10}`

What does it actually do connecting to the internet, if there isn't a need to do so? Can we restrict network connectivity unless it's necessary? I would like this to somewhat work if the user turns the WIFI off.

**Comment by alisonkohl** [comment]
+1, also experiencing this on RN 0.36.0

**Comment by br4nnigan** [comment]
Same, with rn 0.40.0. No internet, no video (local file).

but i'm not even getting error (or any) events, see #458

**Comment by gshotwell** [comment]
+1 I'm also experiencing this, no network connection cannot play local files, any update?

**Comment by erikpoort** [comment]
Seems to me this is only on simulator and it doesn't occur on the 9.3 simulator.

**Comment by sangupandi** [comment]
Video is not playing/buffering on Network-Connectivity changes. How to resolve this??

**Comment by leejunhui** [comment]
It seems this problem not sovled by the maintainer of the repo,so the reasonable solution could be writing the Network-Connectivity related logic in the source code.
