### ISSUE TITLE
[BUG]: On Android only : Video inside action sheet with scroll are out of boundes

### ISSUE THREAD

**Issue by edenmeshulam** [TheWidlarzGroup/react-native-video#4310]
### Version

latest

### What platforms are you having the problem on?

Android

### System Version

latest

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?

When i scroll down inside action sheet the video is out from the action sheet

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: video inside action sheet with scrollview
![image](https://github.com/user-attachments/assets/1b71439b-1b02-417e-a108-88a2d70f174d)

**Comment by freeboub** [comment]
I think you should try with textureView

**Comment by edenmeshulam** [comment]
> I think you should try with textureView
 
Thanks @freeboub using viewType={0} (TEXTURE) was solved my problem!, thank a lot

**Comment by NicoTorteli** [comment]
Hi @freeboub  
when we tried viewType={0} (TEXTURE) we get a black screen.
This is what we get, but only when there are 2 consecutive videos in our list. When there is a photo after the video stays within the action sheet.
![screenshot_20241204-233219_720-1](https://github.com/user-attachments/assets/58f0a4dd-70da-406b-8144-dfc98023210e)

Just for context:
"react-native": "0.74.4"
"react-native-video": "^6.8.2" 

Any tips?
