### ISSUE TITLE
[BUG]: onBuffer function is not working on android.Meanwhile its working fine on IOS

### ISSUE THREAD

**Issue by Shahjahan62** [TheWidlarzGroup/react-native-video#4315]
### Version

5.2.1

### What platforms are you having the problem on?

Android

### System Version

android 13

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

A bug happened! when there is video buffering started loading is showing on IOS and onBuffer function is working fine.But in case of android onBuffer is not working

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
There is no more support on version 5.2.1.
Should be retested on last V6 version
