### ISSUE TITLE
[BUG]: Embedded HLS subtitles cannot be switched off on iOS

### ISSUE THREAD

**Issue by proohit** [TheWidlarzGroup/react-native-video#4318]
### Version

6.8.0

### What platforms are you having the problem on?

iOS

### System Version

17.5.1

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Embedded captions in HLS streams seem to be always rendered, even though no `selectedTextTrack` is provided. The text tracks are correctly found in the media file(s). This seems to be a native issue.

Android is working correctly. We toggle captions with `selectedTextTrack`.

### Reproduction

I would love to provide a repro, but I cannot share a video url. Maybe you have a HLS stream with embedded subtitles?

**Comment by proohit** [comment]
also present in 6.8.1 and 6.8.2

**Comment by proohit** [comment]
upon investigation, it seems that the default `SelectedTrackType` is `none`, which doesn't seem to disable subtitles. Maybe, `RCTPlayerOperations#setMediaSelectionTrackForCharacteristic` should also handle `type=="none"` and `type==""`. I can provide a PR for that.

**Comment by KrzysztofMoch** [comment]
Fix will be included in next release! Thanks @proohit!

**Comment by mlazari** [comment]
@KrzysztofMoch @proohit I think the behaviour before the changes in https://github.com/TheWidlarzGroup/react-native-video/pull/4319 was the correct one. Also that change caused the audio to be turned off by default on iOS (https://github.com/TheWidlarzGroup/react-native-video/issues/4400) which also seems incorrect. See my PR that reverts those changes for more details: https://github.com/TheWidlarzGroup/react-native-video/pull/4409

**Comment by freeboub** [comment]
@proohit your PR has been reverted, please see @mlazari comment.
