### ISSUE TITLE
[BUG]: iOS - Video does not stay paused when app moves from background to foreground

### ISSUE THREAD

**Issue by giodevcoding** [TheWidlarzGroup/react-native-video#4321]
### Version

6.8.1

### What platforms are you having the problem on?

iOS

### System Version

iOS 18.0

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

New architecture with interop layer

### What happened?
When my app is in the background and current video is paused via native controls, the video **does not** stay paused and instead resumes playing when the app is foregrounded

What I expected was that when my app is in the background and the current video is paused via native controls, the video should continue to be paused when I foreground the app.

#### Potential Cause & Fix
I did some digging in order to create a patch for my app, and came across what I believe was the cause, and I did create a fix as well that is working smoothly for me. I've specified more details of the cause and fix in this PR: https://github.com/TheWidlarzGroup/react-native-video/pull/4320

### Reproduction Link
*No response*

### Reproduction

1. Open Video
2. Pause Video
3. Background App
4. Foreground App
5. Video should automatically start playing on foregrounding

**Comment by giodevcoding** [comment]
Resolved by the merging of https://github.com/TheWidlarzGroup/react-native-video/pull/4320

**Comment by freeboub** [comment]
The PR will be reverted as it causes a major regression.
The issue is that the fix you want to do is liked on controls. We cannot handle thin playback management on ios with controls enable. As you understand the issue I think you can try to workaround it by calling pause when app goes in foreground.

**Comment by giodevcoding** [comment]
> The PR will be reverted as it causes a major regression.
> The issue is that the fix you want to do is liked on controls. We cannot handle thin playback management on ios with controls enable. As you understand the issue I think you can try to workaround it by calling pause when app goes in foreground.

I'm not sure I understand what you're describing, but my team has had this implemented on iOS with controls enabled and have had no issues. 

Can you explain what the major regression you're referring to is?

**Comment by freeboub** [comment]
@giodevcoding here is the issue: https://github.com/TheWidlarzGroup/react-native-video/issues/4373

I tried to put a `if (control)` around your patch but I had another issue, If I remember well, I had the other bad behavior. If I move to background while playing, the playback is paused when I come back to the app...
Please consider that the AVPlayer control implementation is not flexible and here we are trying to patch business logic.
If you have a better solution, I am open to discuss !

**Comment by freeboub** [comment]
@giodevcoding I will release a version with only the addtional if, it will be OK

**Comment by giodevcoding** [comment]
@freeboub Oh okay, great! I actually just encountered the issue on our app you described and remembered this feed, and I did the same thing of wrapping it with that if. Glad that it appears to work. If any other issues arise as a result, I can see about taking some time looking for alternative fixes.
