### ISSUE TITLE
Don't preload video prop

### ISSUE THREAD

**Issue by logileifs** [TheWidlarzGroup/react-native-video#433]
It would be really nice if there was a prop you could set to stop video from preloading and only load when play is pressed or on an explicit call to load.

The use case I'm dealing with is that I have multiple videos in one view and it seems they are all loaded into memory even though they are not playing. This causes my app to crash once it reaches a certain number of videos.

I think preventing preloading could probably solve that issue. I propose that the first frame of the video would only be loaded (unless a poster is set) if preload would be true, similar to html5 video

**Comment by sahimar90** [comment]
react-native-video is amazing. but i don't see preload. the preload is required to wait for loading video. please add preload. thanks for advanced. 👍

**Comment by cobarx** [comment]
There's no way to do this at the moment, but you can get the same effect by creating a placeholder component that displays a thumbnail or other view and then sets state to load the video when you press it.

**Comment by k3v1n-uncle** [comment]
how can i sets state to load the video when i press it.i dont want the video loading when the page show,i want to press start button then the video will load,thx

**Comment by juanjsebgarcia** [comment]
Hate to be the one to necromance such an old thread, but what's the best way to do this in late 2019? I want to avoid any network traffic until I explicitly ask the player to play. Does the `paused` parameter achieve this?

**Comment by juanjsebgarcia** [comment]
I ended up using `expo-av` through `react-native-unimodules`. Which is a bit heavy handed but I was able to get the API to do what I needed.

**Comment by mladenp** [comment]
I just figured out that there is not way to stop loading of videos, i am using it in Flatlist, is there any workaround besides using `expo-av` as @juanjsebgarcia suggested?
It is real pain to get expo-av working.

**Comment by juanjsebgarcia** [comment]
@mladenp I would suggest you just move to `expo-av` this `react-native-video` package feels abandoned and I found it to be very buggy when I was implementing it. It's a shame, and I hope it does progress given its the most popular `video` package.

**Comment by StanislavMayorov** [comment]
@mladenp Hi. Did you find any solution?

**Comment by hueniverse** [comment]
Consolidated into #2668
