### ISSUE TITLE
Broken for React Native 0.40.0

### ISSUE THREAD

**Issue by mosesoak** [TheWidlarzGroup/react-native-video#434]
1. Init a new react-native 0.40.0 project
2. add react-native-video module
2. build in Xcode

Multiple "previous declaration" errors halt the build.

![screen shot 2017-01-05 at 10 15 24 am](https://cloud.githubusercontent.com/assets/24345/21692075/0d49e1ea-d330-11e6-9a49-8c356b74dc80.png)

**Comment by Lepozepo** [comment]
As expressed [here](https://github.com/facebook/react-native/releases/tag/v0.40.0) all packages are now incompatible with 0.40.

**Comment by mosesoak** [comment]
Bummer. We use a lot of libraries and this is the only one that got broken aside from VectorIcons.

So what's the plan, should we work on fixing the imports in this library, and perhaps release that in a feature branch for now until enough folks are using 0.40.0?

**Comment by mosesoak** [comment]
This is not a full fix, the module and its example are broken, but it works as a  patch when using the module in a react native 0.40. project: https://github.com/Instrument/react-native-video/commit/79b23b26423827fa28dba238ac5bcbb46533dabd

**Comment by mosesoak** [comment]
^ I just updated the link in the previous comment, the first try didn't work right.

**Comment by mosesoak** [comment]
I found that one of the failing imports could safely be removed and the standalone module project would still build. (see code comment in my commit above)

That just leaves one import that needs to be made to work for both cases, in RCTVideo.h. 

- The static library import `<React/RCTView.h>` works when used as a node module in an example project, but doesn't work in the current project

**Comment by hellogerard** [comment]
#437 should fix this, once it is merged and published.

**Comment by ferbass** [comment]
The version with the fix needs to be published

https://github.com/react-native-community/react-native-video/issues/447

**Comment by ghost** [comment]
Update to RNV 1.0 for RN 0.40 support.
