### ISSUE TITLE
[BUG]: errorrr {"error": {"code": -11828, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Open", "localizedFailureReason": "This media format is not supported.", "localizedRecoverySuggestion": ""}, "target": 8743}

### ISSUE THREAD

**Issue by lavarajallu** [TheWidlarzGroup/react-native-video#4349]
### Version

^5.21

### What platforms are you having the problem on?

iOS, Android

### System Version

MacOS

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

A bug happened!
errorrr {"error": {"code": -11828, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Open", "localizedFailureReason": "This media format is not supported.", "localizedRecoverySuggestion": ""}, "target": 8743}

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: 
errorrr {"error": {"code": -11828, "domain": "AVFoundationErrorDomain", "localizedDescription": "Cannot Open", "localizedFailureReason": "This media format is not supported.", "localizedRecoverySuggestion": ""}, "target": 8743}

**Comment by freeboub** [comment]
error seems to be clear: This media format is not supported.
