### ISSUE TITLE
No proptype for native prop RCTVideo.progressUpdateInterval 

### ISSUE THREAD

**Issue by EliteMarauder** [TheWidlarzGroup/react-native-video#435]
I use react-native-video in my react-native project. I run it on ios simulator and meet this error: 
"'Video' has no propType for native prop 'RCTVideo.progressUpdateInterval' of native type 'float'. If you havent' changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away".
Detail:
<unknown>
Video.js: 224

It seems like the RCTVideo native component and Video.js file are out of sync. So please show me how to fix it?

**Comment by johnbryant** [comment]
same error
![image](https://cloud.githubusercontent.com/assets/5527451/21960318/c74dddaa-db21-11e6-80f0-20bf7ea11f8e.png)

**Comment by felipecocco** [comment]
+1

**Comment by cherniv** [comment]
+1 :(

**Comment by cherniv** [comment]
For me it was my mistake, my packager ran from different project' folder. Closed it and re-ran it from the right folder and it worked..

**Comment by KatSick** [comment]
+1

**Comment by sayhei** [comment]
+1

**Comment by muhammedkanlidere** [comment]
I just downgrade my version 0.9.0 and get this error is there any solution for this ?

**Comment by eyalcohen4** [comment]
+1 on 1.0.0

UPDATE: My bad! 
if you came here from searching, check out [this](https://stackoverflow.com/questions/38520003/react-native-no-proptype-for-native-prop-rctview-maxheight) answer. my problem was with Packager.

**Comment by HouLinguo** [comment]
`react-native-video version3.2.1`

Video.js line 3
```js
import {StyleSheet, requireNativeComponent, NativeModules, ViewPropTypes as RNViewPropTypes,	View,Image, Platform} from 'react-native';
const ViewPropTypes = RNViewPropTypes || View.propTypes; //add
```
