### ISSUE TITLE
[BUG]: Vimeo url not playing [WARN  Trying to load empty source.]

### ISSUE THREAD

**Issue by lavarajallu** [TheWidlarzGroup/react-native-video#4351]
### Version

^5.21

### What platforms are you having the problem on?

iOS, Android

### System Version

MacOS

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

A bug happened! When I give public or sample Vimeo URL video is not playing
<img width="410" alt="Screenshot 2024-12-27 at 10 18 11 PM" src="https://github.com/user-attachments/assets/44b3d6d0-5fc5-40d1-8c58-7f457f290d44" />

### Reproduction Link

repository link

### Reproduction

Steps to reproduce this bug are: 
<img width="410" alt="Screenshot 2024-12-27 at 10 18 11 PM" src="https://github.com/user-attachments/assets/34ddbb60-b0c3-4306-ad1e-ccaa9e36c986" />
I just Integrated 
`            <Video
              source={{
                uri:
                  props.activityType === 'conceptual_video'
                    ? props.vimeourl
                    : normaldata.url,
                headers: {
                  Referer: 'https://login.iqcandy.com/',
                },
              }} // Can be a URL or a local file.
              ref={playerRef}
              paused={isPlaying}
              progressUpdateInterval={900}
              //controls={true}
              // fullscreen={true}                          // Store referenc              // Callback when video cannot be loaded
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                bottom: 0,
                right: 0,
                elevation: 20,
              }}
              onLoad={onLoad}
              onError={(err) => console.log('errorrr', err)}
              resizeMode={fullscreen ? 'cover' : 'contain'}
              onProgress={onProgress}
            />`
<img width="418" alt="Screenshot 2024-12-27 at 11 02 22 PM" src="https://github.com/user-attachments/assets/1576e9bb-f8ef-4e5a-a5ba-9c23e8e42a49" />

**Comment by freeboub** [comment]
no support done on 5.2, you should try on V6 version

**Comment by SujathaChristy** [comment]
Not able to play a vimeo video url
