### ISSUE TITLE
repeat={true} doesnt trigger onProgress

### ISSUE THREAD

**Issue by proProbe** [TheWidlarzGroup/react-native-video#436]
Hello! Thanks for the awesome library!
I've noticed that by having repeat={true} does not trigger `onProgress`. Is this intentional?
My current code is the following: 
```
<Video source={{uri: this.props.video_src}}   // Can be a URL or a local file.
  rate={1.0}                     // 0 is paused, 1 is normal.
  volume={1.0}                   // 0 is muted, 1 is normal.
  muted={this.state.muted}                  // Mutes the audio entirely.
  paused={false}                 // Pauses playback entirely.
  resizeMode="cover"             // Fill the whole screen at aspect ratio.
  repeat={true}                  // Repeat forever.
  playInBackground={false}       // Audio continues to play when app entering background.
  playWhenInactive={false}       // [iOS] Video continues to play when control or notification center are shown.
  progressUpdateInterval={250.0} // [iOS] Interval to fire onProgress (default to ~250ms)
  onLoadStart={this._videoLoadStart}   // Callback when video starts to load
  onLoad={this._videoLoadEnd}      // Callback when video loads
  onProgress={this._setVideoProgress}      // Callback every ~250ms with currentTime
  onEnd={this._setVideoEnd}             // Callback when playback finishes

...
```
Why this troubles me is that Im having a `countdown` that count down how many seconds there still are in the video. This is reset when the video ends but when it repeats itself, the `onProgress` does not actually trigger which makes my code only work once but not after that.

**Comment by flybayer** [comment]
Hmm, `onProgress` is being called for me, even when `repeat=true`

Are you still having this problem with `v1.0.0`?

**Comment by proProbe** [comment]
Oh this should perhaps have been closed. I realized that my old `nexus 4` was the culprit. That phone didnt trigger the onProgress. After testing it out on other phones, ths `onProgress` triggers correctly
