### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by dazziola** [TheWidlarzGroup/react-native-video#438]
I'm having a similar issue that has come up before #354 but none of the solutions mentioned remedy my problem.

![screen shot 2017-01-08 at 21 47 01](https://cloud.githubusercontent.com/assets/1335585/21753810/50a3c62c-d5ec-11e6-87ea-084ef886d5ef.png)

My versions are:

    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-video": "^0.9.0",

Any suggestions would be great. I had this working before with a previous version of RN but it was a good few iterations before 0.40.

Edit: I've linked the libraries, and the libRCTVideo.a do appear in the linked libraries section in XCode, however they do not seem to make it into /ios/build/Build/Products/DebusiPhoneSimulator/. does not include the libRCTVideo.a file. Nothing I seem to do create the correct libRCTVideo.a file here, so this could be part of the problem.

Thanks all!

Darragh

**Comment by feng-he** [comment]
come up with this problem too, hope for any solutions

**Comment by JoelHensley** [comment]
Same issue as well

**Comment by benterprise** [comment]
same here

**Comment by timmywil** [comment]
Anyone find a workaround or solution?

**Comment by timmywil** [comment]
By the way, I only run into this during testing. Reinstalling/relinking seems to fix it in the ios simulator.

**Comment by roysG** [comment]
I found the solution that fixed me the problem.

Go to.. xCode -> Build Phases -> Link Binary With Libraries.

In the list find the file "libRCTVideo.a", if you will see it like icon of clean white paper than just delete it from the list and add it again by click on the plus (+) icon and just type "video" and add it.

Now in the commnd line run the commnad: "react-native run-ios", and "WALLA" no error.

**Comment by ghost** [comment]
Please upgrade to RNV 1.0

**Comment by pjpsoft** [comment]
roysG's solution worked for me.

**Comment by ravalikarumuri** [comment]
roysG's solution worked for me.

**Comment by Farhadkm** [comment]
For me, Ill I needed to do was to use "react-native link" and then use "pod install"

**Comment by damassi** [comment]
When using CocoaPods, one might have to link it manually in the podfile:

```rb
pod 'react-native-video', :path => File.join(node_modules_path, 'react-native-video/react-native-video.podspec')
```

**Comment by ManishAhire** [comment]
For me,

1. ` react-native link react-native-video`
2. `npm start`

**Comment by ghost** [comment]
> For me,
> 
> 1. ` react-native link react-native-video`
> 2. `nom start`

nom nom nom :D

**Comment by ManishAhire** [comment]
> > For me,
> > 
> > 1. ` react-native link react-native-video`
> > 2. `nom start`
> 
> nom nom nom :D

@jhabdas  Its by mistake bro.  But thanks for your good reply.

**Comment by ghost** [comment]
You're just one alias away from making npm modules even easier to consume. 😋

**Comment by CyrusZei** [comment]
For anybody that did not get this to work and got that "constant" error. This is how I solved it 👍 

1. yarn add react-native-video
2. open up your `[Project name].xcworkspace`
3. right click on your `librariers
4. click on "add files to [Project name]"
5. Go to your node_modules
6. find `react-native-video`
7. open up `ios` folder
8. There should be a `RCTVideo.xcodeproj` file
9. Add the file `RCTVideo.xcodeproj`
10. go to `Build Phases`
11. Expand `Link Binary with Libraries`
12. Click on the plus sign
13. Search for `libRctVideo`
14. add `libRctVideo`
15. run in a terminal tab`yarn start`
16. run in another terminal tab `yarn run ios`

add this to the README ?

**and it should work. Enjoy**

**Comment by ghasemikasra39** [comment]
Same issue on android. Any solution?

**Comment by bayareacoder** [comment]
Thank you @CyrusZei for clear and complete explanation (unlike some of the other BS posts in this thread). I had the same issue issue. Yes this should be added to README for installation.

**Comment by felipebutcher** [comment]
> Same issue on android. Any solution?

@ghasemikasra39 had this on android. just opened project from android studio, clean and run.

**Comment by Skobraf** [comment]
I'm still having this issue, react-native: 0.6.3

**Comment by Skobraf** [comment]
react-native: 0.63.4:
I Hi Guys! after spending some time on the issue reported,  the issue got fixed by following these steps:
* removing the Pods folder from the ios folder:
* removing the node modules
* removing the build using this command: rm -rf ios/build
* running Yarn to reinstall the packages
* installing Pods using this command: cd ios && pod install --repo-update && cd ..
* running the ios build
* starting react native and removing the cache with this command: yarn start --reset-cache

**Comment by Iman-IT** [comment]
> I found the solution that fixed me the problem.
> 
> Go to.. xCode -> Build Phases -> Link Binary With Libraries.
> 
> In the list find the file "libRCTVideo.a", if you will see it like icon of clean white paper than just delete it from the list and add it again by click on the plus (+) icon and just type "video" and add it.
> 
> Now in the commnd line run the commnad: "react-native run-ios", and "WALLA" no error.

Where is build phases???

**Comment by Vijay-Govani** [comment]
onlymac@Onlys-iMac Test2 % react-native link react-native-video
zsh: command not found: react-native

**Comment by imranemi143** [comment]
react-native link is not working

**Comment by ArronJLinton** [comment]
This solution worked for me: https://github.com/TheWidlarzGroup/react-native-video/issues/1738#issuecomment-533917249

Classic Rinse and Repeat.

For reference:
```
"react-native": "0.74.3",
"react-native-video": "^5.2.1",
```
