### ISSUE TITLE
how fix?

### ISSUE THREAD

**Issue by gxhx** [TheWidlarzGroup/react-native-video#439]
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger
![image](https://cloud.githubusercontent.com/assets/13634141/21755921/55b9a014-d655-11e6-916e-7d7c8f0f0192.png)

![image](https://cloud.githubusercontent.com/assets/13634141/21755838/6a4ddcbc-d654-11e6-81d0-6660fc7d5f44.png)
![image](https://cloud.githubusercontent.com/assets/13634141/21755949/a5f45772-d655-11e6-86c5-dbe47b6dbe66.png)
```
 fullScreen: {
        width:width,
        height:height,
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },

```

**Comment by mattapperson** [comment]
this should be fixed in 1.0
