### ISSUE TITLE
invoke onend function from background for autoplay feature.

### ISSUE THREAD

**Issue by codesinghanoop** [TheWidlarzGroup/react-native-video#441]
When i play the music from the foreground and go to background then how can i call onend() function to pass new path of song to player. But,when i come back from background to foreground next song start playing i.e onend() function in invoked. Any help would be appreciated, thank you :)

**Comment by nhoclove9x** [comment]
i was same problem :(

**Comment by mmsmsy** [comment]
Same problem here. Whether it's just sitting in background or the phone is locked the onEnd callback isn't called until I open the app to foreground again. The issue, however, happens only on iOS. On Android it works as expected (triggering onEnd whether the device is locked or the app is in the background). Help on this would be much appreciated.
