### ISSUE TITLE
uri source not working (even though it is httpS)

### ISSUE THREAD

**Issue by davidruisinger** [TheWidlarzGroup/react-native-video#446]
Tested on a fresh react-natiove project with:
react-native: 0.39,
react-native-video: 0.9.0

My source object looks like this:
```
{
  uri: 'https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8'
}
```

And I'm getting an `AVFoundationErrorDomain` error with code `-11800`

**Comment by Isgi** [comment]
I was trying this lates library (1.0.0) , and got same problem message "AVFoundationErrorDomain", can you fix it? or in my fault? sory for my bad english.

**Comment by peterjacobson** [comment]
We have exactly the same issue, 
react-native: 0.41.2,
react-native-video: 1.0.0. Hmmm

**Comment by cainaleaouk** [comment]
I have just installed the lib with nothing but the example in the docs pointing to a youtube link and Im getting the same thing. My error code is -11850 tho.
react-native : 0.41.2,
react-native-video : 1.0.0

**Comment by JeremyBradshaw7** [comment]
Also getting error code -11850

**Comment by cobarx** [comment]
Seeing in the console:
```
2018-06-02 23:16:14.933602-0700 rnv[23599:8278239] TIC SSL Trust Error [6:0x604000166f00]: 3:0
2018-06-02 23:16:14.933932-0700 rnv[23599:8278239] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9843)
2018-06-02 23:16:14.934084-0700 rnv[23599:8278239] Task <824A084D-275A-4C16-AEDD-9F1C5BE672F0>.<1> HTTP load failed (error code: -1202 [3:-9843])
2018-06-02 23:16:14.934327-0700 rnv[23599:8278240] Task <824A084D-275A-4C16-AEDD-9F1C5BE672F0>.<1> finished with error - code: -1202
```

I went to that URL in the browser and it's a bad SSL cert.

**Comment by hans0low** [comment]
@cobarx How did you get that in the console?

**Comment by burakozturk16** [comment]
> @cobarx How did you get that in the console?

console.log(error.error)

**Comment by MaximoSucari** [comment]
any solution? videos on Android do not load when the URI starts with "**HTTPS**", but it works with HTTP videos
