### ISSUE TITLE
Android: prepareAsync() instead of prepare()

### ISSUE THREAD

**Issue by arjan** [TheWidlarzGroup/react-native-video#451]
`prepare()` blocks the UI for seconds while loading the video. This is pretty unacceptable. The [code](https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L292) mentions something about race conditions when `prepareAsync()` is used, anyone care to explain?

I have been using a patched react-native-video using prepareAsync() with success on one project.

**Comment by wschurman** [comment]
Check out #426. While still early in development, preparing with that player seems to be non-blocking.

**Comment by arribbar** [comment]
It seems there is not anymore the issue using exoplayer.
Check this issue https://github.com/react-native-community/react-native-video/issues/555

**Comment by cobarx** [comment]
Would strongly recommend using ExoPlayer to get the best performance. Android MediaPlayer was updated to use prepareAsync, not sure what kind of race condition they were talking about but I have no idea how I'd reproduce it. Shrug, gotta wait for someone to report a bug on it.
