### ISSUE TITLE
Seek() method jumps to the wrong time

### ISSUE THREAD

**Issue by boplennon** [TheWidlarzGroup/react-native-video#452]
I'm working on a video player player which could displays subtitle and jumps to a specific subtitle. Seek method on Android often makes the player jumps to a position that slower than subtitles in range of few seconds.

**Comment by gijoehosaphat** [comment]
This is mostly due to however the video itself was encoded. Some of the algorithms designed to reduce disk space make it difficult to seek to specific frames. You can add keyframes if you need to be able to cue up at specific points. You can use a tool like `ffmpeg` for this.

**Comment by boplennon** [comment]
But in iOS, everything work fine. I thought there's some things need to adjust in this Java code:

`    @Override
    public void seekTo(int msec) {

        if (mMediaPlayerValid) {
            WritableMap event = Arguments.createMap();
            event.putDouble(EVENT_PROP_CURRENT_TIME, getCurrentPosition() / 1000.0);
            event.putDouble(EVENT_PROP_SEEK_TIME, msec / 1000.0);
            mEventEmitter.receiveEvent(getId(), Events.EVENT_SEEK.toString(), event);

            super.seekTo(msec);
            if (isCompleted && mVideoDuration != 0 && msec < mVideoDuration) {
                isCompleted = false;
            }
        }
    }`

**Comment by ghost** [comment]
@boplennon per @gijoehosaphat (love that icon btw) comment could you please try and repro with a different video, preferably one that is open source and reopen if this is still an issue? Thanks!

**Comment by geroale** [comment]
Same issue here.
