### ISSUE TITLE
Can not play video from https link

### ISSUE THREAD

**Issue by ak1103dev** [TheWidlarzGroup/react-native-video#453]
I try this example https://github.com/react-native-community/react-native-video/tree/0.9.0/Examples/VideoPlayer

when I change uri from 'broadchurch'(local file) to 'http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4', it work.

but I change uri to 'https://openload.co/embed/mhuOOvbWusI/001.mp4', it doesn't work.

I think about 'http' vs 'https'

**Comment by ak1103dev** [comment]
This link ('https://openload.co/embed/mhuOOvbWusI/001.mp4') may is not static file

**Comment by mattapperson** [comment]
I am unable to replicate this issue... closing until further info is provided
