### ISSUE TITLE
can't use any of these function

### ISSUE THREAD

**Issue by ninevcat** [TheWidlarzGroup/react-native-video#458]
onLoadStart={this.loadStart}   // Callback when video starts to load
       onLoad={this.setDuration}      // Callback when video loads
       onProgress={this.setTime}      // Callback every ~250ms with currentTime
       onEnd={this.onEnd}             // Callback when playback finishes
       onError={this.videoError}      // Callback when video cannot be loaded

**Comment by edencakir** [comment]
Which version are you using?

**Comment by ninevcat** [comment]
"react-native": "0.39.2",
    "react-native-video": "^0.9.0",

**Comment by edencakir** [comment]
Change react-native-video to 1.0.0 and 'npm install'

**Comment by ninevcat** [comment]
i'll try Thanks

**Comment by ghost** [comment]
> Change react-native-video to 1.0.0 and 'npm install'

RNV requires RN 0.40 or better. Please give `9bcf70c` a shot instead. It contains some event bubbling fixes. If it does the trick for you it'll help justify #480 so please report back.

**Comment by ninevcat** [comment]
> RNV requires RN 0.40 or better. Please give 9bcf70c a shot instead. It contains some event bubbling fixes. If it does the trick for you it'll help justify #480 so please report back.

I'm sorry em..how can i give 9bcf70c a shot instead

**Comment by ghost** [comment]
Pin the version in your package manifest. Others have done the same. Look through the issues for examples.

**Comment by ghost** [comment]
Please open a new issue if you are still having problems. We needed to do some housekeeping on issues. Thanks!

**Comment by sangupandi** [comment]
Video is not playing/buffering on Network-Connectivity changes. How to resolve this??
