### ISSUE TITLE
[Discussion] Shouldn't `seek` be renamed to `currentTime`?

### ISSUE THREAD

**Issue by bparadie** [TheWidlarzGroup/react-native-video#46]
See http://www.w3schools.com/tags/av_prop_currenttime.asp
That would be sweet!

**Comment by brentvatne** [comment]
@bparadie - @johanneslumpe and I thought about this, the main issue is that because we can't really make this a "controlled" component in the React sense - we can't have the value passed in to current time always be kept in sync with the actual time - it made more sense for us to break out of the React model and seek imperatively here. Thoughts?

**Comment by bparadie** [comment]
@brentvatne Just  checking whether I got your point: `currentTime` cannot be safely kept in sync w/t `AVPlayerItem.currentTime` and that's why you suggest using a different name i.e. `seek`.

Here is my take:
I did notice that the `currentTime` setter (JS to native) works as I would expect it to work with `HTMLVideoElement`. Now, the `currentTime` getter is a different story. I don't have a good solution for getting the `currentTime` other than recording the current time via incoming progress events. 

Or is there a way to retrieve property values directly through the bridge?
If so then this method added to `RCTVideo.m` should make everything work, correct?

``` objective-c
- (float)getCurrentTime
{
  return _playerItem != NULL ? CMTimeGetSeconds(_playerItem.currentTime) : 0;
}
```

But even with `currentTime` setter working and getter not working I would prefer `currentTime`, because it's in line with the `HTMLVideoElement` spec. 

BTW, similar arguments apply to `repeat` versus `loop` (http://www.w3schools.com/tags/att_video_loop.asp).

**Comment by johanneslumpe** [comment]
@bparadie The bridge is 100% async, in order to retrieve a value you will have to provide a callback which can be called with the new value.

**Comment by bparadie** [comment]
@johanneslumpe Yeah, that's what I thought. You'd probably have to observe a custom event and then somehow call the video player and wait for the result. Now, how would this all work with multiple video players on the page? The notification system is kind of global from what I can tell. That means each video player instance would probably need a UID, otherwise you wouldn't know which video player's `currentTime` was the right one. 

It would be great if `react-native` did some magic in the background and provide an easy way for retrieving property values. I am okay with async. I remember vaguely that `video.js`, or `Brightcove` has a similar problem with `currentTime` in Flash Player environments. Because the Flash/JS bridge is async you have to pass a callback function to  `getCurrentTime`.

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.
