### ISSUE TITLE
List of supported codecs

### ISSUE THREAD

**Issue by LukasBombach** [TheWidlarzGroup/react-native-video#461]
Hi, quick question: is there a list of codecs supported by `react-native-video`? Like, is MPEG-4 / XVID supported etc pp. What is this project built on?

**Comment by mattapperson** [comment]
On iOS we use the system video player. This was true on android as well until v1.0 where the switch was made to ExoPlayer. There are no plans to compile and maintain a list for the codecs supported as they are not in the control of this project. But the iOS docs and ExoPlayer docs can guide you in this

**Comment by LukasBombach** [comment]
Thank you
