### ISSUE TITLE
(iOS) EXC_BAD_ACCESS when calling presentFullscreenPlayer()

### ISSUE THREAD

**Issue by wildseansy** [TheWidlarzGroup/react-native-video#462]
When calling `presentFullscreenPlayer()`, it seems like UIResponder gets into some kind of loop or infinite recursive vortex.

I'm using React 0.40 on iOS 10.2 with react-native-video `master` (perhaps I should wait for an official release? Just wanted to get up and running with react 40).

`RCTVideo.m`
![screen shot 2017-01-17 at 9 42 22 am](https://cloud.githubusercontent.com/assets/177857/22032457/623eb67c-dc99-11e6-86a0-825c3a51306e.png)

How my component looks
```jsx
....
  <TouchableOpacity onPress={() => {this.setState({videoPaused: false}); this.player.presentFullscreenPlayer();}}>
    <Text>Play</Text>
  </TouchableOpacity>
  <Video
    source={{uri: 'http://techslides.com/demos/sample-videos/small.mp4', type: ''}}
    paused={this.state.videoPaused}
    ref={(ref) => {
      this.player = ref;
    }}
    resizeMode={'cover'} />
...
```
This video works fine playing without fullscreen mode.

**Comment by wildseansy** [comment]
this is now working for me, but would be interested if anyone else gets this.

**Comment by vadzim-wellit** [comment]
same thing.
how did you avoid that issue?

**Comment by wildseansy** [comment]
@vadzim-wellit - I eventually just [forked master into my own](https://github.com/theseansy/react-native-video) and pointed to that, so no changes would be introduced that might break my project.  I think that's what fixed it, but i'm not completely sure.
