### ISSUE TITLE
Duplicate interface definition for class 'RCTView' (iOS)

### ISSUE THREAD

**Issue by KBLNY** [TheWidlarzGroup/react-native-video#463]
Hello,
I tried to use react-native-video 0.9.0 with react-native (0.40.0). The project is well linked in the iOS project.
However, when I `react-nation run-ios` the project. I got the following errors:
`Duplicate interface definition for class 'RCTView'` 
and several `Property has a previous declaration` on the module `RCTVideo`
Thanks for helping

**Comment by kevinvandijk** [comment]
I'm having the exact same issue. Was about to create an issue about it. I've been scratching my head for a good hour on this now. Full compile output here: https://gist.github.com/kevinvandijk/3670159b9a9bb57e0858e40aaee57aa7

To make sure it's not any of my other dependencies I ran this on a completely fresh project as well but it yields the same results

Thanks for any help

**Comment by qpowell** [comment]
Same thing happened to me about 10 mins ago after getting the dependency added to my project. Currently unable to build the project in Xcode. 

I'm using react-native-video 0.9.0 and react-native 0.40 as well.

**Comment by crysfel** [comment]
If you want to use `0.9.0` you need to use RN `0.39`, however there's an issue with `0.9.0` on iOS with the callbacks. 

If you want to use RN `0.40` you will need to use master, the latest code on master works with `0.40`:

```
"dependencies": {
    "react": "15.4.2",
    "react-native": "^0.40.0",
    "react-native-video": "git+https://github.com/react-native-community/react-native-video.git#master"
}
```

I hope this helps.

**Comment by qpowell** [comment]
@crysfel Thanks. Your suggestion clears up the build issue for me.

**Comment by KBLNY** [comment]
thanks @crysfel I tried this, but the App crash on launch. I even tried from a clean project.

I will downgrade to RN 0.39.

**Comment by georgiana-gligor** [comment]
A lot of the 3rd party libraries have yet to release stable versions with RN 0.40 fix, and it can get frustrating very quickly. We confronted with this problem as well, on several packages. I described [our approach](http://tekkie.ro/quick-n-dirty/support-react-native-0.40-ios-headers/) and am leaving the link here in case you need to continue working asap.

**Comment by KBLNY** [comment]
Hey! Check this out: https://github.com/react-native-community/react-native-video/issues/470

> Don't know if my issue is related (iOS, react-native-video/example project RN 0.40.0)
> 
> But I got the iOS version running by adding type: "mp4" to the source prop:
> source={{uri: "broadchurch", type: "mp4"}}
