### ISSUE TITLE
Video freezes on iPhone 5 and below

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#464]
I have a media intensive app which plays a fullscreen background video layered with a separate audio file on top. Often, on old hardware like an iPhone 5, the video freezes and renders the app irresponsive while the audio continues to play. This usually happens when the audio file source is changed.

Are there any performance improvements in `1.0.0` vs `0.9`? Any suggestions from others experiencing a similar behavior would be greatly appreciated as well.

**Comment by realjamie** [comment]
+1

**Comment by mattapperson** [comment]
Have you profiled to see where the issue is? Is the issue a memory related one?

**Comment by anshul-kai** [comment]
I've made the following changes since and am no longer able to reproduce it.

1. I'm on `RN 0.39.2`. I moved my package from `github:larryranches/react-native-video` to `github:react-native-community/react-native-video#9bcf70cbb513402622bc114f93da751c28f15303`
2. I'm using `Navigator` and realized that old `scenes` in the stack aren't `unmounted` upon `navigator.push`. Which means a `Video` on an old `scene` will continue to play. I fixed this in my app.

There is often a slowness in my app but no freezes since. I'll close this issue for now and re-open with more details if this continues to persist as a problem.

**Comment by shiyunsheng** [comment]
how do you solve it？
I hava same problem  on all models

**Comment by anshul-kai** [comment]
@shiyunsheng It turns out that the freezing is related to other performance related actions. It's tricky to get to the bottom of these but [here's](http://facebook.github.io/react-native/releases/0.46/docs/performance.html) a great article about it.
