### ISSUE TITLE
Please confirm: asset system require() must use absolute positioning?

### ISSUE THREAD

**Issue by mosesoak** [TheWidlarzGroup/react-native-video#467]
Referring to your docs on using the RN asset system (https://github.com/react-native-community/react-native-video#load-files-with-the-rn-asset-system), I wanted to confirm that it's not possible to use `flexGrow: 1` with videos linked in this manner?

I can't get flexGrow to work in my current project, and that does make sense according to the original commit where Facebook added support for non-image types (https://github.com/facebook/react-native/commit/81fb985335a8ee3657905177abe32380b6b5fdc0) in which they describe how no size information is passed for non-images.

I'm submitting a PR to FB to update their docs to include non-image types, and I included mention that absolute positioning is required, but I wanted to check here and be sure. Please let me know if I'm wrong and flexGrow does work on videos using require! Thanks

**Comment by ghost** [comment]
Confirmed.
