### ISSUE TITLE
undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

### ISSUE THREAD

**Issue by airliuchuan** [TheWidlarzGroup/react-native-video#468]
Getting red screen of death with

undefined is not an object (evaluating NativeModuels.UIManager.RCTVideo.Constants')

on Android

under react-native 0.40
http://a1.qpic.cn/psb?/V14gZZNl1TvkWh/u0I7fflYwwrWdLYLkReb16CeTW6RW39NAg.BZrtYRbU!/b/dPYAAAAAAAAA&bo=eQGyAgAAAAADB.o!&rf=viewer_4
http://a3.qpic.cn/psb?/V14gZZNl1TvkWh/VCGu.S*gcpvXZWT1LuNWSyuze.3wmgOtJBeJAK*32sA!/b/dB8BAAAAAAAA&bo=.wDwAgAAAAADACw!&rf=viewer_4&t=5

**Comment by roysG** [comment]
Same for me

**Comment by tonicastillo** [comment]
Same, on IOS

**Comment by grovertb** [comment]
I also have the same problem with ios

**Comment by adriansuna** [comment]
same for me on ios + android. rn 0.40

**Comment by muhammetdemirci** [comment]
same for me on android.
rn 0.41.2

**Comment by cheeming** [comment]
I had this issue when I opened the project in Xcode first, installed (and linked) the react-native-video module later. After I close Xcode, and reopen it, reinstall app, it was fine for me.

**Comment by kfiroo** [comment]
`react-native link react-native-video` solved it for me.

**Comment by ordram** [comment]
How to solve

**Comment by zhangzeyan** [comment]
How to solve

**Comment by zhangzeyan** [comment]
How to solve， I also have the same problem with ios

**Comment by habibridho** [comment]
There are several possible solutions above, have you try them all?

**Comment by Bryan792** [comment]
Make sure to actually reinstall the native app, not just rebundle the JS. This fixed it for me.

**Comment by xylxpm** [comment]
ios
1、先按照这个组件的说明，修改APPDelegate.m。如果还不行。
2、打开xcode。查看Libraries里面有没有RCTVideo.xcodeproj.。如果没有，添加它。这个文件在你的项目node_modules/react-native-video文件夹中
3、build Phases----Link Binary with Libraries中添加libRCTVideo.a
4、编译运行。

我的问题就是这样解决的

**Comment by a1g0rithm** [comment]
Make sure you link binary with libraries and if you're using the iOS simulator make sure to clean derived data from Hardware -> Erase All Content and Settings.  This fixed it for me.

**Comment by YaoZeyuan** [comment]
i have faced this problem too.  @xylxpm 's solution is correct. 

This problem cause by Error Document in this project, for iOS developer, after Install Step in Document,  the next step is

> 1)in XCode right click on "Libraries" folder and choose 'add files to prjctname'
> then go to node_modules/react-native-video/ios/ and choose RCTVIdeo.xcodeproj
> 2) go to targets -> Build Phases ->Link Binary With Libraries hit + and choose libRCTVideo.a
> 3)profit 
> via @Lipfroy  #541 

to test this description, you can type this code 

```
import {NativeModules} from 'react-native'

console.log("check current NativeModules.UIManager")
console.log(NativeModules.UIManager)

```


if install correct, you will found `RCTVideo` Moudle in this list

**Comment by cobarx** [comment]
On Android I ran into this issue because I had forgotten to add `new ReactVideoPackage()` to my `getPackages()` list in MainApplication.java. It sounds like the issues on iOS are caused by some kind of corruption in the build process. I would recommend trying the fixed described in https://github.com/react-native-community/react-native-video/issues/468#issuecomment-355382160

**Comment by Lhamarama** [comment]
import { Video } from expo;

that worked for me
