### ISSUE TITLE
build failed in rn- 0.40.0

### ISSUE THREAD

**Issue by roysG** [TheWidlarzGroup/react-native-video#470]
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:21:1: error: duplicate interface definition for class 'RCTView'
@interface RCTView : UIView
^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:21:12: note: previous definition is here
@interface RCTView : UIView
           ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:26:49: error: property has a previous declaration
@property (nonatomic, copy) RCTDirectEventBlock onAccessibilityTap;
                                                ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:26:49: note: property declared here
@property (nonatomic, copy) RCTDirectEventBlock onAccessibilityTap;
                                                ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:27:49: error: property has a previous declaration
@property (nonatomic, copy) RCTDirectEventBlock onMagicTap;
                                                ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:27:49: note: property declared here
@property (nonatomic, copy) RCTDirectEventBlock onMagicTap;
                                                ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:32:48: error: property has a previous declaration
@property (nonatomic, assign) RCTPointerEvents pointerEvents;
                                               ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:32:48: note: property declared here
@property (nonatomic, assign) RCTPointerEvents pointerEvents;
                                               ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:48:41: error: property has a previous declaration
@property (nonatomic, assign) NSInteger reactZIndex;
                                        ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:48:41: note: property declared here
@property (nonatomic, assign) NSInteger reactZIndex;
                                        ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:57:36: error: property has a previous declaration
@property (nonatomic, assign) BOOL removeClippedSubviews;
                                   ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:57:36: note: property declared here
@property (nonatomic, assign) BOOL removeClippedSubviews;
                                   ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:70:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:70:39: note: property declared here
@property (nonatomic, assign) CGFloat borderRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:71:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopLeftRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rs
abah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:71:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopLeftRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:72:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopRightRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:72:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopRightRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:73:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderBottomLeftRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:73:39: note: property declared here
@property (nonatomic, assign) CGFloat borderBottomLeftRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:74:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderBottomRightRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:74:39: note: property declared here
@property (nonatomic, assign) CGFloat borderBottomRightRadius;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:79:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderTopColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:79:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderTopColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:80:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderRightColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:80:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderRightColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:81:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderBottomColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:81:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderBottomColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:82:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderLeftColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:82:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderLeftColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:83:42: error: property has a previous declaration
@property (nonatomic, assign) CGColorRef borderColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:83:42: note: property declared here
@property (nonatomic, assign) CGColorRef borderColor;
                                         ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h
:88:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderTopWidth;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:88:39: note: property declared here
@property (nonatomic, assign) CGFloat borderTopWidth;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:89:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderRightWidth;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:89:39: note: property declared here
@property (nonatomic, assign) CGFloat borderRightWidth;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
../react-native/React/Views/RCTView.h:90:39: error: property has a previous declaration
@property (nonatomic, assign) CGFloat borderBottomWidth;
                                      ^
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.m:2:
In file included from /Users/rsabah/www/letsgout/public_html/aa/node_modules/react-native-video/RCTVideo.h:1:
In file included from ../react-native/React/Views/RCTView.h:15:
/Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTView.h:90:39: note: property declared here
@property (nonatomic, assign) CGFloat borderBottomWidth;
                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

** BUILD FAILED **

The following build commands failed:

       	CompileC /Users/rsabah/www/letsgout/public_html/aa/ios/build/Build/Intermediates/RCTVideo.build/Debug-iphonesimulator/RCTVideo.build/Objects-normal/x86_64/RCTVideo.o RCTVideo.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by bjrn** [comment]
Don't know if my issue is related (iOS, react-native-video/example project RN 0.40.0)

But I got the iOS version running by adding `type: "mp4"` to the source prop:
```source={{uri: "broadchurch", type: "mp4"}}```

**Comment by KBLNY** [comment]
@bjrn You saved my life ! I had the same issue. Adding `type : "mov"` to the source prop ("mov" in my case) works !

**Comment by rclai** [comment]
Uh guys, this project's 1.0.0 hasn't been released to NPM?

**Comment by mattapperson** [comment]
v1.0 is now on npm
