### ISSUE TITLE
event handlers not working

### ISSUE THREAD

**Issue by nairihar** [TheWidlarzGroup/react-native-video#472]
onError, onEnd, onLoad... functions doesn't  work.

**Comment by nairihar** [comment]
so, I put console.log in your script Video.js the don't work there as well. I think it could be connected to RN bridging I'm using RN V. 0.40

**Comment by glacialspring** [comment]
same here

**Comment by nairihar** [comment]
just use v1.0.0

**Comment by edencakir** [comment]
How we are supposed to use v1.0.0 having RN 0.40 installed? @nairicode

**Comment by nairihar** [comment]
change in package.json
