### ISSUE TITLE
No video displays on iPad 3rd gen (A1416), works on all others

### ISSUE THREAD

**Issue by tomchambers2** [TheWidlarzGroup/react-native-video#473]
Works in simulator for all devices, just not this particular physical hardware. Tested on multiple devices.

Here's the sample code for the component:

```
import React, { Component } from 'react'
import {
  StyleSheet,
} from 'react-native'

import Video from 'react-native-video'
import loadingVideo from '../assets/loadingVideo.mp4'

class SplashScreen extends Component {
  render() {
    return (
      <Video
        style={styles.backgroundVideo}
        ref={(ref) => {
          this.player = ref
        }}
        muted
        repeat={true}
        source={loadingVideo}
        resizeMode="cover"
      />
    )
  }

  componentDidMount() {
    setTimeout(() => {
      this.props.hideSplashScreen()
    }, 6000)
  }
}

const styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
})

export default SplashScreen
```

**Comment by mattapperson** [comment]
I just tried my iPad 3rd gen and it worked for me... Are you sure this is not an issue with just that particular device? Have you tried removing and reinstalling the app?

**Comment by tomchambers2** [comment]
Going to try a very simple test app to double check. Will also try the 0.40.0 support just added.

**Comment by tomchambers2** [comment]
Ok, tested on an iPad 2 running iOS 9.3.1. Preliminary investigation suggests that it's an issue with the encoding or something like that with the video file itself.

Missed the fact that there was an error callback on the component which gives code 11855 which is described in this [SO issue](https://stackoverflow.com/questions/37037019/avassetwriter-could-not-be-decoded-on-this-device). Whoops! Tried a big buck bunny sample clip mp4 and that works fine.

Will close this as it's to do with the native video player, but would be grateful for any tips on how to solve by changing the video source.

**Comment by tomchambers2** [comment]
Have asked this question on stackoverflow as it's a completely mysterious error code and I can't find any documentation on what resolution video is supported by various devices.

http://stackoverflow.com/questions/41975280/11855-error-code-when-using-avfoundation-with-high-res-video-what-resolution-s

**Comment by tomchambers2** [comment]
The reason for this limitation is due to different maximum resolutions on different devices. The ipad 2 and ipad 3rd gen can only play 1080p video whereas the ipad mini 2 is capable of much higher resolutions.
