### ISSUE TITLE
Using 'source={{uri: 'example', type: 'mp4'}}' crashes the app

### ISSUE THREAD

**Issue by dvluong** [TheWidlarzGroup/react-native-video#474]
Not sure what's going on, but the app crashes when you use the 'source={{uri: 'example', type: 'mp4'}}', however, using 'require('../../asset/your-mp4-file.mp4')' works fine but I can't see the video anywhere, only hear the sound.

EDIT:

I forgot to add styling which caused the video to not appear. Just make sure you follow the 'example' code in styling and change from 'uri' to 'require' and it will work.

**Comment by anshul-kai** [comment]
`uri` will work if your media file has been added as a resource in XCode or for remote files. To see the video, make sure your `Video` view in inside a container that fills up enough space. I'd start by setting the below on your video component.

```
const styles = StyleSheet.create({
  video: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  }
});
```

**Comment by dvluong** [comment]
Ahh good to know, thanks!

**Comment by anshul-kai** [comment]
If my suggestion solved your problem, you may want to close this issue @dvluong
