### ISSUE TITLE
Support for Authorization header for remote videos

### ISSUE THREAD

**Issue by bitfused** [TheWidlarzGroup/react-native-video#475]
Would be great if we could add http header support for remote videos similarly to what has been done with Image component: https://github.com/facebook/react-native/pull/7338/files

**Comment by ghost** [comment]
Seems like a slippery slope IMHO, and something which should be handled by a proxy or by RN internals. Otherwise we'd be duping code in RN core.

**Comment by duhseekoh** [comment]
Why a slippery slope? Blanket support for throwing headers on the video requests seems like a one and done type solution.

**Comment by ghost** [comment]
I suppose it doesn't really matter this is react native. Where dogs play a serious poker game at least once a week. Please ignore my comment.
