### ISSUE TITLE
Android release and videos resources - add documentation

### ISSUE THREAD

**Issue by lebascou** [TheWidlarzGroup/react-native-video#476]
It would be great to add some documentation on how to add video resources properly to have an app that can be bundled for release on both Android and iOS.

On iOS everything works fine if you use videos as assets (like images):
`<Video source={require('assets/my_video.mp4')}></Video>`

But on Android this only works in debug mode. Trying to bundle your app for release will raise an error due to video assets being copied in res/drawables automatically by gradle.

There might be a better solution but a functional one is to use native assets on android:
- add video to res/raw/my_video
- use `<Video source={{uri: 'my_video'}}></Video>` on android and keep the version above for iOS
- note: you might have to set the res name to the relative path of your resource (I currently don't really know why). For exemple, if your asset is in a folder named app/assets/video/my_video.mp4 if will be res/raw/app_assets_video_my_video.mp4

**Comment by patricktresp** [comment]
It workes like this now in my system:

iOS
`import videoSRC from './../assets/video/myVideo.mp4';
<Video source={videoSRC} … />`

android
`<Video source={require('./../assets/video/myVideo.mp4')} … />`
