### ISSUE TITLE
Can't succeed to build and run the project in the simulator !!

### ISSUE THREAD

**Issue by jf423** [TheWidlarzGroup/react-native-video#48]
thanks for sharing this library.
but i faced some problem when i am going to run the project in the simulator.
it shows 
![2015-06-10 2 25 19](https://cloud.githubusercontent.com/assets/11975649/8076400/adc487f0-0f7e-11e5-911f-46d1ca7ed01c.png)

**Comment by johanneslumpe** [comment]
Have you added the static library to your project as describe in the [readme](https://github.com/brentvatne/react-native-video/blob/master/README.md) at step 3?

**Comment by jf423** [comment]
yes, already added 
![2015-06-10 3 32 56](https://cloud.githubusercontent.com/assets/11975649/8077283/043e1c60-0f87-11e5-8bdb-c20653e4689a.png)

but still failed 
![2015-06-10 3 32 31](https://cloud.githubusercontent.com/assets/11975649/8077289/0dc0ad16-0f87-11e5-8e9c-d0f57ce08633.png)

**Comment by brentvatne** [comment]
@jf423 - that's weird! what version of the library and React Native are you using?

**Comment by jf423** [comment]
@brentvatne i think i am in the latest version.
it's keep showing the issue of RCTWebSocketDebugger.
![2015-06-12 10 08 21](https://cloud.githubusercontent.com/assets/11975649/8122801/23dd2eb4-10f2-11e5-8378-323b193ac622.png)

**Comment by jf423** [comment]
@brentvatne i solve this problem.Turn out I just need to delete the link of RCTWebSocketDebugger in link libraries .
Thanks for your patient in my issue and your contribution in this resource.

**Comment by brentvatne** [comment]
Great :smile: thanks!
