### ISSUE TITLE
Can we get a minor release for the event bubbling fixes for rn 0.39?

### ISSUE THREAD

**Issue by kathawthorne** [TheWidlarzGroup/react-native-video#480]
Currently in my package.json I'm using the specific commit (#9bcf70cbb513402622bc114f93da751c28f15303) that fixes event bubbling due to `1.0.0` not supporting rn `0.39`. Could we do a minor npm release (e.g. `0.9.3` or whatever it would be) to make it easier for people on rn `0.39`?

**Comment by joeferraro** [comment]
minor release for `0.39` would be tremendous! cheers for the thought 👍

**Comment by ghost** [comment]
Technically that would be a patch release, but agree it would be a nice to have.

**Comment by mkdotcom** [comment]
+1! please!

**Comment by mkdotcom** [comment]
@kathawthorne "Currently in my package.json I'm using the specific commit " -> could you please explain how you do that?

**Comment by kathawthorne** [comment]
@mkdotcom in your `package.json` file put:
` "react-native-video": "git://github.com/react-native-community/react-native-video.git#9bcf70cbb513402622bc114f93da751c28f15303",` instead of something like `0.9.0`.

**Comment by ghost** [comment]
For brevity you can also use the first 7 characters of the SHA. Please see NPM docs for more info.

**Comment by mkdotcom** [comment]
thanks, i did it but now i get this error when using it... sorry to bother you but any idea what is wrong ?

2017-02-13 12:14:15.993 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')
2017-02-13 12:14:15.992889 app[772:497975] undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')
2017-02-13 12:14:16.023 [fatal]

**Comment by mkdotcom** [comment]
thanks

**Comment by BraunreutherA** [comment]
This commit didn't fix it. the event protection comes after RN 0.40. I created a fork u can use if you want and will send a PR.

"react-native-video": "git://github.com/haulinit/react-native-video.git#db623b7"
