### ISSUE TITLE
[ExoPlayer] Changing the `source.uri` of a `Video` instance does not load new video

### ISSUE THREAD

**Issue by jhilden** [TheWidlarzGroup/react-native-video#481]
I have a Player component which is getting changing remote video URLs via props from it's parent.  However, the `Video` component instance does not seem to load the new URL.  After pausing/unpausing the player it will keep playing the old video URL. Debugging this I was not seeing a `load` event being fired for the new video.

This used to work with version `0.9` without the ExoPlayer (testing on Android 6.0.1).

Has somebody else experienced something similar?  Or am I missing some API that I need to call for loading a new video?

My workaround is to temporarily render `undefined` instead of the `Video` component when the video gets switched and then rendering a fresh new `Video` component with the new video URL.

**Comment by iou90** [comment]
Same for me.

**Comment by AndrewJack** [comment]
I'll have a look at fixing this.

**Comment by AndrewJack** [comment]
Try out that PR and see if it fixes it for you. @jaggerwang, @iou90, & @jhilden

**Comment by jhilden** [comment]
Thanks @AndrewJack 

The structure of our app actually changed in the meantime, so that we don't have one player instance with switchable sources anymore.  That's why I can't just test your fix without additional effort.  But I will see if I can still find some time for that soon.

**Comment by iou90** [comment]
@AndrewJack This PR works for me, thanks a lot. Tested on rn0.42;ios10.2/android_api18,23,25.

**Comment by LeeZC** [comment]
could you show me how to play video from url ?

**Comment by ckOfor** [comment]
@LeeZc figured it out yet ?

**Comment by hemantbavle1** [comment]
I have 2 URLs  - URL 1 and URL 2, I want to be able to switch between the two on button press. How do I achieve it. Does anyone have a working example for this?

**Comment by joemewes** [comment]
I have this issue too. when switching source the remain overlay is the previous video, but I can here the new video playing in BG/behind. 

NB : it works as normal when the `controls={false}` prop is set.  I need controls to show. any tips/hints on switching source without a hack to force re-render a couple times?

thanks all.

**Comment by tgreco** [comment]
Any solution to this? 
Does not re-render new video if controls={true} on iOS.
