### ISSUE TITLE
Android | Video source file location

### ISSUE THREAD

**Issue by patricktresp** [TheWidlarzGroup/react-native-video#485]
Hi all,

where do you need to put the local android video file to be used in video component.

I did put the video - assisting to ( root/assets/video/video.mp4 for iOS ) - in
app/src/main/assets/video/video.mp4

So how do i reference this video located in android asset directory?
whatever i try, it does not work.

Do you have any hints on that?

Thx!

**Comment by ghost** [comment]
https://github.com/jhabdas/lumpen-radio/blob/master/app/components/BackgroundVideo.js#L20-L31

**Comment by patricktresp** [comment]
This is the answer?
A link to a different module.
Unfortunatly this is not the answer since the url on ios will be "assets/video/video.mp4" and not just "video" and on android it will look up somewhere on android raw folders.

**Comment by jhabdas** [comment]
@patricktresp it was wise of you to remove that comment after I tried to help

**Comment by patricktresp** [comment]
Well you now, it was a reference with no comment on what difference to look at.

a simple - just require it instead of referencing it, would have helped even more :)

Whatever, your awesome!
