### ISSUE TITLE
Integrate VAST Ads for Pre-Roll Mid-Roll Post-Roll

### ISSUE THREAD

**Issue by FullstackJack** [TheWidlarzGroup/react-native-video#488]
Both Android and iOS possess the capability to integrate with third-party Video Ad Serving Tempaltes (VAST) services to pre-roll, mid-roll, and post-roll ads interspersed with video playback. If  React Native is to be considered a serious replacement for native app development, we need a mechanism to generate ad revenue from video views.

As mentioned, there are pre-existing native solutions that exist for both iOS and Android platforms. Interactive Media Ads (IMA) SDK is one such solution which integrates with both. The IMA SDK is maintained by Google. 

IMA SDK integrates with DoubleClick for Publishers (DFP), Google AdSense network, or any VAST-compliant ad server. [Google Developers](https://developers.google.com/interactive-media-ads/) has documentation for integration on each platform.

[IMA Platform Support Matrix](https://developers.google.com/interactive-media-ads/docs/sdks/ios/compatibility)
[Android Get Started](https://developers.google.com/interactive-media-ads/docs/sdks/android/quickstart)
[iOS Get Started](https://developers.google.com/interactive-media-ads/docs/sdks/ios/quickstart)

**Comment by OrenMe** [comment]
Hi @FullstackJack, do you have an example of IMA SDK for Android or iOS that actually works?
From a couple of experiments with Android it seems that if you wrap IMA SDK in a RN component then there are some weird quirks with the clocks and the outcome is that although ad request does load and also the ad creative (you can see it in a network sniffer) the IMA SDK always emits an error and ad playback fails.

**Comment by FullstackJack** [comment]
I wish I did, but I hadn't made it to that point before switching to a new project. I was working on a prototype and the company Ibwas building it for decided to spend a huge amount of money on full native versions instead. Maybe I'll come back to it someday.

**Comment by OrenMe** [comment]
Thanks @FullstackJack.
I asked around with the IMA SDK team but unfourtounatly they are not supporting react native officially yet.

**Comment by brinkkemper** [comment]
I've spend the past couple of days trying to get this to work. If it works I could contribute to this project. However, I'm horribly stuck on this strange issue: 
[Google IMA webview is not showing when used inside react native on android
](https://stackoverflow.com/questions/48567794/google-ima-webview-is-not-showing-when-used-inside-react-native-on-android)
Perhaps someone here has the solution?

**Comment by benoit-ponsero** [comment]
Hi, 
any news on this feature ? it could be interesting to have

**Comment by riza** [comment]
Hi,
any alternative for VAST on react-native? its very important feature of mobile apps.

**Comment by orhunkupeli** [comment]
Hi,
Is there any improvements about issue?

**Comment by dbramwell** [comment]
Hi all. I've taken a stab at forking react-native-video and adding google's IMA SDK to the IOS Video player and Android Exoplayer.

It's very much a work in progress, but it'd be useful to get people's thoughts on it.

https://github.com/EndemolShineGroup/react-native-video-with-ads

**Comment by FullstackJack** [comment]
Hi all. Long time no see. I'm back with renewed hope that my employer will support my efforts to replace those expensive bifurcated app silos they built with a unified React Native solution so I'll try my hand at this as well. I just found out that ExoPlayer has a plug-in for DFP so that may resolve half the battle. Sorry I couldn't help much earlier.

**Comment by FullstackJack** [comment]
@dbramwell How did you work on this project locally? I've spent several hours trying to use a symlink module to no avail. Found out Metro Bundler doesn't like symlinks so I installed Haul and still having massive problems getting that to run. It now complains about Module Build Failed from thread-loader, I had to install react, react-native, in react-native-video. Would love to try the your solution as well, have you considered creating a PR?

**Comment by dbramwell** [comment]
Hi @FullstackJack. Yeah I struggled to set it up locally also. I think in the end I just added react-native-video with yarn and then made changes directly to the code in node_modules. Obviously not the best workflow...

I've thought about a pull request, but I think the implementation is a bit sloppy at the moment. I pretty much just copied the samples from the [IMA SDK](https://developers.google.com/interactive-media-ads/) site into the right places (for ios and exoplayer, didn't touch the others which is probably why simple player still works for you). This means it adds the google ad SDKs by default which isn't ideal for everyone.

I guess in IOS we could do something similar to how the VideoCaching module works (Objective C is a massive black box for me. This is the first time I've as much as read it, let alone tried to program in it)? Not sure how it'd work with ExoPlayer. Do you have any thoughts on this?

Do you get any specific errors when Exoplayer crashes?

**Comment by brinkkemper** [comment]
Check out this app. Me and the team got it working super smooth up from
iphone 4s and android 4.0

https://play.google.com/store/apps/details?id=be.persgroep.android.news.mobilead

Its a commercial project and I can't open source the code. But it is
definitly possible.


Op ma 22 okt. 2018 03:19 schreef Kyle Bedell <notifications@github.com>:

**Comment by FullstackJack** [comment]
@dbramwell I haven't tried running your solution yet, just wanted to get the basic example working first which I now have working after lots of Gradle changes for Gradle 4.6, SDK 28 and Java 8. I will try to run yours, but I am hoping we can have a comprehensive solution. Is there a way to allow ads to be additive code that only gets included if uncommented in Gradle? How about with iOS? I'll look into this.

**Comment by aamirnbs** [comment]
> Hi all. I've taken a stab at forking react-native-video and adding google's IMA SDK to the IOS Video player and Android Exoplayer.
> 
> It's very much a work in progress, but it'd be useful to get people's thoughts on it.
> 
> https://github.com/EndemolShineGroup/react-native-video-with-ads

@dbramwell I was about to integrate react-native-video-with-ads in my application. As you said it is very much work in progress, do you know how much it supports for ads (Google ad manager ads etc.) or what are their TO-DOs. It will be very helpful. Thanks

**Comment by dbramwell** [comment]
Hi @aamirnbs, my focus changed at work so I've not played with this for a while. I had it working with some VAST sample ads on both IOS and Android. There are samples here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

If I remember rightly the VPAID ones didn't work, but I'm not sure.

**Comment by zikwall** [comment]
Hi! I would like to know if the implementation of advertising in the player works? I just can’t start...

https://github.com/EndemolShineGroup/react-native-video-with-ads

**Comment by robbywh** [comment]
Hello,

i have create a PR to play ad url on react-native-video with ima SDK : 
https://github.com/react-native-community/react-native-video/pull/1839

Please review for my code

**Comment by zikwall** [comment]
Hi @RobbyWH, Will there be support for event props in the future?

**Comment by robbywh** [comment]
Hello @zikwall , 
I have no plans for that in the near future

**Comment by Utkarshkataria** [comment]
Anyone can asnwer how to add the ads in react native video player??

**Comment by Utkarshkataria** [comment]
> Hello @zikwall ,
> I have no plans for that in the near future

Hello @RobbyWH are you gonna add the VAST tag in library in near Future now?
Thanks

**Comment by robbywh** [comment]
hello @Utkarshkataria, i still wait for review, so i can merge this PR, after the review is OK..
This is my PR : https://github.com/react-native-community/react-native-video/pull/1839

if you want to add the ads, maybe you can use my branch for a while : https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk

**Comment by Utkarshkataria** [comment]
> hello @Utkarshkataria, i still wait for review, so i can merge this PR, after the review is OK..
> This is my PR : #1839
> 
> if you want to add the ads, maybe you can use my branch for a while : https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk

is it working? because i am adding a fast tag url to adtag prop but nothing happening.

**Comment by robbywh** [comment]
@Utkarshkataria Have you tried my sample code ?

```
const adTagUrl = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/"
+ "ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp"
+ "&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite"
+ "%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=";

adTagUrl={adTagUrl}
```

and add it in your package.json, with spesific branch

```
   "react-native-video": "git://github.com/RobbyWH/react-native-video.git#implement-ima-sdk",
```

**Comment by Utkarshkataria** [comment]
> https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/"
> + "ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp"
> + "&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite"
> + "%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

yes i even did npm install after adding this "react-native-video": "git://github.com/RobbyWH/react-native-video.git#implement-ima-sdk"  in package.json and used that adtag prop but not showing the ad's in starting or ending.

**Comment by robbywh** [comment]
@Utkarshkataria : Have you used the right prop? the right prop is adTagUrl not adTag

**Comment by Utkarshkataria** [comment]
> @Utkarshkataria : Have you used the right prop? the right prop is adTagUrl not adTag

Yes i have used the exact prop you have given in documentation. when are u gonna merge it in your main branch?

**Comment by robbywh** [comment]
@Utkarshkataria : what platform do you use? i only implement IMA SDK in android exoplayer and iOS

i think i'm not gonna merge it in my main branch, i hope i can merge it in the react-native-video immediately, after the review is OK

**Comment by Utkarshkataria** [comment]
> @Utkarshkataria : what platform do you use? i only implement IMA SDK in android exoplayer and iOS
> 
> i think i'm not gonna merge it in my main branch, i hope i can merge it in the react-native-video immediately, after the review is OK

i am working on react native i have installed your library react-native -video with a specific branch as well and using the specific prop from documentation.

**Comment by robbywh** [comment]
@Utkarshkataria i mean what device you use for testing ? (iOS/Android)

if you use android device, it is only working if you use android exoplayer

you must set this on your **android/settings.gradle** :
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

you can check the complete step in this : https://github.com/react-native-community/react-native-video/blob/2738892631fda1b9cebc894ce51cb875f5dddd9a/README.md#android-installation

**Comment by Utkarshkataria** [comment]
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

yes android device, Android X wont add these by itself? otherwise i'll add it manually and check again. Thanks for helping man. And great Library @RobbyWH :)

**Comment by robbywh** [comment]
no @Utkarshkataria , we must setup manually, if we want use the android exoplayer in react-native-video

Your welcome @Utkarshkataria

**Comment by FullstackJack** [comment]
In case you really need ads and are open to hack solutions. Our team abandoned trying to use this module and just wrote a simple WebView video player using an HTML5 player. If you think about it, the browsers are built with native-backed code, i.e. ExoPlayer and AVFoundation. All you have to do is build a mobile friendly iframe video player, pass through some URLs and blamo! It actually works pretty well and you can bring in IMA SDK. We tested performance and it actually performs better than our own attempt to build a React Native Video Player with Ads natively. We did this because we couldn't afford any more time to make the native approach work. I'm not recommending this a hard and fast approach, but it's at least a stopgap measure to satisfy the business requirements.

**Comment by Utkarshkataria** [comment]
> no @Utkarshkataria , we must setup manually, if we want use the android exoplayer in react-native-video
> 
> Your welcome @Utkarshkataria

hello @RobbyWH i am having issue with PictureInPicture prop too its not working by adding PIP prop true.. do it also require some manual code in android ?
thanks.

**Comment by robbywh** [comment]
@Utkarshkataria Hello, i think pictureInPicture prop only working for iOS platform right now. If you want to make it work for android, you must adding native code in android

<img width="490" alt="Screen Shot 2020-02-10 at 15 38 14" src="https://user-images.githubusercontent.com/11469477/74133559-66c16600-4c1b-11ea-8587-1d761e2eb2f0.png">

**Comment by luiscerqueira** [comment]
@RobbyWH 
I tested this branch on android with some ads (google test ads + other vast ads) and it's working.

Is there anything missing for this feature to be merged?

@Utkarshkataria 
I don't know which react-native version you are using, but maybe this can help:

**react-native.config.js**
```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```
You need to tell react-native to use the react-native-video exoplayer implementation

**Comment by robbywh** [comment]
hello @luiscerqueira , i still wait my PR to be approved by reviewer, but no response until now : https://github.com/react-native-community/react-native-video/pull/1839

**Comment by arslan-akh** [comment]
> @Utkarshkataria : what platform do you use? i only implement IMA SDK in android exoplayer and iOS
> 
> i think i'm not gonna merge it in my main branch, i hope i can merge it in the react-native-video immediately, after the review is OK

Hello, @RobbyWH I try to use your branch for integrate ads for iOS but same problem as @Utkarshkataria nothing happening after adding prop adTagUrl

**Comment by arslan-akh** [comment]
And there are any progress for ads integration for react native video in core as extension or something else?

**Comment by robbywh** [comment]
hello @arslan-akh what platform do you use? 

you can check this PR to see the progress : 
https://github.com/react-native-community/react-native-video/pull/1839
https://github.com/react-native-community/react-native-video/pull/1740

**Comment by arslan-akh** [comment]
> hello @arslan-akh what platform do you use? 
> 
> 
> 
> you can check this PR to see the progress : 
> 
> https://github.com/react-native-community/react-native-video/pull/1839
> 
> https://github.com/react-native-community/react-native-video/pull/1740
> 
> 
> 
> 

Hello, I try on iOS 13.4

**Comment by robbywh** [comment]
> @Utkarshkataria Have you tried my sample code ?
> 
> ```
> const adTagUrl = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/"
> + "ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp"
> + "&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite"
> + "%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=";
> 
> adTagUrl={adTagUrl}
> ```
> 
> and add it in your package.json, with spesific branch
> 
> ```
>    "react-native-video": "git://github.com/RobbyWH/react-native-video.git#implement-ima-sdk",
> ```

hello @arslan-akh have you tried this ?

**Comment by arslan-akh** [comment]
> > @Utkarshkataria Have you tried my sample code ?
> 
> > 
> 
> > ```
> 
> > const adTagUrl = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/"
> 
> > + "ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp"
> 
> > + "&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite"
> 
> > + "%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=";
> 
> > 
> 
> > adTagUrl={adTagUrl}
> 
> > ```
> 
> > 
> 
> > and add it in your package.json, with spesific branch
> 
> > 
> 
> > ```
> 
> >    "react-native-video": "git://github.com/RobbyWH/react-native-video.git#implement-ima-sdk",
> 
> > ```
> 
> 
> 
> hello @arslan-akh have you tried this ?

Yes of course. Also I did integration ima sdk from zero with fresh fork of react-native-video and I use your pr as reference but ad not started. Now I use react-native-with-ads it’s work but I want use fresh react native video version.

**Comment by arslan-akh** [comment]
@Utkarshkataria I don’t no why but [adsManager start] not started ads and I did debug requestAds method in RCTVideo I see adTagUrl link and I think ad requested but not started through adsManager

**Comment by robbywh** [comment]
@arslan-akh have you tried the basic example : https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk/examples/basic ?

i have updated the basic sample code

**Comment by arslan-akh** [comment]
> @arslan-akh have you tried the basic example : https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk/examples/basic ?
> 
> i have updated the basic sample code

Hello, thank you it works but only in native or embed mode but not on custom skin mode is it ok? I have custom skin with my own implementation, should it reason why ad not working for me?

**Comment by robbywh** [comment]
@arslan-akh Maybe the reason why it is not working because the custom skin, because i never tested the code with the custom skin

Beside of that, I have hold my MR, because the contributors don't want make IMA SDK a required dependency for all users of react-native-video, they are want add the IMA SDK via an extension mechanism

**Comment by cbawebdesign** [comment]
Hello! Thanks so much for working on this package. 

I am trying to run your example Basic App- however am getting


![Simulator Screen Shot - iPhone 11 - 2020-10-16 at 02 30 06](https://user-images.githubusercontent.com/35353826/96241980-c5cc3d00-0f57-11eb-8737-1dfbbc207642.png)

any help would be awesome!!

**Comment by Buddikazz** [comment]
@RobbyWH 
hello,thank you for your update can i play ad every 10 minutes using your basic sample

**Comment by RobbyWH** [comment]
your welcome @Buddikazz

**Comment by Buddikazz** [comment]
@RobbyWH  can u help me on playing ad every 10 minutes without vmap.Your sample is working

**Comment by fernandopascoalbr** [comment]
@RobbyWH you can help me?

I`m try build with you repo but given two errors:

=> Property 'webOpenerPresentingController' not found on object of type 'IMAAdsRenderingSettings *'; did you mean 'linkOpenerPresentingController'?

=> No visible @interface for 'IMAAdDisplayContainer' declares the selector 'initWithAdContainer:companionSlots:'

**Comment by robbywh** [comment]
@fpgce have you tried the basic example: https://github.com/RobbyWH/react-native-video/tree/implement-ima-sdk/examples/basic?

what platform did you test?

**Comment by fernandopascoalbr** [comment]
@RobbyWH 
Yes, my problem is in the project build after installing its branch.

From the failure and with this message in the RCTVideo.m file.

`
No @interface visible to 'IMAAdDisplayContainer' declares selector 'initWithAdContainer: companionSlots:'
`

i`m using react-native 0.61

**Comment by robbywh** [comment]
@fpgce have you run `npx pod-install` before building the app?

**Comment by fernandopascoalbr** [comment]
@RobbyWH yes, installed it as described in your repository

**Comment by robbywh** [comment]
@fpgce please look at your Podfile.lock, is there any  GoogleAds-IMA-iOS-SDK (3.10.1) in that file? and please also check your Pods folder, is GoogleAds-IMA-iOS-SDK already installed there?

**Comment by fernandopascoalbr** [comment]
@RobbyWH thanks Robby, my pod are installing a different version of GoogleAds-Ima-ios-sdk, thats work now.

**Comment by olgunkaya** [comment]
@RobbyWH quite late for the party but, is your branch support skipping the ads ? Or am I fully mis understand the flow that ima sdk itself does support it ?

**Comment by robbywh** [comment]
@olgunkaya If your Ad Manager network uses VAST 3, the "Skippable skip time" and "Skippable view time" are customizable for reservation campaigns under Admin and then Video and audio.

you can check this link for more information :
https://support.google.com/admanager/answer/3376934?hl=en
https://support.google.com/admanager/answer/4517679

**Comment by olgunkaya** [comment]
@RobbyWH, first of all thanks for blazing fast response. I mean your addon on the video is supporting it or not ? Or, there is nothing with your add on, it's all about ima-extension.

**Comment by robbywh** [comment]
@olgunkaya Skipping ads is configurable inside AdManager, for example in VAST 3 you  can set the "Skippable skip time" and "Skippable view time", IMA SDK helps us to play the ads inside our video player for example VAST ads, and my branch is only implemented IMA SDK in the native side of the react-native-video, so you can play ads inside your react-native app video

**Comment by olgunkaya** [comment]
Thanks a lot RobbyWH.

**Comment by olgunkaya** [comment]
> In case you really need ads and are open to hack solutions. Our team abandoned trying to use this module and just wrote a simple WebView video player using an HTML5 player. If you think about it, the browsers are built with native-backed code, i.e. ExoPlayer and AVFoundation. All you have to do is build a mobile friendly iframe video player, pass through some URLs and blamo! It actually works pretty well and you can bring in IMA SDK. We tested performance and it actually performs better than our own attempt to build a React Native Video Player with Ads natively. We did this because we couldn't afford any more time to make the native approach work. I'm not recommending this a hard and fast approach, but it's at least a stopgap measure to satisfy the business requirements.

Is it possible you to share your implementation ?

**Comment by olgunkaya** [comment]
@RobbyWH sorry for disturbing you back again but I am facing an issue while trying to update/merge your version to latest rn video. Basically, exo guys removed the interface `AdsMediaSource.MediaSourceFactory` around exo player v2.11. But considering that there are a lot of fixes on rn video main branch I need to update your code to there. What is your suggestion ? why do you need to implement that interface, as I could not see any place in the `ReactExoplayerView` class for setting itself as media source factory.

**Comment by robbywh** [comment]
@olgunkaya hello, you can see in this closed PR, for the location of the specific changes: https://github.com/react-native-video/react-native-video/pull/1839/files

the _AdsMediaSource.MediaSourceFactory_ is implemented in here :
```
    // AdsMediaSource.MediaSourceFactory implementation.

    @Override
    public MediaSource createMediaSource(Uri uri) {
      return buildMediaSource(uri, extension);
    }
```

sorry, currently, I don't have enough time to sync with the latest master

**Comment by olgunkaya** [comment]
Thanks Robby I will fix it ;) But  @RobbyWH I would like to ask that why you implemented this interface ? I did not find any reason to implement it. Checked a bit and see the view class is not assigned to anywhere as listener or media source factory.. Am I missing it somewhere else ?

**Comment by robbywh** [comment]
@olgunkaya I'm sorry , i'm not maintained it for a long time, As i recall, I just follow the tutorial written by google to implement IMA SDK on exoplayer. I will try to look at it, after I have an enough time. Maybe you can check the another way to implement the IMA SDK : https://github.com/react-native-video/react-native-video/pull/1740

**Comment by Alexandrusandy** [comment]
Hello @RobbyWH i'm trying to add this library in my project the ads work but only on Ios on Android doesn't show any ads.Any ideea?

**Comment by olgunkaya** [comment]
> Hello @RobbyWH i'm trying to add this library in my project the ads work but only on Ios on Android doesn't show any ads.Any ideea?

@Alexandrusandy I got @RobbyWH 's branch and added some stuff on it and published on npmjs. react-native-video-inc-ads for a side project. https://www.npmjs.com/package/react-native-video-inc-ads our guys confirmed that they can play ads and skip ads and etc... on android. IOS side has also some bug fixing too (not by me but someone else) please try that one too. 

installation is also the same as react-native-video. some new props added. At the very top of readme you can see these two props too. 

I should appreciate @RobbyWH 's work here again. It's to the point work honestly. all credits to him :)

**Comment by Alexandrusandy** [comment]
Hey @olgunkaya,thank you for your quick answer i-m trying your library but it's the same i follow all the steps i was trying with link and whitout with manually install, but when i put mannualy @Overrideprotected List<ReactPackage> getPackages() {
    return Arrays.asList(             new MainReactPackage(),            new ReactVideoPackage()   );  } it crash.I am using react native 0.64.2.Thank you .

**Comment by olgunkaya** [comment]
Can you share your crash logs here ?

**Comment by Alexandrusandy** [comment]
@olgunkaya  when it's building my project give me this error: ' cannot find symbol class MainReactPackage' 
'cannot find symbol variable Arrays' in the MainApplication.java

**Comment by olgunkaya** [comment]
> @olgunkaya when it's building my project give me this error: ' cannot find symbol class MainReactPackage'
> 'cannot find symbol variable Arrays' in the MainApplication.java

I dont think this really related to the module. But can you share your `MainReactPackage `including import statements ?

**Comment by Alexandrusandy** [comment]
The MainReactPackage was not imported i imported the package and now it's building the app and start but still no ads in the video

**Comment by olgunkaya** [comment]
Well to me this is more of classpath issue. What I see from your code piece. You are creating packages but not adding them to package list etc..

**Comment by Alexandrusandy** [comment]
Ok thank you for answering !

**Comment by olgunkaya** [comment]
you are wellcome, I can confirm our package inc-ads working in our apps. and nothing specific for the side project included in

**Comment by robbywh** [comment]
@Alexandrusandy :  what platform do you use? i only implement IMA SDK in android exoplayer and iOS

**Comment by fernandopascoalbr** [comment]
@RobbyWH i'm using your implementation, thats works fine.

I need now to show a banner that comes with the XML VAST. Your implementation only shows a black screen with audio, can you help me with this? or ima SDK does not support?

**Comment by robbywh** [comment]
@fpgce have you tried the @olgunkaya implementation: https://www.npmjs.com/package/react-native-video-inc-ads?
I'm sorry because I don't have enough time to do the research about this.

**Comment by olgunkaya** [comment]
Black screen with audio ? Either @RobbyWH 's impl or mine does shows video ads. If you are on an emulator that's a possibility to hear only the sound. But just possibility. 
If you only need the banner, I would try to find a admob implementation. Have a look at https://techgaun.github.io/active-forks/index.html#https://github.com/sbugert/react-native-admob for the admob lib's latest/most up-to-date forks.

**Comment by Durkaen** [comment]
Hello @olgunkaya and @RobbyWH,

I would like to thank you for your effort and time.

I use @olgunkaya implementation and I have a weird problem on iOS side.

The ad continues to play even though I close the screen where the video player is located.

**Comment by olgunkaya** [comment]
@Durkaen ,

I did not face such issue tbh but as a workaround you can just set stopped for the player while exiting the view.

**Comment by krunal54** [comment]
@Durkaen ,

I run "basic" in example folder but give the error (Nothing I change): 

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-video-inc-ads.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-video-inc-ads: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081




Can you please change the example "basic" so that check how its works.

Thanks a lot!

**Comment by krunal54** [comment]
Hi @RobbyWH,

I did same steps as per mention but when I run using "yarn android" then got error:

![image](https://user-images.githubusercontent.com/29136594/154433517-8f801495-e2c2-457c-aa5c-6d84d2eb3e56.png)

**Comment by krunal54** [comment]
Hi @RobbyWH,

My ads not showing even I perform all step:

const adTagUrl =
  'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=';


```
<View style={styles.container}>
        <TouchableOpacity
          style={styles.fullScreen}
          onPress={() => this.setState({paused: !this.state.paused})}>
          <Video
            /* For ExoPlayer */
            ref={ref => {
              this.video = ref;
            }}
            source={{
              uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              type: 'mp4',
            }}
            style={styles.fullScreen}
            adTagUrl={adTagUrl}
          />
        </TouchableOpacity>
```

Is there anything which I am missing?

One more thing I not understand is in Video.js you not handle adTagUrl props then how it can works?

**Comment by olgunkaya** [comment]
> Hi @RobbyWH,
> 
> My ads not showing even I perform all step:
> 
> const adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=';
> 
> ```
> <View style={styles.container}>
>         <TouchableOpacity
>           style={styles.fullScreen}
>           onPress={() => this.setState({paused: !this.state.paused})}>
>           <Video
>             /* For ExoPlayer */
>             ref={ref => {
>               this.video = ref;
>             }}
>             source={{
>               uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
>               type: 'mp4',
>             }}
>             style={styles.fullScreen}
>             adTagUrl={adTagUrl}
>           />
>         </TouchableOpacity>
> ```
> 
> Is there anything which I am missing?
> 
> One more thing I not understand is in Video.js you not handle adTagUrl props then how it can works?

I don't have too much time and possibly will not be able to follow up from here but have you checked to make sure if you are using exoplayer ?

**Comment by krunal54** [comment]
Hi @Durkaen ,

Hi,

I saw that you have implemented @olgunkaya solution. When I tried to implement I get error in both android and iOS. Can you please post working demo project link.

In example folder of @olgunkaya has older version code and its not working.

Thanks

**Comment by olgunkaya** [comment]
@krunal54 since I am not working on this actively anymore, please submit a PR if you want to get that working on my version too.

**Comment by krunal54** [comment]
Hi @all,

Android works fine now ads is playing but in IOS getting error:

node_modules/react-native-video/ios/Video/RCTVideo.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-video' from project 'Pods')

If anyone has any idea on it please share.

Thanks!

**Comment by krunal54** [comment]
I have investigated above comment issue and I fix as well.

If you got same error then please replace below 3 function as per below in:- Video/RCTVideo.m:

```
- (void)setupAdsLoader {
    self.adsLoader = [[IMAAdsLoader alloc] initWithSettings:nil];
    self.adsLoader.delegate = self;
}

- (void)requestAds {
  // Create an ad display container for ad rendering.
  IMAAdDisplayContainer *adDisplayContainer =
      [[IMAAdDisplayContainer alloc] initWithAdContainer:self
                                          viewController:self.reactViewController
                                          companionSlots:nil];
   // Create an ad request with our ad tag, display container, and optional user context.
  IMAAdsRequest *request = [[IMAAdsRequest alloc] initWithAdTagUrl:_adTagUrl
                                                adDisplayContainer:adDisplayContainer
                                                   contentPlayhead:self.contentPlayhead
                                                       userContext:nil];
  [self.adsLoader requestAdsWithRequest:request];
}

#pragma mark AdsLoader Delegates

- (void)adsLoader:(IMAAdsLoader *)loader adsLoadedWithData:(IMAAdsLoadedData *)adsLoadedData {
 // Grab the instance of the IMAAdsManager and set ourselves as the delegate.
  self.adsManager = adsLoadedData.adsManager;
  self.adsManager.delegate = self;
  // Create ads rendering settings to tell the SDK to use the in-app browser.
  IMAAdsRenderingSettings *adsRenderingSettings = [[IMAAdsRenderingSettings alloc] init];
  adsRenderingSettings.linkOpenerPresentingController  = self;
  // Initialize the ads manager.
  [self.adsManager initializeWithAdsRenderingSettings:adsRenderingSettings];
}
```




Reference link: https://github.com/googleads/googleads-ima-ios/blob/main/Objective-C/BasicExample/BasicExample/ViewController.m

**Comment by rohitsingh2410** [comment]
@krunal54 initially what was the issue, i also installed the library and not able to see any ads? any suggetions?

**Comment by krunal54** [comment]
Which platform? Android or iOS?

**Comment by rohitsingh2410** [comment]
@krunal54 Android

**Comment by rohitsingh2410** [comment]
> > @Utkarshkataria Have you tried my sample code ?
> > ```
> > const adTagUrl = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/"
> > + "ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp"
> > + "&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite"
> > + "%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=";
> > 
> > adTagUrl={adTagUrl}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and add it in your package.json, with spesific branch
> > ```
> >    "react-native-video": "git://github.com/RobbyWH/react-native-video.git#implement-ima-sdk",
> > ```
> 
> hello @arslan-akh have you tried this ?

if i do this after editing package.json i am getting 

`Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/nanohttpd/mimetypes.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s

    at checkExecSyncError (node:child_process:680:11)
    at execFileSync (node:child_process:699:15)
    at runOnAllDevices (/Users/deepak/Documents/vuc-device-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/deepak/Documents/vuc-device-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/deepak/Documents/vuc-device-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Command.handleAction (/Users/deepak/Documents/vuc-device-android/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)`

**Comment by hueniverse** [comment]
@krunal54 would you like to submit a PR with your proposed changes?

**Comment by avencat** [comment]
@hueniverse I opened a PR with those changes: #2923 (thank you @olgunkaya @krunal54 and @RobbyWH for pointing me in the right direction) If anyone wants to review, this could be merged! 🙂

Thank you all for your contributions!

**Comment by FR073N** [comment]
Good job @avencat . We also need this on or side and we were thinking of tweaking this MR. Good job, your PR seems to work on our side too !

**Comment by freeboub** [comment]
After 5 years of activity, I happy to say this ticket is closed !
Let's follow up  in next ticket.
Thank you everybody !
