### ISSUE TITLE
Video Not Paused in first load (Android)

### ISSUE THREAD

**Issue by RZulfikri** [TheWidlarzGroup/react-native-video#489]
I used paused props in my code to stop autoplay video, it work on IOS but not work in Android. Anyone know how to stop automatic playing video ?

**Comment by RZulfikri** [comment]
sorry, after i try again. it can be handle with onLoad then change paused state to true.

**Comment by mgufrone** [comment]
setting the state is somehow not working. I literally set the pause prop with true and it doesn't work. in Android, it is still autoplayed

**Comment by mgufrone** [comment]
nvm, I need to use `master` instead.
