### ISSUE TITLE
Play source outside of Main bundle directory

### ISSUE THREAD

**Issue by maxs15** [TheWidlarzGroup/react-native-video#49]
I have an issue trying to play a video that I recorded, the file is outside of the mainBundle directory and so the player can't of course find the file.
The issue is related to that code:

```
NSURL *url = (isNetwork || isAsset) ?
    [NSURL URLWithString:uri] :
    [[NSURL alloc] initFileURLWithPath:[[NSBundle mainBundle] pathForResource:uri ofType:type]];
```

A solution would be to override the isNetwork property, but unfortunately impossible on the js side, I think the variable is initialized by React.
@brentvatne do you have any idea ? We could maybe create a prop to force the use of URLWithString

Thanks,

**Comment by brentvatne** [comment]
Makes sense, this seems like it would be very useful. We can add an `isStatic` option to the source object. Do you have time to submit a PR for it?

**Comment by maxs15** [comment]
Sure, will submit that

**Comment by markburns** [comment]
Looks like this needs closing? Re: https://github.com/brentvatne/react-native-video/pull/54

**Comment by brentvatne** [comment]
Yup :smile: Thanks
