### ISSUE TITLE
can't play youtube videos (ios / android)

### ISSUE THREAD

**Issue by cinder92** [TheWidlarzGroup/react-native-video#493]
Hello thanks for your plugin, im not receiving any kind of error, i only see a white space square. this is my code

```
                                 <Video
					source={{uri:props.video.url,mainVer: 1, patchVer: 0}}
					resizeMode="cover"
					playInBackground={false}
					playWhenInactive={false}
					style={styles.video}
				 />
```

this is what i see

![captura de pantalla 2017-02-13 a la s 18 18 13](https://cloud.githubusercontent.com/assets/4725556/22909281/c592c81e-f218-11e6-8b17-ffbb5b16e20e.png)

is there any fix for that?

**Comment by neuberoliveira** [comment]
Look at the issue #358 maybe its related to your question

**Comment by cobarx** [comment]
react-native-video is not going to be able to play YouTube videos since they webpages rather than video files. In order to get this to work, you would either need to get a direct link to the mp4 on YouTube or display the whole YouTube page in a WebView.
