### ISSUE TITLE
Videos on exoplayer gets dark when used in modal

### ISSUE THREAD

**Issue by note89** [TheWidlarzGroup/react-native-video#496]
Hi i switched to using Exoplayer and it is much faster nice!. 
But when i add a video in a modal it's like it has a filter on it now. 
Whites become gray.

![image](https://cloud.githubusercontent.com/assets/6696963/23030538/5c92007a-f46e-11e6-8501-9d422a1127ed.png)

supposed to be white.

**Comment by note89** [comment]
![image](https://cloud.githubusercontent.com/assets/6696963/23030713/d7780c3a-f46e-11e6-908b-b401814b7aac.png)
When not in a modal

**Comment by perttuim** [comment]
I seem to be getting the same behaviour. Did you manage to solve this?

EDIT: Setting `transparent={true}` on Modal seems to fix the issue. https://facebook.github.io/react-native/docs/modal.html#transparent.

**Comment by emilioicai** [comment]
the `transparent={true}` did the trick
