### ISSUE TITLE
Is there any method to play a video given its URL ? 

### ISSUE THREAD

**Issue by MorrisDa** [TheWidlarzGroup/react-native-video#498]
Hello, searching through issues and documentation i cannot find any method to open a video player given a video's URL.

I would like to add a method in my component to perform something like this:

`VideoPlayer.play(videoUrl) `

This may prompt an in-app native video player for both IOS and Android. The main point here is that i don't need to create any component.

Thank you for any help

**Comment by gorjanz** [comment]
I think you can use the component the same as in the example, only substituting (in the props passed to the component):
```
source={{uri: YOUR_VIDEO_URL}}
```
But you still have to instantiate it, and include it in the views seen on the screen.

**Comment by Ponnak** [comment]
Actually I use source={{uri: YOUR_VIDEO_URL}} but I can't play the video url from youtube. It worked fine if I use the local video by source={require('./broadchurch.mp4')}

Any suggestion for this issue, due to I am new with react native. 
Regards,

**Comment by dittmarconsulting** [comment]
I have the same question. Is there a way to play YouTube videos? Tried

`source={{uri: 'https://www.youtube.com/watch?v=7RaoCymNbuQ'}}`

but nothing happens.

**Comment by martinlockett** [comment]
See https://github.com/react-native-community/react-native-video/issues/358

**Comment by cobarx** [comment]
It's not possible to play YouTube videos.

**Comment by zyan-dev** [comment]
Use react-native-youtube instead of this package. :)

**Comment by smironescu** [comment]
This would be awesome to have support for youtube videos! 🥳
