### ISSUE TITLE
Android: Streaming remote video waits for whole download to play

### ISSUE THREAD

**Issue by nathanmalishev** [TheWidlarzGroup/react-native-video#499]
Streaming a video on android waits for the whole video to download before playing. 
This is super evident on some longer videos, as there is a huge delay (or the video doesn't start) before the video starts playing.

This might be more of a general issue of porting VideoView to react-native.

RN: 0.39/0.41
Android: 7.1.1 - 25.0.2
React-Native-Video: 0.9.0 / 1.0.0

**Comment by xavieramoros** [comment]
Check these two issues, they might be related to your problem:
#451 
#494 

Apparently the UI gets blocked while loading the video.

**Comment by arribbar** [comment]
Check this one as well https://github.com/react-native-community/react-native-video/issues/555.
Using exoplayer fixed the issue for me
