### ISSUE TITLE
onProgress is still called after onEnd...

### ISSUE THREAD

**Issue by lizhaobomb** [TheWidlarzGroup/react-native-video#501]
onProgress is still called after onEnd called how could i solve this problem

**Comment by allisonnn** [comment]
I have the same problem. I'm using RN 0.41 in ios.

**Comment by linmic** [comment]
@lizhaobomb You might need something like `this.isEnded` and use it for your judgement in your `onProgress` handler for now.

`if (!this.isEnded) { ... }`

**Comment by NUWW** [comment]
Find the solution on https://github.com/react-native-community/react-native-video/issues/545
