### ISSUE TITLE
Doesn't work in phone device

### ISSUE THREAD

**Issue by JunhyeokHeo** [TheWidlarzGroup/react-native-video#503]
RN: 0.41.2
Android: 6.0.1 - 25.0.2

i played my background video in AVD(Amulater) but not work in my phone, Galaxy 6 .
but i can listen video sounds but can't see.

what happen??

**Comment by AndrewJack** [comment]
Emulators often don't properly implement components of Android’s media stack, try with a real device. 

https://google.github.io/ExoPlayer/faqs.html

**Comment by annelorraineuy** [comment]
@JunhyeokHeo try setting a height and width to your video. Same thing happened to me at first.
