### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by GregoryTravis** [TheWidlarzGroup/react-native-video#508]
I've installed react-native-video using:

npm install -S react-native-video
react-native link

When I go to build and run on the iOS simulator, I get numerous include errors like this:

'React/Views/RCTViewManager.h' file not found

I'm running react-native 0.38.0 and react-native-video@1.0.0.

**Comment by annelorraineuy** [comment]
Install `react-native-video@0.9.0`

**Comment by GregoryTravis** [comment]
That worked -- thanks!
