### ISSUE TITLE
ExoPlayer shows blank screen  

### ISSUE THREAD

**Issue by muvv** [TheWidlarzGroup/react-native-video#510]
RN version: 0.41.2 
react-native-video version: 1.0.0
Player used: ExoPlayer
Android versions tested: 6 and 7

Issue: When player is unbale to fetch the video's source or when the video is buffering on low speeds (stopping midway when playing), the player is displaying a blank screen. This is creating a problem when going back and trying to play another video (blank screen is displayed). No errors are thrown / displayed during this process.

Please check and confirm. Hoping this issue gets resolved soon. Will post logs if needed. Thanks

**Comment by ghost** [comment]
Same issue here
