### ISSUE TITLE
iOS: onEnd does not fire after video finishes playing

### ISSUE THREAD

**Issue by annelorraineuy** [TheWidlarzGroup/react-native-video#511]
On iOS, `onEnd()` doesn't get called after the video finishes playing. Right now my workaround is really bad, setting a timer based on the video length to trigger my post-video action.

react-native: 0.39.2
react-native-video: 0.9.0

Here is my code:
```
class SplashAnimated extends Component {
    onEnd() {
        _delay(function(parent){
            parent.props.setPlayed(true);
        }, 4300, this)
    }

    render() {
        const { containerStyle, splashVideo } = styles;

        return (
            <View style={containerStyle}>
                <View style={{
                    height: height * 0.35
                }} />
                <View>
                    <Video
                        source={require('./../assets/splash/splash.mp4')}
                        ref={(ref) => {
                         this.splashPlayer = ref
                       }}
                        resizeMode="contain"
                        repeat={false}
                        pause={false}
                        style={splashVideo}
                        onEnd={this.onEnd()} <-- does not get called on iOS but works on android (should be onEnd, don't mind onEnd() its my hack for now)
                    />
                </View>
            </View>
        )
    }
}
```

**Comment by tkmct** [comment]
Same problem is happening to me.  

But in this piece of code, it seems different problem.

`onEnd={this.onEnd()}`
should be 
`onEnd={this.onEnd}`


In my case, 
```
            <Video
              source={{ uri }}
              ref={(ref) => {
              this.player = ref
            }}
              style={[styles.videoStyle ]}
              resizeMode={'cover'}
              playWhenInactive={false}
              muted={true}
              rate={this.state.videoRate}
              onEnd={this.onVideoEnd}
            />

```

onVideoEnd is not called after finishing video play.

**Comment by annelorraineuy** [comment]
Yeah i did it on purpose. `onEnd()` to immediately trigger the function on render, and set a timer to delay the execution inside. Its a hack for now.

**Comment by cobarx** [comment]
`onEnd` is working for me with the latest version.

**Comment by RishavKumar-3796** [comment]
Why closed?

**Comment by baughmann** [comment]
> Why closed?

I agree. It seems to be broken still.

**Comment by baughmann** [comment]
> > Why closed?
> 
> I agree. It seems to be broken still.

Nevermind. It appears to be working, but `onVideoEnd` is not. I don't see `onVideoEnd` in the docs. Why is it in the type definition? The same goes for stuff like `onVideoProgress`

**Comment by tosnextly** [comment]
Change To:
onEnd={() => console.log('end')}

**Comment by pedropuppim** [comment]
Change to:
onEnd={() => console.log('end')}
