### ISSUE TITLE
duration on mp3 files loaded as -0.001

### ISSUE THREAD

**Issue by djtango** [TheWidlarzGroup/react-native-video#513]
When using react-native-video to load a local mp3 asset, the duration is calculated as -0.001 in the onLoad callback.

I've tried adding a "duration" tag to the mp3 file but this doesn't seem to help. Is anyone able to explain where duration comes from?

**Comment by djtango** [comment]
Hi is anyone able to shed any light on this? It seems that for any locally added MP3 file required via the react-native `require('path/to/asset.mp3')` syntax doesn't seem to be picked up correctly by the Android media player.

**Comment by djtango** [comment]
Any news on this?

**Comment by smkhalsa** [comment]
@djtango Did you ever find a solution for this?

I'm getting a duration of `0` for mp3 files. Interestingly, it worked fine when I was serving my mp3s directly from an amazon s3 bucket. However, now that I'm using a CDN (fastly), I get a duration of `0` the first time I play the track, then if I try to play it again, I get the correct duration.

**Comment by smkhalsa** [comment]
Sot it looks like the issue is that duration [here](https://github.com/react-native-community/react-native-video/blob/master/ios/RCTVideo.m#L357) is returned as NaN. 

There's been some discussion on this, but I haven't been able to get a working solution yet.

http://stackoverflow.com/questions/19059321/ios-7-avplayer-avplayeritem-duration-incorrect-in-ios-7

**Comment by xsgkaka** [comment]
when i load a mp3 in /data/data/com.xxx/ dir ,the duration  is 0.

i got a working solution.
bad code:
`<Video
                    source={{uri:this.state.mp3Uri}}
                    paused={!this.state.isPlaying}
                    ref={(ref) => {
                        this.player = ref
                    }}
                    onProgress={(obj) => {
                        //console.log(obj);
                    }}
                    onLoad={(duration) => {
                        console.log(duration);
                    }}
                />`
good code:
`<Video
                source={this.state.mp3Uri}
                paused={!this.state.isPlaying}
                ref={(ref) => {
                    this.player = ref
                }}
                onProgress={(obj) => {
                    //console.log(obj);
                }}
                onLoad={(obj) => {
                    this.state.totalSeconds = obj.duration;
                    this.setState(this.state);
                }}
            />`
so , Got it?

**Comment by thomasobrien99** [comment]
I was having this problem with some mp3 files but not others (specifically twilio files). My solution right now is to add the following to RCTVideo.m
```
if (isnan(duration)) {
          NSData *_objectData = [NSData dataWithContentsOfURL: _sourceURL];
          AVAudioPlayer *audioPlayer = [[AVAudioPlayer alloc] initWithData:_objectData error:nil];
          duration = audioPlayer.duration;
        }
```
beginning on line 375, where `_sourceURL` = the url of the mp3

**Comment by dayudodo** [comment]
same problem with 2.0.0
