### ISSUE TITLE
any plan for react-native-image

### ISSUE THREAD

**Issue by musicode** [TheWidlarzGroup/react-native-video#514]
The `<Image />` component of react native is so weak:

1. don't support cache
2. don't support webp
3. don't support zoom by double tap
4. don't support drag by finger
5. ...

if an app don't have these feature, I can't imagine how to express the idea.

**Comment by linmic** [comment]
@musicode I believe this is the wrong place for the problems you mentioned, you might try to file a report at [react-native issues](https://github.com/facebook/react-native/issues).

**Comment by sunkibaek** [comment]
you can try https://github.com/huiseoul/react-native-fit-image for some of those features
