### ISSUE TITLE
Save/cache Vimeo videos

### ISSUE THREAD

**Issue by davingreen** [TheWidlarzGroup/react-native-video#516]
This is more of a general question. Is it possible to save a streamed video locally and/or cache it? We're trying to support offline mode for an app that streams from Vimeo. Any ideas, links, guides, etc would be helpful.

Thanks!

**Comment by ghost** [comment]
I think you should set up a custom node server that downloads from Vimeo and send it to your client.
Package : https://github.com/sub2u/vimeo-downloader

**Comment by sibelius** [comment]
@davingreen vimeo videos works with this component?
