### ISSUE TITLE
onBuffer doesn't provide progress

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#519]
`onBuffer` only provides a boolean state and not progress as stated in the docs. Are there methods to get the progress and if so can the documentation be updated to reflect this?

**Comment by b-asaf** [comment]
for progress you should use 'onProgress'.

handleProgressBarPress = (e) => {
        const position = e.nativeEvent.locationX;
        const progress = (position / [progressBarWidth]) * [videoDuration];
        this.player.seek(progress);
    }

**Comment by b-asaf** [comment]
is onBuffer triggers on your android device, or only on your iOS device?
I am working with RN 0.45.1 and react-native-video 1.2.0

**Comment by prestonlanetz** [comment]
face the same problem

**Comment by marlti7** [comment]
face the same problem

**Comment by xpertystanalyst** [comment]
onBuffer never call on android. 
I am working with RN 0.60.5 and "react-native-video": "^5.0.2",
