### ISSUE TITLE
progressUpdateInterval Not Working

### ISSUE THREAD

**Issue by flybayer** [TheWidlarzGroup/react-native-video#521]
I'm trying to do this:
```jsx
<Video
  source={{uri: this.props.uri}}
  repeat
  resizeMode="cover"
  progressUpdateInterval={16}
  onProgress={play => this.setState({
    playProgress: play.currentTime / play.playableDuration
  })}
/>
```

But onProgress is still being called on the default 250ms interval.

I added some logging in this component and found [setSource()](https://github.com/react-native-community/react-native-video/blob/d792427ce113637f127fb6bc2d92417c668882ce/ios/RCTVideo.m#L250) is being called **before** [setProgressUpdateInterval()](https://github.com/react-native-community/react-native-video/blob/d792427ce113637f127fb6bc2d92417c668882ce/ios/RCTVideo.m#L694), so `setSource()` is always using the default.

I couldn't figure out how to fix it :(

### Versions
```
iPhone 7+
react-native-video: 1.0.0
react-native: 0.42.0
```

**Comment by maltz** [comment]
+1

**Comment by maltz** [comment]
I fiexd ract-native-video/ios/RCTVideo.m  line63
```
// _progressUpdateInterval = 250;
_progressUpdateInterval = 500;
```
It works.

**Comment by skizzo** [comment]
+1

**Comment by Sundin** [comment]
+1

**Comment by ArtisanalPickle** [comment]
+1 please address this

**Comment by ouabing** [comment]
+1 here
