### ISSUE TITLE
onPregress and onEnd callback does not work RN version 0.39.0, react-native-video version 0.9.0

### ISSUE THREAD

**Issue by rhwish** [TheWidlarzGroup/react-native-video#523]
`render() {`
       ` const { data } = this.props;`
      ` const flexCompleted = this.getCurrentTimePercentage() * 100;`
        `const flexRemaining = (1 - this.getCurrentTimePercentage()) * 100;`
       ` return (`
           `<View style={styles.container}>`
                `<View style={styles.videoBox}>`
                    `<Video`
                        `source={{uri: 'http://cdn1.highfaner.com/2017-03/06/Video1488813979559.mp4'}}`
                        `style={styles.video}`
                        `rate={this.state.rate}`
                       ` paused={this.state.paused}`
                        `volume={this.state.volume}`
                        `muted={this.state.muted}`
                        `resizeMode={this.state.resizeMode}`
                        `repeat={false}`
                        `onLoadStart={this._onLoadStart}`
                        `onLoad={this._onLoad}`
                       `onProgress={this._onProgress}`
                        `onEnd={this._onEnd}`
                        `onError={this._onError}`
                        `/>`
                    `<View style={styles.progress}>`
                        `<View style={[styles.innerProgressCompleted, {flex: flexCompleted}]} />`
                        `<View style={[styles.innerProgressRemaining, {flex: flexRemaining}]} />`
                    `</View>`
                `</View>`
                `<Text onPress={() => { this.setState({paused:!this.state.paused})}}>暂停/播放</Text>`
            `</View>`
       ` );`
   ` }`

**Comment by henocdz** [comment]
did you find any fix for this?

**Comment by judemorrissey** [comment]
+1, no wonder my progress bar was not updating, logging out the currentTime from the onProgress callback param yields a small like it works the first time, but remains at that same number for the remainder of the playback

Edit: It would be useful I think if I mention that we are using react-native 0.42, and react-native-video 1.0.0

Edit again: Seems like my `onProgress` issue is resolved, not sure with what. We did upgrade just today to `react-native: ^0.42.3` while keeping `react-native-video: ^1.0`

**Comment by rhwish** [comment]
@henocdz I haven't find a way to fix it

**Comment by henocdz** [comment]
@SegmentControl You can find a working solution on #480 it works with RN 0.39.1

**Comment by cobarx** [comment]
@SegmentControl Please re-test with the latest release and let us know if it's not working. Also make sure to include which platform (iOS, Android, or ExoPlayer) is having the issue.
