### ISSUE TITLE
onBuffer doesn't report when buffering on iOS

### ISSUE THREAD

**Issue by deshiknaves** [TheWidlarzGroup/react-native-video#525]
I'm playing an audio file using the player and am noticing that buffer states are not reported correctly.

When the stream starts, it says it's buffering then says it's not, but it is buffering. Then the third time it says that it has finished buffering and starts playing. It's impossible to tell when it has completed buffering.

Then if I seek to a new time, the audio keep playing at the current time for a while before it has buffered and then moves on the new time. When this happens, there is no notification that it is buffering, but it does notify when buffering in over. It should say when it is buffering and when it finishes.

Is there something else I can use to find this state?

**Comment by caoyd** [comment]
Same here, android
onBuffer never fired

**Comment by alimot22** [comment]
onBuffer is not firing  on Android. Any solution ?

**Comment by xpertystanalyst** [comment]
onBuffer is not firing on android.
I am working with RN 0.60.5 and "react-native-video": "^5.0.2",
