### ISSUE TITLE
Render encoded MPEG-TS 

### ISSUE THREAD

**Issue by brikendr** [TheWidlarzGroup/react-native-video#527]
I was wondering if it is possible to use the Video component for rendering incoming MPEG-TS encoded data stream. The incoming data are captured by ffmpeg and are sent to a node server which in turn broadcasts the data to connected peers (react-native app) using websockets. Is there any way of rendering this constant incoming stream using the <Video /> component? 

Thank you in advance!

**Comment by Lizhooh** [comment]
[https://github.com/phoboslab/jsmpeg](https://github.com/phoboslab/jsmpeg)

Look, jsmpeg
Use `<WebView>` to get data from `websocket`, and then use WebGL / Canvas to render

**Comment by cchamikara** [comment]
@Lizhooh I tried but did not work

**Comment by billyjacoby** [comment]
Is there any way to get this to work? I'm trying to figure out how to stream a JSMPEG video to my react native app.
