### ISSUE TITLE
video playing multiple times 

### ISSUE THREAD

**Issue by dht** [TheWidlarzGroup/react-native-video#528]
Using the example code on Android API 22 the video runs twice with a delay. Render is called twice and onLoad is called twice. This is peculiar as the expected behaviour is the the video would pause and it's "double playing". I tried version 1.00 and 0.90, neither worked. Could it be something to do with redux?

      this.state = {
            rate: 1,
            volume: 1,
            muted: false,
            resizeMode: 'contain',
            duration: 0.0,
            currentTime: 0.0,
            paused: true
        }
        <VideoPlayer source={{uri: this.state.url}}   // Can be a URL or a local file.
                                 ref={(ref) => {this.player = ref}}                                      // Store reference
                                 style={styles.backgroundVideo}
                                 rate={this.state.rate}
                                 paused={this.state.paused}
                                 volume={this.state.volume}
                                 muted={this.state.muted}
                                 resizeMode={this.state.resizeMode}
                                 onLoad={this.onLoad}
                                 onProgress={this.onProgress}
                                 onEnd={this.onEnd}
                                 onAudioBecomingNoisy={this.onAudioBecomingNoisy}
                                 onAudioFocusChanged={this.onAudioFocusChanged}
                    />

**Comment by boypanjaitan16** [comment]
Having the same problem too, and why is it only on android ? in iOS seems fine

**Comment by joaohenrifranco** [comment]
@boypanjaitan16 This seems to be solved here https://github.com/react-native-community/react-native-video/issues/664#issuecomment-442304985
