### ISSUE TITLE
App freezes completely when attempting to play remote video with no data connection

### ISSUE THREAD

**Issue by j-rul** [TheWidlarzGroup/react-native-video#529]
Using version 1.00 and RN version is 0.40.0. When a remote url is passed to the player, it will freeze the UI and eventually just crash, if there is no internet connection.
This happens on android (have not yet tested on iOS)

**Comment by kamalk333** [comment]
I'm facing the same issue here. My screen gets freezed for couple of seconds and suddenly after then everything works fine.

**Comment by lwinkyawmyat** [comment]
I have the same problem on android.
`react-native@0.42.3`
`react-native-video@^1.0.0`

**Comment by Lizhooh** [comment]
It will block the entire UI thread, my android 4.4, will block at least 10s

**Comment by DavidVentura** [comment]
Same here

**Comment by haroonob** [comment]
any update. did any buddy manage to fine solution??

**Comment by j-rul** [comment]
Not yet, I reverted to an older version of the player, until this is resolved or I find a way around it.

**Comment by haroonob** [comment]
Could you tell me which version should I use. I am using react native 4.0 version

**Comment by j-rul** [comment]
0.9.0, have not encountered the issue with that version

**Comment by rogerkerse** [comment]
For me the whole ios app crashes when i have no connection
