### ISSUE TITLE
Properties not being set after altering media source

### ISSUE THREAD

**Issue by markburns** [TheWidlarzGroup/react-native-video#53]
I think there is a bug here: https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L133

I'm not sure what the fix is, but it seems that for example, the resizeMode property never gets set on the new instance created. I guess all the properties should be set, but I wasn't sure where this was occurring to be able to do a pull request.

**Comment by brentvatne** [comment]
Thanks for the report! 

I think we need to add `[self applyModifiers];` to https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L161

**Comment by markburns** [comment]
Fixed in https://github.com/brentvatne/react-native-video/commit/9723f8849fca2d750885256cd1d466dc51ff0ca8
