### ISSUE TITLE
[iOS: Question] Audio on mute mode

### ISSUE THREAD

**Issue by St1ma** [TheWidlarzGroup/react-native-video#531]
Hi

Could I keep audio ON for mute mode on iOS? To avoiding turning the ringer on for listening to the video?

Thank you

**Comment by shahen94** [comment]
Yes you can, you have to add this lines into your AppDelegate file.
I did that with swift, so you can just convert this lines to objective-c if needed.
```
do {
      try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with:AVAudioSessionCategoryOptions.mixWithOthers)
      print("AppDelegate: [AVPlayer] setCategory to Playback")
      do {
        try AVAudioSession.sharedInstance().setActive(true)
        print("AppDelegate: [AVPlayer] activate ")
      } catch let error as NSError {
        print("AppDelegate: Warning [AVPlayer] setCategory failed with error \(error)")
      }
    }
    catch let error as NSError {
      print("AppDelegate: Warning [AVPlayer] failed to change category: \(error)")
    }
```

**Comment by j3rin** [comment]
Obj - C

NSError *setCategoryErr = nil;
NSError *activationErr = nil;
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:&setCategoryErr];
[[AVAudioSession sharedInstance] setActive:YES error:&activationErr];

**Comment by cmoody** [comment]
Obj-c works like a charm.  Just remember to import the audio libraries at the top of the file.

```
#import <AVFoundation/AVFoundation.h>
#import <AudioToolbox/AudioToolbox.h>
```

**Comment by mattdwardle** [comment]
I am getting this error when adding the objective c code to either appdelgate files. I have no idea what I am doing with Objective C. I have added both imports also. Any ideas?
![screen shot 2017-10-16 at 12 23 57 pm](https://user-images.githubusercontent.com/22203166/31623306-0678e92a-b26d-11e7-9470-75df0f6e5165.png)

**Comment by xstable** [comment]
@j3rin @cmoody Can you show an example, where to add those Object-C Code?

**Comment by diogoqds** [comment]
https://github.com/react-native-community/react-native-video#ignoresilentswitch

**Comment by SamiChab** [comment]
Check this answer: https://github.com/react-native-community/react-native-video/issues/874#issuecomment-352590866
It solved the problem for me
