### ISSUE TITLE
Closed Captions

### ISSUE THREAD

**Issue by mosesmc52** [TheWidlarzGroup/react-native-video#538]
Are there any plans to implement closed captions. If so, how soon?

**Comment by ghost** [comment]
This is a community maintained project. Before any features are added a bug bash and keeping pace with RN is most important. Pulls welcome.

**Comment by MahmoudYaser1** [comment]
so what ??

**Comment by jsalazar24712** [comment]
Can you at least answer the question jhabdas?

**Comment by petrbela** [comment]
@jsalazar24712 The answer is anyone from the community (even you!) can build this feature and submit a PR. The core team doesn't have the capacity to work on this and there's no plan on when it will be done.

That being said, there's an effort at #972 to make this work.
