### ISSUE TITLE
NativeModules.UIManager.RCTVideo.Constants

### ISSUE THREAD

**Issue by darkfiredarkhalo** [TheWidlarzGroup/react-native-video#541]
nhandled JS Exception: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')

**Comment by darkfiredarkhalo** [comment]
nhandled JS Exception: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')

**Comment by ordram** [comment]
I also encountered such a problem

**Comment by MrPluto** [comment]
#468

**Comment by pppluto** [comment]
#468 
 for me,  have no idea because  `RCT` files should be ios only right? why i get this error on android
**solved (for me)**:later, i try to install it manually on ios and rebuild, it just ok 🤔 ,hope can help

**Comment by keyuanupup** [comment]
I have same problem!help me!

**Comment by roshan-shelar** [comment]
Facing the same issue in android. 
Please help.

**Comment by guokai1120** [comment]
My native project integrates the reactnative project i would like to develop a video module in my reactnative project i ask which good advice or demo hits hello

**Comment by piuccio** [comment]
looks very similar to #597 if this happen after you installed the package try

```
react-native link
# close the simulator
react-native run-android
```

**Comment by FullstackJack** [comment]
I have it working fine in iOS and Android, but now I'm trying to run my application on the tvOS build target, auto linking doesn't seem to work for that. Will probably need to edit the sub-project in XCode. Perhaps, we should fix the linker?

**Comment by jlemoscds** [comment]
react-native link is not working right. You need to do the configurations manually.

**Comment by Lipfroy** [comment]
to link library on iOS do next steps:
1)in XCode right click on "Libraries" folder and choose 'add files to *prjctname*'
then go to node_modules/react-native-video/ios/ and choose RCTVIdeo.xcodeproj
2) go to targets -> Build Phases ->Link Binary With Libraries hit +  and choose libRCTVideo.a
3)profit

**Comment by oguennec** [comment]
I confirm @piuccio comment.

> react-native link

 solved the issue on both iOS and Android for me with the following versions:

>     "react-native": "0.52.0",
>     "react-native-video": "^2.0.0"

Add the following in the script section of package.json if you want to link automatically after installing a new package that requires linking.

>  "postinstall": "react-native link",

**Comment by IgorGanapolsky** [comment]
I am having the same issue on android, despite having **"react-native-video": "^2.0.0",** in package.json.  What is the solution?

**Comment by judemanutd** [comment]
@Lipfroy thanks that worked

Using 
```
{
    "react": "^16.3.2",
    "react-native": "0.55.4",
    "react-native-video": "^2.0.0",
    "react-native-video-controls": "^2.2.1",
}
```
I can confirm it works on both iOS and android by using @Lipfroy [method ](https://github.com/react-native-community/react-native-video/issues/541#issuecomment-354708996)

**Comment by fabiancarlos** [comment]
This was the fix for me, i was using `react-native-navigation` and missed some configs:
https://stackoverflow.com/questions/45146173/does-react-native-video-work-with-react-native-navigation

**Comment by fahadhaq** [comment]
@Lipfroy you sunk my battleship, by that I mean thanks so much. Your solution is the only one that worked for me

**Comment by kotelesroberto** [comment]
Run the command of react-native link and after react-native run-android.

The first command links the dependencies and after that it will work!
