### ISSUE TITLE
onLoad, onError, onProgress not fired (IOS)

### ISSUE THREAD

**Issue by voeurnchy** [TheWidlarzGroup/react-native-video#542]
All this callback function not fired. Just Play the video on ios. but it works on android. 

        onLoad(data) {
            alert('load fired');
            console.log('On load fired!');
            this.setState({duration: data.duration});
        }

----------- 

         <Video
            source={require('./../resources/videos/guide.mp4')}
            style={videoStyle}
            rate={this.state.rate}
            paused={this.state.paused}
            volume={this.state.volume}
            muted={this.state.muted}
            resizeMode={this.state.resizeMode}
            onLoad={this.onLoad}
            onBuffer={this.onBuffer}
            onProgress={this.onProgress}
            onEnd={() => { AlertIOS.alert('Done!') }}
            repeat={true}
            controls={this.state.controls}
          />

Note: I Just copy code from [example\index.ios.js](https://github.com/react-native-community/react-native-video/blob/master/example/index.ios.js)

- RN is 0.38.1
- RN Video 0.9.0
- If I test with Latest version of RN(0.42.3) && RN Video(0.1.1) works fine.

**Comment by lwinkyawmyat** [comment]
You would make edits so as to change `onLoad={this.onLoad}` to `onLoad={this.onLoad.bind(this)}`.
### (or)
```javascript
...
  constructor(props) {
    ...
    this.onLoad = this.onLoad.bind(this);
    ...
  }
...
```
### (or)
```javascript
...
  onLoad = (data) => {
    alert('load fired');
    console.log('On load fired!');
    this.setState({duration: data.duration});
  }
...
```

**Comment by voeurnchy** [comment]
it show a syntax error 
I change to this still not alert

    ...
    onLoad = {(data) => {
        alert('load fired');
        console.log('On load fired!');
        this.setState({duration: data.duration});
    }}
    ...

**Comment by lwinkyawmyat** [comment]
you should use:
```javascript
...
onLoad =  (data) => {
    alert('load fired');
    console.log('On load fired!');
    this.setState({duration: data.duration});
} 
...
```

**Comment by voeurnchy** [comment]
Yes, I do. but still not work.

**Comment by lwinkyawmyat** [comment]
don't need `curly brackets( {} )` after `equal( = )`.

**Comment by voeurnchy** [comment]
if not use curly brackets it show me an error 

SyntaxError ... JSX value should be either an expression or a quoted JSX tex

**Comment by yuanliangYL** [comment]
Same issue, have you fixed it?

**Comment by shahen94** [comment]
+

**Comment by zachrnolan** [comment]
+1 onProgress isn't firing after I re-render the component with a new video uri. This only seems to be an issue on Android.

RN: 0.42.0
RN Video: 1.0.0

**Comment by voeurnchy** [comment]
Any idea? Or I need to upgrade my RN to the latest version? But @zachrnolan still has an issue with the latest version. How can I do?

**Comment by 7091lapS** [comment]
+1, none of these callbacks work on ios.
RN: 0.38.0
RN Video: 0.9.0

**Comment by ptfly** [comment]
Yep, same here, when repeat=true, onProgress not invoked after first play.
```
"react": "^16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-native-video": "^1.0.0",
```

**Comment by rachmcnamara** [comment]
I'm also seeing this on react-native-windows - onProgress doesn't fire after first play.

**Comment by Kwon11** [comment]
I am seeing this on iOS. Works on android. I can call my .onLoad function from debugger console (on iOS device that is malfunctioning) and get the behavior I want.

```javascript
@action onLoad = () => {
    console.log('fired')
    this.videoStyle = styles.active;
}

<Video
   ref={this.setPlayerRef}
   source={{ uri: this.source, type: 'mp4' }}
   style={this.videoStyle}
   resizeMode={resizeMode}
   onLoad={this.onLoad}
   rate={1.0}
   muted
   repeat
  />
```

**Comment by lossen** [comment]
I had the same problem. I solved this problem this way:

```javascript
render() {
      const onProgress = (data) => {
          console.log(JSON.stringify(data))
      }
      return (
          <View style={{marginBottom:64}}>
              <VideoPlayer
                  onProgress={onProgress}
                  endWithThumbnail
                  thumbnail={{ uri: this.state.thumbnailUrl }}
                  video={{ uri: this.state.videoUrl }}
                  videoWidth={this.state.video.width}
                  videoHeight={this.state.video.height}
                  duration={this.state.video.duration}
                  customStyles={{
                    wrapper:{
                      alignSelf:'stretch',
                      marginBottom:0
                    }
                  }}
              />
              {this.props.blocked &&
              <View style={[styles.blockedVideo]}>
                  <TouchableOpacity activeOpacity={0.8} style={styles.blockedVideoIconContainer} onPress={() => this.props.toggleSubscriberModalVisible(true)}>
                      <Icon name='md-lock' style={{fontSize:35,color:'#fff'}}/>
                  </TouchableOpacity>
              </View>
              }
              <ModalSubscriber/>
          </View>
    );
```

**Comment by paraswatts** [comment]
I am facing the same problem. Have you been able to solve this?

**Comment by feliperaul** [comment]
Same here, onLoad doesn't fire on iOS but it does in Android. 

RN version 0.52.0

**Comment by xoapit** [comment]
In my case, onLoad doesn't fire on Android also.
