### ISSUE TITLE
Fairplay and Widevine DRM support?

### ISSUE THREAD

**Issue by Phenek** [TheWidlarzGroup/react-native-video#546]
Hello guys,

Do react-native-video support Fairplay and Widevine DRM?
Will it do it?

If not there is any other solution?

**Comment by ghost** [comment]
> Do react-native-video support Fairplay and Widevine DRM?

Not as far as I know. Will it? Probably not. Other solutions? Unknown. Why do you ask?

**Comment by Phenek** [comment]
Hello @jhabdas ,
I asking that, for making a VOD services with DRM encryptions like Netflix!
Thanks,

**Comment by shaneneal** [comment]
@clovs did you mange to find a solution/alternative?

**Comment by wmucheru** [comment]
I'm also interested in DRM playback support for a similar application. Was this ever looked into?

**Comment by danielmarino24i** [comment]
I would suggest to check this PR: https://github.com/react-native-community/react-native-video/pull/1445
