### ISSUE TITLE
Cannot get it running on Win10

### ISSUE THREAD

**Issue by adamledwards** [TheWidlarzGroup/react-native-video#548]
Hi,

We're having issues getting the library running on windows 10, I've tried the example too and we are still having issues.
The strange thing is onLoadStart, onLoad and onProgress all fire but we hear no sounds and see no video. 
There are no visible errors from the CLI. 
Has anyone else had any issues like this?
I know its a long shot and wish I could be more helpful in sending debug info

**Comment by ghost** [comment]
@adamledwards please try and provide debug some debug info, or close this and move to StackOverflow for support. Thanks!

**Comment by adamledwards** [comment]
Hi jhabdas, 

Thanks for the reply, it turns out we was targeting an old version of Windows 10. 
To use the MediaPlayerElement you need to be running Windows 10, version 1607 (anniversary update)
From docs.microsoft.com

> MediaPlayerElement is only available in Windows 10, version 1607 and up. If you are developing an app for an earlier version of Windows 10 you will need to use MediaElement instead. All of the recommendations on this page apply to MediaElement as well.

https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/media-playback

We have found that if your target an old version it results in just audio playback of a video file.

To change this go to properties on your project and update Target version to Windows 10, Anniversary Edition 
![image](https://cloud.githubusercontent.com/assets/5575331/24753868/0895ea2a-1acc-11e7-9ac4-a3869cdf2cef.png)

**Comment by ghost** [comment]
@adamledwards awesome. how'd you figure that out? strong will I'm guessing 😜 . thanks for leaving the info for others.

**Comment by adamledwards** [comment]
Haha It was down to pure luck :) btw great work on this module.
