### ISSUE TITLE
[iOS] Not getting callback when fullscreen player is dismissed via controls

### ISSUE THREAD

**Issue by acgourley** [TheWidlarzGroup/react-native-video#552]
I would expect onVideoFullscreenPlayerWillDismiss or onVideoFullscreenPlayerDidDismiss to trigger, but they do not seem to be either on device or simulator. 

Testing on iOS 10 with RN 41 and react-native-video 1.0.0

**Comment by qamil** [comment]
Hey @acgourley 
Looking at `VideoManager.m`, I had the same expectation. 
After debugging things a little bit I discovered that these are the right props: 
* `onFullscreenPlayerWillPresent`
* `onFullscreenPlayerDidPresent`
* `onFullscreenPlayerWillDismiss`
* `onFullscreenPlayerDidDismiss`

Hope this helps.

**Comment by ciriac** [comment]
Can confirm this works for me.

`          <Video
            onFullscreenPlayerWillDismiss={this._onFullscreenPlayerWillDismiss.bind(this)}
          />`

**Comment by AnisDerbel** [comment]
it's not working for me the callback onFullscreenPlayerWillDismiss

**Comment by GuillaumeMunsch** [comment]
This is still not working. Either onFullscreenPlayerWillDismiss or onFullscreenPlayerDidDismiss.
Tested with `react-native-video: 3.2.1` and `react-native: 0.57.5`

**Comment by fukuball** [comment]
Not working with `"react-native-video": "^4.2.0"` and `"react-native": "0.57.7"`

**Comment by nickinit** [comment]
Not working with ```  "react-native": "^0.57.3"``` and ```"react-native-video": "4.3.0"``` either

**Comment by thanhdevapp** [comment]
Not working with `"react-native": "^0.57.7"` and `"react-native-video": "4.3.1"`

**Comment by livfwd** [comment]
We're running into the same issue. Any updates on this?

**Comment by fubar** [comment]
Based on my tests it seems like those events are only emitted when fullscreen mode is opened through the player's functionality (ie. `presentFullscreenPlayer`), but not via the expand icon in the upper left corner of the video. There seem to be various issues with fullscreen behaviour, such as https://github.com/react-native-community/react-native-video/issues/1319. Given how long these issues have been unresolved, I wouldn't hold my breath for them to be fixed anytime soon.

**Comment by CHaNGeTe** [comment]
Can you check on this PR?
https://github.com/react-native-community/react-native-video/pull/1669

**Comment by jeremyfrancis** [comment]
This is a serious problem. Is someone able to fix this?

**Comment by danlupascu** [comment]
I'm having the same problem - none of the callbacks are working, any chance this could be fixed?

**Comment by softmastx** [comment]
Same here!
"react-native-video": "^5.1.0-alpha8", iOS Simulator 14.2

**Comment by OmarCocchiarella** [comment]
I'm having the same problem

**Comment by joaocosta9** [comment]
any updates on this?

**Comment by EgorGitHub11** [comment]
any updates?

**Comment by saadamjad** [comment]
any update please ? still facing same issues .  these callbacks are not trigger
onFullscreenPlayerWillDismiss
onFullscreenPlayerDidDismiss

**Comment by jsaq007** [comment]
Having the same issue.. any news on a fix?

**Comment by hueniverse** [comment]
Can someone please try out #2379 and let us know if it fixes the issue?
