### ISSUE TITLE
Play next audio in background mode

### ISSUE THREAD

**Issue by nhoclove9x** [TheWidlarzGroup/react-native-video#553]
I was problem while play audio finished go event onend() play next audio url but react-native-video stop buffer new audio url.
How to make background mode start buffer new audio url and playing.

**Comment by mvpdream** [comment]
@nhoclove9x Is there any solution for the landlord? Please.

**Comment by babydanger** [comment]
same problem :(

**Comment by waqaramjad** [comment]
same i want next video to buffer while one is playing

**Comment by tannguyen05** [comment]
same issues :((

**Comment by duansailong** [comment]
same issues :((
