### ISSUE TITLE
[Android] onProgress fired multiple times and before playback actually starts

### ISSUE THREAD

**Issue by maxschmeling** [TheWidlarzGroup/react-native-video#554]
The Android `onProgress` handler is called multiple times with a `currentTime` of `0` prior to playback actually happening.

I'm playing videos from the CloudFront. I'm on `react-native@0.42.3` and have `react-native-video` referenced from the `master` branch.

It doesn't seem to be an issue in iOS.

**Comment by maxschmeling** [comment]
This seems to be because the [progress handler is fired](https://github.com/react-native-community/react-native-video/blob/c45f5f5b38d516ceb0d8e1421cbe3946e475e069/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L122) in a `Runnable` that runs every `{progressUpdateInterval}` milliseconds. It doesn't wait for the the video to actually begin playing before firing the event.

I'm not very familiar with the underlying API (not a Java or Android developer typically), but in a quick search I wasn't able to find a good way to wait for the `MediaPlayer` to actually start playing before sending the event (without missing the initial `0`).

Maybe this is something the new `ExoPlayer` stuff will be able to handle? I don't know much about that. I also don't know what the timeline is on that totally replacing the `MediaPlayer` implementation.

For now, it might be good to [postDelayed](https://github.com/react-native-community/react-native-video/blob/c45f5f5b38d516ceb0d8e1421cbe3946e475e069/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L133) with a small `delayMillis` until the first time `mMediaPlayer.getCurrentPosition()` returns a non-zero value, then fire the event and start calling `postDelayed` with the `progressUpdateInterval` specified in `props`.

This would mean no `currentTime=0` progress event would get called. If that's a problem, the first progress event emission could be sent with `currentTime=0` (maybe with a guard to make sure the actual `currentTime` is roughly within that smaller `delayMillis` from `0`).

**Comment by gudwns0102** [comment]
I have same issue. Only on android, when I trigger 'seek' method of Video component, onProgress callback runs twice in given interval. If I trigger seek n times, n+1 onProgress callback runs in given interval and the device get slower. I wonder why this issue is not discussed well.
