### ISSUE TITLE
Android: UI gets blocked while loading the remote video

### ISSUE THREAD

**Issue by izadmehr** [TheWidlarzGroup/react-native-video#555]
On android for remote videos, player block UI until onLoadStart called. There isn't any problem with iOS devices. Is there any solution?

react-native@0.42.3
react-native-video@^1.0.0

```javascript
{!!this.state.url &&
          <Video
                 onLoadStart={()=>{
                   console.warn('onVideoLoadStart');
                 }}
                 source={{uri: this.state.url}}
                 resizeMode="contain"
            />
}
```

**Comment by zackz-woolloo** [comment]
yeah, I am having the same issue. seems like the render video player process is blocking the UI thread

**Comment by deshiknaves** [comment]
I'm having exactly the same issue. Anyone have a fix for this or a workaround?

**Comment by deshiknaves** [comment]
I've found using the Exoplayer fixes this issue. https://github.com/react-native-community/react-native-video/pull/426

**Comment by izadmehr** [comment]
@deshiknaves is right.
The problem came from not using ExoPlayer.
For using ExoPlayer update android/settings.gradle: 
```javascript
-project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
+project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by manuTro** [comment]
@izadmehr I updated settings.grandle as you said but now the video hasn't been load, and I got a 401 error. Did you got the same behaviour?

**Comment by izadmehr** [comment]
@manuTro. It solved by using ExoPlayer. Maybe some other thing is making the error.

**Comment by manuTro** [comment]
@deshiknaves By using exoplayer I got other problems (issue https://github.com/react-native-community/react-native-video/issues/683 and issue https://github.com/react-native-community/react-native-video/issues/693). Is there another solution? thanks

**Comment by deshiknaves** [comment]
I haven't been using it as a video player. Sorry.

**Comment by maagee** [comment]
A low version of android flash back
