### ISSUE TITLE
Android: Can't access videos saved as .zip expansion file

### ISSUE THREAD

**Issue by dgurns** [TheWidlarzGroup/react-native-video#558]
I'm trying to access videos from an Android expansion file, which was uploaded in .zip format with no compression. Looking at the react-native-video source code, it seems like .zip expansion files are supported, but it's not working and I can't figure out why. Here's the basic code:

`<Video source={{ uri: 'v1', mainVer: 4, patchVer: 0 }} />`

(With 4 being the version number from the uploaded expansion file)

Any ideas why this isn't working? Is it the zip format?

**Comment by scgough** [comment]
Is your zip file in the right location on your Android device? 

If you step through the code in debug mode using Android Studio, bookmark here:

 `https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L256` 



...and check that `expansionFile` is not null.

**Comment by AntoineGrandchamp** [comment]
I have the same problem. My zip file is in Android/obb/<My.Package>/. When I put a breakpoint on the line you pointed, `expansionFile` is null.
