### ISSUE TITLE
Size Video Height Based on Available Width and Aspect Ratio

### ISSUE THREAD

**Issue by FuadBalashov** [TheWidlarzGroup/react-native-video#566]
I would like for videos to fill 100% of their container width while growing their height as much as possible and maintaining their aspect ratios.
examples:
![video scaling behavior mockup](https://cloud.githubusercontent.com/assets/7839848/24919472/d1dd89a4-1eb1-11e7-8763-86c1ee610b9f.png)

I tried to achieve this by setting a width to 100% on the video component and then using the different resizeMode's to get the video component's height to scale itself based on the aspect ratio and given width. However if I did not set a height on the video component then it would have a height of 0.

The only approach I can think of is to use the dimensions provided in onLoad to resize the video view. Before committing to that I wanted to see if I was missing something obvious.

**Comment by EdenGottlieb** [comment]
I am having the same problem, no solution yet. Seems rather basic, doesn't it?

Edit: I tried your workaround and it's fine.

I set my default height to match a 16:9 video in the constructor:
```javascript
this.state = { height: Dimensions.get('window').width / (16 / 9) };
```
Set my height to equal the one in state:
```javascript
style={{ height: this.state.height }}
```
And set onLoad to a setHeight function:
```javascript
    setHeight = (e) => {
        const naturalRatio = 16 / 9;
        const videoRatio = e.naturalSize.width / e.naturalSize.height;
        if (videoRatio !== naturalRatio) {
           this.setState({ height: (this.state.height * naturalRatio) / videoRatio });
        }
    }
```
If you want low-res videos to be small and centered I think you should use `alignItems = 'center'` in the style of your container. 
If you want low-res video to stretch put `resizeMode = "stretch"` on your Video component.

Really ugly but it works fine, and since most videos are 16:9 it shouldn't impact performance too much.

**Comment by gezichenshan** [comment]
I searched for this one #205 , BUT it returns a wrong value.

**Comment by RWOverdijk** [comment]
Did you find any other solutions besides assuming ratio?

**Comment by crzycoder** [comment]
### When I rotate the screen in landscape it changes the height and width of video card items .. Mean i wrap 2 card items in one row but it take 3 items when mobile is in landscape ..


`<DrawerLayoutAndroid
        drawerWidth={300}
        drawerPosition={DrawerLayoutAndroid.positions.Right}
        ref={ref => {
          this.drawer = ref;
        }}
        renderNavigationView={() => <Drawer navigator={this.navigator} />}
        onClose={() => this.closeDrawer()}
      >
        <View style={{ flex: 1, borderWidth: 1, borderColor: "red" }}>
          <Header />
          <TouchableOpacity
            style={{ margin: 10 }}
            onPress={() => this.props.navigation.navigate("VideoScreen")}
          >
            <Text>Button</Text>
          </TouchableOpacity>
          <ScrollView style={{ flex: 1 }}>
            <View style={{ height: 200, borderWidth: 1 }}>
              <ImageSlider />
            </View>
            <View
              style={{
                flex: 1,
                flexDirection: "row",
                flexWrap: "wrap"
              }}
            >
              {this.state.dataSource.map(function(videoData, index) {
                return (
                  <View style={styles.card_contanier} key={index}>
                    <TouchableOpacity
                      style={{ flex: 1 }}
                      //onPress={() => this._navigation()}
                    >
                      <View
                        style={{
                          height: 85
                        }}
                      >
                        <Image
                          source={require("../img/special-page-banner.jpg")}
                          style={{
                            flex: 1,
                            width: imageWidth,
                            height: 28,
                            resizeMode: "stretch"
                          }}
                        />
                      </View>
                      <View style={styles.title}>
                        <Text
                          style={{ color: "black" }}
                          numberOfLines={2}
                          ellipsizeMode={"tail"}
                        >
                          {videoData.name}
                        </Text>
                      </View>
                      <View style={{ height: 57 }}>
                        <View style={styles.buttom_contanier}>
                          <View style={styles.logo}>
                            <Thumbnail
                              source={require("../img/andy-sm.png")}
                              style={{ height: 32, width: 32 }}
                            />
                          </View>
                          <View style={{ flexDirection: "column" }}>
                            <View
                              style={{
                                flexDirection: "row",
                                left: 5
                              }}
                            >
                              <Text
                                style={{ color: "black" }}
                                numberOfLines={1}
                                ellipsizeMode={"tail"}
                              >
                                {videoData.created_by_user.name}
                              </Text>
                            </View>
                            <View style={styles.iconic_contanier}>
                              <Icon
                                name="calendar"
                                size={10}
                                style={{ top: 2 }}
                              />
                              <Text style={styles.text}>10 Oct 2018</Text>
                            </View>
                            <View style={styles.iconic_contanier}>
                              <Icon name="eye" size={10} style={{ top: 2 }} />
                              <Text style={styles.text}>11 views</Text>
                            </View>
                          </View>
                        </View>
                      </View>
                    </TouchableOpacity>
                  </View>
                );
              })}
            </View>
            {this.state.isLoading && (
              <ActivityIndicator size="large" color="red" />
            )}
          </ScrollView>
        </View>
      </DrawerLayoutAndroid>
    );
  }
}

const styles = StyleSheet.create({
  /*  header: {
    borderWidth: 1,
    height: 55,
    flexDirection: "row",
    backgroundColor: "#3E3C3C"
  },*/
  card_contanier: {
    height: Dimensions.get("window").height / 3.4,
    width: Dimensions.get("window").height / 3.8,
    margin: 5,
    elevation: 2,
    backgroundColor: "#F5F5FA"
  },
  title: {
    height: 43,
    padding: 5
  },
  buttom_contanier: {
    height: 58.5,
    flexDirection: "row",
    padding: 5,
    overflow: "hidden"
  },
  logo: {
    elevation: 2,
    borderRadius: 20,
    height: 33.5,
    flexDirection: "column",
    top: 4
  },
  iconic_contanier: {
    flexDirection: "row",
    left: 5
  },
  text: {
    left: 5,
    fontSize: 10.5
  }
});`

**Comment by mnlbox** [comment]
Guys I want a more cleaner way to do this. @FuadBalashov Are you find any working solution?

**Comment by asifhussainoyo** [comment]
This might help [https://github.com/react-native-community/react-native-video/issues/746](#746 )

**Comment by asifhussainoyo** [comment]
This might help [#746](https://github.com/react-native-community/react-native-video/issues/746)

**Comment by zachrnolan** [comment]
Do something like this:

```
StyleSheet.create({
    video: {
        aspectRatio: 1 / 2, (change this to your actual aspect ratio)
        width: '100%',
    }
})
```

**Comment by juliushuck** [comment]
@zachrnolan answer is good, but I feel like the video component should do it internally automatically. Also for me, native controls do not show up that way
