### ISSUE TITLE
Naming collisions (not urgent)

### ISSUE THREAD

**Issue by onpaws** [TheWidlarzGroup/react-native-video#567]
Hey,
Thanks for writing this handy component.

Don't think this is a bug necessarily, just was curious if you might have a recommendation for my situation. Story is, I upgraded react-native-video today restarted the Packager and (for the first time) encountered several naming collisions:
```
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: WebSocket
  Paths: /Users/paws/projects/myapp/node_modules/react-native-windows/Libraries/WebSocket/WebSocket.windows.js collides with /Users/paws/projects/myapp/node_modules/react-native/Libraries/WebSocket/WebSocket.js
```

I'm only targeting iOS/Android, so if it's sensible & easy enough, I'd like to avoid having react-native-windows be a dependency. 
For the time being I'm consuming my own [fork](/onpaws/react-native-video) to silence the noise.

Are the collisions a bug?
Is there a recommended way for iOS/Android users to avoid pulling in react-native-windows? Like an [optional dependency](http://softwareengineering.stackexchange.com/questions/238257/optional-dependencies-in-npm)?

--------------------
react-native-video latest on NPM as of today (sorry forgot to record version)
react-native 0.43.2
react 16.0.0-alpha.6
macOS 10.12.4/node 7.7.2

**Comment by manask88** [comment]
+1

**Comment by lznt** [comment]
I can't get the react-native-video to work on RN Windows. The windows package.json has dependency to React Native Windows and after installing, react native packager won't stay up and building can't be finished due to naming collision with hasteMap of RNWindows that my main project is using and the dependency on react-native-video. Anyone else? 

Is it necessary to have a internal dependency to React Native Windows from RNVideo?

**Comment by grundmanise** [comment]
[RN 0.44.0] Because of the WP platform I had an issue that on iOS `Text` component's prop `ellipsizeMode` did not work. 5h lost to resolve it. Fork without WP support: https://github.com/grundmanise/react-native-video/tree/remove-WPF-platform

**Comment by manask88** [comment]
It used to be only warnings but now my react native app in Android just crashes. It returns a red screen.
![image](https://user-images.githubusercontent.com/694340/28347488-489ce602-6bec-11e7-8026-779920151b49.png)

So this is getting much worse. The only way I can get this to work is by blacklisting react-native-windows.  Have you @onpaws faced a similar situation? I'm using rn 0.44.0 and pointing to master in this repo

**Comment by manask88** [comment]
I can see that react-native is not a dependency or peerDependency in package.json. Do you guys think a possible solution to this problem is to simply remove react-native-windows from package.json? If so, I'd be more than happy to create a PR for it.

**Comment by lznt** [comment]
We did just that to prevent this error and it works. Frustrating

2017-07-19 20:39 GMT+03:00 manask88 <notifications@github.com>:
