### ISSUE TITLE
How to integrate react-native-video when using Podfiles to integrate react-native?

### ISSUE THREAD

**Issue by esilverberg** [TheWidlarzGroup/react-native-video#569]
In the installation instructions for iOS, it says to run

`react-native link`

After completion I see:

![screen shot 2017-04-17 at 11 28 37 am](https://cloud.githubusercontent.com/assets/58332/25093612/044b3da6-2361-11e7-9aba-09a8dbc98201.png)

However, compiling immediately fails with the error `React/RCTViewManager.h not found`:

![screen shot 2017-04-17 at 11 28 59 am](https://cloud.githubusercontent.com/assets/58332/25093635/18e01700-2361-11e7-9f5a-048e663582ba.png)

When looking at the [integration instructions on Facebook's website](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html
), it has us using a Podfile. When you use a Podfile, your project looks like this:

![screen shot 2017-04-17 at 11 18 42 am](https://cloud.githubusercontent.com/assets/58332/25093567/d4b0aeb4-2360-11e7-980c-13067967a6ab.png)

Comparing this to the react native sample project, I can see that in fact, it does not appear to use a Podfile to integrate react native at all; instead all React components are included as libraries:

![screen shot 2017-04-17 at 11 29 59 am](https://cloud.githubusercontent.com/assets/58332/25093660/3a36a52c-2361-11e7-83b6-e317b55b1979.png)

Thus, I suspect that the integration instructions for react-native-video are not compatible with the [integration instructions found here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#podfile).

Can anyone suggest how to integrate react-native-video when using Podfiles to integrate react-native?

**Comment by esilverberg** [comment]
Guys,

For the record I did *not* integrate using `react-native link`, as [specified here](https://github.com/react-native-community/react-native-video/blob/master/README.md).

Instead, I used: 

`pod 'react-native-video', :path => 'node_modules/react-native-video`

I believe the instructions provided are inaccurate and should be changed to reflect this method which is compatible with Podfiles.

**Comment by cinder92** [comment]
@esilverberg im having same issue, not working after pod install :/, always RCTViewManager not found
