### ISSUE TITLE
Remote video doesn’t continue playing after being paused due to hitting unbuffered section

### ISSUE THREAD

**Issue by isair** [TheWidlarzGroup/react-native-video#57]
AVPlayer automatically pauses itself if a playing media reaches an unbuffered section, but doesn't continue playing after more data is buffered so it has to be manually asked for a start after such a case.

**Comment by brentvatne** [comment]
Seems like we need to just check if `_paused` is set and play if not after the video buffers. Overall I think it's worth getting a simple streaming video example into the `Examples` directory as well so we have a go-to project to test this against. Any interest in tackling these two @isair?

**Comment by isair** [comment]
I'll see what I can do in my free time.

**Comment by isair** [comment]
@brentvatne Turns out this was actually pretty easy to solve thanks to the playbackLikelyToKeepUp property of AVPlayerItem.

**Comment by brentvatne** [comment]
:+1: nice one @isair
