### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by zachrnolan** [TheWidlarzGroup/react-native-video#575]
Are there any plans to release a new version soon? There are some updates to exoplayer I'd like to use without pointing to the master branch of the repo.

ps - love this component, thank you to everyone involved!

**Comment by GeoffreyPlitt** [comment]
Any update on this?

**Comment by cobarx** [comment]
Version 2.1.0 just shipped!

**Comment by cobarx** [comment]
and includes ExoPlayer 2.7.3
