### ISSUE TITLE
Application Freeze when loading the video

### ISSUE THREAD

**Issue by janakact** [TheWidlarzGroup/react-native-video#577]
If we are trying to play a video from a web URL, the whole application stay stuck (About 2-3 seconds until ) the a portion of the video is buffered. Seems like the whole UI rendering thread in blocked. Is there a solution for this or is it a bug?

**Comment by janakact** [comment]
Tried different versions. Currently using,

```
    "react-native": "^0.38.0",
    "react-native-video": "github:react-native-community/react-native-video#9bcf70cbb513402622bc114f93da751c28f15303"
```

**Comment by dquak** [comment]
Same here!
all UI is feezing for about 5-10 secounds before showing the video.
Tried @janakact solution with no luck:
`
"react-native": "0.42.3",
    "react-native-video": "github:react-native-community/react-native-video#9bcf70cbb513402622bc114f93da751c28f15303",
`

**Comment by kamalk333** [comment]
I faced the same Issue. Application freezes up because the video loading takes place on the main thread.
Try degrading the version of react-native-video to 0.9.0

It will work.

**Comment by dquak** [comment]
@kamalk333  Thanks!! This fixed this issue, - BTW version 1.0.0 works as well for me.
When setting some mp4 file in the uri, it seem that the player is not buffering, but waiting for the video to fully loaded before start playing it, any idea of how to fix it?

**Comment by janakact** [comment]
Solved. If you are using an older version, 
try changing the following file.  Change `prepare(this);` => `prepareAsync(this);` 
https://github.com/ttdat89/demo-video-streaming/blob/master/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L301

Thanks [Tien Dat](https://www.facebook.com/TranTienDat?fref=ufi) for the help.

**Comment by dquak** [comment]
@janakact Amazing, would really like to know how you got to this solution, as I would really like to fix the issue on the latest version

**Comment by mesbahsabur** [comment]
+1

**Comment by janakact** [comment]
@itay9001 
Got it from [FB React Native Community group. You should contact [Tien Dat](https://www.facebook.com/TranTienDat?fref=ufi)
 Hope it will be helpful. 
[https://www.facebook.com/groups/react.native.community/permalink/971188333016745/](https://www.facebook.com/groups/react.native.community/permalink/971188333016745/)

**Comment by carbureted** [comment]
I'm having this issue on iOS (javascript FPS drops to 0 for a second or two when the video starts) - are there any fixes floating around for it?

**Comment by areeb111** [comment]
You would be better to use ExoPlayer because it's faster and more stable.
To use it follow these steps: 
Go to `node_modules/react-native-video/`
Rename `android` to `android-mediaplyer`
Rename `android-exoplayer` to `android`
Run `react-native run-android` and Enjoy ExoPlayer :)

**Comment by PimDeWitte** [comment]
Some more info:

when buffering a currrent video, and then trying to create another video component and dispose of the current one, the new component will not start buffering until the previous video finishes buffeirng, causing the UI to lock.

**Comment by nartjie101** [comment]
+1 I got the issue in the latest code on IOS. It worked well on AD

**Comment by olivierlesnicki** [comment]
Same issue on iOS

**Comment by ami9000** [comment]
Same issue on iOS. Application hang/freezes while a Video component buffers. Is there a fix for iOS?

**Comment by nartjie101** [comment]
@ami9000 you can follow #1086 post to temporarily fix the issue. Remove these props: 'ignoreSilentSwitch', 'rate', 'volume' and 'muted'

**Comment by ami9000** [comment]
@nartjie101 Oh wow - this was the real issue! Thank you!

**Comment by anukuljha** [comment]
@itay9001  did you find any solution? stuck in a similar problem.

**Comment by isandre** [comment]
Its and old bug, but maybe I can help someone. Try to play with buffer parameters. It did help me to get rid of UI freezes when remote video is loading by adjusting bufferConfig.
The parameters was:
const bufferConfig = {
    minBufferMs: 5000,
    maxBufferMs: 10000,
    bufferForPlaybackMs: 1000,
    bufferForPlaybackAfterRebufferMs: 2000,
};

**Comment by matinzd** [comment]
@hueniverse 
This is still happening for me on iOS. UI FPS drops to zero for about 2-3 seconds until video becomes playable (buffered a bit).

**Comment by vaibhavgehani** [comment]
I still face this problem in iOS. Any one got the solution. Help

**Comment by freeboub** [comment]
@vaibhavgehani a fix has been pushed in last V6 release

**Comment by adriandiaz** [comment]
v6 release did not fix the issue for me in iOS

**Comment by Usman1214** [comment]
+1

**Comment by douzal34** [comment]
+1

**Comment by vemarav** [comment]
@douzal34 @Usman1214 @adriandiaz @vaibhavgehani @ami9000 
For ios:

modify `applyModifiers` with following changes:

add statements preceeded by `+` sign:

```swift
 
 
     func applyModifiers() {
+        if let video = _player?.currentItem,
+           video == nil || video.status != AVPlayerItem.Status.readyToPlay {
+            return
+        }
         if _muted {
             if !_controls {
                 _player?.volume = 0

```

**Comment by szpanel** [comment]
@vemarav Thank you, do you plan to post a PR of this?

**Comment by vemarav** [comment]
> @vemarav Thank you, do you plan to post a PR of this?

@szpanel I have open PR #3173 for this but I don't have any rights to add label or assign reviewer
