### ISSUE TITLE
Get Video Duration

### ISSUE THREAD

**Issue by cchamnab** [TheWidlarzGroup/react-native-video#578]
How can I get video duration ? Do video need to play or it can get from raw uri ?

**Comment by peter-mach** [comment]
You can get the duration after video loads in `onLoad` 

```
onLoad = (data) => {
    this.setState({ duration: data.duration });
};

<Video
    source={require('./broadchurch.mp4')}
    onLoad={this.onLoad}
/>
```

Full example: https://github.com/react-native-community/react-native-video/blob/master/example/index.android.js

**Comment by shiyunsheng** [comment]
when video not load,How can I get video duration ?

**Comment by cobarx** [comment]
@shiyunsheng If the video doesn't load, there's no way to get the info since it didn't work. You'll have to use another tool or something like that.

**Comment by ganeshintegrass** [comment]
in my react native app i wanna upload a video and after uploads in video page it will show the video with duration at end right corner like in youtube

**Comment by shyambhongle** [comment]
This package solved my issue
"react-native-video-duration"

**Comment by ganeshintegrass** [comment]
> This package solved my issue "react-native-video-duration"

yes its working for me too thank you
