### ISSUE TITLE
Can't find variable:  Video

### ISSUE THREAD

**Issue by cchamnab** [TheWidlarzGroup/react-native-video#579]
I got following error :

`Can't find variable:  Video`

Below this is my code : 

`<Video source={{uri: "/storage/emulated/0/DCIM/Camera/20170413_215032.mp4"}}   // Can be a URL or a local file.
       ref={(ref) => {
         this.player = ref
       }}                                      // Store reference
       rate={1.0}                              // 0 is paused, 1 is normal.
       volume={1.0}                            // 0 is muted, 1 is normal.
       muted={false}                           // Mutes the audio entirely.
       paused={false}                          // Pauses playback entirely.
       resizeMode="cover"                      // Fill the whole screen at aspect ratio.*
       repeat={true}                           // Repeat forever.
       playInBackground={false}                // Audio continues to play when app entering background.
       playWhenInactive={false}                // [iOS] Video continues to play when control or notification center are shown.
       progressUpdateInterval={250.0}          // [iOS] Interval to fire onProgress (default to ~250ms)
       style={styles.backgroundVideo} `/>``

**Comment by emik** [comment]
Just to clarify have you imported the component? `import Video from "react-native-video";`

**Comment by rashmimhatre100** [comment]
Not specified in documents import Video from "react-native-video";
