### ISSUE TITLE
When will 1.1 be published?

### ISSUE THREAD

**Issue by StevePotter** [TheWidlarzGroup/react-native-video#581]
It's been months since 1.0 went out and there is a bug that crashed my Android app that has been fixed since then.  For now I'm using a github commit in package.json and would love to see the upgrade on npm.  Any idea when that will be?

**Comment by jasonfma** [comment]
+1

We're using a fork of the library that has the fix but would love to come back to mainline. 

Looks like we're just waiting for just the npm publish of the new version?

**Comment by anshul-kai** [comment]
My videos don't work on Android when using `master`. Everything works fine when using 1.0 from npm. Are you guys not having issues on Android?

**Comment by cobarx** [comment]
Version 2.1.0 was just published.
