### ISSUE TITLE
android is very very slow

### ISSUE THREAD

**Issue by KurenaiKami** [TheWidlarzGroup/react-native-video#582]
my android device Sony E6683  android6.0.0 from Homepage to VideoPage is too slow about 10s.how to solve it;.
thanks

**Comment by JABirchall** [comment]
I am also experiencing this. When loading a video through react-native-video it would load really slow causing the app to lag and when the video had loaded the page took a while to load while the video was playing in the background. I am now using react-native-video-player which loads the page instantly and prevents the video from auto-loading/auto-playing but when pressing play the video still takes about 10 seconds to load.

I have confirmed that this is a network related issue, when loading a local file the experience is smooth and fast. However when trying to load a video from our servers the loading times leaves much to be desired. _and this isn't a issue with our servers._

Using:
* RN: 0.41.2
* react-native-video: 1.0.0
* react-native-video-player: 0.7.0

**Comment by drpiou** [comment]
I have the same here. On iOS the load is very fast, same for the `seek` method, it's fast from our server. However, on Android, this is slow af, it can take up from 10s to never...
[logcat.txt](https://github.com/react-native-community/react-native-video/files/1775231/logcat.txt)

**Comment by cobarx** [comment]
Try with ExoPlayer, it's designed to be faster than Android MediaPlayer.

**Comment by bachphuc** [comment]
@cobarx I think react-native-video on android is using ExoPlayer right? so what do you mean Try with ExoPlayer?

**Comment by ajaykumar97** [comment]
@cobarx How to do that? I am using react-native-video in flatlist. I am building an application which has number of video posts and I am using react-native-video to play them. But when I use it in my app, flatlist has number of videos and app becomes very slow. Also, my app is occupying lots of RAM. Please tell me how to optimise the performance.

**Comment by cobarx** [comment]
I am not an expert on FlatList. You should read up on it and determine how to make sure only the items on the screen are loaded. I would display thumbnails and not load the videos until someone clicks on it.

**Comment by jedashford** [comment]
> I am not an expert on FlatList. You should read up on it and determine how to make sure only the items on the screen are loaded. I would display thumbnails and not load the videos until someone clicks on it.

This is what I have done. Loading 15 video elements on startup is extremely slow. For us showing a poster, then loading the video element when its visible was the solution. Funny enough, once I scroll through the entire list and all 15+ are loaded (one at a time), its really performant. I suspect they are all trying to buffer at the same time when loaded together. So loading one at at a time is quick.

**Comment by addingama** [comment]
Hey @jedashford would you mind sharing the snippet how you accomplish that?
