### ISSUE TITLE
Background loading of next track

### ISSUE THREAD

**Issue by deshiknaves** [TheWidlarzGroup/react-native-video#583]
I use this component to steam a bunch of tracks. However, when one finishes and the next one starts, it sometimes takes a while for the next track to be buffered. I don't see any mechanism currently available to make this happen. But is there some other way to preload a track that will take buffering less time when it does start playing?

**Comment by iraycd** [comment]
@deshiknaves Any solution?

**Comment by deshiknaves** [comment]
Nope. I'm going to have to write something natively to get the functionality that I need.

**Comment by iraycd** [comment]
Even, I have planned to write my own way of doing it. 
I think you will get a great inspiration from 
https://github.com/kfiroo/react-native-cached-image as they are using `react-native-fetch-blob`

Will test it and let you know. In few weeks. 😝

**Comment by ninjz** [comment]
any updates on this? @iraycd

**Comment by diegodorado** [comment]
wow: third PR related to the same unsolved issue that I see closed without any comment... that is disappointing

**Comment by freeboub** [comment]
Stale is the close reason ... Ticket with 4y of inactivity...

**Comment by KrzysztofMoch** [comment]
@diegodorado Btw this is (probably) not possible with current library structure - player is nested in view so you need to init view in order to start video loading

**Comment by diegodorado** [comment]
@KrzysztofMoch , I was hoping to have a non-UI preloading mechanism callable without any UI component

**Comment by KrzysztofMoch** [comment]
This is not possible yet 😕 - we are planing to separate player from view in v7
