### ISSUE TITLE
Setting rate doesn't change video playback speed in Android

### ISSUE THREAD

**Issue by emik** [TheWidlarzGroup/react-native-video#584]
(Not using exoplayer)

**Comment by emik** [comment]
Realised this is a recognised unimplemented feature

**Comment by RickDT** [comment]
I'm seeing this too. I noticed the ExoPlayer README says that rate is not supported. Does that mean rate is not supported on Android at all as of 1.0.0?

**Comment by bharath-kamath** [comment]
Would be good to have this on android.

**Comment by elaffey** [comment]
Has there been update on this issue?

I have also noticed that the README for the ExoPlayer has rate as unsupported but from what I can tell using the ExoPlayer is not the default behaviour. 

By having the following in `android/settings.gradle` it will not use the ExoPlayer
```gradle
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
```

Despite this, rate does not work for android.

**Comment by cobarx** [comment]
Setting the rate is now supported now that #798 is merged. However, the Android media player APIs only support setting the rate on Android 6.0 and up. I'd suggest using the ExoPlayer version instead since it doesn't have this limitation.
