### ISSUE TITLE
assign  a wrong source value,the app will be crash on IOS

### ISSUE THREAD

**Issue by ymuzi** [TheWidlarzGroup/react-native-video#585]
<Video
                        source={{uri:this.props.src}}//this.props.src is an empty string '' 
                        style={styles.fullScreen}
                        rate={this.state.rate}
                        paused={this.state.paused}
                        volume={this.state.volume}
                        muted={this.state.muted}
                        ignoreSilentSwitch={this.state.ignoreSilentSwitch}
                        resizeMode={this.state.resizeMode}
                        onLoad={this.onLoad}
                        onBuffer={this.onBuffer}
                        onProgress={this.onProgress}
                        onEnd={() => { AlertIOS.alert('Done!') }}
                        repeat={true}
                    />
app will crash

**Comment by Hydraz320** [comment]
Hi, ymuzi. I just found this problem, either. Maybe we should change the uri anyway...

**Comment by piuccio** [comment]
Had the same, for sure we need to fix the uri, but instead of crashing it would be nicer if the `onError` function was called

**Comment by rogerkerse** [comment]
My app crashes when I have no connection and the url is correct. Those issues might be linked

**Comment by Desintegrator** [comment]
same here
