### ISSUE TITLE
Video not looping on Android

### ISSUE THREAD

**Issue by onehassan** [TheWidlarzGroup/react-native-video#586]
I've put the repeat prop to true, but the video stops playing when it reaches the end

**Comment by radko93** [comment]
Hi, I submitted a PR for that today. Check #587.

**Comment by ezcoding** [comment]
Can confirm. The video loops, if the source isn't changed. If the source changes without the component being mounted again, the video doesn't loop.

**Comment by zachrnolan** [comment]
Having the same issue, any updates? @radko93 any momentum on your PR?

**Comment by radko93** [comment]
@zachrnolan someone from the contributors needs to merge. Maybe it will be helpful if someone else could review it too.

**Comment by cobarx** [comment]
This PR was just merged.
