### ISSUE TITLE
no loading indicator when video buffers in android

### ISSUE THREAD

**Issue by swaroopa94** [TheWidlarzGroup/react-native-video#588]
Hi,

I am Plying an uri video.
But I am not getting an buffering indicator when video buffers initially in android
In iOS I am getting an loading indicator.

Please help me to solve this

**Comment by vvavepacket** [comment]
any update on this?

**Comment by swaroopa94** [comment]
Still have the same issue no loading indicator in android 
Anyone got the solution?

**Comment by shirbr510** [comment]
I think it has to do with the underlying implementation of the android component.

but from my experience, due to the lack of caching, you'll see that loader a lot and probably need to wrap the video component with some sort of http caching mechanism

see more at #99

**Comment by kashifaliquazi** [comment]
any update facing the same problem

**Comment by ankit18singh** [comment]
Use `https://www.npmjs.com/package/react-native-loading-spinner-overlay` and change spinner visiblity state with onBuffer()
