### ISSUE TITLE
android-NativeModules.UIManager.RCTVideo.Constants

### ISSUE THREAD

**Issue by roshan-shelar** [TheWidlarzGroup/react-native-video#589]
no problem on ios, but getting * undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants') * on android

**Comment by jlemoscds** [comment]
react-native link is not working right. You need to do the configurations manually.

**Comment by banli17** [comment]
you need run react-native run-android   after setup react-native-video

**Comment by fabiancarlos** [comment]
This was the fix for me, i was using `react-native-navigation` and missed some configs:
https://stackoverflow.com/questions/45146173/does-react-native-video-work-with-react-native-navigation
