### ISSUE TITLE
Memory increasing over time

### ISSUE THREAD

**Issue by PhilippKrone** [TheWidlarzGroup/react-native-video#59]
Hi,

I'm using this module to play a simple audio file at the moment (an .m4a file) and I get the following warning:

2015-06-24 08:11:14.529 Yoloci[15881:17768305] 08:11:14.529 WARNING:   139: The default input device's sample rate was changed.
2015-06-24 08:11:14.565 Yoloci[15881:17767376] 08:11:14.565 WARNING:   256: Audio device's sample rate changed. You may need to restart the simulator.

and at the same time, the used memory is increasing over time (and doesnt seem to stop increasing at all):

![screen shot 2015-06-24 at 08 13 03](https://cloud.githubusercontent.com/assets/11861008/8323751/e1454536-1a48-11e5-86f8-fd3ef6895afc.png)

Please note that the file I'm playing is only roughly 1MB of size, so that shouldnt be an issue, should it?

Regards
Philipp

**Comment by PhilippKrone** [comment]
Update: Happening in simulator only (?)

**Comment by brentvatne** [comment]
Well that is very odd! Can you check if you still see this on 0.4.8?

**Comment by brentvatne** [comment]
@PhilippKrone - let me know if you're still having this problem :smile:

**Comment by PhilippKrone** [comment]
@brentvatne Aah, sorry, totally forgot to answer! No, I dont have this problem anymore. Was just doing some tests with RN 0.7.1 and the latest video version and everything's fine :)

Thanks!
