### ISSUE TITLE
video has no propType for native prop,this usually means that your versions of native code and js code are out of sync

### ISSUE THREAD

**Issue by sayhei** [TheWidlarzGroup/react-native-video#590]
I use react-native-video in my react-native project. I run it on ios simulator and meet this error:
"'Video' has no propType for native prop 'RCTVideo.progressUpdateInterval' of native type 'float'. If you havent' changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away".
Detail:
react-native version 0.42.0
react-native-video version 1.0.0

and it works fine for android

**Comment by cobarx** [comment]
Pretty sure this is fixed in the latest versions.
