### ISSUE TITLE
Status Bar disappearing after full screen

### ISSUE THREAD

**Issue by ericcastro92** [TheWidlarzGroup/react-native-video#591]
I see that this issue was supposedly resolved in another PR but I'm still encountering it.

### Reproducing

1. Launch video in full screen
2. Rotate device to landscape mode
3. Rotate back to portrait mode
4. Exit full screen

At this point the status bar disappears for the whole app.

**Comment by mesbahsabur** [comment]
I can confirm that this also happens to me when I execute the exact same steps with a `<WebView>` that loads an HTML `<Video>` component (So no react-native-video usage at all).

Not sure why this is happening.

**Comment by Almouro** [comment]
Yes [this PR](https://github.com/react-native-community/react-native-video/pull/532) was merged, but I don't think it was published on NPM :(

**Comment by guilhermepontes** [comment]
@brentvatne ping

**Comment by yewenxiang23** [comment]
@Almouro The problem is still there

**Comment by zakster12** [comment]
Same with me. Any idea when this is going to be working?

**Comment by mactive** [comment]
same with me it is still there

**Comment by nmruss** [comment]
I am also experiencing this issue :/

**Comment by cwiedel** [comment]
I have this issue too.
RN 0.47.1
Has anyone found a work-around?

**Comment by mactive** [comment]
I have solved this problem
in your onFullscreenPlayerDidDismiss function 
`
        StatusBar.setHidden(false) 
`
don't forget 
 import { StatusBar } from 'react-native';

**Comment by fynsok** [comment]
yulyu
