### ISSUE TITLE
undefined is not an object (evaluating 'UIManager.AndroidTextInput.Constants')

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#593]
Hi,

I'm currently working on both the Android and iOS version using react-native but I'm getting the following error arise on the iOS version:

> undefined is not an object (evaluating 'UIManager.AndroidTextInput.Constants')

<img width="458" alt="screen shot 2017-04-29 at 16 00 34" src="https://cloud.githubusercontent.com/assets/7087915/25556982/ae13aeac-2cff-11e7-98cc-3e7eb75b5b85.png">

It appears to occur using TextInput from react-native and only the app error on the iOS version but I question why the error and also why 'UIManager.AndroidTextInput' for an iOS issue.

Thanks!

**Comment by jlemoscds** [comment]
react-native link is not working right. You need to do the configurations manually.
