### ISSUE TITLE
RTSP Support

### ISSUE THREAD

**Issue by nimble-software** [TheWidlarzGroup/react-native-video#594]
Hi,

Does this library support playing RTSP streams?

Thanks in advance.

Regards
Brian

**Comment by Lizhooh** [comment]
[react-native-video/issues/522](https://github.com/react-native-community/react-native-video/issues/522)

**Comment by nimble-software** [comment]
Thank you for your response, however I am still unsure after reading the mentioned link whether RTSP is supported? I have attempted the solutions mentioned in the link, however as soon as the application attempts to load it crashes, with no error message.

I have verified that the URL I am supplying works by testing it through VLC.

**Comment by manjeets12** [comment]
I get it working on android using [react-native-vlc](https://github.com/Ivshti/react-native-vlc)

**Comment by SaraChicaD** [comment]
@manjeets12 did you ever find an ios solution to this? thanks in advance!!

**Comment by choychris** [comment]
@manjeets12 Same question as Sara. Any rtsp solution on IOS ? 
Thanks a lot.

**Comment by SaraChicaD** [comment]
@choychris never figured it out, we decided to get a contractor to build us something custom after all.

**Comment by jpgarcia** [comment]
Hi @SaraChicaD can you share with us which IOS native library did you use to create the react-native wrapper to play RTSP sources? do you have any plans to publish the lib as open source?

**Comment by SaraChicaD** [comment]
hi @jpgarcia unfortunately no :(

**Comment by rogerio-azevedo** [comment]
Still not work with RTSP in IOS, like DVR channel stream?

**Comment by rogerio-azevedo** [comment]
I found this, working RTSP on IOS:

[react-native-vlc-media-player](https://github.com/razorRun/react-native-vlc-media-player)

**Comment by osric69** [comment]
@rogerio-azevedo Hi, I tried this library, working well on Android but have a black screen on IOS. Can you give me a sample of your IOS react-native code ?

Thx

**Comment by rogerio-azevedo** [comment]
Hei @osric69 

1 - git clone: [Working example](https://github.com/razorRun/react-native-vlc-media-player-test)

2 - yarn

3 - cd ios => pod install

4 - cd..

5 - replace you rtsp link, for my camera URL address

6 - yarn ios

**Comment by rahul-5503** [comment]
can any one provide library that support rtsp stream in react native 0.73 most of the library in 2023 are not working that show the error like this "Invariant Violation: 
requireNativeComponent: "RCTVideo" was not found in the UIManager." for react-native-vlc-media-player,react-native-video,and react-native-vlc-rtsp

**Comment by RafaaZahra** [comment]
Me too i have same issue

**Comment by rahul-5503** [comment]
my project is working fine .you have add the types to solve this problem
you have to create react-native-vlc-media-player.d.ts file in typings
folder in that folder have to write
                  declare module'react-native-vlc-media-player';

**Comment by Osric38** [comment]
Hello @rahul-5503,

Can you give more details about your solution ?

Such as screenshots .. ?

I try your solution but i think I dont put in the right path.

Thx

**Comment by rahul-5503** [comment]
[image: Screenshot (257).png]
Yes, I can help you.

**Comment by Osric38** [comment]
Your Screenshot is not visible

**Comment by rahul-5503** [comment]
![Screenshot (258)](https://github.com/react-native-video/react-native-video/assets/130264008/780f1fbc-a48c-4441-94c3-fedc73f7c6ac)
![Screenshot (260)](https://github.com/react-native-video/react-native-video/assets/130264008/1316ce3d-898b-4163-9d9c-7c96be520c98)
![Screenshot (261)](https://github.com/react-native-video/react-native-video/assets/130264008/60bb98ff-ddc9-4d33-b7fd-6188b5f6a34b)

**Comment by RafaaZahra** [comment]
This dependency does not working with expo correctly try to eject from expo , or create New project without expo ...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
