### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by johnchourajr** [TheWidlarzGroup/react-native-video#597]
I know this is a duplicate issue, but none of the other solutions have worked for me.

<img width="487" alt="screen shot 2017-05-02 at 11 00 47 am" src="https://cloud.githubusercontent.com/assets/6431920/25631881/9da1555a-2f26-11e7-852d-8116b0a21eb4.png">

```
...
"react": "15.3.1",
"react-native": "^0.35.0",
"react-native-video": "^1.0.0",
...
```

**Comment by FullstackJack** [comment]
Same happens here.
```
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-video": "^1.0.0",
```
Video component created with these props...
```
<Video
  source={{uri: 'https://wowza.jwplayer.com/live/jelly.stream/playlist.m3u8' }}
  ref={(ref) => { this.player = ref }}
  muted={false}
  paused={false}
/>
```

**Comment by FullstackJack** [comment]
@johnchourajr Nevermind, run `react-native run-ios` to reinstall the application after linking with `react-native link`.

**Comment by petivagyok16** [comment]
I had the same issue. Follow the installation instructions in the README, my package linking failed and there was missing package imports in MainApplication.java, build.gradle etc.
Check the README, those steps solved the issue for me

**Comment by xylxpm** [comment]
ios
1、先按照这个组件的说明，修改APPDelegate.m。如果还不行。
2、打开xcode。查看Libraries里面有没有RCTVideo.xcodeproj.。如果没有，添加它。这个文件在你的项目node_modules/react-native-video文件夹中
3、build Phases----Link Binary with Libraries中添加libRCTVideo.a
4、编译运行。

我的问题就是这样解决的

**Comment by xmeltrut** [comment]
I'm having the same issue.

    npm install react-native-video
    react-native link
    react-native link react-native-video
    react-native run-ios

I assume because of this warning that appears when the app first boots:

    ExceptionsManager.js:73 Warning: Native component for "RCTVideo" does not exist

Which suggests the linking isn't working?

**Comment by FullstackJack** [comment]
Close all React Native terminals and restart iOS Simulator. If still no
avail, uninstall and clean reinstall the app.

**Comment by xmeltrut** [comment]
By uninstall do you mean delete the app from the simulator (like you would on a real device) and then re-run `react-native run-ios`? I get the same problem after having done that, but I don't know if that completely clears the app from the simulator.

**Comment by FullstackJack** [comment]
You might want to try deleting the node_modules directory and reinstall
those. Do the other steps above in addition. If all elsw fails, try
deleting the entire project and doing a fresh git clone. Be sure to commit
any code you intend to keep and push that up first. It might be an NPM
package issue or it could be an iOS build issue.

**Comment by arash-hacker** [comment]
-1 when using `react-native link` it shows an error like this ![screen shot - - at](https://user-images.githubusercontent.com/6451804/37159265-a3a45e0e-2302-11e8-8a01-a101b2a863ac.png)

-2 and when i want add libRCTvidoe.a, it doesn't apear in linkages so let start hacking :)

i cloned react-native-video project and use libRCTvideo.a in project , droped to my .workspace project and walla.. now librctvideo apears and i added to my project and it worked !

**Comment by damassi** [comment]
When using CocoaPods, one might have to link it manually in the podfile:

```rb
pod 'react-native-video', :path => File.join(node_modules_path, 'react-native-video/react-native-video.podspec')
```

**Comment by HengCC** [comment]
> ios
> 1、先按照这个组件的说明，修改APPDelegate.m。如果还不行。
> 2、打开xcode。查看Libraries里面有没有RCTVideo.xcodeproj.。如果没有，添加它。这个文件在你的项目node_modules/react-native-video文件夹中
> 3、build Phases----Link Binary with Libraries中添加libRCTVideo.a
> 4、编译运行。
> 
> 我的问题就是这样解决的

this resolve my problem

**Comment by LorandP** [comment]
I have just made sure to install the library manually on iOS.
1. Add the RCTVideo to Libraries from `node_modules/react-native-video/ios`
2. From` Libraries/RCTVideo/Products add the libRCTVideo.a` to Build Phases
3. In `Build Settings/Header Search Paths/Debug+Production` I have added `$(SRCROOT)/../node_modules/react-native-video/ios`

**Comment by quantumpotato** [comment]
Bump

**Comment by CHaNGeTe** [comment]
As stated before this indicates a bad linking process. Follow readme for that. If problem still persists post library version and RN version

**Comment by quantumpotato** [comment]
"react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-video": "^4.4.4",

I ran 

`yarn install`
`react-native link react-native-video`
and still have the Constants bug

**Comment by CHaNGeTe** [comment]
Can you try with manual linking?
https://github.com/react-native-community/react-native-video/issues/597#issuecomment-493391282

**Comment by quantumpotato** [comment]
Yes, updated to .6 react native and this works now. Thank you.

**Comment by techtunix** [comment]
Leave all and Simply Go Native and Do it Like this!

1). `expo install expo-av`

2). Your `App.js` should be 

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Video } from 'expo-av';

export default class App extends React.Component {
  render(){
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>

        <Video
        source={{ uri: 'https://www.yourdomain.com/uploads/video_file.mp4' }}
        shouldPlay
        useNativeControls 
        style={{ width: "100%", height: "50%" }}
      />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

3). `expo start`
