### ISSUE TITLE
Pause video and clean up when unmounted

### ISSUE THREAD

**Issue by brianchirls** [TheWidlarzGroup/react-native-video#6]
If you remove the video from a view, it keeps playing in the background. You can hear the audio playing, and it continues to occupy memory. It's also evident if you do a JavaScript reload within the app while you're debugging. 

I can implement a quick and dirty fix by adding this to `RCTVideo.m`:

``` Objective-C
- (void)removeFromSuperview
{
    [super removeFromSuperview];
    [_player pause];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}
```

That stops the video from playing, but I don't believe it's really deleted the object, since `dealloc` doesn't run and the memory graph continues to climb. So I'm sure there's more work to be done here. I'd offer to make a pull request, but I don't know Objective-C well enough to do it myself.

**Comment by brentvatne** [comment]
Thanks for the heads up @brianchirls! This is still very early on in this project so there are bound to be some serious problems such as this, that said I fixed it in https://github.com/brentvatne/react-native-video/commit/d9ddb6e75a99954e2003359f42581d75efb33d71 :smile:

**Comment by brianchirls** [comment]
Awesome. Thanks!

**Comment by kshahkshah** [comment]
@brentvatne okay, as far as I can tell, this is broken again. I have controls which let me navigate to the "next" video in a queue, and the old one keeps playing.

**Comment by kshahkshah** [comment]
iOS, XCode 9.

```
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.1",
    "react-native-orientation": "^2.1.0",
    "react-native-sentry": "^0.16.1",
    "react-native-vector-icons": "^4.4.0",
    "react-native-video": "^1.2.0",
    "react-navigation": "^1.0.0-beta.11"
  }
```

**Comment by KlimczakM** [comment]
I have the same issue on iOS as mentioned by @whistlerbrk, have anyone found any solution to this?

It occurs both on iOS10 and iOS11, on Android it works fine. I'm using 2.0.0 version added with yarn.

**Comment by CyxouD** [comment]
```
react-native: "0.61"
react-navigation: "4.0.10"
```
It was happening for me because of incorrect `react-native-screens` version, it should be `react-native-screens@^1.0.0-alpha.23` (https://reactnavigation.org/docs/en/getting-started.html#installing-dependencies-into-a-bare-react-native-project)
