### ISSUE TITLE
Restarting once video has ended

### ISSUE THREAD

**Issue by PhilippKrone** [TheWidlarzGroup/react-native-video#60]
Hi,

is there currently a possibility to restart the video / audio, once it has finished? I can't see anything about it in the example / docs.

Thanks :)
Philipp

**Comment by isair** [comment]
Setting the `repeat` property of your `Video` to true should do that. If that doesn't work for you, and you are trying that with a remote video, this may be related to #61.

**Comment by brentvatne** [comment]
Should be fixed by @isair in #62!
