### ISSUE TITLE
autoplay and paused props not working in Android

### ISSUE THREAD

**Issue by Symous** [TheWidlarzGroup/react-native-video#608]
I want to control the video playing status manually,but even I set autopaly={true} and paused={true} it still play automatically.I also had try chenge a playing state in onLoad method,but still not working.

**Comment by ranjitpandit** [comment]
I'm seeing the same issue on Android. As soon as the Video component is rendered it starts playing the video even if rate=0 and paused=true. 
It works correctly on IOS. 

Any ideas?

**Comment by maboelsoud** [comment]
Same here. However, if there is something externally that changes the paused property from false to to true, it works. However, it always starts playing, no matter what I do.

Does anyone know the reason for this?

**Comment by justfordev123** [comment]
Same here on Android 5.0

**Comment by Symous** [comment]
@ranjitpandit @Mohamed-Abo-El-Soud  @heartAndRain 
Hi, guys , I have found why this happened.This is the PR #625  to fix this problem. the author hasn't merge that. so you can have a look at it and modify the native code. :-)

now we can use pause={true} to make the video stop in the beginning.

**Comment by cobarx** [comment]
Fixed by #1082. In my testing everything is working properly now. Will be released in 3.0. There isn't an autoPlay prop, but if you don't specify a paused prop, it will auto-play.

**Comment by kumarutsav111** [comment]
set paused={true} inside video props.
<Video
        {...videoProps}
        ref={(r) => { this.player = r; }}
        source={{ uri: currentMessage.video }}
        // style={videoStyle}
        style = {{
          aspectRatio: 1,
          width: "90%"
      }}
        resizeMode="cover"
        // onBuffer={this.onBuffer}
        // onLoadStart={this.onLoadStart}
        //onLoad={this.onLoad}
        fullscreenAutorotate = "landscape"
        allowsExternalPlayback ={true}
        controls = {true}
        fullscreen = {true}
        paused = {true}
        // fullscreenAutorotate={true}
        // resizeMode="contain"
      />
