### ISSUE TITLE
[Question] AirPlay Support

### ISSUE THREAD

**Issue by vyky** [TheWidlarzGroup/react-native-video#611]
Hi how to connect to Apple TV? I don't see AirPlay button on Fullscreen mode

**Comment by shirbr510** [comment]
I might be mistaken but I don't think this library takes care of streaming video from the device

you might be looking for this:
https://github.com/wanaya/react-native-airplay

**Comment by tnaughts** [comment]
@vyky were you able to use the react-native-airplay library for connecting to an Apple TV?

**Comment by harshjoshi096** [comment]
@tnaughts  @vyky Did you guys got any solution for connecting to Apple TV?

**Comment by danielmarino24i** [comment]
You can check this PR: https://github.com/react-native-community/react-native-video/pull/1445

**Comment by nathantqn** [comment]
I'm really confused about some react native airplay libraries, all they do is just displaying the Airplay button, and how can we cast a video URL using it is not documented

**Comment by CHaNGeTe** [comment]
AFAIK you have to setup the player locally (on mobile), and then offer an Airplay button (for example integrating react-native-airplay).
The player will send the config for playing to the device. ( AVPlay is doing this under the hood)

**Comment by maliotti** [comment]
@CHaNGeTe Do you know if this library supports both AirPlay and AirPlay 2? We are having issues when attempting to AirPlay to AirPlay 2 devices. Regular AirPlay works great!
