### ISSUE TITLE
Add tvOS Static Library Build Target to Support tvOS Projects

### ISSUE THREAD

**Issue by FullstackJack** [TheWidlarzGroup/react-native-video#613]
Apple requires that tvOS apps only include libraries that were built against the same platform. In attempting to build a tvOS app with the current `libRCTVideo.a` archive, you will run into a clang error. In order to fix this issue, we need to add a new tvOS Static Library build target for this package. After a lot of trying, I was able to accomplish this task. I could create a PR for the project file update if you'd like. Following convention from other React Native modules, the build target Product  Name should be named `RCTVideo-tvOS`. After saving the target, you'd need to manually link the tvOS library under Linking in your main project under tvOS build target, so adding `libRCTVideo-tvOS.a` will do the trick. Can secondary targets get configured from `react-native link`?

**Comment by FullstackJack** [comment]
I dislike having to manually link all font resources and libraries for tvOS builds, but I certainly learned a lot in the process.

**Comment by FullstackJack** [comment]
https://github.com/react-native-community/react-native-video/pull/614

**Comment by FullstackJack** [comment]
Naming convention for `-tvOS` build targets found in docs @ https://facebook.github.io/react-native/releases/next/docs/building-for-apple-tv.html#build-changes

**Comment by hooddanielc** [comment]
👍
