### ISSUE TITLE
Stop video

### ISSUE THREAD

**Issue by TattoDeveloper** [TheWidlarzGroup/react-native-video#617]
how stop video when change view?

**Comment by vvavepacket** [comment]
+1 what is the best way to unmount the Video component?

**Comment by rayronvictor** [comment]
+1

**Comment by mlg87** [comment]
@vvavepacket super late answer, but you could just conditionally render it

```
{ isVideoPlaying && <Video source={{ uri: 'somewhere.com/video.mp4' }} ... /> }
```

**Comment by iraniamir** [comment]
there is no api for pausing video ?!

**Comment by ndbeyer** [comment]
I would also be very happy to know how to implement a `stop video` functionality. Setting `controls`  gives us 
<img width="303" alt="grafik" src="https://user-images.githubusercontent.com/33200064/58416697-b9a1c000-8082-11e9-87b8-eec326d78f3c.png"> 
<img width="309" alt="grafik" src="https://user-images.githubusercontent.com/33200064/58416702-be667400-8082-11e9-89c2-f7852a452cbc.png">

but is there no "X" button or another way except of the `onEnd` event to make it possible to close the video?

**Comment by gaberoganlingumi** [comment]
Why is `pause` even a prop? If it is being _internally_ controlled by `controls`, shouldn't the `this.player` ref provide a method for (un)pausing video?

**Comment by ebarahona** [comment]
> how stop video when change view?

You can add a listener for navigation blur/focus to stop start video playback, here is an example using hooks:

`  useEffect(() => {
    const stopVideo = props.navigation.addListener('blur', () => {
      setStop(true);
    });

    return stopVideo;
  }, [props.navigation]);`

// Video props
<Video
...
paused={stop}
/>
