### ISSUE TITLE
IngoreSilentSwitch not working iOS

### ISSUE THREAD

**Issue by adriandiaz** [TheWidlarzGroup/react-native-video#621]
react-native version: 0.44.0
react-native-video version: 1.0.0
iOS: 10.3.1

I can't get the "ignoreSilentSwitch" prop to work. I've tried in my own app then downloaded the example provided. In both cases, when I set `ignoreSilentSwitch={'ignore'}` if the silent switch is on then video is muted. It will only play if I toggle with switch to on.

Is anyone else having this issue? Any suggestions?

**Comment by rogerkerse** [comment]
Having same problem

**Comment by scarlac** [comment]
Having looked at the released version (1.0.0), it's no surprise it's not working: There's no mention of the prop `ignoreSilentSwitch` anywhere.
While the prop is added in the current development version, it hasn't been released. It was pulled on April 20 from pull request #403 

It effectively calls `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];` which you can do yourself in the meantime:

in `AppDelegate.m`, add this:

```
#import <AVFoundation/AVFoundation.h>  // import

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];  // allow
  ...
}
```

Haven't tested it myself, but it should give the same effect.

**Comment by duhseekoh** [comment]
Correct. I authored #403, and indeed can confirm it has not been cut to a proper npm release. Someone needs to do that. I'm not sure who is in charge of that around here. ¯\_(ツ)_/¯

**Comment by CosmaTrix** [comment]
Hi everybody. I fixed the "issue" installing master version.

`yarn add git://github.com/react-native-community/react-native-video#master`

A new release on npm would be great! :)
