### ISSUE TITLE
Is there a way to play or pause manually ? 

### ISSUE THREAD

**Issue by cchamnab** [TheWidlarzGroup/react-native-video#624]
I have few questions to ask : 
1. I've populated videos in FlatList so user can click video to play it.
2. I don't see any default player control (play, pause ..). is there a property to enable this feature ?

**Comment by vvavepacket** [comment]
you can tap the video, it will pause itself,, or you can add a text control below and call pause property to true

**Comment by cobarx** [comment]
Your best bet is to build your own custom controls or Touchable element to support what you need.

**Comment by chrise86** [comment]
Just found this old issue while searching for the same thing. I don't think the comments above answer the question. Even if building custom controls, which let's say that's what someone wants to do, what methods can you call to play/pause/etc? Looking at the available methods on a ref instance, there doesn't seem to be much you can do.

**Comment by infinitbility** [comment]
Check below documentation to create custom controls

https://infinitbility.com/react-native-video-example-with-custom-control

**Comment by simonNeo** [comment]
by `paused` prop. like this:
```
const [paused, setPaused] = React.useState(false);

// and
<Video source={...} paused={paused} />

```
