### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by berdof** [TheWidlarzGroup/react-native-video#629]
I tried out to use this library with expo but stuck with an error. 
Are there any plans for expo support?

**Comment by silasrm** [comment]
I'm desire to use this on Expo. Any idea?

**Comment by srinivasaltair** [comment]
cannot read property 'Constants' of undefined.
I am using this library with expo. But got the above error. Is there any other way to work this out..
Please help..

**Comment by NickDelfino** [comment]
Did anyone have any luck getting this to work with Expo?

**Comment by natterstefan** [comment]
Any news? :)

**Comment by natterstefan** [comment]
Yeah, but their video component is rather limited compared to this one :/ @joshua-owens
