### ISSUE TITLE
hiding progress bar when playing

### ISSUE THREAD

**Issue by vvavepacket** [TheWidlarzGroup/react-native-video#631]
Do you guys have the proper approach to hide the progress bar when playing a video (lets say after 5 seconds)? I want it to appear only when the screen is touch. If the screen is touch, the video is paused, anyway to avoid that?

**Comment by AliZeynalov** [comment]
I can't even find progress bar, before hiding it :) Do you know how can I use progress bar? I could not find through documentation or props

**Comment by DISKONEKTeD** [comment]
https://github.com/browniefed/examples/tree/rnvideo/controlshide
