### ISSUE TITLE
Question: programmatically play and pause?

### ISSUE THREAD

**Issue by itinance** [TheWidlarzGroup/react-native-video#634]
Could not find any documentation and no (public) methods in video.js that let me "pause" and "play" a video at any time programmatically?

Any hints available?

**Comment by EdenGottlieb** [comment]
Set the paused prop of the Component to a boolean property of your State and change it with this.setState as you wish.

**Comment by muganwas** [comment]
> Set the paused prop of the Component to a boolean property of your State and change it with this.setState as you wish.

I've been using this method but it's not very reliable, it seems to only reliably control the initial state of the video.

**Comment by manuf10** [comment]
> > Set the paused prop of the Component to a boolean property of your State and change it with this.setState as you wish.
> 
> I've been using this method but it's not very reliable, it seems to only reliably control the initial state of the video.

Check you are also changing your State property in onPause and onPlay callbacks.
I have something like this going on and it seems to be working fine:
```
onPlay() {
  this.setState({playing: true});
}

onPause() {
  this.setState({playing: false});
}

onMyToggleButtonClick {
  this.setState((state) => ({
    playing: !state.playing
  }));
}
```

**Comment by hirbod** [comment]
Wow... so you can't really play and pause using the ref? Can't believe this :D

**Comment by GustavPS** [comment]
> Wow... so you can't really play and pause using the ref? Can't believe this :D

Yes you can, set the paused prop to a state boolean as he said. Have always worked fine for me

**Comment by hirbod** [comment]
I am aware of the props but I am missing actions on the ref, like `playerRef.play()` etc.
If you work with a FlatList and work with `onViewableItemsChanged`, you try to avoid as many re-renders as possible on endless lists, and passing down state props to the children to trigger play and pause is non-sense for me. I am forwarding the video ref to the parent to determine the visible and unvisible videos in order to start or stop.

Gonna revert and stick with expo-av instead.

**Comment by GustavPS** [comment]
> I am aware of the props but I am missing actions on the ref, like `playerRef.play()` etc. If you work with a FlatList and work with `onViewableItemsChanged`, you try to avoid as many re-renders as possible on endless lists, and passing down state props to the children to trigger play and pause is non-sense for me. I am forwarding the video ref to the parent to determine the visible and unvisible videos in order to start or stop.
> 
> Gonna revert and stick with expo-av instead.

Yea this library also have problems with multiple video instances. For example in a flatlist, or just re-navigation to the same video multiple times will make the video to get stuck buffering. Though I thought expo-av had the same issue. But maybe not

**Comment by hirbod** [comment]
I just wanted to use `react-native-video` because of the `automaticallyWaitsToMinimizeStalling` but it is lacking so much more that I am just gonna stick with expo-av. Seems much more reliable. This repo has 1.1k unresolved issues. I'm gonna pass.

My FlatList has 800 Videos so far, with really fast swiping (paging enabled, like TikTok/Insta Reels) and I have no issues or memory leaks or framedrops so far)

**Comment by GustavPS** [comment]
> I just wanted to use `react-native-video` because of the `automaticallyWaitsToMinimizeStalling` but it is lacking so much more that I am just gonna stick with expo-av. Seems much more reliable. This repo has 1.1k unresolved issues. I'm gonna pass.
> 
> My FlatList has 800 Videos so far, with really fast swiping (paging enabled, like TikTok/Insta Reels) and I have no issues or memory leaks or framedrops so far)

Is the repo public? Or would you mind sharing the video implementation of expo-av? Been struggling with my video problem for a long time now aswell as many others using this package

**Comment by hirbod** [comment]
It is basically basing on this. It's not public.
https://snack.expo.dev/@jenshandersson/optimized-video-flatlist

But I've improved it much more, using memoization and other optimization techniques + I've rewritten it to functional components only.

**Comment by GustavPS** [comment]
> It is basically basing on this. It's not public. https://snack.expo.dev/@jenshandersson/optimized-video-flatlist
> 
> But I've improved it much more, using memoization and other optimization techniques + I've rewritten it to functional components only.

Thanks, will give that a try

**Comment by aphillipo** [comment]
Shame this was closed, adding play(), reset() and pause() seems like simple additions. I might just wrap it and forward the ref and add them...

**Comment by hirbod** [comment]
I recommended moving to expo-av or https://github.com/aws/amazon-ivs-react-native-player

Way more reliable and better video component

**Comment by ramssutharr** [comment]
> I recommended moving to expo-av or https://github.com/aws/amazon-ivs-react-native-player
> 
> Way more reliable and better video component

does ivs support 3rd party content like Cloudinary.

**Comment by hirbod** [comment]
Yes but HLS from non-ivs is a battery killer on iOS. If you're using mp4 only it's the best though. HLS on android is also fine
