### ISSUE TITLE
exit fullscreen programatically

### ISSUE THREAD

**Issue by rogerkerse** [TheWidlarzGroup/react-native-video#638]
Is there a way to exit full screen programatically?

this.player.presentFullscreenPlayer() only goes in full screen, but does not exit it

**Comment by KristinaHus** [comment]
this is late response, but for someone who will need it later, you can use this.player.dismissFullscreenPlayer()

**Comment by JF-13** [comment]
Is there an event that will fire when physically exiting the FullscreenPlayer

**Comment by cobarx** [comment]
@JF-13 look at the props in the README, there are events for both entering and leaving fullscreen.
