### ISSUE TITLE
[Android, Exoplayer] Video's audio ends prematurely

### ISSUE THREAD

**Issue by re7eal** [TheWidlarzGroup/react-native-video#641]
On Android using Exoplayer, a video's audio track stops before its actual end time/duration about 1-2 seconds or less resulting in clipping audio at the end.

This problem does not occur on iOS.

react-native: 0.44.2
react-native-video: commit [72a46bc308d63f6ae95bb2a18b9ee6feaf867860](https://github.com/react-native-community/react-native-video/commit/72a46bc308d63f6ae95bb2a18b9ee6feaf867860)

**Comment by natureStory** [comment]
I meet the same problem, a video will stop at about 20M loaded. Does anyone has some methods to solve this problem?
