### ISSUE TITLE
Android - Video turns black when app goes from backgrounded to foregrounded

### ISSUE THREAD

**Issue by zachrnolan** [TheWidlarzGroup/react-native-video#643]
When watching a video on Android, If I background the app and then foreground it (press "recent" hardware button) the video will turn black. The video continues to play, but no longer shows up on the screen.

Testing on a Galaxy S7 using RN 0.43.3.

**Comment by schmaluk** [comment]
Having a similar problem on the emulator. IOS works but screen on Android remains black directly after starting.
This is the code Im using. Anything maybe wrong with it?
```
                    <Video
                        style={{flex: 1}}
                        resizeMode="cover"
                        paused={false}
                        onError={e => console.log(JSON.stringify(e))}
                        onProgress={e => console.log(JSON.stringify(e))}
                        source={{uri: "http://127.0.0.1:8080/test.mp4"}}
                    />
```

**Comment by pawlowskim** [comment]
Same here. After "onResume" is triggered, video is not render again there is a black screen. I need simple behaviour - stop video on last frame when it ends. This should be trivial but it isn't for both platforms and we need to make workarounds.

**Comment by chai86** [comment]
Same issue here. When the app is sent to the background, then when it is recalled to the foreground, the video is gone! The user has to go to another tab in the bottomTabNavigator to get it back! 😔
