### ISSUE TITLE
1.1 Should be unpublished / Android Issue React Native Video

### ISSUE THREAD

**Issue by PimDeWitte** [TheWidlarzGroup/react-native-video#645]
1.1 is completely unusable on Android. My assumption is that it has been tested on iOS and not on android

1) Buffering takes significantly longer than it should when loading local assets
2) Videos that are loaded async via prepareAsync (those that don't block the UI) and have sound, only play the sound, and not the video. 

This is resolved when downgrading to 1.0.0 (change package.json version to 1.0.0 not ^1.0.0 and then run npm uninstall react-native-video, then run npm install react-native-video)

I also made this change to ReactVideoView.java (node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoView.java) to fix the race conditions on local assets yet load remote assets faster:

Replace the prepare(this) line with the following block of code:

```java
                 if(isAsset) {
          		prepare(this);
     		 } else {
     		 	prepareAsync(this);
     		 }
```

**Comment by schmaluk** [comment]
@Having a similar problem on the emulator. IOS works but screen on Android remains black directly after starting.
This is the code Im using. Anything maybe wrong with it?
```
                    <Video
                        style={{flex: 1}}
                        resizeMode="cover"
                        paused={false}
                        onError={e => console.log(JSON.stringify(e))}
                        onProgress={e => console.log(JSON.stringify(e))}
                        source={{uri: "http://127.0.0.1:8080/test.mp4"}}
                    />
```

**Comment by PimDeWitte** [comment]
@mlukasch it looks like you are not setting the video height and width

**Comment by schmaluk** [comment]
@PimDeWitte doesnt change anything. still not working. Just hangs
Do you know any alternative video player for react native?

**Comment by itinance** [comment]
@PimDeWitte you should send a PR for your prepare(this)-replacement.

**Comment by PimDeWitte** [comment]
@itinance once it passes our internal QA i will

**Comment by anshul-kai** [comment]
Any update on this @PimDeWitte? Would love to see this in the next release. Thank you!

**Comment by cobarx** [comment]
Both the Android and ExoPlayer versions are working well for me in 2.1.0.
