### ISSUE TITLE
Wrong dimensions in onLoad event with vertical video.

### ISSUE THREAD

**Issue by gezichenshan** [TheWidlarzGroup/react-native-video#646]
I read #203 & #205 and received my video's actual dimensions in onLoad event body, but I got a  wrong width and height of a vertical video. I make this video by my iPhone5S.

here is the event body:
```
{ canPlaySlowForward: false,
	  target: 715,
	  currentTime: 0,
	  canPlayFastForward: false,
	  canStepForward: false,
	  canStepBackward: false,
	  duration: 82.30400085449219,
	  naturalSize: { width: 1280, orientation: 'landscape', height: 720 },
	  canPlayReverse: false,
	  canPlaySlowReverse: false }
```
In fact, it should be 720x1280,not 1280x720.

**Comment by gezichenshan** [comment]
solved! see #205 .

**Comment by EladBezalel** [comment]
@gezichenshan so actually this isn't solved..
You found the solution but it wasn't merged into this repository.. hardcoded changing the library is not helping, do you mind reopen this issue?

**Comment by kinka** [comment]
I encountered the same problem in android's using ExpoMediaPlay. It is a vertical video but I get the orientation 'landscape' in onLoad callback.

**Comment by josesuero** [comment]
I'm still getting this on 4.3.1, iOS naturalSize shows:
{orientation: "portrait", width: 1920, height: 1080}
 the correct dimensions, but android shows the wrong orientation 
{orientation: "landscape", height: 1080, width: 1920}

**Comment by orcunorcun** [comment]
Actually i got that problem with .mov files only. :/ how we can fix?

**Comment by pribeh** [comment]
We're experiencing the same issue with .mov files.

**Comment by jarod-legault** [comment]
I was able to find a workaround for Android. From what I can tell, you can use the `METADATA_KEY_VIDEO_ROTATION` property of the video along with the width and height to determine the orientation. I wrote a native module to retrieve the width, height, and rotation using [Android's `MediaMetadataRetriever`](https://developer.android.com/reference/android/media/MediaMetadataRetriever.html) in Java:

``` java
  @ReactMethod
  public void getVideoDimensions( String filePath, Promise promise ) {
    MediaMetadataRetriever metadataRetriever = new MediaMetadataRetriever();
    metadataRetriever.setDataSource( filePath );
    String rotation = metadataRetriever.extractMetadata( MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION );

    Integer height;
    Integer width;
    if ( rotation.equals( "90" ) || rotation.equals( "270" ) ) { // Swap width & height if video is rotated.
      height = Integer.parseInt( metadataRetriever.extractMetadata( MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH ) );
      width  = Integer.parseInt( metadataRetriever.extractMetadata( MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT ) );
    }
    else {
      height = Integer.parseInt( metadataRetriever.extractMetadata( MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT ) );
      width  = Integer.parseInt( metadataRetriever.extractMetadata( MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH ) );
    }

    WritableMap dimensions = Arguments.createMap();
    dimensions.putInt( "height", height );
    dimensions.putInt( "width", width );
    dimensions.putBoolean( "isLandscape", width > height );

    promise.resolve( dimensions );
  }
```

I can then call this method whenever I need to know the dimensions and/or orientation of the video.
