### ISSUE TITLE
[iOS] Video paused when ejecting headphones

### ISSUE THREAD

**Issue by onchainguy-btc** [TheWidlarzGroup/react-native-video#652]
Steps to reproduce:
1. Connect headphones to your iPhone
2. Go to a view where a video is included
3. Play the video (if not autoplay)
4. While the video is still playing eject your headphones
5. The video gets paused

Expected behavior:
The video keeps playing.

Does anybody else have this issue?

**Comment by onchainguy-btc** [comment]
Sorry my fault, default iOS behavior >.<

**Comment by evanjmg** [comment]
this is still bug, if it's muted that shouldn't happen
