### ISSUE TITLE
iOS - Audio video stops when app goes to background

### ISSUE THREAD

**Issue by AntoineGrandchamp** [TheWidlarzGroup/react-native-video#653]
Even with `playInBackground` activated, the video stops when the app switch to background. You then need to press play in the control center in order to play it in background.

Is it the normal behavior ? Shouldn't it continue playing ?

**Comment by fedebaier** [comment]
I found the solution to this: https://github.com/react-native-community/react-native-video/issues/797#issuecomment-334480547

**Comment by alex3144** [comment]
+1
