### ISSUE TITLE
Video never play

### ISSUE THREAD

**Issue by jose920405** [TheWidlarzGroup/react-native-video#655]
I'm using version `0.9.0`, because my proyect has a `0.39` react version.

This is my config.

`import Video from 'react-native-video';`

```
<Video
   source={{ uri: videoUrl }} -> i'm sure that this `url` is valid and mp4 format
   style={styles.videoSt}
   paused={false}/>
```

![captura de pantalla 2017-06-15 a la s 2 29 21 p m](https://user-images.githubusercontent.com/12536184/27198278-24a4d5f4-51d7-11e7-8d50-726a0f732acc.png)
![captura de pantalla 2017-06-15 a la s 2 29 36 p m](https://user-images.githubusercontent.com/12536184/27198279-24a8aad0-51d7-11e7-81b4-d092eecf760a.png)

Inside my app:

![captura de pantalla 2017-06-15 a la s 2 30 30 p m](https://user-images.githubusercontent.com/12536184/27198295-3753950a-51d7-11e7-83de-d0db43668c60.png)

The red area is the `<Video>`, but only can see that.. not show controls or some image

Please help

**Comment by JBerendes** [comment]
having the same problem in react native 44.2

**Comment by paulomogollon** [comment]
Im having the same issue, I narrow it down to the display zoom settings on the iPhone.
Can you guys check if you have your display zoomed? This only happens on iPhone 6 and greater iPhone 5 has no display zoom option.

Settings -> Display & Brightness -> View

For me after I set up the zoom option it wont work, if I rollback to the standard option still wont work. Already uninstalled the app and rebooted the device with no luck.

**Comment by paulomogollon** [comment]
In my case I added all the callbacks and there is no error called. The onStartLoad, onLoad onEnd and onProgress are all working, but the video still not showing.

**Comment by jose920405** [comment]
```
<Video
  source={{ uri: videoUrl }}
  resizeMode="cover"
  repeat={true}
  muted={false}
/>

This is my code, and the video still not working
```

**Comment by JBerendes** [comment]
I'm probably a rare user on iPod Touch and an iPad. No option for zoom on either.  
No video playing on either of them.

**Comment by jose920405** [comment]
It's a shame to have had to abandon this module, in the end I had to add an html with a video tag to a webview.

**Comment by theBliz** [comment]
@jose920405 how you did it?

**Comment by jose920405** [comment]
hi @theBliz unfortunately this method could not be done. I had to resort to a webview with the source of the video embedded in the html.

```
let htmlString = `<!DOCTYPE html><html><style> #videoId { position: absolute; top: 0; left: 0; right: 0; margin: auto; width: 100%; height: 100%; } }</style><body> <video id=\"videoId\" webkit-playsinline=\"true\" playsinline=\"true\" autoplay> <source src=\"${videoUrl}\" type=\"video/mp4\" /> </video></body></html>`;

<WebView
                key={key}
                source={{ html: htmlString }}
                style={{ width: screen.width, flex: 1 }}
            />

```

**Comment by sudhanshu6247** [comment]
I am also facing the same issue on android. No video is getting loaded.

I am using
react-native: 0.43.4
react-native-video: 1.0.0

My code is

         <Video source={{uri: "youtube-url"}}   // Can be a URL or a local file.
           ref={(ref) => {
             this.player = ref
           }}                                      // Store reference
           rate={1.0}                              // 0 is paused, 1 is normal.
           volume={1.0}                            // 0 is muted, 1 is normal.
           muted={false}                           // Mutes the audio entirely.
           paused={false}                          // Pauses playback entirely.
           resizeMode="cover"                      // Fill the whole screen at aspect ratio.*
           repeat={true}                           // Repeat forever.
           playInBackground={false}                // Audio continues to play when app entering background.
           playWhenInactive={false}                // [iOS] Video continues to play when control or notification center are shown.
           ignoreSilentSwitch={"ignore"}           // [iOS] ignore | obey - When 'ignore', audio will still play with the iOS hard silent switch set to silent. When 'obey', audio will toggle with the switch. When not specified, will inherit audio settings as usual.
           progressUpdateInterval={250.0}          // [iOS] Interval to fire onProgress (default to ~250ms)
           onLoadStart={(el)=>console.log("video is being loaded",el)}            // Callback when video starts to load
           onLoad={()=>console.log("video loading")}               // Callback when video loads
           onProgress={()=>console.log("video loading is in progress")}               // Callback every ~250ms with currentTime
           onEnd={()=>console.log("video is now loaded")}                      // Callback when playback finishes
           onError={()=>console.log("video can not be loaded")}               // Callback when video cannot be loaded
           onBuffer={()=>console.log("buffer stage")}                // Callback when remote video is buffering
           onTimedMetadata={()=>console.log("metadata received")}  // Callback when the stream receive some metadata
           style={()=>styles.videoPlayer} />


Only "onLoadStart" prop is getting triggered
in console I am getting following error

     System.err: java.io.IOException: Prepare failed.: status=0x1
     System.err: 	at android.media.MediaPlayer._prepare(Native Method)
     System.err: 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1163)
     System.err: 	at com.yqritc.scalablevideoview.ScalableVideoView.prepare(ScalableVideoView.java:171)
     System.err: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:300)
     System.err: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:202)
     System.err: 	at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:92)
     System.err: 	at java.lang.reflect.Method.invoke(Native Method)
     System.err: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:78)
     System.err: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
     System.err: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
     System.err: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
     System.err: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
     System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
     System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
     System.err: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
     System.err: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
     System.err: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
     System.err: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
     System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
     System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
     System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
     System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
     System.err: 	at android.os.Handler.handleCallback(Handler.java:746)
     System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
     System.err: 	at android.os.Looper.loop(Looper.java:148)
     System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
     System.err: 	at java.lang.reflect.Method.invoke(Native Method)
     System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
     System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
	 MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://www.youtube.com/watch?v=gENjTs8VskQ     				

Please help.

**Comment by sudhanshu6247** [comment]
@jose920405 I also tried webview, but the problem I am facing that whole youtube interface is getting loaded in webview. When I open a youtube video inside webview which is again inside a card, if someone scroll in this card, whole youtube interface is getting displayed, which I don't want. I want to display only video.

**Comment by sivakumar-cf** [comment]
Any Solution for this issue?

I am getting error in android 4.4 and less, and the same code working fine on android 5.0 and above.

` java.io.IOException: Prepare failed.: status=0x1
 W/System.err:     at android.media.MediaPlayer.prepare(Native Method)
com.yqritc.scalablevideoview.ScalableVideoView.prepare(ScalableVideoView.java:171)
com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:300)
com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:202)
com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:92)`

**Comment by chuyinweilai** [comment]
it looks like no one knows....
I'm using: "react": "16.2.0","react-native": "0.52.1",
![image](https://user-images.githubusercontent.com/21523040/35319104-54836f96-0119-11e8-812a-1c5c860d9833.png)
```
<Video 
	source={{uri: 'http://lovecard.oss-cn-beijing.aliyuncs.com/dev/mtsvideo/0e44f8767baa4c9f9d224b8f7178794609577802.mp4'}}
	ref="player"
	rate={1.0}
	volume={1.0}
	muted={false}
	paused={false}
	resizeMode="contain"
	repeat={true}
	playInBackground={false}
	playWhenInactive={false}
	ignoreSilentSwitch={"ignore"}
	progressUpdateInterval={250.0}
	onLoadStart={this.loadStart}   
	onLoad={this.setDuration}      
	onEnd={this.onEnd}             
	onError={this.videoError}      
	style={styles.backgroundVideo}/>
```



so, we have to choose webview???

**Comment by lsorin81** [comment]
- just give the style of the video fixed width and height and it will work

**Comment by parisaabasian** [comment]
anybody?please help :((

**Comment by parisaabasian** [comment]
@jose920405 does your video auto play works?

**Comment by jose920405** [comment]
I never went back to work in this case. My last answer was what worked for me

**Comment by satyamatwork** [comment]
@lsorin81 thanks man. your last comment worked for me.

**Comment by petrosmm** [comment]
> * just give the style of the video fixed width and height and it will work

on api 24 if i also add an aspect ratio, the video will suddenly appear, how interesting....
