### ISSUE TITLE
Android API 16 doesn't work

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#658]
Versoin `1.0.0` throws no errors while not playing the video. `master` throws the following error when playing a file stored on local storage.

	{"error":{"extra":-2147483648,"what":1}}

Any clue on how to resolve this?

**Comment by 447491480** [comment]
yes it is. me too

**Comment by HessiPard** [comment]
Still the problem exists in api 16. throwing no error while not playing the video

**Comment by DavitVosk** [comment]
Hey guys. Just change the default configuration of gradle files to use exoplayer. See the comment here https://github.com/react-native-community/react-native-video/issues/668#issuecomment-312383674
