### ISSUE TITLE
event handlers not working

### ISSUE THREAD

**Issue by darkfiredarkhalo** [TheWidlarzGroup/react-native-video#659]
onError, onEnd, onLoad... doesn't work.I put console.log in Video.js they don't work there as well.

OS:   iOS
RN :    0.45.0
react:  16.0.0-alpha.12

**Comment by darkfiredarkhalo** [comment]
react-native-video:  1.0.0

**Comment by paraswatts** [comment]
Have you been able to solve this? I am facing the same problem.
