### ISSUE TITLE
React native Video is not working on iOS.

### ISSUE THREAD

**Issue by sidhemuIdea** [TheWidlarzGroup/react-native-video#660]
Video player is working on android but not in iOS. 
"react-native": "^0.42.3",
"react-native-video": "^1.0.0"

this.url is the url without ".mp4".
`
<View style={styles.container} onLayout={this._handleLayout}>
                  <TouchableOpacity
                    style={styles.fullScreen}
                    onPress={() => this.setState({ paused: !this.state.paused })}>
                    <Video
                      ref={(ref: Video) => { this.video = ref }}
                      source={{uri:this.url}}
                      style={styles.fullScreen}
                      rate={this.state.rate}
                      paused={this.state.paused}
                      volume={this.state.volume}
                      controls={true}
                      muted={this.state.muted}
                      resizeMode={this.state.resizeMode}
                      onLoad={this.onLoad}
                      onProgress={this.onProgress}
                      onEnd={this.onEnd}
                      repeat={false}
                    />
                  </TouchableOpacity>
              </View>`

**Comment by JBerendes** [comment]
Likely a dupe of #655 ... in my case I'm not getting the correct value from the constants in resize and then wen I try to set it to something expected the box for where the video should show up is there but nothing plays.

**Comment by juanmajmjr** [comment]
Same issue here with react-native 0.46.2, any news?

**Comment by lighthx** [comment]
me too

**Comment by luisfuertes** [comment]
Same with `react-native-video@2.0.0` and `react-native@0.48.3`, it works on Android but on iOS only show disabled play icon.

Log: 
``` 
017-09-13 11:58:40.888605+0200 myapp_app[817:428324] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x17ed8f80 V:|-(>=10)-[UIImageView:0x17edad30]   (active, names: '|':AVAudioOnlyIndicatorView:0x17eda970 )>",
    "<NSLayoutConstraint:0x17edb9c0 V:[UIImageView:0x17edad30]-(>=10)-|   (active, names: '|':AVAudioOnlyIndicatorView:0x17eda970 )>",
    "<NSLayoutConstraint:0x17f8d860 V:|-(0)-[AVAudioOnlyIndicatorView:0x17eda970]   (active, names: '|':UIView:0x17f7d040 )>",
    "<NSLayoutConstraint:0x17f8d8b0 V:[AVAudioOnlyIndicatorView:0x17eda970]-(0)-|   (active, names: '|':UIView:0x17f7d040 )>",
    "<NSLayoutConstraint:0x17f8d4c0 V:|-(0)-[UIView:0x17f7d040]   (active, names: '|':AVPlayerView:0x17f7cc30 )>",
    "<NSLayoutConstraint:0x17f8d590 V:[UIView:0x17f7d040]-(0)-|   (active, names: '|':AVPlayerView:0x17f7cc30 )>",
    "<NSLayoutConstraint:0x17ee6110 'UIView-Encapsulated-Layout-Height' AVPlayerView:0x17f7cc30.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17edb9c0 V:[UIImageView:0x17edad30]-(>=10)-|   (active, names: '|':AVAudioOnlyIndicatorView:0x17eda970 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

this.props.videoURL: `{ uri: 'http://techslides.com/demos/sample-videos/small.mp4' }`


code:
``` 
          <Video
            source={ this.props.videoURL }
            ref={ (ref) => { this.player = ref }}
            rate={1.0}
            volume={1.0}
            paused={ this.state.paused }
            resizeMode="contain"
            muted={false}
            repeat={false}
            playInBackground={false}
            playWhenInactive={false}
            ignoreSilentSwitch={"ignore"}
            progressUpdateInterval={250.0}
            onEnd={ () => this._onEnd() }
            onFullscreenPlayerDidDismiss={ () => this._onEnd() }
            setControls={true}
            controls={true}
            style={{ position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 }}
          />
``` 

screenshot:
![simulator screen shot 13 sept 2017 12 10 02](https://user-images.githubusercontent.com/18212615/30371954-7cdf80d4-987c-11e7-9c9e-255cab100deb.png)

**Comment by chenghaohao** [comment]
Same issue here with react-native 0.47.1, not work on ios, any solution?

**Comment by nvtam2105** [comment]
I got the same issue with react-native 0.48.3, any updates?

**Comment by eliasws** [comment]
"this.props.videoURL: { uri: '**http**://techslides.com/demos/sample-videos/small.mp4' }"

For me only https Videos are working. Local Videos are broken aswell.

**Comment by djw27** [comment]
Have you tried setting allow arbitrary loads to true in your info.plist for iOS?

```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

More info here: https://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9

**Comment by lsorin81** [comment]
just give the style of the video fixed width and height and it will work

**Comment by akshaygore06** [comment]
Edit info.plist to allow the arbitrary load. This will solve the problem.

<img width="482" alt="screen shot 2018-05-18 at 12 35 30 am" src="https://user-images.githubusercontent.com/9061850/40222188-9392a88c-5a33-11e8-8b6d-56797e246ee7.png">

**Comment by OmarBasem** [comment]
allowing arbitrary loads does not fix the issue. Any suggestions??

**Comment by anjusr** [comment]
Same here.. after adding app transport security setting also not playing video

**Comment by katiachumakova** [comment]
Same issue.

**Comment by mohamedanwer123** [comment]
Same issue.

**Comment by e3bmo3ty** [comment]
same issue here.

**Comment by andrewshortall** [comment]
Same issue

**Comment by takosunil** [comment]
> Edit info.plist to allow the arbitrary load. This will solve the problem.
> 
> <img alt="screen shot 2018-05-18 at 12 35 30 am" width="482" src="https://user-images.githubusercontent.com/9061850/40222188-9392a88c-5a33-11e8-8b6d-56797e246ee7.png">

This works for me. I just had to run `react-native run-ios` command after setting this "Yes"

**Comment by digimonktech** [comment]
same issue

**Comment by waris117** [comment]
same issue getting 
error code: -11800
domain: "AVFoundationErrorDomain"
any fix for ios, android works?

**Comment by freeboub** [comment]
Not enough information to investigate anything linked to this issue.

**Comment by waris117** [comment]
Please any one cam recommend alternative that is working on both ios/android? or at least ios
