### ISSUE TITLE
How to play live stream with RTSP?

### ISSUE THREAD

**Issue by m860** [TheWidlarzGroup/react-native-video#661]

**Comment by sabbyt** [comment]
@m860 This is built on top of react-native-video and supports rtmp and rtsp https://www.npmjs.com/package/react-native-vlc

**Comment by choychris** [comment]
hi @sabbyt ,
Do you find any solution to play RTSP on IOS?

**Comment by imagine10255** [comment]
+1

**Comment by rexlow** [comment]
+1

**Comment by dfucci** [comment]
+1

**Comment by rogerio-azevedo** [comment]
I found this, working RTSP on IOS:

[react-native-vlc-media-player](https://github.com/razorRun/react-native-vlc-media-player)
