### ISSUE TITLE
[Android][iOS Simulator] Sound is echoing

### ISSUE THREAD

**Issue by petivagyok16** [TheWidlarzGroup/react-native-video#664]
There are 2 audio tracks playing simultaneously with a slight delay between them causing echo. Any ideas?

Tried in iOS Simulator and Android device

**Comment by jeffzing** [comment]
any solution?

**Comment by jjant** [comment]
So? What happened?

**Comment by dwilt** [comment]
The issue for us was that we were mounting the component that contained the video _twice_ without previously unmounting - thus the video played twice

**Comment by joaohenrifranco** [comment]
Issues #528 and #967 seems to be the same problem. Any solution or workaround yet? I'm sure i'm not mounting the component twice as @dwilt mentioned.

**Comment by Winglonelion** [comment]
@joaohenriquef If you ensure no duplicated mount in your JS, the critical cause of this problem could be the duplication in your `activity` (almost is `MainActivity`).

This could be reproduced easily by press `home button` then open app again from launcher icon.

**solution:**
add this property to your `.MainActivity` in AndroidManifest.xml 
```
            android:launchMode="singleTask"
```

this is demo:

```
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask"
            android:label="@string/app_name"
            android:exported="true"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"        
            android:windowSoftInputMode="adjustResize">
           <!-- content -->
        </activity>
```

> This prevent your activity start multiple times when one already activated.

**Comment by joaohenrifranco** [comment]
I guess that has solved, so far I haven't seen the bug again. Thanks @Winglonelion !

**Comment by alikianinejad** [comment]
Same problem in ios when play video in react-native-modal

**Comment by umairahmadh** [comment]
> Same problem in ios when play video in react-native-modal

@alikianinejad Did you get to resolve this issue? I am facing the same in iOS.
