### ISSUE TITLE
[Android] Image not appears on Android

### ISSUE THREAD

**Issue by petivagyok16** [TheWidlarzGroup/react-native-video#665]
The image of the video is not appears on Android. In iOS simulator image is fine.
Any ideas?
```
<TouchableOpacity
 style={styles.videoWrapper}
 onPress={() => this.playOrPauseVideo()}>
     <Video
          source={{ uri: product.video.url }}
          ref={(ref) => { this.videoPlayer = ref }}
          rate={1.0}
          volume={0.1}
          playInBackground={false}
          paused={this.state.paused}
          repeat={true}
          muted={this.state.muted}
          style={styles.video}
        />
</TouchableOpacity>
```

Im using `react-native-video` directly from this github repo. The npm package didn't compile on Android (Android build tools (23.0.1) are too low `react-native-video` requires `25.0.0`)

**Comment by fendorio** [comment]
Did you find the fix for this? I'm encountering the same thing, only on Android.

**Comment by tirrorex** [comment]
@petivagyok16 did you fix it mate?
