### ISSUE TITLE
[Android] dash/mpd content problem ("QCMediaPlayer mediaplayer NOT present")

### ISSUE THREAD

**Issue by frankiewiczkamil** [TheWidlarzGroup/react-native-video#668]
Hi,
I have encountered problem with dash streams in my app. 
HLS streams work fine, but dash does not work. There are errors in `adb` log and  `onError` callback gives "error" message in `videoError`. 
I attached logs for both cases : working - hls and error - dash).

It seems that even source given in official example :
```
 /* For ExoPlayer */
            /* source={{ uri: 'http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0', type: 'mpd' }} */
```
doesn't work anymore, at least for me (tested on 2 devices with 5.x android, I can do more tests tomorrow at work)

Does anyone have an idea what is wrong?

My package.json includes this stuff:

```
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-vector-icons": "^4.2.0",
    "react-native-video": "^1.0.0",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1"
  },
```

[dashAndHlsLogs.zip](https://github.com/react-native-community/react-native-video/files/1112399/dashAndHlsLogs.zip)

**Comment by frankiewiczkamil** [comment]
It seems that this is the reason:
`E/MediaPlayer-JNI(26750): QCMediaPlayer mediaplayer NOT present`
I tried to fix it in ReactVideoView.java by creating MediaPlayer instance using static method instead of constructor [(like here),](https://stackoverflow.com/questions/24501086/why-mediaplayer-throws-not-present-error-when-creating-instance-of-it) but it returns me null
```
//mMediaPlayer = new MediaPlayer();
            Uri.Builder uriBuilder = new Uri.Builder();
            uriBuilder.appendPath("http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-common_init.mpd");
            mMediaPlayer = MediaPlayer.create(this.getContext(), uriBuilder.build());
            mMediaPlayer.setScreenOnWhilePlaying(true); // <--- NullPointerException in here...
```
Waiting for your help...

**Comment by frankiewiczkamil** [comment]
I solved problem by changing default configuration of gradle files (written in readme page/file) to use exoplayer. I found solution  [here](https://www.bountysource.com/issues/40364073-exoplayer)
In fact I was not aware that I must excplicitly choose exoplayer over default one... 
I found out that there is already task for readme update (#609), I suggest  taking this seriously for next newcomers, like me.

**Comment by Noitidart** [comment]
Thank you @frankiewiczkamil for sharing link to the solution, I was also running around for a long while trying to figure out.

**Comment by boypanjaitan16** [comment]
Hey, I'm just a new guy about this, and I do look up at the link you provide to the solutions, but I don't know how to do it, 
In that link said something like this :

Change in app/build.gradle:
```

- compile project(':react-native-video')
+ compile project(':react-native-video-exoplayer')
```

Change in settings.gradle:

```
+ include ':app',
-        ':react-native-video',
+        ':react-native-video-exoplayer'

- project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
+ project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
 but in my app/build.gradle, there is no something like that
