### ISSUE TITLE
How to switch poster to video?

### ISSUE THREAD

**Issue by kotazi** [TheWidlarzGroup/react-native-video#671]
I'm using poster like below.

```
const LazyVideo = ({ paused, onLoadVideo, video, poster }) => (
  <Video source={{uri: video}}
         resizeMode="cover"
         repeat
         paused={paused}
         poster={poster}
         onLoad={onLoadVideo} style={[u.w(w), u.h(w)]} />
);
```

So I can see `poster` in correctly.
But if loading video is finished, poster is shown and not switch to video.

**Comment by masiamj** [comment]
+1

**Comment by aike19115** [comment]
Same issue, the poster is always visible and doesn't hide when the video starts playing.

"react-native": "0.51.0",
"react-native-video": "^2.0.0",

**Comment by djw27** [comment]
What does your `onLoadVideo` do? You need to make sure that rate isn't set to 0: https://github.com/react-native-community/react-native-video/pull/412/files

**Comment by c-goettert** [comment]
As long there is no official fix, maybe this workaround can help:

In the container component, store a state-variable `showThumbnail` and set it's default to true:
```javascript
constructor (props) {
  super(props)
  this.state = {
    showThumbnail: true
  }
}
```
Then in the `Video` Component, use the `onLoad`-callback to set the flag to `false`. The flag can then be used to determine whether the `poster`-props should be set or not:
 ```javascript
<Video
  poster={this.state.showThumbnail ? 'https://yoururl.com' : undefined}
  onLoad={() => this.setState({showThumbnail: false})}
/>
```

**Comment by kevinresol** [comment]
This problem still exists as of v2.1.1

**Comment by hsiaray** [comment]
I just modify the Video.js file and it works on android,  maybe that can help

  ```
_onProgress = function(event){
    if (this.state.showPoster) {
      this.setState({showPoster: false});
    }
    if (this.props.onProgress) {
      this.props.onProgress(event.nativeEvent);
    }
  }.bind(this);
```

**Comment by direwolf424** [comment]
Still getting this issue in version 3.2.1

**Comment by mnlbox** [comment]
Any news?

**Comment by llgoer** [comment]
Any news? 😿

**Comment by alanlanglois** [comment]
any news?

**Comment by yongqiangyue** [comment]
see me.
`  const defaultImage = this.state.showDefault ?
            <FastImage style={[this.props.style, { position: "absolute" }]}
                       source={fileIcon('video')}
                       resizeMode={FastImage.resizeMode.cover}
                       fadeDuration={0}
            /> : null;`
`render() {  
        return (
            <View style={[{ backgroundColor: "#fff" }, this.props.containerStyle || this.props.style]}>
                {defaultImage}
                <Video style={!this.state.showDefault ? this.props.style : undefined}
                       ref={(ref) =>{
                           this.player = ref;
                       }}
                       source={this.props.source}
                       paused={true}
                       resizeMode={'cover'}
                       onLoad={() => {
                           this.player.seek(0);
                           this.setState({ showDefault: false });
                       }}
                       hideShutterView={true}
                       audioOnly={true}
                       onError={() => this.setState({ showDefault: true })}
                />
            </View>
        );
    }`

**Comment by yongqiangyue** [comment]
`export default class MyVideo extends Component {
    state = {
        showDefault: true,
    };

    render() {
        const defaultImage = this.state.showDefault ?
            <FastImage style={[this.props.style, { position: "absolute" }]}
                       source={fileIcon('video')}
                       resizeMode={FastImage.resizeMode.cover}
                       fadeDuration={0}
            /> : null;

        return (
            <View style={[{ backgroundColor: "#fff" }, this.props.containerStyle || this.props.style]}>
                {defaultImage}
                <Video style={!this.state.showDefault ? this.props.style : undefined}
                       ref={(ref) =>{
                           this.player = ref;
                       }}
                       source={this.props.source}
                       paused={true}
                       resizeMode={'cover'}
                       onLoad={() => {
                           this.player.seek(0);
                           this.setState({ showDefault: false });
                       }}
                       hideShutterView={true}
                       audioOnly={true}
                       onError={() => this.setState({ showDefault: true })}
                />
            </View>
        );
    }
}`
