### ISSUE TITLE
setting onProgressInterval for android

### ISSUE THREAD

**Issue by tonycai96** [TheWidlarzGroup/react-native-video#673]
Is it possible to change the time interval between onProgress invocations on Android? The "progressUpdateInterval" prop does nothing.

Specifically, on Android, onProgress usually gets triggered every 1s (even though the documentation says it gets triggered every 250ms) but I want it to be triggered more often.

**Comment by EthanLin-TWer** [comment]
I've tried on Android 7 and the `progressUpdateInterval` seems to work for me. Here's my versions of dependencies: 

```json
"react-native": "0.48.4",
"react-native-video": "^2.0.0",
```

**Comment by euroclydon37** [comment]
If using exoplayer, there seems to be no interval at all. It's called nonstop nearly every millisecond. I was using react-native-tcp to receive commands over the network, and those commands would process seconds later due to the processing overhead.

**Comment by cobarx** [comment]
This has been fixed in 2.1.1

**Comment by euroclydon37** [comment]
I've updated to **2.2.0** and `onProgress` is still firing nearly every millisecond with `progressUpdateInterval` set to 1000.

**Comment by cobarx** [comment]
It sounds like something else is going on in your case that's causing it not to have any delay between updates. You'll need to run the app in the Android Studio debugger & set a breakpoint in progressHandler in ReactExoplayerView.java or create a sample project so that I can test this out.

What video are you using in case that's an easy way to reproduce this?

**Comment by euroclydon37** [comment]
I'm using an mp4 video streamed over the local network.

I've got a pretty urgent deadline so I don't think I'll be able to dive into this too deeply. I'll take a look at the progressHandler. Thanks for the info.

And thank you for picking this project up. Your work is greatly appreciated.
