### ISSUE TITLE
Android: onLoadStart and onLoad firing twice

### ISSUE THREAD

**Issue by anshul-kai** [TheWidlarzGroup/react-native-video#674]
The following works just fine on iOS but on Android, onLoad callbacks fire twice. Anyone else experiencing these issues? I'm on version 1.0.0.

    export default class Player extends Component {
      render() {
        return (
          <View>
            <Video source={{uri: 'file:///data/user/0/com.xyz/files/test.m4a'}}
                  volume={1.0}
                  muted={false}
                  paused={false}
                  onLoad={() => console.log('onLoad')}
                  onLoadStart={src => console.log('onLoadStart', src)}
                  onProgress={() => {}}
                  onEnd={() => {}}
                  onError={err => console.error(err)}
                  playInBackground={true}
                  playWhenInactive={true}
                  resizeMode='cover'
                  repeat={false}/>
          </View>
        );
      }
    }

**Comment by Traviskn** [comment]
I'm also seeing this issue, it's a bit strange

**Comment by treemore** [comment]
i use version:2.0.0 . use android-exoplayer .  onload will load twice too.
the play src is a m3u8 in our remote url,the request will send twice too.

**Comment by SuhairZain** [comment]
Has anyone been able to find a solution to this issue? Is anyone working on it?

**Comment by Saumyadip-Pramanik** [comment]
I am also having the same issue. 
Currently making it work with a bool check:
onLoadStart={() => {
    if (!this.state.onLoadCalledOnce) {
        this.videoStateChanged('start')
        //inside 'videoStateChanged' function set the bool: this.state.onLoadCalledOnce = false
    }
}}

**Comment by anshul-kai** [comment]
Check your parent container `View`s guys. Although strange, for me this was happening due to a change of `pointerEvents` on a parent container. Try removing all parent containers and use the process of elimination to identify what's causing this for your case.
