### ISSUE TITLE
Update library release.

### ISSUE THREAD

**Issue by iamronsuez** [TheWidlarzGroup/react-native-video#675]
Hello, thanks for making this handy library, its possible to make a new release for this? given that there are several bugs and fixes that were fixed and merged already and the latest release was on Jan 31.

**Comment by gyf19** [comment]
@mattapperson ping

**Comment by gyf19** [comment]
Update 1.1.0

**Comment by RWOverdijk** [comment]
Yes please. I'm running on master now.

**Comment by mattapperson** [comment]
I am a little slammed this week, ill try to cut a new release on Tuesday

**Comment by RWOverdijk** [comment]
@mattapperson Need help with this lib? If you're too slammed for a release, your release procedure might be suboptimal. I'll be using this library a lot, so perhaps I can assist.

**Comment by gyf19** [comment]
@mattapperson   ping?

**Comment by gyf19** [comment]
@mattapperson  ping?  Thank you

**Comment by anshul-kai** [comment]
We need more contributors and administrators for this repo. This is an amazing library, arguably the best react-native library and thus the high number of issues which can be overwhelming for any one person to handle.

@mattapperson and other admins, can we come up with a strategy to bring about more leadership and pace here?

Thank you!

**Comment by mattapperson** [comment]
Hey sorry, I’ll be cutting a build tomorrow.

I’ll also be talking with the other admins/collaborators about the issue/pr/responsiveness issues

**Comment by iamronsuez** [comment]
@mattapperson

**Comment by mattapperson** [comment]
@iamronsuez sorry... updated!
