### ISSUE TITLE
streaming link with .m3u8 does not play

### ISSUE THREAD

**Issue by mohsen0071** [TheWidlarzGroup/react-native-video#678]
I'm using this component and I notice that in android 5 or below, streaming link with .m3u8 does not play. Can anyone help me to solve this problem?

**Comment by bendellarocco** [comment]
+1

**Comment by choychris** [comment]
+1

**Comment by sagemonkey** [comment]
+1

**Comment by AwayQu** [comment]
I fixed this problem on android by append `type` param like the follow.
```javascript
source={{ uri : url, type : 'm3u8'} }
```
