### ISSUE TITLE
Windows does not display video, only sound plays

### ISSUE THREAD

**Issue by jburich** [TheWidlarzGroup/react-native-video#680]
In a react-native-windows app the sounds will play, and I can see the media controls if I use react-native-video-controls I can interact with the controls successfully, but the video simply doesn't appear. I have tried a bunch of videos and right now I'm using this one: https://ia800209.us.archive.org/24/items/WildlifeSampleVideo/Wildlife.mp4.

Here is my code:

`
import React, {Component} from 'react';
import {Animated, View, Text, StyleSheet, PanResponder} from 'react-native'
import VideoPlayer from 'react-native-video-controls'

export default class TrackPad extends Component {

    player = null;

    render() {
        const src = require('./Wildlife.mp4');
        return (
            <VideoPlayer source={src}   // Can be a URL or a local file.
                         ref={(ref) => {
                             this.player = ref
                         }} isPaused={false}
                         repeat={false}
                         resizeMode="cover"
                         paused={false}
                         style={styles.backgroundVideo}/>
        )
    }
};

const styles = StyleSheet.create({
    backgroundVideo: {
        // flex: 1,
        height: 800,
        width: 800,
    }
});`

**Comment by krishnaglick** [comment]
Trying setting position to absolute. It should show up, but you may have positioning issues.

**Comment by frankiewiczkamil** [comment]
@jburich, Did you try video with style flex:1 nested in view with flex:1?

**Comment by jburich** [comment]
Thanks for the suggestion @krishnaglick , but no luck. I just built a new project and below is my index.windows.js file. I can hear the sounds but the screen is blank. 

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet
  } from 'react-native';
import Video from 'react-native-video'

class vi_table extends Component {
  render() {
      return <Video source={require('./src/jack.mp4')}   // Can be a URL or a local file.
                   repeat={false}
                   resizeMode="cover"
                   paused={false}
                   style={styles.backgroundVideo}/>
  }
}

const styles = StyleSheet.create({
    backgroundVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    }
});

AppRegistry.registerComponent('vi_table', () => vi_table);`

**Comment by jburich** [comment]
@frankiewiczkamil yes the flex:1 set up nested inside a view is how I originally set it up as that is how I would prefer it to work.

**Comment by t14** [comment]
I have a similar issue on android, did you find a solution.
Noticed that it also happens with the example app that comes with this repo

**Comment by jburich** [comment]
no luck, but I haven't put a lot of effort into it yet. I'm hoping to get back to this over the weekend.

**Comment by t14** [comment]
This looks like it might be an emulator issue. Seems to work when you try on a real device. I had this problem Android and IOS emulators. The video showed when I ran the code on a real Android device I have not tried on a real IOS device yet. Im guessing this might be the same issue with windows

**Comment by jburich** [comment]
I am building an app to run on Windows 10 desktops, so there is no emulator involved.

**Comment by mg10110** [comment]
I had the same problem... @jburich try this:
Application properties -> targeting  set: 
**target version: Windows 10 Anniversary Edition (...14393)
min version: Windows 10 (....10586).**
it solved my issue, now I hear and can see ;)

**Comment by jburich** [comment]
been a while since I last got to work on this project, but no luck. The 3 things I've tried (amongst many shots in the dark):

1) ensuring flex:1 is on the VideoPlayer and all container components
2) setting fullscreen via absolute positioning
3) setting the target/min versions

I've tried these all individually and in concert and no luck. I'm going to keep trying different things to see if I can find the problem.

**Comment by ejswenson15** [comment]
+1

**Comment by bereal** [comment]
I have the same issue on Android, both emulator and the device. Nothing of the above helped.

**Comment by rock288** [comment]
same issue on IOS
