### ISSUE TITLE
exoplayer cookies

### ISSUE THREAD

**Issue by manuTro** [TheWidlarzGroup/react-native-video#683]
Hi, following https://github.com/react-native-community/react-native-video/pull/426 I'm using exoplayer (so I changed both the settings.grandle and the build.grandle files), but I cannot see the video. (.m3u8)
From the log I can see this response
**com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401.**

**From the HTTP request Header I noticed that the cookies are not passed**. Instead without exoplayer I was able to see them. 
Maybe there is a different configuration that I should do?

![image](https://user-images.githubusercontent.com/25326470/27959361-6a5192e8-6327-11e7-9f69-d8fb3a83ce78.png)

**Comment by iamronsuez** [comment]
hi there , can you tell me how did you integrate the exoplayer ? cause i'm trying to do it and i'm having the issue described at #697

**Comment by cobarx** [comment]
Cookie support for ExoPlayer will be included in 2.2.0
