### ISSUE TITLE
Border radius doesn't work on Android

### ISSUE THREAD

**Issue by peteroid** [TheWidlarzGroup/react-native-video#685]
Providing the style 'borderRadius' doesn't change the view of the video component on Android. However, it works on iOS.

```javascript
<Video
    style={[{ width: 100, height: 100, borderRadius: 50 }]}
    {...otherProps}
/>
```

**Comment by maxs15** [comment]
Same issue here, did you find a solution @peteroid ?

**Comment by peteroid** [comment]
@maxs15 still no clue. may be related to this https://github.com/facebook/react-native/issues/8885

**Comment by steffina** [comment]
I also have the same problem. My colleague try to do it like this
```
<Image
        style={{width:60,height:60,borderRadius:(Platform.OS === 'ios')?30:100}}
        ... 
/>
```
but sometimes it didn't work and go back to square, still don't know why..

**Comment by crokobit** [comment]
same here...

**Comment by thangkho** [comment]
@perqa 
have you fixed this error?
I user latest version RN 0.54.2 and it have same error.

**Comment by MorcosS** [comment]
Same here, any fix for that?

**Comment by cobarx** [comment]
Try wrapping the Video element in a container View and setting borderRadius on that View. You will also need to set `overflow: hidden` on it.

**Comment by josesuero** [comment]
Logre solo colocar los bordes superiores redondos, los de abajo, no logre hacerlo por los controles (play sonido)

**Comment by lupapp** [comment]
Yo lo solucione asi:
items:{
            borderTopLeftRadius:10,
            borderTopRightRadius:10,
            borderBottomLeftRadius:10,
            borderBottomRightRadius:10
        }

**Comment by maitrungduc1410** [comment]
Just set `borderRadius` doesn't work for me. I have a very simple `View`, and set `borderRadius` doesn't work on Android. I need to apply solution from @lupapp

**Comment by mym0404** [comment]
> Yo lo solucione asi:
> items:{
> borderTopLeftRadius:10,
> borderTopRightRadius:10,
> borderBottomLeftRadius:10,
> borderBottomRightRadius:10
> }

Weird bug.. this is working for me thanks 👍

**Comment by joseph-allen** [comment]
This still isn't working

**Comment by L-Thirunavukkarasu** [comment]
Hi,
i found solution in hard way...i think it will help someone...

![Screenshot_1614379639](https://user-images.githubusercontent.com/42915494/109363513-c59f5f00-78b2-11eb-8faa-6368f5b95721.png)

`<View style={{height: 215, alignItems: 'center', flex: 1}}>
        <View
          style={{
            position: 'absolute',
            height: 215,
            width: ScreenWidth * 0.95,
            borderWidth: 10,
            borderRadius: 5,
            borderColor: 'white',
          }}></View>
        <View
          style={{
            position: 'absolute',
            height: 215,
            width: ScreenWidth * 0.95,
            borderWidth: 10,
            borderRadius: 20,
            borderColor: 'white',
          }}></View>
        <Video
          source={{
            uri:
              'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4?_=1',
          }}
          resizeMode="cover"
          style={{height: 215, width: ScreenWidth * 0.9, zIndex: -1}}
          controls={true}
          paused={false}
        />
      </View>`

Thanks :)

**Comment by Renato1478** [comment]
I followed @cobarx suggestion but I also had to set `resizeMode="cover"` in order for it to work properly :ok_hand:

**Comment by DevHamzaShahid** [comment]
Just copy it and paste 😁:
<View
              style={{
                borderRadius: 20,
                overflow: 'hidden',
                flex: 1,
                height: HP(60), // Adjust height based on your design
                width:'94%',
                alignSelf:'center',
                justifyContent:'center',
                backgroundColor:'red',
                marginBottom:20
              }}>
              <Video
                source={{
                  uri: 'https://videos.pexels.com/video-files/5752729/5752729-sd_640_360_30fps.mp4',
                }} // Add your video source here
                style={{flex:1} // Define styles for the video
                controls={true} // Enable video controls if needed
                resizeMode="contain" // Set resize mode (optional)
                onReadyForDisplay={() => {
                  console.log('on ready for display');
                }}
              />
            </View>
