### ISSUE TITLE
RCTVideoManager is returning nil for it's methodQueue, which is not permitted. You must either return a pre-initialized queue, or @synthesize the methodQueue to let the bridge create a queue for you.

### ISSUE THREAD

**Issue by PhilippKrone** [TheWidlarzGroup/react-native-video#69]
After upgrading to 0.7.0-rc.2, I get the following error:

RCTVideoManager is returning nil for it's methodQueue, which is not permitted. You must either return a pre-initialized queue, or @synthesize the methodQueue to let the bridge create a queue for you.

**Comment by yamill** [comment]
I had the same error. I switched back to 0.6.0 until this issue gets resolved :(

**Comment by brentvatne** [comment]
Fixed #77
