### ISSUE TITLE
Can't find React headers

### ISSUE THREAD

**Issue by tspecht** [TheWidlarzGroup/react-native-video#691]
Hey!

First of, thanks for the awesome component, looks great. I wanted to go ahead and use it but somehow I'm not able to get it to compile properly in my React Native application. I did all the steps needed to link (Drag into Libraries, add as Lib) as described in all the documentation but am still receiving the following error:

```
/node_modules/react-native-video/ios/RCTVideoManager.h:1:9: 'React/RCTViewManager.h' file not found
```

Looks like it can't find the React headers properly? I tried setting the HEADER_SEARCH_PATHS do various values but somehow it simply won't start working. If that is of any relevance, I have React installed using Cocoapods since I'm integration React Native into an existing application.

Thanks!

**Comment by cinder92** [comment]
@tspecht did you find a solution? im having same issue with rn 0.59.1 and plugin 4.4.0

**Comment by Fedeorlandau** [comment]
I'm experiencing the same thing. I'm trying to contribute to the iOS side of things and I get the same error
