### ISSUE TITLE
tvos - Issue seeking through video in fullscreen

### ISSUE THREAD

**Issue by maximmcnair** [TheWidlarzGroup/react-native-video#694]
Normally on tvos if you pause a video you can seek through it by swiping the tv controller and you'll see a thumbnail of the video at the time position your on. However react-native-video only allows you to swipe once (only around 4 minutes in an hour show).

![unnamed](https://user-images.githubusercontent.com/1009787/28121240-584aeb5a-6712-11e7-8ae1-8647b848d258.jpg)

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  View
} from 'react-native';
import Video from 'react-native-video'

export default class test extends Component {
  componentDidMount = () => {
    setTimeout(()=>{
      console.log('presentFullscreenPlayer')
      this.video.presentFullscreenPlayer()
    }, 5000)
  }

  render() {
    return (
      <View style={styles.container}>
        <Video
         ref={r => { this.video = r }}
         repeat={false}
         muted={true}
         source={{uri: 'https://content.jwplatform.com/manifests/vM7nH0Kl.m3u8'}}
         onEnd={() => { console.log('onEnd') }}
         onFullscreenPlayerDidDismiss={() => { console.log('onFullscreenPlayerDidDismiss') }}
         onProgress={(evt) => { console.log('onProgress', evt) }}
         style={{
          position: 'absolute',
          top: 100,
          left: 100,
          bottom: 100,
          right: 100,
         }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
});

AppRegistry.registerComponent('test', () => test);
```

**Comment by aditya27dev** [comment]
Hi @maximmcnair I am trying to run my app on tvos but getting below error. Also i am not getting RCTvideo-tvos. I want to know how did you implemented react-native-video for tvos. Can you please help me?

Apple Mach-O Linker Error of no such file or directory

![screen shot 2017-07-20 at 12 22 06 pm](https://user-images.githubusercontent.com/25629063/28405183-e5e85cc6-6d49-11e7-873a-2e1aee2b89ab.png)
