### ISSUE TITLE
Android: Video doesn't change

### ISSUE THREAD

**Issue by tspecht** [TheWidlarzGroup/react-native-video#696]
Hey!

First off: Awesome package, started using it on both Android & iOS, works really well out of the box!

One issue I found on Android though: Whenever I re-use the same component but just assign a different source the video doesn't change? I'm using the ExoPlayer variant. On iOS & with the normal (really laggy ...) version the video does change when I change the `source` prop but the ExoPlayer one stays the same ... Any idea?

**Comment by frankiewiczkamil** [comment]
Hi. take a look #666

**Comment by cobarx** [comment]
Fixed in newer releases
