### ISSUE TITLE
Android ExoPlayer Integration

### ISSUE THREAD

**Issue by iamronsuez** [TheWidlarzGroup/react-native-video#697]
Hi, i'm trying to integrate the android-exoplayer project and it throws me an error due duplicate modules for android support, is there a particular configuration at the build.gradle that i'm missing ? 

> FAILURE: Build failed with an exception.

> What went wrong:
> Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/graphics/BitmapCompat.class

> Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more >log output.

**Comment by AndrewJack** [comment]
Could you share an example project that reproduces this issue?

What version of react native are you using too?

**Comment by iamronsuez** [comment]
Hello, thanks for your response, here is the example [repo](https://github.com/iamronsuez/rn-video).

`react-native-cli: 2.0.1
react-native: 0.46.2
`

**Comment by iamronsuez** [comment]
i was having issues with dex so i added `multiDexEnabled true` at the android default conf, when I try to make the debug apk it throws me the error mentioned above.

**Comment by AndrewJack** [comment]
ExoPlayer uses a newer version of the support library than react native.

Forcing react native to use a newer version fixes it.

I'm using v25.3.1, it works with react native because there isn't currently any breaking api changes.

**Comment by iamronsuez** [comment]
many thanks!

**Comment by eyalcohen4** [comment]
still happening here in 2.0.0 

- react-native init <app> 
- npm install react-native-video
- react-native link react-native-video
- switch react-native-video package to react-native-video-exoplayer package in `settings.gradle` and `build.gradle`


     
```

    dependencies {
         compile project(':react-native-video-exoplayer')
         compile fileTree(dir: "libs", include: ["*.jar"])
         compile "com.android.support:appcompat-v7:23.0.1"
        compile "com.facebook.react:react-native:+"  // From node_modules
    }
```

```
    include ':react-native-video-exoplayer'
    project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, 
    '../node_modules/react-native-video/android-exoplayer')
```

**Comment by vbnospace** [comment]
Its crashing the app
