### ISSUE TITLE
[Android] Seek Method Not Working

### ISSUE THREAD

**Issue by zachrnolan** [TheWidlarzGroup/react-native-video#698]
The seek method is not working on Android. I'm using a Slider to change the position of the video. 

```
<View style={ styles.container }>
  <View style={ styles.videoContainer }>
    <Video
      source={{uri: this.props.videoUri}}
      ref={ ref => this.player = ref } // eslint-disable-line
      rate={1.0}
      volume={1.0}
      muted={false}
      paused={true}
      resizeMode="cover"
      style={ styles.video } />
  </View>
  <View style={ styles.sliderContainer }>
    <Slider
      value={ position }
      minimumValue={ 0 }
      maximumValue={ duration }
      step={ 1 }
      onValueChange={ this.seekVideo } />
    <PrimaryButton
      text='Use This Image'
      action={ this.setCoverPhoto }
      buttonStyle={ styles.setCoverPhotoBtn } />
  </View>
</View>
```

```
seekVideo(position) {
  this.player.seek(position)
}
```

seekVideo is being called and is receiving a number (in seconds). This code works great on iOS, but fails to seek the video on Android.

The video file being generated by my Android Galaxy S7 is .mp4, not sure if that makes any difference. We are using ExoPlayer as well.

RN 0.45.1

**Comment by mrtaikandi** [comment]
I'm having the same problem. Did you find any workarounds?

**Comment by recepkocur** [comment]
+1

ios is worked. android is not worked.

**Comment by k-gregor** [comment]
EDIT: for me the problem was actually depending on the video file. It happened only for certain compressed files (with android mediacodec to be exact).

If you have this issue, try to use a different video. For example http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by cobarx** [comment]
@zachrnolan Guessing that @skatego is correct. We've just updated to a fairly recent version of ExoPlayer, so there's a chance that fixes the issue. 

If you're still having the problem, please post a link to the affected video. Chances are it's an issue with ExoPlayer and you'll need to file and issue with them.

**Comment by grifotv** [comment]
@skatego would you be able to tell how to properly export videos for Android? thanks!

**Comment by k-gregor** [comment]
@grifotv Still having this problem sometimes, mostly on short videos. I don't have a solution for you unfortunately.

**Comment by chinthakarupasinghe** [comment]
seekVideo(position) {
setTimeout(() => {
  this.player.seek(position);
  }, 10);
}

**Comment by zackfly** [comment]
as this comment says https://github.com/google/ExoPlayer/issues/10587#issuecomment-1238246943
if ur using  a compressed video.  seek will be slow.

**Comment by zackfly** [comment]
as this comment says https://github.com/google/ExoPlayer/issues/10587#issuecomment-1238246943
if ur using a compressed video. seek will be slow.
![image](https://github.com/react-native-video/react-native-video/assets/5593858/b6aca5cc-e203-4405-836e-0fffd1d40d7c)
in my code it stucks if  i loop ervery 0.5s even under 2s

so .i simply  increase the key frame. it will increase space but its really fast.


ffmpeg -i input1.mp4 -c:v libx264 -x264opts keyint=1 -g 1 output.mp4
this command will decode the video and turn every frame to key frame
