### ISSUE TITLE
Get EXT-X-PROGRAM-DATE-TIME

### ISSUE THREAD

**Issue by RWOverdijk** [TheWidlarzGroup/react-native-video#699]
I'm wondering how I can get the EXT-X-PROGRAM-DATE-TIME every time it changes. Is there an event for this? If not, can I help add it?

**Comment by MDrooker** [comment]
Did you end up getting this worked out?

**Comment by cobarx** [comment]
@RWOverdijk PRs to add new functionality are always welcome.

**Comment by RWOverdijk** [comment]
A bit late. I already forked.
