### ISSUE TITLE
Load videos remotely from the network

### ISSUE THREAD

**Issue by brianchirls** [TheWidlarzGroup/react-native-video#7]
Right now, this component only works with local videos. AVPlayer works either way; you just have to change how you create the `NSURL`. Something like this:

``` Objective-C
- (void)setSrc:(NSString *)source
{
  // ...
  _videoURL = [[NSURL alloc] initWithString:source];
  // ...
```

I think you'd want to do parse the incoming `source` string and decide whether to look in the `mainBundle`. I can try to take a stab at it myself if I have some time later, unless you have a preference as to how this would work.

**Comment by brianchirls** [comment]
As an alternative, consider defining the source as an object, to match [how `Image` works](http://facebook.github.io/react-native/docs/image.html#source-being-an-object).

**Comment by brentvatne** [comment]
@brianchirls - absolutely would love to do this, just haven't had the time yet - feel free to take a stab at it!

**Comment by brianchirls** [comment]
@brentvatne In response to your comment in #8 about adding `onLoadStart`, it might be worth taking a look at the states and events fired by the HTML video element. They're pretty good about covering a lot of cases. For example, now you have `onProgress`, which appears to fire when the video progresses. HTML has `progress` for reporting when new chunks for data are buffered from the network and `timeupdate` for when the video `currentTime` changes, whether by playing or seeking, forward or backward. It makes sense because the play head can go forward or backward, whereas buffering typically only makes "progress" and does not get undone.

**Comment by johanneslumpe** [comment]
#9 addresses this - it's a work in progress though.

**Comment by brentvatne** [comment]
@brianchirls - looks like this is resolved now, let's take the discussion of how to best handle progress events to #10!
