### ISSUE TITLE
Video Got This: [js] 'types' can only be used in a .ts file.

### ISSUE THREAD

**Issue by saeedhei** [TheWidlarzGroup/react-native-video#700]
When I opened your Example Project I Got This:
![untitled](https://user-images.githubusercontent.com/25050762/28291052-19a00674-6b5e-11e7-8860-9d4f2986ddd9.jpg)
How Can I Solve That?

**Comment by freeboub** [comment]
This issue is still valid, I will try to update sample

**Comment by hueniverse** [comment]
Type issues should go away once we move the code to TS.
