### ISSUE TITLE
React native video not working

### ISSUE THREAD

**Issue by weiqing-nic** [TheWidlarzGroup/react-native-video#701]
Hi all,

I want to have a video gallery. when I swipe it, the next video will play and the previous video will pause. But when I swipe it, both the video will still keep playing.. please help me!!

The video will keep running and it won't stop. I used react native swiper and react native video library.

thank you

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import Swiper from 'react-native-swiper';
import Video from 'react-native-video';

var styles = StyleSheet.create({
  wrapper: {
  },
  slide1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9DD6EB',
  },
  slide2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#97CAE5',
  },
  slide3: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#92BBD9',
  },
  text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },
  fullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0
  }
})

var swiper = React.createClass({
  render: function() {
    return (
      <Swiper style={styles.wrapper} showsButtons={true}>
        <Video
          source={require('./background.mp4')}
          rate={1.0}
          volume={1.0}
          paused={false}
          muted={false}
          resizeMode={"cover"}
          repeat={true}
          playInBackground={false}
          style={styles.fullScreen}
        />
        <Video
          source={require('./background2.mp4')}
          rate={1.0}
          volume={1.0}
          paused={false}
          muted={false}
          resizeMode={"cover"}
          repeat={true}
          playInBackground={false}
          style={styles.fullScreen}
        />

        <View style={styles.slide2}>
          <Text style={styles.text}>Beautiful</Text>
        </View>
        <View style={styles.slide3}>
          <Text style={styles.text}>And simple</Text>
        </View>
      </Swiper>
    )
  }
})

AppRegistry.registerComponent('dragonswipe', () => swiper);

**Comment by jasnig** [comment]
in fact, this is not react-native-video's problem. you need to know more about react-native.

**Comment by asgvard** [comment]
You have to modify "paused" property when swiping to next video. It's not this library issue.
