### ISSUE TITLE
controls in android-exoplayer

### ISSUE THREAD

**Issue by frankiewiczkamil** [TheWidlarzGroup/react-native-video#702]
Hi,
I can't find any way for using exoplayer's native controls ([like this](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a))  with react-native-video (android-exoplayer). 
Is there any feature request for that already?

**Comment by duanyachao** [comment]
@frankiewiczkamil  HI  Did you find the exoplayer‘s native controls   can you help me ?

**Comment by frankiewiczkamil** [comment]
@duanyachao I know that exoplayer has some controls support, and one can use it in native android [like in this link](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a). 
However it seems that there is no support for that in react-natvie-video yet, and I am asking if somebody is going to do that.

**Comment by duanyachao** [comment]
@frankiewiczkamil  There is no controls when i use exoplayer , please tell  where to setting the controls

**Comment by brinkkemper** [comment]
It's been a while, anyone found a solution?

**Comment by frankiewiczkamil** [comment]
@brinkkemper I use react-native-video-controls as temp solution
