### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by aditya27dev** [TheWidlarzGroup/react-native-video#703]
Hello,

I am trying to run my react-native app with react-native-video in apple simulator. But i am getting an error. Please check below image and let me know how can i fix this.

Any help will be appreciated.
Thanks

![screen shot 2017-07-20 at 12 22 06 pm](https://user-images.githubusercontent.com/25629063/28404962-01d5fb60-6d49-11e7-87f7-0b1bd5dc4389.png)

![screen shot 2017-07-20 at 12 44 11 pm](https://user-images.githubusercontent.com/25629063/28405017-318b8d98-6d49-11e7-8887-f937d7a866a2.png)

![screen shot 2017-07-20 at 12 44 23 pm](https://user-images.githubusercontent.com/25629063/28405031-40259722-6d49-11e7-921c-9f447371ac9b.png)

**Comment by cobarx** [comment]
If you're still having this issue, I would try:
`react-native unlink react-native-video`
`react-native link react-native-video`
