### ISSUE TITLE
Working only on simulator

### ISSUE THREAD

**Issue by Jaafar-abusair** [TheWidlarzGroup/react-native-video#704]
Hi guys,

It's working only on simulator but it's not working on real device, xiaomi M5

<Video
            repeat
            resizeMode='cover'
            source={require('../../assets/video/intro.mp4')}
            style={styles.backgroundVideo}
          />

**Comment by supermanxiacheng** [comment]
same problem , on real device ,  MX3(Meizu,China),hongmi 4(xiaomi)

**Comment by supermanxiacheng** [comment]
#560

**Comment by supermanxiacheng** [comment]
#506      fix this problem
