### ISSUE TITLE
onTimedMetaData For Android

### ISSUE THREAD

**Issue by raihanabbas232** [TheWidlarzGroup/react-native-video#705]
As far as I am concerned there is no functionality provided to get metadata for streaming specifically for Android. Can anyone guide me or provide some direction how can I implement  that at my own in a react native android app.

**Comment by RWOverdijk** [comment]
:+1: I just now tried this and I'm not getting the onTimedMetadata either. There's the exoplayer which supposedly does support it, but then you lose the `playInBackground` feature which I also really need.

If this requires me to do some work, I'm fine with it. I'd like to get these two features working on both iOS and Android

**Comment by raihanabbas232** [comment]
@RWOverdijk that would be very helpful... I have searched on that and analyzed that firstly we need to implement `MediaPlayer.OnTimedMetaDataAvailableListener` but I am exactly not sure how this method `void onTimedMetaDataAvailable (MediaPlayer mp,  TimedMetaData data)` is gonna work....I have to search about it... :)

**Comment by RWOverdijk** [comment]
@raihanabbas232 I implemented it already. https://github.com/react-native-community/react-native-video/pull/707

I've forked this module and will publish it soon, including some other fixes.

**Comment by raihanabbas232** [comment]
@RWOverdijk appreciated... :)

**Comment by RWOverdijk** [comment]
@raihanabbas232 Sorry for the delay, if you want you can just install from my branch to see if it works for you. There are no tests for this currently so I think having more eyes on it is a good idea :)

If you're in the infinite red community, hit me up there :) If not, join us: https://infiniteredcommunity.herokuapp.com/

It's a bunch of clever people and a good place to get general help with react native.

**Comment by airman00** [comment]
For me the solution was simple

I just needed to modify the selectTimedMetadataTrack function in ReactVideoView.java as follows:

```
  // Select track (so we can use it to listen to timed meta data updates)
    private void selectTimedMetadataTrack(MediaPlayer mp) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            return;
        }
        try { // It's possible this could throw an exception if the framework doesn't support getting track info
            mp.selectTrack(0);  // <--- add this 
            
            /*  // Comment out this
            MediaPlayer.TrackInfo[] trackInfo = mp.getTrackInfo();
            for (int i = 0; i < trackInfo.length; ++i) {
                if (trackInfo[i].getTrackType() == MediaPlayer.TrackInfo.MEDIA_TRACK_TYPE_TIMEDTEXT) {
                    mp.selectTrack(i);
                    break;
                }
            }*/
            
        } catch (Exception e) {
        }
    }
```
