### ISSUE TITLE
playInBackground attribute doesn't work in ios

### ISSUE THREAD

**Issue by lirui0407** [TheWidlarzGroup/react-native-video#706]
Problem description:

Attribute _playInBackground_ in Android platform, official emulator, works well: if video is playing, video would not play anymore as long as I tapped home button(Identified by the fact that audio and  video always paused simultaneously, we can hear the state by sound).

However, in ios platform, official emulator, when I tapped home button cmd+shift+h made my rn app  backgrounded while video was playing, the video do paused but only last for about 3 seconds, later the video continues playing in background (Identified by sound, too).

Had never tested this problem in a real phone yet, but I think it's no matter with hardware.

Please test and confirm this problem. Thanks, everyone.

**Comment by RWOverdijk** [comment]
@lirui0407 Using HLS by any chance?

**Comment by danfair** [comment]
@RWOverdijk i'm having this issue as well, and yes it is HLS audio

**Comment by RWOverdijk** [comment]
It's working for me, but it sometimes doesn't recover the video feed when waking up the app again. It shows inconsistent behavior. I'll look into this once I need it.

**Comment by rfw** [comment]
+1

**Comment by 29hsaeed** [comment]
Not working for me in Android as well
