### ISSUE TITLE
Video only plays for 1 second 

### ISSUE THREAD

**Issue by ryan-turnbull** [TheWidlarzGroup/react-native-video#708]
Hi all, so i have the following code

`<Video source={video}                                       `
                  `       ref={(ref) => {                             `
                   `       this.player = ref                          `
                   `     }}                                                    `
                   `      rate={0.1}                                     `
                   `      volume={1.0}                               `
                   `      muted={false}                              `
                   `       paused={true}                             `
                  `        resizeMode="cover"                   `
                   `       style = {{flex: 1}}/>                      `

And the video is called in a touchableOpacity component's onpress method, with invokes the two functions `this.player.presentFullscreenPlayer();
    this.player.seek(0);`

And when i play the video, it plays for 1 second and then stops. the music continues to play, but the video image does not change at all. 

However, whenever i used the slider to seek ( pan ) to a new part of the video, the video will again play 1 second from the new position and then freeze, with the audio acting completely as expected.

I've made the video in iMovie and exported it to an mp4. I thought that lowering the quality of the video would help but the issue still exists.

Any help would be much appreciated, seems to be such a weird issue

**Comment by JasonIdris** [comment]
```paused={true}``` , maybe?

**Comment by arvinsingla** [comment]
Is this a build for iOS/tvOS? If so have you tried running it on a real device? I was having similar symptoms when running on the simulator. But when I tried on a real device it worked as expected.

**Comment by vzaffalon** [comment]
same problem here no solution

**Comment by aengl** [comment]
Same problem on iOS, but only seems to be an issue in the simulator. Works as expected on a real device. Would still be nice to have this resolved.

**Comment by aengl** [comment]
There seem to be some more things that don't work in the simulator:
* Dismounting a video component and remounting another (when in fullscreen mode)
* Dismissing the fullscreen player when it reaches the end
* Reloading the app while the fullscreen player is running
