### ISSUE TITLE
Errors with Live HLS Stream on iOS Only

### ISSUE THREAD

**Issue by areeb111** [TheWidlarzGroup/react-native-video#709]
Hello I am using react-native-video on iOS,
I have tried to play a live stream getting out from Wowza Streaming Engine (Which is one of the best in the world).
The video is being played perfectly in the background but i got too many errors with 
```
folly::toJson: JSON object value was a NaN or INF
2017-07-29 16:14:24.925 [fatal][tid:com.facebook.react.JavaScript] Error calling RCTEventEmitter.receiveEvent
```

**Video codec is : H264 , Audio: AAC
Xcode: 8.3.3
iOS 10.3 - iPhone 6**

Also i have tried to init a new project and installed "react-native-video" with a fresh project and i got the same issue.

Please is there any solution ?

**Comment by n4kz** [comment]
I'm experiencing the same issue. Found that seekable time range can contain invalid duration. Will submit PR with fix later.

**Comment by luco** [comment]
+1 on this

**Comment by grylance** [comment]
With your fix @n4kz the error still happens for us on app reopen whilst a player is rendered. If `playInBackground === true` the error doesn't happen provided the component is not paused, If the player is paused when the app is backgrounded on reopen it will crash.

This happens consistently on devices however we are completely unable to reproduce in the emulator.

**Comment by grylance** [comment]
Downgrading from RN 0.47 to 0.44 fixed this for us.

**Comment by indiejoseph** [comment]
I still got the error message 'JSON object value was a NaN or INF' with this latest fix, any idea? thanks

```
<Critical>: Error calling RCTEventEmitter.receiveEvent
	
	folly::toJson: JSON object value was a NaN or INF
```

**Comment by indiejoseph** [comment]
That works fine with non-live video m3u8, but crashed with live streaming m3u8

**Comment by wsupajirakit** [comment]
how can I fix it   "Error calling RCTEventEmitter.receiveEvent folly::tojson: JSON. object value was n NaN or INF"

  "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-video": "^2.0.0",

**Comment by arthuryeti** [comment]
@n4kz I'm still experimenting this issue. Any idea how to solve this?

**Comment by Obooman** [comment]
react-native@0.53, same issue with react-native-camera@2.0.0, the app will crash with this error.how can I fix it or evade this?
