### ISSUE TITLE
useNativeDriver for onProgress event

### ISSUE THREAD

**Issue by nerdmed** [TheWidlarzGroup/react-native-video#711]
Dear Team, we are having enormous performance issues with the onProgress event on older devices like the iPad 2 or iPad Mini. Sending the progress over the JS/Native bridge to display it on a specific view is very slow and makes the app not usable! It is possible to map the event via Animated.Event like this:

```js
const animatedProgress = new Animated.Value(0);
<Video
  onProgress={Animated.event([{ currentTime: animatedProgress }], { useNativeDriver: false })}
/>
```

You can check if the events are working before connecting it to a view with:

```js
progress.addListener((e) => {
    console.log('NATIVE PROGRESS', e);
});
```

If you enable useNativeDriver this will not work. Does any of you guys has an idea how to achieve this or does know any package that enables useNativeDriver for a custom view ? @jameshartt @ brentvatne @isair ? Thanks!

**Comment by nerdmed** [comment]
@jameshartt @isair  I have created an example repo to play with:

https://github.com/nerdmed/nativeVideoProgress/

It includes the package a checkout to play with it easily. So ist just clone, yarn and run! 
Maybe anyone is also interested in finding a solution 👍

**Comment by nerdmed** [comment]
This is currently not possible. Tracking the following PR to allow the described behaviour: https://github.com/facebook/react-native/pull/15611

**Comment by RustyDev** [comment]
Any update on this? A PR in that issue was merged.

**Comment by nerdmed** [comment]
@RustyDev Thanks for writing. From what i can see i can confirm that the react-native team finally merged the change after 3 years. I think it is worth looking into the status quo of this package and see if we can integrate now natively. Do you have capacities to support with this @RustyDev ?
