### ISSUE TITLE
Taking screenshot of source

### ISSUE THREAD

**Issue by onehassan** [TheWidlarzGroup/react-native-video#712]
I've tried to take screenshot of video using react-native-view-shot but the screenshot is blank, Is there a way to save a screenshot of the source video? any lead or help is very appreciated

**Comment by evanjmg** [comment]
+1 - anyone solve this yet? I need to blur a freezed video

**Comment by evanjmg** [comment]
Nvm react-native-blur supports all videos with a frozen video :)
