### ISSUE TITLE
1.1.0 tags and 1.2.0 tags and commits missing

### ISSUE THREAD

**Issue by edmundito** [TheWidlarzGroup/react-native-video#714]
Hello, I noticed that the latest version is 1.2.0 which was released a few hours ago, but when I look in this repo I do not see tags nor commits for it nor a tag for 1.1.0. Would it be possible to push these changes to the repo? Thanks!

**Comment by piuccio** [comment]
would be nice to have version `2.0.0` as well including the changelog

**Comment by tirrorex** [comment]
Agree, especially since 2.0.0 is listed on npm, which it shouldn't since 2.0.0 has no release tag thus cannot be installed
