### ISSUE TITLE
Android HLS stream regression in 1.2.0, error code -1004

### ISSUE THREAD

**Issue by chrisshiplet** [TheWidlarzGroup/react-native-video#716]
I will update this issue with more information as I dig into this, but it seems the update from 1.0.0 to 1.2.0 broke our HLS streaming on Android. iOS seems to work fine. The error code I saw in the Android system logs was -1004, which is apparently "MEDIA_ERROR_UNKNOWN"...

Edit 1: Tracked it down to this commit: https://github.com/react-native-community/react-native-video/commit/9ce1f4b5f41c1d9901f25ab180692a93d478c8df

/cc @gorjanz @mattapperson any insight on this change?

**Comment by danfair** [comment]
@chrisshiplet i am streaming HLS audio, it starts for exactly 10 seconds, then cuts out. Is that the issue you were having? Can't find anything in my code that would cause that on Android only. Thanks!

**Comment by KingAmo** [comment]
any update ?

**Comment by kotoyama** [comment]
Any updates?

**Comment by codal-mpawar** [comment]
Any updates?
