### ISSUE TITLE
controls in Android 

### ISSUE THREAD

**Issue by duanyachao** [TheWidlarzGroup/react-native-video#719]
there has  controls for video  in react-native-video ,but  none  in react-native-video-exoplayer ,how can i use the controls in react-native-video-exoplayer, i  compile  react-native-video & react-native-video-exoplayer in bulid.gradle for  dependencies, but when react-native run-android  it show error  like this "more than one library with package name 'com.brentvatne.react'".  so  someone  can help me ？ Thanks

**Comment by C0deWithAj** [comment]
Have you tried using [React Native Video controls](https://github.com/itsnubix/react-native-video-controls) , built specifically for React-native-video

**Comment by duanyachao** [comment]
@Ajmalajji  thank you it's works   but  the fullscreen function just change the resizeMode not fullscreen.

**Comment by yogeshmoradiya121** [comment]
@Ajmalajji seek bar not showing in react native video controls

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.
