### ISSUE TITLE
Unable to ref Video component

### ISSUE THREAD

**Issue by holoed** [TheWidlarzGroup/react-native-video#72]
I tried to ref the video component in order to call seek(), but the object never becomes available on the this.refs object (is always undefined).

I also tried the ref callback but is never called.

Could you provide an example using seek() through a ref on the Video component ?

**Comment by casio** [comment]
Seeing the same issue - react-native 0.6.0, react-native-video 0.4.9

Also when assigning a ref on a video component, react will repeatetly warn

```
[tid:com.facebook.React.JavaScript] "Warning: You are calling cloneWithProps() on a child with a ref. This is dangerous because you're creating a new child which will not be added as a ref to its parent."
```

**Comment by brentvatne** [comment]
Hmm okay I'll look into this

**Comment by casio** [comment]
Fyi this one seems fixed - working as expected in `0.5.1` (using react-native 0.9.0)

**Comment by af** [comment]
I've also been pointing a ref to a video component and seeking, without any issues. Is anyone still experiencing this?

**Comment by isair** [comment]
Closing as it seems to be fixed. @holoed let me know if you're still experiencing this problem and I'll reopen it.

**Comment by skleest** [comment]
@isair 
I'm having the same problem, cannot get refs to work (always undefined). Any suggestions?
"react-native-video": "^0.7.1",
RN 0.22
both iOS/Android
