### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by mike-aungsan** [TheWidlarzGroup/react-native-video#722]
...\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoP
ackage.java:21: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: ...\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\React
VideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

"react": "16.0.0-alpha.12",
"react-native": "0.46.4",

    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.xxx"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

**Comment by iamsee** [comment]
same

**Comment by Senasiko** [comment]
Please see the pull request [#718](https://github.com/react-native-community/react-native-video/pull/718/commits/10ea980d649876818b96ad37813e6a4a92c20cf5)

**Comment by cobarx** [comment]
The fix for this has been merged and is in at least version 2.1.1.
