### ISSUE TITLE
presentFullscreenPlayer doesn't work on Android

### ISSUE THREAD

**Issue by RyanMitchellWilson** [TheWidlarzGroup/react-native-video#726]
I'm trying to use the `presentFullscreenPlayer` method to play my video. This works perfectly in iOS but it doesn't seem to do anything on the Android side. Here is my basic implementation:
```
return (
  <View style={{flex: 1}}>
    <TouchableOpacity
      onPress={() => {
        console.log('Open Full Screen Video', this.player)
        this.player.presentFullscreenPlayer()
      }}
      style={{backgroundColor: 'blue', height: 40, width: 60}}/>
    <Video
      rate={0}
      ref={ref => this.player = ref}
      source={{uri: 'https://results.chronotrack.com/mobile/results/video-clip/id/12321/start/1671/duration/20/name/2016JuneJerika.mp4'}}/>
  </View>
)
```

I can see the console log when running Android but nothing else happens. I can even see in the Video object I'm printing (`this.player`) has the `presentFullscreenPlayer` method on the object.

**Comment by frankiewiczkamil** [comment]
@RyanMitchellWilson  It's discussed in #534

**Comment by cobarx** [comment]
Closed since this is a dupe.
