### ISSUE TITLE
react-native run-android：Compile failed with 0.47

### ISSUE THREAD

**Issue by tangbrrr** [TheWidlarzGroup/react-native-video#727]
Breaking changes

Android

Remove unused createJSModules calls (ce6fb33, 53d5504) - @javache
iOS

Fix font weight resolution (cfeaefb) - @kipricker

**Comment by hellogerard** [comment]
This is fixed by #718 (merged, but not released at this time).

**Comment by arribbar** [comment]
When do you think we can get a release ? :(
@mattapperson, can you make a quick release ?

**Comment by asgvard** [comment]
@mattapperson Yes please, could you publish new version with the latest fixes? There are a lot actually, new prop-types usage, createJSModules fix, removed rn-windows. Would be really nice to have new version with these, thanks!

**Comment by mattapperson** [comment]
@asgvard I dont do releases over the weekends in case things go badly, but will push a release on Monday

**Comment by asgvard** [comment]
Thanks, looking forward :)

**Comment by avers2000** [comment]
@mattapperson, any news?
