### ISSUE TITLE
Initial paused state has no effect

### ISSUE THREAD

**Issue by casio** [TheWidlarzGroup/react-native-video#73]
Setting the `paused` prop to true doesnt have the expected effect.
Instead the video starts playing whatsoever.

**Comment by gazzer82** [comment]
i'm seeing the same issue, any ideas on a fix?

**Comment by brentvatne** [comment]
Not ideal! I wonder what caused this regression. PR with a fix very welcome! :smile:

**Comment by isair** [comment]
Weird, seems like setPaused is called with `false` as its parameter after it is called with `true`.

**Comment by isair** [comment]
Debugged it. The problems is caused by `setRate` being called on `_player` after `[_player pause]` is called.
