### ISSUE TITLE
IOS calling presentFullscreenPlayer in modal crashes app with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by RyanMitchellWilson** [TheWidlarzGroup/react-native-video#732]
Just installed the latest version 1.2 to my app and every time I call `presentFullscreenPlayer` it crashes the app and xcode throws the error:
`Thread 1: EXC_BAD_ACCESS (code=2, address=0x7fff58b60ff8)`

Looks like it's happening in the RCTVideo.m file
<img width="883" alt="screen shot 2017-08-10 at 12 05 37 pm" src="https://user-images.githubusercontent.com/11371200/29184687-4366b868-7dc4-11e7-9eac-a93cfb0ee3b4.png">

This also happens with react-native-video 1.0

Has anyone else run into this or know how to fix it?

Using:
react-native: 0.44
react: 16.0.0-alpha.6

UPDATE: This is causes by calling calling `presentFullscreenPlayer` from a modal. Example below

**Comment by RyanMitchellWilson** [comment]
Ok I'm pretty sure I figured out what causes this, it is the fact that I am trying to call `presentFullscreenPlayer` from a modal. If you are trying to open the fullscreen player while currently in a modal it will cause the app to crash.

Working Example: 
```
<View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
  <Text>{'Test App'}</Text>
  <TouchableOpacity
    onPress={() => this.video && this.video.presentFullscreenPlayer()}
    style={{backgroundColor: 'red', height: 50, width: 100}}/>
  <Video
    rate={0}
    ref={ref => this.video = ref}
    source={{uri: 'https://results.chronotrack.com/mobile/results/video-clip/id/12321/start/1671/duration/20/name/2016JuneJerika.mp4'}}/>
</View>
```

None-working Example:
```
<Modal
  animationType={'slide'}
  transparent={true}
  visible={true}>
  <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
    <Text>{'Test App'}</Text>
    <TouchableOpacity
      onPress={() => this.video && this.video.presentFullscreenPlayer()}
      style={{backgroundColor: 'red', height: 50, width: 100}}/>
    <Video
      rate={0}
      ref={ref => this.video = ref}
      source={{uri: 'https://results.chronotrack.com/mobile/results/video-clip/id/12321/start/1671/duration/20/name/2016JuneJerika.mp4'}}/>
  </View>
</Modal>
```

**Comment by gitlovenotwar** [comment]
Any fix for this? Playing in modal really crashes in full screen.

**Comment by syardumi** [comment]
+1 Same. Any ideas on a fix?

**Comment by RyanMitchellWilson** [comment]
I went ahead and changed my modal to be an actual page that I navigate to since it was just a media gallery but that is only temporary until I can write my own full screen video player. presentFullscreenPlayer only works in iOS as well so it might be worth it just to spend some time rolling your own FullscreenPlayer which will work on both platforms.

Although a real fix would be greatly appreciated.

**Comment by Tonyangl** [comment]
+1 Same.......... @syardumi ...   I use [this](https://github.com/sundayhd/react-native-display)  to replace 'Modal' 。。。

**Comment by pintocarlos** [comment]
+1

**Comment by natioskar** [comment]
+1

**Comment by BenBrostoff** [comment]
I'm seeing this issue still exists using `react-native-modal` and Expo's `Video` component. Full screen opens fine, but it's behind the modal. Closing the modal and then closing full screen causes the app to crash, presumably because there's some reference to the video ref in the modal.

**Comment by mitevdev** [comment]
The exact same issue here. The App crashes on this line when calling presentFullscreenPlayer from within a modal.

UPDATE: Just enabled controls on video element enabling the user to play and switch to fullScreenMode by itself solved the problem.

**Comment by DavitVosk** [comment]
Any success? I am still getting problem when calling `presentFullscreenPlayer` in modal...
