### ISSUE TITLE
Image resizeMode 'cover',it's default crop the top of pic while the height of pic higher than Image height.how can i crop bottom,  

### ISSUE THREAD

**Issue by LeeZC** [TheWidlarzGroup/react-native-video#735]
in my case, i want it crop the bottom of pic while pic height higher than Image height. does somebody same to me  ?

**Comment by cobarx** [comment]
Version 2.1.1 now allows you to specify the resizeMode for the poster. I believe posterResizeMode="cover" will do what you're asking for.

**Comment by fabriziobertoglio1987** [comment]
@cobarx postResizeMode seems to not fix this issue on android with version 5
