### ISSUE TITLE
[ANDROID] Exoplayer view + transform rotate does not work

### ISSUE THREAD

**Issue by asgvard** [TheWidlarzGroup/react-native-video#736]
Hi,

My goal is to rotate the video 90deg to display it in fullscreen, w/o flipping the device (the app is locked to Portrait). I'm trying to achieve this by using transform rotate on a Video parent. In result the Video "box" is rotated correctly, but the video surface itself still stays in the initial degree (which makes Big Buck Bunny not happy and confused as you can see on a screenshot).
Please note that I'm not trying to use native fullscreen mode, I'm just trying to rotate the Video box itself with transformation.

![screenshot_20170814-131159](https://user-images.githubusercontent.com/2877657/29269653-e3e8a48c-80f2-11e7-9165-67c73e005fe3.png)

The code is just a new react-native project with Video:

```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  View
} from 'react-native';
import Video from 'react-native-video';

export default class videoRotateTest extends Component {
  render() {
    return (
      <View style={[styles.container, {
          transform: [{
            rotate: '40deg'
          }]
        }]}>
        <Video
        style={styles.container}
        paused={false}
        resizeMode={'contain'}
        source={{uri: 'http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8'}}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0
  }
});

AppRegistry.registerComponent('videoRotateTest', () => videoRotateTest);
```

RN: 0.47
react-native-video: latest from master branch

Exactly the same thing works fine on iOS and the video is rotated. Seems like transformation props are not propagated to SurfaceView? I'm not an Android dev so can't say exactly.
I've also tried to use `rotation` prop of Video component itself, but it doesn't work either and it cannot be animated with useNativeDriver Animation anyway, so it's not an option.

@AndrewJack Seems like you've done initial Exoplayer integration, maybe you could share any suggestion about why it's happening? Would appreciate any help, thanks :)

**Comment by asgvard** [comment]
Small update, this works fine with TextureView, I just set the flag `useTextureView` to true [here](https://github.com/asgvard/react-native-video/commit/f9a2915946aa0fd1d05df47351a9a476d45b9e30).
So seems the problem is specifically with SurfaceView. Does it have any obvious advantages compared to TextureView?

**Comment by AndrewJack** [comment]
https://source.android.com/devices/graphics/arch-tv#surface_or_texture Might be useful to you.

TextureView allows scaling and transforming whereas SurfaceView does not.

Generally it is better to use SurfaceView as it offers better performance.

Personally I'd just lock/unlock the orientation change when you want to allow and disallow it.
A library like https://github.com/yamill/react-native-orientation would help with this.

**Comment by asgvard** [comment]
@AndrewJack Thanks, so basically SurfaceView does not allow any transformations, clear now. Then I guess this Bug might be closed

**Comment by rohit9625** [comment]
Using `useTextureView={true}` doesn't solve the problem for version `6.16.1`

**Comment by zohayk** [comment]
The solution is here!

https://github.com/TheWidlarzGroup/react-native-video/issues/4730#issuecomment-3615075092
