### ISSUE TITLE
Failing to import Video due to failing import of PropTypes from react module.

### ISSUE THREAD

**Issue by pintocarlos** [TheWidlarzGroup/react-native-video#738]
This is happening because as of React V15.5 `PropTypes` does not live within the react npm module. It lives in prop-types npm module. 
In Video.js, you will see the following which is failing:

```
line 1: import React, {Component, PropTypes} from 'react';
```

Which should be updated to...
```
line 1: import React, {Component} from 'react';
line 2: import PropTypes from 'prop-types';
```
And of course include `prop-types` as a dependency in the package.json file.

Can we get this updated? Thanks!

![screen shot 2017-08-14 at 4 11 13 pm](https://user-images.githubusercontent.com/1060904/29289632-389778ba-810b-11e7-9d85-ca24737b5984.png)

**Comment by pintocarlos** [comment]
I see that this was fixed on PR #677  however it is still not published to npm.
I just downloaded clean the published version 1.2.0 and it does not contain this fix.

When can this be published? Thanks!

**Comment by vinagrito** [comment]
@mattapperson any idea who can update the package with the master version?

**Comment by mattapperson** [comment]
I can and will hopefully tomorrow. Sorry, just been swamped.

**Comment by cobarx** [comment]
Version 2.1.0 has been published.
