### ISSUE TITLE
Suggestion: event listener for route change

### ISSUE THREAD

**Issue by yamill** [TheWidlarzGroup/react-native-video#74]
I think it would be great if there was an event listener for route change.

For example one issue I'm facing right now is that when I switch to a new route with the Navigator component. I have no way to pause any videos that are autoplaying.

**Comment by jaysalvat** [comment]
Hello!
Same problem here.
Video is running after route changed. Impossible to stop it.

**EDIT**

I fixed my problem with setting some video's states in the function that pushes the route.

``` javascrip
    goBack: function () {
        this.setState({
            volume: 0,
            paused: true,
        });

        this.props.navigator.push({
            title: 'Movies',
            component:  require('./details'),
        });
    },
```

**Comment by brentvatne** [comment]
Hey folks,

Pretty low bandwidth at the moment, working on a lot of things, if anyone has some spare time to throw at solving this problem a PR would be very welcome!

**Comment by yamill** [comment]
I was able to resolve this issue using the 'willfocus' event from the [Navigator].

I posted a gist for anyone interested.

https://gist.github.com/yamill/9ff0fe84e5b820cf80eb#file-video-scene-component-L7-L14

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by goldylucks** [comment]
I would like to b able to listen to route changes

**Comment by zchwyng** [comment]
Closing this since it's outdated.
