### ISSUE TITLE
Can't Checkout And Install App With Node v8.0

### ISSUE THREAD

**Issue by johndanek** [TheWidlarzGroup/react-native-video#740]
I cloned the project, and attempted an `npm install` while making no changes to the code. I was unable to do so with node v8.3.0. This was due to 

```
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
```

is anyone else able to `git clone`, then `npm install` with Node 8.3.0?

**Comment by n1ru4l** [comment]
This is caused because of the `jest-cli` dependency. After removing it, I do no longer experience this issue. Also it seems like it is not used anyway.
