### ISSUE TITLE
presentFullscreenPlayer should start playing video automatically

### ISSUE THREAD

**Issue by RyanMitchellWilson** [TheWidlarzGroup/react-native-video#741]
I'm trying to set up my video so that when I press a button it opens the video in a the fullscreen player and then it should start the video. Currently there is no way to do this that I have found. 

I've tried setting my rate to 1 but that just causes the video to play when not in fullscreen. If you set the rate to 0 it doesn't play the video outside of the fullscreen player but it causes you to have to press the play button after opening the player. I've also tried setting the rate to 1 at the same time as opening the fullscreen player, which works except for the fact that if you close the fullscreen player before the video ends, there is no way to tell, so I cannot set the rate back to 0 which then causes it to start playing in the background. 

Has anyone figured out how to do this or know if it is even possible?

**Comment by RyanMitchellWilson** [comment]
Alright I had to dig through the code to find this but there are actually props called `onFullscreenPlayerWillPresent`, `onFullscreenPlayerDidPresent`, `onFullscreenPlayerWillDismiss` and `onFullscreenPlayerDidDismiss` which can be used and they are not documented.

Really need some better documentation for this project. I shouldn't have to dig through the code to figure out how to use this properly.

https://github.com/react-native-community/react-native-video/blob/master/Video.js#L89

**Comment by tirrorex** [comment]
seems like you can also dismiss the fullscreenplayer directly which should be documented aswell.
I assume the component will then rerender with the frame you gave it before the fullscreen presentation and video should continue playing properly?

**Comment by rudyryk** [comment]
@RyanMitchellWilson Thank you for the hint! These events are really useful and should be documented. And seems like documentation PR's are not merged that fast, looking at #815 one.

**Comment by cobarx** [comment]
All of these props are now documented.
