### ISSUE TITLE
long load time

### ISSUE THREAD

**Issue by gooor** [TheWidlarzGroup/react-native-video#745]
I have problem on IOS when viewing videos from external URL (AWS S3). The problem is that when I enters the view with the video it takes 5-10s or more until the video starts but even after it starts it stops several times for a 1-4s during a 30s long video.
Video is ~30mb 480p, as I mentioned from AWS S3. When viewing directly on safari or chrome it loads instantly (1-2s but not 5-10s, I'm on a 100mbit connection) and plays without any pauses.
I could understand initial load so it waits until it gets all 30 megabytes but why it has so much stops and buffering ...
Is there some kind of network usage limitation (ie. use no more than 50kbps or something) - because this app behaves as it was on some kind of network limitation - uses 50-80mb of ram and up to 20% CPU, so it's not what causes freezes - app is fully responsive during load and freezes.

**Comment by maagee** [comment]
+1

**Comment by mattapperson** [comment]
If you access the same URL via mobile safari or another video player on the device the issue is not there?

**Comment by gooor** [comment]
Yes - if I access this video on safari/chrome it works ok. As I mentioned it loads for 1-2s and then plays without any freeze. but in the app it behaves as on 3g or the video is 1gb not 30mb.

**Comment by aacxg** [comment]
+1

**Comment by maagee** [comment]
@mattapperson  Video(MediaPlayer) take a long time。exoplayer without this question,but exoplayer crash  width low version android （<5.0）

**Comment by t14** [comment]
+1 
I have the same issue on android

**Comment by gooor** [comment]
@mattapperson Any thoughts?

**Comment by mattapperson** [comment]
Honestly, no. The fact that the issue happens on iOS and Android seems to point to a RN or RN implementation issue... but ill have to dive in to better understand

**Comment by gooor** [comment]
@mattapperson I found that even when I use source={require('...'} it also loads far too long :| so it's surely not a network problem
Is it the video codec maybe?

**Comment by mattapperson** [comment]
Well the thing is, on iOS there is not much that could delay things. It’s a fairly “close to the metal” implementation using the built in api, and I would assume iOS used the same codec for playing in safari. So the main place to look would then be the RN bridge. Not saying the issue IS there just it seems most likely

**Comment by gooor** [comment]
I did some more digging:
1. I did experiment: I created page with <video /> html5 tag and in app added WebView component that point to this page - turns out it had same issues with long time before start and randomly stopped several times during video play - page was in my localhost so network connectiion was not an issue here
2. I thought maybe it's a codec - videos I was trying to play were over 1200kbps so I changed it to 768kbps and it works much much better .... 

I tested it on local asset require() source, not network resource ....

Strage thing is that when I'm trying to play this video directly in safari, from a network (AWS S3) url - it plays without any problems, network nor codec is an issue here ...

**Comment by gooor** [comment]
Adn

**Comment by t14** [comment]
@gooor noticed you closed the issue, but its not quite clear what the fix was? Seems like you are suggesting the bitrate maybe an issue for local assets.
Think we should keep the issue open, there is still issues around playing video over the net (e.g aws storage).

**Comment by mattapperson** [comment]
@t14 their was not a fix. he pointed out then even when playing via an html page in the browser it is just as slow meaning the issue is at the OS level outside the reach of this plugin

**Comment by gooor** [comment]
@t14 we are playing videos from AWS S3 storage - at the beginning I thought server was the issue. But when I used local asset problem was the same - so it wasn't the network issue or server. I then read about some issues on iOS with videos when they use "incompatible" codecs (whatever this means ;)
We used mp4 and dropped bitrate to 768kbps - and it worked (at least client is satisfied - or even very happy)
Honestly - I don't know what was wrong with previous one - but after changing codec we reduced file size to 25% and it then didn't had any problems (I mentioned that I tested it on local asset to skip network issues). Maybe there's some memory usage limit or CPU limit somewhere set.

I cannot tell you how this works on Android.

**Comment by viperfx** [comment]
@gooor what codec did you use?

**Comment by t14** [comment]
Reducing the bitrate like @gooor suggested definitely makes a difference. Although still feels like a bug and bitrate reduction is work around.
@viperfx I used mp4 has the codec and I used a tool like handbrakes to reduce the bitrate (check link https://superuser.com/questions/455249/change-bitrate-of-mp4-file )

**Comment by oleksiy-nesterov** [comment]
I still see that bug...

**Comment by diosney** [comment]
@gooor Can confirm that it works on Android too, did the same and the issue was fixed. Thanks.

**Comment by nilu2039** [comment]
any update on this?
