### ISSUE TITLE
Seeking paused HLS stream resumes playback

### ISSUE THREAD

**Issue by dpeek** [TheWidlarzGroup/react-native-video#75]
Seeking a paused HLS stream like `http://www.streambox.fr/playlists/test_001/stream.m3u8` resumes playback, ignoring `props.paused` and `props.rate`.

I'm poking around `RTCVideo.m` but thought I should ask here in case it was something obvious (to you at least).

Great plugin, once I've got my head around it I'd like to add support for multiple audio tracks.

**Comment by brentvatne** [comment]
Heya @dpeek - pretty low bandwidth for me at the moment, not entirely sure what would be causing this but if you do have time to dig in that would be awesome!
