### ISSUE TITLE
Cannot stream or play some files on android

### ISSUE THREAD

**Issue by mannol** [TheWidlarzGroup/react-native-video#750]
I'm trying to test streaming and playing with [this](https://dwknz3zfy9iu1.cloudfront.net/uscenes_h-264_hd_test.mp4) file. All I can see is black screen. However some links work, like [this](http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4) one. I'm using android exoplayer on Android 4.1.2.
It's important to note that, I can't play the said file even when it's loaded from the disk.

EDIT:
I just tired regular player and, I get the video error: { error: { extra: -2147483648, what: 1 } }

**Comment by Ogulcan-Ozdemir** [comment]
I have similar issue stream videos not play some times if it's playing just corrupted version of them 
<img src="https://user-images.githubusercontent.com/18949258/29749876-6021a328-8b3e-11e7-8b99-232379829b69.png " width="300">

**Comment by cobarx** [comment]
Version 2.1.1 has an updated version of ExoPlayer which could possibly fix this. However, older devices are often missing the codecs necessary to play some videos. My guess is that's what you're encountering. You can verify this by trying the video on a newer device.

The only real fix is to re-encode the video with settings (h.264 main profile, for example) that are more compatible with older devices.
