### ISSUE TITLE
[Android] - Video resizes visually before playing

### ISSUE THREAD

**Issue by tdekoning** [TheWidlarzGroup/react-native-video#752]
When using the video player on android (Samsung galaxy Tab A, running android 7.0), the video is already rendered before the `onPrepared` event is triggered. This results in a single frame that is being shown for about 1 second in the wrong size and after that 1 second, the video is being shown in full screen.

Expected:
I expect the video to only be rendered in the correct `resizeMode="cover"` way, without a frame first being shown in a incorrect size.

I've also tested this on a Oneplus 3T running android 7.1.1 and on a nexus 7 running android 6.0.1, the video player works fine on those devices.

react native version: 0.47.1
react-native-video version: 2.0.0

**Comment by bella-silveira** [comment]
I'm getting this problem as well, any fixes for this yet?

Samsung S8
react-native 0.55.2
react-native-video 2.0.0
