### ISSUE TITLE
The video rotates, but the control bar does not rotate

### ISSUE THREAD

**Issue by czhaoli** [TheWidlarzGroup/react-native-video#756]
当传入rotation时，视频会旋转，控制条不会旋转，这样控制条会在视频的一遍而不是底部
When the incoming rotation, the video will rotate, the control bar will not rotate, so that the control bar will be in the video instead of the bottom

**Comment by meiqi1992** [comment]
我设置了rotation 视频都没旋转，能看下你的代码是怎么设置的吗？
