### ISSUE TITLE
[Android] Works with Android 23 and 25, but not working lower than Android Lollipop

### ISSUE THREAD

**Issue by nzwnabdulwahid** [TheWidlarzGroup/react-native-video#760]
Hi everybody, I use this plugin to play video hosted remotely. When testing inside simulator of Android Lollipop and below, the player hangs and blocked the UI. Android Studio prompted this error: 

`Attempt to call getDuration without a valid mediaplayer `
`Error:(-38,0)`

Anyone else encountered this issue ?

**Comment by KalebPortillo** [comment]
+1
