### ISSUE TITLE
Rate is reset to 1 after using .seek() method

### ISSUE THREAD

**Issue by alexfoxy** [TheWidlarzGroup/react-native-video#763]
If I set the rate of a video tag to 0.1 and hit play it works as expected but after I use the seek method on the video it reverts to a rate of 1. 

Any pointers or is this a bug?

**Comment by RyanMitchellWilson** [comment]
I think it is a bug, I'm experiencing the same thing

**Comment by QuietListener** [comment]
+1

**Comment by cobarx** [comment]
This has been fixed by #771
