### ISSUE TITLE
Playing this m3u8 has no picture

### ISSUE THREAD

**Issue by caoyd** [TheWidlarzGroup/react-native-video#765]
http://skydvn-nowtv-atv-prod.skydvn.com/atv/skynews/1404/live/04.m3u8
Hi, guys, when I open this m3u8, It has no picture, but sound is playing
I open this m3u8 with potplayer in my pc works fine
Any idea?
Thank you

Android Emulator API 26

"dependencies": {
  "babel-preset-react-native": "2.1.0",
  "react": "16.0.0-alpha.12",
  "react-native": "0.47.2",
  "react-native-immersive": "^1.0.0",
  "react-native-orientation": "^3.0.0",
  "react-native-video": "^2.0.0",
  "react-navigation": "^1.0.0-beta.11"
},

**Comment by t14** [comment]
https://github.com/react-native-community/react-native-video/issues/759#issuecomment-326819269

**Comment by caoyd** [comment]
thanks
