### ISSUE TITLE
Player only showing black screen while playing HLS stream from Wowza on Android only

### ISSUE THREAD

**Issue by rezonjov** [TheWidlarzGroup/react-native-video#766]
For some reasons, I can't play any HLS stream from Wowza on Android. It only shows black screen and nothing else.

Video player works just fine using any other HLS stream. If this is due bad implementation of the video player, it shouldn't be able to display any other stream for sure.

And strangely, the same video player setting works just fine on an iOS device. 

There is no error whatsoever, I'm quite clueless as to what is wrong exactly. Is there anybody who have the same issue as mine? Any help would be much appreciated.

**Comment by shiyunsheng** [comment]
You need a thumbnail in android and update setting.gradle 
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

**Comment by rezonjov** [comment]
Hi @shiyunsheng, can you elaborate more on thumbnail for android? Do you mean I should use react native video thumbnail?

**Comment by shiyunsheng** [comment]
You have to give it a thumbnail, otherwise you will see a black screen 
You can try

**Comment by inanbayram** [comment]
@rezonjov Have you found a solution?

**Comment by rezonjov** [comment]
hey @inanbayram, Sort of. 

We started paying for the API wowza cloud engine and the black screen problem is gone. I think it's more to wowza limitation than to the react native video. 

on a side note, we tried using rn video thumbnail, sadly it didn't work.

closing the issue for now.
