### ISSUE TITLE
onEnd not called on android

### ISSUE THREAD

**Issue by michaelknoch** [TheWidlarzGroup/react-native-video#767]
run this example on android and you will notice that onEnd is never called.
Does anyone else experience this issue?

```js
<Video
       source={{ uri: videoSource }}
       paused={!videoIsPlaying}
       resizeMode='contain'
       repeat={false}
       onEnd={onEnd}
/>
```

**Comment by KalebPortillo** [comment]
+1

**Comment by agumack** [comment]
same here https://github.com/react-native-community/react-native-video/issues/281

**Comment by wuxiii** [comment]
the same ,Generating Signed APK , onEnd is not called

**Comment by cobarx** [comment]
This is working properly for me on 2.1.0 if repeat is turned off. It's broken if it's on though.
