### ISSUE TITLE
Undefined is not a function while attempting to use video.seek()

### ISSUE THREAD

**Issue by absurdmoe** [TheWidlarzGroup/react-native-video#768]
native-video-controls component (https://www.npmjs.com/package/react-native-video-controls) which is based off react-native-video(https://www.npmjs.com/package/react-native-video) and I am trying to play the next video in a sequence and have that video seek to 0 (so it plays from the beginning). But I am getting the error: "Undefined is not a function (evaluating 'this.refs.myVideo.seek(0)') React-Native"

Here is my code:

import Video from 'react-native-video';
import VideoPlayer from 'react-native-video-controls';

export default class Player extends Component {
constructor(props){
  this.state = {
    playlist: [require(file1.mp4),require(file2.mp4)]
  }
 }
  playNext() {
    this.refs.myVideo.seek(0);
    let playlist = this.state.playlist;
    playlist.shift();
    this.setState({playlist,})
}
render() {
    return (
      <View>
        <VideoPlayer
          ref='myVideo'
          muted={false}
          seekColor={ 'red' }
          source={this.state.playlist[0]}
          navigator={ this.props.navigator }
          style={styles.player}
          onEnd={()=>this.playNext()}
        />
      </View>
    );
  }
} 
what's my errpr?

Edit: this is for android btw

up vote0down votefavorite | I am using react-native-video-controls component (https://www.npmjs.com/package/react-native-video-controls) which is based off react-native-video(https://www.npmjs.com/package/react-native-video) and I am trying to play the next video in a sequence and have that video seek to 0 (so it plays from the beginning). But I am getting the error: "Undefined is not a function (evaluating 'this.refs.myVideo.seek(0)') React-Native"Here is my code:import Video from 'react-native-video'; import VideoPlayer from 'react-native-video-controls';   export default class Player extends Component { constructor(props){   this.state = {     playlist: [require(file1.mp4),require(file2.mp4)]   }  }   playNext() {     this.refs.myVideo.seek(0);     let playlist = this.state.playlist;     playlist.shift();     this.setState({playlist,}) } render() {     return (       <View>         <VideoPlayer           ref='myVideo'           muted={false}           seekColor={ 'red' }           source={this.state.playlist[0]}           navigator={ this.props.navigator }           style={styles.player}           onEnd={()=>this.playNext()}         />       </View>     );   } }  what am I doing wrongEdit: this is for android btw
-- | --

**Comment by Noitidart** [comment]
It's not recommended to use ref as a string. I don't know if this is he problem. Try using callback method though.

**Comment by amberv0** [comment]
@Mohammadhunan97 , just got the same issue. Have you solved it?

**Comment by absurdmoe** [comment]
@amberv0 nope never figured it out, but I'm not working on that project anymore. Best of luck in solving this, if you figure it out, I'd love to hear about it

**Comment by amberv0** [comment]
@Mohammadhunan97 , I actually did. The thing was not related to `react-native-video`, it's a general react-native thing. My `<Video/>` was wrapped with several other components and it was breaking the behavior - the `ref` callback simply never was called when `<Video/>` was wrapped in `TouchableHighlight`. Once I additionally wrapped `Video` with `View` ( so now `Video` was inside of `View` which was inside of `TouchableHighlight`) everything started working perfectly
