### ISSUE TITLE
Cannot get to play in Background IOS

### ISSUE THREAD

**Issue by Monte47** [TheWidlarzGroup/react-native-video#770]
Although I have the attribute playInBackground={true} on IOS. The audio shuts off when I lock my screen or press home. This does not happen on Android. 

Using IPhone 7, ios 10.3.3

**Comment by Monte47** [comment]
Also should note that it works fine in a simulator, but not on actual devices.

**Comment by Monte47** [comment]
Upon further inspection, I have found that the audio fades out while playInBackground is set to True, and simply cuts off when set to false on Device.

Does anyone know what could be causing this?

**Comment by fedebaier** [comment]
I found the solution to this: https://github.com/react-native-community/react-native-video/issues/797#issuecomment-334480547
