### ISSUE TITLE
BackHandler closes app when using this package.

### ISSUE THREAD

**Issue by samdoj** [TheWidlarzGroup/react-native-video#774]
enivronment:
------------
React 16.0.0.apha.6
RN: 0.44.0
CLI: 2.0.1
Node 7.2.1

Using `BackHandler` in any capacity causes the app to close immediately when using this package.  To fix it, I added react-native-windows as a project dependency.  Why this is the case is beyond me, but this library does not play nice with BackHandler.

**Comment by lyccccc1piano** [comment]
Has this problem been resolved?

**Comment by lyccccc1piano** [comment]
I tried react-native-windows, the problem still exists.
