### ISSUE TITLE
Library is not linkable

### ISSUE THREAD

**Issue by Puzzleton** [TheWidlarzGroup/react-native-video#775]
`node v7.10.1`
`npm v4.2.0`
`react-native v0.47.0`
`react-native-video v2.0.0`

Running `react-native link` skips `react-native-video` in the linking process. Running `react-native-link react-native-video` produces no results. Other issues suggest methods to manually link the library, but I have not found one that fixes the issue.

Without linking, like others have said, I get the error "Cannot read property 'Constants' of undefined".

**Comment by JesseDunlap** [comment]
`node v7.10.1`
`npm v4.2.0`
`react-native v0.47.0`
`react-native-video v2.0.0`

Adding to this, I was able to resolve this issue by modifying the `package.json` file and including the following `files` section...

```
"files": [
      "ios/",
      "Video.js",
      "VideoResizeMode.js"
]
```

This appears to be missing in versions after `0.6.0`, and seems to be preventing `react-native link` from finding the required files to copy over. After adding this, I'm able to link the library and use it as expected on iOS.

I have another odd issue though, which is that when I add the `android/` folder to the `files` list it stops linking again. This doesn't seem to happen if I add `android-exoplayer/` or `windows/`. Not sure what it is about the `android/` folder that's causing this issue.

**Comment by cobarx** [comment]
Haven't encountered this lately or seen people running into issues. Please reopen if it's still a problem.
