### ISSUE TITLE
No "thumbnail" on Android, present on IOS

### ISSUE THREAD

**Issue by fendorio** [TheWidlarzGroup/react-native-video#777]
On Android, if you render the Video element with the 'paused' prop set to true, no "thumbnail" is shown. On IOS, a thumbnail is displayed. 

I'm guessing that this is due to the difference in how the videos are handled, perhaps IOS is fetching some data on load when Android is not, haven't had a dig for the cause.

**Comment by selsamman** [comment]
As a workaround to this I have found that if in the onLoad event if you seek to zero the thumbnail appears.

**Comment by SharanyaRao91** [comment]
@selsamman How did you do this?

**Comment by selsamman** [comment]
``
<Video source={{uri: uri}} 
             paused={true} 
             ref={(ref)=>{this.player=ref}} 
             onLoad={()=>{this.player.seek(0)}} \>
``

Still sometimes it doesn't load when working with the debugger. I am working with local files rather than urls.  If it is not reliable as I move to production I will use a screen shot stand in.

**Comment by rblcb** [comment]
iOS can generate thumbnail with uri of video but android doesn't.
You can generate the thumbnail from the uri of video with react-native-thumbnail.
Then place the exported thumbnail on top of the video and then play video once you click play button or any other actions.

**Comment by waqaramjad** [comment]
@selsamman , I am getting this error this.player.seek is not a function on your solution

**Comment by aftabaminzoobiapps** [comment]
`<Video
source={{uri:`${props.source}`}}
paused={paused}
style={{ ...StyleSheet.absoluteFill }}
onLoad={load}
            onProgress={progress}
            resizeMode="cover"
            ref={ref => (video = ref)}
            seekColor="#fff"
          />


  const load = ({duration}) => {
    video.seek(0)
    setDuration(duration);
  } // now here the duration is update on load video
  `

**Comment by Atuldhaka** [comment]
i have a swiper which contains multiple videos and if i use seek method for thumbnail then last video of the swiper seeks to 0 but other's don't so, how to create thumbnail for all swiper elements ?

**Comment by doublelam** [comment]
> i have a swiper which contains multiple videos and if i use seek method for thumbnail then last video of the swiper seeks to 0 but other's don't so, how to create thumbnail for all swiper elements ?

I guess because you just bind the last video to the ref. I suggest that you can create a new react component, put `<Video />` into this component and bind `<Video />` into this component, then import this component from the screen where you were playing the video

**Comment by RavishGarg2** [comment]
my code started working with following code  

const videoRef  = useRef();

onLoad={() => {
              videoRef.current.seek(0);
            }}
