### ISSUE TITLE
Can it work with local recorded video?

### ISSUE THREAD

**Issue by PrimeObjects** [TheWidlarzGroup/react-native-video#779]
My app used react-native-camera to record and save a local mp4 file. The location is file:///storage/emulated/0/DCIM/somename.mp4. I tried to put this video path to source property, the video failed to play. 

How can the component play the mp4 in the local storage?

Thanks
Gary

**Comment by Noitidart** [comment]
Yes it works for me. Try removing the `file://` prefix, I find I don't need that on Android, unlike with `<Image>`. Make sure to give it a height and width in the style prop, it probably is loading but not showing.

**Comment by PrimeObjects** [comment]
Hi Noitidart,

Thank you for the update. I found {uri: 'file:///'} also works. It is all good now.

Cheers
Gary

**Comment by Noitidart** [comment]
Thanks for sharing, what was the issue? I might be having it too.

**Comment by PrimeObjects** [comment]
It was the issue unrelated to the react-native-video. In our code the player was not positioned correctly in the View and it was invisible. Because the background of View is black, we did not recognize the player was not actually shown. We can hear sound but was not able to see the video. We thought it was the issue of react-native-video because the video we are playing taken from react-native-camera and saved in the local. 

Cheers
Gary

**Comment by Noitidart** [comment]
Ah, yes images and video share the same funk. Getting with:100% and height:auto does not seem easy. Thanks for sharing!
