### ISSUE TITLE
.MOV does not work on Android?

### ISSUE THREAD

**Issue by Noitidart** [TheWidlarzGroup/react-native-video#780]
I am seeing a lot of issues but no definitive answer. Does `react-native-video` not support playing `.MOV` files on Android?

react-native-video: ^2.0.0
react-native-cli: 2.0.1
react-native: 0.47.1

Here is my code, I am using `react-native-fetch-blob`:

```
RNFetchBlob
  .config({
    fileCache : true,
    appendExt : 'mov'
  })
  .fetch('GET', 'http://www.example.com/file/example.zip', {
    //some headers ..
  })
  .then((res) => {
    console.log('The file saved to ', res.path())
    videoView = <Video source={{ uri :res.path() }}/>
  })
```

Trying to play this cause the error:

```
{ extra: -2147483648, what: 1 }
```

Report here says this means "Unknown error" - https://github.com/react-native-community/react-native-video/issues/264#issuecomment-243275079

**Comment by LEEY19** [comment]
@Noitidart hey dude, have you managed to find any solution to this? It does seem like the video player does not support playing of .mov file. Have tested with mp4 files and it works fine

**Comment by Noitidart** [comment]
@LEEY19 - thansk for the comment, I have not figured it out yet :(

**Comment by niloufarMakhzani** [comment]
Hi, any solution for MOV?

**Comment by DISKONEKTeD** [comment]
This use to work for one on android but recently I've had users report issues with mov type files not displaying.

Currently, I can get it to run fine on a Google Pixel android 11, but my old samsung android 9 does not work anymore

**Comment by Arslan106** [comment]
same issue did you found any solution ...? @DISKONEKTeD

**Comment by Noitidart** [comment]
You can try expo video solution, I'm not sure if it uses react-native-video underneath, it might not.

https://docs.expo.dev/versions/latest/sdk/video/

**Comment by Desintegrator** [comment]
also looking for playing .mov on Android

**Comment by arlovip** [comment]
The same issue! It works well on iOS with `MOV` format but not on Android.
