### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kledk** [TheWidlarzGroup/react-native-video#787]
What about a new version release. Its been a long time since a release.
Latest from 31. Jan...

**Comment by SaraChicaD** [comment]
I agree, is there even anyone working on this anymore? There are 37 PRs pending?

**Comment by afilp** [comment]
Can someone take charge of this and release? Thanks a lot!

**Comment by afilp** [comment]
@mattapperson As you have done the previous releases, is it possible that you do a release? Or at least give us a clue if this is not possible for them now? Thanks again!

**Comment by cobarx** [comment]
Version 2.1.0 was just published. Hoping to keep the releases flowing as I work through the PR backlog!
