### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by michaelspeed** [TheWidlarzGroup/react-native-video#788]
Any idea how can we implement picture in picture on android o?

**Comment by FullstackJack** [comment]
Should be pretty easy to implement this. https://developer.android.com/guide/topics/ui/picture-in-picture#java

**Comment by luiey** [comment]
> Should be pretty easy to implement this. https://developer.android.com/guide/topics/ui/picture-in-picture#java

Anyhow, on react native cli; how do I achieve picture-in-picture? But not drag my concept too far, is this feature is like slide show thingy? Which mean, I get the multiple files, and queue one by one to show video etc and then image and then repeat back the video with timeout delay for each image slide show?
