### ISSUE TITLE
Add 'stop' to the API

### ISSUE THREAD

**Issue by yamill** [TheWidlarzGroup/react-native-video#79]
Hey @brentvatne so I was thinking... maybe we can add <strong>stop</strong> to the API? Something like this. What do you think?

``` objective-c
- (void)setStop:(BOOL)stop
{
    if (stop) {
        [_player seekToTime:CMTimeMake(0, 1)];
        [_player pause];
    }

    _stop = stop;
}
```

**Comment by isair** [comment]
I'd say if stop is to be added it should be a method, not a property.

**Comment by brentvatne** [comment]
Yeah I agree with @isair - this should be a method that we call on a ref. @yamill interested in submitting a PR?

**Comment by arilitan** [comment]
Wanted to re-open the discussion here if needed. We are trying to clean up open issues in this repo, so if no further comments in the next couple weeks it will be closed.

**Comment by zchwyng** [comment]
Closing this since it's outdated.
