### ISSUE TITLE
Repeating video ducks audio at the beginning of every loop

### ISSUE THREAD

**Issue by garrettg123** [TheWidlarzGroup/react-native-video#796]
When playing a video and audio separately with an audio ducking playback session, the ducking is properly activated/deactivated with:

```objectivec
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
    // play audio
    [[AVAudioSession sharedInstance] setActive:NO error:nil];
```

However, after about 10 seconds, the background audio is ducked again (without calling `setActive:YES`). If the video is commented out, the ducking works properly.

Here is how ReactNativeVideo is being used:

```js
      <ReactNative.View style={styleSheet.videoFrame}>
        <ReactNativeVideo
          // ignoreSilentSwitch='ignore'
          // muted={true}
          // onBuffer={this.onBuffer}             // Callback when remote video is buffering
          // onEnd={this.onEnd}                   // Callback when playback finishes
          // onError={this.videoError}            // Callback when video cannot be loaded
          // onLoad={this.setDuration}            // Callback when video loads
          // onLoadStart={this.loadStart}         // Callback when video starts to load
          // onProgress={this.setTime}            // Callback every ~250ms with currentTime
          // paused={this.state.isPaused}
          playWhenInactive={false}
          // ref={(node) => { this.video = node }}
          repeat={true}
          resizeMode='contain'
          source={{ uri: videoUri }}
          style={styleSheet.video}
          volume={1}
          />
      </ReactNative.View>
```

One thing to note is that the only code in ReactNativeVideo that uses `sharedInstance` is when `ignoreSilentSwitch` is set, but as you can see, it's commented out above.

The question is: where is the other audio ducking coming from and how can it be removed?

UPDATE:
The audio is being ducked again every time the video restarts (because it's looping). Still unsure as to how to fix it, though...

**Comment by kaancembertas** [comment]
Did you find solution of this topic?
