### ISSUE TITLE
Can't play in background on Ios 11

### ISSUE THREAD

**Issue by hathnv** [TheWidlarzGroup/react-native-video#797]
I use rn video to play an audio. playInBackground is not working on ios 11. It still works in lower versions.

**Comment by fedebaier** [comment]
I had the same problem and found the solution: you must enable the Audio Background Mode in your Xcode project as explained here: [Enabling Background Audio](https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW3)

![screen shot 2017-10-05 at 16 18 11](https://user-images.githubusercontent.com/2706853/31232205-78fb1ffe-a9e9-11e7-936b-7afa08c3b94e.png)

**Comment by anshul-kai** [comment]
No dice! I have the following in `AppDelegate.m` and is still doesn't work on iOS 11. 

```
  // Set the Audio Session Category to Playback
  // https://developer.apple.com/library/content/qa/qa1668/_index.html
  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
  NSError *setCategoryError = nil;
  BOOL success = [audioSession setCategory:AVAudioSessionCategoryPlayback error:&setCategoryError];
  if (!success) { /* handle the error condition */ }
  NSError *activationError = nil;
  success = [audioSession setActive:YES error:&activationError];
  if (!success) { /* handle the error condition */ }

```

**Comment by anshul-kai** [comment]
Turns out you need to set `ignoreSilentSwitch` to `ignore` for this to work. Although, with that set, `playInBackground={false}` has no effect.

**Comment by peterlazar1993** [comment]
@fedebaier Were you able to get this working?

**Comment by robcalcroft** [comment]
Also experiencing this issue on iOS 11. Have tested adding the `ignoreSilentSwitch` prop and enabling background audio in Xcode

**Comment by aditya-sodhani** [comment]
Same issue here. Tested all the above methods.

**Comment by robcalcroft** [comment]
@Justkant cheers for posting that will try it out in the newer sim. If I install onto my phone (11.1) will I still see the issue or is it specifically a simulator issue?

**Comment by fedebaier** [comment]
@peterlazar1993 Yes, in my case it was solved doing what I mention in my previous comment. I don't know why the downvotes, though. It worked for me and I just wanted to share it.

**Comment by peterlazar1993** [comment]
@fedebaier Were you testing on simulator or device? Also what was the OS version.

@robcalcroft Please ping here if you get it working :)

**Comment by robcalcroft** [comment]
@peterlazar1993 Will do 😄

**Comment by Justkant** [comment]
@robcalcroft I cannot confirm that the issue is only on the simulator, you'll need to test that yourself.

**Comment by rfw** [comment]
+1

**Comment by kay-is** [comment]
@fedebaier worked for me on device, didn't try this on the simulator.

**Comment by ArtisanalPickle** [comment]
Simply works on iOS 10. Broken on iOS 11, despite proper settings.

It's worth noting that this _will likely cause an app store rejection_ for declaring that your app uses background audio, without actually offering that feature. Reviewers will test on iOS 11, see you enable background but don't offer it as a feature and will think you're planning on slipping by something nefarious.

It happened to us :)

**Comment by ArtisanalPickle** [comment]
Actually regarding my last comment, I can't say with certainty that this is isolated to iOS 11. In fact, in the latest simulator (iOS 11.2) and a iOS 10.3 simulator and the device itself, I get identical behavior:

background audio for video files (in my case a streaming HLS .m3u8 file), functions perfectly when the user locks their phone, but NOT when hitting the home button.

My component looks like this:
```
<Video source={{uri: uri}}   // Can be a URL or a local file.
        onFullscreenPlayerDidDismiss={this.onDismiss}
        ref={(player) => {
          if(!this.state.playing && player) {
            player.presentFullscreenPlayer()
            this.setState({ playing: true })
          }
        }}                                      // Store reference
        rate={1.0}                              // 0 is paused, 1 is normal.
        volume={1.0}                            // 0 is muted, 1 is normal.
        muted={false}                           // Mutes the audio entirely.
        paused={false}                          // Pauses playback entirely.
        resizeMode="cover"                      // Fill the whole screen at aspect ratio.*
        repeat={false}                           // Repeat forever.
        playInBackground={true}                // Audio continues to play when app entering background.
        playWhenInactive={true}                // [iOS] Video continues to play when control or notification center are shown.
        ignoreSilentSwitch={"ignore"}           // [iOS] ignore | obey - When 'ignore', audio will still play with the iOS hard silent switch set to silent. When 'obey', audio will toggle with the switch. When not specified, will inherit audio settings as usual.
        progressUpdateInterval={PROGRESS_MILLISECONDS} // [iOS] Interval to fire onProgress (default to ~250ms)
        onError={this.onVideoError}               // Callback when video cannot be loaded
        onProgress={this.onProgress}
        onLoadStart={this.onStart}
        onEnd={this.stopPlaybackPing}
       /> 
```

**Comment by frenkie** [comment]
I had this background audio problem with the Xcode 9.1 simulator (while it worked on my device) and I can confirm that @Justkant['s comment](https://github.com/react-native-community/react-native-video/issues/797#issuecomment-342081673) on using Xcode 9.2 and it's 10.0 simulator version and iOs 11.2, worked for me.

**Comment by keyuanupup** [comment]
i have a good news。i resolve this problem！

**Comment by keyuanupup** [comment]
in AppDelegate.m

#import "AppDelegate.h"
#import <AVFoundation/AVFoundation.h>
UIBackgroundTaskIdentifier _bgTaskId;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];

}

-(void)applicationWillResignActive:(UIApplication *)application
{
  //开启后台处理多媒体事件
  [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
  AVAudioSession *session=[AVAudioSession sharedInstance];
  [session setActive:YES error:nil];
  //后台播放
  [session setCategory:AVAudioSessionCategoryPlayback error:nil];
  //这样做，可以在按home键进入后台后 ，播放一段时间，几分钟吧。但是不能持续播放网络歌曲，若需要持续播放网络歌曲，还需要申请后台任务id，具体做法是：
  _bgTaskId=[AppDelegate backgroundPlayerID:_bgTaskId];
  //其中的_bgTaskId是后台任务UIBackgroundTaskIdentifier _bgTaskId;在appdelegate.m中定义的全局变量
}

+(UIBackgroundTaskIdentifier)backgroundPlayerID:(UIBackgroundTaskIdentifier)backTaskId
{
  //设置并激活音频会话类别
  AVAudioSession *session=[AVAudioSession sharedInstance];
  [session setCategory:AVAudioSessionCategoryPlayback error:nil];
  [session setActive:YES error:nil];
  //允许应用程序接收远程控制
  [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
  //设置后台任务ID
  UIBackgroundTaskIdentifier newTaskId=UIBackgroundTaskInvalid;
  newTaskId=[[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:nil];
  if(newTaskId!=UIBackgroundTaskInvalid&&backTaskId!=UIBackgroundTaskInvalid)
  {
    [[UIApplication sharedApplication] endBackgroundTask:backTaskId];
  }
  return newTaskId;
}

**Comment by keyuanupup** [comment]
this is work for me.so i share for you.I hope to help you。Contact me。email：307464314@qq.com。

**Comment by keyuanupup** [comment]
and i find in this 'react-native-video' README.md had explained  ‘Play in background on iOS’

**Comment by letminin** [comment]
updating Xcode fix the issue indeed, thanx for ur share ! 👍

**Comment by cobarx** [comment]
This is working properly for me on Xcode 9.4 and both real & simulator devices running iOS 11.4 as long as I enable Background Audio and set ignoreSilentSwitch to "ignore". I've added this to the docs.

How are things looking for other people?

**Comment by dkoo761** [comment]
This solution above from @keyuanupup also has the important side benefit of allowing background audio to function in a sequential multi-file situation (such as a playlist) where there is a slight gap in playback while swapping out the player's current audio file source for the next audio file's source. Without this solution, iOS suspends the app as soon the first file in the playlist finishes playing. 

https://github.com/react-native-community/react-native-video/issues/797#issuecomment-374826812

**Comment by anastely** [comment]
Hello Guys,
I don't know if my issue #2038 related or not but can you check it?

**Comment by Nesh108** [comment]
I am having the same issue. This is the configuration:

```
      ignoreSilentSwitch={'ignore'}
      playInBackground={true}
      playWhenInactive={true}
```

And background modes are set (audio, fetch, processing).

**Comment by Nesh108** [comment]
Did anyone here find a solution in the meantime? For me it's happening both on iOS and Android.
