### ISSUE TITLE
"Error calling RCTEventEmitter.receiveEvent" on IOS

### ISSUE THREAD

**Issue by omgo** [TheWidlarzGroup/react-native-video#802]
Hello, after ~12 seconds of playing video from hls url (hls://.../stream.m3u8) iOS app is crashing with error, stream via Wowza, could you help me? Thank you
```
<Video
  onLoadStart={this.onLoadStart}
  onLoad={this.onLoad}
  style={styles.video}
  source={{ uri: firstCamera.url }}
  muted={true}
  paused={false}
  repeat={true}
  resizeMode="stretch"
/>
```

![image](https://user-images.githubusercontent.com/13779291/31045178-0b6bb6c2-a608-11e7-8c15-24dc9a9e4ee1.png)

**Comment by wsupajirakit** [comment]
how can I fix it

**Comment by omgo** [comment]
**wsupajirakit**, just add react-native-video to your project using direct link - https://github.com/react-native-community/react-native-video.git
example:
didnt work `yarn add react-native-video`
working `yarn add https://github.com/react-native-community/react-native-video.git`
this problem because author fixed that issue, but didnt update package in npm

**Comment by adamsoffer** [comment]
This really tripped me up! Thanks @omgo. It's been quite a while since the last publish. Would any of the authors mind publishing the package in npm with this fix?

**Comment by shawncamp** [comment]
It's March 2018 and I still had to use the fix from omgo above....Lovely.
