### ISSUE TITLE
how to use android-exoplayer in my RN project,I can't find the usage.

### ISSUE THREAD

**Issue by cloudsafe** [TheWidlarzGroup/react-native-video#803]
I feel MediaPlayer was slowly when I paly video.
I thought exoplayer use okhttp, I think it will be faster.
But I don't know ,how to use it.

**Comment by frankiewiczkamil** [comment]
@cloudsafe last post in here:
https://github.com/react-native-community/react-native-video/issues/668#issuecomment-312383674

**Comment by cloudsafe** [comment]
@frankiewiczkamil THX
