### ISSUE TITLE
onBuffer never called on Android

### ISSUE THREAD

**Issue by Simba14** [TheWidlarzGroup/react-native-video#804]
I have noticed that the onBuffer property is never fired on android. Anyone know why this is?

**Comment by kaifah** [comment]
试试这个：
_onProgress(data){
    let nowtime = this.state.currentTime;
    let bmessage = '正在播放';
    if(htime == data.currentTime){
      bmessage = '缓冲中';//buffering
    }
    this.setState({
      currentTime: data.currentTime,
      playinfo: bmessage ,
    });
  }

**Comment by b-asaf** [comment]
@kaifah - as a work around its a great solution!

**Comment by kashifaliquazi** [comment]
does anyone know how to fix this
?

**Comment by marlti7** [comment]
@kaifah  - what is the htime? state.currentTime?

**Comment by ivanhuay** [comment]
same issue here 😢  onBuffer not working on android 

```
"react-native-video": "^5.0.2",
"react": "^16.12.0",
"react-native": "0.60.5",
```

**Comment by helciofranco** [comment]
Same here, onBuffer is not firing! 
Only on Android. 

Before the update (tô the RN 0.61.5 and RN-video to version 5) it was working.

`"react": "16.9.0",
"react-native": "0.61.5",
"react-native-video": "^5.0.2"`

**Comment by IamMasterWayne** [comment]
+1

**Comment by bananer** [comment]
`onBuffer` is only called when you are using exoplayer on android. During the RN upgrade with autolinking it might habe been reverted to the default player.

This line in `android/settings.gradle` makes it work for me:

```gradle
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Comment by prisar** [comment]
@bananer didn't work for me. still looking out for solution. is there any other way?
