### ISSUE TITLE
[Android] Api not consistent between android and android-exoplayer packages

### ISSUE THREAD

**Issue by pawlowskim** [TheWidlarzGroup/react-native-video#806]
Hello :)

I just wanted to say that event "onProgress" and it "playableDuration" property is different between android (MediaPlayer) and android-exoplayer returns different values.

For streaming videos:
-MediaPlayer, playableDuration is progress of buffer for remote video in seconds / milliseconds (don't remember, sorry for that).
- ExoPlayer, playableDuration is progress of buffer for remote video in percentage size of the video / 1000. 

To make it equal, we need to do some math for exoplayer:
```
const playableDurationFromPercentage = videoDuration * playableDuration * 10;
```

Events from r-n-video should be documented somewhere :/

**Comment by cobarx** [comment]
This should be fixed by #1018.

Yes, the events definitely need to be documented. I'm planning on adding that at some point along with a complete list of all the props and which platforms support them.
