### ISSUE TITLE
Videos not playing, white background, android 4

### ISSUE THREAD

**Issue by jackmead515** [TheWidlarzGroup/react-native-video#807]
I have a client using a Motorola Droid Bionic, Android Version 4.1.2

No videos can be played. When the user presses the play button, the background turns white. Thumbnails are able to render.

**Comment by cloudsafe** [comment]
show your code

**Comment by jackmead515** [comment]
What portions would be best for you to see? My components are fairly large, so if there are snippets that I can show you, I can condence them for you.

**Comment by cloudsafe** [comment]
```
<Video
                                 
                                    style={{width:videoWidth,height:videoHeight}}
                                    source={{uri:'http://xxx.com/xxx/xxx/xxx.mp4'}}
                                    
                                    muted={true}
                                    paused={false}
                                    repeat = { true }
                                    resizeMode={'cover'}
                                />
```
you can try it.don't forget set video size(width/height)

**Comment by Drey23** [comment]
Hi, 

Same problem here. Works well in iOS, but in Android I get a white screen

```
<Video {...{
          source     : backgroundVideo,
          muted      : true,
          repeat     : true,
          paused     : false,
          style      : Styles.video,
          resizeMode : 'cover',
        }} />

  video : {
    position : 'absolute',
    top : 0,
    left : 0,
    bottom : 0,
    right : 0,
  },
```

**Comment by ScreamZ** [comment]
Any updates on that ?

**Comment by yayanartha** [comment]
Any updates?

**Comment by ScreamZ** [comment]
@yayanartha I think that's because the parent container has no size, check with `flex: 1`,

I also made a library to abstract some of those things, https://github.com/ScreamZ/react-native-true-sight

**Comment by Drey23** [comment]
We solved this and many others returning to Native Android.
