### ISSUE TITLE
android-exoplayer android4.4,orientation was wrong.the portrait video,playing was display landscape

### ISSUE THREAD

**Issue by cloudsafe** [TheWidlarzGroup/react-native-video#808]

**Comment by timhonders** [comment]
I added a pull request what fixed the problem for me (Android 7) https://github.com/react-native-community/react-native-video/pull/842

**Comment by ghostknow** [comment]
I already add this code.
https://github.com/react-native-community/react-native-video/pull/842/files
but it's not work
