### ISSUE TITLE
.avi format

### ISSUE THREAD

**Issue by hadrienbbt** [TheWidlarzGroup/react-native-video#809]
Hello everyone,
I'm using react-native-video and noticed that the videos I fetch from my server don't display when the format is .avi. The <Video> container remains black.
.mp4 and .mov formats work well. 
onLoad, onProgress and onEnd are triggered, and onError doesn't show up. 
Is there a way to display .avi format videos without touching the native code ?

**Comment by Thanmai-C** [comment]
How did u resolve this issue,?
This component plays mp4 videos well, but throws error if it is .avi video file

**Comment by basim-usman** [comment]
facing the same issue how to resolve it any help ?

**Comment by dev-sathish** [comment]
This player uses Exo player for the video playback in android here we can't able to play .avi since .avi is not supported by exo-player. Please see
https://exoplayer.dev/supported-formats.html
