### ISSUE TITLE
Playing video and audio at the same time

### ISSUE THREAD

**Issue by eltoob** [TheWidlarzGroup/react-native-video#81]
Hey
I am trying to play a mp4 file and add the background of a MP3 file. Is there  a way to specify an audio source for a video?

**Comment by brentvatne** [comment]
@eltoob - alas no, but what you could do is have a second instance and unpause them both at the same time - the start time for both should be the very very close to the same if they're rendered at the same time. If you're interested in adding this functionality a PR would be welcome!

**Comment by AkramSyed002** [comment]
Hi there is any one active this,
