### ISSUE TITLE
Video start callback

### ISSUE THREAD

**Issue by vicA340** [TheWidlarzGroup/react-native-video#812]
I am trying to add a callback function that is called each time the video is started.  I tried using the onStart callback but nothing is happening.  I was wondering if anyone else had a similar issue and if there is anyway to resolve this.  Thanks in advance.

**Comment by n1ru4l** [comment]
@vicA340 I think there is only a `onLoad` callback.

**Comment by djw27** [comment]
There is no `onStart` callback.

Your best bet is to use the `onVideoProgress` callback at the moment

**Comment by afilp** [comment]
I would also need an `onStart` callback, thank you!
