### ISSUE TITLE
Closing fullscreen onEnd

### ISSUE THREAD

**Issue by kay-is** [TheWidlarzGroup/react-native-video#813]
I want to close the fullscreen player `onEnd`

I tried two approaches.

Calling `presentFullscreenPlayer()` in the `onEnd` handler, which did nothing.

Setting a `playing` state to `false` in the `onEnd` handler causing the `<Video>` component not to be rendered anymore, which showed a black screen that forces me to restart the app.

**Comment by kay-is** [comment]
Crawling through the code I found the undocumented `dismissFullscreenPlayer` method.

The _toggle_ in the docs implied I could use `presentFullscreenPlayer` for enabling and disabling the player. I fixed this in the docs.

**Comment by jayasme** [comment]
@kay-is You saved my life!
