### ISSUE TITLE
Fail to play video from library

### ISSUE THREAD

**Issue by trops** [TheWidlarzGroup/react-native-video#817]
This worked before the update, and now I see a blank screen. The url it is trying to play looks like this 

```
assets-library://asset/asset.mov?id=43996B9D-D47E-455F-9093-C464016D3197&ext=mov
```

Using the uri to play this video 

```
<Video
          source={{ uri: <my uri here> }}
```
This was working fine, and now looking for a way to resolve.

**Comment by shawnFallon** [comment]
I have the same issue.  The path is passed in as props from react-native-camera.

I have also tried the type: 'mov' parameter:
```
  <Video
    source={{uri: 'assets-library://asset/asset.mov?id=8C30FCCA-FCEE-4D2B-BA0A DE30FB836AD7&ext=mov', type: 'mov'}}

```

thanks in advance.

**Comment by kumarnitishraj** [comment]
I have also the same issue. It is showing the blank screen only.

**Comment by shawnFallon** [comment]
I did end up sorting this out for myself. In my case, It was a matter of adding the camera values within the this.camera.capture as follows:  
```
  startRecording = () => {
    const {onStartVideoDataProccessing, onVideoDataProccessed} = this.props;
    console.log("Inside startRecording, this.camera = ", this.camera);
    if (this.camera) {
      onStartVideoDataProccessing();
      this.camera.capture({
        mode: Camera.constants.CaptureMode.video,
        audio: true,
        quality: "480p",
        target: Camera.constants.CaptureTarget.disk,
        }).then(data =>  {
          onVideoDataProccessed(data);
          }
        );
        return this.setState({ isRecording: true});
    }
  }

```
When I added the target, my video was viewable.

**Comment by hannigand** [comment]
Bump 🤛

I got it working when using `Camera.constants.CaptureTarget.disk`. However, I am aiming to save it to the Camera Roll and then playing it in react-native-video, the `assets-library..` URI is not working.

**Comment by card-b** [comment]
I also solved this for an arbitrary assets-library:// uri by using React Native FS to convert the asset link to a file:// path. 

```
RNFS.copyAssetsVideoIOS(assetUri, RNFS.TemporaryDirectoryPath + "temp.mov").then(res => {
	const filePathUrl: "file://" + res;

	//filePathUrl works for me in <Video source={{uri: filePathUrl}} />
});
```
