### ISSUE TITLE
React Native iOS I got some error when I use vdo player with HLS Streaming URL

### ISSUE THREAD

**Issue by wsupajirakit** [TheWidlarzGroup/react-native-video#818]
React Native iOS I got some error when I use vdo player with HLS Streaming URL

    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-video": "^2.0.0",

My error on iOS is :

1st URL : it's a problem

http://www.atxmediaserver.com:1935/TV_muslim1/TV_muslim1/chunklist_w1520826529.m3u8

**some link it's return RedScreen with "Error calling RCTEventEmitter.receiveEvent folly::tojson: JSON. object value was n NaN or INF"**

2nd URL : it's work

http://ch3-33.cdn.byteark.com/live/playlist_720p/index.m3u8

**_but on Android it's work don't have any error._**

```


import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Video from 'react-native-video';
export default class App extends Component<{}> {

    constructor(props) {
        super(props);
    }
    state = {
    rate: 1
    };

  render() {
    return (
      <View style={styles.container}>
            <Video
            source={{uri: 'http://www.atxmediaserver.com:1935/TV_muslim1/TV_muslim1/chunklist_w1520826529.m3u8'}}
            />
      </View>
    );
  }
}
```

**Comment by YuriBely** [comment]
I had the same problem after upgrading to iOS11. There is temporary workaround:
![temporary solution for hls seek nan error](https://user-images.githubusercontent.com/17906018/32373663-68429e16-c0ab-11e7-8ea6-e82c45570ff4.png)
