### ISSUE TITLE
OnLoad issue

### ISSUE THREAD

**Issue by selimonline** [TheWidlarzGroup/react-native-video#819]
I have 10 videos in a single page...
I want to start playing when user click on play button. I have figured out it. But it seems, all videos are getting preloaded when page load first time.. Is there any way to set, don't load videos until my click...

Thanks

**Comment by selimonline** [comment]
NVM, I fixed it

**Comment by markmorcos** [comment]
@salimbutex how did you fix it?

**Comment by selimonline** [comment]
can u explain your current requirements. Then I can help you may be...

**Comment by markmorcos** [comment]
@salimbutex I have a large list of videos and I don't want them to preload unless I click on the play button.

**Comment by selimonline** [comment]
well, my idea,  you can use thumbnail for all videos. and when user click on it then create player component with autoplay.

**Comment by markmorcos** [comment]
@salimbutex will try it, thanks!

**Comment by siddushar** [comment]
@salimbutex i used thumbnail for video and when i click on thumbnail popup screen will open for playing video. but when i click on thumbnail image it takes time to open popup screen(this is because popup opens only after video loads completes. video loading taking much time)
