### ISSUE TITLE
Not working in react-native@0.9.0-rc

### ISSUE THREAD

**Issue by danscan** [TheWidlarzGroup/react-native-video#82]
I'm working on a new app using react-native@0.9.0-rc.  There are a number of issues I'm encountering.

To start, I can't get video to play.  The first issue seemed to be that when setting nativeProps for RCTVideo using `merge`, `src` and a number of other props were being excluded.

After changing that to a more explicit assignment (specifying relevant values from `this.props` individually), I now have an issue where it seems to init Video twice, and then gets caught in a loop.

Any ideas?

**Comment by sonthonaxrk** [comment]
What actually get's passed to the `<RCTVideo/>` element in react-native@0.8.0 and react-native@0.9.0 is identical. 

A preliminary investigation tells me that, `- (void)setSrc:(NSDictionary *)source` never gets called when using the latest version of react-native.

https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L175

**Comment by sonthonaxrk** [comment]
So `- (void)setSrc:(NSDictionary *)source` _will be called_ if src is passed in as a separate prop. Now another problem becomes apparent. 

The view has no `self.bounds` property.

**Comment by sonthonaxrk** [comment]
So if you insert a `-(void)reactSetFrame:(CGRect)frame` function into the RCTVideo.m the frame passed has no dimensions.

**Comment by yamill** [comment]
I'm having the same issue.

**Comment by brentvatne** [comment]
Does this help at all? https://github.com/brentvatne/react-native-video/pull/84

Published in 0.5.1

**Comment by yamill** [comment]
@brentvatne perfect, it's now working :smile:
