### ISSUE TITLE
Implement `requiresMainQueueSetup`

### ISSUE THREAD

**Issue by bfanger** [TheWidlarzGroup/react-native-video#820]
react-native 0.49.3 generates a warning:
> Module RCTVideoManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by jeffzing** [comment]
and you can not hot loading the scence
