### ISSUE TITLE
View.propTypes is deprecated 👻

### ISSUE THREAD

**Issue by gran33** [TheWidlarzGroup/react-native-video#822]
Hi,
Can someone plz quick fix this warning in this line:
https://github.com/react-native-community/react-native-video/blob/961baedb26716b0227f08e9cb94b42853910053c/Video.js#L311 
```
Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

Thanks in advance.

**Comment by mandriv** [comment]
@gran33 there is a pending PR for this issue since May - https://github.com/react-native-community/react-native-video/pull/607

**Comment by mandriv** [comment]
@gran33 Updating your `package.json` with `"react-native-video": "git://github.com/react-native-community/react-native-video.git#master"` fixes the problem

**Comment by masarusanjp** [comment]
@react-native-community
 
When are you going to release a version that fixed this problem?

**Comment by cobarx** [comment]
Version 2.1.0 was just released.
