### ISSUE TITLE
Webm support?

### ISSUE THREAD

**Issue by fritsvt** [TheWidlarzGroup/react-native-video#825]
Hello,

I have been able to load in mp4's in the player but webm's don't seem to load for me.

And now I'm wondering if webm is currently supported by the package.

**Comment by wilbyang** [comment]
hi, do you get answer from it?

**Comment by fritsvt** [comment]
Obviously not

**Comment by reactdevrocks** [comment]
??

**Comment by ikedj** [comment]
??

**Comment by seyedmostafahasani** [comment]
It supports `webm`.  I've tested it with the latest version, and it works correctly.

**Comment by NguyenHoangMinhkkkk** [comment]
> It supports `webm`. I've tested it with the latest version, and it works correctly.

im tested. just only play on android, not for IOS. do u have any idea about ?

**Comment by freeboub** [comment]
AVPlayer doesn't support webm playback ...
