### ISSUE TITLE
<Image> with children is deprecated

### ISSUE THREAD

**Issue by nakarin0528** [TheWidlarzGroup/react-native-video#826]
![warning](https://user-images.githubusercontent.com/22139186/31858226-728b0390-b72d-11e7-818f-46e4771516fe.png)

**Comment by travismgibson** [comment]
Same issue..any ideas?

**Comment by djw27** [comment]
I don't think this is an issue with this library. There's only one use of the `<Image />` component within the library and it has no children: https://github.com/react-native-community/react-native-video/blob/master/Video.js#L230

**Comment by cobarx** [comment]
Yes this is almost certainly coming from a different module.
