### ISSUE TITLE
seek not work

### ISSUE THREAD

**Issue by Iliker** [TheWidlarzGroup/react-native-video#83]
```
<Video source={...} seek={20.0} 
     rate={1}
     volume={1.0} 
     muted={false} 
     paused={false}
     resizeMode="cover"
     repeat={true}     
/>
```

I need to start playing at a specific time，but  not  work
I don't know why.... help..

**Comment by qingfeng** [comment]
The same question

**Comment by brentvatne** [comment]
You need to call `seek` on the ref

`<Video ref="someVideo" {...otherProps} />`

later..

`this.refs.someVideo.seek(someTime)`

Let me know if this fixes your issue!

**Comment by Iliker** [comment]
@brentvatne You are right!  Thanks!

**Comment by Iliker** [comment]
react-native@0.9
rect-natvie-video@5.1
but seek no work

```
let time = new Date().getTime() / 1000;
time = time - startTime
this.refs['_video'].seek(time)
```

**Comment by qingfeng** [comment]
After the upgrade, I have encountered this problem

**Comment by qingfeng** [comment]
I try to modify, you can run:

https://github.com/brentvatne/react-native-video/blob/master/RCTVideo.m#L306
`if (item && (item.status == AVPlayerItemStatusReadyToPlay || item.status == AVPlayerItemStatusUnknown)) {`

**Comment by brentvatne** [comment]
Is this working for you guys @qingfeng @Iliker? Can you submit a PR if not? Thanks!

**Comment by stereodenis** [comment]
@brentvatne close issue?

**Comment by nwaughachukwuma** [comment]
Was this problem ever solved? I am trying to return the seek to 0 after the video is done playing (onEnd), using this.player.seek(0) but I get undefined is not an object (evaluating _this.player.seek)

**Comment by sami3898** [comment]
did anybody solved this issue?

**Comment by sami3898** [comment]
> Was this problem ever solved? I am trying to return the seek to 0 after the video is done playing (onEnd), using this.player.seek(0) but I get undefined is not an object (evaluating _this.player.seek)

Did you solve this?

**Comment by nwaughachukwuma** [comment]
Hi @sami3898, see what I ended up doing

```javascript
// method
 onEnd = () => {
    if (this.player) {
      this.player.seek(0);
    }
  };

// JSX
<View style={styles.container}>
     <Video
         ref={ref => (this.player = ref)}
         ...other props
      />
     ...other logic
</Video>
```

And yes, it worked for me.

**Comment by raghvendra007** [comment]
it's still not working 
  if(videoref?.current){
            console.log("vieo ref seek",videoref.current)

            videoref.current.seek(0);
          }
  },[currIndex])

**Comment by raghvendra007** [comment]
it is giving undefined

**Comment by freeboub** [comment]
OnEnd playback is finish, then you need to restart the stream. Why not using repeat prop ? @raghvendra007

**Comment by raghvendra007** [comment]
@freeboub my case is a little different, suppose I am playing a video and go to the next video, when I go back to the previous video I want to start it from 0

**Comment by IamMasterWayne** [comment]
Trying to implement **Forward/Backword for 10 seconds.**
`videoPlayer?.current.seek(seek) `

sometimes it works, but mostly it doesn't work.

**Comment by freeboub** [comment]
> @freeboub my case is a little different, suppose I am playing a video and go to the next video, when I go back to the previous video I want to start it from 0

But starting a new playback always starts at 0 ...

**Comment by raghvendra007** [comment]
> > @freeboub my case is a little different, suppose I am playing a video and go to the next video, when I go back to the previous video I want to start it from 0
> 
> But starting a new playback always starts at 0 ...

no @freeboub it plays from where it was paused last time
