### ISSUE TITLE
android video autoplay even if paused={true}

### ISSUE THREAD

**Issue by SharanyaRao91** [TheWidlarzGroup/react-native-video#830]
I followed PR #625 but video continues to autoplay when rendered. I manually added "mActiveStatePauseStatus = paused;" to my ReactVideoView.java file.  Here is what I have (RN - 0.44; react-native-video - 2.0.0) -
rate={0} //paused
paused={true}
volume={1}
muted={false}
playInBackground={false} // Audio continues to play when app entering background.
playWhenInactive={false}
ignoreSilentSwitch={"obey"}
resizeMode="cover"
onError={e => console.log(e)}
onLoad={load => console.log(load)}
repeat={false}

**Comment by gedu** [comment]
Hey maybe this helps I have it like this:

`style={styles.backgroundVideo}
                ref={this.videoReference.bind(this)}
                onLoad={this.videoOnLoad.bind(this)}
                onError={this.videoError.bind(this)}
                resizeMode="cover" paused={this.state.paused}
                rate={1} volume={this.state.videoVolume} muted={false} repeat={false} key="video2" `

and I'm pausing the video like this

AppState.addEventListener('change', this._handleAppStateChange);
`_handleAppStateChange = (nextAppState) =>
    {
        this.playVideoFromStart();
        this.pauseVideo();
        this.setState({appState: nextAppState});
    }`
where pause video just setState({paused:true})

note: also I had to add the fix from the PR #625

**Comment by deehuey** [comment]
Can you share more of this code ^? I am unable by any means to get android to stop playing.  I'm more asking, what is `this.playVideoFromStart()` and `this.pauseVideo()` methods?

**Comment by gedu** [comment]
@deehuey sure!


```
constructor()
    {
      super();
      this.player;
      this.state = {
        paused: true,
        videoError: false,
        appState: AppState.currentState,
        videoVolume: 1.0
      };
    }

componentDidMount()
    {
      AppState.addEventListener('change', this._handleAppStateChange);
    }

_handleAppStateChange = (nextAppState) =>
    {
      if(!this.state.videoError)
      {
        this.playVideoFromStart();
        this.pauseVideo();
      }
      this.setState({appState: nextAppState});
    }

playVideoFromStart()
    {
      if(this.player != null) this.player.seek(0);
    }

pauseVideo()
    {
      this.setState({paused: true});
    }

  renderVideoSlide()
    {
      return <TouchableOpacity style={styles.videoView}
                       onPress={this.onPlayOrPauseVideo.bind(this, this.state.paused)}>

              {!this.state.videoError && <Video source={require('../../assets/videos/home_video.mp4')}
                style={styles.backgroundVideo}
                ref={this.videoReference.bind(this)}
                onLoad={this.videoOnLoad.bind(this)}
                onError={this.videoError.bind(this)}
                resizeMode="cover" paused={this.state.paused}
                rate={1} volume={this.state.videoVolume} muted={false} repeat={false} key="video2" />}
             
              {this.state.paused && !this.state.videoError &&
                  <Image style={styles.videoIcon}
                         source={require('../../assets/icons/btn-play/btn-play.png')}/>}
            </TouchableOpacity>;
    }
```

+ the PR #625

**Comment by abrown1982** [comment]
Bit of a hack, but if you pass the endWithThumbnail={true} prop then the repeat bug does not occur on iOS

**Comment by hoscarcito** [comment]
I'm also facing this problem, PR #625 is not working either. 

What I'm trying to accomplish is to start/stop the video depending it's being shown by the scrollview or not. I'm passing a prop "isViewable" to the component and nothing happen. My idea is to give the autoplay to start fetching the video when the component is loaded but pause it until is on screen.
Is there any other way to do it? Will this work as intended?
Thanks!

**Comment by cobarx** [comment]
I cleaned up the pause code for both MediaPlayer & ExoPlayer and am pretty sure this is resolved. Reopen if not.
