### ISSUE TITLE
iOS 11 repeat with m3u8 video repeats only once

### ISSUE THREAD

**Issue by jalieven** [TheWidlarzGroup/react-native-video#831]
We observed the fact that our videos are only looping once after which they are stuck on the last frame on iOS 11. While we encountered no problems of the sort in lower iOS versions. Looking at the code it all boils down to the AVPlayerItemDidPlayToEndTimeNotification observer not getting called after the first repeat. While the _repeat variable doesn't change and the removeFromSuperView nor the dealloc methods get called while looping (these methods remove the AVPlayerItemDidPlayToEndTimeNotification observer). So I am quite baffled on how it is that this observer isn't getting called after the first loop. So to be clear: the AVPlayerItemDidPlayToEndTimeNotification observer method is called once after which the video stops and doesn't get repeated. Also worth noting is that this only occurs with m3u8 videos. Our mp4 variants work fine.

**Comment by itaydressler** [comment]
Same here. iOS 11, m3u8, repeats only once.

**Comment by ftuckey** [comment]
Same here.

**Comment by JonChristensen** [comment]
@jalieven have you been able to find a work around for this? We're currently pretty badly stuck on it.

**Comment by jalieven** [comment]
@JonChristensen No progress from my part. Not sure when I could look into this and try to work around the problem.

**Comment by jalieven** [comment]
FWIW There appears to exist another way to loop video with AVPlayer:

```player = AVQueuePlayer()
playerLayer = AVPlayerLayer(player: player)
playerItem = AVPLayerItem(url: videoURL)
playerLooper = AVPlayerLooper(player: player, templateItem: playerItem)
player.play()
```
I haven't tried to integrate this into the react-native-video though. Don't know if this fixes the problem for hls video on iOS 11.
Another possible (less optimal) workaround would be to obtain the length of the movie on the first succesful complete run of the video and on the second run monitor the progress and act accordingly. This can prolly be done in the sendProgressUpdate method of RCTVideo.m.

**Comment by zachrnolan** [comment]
Running into the same issue. If anyone has a workaround, please let me know.

RN 0.54.1
react-native-video 2.0.0

**Comment by SheldonWangRJT** [comment]
Is this solved in react-community? 

I am seeing the same behavior on **native** iOS 12.2. 

I do have a work around, which is to observe the current playing time of the playerItem, once it reaches the end, call reply function.
