### ISSUE TITLE
Playing audio over earpiece

### ISSUE THREAD

**Issue by andrenanninga** [TheWidlarzGroup/react-native-video#835]
Would it be possible to add a feature to play audio over the earpiece?

I am using this library to play video and audio for tours in museums and we would like to use the earpiece instead of the speaker to maintain a quiet atmosphere in the museum.

For Android it seems to be possible to change the audio output using a [method like this](https://github.com/react-native-community/react-native-video/blob/7f2cd8751a1a7e5b4cf3b6b50916156bee7c63b0/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L272-L275) but changing `AudioManager.STREAM_MUSIC` to `AudioManager.STREAM_VOICE_CALL`.

I am less familiar with iOS but according to [this stackoverflow post](https://stackoverflow.com/questions/18026578/play-audio-through-upper-phone-call-speaker/24418204#24418204) and doing something like this:

```
NSError *error = nil;
// Get the current session
AVAudioSession *session = [AVAudioSession sharedInstance];
AVAudioSessionPortDescription *routePort = session.currentRoute.outputs.firstObject;
NSString *portType = routePort.portType;

// Toggle between speaker and earpiece
if ([portType isEqualToString:@"Receiver"]) {
       [session  overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:&error];
} else {
       [session  overrideOutputAudioPort:AVAudioSessionPortOverrideNone error:&error];
}
```

It might be cool to add a prop to `<Video />` to enable the earpiece, something like `<Video src="/tour.mp3" earpiece={true/false} />`.

Curious to hear what you think about this feature and how to implement it.

Thanks.

**Comment by cobarx** [comment]
@FakeYou Would you be interested in creating a PR for this? It's a neat feature and would be great to support it. I won't be able to get to this for awhile and it'll take some testing to make sure toggling back and forth works correctly, so if you could do it, it will get merged a lot sooner.

I would suggest calling it something like `audioPort={"default"|"headset"}` or whatever the correct term is.

**Comment by andrenanninga** [comment]
I recently implemented a similar feature in a native Android app and got it to work for my use cases. I will take a look if I can port this implementation to React Native. I am unfamiliar with developing native iOS apps but I can take a look if I have the time.

**Comment by andrenanninga** [comment]
@jordibruin we didn't end up needing it any React Native apps only in a native Android app. In Android I was able to solve it using the method described in the original post, using `AudioManager.STREAM_VOICE_CALL`. For iOS I unfortunately never had the opportunity to take a look at it.

**Comment by CHaNGeTe** [comment]
Added to roadmap when we hit the audio manager refactor

**Comment by thedanhoffman** [comment]
I would love it if this could happen. I need something that allows custom buffering amounts and can play over the earpiece

**Comment by mysport12** [comment]
I am trying to incorporate this functionality as well. I am not an Android or iOS dev, but took a shot at implementing on both platforms. iOS seems to be working (at least for my use case), but I haven't tested Android yet. Happy to create a PR when both iOS and Android are working correctly.

https://github.com/mysport12/react-native-video
