### ISSUE TITLE
Pause Live Stream

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#837]
How can I pause the live stream and stop it for buffering, i tired to set the `paused` props to false while on streaming, live stream are still streaming. Any idea ?

**Comment by mauriziocarella** [comment]
Any news?

**Comment by fidelsam1992** [comment]
To be able to stop and then play from the live stream at the latest time, I've add this line that had the issue fixed

```ReactExoplayerView.java```

```
public void setPausedModifier(boolean paused) {
        isPaused = paused;
        if (player != null) {
            if (!paused) {
                player.seekTo(player.getDuration()); //CUSTOM
                startPlayback();
            } else {
                pausePlayback();
            }
        }
    }
```
