### ISSUE TITLE
Know when video is fully buffered

### ISSUE THREAD

**Issue by robcalcroft** [TheWidlarzGroup/react-native-video#838]
I'd like to know when the cache is fully populated with the entire video contents. onBuffer seems to just occur at the start and then when the video starts playing but on a good connection you don't see it again. onLoad seems to happen fairly quickly too. Is there a way to see when the whole video could be scrubbed / played through offline in memory?

**Comment by cobarx** [comment]
You can look at the progress update events and see if the seekableDuration is the same as the playableDuration. I just merged this for Android, so I believe it's there on iOS, Android, and ExoPlayer.

This might be worth adding as a separate event at some point in the future.

**Comment by ghyzx** [comment]
Then, how to get the buffer data ？I want to have it stored locally.
