### ISSUE TITLE
"Error calling RCTEventEmitter.receiveEvent" on IOS react-native

### ISSUE THREAD

**Issue by TheIdhem** [TheWidlarzGroup/react-native-video#841]
![31045178-0b6bb6c2-a608-11e7-8c15-24dc9a9e4ee1](https://user-images.githubusercontent.com/31737620/32313913-58e465b8-bfba-11e7-8c7b-8dcff978648a.png)
hellow! is there any body know what should I do for this?this issue same like the #802 issue but that answer isn't work for me!!plz do not close this issue before I accept that answer!!I should say that I use react-native-video-contorols

**Comment by TheIdhem** [comment]
I found out that this issue only occurs on iOS 11 and it works fine on iOS 10!!

**Comment by edwardlai3582** [comment]
hi @TheIdhem , did you come up with a solution? Thanks!

**Comment by adamsoffer** [comment]
Any resolution here?

**Comment by YuriBely** [comment]
Hi @TheIdhem
I had the same problem after upgrading to iOS11. There is temporary workaround:
![32373663-68429e16-c0ab-11e7-8ea6-e82c45570ff4](https://user-images.githubusercontent.com/17906018/36385771-970ac8f6-15a4-11e8-9036-efae9bf20542.png)

**Comment by gilra2000** [comment]
+1

**Comment by wangliguang** [comment]
@YuriBely  Is there a sequela？
