### ISSUE TITLE
Local files not working on iOS

### ISSUE THREAD

**Issue by eliasws** [TheWidlarzGroup/react-native-video#846]
I'm trying to use react-native-video on iOS to play previously downloaded mp4s. 
Android and HTTPS links on iOS work fine, but playing local files is not working.

Any suggestion/idea how to resolve this issue?

Example:

this.props.source is: 

{uri: "file:///Users/test/Library/Developer/CoreSimulator/Devices/4DF4423B-11DE-434B-BFAF-5EB196F9A44D/data/Containers/Data/Application/387BE037-28BB-41C0-BA45-45250675AF27/Documents/data/ftp/test/video/SampleVideo_1280x720_2mb.mp4"}

   <Video
                     ref={component => this._videoPlayer = component}
                     source={this.props.source}
                     onLoadStart={(err) => console.log("Video load start: " + JSON.stringify(err))}
                     onLoad={(err) => console.log("Video load: " + JSON.stringify(err))}
                     onError={(err) => console.log("Video error: " + JSON.stringify(err))}
                     onProgress={(progress) => this.onSetTime(progress)}
        />

"react-native": "0.49.3"
 "react-native-video": "^2.0.0"

**Comment by eliasws** [comment]
Can be closed.

Try to use "encodeURI("file://" + video.path)" instead of the raw path.

**Comment by univalchemist** [comment]
> Can be closed.
> 
> Try to use "encodeURI("file://" + video.path)" instead of the raw path.

It does not work.

**Comment by Aycom366** [comment]
This issue still persist @eliasws 
It doesn't work

**Comment by eliasws** [comment]
@Aycom366 Sry, cannot help here as I haven't worked with this library for seven years.

**Comment by sandipmishraarp** [comment]
> Can be closed.
> 
> Try to use "encodeURI("file://" + video.path)" instead of the raw path.

not working
