### ISSUE TITLE
Playback speed inconsistent behaviour 

### ISSUE THREAD

**Issue by elaffey** [TheWidlarzGroup/react-native-video#848]
I am using the latest version of react-native-video:

```json
"react": "16.0.0"
"react-native": "0.49.5"
"react-native-video": "2.0.0"
```

Seeking through a video on iOS sometimes causes the playback speed to be at the default rate regardless of any value passed into the `rate` prop. Furthermore on Android using the `rate` prop is not working at all. 

I have brought up issues with the playback rate on Android in issue: #584

**Comment by antoxann96** [comment]
@EamonnLaffey Hi. Do you have solution for this issue? Faced the same Android `rate` problem

**Comment by elaffey** [comment]
@antoxann96 I have not been able to find a solution unfortunately.

**Comment by cobarx** [comment]
Setting the rate is now supported on Android Media Player but only on 6.0 and up. You should use ExoPlayer since it works on all versions of Android.

There was an issue where when you paused the video on iOS it would wipe out the rate setting. That has been fixed and may have been your issue.
