### ISSUE TITLE
Can't install package getting error 1

### ISSUE THREAD

**Issue by isAlmogK** [TheWidlarzGroup/react-native-video#851]
I'm getting the following error 

enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-video-player/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-video-processing/package.json'

when I run - npm install --save react-native-video

**Comment by thatjuan** [comment]
I'd try `rm -rf node_modules package.lock && npm install` then `react-native link`

Also, I'd recommend switching to [yarn](https://yarnpkg.com/en/) from npm. I was reluctant for awhile, but I should've done it sooner. It's way way faster, it prints clearer errors and you don't have to deal with npm/node version compatibility bs..

**Comment by cobarx** [comment]
I'd try what @thatjuan suggested
