### ISSUE TITLE
How to play .m3u8 in file system on Android?

### ISSUE THREAD

**Issue by uimeet** [TheWidlarzGroup/react-native-video#853]
Hi there.

I tried:
`<Video source={{uri: "file:///storage/emulated/0/Download/xxxx/xxxx.m3u8"}} />`
and
`<Video source={{uri: "/storage/emulated/0/Download/xxxx/xxxx.m3u8"}} />`

"adb logcat" output some errors:
`11-16 16:31:03.021   520 27234 E ffmpeg-avlog: Error when loading first segment 'file:///storage/emulated/0/Download/xrcache/HEYDOUGA4157-031/ts/HEYDOUGA4157-031-0.ts'`
`11-16 16:31:03.022   520 27234 E FFMPEGExtractor: FFMPEGExtractor Failed open file`
`11-16 16:31:03.024 26433 27043 E MediaPlayer: error (1, -2147483648)`

I am sure all ts files are exists and I use other android player can play this .m3u8 file.

thx.

**Comment by karltaylor** [comment]
Try adding `type`.

```javascript
<Video source={{ uri: videoUri, type: 'm3u8' }} />
```

**Comment by uimeet** [comment]
Thx @karltaylor and it is not work.

**Comment by uimeet** [comment]
OK...I found a way to solve it.
I use [react-native-static-server](https://github.com/futurepress/react-native-static-server) run a internal web server to hosting .m3u8 file for Android MediaPlayer.

It is not prefect, but it is working. :)
