### ISSUE TITLE
Can't play video in example!

### ISSUE THREAD

**Issue by thiennhank9** [TheWidlarzGroup/react-native-video#854]
Hi guys, I'm new to this lib. After using code in example project, I can't play video by uri or file. Can someone have a simple play video by this lib from youtube.

**Comment by devanshsadhotra** [comment]
same issue to me too

**Comment by GT-3** [comment]
same here
<img width="364" alt="screen shot 2017-12-07 at 10 59 04" src="https://user-images.githubusercontent.com/6053149/33706747-b837a428-db3d-11e7-831a-7a11786c37d3.png">

**Comment by ksegla** [comment]
@GT-3 
I had the same problem with the example, activated Debug Mode and got a nice message suggesting that there was no export. You need to add something like "export default" and get "export default class VideoPlayer extends Component" if you want to do <VideoPlayer />
