### ISSUE TITLE
Progressive Downloading - Supported or Not Supported?

### ISSUE THREAD

**Issue by rmutter** [TheWidlarzGroup/react-native-video#855]
Has anyone been able to get progressive download working with the video player? I have not been able to find any mention of "progressive" across Github Issues or PRs. I am trying to serve mp4's from Amazon's S3 / Cloudfront and it seems that the video player on iOS will show the thumbnail (first frame) of the video then wait until the video is entirely downloaded to start playing it.

On poorer network conditions this is not optimal as it can take quite awhile for the whole video to load. If this library does work with progressive downloading than it must be something with my videos + serving them through Cloudfront that is not working, I just wanted to get a sanity check. I have checked that the moov atom / metadata is at the front of my videos so in theory this should work.

Thanks for any help or insight anyone can give!

**Comment by djw27** [comment]
We're solving this problem by using HLS videos. If this isn't an option for you then this is the closest discussion I've come across to what you're asking https://github.com/react-native-community/react-native-video/issues/99

**Comment by thatjuan** [comment]
Progressive download does work, but the server has to support byte range requests. See [this sample app](https://github.com/ndea/rstreamor) and [the spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range). This is generally simple to implement, but I really don't know if S3/CloudFront support it.

You can test it by hitting the video url directly from Safari in iOS. If it starts playing right away, it means the server supports it. In my experience, whatever plays in Safari iOS will work in this video player as well.

**Comment by n1ru4l** [comment]
Seems like s3 supports range requests for GET https://stackoverflow.com/a/28166834/4202031

**Comment by Not-Qualified** [comment]
> Progressive download does work, but the server has to support byte range requests. See [this sample app](https://github.com/ndea/rstreamor) and [the spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range). This is generally simple to implement, but I really don't know if S3/CloudFront support it.
> 
> You can test it by hitting the video url directly from Safari in iOS. If it starts playing right away, it means the server supports it. In my experience, whatever plays in Safari iOS will work in this video player as well.

@thatjuan , Are you sure that Progressive Download does supported by react-native-video ?
because, I'm making a tiktok like application and I'm using react-native-video within flatlist to make a list of videos and video is getting fully dowloaded even if i've not played it whole

**Comment by vamsichadaram123** [comment]
@Not-Qualified I am trying react native reels feature but I was facing same issue. Video getting downloaded first and then playing. Need to please without getting downloaded.
Please help @Not-Qualified  @thatjuan

**Comment by Not-Qualified** [comment]
@vamsichadaram123 , I can connect you with our main react native developer, if you want

**Comment by vamsichadaram123** [comment]
@Not-Qualified  kindly please your contact details, I will schedule a call. or please call me on my number +919949678679. Your help is very much needed as we are struggling since long to solve this issue.
