### ISSUE TITLE
Use multiple Video components on same scene

### ISSUE THREAD

**Issue by pottercomuneo** [TheWidlarzGroup/react-native-video#856]
Hi everyone! I have to render a variable number of videos, where each one is in a row of a listview. So my code is like this:
````
function _renderRow(rowData, sectionID, rowID) {
      return (
        <TouchableHighlight onPress={() => this.playFullScreen(rowID)}>
          <View>
            <Video source={{uri: rowData}}
             ref={(ref) => {
               this.player = ref
             }}
             rate={1.0}
             volume={1.0}
            ...
           />
          </View>
        </TouchableHighlight>
      );
}

function playFullScreen(rowID) {
  this.player.presentFullscreenPlayer();
 }
````
But of course only the last video rendered is played since `this.player` is overwritter each time.
How can I set the refs properly? This is what I tried and didn't work: 
- Make this.player an array (to use rowID)
- Make the ref property a string and call it in playFullScreen()

Does react-native-video support this? Thanks everybody!

**Comment by KinanKazmi** [comment]
Did you try it like this?
```
this.player[rowID] = ref;
```
and then to call it
```
this.player[0].presentFullscreenPlayer()
```
?

**Comment by KinanKazmi** [comment]
By the way, ListView is dead now and also, ListView's rendered items dont save direct references in your component. Use FlatList instead.

**Comment by pottercomuneo** [comment]
Solved! @KinanKazmi I had done what you suggest, but it didn't work: it seems that if you simply use `this.player` it is self-declared, but if you want it to be an array you have to declare it previously on the class like this
`var player = Array()`
Thanks everybody!

**Comment by ghost** [comment]
@pottercomuneo Can you elaborate further on how you solved this issue?

**Comment by pottercomuneo** [comment]
@kk1429 of course!
In the `constructor` add `this.player = Array();`
In the `Video` component, set the parameter `ref` like this:
```
ref={(ref) => {
   this.player[rowID] = ref;
}} 
```
where `rowID` is the number of your row in the list, parameter of `_renderRow()`. So `playFullScreen()` becomes:
```
function playFullScreen(rowID) {
  this.player[rowID].presentFullscreenPlayer();
}
```
