### ISSUE TITLE
Check Streaming Url are suitable

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#860]
I facing an issue that streaming a url (HLS) from other side that not sure using what setting. When I start stream, it make my app crash. Is there a way to check the url is able to stream or not / get the stream meta, so i can check what issue.

**Comment by Winglonelion** [comment]
good idea

**Comment by djw27** [comment]
I use the 'Native HLS Playback' plugin for Chrome to check if the URL can stream

**Comment by callmejm** [comment]
@djw27 Native HLS Playback check fine, but using react-native-video are same issue

**Comment by choychris** [comment]
+1
I am using android exoplayer to play .m3u8
Most times,  it is just black screen. Sometimes, it causes app crash ( my_app has been stopped ).
