### ISSUE TITLE
Play from custom stream possible?

### ISSUE THREAD

**Issue by hardcodet** [TheWidlarzGroup/react-native-video#870]
Hi all

My use case is the following: I'll have 

* some encrypted video content (probably residing in the cloud)
* that I want to decrypt on the client on the fly
* and feed it into the player as a stream.

Is this possible with this component?

Thanks!

**Comment by liamdkane** [comment]
+1

**Comment by cobarx** [comment]
This will work if you can put it into some kind of format the video player will recognize. I've seen this done by creating an HLS playlist the references a proxy that handles the stream.
