### ISSUE TITLE
undefined is not an object (evaluating _reactNative.NativeModules.UIManager.RCTVideo.Constants)

### ISSUE THREAD

**Issue by ghcm** [TheWidlarzGroup/react-native-video#873]
I tried everything to solve this problem and still getting error (for a few days already):

`import Video from 'react-native-video';`
```
 <Video
       repeat
       resizeMode='cover'
       source={{uri: "http://clips.vorwaerts-gmbh.de/VfE_html5.mp4"}}
/>
```
![screenshot from 2017-12-10 15-52-02](https://user-images.githubusercontent.com/4146753/33805281-279a4768-ddc7-11e7-99f2-861352d963dd.png)

my package.json

```
{
  "name": "courses",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-elements": "^0.18.4",
    "react-native-vector-icons": "^4.4.2",
    "react-native-video": "^2.0.0",
    "react-native-video-player": "^0.8.6",
    "react-navigation": "^1.0.0-beta.21",
    "react-virtualized-sectionlist": "0.0.4"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "prettier": "^1.1.0",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by paraswatts** [comment]
I am facing same error

**Comment by maxyegorov** [comment]
+1 getting the same error

**Comment by canfoo** [comment]
+1 getting the same error

**Comment by guharakesh** [comment]
Getting this error as well. Occasionally in the form described in https://github.com/react-native-community/react-native-video/issues/865 

Tried uninstalling/unlinking and reinstalling/relinking several times. Building fails when manually linking, with the error `React/RCTView.h` file not found, from RCTVideo.h

If I try to build just the RCTVideo project, I get a `React/RCTViewManager.h` file not found, from RCTVideoManager.h

Header search paths include `"${SRCROOT}/../node_modules/react-native/React`, recursive

**Comment by kf729ik** [comment]
Same problem here!

**Comment by guharakesh** [comment]
Using Cocoapods works! Not a solution if you're not using pods I know, but if you are, add 

`pod 'react-native-video', :path => '../node_modules/react-native-video'` 

to your podfile (be sure to point it to your actual node modules location.

**Comment by kf729ik** [comment]
Thanks @guharakesh for the advice, I'm using so I give it a try.

**Comment by kf729ik** [comment]
In Xcode it cannot find the #import <React/RCTView.h> in RCTView.h file. Has anyone experience with it ?

**Comment by olivierlesnicki** [comment]
Observing the same issue here.

**Comment by kf729ik** [comment]
I have deleted the node_modules directory, made an npm install and that solved my problem.

**Comment by devagul93** [comment]
had the same issue.
@guharakesh solution works for me 
Using Cocoapods works! Not a solution if you're not using pods I know, but if you are, add

pod 'react-native-video', :path => '../node_modules/react-native-video'

to your podfile (be sure to point it to your actual node modules location.
then cd ios
pod install
and then recompile the project.

**Comment by figure-ai** [comment]
I am facing same error

**Comment by figure-ai** [comment]
in my way. I add the libRCTVideo.a to solve my problem. my project is a iOS
![image](https://user-images.githubusercontent.com/22285194/34931399-879d29f6-fa09-11e7-9dfb-51527c9ea3eb.png)

**Comment by IgorGanapolsky** [comment]
I have the same error in my android project.  What is the workaround?

**Comment by zkeyword** [comment]
+1 The same error on android emulator

**Comment by GianniGM** [comment]
Same error on Android and iOS

**Comment by jjant** [comment]
Same error on iOS

**Comment by subelsky** [comment]
FYI this appears to be a duplicate of #468 and #237

**Comment by jeffmon** [comment]
I have the same error on iOS. Did `react-native lin`,  tried `pod install` also added `libRCTVideo.a` in Xcode. Any other solutions?

**Comment by camel113** [comment]
@jeffmon Did you remove the /ios/build folder and run again `react-native run-ios`... It worked for me

**Comment by kotelesroberto** [comment]
Run the command of react-native link and after react-native run-android.

The first command links the dependencies and after that it will work!

**Comment by EvalGitHub** [comment]
what should i do??please!!!

**Comment by sajithnwijerathne** [comment]
Just run `react-native link react-native-video` fixed my issue!

**Comment by Mohsen322** [comment]
> 
> 
> Just run `react-native link react-native-video` fixed my issue!

Hi. after doing this i got new error

> > Could not resolve com.google.android.exoplayer:exoplayer:2.9.1.
  Required by:
      project :app > project :react-native-video
   > Could not resolve com.google.android.exoplayer:exoplayer:2.9.1.

**Comment by zywu2** [comment]
`import { Video } from 'expo';`

it works for me!

**Comment by wmonecke** [comment]
This error is due to a bug with react-native link.

Open xCode and right click on your project names folder and click Add Files to "yourProjName".

Go to node modules and find react native video/ios and add RCTVideo.xcodeproj

The click this newly ad Lib and go to Products and drag and drop libRCTVideo.a into Link Binary With Libraries.

**Comment by ghost** [comment]
I have the same problem.
Was it a fix?

**Comment by jiangli1984** [comment]
+1 how to fix it?

**Comment by vivi19** [comment]
link is not work......mmp, how to fix it???

**Comment by fubar** [comment]
Following these steps with this library fixed it for me: https://github.com/joltup/rn-fetch-blob/wiki/Manually-Link-Package#user-content-link-ios-package

1. `Add files to "(project name)"`
2. Add file `node_modules/react-native-video/ios/RCTVideo.xcodeproj`
3. Add `libRCTVideo.a` under "Linked Frameworks and Libraries"

**Comment by venux92** [comment]
@fubar worked for me as well following the same steps

**Comment by rkingon** [comment]
@zywu2 solution works for me -- ditch `react-native-video` in favor of just using the `Video` component within `Expo`

**Comment by twhoff** [comment]
Re-linking may not fix the issue. For me I needed to clear out the Pods directory:

```
> cd ios
> rm -Rfd Pods
> pod install
```

Then re-build the project.

**Comment by srish** [comment]
I am using `react-native`  v0.60.4 and `react-native-cli` v2.0.1. I manually linked the libraries as per some comments in this thread to resolve the error, but ran into the error below: 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lRCTVideo
error: 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lRCTVideo is not an object file (not allowed in a library)
Command Libtool failed with a nonzero exit code
```
I was trying to avoid installing pods until very recently I learned that this step couldn't be skipped. Version 0.60 comes with CocoaPods, and there isn't any need to link the library manually ([more details](https://facebook.github.io/react-native/blog/2019/07/03/version-60)). 

So, here is what worked for me:
* Removed `~/Library/Developer/Xcode/DerivedData` 
* Unlinked all the libraries that I manually added via `react-native unlink`
* Removed all libraries from  “Link binary with libraries” list.
* Reinstalled pods using the steps in https://github.com/react-native-community/react-native-video/issues/873#issuecomment-498272297. 

Executing the build worked like a charm :)

**Comment by Lavleshmishra** [comment]
> had the same issue.
> @guharakesh solution works for me
> Using Cocoapods works! Not a solution if you're not using pods I know, but if you are, add
> 
> pod 'react-native-video', :path => '../node_modules/react-native-video'
> 
> to your podfile (be sure to point it to your actual node modules location.
> then cd ios
> pod install
> and then recompile the project.

it works for me.

**Comment by rochapablo** [comment]
I'm still getting the error on iOS

```
{
    "message": "undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')",
    "data": {
        "error": {
            "componentStack": "\n    in NavigationContainer (at app.tsx:41)\n    in PersistGate (at app.tsx:40)\n    in Provider (at app.tsx:39)\n    in App (at renderApplication.js:47)\n    in RCTView (at View.js:34)\n    in Unknown (at AppContainer.js:107)\n    in RCTView (at View.js:34)\n    in Unknown (at AppContainer.js:134)\n    in AppContainer (at renderApplication.js:40)",
            "isComponentError": true
        },
        "info": {
            "componentStack": "\n    in NavigationContainer (at app.tsx:41)\n    in PersistGate (at app.tsx:40)\n    in Provider (at app.tsx:39)\n    in App (at renderApplication.js:47)\n    in RCTView (at View.js:34)\n    in Unknown (at AppContainer.js:107)\n    in RCTView (at View.js:34)\n    in Unknown (at AppContainer.js:134)\n    in AppContainer (at renderApplication.js:40)"
        }
    },
    "class": "App",
    "method": "componentDidCatch"
}
```

```
"react-native": "^0.64.2",
"react-native-video-player": "^0.12.0",
```

**Comment by SangeethSujith** [comment]
How to fix this in android?

**Comment by hippiejuice** [comment]
How to fix this on windows?
