### ISSUE TITLE
ios videos  no sound

### ISSUE THREAD

**Issue by banli17** [TheWidlarzGroup/react-native-video#874]
i don't know why， android is ok，ios can play video ,but no voice.  not playback，and not  silent mode。
react-native 0.44
react-native-video 1.0

```
<Video
	resizeMode="cover"
	style={{
		width: WinWidth,
		height: WinWidth * 9 / 16,
		backgroundColor: '#000'
	}}
	source={{uri: 'http://58.63.233.44/v.cctv.com/flash/mp4video6/TMS/2011/01/05/cf752b1c12ce452b3040cab2f90bc265_h264818000nero_aac32-1.mp4'|| liveUri}}
	ref={(ref) => {this.player = ref}}
	onLoad={this.onLoad}
	onEnd={this.onEnd}
	playInBackground={isPlayBack}
	onError={this.videoError}
	paused={paused}
/>
```

**Comment by taylorgoolsby** [comment]
I am experiencing the same problem with the same versions.

My device is running iOS 11.2

**Comment by teng231** [comment]
Plz update .On device audio muted. i dont know how to fix it

**Comment by taylorgoolsby** [comment]
I fixed this by adding this in my `AppDelegate.m` file:
```
#import <AVFoundation/AVFoundation.h>  // import

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];  // allow
  ...
}
```

**Comment by sunweiyang** [comment]
Could it be that you just have your silent mode hardware switch enabled on your iPhone?
If you want your app to ignore the silent switch, have the following prop in your `<Video>` component:
```
ignoreSilentSwitch={"ignore"}
```

**Comment by j3rin** [comment]
I'm experiencing the same issue, any solution?

**Comment by zisheng-ai** [comment]
@sunweiyang Thanks Bro.

**Comment by amil-m** [comment]
I tried all the suggestions, finally this worked for me:

In the `AppDelegate.m` i added:

```
#import <AVFoundation/AVFoundation.h>  // import

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...

  // Play Audio in Silent Mode  
  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
  NSError *setCategoryError = nil;
  [audioSession setCategory:AVAudioSessionCategoryPlayback
                      error:&setCategoryError];
  ...
}

```

**Comment by djw27** [comment]
@amil-m https://github.com/react-native-community/react-native-video/blob/bf5974242c279ab90e1ca6613b6627635a7e0092/ios/RCTVideo.m#L650

**Comment by deathemperor** [comment]
I added the ```  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];``` on iOS 12 but still no sound on silent mode

**Comment by luongs3** [comment]
me too. Got this error on IOS 12.

**Comment by Kiran0791** [comment]
+1

**Comment by cactis** [comment]
No sound on Android, no error message.

**Comment by voxspox** [comment]
<Video
        ...
        ignoreSilentSwitch="ignore"
    />

worked for me

**Comment by naishadh-hyperspace** [comment]
`ignoreSilentSwitch={"ignore"}`

is it working on iOS 13 and is it working on Simulator ? Help!

**Comment by Naishadh8115** [comment]
> I fixed this by adding this in my `AppDelegate.m` file:
> 
> ```
> #import <AVFoundation/AVFoundation.h>  // import
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   ...
>   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];  // allow
>   ...
> }
> ```



> Could it be that you just have your silent mode hardware switch enabled on your iPhone?
> If you want your app to ignore the silent switch, have the following prop in your `<Video>` component:
> 
> ```
> ignoreSilentSwitch={"ignore"}
> ```

This is not working for me, iOS 13 in simulator.

**Comment by katiachumakova** [comment]
I have a project I've recently updated and audio stopped working, I've since reverted to previous commits and it's no longer working anywhere. I'm at a loss, any ideas? (I've tried all the stuff above)

**Comment by amalmohann-dgnl** [comment]
@deathemperor @luongs3 @Kiran0791 you guys have missed the import? 

please add the import as well

`#import <AVFoundation/AVFoundation.h> `

**Comment by dipkrao** [comment]
> I fixed this by adding this in my `AppDelegate.m` file:
> 
> ```
> #import <AVFoundation/AVFoundation.h>  // import
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   ...
>   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];  // allow
>   ...
> }
> ```

yes, it really works. thanks a lot for saving my time

**Comment by alfarodarwaynejay** [comment]
> I fixed this by adding this in my `AppDelegate.m` file:
> 
> ```
> #import <AVFoundation/AVFoundation.h>  // import
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   ...
>   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];  // allow
>   ...
> }
> ```

this throws an error.
![Screenshot 2024-08-15 at 9 57 51 PM](https://github.com/user-attachments/assets/555369e3-633b-486e-a0be-df5538789c63)

**Comment by sanjaysilversky** [comment]
look i'm at god level cause i found solution 

#import <AVFoundation/AVFoundation.h>  //->import

 [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; // add this into bool function

ignoreSilentSwitch="ignore"
selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}

use this two props

**Comment by maxpein12** [comment]
> look i'm at god level cause i found solution
> 
> #import <AVFoundation/AVFoundation.h> //->import
> 
> [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; // add this into bool function
> 
> ignoreSilentSwitch="ignore" selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}
> 
> use this two props

hii. wanted to try this but i got an error
ERROR  Warning: ReferenceError: Property 'SelectedTrackType' doesn't exist

you have any idea if i should configure something first? 
already put the lines for the AppDelegate.m

**Comment by abxlayedev** [comment]
Try this : 
import { SelectedTrackType } from 'react-native-video';


<Video
....
ignoreSilentSwitch={"ignore"}
selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}
/>

**Comment by abxlayedev** [comment]
> > look i'm at god level cause i found solution
> > #import <AVFoundation/AVFoundation.h> //->import
> > [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; // add this into bool function
> > ignoreSilentSwitch="ignore" selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}
> > use this two props
> 
> hii. wanted to try this but i got an error ERROR Warning: ReferenceError: Property 'SelectedTrackType' doesn't exist
> 
> you have any idea if i should configure something first? already put the lines for the AppDelegate.m

Try this : 
import { SelectedTrackType } from 'react-native-video';


<Video
....
ignoreSilentSwitch={"ignore"}
selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}
/>

**Comment by sanjaysilversky** [comment]
> > look i'm at god level cause i found solution
> > #import <AVFoundation/AVFoundation.h> //->import
> > [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil]; // add this into bool function
> > ignoreSilentSwitch="ignore" selectedAudioTrack={{type: SelectedTrackType.SYSTEM}}
> > use this two props
> 
> hii. wanted to try this but i got an error ERROR Warning: ReferenceError: Property 'SelectedTrackType' doesn't exist
> 
> you have any idea if i should configure something first? already put the lines for the AppDelegate.m

you have to import SelectedTrackType like

import { SelectedTrackType } from 'react-native-video';

**Comment by maxpein12** [comment]
just did it like this without importing 
selectedAudioTrack={{ type: 'system', value: '0' }}
and it works!
thanks guyss

**Comment by shubhammmmpal** [comment]
> > I fixed this by adding this in my `AppDelegate.m` file:
> > ```
> > #import <AVFoundation/AVFoundation.h>  // import
> > 
> > - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> > {
> >   ...
> >   [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];  // allow
> >   ...
> > }
> > ```
> 
> yes, it really works. thanks a lot for saving my time

this is working , Thanks buddy:)

**Comment by RohanRajGautam** [comment]
For me the audio was not working in iOS only, worked fined in android. This adding this props to Video fixed it for me. Passing this to anyone in need.


```
import { SelectedTrackType } from 'react-native-video';

<Video
   {...rest}
   selectedAudioTrack={{ type: SelectedTrackType.SYSTEM }}
/>
```
