### ISSUE TITLE
IOS: HLS stream issue on iOS

### ISSUE THREAD

**Issue by aybb** [TheWidlarzGroup/react-native-video#879]
Can hear stream but i get red screen with error: 'Unhandled JS Exception: Unsupported top level event type "topVideoLoadStart" dispatched'
![screen shot 2017-12-19 at 8 31 08 pm](https://user-images.githubusercontent.com/16851868/34172728-b6b79280-e4fb-11e7-8963-bedc22ad4226.png)

Basically, i have added 
<Video
     source={{ uri: 'https://DOMAIN/index.m3u8' }}
/>
and it returns red screen in DEBUG mode (crashes when i build .ipa)
"react-native-video": "^2.0.0",
"react": "16.0.0",
"react-native": "0.50.1"
Error occurs in ReactNativeFiber-dev file in method 'receiveEvent'

**Comment by neonguyen** [comment]
The problem is your project cannot link to the library. Please follow the tutorial on Github: https://github.com/react-native-community/react-native-video

You can also check Xcode for project link. Make sure that the library folder contains Xcode project link
