### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Zygro** [TheWidlarzGroup/react-native-video#88]
I installed the module as described by readme, but when I try to add it to a project and then run the project I get error 

<pre><code>2015-08-27 12:31:08.912 ProjectName[11310:337993] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableDictionary addEntriesFromDictionary:]: dictionary argument is not an NSDictionary'
*** First throw call stack:
(
    0   CoreFoundation                      0x0000000107c85a75 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000106dadbb7 objc_exception_throw + 45
    2   CoreFoundation                      0x0000000107baaf87 -[NSMutableDictionary addEntriesFromDictionary:] + 535
    3   ProjectName                            0x00000001066ecab5 -[RCTUIManager customDirectEventTypes] + 3621
    4   ProjectName                            0x00000001066ecc5f -[RCTUIManager constantsToExport] + 127
    5   ProjectName                            0x00000001066a1c67 -[RCTModuleData generateConfig] + 295
    6   ProjectName                            0x00000001066a176e -[RCTModuleData initWithExecutor:uid:instance:] + 414
    7   ProjectName                            0x00000001066967e0 -[RCTBatchedBridge registerModules] + 4208
    8   ProjectName                            0x0000000106695326 -[RCTBatchedBridge initWithParentBridge:] + 1654
    9   ProjectName                            0x00000001066bb9b9 -[RCTBridge setUp] + 377
    10  ProjectName                            0x00000001066bb048 -[RCTBridge initWithBundleURL:moduleProvider:launchOptions:] + 712
    11  ProjectName                            0x0000000106656994 -[RCTRootView initWithBundleURL:moduleName:launchOptions:] + 164
    12  ProjectName                            0x000000010662f385 -[AppDelegate application:didFinishLaunchingWithOptions:] + 197
    13  UIKit                               0x0000000109773458 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 248
    14  UIKit                               0x0000000109774002 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
    15  UIKit                               0x0000000109776e3e -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
    16  UIKit                               0x0000000109775d35 -[UIApplication workspaceDidEndTransaction:] + 179
    17  FrontBoardServices                  0x000000010e467243 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
    18  CoreFoundation                      0x0000000107bbac7c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    19  CoreFoundation                      0x0000000107bb09c5 __CFRunLoopDoBlocks + 341
    20  CoreFoundation                      0x0000000107bb0785 __CFRunLoopRun + 2389
    21  CoreFoundation                      0x0000000107bafbc6 CFRunLoopRunSpecific + 470
    22  UIKit                               0x00000001097757a2 -[UIApplication _run] + 413
    23  UIKit                               0x0000000109778580 UIApplicationMain + 1282
    24  ProjectName                            0x000000010662f713 main + 115
    25  libdyld.dylib                       0x000000010b291145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException</code></pre>

The build is successful, but this error occurs during the loading screen, which then does not progress to the first scene. 

Eidt: Additional info
I created this project in older version of Xcode, for example my .xcodeproj file is in main directory, not iOS like in new projects. when I move source files to new project, it compiles just fine (has different problems, probably unrelated)

**Comment by dalhundal** [comment]
For what it's worth - I had the same problem when trying to use this for the first time a few days ago, but I tried again today on a fresh project (ensuring I followed the instructions in the README) and it worked with no issues.

**Comment by brentvatne** [comment]
Sorry not really sure what could be causing it! As @dalhundal suggests, maybe try walking through the process again from scratch! Let me know how it goes

**Comment by isair** [comment]
Closing. @Zygro let me know if you're still experiencing this problem and I'll reopen the issue.
