### ISSUE TITLE
Video that is initialized with paused={true} is not shown

### ISSUE THREAD

**Issue by sarykemmoun** [TheWidlarzGroup/react-native-video#880]
Hello.
First thanks for the useful library.
I want to show a video with an option to pause and continue by pressing the video.
my code is:
               ` <TouchableWithoutFeedback
                    style={backgroundVideo}
                    onPress={() => this.setState({ paused: !this.state.paused })}
                 >
                   <Video
                        source={{ uri: path }}
                        paused={this.state.paused}
                        style={videoStyle}
                    />
                </TouchableWithoutFeedback>`
It works fine. but the problem is that if the initial value of pause in the state is set to true the video is not shown,
and I don't want to play the movie until the user will press the video

Do you have any solution? thanks.

**Comment by selsamman** [comment]
This worked for me [https://github.com/react-native-community/react-native-video/issues/777](url)

**Comment by sarykemmoun** [comment]
@Donhv I didn't resolve it. Finally, I've just declared that the video starts in play mode.
But if you like to start it in paused mode. I think you can try this workaround:

**Constructor:** `this.state = {  paused: false  }`
**componentDidMount:** `setTimeout(() => this.setState({paused: true}), 1);`
**render:** `<Video source={{ uri: path }} paused={this.state.paused} />`

In this case, the video starts in play - so it's should be rendered well, but there is no user impact 
**I didn't try this code** It's only my suggestion.

**Comment by selsamman** [comment]
@sarykemmoun - that sounds like a good approach if the seek I referred to doesn't work.  The timer though makes we worry a bit about consistency.  Another similar approach might be to set the paused state on video loading.  So far my experience with the seek is that it doesn't work consistently in debug mode but has worked in production mode so it makes me worry.  I would suspect your approach could be more reliable.

**Comment by Donhv** [comment]
@sarykemmoun  I think it is not good ideal. 
I fix it by use libary react-native-video-controls base from react-native-video. 
paused={true} work well

**Comment by afilp** [comment]
I do not see any difference with the other library, is there any other solution? Thanks!

**Comment by MaiconGilton** [comment]
For those facing this problem, I fixed it by doing this:
       <Video
          ref={r => this.player = r}
          onLoad={(e) => this.setState({ videoPaused: true })}
          paused={this.state.videoPaused} ==> init false
        />
