### ISSUE TITLE
not working on Android, remote address

### ISSUE THREAD

**Issue by Chocolate-Lee** [TheWidlarzGroup/react-native-video#883]
`<View style={styles.container}>
			<Video 
				source={{uri: 'http://lovecard.oss-cn-beijing.aliyuncs.com/dev/mtsvideo/0e44f8767baa4c9f9d224b8f7178794609577802.mp4'}}
       			ref="player"                            
			    rate={1.0}                              
        		volume={1.0}                            
        		muted={false}                           
        		paused={false}                          
        		resizeMode="contain"                    
        		repeat={true}                           
        		playInBackground={false}                
        		playWhenInactive={false}                
        		ignoreSilentSwitch={"ignore"}           
        		progressUpdateInterval={250.0}          
       			onLoadStart={this.loadStart}            
        		onLoad={this.setDuration}               
        		onProgress={this.setTime}               
        		onEnd={this.onEnd}                      
        		onError={this.videoError}               
        		onBuffer={this.onBuffer}                
        		onTimedMetadata={this.onTimedMetadata}  
        		style={styles.fullScreen} />
</View>

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: 'green'
	},
	fullScreen: {
		width: Dimensions.get('window').width,
		height: Dimensions.get('window').height,
    	position: 'absolute',
	    top: 0,
    	left: 0,
	    bottom: 100,
    	right: 0,
    	backgroundColor: 'yellow',
	},
})`

Everything is ok on iOS.
Nothing on Android

**Comment by zhj135** [comment]
@Chocolate-Lee , Did you solve this issue? I'm facing the the problem and don't konw how to fix this.

**Comment by djw27** [comment]
Make sure you specify a source type on Android:

```
<Video
    source={{ uri: videoUri, type: 'mp4' }}
    ...
/>
```

**Comment by franckmaurin** [comment]
I'm facing the same problem. Video don't work on android (but work well on ios)

**Comment by teilala** [comment]
my mp4 file don't work ,too .
but when i use https://www.w3schools.com/html/mov_bbb.mp4 
it's work!
so , i think it's format problem ...

**Comment by Yessengerey** [comment]
React-native-video fires onLoadStart and onLoad but doesn't display anything on API 23 and then fires onError.

**Comment by cobarx** [comment]
This video is working for me on both Android Media Player and ExoPlayer on an API 23 device. My guess is your device doesn't have the right codecs to play this video, iOS has better codec support than Android in general. I would suggest testing with ExoPlayer as you may have better luck.

Check your LogCat and see if there's an error when the video loads.
