### ISSUE TITLE
 rate does not work on Android

### ISSUE THREAD

**Issue by smartliuliu** [TheWidlarzGroup/react-native-video#886]
<Video
              ref={(video) => { this.video = video; }}
              style={styles.videoComponent}
              rate={this.state.rate}
              source={{ uri: playRealUrl }}
              paused={!isPlay}
              resizeMode={!isIOS && is43 ? 'stretch' : 'contain'}
              onLoad={status => this.onLoad(status)}
              onProgress={status => this.onProgress(status)}
              onBuffer={() => this.onBuffer()}
              onEnd={() => this.onEnd()}
              onError={err => this.onError(err)}
            />

rate is not work on Android

**Comment by vitto-moz** [comment]
Is this feature planned to implement? Thanks!

**Comment by djw27** [comment]
Doesn't work because it hasn't been added yet: https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L380

Unless you use explayer, then it should work: https://github.com/react-native-community/react-native-video/blob/master/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L623

**Comment by vitto-moz** [comment]
@djw27  Can I use exoplayer through react-native-video api?

**Comment by vitto-moz** [comment]
here is information about unimplemented "rate" prop - is this info actual? 
https://github.com/react-native-community/react-native-video/tree/master/android-exoplayer

**Comment by djw27** [comment]
@vitto-moz you can indeed. Check the following for info:

https://github.com/react-native-community/react-native-video/pull/426#issuecomment-272810170
https://www.bountysource.com/issues/40364073-exoplayer

**Comment by vitto-moz** [comment]
Ok, it seems it's not a very difficult task to implement exoplayer. 
One more question, can I use them in parallel? (I am developing an app for mindmapping - making maps from video and other resources on fly, so I want to implement different features like zooming video. I can easily make it with react-native-video (zooming), but I suppose it will be difficult to make it with exoplayer, but I also need **speed changing** feature that would be provided by exoplayer, so I can use it for different videos  )

**Comment by djw27** [comment]
I don't think it's possible in the same project since both Java packages expose the same class name `RCTVideo` which is used as a key in `Video.js` to pull in the native module:

https://github.com/react-native-community/react-native-video/search?l=Java&q=RCTVideo&type=&utf8=%E2%9C%93

**Comment by MERTKIRKALI** [comment]
@vitto-moz rate is still not workin on Android, right ?

**Comment by cobarx** [comment]
Setting the rate is now supported now that #798 is merged. However, the Android media player APIs only support setting the rate on Android 6.0 and up. I'd suggest using the ExoPlayer version instead since it doesn't have this limitation.
