### ISSUE TITLE
Repeatedly loading the component in quick succession sometimes breaks the loading 

### ISSUE THREAD

**Issue by riwu** [TheWidlarzGroup/react-native-video#891]
On iOS with `<Video source={require('./video.mp4')} />`, if the component is repeatedly mounted and unmounted in quick succession, the video will sometimes fail to load (black screen, `onError` did not get called while `onLoad` did).

Is anyone else experiencing this?
Could it be that the we need to wait for the resources to be freed before loading another video? If so could callbacks etc be provided to handle that?

**Comment by kvieira90** [comment]
I'm also experiencing this. It also blocks all outgoing requests as well

**Comment by zachrnolan** [comment]
Getting a black screen as well. Did anyone figure this out?

**Comment by georgewwindsor** [comment]
I am also experiencing this, and it is via unmounting and mounting videos. unfortunately changing the "state" to update a video causes the same behaviour.
