### ISSUE TITLE
Show list video preview

### ISSUE THREAD

**Issue by Donhv** [TheWidlarzGroup/react-native-video#892]
I want to show list video with image. I try use <Image style = {} source={{uri : this.state.videoUri}} /> but show nothing.
And now I try use add view to flatlist
 <View>
                    <Text style={{ fontSize: 20, color: 'green' }}>{item.key}</Text>
                    <Video style={{ width: 100, height: 100 }}
                        source={item.value}
                        paused={true}
                        ref={(ref) => { this.player = ref }}
                        onLoad={() => { this.player.seek(0) }}
                    />
 </View>

but it only show preview video at last item and different item only show text
Help me!

**Comment by VrajSolanki** [comment]
you can use [CameraRoll](https://facebook.github.io/react-native/docs/cameraroll.html) from react-native which gives you a list of all the videos/images from the device.
It would also generate Preview image for you for the videos and you can also show video duration, to indicate whether it is a video or image.
