### ISSUE TITLE
onEndBuffering

### ISSUE THREAD

**Issue by nbennink** [TheWidlarzGroup/react-native-video#895]
Hi,

Is there a prop that calls every time that the player is able to play again after buffering?

We have `onBuffer` that calls a function every time when the video is buffering (it shows a loading indicator for me). But there is no `onEndBuffering` so I can't let the spinner disappear when the buffering is over. How can I achieve something like this?

Thanks

**Comment by nbennink** [comment]
Fixed it by using onProgress. When the video start playing I make the spinner invincible.

**Comment by kinka** [comment]
What about the case after seeking, no onProgress triggered. I have such a case that the video is paused, and after seeking it should still be paused...

**Comment by narolareact** [comment]
hey @nbennink  would you please post specific steps by which you achieved that?

**Comment by nbennink** [comment]
@narolareact 

```
<Video
    onBuffer={this.setState(showSpinner: true)}
    onProgress={this.setState(showSpinner: false)}
```
At first I thought that onBuffer should return true or false. But onBuffer is an event that fires when the video starts buffering. When the video continues playing the player fires an onProgress event.
