### ISSUE TITLE
Live HLS stream crashing on IOS

### ISSUE THREAD

**Issue by paraswatts** [TheWidlarzGroup/react-native-video#899]
I am playing a live HLS stream URL which works fine on Android and on IOS emulator, but when I play on iPhone player gets crashed 

Stream url: http://capcobroadcaststream.in:1935/capco/ad24/playlist.m3u8

**Comment by KrGyan** [comment]
Its not working on andriod as well, can you share example set up for Android

**Comment by paraswatts** [comment]
It is working fine for Android, My application is live on Google play store, not facing any issue

**Comment by mandriv** [comment]
@paraswatts did you find a workaround? Experiencing same issue, working well inside iOS simulator, crashing after a second on a device.
