### ISSUE TITLE
fullscreen option?

### ISSUE THREAD

**Issue by wynnej1983** [TheWidlarzGroup/react-native-video#90]
↑ must have, doesn't it exist?

**Comment by brentvatne** [comment]
You can just set position: absolute and make it top: 0, left: 0, bottom: 0, right: 0 at the root and it will become full screen - should work just like other views in React Native!

**Comment by rclai** [comment]
My video is in between several Views. Given the current state of view ordering where the later elements are layed on top, my video will get overlapped by the content below with your solution @brentvatne .

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.
