### ISSUE TITLE
Recommended production releases?

### ISSUE THREAD

**Issue by hardcodet** [TheWidlarzGroup/react-native-video#900]
First of all: Thanks for all the work you've put into this package. Awesome!
Now, I noticed that the NPM package is lagging several months behind with this being a rather active repo. Is the current recommendation to just import master instead of the NPM package?

**Comment by cobarx** [comment]
The 2.0 version is semi-recent. I just started maintaining this project and am starting to merge some of the outstanding PRs. With any luck, we should be doing regular releases pretty soon, in the meantime tracking master will work.
