### ISSUE TITLE
Sound does not match picture after unlock screen（Exoplayer）

### ISSUE THREAD

**Issue by jcliang1212** [TheWidlarzGroup/react-native-video#901]
I am developing a video player. 
When I lock the screen, I set the “paused” to be "true".  Then I unlock the screen. The video still stays "paused", but the "frame" in "screen" is not right. Then I set the “paused” to be "false", the "sound" of "video" is played, and the "frame" of "video" not update until the "sound" match the "frame".
Here is my main code: 
 1. AppState.addEventListener("change", () => {
      if (this._video) {
        const { currentState } = AppState;
        if (
          currentState === AppStateType.background ||
          currentState === AppStateType.inactive
        ) {
          this.setState({ paused:true });
        } 
      }
    });
2. <Video
          ref={video => {
            this._video = video;
          }}
          source={{ uri: videoUrls[videoIndex] }}
          style={styles.videoPlayer}
          resizeMode="contain"
          playInBackground={false}
          paused={paused}
          onProgress={({ currentTime }) => {
            this._setCurrentTime(currentTime);
          }}
          onLoad={({ duration }) => {
            this._setDuration(duration);
          }}
          onEnd={() => {
            this._playNextVideo();
          }}
        />

Can anybody help me? Thanks! @jsierles @qingfeng @arjan @thoblr @zachrnolan

**Comment by artem-romanov** [comment]
I confirm that. When I minimize and maximize app, video paused and has a wrong frame. Original (MediaPlayer API) seems working ok.

If anybody knows how to fix that - please, provide an info.
