### ISSUE TITLE
iOS native dismiss fullscreen callback

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#903]
Is there any call back to notice when iOS native dismiss the fullscreen ? Maybe boolean return ? So I could base on the boolean to do a function for further UI exchange when dismiss from native.

**Comment by kyle-ssg** [comment]
@JayricMok Did a bit of digging, think this may we what we need 
https://github.com/kay-is/react-native-video/commit/c0a8f7c0c9ebf1a82a6f37381de9d96754c931c9
