### ISSUE TITLE
Error UI block RCTVideo 0x123e3f990

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#907]
I getting two error when I switch m3u8 link in iOS, Android Work Perfectly.

`Exception thrown while executing UI block: Cannot remove an observer <RCTVideo 0x123e3f990> for the key path "readyForDisplay" from <AVPlayerLayer 0x1c4625060> because it is not registered as an observer.`

`Exception thrown while executing UI block: 'parentNode' is a required parameter`

**Comment by kvieira90** [comment]
Also seeing this issue +1

**Comment by franzejr** [comment]
@JayricMok and @kvieira90 this commit: https://github.com/svtek/react-native-video/commit/511c73ee7320d2ff3c1534b4bcecbc2717c9f398 fixes this. 

I think @ardalahmet will create a PR ?

I just tested that and it works. Me and @rclements were having this issue.

**Comment by ahmetardal** [comment]
Hi @franzejr 
I don't think my solution is complete. It just fixes the crash but causes a blink when the video ends and starts playing again. You can fork and cherry-pick my commit for a temporary fix, though.

If I end up with a better fix I'll create a PR for sure. Thanks.

**Comment by facuacostag** [comment]
Has this been merged?

**Comment by wonday** [comment]
Also seeing this issue +1

**Comment by dwilt** [comment]
We are experiencing this issue as well

**Comment by dwilt** [comment]
We have confirmed that this PR has fixed the problem

**Comment by n1ru4l** [comment]
@ardalahmet could you please open a pull request for this fix?

**Comment by ahmetardal** [comment]
https://github.com/react-native-community/react-native-video/pull/1072

**Comment by cobarx** [comment]
When are you seeing this? I've tried switching between HLS streams and am not encountering any issues. I want to see if I can figure out why we don't have an observer to remove, if I can't I'll merge this fix. Either way I'll get it fixed right away.

**Comment by cobarx** [comment]
Ok, didn't know exactly how to check this, but #1075 should handle it. It felt a little bit cleaner to use a boolean to track if there was an observer to clear so that we match the code used for the other observers. Thanks to everyone who submitted a PR.
