### ISSUE TITLE
Play/Pause/Download Video in FlatList

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#908]
I understand that this `Issues` of library is only to specific library problem and not what I am about to ask. I have already posted a question on Stackoverflow. But noone answered, since its related to video, I am sure someone must have come across this feature. So giving it a shot here. Apologizes again. :)

The idea is simple play a video which is being shown currently in the flatlist, pause the rest.

This is my `FeedCard` -> `MyFlatListItem`

```
class FeedCard extends PureComponent {

    constructor(props){
        super(props);
        this.state = {
            pauseVideo: true
        };
    }

    playThisVieo = (playVideo) => {
      this.setState({
          pauseVideo: !playVideo
      });
    };

    render() {
        return (
            <Card>
                <CardItem cardBody>
                    <View style={styles.preview}>
                        <Video
                            source={{ uri: this.props.videoURL}}
                            ref={(ref) => {
                                this.player = ref;
                            }}
                            rate={1.0}
                            volume={1.0}
                            muted={false}
                            paused={this.state.pauseVideo}
                            resizeMode="stretch"
                            repeat={true}
                            playInBackground={false}
                            playWhenInactive={false}
                            ignoreSilentSwitch={"ignore"}
                            progressUpdateInterval={250.0}
                            onLoadStart={() => this.player.seek(0)}
                            onLoad={this.setDuration}
                            onProgress={this.setTime}
                            onEnd={this.onEnd}
                            onError={this.videoError}
                            onBuffer={this.onBuffer}
                            onTimedMetadata={this.onTimedMetadata}
                            style={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                bottom: 0,
                                right: 0,
                            }}
                        />
                    </View>
                </CardItem>
            </Card>
        );
    }
}
```

Now all I have to do is renderThisItem In FlatList and then in onViewableItems, only play that video which is being shown.

```
constructor(props){
    super(props);
    this.viewabilityConfig = {viewAreaCoveragePercentThreshold: 70};
}


 <FlatList
        horizontal={false}
        data={this.props.feeds}
        renderItem={this.renderFeeds}
        viewabilityConfig={this.viewabilityConfig}
        onViewableItemsChanged={this._onViewableItemsChanged}
 />

 renderFeeds = (feed) => {
    return (
        <FeedCard
            ref={(ref) => this.feedCardRef = {...this.feedCardRef, [`REF-FLATLIST${feed.item.feedID}`]: ref}} //Saving Refs Here
            videoURL={feed.item.videoURL}
            //Other Props
        />
    );
};

    _onViewableItemsChanged = (props) => {
        const changed = props.changed;
        const viewableItems = props.viewableItems;
        console.log(changed);
        console.log(viewableItems);
        changed.forEach(item => {
            if (!item.isViewable) {
                this.feedCardRef[`REF-FLATLIST${item.key}`].playThisVideo(item.isViewable);
            }
        });
        viewableItems.forEach(item => {
            if (item.isViewable) {
                this.feedCardRef[`REF-FLATLIST${item.key}`].playThisVideo(item.isViewable);
            }
        });
    };
```
Now the above works well for playing video only if its the one being shown in the screen, but I also want to download the video only if that video is being currently shown in the screen. How do I control the download of a video? I couldnt find anything in the readme.

[StackOverFlow](https://stackoverflow.com/questions/48287658/play-pause-download-video-in-flatlist) Link

**Comment by VrajSolanki** [comment]
@kk1429 I have the exact same implementation and struggling to not download the remaining videos and only the one which is playing. did you manage to get a solution. ??

**Comment by gusgoose** [comment]
Did either of you find a way to achieve this or a good workaround?

**Comment by abdelhakimkotti** [comment]
Hello,
I have same  problem if i'm read 3 videos on ligne.
Any solution to read very fast video .mp4 on ligne , if on click next video or back video .
Thanks :)

**Comment by n1ru4l** [comment]
You could use a thumbnail and first start rendering the `Video` component behind the thumbnail when it is in the center of the  screen (calculated based on offsetY of the ListView and the index + height of the list items). After the video is loaded  (`onLoad`) event you could fade out the thumbnail and start playing the video. furthermore you could debounce on the  onScroll event handler of the ListView, to ensure that a video component is only rendered after there was no scroll event triggered for the last few milliseconds or so. This is what I am basically implementing. If you guys are interested I can share some code after I finished it.

**Comment by n1ru4l** [comment]
@abdelhakimkotti The first step of the process is https://github.com/n1ru4l/react-in-center-of-screen which I now use to determine whether a list item is in the center of the screen.

Code for the video component with a preview image will follow soon!

**Comment by pribeh** [comment]
@n1ru4l I'm subscribing and awaiting your suggestion.

**Comment by n1ru4l** [comment]
@pribeh I am currently working on our android part of the application. On android the video component (with preview image) does not work as performant as it should be. I will try to provide updates (and hopefully I can also open source that component).

**Comment by n1ru4l** [comment]
@elzii sorry currently I have not time to work on open sourcing that component. I will try to do it asap, I cannot give a guaranteed date 😕

**Comment by imMayankRaj** [comment]
[`https://stackoverflow.com/questions/54839940/pause-video-in-flatlist-when-out-of-view`](https://stackoverflow.com/questions/54839940/pause-video-in-flatlist-when-out-of-view)

**Comment by anwersolangi** [comment]
I'm also struggling with this scenario, anyone here who found the solution? I only want to download the visible video in flatlist.

**Comment by usmandilmeer** [comment]
Hi, friends I have solved the issue for my react native video project. 
the issue was that all videos are playing in Flatlist but we need to play only singal video on the current viewport and pause the rest.
just do the following steps to solve all videos playing issue
1: npm install @svanboxel/visibility-sensor-react-native
2: import VisibilitySensor from '@svanboxel/visibility-sensor-react-native'
3: do this
```
import VisibilitySensor from '@svanboxel/visibility-sensor-react-native'
const video = ()=>{
const [paused, setpaused] = useState(true)
return(
     <VisibilitySensor onChange={(isVisible)=>{ 
        return(
          console.log(isVisible),
          isVisible?setpaused(false):setpaused(true)
        )  
      }
    }
    >
    <View>
     <Video
              source={{uri: 'https://d8vywknz0hvjw.cloudfront.net/fitenium-media-prod/videos/45fee890-a74f-11ea-8725-311975ea9616/proccessed_720.mp4'}}
              style={styles.video}
              onError={(e) => console.log(e)}
              resizeMode={'cover'}
              repeat={true}
              paused={paused}
            />
      </View>
    </VisibilitySensor>
)
}
```
4: I have just given you the basic structure you can add styling stuff as your requirements.
5: remember that always add your view/video elements between the VisibilitySensor tags, otherwise it will not work.
6: this code will give you true when your video component will render in flatlist viewport and remainig will give you false. with this you can manage play/pause state of video element.
thanks...

**Comment by hueniverse** [comment]
Moved to #2668
