### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by Wingie** [TheWidlarzGroup/react-native-video#91]
Am interested to see if this can be set up to work on android also. 
Had a look at the existing code and had some queries though.

`libRCTVideo.a` step - is this also necessary to get it to work on android?
`RCTVideo.h, RCTVideo.m, RCTVideoManager.h, RCTVideoManager.m` - these are objective C stuff so i'm guessing an equivalent android native code for media must also be added?

**Comment by brentvatne** [comment]
Indeed! Anyone willing to tackle this, it would be amazing. I don't think I'll have a chance in the very near future

**Comment by ms88privat** [comment]
@brentvatne if someone is interested in doing this on your side. I posted a job offer
https://www.upwork.com/jobs/React-Native-VideoPlayer-Component-for-Android-with-ffmpeg-library_~~5c15d1fae396c3d9

**Comment by brentvatne** [comment]
Neat @ms88privat! I'll share in my newsletter

**Comment by ms88privat** [comment]
@brentvatne thanks, but I already found someone at upwork, so this offer will be closed soon. Share it in the next letter when the component is finished :+1:

**Comment by a-axton** [comment]
@ms88privat do you have plans to merge it with this repo? I have a project currently that could use your component. I'd be willing to help with your upwork costs if that helps. I will also love you long time.

**Comment by undef1ned** [comment]
looking for the android video component as well

**Comment by ms88privat** [comment]
@a-axton @undef1ned 
I am going to create a new repo until Saturday with the actual status of implementation, documentation and example. Later on we can migrate it into this repo. 

I will keep you updated here.

**Comment by sejoker** [comment]
I have wrapped Vitamio android into RN component, it maybe helpful https://github.com/sejoker/react-native-android-vitamio

**Comment by niftylettuce** [comment]
:+1: Please add!

**Comment by ms88privat** [comment]
@a-axton @undef1ned @niftylettuce 
here is the first version. The install guide is still missing... should be done by tomorrow.
Better Example will also follow and so on...

https://github.com/ms88privat/react-native-video-gstreamer

If someone has experience with android / gstreamer library, I would be happy to add you as a collaborator. 

@brentvatne when this module is more stable and has a better defined API, we can integrate it into this repo here.

Greetings.

**Comment by ms88privat** [comment]
@sejoker also nice job! looking forward, I am really curios about the performance difference between gstreamer vs vitamio implementation detail. The bad thing is, that you need a vitamio licence if you want to build a commercial app, what I know about.

**Comment by isair** [comment]
I'm going to start working on the Android component using Android's native [VideoView](http://developer.android.com/reference/android/widget/VideoView.html).

**Comment by ms88privat** [comment]
https://github.com/ms88privat/react-native-video-gstreamer

The install guide is now complete and it should be possible to get it running. Feel free to open a issue if you have some problems.

@isair nice, lets see what the native View is able to do.

**Comment by brentvatne** [comment]
@isair :rocket: :art:
