### ISSUE TITLE
onBuffer is not firing on android.

### ISSUE THREAD

**Issue by arun477** [TheWidlarzGroup/react-native-video#910]
````
<Video
              ref={ref => {
                if(!this.state.player){
                  this.setState({
                    player : ref,
                  })
                }
              }}
              source={{ uri: this.state.channelUrl }} // Looks for .mp4 file (background.mp4) in the given expansion version.
              rate={1.0} // 0 is paused, 1 is normal.
              volume={2.0} // 0 is muted, 1 is normal.
              muted={false} // Mutes the audio entirely.
              paused={false} // Pauses playback entirely.
              resizeMode="cover" // Fill the whole screen at aspect ratio.
              repeat={false} // Repeat forever.
              onLoadStart={data => this.loadStart(data)} // Callback when video starts to load
              onLoad={data => this.onLoad(data)} // Callback when video loads
              progressUpdateInterval={250.0}
              onProgress={this.setTime.bind(this)} // Callback every ~250ms with currentTime
              onEnd={data => {
                this.onEnd(data);
              }} // Callback when playback finishes
              onError={() => this.videoError()} // Callback when video cannot be loaded
              onTimedMetadata={data => this.onTimedMetadata(data)}
              onBuffer={this.onBuffer.bind(this)}
              style={styles.backgroundVideo}
            />
````

"react-native": "0.51.0"
"react-native-video": "^2.0.0"

**Comment by qadirhusainee** [comment]
Facing same problem.

**Comment by arun477** [comment]
hi qadirhusainee,
I solved that problem by changing the player to exo player.

**Comment by kashifaliquazi** [comment]
@coolarun can you please explain how did you do that, facing the same problem

**Comment by arun477** [comment]
@kashifaliquazi 
add the following changes to your android files

**android/setting.gradle**
**remove:**
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
**add:**
include ':react-native-video-exoplayer'
project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

**android/app/build.gradle**
**remove:**
   compile project(':react-native-video')
**add**
  compile project(':react-native-video-exoplayer')

**Comment by chetanshewale** [comment]
I am having similar issue, but 
**removing**
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
&
compile project(':react-native-video')

doesn't remove the module from the project, tried clearing project, rebuilding, clearing Android Studio cache any solution for this?

**Comment by arun477** [comment]
@chetanshewale
have you removed this line "compile project(':react-native-video')"
and replaced with  this line "compile project(':react-native-video-exoplayer')" ?

**Comment by chetanshewale** [comment]
@arun477 yes, found a workaround tho different than yours :) 

I just replaced the source code of **react-native-video** package in **node_modules** with **react-native-video-exoplayer** source and that worked fine !

**Comment by arun477** [comment]
@chetanshewale if you change source code in node_modules. make sure pull that package and put it outside of your "node_modules" and reference that path. so that when you do "npm install" again it won't override your changes.

**Comment by chetanshewale** [comment]
@arun477 thanks, where is the best place in the project to put these packages?

**Comment by arun477** [comment]
@chetanshewale create a folder inside your root folder "lib" put that package there.  it doesn't matter where you put that package as long as it's outside of the node_modules folder, it will be fine.

**Comment by chetanshewale** [comment]
@arun477 thanks, is there any way where we can exclude this package to be overwritten when we run **npm install**? so that we can avoid this manual work with a standard.
