### ISSUE TITLE
react-native-video:prepareReleaseDependencies

### ISSUE THREAD

**Issue by HadisNZL** [TheWidlarzGroup/react-native-video#914]
react-native-video:prepareReleaseDependencies

**Comment by DIVIBEAR** [comment]
I meet the same error.
I solved it. U could do this:
react-native-video -> android -> build.gradle  
-----------------------------------
dependencies {
  provided "com.facebook.react:react-native:+"
  ...
}
------------------------------------
to
------------------------------------
dependencies {
  compile "com.facebook.react:react-native:+"
  ...
}
------------------------------------
