### ISSUE TITLE
poster Image supports only images  from a url , need support for local images in the project

### ISSUE THREAD

**Issue by gogoku** [TheWidlarzGroup/react-native-video#917]
i need to set poster image for a video, the poster image is present in my project folder,
the current implementation supports only images from  url's

**Comment by ahmetabdi** [comment]
Anyone looking into this? Been around since Jan and seems simple

**Comment by MatheusParanhos** [comment]
Anyone?

**Comment by heineiuo** [comment]
Use `Image.resolveAssetSource`:

```js
Image.resolveAssetSource(require('./path/to/assets/poster.png')).uri
```
