### ISSUE TITLE
Livestream freezes on IOS after 1-1.5 min

### ISSUE THREAD

**Issue by stobe1** [TheWidlarzGroup/react-native-video#919]
Hello,
I've encoutered issue with HLS livestreams
after 1-2 mins of playing HLS stream, video completely frezees, and on ios 10 is not unfreezing after that.

Tested both in our app and on fresh example app from this repo with latest version.

Pretty huge issue, please let me know if there is any workaround

Thanks

**Comment by kvieira90** [comment]
Look into your streaming configuration a bit more. I'm using this repo with Wowza live streaming HLS and able to watch 5 min+
