### ISSUE TITLE
Resuming a HLS live stream on IOS

### ISSUE THREAD

**Issue by SunilChiluvuri** [TheWidlarzGroup/react-native-video#921]
Hi,
I'm using react-native-video to play a HLS live stream served by  wowza streaming cloud. 
It works great and the lag from live is about 12 seconds which is reasonable given that the video has to be encoded and pushed to CDN. 

When the app goes to background and returns to the foreground however, the player tries to resume playback from the time the app went to background. 
This causes the lag to increase and the playback never catches up. If the app was in the background for 15 seconds then the lag from live jumps from 12seconds to about 35seconds and never catches up. 

Is there a hook to reset playback of the live stream so the player resumes from the latest available chunk and does not try to request older chunks of the HLS stream?

Thanks

**Comment by kvieira90** [comment]
Also having this issue, let me know if you can figure it out. I've been trying to setup amlst which will allow adaptive bitrate streaming but I'm getting an 'error: %0', { error: { domain: 'AVFoundationErrorDomain', code: -11800 },
  target: 486 } error

**Comment by illl48** [comment]
Also facing similar issue. How do we set the paused prop when AppState was inactive or background? Appreciate it.
