### ISSUE TITLE
Using player as splash screen stops Spotify player.

### ISSUE THREAD

**Issue by matiasbontempo** [TheWidlarzGroup/react-native-video#927]
Hi! We are using this package to show an animated splash screen (we tried lottie but it had several issues) and it's working excellent!

However, in one of our tests we were playing a song in Spotify and when we started the app the video player took control over media and stopped the song. Is there any way to prevent this behavior?

Thanks!

**Comment by yelkamel** [comment]
same as @MatiasBontempo with soundcloud app, I got this problem too. 
if some have any idea !  :)

**Comment by qudde** [comment]
Is this fixed yet? Having the same problem.
