### ISSUE TITLE
How to replay when android error (video unavailable)?

### ISSUE THREAD

**Issue by camellieeee** [TheWidlarzGroup/react-native-video#930]
![wechatimg92](https://user-images.githubusercontent.com/18331008/35727387-e97e028e-0842-11e8-858c-c5997cad6de8.jpeg)

#### react-native-video : 1.0.0

**Comment by fabdrol** [comment]
I have this issue too, but the video behind the overlay plays on without issues. Any ideas?

**Comment by sokratisvs** [comment]
I have the same issue but without being able to play the video again (After checking the codecs of the video comparing to another that can play again i noticed the following (Video with (Codec: mp41/isom) was playing again with onEnd={ this.video.seekTo (0) } but with a video with (Codec: m4v/mp42/isom) i had the issue with the icon as above but without the video been able to play again.
I also checked this issue but it didn't help:
https://github.com/react-native-community/react-native-video/issues/187

**Comment by andy-io** [comment]
any solutions for this bug ? i experience this often on m3u8 streams

**Comment by xinfang** [comment]
+1

**Comment by mayuraitavadekar** [comment]
+1

**Comment by coofzilla** [comment]
just got the same bug with `hls` urls.
