### ISSUE TITLE
get video duration

### ISSUE THREAD

**Issue by hawkson-lemuel** [TheWidlarzGroup/react-native-video#931]
How do i get the duration of a video?

**Comment by VrajSolanki** [comment]
you can use onLoad={this.setDuration}  function to get the video duration.
for ex: 
` <VideoPlayer
                            isPlay={this.state.videoPlay}
                            source={url} 
                            resizeMode={"contain"}
                            setDuration={this.setDuration}
                            ref={(ref) => {
                                this.videoPlayer = ref
                            }}  
                        />`

`setDuration=(item)=>{
        this.setState({duration:item})
    }`

**Comment by cavator** [comment]
how can i get video duration after record, no when i load one
