### ISSUE TITLE
Displays Black Screen 

### ISSUE THREAD

**Issue by harikanammi** [TheWidlarzGroup/react-native-video#936]
Hi, I am running sample example. I am using this module for displaying video. But in iOS it displays only black box and in Android nothing is displayed. Please give me any suggestions. Thank you.

here is my code:
```
<Video
            source={{ uri: 'https://youtu.be/lv00UOXxy0g' }}
            ref={ref => {
              this.player = ref
            }}
            rate={1.0}
            volume={1.0}
            muted={false}
            paused={false}
            resizeMode="cover"
            repeat={true}
            playInBackground={false}
            playWhenInactive={false}
            ignoreSilentSwitch={'ignore'}
            progressUpdateInterval={250.0}
            onLoadStart={this.loadStart}
            onLoad={this.setDuration}
            onProgress={this.setTime}
            onEnd={this.onEnd}
            onError={this.videoError}
            onBuffer={this.onBuffer}
            onTimedMetadata={this.onTimedMetadata}
            style={styles.backgroundVideo}
          />

var styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 10,
    left: 10,
    bottom: 200,
    right: 10
  }
})

```
Here is my screenshot:
for iOS:
![screen shot 2018-02-10 at 10 51 31 am](https://user-images.githubusercontent.com/31063894/36058823-758279a0-0e50-11e8-89e5-c5bf4283d0b6.png)
for Android:
![screen shot 2018-02-10 at 10 51 45 am](https://user-images.githubusercontent.com/31063894/36058824-7e68ed74-0e50-11e8-8f84-c37dcbcd37ab.png)

**Comment by baloot-mobile** [comment]
same problem but I have 2 links

http://velgardi-game.ir/api/get_video?path=app/public/videos/question3/movie_x264.mp4

http://techslides.com/demos/sample-videos/small.mp4

react native shows number 2 link but doesn't show first one
why?

in both onProgress is working

**Comment by harikanammi** [comment]
Hi, @baloot-mobile  I fixed this issue...
In this module.... I am downloaded the video file and it is copied in follow below process.
iOS --> go to your project folder -->open your iOS folder and paste the video with unique name.
Android --> go to your project folder --> android/app/src/main/res --> Create a folder name as raw and paste the video with unique name in this(raw) folder.

Here is the code:
  ```
constructor(props) {
    super(props)
    this.state = {
paused: false,
      currentTime: '',
      duration: ''
}
}
  onLoad(data) {
    this.setState({ duration: data.duration })
  }

  onProgress(data) {
    this.setState({ currentTime: data.currentTime })
  }

  <Video
                  source={{ uri: 'DowloadedVideoName', type: 'mp4' }}
                  style={styles.backgroundVideo}
                  rate={1.0}
                  volume={1.0}
                  paused={this.state.paused}
                  muted={false}
                  resizeMode="cover"
                  onLoad={this.onLoad.bind(this)}
                  onProgress={this.onProgress.bind(this)}
                  onEnd={() => {
                    this.setState({ paused: !this.state.paused })
                  }}
                  repeat={true}
                  playInBackground={false}
                  playWhenInactive={false}
                />
```

I think it is working.

**Comment by jzhw0130** [comment]
@baloot-mobile 

Do you get the problem now? 
It seems there are some differences between your 2 links. How do you get the 2 links?

Link1:
![link1](https://user-images.githubusercontent.com/12521790/36519112-922fd5b6-17c4-11e8-8c45-b1915e59d6a9.png)

Link2:
![link2](https://user-images.githubusercontent.com/12521790/36519113-96f65a48-17c4-11e8-8771-b2708caca0c2.png)

**Comment by isaiahgrey93** [comment]
@harikanammi @baloot-mobile @jzhw0130 
[https://facebook.github.io/react-native/docs/network.html](https://facebook.github.io/react-native/docs/network.html)

<img width="860" alt="screen shot 2018-03-04 at 10 02 34 am" src="https://user-images.githubusercontent.com/7504299/36948694-915808e4-1f93-11e8-8822-f8f9d21caa9a.png">

IOS by default will block any non-HTTPS requests.
I believe that the Youtube URL will not work as the source `uri`, you will have to extract the youtube playback URL another way.

The original Youtube URL @harikanammi listed, can be seen [here](https://r2---sn-apbiun2xxq-2qme.googlevideo.com/videoplayback?mt=1520203259&mv=m&ms=au%2Crdu&source=youtube&mm=31%2C29&mn=sn-apbiun2xxq-2qme%2Csn-nx5e6n7d&pl=24&id=o-AEwc89bC1y7OzQIUzIpDI0Rr6ZxezZjpnPB00ahPwGno&requiressl=yes&dur=880.433&ipbits=0&expire=1520224967&initcwndbps=1225000&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=24.75.121.21&lmt=1490833543483953&signature=90F802CCE0F4AE25BB23D751B86C396CE162CFB2.8E35529B4F71D306710645049BE198217D707F28&mime=video%2Fwebm&itag=247&key=yt6&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&gir=yes&clen=36960097&keepalive=yes&fvip=2&c=WEB&ei=ZnacWrrNOIbV_APU0Z2IAw&alr=yes&cpn=OEsdQYtWq63xz4by&cver=2.20180227&range=0-431421&rn=0&rbuf=0). Link may expire quickly, but I retrieved this from network inpsector on video youtube page. Also, this url may only work on Android, I believe presently IOS does not supoort the `video/webm` playback format.

Other formats and resolutions may/may not be supported, it's probably best to check each platform/device support for the required format & resolutions.
