### ISSUE TITLE
can anyone say why react native doesn't show this link

### ISSUE THREAD

**Issue by baloot-mobile** [TheWidlarzGroup/react-native-video#937]
1.
http://velgardi-game.ir/api/get_video?path=app/public/videos/question3/movie_x264.mp4

2.
http://techslides.com/demos/sample-videos/small.mp4

react native shows number 2 link but doesn't show first one
why?

in both onProgress is working

**Comment by djw27** [comment]
The first link doesn't load a video? I just get a page which says 

> string(23) "/storage/movie_x264.mp4"
