### ISSUE TITLE
onVideoError and onVideoLoadStart native properties are unset

### ISSUE THREAD

**Issue by ethul** [TheWidlarzGroup/react-native-video#94]
It looks like the `onVideoError` and `onVideoLoadStart` properties are not being [set as nativeProps](https://github.com/brentvatne/react-native-video/blob/3aa46875a58b857861377dc1528088ae027627e2/Video.ios.js#L83-L95).

Should they be set to `this._onError` and `this._onLoadStart`?

**Comment by ghost** [comment]
+1, onError does not get fired.
