### ISSUE TITLE
android: changing rate introduces distortion into audio

### ISSUE THREAD

**Issue by w-** [TheWidlarzGroup/react-native-video#941]
i am consuming react-native-video but to playback hls audio only stream from s3 buckets.

When I set the playback rate to be smaller or larger, I get a lot of distortion in the audio. This does not happen on web or ios (there are separate clients for these. iOS version is a separate native app).

What can i do on the android side to prevent distortion?

The current range for the rate change is only 0.9-1.1 with a step of 0.02

**Comment by vitto-moz** [comment]
Does rate work at all? I saw a note in a readme that this feature is not implemented. So I don't see any changes in player behavior after rate value is changed

**Comment by w-** [comment]
It definitely does work. We get a change in rate when adjusting the value.

Which README are you referring to?

**Comment by vitto-moz** [comment]
That is strange - I can't find right now. I apologize for misleading in my comments. I will check one more time this functionality (rate prop) and report here

**Comment by vitto-moz** [comment]
So, I expect video will increase its speed twice after I change rate to 2, right? Or, does this prop ('rate') has its influence only on audio stream?

**Comment by w-** [comment]
> I apologize for misleading in my comments. 
no worries at all. thanks for replying and taking a look.

hmm i 'm not sure about video. i'm only playing back audio files. mp3 and hls ts files to be specific.

**Comment by vitto-moz** [comment]
So, here is a related issue. According to it we don't have rate prop implemented 
https://github.com/react-native-community/react-native-video/issues/886#issuecomment-366639883

**Comment by vitto-moz** [comment]
@w-  finally I found information about unimplemented "rate" 
https://github.com/react-native-community/react-native-video/tree/master/android-exoplayer
here it is - but it related to exoplayer

**Comment by malonguwa** [comment]
@vitto-moz @w- HI guys I can confirm v2.0.0 does not has rate prop implement yet, but iOS did... hope we can get this feature available in android soon

**Comment by natashache** [comment]
@w-  Did you get the android version working without distortion? I also need this feature.

**Comment by w-** [comment]
@malonguwa  there must be a huge disconnect somewhere. I'm using the published version of react-native-video and adjusting the rate prop definitely has an impact on audio playback rate.

@natashache Nope. the distortion is there. It is proportional to the degree we adjust the rate. it also depends on the source audio. if the audio is bass heavy it seems particularly bad
i'm using it between the range of 0.9 and 1.1
