### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by sm2017** [TheWidlarzGroup/react-native-video#942]
I create a PR https://github.com/react-native-community/react-native-video/pull/882 on Dec 24, 2017

After 2+ months you don't reply/accept/reject my PR

**Comment by sm2017** [comment]
I'm sorry for @react-native-community , You have poor supporting

**Comment by cobarx** [comment]
Sorry about this, a coworker and I just started maintaining this project and will be a lot more responsive about reviewing & merging PRs. Previously, I don't think anyone was working on this.
