### ISSUE TITLE
Uses pod but seems to be incompatible with it 

### ISSUE THREAD

**Issue by cyrilbos** [TheWidlarzGroup/react-native-video#944]
Hello,
I followed the installation instructions for iOS but when executing `react-native run-ios` I ran into the following error:

>  ** BUILD FAILED **
> The following build commands failed:
>	CompileC /Users/me/MyApp/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-video.build/Objects-normal/x86_64/RCTVideoManager.o /Users/cbos/Dosatron-mobile/node_modules/react-native-video/ios/RCTVideoManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>	CompileC /Users/me/MyApp/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-video.build/Objects-normal/x86_64/RCTVideoPlayerViewController.o /Users/cbos/Dosatron-mobile/node_modules/react-native-video/ios/RCTVideoPlayerViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (2 failures)

I'm using cocoapods and while googling those errors I found similar issues for the package react-native-maps which also uses RCTVideo: [https://github.com/react-community/react-native-maps/issues/371](https://github.com/react-community/react-native-maps/issues/371)

After testing several hypotheses, I found that removing the react-native-video line in the Podfile and cleaning the project fixed it. It was installing React as a pod to satisfy a dependency although another version was already present in node_modules. I guess deleting the Podspec should fix that.

**Comment by cobarx** [comment]
You shouldn't need to setup react-native-video using CocoaPods. As you mentioned, deleting the entry in the Podfile will fix it.
