### ISSUE TITLE
Play video with token

### ISSUE THREAD

**Issue by PanRada** [TheWidlarzGroup/react-native-video#946]
Hi 

Just wondering if someone notice error (not playing) video on real device with URL and token like this $(URL)?$(token)

On my try in simulator working fine but real device not play

Some solution direction?

**Comment by cobarx** [comment]
Just tested with a URL where I added a query parameter at the end and it works properly. I'm guessing there is something different about your device that is causing the issue. You will need to set breakpoints in the native code and see if you can find some info about what's happening.
