### ISSUE TITLE
Internet video is not playing

### ISSUE THREAD

**Issue by rf1804** [TheWidlarzGroup/react-native-video#947]
**_Hey i've implemented this package when i use system file of video it works fine but when i give the internet link of file it does not play._**

"react-native": "0.51.0",
"react-native-video": "^2.0.0",

**My Code**
      <View style={{flex:1}}>
        <Video source={{uri: 'https://www.youtube.com/watch?v=Rv3v7ZfYp-g' }}
           rate={1.0}                   // 0 is paused, 1 is normal.
           volume={1.0}
           muted={false}
           paused={false}               // Pauses playback entirely.
           resizeMode="cover"           // Fill the whole screen at aspect ratio.
           repeat={true}                // Repeat forever.
           onLoadStart={this.loadStart} // Callback when video starts to load
           onLoad={this.setDuration}    // Callback when video loads
           onProgress={this.setTime}    // Callback every ~250ms with currentTime
           onEnd={this.onEnd}           // Callback when playback finishes
           onError={this.videoError}    // Callback when video cannot be loaded
           style={styles.backgroundVideo}
         />
      </View>

**Comment by GianniGM** [comment]
Same problem!

**Comment by chuckb1789** [comment]
I'm also having the same problem.

**Comment by shufanger** [comment]
+1

**Comment by shufanger** [comment]
+1

**Comment by chuckb1789** [comment]
Anybody?

**Comment by Karzam** [comment]
Same here (with https link)

**Comment by chuckb1789** [comment]
Hey folks, I was running into this issue, but everything seems to work fine once you test on an actual device. It seems that the Android Studio emulator was the issue, at least for me. Hope that helps!

**Comment by JKonTiki** [comment]
yeah same issue here, on emulator and device

**Comment by ghost** [comment]
+1

**Comment by jjant** [comment]
Same here

**Comment by JKonTiki** [comment]
i tried reconfiguring to use the android exoplayer from this lib and my vids are now playing remote url's. documentation is sparse but here are some instructions for the setup:

https://www.bountysource.com/issues/40364073-exoplayer

**Comment by isaiah** [comment]
Correct me if I'm wrong, but maybe this library doesn't support random youtube page as source? Try some directly link to `.mp4` file.

**Comment by rf1804** [comment]
I've tried with s3 links also, but it didn't worked.
However i tried a hack to make it work by using react native fetch blob or any file system access u can download the video and then give that path to video player, then it works like a charm.

**Comment by martinlockett** [comment]
See https://github.com/react-native-community/react-native-video/issues/358
