### ISSUE TITLE
Android: vertical videos (tall native aspect ratio) are displayed incorrectly

### ISSUE THREAD

**Issue by sunweiyang** [TheWidlarzGroup/react-native-video#948]
I'm seeing this for both the default react-native-video (Android’s MediaPlayer API) and react-native-video-exoplayer (even with PR #842 -- I still see this issue).

For tall native aspect ratio videos (height > width, .mp4 files in my case), Android seems to transform my video (height becomes width, width becomes height, pixels are remapped to look like it's rotated). This happens with all resizeMode settings and all style sizes (I happen to have a full screen component in my screenshots, but it consistently happens regardless of component sizes).

This library works perfectly fine for wide native aspect ratio videos (width > height).

Screenshot of Android API 26 (Pixel) showing this problem:
![screenshot_1519349292](https://user-images.githubusercontent.com/12490625/36573531-582b8338-17f6-11e8-961f-da2851a29206.png)

Screenshot of iOS 11.2 (iPhone SE) with no issues:
![simulator screen shot - iphone se - 2018-02-22 at 17 28 15](https://user-images.githubusercontent.com/12490625/36573537-5f5f62e6-17f6-11e8-9be4-91bc9678654f.png)

**Comment by sunweiyang** [comment]
Some more background: this issue happens for an **emulator** of Android API 26 (Pixel).
It worked for the one physical Android device I have, which is Android API 24 (Samsung Galaxy S6).

**Comment by cobarx** [comment]
Any chance you can provide a video that doesn't work. I've tested:
http://www.exit109.com/~dnn/clips/RW20seconds_1.mp4
and it's working properly on an API 26 emulator.

We recently updated from ExoPlayer 2.4.0 to 2.7.3 and before merging a fix, I want to make sure there's still a problem. Plus I need to test to make sure the fix works :)

**Comment by sunweiyang** [comment]
Looks like it works now with the latest exoplayer -- thank you!

**Comment by Rotemy** [comment]
This is not working with 4.4.5
