### ISSUE TITLE
Can not play videos from local file system on Android 4.1.x and 4.2.x

### ISSUE THREAD

**Issue by LukaszC** [TheWidlarzGroup/react-native-video#951]
Playing videos from local filesystem seems to not work for Android <= 4.2.x (17).

As far as I could figure out it is caused by `file://` schema which is added in `Video.js`

Since Android API version 18 (4.3.x) `MediaPlayer` seems to remove schema before trying to access the path:
```
    private void setDataSource(String path, String[] keys, String[] values)
            throws IOException, IllegalArgumentException, SecurityException, IllegalStateException {
        final Uri uri = Uri.parse(path);
        if ("file".equals(uri.getScheme())) {
            path = uri.getPath();
        }

        final File file = new File(path);
        if (file.exists()) {
            FileInputStream is = new FileInputStream(file);
        ...
```
where in previous version of API (16 and 17), the schema is not removed:
```
    private void setDataSource(String path, String[] keys, String[] values)
            throws IOException, IllegalArgumentException, SecurityException, IllegalStateException {
        File file = new File(path);
        if (file.exists()) {
            FileInputStream is = new FileInputStream(file);
```
This causes that `file.exists()` returns `false`

**Comment by alisn72** [comment]
hi
i have the same issue but not only for local addressing.
in my case, video can not play from web address on android sdk 16, 17, 18
I will be thankful if anybody have any idea to fix this problem...
