### ISSUE TITLE
iOS duration onLoad is always 0

### ISSUE THREAD

**Issue by LuisRevillaM** [TheWidlarzGroup/react-native-video#954]
<img width="643" alt="screen shot 2018-03-01 at 9 40 22 am" src="https://user-images.githubusercontent.com/16518594/36850653-5b711ca8-1d35-11e8-8e5a-af617076c6d0.png">

Issue must be on the native side of things.

**Comment by cobarx** [comment]
What video are you seeing this with, I tested a number of videos and the duration is getting set properly. Is this a live stream? That wouldn't have a determinable duration.

**Comment by cobarx** [comment]
Going to close this, please re-open if you're still having the issue and can provide a sample video / URL.
