### ISSUE TITLE
如何让视频全屏后横向显示－How to make the video display full screen after the horizontal

### ISSUE THREAD

**Issue by cyjcxy** [TheWidlarzGroup/react-native-video#956]
请教一下各位老师，如何让视频全屏后横向显示，APP初始坚屏锁定，不允许横向的

Ask you teachers, how to make the video display after the full screen landscape, APP initial screen lock, does not allow horizontal

**Comment by pwj1993** [comment]
设置样式transform

**Comment by thatjuan** [comment]
Try

`resizeMode="contain"`

**Comment by keyuanupup** [comment]
I have same problem，how to resolve？

**Comment by marlti7** [comment]
user this  react-native-orientation

**Comment by coocon** [comment]
use react-native-orientation can resolve this problem
