### ISSUE TITLE
Exoplayer webm format doesn't start after video loads in Android .  (with cause)

### ISSUE THREAD

**Issue by danielbenedykt** [TheWidlarzGroup/react-native-video#957]
Exoplayer webm doesnt start after video loads.

my code:

```
<Video 
                      ref={(ref) => {
                        this.player = ref
                      }}
                      muted={false}
                      paused={false} 
                      playInBackground={true}                // Audio continues to play when app entering background.
                      playWhenInactive={true}         
                      style={{position: 'absolute',top:0,left:0,bottom:0,right:0}}
                      source={{uri:this.state.theSource}}
                      resizeMode='cover'
                      progressUpdateInterval={250.0}
                      onProgress={this.onProgress}
                      onLoadStart={this.onLoadStart} // Callback when video starts to load
                      onLoad={this.onLoad}    // Callback when video loads
                      onError={this.onError}   />
```

That is because player.setPlayWhenReady(true) is never set.

I did a hack to force player.setPlayWhenReady(true) when player != null just to make it work.
But something is wrong either on this method, or on startPlayback method,  because `case ExoPlayer.STATE_READY:` is never reached so `setPlayWhenReady(true);` is never set.

```
private void setPlayWhenReady(boolean playWhenReady) {
        if (player == null) {
            return;
        }

        if (playWhenReady) {
            boolean hasAudioFocus = requestAudioFocus();
            if (hasAudioFocus) {
                player.setPlayWhenReady(true);
            }
        } else {
            player.setPlayWhenReady(false);
        }
    }
```

**Comment by dhavalshahmi** [comment]
Same issue in webm, we are facing. Webm can not be played in exo player.

**Comment by eambutu** [comment]
I had this same issue, and it turned out it was because webm videos recorded from popular Chrome/Firefox libraries don't add the duration metadata onto the videos. (You can see this by `ffprobe [YOUR_FILE_NAME]`.) I fixed this on the recording side using the fix here: https://github.com/legokichi/ts-ebml/issues/14#issuecomment-452144243, but you can otherwise just use ffmpeg if your webm files are also missing this metadata.

**Comment by fabriziobertoglio1987** [comment]
as I read [here](https://cloudinary.com/blog/best_practices_for_the_mobile_world##%20Optimizations%20for%20the%20Mobile%20Web)
`ExoPlayer for Android supports the DASH streaming solution, and AVPlayer for iOS supports HLS`
