### ISSUE TITLE
Unable to reset video using this.player.seek(0) on ios

### ISSUE THREAD

**Issue by ingviso** [TheWidlarzGroup/react-native-video#958]
When I use the command "this.player.seek(0) for the onEnd, the video doesn't reset to initial state instead just keeps on repeating. 
I have no other parameter to reset the video to 0 sec on ios side.

Please fix this!

**Comment by thatjuan** [comment]
Try `this.player.seekTo(0);` instead and also make sure ` repeat={false}`

**Comment by tjkind** [comment]
I'm having the same problem. I'm trying to make a function that show fullscreen and starts playing the video from the beginning but for some reason seek does nothing.
I tried using seekTo but it's not a function

**Comment by clmntcrl** [comment]
I encounter the same issue with the following code:

```js
onVideoEnd = () => {
    this.setState({ isVideoPaused: true })
    this.player.seek(0)
}
```

I don't know why but it appears that delaying `this.player.seek(0)` solve my problem. To do this I used `setState` callback to execute `seek(0)` after state has been set.
 
```js
onVideoEnd = () =>  this.setState({ isVideoPaused: true }, () => this.player.seek(0))
``` 

Hope this could help you.

**Comment by ThanhDuongLe** [comment]
> I encounter the same issue with the following code:
> 
> ```js
> onVideoEnd = () => {
>     this.setState({ isVideoPaused: true })
>     this.player.seek(0)
> }
> ```
> 
> I don't know why but it appears that delaying `this.player.seek(0)` solve my problem. To do this I used `setState` callback to execute `seek(0)` after state has been set.
> 
> ```js
> onVideoEnd = () =>  this.setState({ isVideoPaused: true }, () => this.player.seek(0))
> ```
> 
> Hope this could help you.

Cool this really solve the problem. Thank you.

**Comment by erikfenriz** [comment]
>

**Comment by kodayashi** [comment]
It would be nice to address this. I have dozens of dynamic videos in a feed so I cannot maintain paused state for each one just to work around seek(). Is this something that can be fixed (seek working as designed in the onEnd handler)?

**Comment by kchijim** [comment]
Same problem!

**Comment by fathomkiran** [comment]
Hello @all,
Please use the below the simple solution for the same ;

```
onVideoEnd = () => {
    this.setState({ videoIsPaused: true });
    setTimeout(() => {
      this.player.seek(0)
    }, 500);
}

```
