### ISSUE TITLE
No Video. Audio and everything else works

### ISSUE THREAD

**Issue by scalhoun** [TheWidlarzGroup/react-native-video#96]
Is anyone else experiencing no video with the latest react-native and xcode?  I have audio, progress bars, etc but no video.

Thanks

**Comment by isair** [comment]
I can't reproduce this; could you create an example project?

**Comment by scalhoun** [comment]
Yeah, I'll get something posted.  When debugging I noticed the issue was with the bounds for the video placement which was returning 0,0.  It's been a few weeks so I'll refresh my memory on it and update.

**Comment by scalhoun** [comment]
Closing this issue.  I built a new project and everything seems to be working fine now.  Must have a been a quirk on my end.  Thanks!

**Comment by bickerstoff** [comment]
#155 may have been part of this.
