### ISSUE TITLE
[ iOS] Videos from assets-library are not played

### ISSUE THREAD

**Issue by facuacostag** [TheWidlarzGroup/react-native-video#960]
I have a video uri from the file system like this: `assets-library://asset/asset.mp4?id=7ED0862F-75A0-4EDE-8096-0F5F695045C2&ext=mp4` and I'm sending it to the video component like `source={{ uri: this.props.source }}`. This works fine on Android because the path is totally different, but on iOS I don't get the videos to play and I really need it. By checking the source code it seems that this type of path is allowed, so i don't know what's going on

```
let uri = source.uri || '';
    if (uri && uri.match(/^\//)) {
      uri = `file://${uri}`;
    }

    const isNetwork = !!(uri && uri.match(/^https?:/));
    const isAsset = !!(uri && uri.match(/^(assets-library|file|content|ms-appx|ms-appdata):/));
```

**Comment by davidfant** [comment]
I'm experiencing the same issues on iOS. Local file system uri like `file:///private/var/mobile/Containers/Data/Application/76FC3720-D48A-420B-AB4D-ECC95BBC143C/tmp/7FAC69A0-7469-4B51-BE21-1347A8C18B2E`

**Comment by kesha-antonov** [comment]
+1. ios

**Comment by kesha-antonov** [comment]
Did you solve it?

**Comment by xGum** [comment]
+1. ios too

**Comment by amsul** [comment]
Yup..same issue here. Started happening after upgrading my React Native version to the latest release.

**Comment by amsul** [comment]
FYI, downgrading to 3.0 worked for me.

**Comment by zhigang1992** [comment]
Downground to 3.0 still doesn't work for me.

This one does:

https://github.com/react-native-community/react-native-video/issues/817#issuecomment-357767683

And it's actually very fast.

**Comment by selsamman** [comment]
Copying a large file is not always workable.  Downgrading to 3.0 seems to work for me but at some point one will have to move forward.

**Comment by castalonirenz** [comment]
any update on this?

**Comment by iamabdulhaseeb** [comment]
Any updates on this issue?

**Comment by izuutech** [comment]
Any update on this issue please

**Comment by KrzysztofMoch** [comment]
iirc this should work o latest version
