### ISSUE TITLE
call 'onError' only when trying to start playing

### ISSUE THREAD

**Issue by b-asaf** [TheWidlarzGroup/react-native-video#969]
currently the `onError` is called once `onLoadStart` fails.

My video does not plays automatically, it plays only after the user click on the `Play` button.
I want the `onError` to be called only after the user tries to watch the video and not once the video element mounts.

**Comment by cobarx** [comment]
The video is going to start loading the moment it starts being rendered. You could render another component and click on it to load the Video element.
