### ISSUE TITLE
Stop audio and video when offscreen in ListView

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#97]
Any recommendations how I can stop the audio and video when it scrolls offscreen? I tried removeClippedSubviews on the ListView but it seems to have no effect on playing videos as I can still hear the audio.

**Comment by ghost** [comment]
Subscribed to onChangeVisibleRows to manipulate the volume prop.

**Comment by brentvatne** [comment]
Thanks for the followup @blairvanderhoof!
