### ISSUE TITLE
suport for rtsp / hls url shemes for the source

### ISSUE THREAD

**Issue by gorhgorh** [TheWidlarzGroup/react-native-video#971]
Hi there, 
For a project I'm working on we need to display rtsp / hls stream in an app, provided url will be of form ```rtsp://...``` and ```hls://...``` 

android player and IOS players CAN play these types of stream (rtsp on android, hls on IOS), so your lib does too, but in this [line](https://github.com/react-native-community/react-native-video/blob/master/Video.js#L168)

```
const isNetwork = !!(uri && uri.match(/^https?:/));
```

you check only for https schemes, is that because of some appstore restrictions, or is that not intended ?

If it is the latter I would be glad to do a PR with the supported schemes added.

Thanks for working on this player!

**Comment by djw27** [comment]
I think as long as you pass in a valid `type` along with the `uri` then the stream should still play? The line of code you've referenced simply sets a native prop which is used to set cookies natively on iOS or Android, for example, if a user needs an authentication cookie to access a video.

I know the following issue doesn't use a different protocol like you've mentioned, but may offer some clues for you: #522

**Comment by rogerio-azevedo** [comment]
I found this, working RTSP on IOS:

[react-native-vlc-media-player](https://github.com/razorRun/react-native-vlc-media-player)
