### ISSUE TITLE
black container problem only in iOS

### ISSUE THREAD

**Issue by bodaghialib4** [TheWidlarzGroup/react-native-video#973]
hello, 
I used react-native-video to show video from internet. in Android it work correctly but in iOS I only get black screen. as a local video from my assets, I can play video. but from server (internet) I get black screen.
I read below links:

https://github.com/react-native-community/react-native-video/issues/821
https://github.com/react-native-community/react-native-video/issues/596
https://github.com/react-native-community/react-native-video/issues/936
https://stackoverflow.com/questions/46512241/react-native-video-shows-blank-screen-in-my-app-without-any-error-log

but none of them helped me!!

```
render() {
    return (
      <View style={styles.container}>
        <Video
            //source={require('./assets/small.mp4')}
            source={{uri: 'https://techslides.com/demos/sample-videos/small.mp4'}}
            volume={50}
            muted={false}
            paused={false}
            resizeMode="cover"
            repeat={true}
            playInBackground={false}
            playWhenInactive={false}
            style={{
                width: 200,
                height: 200,
            }}
        />

      </View>
    );
  }
```
<img width="445" alt="screen shot 1396-12-26 at 17 47 54" src="https://user-images.githubusercontent.com/23075818/37556487-28ff1ac0-2a0c-11e8-94fe-1b3aca19ae13.png">

I also tested in my iPhone device but not work and have same result.

**Comment by bodaghialib4** [comment]
@brentvatne @isair @sjchmiela @johanneslumpe

I will be very grateful if you have solution for my problem.

**Comment by sjchmiela** [comment]
Could you please, try using a HTTPS video resource? (vide [comment](https://github.com/react-native-community/react-native-video/issues/936#issuecomment-370273868))

**Comment by sjchmiela** [comment]
Also, there is a possibility `onError` callback is called with some helpful error message. 🙂

**Comment by bodaghialib4** [comment]
I always test HTTPS link of the video that streamed from our server and it was not worked.

finally after having a meeting with our backend developer, I understood that our server not supported HTTPS. 


Now after supporting HTTPS from our server, it worked correctly. 



thanks you.
