### ISSUE TITLE
Not able to play video in android OS version 7.1.1 ? 

### ISSUE THREAD

**Issue by ios-dev-newbie** [TheWidlarzGroup/react-native-video#977]
setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
setSubtitleAnchor in MediaPlayer
setScreenOnWhilePlaying(true) is ineffective for Surface
error (1, -2147479543)
Error (1,-2147479543)
error (1, -38)
Error (1,-38)

**Comment by darshana96** [comment]
I am facing the same unable play video on android OS version 7.1.1

**Comment by Lohins** [comment]
Anyone knows how to fix this?

**Comment by vladislav-puzyrev** [comment]
+1

**Comment by dingcxx** [comment]
I have the same issue

maybe the media codec is not supported by OS

in my case 

the video format is video/mp4; codecs="avc1.f40028"

 phone is vivo x21s  android 9
