### ISSUE TITLE
Support External Subtitles

### ISSUE THREAD

**Issue by hitaloramon** [TheWidlarzGroup/react-native-video#978]
would I have to add support for external .srt or .vtt subtitles?
sorry for my bad english

**Comment by huanghanzhilian** [comment]
I have this need, too

**Comment by huanghanzhilian** [comment]
Have you solved your problem?

**Comment by cobarx** [comment]
This has been added for Android ExoPlayer and will be supported in iOS shortly.

**Comment by EugeneKovalev** [comment]
Hey @cobarx 
As I understand it only supports web-hosted subtitles which makes the app totally unusable offline.
Do you have any thoughts on how I can work with subtitles locally?

Many thanks
