### ISSUE TITLE
render video in two views

### ISSUE THREAD

**Issue by kailenwinfrey** [TheWidlarzGroup/react-native-video#979]
I am working on a project that requires a live stream to display in two positions in my app. Is it possible to render a streaming video in more than one view without downloading it twice? Can one video be passed into another instance as it's source?

**Comment by cobarx** [comment]
I'm not sure this is possible for the standard video players. Definitely not something we'll be able to support any time soon.

**Comment by DavitVosk** [comment]
First of all the video caching problem should be fixed. How is it going on guys?

**Comment by cobarx** [comment]
I haven't had a chance to review the caching PR yet, it's a pretty good sized chunk of code. Having some people look it over and test it would help move towards being ready to merge.

**Comment by DavitVosk** [comment]
Hi @cobarx. You are speaking about PR with #955?

**Comment by cobarx** [comment]
Yes that's the one.

**Comment by DavitVosk** [comment]
@cobarx the owner has created a fork. Now testing this to understand how does that work. Just can you please advise how I can see that the caching is done properly? Where can I check the cached data?

**Comment by n1ru4l** [comment]
@cobarx @DavitVosk I updated the pull request. You can checkout the example application and enable/disable network (or checkout the files which are persisted on the filesystem).
