### ISSUE TITLE
Audio won't play out of speakers if muted

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#98]
I noticed other apps will play sound even if your mute switch on the phone is on. How can we get audio to play when the mute switch is active on the device?

**Comment by blairvanderhoof** [comment]
Subscribed to onChangeVisibleRows to manipulate the volume prop.

**Comment by blairvanderhoof** [comment]
Oops I commented on the wrong task. My initial question about muting still stands.

**Comment by brentvatne** [comment]
Not really sure about this one, @johanneslumpe do you know? :P

**Comment by johanneslumpe** [comment]
@brentvatne @blairvanderhoof have you tried using the AVAudioSession?

```
[[AVAudioSession sharedInstance]
                setCategory: AVAudioSessionCategoryPlayback
                      error: nil];
```

**Comment by isair** [comment]
@johanneslumpe is correct. @blairvanderhoof That is the default behavior. From Apple's docs, for `AVAudioSessionCategoryPlayback`:

> When using this category, your app audio continues with the Silent switch set to silent or when the screen locks.

Check [this page](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAudioSession_ClassReference/#//apple_ref/doc/constant_group/Audio_Session_Categories) to make sure you are picking the right category for your needs.
