### ISSUE TITLE
(Android) Video fails to play

### ISSUE THREAD

**Issue by peacechen** [TheWidlarzGroup/react-native-video#980]
react-native: 0.53.3
react-native-video: 2.0.0
Device: Nexus 6 / Android 7.1.2

This MP4 fails to play on Android.  It works in the iOS build.
http://d3959tuydafzg6.cloudfront.net/1/travelogue2015.mp4

The onError callback returns the object:
```
error: {
  extra: 0,
  what: 100  --> MEDIA_ERROR_SERVER_DIED
}
```

Code snippet:
```
            <Video source={{uri: "http://d3959tuydafzg6.cloudfront.net/1/travelogue2015.mp4"}}
              style={styles.backgroundVideo}
              rate={1.0}
              resizeMode='contain'
              muted={false}
              volume={1.0}
              repeat={true}
              playInBackground={false}
              playWhenInactive={false}
              onError={err => requestAnimationFrame(() => {
                console.log(err);
              }
              ) }
            />
```

**Comment by peacechen** [comment]
An `error.what` value of 100 is [MEDIA_ERROR_SERVER_DIED](https://developer.android.com/reference/android/media/MediaPlayer.html#MEDIA_ERROR_SERVER_DIED)

What might cause that?

This happens with either a remote file (http) or a local file on the device.

**Comment by pawelbrzezinski** [comment]
same

**Comment by peacechen** [comment]
Could be related to #977 or #975.

Tested on Nexus 6 running Android 7.1.2

I've also tried `react-native-video-exoplayer` which renders a black box but no video.

**Comment by peacechen** [comment]
The playback failure appears to be a video format compatibility issue.  The video in my original post doesn't play, but this one does:
http://techslides.com/demos/sample-videos/small.mp4

Oddly, exoplayer won't play that one.  It shows the first frame but gets "stuck".

This one won't play either:
https://github.com/mediaelement/mediaelement-files/blob/master/big_buck_bunny.mp4
Error is slightly different: `{extra: -2147483648, what: 1}`

Any recommendations on how to support a wider variety of video files?

**Comment by peacechen** [comment]
I upgraded ExoPlayer to 2.7.2 as an experiment.  Didn't help, but created PR #983 so that the work isn't lost.

**Comment by peacechen** [comment]
ExoPlayer's extension decoders sound like they could help.  How to enable and build that in automatically could be problematic as the documentation says
`Build each of the extensions that you want to include. Note that this is a manual process.`

https://google.github.io/ExoPlayer/demo-application.html#including-extension-decoders

**Comment by pawelbrzezinski** [comment]
@peacechen but have you succeeded with those extension decoders?

**Comment by pawelbrzezinski** [comment]
@peacechen do you know what other options do we have to play videos on android then ; )?

**Comment by peacechen** [comment]
How about loading the video in a WebView?  The browser seems to have a robust video playback engine.  It would be nice to include that as a rendering option in `react-native-video` so we can have one reusable API.  It may be a challenge to provide all the callback hooks and playback controls.

**Comment by cobarx** [comment]
@peacechen I tested all three videos.

I've used small.mp4 for my testing for weeks and never encountered any issues with it on any of the players. The big buck bunny link you posted is to the GitHub page rather than to the actual video, which is why you're getting the error.

On the travelogue video, when I test with ExoPlayer on a Nexus 5X Android 7.1 emulator it works fine. However on an Android 4.4.4 emulator, it throws the following error:
```
05-29 02:31:16.781 1596-1665/com.rnv E/SoftAVC: Decoder failed: -2
05-29 02:31:16.781 1596-1663/com.rnv E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
05-29 02:31:16.785 1596-1662/com.rnv E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
05-29 02:31:16.785 1596-1640/com.rnv E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.queueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:758)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

This is a good example of a common situation with videos - older Android versions, Android emulators, and budget devices are often missing the codecs or hardware features necessary to play certain videos. In those cases, it won't matter what video player you use as all the players use the same set of codecs packaged with the system. The only way around it is to bundle codec packs with your player which is what very sophisticated video players like MXPlayer do. That is a massive amount of effort. FWIW, I tried loading that video in the browser on that device and got no video there either.

Your other alternative is to use conservative video encodings that are supported by all devices. h.264 main rather than high, 480p rather than 720p, etc. With that video the issue is likely either that it's 720p or using mp42 rather than the standard v1 mp4. Not sure how you diagnose it.

This is one of the areas where iOS is nice since all the devices are running recent versions of the OS so they have similar (and broad) codec support.

**Comment by peacechen** [comment]
Yes, typo on the big buck bunny video.  However the video linked in the OP shows a case that's *opposite* to your hypothesis of older devices lacking support.  That video plays on an older Nexus 5 running Android 6, but fails on a *newer* Nexus 6 running Android 7.

ExoPlayer just doesn't have broad support for codecs unless the extension decoders are built with it.

**Comment by cobarx** [comment]
Is that on a Nexus 6 emulator or actual device. Sometimes they strip out the codecs on the emulator to only include free software, but if it's a real device that's disappointing. Probably Google saving money 😐

The extension decoders are separate from the codecs so I don't think there is any way to havdle it. Extension decoder: read HLS Playlist, codec: decode h.264 or HEVC file. I'd love to be proven wrong though and happy to implement support if there's a way to achieve it.

**Comment by peacechen** [comment]
Physical Nexus 6.  Tried it on multiple flavors of firmware (stock and Lineage) and it won't play that file.  Unexpected and disappointing ☹️ 

Interesting note is that the video plays fine in Chrome on the Nexus 6, so it's purely a codec issue.

**Comment by vtam311** [comment]
I had the same issue and am using react-native-video 3.2.0.

Switching '../node_modules/react-native-video/android-exoplayer' to '../node_modules/react-native-video/android' in settings.gradle fixed it for me

**Comment by gauravsbagul** [comment]
I am facing the same issue, and I am not using expo player please help here.

**Comment by isllyend** [comment]
I have the same problem today ）：

**Comment by ithustle** [comment]
+1

**Comment by carltian** [comment]
+1

**Comment by mohamed2m2018** [comment]
+1

**Comment by anatooly** [comment]
It's actual problem ^____^

**Comment by Carlosp16** [comment]
Closed? I'm facing the issue
