### ISSUE TITLE
Getting error on iOS: Exception thrown while executing UI block: ***-[NSURL initURLWithPath]: nil string parameter

### ISSUE THREAD

**Issue by har2008preet** [TheWidlarzGroup/react-native-video#981]
I am getting above error on iOS simulator on running following code: 

```
<Video
                            source={{ uri: this.state.videoUrl }}
                            style={styles.backgroundVideo}
                            rate={this.state.rate}
                            paused={this.state.paused}
                            volume={this.state.volume}
                            muted={this.state.muted}
                            ignoreSilentSwitch={this.state.ignoreSilentSwitch}
                            resizeMode={'cover'}
                            onLoad={this.onLoad}
                            onBuffer={this.onBuffer}
                            onProgress={this.onProgress}
                            onEnd={() => null}
                            repeat={false}
                        />
```

It is running perfectly on android.

**Note:** on giving url directly, in place of 'this.state.videoUrl', video is running on simulator.

**Comment by fpvvoyage** [comment]
To fix navigate to the node_modules folder and open the folder react-native-video. 

- Open video.js 
and add the following to the first if statement in the render() function.
    
> else if (uri === '') {
>       return null;
>     }	    

You should now have the following in your render function:

> if (uri && uri.match(/^\//)) {
>       uri = `file://${uri}`;
>     }
>     else if (uri === '') { 
>       return null;
>     }	    

note: the '' in the uri comparison is two single quotes.
