### ISSUE TITLE
Remote video loading failed

### ISSUE THREAD

**Issue by yz-xlame** [TheWidlarzGroup/react-native-video#984]
item is video url
<Video style={styles.video}
              source={{uri: item}}
              ref = {(ref) => {this.player = ref}}
              muted={false}
              rate ={0}
              volume = {0.6}
              paused = {false}
              repeat={false}
              onLoad = {() => {console.log('正在加载视频',item)}}
              /*onBuffer = {(response) => {console.log('onBuffer接收到：',response)}}
              onTimedMetadata={(response) => {console.log('onTimedMetadata接收到：',response)}}*/
              onError={() => {Alert.alert('视频加载错误!')}}
/>

Always load failed

**Comment by yz-xlame** [comment]
error: {domain: "AVFoundationErrorDomain", code: -11850}

**Comment by yz-xlame** [comment]
This seems to be a problem with ios

**Comment by JeremyBradshaw7** [comment]
I also get this error - why is this closed with no documented solution?

**Comment by 0xouzm** [comment]
I'm trying to translate .mov to .mp4,praying it will work

**Comment by chj-damon** [comment]
> This seems to be a problem with ios

what do you mean "a problem with IOS" ? What do I need to do to fix it?

**Comment by MSalmanAwan5** [comment]
Also getting this issue when running a remote video. anyone found a solution?

**Comment by BadtzMaru** [comment]
I also got the error. Is anyone solved this problem?

{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "操作停止", "localizedFailureReason": "服务器配置不正确。", "localizedRecoverySuggestion": ""}, "target": 3439}
