### ISSUE TITLE
cloud not load video

### ISSUE THREAD

**Issue by booniez** [TheWidlarzGroup/react-native-video#985]
when i using video for iOS, TypeError: undefined is not an object(evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')

**Comment by yz-xlame** [comment]
code?

**Comment by booniez** [comment]
<Video
                repeat
                resizeMode='cover'
                source={{uri:'http://123.207.181.131/x.mp4'}}
                style={styles.backgroundVideo}
                />

**Comment by martinlockett** [comment]
You haven't included the native library in your build. See the instructions "Linked Frameworks and Libraries" on the main page of this repo

**Comment by booniez** [comment]
@martinlockett ok,thanks.
