### ISSUE TITLE
Video is not pausing in list view

### ISSUE THREAD

**Issue by saraswathirbt** [TheWidlarzGroup/react-native-video#986]
I have many videos in listview when i set paused={true} in android it is not working . but it is working well in ios
Solution:
this.state={paused:false}
setDuration = () => {
this.setState({ paused: true })
    }
<Video source={{ uri: config.Profile_url + data.files[0].path, type: 'mp4' }}
   style={{ width: "100%", height }}
     resizeMode="contain"
paused={true}
 onLoad={this.setDuration}  />Ï

I used above code in android to pause a video in list view but it is not working .how to pause a video in listview

can any one please help me to solve this issue

**Comment by jeremyfrancis** [comment]
You have a state for paused but your paused property is not linked to that state... ?

**Comment by saraswathirbt** [comment]
@jeremyfrancis  thanks for your reply

even though i link with my state variable in android it is not working
