### ISSUE TITLE
Exception thrown while executing UI block: *** -[NSURL initFileURLWithPath:]: nil string parameter

### ISSUE THREAD

**Issue by ankits47b** [TheWidlarzGroup/react-native-video#987]
I have error like this when I am going to play Video from server URL

**Comment by dimasdanz** [comment]
Make sure the url is there, not `null` at any time. Don't render the <Video /> before you fetched the url.

**Comment by mickaelwegerich** [comment]
@ankits47b make sure you have uri like `source={{uri: "https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"}}`

**Comment by JeremyBradshaw7** [comment]
Doing this for me too, when I call presentFullscreenPlayer() - the source URL is defined, in fact the full screen video does show, but this error is thrown anyway.
