### ISSUE TITLE
Slow Read Video .mp4 on ligne  -> VERY FAST PLAY  

### ISSUE THREAD

**Issue by abdelhakimkotti** [TheWidlarzGroup/react-native-video#991]
Hello,
I have a problem if i'm read 3 videos on ligne. 
Any solution to read very fast video .mp4 on ligne , if on click next video or back video .
Thanks :)

**Comment by skantus** [comment]
@abdelhakimkotti  use an ultra mega fast server?

**Comment by CHaNGeTe** [comment]
And config the server to allow progressive streaming

**Comment by CHaNGeTe** [comment]
I close the issue as this question probably is better to StackOverflow

**Comment by skantus** [comment]
@CHaNGeTe yes, this is out the box, maybe @abdelhakimkotti should download the videos using `rn-fetch-blob` to improve the performance, just only an idea.
