### ISSUE TITLE
Video image got stucked and audio keeps playing on bad internet connections

### ISSUE THREAD

**Issue by jclrosa** [TheWidlarzGroup/react-native-video#993]
Hey, I am having issues Playing a video from a CloudFront url, when the connection decreases his quality.

**Current:**
I start playing the video, and it plays as expected , then I simulate a bad internet connection, and the video continues playing, but only the audio is playing, the video got stucked.

**Expected:**
I start playing the video, and it plays as expected, then I simulate a bad internet connection, and the video stops playing (both audio and video). Then, when it loads sufficiently it should resume the video.

I just searched for some other similar issues, and I think that the thing is that any of the provided video handlers, seems to able to be triggered by this case. I think that “onError”,  would be the best candidate since the video is playing wrongly, but this does not happen.

**What I found so far:**
The “onProgress” event seems to be the only one that is constantly triggered when playing a video, and when the above situation happens (audio continues, but no video), the “playableDuration” value is updated to 0.

You would say, that this can be the trigger that I need for me to paused the video, and I have already tried that. The problem is that if I set up again a good internet connection, the playableDuration value updates for the right values and the video starts playing again. However it plays only with the audio and with the image stuck for some time (~20 seconds). After that time passes the video and audio plays just fine. 

Do you know any workaround that can work on this case? I’ve also though in only play the video if I the device has an internet connection above some requirements, but doesn’t seems to be a great solution.

**Comment by marlti7** [comment]
same problem

**Comment by cobarx** [comment]
@jclrosa Which platforms are you seeing this on? Can you provide some instructions on how to simulate the poor connection so I can take a look into this?

Most of the video players have some kind of onBufferExhausted event that we could export, I think that would be a better fit than onError. Even so, I wouldn't expect the audio & video streams to get out of sync, it should probably pause until the buffer fills up enough to play again.

**Comment by jclrosa** [comment]
@cobarx  I have only tested this on IOS. 
Yeah, I agree with you that “the audio & video streams shouldn’t get out of sync, and should probably pause until the buffer fills up enough to play again”.

Here are the steps to reproduce it using a real device:
	1. play video (in normal internet connection)
	2. In IOS development mode go to Settings -> Development -> Network Link Conditioner and turn on 3G connection (the video should now start buffering - sometimes the video/audio get out of sync at this stage)
	3. enable normal connection again (most of the times the video/audio get out of sync at this stage)

You can also see test the behaviour on the simulator. You need to have a software that can simulate a 3G or slower network connections. (I’ve used Charles Proxy for that [Charles Web Debugging Proxy • HTTP Monitor / HTTP Proxy / HTTPS & SSL Proxy / Reverse Proxy](https://www.charlesproxy.com/))

**Comment by TiagoJeronimo** [comment]
Same problem

**Comment by Steve1820** [comment]
Same here!

**Comment by Yogiyadavmca** [comment]
Did anyone find any solution ? I am facing the same issue.

**Comment by Riaz5687** [comment]
same here, any solution ?

**Comment by hieunc229** [comment]
Still receive this issue on both v5 and v6 for iOS
