### ISSUE TITLE
On the problem of m3u8, TS offline cache playback

### ISSUE THREAD

**Issue by huanghanzhilian** [TheWidlarzGroup/react-native-video#994]
**Hello, if react-native-video can play local m3u8 files, I downloaded the m3u8 and TS addresses on the network to the local. I would like to ask if I can provide the effect of reading the local TS slices to play the video, so as to achieve the effect of offline caching.**

**This is the code I download to parse m3u8 and download the TS queue.**

```
downloadVideo(fromUrl, toFile){
    const activeDownloads = {};
    activeDownloads[toFile] = new Promise((resolve, reject) => {
        RNFetchBlob
            .config({path: toFile})
            .fetch('GET', fromUrl)
            .then(res => {
                if (Math.floor(res.respInfo.status / 100) !== 2) {
                    throw new Error('Failed to successfully download video');
                }
                //resolve(toFile);
                resolve(res);
            })
            .catch(err => {
                return deleteFile(toFile)
                  .then(() => reject(err));
            })
            .finally(() => {
                // cleanup
                delete activeDownloads[toFile];
            });
    });
    return activeDownloads[toFile];
  }
  async _download(){
    var fs=RNFetchBlob.fs
    var path=RNFetchBlob.fs.dirs.DocumentDir
    var videocache=path+'/videocache'
    let isDir=await fs.isDir(videocache)
    if(!isDir){
      await fs.mkdir(videocache)
        .then(() => {console.log('Create videocache success')})
        .catch((err) => {console.log('Create videocache err')})
    }

    var url='http://video.test.com/6f94765277492f9b8ab181ce6a22b387%3D%2FlrOn4B7V9FewWz96xCggAUHObdPc%2F0?pm3u8/0/expires/90384&e=1524169405&token=vcZj_ZMWMJ8gU759Lfsd8_A2jgriPXGS6tBJX1Ss:u5YUx1lI_8VzrXrgTOGOvkurKUs=';

    let dirs = videocache+'/test.m3u8'
 
    var dirsRes=await this.downloadVideo(url,dirs)
    var manifest = await dirsRes.text()

    //analysis m3u8
    var parser = new m3u8Parser.Parser();
    parser.push(manifest);
    parser.end();
    var parsedManifest = parser.manifest;
    console.log(parsedManifest)

    var segments=parsedManifest.segments
 
    if(segments){
      this.walk(segments,videocache)
    }
    
  }
  async walk(segments,videocache){
    this.asyncForEach(segments, async x => {
      var qianzui='http://video.samuredwonder.com'
      let dirs = videocache+'/'+x.uri
      let url = qianzui+x.uri
      var res = this.downloadVideo(url,dirs)
    })
  }

  async asyncForEach(array, callback) {
    for (let index = 0; index < array.length; index++) {
      await callback(array[index], index, array)
    }
  }
```

**This is the screenshot I have downloaded**

![image](https://user-images.githubusercontent.com/22462288/38985831-118873ea-43fd-11e8-807a-e65cc3108076.png)

### What I want to get is that video can find my TS queue to play.

# I hope to get your help, thank you.

**Comment by djw27** [comment]
More information here: https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html

**Comment by Strate** [comment]
@huanghanzhilian you should keep local m3u8 files modified, all links to external video files and nested playlists should be replaced to locals one. Just tested - worked for me.

**Comment by Strate** [comment]
Update: didn;t work for ios, only for android. Looks like for ios hls content should be downloaded with special api

**Comment by mangdin** [comment]
@Strate 
Does it work for ios now?

**Comment by Strate** [comment]
@mangdin you should implement native module for ios using https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html

**Comment by mangdin** [comment]
Ok
thanks. @Strate

**Comment by 0xleeaki** [comment]
Hi @Strate ,

I try play m3u8 local file but not work. This code work with mp4 local file.

`<Video
                source={require('../Assets/Images/video.m3u8')}
                muted={muted}
                paused={paused}
                ref={this.videoRef}
              />
`
Error
`
None of these files exist:
App/Assets/Images/test.m3u8(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
`
Can you tell me what is wrong

**Comment by puneetkansal04** [comment]
Hi @huanghanzhilian did you able to play HLS .m3u8 offline on android android IOS?

**Comment by santanu07** [comment]
please help me I can not play local m3u8 video

**Comment by mohdzaifquraishi-greenapex** [comment]
> @huanghanzhilian you should keep local m3u8 files modified, all links to external video files and nested playlists should be replaced to locals one. Just tested - worked for me.


Please can you share us sample modified m3u3 that target to local, also the m3u8 folder structure

**Comment by moskalakamil** [comment]
Hey all!

We can’t simply save the `.m3u8` file as-is, but we’ve recently released an [Offline Video SDK](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk_title&utm_id=994) that lets you download and play video content offline - including DRM-protected streams.  
It supports HLS, DASH, and other common formats like MP4.

If you're curious or just looking for a starting point, here's a starter kit you can check out:  
https://github.com/TheWidlarzGroup/react-native-offline-video-starter/

More info here if you want to dig deeper:
[https://www.thewidlarzgroup.com/offline-video-sdk](https://www.thewidlarzgroup.com/offline-video-sdk?utm_source=github&utm_medium=issue&utm_campaign=offline_video_sdk&utm_id=994)
